# Cleaning Downloaded Data from avian-flu

Author: Alexander Maksiaev

Purpose: Clean downloaded data from avian-flu, rename sequences according to convention, de-duplicate from GISAID

In [1]:
# Housekeeping

import os
import glob 
import pandas as pd
import xml.etree.ElementTree as ET
import requests
import time
import numpy as np
import dateutil 
from datetime import datetime
from collections import defaultdict 
import importlib
import utils  
importlib.reload(utils)
from utils import * 

# Make sure you have the correct paths

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/"
# downloads = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
originals = downloads + "Andersen/"
temp_files = originals + "temp/"
complete_files = originals + "complete/"

# Day we're updating data
update_date = "05-14-2025"

os.chdir(downloads)

## Read Metadata

In [2]:
# Read metadata

os.chdir(downloads)
metadata_normalized = pd.read_csv("metadata_normalized.tsv", delimiter="\t") # Collection dates

metadata_folder = originals + "avian-influenza/metadata/"
os.chdir(metadata_folder)

metadata = pd.read_csv("SraRunTable_automated.csv")

print(len(metadata)) # 7397 rows

metadata = metadata.merge(metadata_normalized, how="outer")
print(metadata.columns)

# Get rid of missing dates; they won't be counted anyway
# for date in metadata["Collection_Date"]:
#     if "/" in date or date == "missing":
#         metadata = metadata[metadata["Collection_Date"] != date]

# # Find only >= 2024 to start
# metadata["Collection_Date_Compare"] = metadata["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
# metadata = metadata[metadata["Collection_Date_Compare"] >= datetime(2021, 11, 1).strftime("%Y-%m-%d")] # Note that those with only years will default to today

# Find only >= last date using Release Date from metadata 
metadata["ReleaseDate"] = metadata["ReleaseDate"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
metadata = metadata[metadata["ReleaseDate"] >= datetime(2025, 4, 14).strftime("%Y-%m-%d")]
# Find only <= update date using Release Date from metadata
metadata = metadata[metadata["ReleaseDate"] <= datetime(2025, 5, 14).strftime("%Y-%m-%d")]

print(len(metadata)) # 6053 rows between 1/1/2024 and 4/14/2025
display(metadata)

8959
Index(['Run', 'Assay Type', 'AvgSpotLen', 'Bases', 'BioProject', 'BioSample',
       'BioSampleModel', 'Bytes', 'Center Name', 'Collection_Date', 'Consent',
       'DATASTORE filetype', 'DATASTORE provider', 'DATASTORE region',
       'Experiment', 'geo_loc_name_country', 'geo_loc_name_country_continent',
       'geo_loc_name', 'Host', 'Instrument', 'isolate', 'Library Name',
       'LibraryLayout', 'LibrarySelection', 'LibrarySource', 'Organism',
       'Platform', 'ReleaseDate', 'create_date', 'version', 'Sample Name',
       'SRA Study', 'serotype', 'isolation_source', 'BioSample Accession',
       'is_retracted', 'retraction_detection_date_utc'],
      dtype='object')
1415

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,ReleaseDate,create_date,version,Sample Name,SRA Study,serotype,isolation_source,BioSample Accession,is_retracted,retraction_detection_date_utc
16776,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,2025-04-14,2025-04-14 15:21:54,1,25-006243-005,SRP503016,NaN,"MILK, BULK TANK",SRS24711993,False,NaN
16777,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,2025-04-14,2025-04-14 15:21:54,1,25-006243-005,SRP503016,NaN,",",SRS24711993,False,NaN
16778,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,2025-04-14,2025-04-14 15:20:51,1,25-006243-002,SRP503016,NaN,"MILK, BULK TANK",SRS24711992,False,NaN
16779,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,2025-04-14,2025-04-14 15:20:51,1,25-006243-002,SRP503016,NaN,",",SRS24711992,False,NaN
16780,SRR33124596,WGS,262.12,61927215,PRJNA1102327,SAMN47941262,Viral,21760157,USDA-NVSL,2025,...,2025-04-14,2025-04-14 15:20:49,1,25-006243-001,SRP503016,NaN,"MILK, BULK TANK",SRS24711991,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18186,SRR33508855,WGS,148.87,103940184,PRJNA980729,SAMN48412465,Viral,37006525,USDA-NVSL,2025-03-31,...,2025-05-09,2025-05-09 20:26:20,1,25-010935-011,SRP441379,NaN,NaN,SRS24987944,False,NaN
18187,SRR33508856,WGS,148.95,109428817,PRJNA980729,SAMN48412464,Viral,39060159,USDA-NVSL,2025-03-31,...,2025-05-09,2025-05-09 20:26:32,1,25-010935-010,SRP441379,NaN,NaN,SRS24987943,False,NaN
18188,SRR33508857,WGS,149.37,58966003,PRJNA980729,SAMN48412463,Viral,21375627,USDA-NVSL,2025-03-31,...,2025-05-09,2025-05-09 20:26:25,1,25-010935-009,SRP441379,NaN,NaN,SRS24987942,False,NaN
18189,SRR33508858,WGS,148.55,117986368,PRJNA980729,SAMN48412454,Viral,41978420,USDA-NVSL,2025-03-28,...,2025-05-09,2025-05-09 20:26:28,1,25-010791-001,SRP441379,NaN,NaN,SRS24987941,False,NaN
18190,SRR33508859,WGS,148.36,111573968,PRJNA980729,SAMN48412453,Viral,39429900,USDA-NVSL,2025-03-18,...,2025-05-09,2025-05-09 20:26:28,1,25-009621-001,SRP441379,NaN,NaN,SRS24987940,False,NaN

In [3]:
# Get list of genotypes

# os.chdir(home)

# genotypes_df = pd.read_excel("genotype_key.xlsx")

# genotypes = list(genotypes_df["Genotype"])

# print(genotypes)

genotypes = ["B3.13"]

### Naming convention ###
>A/[host]/[geo_loc_name]/[isolate]/[year]|[serotype: H5N1]|[collection_date]|[host_type]|[genotype]

host_type is from manual animal reference

In metadata, we have: host, geo_loc_name, isolate, year

We need: geo_loc_name, collection_date, host_type, genotype

host = Host

geo_loc_name (primary) = geo_loc_name

geo_loc_name (secondary) = genbank_mapping.tsv > genbank_name

isolate = isolate

collection date (primary) = Collection_Date

collection date (secondary) = https://www.ncbi.nlm.nih.gov/genbank/ > BioSample (input: BioSample) > Nucleotide > [first result] > collection_date

serotype = serotype

host type = [from ref] 

genotype = [from genoflu] -- use genoflu_results.tsv

## Get genotype, specific geolocation

In [4]:
# Get genotype from genoflu_results.tsv

os.chdir(metadata_folder)

genoflu_results = pd.read_csv("genoflu_results.tsv", delimiter="\t")

genoflu_results["Run"] = genoflu_results["sample"]

metadata = metadata.merge(genoflu_results, on="Run", how="inner")
print(metadata)
# metadata = metadata[~metadata["Genotype"].str.contains('Not assigned')] # Do not include non-assigned genotypes
metadata = metadata[metadata["Genotype"] == genotypes[0]]

# Get only the genotypes we want: B3.13 and D1.1

# b313_and_d11_only = genoflu_results[(genoflu_results["Genotype"] == "B3.13") | (genoflu_results["Genotype"] == "D1.1")]
# b313_and_d11_only = b313_and_d11_only.rename(columns={"sample": "Run"})
# b313_and_d11_only = b313_and_d11_only.drop_duplicates(subset="Run", keep="last")

# metadata = metadata.merge(b313_and_d11_only, on=["Run", "Genotype"], how="inner")

print(len(metadata)) 

display(metadata)

              Run Assay Type  AvgSpotLen      Bases    BioProject  \
0     SRR33124594        WGS      246.43  145473401  PRJNA1102327
1     SRR33124594        WGS      246.43  145473401  PRJNA1102327
2     SRR33124595        WGS      240.38  139928333  PRJNA1102327
3     SRR33124595        WGS      240.38  139928333  PRJNA1102327
4     SRR33124596        WGS      262.12   61927215  PRJNA1102327
...           ...        ...         ...        ...           ...
1137  SRR33370223        WGS      149.04  273190268  PRJNA1207547
1138  SRR33370224        WGS      148.74  391558200  PRJNA1207547
1139  SRR33370224        WGS      148.74  391558200  PRJNA1207547
1140  SRR33370225        WGS      148.34  167910290  PRJNA1207547
1141  SRR33370225        WGS      148.34  167910290  PRJNA1207547

         BioSample BioSampleModel      Bytes Center Name Collection_Date  ...  \
0     SAMN47941264          Viral   50832578   USDA-NVSL            2025  ...
1     SAMN47941264          Viral   50832578   USDA-NVSL            2025  ...
2     SAMN47941263          Viral   48295907   USDA-NVSL            2025  ...
3     SAMN47941263          Viral   48295907   USDA-NVSL            2025  ...
4     SAMN47941262          Viral   21760157   USDA-NVSL            2025  ...
...            ...            ...        ...         ...             ...  ...
1137  SAMN48201624          Viral   99061849   USDA-NVSL            2025  ...
1138  SAMN48201615          Viral  140357199   USDA-NVSL            2025  ...
1139  SAMN48201615          Viral  140357199   USDA-NVSL            2025  ...
1140  SAMN48201614          Viral   68333303   USDA-NVSL            2025  ...
1141  SAMN48201614          Viral   68333303   USDA-NVSL            2025  ...

     retraction_detection_date_utc       sample                 date  \
0                              NaN  SRR33124594  2025-04-15_06-38-07
1                              NaN  SRR33124594  2025-04-15_06-38-07
2                              NaN  SRR33124595  2025-04-15_06-38-07
3                              NaN  SRR33124595  2025-04-15_06-38-07
4                              NaN  SRR33124596  2025-04-15_06-38-12
...                            ...          ...                  ...
1137                           NaN  SRR33370223  2025-05-02_06-24-03
1138                           NaN  SRR33370224  2025-05-02_06-24-02
1139                           NaN  SRR33370224  2025-05-02_06-24-02
1140                           NaN  SRR33370225  2025-05-02_06-24-02
1141                           NaN  SRR33370225  2025-05-02_06-24-02

           File Name                                           Genotype  \
0     SRR33124594.fa                                              B3.13
1     SRR33124594.fa                                              B3.13
2     SRR33124595.fa                                              B3.13
3     SRR33124595.fa                                              B3.13
4     SRR33124596.fa                                              B3.13
...              ...                                                ...
1137  SRR33370223.fa                                               D1.1
1138  SRR33370224.fa  Not assigned: Only 5 segments >98.0% match fou...
1139  SRR33370224.fa  Not assigned: Only 5 segments >98.0% match fou...
1140  SRR33370225.fa  Not assigned: Only 1 segments >98.0% match fou...
1141  SRR33370225.fa  Not assigned: Only 1 segments >98.0% match fou...

                            Genotype List Used, >=98.0%  \
0     MP:ea1, NS:am1.1, NA:ea1, NP:am8, HA:ea1, PA:e...
1     MP:ea1, NS:am1.1, NA:ea1, NP:am8, HA:ea1, PA:e...
2     MP:ea1, PB1:am4, NA:ea1, NS:am1.1, NP:am8, HA:...
3     MP:ea1, PB1:am4, NA:ea1, NS:am1.1, NP:am8, HA:...
4     NP:am8, PB2:am2.2, PB1:am4, HA:ea1, NA:ea1, MP...
...                                                 ...
1137  PB2:am24, PA:am4, NS:ea3, PB1:ea3, MP:ea3, NP:...
1138    PB2:am27, PA:am8, NP:am1.2, PB1:am1.2, NS:am1.2
1139    PB2:am27, PA:am8, NP:am1.2, PB1:am1.2, NS:am1.2
1140                                           NS:am1.2
1141                                           NS:am1.2

                             Genotype Sample Title List  \
0     ea1:22-003707-003:MP, am1.1:22-010085-001:NS, ...
1     ea1:22-003707-003:MP, am1.1:22-010085-001:NS, ...
2     ea1:22-003707-003:MP, am4:23-001855-001:PB1, e...
3     ea1:22-003707-003:MP, am4:23-001855-001:PB1, e...
4     am8:23-032005-001:NP, am2.2:22-010445-001:PB2,...
...                                                 ...
1137  am24:24-030039-001:PB2, am4:24-030039-001:PA, ...
1138  am27:24-037288-001:PB2, am8:24-036222-001:PA, ...
1139  am27:24-037288-001:PB2, am8:24-036222-001:PA, ...
1140  am2.2:22-010445-001:PB2, am1:24-032138-001:MP,...
1141  am2.2:22-010445-001:PB2, am1:24-032138-001:MP,...

                            Genotype Percent Match List  \
0     98.78%, 99.17%, 98.86%, 98.66%, 98.36%, 98.70%...
1     98.78%, 99.17%, 98.86%, 98.66%, 98.36%, 98.70%...
2     98.78%, 99.43%, 98.86%, 99.17%, 98.66%, 98.36%...
3     98.78%, 99.43%, 98.86%, 99.17%, 98.66%, 98.36%...
4     98.80%, 98.55%, 99.43%, 98.42%, 98.86%, 98.88%...
...                                                 ...
1137  99.56%, 98.42%, 98.69%, 99.21%, 99.80%, 99.67%...
1138  98.64%, 98.51%, 99.00%, 98.42%, 98.93%, 84.44%...
1139  98.64%, 98.51%, 99.00%, 98.42%, 98.93%, 84.44%...
1140             85.29%, 96.33%, 96.94%, 99.05%, 98.00%
1141             85.29%, 96.33%, 96.94%, 99.05%, 98.00%

             Genotype Mismatch List Genotype Average Depth of Coverage List
0     12, 7, 16, 20, 28, 28, 13, 31       Ran on FASTA - No Coverage Report
1     12, 7, 16, 20, 28, 28, 13, 31       Ran on FASTA - No Coverage Report
2     12, 13, 16, 7, 20, 28, 28, 31       Ran on FASTA - No Coverage Report
3     12, 13, 16, 7, 20, 28, 28, 31       Ran on FASTA - No Coverage Report
4     18, 33, 13, 27, 16, 11, 25, 8       Ran on FASTA - No Coverage Report
...                             ...                                     ...
1137     10, 34, 11, 18, 2, 5, 4, 7       Ran on FASTA - No Coverage Report
1138      31, 32, 15, 36, 9, 14, 25       Ran on FASTA - No Coverage Report
1139      31, 32, 15, 36, 9, 14, 25       Ran on FASTA - No Coverage Report
1140              35, 36, 21, 8, 30       Ran on FASTA - No Coverage Report
1141              35, 36, 21, 8, 30       Ran on FASTA - No Coverage Report

[1142 rows x 46 columns]
306

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,retraction_detection_date_utc,sample,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List
0,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,NaN,SRR33124594,2025-04-15_06-38-07,SRR33124594.fa,B3.13,"MP:ea1, NS:am1.1, NA:ea1, NP:am8, HA:ea1, PA:e...","ea1:22-003707-003:MP, am1.1:22-010085-001:NS, ...","98.78%, 99.17%, 98.86%, 98.66%, 98.36%, 98.70%...","12, 7, 16, 20, 28, 28, 13, 31",Ran on FASTA - No Coverage Report
1,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,NaN,SRR33124594,2025-04-15_06-38-07,SRR33124594.fa,B3.13,"MP:ea1, NS:am1.1, NA:ea1, NP:am8, HA:ea1, PA:e...","ea1:22-003707-003:MP, am1.1:22-010085-001:NS, ...","98.78%, 99.17%, 98.86%, 98.66%, 98.36%, 98.70%...","12, 7, 16, 20, 28, 28, 13, 31",Ran on FASTA - No Coverage Report
2,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,NaN,SRR33124595,2025-04-15_06-38-07,SRR33124595.fa,B3.13,"MP:ea1, PB1:am4, NA:ea1, NS:am1.1, NP:am8, HA:...","ea1:22-003707-003:MP, am4:23-001855-001:PB1, e...","98.78%, 99.43%, 98.86%, 99.17%, 98.66%, 98.36%...","12, 13, 16, 7, 20, 28, 28, 31",Ran on FASTA - No Coverage Report
3,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,NaN,SRR33124595,2025-04-15_06-38-07,SRR33124595.fa,B3.13,"MP:ea1, PB1:am4, NA:ea1, NS:am1.1, NP:am8, HA:...","ea1:22-003707-003:MP, am4:23-001855-001:PB1, e...","98.78%, 99.43%, 98.86%, 99.17%, 98.66%, 98.36%...","12, 13, 16, 7, 20, 28, 28, 31",Ran on FASTA - No Coverage Report
4,SRR33124596,WGS,262.12,61927215,PRJNA1102327,SAMN47941262,Viral,21760157,USDA-NVSL,2025,...,NaN,SRR33124596,2025-04-15_06-38-12,SRR33124596.fa,B3.13,"NP:am8, PB2:am2.2, PB1:am4, HA:ea1, NA:ea1, MP...","am8:23-032005-001:NP, am2.2:22-010445-001:PB2,...","98.80%, 98.55%, 99.43%, 98.42%, 98.86%, 98.88%...","18, 33, 13, 27, 16, 11, 25, 8",Ran on FASTA - No Coverage Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
953,SRR33369830,WGS,148.50,182024260,PRJNA1102327,SAMN48199899,Viral,74408243,USDA-NVSL,2024,...,NaN,SRR33369830,2025-05-02_06-24-03,SRR33369830.fa,B3.13,"MP:ea1, NA:ea1, PB2:am2.2, NP:am8, NS:am1.1, P...","ea1:22-003707-003:MP, ea1:22-003707-003:NA, am...","98.98%, 98.86%, 98.64%, 99.06%, 99.05%, 99.52%...","10, 16, 31, 14, 8, 11, 25, 19",Ran on FASTA - No Coverage Report
954,SRR33369831,WGS,148.39,131993112,PRJNA1102327,SAMN48199890,Viral,54162419,USDA-NVSL,2024,...,NaN,SRR33369831,2025-05-02_06-24-03,SRR33369831.fa,B3.13,"NS:am1.1, MP:ea1, PA:ea1, NA:ea1, PB2:am2.2, P...","am1.1:22-010085-001:NS, ea1:22-003707-003:MP, ...","98.81%, 98.98%, 99.02%, 98.79%, 98.68%, 99.52%...","10, 10, 21, 17, 30, 11, 24, 15",Ran on FASTA - No Coverage Report
955,SRR33369831,WGS,148.39,131993112,PRJNA1102327,SAMN48199890,Viral,54162419,USDA-NVSL,2024,...,NaN,SRR33369831,2025-05-02_06-24-03,SRR33369831.fa,B3.13,"NS:am1.1, MP:ea1, PA:ea1, NA:ea1, PB2:am2.2, P...","am1.1:22-010085-001:NS, ea1:22-003707-003:MP, ...","98.81%, 98.98%, 99.02%, 98.79%, 98.68%, 99.52%...","10, 10, 21, 17, 30, 11, 24, 15",Ran on FASTA - No Coverage Report
956,SRR33369832,WGS,146.48,232073985,PRJNA1102327,SAMN48199889,Viral,92689954,USDA-NVSL,2024,...,NaN,SRR33369832,2025-05-02_06-24-03,SRR33369832.fa,B3.13,"NP:am8, HA:ea1, PB1:am4, PA:ea1, PB2:am2.2, NS...","am8:23-032005-001:NP, ea1:22-003707-003:HA, am...","99.00%, 98.59%, 99.52%, 99.02%, 98.68%, 98.93%...","15, 24, 11, 21, 30, 9, 10, 17",Ran on FASTA - No Coverage Report
957,SRR33369832,WGS,146.48,232073985,PRJNA1102327,SAMN48199889,Viral,92689954,USDA-NVSL,2024,...,NaN,SRR33369832,2025-05-02_06-24-03,SRR33369832.fa,B3.13,"NP:am8, HA:ea1, PB1:am4, PA:ea1, PB2:am2.2, NS...","am8:23-032005-001:NP, ea1:22-003707-003:HA, am...","99.00%, 98.59%, 99.52%, 99.02%, 98.68%, 98.93%...","15, 24, 11, 21, 30, 9, 10, 17",Ran on FASTA - No Coverage Report

In [5]:
# # Get specific geolocation and name_state from genbank_mapping.tsv

# genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
# genbank_mapping["Run"] = genbank_mapping["sra_run"]
# genbank_mapping = genbank_mapping.drop_duplicates(subset="Run", keep="first") # Drop duplicates
# genbank_mapping["name_state"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[2]) # Get the name of the state

# print(genbank_mapping)

# metadata_genbank = metadata.merge(genbank_mapping, on=["Run"]) # Only include data that has states

# # Get geolocation for second state attribute

# os.chdir(home + "/references/")
# state_ref = pd.read_csv("states_ref.csv")
# metadata_genbank["Geo_Location"] = metadata_genbank["name_state"].apply(lambda x: state_ref.loc[state_ref["Abbreviation"] == x, 'Country'].iloc[0] + "-" + x if x in state_ref["Abbreviation"].values else state_ref.loc[state_ref["State"] == x, 'Country'].iloc[0] + "-" + state_ref.loc[state_ref["State"] == x, 'Abbreviation'].iloc[0] if x in state_ref["State"].values else x)


# print(genbank_mapping["name_state"])
# print(len(metadata_genbank))
# display(metadata_genbank) # Maybe there is no state information since 3/18/2025?

In [ ]:
# If no states

metadata_genbank = metadata

metadata_genbank["name_state"] = "USA"

metadata_genbank["Geo_Location"] = "USA"

display(metadata_genbank)

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,sample,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,name_state
0,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,SRR33124594,2025-04-15_06-38-07,SRR33124594.fa,B3.13,"MP:ea1, NS:am1.1, NA:ea1, NP:am8, HA:ea1, PA:e...","ea1:22-003707-003:MP, am1.1:22-010085-001:NS, ...","98.78%, 99.17%, 98.86%, 98.66%, 98.36%, 98.70%...","12, 7, 16, 20, 28, 28, 13, 31",Ran on FASTA - No Coverage Report,USA
1,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,SRR33124594,2025-04-15_06-38-07,SRR33124594.fa,B3.13,"MP:ea1, NS:am1.1, NA:ea1, NP:am8, HA:ea1, PA:e...","ea1:22-003707-003:MP, am1.1:22-010085-001:NS, ...","98.78%, 99.17%, 98.86%, 98.66%, 98.36%, 98.70%...","12, 7, 16, 20, 28, 28, 13, 31",Ran on FASTA - No Coverage Report,USA
2,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,SRR33124595,2025-04-15_06-38-07,SRR33124595.fa,B3.13,"MP:ea1, PB1:am4, NA:ea1, NS:am1.1, NP:am8, HA:...","ea1:22-003707-003:MP, am4:23-001855-001:PB1, e...","98.78%, 99.43%, 98.86%, 99.17%, 98.66%, 98.36%...","12, 13, 16, 7, 20, 28, 28, 31",Ran on FASTA - No Coverage Report,USA
3,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,SRR33124595,2025-04-15_06-38-07,SRR33124595.fa,B3.13,"MP:ea1, PB1:am4, NA:ea1, NS:am1.1, NP:am8, HA:...","ea1:22-003707-003:MP, am4:23-001855-001:PB1, e...","98.78%, 99.43%, 98.86%, 99.17%, 98.66%, 98.36%...","12, 13, 16, 7, 20, 28, 28, 31",Ran on FASTA - No Coverage Report,USA
4,SRR33124596,WGS,262.12,61927215,PRJNA1102327,SAMN47941262,Viral,21760157,USDA-NVSL,2025,...,SRR33124596,2025-04-15_06-38-12,SRR33124596.fa,B3.13,"NP:am8, PB2:am2.2, PB1:am4, HA:ea1, NA:ea1, MP...","am8:23-032005-001:NP, am2.2:22-010445-001:PB2,...","98.80%, 98.55%, 99.43%, 98.42%, 98.86%, 98.88%...","18, 33, 13, 27, 16, 11, 25, 8",Ran on FASTA - No Coverage Report,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
953,SRR33369830,WGS,148.50,182024260,PRJNA1102327,SAMN48199899,Viral,74408243,USDA-NVSL,2024,...,SRR33369830,2025-05-02_06-24-03,SRR33369830.fa,B3.13,"MP:ea1, NA:ea1, PB2:am2.2, NP:am8, NS:am1.1, P...","ea1:22-003707-003:MP, ea1:22-003707-003:NA, am...","98.98%, 98.86%, 98.64%, 99.06%, 99.05%, 99.52%...","10, 16, 31, 14, 8, 11, 25, 19",Ran on FASTA - No Coverage Report,USA
954,SRR33369831,WGS,148.39,131993112,PRJNA1102327,SAMN48199890,Viral,54162419,USDA-NVSL,2024,...,SRR33369831,2025-05-02_06-24-03,SRR33369831.fa,B3.13,"NS:am1.1, MP:ea1, PA:ea1, NA:ea1, PB2:am2.2, P...","am1.1:22-010085-001:NS, ea1:22-003707-003:MP, ...","98.81%, 98.98%, 99.02%, 98.79%, 98.68%, 99.52%...","10, 10, 21, 17, 30, 11, 24, 15",Ran on FASTA - No Coverage Report,USA
955,SRR33369831,WGS,148.39,131993112,PRJNA1102327,SAMN48199890,Viral,54162419,USDA-NVSL,2024,...,SRR33369831,2025-05-02_06-24-03,SRR33369831.fa,B3.13,"NS:am1.1, MP:ea1, PA:ea1, NA:ea1, PB2:am2.2, P...","am1.1:22-010085-001:NS, ea1:22-003707-003:MP, ...","98.81%, 98.98%, 99.02%, 98.79%, 98.68%, 99.52%...","10, 10, 21, 17, 30, 11, 24, 15",Ran on FASTA - No Coverage Report,USA
956,SRR33369832,WGS,146.48,232073985,PRJNA1102327,SAMN48199889,Viral,92689954,USDA-NVSL,2024,...,SRR33369832,2025-05-02_06-24-03,SRR33369832.fa,B3.13,"NP:am8, HA:ea1, PB1:am4, PA:ea1, PB2:am2.2, NS...","am8:23-032005-001:NP, ea1:22-003707-003:HA, am...","99.00%, 98.59%, 99.52%, 99.02%, 98.68%, 98.93%...","15, 24, 11, 21, 30, 9, 10, 17",Ran on FASTA - No Coverage Report,USA
957,SRR33369832,WGS,146.48,232073985,PRJNA1102327,SAMN48199889,Viral,92689954,USDA-NVSL,2024,...,SRR33369832,2025-05-02_06-24-03,SRR33369832.fa,B3.13,"NP:am8, HA:ea1, PB1:am4, PA:ea1, PB2:am2.2, NS...","am8:23-032005-001:NP, ea1:22-003707-003:HA, am...","99.00%, 98.59%, 99.52%, 99.02%, 98.68%, 98.93%...","15, 24, 11, 21, 30, 9, 10, 17",Ran on FASTA - No Coverage Report,USA

## Get and save collection date

In [7]:

# # Get all dates
# metadata_genbank["Collection_Date_Specific"] = metadata_genbank["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank))

# # Save this so we don't have to do it again

# os.chdir(temp_files)
# metadata_genbank.to_csv("metadata_genbank.csv")

In [8]:
# # Upload saved data -- if doing this, make sure the above cell is commented out
# os.chdir(temp_files + "saved/")
# metadata_genbank = pd.read_csv("metadata_genbank_4-18-2025.csv")
# os.chdir(temp_files)

# # Get only updated dates

# unknown_dates = metadata_genbank[(metadata_genbank["Collection_Date_Specific"] == "2024") | (metadata_genbank["Collection_Date_Specific"] == "2025")] # Dates we don't have
# known_dates = metadata_genbank[(metadata_genbank["Collection_Date_Specific"] != "2024") & (metadata_genbank["Collection_Date_Specific"] != "2025")] # Dates we've already gotten

# # Get new dates also 
# # new_dates = metadata_genbank["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank) if )

# updated_unknown_dates = unknown_dates["BioSample"].apply(lambda x: search_collection_date(x, unknown_dates)) # Update unknown dates, if possible

# metadata_genbank = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # Remove pre-2024 dates

# metadata_genbank["Collection_Date_Compare"] = metadata_genbank["Collection_Date_Specific"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
# metadata_genbank = metadata_genbank[metadata_genbank["Collection_Date_Compare"] >= datetime(2024, 1, 1).strftime("%Y-%m-%d")]

# print(metadata_genbank[["Collection_Date_Specific"]])

# display(metadata_genbank)

In [9]:
# If no collection dates

# metadata_genbank["Collection_Date_Specific"] = metadata_genbank["Collection_Date"]

## Get host type

In [10]:
# # Create animals ref if needed

# unique_animals_all = sort_animals_andersen(metadata_genbank)

# # Flatten unique_animals_all
# every_unique_animal = []
# for animal in unique_animals_all:
#     every_unique_animal.append(animal)

# print(every_unique_animal)

# unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# os.chdir(downloads)

# animals_ref = pd.read_csv("animals_ref.csv") # Upload animals ref

# # If animal not in ref1, put in ref2

# common_animals = []
# # Check if animals in unique_animals_set are in ref1
# for animal in unique_animals_set:
#     for col in animals_ref.columns:
#         if animal in animals_ref[col].values and type(animal) == str:
#             common_animals.append(animal)

# # If not in ref1, make a list of the new animals
# different_animals = []
# for animal in unique_animals_set:
#     if animal not in common_animals:
#         different_animals.append(animal)

# print(different_animals)

# # Add to dataframe
# animals_df = animals_ref
# # Make different_animals same length as dataframe, if shorter
# if len(different_animals) < len(animals_df):
#     number_of_times_to_add_nan = len(animals_df) - len(different_animals)
#     for i in range(number_of_times_to_add_nan):
#         different_animals.append(float('nan'))
# # If longer, deal with that later

# animals_df["new"] = (different_animals)

# print(animals_df)

# animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

In [11]:
# Get animals from animal reference
os.chdir(downloads)
animals_ref = pd.read_csv("animals_ref.csv")
fix_animals_andersen(metadata_genbank, animals_ref) # Get host type

metadata_genbank["years"] = metadata_genbank["Collection_Date"].apply(lambda x: str(x).split("-")[0]) # Get year only from collection date

## Make names using all the attributes we collected

In [12]:
for num, collection_date in enumerate(metadata_genbank["Collection_Date"]):
    
    if collection_date != collection_date: # If nan
        metadata_genbank.loc[num, "Collection_Date"] = metadata_genbank.loc[num, "years"]
    else: # If actual date
        if len(str(collection_date)) == 4: # If it's a year
            # print("caught")
            metadata_genbank.loc[num, "Collection_Date"] = collection_date
        else:
            parsed_date = dateutil.parser.parse(collection_date)
            date = parsed_date.strftime("%Y-%m-%d") # Make sure it doesn't default to today, if just a year
            metadata_genbank.loc[num, "Collection_Date"] = date

    metadata_genbank = metadata_genbank.dropna(thresh=2)

# Make names

names = ">A/" + metadata_genbank["Host"] + "/" + metadata_genbank["name_state"] + "/" + metadata_genbank["isolate"] + "/" + metadata_genbank["years"].apply(lambda x: str(x)) + "|H5N1|" + metadata_genbank["Geo_Location"] + "|" + metadata_genbank["Collection_Date"].apply(lambda x: str(x)) + "|" + metadata_genbank["Host_Type"] + "|" + metadata_genbank["Genotype"]

metadata_genbank["Name"] = names

# metadata_genbank.to_csv("metadata_genbank_named.csv")

display(metadata_genbank[["ReleaseDate", 'create_date', 'Collection_Date']])

KeyError: 'Geo_Location'

In [ ]:
print(metadata_genbank)

              Run Assay Type  AvgSpotLen        Bases    BioProject  \
8388  SRR33125012        WGS      148.14  103837402.0  PRJNA1207547
8389  SRR33125013        WGS      148.47  151899011.0  PRJNA1207547
8390  SRR33125014        WGS      147.45  166656358.0  PRJNA1207547
8391  SRR33125015        WGS      148.33  107664413.0  PRJNA1207547
8392  SRR33125016        WGS      120.38    2476776.0  PRJNA1207547
...           ...        ...         ...          ...           ...
8862  SRR33370187        WGS      149.06  266567663.0  PRJNA1207547
8863  SRR33370188        WGS      149.12  252084447.0  PRJNA1207547
8864  SRR33370189        WGS      147.86  126955445.0  PRJNA1207547
8865  SRR33370190        WGS      148.58  124032966.0  PRJNA1207547
8866  SRR33370191        WGS      148.75  261906821.0  PRJNA1207547

         BioSample BioSampleModel       Bytes Center Name Collection_Date  \
8388  SAMN47941494          Viral  38567600.0   USDA-NVSL            2025
8389  SAMN47941493          Viral  55900173.0   USDA-NVSL            2025
8390  SAMN47941492          Viral  60793010.0   USDA-NVSL            2025
8391  SAMN47941491          Viral  39666477.0   USDA-NVSL            2025
8392  SAMN47941490          Viral    986034.0   USDA-NVSL            2025
...            ...            ...         ...         ...             ...
8862  SAMN48201686          Viral  96596674.0   USDA-NVSL            2025
8863  SAMN48201685          Viral  91406525.0   USDA-NVSL            2025
8864  SAMN48201684          Viral  52294003.0   USDA-NVSL            2025
8865  SAMN48201654          Viral  50995262.0   USDA-NVSL            2025
8866  SAMN48201618          Viral  95847934.0   USDA-NVSL            2025

      ...                 isolation_source BioSample Accession is_retracted  \
8388  ...  CLOACAL/OROPHARYNGEAL SWAB POOL         SRS24712538        False
8389  ...  CLOACAL/OROPHARYNGEAL SWAB POOL         SRS24712537        False
8390  ...  CLOACAL/OROPHARYNGEAL SWAB POOL         SRS24712536        False
8391  ...  CLOACAL/OROPHARYNGEAL SWAB POOL         SRS24712534        False
8392  ...                    tracheal swab         SRS24712535        False
...   ...                              ...                 ...          ...
8862  ...       CLOACAL/TRACHEAL SWAB POOL         SRS24885803        False
8863  ...                       BLOOD SWAB         SRS24885802        False
8864  ...       CLOACAL/TRACHEAL SWAB POOL         SRS24885801        False
8865  ...       CLOACAL/TRACHEAL SWAB POOL         SRS24885800        False
8866  ...  CLOACAL/OROPHARYNGEAL SWAB POOL         SRS24885799        False

     retraction_detection_date_utc Genotype name_state  \
8388                           NaN    B3.13        USA
8389                           NaN    B3.13        USA
8390                           NaN    B3.13        USA
8391                           NaN    B3.13        USA
8392                           NaN    B3.13        USA
...                            ...      ...        ...
8862                           NaN    B3.13        USA
8863                           NaN    B3.13        USA
8864                           NaN    B3.13        USA
8865                           NaN    B3.13        USA
8866                           NaN    B3.13        USA

     Collection_Date_Specific Host_Type years  \
8388                     2025     avian  2025
8389                     2025     avian  2025
8390                     2025     avian  2025
8391                     2025     avian  2025
8392                     2025     avian  2025
...                       ...       ...   ...
8862                     2025     avian  2025
8863                     2025     avian  2025
8864                     2025     avian  2025
8865                     2025     avian  2025
8866                     2025     avian  2025

                                                   Name
8388  >A/FLAMINGO/USA/25-004426-001/2025|H5N1|2025|a...
8389  >A/DUNLIN/USA/25-004499-002/2025|H5N1|2025|avi...
8390  >A/DUNLIN/USA/25-004497-005/2025|H5N1|2025|avi...
8391  >A/DUNLIN/USA/25-004497-004/2025|H5N1|2025|avi...
8392  >A/DUCK/USA/25-004480-001/2025|H5N1|2025|avian...
...                                                 ...
8862  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
8863  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
8864  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
8865  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
8866  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

[153 rows x 43 columns]

## Make FASTA files

In [ ]:
# Get information to create the fasta files

fasta_folder = originals + "avian-influenza/fasta/"

os.chdir(fasta_folder)

segments = ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]
pairs = []
fasta_files = {}

for genotype in genotypes: # ["B3.13", "D1.1"]:
    for segment in segments:
        pair = genotype + "_" + segment
        pairs.append(pair)

for pair in pairs:
    fasta_files[pair] = [] # List to hold fasta files

for run in metadata_genbank["Run"].values: # For each run 
    for dirpath, dirs, files in os.walk(fasta_folder): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            # print(file_name)
            if run in file_name: # Note that there will be ~8 files total with that run name
                # Make a fasta file and put it in the list
                with open(file_name) as f:
                    lines = f.readlines()
                    sequence = lines[1] 
                    # Each run/segment pair has one sequence -- it's placed into a file with other run/segment pairs with the same segment and genotype
                    header = metadata_genbank[metadata_genbank["Run"] == run].loc[:, "Name"].values[0]
                    genotype = metadata_genbank[metadata_genbank["Run"] == run].loc[:, "Genotype"].values[0]
                    # print(header)
                    # print(genotype)
                    # break 
                    segment = file_name.split("_")[-2]
                    # Find the pair that corresponds to 
                    pair_name = genotype + "_" + segment
                    this_specific_fasta = []
                    for pair in pairs:
                        # print(pair)
                        # print(pair_name)
                        if pair_name == pair:
                            this_specific_fasta.append(header)
                            this_specific_fasta.append(sequence)
                            fasta_files[pair].append(this_specific_fasta)
                f.close()
        break

In [ ]:
# print(fasta_files.keys())

In [ ]:
# Create fasta files 

os.chdir(originals + "complete/B3_13_D1_1/04-14-2025--05-14-2025_B3_13/")
names = []
for pair in fasta_files.keys():
    output_path = originals + "complete/B3_13_D1_1/04-14-2025--05-14-2025_B3_13/" + pair + "_andersen_" + update_date + ".fasta" 

    output_file = open(output_path, "w")
    for item in fasta_files[pair]:
        # for item in item:
        # item = fasta_files[pair]
        try:
            name = str(item[0].values[0]) # See if this is one we didn't have a collection date for
        except:
            name = str(item[0])
        print(name)
        names.append(name)
        # First is header, second is sequence
        # print(value)
        output_file.write(name + "\n")
        output_file.write(item[1])
    output_file.close()

print(len(names)/8)

>A/FLAMINGO/USA/25-004426-001/2025|H5N1|2025|avian|B3.13
>A/DUNLIN/USA/25-004499-002/2025|H5N1|2025|avian|B3.13
>A/DUNLIN/USA/25-004497-005/2025|H5N1|2025|avian|B3.13
>A/DUNLIN/USA/25-004497-004/2025|H5N1|2025|avian|B3.13
>A/DUCK/USA/25-004480-001/2025|H5N1|2025|avian|B3.13
>A/DUCK/USA/25-004477-001/2025|H5N1|2025|avian|B3.13
>A/CAT/USA/25-006823-001/2025|H5N1|2025|feline|B3.13
>A/CAT/USA/25-006491-001/2025|H5N1|2025|feline|B3.13
>A/BALD EAGLE/USA/25-005869-001/2025|H5N1|2025|avian|B3.13
>A/CAT/USA/25-006047-001/2025|H5N1|2025|feline|B3.13
>A/CROW/USA/25-004431-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004425-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004417-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-016/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-012/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-011/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-006/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-005/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004378-001/2025|H5N1|2025|avian|B3.13
>A/BALD EAGLE/USA/25-005865-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004376-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006343-005/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006332-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006331-003/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006331-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006283-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006220-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006145-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-002735-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-005879-001/2025|H5N1|2025|avian|B3.13
>A/AMERICAN CROW/USA/25-004498-005/2025|H5N1|2025|avian|B3.13
>A/BUFFLEHEAD/USA/25-004424-001/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-006142-008/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-006140-002/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-006139-001/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005927-005/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005883-001/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-009/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-008/2025|H5N1|2025|avian|B3.13
>A/BALD EAGLE/USA/25-006076-002/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-007/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-006/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-005/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-003/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-001/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005866-001/2025|H5N1|2025|avian|B3.13
>A/HOODED MERGANSER/USA/25-005880-001/2025|H5N1|2025|avian|B3.13
>A/GREEN-WINGED TEAL/USA/25-002583-006/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011694-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011691-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011541-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011424-002/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011424-001/2025|H5N1|2025|avian|B3.13
>A/BALD EAGLE/USA/25-011024-006/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011423-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011283-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011178-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-006499-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011024-001/2025|H5N1|2025|avian|B3.13
>A/COOPER'S HAWK/USA/25-011693-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-011519-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-002623-001/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-055/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-044/2025|H5N1|2025|avian|B3.13
>A/BALD EAGLE/USA/25-010933-001/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-037/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-036/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-034/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-032/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-031/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-022/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-021/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-019/2025|H5N1|2025|avian|B3.13
>A/BONAPARTE'S GULL/USA/25-011024-005/2025|H5N1|2025|avian|B3.13
>A/BLACK VULTURE/USA/25-011541-003/2025|H5N1|2025|avian|B3.13
>A/AMERICAN CROW/USA/25-011667-003/2025|H5N1|2025|avian|B3.13
>A/AMERICAN CROW/USA/25-011667-002/2025|H5N1|2025|avian|B3.13
>A/CATTLE/USA/25-011299-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-011299-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-011296-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-011296-004/2025|H5N1|2025|cattle|B3.13
>A/PET FOOD/USA/25-010008-011-v/2025|H5N1|2025|feline|B3.13
>A/PET FOOD/USA/25-010008-007-v/2025|H5N1|2025|feline|B3.13
>A/CATTLE/USA/25-011296-003/2025|H5N1|2025|cattle|B3.13
>A/PET FOOD/USA/25-010008-005-v/2025|H5N1|2025|feline|B3.13
>A/PET FOOD/USA/25-010008-004-v/2025|H5N1|2025|feline|B3.13
>A/CATTLE/USA/25-012178-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012178-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012178-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012133-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012131-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012130-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012130-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012130-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-011010-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012118-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012116-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012115-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012115-001/2025|H5N1|2025|cattle|B3.13
>A/ROUGH-LEGGED HAWK/USA/25-012510-001/2025|H5N1|2025|avian|B3.13
>A/RED FOX/USA/25-012694-001/2025|H5N1|2025|other_mammal|B3.13
>A/RED-BREASTED MERGANSER/USA/25-011271-008/2025|H5N1|2025|avian|B3.13
>A/OSPREY/USA/25-012508-004/2025|H5N1|2025|avian|B3.13
>A/Duck/USA/25-012397-002/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-050/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-048/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-043/2025|H5N1|2025|avian|B3.13
>A/AMERICAN BLACK DUCK/USA/25-012269-009/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-042/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-037/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-030/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-027/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-022/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-020/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-014/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-012/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012269-004/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012269-003/2025|H5N1|2025|avian|B3.13
>A/AMERICAN BLACK DUCK/USA/25-012269-008/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012269-001/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012246-013/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012246-029/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012246-009/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012246-007/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012246-005/2025|H5N1|2025|avian|B3.13
>A/LESSER SCAUP/USA/25-011672-001/2025|H5N1|2025|avian|B3.13
>A/HOODED MERGANSER/USA/25-007118-068/2025|H5N1|2025|avian|B3.13
>A/HERRING GULL/USA/25-012508-006/2025|H5N1|2025|avian|B3.13
>A/WOOD DUCK/USA/25-012269-016/2025|H5N1|2025|avian|B3.13
>A/WOOD DUCK/USA/25-012268-015/2025|H5N1|2025|avian|B3.13
>A/AMERICAN BLACK DUCK/USA/25-012269-013/2025|H5N1|2025|avian|B3.13
>A/VULTURE/USA/25-012105-004/2025|H5N1|2025|avian|B3.13
>A/VULTURE/USA/25-012105-003/2025|H5N1|2025|avian|B3.13
>A/VULTURE/USA/25-012105-002/2025|H5N1|2025|avian|B3.13
>A/VULTURE/USA/25-012105-001/2025|H5N1|2025|avian|B3.13
>A/TURKEY VULTURE/USA/25-012510-002/2025|H5N1|2025|avian|B3.13
>A/TURKEY VULTURE/USA/25-012249-001/2025|H5N1|2025|avian|B3.13
>A/TURKEY VULTURE/USA/25-012059-002/2025|H5N1|2025|avian|B3.13
>A/TRUMPETER SWAN/USA/25-011816-001/2025|H5N1|2025|avian|B3.13
>A/SNOWY OWL/USA/25-012050-001/2025|H5N1|2025|avian|B3.13
>A/SNOW GOOSE/USA/25-012364-001/2025|H5N1|2025|avian|B3.13
>A/AMERICAN BLACK DUCK/USA/25-012269-011/2025|H5N1|2025|avian|B3.13
>A/SNOW GOOSE/USA/25-012363-001/2025|H5N1|2025|avian|B3.13
>A/SNOW GOOSE/USA/24-037947-001/2024|H5N1|2024|avian|B3.13
>A/SAND CRANE/USA/25-012328-001/2025|H5N1|2025|avian|B3.13
>A/SAND CRANE/USA/25-012104-002/2025|H5N1|2025|avian|B3.13
>A/SAND CRANE/USA/25-012104-001/2025|H5N1|2025|avian|B3.13
>A/RED-TAILED HAWK/USA/25-012741-002/2025|H5N1|2025|avian|B3.13
>A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1|2025|avian|B3.13
>A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1|2025|avian|B3.13
>A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1|2025|avian|B3.13
>A/HERRING GULL/USA/25-012058-001/2025|H5N1|2025|avian|B3.13
>A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|H5N1|2025|avian|B3.13
>A/FLAMINGO/USA/25-004426-001/2025|H5N1|2025|avian|B3.13
>A/DUNLIN/USA/25-004499-002/2025|H5N1|2025|avian|B3.13
>A/DUNLIN/USA/25-004497-005/2025|H5N1|2025|avian|B3.13
>A/DUNLIN/USA/25-004497-004/2025|H5N1|2025|avian|B3.13
>A/DUCK/USA/25-004480-001/2025|H5N1|2025|avian|B3.13
>A/DUCK/USA/25-004477-001/2025|H5N1|2025|avian|B3.13
>A/CAT/USA/25-006823-001/2025|H5N1|2025|feline|B3.13
>A/CAT/USA/25-006491-001/2025|H5N1|2025|feline|B3.13
>A/BALD EAGLE/USA/25-005869-001/2025|H5N1|2025|avian|B3.13
>A/CAT/USA/25-006047-001/2025|H5N1|2025|feline|B3.13
>A/CROW/USA/25-004431-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004425-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004417-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-016/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-012/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-011/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-006/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-005/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004378-001/2025|H5N1|2025|avian|B3.13
>A/BALD EAGLE/USA/25-005865-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004376-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006343-005/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006332-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006331-003/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006331-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006283-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006220-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006145-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-002735-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-005879-001/2025|H5N1|2025|avian|B3.13
>A/AMERICAN CROW/USA/25-004498-005/2025|H5N1|2025|avian|B3.13
>A/BUFFLEHEAD/USA/25-004424-001/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-006142-008/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-006140-002/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-006139-001/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005927-005/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005883-001/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-009/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-008/2025|H5N1|2025|avian|B3.13
>A/BALD EAGLE/USA/25-006076-002/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-007/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-006/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-005/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-003/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005882-001/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-005866-001/2025|H5N1|2025|avian|B3.13
>A/HOODED MERGANSER/USA/25-005880-001/2025|H5N1|2025|avian|B3.13
>A/GREEN-WINGED TEAL/USA/25-002583-006/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011694-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011691-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011541-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011424-002/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011424-001/2025|H5N1|2025|avian|B3.13
>A/BALD EAGLE/USA/25-011024-006/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011423-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011283-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011178-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-006499-001/2025|H5N1|2025|avian|B3.13
>A/GREAT HORNED OWL/USA/25-011024-001/2025|H5N1|2025|avian|B3.13
>A/COOPER'S HAWK/USA/25-011693-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-011519-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-002623-001/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-055/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-044/2025|H5N1|2025|avian|B3.13
>A/BALD EAGLE/USA/25-010933-001/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-037/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-036/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-034/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-032/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-031/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-022/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-021/2025|H5N1|2025|avian|B3.13
>A/BLUE-WINGED TEAL/USA/25-011759-019/2025|H5N1|2025|avian|B3.13
>A/BONAPARTE'S GULL/USA/25-011024-005/2025|H5N1|2025|avian|B3.13
>A/BLACK VULTURE/USA/25-011541-003/2025|H5N1|2025|avian|B3.13
>A/AMERICAN CROW/USA/25-011667-003/2025|H5N1|2025|avian|B3.13
>A/AMERICAN CROW/USA/25-011667-002/2025|H5N1|2025|avian|B3.13
>A/CATTLE/USA/25-011299-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-011299-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-011296-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-011296-004/2025|H5N1|2025|cattle|B3.13
>A/PET FOOD/USA/25-010008-011-v/2025|H5N1|2025|feline|B3.13
>A/PET FOOD/USA/25-010008-007-v/2025|H5N1|2025|feline|B3.13
>A/CATTLE/USA/25-011296-003/2025|H5N1|2025|cattle|B3.13
>A/PET FOOD/USA/25-010008-005-v/2025|H5N1|2025|feline|B3.13
>A/PET FOOD/USA/25-010008-004-v/2025|H5N1|2025|feline|B3.13
>A/CATTLE/USA/25-012178-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012178-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012178-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012133-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012131-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012130-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012130-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012130-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-011010-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012118-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012116-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012115-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/USA/25-012115-001/2025|H5N1|2025|cattle|B3.13
>A/ROUGH-LEGGED HAWK/USA/25-012510-001/2025|H5N1|2025|avian|B3.13
>A/RED FOX/USA/25-012694-001/2025|H5N1|2025|other_mammal|B3.13
>A/RED-BREASTED MERGANSER/USA/25-011271-008/2025|H5N1|2025|avian|B3.13
>A/OSPREY/USA/25-012508-004/2025|H5N1|2025|avian|B3.13
>A/Duck/USA/25-012397-002/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-050/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-048/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-043/2025|H5N1|2025|avian|B3.13
>A/AMERICAN BLACK DUCK/USA/25-012269-009/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-042/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-037/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-030/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-027/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-022/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-020/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-014/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012365-012/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012269-004/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012269-003/2025|H5N1|2025|avian|B3.13
>A/AMERICAN BLACK DUCK/USA/25-012269-008/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012269-001/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012246-013/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012246-029/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012246-009/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012246-007/2025|H5N1|2025|avian|B3.13
>A/MALLARD/USA/25-012246-005/2025|H5N1|2025|avian|B3.13
>A/LESSER SCAUP/USA/25-011672-001/2025|H5N1|2025|avian|B3.13
>A/HOODED MERGANSER/USA/25-007118-068/2025|H5N1|2025|avian|B3.13
>A/HERRING GULL/USA/25-012508-006/2025|H5N1|2025|avian|B3.13
>A/WOOD DUCK/USA/25-012269-016/2025|H5N1|2025|avian|B3.13
>A/WOOD DUCK/USA/25-012268-015/2025|H5N1|2025|avian|B3.13
>A/AMERICAN BLACK DUCK/USA/25-012269-013/2025|H5N1|2025|avian|B3.13
>A/VULTURE/USA/25-012105-004/2025|H5N1|2025|avian|B3.13
>A/VULTURE/USA/25-012105-003/2025|H5N1|2025|avian|B3.13
>A/VULTURE/USA/25-012105-002/2025|H5N1|2025|avian|B3.13
>A/VULTURE/USA/25-012105-001/2025|H5N1|2025|avian|B3.13
>A/TURKEY VULTURE/USA/25-012510-002/2025|H5N1|2025|avian|B3.13
>A/TURKEY VULTURE/USA/25-012249-001/2025|H5N1|2025|avian|B3.13
>A/TURKEY VULTURE/USA/25-012059-002/2025|H5N1|2025|avian|B3.13
>A/TRUMPETER SWAN/USA/25-011816-001/2025|H5N1|2025|avian|B3.13
>A/SNOWY OWL/USA/25-012050-001/2025|H5N1|2025|avian|B3.13
>A/SNOW GOOSE/USA/25-012364-001/2025|H5N1|2025|avian|B3.13
>A/AMERICAN BLACK DUCK/USA/25-012269-011/2025|H5N1|2025|avian|B3.13
>A/SNOW GOOSE/USA/25-012363-001/2025|H5N1|2025|avian|B3.13
>A/SNOW GOOSE/USA/24-037947-001/2024|H5N1|2024|avian|B3.13
>A/SAND CRANE/USA/25-012328-001/2025|H5N1|2025|avian|B3.13
>A/SAND CRANE/USA/25-012104-002/2025|H5N1|2025|avian|B3.13
>A/SAND CRANE/USA/25-012104-001/2025|H5N1|2025|avian|B3.13
>A/RED-TAILED HAWK/USA/25-012741-002/2025|H5N1|2025|avian|B3.13
>A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1|2025|avian|B3.13
>A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1|2025|avian|B3.13
>A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1|2025|avian|B3.13
>A/HERRING GULL/USA/25-012058-001/2025|H5N1|2025|avian|B3.13
>A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|H5N1|2025|avian|B3.13
>A/FLAMINGO/USA/25-004426-001/2025|H5N1|2025|avian|B3.13
>A/DUNLIN/USA/25-004499-002/2025|H5N1|2025|avian|B3.13
>A/DUNLIN/USA/25-004497-005/2025|H5N1|2025|avian|B3.13
>A/DUNLIN/USA/25-004497-004/2025|H5N1|2025|avian|B3.13
>A/DUCK/USA/25-004480-001/2025|H5N1|2025|avian|B3.13
>A/DUCK/USA/25-004477-001/2025|H5N1|2025|avian|B3.13
>A/CAT/USA/25-006823-001/2025|H5N1|2025|feline|B3.13
>A/CAT/USA/25-006491-001/2025|H5N1|2025|feline|B3.13
>A/BALD EAGLE/USA/25-005869-001/2025|H5N1|2025|avian|B3.13
>A/CAT/USA/25-006047-001/2025|H5N1|2025|feline|B3.13
>A/CROW/USA/25-004431-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004425-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004417-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-016/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-012/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-011/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-006/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004415-005/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004378-001/2025|H5N1|2025|avian|B3.13
>A/BALD EAGLE/USA/25-005865-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-004376-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006343-005/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006332-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006331-003/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006331-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006283-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006220-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-006145-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-002735-001/2025|H5N1|2025|avian|B3.13
>A/CANADA GOOSE/USA/25-005879-001/2025|H5N1|2025|avian|B3.13

## De-Duplication

In [ ]:
# De-duplication 

# Gisaid 

gisaid = downloads + "GISAID/complete/B3_13_D1_1/04-14-2025--05-14-2025_B3_13_northa/"

os.chdir(gisaid)

dfs_gisaid = create_dataframes(gisaid)
# dfs_gisaid2 = create_dataframes(gisaid2)

B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2

In [ ]:
# Do the same with Andersen 

dfs_andersen = create_dataframes(originals + "complete/B3_13_D1_1/04-14-2025--05-14-2025_B3_13/")

B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2

In [ ]:
# os.chdir(downloads)
# dfs_gisaid["B3.13_HA"].to_csv

In [ ]:
for key in dfs_andersen.keys():
    dataframes = dfs_andersen[key]
    print(key)

print(dfs_andersen)

B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
defaultdict(<class 'list'>, {'B3.13_HA': [    isolate_partial                                        full_header  \
0        004426-001  >A/FLAMINGO/USA/25-004426-001/2025|H5N1|2025|a...
1        004499-002  >A/DUNLIN/USA/25-004499-002/2025|H5N1|2025|avi...
2        004497-005  >A/DUNLIN/USA/25-004497-005/2025|H5N1|2025|avi...
3        004497-004  >A/DUNLIN/USA/25-004497-004/2025|H5N1|2025|avi...
4        004480-001  >A/DUCK/USA/25-004480-001/2025|H5N1|2025|avian...
..              ...                                                ...
148      012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149      012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150      012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151      012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152      012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1    ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2    ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
3    ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4    ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
..                                                 ...
148  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
149  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
150  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
151  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
152  NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...

[153 rows x 3 columns]], 'B3.13_MP': [    isolate_partial                                        full_header  \
0        004426-001  >A/FLAMINGO/USA/25-004426-001/2025|H5N1|2025|a...
1        004499-002  >A/DUNLIN/USA/25-004499-002/2025|H5N1|2025|avi...
2        004497-005  >A/DUNLIN/USA/25-004497-005/2025|H5N1|2025|avi...
3        004497-004  >A/DUNLIN/USA/25-004497-004/2025|H5N1|2025|avi...
4        004480-001  >A/DUCK/USA/25-004480-001/2025|H5N1|2025|avian...
..              ...                                                ...
148      012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149      012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150      012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151      012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152      012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
..                                                 ...
148  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
149  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
150  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
151  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
152  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...

[153 rows x 3 columns]], 'B3.13_NA': [    isolate_partial                                        full_header  \
0        004426-001  >A/FLAMINGO/USA/25-004426-001/2025|H5N1|2025|a...
1        004499-002  >A/DUNLIN/USA/25-004499-002/2025|H5N1|2025|avi...
2        004497-005  >A/DUNLIN/USA/25-004497-005/2025|H5N1|2025|avi...
3        004497-004  >A/DUNLIN/USA/25-004497-004/2025|H5N1|2025|avi...
4        004480-001  >A/DUCK/USA/25-004480-001/2025|H5N1|2025|avian...
..              ...                                                ...
148      012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149      012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150      012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151      012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152      012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
1    ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
2    ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
3    ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
4    ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
..                                                 ...
148  ATGAATCCAAATCAAAAGACAATAACTATCGGGTCAATCTGCATGG...
149  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
150  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
151  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
152  NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...

[153 rows x 3 columns]], 'B3.13_NP': [    isolate_partial                                        full_header  \
0        004426-001  >A/FLAMINGO/USA/25-004426-001/2025|H5N1|2025|a...
1        004499-002  >A/DUNLIN/USA/25-004499-002/2025|H5N1|2025|avi...
2        004497-005  >A/DUNLIN/USA/25-004497-005/2025|H5N1|2025|avi...
3        004497-004  >A/DUNLIN/USA/25-004497-004/2025|H5N1|2025|avi...
4        004480-001  >A/DUCK/USA/25-004480-001/2025|H5N1|2025|avian...
..              ...                                                ...
148      012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149      012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150      012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151      012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152      012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
1    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
2    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
3    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
4    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
..                                                 ...
148  ATGGCGTCTCAAGGCACCAAACGGTCCTATGAACAAATGGAAACTG...
149  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
150  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
151  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
152  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...

[153 rows x 3 columns]], 'B3.13_NS': [    isolate_partial                                        full_header  \
0        004426-001  >A/FLAMINGO/USA/25-004426-001/2025|H5N1|2025|a...
1        004499-002  >A/DUNLIN/USA/25-004499-002/2025|H5N1|2025|avi...
2        004497-005  >A/DUNLIN/USA/25-004497-005/2025|H5N1|2025|avi...
3        004497-004  >A/DUNLIN/USA/25-004497-004/2025|H5N1|2025|avi...
4        004480-001  >A/DUCK/USA/25-004480-001/2025|H5N1|2025|avian...
..              ...                                                ...
148      012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149      012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150      012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151      012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152      012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
1    ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
2    ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
3    ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
4    ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
..                                                 ...
148  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
149  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
150  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
151  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
152  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...

[153 rows x 3 columns]], 'B3.13_PA': [    isolate_partial                                        full_header  \
0        004426-001  >A/FLAMINGO/USA/25-004426-001/2025|H5N1|2025|a...
1        004499-002  >A/DUNLIN/USA/25-004499-002/2025|H5N1|2025|avi...
2        004497-005  >A/DUNLIN/USA/25-004497-005/2025|H5N1|2025|avi...
3        004497-004  >A/DUNLIN/USA/25-004497-004/2025|H5N1|2025|avi...
4        004480-001  >A/DUCK/USA/25-004480-001/2025|H5N1|2025|avian...
..              ...                                                ...
148      012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149      012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150      012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151      012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152      012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
1    ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
2    ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
3    ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
4    ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
..                                                 ...
148  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
149  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
150  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
151  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
152  ATGGAAGATTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...

[153 rows x 3 columns]], 'B3.13_PB1': [    isolate_partial                                        full_header  \
0        004426-001  >A/FLAMINGO/USA/25-004426-001/2025|H5N1|2025|a...
1        004499-002  >A/DUNLIN/USA/25-004499-002/2025|H5N1|2025|avi...
2        004497-005  >A/DUNLIN/USA/25-004497-005/2025|H5N1|2025|avi...
3        004497-004  >A/DUNLIN/USA/25-004497-004/2025|H5N1|2025|avi...
4        004480-001  >A/DUCK/USA/25-004480-001/2025|H5N1|2025|avian...
..              ...                                                ...
148      012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149      012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150      012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151      012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152      012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
1    ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
2    ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
3    ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
4    ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
..                                                 ...
148  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
149  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
150  ATGGATGTCAATCCGACTTTACTTTTTTTAAAAGTGCCAGCGCAAG...
151  ATGGATGTCAATCCGACTTTACTTTTTTTAAAAGTGCCAGCGCAAG...
152  ATGGATGTCAATCCGACTTTACTTTTCTTGAAAGTTCCAGCGCAAA...

[153 rows x 3 columns]], 'B3.13_PB2': [    isolate_partial                                        full_header  \
0        004426-001  >A/FLAMINGO/USA/25-004426-001/2025|H5N1|2025|a...
1        004499-002  >A/DUNLIN/USA/25-004499-002/2025|H5N1|2025|avi...
2        004497-005  >A/DUNLIN/USA/25-004497-005/2025|H5N1|2025|avi...
3        004497-004  >A/DUNLIN/USA/25-004497-004/2025|H5N1|2025|avi...
4        004480-001  >A/DUCK/USA/25-004480-001/2025|H5N1|2025|avian...
..              ...                                                ...
148      012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149      012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150      012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151      012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152      012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
1    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
2    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
3    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
4    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
..                                                 ...
148  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
149  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
150  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
151  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
152  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...

[153 rows x 3 columns]]})

In [ ]:
print(len(list(dfs_gisaid.keys())))
print(len(list(dfs_andersen.keys())))

8
8

In [ ]:
# Merge dataframes and drop duplicates

full_dfs = defaultdict(list)
# same = []
# andersen = set()
# gisaid = set()

for i, andersen_key in enumerate(dfs_andersen.keys()):
    if len(dfs_andersen[andersen_key]) > 0:
        for j, gisaid_key in enumerate(dfs_gisaid.keys()):
            if andersen_key == gisaid_key:
                # same.append(gisaid_key)
        # gisaid_key = list(dfs_gisaid.keys())[i]
        # gisaid2_key = list(dfs_gisaid2.keys())[i]

                andersen_df = dfs_andersen[andersen_key][0]
                print(len(andersen_df))
                # print(andersen_df)
                gisaid_df = dfs_gisaid[gisaid_key][0]
                print(len(gisaid_df))
                # gisaid2_df = dfs_gisaid2[gisaid2_key][0]

                print(pd.concat([gisaid_df, andersen_df]).drop_duplicates())

                full_df = pd.concat([andersen_df, gisaid_df], ignore_index=True)
                print("len full df:", len(full_df))
                test = len(full_df.drop_duplicates(subset="isolate_partial"))

                dedup_df = full_df.drop_duplicates(subset="isolate_partial", keep="last")

                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print(full_df)
                
                print("Keeping nothing: ", test)
                
                print("len deduplicated:", len(dedup_df))
                full_dfs[andersen_key].append(dedup_df)
            # else:
                # gisaid.add(gisaid_key)
                # andersen.add(andersen_key)
    
    # break 


# print(full_dfs)
# print(len(full_dfs))
# print(319*8)
# print(len(same))
# print(len(andersen))
# print(len(gisaid))

153
184
          isolate_partial                                        full_header  \
0    Inoc-TX-24-029328-01  >A/dairy_cow/Kansas/Inoc-TX-24-029328-01/2024|...
1              012903-002  >A/dairy_cow/USA/012903-002/2025|H5N1|2025|cat...
2              012903-003  >A/dairy_cow/USA/012903-003/2025|H5N1|2025|cat...
3              012902-001  >A/dairy_cow/USA/012902-001/2025|H5N1|2025|cat...
4              012902-002  >A/dairy_cow/USA/012902-002/2025|H5N1|2025|cat...
..                    ...                                                ...
148            012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149            012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150            012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151            012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152            012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    actctgtcaaaatggagaacatagtactacttcttgcaatagttag...
1    atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
2    atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
3    atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
4    atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
..                                                 ...
148  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
149  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
150  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
151  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
152  NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...

[337 rows x 3 columns]
len full df: 337
Keeping nothing:  319
len deduplicated: 319
153
184
          isolate_partial                                        full_header  \
0    Inoc-TX-24-029328-01  >A/dairy_cow/Kansas/Inoc-TX-24-029328-01/2024|...
1              012903-002  >A/dairy_cow/USA/012903-002/2025|H5N1|2025|cat...
2              012903-003  >A/dairy_cow/USA/012903-003/2025|H5N1|2025|cat...
3              012902-001  >A/dairy_cow/USA/012902-001/2025|H5N1|2025|cat...
4              012902-002  >A/dairy_cow/USA/012902-002/2025|H5N1|2025|cat...
..                    ...                                                ...
148            012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149            012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150            012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151            012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152            012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    gaaagatgagtcttctaaccgaggtcgaaacgtacgttctctctat...
1    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
2    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
3    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
4    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
..                                                 ...
148  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
149  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
150  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
151  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
152  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...

[337 rows x 3 columns]
len full df: 337
Keeping nothing:  319
len deduplicated: 319
153
184
          isolate_partial                                        full_header  \
0    Inoc-TX-24-029328-01  >A/dairy_cow/Kansas/Inoc-TX-24-029328-01/2024|...
1              012903-002  >A/dairy_cow/USA/012903-002/2025|H5N1|2025|cat...
2              012903-003  >A/dairy_cow/USA/012903-003/2025|H5N1|2025|cat...
3              012902-001  >A/dairy_cow/USA/012902-001/2025|H5N1|2025|cat...
4              012902-002  >A/dairy_cow/USA/012902-002/2025|H5N1|2025|cat...
..                    ...                                                ...
148            012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149            012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150            012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151            012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152            012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    aaaatgaatccaaatcaaaagataacaaccattggatcaatctgta...
1    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
2    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
3    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
4    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
..                                                 ...
148  ATGAATCCAAATCAAAAGACAATAACTATCGGGTCAATCTGCATGG...
149  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
150  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
151  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
152  NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...

[337 rows x 3 columns]
len full df: 337
Keeping nothing:  319
len deduplicated: 319
153
184
          isolate_partial                                        full_header  \
0    Inoc-TX-24-029328-01  >A/dairy_cow/Kansas/Inoc-TX-24-029328-01/2024|...
1              012903-002  >A/dairy_cow/USA/012903-002/2025|H5N1|2025|cat...
2              012903-003  >A/dairy_cow/USA/012903-003/2025|H5N1|2025|cat...
3              012902-001  >A/dairy_cow/USA/012902-001/2025|H5N1|2025|cat...
4              012902-002  >A/dairy_cow/USA/012902-002/2025|H5N1|2025|cat...
..                    ...                                                ...
148            012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149            012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150            012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151            012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152            012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    ctcactgagtgacatccacatcatggcgtctcaaggcaccaaacga...
1    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
2    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
3    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
4    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
..                                                 ...
148  ATGGCGTCTCAAGGCACCAAACGGTCCTATGAACAAATGGAAACTG...
149  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
150  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
151  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
152  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...

[337 rows x 3 columns]
len full df: 337
Keeping nothing:  319
len deduplicated: 319
153
184
          isolate_partial                                        full_header  \
0    Inoc-TX-24-029328-01  >A/dairy_cow/Kansas/Inoc-TX-24-029328-01/2024|...
1              012903-002  >A/dairy_cow/USA/012903-002/2025|H5N1|2025|cat...
2              012903-003  >A/dairy_cow/USA/012903-003/2025|H5N1|2025|cat...
3              012902-001  >A/dairy_cow/USA/012902-001/2025|H5N1|2025|cat...
4              012902-002  >A/dairy_cow/USA/012902-002/2025|H5N1|2025|cat...
..                    ...                                                ...
148            012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149            012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150            012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151            012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152            012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    taaaaacataatggattccaacactgtgttaagctttcaggtagac...
1    atggattccaacactgtgttaagctttcaggtagactgctttcttt...
2    atggattccaacactgtgttaagctttcaggtagactgctttcttt...
3    atggattccaacactgtgttaagctttcaggtagactgctttcttt...
4    atggattccaacactgtgttaagctttcaggtagactgctttcttt...
..                                                 ...
148  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
149  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
150  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
151  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
152  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...

[337 rows x 3 columns]
len full df: 337
Keeping nothing:  319
len deduplicated: 319
153
184
          isolate_partial                                        full_header  \
0    Inoc-TX-24-029328-01  >A/dairy_cow/Kansas/Inoc-TX-24-029328-01/2024|...
1              012903-002  >A/dairy_cow/USA/012903-002/2025|H5N1|2025|cat...
2              012903-003  >A/dairy_cow/USA/012903-003/2025|H5N1|2025|cat...
3              012902-001  >A/dairy_cow/USA/012902-001/2025|H5N1|2025|cat...
4              012902-002  >A/dairy_cow/USA/012902-002/2025|H5N1|2025|cat...
..                    ...                                                ...
148            012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149            012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150            012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151            012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152            012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    agcgaaagcaggtgctgattcaaaatggaagactttgtgcgacaat...
1    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
2    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
3    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
4    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
..                                                 ...
148  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
149  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
150  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
151  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
152  ATGGAAGATTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...

[337 rows x 3 columns]
len full df: 337
Keeping nothing:  319
len deduplicated: 319
153
184
          isolate_partial                                        full_header  \
0    Inoc-TX-24-029328-01  >A/dairy_cow/Kansas/Inoc-TX-24-029328-01/2024|...
1              012903-002  >A/dairy_cow/USA/012903-002/2025|H5N1|2025|cat...
2              012903-003  >A/dairy_cow/USA/012903-003/2025|H5N1|2025|cat...
3              012902-001  >A/dairy_cow/USA/012902-001/2025|H5N1|2025|cat...
4              012902-002  >A/dairy_cow/USA/012902-002/2025|H5N1|2025|cat...
..                    ...                                                ...
148            012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149            012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150            012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151            012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152            012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    ccatttgaatggatgtcaatccgaccttactcttcttgaaagttcc...
1    atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
2    atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
3    atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
4    atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
..                                                 ...
148  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
149  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
150  ATGGATGTCAATCCGACTTTACTTTTTTTAAAAGTGCCAGCGCAAG...
151  ATGGATGTCAATCCGACTTTACTTTTTTTAAAAGTGCCAGCGCAAG...
152  ATGGATGTCAATCCGACTTTACTTTTCTTGAAAGTTCCAGCGCAAA...

[337 rows x 3 columns]
len full df: 337
Keeping nothing:  319
len deduplicated: 319
153
184
          isolate_partial                                        full_header  \
0    Inoc-TX-24-029328-01  >A/dairy_cow/Kansas/Inoc-TX-24-029328-01/2024|...
1              012903-002  >A/dairy_cow/USA/012903-002/2025|H5N1|2025|cat...
2              012903-003  >A/dairy_cow/USA/012903-003/2025|H5N1|2025|cat...
3              012902-001  >A/dairy_cow/USA/012902-001/2025|H5N1|2025|cat...
4              012902-002  >A/dairy_cow/USA/012902-002/2025|H5N1|2025|cat...
..                    ...                                                ...
148            012740-001  >A/RED-TAILED HAWK/USA/25-012740-001/2025|H5N1...
149            012695-001  >A/RED-TAILED HAWK/USA/25-012695-001/2025|H5N1...
150            012058-002  >A/RED-TAILED HAWK/USA/25-012058-002/2025|H5N1...
151            012058-001  >A/HERRING GULL/USA/25-012058-001/2025|H5N1|20...
152            012269-006  >A/AMERICAN BLACK DUCK/USA/25-012269-006/2025|...

                                              sequence
0    atatattcaatatggagagaataaaagaactgagagatctaatgtc...
1    atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
2    atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
3    atggagagaataaaagaactgagagatctaatgtcacagcctcgca...
4    atggagagaataaaagaactgagagatctaatgtcacagcctcgca...
..                                                 ...
148  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
149  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
150  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
151  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
152  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...

[337 rows x 3 columns]
len full df: 337
Keeping nothing:  319
len deduplicated: 319

In [ ]:
# If none in one database, only use the other and drop duplicates

# full_dfs = defaultdict(list)
# for key in dfs_andersen.keys():
#     print(key)
# # for key in ["D1.3"]:
#     dataframes = dfs_andersen[key]
#     for i, df in enumerate(dataframes):
#         print(i)
#         try:
#             # full_df = df.merge(dfs_gisaid[key][i], how="outer")
#             # print(full_df)
#             full_df = full_df.drop_duplicates(subset=["isolate_partial"])
#             full_dfs[key].append(full_df)
#         except:
#             print("Failed to merge dataframes in ", key)

## Create FASTA files combining Andersen and GISAID

In [ ]:
# Create FASTA files per segment

combined_files = downloads + "Combinations/GISAID_Andersen/B3_13_D1_1/04-14-2025--05-14-2025_B3_13/"

os.chdir(combined_files)
for pair in full_dfs.keys():
    print(pair)
    output_path = combined_files + pair + "_combined_" + update_date + ".fasta" 

    output_file = open(output_path, "w")
    for item in full_dfs[pair]:
        # for item in item:
        # item = fasta_files[pair]
        for index, row in item.iterrows():
            name = item.loc[index, "full_header"]
            sequence = item.loc[index, "sequence"]
            # print(name)
        # First is header, second is sequence
        # print(value)
            output_file.write(name)
            output_file.write(sequence)
    output_file.close()

B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2