# Cleaning Downloaded Data from avian-flu

Author: Alexander Maksiaev

Purpose: Clean downloaded data from avian-flu, rename sequences according to convention, de-duplicate from GISAID

In [1]:
# Housekeeping

import os
import glob 
import pandas as pd
import xml.etree.ElementTree as ET
import requests
import time
import numpy as np
import dateutil 
from datetime import datetime
from collections import defaultdict 
import importlib
import utils  
importlib.reload(utils)
from utils import * 


# Dates
start_date = "11-01-2021"
end_date = "06-13-2025"
date_range = start_date + "--" + end_date
# update_date = "06-18-2025"

# Make sure you have the correct paths

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/"
# downloads = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
originals = downloads + "Andersen/"
saved = originals + "saved/"
temp_files = originals + "temp/"
complete_files = downloads + "complete/"

os.chdir(downloads)

## Read Metadata

In [2]:
# Read metadata

os.chdir(saved)
metadata_normalized = pd.read_csv("metadata_normalized.tsv", delimiter="\t") # Collection dates

metadata_folder = originals + "avian-influenza/metadata/"
os.chdir(metadata_folder)

metadata = pd.read_csv("SraRunTable_automated.csv")

print(len(metadata)) # 7397 rows

metadata = metadata.merge(metadata_normalized, how="outer")
print(metadata.columns)

metadata["name_state"] = metadata["geo_loc_name"].apply(lambda x: x.split("/")[1] if len(x.split("/")) > 1 else x.split("/")[0])

# Find only >= last date using Release Date from metadata 
metadata["ReleaseDate"] = metadata["ReleaseDate"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
metadata = metadata[metadata["ReleaseDate"] >= dateutil.parser.parse(start_date).strftime("%Y-%m-%d")]
# Find only <= update date using Release Date from metadata
metadata = metadata[metadata["ReleaseDate"] <= dateutil.parser.parse(end_date).strftime("%Y-%m-%d")]

print(len(metadata)) # 6053 rows between 1/1/2024 and 4/14/2025
display(metadata)

9697
Index(['Run', 'Assay Type', 'AvgSpotLen', 'Bases', 'BioProject', 'BioSample',
       'BioSampleModel', 'Bytes', 'Center Name', 'Collection_Date', 'Consent',
       'DATASTORE filetype', 'DATASTORE provider', 'DATASTORE region',
       'Experiment', 'geo_loc_name_country', 'geo_loc_name_country_continent',
       'geo_loc_name', 'Host', 'Instrument', 'isolate', 'Library Name',
       'LibraryLayout', 'LibrarySelection', 'LibrarySource', 'Organism',
       'Platform', 'ReleaseDate', 'create_date', 'version', 'Sample Name',
       'SRA Study', 'serotype', 'isolation_source', 'BioSample Accession',
       'is_retracted', 'retraction_detection_date_utc'],
      dtype='object')
19050

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,create_date,version,Sample Name,SRA Study,serotype,isolation_source,BioSample Accession,is_retracted,retraction_detection_date_utc,name_state
0,SRR24839058,AMPLICON,230.77,32942716,PRJNA980729,SAMN35647642,Viral,18373327,United States Department of Agriculture,missing,...,2023-06-07 02:01:47,1,22-005893-001,SRP441379,H5N1,",",SRS17903639,False,NaN,Massachusetts
1,SRR24839058,AMPLICON,230.77,32942716,PRJNA980729,SAMN35647642,Viral,18373327,United States Department of Agriculture,missing,...,2023-06-07 02:01:47,1,22-005893-001,SRP441379,H5N1,"Swab, Tracheal",SRS17903639,False,NaN,"USA: Massachusetts, Barnstable County"
2,SRR24839059,AMPLICON,207.54,53993591,PRJNA980729,SAMN35647620,Viral,29609119,United States Department of Agriculture,2022-02-08,...,2023-06-07 02:01:22,1,AH0210318,SRP441379,H5N1,",/",SRS17903636,False,NaN,Kentucky
3,SRR24839059,AMPLICON,207.54,53993591,PRJNA980729,SAMN35647620,Viral,29609119,United States Department of Agriculture,2022-02-08,...,2023-06-07 02:01:22,1,AH0210318,SRP441379,H5N1,"Swab Pool, Cloacal/Oropharyngeal",SRS17903636,False,NaN,"USA: Kentucky, Henderson County"
4,SRR24839060,AMPLICON,201.66,21703662,PRJNA980729,SAMN35647621,Viral,10716272,United States Department of Agriculture,2022-02-17,...,2023-06-07 02:01:28,1,22-005158-001,SRP441379,H5N1,NaN,SRS17903631,False,NaN,Maine
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19045,SRR33830446,WGS,148.77,95232771,PRJNA1102327,SAMN48895426,Viral,37952018,USDA-NVSL,2025,...,2025-06-04 14:24:56,1,25-015677-004,SRP503016,NaN,"MILK, BULK TANK",SRS25266464,False,NaN,USA
19046,SRR33830447,WGS,148.43,106145246,PRJNA1102327,SAMN48895425,Viral,42182759,USDA-NVSL,2025,...,2025-06-04 14:25:01,1,25-015677-003,SRP503016,NaN,"MILK, BULK TANK",SRS25266463,False,NaN,USA
19047,SRR33830448,WGS,148.30,110812426,PRJNA1102327,SAMN48895424,Viral,43738503,USDA-NVSL,2025,...,2025-06-04 14:24:55,1,25-015677-002,SRP503016,NaN,"MILK, BULK TANK",SRS25266462,False,NaN,USA
19048,SRR33830449,WGS,131.52,67358891,PRJNA1102327,SAMN48895415,Viral,26336550,USDA-NVSL,2024,...,2025-06-04 14:24:53,1,24-036379-001-tile,SRP503016,NaN,"MILK, BULK TANK",SRS25266461,False,NaN,USA
19049,SRR33830450,WGS,131.13,69602732,PRJNA1102327,SAMN48895414,Viral,27556171,USDA-NVSL,2024,...,2025-06-04 14:24:53,1,24-034788-001-tile,SRP503016,NaN,"MILK, BULK TANK",SRS25266460,False,NaN,USA

In [3]:
# Get list of genotypes

os.chdir(home + "references/")

genotypes_df = pd.read_excel("genotype_key.xlsx")

genotypes = list(genotypes_df["Genotype"])

# print(genotypes)

# genotypes = ["B3.2"] #, "B3.2", "B3.6", "B3.7", "B3.5", "A3"]

### Naming convention ###
>A/[host]/[geo_loc_name]/[isolate]/[year]|[serotype: H5N1]|[collection_date]|[host_type]|[genotype]

host_type is from manual animal reference

In metadata, we have: host, geo_loc_name, isolate, year

We need: geo_loc_name, collection_date, host_type, genotype

host = Host

geo_loc_name (primary) = geo_loc_name

geo_loc_name (secondary) = genbank_mapping.tsv > genbank_name

isolate = isolate

collection date (primary) = Collection_Date

collection date (secondary) = https://www.ncbi.nlm.nih.gov/genbank/ > BioSample (input: BioSample) > Nucleotide > [first result] > collection_date

serotype = serotype

host type = [from ref] 

genotype = [from genoflu] -- use genoflu_results.tsv

## Get genotype, specific geolocation

In [4]:
# Get genotype from genoflu_results.tsv

os.chdir(metadata_folder)

genoflu_results = pd.read_csv("genoflu_results.tsv", delimiter="\t")

genoflu_results["Run"] = genoflu_results["sample"]

metadata = metadata.merge(genoflu_results, on="Run", how="inner")
print(metadata)
# metadata = metadata[~metadata["Genotype"].str.contains('Not assigned')] # Do not include non-assigned genotypes
metadata = metadata[metadata["Genotype"].isin(genotypes)]

# Get only the genotypes we want: B3.13 and D1.1

# b313_and_d11_only = genoflu_results[(genoflu_results["Genotype"] == "B3.13") | (genoflu_results["Genotype"] == "D1.1")]
# b313_and_d11_only = b313_and_d11_only.rename(columns={"sample": "Run"})
# b313_and_d11_only = b313_and_d11_only.drop_duplicates(subset="Run", keep="last")

# metadata = metadata.merge(b313_and_d11_only, on=["Run", "Genotype"], how="inner")

print(len(metadata)) 

display(metadata)

               Run Assay Type  AvgSpotLen      Bases    BioProject  \
0      SRR24839058   AMPLICON      230.77   32942716   PRJNA980729
1      SRR24839058   AMPLICON      230.77   32942716   PRJNA980729
2      SRR24839059   AMPLICON      207.54   53993591   PRJNA980729
3      SRR24839059   AMPLICON      207.54   53993591   PRJNA980729
4      SRR24839060   AMPLICON      201.66   21703662   PRJNA980729
...            ...        ...         ...        ...           ...
19045  SRR33830446        WGS      148.77   95232771  PRJNA1102327
19046  SRR33830447        WGS      148.43  106145246  PRJNA1102327
19047  SRR33830448        WGS      148.30  110812426  PRJNA1102327
19048  SRR33830449        WGS      131.52   67358891  PRJNA1102327
19049  SRR33830450        WGS      131.13   69602732  PRJNA1102327

          BioSample BioSampleModel     Bytes  \
0      SAMN35647642          Viral  18373327
1      SAMN35647642          Viral  18373327
2      SAMN35647620          Viral  29609119
3      SAMN35647620          Viral  29609119
4      SAMN35647621          Viral  10716272
...             ...            ...       ...
19045  SAMN48895426          Viral  37952018
19046  SAMN48895425          Viral  42182759
19047  SAMN48895424          Viral  43738503
19048  SAMN48895415          Viral  26336550
19049  SAMN48895414          Viral  27556171

                                   Center Name Collection_Date  ...  \
0      United States Department of Agriculture         missing  ...
1      United States Department of Agriculture         missing  ...
2      United States Department of Agriculture      2022-02-08  ...
3      United States Department of Agriculture      2022-02-08  ...
4      United States Department of Agriculture      2022-02-17  ...
...                                        ...             ...  ...
19045                                USDA-NVSL            2025  ...
19046                                USDA-NVSL            2025  ...
19047                                USDA-NVSL            2025  ...
19048                                USDA-NVSL            2024  ...
19049                                USDA-NVSL            2024  ...

                                  name_state       sample  \
0                              Massachusetts  SRR24839058
1      USA: Massachusetts, Barnstable County  SRR24839058
2                                   Kentucky  SRR24839059
3            USA: Kentucky, Henderson County  SRR24839059
4                                      Maine  SRR24839060
...                                      ...          ...
19045                                    USA  SRR33830446
19046                                    USA  SRR33830447
19047                                    USA  SRR33830448
19048                                    USA  SRR33830449
19049                                    USA  SRR33830450

                      date       File Name  \
0      2025-05-09_10-45-20  SRR24839058.fa
1      2025-05-09_10-45-20  SRR24839058.fa
2      2025-05-09_10-45-06  SRR24839059.fa
3      2025-05-09_10-45-06  SRR24839059.fa
4      2025-05-09_10-45-39  SRR24839060.fa
...                    ...             ...
19045  2025-06-06_07-56-21  SRR33830446.fa
19046  2025-06-06_07-56-21  SRR33830447.fa
19047  2025-06-06_07-56-21  SRR33830448.fa
19048  2025-06-06_07-56-20  SRR33830449.fa
19049  2025-06-06_07-56-20  SRR33830450.fa

                                                Genotype  \
0                                                     A1
1                                                     A1
2                                                     A1
3                                                     A1
4                                                     A1
...                                                  ...
19045  Not assigned: Only 7 segments >98.0% match fou...
19046  Not assigned: Only 7 segments >98.0% match fou...
19047  Not assigned: Only 7 segments >98.0% match fou...
19048                                              B3.13
19049                                              B3.13

                             Genotype List Used, >=98.0%  \
0      NP:ea1, PB2:ea1, PB1:ea1, MP:ea1, NA:ea1, NS:e...
1      NP:ea1, PB2:ea1, PB1:ea1, MP:ea1, NA:ea1, NS:e...
2      NP:ea1, PA:ea1, MP:ea1, NA:ea1, PB1:ea1, PB2:e...
3      NP:ea1, PA:ea1, MP:ea1, NA:ea1, PB1:ea1, PB2:e...
4      NP:ea1, MP:ea1, NS:ea1, PA:ea1, PB1:ea1, PB2:e...
...                                                  ...
19045  PB1:am4, NA:ea1, NS:am1.1, PA:ea1, MP:ea1, NP:...
19046  PB1:am4, PB2:am2.2, NA:ea1, NS:am1.1, PA:ea1, ...
19047  NA:ea1, MP:ea1, PB2:am2.2, PA:ea1, PB1:am4, NP...
19048  NP:am8, NA:ea1, PB1:am4, HA:ea1, NS:am1.1, MP:...
19049  HA:ea1, NA:ea1, NP:am8, PB2:am2.2, MP:ea1, PB1...

                              Genotype Sample Title List  \
0      ea1:22-003707-003:NP, ea1:22-003707-003:PB2, e...
1      ea1:22-003707-003:NP, ea1:22-003707-003:PB2, e...
2      ea1:22-003707-003:NP, ea1:22-003707-003:PA, ea...
3      ea1:22-003707-003:NP, ea1:22-003707-003:PA, ea...
4      ea1:22-003707-003:NP, ea1:22-003707-003:MP, ea...
...                                                  ...
19045  am4:23-001855-001:PB1, ea1:22-003707-003:NA, e...
19046  am4:23-001855-001:PB1, am2.2:22-010445-001:PB2...
19047  ea1:22-003707-003:HA, ea1:22-003707-003:NA, ea...
19048  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
19049  ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...

                             Genotype Percent Match List  \
0      99.87%, 99.80%, 99.91%, 99.90%, 99.79%, 99.88%...
1      99.87%, 99.80%, 99.91%, 99.90%, 99.79%, 99.88%...
2      100.00%, 100.00%, 99.90%, 99.93%, 99.96%, 100....
3      100.00%, 100.00%, 99.90%, 99.93%, 99.96%, 100....
4      99.80%, 99.90%, 99.88%, 99.72%, 99.65%, 99.66%...
...                                                  ...
19045  99.34%, 98.79%, 97.95%, 98.33%, 98.70%, 98.88%...
19046  99.34%, 98.38%, 97.95%, 98.86%, 98.45%, 98.79%...
19047  97.95%, 98.86%, 98.88%, 98.38%, 98.79%, 99.34%...
19048  98.93%, 98.86%, 99.47%, 98.43%, 99.17%, 98.95%...
19049  98.92%, 98.71%, 99.00%, 98.55%, 98.74%, 99.47%...

               Genotype Mismatch List Genotype Average Depth of Coverage List
0              2, 3, 2, 1, 3, 1, 6, 4       Ran on FASTA - No Coverage Report
1              2, 3, 2, 1, 3, 1, 6, 4       Ran on FASTA - No Coverage Report
2              0, 0, 1, 1, 1, 0, 1, 0       Ran on FASTA - No Coverage Report
3              0, 0, 1, 1, 1, 0, 1, 0       Ran on FASTA - No Coverage Report
4              3, 1, 1, 6, 8, 5, 6, 4       Ran on FASTA - No Coverage Report
...                               ...                                     ...
19045  15, 17, 35, 14, 28, 11, 17, 37       Ran on FASTA - No Coverage Report
19046  15, 37, 35, 16, 13, 26, 11, 17       Ran on FASTA - No Coverage Report
19047  35, 16, 11, 37, 26, 15, 17, 13       Ran on FASTA - No Coverage Report
19048   16, 16, 12, 12, 7, 10, 31, 24       Ran on FASTA - No Coverage Report
19049   11, 12, 15, 33, 12, 12, 8, 23       Ran on FASTA - No Coverage Report

[19050 rows x 47 columns]
18082

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,name_state,sample,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List
0,SRR24839058,AMPLICON,230.77,32942716,PRJNA980729,SAMN35647642,Viral,18373327,United States Department of Agriculture,missing,...,Massachusetts,SRR24839058,2025-05-09_10-45-20,SRR24839058.fa,A1,"NP:ea1, PB2:ea1, PB1:ea1, MP:ea1, NA:ea1, NS:e...","ea1:22-003707-003:NP, ea1:22-003707-003:PB2, e...","99.87%, 99.80%, 99.91%, 99.90%, 99.79%, 99.88%...","2, 3, 2, 1, 3, 1, 6, 4",Ran on FASTA - No Coverage Report
1,SRR24839058,AMPLICON,230.77,32942716,PRJNA980729,SAMN35647642,Viral,18373327,United States Department of Agriculture,missing,...,"USA: Massachusetts, Barnstable County",SRR24839058,2025-05-09_10-45-20,SRR24839058.fa,A1,"NP:ea1, PB2:ea1, PB1:ea1, MP:ea1, NA:ea1, NS:e...","ea1:22-003707-003:NP, ea1:22-003707-003:PB2, e...","99.87%, 99.80%, 99.91%, 99.90%, 99.79%, 99.88%...","2, 3, 2, 1, 3, 1, 6, 4",Ran on FASTA - No Coverage Report
2,SRR24839059,AMPLICON,207.54,53993591,PRJNA980729,SAMN35647620,Viral,29609119,United States Department of Agriculture,2022-02-08,...,Kentucky,SRR24839059,2025-05-09_10-45-06,SRR24839059.fa,A1,"NP:ea1, PA:ea1, MP:ea1, NA:ea1, PB1:ea1, PB2:e...","ea1:22-003707-003:NP, ea1:22-003707-003:PA, ea...","100.00%, 100.00%, 99.90%, 99.93%, 99.96%, 100....","0, 0, 1, 1, 1, 0, 1, 0",Ran on FASTA - No Coverage Report
3,SRR24839059,AMPLICON,207.54,53993591,PRJNA980729,SAMN35647620,Viral,29609119,United States Department of Agriculture,2022-02-08,...,"USA: Kentucky, Henderson County",SRR24839059,2025-05-09_10-45-06,SRR24839059.fa,A1,"NP:ea1, PA:ea1, MP:ea1, NA:ea1, PB1:ea1, PB2:e...","ea1:22-003707-003:NP, ea1:22-003707-003:PA, ea...","100.00%, 100.00%, 99.90%, 99.93%, 99.96%, 100....","0, 0, 1, 1, 1, 0, 1, 0",Ran on FASTA - No Coverage Report
4,SRR24839060,AMPLICON,201.66,21703662,PRJNA980729,SAMN35647621,Viral,10716272,United States Department of Agriculture,2022-02-17,...,Maine,SRR24839060,2025-05-09_10-45-39,SRR24839060.fa,A1,"NP:ea1, MP:ea1, NS:ea1, PA:ea1, PB1:ea1, PB2:e...","ea1:22-003707-003:NP, ea1:22-003707-003:MP, ea...","99.80%, 99.90%, 99.88%, 99.72%, 99.65%, 99.66%...","3, 1, 1, 6, 8, 5, 6, 4",Ran on FASTA - No Coverage Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19042,SRR33830443,WGS,148.11,100597029,PRJNA1102327,SAMN48895429,Viral,39710063,USDA-NVSL,2025,...,USA,SRR33830443,2025-06-06_07-56-21,SRR33830443.fa,B3.13,"NA:ea1, PB1:am4, MP:ea1, PA:ea1, NP:am8, HA:ea...","ea1:22-003707-003:NA, am4:23-001855-001:PB1, e...","98.72%, 99.52%, 98.98%, 98.88%, 98.86%, 98.06%...","18, 11, 10, 24, 17, 33, 38, 9",Ran on FASTA - No Coverage Report
19043,SRR33830444,WGS,148.50,131987248,PRJNA1102327,SAMN48895428,Viral,51617990,USDA-NVSL,2025,...,USA,SRR33830444,2025-06-06_07-56-20,SRR33830444.fa,B3.13,"PA:ea1, NA:ea1, PB2:am2.2, NP:am8, HA:ea1, MP:...","ea1:22-003707-003:PA, ea1:22-003707-003:NA, am...","98.88%, 98.65%, 98.20%, 98.93%, 98.06%, 98.98%...","24, 19, 41, 16, 33, 10, 12, 9",Ran on FASTA - No Coverage Report
19044,SRR33830445,WGS,148.12,115677479,PRJNA1102327,SAMN48895427,Viral,45674405,USDA-NVSL,2025,...,USA,SRR33830445,2025-06-06_07-56-21,SRR33830445.fa,B3.13,"NP:am8, HA:ea1, PA:ea1, NS:am1.1, PB1:am4, PB2...","am8:23-032005-001:NP, ea1:22-003707-003:HA, ea...","98.93%, 98.24%, 98.79%, 98.93%, 99.56%, 98.51%...","16, 30, 26, 9, 10, 34, 19, 11",Ran on FASTA - No Coverage Report
19048,SRR33830449,WGS,131.52,67358891,PRJNA1102327,SAMN48895415,Viral,26336550,USDA-NVSL,2024,...,USA,SRR33830449,2025-06-06_07-56-20,SRR33830449.fa,B3.13,"NP:am8, NA:ea1, PB1:am4, HA:ea1, NS:am1.1, MP:...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","98.93%, 98.86%, 99.47%, 98.43%, 99.17%, 98.95%...","16, 16, 12, 12, 7, 10, 31, 24",Ran on FASTA - No Coverage Report
19049,SRR33830450,WGS,131.13,69602732,PRJNA1102327,SAMN48895414,Viral,27556171,USDA-NVSL,2024,...,USA,SRR33830450,2025-06-06_07-56-20,SRR33830450.fa,B3.13,"HA:ea1, NA:ea1, NP:am8, PB2:am2.2, MP:ea1, PB1...","ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...","98.92%, 98.71%, 99.00%, 98.55%, 98.74%, 99.47%...","11, 12, 15, 33, 12, 12, 8, 23",Ran on FASTA - No Coverage Report

In [5]:
# Get specific geolocation and name_state from genbank_mapping.tsv

genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
genbank_mapping["Run"] = genbank_mapping["sra_run"]
genbank_mapping = genbank_mapping.drop_duplicates(subset="Run", keep="first") # Drop duplicates
genbank_mapping["name_state"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[2]) # Get the name of the state

# print(genbank_mapping)

# metadata_genbank = metadata.merge(genbank_mapping, on=["Run"]) # Only include data that has states

# Get geolocation for second state attribute

os.chdir(home + "references/")
state_ref = pd.read_csv("states_ref.csv")
metadata["Geo_Location"] = metadata["name_state"].apply(lambda x: state_ref.loc[state_ref["Abbreviation"] == x, 'Country'].iloc[0] + "-" + x if x in state_ref["Abbreviation"].values else state_ref.loc[state_ref["State"] == x, 'Country'].iloc[0] + "-" + state_ref.loc[state_ref["State"] == x, 'Abbreviation'].iloc[0] if x in state_ref["State"].values else x)


print(metadata["name_state"])
print(len(metadata))
display(metadata) # Maybe there is no state information since 3/18/2025?

0                                Massachusetts
1        USA: Massachusetts, Barnstable County
2                                     Kentucky
3              USA: Kentucky, Henderson County
4                                        Maine
                         ...
19042                                      USA
19043                                      USA
19044                                      USA
19048                                      USA
19049                                      USA
Name: name_state, Length: 18082, dtype: object
18082

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,sample,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,Geo_Location
0,SRR24839058,AMPLICON,230.77,32942716,PRJNA980729,SAMN35647642,Viral,18373327,United States Department of Agriculture,missing,...,SRR24839058,2025-05-09_10-45-20,SRR24839058.fa,A1,"NP:ea1, PB2:ea1, PB1:ea1, MP:ea1, NA:ea1, NS:e...","ea1:22-003707-003:NP, ea1:22-003707-003:PB2, e...","99.87%, 99.80%, 99.91%, 99.90%, 99.79%, 99.88%...","2, 3, 2, 1, 3, 1, 6, 4",Ran on FASTA - No Coverage Report,USA-MA
1,SRR24839058,AMPLICON,230.77,32942716,PRJNA980729,SAMN35647642,Viral,18373327,United States Department of Agriculture,missing,...,SRR24839058,2025-05-09_10-45-20,SRR24839058.fa,A1,"NP:ea1, PB2:ea1, PB1:ea1, MP:ea1, NA:ea1, NS:e...","ea1:22-003707-003:NP, ea1:22-003707-003:PB2, e...","99.87%, 99.80%, 99.91%, 99.90%, 99.79%, 99.88%...","2, 3, 2, 1, 3, 1, 6, 4",Ran on FASTA - No Coverage Report,"USA: Massachusetts, Barnstable County"
2,SRR24839059,AMPLICON,207.54,53993591,PRJNA980729,SAMN35647620,Viral,29609119,United States Department of Agriculture,2022-02-08,...,SRR24839059,2025-05-09_10-45-06,SRR24839059.fa,A1,"NP:ea1, PA:ea1, MP:ea1, NA:ea1, PB1:ea1, PB2:e...","ea1:22-003707-003:NP, ea1:22-003707-003:PA, ea...","100.00%, 100.00%, 99.90%, 99.93%, 99.96%, 100....","0, 0, 1, 1, 1, 0, 1, 0",Ran on FASTA - No Coverage Report,USA-KY
3,SRR24839059,AMPLICON,207.54,53993591,PRJNA980729,SAMN35647620,Viral,29609119,United States Department of Agriculture,2022-02-08,...,SRR24839059,2025-05-09_10-45-06,SRR24839059.fa,A1,"NP:ea1, PA:ea1, MP:ea1, NA:ea1, PB1:ea1, PB2:e...","ea1:22-003707-003:NP, ea1:22-003707-003:PA, ea...","100.00%, 100.00%, 99.90%, 99.93%, 99.96%, 100....","0, 0, 1, 1, 1, 0, 1, 0",Ran on FASTA - No Coverage Report,"USA: Kentucky, Henderson County"
4,SRR24839060,AMPLICON,201.66,21703662,PRJNA980729,SAMN35647621,Viral,10716272,United States Department of Agriculture,2022-02-17,...,SRR24839060,2025-05-09_10-45-39,SRR24839060.fa,A1,"NP:ea1, MP:ea1, NS:ea1, PA:ea1, PB1:ea1, PB2:e...","ea1:22-003707-003:NP, ea1:22-003707-003:MP, ea...","99.80%, 99.90%, 99.88%, 99.72%, 99.65%, 99.66%...","3, 1, 1, 6, 8, 5, 6, 4",Ran on FASTA - No Coverage Report,USA-ME
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19042,SRR33830443,WGS,148.11,100597029,PRJNA1102327,SAMN48895429,Viral,39710063,USDA-NVSL,2025,...,SRR33830443,2025-06-06_07-56-21,SRR33830443.fa,B3.13,"NA:ea1, PB1:am4, MP:ea1, PA:ea1, NP:am8, HA:ea...","ea1:22-003707-003:NA, am4:23-001855-001:PB1, e...","98.72%, 99.52%, 98.98%, 98.88%, 98.86%, 98.06%...","18, 11, 10, 24, 17, 33, 38, 9",Ran on FASTA - No Coverage Report,USA
19043,SRR33830444,WGS,148.50,131987248,PRJNA1102327,SAMN48895428,Viral,51617990,USDA-NVSL,2025,...,SRR33830444,2025-06-06_07-56-20,SRR33830444.fa,B3.13,"PA:ea1, NA:ea1, PB2:am2.2, NP:am8, HA:ea1, MP:...","ea1:22-003707-003:PA, ea1:22-003707-003:NA, am...","98.88%, 98.65%, 98.20%, 98.93%, 98.06%, 98.98%...","24, 19, 41, 16, 33, 10, 12, 9",Ran on FASTA - No Coverage Report,USA
19044,SRR33830445,WGS,148.12,115677479,PRJNA1102327,SAMN48895427,Viral,45674405,USDA-NVSL,2025,...,SRR33830445,2025-06-06_07-56-21,SRR33830445.fa,B3.13,"NP:am8, HA:ea1, PA:ea1, NS:am1.1, PB1:am4, PB2...","am8:23-032005-001:NP, ea1:22-003707-003:HA, ea...","98.93%, 98.24%, 98.79%, 98.93%, 99.56%, 98.51%...","16, 30, 26, 9, 10, 34, 19, 11",Ran on FASTA - No Coverage Report,USA
19048,SRR33830449,WGS,131.52,67358891,PRJNA1102327,SAMN48895415,Viral,26336550,USDA-NVSL,2024,...,SRR33830449,2025-06-06_07-56-20,SRR33830449.fa,B3.13,"NP:am8, NA:ea1, PB1:am4, HA:ea1, NS:am1.1, MP:...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","98.93%, 98.86%, 99.47%, 98.43%, 99.17%, 98.95%...","16, 16, 12, 12, 7, 10, 31, 24",Ran on FASTA - No Coverage Report,USA
19049,SRR33830450,WGS,131.13,69602732,PRJNA1102327,SAMN48895414,Viral,27556171,USDA-NVSL,2024,...,SRR33830450,2025-06-06_07-56-20,SRR33830450.fa,B3.13,"HA:ea1, NA:ea1, NP:am8, PB2:am2.2, MP:ea1, PB1...","ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...","98.92%, 98.71%, 99.00%, 98.55%, 98.74%, 99.47%...","11, 12, 15, 33, 12, 12, 8, 23",Ran on FASTA - No Coverage Report,USA

In [6]:
# # If no states

# metadata_genbank = metadata

# metadata_genbank["name_state"] = "USA"

# metadata_genbank["Geo_Location"] = "USA"

# display(metadata_genbank)

## Collection Dates

If date is N/A, try finding it first

In [7]:

# # Get all dates
# metadata["Collection_Date_Specific"] = metadata["BioSample"].apply(lambda x: search_collection_date(x, metadata) if "-" not in x else x)

# # Save this so we don't have to do it again

# # os.chdir(temp_files)
# metadata.to_csv("metadata_genbank.csv")

In [ ]:
os.chdir(temp_files)
metadata = pd.read_csv("metadata_genbank_" + date_range + ".csv")

In [ ]:
# # # Upload saved data -- if doing this, make sure the above cell is commented out
# # os.chdir(temp_files + "saved/")
# # metadata_genbank = pd.read_csv("metadata_genbank.csv")
# # os.chdir(temp_files)

# # Get only updated dates

# # unknown_dates = metadata[(metadata["Collection_Date"] == "2024") | (metadata["Collection_Date"] == "2025")] # Dates we don't have
# years = ["2021", "2022", "2023", "2024", "2025"]
# unknown_dates = metadata[metadata["Collection_Date"].isin(years)]
# # known_dates = metadata[(metadata["Collection_Date"] != "2024") & (metadata["Collection_Date"] != "2025")] # Dates we've already gotten
# known_dates = metadata[~metadata["Collection_Date"].isin(years)]

# # Get new dates also 
# # new_dates = metadata["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank) if )

# updated_unknown_dates = unknown_dates["BioSample"].apply(lambda x: search_collection_date(x, unknown_dates)) # Update unknown dates, if possible
# unknown_dates["Collection_Date"] = updated_unknown_dates

# metadata_genbank = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # Save this so we don't have to do it again

# os.chdir(temp_files)
# metadata.to_csv("metadata_genbank_" + date_range + ".csv")

# display(metadata)

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5913cf137baef0bf7dc&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
16-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c59316506c9211018594&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5963d1722948808c394&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c599c55ff0a00b07fa74&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c59bf822d64931039b4c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c59eda3488d775043d22&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5a012bcb77d5a048860&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
13-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5a4bf68b0848c0f2990&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
13-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5a7a4a75d2e9d0bd696&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5a9c1a9aa1dc008eae0&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
21-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5acb925e703b008ca3e&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5ae8764c85723088292&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
07-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5b120828c2b350790ce&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5b4e57998c1d10c8ffc&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5b79c830237c7068994&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5b9e154f776a70e3760&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5bc4905de1e740f4fb8&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5bfd519fd0af60a7940&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5c116506c9211018596&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
24-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5c45ebc5bd0f0030cdc&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
24-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5c798905f247f09bbd8&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
24-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5ca8d2f8f26f501cc8c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
07-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5cc16d1a1309f0c214c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
24-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5cf1d794cc9480aa9b6&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
24-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5d10493d8df060fb42c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
24-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5d4f4998fc4fb0f1d14&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
24-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5d6d5c8d67b9c081c2c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
24-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5d932976f68620d6f02&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
24-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5dcbe780078d9012ba0&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5deb27cfdd0130f2d72&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5e1716ac9299e0fb114&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5e5c5b58276e8050512&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5e7060926e051068614&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
21-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5ea8aa786d39d03e0cc&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
21-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5ecfd5011ef7408e730&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
21-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5ef595d554dca0be1ca&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
29-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5f284c423c9e30d3dce&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5f4b7521e468b04425e&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5f74c9938050108b0e2&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5f9b3dff109e20b7f0a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5fcd5a0ab91a90ed780&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c5ffd8a4dcaade05a978&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c60222e9c36e8804fcb0&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6041b4f8af2290a5670&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6073c1d6bbb400829c6&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c60a42a6fce0ea07cf68&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c60dc18bddfab60e16d8&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c60f181e38a2760e5420&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
10-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c61245c964f7ff0f1192&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
10-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c615ac9dd8fcfd0b0f62&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
10-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c61738afdf91b305b7f6&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
10-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c61b1af8cbdb10020106&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
10-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c61fe90f4f14ef0ba8be&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c62163cd873db4010a56&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c624097c933a28083ac6&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
29-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c62740432b0beb06c474&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c629371238b1d804d61e&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
29-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c62c4bfbb2a4b10f0e12&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
29-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c62f69c1b1f54206f8c4&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
29-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6317aa5a26849057358&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
29-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c635530769012207b0fc&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
29-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6388f74e584d902b82c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
29-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c63afd9435ddd00f566e&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
29-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c63d953895965b011980&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
29-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c640b2ca4314f20a382c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c643352845b5ed0b8924&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
01-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6462f8e452b950f432c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c649f1567d91900daa04&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
13-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c64c671e3b3b7c074308&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c64f6cec3f98a1022f66&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c651e57998c1d10c8ffe&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c65469c1b1f54206f8c6&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
14-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6560493d8df060fb42e&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
14-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c659e8fc3b7f6c05f6e2&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
14-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c65c6e241f42a3041cd6&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
14-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c65e8b5a4f89e60b91f0&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
14-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c661dbc666eef90173f2&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
14-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6636fe65494bd0915e4&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
16-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6678b8f4e2d1601f3a0&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c66bc2034fc9d60f1f9c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
22-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c66e632c5a7e6302b402&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
22-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c671ac168cef110c6d2c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c67398905f247f09bbde&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c67869cedb27b702c4fe&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c67c3b434584b80ff972&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
03-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c67fe9d28d0c130e7d7a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6827396d890230ac3b2&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
28-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c68426cc9ee5d9053820&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c688c2034fc9d60f1f9e&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c68a38065291a40ab480&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c68da90367a26609faa6&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
02-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c69073f6bbd2da0b2d32&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
08-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6921f88793d810ade4c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
05-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6956d846e4be100fe06&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
20-Mar-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c697d686a2ed3003e22c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
05-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c69a491c5e4ce50c75c0&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
05-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c69c5aef4206f105e84a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
05-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c69f53d693a5a901d06a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
05-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6a2138deff3bb013406&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
05-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6a8b2d729a89706bf7a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
05-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6ab9b2db815e20178aa&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
05-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6aeac7f58b8d406719c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
05-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6b10391963311057a46&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
05-Apr-2024
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6b31b6729108d09bc48&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
05-Apr-2024
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6852c6ba948d9fb70a09c6c6&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_15188\4200550917.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unknown_dates["Collection_Date"] = updated_unknown_dates

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,sample,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,Geo_Location
0,SRR24839058,AMPLICON,230.77,32942716,PRJNA980729,SAMN35647642,Viral,18373327,United States Department of Agriculture,missing,...,SRR24839058,2025-05-09_10-45-20,SRR24839058.fa,A1,"NP:ea1, PB2:ea1, PB1:ea1, MP:ea1, NA:ea1, NS:e...","ea1:22-003707-003:NP, ea1:22-003707-003:PB2, e...","99.87%, 99.80%, 99.91%, 99.90%, 99.79%, 99.88%...","2, 3, 2, 1, 3, 1, 6, 4",Ran on FASTA - No Coverage Report,USA-MA
1,SRR24839058,AMPLICON,230.77,32942716,PRJNA980729,SAMN35647642,Viral,18373327,United States Department of Agriculture,missing,...,SRR24839058,2025-05-09_10-45-20,SRR24839058.fa,A1,"NP:ea1, PB2:ea1, PB1:ea1, MP:ea1, NA:ea1, NS:e...","ea1:22-003707-003:NP, ea1:22-003707-003:PB2, e...","99.87%, 99.80%, 99.91%, 99.90%, 99.79%, 99.88%...","2, 3, 2, 1, 3, 1, 6, 4",Ran on FASTA - No Coverage Report,"USA: Massachusetts, Barnstable County"
2,SRR24839059,AMPLICON,207.54,53993591,PRJNA980729,SAMN35647620,Viral,29609119,United States Department of Agriculture,2022-02-08,...,SRR24839059,2025-05-09_10-45-06,SRR24839059.fa,A1,"NP:ea1, PA:ea1, MP:ea1, NA:ea1, PB1:ea1, PB2:e...","ea1:22-003707-003:NP, ea1:22-003707-003:PA, ea...","100.00%, 100.00%, 99.90%, 99.93%, 99.96%, 100....","0, 0, 1, 1, 1, 0, 1, 0",Ran on FASTA - No Coverage Report,USA-KY
3,SRR24839059,AMPLICON,207.54,53993591,PRJNA980729,SAMN35647620,Viral,29609119,United States Department of Agriculture,2022-02-08,...,SRR24839059,2025-05-09_10-45-06,SRR24839059.fa,A1,"NP:ea1, PA:ea1, MP:ea1, NA:ea1, PB1:ea1, PB2:e...","ea1:22-003707-003:NP, ea1:22-003707-003:PA, ea...","100.00%, 100.00%, 99.90%, 99.93%, 99.96%, 100....","0, 0, 1, 1, 1, 0, 1, 0",Ran on FASTA - No Coverage Report,"USA: Kentucky, Henderson County"
4,SRR24839060,AMPLICON,201.66,21703662,PRJNA980729,SAMN35647621,Viral,10716272,United States Department of Agriculture,2022-02-17,...,SRR24839060,2025-05-09_10-45-39,SRR24839060.fa,A1,"NP:ea1, MP:ea1, NS:ea1, PA:ea1, PB1:ea1, PB2:e...","ea1:22-003707-003:NP, ea1:22-003707-003:MP, ea...","99.80%, 99.90%, 99.88%, 99.72%, 99.65%, 99.66%...","3, 1, 1, 6, 8, 5, 6, 4",Ran on FASTA - No Coverage Report,USA-ME
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19042,SRR33830443,WGS,148.11,100597029,PRJNA1102327,SAMN48895429,Viral,39710063,USDA-NVSL,2025,...,SRR33830443,2025-06-06_07-56-21,SRR33830443.fa,B3.13,"NA:ea1, PB1:am4, MP:ea1, PA:ea1, NP:am8, HA:ea...","ea1:22-003707-003:NA, am4:23-001855-001:PB1, e...","98.72%, 99.52%, 98.98%, 98.88%, 98.86%, 98.06%...","18, 11, 10, 24, 17, 33, 38, 9",Ran on FASTA - No Coverage Report,USA
19043,SRR33830444,WGS,148.50,131987248,PRJNA1102327,SAMN48895428,Viral,51617990,USDA-NVSL,2025,...,SRR33830444,2025-06-06_07-56-20,SRR33830444.fa,B3.13,"PA:ea1, NA:ea1, PB2:am2.2, NP:am8, HA:ea1, MP:...","ea1:22-003707-003:PA, ea1:22-003707-003:NA, am...","98.88%, 98.65%, 98.20%, 98.93%, 98.06%, 98.98%...","24, 19, 41, 16, 33, 10, 12, 9",Ran on FASTA - No Coverage Report,USA
19044,SRR33830445,WGS,148.12,115677479,PRJNA1102327,SAMN48895427,Viral,45674405,USDA-NVSL,2025,...,SRR33830445,2025-06-06_07-56-21,SRR33830445.fa,B3.13,"NP:am8, HA:ea1, PA:ea1, NS:am1.1, PB1:am4, PB2...","am8:23-032005-001:NP, ea1:22-003707-003:HA, ea...","98.93%, 98.24%, 98.79%, 98.93%, 99.56%, 98.51%...","16, 30, 26, 9, 10, 34, 19, 11",Ran on FASTA - No Coverage Report,USA
19048,SRR33830449,WGS,131.52,67358891,PRJNA1102327,SAMN48895415,Viral,26336550,USDA-NVSL,2024,...,SRR33830449,2025-06-06_07-56-20,SRR33830449.fa,B3.13,"NP:am8, NA:ea1, PB1:am4, HA:ea1, NS:am1.1, MP:...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","98.93%, 98.86%, 99.47%, 98.43%, 99.17%, 98.95%...","16, 16, 12, 12, 7, 10, 31, 24",Ran on FASTA - No Coverage Report,USA
19049,SRR33830450,WGS,131.13,69602732,PRJNA1102327,SAMN48895414,Viral,27556171,USDA-NVSL,2024,...,SRR33830450,2025-06-06_07-56-20,SRR33830450.fa,B3.13,"HA:ea1, NA:ea1, NP:am8, PB2:am2.2, MP:ea1, PB1...","ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...","98.92%, 98.71%, 99.00%, 98.55%, 98.74%, 99.47%...","11, 12, 15, 33, 12, 12, 8, 23",Ran on FASTA - No Coverage Report,USA

In [ ]:


# os.chdir(temp_files)
# metadata_genbank.to_csv("metadata_genbank_" + date_range + ".csv")

# metadata = metadata_genbank 

# display(metadata)

# If no collection dates

# metadata_genbank["Collection_Date_Specific"] = metadata_genbank["Collection_Date"]

,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSample Accession,BioSampleModel,Bytes,Center Name,Collection_Date,...,is_retracted,isolate,isolation_source,name_state,retraction_detection_date_utc,sample,serotype,version,Host_Type,years
0,AMPLICON,230.77,32942716,PRJNA980729,SAMN35647642,SRS17903639,Viral,18373327,United States Department of Agriculture,missing,...,False,A/Canada Goose/Massachusetts/22-005893-001/2022,",",Massachusetts,NaN,SRR24839058,H5N1,1,other,missing
1,AMPLICON,230.77,32942716,PRJNA980729,SAMN35647642,SRS17903639,Viral,18373327,United States Department of Agriculture,missing,...,False,A/Canada Goose/Massachusetts/22-005893-001/2022,"Swab, Tracheal","USA: Massachusetts, Barnstable County",NaN,SRR24839058,H5N1,1,avian,missing
2,AMPLICON,207.54,53993591,PRJNA980729,SAMN35647620,SRS17903636,Viral,29609119,United States Department of Agriculture,2022-02-08,...,False,A/Gadwall/Kentucky/22-005154-004/2022,",/",Kentucky,NaN,SRR24839059,H5N1,1,other,2022
3,AMPLICON,207.54,53993591,PRJNA980729,SAMN35647620,SRS17903636,Viral,29609119,United States Department of Agriculture,2022-02-08,...,False,A/Gadwall/Kentucky/22-005154-004/2022,"Swab Pool, Cloacal/Oropharyngeal","USA: Kentucky, Henderson County",NaN,SRR24839059,H5N1,1,avian,2022
4,AMPLICON,201.66,21703662,PRJNA980729,SAMN35647621,SRS17903631,Viral,10716272,United States Department of Agriculture,2022-02-17,...,False,A/Backyard bird/Maine/22-005158-001/2022,NaN,Maine,NaN,SRR24839060,H5N1,1,other,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18077,WGS,148.11,100597029,PRJNA1102327,SAMN48895429,SRS25266467,Viral,39710063,USDA-NVSL,2025,...,False,25-015681-003,"MILK, BULK TANK",USA,NaN,SRR33830443,NaN,1,cattle,2025
18078,WGS,148.50,131987248,PRJNA1102327,SAMN48895428,SRS25266466,Viral,51617990,USDA-NVSL,2025,...,False,25-015681-002,"MILK, BULK TANK",USA,NaN,SRR33830444,NaN,1,cattle,2025
18079,WGS,148.12,115677479,PRJNA1102327,SAMN48895427,SRS25266465,Viral,45674405,USDA-NVSL,2025,...,False,25-015681-001,"MILK, BULK TANK",USA,NaN,SRR33830445,NaN,1,cattle,2025
18080,WGS,131.52,67358891,PRJNA1102327,SAMN48895415,SRS25266461,Viral,26336550,USDA-NVSL,2024,...,False,24-036379-001-tile,"MILK, BULK TANK",USA,NaN,SRR33830449,NaN,1,cattle,2024
18081,WGS,131.13,69602732,PRJNA1102327,SAMN48895414,SRS25266460,Viral,27556171,USDA-NVSL,2024,...,False,24-034788-001-tile,"MILK, BULK TANK",USA,NaN,SRR33830450,NaN,1,cattle,2024

## Get host type

In [15]:
# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

os.chdir(downloads)

animals_ref = pd.read_csv("animals_ref.csv") # Upload animals ref

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['house-mouse', 'western gull', 'goat', 'rough-legged hawk', "cooper's hawk", 'corvus sp.', 'sanderling', 'guinea', 'sparrow', 'falcon', 'aves sp.', 'cattle milk product', 'anser sp.', 'ganada goose', 'partridge', 'snowy owl', 'dunlin', 'buteo jamaicensis', 'american wigeon', 'american black duck', 'grackle', 'mute swan', 'northern shoveler', 'strigiformes sp.', 'gallus gallus', 'anas rubripes', 'chukar', 'black-crowned night-heron', 'mareca strepera', 'common grackle', 'pelecanus erythrorhynchos', 'corvidae sp.', 'cackling goose', "geoffroy's cat", 'anser albifrons', 'black scoter', 'skunk', 'american crow', 'common merganser', 'dolphin', 'american coot', 'thalasseus maximus', 'cougar', 'antigone canadensis', 'melegris gallopavo', 'scoter', 'accipitridae sp.', 'great egret', 'american robin', 'coragyps atratus', 'brandt goose', 'mareca americana', 'barn owl', 'guinea fowl', 'lesser scaup', 'swallow', 'chicken', 'callipepla sp.', 'avian', 'larus argentatus', 'gavia immer', 'great black-backed gull', 'anas acuta', 'ermine', 'cat', 'anas platyrhynchos', 'common raven', 'calidris alba', 'anser anser', 'cairina moschata', 'dove', 'barred owl', 'comon goldeneye', 'white-faced ibis', 'dark-eyed junco', 'haliaeetus leucocephalus', 'aythya affinis', 'blue-winged teal', '--', 'red-tailed hawk', 'blue jay', 'sibirionetta formosa', 'black vulture', 'red fox', 'common loon', 'western kingbird', 'gull', 'blackbird', 'brown pelican', 'snow goose', 'peregrine', 'spatula discors', 'feline', 'pefa', 'sand crane', 'anser rossii', 'greater scaup', 'deer mouse', 'common eider', 'phasianidae sp.', 'corvus corax', 'tiger', 'peafowl', 'gadwall', 'red-shouldered hawk', 'ruddy duck', "swanson's hawk", 'duck', 'wood duck', 'western sandpiper', 'aix sponsa', 'branta canadensis', 'meleagris gallopavo', 'pelecanidae sp.', 'house sparrow', "bonaparte's gull", 'merganser', 'bucephala clangula', 'mallard x american black duck hybrid', 'falco peregrinus', 'owl', 'bufflehead', 'accipiter cooperii', 'anser caerulescens', 'pelecanus occidentalis', 'white-winged scoter', 'trumpeter swan', 'mountain lion', 'bobcat', 'mink', 'cago', 'laridae sp.', 'savannah cat', 'aythya collaris', 'norway rat', 'buteo lineatus', 'great blue heron', 'bubo scandiacus', 'harbor seal', 'fox', 'strix varia', 'mallard', 'numididae sp.', 'serval', 'phalacrocoracidae sp.', 'black billed magpie', 'larus delawarensis', 'domestic cat', 'guineafowl', 'white-winged dove', 'spatula clypeata', 'corvus brachyrhynchos', 'hooded merganser', 'turkey', 'pelican', 'rock pigeon', 'hawk', 'harris hawk', 'phasianus colchicus', 'alpaca', 'pet food', 'lynx', 'cygnus atratus', 'european starling', 'pig', 'cattle', 'corvus ossifragus', 'eurasian collared dove', 'crested caracara', 'house mouse', 'swan', 'surf scoter', 'aythya americana', 'red tailed hawk', 'emu', 'common goldeneye', 'double-crested cormorant', 'pheasant', 'heron', 'crow', 'northern pintail', '-', 'bubo virginianus', 'ring-billed gull', 'lophodytes cucullatus', 'sharp-shinned hawk', 'comon-grackle', 'accipiter striatus', 'flamingo', 'cathartidae sp.', "ross's goose", 'herring gull', "'", 'goose', 'cygnus sp.', 'rock goose', 'cathartes aura', 'green-winged teal', 'american woodcock', 'pigeon', 'weasel', 'tundra swan', 'lion', 'sandhill crane', 'anas crecca', 'great black-backed gulll', 'bottlenose dolphin', 'quail', 'snowy egret', 'mergus merganser', 'vulture', 'glaucous gull', 'cygnus columbianus', 'bald eagle', 'red-breasted merganser', 'canada goose', nan, 'cygnus olor', '.', 'anas sp.', 'turkey vulture', 'osprey', 'wild turkey', 'cygnus buccinator', 'domestic-cat', 'ardea herodias', 'great horned owl', 'raw pet food', 'bear', 'crane', 'northern harrier', 'raccoon', 'burrowing owl']
[nan]
                  avian               cattle        feline   other_mammal  \
0      great_horned_owl            dairy_cow           cat     deer mouse
1          common_raven               cattle  domestic_cat    house_mouse
2         cooper's_hawk  cattle milk product     feral_cat          skunk
3          coopers_hawk          bovine_milk        feline  striped_skunk
4               peafowl              bovine   domestic-cat     norway rat
..                  ...                  ...           ...            ...
515  cygnus columbianus                  NaN           NaN            NaN
516            anas sp.                  NaN           NaN            NaN
517         wild turkey                  NaN           NaN            NaN
518   cygnus buccinator                  NaN           NaN            NaN
519    northern harrier                  NaN           NaN            NaN

          human         other  new
0    washington         mixed  NaN
1        nevada   environment  NaN
2       wyoming  multispecies  NaN
3    california       unknown  NaN
4      michigan             -  NaN
..          ...           ...  ...
515         NaN           NaN  NaN
516         NaN           NaN  NaN
517         NaN           NaN  NaN
518         NaN           NaN  NaN
519         NaN           NaN  NaN

[520 rows x 7 columns]

In [16]:
# Get animals from animal reference
os.chdir(downloads)
animals_ref = pd.read_csv("animals_ref.csv")
fix_animals_andersen(metadata, animals_ref) # Get host type

metadata["years"] = metadata["Collection_Date"].apply(lambda x: str(x).split("-")[0]) # Get year only from collection date

## Make names using all the attributes we collected

In [18]:
for num, collection_date in enumerate(metadata["Collection_Date"]):
    
    if collection_date != collection_date: # If nan
        metadata.loc[num, "Collection_Date"] = metadata.loc[num, "years"]
    else: # If actual date
        if len(str(collection_date)) == 4: # If it's a year
            # print("caught")
            metadata.loc[num, "Collection_Date"] = collection_date
        else:
            try:
                parsed_date = dateutil.parser.parse(collection_date)
                date = parsed_date.strftime("%Y-%m-%d") # Make sure it doesn't default to today, if just a year
                metadata.loc[num, "Collection_Date"] = date
            except: # If no date at all
                metadata.loc[num, "Collection_Date"] = collection_date

    metadata = metadata.dropna(thresh=2)

# Make names

# + metadata["BioSample"] + "|" 
names = ">" + metadata["Run"] + "|" + "A/" + metadata["Host"] + "/" + metadata["name_state"] + "/" + metadata["isolate"] + "/" + metadata["years"].apply(lambda x: str(x)) + "|H5N1|" + metadata["Geo_Location"] + "|" + metadata["Collection_Date"].apply(lambda x: str(x)) + "|" + metadata["Host_Type"] + "|" + metadata["Genotype"]

metadata["Name"] = names

# metadata_genbank.to_csv("metadata_genbank_named.csv")

display(metadata[["ReleaseDate", 'create_date', 'Collection_Date']])

      ReleaseDate          create_date Collection_Date
0      2023-06-30  2023-06-07 02:01:47         missing
1      2023-06-30  2023-06-07 02:01:47         missing
2      2023-06-30  2023-06-07 02:01:22      2022-02-08
3      2023-06-30  2023-06-07 02:01:22      2022-02-08
4      2023-06-30  2023-06-07 02:01:28      2022-02-17
...           ...                  ...             ...
18077  2025-06-06  2025-06-04 14:25:00            2025
18078  2025-06-06  2025-06-04 14:25:01            2025
18079  2025-06-06  2025-06-04 14:24:54            2025
18080  2025-06-06  2025-06-04 14:24:53            2024
18081  2025-06-06  2025-06-04 14:24:53            2024

[18082 rows x 3 columns]

In [19]:
# Drop duplicate runs 
metadata = metadata.drop_duplicates(subset="Run", keep="first")

In [20]:
print(metadata)

      Assay Type  AvgSpotLen      Bases    BioProject     BioSample  \
0       AMPLICON      230.77   32942716   PRJNA980729  SAMN35647642
2       AMPLICON      207.54   53993591   PRJNA980729  SAMN35647620
4       AMPLICON      201.66   21703662   PRJNA980729  SAMN35647621
6       AMPLICON      209.57   46055893   PRJNA980729  SAMN35647622
8       AMPLICON      237.36   26794193   PRJNA980729  SAMN35647623
...          ...         ...        ...           ...           ...
18077        WGS      148.11  100597029  PRJNA1102327  SAMN48895429
18078        WGS      148.50  131987248  PRJNA1102327  SAMN48895428
18079        WGS      148.12  115677479  PRJNA1102327  SAMN48895427
18080        WGS      131.52   67358891  PRJNA1102327  SAMN48895415
18081        WGS      131.13   69602732  PRJNA1102327  SAMN48895414

      BioSample Accession BioSampleModel     Bytes  \
0             SRS17903639          Viral  18373327
2             SRS17903636          Viral  29609119
4             SRS17903631          Viral  10716272
6             SRS17903632          Viral  23524044
8             SRS17903627          Viral  16149521
...                   ...            ...       ...
18077         SRS25266467          Viral  39710063
18078         SRS25266466          Viral  51617990
18079         SRS25266465          Viral  45674405
18080         SRS25266461          Viral  26336550
18081         SRS25266460          Viral  27556171

                                   Center Name Collection_Date  ...  \
0      United States Department of Agriculture         missing  ...
2      United States Department of Agriculture      2022-02-08  ...
4      United States Department of Agriculture      2022-02-17  ...
6      United States Department of Agriculture      2022-02-21  ...
8      United States Department of Agriculture      2022-02-16  ...
...                                        ...             ...  ...
18077                                USDA-NVSL            2025  ...
18078                                USDA-NVSL            2025  ...
18079                                USDA-NVSL            2025  ...
18080                                USDA-NVSL            2024  ...
18081                                USDA-NVSL            2024  ...

                                               isolate isolation_source  \
0      A/Canada Goose/Massachusetts/22-005893-001/2022                ,
2                A/Gadwall/Kentucky/22-005154-004/2022               ,/
4             A/Backyard bird/Maine/22-005158-001/2022              NaN
6                A/Chicken/Delaware/22-005260-001/2022                ,
8                  A/Turkey/Indiana/22-005289-001/2022                ,
...                                                ...              ...
18077                                    25-015681-003  MILK, BULK TANK
18078                                    25-015681-002  MILK, BULK TANK
18079                                    25-015681-001  MILK, BULK TANK
18080                               24-036379-001-tile  MILK, BULK TANK
18081                               24-034788-001-tile  MILK, BULK TANK

          name_state retraction_detection_date_utc       sample serotype  \
0      Massachusetts                           NaN  SRR24839058     H5N1
2           Kentucky                           NaN  SRR24839059     H5N1
4              Maine                           NaN  SRR24839060     H5N1
6           Delaware                           NaN  SRR24839061     H5N1
8            Indiana                           NaN  SRR24839062     H5N1
...              ...                           ...          ...      ...
18077            USA                           NaN  SRR33830443      NaN
18078            USA                           NaN  SRR33830444      NaN
18079            USA                           NaN  SRR33830445      NaN
18080            USA                           NaN  SRR33830449      NaN
18081            USA                           NaN  SRR33830450      NaN

      version Host_Type    years  \
0           1     other  missing
2           1     other     2022
4           1     other     2022
6           1     other     2022
8           1     other     2022
...       ...       ...      ...
18077       1    cattle     2025
18078       1    cattle     2025
18079       1    cattle     2025
18080       1    cattle     2024
18081       1    cattle     2024

                                                    Name
0                                                    NaN
2                                                    NaN
4                                                    NaN
6                                                    NaN
8                                                    NaN
...                                                  ...
18077  >SRR33830443|A/CATTLE/USA/25-015681-003/2025|H...
18078  >SRR33830444|A/CATTLE/USA/25-015681-002/2025|H...
18079  >SRR33830445|A/CATTLE/USA/25-015681-001/2025|H...
18080  >SRR33830449|A/CATTLE/USA/24-036379-001-tile/2...
18081  >SRR33830450|A/CATTLE/USA/24-034788-001-tile/2...

[9203 rows x 51 columns]

## Make FASTA files

In [21]:
# Get information to create the fasta files

fasta_folder = originals + "avian-influenza/fasta/"

os.chdir(fasta_folder)

segments = ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]
pairs = []
fasta_files = {}

for genotype in genotypes: # ["B3.13", "D1.1"]:
    for segment in segments:
        pair = genotype + "_" + segment
        pairs.append(pair)

for pair in pairs:
    fasta_files[pair] = [] # List to hold fasta files

for run in metadata["Run"].values: # For each run 
    for dirpath, dirs, files in os.walk(fasta_folder): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            # print(file_name)
            if run in file_name: # Note that there will be ~8 files total with that run name
                # Make a fasta file and put it in the list
                with open(file_name) as f:
                    lines = f.readlines()
                    sequence = lines[1] 
                    # Each run/segment pair has one sequence -- it's placed into a file with other run/segment pairs with the same segment and genotype
                    header = metadata[metadata["Run"] == run].loc[:, "Name"].values[0]
                    genotype = metadata[metadata["Run"] == run].loc[:, "Genotype"].values[0]
                    # print(header)
                    # print(genotype)
                    # break 
                    segment = file_name.split("_")[-2]
                    # Find the pair that corresponds to 
                    pair_name = genotype + "_" + segment
                    this_specific_fasta = []
                    for pair in pairs:
                        # print(pair)
                        # print(pair_name)
                        if pair_name == pair:
                            this_specific_fasta.append(header)
                            this_specific_fasta.append(sequence)
                            fasta_files[pair].append(this_specific_fasta)
                f.close()
        break

In [ ]:
# print(fasta_files.keys())

In [22]:
# Create fasta files 

# os.chdir(complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/")
os.chdir(originals + "complete/")
names = []
for pair in fasta_files.keys():
    # output_path = complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/" + pair + "_andersen_updated_" + update_date + ".fasta" 
    output_path = originals + "complete/" + pair + "_" + date_range + "_andersen_updated.fasta"

    output_file = open(output_path, "w")
    for item in fasta_files[pair]:
        # for item in item:
        # item = fasta_files[pair]
        try:
            name = str(item[0].values[0]) # See if this is one we didn't have a collection date for
        except:
            name = str(item[0])
        print(name)
        names.append(name)
        # First is header, second is sequence
        # print(value)
        output_file.write(name + "\n")
        output_file.write(item[1])
    output_file.close()

print(len(names)/8)

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839171|A/./Massachusetts/A/Backyard bird/Massachusetts/22-009371-001/2022/2022|H5N1|USA-MA|2022-03-25|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839298|A/./Nebraska/A/Swan/Nebraska/22-008227-001/2022/2022|H5N1|USA-NE|2022-03-13|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839316|A/./Kansas/A/Backyard bird/Kansas/22-008114-001/2022/2022|H5N1|USA-KS|2022-03-16|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839413|A/./Texas/A/Pheasant/Texas/22-010008-002/2022/2022|H5N1|USA-TX|2022-04-01|other|A1
nan
nan
>SRR24839416|A/./Texas/A/Pheasant/Texas/22-010008-001/2022/2022|H5N1|USA-TX|2022-04-01|other|A1
nan
nan
>SRR24839423|A/./Texas/A/Pheasant/Texas/22-009984-001/2022/2022|H5N1|USA-TX|2022-03-29|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839442|A/./Florida/A/Black Vulture/Florida/22-009936-001/2022/2022|H5N1|USA-FL|2022-03-27|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839476|A/./Maine/A/Backyard bird/Maine/22-009412-002/2022/2022|H5N1|USA-ME|2022-03-25|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839501|A/./Illinois/A/Graylag Goose/Illinois/22-008377-005/2022/2022|H5N1|USA-IL|2022-03-14|other|A1
>SRR24839502|A/./Illinois/A/Graylag Goose/Illinois/22-008377-002/2022/2022|H5N1|USA-IL|2022-03-14|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839551|A/./New York/A/Backyard bird/New York/22-009324-009/2022/2022|H5N1|USA-NY|2022-03-28|other|A1
nan
>SRR24839558|A/./Nebraska/A/Backyard bird/Nebraska/22-009190-001/2022/2022|H5N1|USA-NE|2022-03-24|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839628|A/./Florida/A/Gull/Florida/22-007915-006/2022/2022|H5N1|USA-FL|2022-03-01|other|A1
nan
nan
nan
nan
nan
nan
nan
>SRR24839652|A/./Illinois/A/Guineafowl/Illinois/22-007382-001/2022/2022|H5N1|USA-IL|2022-03-09|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839724|A/./New York/A/Backyard bird/New York/22-005647-001/2022/2022|H5N1|USA-NY|2022-02-19|other|A1
>SRR24839725|A/./New York/A/Backyard bird/New York/22-005647-002/2022/2022|H5N1|USA-NY|2022-02-19|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843008|A/./Missouri/A/Pelican/Missouri/22-012338-019/2022/missing|H5N1|USA-MO|missing|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843106|A/./Texas/A/Owl/Texas/22-012996-001/2022/2022|H5N1|USA-TX|2022-04-27|other|A1
nan
nan
>SRR24843142|A/./Missouri/A/Goose/Missouri/22-012338-006/2022/2022|H5N1|USA-MO|2022-03-15|other|A1
nan
>SRR24843264|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-004/2022/2022|H5N1|USA-PA|2022-04-28|other|A1
>SRR24843265|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-003/2022/2022|H5N1|USA-PA|2022-04-28|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839171|A/./Massachusetts/A/Backyard bird/Massachusetts/22-009371-001/2022/2022|H5N1|USA-MA|2022-03-25|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839298|A/./Nebraska/A/Swan/Nebraska/22-008227-001/2022/2022|H5N1|USA-NE|2022-03-13|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839316|A/./Kansas/A/Backyard bird/Kansas/22-008114-001/2022/2022|H5N1|USA-KS|2022-03-16|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839413|A/./Texas/A/Pheasant/Texas/22-010008-002/2022/2022|H5N1|USA-TX|2022-04-01|other|A1
nan
nan
>SRR24839416|A/./Texas/A/Pheasant/Texas/22-010008-001/2022/2022|H5N1|USA-TX|2022-04-01|other|A1
nan
nan
>SRR24839423|A/./Texas/A/Pheasant/Texas/22-009984-001/2022/2022|H5N1|USA-TX|2022-03-29|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839442|A/./Florida/A/Black Vulture/Florida/22-009936-001/2022/2022|H5N1|USA-FL|2022-03-27|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839476|A/./Maine/A/Backyard bird/Maine/22-009412-002/2022/2022|H5N1|USA-ME|2022-03-25|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839501|A/./Illinois/A/Graylag Goose/Illinois/22-008377-005/2022/2022|H5N1|USA-IL|2022-03-14|other|A1
>SRR24839502|A/./Illinois/A/Graylag Goose/Illinois/22-008377-002/2022/2022|H5N1|USA-IL|2022-03-14|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839551|A/./New York/A/Backyard bird/New York/22-009324-009/2022/2022|H5N1|USA-NY|2022-03-28|other|A1
nan
>SRR24839558|A/./Nebraska/A/Backyard bird/Nebraska/22-009190-001/2022/2022|H5N1|USA-NE|2022-03-24|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839628|A/./Florida/A/Gull/Florida/22-007915-006/2022/2022|H5N1|USA-FL|2022-03-01|other|A1
nan
nan
nan
nan
nan
nan
nan
>SRR24839652|A/./Illinois/A/Guineafowl/Illinois/22-007382-001/2022/2022|H5N1|USA-IL|2022-03-09|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839724|A/./New York/A/Backyard bird/New York/22-005647-001/2022/2022|H5N1|USA-NY|2022-02-19|other|A1
>SRR24839725|A/./New York/A/Backyard bird/New York/22-005647-002/2022/2022|H5N1|USA-NY|2022-02-19|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843008|A/./Missouri/A/Pelican/Missouri/22-012338-019/2022/missing|H5N1|USA-MO|missing|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843106|A/./Texas/A/Owl/Texas/22-012996-001/2022/2022|H5N1|USA-TX|2022-04-27|other|A1
nan
nan
>SRR24843142|A/./Missouri/A/Goose/Missouri/22-012338-006/2022/2022|H5N1|USA-MO|2022-03-15|other|A1
nan
>SRR24843264|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-004/2022/2022|H5N1|USA-PA|2022-04-28|other|A1
>SRR24843265|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-003/2022/2022|H5N1|USA-PA|2022-04-28|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839171|A/./Massachusetts/A/Backyard bird/Massachusetts/22-009371-001/2022/2022|H5N1|USA-MA|2022-03-25|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839298|A/./Nebraska/A/Swan/Nebraska/22-008227-001/2022/2022|H5N1|USA-NE|2022-03-13|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839316|A/./Kansas/A/Backyard bird/Kansas/22-008114-001/2022/2022|H5N1|USA-KS|2022-03-16|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839413|A/./Texas/A/Pheasant/Texas/22-010008-002/2022/2022|H5N1|USA-TX|2022-04-01|other|A1
nan
nan
>SRR24839416|A/./Texas/A/Pheasant/Texas/22-010008-001/2022/2022|H5N1|USA-TX|2022-04-01|other|A1
nan
nan
>SRR24839423|A/./Texas/A/Pheasant/Texas/22-009984-001/2022/2022|H5N1|USA-TX|2022-03-29|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839442|A/./Florida/A/Black Vulture/Florida/22-009936-001/2022/2022|H5N1|USA-FL|2022-03-27|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839476|A/./Maine/A/Backyard bird/Maine/22-009412-002/2022/2022|H5N1|USA-ME|2022-03-25|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839501|A/./Illinois/A/Graylag Goose/Illinois/22-008377-005/2022/2022|H5N1|USA-IL|2022-03-14|other|A1
>SRR24839502|A/./Illinois/A/Graylag Goose/Illinois/22-008377-002/2022/2022|H5N1|USA-IL|2022-03-14|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839551|A/./New York/A/Backyard bird/New York/22-009324-009/2022/2022|H5N1|USA-NY|2022-03-28|other|A1
nan
>SRR24839558|A/./Nebraska/A/Backyard bird/Nebraska/22-009190-001/2022/2022|H5N1|USA-NE|2022-03-24|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839628|A/./Florida/A/Gull/Florida/22-007915-006/2022/2022|H5N1|USA-FL|2022-03-01|other|A1
nan
nan
nan
nan
nan
nan
nan
>SRR24839652|A/./Illinois/A/Guineafowl/Illinois/22-007382-001/2022/2022|H5N1|USA-IL|2022-03-09|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839724|A/./New York/A/Backyard bird/New York/22-005647-001/2022/2022|H5N1|USA-NY|2022-02-19|other|A1
>SRR24839725|A/./New York/A/Backyard bird/New York/22-005647-002/2022/2022|H5N1|USA-NY|2022-02-19|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843008|A/./Missouri/A/Pelican/Missouri/22-012338-019/2022/missing|H5N1|USA-MO|missing|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843106|A/./Texas/A/Owl/Texas/22-012996-001/2022/2022|H5N1|USA-TX|2022-04-27|other|A1
nan
nan
>SRR24843142|A/./Missouri/A/Goose/Missouri/22-012338-006/2022/2022|H5N1|USA-MO|2022-03-15|other|A1
nan
>SRR24843264|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-004/2022/2022|H5N1|USA-PA|2022-04-28|other|A1
>SRR24843265|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-003/2022/2022|H5N1|USA-PA|2022-04-28|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839171|A/./Massachusetts/A/Backyard bird/Massachusetts/22-009371-001/2022/2022|H5N1|USA-MA|2022-03-25|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839298|A/./Nebraska/A/Swan/Nebraska/22-008227-001/2022/2022|H5N1|USA-NE|2022-03-13|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839316|A/./Kansas/A/Backyard bird/Kansas/22-008114-001/2022/2022|H5N1|USA-KS|2022-03-16|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839413|A/./Texas/A/Pheasant/Texas/22-010008-002/2022/2022|H5N1|USA-TX|2022-04-01|other|A1
nan
nan
>SRR24839416|A/./Texas/A/Pheasant/Texas/22-010008-001/2022/2022|H5N1|USA-TX|2022-04-01|other|A1
nan
nan
>SRR24839423|A/./Texas/A/Pheasant/Texas/22-009984-001/2022/2022|H5N1|USA-TX|2022-03-29|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839442|A/./Florida/A/Black Vulture/Florida/22-009936-001/2022/2022|H5N1|USA-FL|2022-03-27|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839476|A/./Maine/A/Backyard bird/Maine/22-009412-002/2022/2022|H5N1|USA-ME|2022-03-25|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839501|A/./Illinois/A/Graylag Goose/Illinois/22-008377-005/2022/2022|H5N1|USA-IL|2022-03-14|other|A1
>SRR24839502|A/./Illinois/A/Graylag Goose/Illinois/22-008377-002/2022/2022|H5N1|USA-IL|2022-03-14|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839551|A/./New York/A/Backyard bird/New York/22-009324-009/2022/2022|H5N1|USA-NY|2022-03-28|other|A1
nan
>SRR24839558|A/./Nebraska/A/Backyard bird/Nebraska/22-009190-001/2022/2022|H5N1|USA-NE|2022-03-24|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839628|A/./Florida/A/Gull/Florida/22-007915-006/2022/2022|H5N1|USA-FL|2022-03-01|other|A1
nan
nan
nan
nan
nan
nan
nan
>SRR24839652|A/./Illinois/A/Guineafowl/Illinois/22-007382-001/2022/2022|H5N1|USA-IL|2022-03-09|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839724|A/./New York/A/Backyard bird/New York/22-005647-001/2022/2022|H5N1|USA-NY|2022-02-19|other|A1
>SRR24839725|A/./New York/A/Backyard bird/New York/22-005647-002/2022/2022|H5N1|USA-NY|2022-02-19|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843008|A/./Missouri/A/Pelican/Missouri/22-012338-019/2022/missing|H5N1|USA-MO|missing|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843106|A/./Texas/A/Owl/Texas/22-012996-001/2022/2022|H5N1|USA-TX|2022-04-27|other|A1
nan
nan
>SRR24843142|A/./Missouri/A/Goose/Missouri/22-012338-006/2022/2022|H5N1|USA-MO|2022-03-15|other|A1
nan
>SRR24843264|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-004/2022/2022|H5N1|USA-PA|2022-04-28|other|A1
>SRR24843265|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-003/2022/2022|H5N1|USA-PA|2022-04-28|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839171|A/./Massachusetts/A/Backyard bird/Massachusetts/22-009371-001/2022/2022|H5N1|USA-MA|2022-03-25|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839298|A/./Nebraska/A/Swan/Nebraska/22-008227-001/2022/2022|H5N1|USA-NE|2022-03-13|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839316|A/./Kansas/A/Backyard bird/Kansas/22-008114-001/2022/2022|H5N1|USA-KS|2022-03-16|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839413|A/./Texas/A/Pheasant/Texas/22-010008-002/2022/2022|H5N1|USA-TX|2022-04-01|other|A1
nan
nan
>SRR24839416|A/./Texas/A/Pheasant/Texas/22-010008-001/2022/2022|H5N1|USA-TX|2022-04-01|other|A1
nan
nan
>SRR24839423|A/./Texas/A/Pheasant/Texas/22-009984-001/2022/2022|H5N1|USA-TX|2022-03-29|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839442|A/./Florida/A/Black Vulture/Florida/22-009936-001/2022/2022|H5N1|USA-FL|2022-03-27|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839476|A/./Maine/A/Backyard bird/Maine/22-009412-002/2022/2022|H5N1|USA-ME|2022-03-25|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839501|A/./Illinois/A/Graylag Goose/Illinois/22-008377-005/2022/2022|H5N1|USA-IL|2022-03-14|other|A1
>SRR24839502|A/./Illinois/A/Graylag Goose/Illinois/22-008377-002/2022/2022|H5N1|USA-IL|2022-03-14|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839551|A/./New York/A/Backyard bird/New York/22-009324-009/2022/2022|H5N1|USA-NY|2022-03-28|other|A1
nan
>SRR24839558|A/./Nebraska/A/Backyard bird/Nebraska/22-009190-001/2022/2022|H5N1|USA-NE|2022-03-24|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839628|A/./Florida/A/Gull/Florida/22-007915-006/2022/2022|H5N1|USA-FL|2022-03-01|other|A1
nan
nan
nan
nan
nan
nan
nan
>SRR24839652|A/./Illinois/A/Guineafowl/Illinois/22-007382-001/2022/2022|H5N1|USA-IL|2022-03-09|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839724|A/./New York/A/Backyard bird/New York/22-005647-001/2022/2022|H5N1|USA-NY|2022-02-19|other|A1
>SRR24839725|A/./New York/A/Backyard bird/New York/22-005647-002/2022/2022|H5N1|USA-NY|2022-02-19|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843008|A/./Missouri/A/Pelican/Missouri/22-012338-019/2022/missing|H5N1|USA-MO|missing|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843106|A/./Texas/A/Owl/Texas/22-012996-001/2022/2022|H5N1|USA-TX|2022-04-27|other|A1
nan
nan
>SRR24843142|A/./Missouri/A/Goose/Missouri/22-012338-006/2022/2022|H5N1|USA-MO|2022-03-15|other|A1
nan
>SRR24843264|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-004/2022/2022|H5N1|USA-PA|2022-04-28|other|A1
>SRR24843265|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-003/2022/2022|H5N1|USA-PA|2022-04-28|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839171|A/./Massachusetts/A/Backyard bird/Massachusetts/22-009371-001/2022/2022|H5N1|USA-MA|2022-03-25|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839298|A/./Nebraska/A/Swan/Nebraska/22-008227-001/2022/2022|H5N1|USA-NE|2022-03-13|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839316|A/./Kansas/A/Backyard bird/Kansas/22-008114-001/2022/2022|H5N1|USA-KS|2022-03-16|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839413|A/./Texas/A/Pheasant/Texas/22-010008-002/2022/2022|H5N1|USA-TX|2022-04-01|other|A1
nan
nan
>SRR24839416|A/./Texas/A/Pheasant/Texas/22-010008-001/2022/2022|H5N1|USA-TX|2022-04-01|other|A1
nan
nan
>SRR24839423|A/./Texas/A/Pheasant/Texas/22-009984-001/2022/2022|H5N1|USA-TX|2022-03-29|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839442|A/./Florida/A/Black Vulture/Florida/22-009936-001/2022/2022|H5N1|USA-FL|2022-03-27|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839476|A/./Maine/A/Backyard bird/Maine/22-009412-002/2022/2022|H5N1|USA-ME|2022-03-25|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839501|A/./Illinois/A/Graylag Goose/Illinois/22-008377-005/2022/2022|H5N1|USA-IL|2022-03-14|other|A1
>SRR24839502|A/./Illinois/A/Graylag Goose/Illinois/22-008377-002/2022/2022|H5N1|USA-IL|2022-03-14|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839551|A/./New York/A/Backyard bird/New York/22-009324-009/2022/2022|H5N1|USA-NY|2022-03-28|other|A1
nan
>SRR24839558|A/./Nebraska/A/Backyard bird/Nebraska/22-009190-001/2022/2022|H5N1|USA-NE|2022-03-24|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839628|A/./Florida/A/Gull/Florida/22-007915-006/2022/2022|H5N1|USA-FL|2022-03-01|other|A1
nan
nan
nan
nan
nan
nan
nan
>SRR24839652|A/./Illinois/A/Guineafowl/Illinois/22-007382-001/2022/2022|H5N1|USA-IL|2022-03-09|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839724|A/./New York/A/Backyard bird/New York/22-005647-001/2022/2022|H5N1|USA-NY|2022-02-19|other|A1
>SRR24839725|A/./New York/A/Backyard bird/New York/22-005647-002/2022/2022|H5N1|USA-NY|2022-02-19|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

## De-Duplication

In [ ]:
# De-duplication 

# Gisaid 
dfs_gisaid_list = []
for genotype in genotypes:

    # gisaid = downloads + "GISAID/complete/" + genotype.replace(".", "_") + "/" + date_range + "_" + genotype.replace(".", "_") + "_Antarctica_North_America_South_America/"
    gisaid = downloads + "GISAID/complete/all_genotypes/11-01-2021--06-13-2025_all_genotypes_Antarctica_North_America_South_America/"
    # gisaid = downloads + "Cats/Datasets/GISAID/"

    os.chdir(gisaid)

    dfs_gisaid = create_dataframes(gisaid)
    dfs_gisaid_list.append(dfs_gisaid)

dfs_gisaid = {}
for df_gisaid in dfs_gisaid_list:
    dfs_gisaid = dfs_gisaid | df_gisaid
# dfs_gisaid2 = create_dataframes(gisaid2)

A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP

In [ ]:
# Do the same with Andersen 

# dfs_andersen = create_dataframes(complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/")
dfs_andersen = create_dataframes(originals + "complete/")

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_HA
A3_MP
A3_MP
A3_NA
A3_NA
A3_NP
A3_NP
A3_NS
A3_NS
A3_PA
A3_PA
A3_PB1
A3_PB1
A3_PB2
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_HA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_HA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_MP
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_MP
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NP
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NP
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NS
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NS
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PB1
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PB1
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PB2
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_HA
B3.6_MP
B3.6_MP
B3.6_NA
B3.6_NA
B3.6_NP
B3.6_NP
B3.6_NS
B3.6_NS
B3.6_PA
B3.6_PA
B3.6_PB1
B3.6_PB1
B3.6_PB2
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_HA
D1.1_MP
D1.1_MP
D1.1_NA
D1.1_NA
D1.1_NP
D1.1_NP
D1.1_NS
D1.1_NS
D1.1_PA
D1.1_PA
D1.1_PB1
D1.1_PB1
D1.1_PB2
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
D2.1_HA
D2.1_MP
D2.1_NA
D2.1_NP
D2.1_NS
D2.1_PA
D2.1_PB1
D2.1_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor101_HA
Minor101_MP
Minor101_NA
Minor101_NP
Minor101_NS
Minor101_PA
Minor101_PB1
Minor101_PB2
Minor102_HA
Minor102_MP
Minor102_NA
Minor102_NP
Minor102_NS
Minor102_PA
Minor102_PB1
Minor102_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor104_HA
Minor104_MP
Minor104_NA
Minor104_NP
Minor104_NS
Minor104_PA
Minor104_PB1
Minor104_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor106_HA
Minor106_MP
Minor106_NA
Minor106_NP
Minor106_NS
Minor106_PA
Minor106_PB1
Minor106_PB2
Minor10_HA
Minor10_MP
Minor10_NA
Minor10_NP
Minor10_NS
Minor10_PA
Minor10_PB1
Minor10_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor16_HA
Minor16_MP
Minor16_NA
Minor16_NP
Minor16_NS
Minor16_PA
Minor16_PB1
Minor16_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor18_HA
Minor18_MP
Minor18_NA
Minor18_NP
Minor18_NS
Minor18_PA
Minor18_PB1
Minor18_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor24_HA
Minor24_MP
Minor24_NA
Minor24_NP
Minor24_NS
Minor24_PA
Minor24_PB1
Minor24_PB2
Minor25_HA
Minor25_MP
Minor25_NA
Minor25_NP
Minor25_NS
Minor25_PA
Minor25_PB1
Minor25_PB2
Minor26_HA
Minor26_MP
Minor26_NA
Minor26_NP
Minor26_NS
Minor26_PA
Minor26_PB1
Minor26_PB2
Minor27_HA
Minor27_MP
Minor27_NA
Minor27_NP
Minor27_NS
Minor27_PA
Minor27_PB1
Minor27_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor29_HA
Minor29_MP
Minor29_NA
Minor29_NP
Minor29_NS
Minor29_PA
Minor29_PB1
Minor29_PB2
Minor30_HA
Minor30_MP
Minor30_NA
Minor30_NP
Minor30_NS
Minor30_PA
Minor30_PB1
Minor30_PB2
Minor31_HA
Minor31_MP
Minor31_NA
Minor31_NP
Minor31_NS
Minor31_PA
Minor31_PB1
Minor31_PB2
Minor32_HA
Minor32_MP
Minor32_NA
Minor32_NP
Minor32_NS
Minor32_PA
Minor32_PB1
Minor32_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor37_HA
Minor37_MP
Minor37_NA
Minor37_NP
Minor37_NS
Minor37_PA
Minor37_PB1
Minor37_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor39_HA
Minor39_MP
Minor39_NA
Minor39_NP
Minor39_NS
Minor39_PA
Minor39_PB1
Minor39_PB2
Minor40_HA
Minor40_MP
Minor40_NA
Minor40_NP
Minor40_NS
Minor40_PA
Minor40_PB1
Minor40_PB2
Minor41_HA
Minor41_MP
Minor41_NA
Minor41_NP
Minor41_NS
Minor41_PA
Minor41_PB1
Minor41_PB2
Minor42_HA
Minor42_MP
Minor42_NA
Minor42_NP
Minor42_NS
Minor42_PA
Minor42_PB1
Minor42_PB2
Minor43_HA
Minor43_MP
Minor43_NA
Minor43_NP
Minor43_NS
Minor43_PA
Minor43_PB1
Minor43_PB2
Minor44_HA
Minor44_MP
Minor44_NA
Minor44_NP
Minor44_NS
Minor44_PA
Minor44_PB1
Minor44_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor46_HA
Minor46_MP
Minor46_NA
Minor46_NP
Minor46_NS
Minor46_PA
Minor46_PB1
Minor46_PB2
Minor47_HA
Minor47_MP
Minor47_NA
Minor47_NP
Minor47_NS
Minor47_PA
Minor47_PB1
Minor47_PB2
Minor48_HA
Minor48_MP
Minor48_NA
Minor48_NP
Minor48_NS
Minor48_PA
Minor48_PB1
Minor48_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor52_HA
Minor52_MP
Minor52_NA
Minor52_NP
Minor52_NS
Minor52_PA
Minor52_PB1
Minor52_PB2
Minor53_HA
Minor53_MP
Minor53_NA
Minor53_NP
Minor53_NS
Minor53_PA
Minor53_PB1
Minor53_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor56_HA
Minor56_MP
Minor56_NA
Minor56_NP
Minor56_NS
Minor56_PA
Minor56_PB1
Minor56_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor67_HA
Minor67_MP
Minor67_NA
Minor67_NP
Minor67_NS
Minor67_PA
Minor67_PB1
Minor67_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor71_HA
Minor71_MP
Minor71_NA
Minor71_NP
Minor71_NS
Minor71_PA
Minor71_PB1
Minor71_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor74_HA
Minor74_MP
Minor74_NA
Minor74_NP
Minor74_NS
Minor74_PA
Minor74_PB1
Minor74_PB2
Minor75_HA
Minor75_MP
Minor75_NA
Minor75_NP
Minor75_NS
Minor75_PA
Minor75_PB1
Minor75_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor78_HA
Minor78_MP
Minor78_NA
Minor78_NP
Minor78_NS
Minor78_PA
Minor78_PB1
Minor78_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor80_HA
Minor80_MP
Minor80_NA
Minor80_NP
Minor80_NS
Minor80_PA
Minor80_PB1
Minor80_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor82_HA
Minor82_MP
Minor82_NA
Minor82_NP
Minor82_NS
Minor82_PA
Minor82_PB1
Minor82_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor84_HA
Minor84_MP
Minor84_NA
Minor84_NP
Minor84_NS
Minor84_PA
Minor84_PB1
Minor84_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor92_HA
Minor92_MP
Minor92_NA
Minor92_NP
Minor92_NS
Minor92_PA
Minor92_PB1
Minor92_PB2
Minor93_HA
Minor93_MP
Minor93_NA
Minor93_NP
Minor93_NS
Minor93_PA
Minor93_PB1
Minor93_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor95_HA
Minor95_MP
Minor95_NA
Minor95_NP
Minor95_NS
Minor95_PA
Minor95_PB1
Minor95_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
Minor98_HA
Minor98_MP
Minor98_NA
Minor98_NP
Minor98_NS
Minor98_PA
Minor98_PB1
Minor98_PB2
Minor99_HA
Minor99_MP
Minor99_NA
Minor99_NP
Minor99_NS
Minor99_PA
Minor99_PB1
Minor99_PB2

In [ ]:
# os.chdir(downloads)
# dfs_gisaid["B3.13_HA"].to_csv

In [ ]:
for key in dfs_andersen.keys():
    dataframes = dfs_andersen[key]
    print(key)

print(dfs_andersen)

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
D2.1_HA
D2.1_MP
D2.1_NA
D2.1_NP
D2.1_NS
D2.1_PA
D2.1_PB1
D2.1_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor101_HA
Minor101_MP
Minor101_NA
Minor101_NP
Minor101_NS
Minor101_PA
Minor101_PB1
Minor101_PB2
Minor102_HA
Minor102_MP
Minor102_NA
Minor102_NP
Minor102_NS
Minor102_PA
Minor102_PB1
Minor102_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor104_HA
Minor104_MP
Minor104_NA
Minor104_NP
Minor104_NS
Minor104_PA
Minor104_PB1
Minor104_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor106_HA
Minor106_MP
Minor106_NA
Minor106_NP
Minor106_NS
Minor106_PA
Minor106_PB1
Minor106_PB2
Minor10_HA
Minor10_MP
Minor10_NA
Minor10_NP
Minor10_NS
Minor10_PA
Minor10_PB1
Minor10_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor16_HA
Minor16_MP
Minor16_NA
Minor16_NP
Minor16_NS
Minor16_PA
Minor16_PB1
Minor16_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor18_HA
Minor18_MP
Minor18_NA
Minor18_NP
Minor18_NS
Minor18_PA
Minor18_PB1
Minor18_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor24_HA
Minor24_MP
Minor24_NA
Minor24_NP
Minor24_NS
Minor24_PA
Minor24_PB1
Minor24_PB2
Minor25_HA
Minor25_MP
Minor25_NA
Minor25_NP
Minor25_NS
Minor25_PA
Minor25_PB1
Minor25_PB2
Minor26_HA
Minor26_MP
Minor26_NA
Minor26_NP
Minor26_NS
Minor26_PA
Minor26_PB1
Minor26_PB2
Minor27_HA
Minor27_MP
Minor27_NA
Minor27_NP
Minor27_NS
Minor27_PA
Minor27_PB1
Minor27_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor29_HA
Minor29_MP
Minor29_NA
Minor29_NP
Minor29_NS
Minor29_PA
Minor29_PB1
Minor29_PB2
Minor30_HA
Minor30_MP
Minor30_NA
Minor30_NP
Minor30_NS
Minor30_PA
Minor30_PB1
Minor30_PB2
Minor31_HA
Minor31_MP
Minor31_NA
Minor31_NP
Minor31_NS
Minor31_PA
Minor31_PB1
Minor31_PB2
Minor32_HA
Minor32_MP
Minor32_NA
Minor32_NP
Minor32_NS
Minor32_PA
Minor32_PB1
Minor32_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor37_HA
Minor37_MP
Minor37_NA
Minor37_NP
Minor37_NS
Minor37_PA
Minor37_PB1
Minor37_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor39_HA
Minor39_MP
Minor39_NA
Minor39_NP
Minor39_NS
Minor39_PA
Minor39_PB1
Minor39_PB2
Minor40_HA
Minor40_MP
Minor40_NA
Minor40_NP
Minor40_NS
Minor40_PA
Minor40_PB1
Minor40_PB2
Minor41_HA
Minor41_MP
Minor41_NA
Minor41_NP
Minor41_NS
Minor41_PA
Minor41_PB1
Minor41_PB2
Minor42_HA
Minor42_MP
Minor42_NA
Minor42_NP
Minor42_NS
Minor42_PA
Minor42_PB1
Minor42_PB2
Minor43_HA
Minor43_MP
Minor43_NA
Minor43_NP
Minor43_NS
Minor43_PA
Minor43_PB1
Minor43_PB2
Minor44_HA
Minor44_MP
Minor44_NA
Minor44_NP
Minor44_NS
Minor44_PA
Minor44_PB1
Minor44_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor46_HA
Minor46_MP
Minor46_NA
Minor46_NP
Minor46_NS
Minor46_PA
Minor46_PB1
Minor46_PB2
Minor47_HA
Minor47_MP
Minor47_NA
Minor47_NP
Minor47_NS
Minor47_PA
Minor47_PB1
Minor47_PB2
Minor48_HA
Minor48_MP
Minor48_NA
Minor48_NP
Minor48_NS
Minor48_PA
Minor48_PB1
Minor48_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor52_HA
Minor52_MP
Minor52_NA
Minor52_NP
Minor52_NS
Minor52_PA
Minor52_PB1
Minor52_PB2
Minor53_HA
Minor53_MP
Minor53_NA
Minor53_NP
Minor53_NS
Minor53_PA
Minor53_PB1
Minor53_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor56_HA
Minor56_MP
Minor56_NA
Minor56_NP
Minor56_NS
Minor56_PA
Minor56_PB1
Minor56_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor67_HA
Minor67_MP
Minor67_NA
Minor67_NP
Minor67_NS
Minor67_PA
Minor67_PB1
Minor67_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor71_HA
Minor71_MP
Minor71_NA
Minor71_NP
Minor71_NS
Minor71_PA
Minor71_PB1
Minor71_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor74_HA
Minor74_MP
Minor74_NA
Minor74_NP
Minor74_NS
Minor74_PA
Minor74_PB1
Minor74_PB2
Minor75_HA
Minor75_MP
Minor75_NA
Minor75_NP
Minor75_NS
Minor75_PA
Minor75_PB1
Minor75_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor78_HA
Minor78_MP
Minor78_NA
Minor78_NP
Minor78_NS
Minor78_PA
Minor78_PB1
Minor78_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor80_HA
Minor80_MP
Minor80_NA
Minor80_NP
Minor80_NS
Minor80_PA
Minor80_PB1
Minor80_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor82_HA
Minor82_MP
Minor82_NA
Minor82_NP
Minor82_NS
Minor82_PA
Minor82_PB1
Minor82_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor84_HA
Minor84_MP
Minor84_NA
Minor84_NP
Minor84_NS
Minor84_PA
Minor84_PB1
Minor84_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor92_HA
Minor92_MP
Minor92_NA
Minor92_NP
Minor92_NS
Minor92_PA
Minor92_PB1
Minor92_PB2
Minor93_HA
Minor93_MP
Minor93_NA
Minor93_NP
Minor93_NS
Minor93_PA
Minor93_PB1
Minor93_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor95_HA
Minor95_MP
Minor95_NA
Minor95_NP
Minor95_NS
Minor95_PA
Minor95_PB1
Minor95_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
Minor98_HA
Minor98_MP
Minor98_NA
Minor98_NP
Minor98_NS
Minor98_PA
Minor98_PB1
Minor98_PB2
Minor99_HA
Minor99_MP
Minor99_NA
Minor99_NP
Minor99_NS
Minor99_PA
Minor99_PB1
Minor99_PB2
defaultdict(<class 'list'>, {'A1_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A3_HA': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
3   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
5   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
6   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
7   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
8   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
9   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
10  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
11  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
12  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
13  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
14  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
15  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
16  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
17  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...  ,    isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
3   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
5   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
6   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
7   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
8   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
9   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
10  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
11  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
12  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
13  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
14  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
15  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
16  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
17  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...  ], 'A3_MP': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
5   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
6   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
7   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
8   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
9   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
10  ATGAGTCTTCTGACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
11  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
12  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
13  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
14  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
15  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
16  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
17  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...  ,    isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...


In [ ]:
print(len(list(dfs_gisaid.keys())))
print(len(list(dfs_andersen.keys())))

80
968

In [ ]:
# Merge dataframes and drop duplicates

full_dfs = defaultdict(list)
# same = []
# andersen = set()
# gisaid = set()

for i, andersen_key in enumerate(dfs_andersen.keys()):
    if len(dfs_andersen[andersen_key]) > 0:
        for j, gisaid_key in enumerate(dfs_gisaid.keys()):
            if andersen_key == gisaid_key:
                # same.append(gisaid_key)
        # gisaid_key = list(dfs_gisaid.keys())[i]
        # gisaid2_key = list(dfs_gisaid2.keys())[i]

                andersen_df = dfs_andersen[andersen_key][0]
                print(len(andersen_df))
                # print(andersen_df)
                gisaid_df = dfs_gisaid[gisaid_key][0]
                print(len(gisaid_df))
                # gisaid2_df = dfs_gisaid2[gisaid2_key][0]

                print(pd.concat([gisaid_df, andersen_df]).drop_duplicates())

                full_df = pd.concat([andersen_df, gisaid_df], ignore_index=True)
                print("len full df:", len(full_df))
                test = len(full_df.drop_duplicates(subset="isolate_partial"))

                dedup_df = full_df.drop_duplicates(subset="isolate_partial", keep="last")

                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print(full_df)
                
                print("Keeping nothing: ", test)
                
                print("len deduplicated:", len(dedup_df))
                full_dfs[andersen_key].append(dedup_df)
            # else:
                # gisaid.add(gisaid_key)
                # andersen.add(andersen_key)
    
    # break 


# print(full_dfs)
# print(len(full_dfs))
# print(319*8)
# print(len(same))
# print(len(andersen))
# print(len(gisaid))

0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atggagagaataaaagagctaagagatttgatgtcgcagtctcgca...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
18
22
   isolate_partial                                        full_header  \
0       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
1       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
2       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
3       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
4       010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
5       010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
6        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
7        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
8        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
9        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
10       IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
11       IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atggagaacatagtacttcttcttgcaataattagccttgttaaaa...
1   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
2   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
3   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
4   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
5   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
6   atggagaacatagtacttcttcttgcaataattagccttgttaaaa...
7   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
8   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
9   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
10  ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
11  ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
12  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
13  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
14  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
15  atggaaaccatagtacttcttcttgcaataattagccttgttaaaa...
16  atggaaaacatagcacttcttcttgcaataattagccttgttaaaa...
17  atggaaaccatagtacttcttcttgcaataattagccttgttaaaa...
18  atggaaaacatagcacttcttcttgcaataattagccttgttaaaa...
19  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
20  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
21  atggaaaacatagcacttcttcttgcaataattagccttgttaaaa...
0   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
3   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
5   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
6   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
7   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
8   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
9   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
10  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
11  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
12  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
13  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
14  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
15  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
16  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
17  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
len full df: 40
Keeping nothing:  24
len deduplicated: 24
18
22
   isolate_partial                                        full_header  \
0       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
1       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
2       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
3       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
4       010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
5       010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
6        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
7        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
8        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
9        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
10       IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
11       IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
1   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
2   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
3   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
4   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
5   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
6   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
7   tagatattgaaagatgagtcttctaaccgaggtcgaaacgtacgtt...
8   tagatattgaaagatgagtcttctaaccgaggtcgaaacgtacgtt...
9   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
10  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
11  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
12  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
13  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
14  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
15  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
16  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
17  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
18  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
19  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
20  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
21  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
0   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
5   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
6   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
7   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
8   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
9   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
10  ATGAGTCTTCTGACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
11  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
12  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
13  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
14  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
15  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
16  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
17  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
len full df: 40
Keeping nothing:  24
len deduplicated: 24
18
22
   isolate_partial                                        full_header  \
0       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
1       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
2       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
3       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
4       010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
5       010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
6        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
7        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
8        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
9        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
10       IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
11       IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
1   atgaatccaaatcaaaggataataatcactggatcaatctgtatgg...
2   atgaatccaaatcaaaggataataatcactggatcaatctgtatgg...
3   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
4   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
5   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
6   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
7   aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
8   agttcaaaatgaatccaaatcaaaggataataaccactggatcaat...
9   aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
10  aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
11  aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
12  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
13  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
14  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
15  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
16  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
17  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
18  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
19  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
20  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
21  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
0   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
1   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
2   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
3   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
4   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
5   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
6   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
7   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
8   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
9   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
10  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
11  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
12  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
13  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
14  ATGAATCCAAATCAAAGGATAATAATCACTGGATCAATCTGTATGG...
15  ATGAATCCAAATCAAAGGATAATAATCACTGGATCAATCTGTATGG...
16  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
17  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
len full df: 40
Keeping nothing:  24
len deduplicated: 24
18
22
   isolate_partial                                        full_header  \
0       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
1       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
2       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
3       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
4       010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
5       010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
6        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
7        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
8        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
9        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
10       IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
11       IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...

In [ ]:
# # If none in one database, only use the other and drop duplicates

# full_dfs = defaultdict(list)
# for key in dfs_andersen.keys():
#     print(key)
# # for key in ["D1.3"]:
#     dataframes = dfs_andersen[key]
#     for i, df in enumerate(dataframes):
#         print(i)
#         try:
#             full_df = df.merge(dfs_gisaid[key][i], how="outer")
#             # print(full_df)
#             full_df = full_df.drop_duplicates(subset=["isolate_partial"])
#             full_dfs[key].append(full_df)
#         except:
#             print("Failed to merge dataframes in ", key)
#             full_dfs[key].append(dataframes[i])

## Create FASTA files combining Andersen and GISAID

In [ ]:
# Create FASTA files per segment

combined_files = downloads + "Combinations/GISAID_Andersen/" # B3_13_D1_1/" + date_range + "_B3_13_D1_1/"

os.chdir(combined_files)
for pair in full_dfs.keys():
    print(pair)
    output_path = combined_files + pair + "_combined_" + date_range + ".fasta" 

    output_file = open(output_path, "w")
    for item in full_dfs[pair]:
        # for item in item:
        # item = fasta_files[pair]
        for index, row in item.iterrows():
            name = item.loc[index, "full_header"]
            sequence = item.loc[index, "sequence"]
            # print(name)
        # First is header, second is sequence
        # print(value)
            output_file.write(name)
            output_file.write(sequence)
    output_file.close()

A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2

: