# Cleaning Downloaded Data from avian-flu

Author: Alexander Maksiaev

Purpose: Clean downloaded data from avian-flu, rename sequences according to convention, de-duplicate from GISAID

In [1]:
# Housekeeping

import os
import glob 
import pandas as pd
import xml.etree.ElementTree as ET
import requests
import time
import numpy as np
import dateutil 
from datetime import datetime
from collections import defaultdict 
import importlib
import utils  
importlib.reload(utils)
from utils import * 

# Make sure you have the correct paths

home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/"
downloads = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/"
# downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
originals = downloads + "Andersen/"
saved = originals + "saved/"
temp_files = originals + "temp/"
complete_files = downloads + "Cats/Datasets/Andersen/"

# Day we're updating data
update_date = "06-05-2025"

# Date range
date_range = "04-14-2025--06-05-2025"

os.chdir(downloads)

## Read Metadata

In [2]:
# Read metadata

os.chdir(saved)
metadata_normalized = pd.read_csv("metadata_normalized.tsv", delimiter="\t") # Collection dates

metadata_folder = originals + "avian-influenza/metadata/"
os.chdir(metadata_folder)

metadata = pd.read_csv("SraRunTable_automated.csv")

print(len(metadata)) # 7397 rows

metadata = metadata.merge(metadata_normalized, how="outer")
print(metadata.columns)

metadata["name_state"] = metadata["geo_loc_name"].apply(lambda x: x.split("/")[1] if len(x.split("/")) > 1 else x.split("/")[0])

# Find only >= last date using Release Date from metadata 
metadata["ReleaseDate"] = metadata["ReleaseDate"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
metadata = metadata[metadata["ReleaseDate"] >= datetime(2025, 4, 14).strftime("%Y-%m-%d")]
# Find only <= update date using Release Date from metadata
metadata = metadata[metadata["ReleaseDate"] <= datetime(2025, 6, 5).strftime("%Y-%m-%d")]

print(len(metadata)) # 6053 rows between 1/1/2024 and 4/14/2025
display(metadata)

9580
Index(['Run', 'Assay Type', 'AvgSpotLen', 'Bases', 'BioProject', 'BioSample',
       'BioSampleModel', 'Bytes', 'Center Name', 'Collection_Date', 'Consent',
       'DATASTORE filetype', 'DATASTORE provider', 'DATASTORE region',
       'Experiment', 'geo_loc_name_country', 'geo_loc_name_country_continent',
       'geo_loc_name', 'Host', 'Instrument', 'isolate', 'Library Name',
       'LibraryLayout', 'LibrarySelection', 'LibrarySource', 'Organism',
       'Platform', 'ReleaseDate', 'create_date', 'version', 'Sample Name',
       'SRA Study', 'serotype', 'isolation_source', 'BioSample Accession',
       'is_retracted', 'retraction_detection_date_utc'],
      dtype='object')
2157

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,create_date,version,Sample Name,SRA Study,serotype,isolation_source,BioSample Accession,is_retracted,retraction_detection_date_utc,name_state
16776,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,2025-04-14 15:21:54,1,25-006243-005,SRP503016,NaN,"MILK, BULK TANK",SRS24711993,False,NaN,USA
16777,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,2025-04-14 15:21:54,1,25-006243-005,SRP503016,NaN,",",SRS24711993,False,NaN,
16778,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,2025-04-14 15:20:51,1,25-006243-002,SRP503016,NaN,"MILK, BULK TANK",SRS24711992,False,NaN,USA
16779,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,2025-04-14 15:20:51,1,25-006243-002,SRP503016,NaN,",",SRS24711992,False,NaN,
16780,SRR33124596,WGS,262.12,61927215,PRJNA1102327,SAMN47941262,Viral,21760157,USDA-NVSL,2025,...,2025-04-14 15:20:49,1,25-006243-001,SRP503016,NaN,"MILK, BULK TANK",SRS24711991,False,NaN,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18928,SRR33764587,WGS,148.55,209851920,PRJNA1207547,SAMN48808596,Viral,77089614,USDA-NVSL,2025,...,2025-05-30 12:24:46,1,25-015209-001,SRP557452,NaN,lung,SRS25207040,False,NaN,USA
18929,SRR33764588,WGS,146.62,75060770,PRJNA1207547,SAMN48808595,Viral,23409535,USDA-NVSL,2025,...,2025-05-30 12:24:41,1,25-015467-001,SRP557452,NaN,OROPHARYNGEAL SWAB,SRS25207039,False,NaN,USA
18930,SRR33764589,WGS,148.16,159798811,PRJNA1207547,SAMN48808594,Viral,59432778,USDA-NVSL,2025,...,2025-05-30 12:24:45,1,25-015388-002,SRP557452,NaN,CLOACAL/TRACHEAL SWAB POOL,SRS25207038,False,NaN,USA
18931,SRR33764590,WGS,148.93,170062068,PRJNA1207547,SAMN48808593,Viral,61180963,USDA-NVSL,2025,...,2025-05-30 12:24:44,1,25-013929-001,SRP557452,NaN,CLOACAL/TRACHEAL SWAB POOL,SRS25207037,False,NaN,USA
18932,SRR33764593,WGS,147.58,126434183,PRJNA1219588,SAMN48808603,Viral,45988679,USDA-NVSL,2025,...,2025-05-30 12:24:44,1,25-013772-001,SRP561968,NaN,"MILK, BULK TANK",SRS25207049,False,NaN,USA

In [3]:
# Get list of genotypes

# os.chdir(home)

# genotypes_df = pd.read_excel("genotype_key.xlsx")

# genotypes = list(genotypes_df["Genotype"])

# print(genotypes)

genotypes = ["B3.13", "D1.1", "B3.2", "B3.6", "B3.7", "B3.5", "A3"]

### Naming convention ###
>A/[host]/[geo_loc_name]/[isolate]/[year]|[serotype: H5N1]|[collection_date]|[host_type]|[genotype]

host_type is from manual animal reference

In metadata, we have: host, geo_loc_name, isolate, year

We need: geo_loc_name, collection_date, host_type, genotype

host = Host

geo_loc_name (primary) = geo_loc_name

geo_loc_name (secondary) = genbank_mapping.tsv > genbank_name

isolate = isolate

collection date (primary) = Collection_Date

collection date (secondary) = https://www.ncbi.nlm.nih.gov/genbank/ > BioSample (input: BioSample) > Nucleotide > [first result] > collection_date

serotype = serotype

host type = [from ref] 

genotype = [from genoflu] -- use genoflu_results.tsv

## Get genotype, specific geolocation

In [4]:
# Get genotype from genoflu_results.tsv

os.chdir(metadata_folder)

genoflu_results = pd.read_csv("genoflu_results.tsv", delimiter="\t")

genoflu_results["Run"] = genoflu_results["sample"]

metadata = metadata.merge(genoflu_results, on="Run", how="inner")
print(metadata)
# metadata = metadata[~metadata["Genotype"].str.contains('Not assigned')] # Do not include non-assigned genotypes
metadata = metadata[metadata["Genotype"].isin(genotypes)]

# Get only the genotypes we want: B3.13 and D1.1

# b313_and_d11_only = genoflu_results[(genoflu_results["Genotype"] == "B3.13") | (genoflu_results["Genotype"] == "D1.1")]
# b313_and_d11_only = b313_and_d11_only.rename(columns={"sample": "Run"})
# b313_and_d11_only = b313_and_d11_only.drop_duplicates(subset="Run", keep="last")

# metadata = metadata.merge(b313_and_d11_only, on=["Run", "Genotype"], how="inner")

print(len(metadata)) 

display(metadata)

              Run Assay Type  AvgSpotLen      Bases    BioProject  \
0     SRR33124594        WGS      246.43  145473401  PRJNA1102327
1     SRR33124594        WGS      246.43  145473401  PRJNA1102327
2     SRR33124595        WGS      240.38  139928333  PRJNA1102327
3     SRR33124595        WGS      240.38  139928333  PRJNA1102327
4     SRR33124596        WGS      262.12   61927215  PRJNA1102327
...           ...        ...         ...        ...           ...
2152  SRR33764587        WGS      148.55  209851920  PRJNA1207547
2153  SRR33764588        WGS      146.62   75060770  PRJNA1207547
2154  SRR33764589        WGS      148.16  159798811  PRJNA1207547
2155  SRR33764590        WGS      148.93  170062068  PRJNA1207547
2156  SRR33764593        WGS      147.58  126434183  PRJNA1219588

         BioSample BioSampleModel     Bytes Center Name Collection_Date  ...  \
0     SAMN47941264          Viral  50832578   USDA-NVSL            2025  ...
1     SAMN47941264          Viral  50832578   USDA-NVSL            2025  ...
2     SAMN47941263          Viral  48295907   USDA-NVSL            2025  ...
3     SAMN47941263          Viral  48295907   USDA-NVSL            2025  ...
4     SAMN47941262          Viral  21760157   USDA-NVSL            2025  ...
...            ...            ...       ...         ...             ...  ...
2152  SAMN48808596          Viral  77089614   USDA-NVSL            2025  ...
2153  SAMN48808595          Viral  23409535   USDA-NVSL            2025  ...
2154  SAMN48808594          Viral  59432778   USDA-NVSL            2025  ...
2155  SAMN48808593          Viral  61180963   USDA-NVSL            2025  ...
2156  SAMN48808603          Viral  45988679   USDA-NVSL            2025  ...

     name_state       sample                 date       File Name  \
0           USA  SRR33124594  2025-05-09_10-46-09  SRR33124594.fa
1                SRR33124594  2025-05-09_10-46-09  SRR33124594.fa
2           USA  SRR33124595  2025-05-09_10-52-41  SRR33124595.fa
3                SRR33124595  2025-05-09_10-52-41  SRR33124595.fa
4           USA  SRR33124596  2025-05-09_10-50-43  SRR33124596.fa
...         ...          ...                  ...             ...
2152        USA  SRR33764587  2025-05-31_08-53-48  SRR33764587.fa
2153        USA  SRR33764588  2025-05-31_08-53-48  SRR33764588.fa
2154        USA  SRR33764589  2025-05-31_08-53-49  SRR33764589.fa
2155        USA  SRR33764590  2025-05-31_08-53-48  SRR33764590.fa
2156        USA  SRR33764593  2025-05-31_08-53-48  SRR33764593.fa

                                               Genotype  \
0                                                 B3.13
1                                                 B3.13
2                                                 B3.13
3                                                 B3.13
4     Not assigned: Only 7 segments >98.0% match fou...
...                                                 ...
2152                                               D1.1
2153                                               D1.1
2154                                               D1.1
2155                                               D1.1
2156                                               D1.1

                            Genotype List Used, >=98.0%  \
0     NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...
1     NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...
2     HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...
3     HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...
4     HA:ea1, MP:ea1, PB2:am2.2, PB1:am4, NA:ea1, NS...
...                                                 ...
2152  NP:am13, HA:ea3, NS:ea3, NA:am4N1, PB2:am24, P...
2153  HA:ea3, PB2:am24, PA:am4, PB1:ea3, MP:ea3, NP:...
2154  NS:ea3, PB2:am24, NA:am4N1, HA:ea3, MP:ea3, PA...
2155  PA:am4, HA:ea3, MP:ea3, NS:ea3, NA:am4N1, NP:a...
2156  NS:ea3, PB2:am24, HA:ea3, PB1:ea3, MP:ea3, NA:...

                             Genotype Sample Title List  \
0     am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...
1     am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...
2     ea1:22-003707-003:HA, am8:23-032005-001:NP, am...
3     ea1:22-003707-003:HA, am8:23-032005-001:NP, am...
4     ea1:22-003707-003:HA, ea1:22-003707-003:MP, ea...
...                                                 ...
2152  am13:24-030039-001:NP, ea3:22-013001-001:HA, e...
2153  ea3:22-013001-001:HA, am24:24-030039-001:PB2, ...
2154  ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...
2155  am4:24-030039-001:PA, ea3:22-013001-001:HA, ea...
2156  ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...

                            Genotype Percent Match List  \
0     99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...
1     99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...
2     98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...
3     98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...
4     98.42%, 98.68%, 97.63%, 98.55%, 99.38%, 98.86%...
...                                                 ...
2152  99.73%, 99.41%, 98.69%, 99.42%, 99.74%, 99.06%...
2153  99.35%, 99.56%, 99.37%, 99.30%, 99.69%, 99.67%...
2154  98.93%, 99.65%, 99.33%, 99.30%, 99.69%, 99.72%...
2155  99.85%, 99.53%, 99.90%, 99.05%, 99.04%, 99.87%...
2156  98.93%, 99.65%, 99.47%, 99.21%, 99.90%, 99.04%...

             Genotype Mismatch List Genotype Average Depth of Coverage List
0     7, 20, 16, 12, 28, 13, 28, 33       Ran on FASTA - No Coverage Report
1     7, 20, 16, 12, 28, 13, 28, 33       Ran on FASTA - No Coverage Report
2     28, 20, 7, 33, 14, 16, 12, 28       Ran on FASTA - No Coverage Report
3     28, 20, 7, 33, 14, 16, 12, 28       Ran on FASTA - No Coverage Report
4     27, 13, 51, 33, 14, 16, 8, 18       Ran on FASTA - No Coverage Report
...                             ...                                     ...
2152      4, 10, 11, 6, 6, 17, 2, 5       Ran on FASTA - No Coverage Report
2153    11, 10, 11, 16, 3, 5, 11, 9       Ran on FASTA - No Coverage Report
2154       9, 8, 7, 12, 3, 5, 4, 13       Ran on FASTA - No Coverage Report
2155        1, 8, 1, 8, 10, 2, 3, 3       Ran on FASTA - No Coverage Report
2156        9, 8, 9, 18, 1, 9, 9, 8       Ran on FASTA - No Coverage Report

[2157 rows x 47 columns]
1864

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,name_state,sample,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List
0,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,USA,SRR33124594,2025-05-09_10-46-09,SRR33124594.fa,B3.13,"NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...","am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...","99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...","7, 20, 16, 12, 28, 13, 28, 33",Ran on FASTA - No Coverage Report
1,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,,SRR33124594,2025-05-09_10-46-09,SRR33124594.fa,B3.13,"NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...","am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...","99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...","7, 20, 16, 12, 28, 13, 28, 33",Ran on FASTA - No Coverage Report
2,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,USA,SRR33124595,2025-05-09_10-52-41,SRR33124595.fa,B3.13,"HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...","ea1:22-003707-003:HA, am8:23-032005-001:NP, am...","98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...","28, 20, 7, 33, 14, 16, 12, 28",Ran on FASTA - No Coverage Report
3,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,,SRR33124595,2025-05-09_10-52-41,SRR33124595.fa,B3.13,"HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...","ea1:22-003707-003:HA, am8:23-032005-001:NP, am...","98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...","28, 20, 7, 33, 14, 16, 12, 28",Ran on FASTA - No Coverage Report
6,SRR33124597,WGS,264.06,73438935,PRJNA1102327,SAMN47941261,Viral,26040226,USDA-NVSL,2025,...,USA,SRR33124597,2025-05-09_10-52-41,SRR33124597.fa,B3.13,"NP:am8, PA:ea1, MP:ea1, PB1:am4, PB2:am2.2, NA...","am8:23-032005-001:NP, ea1:22-003707-003:PA, ea...","99.00%, 98.75%, 98.78%, 99.38%, 98.64%, 98.86%...","15, 27, 12, 14, 31, 16, 7, 29",Ran on FASTA - No Coverage Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2152,SRR33764587,WGS,148.55,209851920,PRJNA1207547,SAMN48808596,Viral,77089614,USDA-NVSL,2025,...,USA,SRR33764587,2025-05-31_08-53-48,SRR33764587.fa,D1.1,"NP:am13, HA:ea3, NS:ea3, NA:am4N1, PB2:am24, P...","am13:24-030039-001:NP, ea3:22-013001-001:HA, e...","99.73%, 99.41%, 98.69%, 99.42%, 99.74%, 99.06%...","4, 10, 11, 6, 6, 17, 2, 5",Ran on FASTA - No Coverage Report
2153,SRR33764588,WGS,146.62,75060770,PRJNA1207547,SAMN48808595,Viral,23409535,USDA-NVSL,2025,...,USA,SRR33764588,2025-05-31_08-53-48,SRR33764588.fa,D1.1,"HA:ea3, PB2:am24, PA:am4, PB1:ea3, MP:ea3, NP:...","ea3:22-013001-001:HA, am24:24-030039-001:PB2, ...","99.35%, 99.56%, 99.37%, 99.30%, 99.69%, 99.67%...","11, 10, 11, 16, 3, 5, 11, 9",Ran on FASTA - No Coverage Report
2154,SRR33764589,WGS,148.16,159798811,PRJNA1207547,SAMN48808594,Viral,59432778,USDA-NVSL,2025,...,USA,SRR33764589,2025-05-31_08-53-49,SRR33764589.fa,D1.1,"NS:ea3, PB2:am24, NA:am4N1, HA:ea3, MP:ea3, PA...","ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...","98.93%, 99.65%, 99.33%, 99.30%, 99.69%, 99.72%...","9, 8, 7, 12, 3, 5, 4, 13",Ran on FASTA - No Coverage Report
2155,SRR33764590,WGS,148.93,170062068,PRJNA1207547,SAMN48808593,Viral,61180963,USDA-NVSL,2025,...,USA,SRR33764590,2025-05-31_08-53-48,SRR33764590.fa,D1.1,"PA:am4, HA:ea3, MP:ea3, NS:ea3, NA:am4N1, NP:a...","am4:24-030039-001:PA, ea3:22-013001-001:HA, ea...","99.85%, 99.53%, 99.90%, 99.05%, 99.04%, 99.87%...","1, 8, 1, 8, 10, 2, 3, 3",Ran on FASTA - No Coverage Report
2156,SRR33764593,WGS,147.58,126434183,PRJNA1219588,SAMN48808603,Viral,45988679,USDA-NVSL,2025,...,USA,SRR33764593,2025-05-31_08-53-48,SRR33764593.fa,D1.1,"NS:ea3, PB2:am24, HA:ea3, PB1:ea3, MP:ea3, NA:...","ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...","98.93%, 99.65%, 99.47%, 99.21%, 99.90%, 99.04%...","9, 8, 9, 18, 1, 9, 9, 8",Ran on FASTA - No Coverage Report

In [5]:
# Get specific geolocation and name_state from genbank_mapping.tsv

genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
genbank_mapping["Run"] = genbank_mapping["sra_run"]
genbank_mapping = genbank_mapping.drop_duplicates(subset="Run", keep="first") # Drop duplicates
genbank_mapping["name_state"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[2]) # Get the name of the state

# print(genbank_mapping)

# metadata_genbank = metadata.merge(genbank_mapping, on=["Run"]) # Only include data that has states

# Get geolocation for second state attribute

os.chdir(home + "references/")
state_ref = pd.read_csv("states_ref.csv")
metadata["Geo_Location"] = metadata["name_state"].apply(lambda x: state_ref.loc[state_ref["Abbreviation"] == x, 'Country'].iloc[0] + "-" + x if x in state_ref["Abbreviation"].values else state_ref.loc[state_ref["State"] == x, 'Country'].iloc[0] + "-" + state_ref.loc[state_ref["State"] == x, 'Abbreviation'].iloc[0] if x in state_ref["State"].values else x)


print(metadata["name_state"])
print(len(metadata))
display(metadata) # Maybe there is no state information since 3/18/2025?

0       USA
1
2       USA
3
6       USA
       ...
2152    USA
2153    USA
2154    USA
2155    USA
2156    USA
Name: name_state, Length: 1864, dtype: object
1864

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,sample,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,Geo_Location
0,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,SRR33124594,2025-05-09_10-46-09,SRR33124594.fa,B3.13,"NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...","am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...","99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...","7, 20, 16, 12, 28, 13, 28, 33",Ran on FASTA - No Coverage Report,USA
1,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,SRR33124594,2025-05-09_10-46-09,SRR33124594.fa,B3.13,"NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...","am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...","99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...","7, 20, 16, 12, 28, 13, 28, 33",Ran on FASTA - No Coverage Report,
2,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,SRR33124595,2025-05-09_10-52-41,SRR33124595.fa,B3.13,"HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...","ea1:22-003707-003:HA, am8:23-032005-001:NP, am...","98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...","28, 20, 7, 33, 14, 16, 12, 28",Ran on FASTA - No Coverage Report,USA
3,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,SRR33124595,2025-05-09_10-52-41,SRR33124595.fa,B3.13,"HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...","ea1:22-003707-003:HA, am8:23-032005-001:NP, am...","98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...","28, 20, 7, 33, 14, 16, 12, 28",Ran on FASTA - No Coverage Report,
6,SRR33124597,WGS,264.06,73438935,PRJNA1102327,SAMN47941261,Viral,26040226,USDA-NVSL,2025,...,SRR33124597,2025-05-09_10-52-41,SRR33124597.fa,B3.13,"NP:am8, PA:ea1, MP:ea1, PB1:am4, PB2:am2.2, NA...","am8:23-032005-001:NP, ea1:22-003707-003:PA, ea...","99.00%, 98.75%, 98.78%, 99.38%, 98.64%, 98.86%...","15, 27, 12, 14, 31, 16, 7, 29",Ran on FASTA - No Coverage Report,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2152,SRR33764587,WGS,148.55,209851920,PRJNA1207547,SAMN48808596,Viral,77089614,USDA-NVSL,2025,...,SRR33764587,2025-05-31_08-53-48,SRR33764587.fa,D1.1,"NP:am13, HA:ea3, NS:ea3, NA:am4N1, PB2:am24, P...","am13:24-030039-001:NP, ea3:22-013001-001:HA, e...","99.73%, 99.41%, 98.69%, 99.42%, 99.74%, 99.06%...","4, 10, 11, 6, 6, 17, 2, 5",Ran on FASTA - No Coverage Report,USA
2153,SRR33764588,WGS,146.62,75060770,PRJNA1207547,SAMN48808595,Viral,23409535,USDA-NVSL,2025,...,SRR33764588,2025-05-31_08-53-48,SRR33764588.fa,D1.1,"HA:ea3, PB2:am24, PA:am4, PB1:ea3, MP:ea3, NP:...","ea3:22-013001-001:HA, am24:24-030039-001:PB2, ...","99.35%, 99.56%, 99.37%, 99.30%, 99.69%, 99.67%...","11, 10, 11, 16, 3, 5, 11, 9",Ran on FASTA - No Coverage Report,USA
2154,SRR33764589,WGS,148.16,159798811,PRJNA1207547,SAMN48808594,Viral,59432778,USDA-NVSL,2025,...,SRR33764589,2025-05-31_08-53-49,SRR33764589.fa,D1.1,"NS:ea3, PB2:am24, NA:am4N1, HA:ea3, MP:ea3, PA...","ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...","98.93%, 99.65%, 99.33%, 99.30%, 99.69%, 99.72%...","9, 8, 7, 12, 3, 5, 4, 13",Ran on FASTA - No Coverage Report,USA
2155,SRR33764590,WGS,148.93,170062068,PRJNA1207547,SAMN48808593,Viral,61180963,USDA-NVSL,2025,...,SRR33764590,2025-05-31_08-53-48,SRR33764590.fa,D1.1,"PA:am4, HA:ea3, MP:ea3, NS:ea3, NA:am4N1, NP:a...","am4:24-030039-001:PA, ea3:22-013001-001:HA, ea...","99.85%, 99.53%, 99.90%, 99.05%, 99.04%, 99.87%...","1, 8, 1, 8, 10, 2, 3, 3",Ran on FASTA - No Coverage Report,USA
2156,SRR33764593,WGS,147.58,126434183,PRJNA1219588,SAMN48808603,Viral,45988679,USDA-NVSL,2025,...,SRR33764593,2025-05-31_08-53-48,SRR33764593.fa,D1.1,"NS:ea3, PB2:am24, HA:ea3, PB1:ea3, MP:ea3, NA:...","ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...","98.93%, 99.65%, 99.47%, 99.21%, 99.90%, 99.04%...","9, 8, 9, 18, 1, 9, 9, 8",Ran on FASTA - No Coverage Report,USA

In [6]:
# # If no states

# metadata_genbank = metadata

# metadata_genbank["name_state"] = "USA"

# metadata_genbank["Geo_Location"] = "USA"

# display(metadata_genbank)

## Collection Dates

If date is N/A, try finding it first

In [ ]:

# Get all dates
# metadata["Collection_Date_Specific"] = metadata["BioSample"].apply(lambda x: search_collection_date(x, metadata) if "-" not in x else x)

# Save this so we don't have to do it again

# os.chdir(temp_files)
# metadata.to_csv("metadata_genbank.csv")

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fc9d1daf9fb804024f89&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fca0b2a871884a0e2f13&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fca3859ccb22a801abb3&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fca58df6e0882c08d951&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcad5a8ada2580075201&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-22
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcb0341bd77b4c028311&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-22
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcb41d104e89d30cfa73&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-22
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcb87404e8751f081e19&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-22
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcbbfe5e0665e00c9d37&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcbdcba4282dca02bef9&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcc0a22b29f33b0399a7&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcc36817cbb90307194d&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcc554e0ce02280b0979&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcc7976015f62f032655&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fccc53187a1dbf0cd599&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2024-11-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fccfeb186a426c034869&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2024-11-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcd158fc0d27990a841b&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcd450fca55b5d0350f9&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcd79030b10a6d006961&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2024-11-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcd965b82376650cfae5&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2024-11-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcdce00813f999082d47&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2024-11-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcde57a3b1672b03ab2f&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2024-11-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fce3070b459cff05db8f&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2024-11-29
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fce6013f6d52050dcba9&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2024-11-29
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcf323c4efb00e0b79db&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcf654e0ce02280b097b&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcf893a849188e05664d&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcfbfa645c37f706149d&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fcfe1bbf3af42107dd03&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd00911448c0b50b06e5&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd02253a28f81a059bad&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd0523c4efb00e0b79dd&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd072bc0e49e65096329&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd0ab2d1508c060c4781&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd0d00fcc63bb9014dbb&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd0fcee5e9859e0c1e4b&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd11e00813f999082d4b&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd14cdd9a97dd406d2dd&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd1770acec270d088aad&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd197d0b287ec5049f21&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd1c2a8ce8e4ac0f43cb&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd1e5e3070cd960a5b3f&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd2ce60b873338044a19&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd2e96710ba4c105a0ed&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd468e895f38a100fedb&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd48dea570b3c20304c1&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd4a00fcc63bb9014dbd&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd4da90f43bf700af23b&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd4fb14e7433890a9f59&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd52b39afe5f12017c4d&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd57b05d72c200062d7f&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd5a61628faee0014b2b&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd5f816ee0c6da015a95&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd61063a053b79059b81&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd649a7ee11b3d09510b&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd6716722aca9d0cb805&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd6e4d5e2a1d38098d07&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd7162629e8642024061&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd7390d81bd18d0cb4fb&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd7684563dd85b03e0ff&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd78d3a99088b408f7f7&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd7b0b2f9c89b50e2001&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd7db15584696e096c53&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd804e849fbe250d2e77&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd82535cbb932a0be3c1&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd85dc49c1effb0aba87&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd879c29c9358b0c95a7&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd89cde1169e7a00b9a1&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd8c59e17e81770d3dcf&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd8f253a28f81a059baf&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd934f880815ce020291&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd9527ea1830ad04cd1b&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd98f52cfefd4e06fa8b&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd9a7404e8751f081e23&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd9d348650e8c30cc807&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fd9f1c301cb97607835d&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fda29f25a3ce530be9ef&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fda437419284b60ea947&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fda79eb64255c2092d3f&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fda99dfdd6581403e509&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdacad5abcb8d50e7ca5&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdafe2a46b2f3f0eaf2d&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdb27e60ceca19067d31&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-22
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdb47846e79c350744e1&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-22
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdb7254f2eb4ae0dc11f&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-17
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdb9c15d9c61430cfe2f&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-17
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdbc304425ac7e04b1b7&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdbead5abcb8d50e7ca7&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdc1d666a99bfa0bb0c9&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdc452484a033f06a60d&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdc75324112df701199d&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdcab4337d78ab0a5447&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdcce7e2a6ff3e0ae429&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-26
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdcf1038319ba0071545&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-26
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdd170768db1b403929f&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-25
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdd4c5626797a50535bf&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-25
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdd69ee70dbceb0d7b65&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-25
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6841fdd9c3552571760306af&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-25
Unable to find collection date.
Unable to find collection date.

In [11]:
# # Upload saved data -- if doing this, make sure the above cell is commented out
# os.chdir(temp_files + "saved/")
# metadata_genbank = pd.read_csv("metadata_genbank.csv")
# os.chdir(temp_files)

# # Get only updated dates

# unknown_dates = metadata_genbank[(metadata_genbank["Collection_Date_Specific"] == "2024") | (metadata_genbank["Collection_Date_Specific"] == "2025")] # Dates we don't have
# known_dates = metadata_genbank[(metadata_genbank["Collection_Date_Specific"] != "2024") & (metadata_genbank["Collection_Date_Specific"] != "2025")] # Dates we've already gotten

# # Get new dates also 
# # new_dates = metadata_genbank["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank) if )

# updated_unknown_dates = unknown_dates["BioSample"].apply(lambda x: search_collection_date(x, unknown_dates)) # Update unknown dates, if possible

# metadata_genbank = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # Remove pre-2024 dates

# metadata_genbank["Collection_Date_Compare"] = metadata_genbank["Collection_Date_Specific"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
# metadata_genbank = metadata_genbank[metadata_genbank["Collection_Date_Compare"] >= datetime(2024, 1, 1).strftime("%Y-%m-%d")]

print(metadata[["Collection_Date_Specific"]])

display(metadata)

     Collection_Date_Specific
0                  2025-02-18
1                  2025-02-18
2                  2025-02-18
3                  2025-02-18
6                        2025
...                       ...
2152                     2025
2153                     2025
2154                     2025
2155                     2025
2156                     2025

[1864 rows x 1 columns]

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,Geo_Location,Collection_Date_Specific
0,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,2025-05-09_10-46-09,SRR33124594.fa,B3.13,"NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...","am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...","99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...","7, 20, 16, 12, 28, 13, 28, 33",Ran on FASTA - No Coverage Report,USA,2025-02-18
1,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,2025-05-09_10-46-09,SRR33124594.fa,B3.13,"NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...","am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...","99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...","7, 20, 16, 12, 28, 13, 28, 33",Ran on FASTA - No Coverage Report,,2025-02-18
2,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,2025-05-09_10-52-41,SRR33124595.fa,B3.13,"HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...","ea1:22-003707-003:HA, am8:23-032005-001:NP, am...","98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...","28, 20, 7, 33, 14, 16, 12, 28",Ran on FASTA - No Coverage Report,USA,2025-02-18
3,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,2025-05-09_10-52-41,SRR33124595.fa,B3.13,"HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...","ea1:22-003707-003:HA, am8:23-032005-001:NP, am...","98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...","28, 20, 7, 33, 14, 16, 12, 28",Ran on FASTA - No Coverage Report,,2025-02-18
6,SRR33124597,WGS,264.06,73438935,PRJNA1102327,SAMN47941261,Viral,26040226,USDA-NVSL,2025,...,2025-05-09_10-52-41,SRR33124597.fa,B3.13,"NP:am8, PA:ea1, MP:ea1, PB1:am4, PB2:am2.2, NA...","am8:23-032005-001:NP, ea1:22-003707-003:PA, ea...","99.00%, 98.75%, 98.78%, 99.38%, 98.64%, 98.86%...","15, 27, 12, 14, 31, 16, 7, 29",Ran on FASTA - No Coverage Report,USA,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2152,SRR33764587,WGS,148.55,209851920,PRJNA1207547,SAMN48808596,Viral,77089614,USDA-NVSL,2025,...,2025-05-31_08-53-48,SRR33764587.fa,D1.1,"NP:am13, HA:ea3, NS:ea3, NA:am4N1, PB2:am24, P...","am13:24-030039-001:NP, ea3:22-013001-001:HA, e...","99.73%, 99.41%, 98.69%, 99.42%, 99.74%, 99.06%...","4, 10, 11, 6, 6, 17, 2, 5",Ran on FASTA - No Coverage Report,USA,2025
2153,SRR33764588,WGS,146.62,75060770,PRJNA1207547,SAMN48808595,Viral,23409535,USDA-NVSL,2025,...,2025-05-31_08-53-48,SRR33764588.fa,D1.1,"HA:ea3, PB2:am24, PA:am4, PB1:ea3, MP:ea3, NP:...","ea3:22-013001-001:HA, am24:24-030039-001:PB2, ...","99.35%, 99.56%, 99.37%, 99.30%, 99.69%, 99.67%...","11, 10, 11, 16, 3, 5, 11, 9",Ran on FASTA - No Coverage Report,USA,2025
2154,SRR33764589,WGS,148.16,159798811,PRJNA1207547,SAMN48808594,Viral,59432778,USDA-NVSL,2025,...,2025-05-31_08-53-49,SRR33764589.fa,D1.1,"NS:ea3, PB2:am24, NA:am4N1, HA:ea3, MP:ea3, PA...","ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...","98.93%, 99.65%, 99.33%, 99.30%, 99.69%, 99.72%...","9, 8, 7, 12, 3, 5, 4, 13",Ran on FASTA - No Coverage Report,USA,2025
2155,SRR33764590,WGS,148.93,170062068,PRJNA1207547,SAMN48808593,Viral,61180963,USDA-NVSL,2025,...,2025-05-31_08-53-48,SRR33764590.fa,D1.1,"PA:am4, HA:ea3, MP:ea3, NS:ea3, NA:am4N1, NP:a...","am4:24-030039-001:PA, ea3:22-013001-001:HA, ea...","99.85%, 99.53%, 99.90%, 99.05%, 99.04%, 99.87%...","1, 8, 1, 8, 10, 2, 3, 3",Ran on FASTA - No Coverage Report,USA,2025
2156,SRR33764593,WGS,147.58,126434183,PRJNA1219588,SAMN48808603,Viral,45988679,USDA-NVSL,2025,...,2025-05-31_08-53-48,SRR33764593.fa,D1.1,"NS:ea3, PB2:am24, HA:ea3, PB1:ea3, MP:ea3, NA:...","ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...","98.93%, 99.65%, 99.47%, 99.21%, 99.90%, 99.04%...","9, 8, 9, 18, 1, 9, 9, 8",Ran on FASTA - No Coverage Report,USA,2025

In [12]:
# If no collection dates

# metadata_genbank["Collection_Date_Specific"] = metadata_genbank["Collection_Date"]

## Get host type

In [14]:
# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

os.chdir(downloads)

animals_ref = pd.read_csv("animals_ref.csv") # Upload animals ref

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['owl', 'western gull', 'great horned owl', 'falcon', 'vulture', 'american black duck', 'flamingo', "'", 'tundra swan', 'red-shouldered hawk', 'cattle', 'blue jay', 'bufflehead', 'red-tailed hawk', 'goose', 'wood duck', 'cackling goose', 'gull', 'red-breasted merganser', 'turkey vulture', 'partridge', 'sharp-shinned hawk', '-', 'gadwall', 'cougar', 'duck', 'snow goose', 'american crow', 'bobcat', 'sanderling', 'trumpeter swan', 'western sandpiper', 'dunlin', 'barn owl', 'lesser scaup', 'cat', 'great blue heron', "bonaparte's gull", 'peregrine', 'bald eagle', 'mallard x american black duck hybrid', 'swan', 'american coot', 'hooded merganser', 'quail', 'greater scaup', 'common raven', "cooper's hawk", 'fox', 'snowy egret', 'mallard', 'barred owl', 'pet food', 'glaucous gull', 'black vulture', 'snowy owl', 'great black-backed gull', 'common loon', 'rock goose', 'skunk', 'canada goose', 'mute swan', 'sand crane', nan, 'mink', "ross's goose", 'great egret', 'crow', 'guinea', 'hawk', 'raccoon', 'chukar', 'common merganser', 'chicken', 'herring gull', 'guineafowl', 'turkey', 'red fox']
[nan]
                avian               cattle        feline   other_mammal  \
0    great_horned_owl            dairy_cow           cat     deer mouse
1        common_raven               cattle  domestic_cat    house_mouse
2       cooper's_hawk  cattle milk product     feral_cat          skunk
3        coopers_hawk          bovine_milk        feline  striped_skunk
4             peafowl              bovine   domestic-cat     norway rat
..                ...                  ...           ...            ...
422        rock goose                  NaN           NaN            NaN
423        sand crane                  NaN           NaN            NaN
424      ross's goose                  NaN           NaN            NaN
425       great egret                  NaN           NaN            NaN
426            guinea                  NaN           NaN            NaN

          human         other  new
0    washington         mixed  NaN
1        nevada   environment  NaN
2       wyoming  multispecies  NaN
3    california       unknown  NaN
4      michigan             '  NaN
..          ...           ...  ...
422         NaN           NaN  NaN
423         NaN           NaN  NaN
424         NaN           NaN  NaN
425         NaN           NaN  NaN
426         NaN           NaN  NaN

[427 rows x 7 columns]

In [15]:
# Get animals from animal reference
os.chdir(downloads)
animals_ref = pd.read_csv("animals_ref.csv")
fix_animals_andersen(metadata, animals_ref) # Get host type

metadata["years"] = metadata["Collection_Date"].apply(lambda x: str(x).split("-")[0]) # Get year only from collection date

## Make names using all the attributes we collected

In [16]:
for num, collection_date in enumerate(metadata["Collection_Date"]):
    
    if collection_date != collection_date: # If nan
        metadata.loc[num, "Collection_Date"] = metadata.loc[num, "years"]
    else: # If actual date
        if len(str(collection_date)) == 4: # If it's a year
            # print("caught")
            metadata.loc[num, "Collection_Date"] = collection_date
        else:
            parsed_date = dateutil.parser.parse(collection_date)
            date = parsed_date.strftime("%Y-%m-%d") # Make sure it doesn't default to today, if just a year
            metadata.loc[num, "Collection_Date"] = date

    metadata = metadata.dropna(thresh=2)

# Make names

# + metadata["BioSample"] + "|" 
names = ">" + metadata["Run"] + "|" + "A/" + metadata["Host"] + "/" + metadata["name_state"] + "/" + metadata["isolate"] + "/" + metadata["years"].apply(lambda x: str(x)) + "|H5N1|" + metadata["Geo_Location"] + "|" + metadata["Collection_Date"].apply(lambda x: str(x)) + "|" + metadata["Host_Type"] + "|" + metadata["Genotype"]

metadata["Name"] = names

# metadata_genbank.to_csv("metadata_genbank_named.csv")

display(metadata[["ReleaseDate", 'create_date', 'Collection_Date']])

     ReleaseDate          create_date Collection_Date
0     2025-04-14  2025-04-14 15:21:54            2025
1     2025-04-14  2025-04-14 15:21:54            2025
2     2025-04-14  2025-04-14 15:20:51            2025
3     2025-04-14  2025-04-14 15:20:51            2025
6     2025-04-14  2025-04-14 15:21:19            2025
...          ...                  ...             ...
2152  2025-05-30  2025-05-30 12:24:46            2025
2153  2025-05-30  2025-05-30 12:24:41            2025
2154  2025-05-30  2025-05-30 12:24:45            2025
2155  2025-05-30  2025-05-30 12:24:44            2025
2156  2025-05-30  2025-05-30 12:24:44            2025

[1864 rows x 3 columns]

In [18]:
# Drop duplicate runs 
metadata = metadata.drop_duplicates(subset="Run", keep="first")

In [19]:
print(metadata)

              Run Assay Type  AvgSpotLen        Bases    BioProject  \
0     SRR33124594        WGS      246.43  145473401.0  PRJNA1102327
2     SRR33124595        WGS      240.38  139928333.0  PRJNA1102327
6     SRR33124597        WGS      264.06   73438935.0  PRJNA1102327
8     SRR33124598        WGS      255.94   76531946.0  PRJNA1102327
10    SRR33124599        WGS      145.79   94820034.0  PRJNA1102327
...           ...        ...         ...          ...           ...
2152  SRR33764587        WGS      148.55  209851920.0  PRJNA1207547
2153  SRR33764588        WGS      146.62   75060770.0  PRJNA1207547
2154  SRR33764589        WGS      148.16  159798811.0  PRJNA1207547
2155  SRR33764590        WGS      148.93  170062068.0  PRJNA1207547
2156  SRR33764593        WGS      147.58  126434183.0  PRJNA1219588

         BioSample BioSampleModel       Bytes Center Name Collection_Date  \
0     SAMN47941264          Viral  50832578.0   USDA-NVSL            2025
2     SAMN47941263          Viral  48295907.0   USDA-NVSL            2025
6     SAMN47941261          Viral  26040226.0   USDA-NVSL            2025
8     SAMN47941260          Viral  27022104.0   USDA-NVSL            2025
10    SAMN47941301          Viral  34313048.0   USDA-NVSL            2025
...            ...            ...         ...         ...             ...
2152  SAMN48808596          Viral  77089614.0   USDA-NVSL            2025
2153  SAMN48808595          Viral  23409535.0   USDA-NVSL            2025
2154  SAMN48808594          Viral  59432778.0   USDA-NVSL            2025
2155  SAMN48808593          Viral  61180963.0   USDA-NVSL            2025
2156  SAMN48808603          Viral  45988679.0   USDA-NVSL            2025

      ...                        Genotype List Used, >=98.0%  \
0     ...  NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...
2     ...  HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...
6     ...  NP:am8, PA:ea1, MP:ea1, PB1:am4, PB2:am2.2, NA...
8     ...  NS:am1.1, PB1:am4, HA:ea1, PB2:am2.2, PA:ea1, ...
10    ...  NA:ea1, MP:ea1, NP:am8, PA:ea1, HA:ea1, PB2:am...
...   ...                                                ...
2152  ...  NP:am13, HA:ea3, NS:ea3, NA:am4N1, PB2:am24, P...
2153  ...  HA:ea3, PB2:am24, PA:am4, PB1:ea3, MP:ea3, NP:...
2154  ...  NS:ea3, PB2:am24, NA:am4N1, HA:ea3, MP:ea3, PA...
2155  ...  PA:am4, HA:ea3, MP:ea3, NS:ea3, NA:am4N1, NP:a...
2156  ...  NS:ea3, PB2:am24, HA:ea3, PB1:ea3, MP:ea3, NA:...

                             Genotype Sample Title List  \
0     am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...
2     ea1:22-003707-003:HA, am8:23-032005-001:NP, am...
6     am8:23-032005-001:NP, ea1:22-003707-003:PA, ea...
8     am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
10    ea1:22-003707-003:NA, ea1:22-003707-003:MP, am...
...                                                 ...
2152  am13:24-030039-001:NP, ea3:22-013001-001:HA, e...
2153  ea3:22-013001-001:HA, am24:24-030039-001:PB2, ...
2154  ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...
2155  am4:24-030039-001:PA, ea3:22-013001-001:HA, ea...
2156  ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...

                            Genotype Percent Match List  \
0     99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...
2     98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...
6     99.00%, 98.75%, 98.78%, 99.38%, 98.64%, 98.86%...
8     99.17%, 99.38%, 98.42%, 98.68%, 98.75%, 98.98%...
10    98.94%, 98.88%, 98.93%, 99.02%, 98.53%, 98.60%...
...                                                 ...
2152  99.73%, 99.41%, 98.69%, 99.42%, 99.74%, 99.06%...
2153  99.35%, 99.56%, 99.37%, 99.30%, 99.69%, 99.67%...
2154  98.93%, 99.65%, 99.33%, 99.30%, 99.69%, 99.72%...
2155  99.85%, 99.53%, 99.90%, 99.05%, 99.04%, 99.87%...
2156  98.93%, 99.65%, 99.47%, 99.21%, 99.90%, 99.04%...

             Genotype Mismatch List Genotype Average Depth of Coverage List  \
0     7, 20, 16, 12, 28, 13, 28, 33       Ran on FASTA - No Coverage Report
2     28, 20, 7, 33, 14, 16, 12, 28       Ran on FASTA - No Coverage Report
6     15, 27, 12, 14, 31, 16, 7, 29       Ran on FASTA - No Coverage Report
8     7, 14, 27, 30, 27, 10, 18, 18       Ran on FASTA - No Coverage Report
10    15, 11, 16, 21, 25, 32, 8, 12       Ran on FASTA - No Coverage Report
...                             ...                                     ...
2152      4, 10, 11, 6, 6, 17, 2, 5       Ran on FASTA - No Coverage Report
2153    11, 10, 11, 16, 3, 5, 11, 9       Ran on FASTA - No Coverage Report
2154       9, 8, 7, 12, 3, 5, 4, 13       Ran on FASTA - No Coverage Report
2155        1, 8, 1, 8, 10, 2, 3, 3       Ran on FASTA - No Coverage Report
2156        9, 8, 9, 18, 1, 9, 9, 8       Ran on FASTA - No Coverage Report

     Geo_Location Collection_Date_Specific     Host_Type years  \
0             USA               2025-02-18        cattle  2025
2             USA               2025-02-18        cattle  2025
6             USA                     2025        cattle  2025
8             USA                     2025        cattle  2025
10            USA               2025-02-22        feline  2025
...           ...                      ...           ...   ...
2152          USA                     2025  other_mammal  2025
2153          USA                     2025        feline  2025
2154          USA                     2025         avian  2025
2155          USA                     2025         avian  2025
2156          USA                     2025        cattle  2025

                                                   Name
0     >SRR33124594|A/CATTLE/USA/25-006243-005/2025|H...
2     >SRR33124595|A/CATTLE/USA/25-006243-002/2025|H...
6     >SRR33124597|A/CATTLE/USA/25-006240-005/2025|H...
8     >SRR33124598|A/CATTLE/USA/25-006031-002/2025|H...
10    >SRR33124599|A/CAT/USA/25-007097-002/2025|H5N1...
...                                                 ...
2152  >SRR33764587|A/FOX/USA/25-015209-001/2025|H5N1...
2153  >SRR33764588|A/CAT/USA/25-015467-001/2025|H5N1...
2154  >SRR33764589|A/BALD EAGLE/USA/25-015388-002/20...
2155  >SRR33764590|A/BALD EAGLE/USA/25-013929-001/20...
2156  >SRR33764593|A/CATTLE/USA/25-013772-001/2025|H...

[1036 rows x 52 columns]

## Make FASTA files

In [20]:
# Get information to create the fasta files

fasta_folder = originals + "avian-influenza/fasta/"

os.chdir(fasta_folder)

segments = ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]
pairs = []
fasta_files = {}

for genotype in genotypes: # ["B3.13", "D1.1"]:
    for segment in segments:
        pair = genotype + "_" + segment
        pairs.append(pair)

for pair in pairs:
    fasta_files[pair] = [] # List to hold fasta files

for run in metadata["Run"].values: # For each run 
    for dirpath, dirs, files in os.walk(fasta_folder): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            # print(file_name)
            if run in file_name: # Note that there will be ~8 files total with that run name
                # Make a fasta file and put it in the list
                with open(file_name) as f:
                    lines = f.readlines()
                    sequence = lines[1] 
                    # Each run/segment pair has one sequence -- it's placed into a file with other run/segment pairs with the same segment and genotype
                    header = metadata[metadata["Run"] == run].loc[:, "Name"].values[0]
                    genotype = metadata[metadata["Run"] == run].loc[:, "Genotype"].values[0]
                    # print(header)
                    # print(genotype)
                    # break 
                    segment = file_name.split("_")[-2]
                    # Find the pair that corresponds to 
                    pair_name = genotype + "_" + segment
                    this_specific_fasta = []
                    for pair in pairs:
                        # print(pair)
                        # print(pair_name)
                        if pair_name == pair:
                            this_specific_fasta.append(header)
                            this_specific_fasta.append(sequence)
                            fasta_files[pair].append(this_specific_fasta)
                f.close()
        break

In [21]:
# print(fasta_files.keys())

In [22]:
# Create fasta files 

# os.chdir(complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/")
os.chdir(complete_files)
names = []
for pair in fasta_files.keys():
    # output_path = complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/" + pair + "_andersen_updated_" + update_date + ".fasta" 
    output_path = complete_files + pair + "_andersen_updated_" + update_date + ".fasta"

    output_file = open(output_path, "w")
    for item in fasta_files[pair]:
        # for item in item:
        # item = fasta_files[pair]
        try:
            name = str(item[0].values[0]) # See if this is one we didn't have a collection date for
        except:
            name = str(item[0])
        print(name)
        names.append(name)
        # First is header, second is sequence
        # print(value)
        output_file.write(name + "\n")
        output_file.write(item[1])
    output_file.close()

print(len(names)/8)

>SRR33124594|A/CATTLE/USA/25-006243-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124595|A/CATTLE/USA/25-006243-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124597|A/CATTLE/USA/25-006240-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124598|A/CATTLE/USA/25-006031-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124599|A/CAT/USA/25-007097-002/2025|H5N1|USA|2025|feline|B3.13
>SRR33124600|A/CAT/USA/25-007097-001/2025|H5N1|USA|2025|feline|B3.13
>SRR33124601|A/CAT/USA/25-006638-001/2025|H5N1|USA|2025|feline|B3.13
>SRR33124602|A/CAT/USA/25-006544-001/2025|H5N1|USA|2025|feline|B3.13
>SRR33124603|A/CAT/USA/25-006543-001/2025|H5N1|USA|2025|feline|B3.13
>SRR33124604|A/CATTLE/USA/25-006954-002/2025|H5N1|USA|2024-11-19|cattle|B3.13
nan
>SRR33124606|A/CATTLE/USA/25-006029-002/2025|H5N1|USA|2024-11-19|cattle|B3.13
nan
nan
nan
>SRR33124610|A/CATTLE/USA/25-006276-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124611|A/CATTLE/USA/25-006276-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124612|A/CATTLE/USA/25-006276-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124613|A/CATTLE/USA/25-006276-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124614|A/CATTLE/USA/25-006274-006/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124616|A/CATTLE/USA/25-006274-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124617|A/CATTLE/USA/25-006028-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124618|A/CATTLE/USA/25-006274-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124619|A/CATTLE/USA/25-006274-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124620|A/CATTLE/USA/25-006274-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124621|A/CATTLE/USA/25-006263-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124622|A/CATTLE/USA/25-006263-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124623|A/CATTLE/USA/25-006263-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124624|A/CATTLE/USA/25-006260-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124625|A/CATTLE/USA/25-006260-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124626|A/CATTLE/USA/25-006260-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124627|A/CATTLE/USA/25-006260-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124628|A/CATTLE/USA/25-006026-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124629|A/CATTLE/USA/25-006260-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124630|A/CATTLE/USA/25-006251-007/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124631|A/CATTLE/USA/25-006251-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124632|A/CATTLE/USA/25-006251-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124633|A/CATTLE/USA/25-006251-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124634|A/CATTLE/USA/25-006248-006/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124635|A/CATTLE/USA/25-006248-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124638|A/CATTLE/USA/25-006243-006/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124639|A/CATTLE/USA/25-006020-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124640|A/CATTLE/USA/25-006020-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318592|A/CATTLE/USA/25-011299-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318593|A/CATTLE/USA/25-011299-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318594|A/CATTLE/USA/25-011296-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318595|A/CATTLE/USA/25-011296-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318596|A/PET FOOD/USA/25-010008-011-v/2025|H5N1|USA|2025|feline|B3.13
>SRR33318597|A/PET FOOD/USA/25-010008-007-v/2025|H5N1|USA|2025|feline|B3.13
>SRR33318598|A/CATTLE/USA/25-011296-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318599|A/PET FOOD/USA/25-010008-005-v/2025|H5N1|USA|2025|feline|B3.13
>SRR33318600|A/PET FOOD/USA/25-010008-004-v/2025|H5N1|USA|2025|feline|B3.13
>SRR33318601|A/CATTLE/USA/25-012178-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318602|A/CATTLE/USA/25-012178-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318603|A/CATTLE/USA/25-012178-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318604|A/CATTLE/USA/25-012133-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318605|A/CATTLE/USA/25-012131-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318606|A/CATTLE/USA/25-012130-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318607|A/CATTLE/USA/25-012130-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318608|A/CATTLE/USA/25-012130-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318609|A/CATTLE/USA/25-011010-002/2025|H5N1|USA|2024|cattle|B3.13
>SRR33318610|A/CATTLE/USA/25-012118-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318612|A/CATTLE/USA/25-012115-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318613|A/CATTLE/USA/25-012115-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318614|A/CATTLE/USA/25-012114-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318615|A/CATTLE/USA/25-012113-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318616|A/CATTLE/USA/25-012113-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318617|A/CATTLE/USA/25-012112-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318618|A/CATTLE/USA/25-012112-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318619|A/CATTLE/USA/25-012111-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318620|A/CATTLE/USA/25-011010-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318621|A/CATTLE/USA/25-012111-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318622|A/CATTLE/USA/25-012092-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318623|A/CATTLE/USA/25-011474-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318624|A/CATTLE/USA/25-011468-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318625|A/CATTLE/USA/25-011468-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318626|A/CATTLE/USA/25-011468-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318627|A/CATTLE/USA/25-011387-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318628|A/CATTLE/USA/25-011387-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318629|A/CATTLE/USA/25-011387-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318630|A/CATTLE/USA/25-011373-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318631|A/CATTLE/USA/25-011000-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318632|A/CATTLE/USA/25-011373-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318633|A/CATTLE/USA/25-011373-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318634|A/CATTLE/USA/25-011373-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318635|A/CATTLE/USA/25-011373-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33318636|A/CATTLE/USA/25-011372-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33318637|A/CATTLE/USA/25-011320-002/2025|H5N1|USA|2024|cattle|B3.13
>SRR33318638|A/CATTLE/USA/25-011320-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33318639|A/CATTLE/USA/25-011318-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318640|A/CATTLE/USA/25-011318-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318641|A/CATTLE/USA/25-011318-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318642|A/CATTLE/USA/25-010999-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318643|A/CATTLE/USA/25-010998-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369778|A/CATTLE/USA/24-036208-001/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369779|A/CATTLE/USA/24-036204-001/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369780|A/CATTLE/USA/24-036203-002/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369781|A/CATTLE/USA/24-036203-001/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369782|A/CATTLE/USA/25-012953-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369783|A/CATTLE/USA/25-012952-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369784|A/CATTLE/USA/25-012952-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369785|A/CATTLE/USA/25-012952-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33369786|A/CATTLE/USA/25-012951-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369787|A/CATTLE/USA/24-036187-002/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369788|A/CATTLE/USA/25-012949-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369789|A/CATTLE/USA/25-012948-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369790|A/CATTLE/USA/25-012189-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369791|A/CATTLE/USA/25-012189-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369792|A/CATTLE/USA/25-012189-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369793|A/CATTLE/USA/25-012189-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369794|A/CATTLE/USA/25-012187-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369795|A/CATTLE/USA/25-012187-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369796|A/CATTLE/USA/25-012183-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369797|A/CATTLE/USA/25-012183-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369798|A/CATTLE/USA/24-036187-001/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369799|A/CATTLE/USA/25-012183-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369800|A/CATTLE/USA/25-012183-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369801|A/CATTLE/USA/25-012134-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369802|A/CATTLE/USA/25-012134-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369803|A/CATTLE/USA/25-012132-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369804|A/CATTLE/USA/25-012129-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369805|A/CATTLE/USA/25-012128-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369806|A/CATTLE/USA/25-012128-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369807|A/CATTLE/USA/25-012128-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369808|A/CATTLE/USA/25-012128-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369809|A/CATTLE/USA/24-036182-002/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369810|A/CATTLE/USA/25-012127-006/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369811|A/CATTLE/USA/25-012127-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369812|A/CATTLE/USA/25-012127-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369813|A/CATTLE/USA/25-012127-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369814|A/CATTLE/USA/25-012127-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369815|A/CATTLE/USA/25-012125-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369816|A/CATTLE/USA/25-012124-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369817|A/CATTLE/USA/25-012089-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369818|A/CATTLE/USA/25-012089-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369819|A/CATTLE/USA/25-012089-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369820|A/CATTLE/USA/24-036182-001/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369821|A/CATTLE/USA/25-012089-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369822|A/CATTLE/USA/25-012089-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369824|A/CATTLE/USA/25-011907-009/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369825|A/CATTLE/USA/25-011907-008/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369826|A/CATTLE/USA/25-011907-007/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369827|A/CATTLE/USA/25-011907-006/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369828|A/CATTLE/USA/25-011907-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369829|A/CATTLE/USA/25-011907-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369830|A/CATTLE/USA/24-036208-002/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369831|A/CATTLE/USA/24-036138-002/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369832|A/CATTLE/USA/24-036138-001/2024|H5N1|USA|2025|cattle|B3.13
>SRR33476704|A/CATTLE/USA/25-012902-008/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476705|A/CATTLE/USA/25-012902-007/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476706|A/CATTLE/USA/25-012902-006/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476707|A/CATTLE/USA/25-012902-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476708|A/CATTLE/USA/25-012902-004/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476709|A/CATTLE/USA/25-012902-003/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476710|A/CATTLE/USA/25-012939-007/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476711|A/CATTLE/USA/25-012934-004/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476712|A/CATTLE/USA/25-012934-003/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476713|A/CATTLE/USA/25-012934-002/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476714|A/CATTLE/USA/25-012934-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476715|A/CATTLE/USA/25-012928-002/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476716|A/CATTLE/USA/25-012928-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476717|A/CATTLE/USA/25-012917-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476718|A/CATTLE/USA/25-012911-004/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476719|A/CATTLE/USA/25-012902-002/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476720|A/CATTLE/USA/25-012911-003/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476721|A/CATTLE/USA/25-012911-002/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476722|A/CATTLE/USA/25-012911-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476723|A/CATTLE/USA/25-012910-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476724|A/CATTLE/USA/25-012910-002/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476725|A/CATTLE/USA/25-012910-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476726|A/CATTLE/USA/25-012909-004/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476727|A/CATTLE/USA/25-012909-003/2025|H5N1|USA|2024|cattle|B3.13
>SRR33476728|A/CATTLE/USA/25-012909-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476729|A/CATTLE/USA/25-012909-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476730|A/CATTLE/USA/25-012902-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476731|A/CATTLE/USA/25-012907-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476732|A/CATTLE/USA/25-012906-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476733|A/CATTLE/USA/25-012905-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476734|A/CATTLE/USA/25-012903-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476735|A/CATTLE/USA/25-012903-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476736|A/CATTLE/USA/25-012903-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476737|A/CATTLE/USA/25-012902-012/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476738|A/CATTLE/USA/25-012902-011/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476739|A/CATTLE/USA/25-012902-010/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476740|A/CATTLE/USA/25-012902-009/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476741|A/CATTLE/USA/25-011466-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33476742|A/CATTLE/USA/25-011298-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508205|A/CATTLE/USA/25-010524-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508206|A/CATTLE/USA/25-010524-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508207|A/CATTLE/USA/25-010524-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508208|A/CATTLE/USA/25-010523-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508209|A/CATTLE/USA/25-010521-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508210|A/CATTLE/USA/25-010517-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508211|A/CAT/USA/25-011002-002/2025|H5N1|USA|2025|feline|B3.13
>SRR33508212|A/CAT/USA/25-011002-001/2025|H5N1|USA|2025|feline|B3.13
>SRR33508213|A/CATTLE/USA/25-010642-007/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508214|A/CATTLE/USA/25-010642-006/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508215|A/CATTLE/USA/25-010517-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508216|A/CATTLE/USA/25-010642-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508217|A/CATTLE/USA/25-010642-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508218|A/CATTLE/USA/25-010642-003/2025|H5N1|USA|2024|cattle|B3.13
>SRR33508219|A/CATTLE/USA/25-010642-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33508220|A/CATTLE/USA/25-010637-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508221|A/CATTLE/USA/25-010637-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508222|A/CATTLE/USA/25-010637-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508223|A/CATTLE/USA/25-010626-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508224|A/CATTLE/USA/25-010626-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508225|A/CATTLE/USA/25-010626-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508226|A/CATTLE/USA/25-010517-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508227|A/CATTLE/USA/25-010626-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508228|A/CATTLE/USA/25-010626-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508229|A/CATTLE/USA/25-010526-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508230|A/CATTLE/USA/25-010526-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508231|A/CATTLE/USA/25-010526-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508232|A/CATTLE/USA/25-010525-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508233|A/CATTLE/USA/25-010525-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508234|A/CATTLE/USA/25-010525-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508235|A/CATTLE/USA/25-010525-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508236|A/CATTLE/USA/25-010524-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508237|A/CATTLE/USA/25-010517-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508238|A/CATTLE/USA/25-010516-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33508249|A/RACCOON/USA/25-010817-001/2025|H5N1|USA|2025|other_mammal|B3.13
>SRR33565399|A/CATTLE/USA/25-013627-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565400|A/CATTLE/USA/25-013625-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565401|A/CATTLE/USA/25-013623-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565402|A/CATTLE/USA/25-013623-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565403|A/CATTLE/USA/25-013621-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565404|A/CATTLE/USA/25-013621-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565405|A/CATTLE/USA/25-013621-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565406|A/CATTLE/USA/24-016686-014-tile/2024|H5N1|USA|2025|cattle|B3.13
>SRR33565407|A/CATTLE/USA/25-013621-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565408|A/CATTLE/USA/25-013621-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565409|A/CATTLE/USA/25-013620-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565410|A/CATTLE/USA/25-013620-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565411|A/CATTLE/USA/25-013620-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565412|A/CATTLE/USA/25-013620-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565413|A/CATTLE/USA/25-013619-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565414|A/CATTLE/USA/25-013618-006/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565415|A/CATTLE/USA/25-013618-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565416|A/CATTLE/USA/25-013618-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565417|A/CATTLE/USA/24-016686-013-tile/2024|H5N1|USA|2025|cattle|B3.13
>SRR33565418|A/CATTLE/USA/25-013618-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565419|A/CATTLE/USA/25-013618-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565420|A/CATTLE/USA/25-013618-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565421|A/CATTLE/USA/25-013617-010/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565422|A/CATTLE/USA/25-013617-009/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565423|A/CATTLE/USA/25-013617-008/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565424|A/CATTLE/USA/25-013617-007/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565425|A/CATTLE/USA/25-013617-006/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565426|A/CATTLE/USA/25-013617-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565427|A/CATTLE/USA/25-013617-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565428|A/CATTLE/USA/24-016686-011-tile/2024|H5N1|USA|2025|cattle|B3.13
>SRR33565429|A/CATTLE/USA/25-013617-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565430|A/CATTLE/USA/25-013617-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565431|A/CATTLE/USA/25-013617-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565432|A/CATTLE/USA/25-013615-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565433|A/CATTLE/USA/25-013613-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565434|A/CATTLE/USA/25-013605-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565435|A/CATTLE/USA/25-013483-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565436|A/CATTLE/USA/25-013477-006/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565437|A/CATTLE/USA/25-013477-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565438|A/CATTLE/USA/25-013477-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565439|A/CATTLE/USA/24-016686-010-tile/2024|H5N1|USA|2025|cattle|B3.13
>SRR33565440|A/CATTLE/USA/25-013477-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565441|A/CATTLE/USA/25-013476-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565442|A/CATTLE/USA/25-013476-002/2025|H5N1|USA|2024|cattle|B3.13
>SRR33565443|A/CATTLE/USA/25-013473-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565444|A/CATTLE/USA/25-013473-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565445|A/CATTLE/USA/25-013473-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565446|A/CATTLE/USA/25-013473-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565447|A/CATTLE/USA/25-013473-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565448|A/CATTLE/USA/25-013469-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33565449|A/CATTLE/USA/24-028773-001-tile/2024|H5N1|USA|2025|cattle|B3.13
>SRR33565450|A/CATTLE/USA/24-016686-008-tile/2024|H5N1|USA|2025|cattle|B3.13
>SRR33565451|A/CATTLE/USA/24-028760-003-tile/2024|H5N1|USA|2025|cattle|B3.13
>SRR33565452|A/CATTLE/USA/24-028760-002-tile/2024|H5N1|USA|2025|cattle|B3.13
>SRR33565453|A/CATTLE/USA/24-028760-001-tile/2024|H5N1|USA|2025|cattle|B3.13
>SRR33565454|A/CATTLE/USA/24-020928-002-tile/2024|H5N1|USA|2025|cattle|B3.13
>SRR33565455|A/CATTLE/USA/24-020928-001-tile/2024|H5N1|USA|2025|cattle|B3.13
>SRR33565456|A/CATTLE/USA/24-020799-004-tile/2024|H5N1|USA|2025|cattle|B3.13

## De-Duplication

In [40]:
# De-duplication 

# Gisaid 

# gisaid = downloads + "GISAID/complete/B3_13_D1_1/" + date_range + "_B3_13_D1_1_North_America/"

gisaid = downloads + "Cats/Datasets/GISAID/"

os.chdir(gisaid)

dfs_gisaid = create_dataframes(gisaid)
# dfs_gisaid2 = create_dataframes(gisaid2)

A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2

In [41]:
# Do the same with Andersen 

# dfs_andersen = create_dataframes(complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/")
dfs_andersen = create_dataframes(complete_files)

A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
B3.13_HA
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
B3.13_MP
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
B3.13_NA
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
B3.13_NP
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
B3.13_NS
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
B3.13_PA
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
B3.13_PB1
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/Cats/Datasets/Andersen/
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2

In [42]:
# os.chdir(downloads)
# dfs_gisaid["B3.13_HA"].to_csv

In [43]:
for key in dfs_andersen.keys():
    dataframes = dfs_andersen[key]
    print(key)

print(dfs_andersen)

A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
defaultdict(<class 'list'>, {'A3_HA': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
3   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
5   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
6   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
7   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
8   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
9   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
10  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
11  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
12  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
13  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
14  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
15  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
16  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
17  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...  ], 'A3_MP': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
5   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
6   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
7   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
8   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
9   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
10  ATGAGTCTTCTGACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
11  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
12  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
13  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
14  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
15  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
16  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
17  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...  ], 'A3_NA': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
1   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
2   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
3   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
4   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
5   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
6   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
7   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
8   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
9   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
10  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
11  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
12  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
13  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
14  ATGAATCCAAATCAAAGGATAATAATCACTGGATCAATCTGTATGG...
15  ATGAATCCAAATCAAAGGATAATAATCACTGGATCAATCTGTATGG...
16  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
17  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...  ], 'A3_NP': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
1   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
2   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
3   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
4   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
5   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
6   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
7   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
8   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
9   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
10  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
11  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
12  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
13  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
14  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
15  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
16  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
17  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...  ], 'A3_NS': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
1   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
2   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
3   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
4   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
5   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
6   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
7   ATGGATACCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
8   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
9   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
10  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
11  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
12  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
13  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
14  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
15  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
16  ATGGATTCCAACACTGTGTCGAGCTTTCAGGTAGACTGCTTTCTTT...
17  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...  ], 'A3_PA': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
1   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
2   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
3   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
4   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
5   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
6   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
7   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
8   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
9   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
10  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
11  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
12  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
13  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
14  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
15  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
16  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
17  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...  ], 'A3_PB1': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
1   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
2   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
3   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
4   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
5   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
6   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
7   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
8   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
9   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
10  ATGGATGTCAATCCGACTTTACTTCTCTTAAAAGTGCCAGCGCAAG...
11  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
12  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
13  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
14  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
15  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
16  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
17  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...  ], 'A3_PB2': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
1   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
2   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
3   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
4   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
5   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
6   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
7   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
8   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
9   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
10  ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
11  ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
12  ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
13  ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
14  ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
15  ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
16  ATGGAGAGAATAAAAAAGCTAAGAGATTTGATGTCGCAGTCTCGCA...
17  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...  ], 'B3.13_HA': [    isolate_partial                                        full_header  \
0        006243-005  >SRR33124594|A/CATTLE/USA/25-006243-005/2025|H...
1        006243-002  >SRR33124595|A/CATTLE/USA/25-006243-002/2025|H...
2        006240-005  >SRR33124597|A/CATTLE/USA/25-006240-005/2025|H...
3        006031-002  >SRR33124598|A/CATTLE/USA/25-006031-002/2025|H...
4        007097-002  >SRR33124599|A/CAT/USA/25-007097-002/2025|H5N1...
..              ...                                                ...

In [44]:
print(len(list(dfs_gisaid.keys())))
print(len(list(dfs_andersen.keys())))

32
56

In [37]:
# Merge dataframes and drop duplicates

full_dfs = defaultdict(list)
# same = []
# andersen = set()
# gisaid = set()

for i, andersen_key in enumerate(dfs_andersen.keys()):
    if len(dfs_andersen[andersen_key]) > 0:
        for j, gisaid_key in enumerate(dfs_gisaid.keys()):
            if andersen_key == gisaid_key:
                # same.append(gisaid_key)
        # gisaid_key = list(dfs_gisaid.keys())[i]
        # gisaid2_key = list(dfs_gisaid2.keys())[i]

                andersen_df = dfs_andersen[andersen_key][0]
                print(len(andersen_df))
                # print(andersen_df)
                gisaid_df = dfs_gisaid[gisaid_key][0]
                print(len(gisaid_df))
                # gisaid2_df = dfs_gisaid2[gisaid2_key][0]

                print(pd.concat([gisaid_df, andersen_df]).drop_duplicates())

                full_df = pd.concat([andersen_df, gisaid_df], ignore_index=True)
                print("len full df:", len(full_df))
                test = len(full_df.drop_duplicates(subset="isolate_partial"))

                dedup_df = full_df.drop_duplicates(subset="isolate_partial", keep="last")

                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print(full_df)
                
                print("Keeping nothing: ", test)
                
                print("len deduplicated:", len(dedup_df))
                full_dfs[andersen_key].append(dedup_df)
            # else:
                # gisaid.add(gisaid_key)
                # andersen.add(andersen_key)
    
    # break 


# print(full_dfs)
# print(len(full_dfs))
# print(319*8)
# print(len(same))
# print(len(andersen))
# print(len(gisaid))

18
22
   isolate_partial                                        full_header  \
0        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
1        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
2        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
3        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
4        IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
5        IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
6       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
7       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
8       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
9       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
10      010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
11      010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atggagaacatagtacttcttcttgcaataattagccttgttaaaa...
1   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
2   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
3   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
4   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
5   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
6   atggagaacatagtacttcttcttgcaataattagccttgttaaaa...
7   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
8   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
9   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
10  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
11  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
12  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
13  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
14  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
15  atggaaaccatagtacttcttcttgcaataattagccttgttaaaa...
16  atggaaaacatagcacttcttcttgcaataattagccttgttaaaa...
17  atggaaaccatagtacttcttcttgcaataattagccttgttaaaa...
18  atggaaaacatagcacttcttcttgcaataattagccttgttaaaa...
19  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
20  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
21  atggaaaacatagcacttcttcttgcaataattagccttgttaaaa...
0   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
3   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
5   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
6   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
7   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
8   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
9   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
10  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
11  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
12  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
13  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
14  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
15  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
16  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
17  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
len full df: 40
Keeping nothing:  24
len deduplicated: 24
18
22
   isolate_partial                                        full_header  \
0        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
1        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
2        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
3        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
4        IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
5        IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
6       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
7       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
8       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
9       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
10      010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
11      010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
1   tagatattgaaagatgagtcttctaaccgaggtcgaaacgtacgtt...
2   tagatattgaaagatgagtcttctaaccgaggtcgaaacgtacgtt...
3   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
4   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
5   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
6   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
7   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
8   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
9   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
10  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
11  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
12  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
13  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
14  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
15  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
16  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
17  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
18  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
19  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
20  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
21  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
0   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
5   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
6   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
7   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
8   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
9   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
10  ATGAGTCTTCTGACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
11  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
12  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
13  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
14  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
15  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
16  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
17  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
len full df: 40
Keeping nothing:  24
len deduplicated: 24
18
22
   isolate_partial                                        full_header  \
0        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
1        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
2        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
3        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
4        IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
5        IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
6       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
7       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
8       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
9       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
10      010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
11      010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
1   aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
2   agttcaaaatgaatccaaatcaaaggataataaccactggatcaat...
3   aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
4   aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
5   aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
6   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
7   atgaatccaaatcaaaggataataatcactggatcaatctgtatgg...
8   atgaatccaaatcaaaggataataatcactggatcaatctgtatgg...
9   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
10  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
11  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
12  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
13  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
14  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
15  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
16  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
17  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
18  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
19  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
20  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
21  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
0   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
1   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
2   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
3   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
4   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
5   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
6   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
7   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
8   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
9   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
10  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
11  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
12  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
13  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
14  ATGAATCCAAATCAAAGGATAATAATCACTGGATCAATCTGTATGG...
15  ATGAATCCAAATCAAAGGATAATAATCACTGGATCAATCTGTATGG...
16  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
17  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
len full df: 40
Keeping nothing:  24
len deduplicated: 24
18
22
   isolate_partial                                        full_header  \
0        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
1        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
2        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
3        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
4        IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
5        IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
6       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
7       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
8       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
9       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
10      010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
11      010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
1   gtagataatcactcactgagtgacatcaacatcatggcgtctcaag...
2   gtagataatcactcactgagtgacatcaacatcatggcgtctcaag...
3   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
4   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
5   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
6   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
7   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
8   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
9   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
10  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
11  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
12  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
13  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
14  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
15  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
16  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
17  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
18  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
19  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
20  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
21  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
0   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
1   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
2   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
3   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
4   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
5   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
6   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...

In [47]:
# If none in one database, only use the other and drop duplicates

full_dfs = defaultdict(list)
for key in dfs_andersen.keys():
    print(key)
# for key in ["D1.3"]:
    dataframes = dfs_andersen[key]
    for i, df in enumerate(dataframes):
        print(i)
        try:
            full_df = df.merge(dfs_gisaid[key][i], how="outer")
            # print(full_df)
            full_df = full_df.drop_duplicates(subset=["isolate_partial"])
            full_dfs[key].append(full_df)
        except:
            print("Failed to merge dataframes in ", key)
            full_dfs[key].append(dataframes[i])

A3_HA
0
A3_MP
0
A3_NA
0
A3_NP
0
A3_NS
0
A3_PA
0
A3_PB1
0
A3_PB2
0
B3.13_HA
0
B3.13_MP
0
B3.13_NA
0
B3.13_NP
0
B3.13_NS
0
B3.13_PA
0
B3.13_PB1
0
B3.13_PB2
0
B3.2_HA
0
Failed to merge dataframes in  B3.2_HA
B3.2_MP
0
Failed to merge dataframes in  B3.2_MP
B3.2_NA
0
Failed to merge dataframes in  B3.2_NA
B3.2_NP
0
Failed to merge dataframes in  B3.2_NP
B3.2_NS
0
Failed to merge dataframes in  B3.2_NS
B3.2_PA
0
Failed to merge dataframes in  B3.2_PA
B3.2_PB1
0
Failed to merge dataframes in  B3.2_PB1
B3.2_PB2
0
Failed to merge dataframes in  B3.2_PB2
B3.5_HA
0
Failed to merge dataframes in  B3.5_HA
B3.5_MP
0
Failed to merge dataframes in  B3.5_MP
B3.5_NA
0
Failed to merge dataframes in  B3.5_NA
B3.5_NP
0
Failed to merge dataframes in  B3.5_NP
B3.5_NS
0
Failed to merge dataframes in  B3.5_NS
B3.5_PA
0
Failed to merge dataframes in  B3.5_PA
B3.5_PB1
0
Failed to merge dataframes in  B3.5_PB1
B3.5_PB2
0
Failed to merge dataframes in  B3.5_PB2
B3.6_HA
0
B3.6_MP
0
B3.6_NA
0
B3.6_NP
0
B3.6_NS
0
B3.6_PA
0
B3.6_PB1
0
B3.6_PB2
0
B3.7_HA
0
Failed to merge dataframes in  B3.7_HA
B3.7_MP
0
Failed to merge dataframes in  B3.7_MP
B3.7_NA
0
Failed to merge dataframes in  B3.7_NA
B3.7_NP
0
Failed to merge dataframes in  B3.7_NP
B3.7_NS
0
Failed to merge dataframes in  B3.7_NS
B3.7_PA
0
Failed to merge dataframes in  B3.7_PA
B3.7_PB1
0
Failed to merge dataframes in  B3.7_PB1
B3.7_PB2
0
Failed to merge dataframes in  B3.7_PB2
D1.1_HA
0
D1.1_MP
0
D1.1_NA
0
D1.1_NP
0
D1.1_NS
0
D1.1_PA
0
D1.1_PB1
0
D1.1_PB2
0

## Create FASTA files combining Andersen and GISAID

In [48]:
# Create FASTA files per segment

combined_files = downloads + "Cats/Datasets/GISAID_Andersen/" # B3_13_D1_1/" + date_range + "_B3_13_D1_1/"

os.chdir(combined_files)
for pair in full_dfs.keys():
    print(pair)
    output_path = combined_files + pair + "_combined_" + update_date + ".fasta" 

    output_file = open(output_path, "w")
    for item in full_dfs[pair]:
        # for item in item:
        # item = fasta_files[pair]
        for index, row in item.iterrows():
            name = item.loc[index, "full_header"]
            sequence = item.loc[index, "sequence"]
            # print(name)
        # First is header, second is sequence
        # print(value)
            output_file.write(name)
            output_file.write(sequence)
    output_file.close()

A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2