# Cleaning Downloaded Data from avian-flu

Author: Alexander Maksiaev

Purpose: Clean downloaded data from avian-flu, rename sequences according to convention, de-duplicate from GISAID

In [1]:
# Housekeeping

import os
import glob 
import pandas as pd
import xml.etree.ElementTree as ET
import requests
import time
import numpy as np
import dateutil 
from datetime import datetime
from collections import defaultdict 
import importlib
import utils  
importlib.reload(utils)
from utils import * 


# Dates
start_date = "06-14-2025"
end_date = "06-20-2025"
date_range = start_date + "--" + end_date
# update_date = "06-18-2025"

# Make sure you have the correct paths

home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/"
downloads = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/"
# downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
references = home + "references/"
originals = downloads + "Andersen/"
saved = originals + "saved/"
temp_files = originals + "temp/"
complete_files = downloads + "complete/"

os.chdir(downloads)

## Read Metadata

In [2]:
# Read metadata

# os.chdir(saved)
# metadata_normalized = pd.read_csv("metadata_normalized.tsv", delimiter="\t") # Collection dates

metadata_folder = originals + "avian-influenza/metadata/"
os.chdir(metadata_folder)

metadata = pd.read_csv("SraRunTable_automated.csv")

print(len(metadata)) # 7397 rows

# metadata = metadata.merge(metadata_normalized, how="outer")
print(metadata.columns)

metadata["name_state"] = metadata["geo_loc_name"].apply(lambda x: x.split("/")[1] if len(x.split("/")) > 1 else x.split("/")[0])

# Find only >= last date using Release Date from metadata 
metadata["ReleaseDate"] = metadata["ReleaseDate"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
# print(metadata["ReleaseDate"])
metadata = metadata[metadata["ReleaseDate"] >= dateutil.parser.parse(start_date).strftime("%Y-%m-%d")]
# Find only <= update date using Release Date from metadata
metadata = metadata[metadata["ReleaseDate"] <= dateutil.parser.parse(end_date).strftime("%Y-%m-%d")]

print(len(metadata)) # 6053 rows between 1/1/2024 and 4/14/2025
display(metadata)
print(metadata["Library Name"])

9808
Index(['Run', 'Assay Type', 'AvgSpotLen', 'Bases', 'BioProject', 'BioSample',
       'BioSampleModel', 'Bytes', 'Center Name', 'Collection_Date', 'Consent',
       'DATASTORE filetype', 'DATASTORE provider', 'DATASTORE region',
       'Experiment', 'geo_loc_name_country', 'geo_loc_name_country_continent',
       'geo_loc_name', 'Host', 'Instrument', 'isolate', 'Library Name',
       'LibraryLayout', 'LibrarySelection', 'LibrarySource', 'Organism',
       'Platform', 'ReleaseDate', 'create_date', 'version', 'Sample Name',
       'SRA Study', 'serotype', 'isolation_source', 'BioSample Accession',
       'is_retracted', 'retraction_detection_date_utc'],
      dtype='object')
49

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,create_date,version,Sample Name,SRA Study,serotype,isolation_source,BioSample Accession,is_retracted,retraction_detection_date_utc,name_state
9759,SRR33993023,WGS,148.15,68132847,PRJNA1102327,SAMN49104730,Viral,22640539,USDA-NVSL,2025,...,2025-06-16 16:08:28,1,25-016878-002,SRP503016,NaN,"MILK, BULK TANK",SRS25388571,False,NaN,USA
9760,SRR33993024,WGS,148.15,63105544,PRJNA1102327,SAMN49104729,Viral,21290975,USDA-NVSL,2025,...,2025-06-16 16:08:28,1,25-016866-004,SRP503016,NaN,"MILK, BULK TANK",SRS25388572,False,NaN,USA
9761,SRR33993025,WGS,148.28,46180111,PRJNA1102327,SAMN49104728,Viral,15373063,USDA-NVSL,2025,...,2025-06-16 16:08:31,1,25-016866-002,SRP503016,NaN,"MILK, BULK TANK",SRS25388570,False,NaN,USA
9762,SRR33993026,WGS,147.53,47042737,PRJNA1102327,SAMN49104727,Viral,15677039,USDA-NVSL,2025,...,2025-06-16 16:08:27,1,25-016847-007,SRP503016,NaN,"MILK, BULK TANK",SRS25388569,False,NaN,USA
9763,SRR33993027,WGS,147.76,65389924,PRJNA1102327,SAMN49104726,Viral,21557873,USDA-NVSL,2025,...,2025-06-16 16:08:41,1,25-016847-006,SRP503016,NaN,"MILK, BULK TANK",SRS25388568,False,NaN,USA
9764,SRR33993028,WGS,147.78,74054528,PRJNA1102327,SAMN49104725,Viral,24486243,USDA-NVSL,2025,...,2025-06-16 16:08:16,1,25-016847-004,SRP503016,NaN,"MILK, BULK TANK",SRS25388567,False,NaN,USA
9765,SRR33993030,WGS,147.73,54441692,PRJNA1102327,SAMN49104724,Viral,18006567,USDA-NVSL,2025,...,2025-06-16 16:08:18,1,25-016846-001,SRP503016,NaN,"MILK, BULK TANK",SRS25388564,False,NaN,USA
9766,SRR33993041,WGS,147.27,52474370,PRJNA1102327,SAMN49104723,Viral,17356512,USDA-NVSL,2025,...,2025-06-16 16:08:17,1,25-016745-002,SRP503016,NaN,"MILK, BULK TANK",SRS25388554,False,NaN,USA
9767,SRR33993043,WGS,147.96,574015012,PRJNA1102327,SAMN49104739,Viral,204462787,USDA-NVSL,2025,...,2025-06-16 16:08:35,1,25-017370-002,SRP503016,NaN,"MILK, BULK TANK",SRS25388552,False,NaN,USA
9768,SRR33993044,WGS,147.98,239374429,PRJNA1102327,SAMN49104738,Viral,85820855,USDA-NVSL,2025,...,2025-06-16 16:08:40,1,25-017369-001,SRP503016,NaN,"MILK, BULK TANK",SRS25388551,False,NaN,USA
9769,SRR33993045,WGS,148.34,238793868,PRJNA1102327,SAMN49104737,Viral,85355492,USDA-NVSL,2025,...,2025-06-16 16:08:22,1,25-017364-002,SRP503016,NaN,"MILK, BULK TANK",SRS25388550,False,NaN,USA
9770,SRR33993046,WGS,148.20,185103703,PRJNA1102327,SAMN49104736,Viral,66232769,USDA-NVSL,2025,...,2025-06-16 16:08:52,1,25-017364-001,SRP503016,NaN,"MILK, BULK TANK",SRS25388549,False,NaN,USA
9771,SRR33993047,WGS,147.70,180096959,PRJNA1102327,SAMN49104735,Viral,64905708,USDA-NVSL,2025,...,2025-06-16 16:08:37,1,25-017354-001,SRP503016,NaN,"MILK, BULK TANK",SRS25388548,False,NaN,USA
9772,SRR33993048,WGS,132.54,45692579,PRJNA1102327,SAMN49104734,Viral,16380741,USDA-NVSL,2025,...,2025-06-16 16:08:19,1,25-002509-001-tile,SRP503016,NaN,"MILK, BULK TANK",SRS25388547,False,NaN,USA
9773,SRR33993049,WGS,148.89,108836285,PRJNA1102327,SAMN49104733,Viral,39521904,USDA-NVSL,2025,...,2025-06-16 16:08:35,1,25-017049-001,SRP503016,NaN,"MILK, BULK TANK",SRS25388546,False,NaN,USA
9774,SRR33993050,WGS,148.32,72069095,PRJNA1102327,SAMN49104732,Viral,23887383,USDA-NVSL,2025,...,2025-06-16 16:08:33,1,25-016878-005,SRP503016,NaN,"MILK, BULK TANK",SRS25388545,False,NaN,USA
9775,SRR33993051,WGS,148.13,71854425,PRJNA1102327,SAMN49104731,Viral,23685525,USDA-NVSL,2025,...,2025-06-16 16:08:20,1,25-016878-003,SRP503016,NaN,"MILK, BULK TANK",SRS25388544,False,NaN,USA
9776,SRR33993052,WGS,147.03,65353759,PRJNA1102327,SAMN49104722,Viral,21469946,USDA-NVSL,2025,...,2025-06-16 16:08:33,1,25-016745-001,SRP503016,NaN,"MILK, BULK TANK",SRS25388543,False,NaN,USA
9777,SRR33993053,WGS,146.19,24058580,PRJNA1102327,SAMN49104721,Viral,8111306,USDA-NVSL,2025,...,2025-06-16 16:08:45,1,25-016741-001,SRP503016,NaN,"MILK, BULK TANK",SRS25388542,False,NaN,USA
9778,SRR33992696,WGS,148.85,190626822,PRJNA980729,SAMN49104545,Viral,68848188,USDA-NVSL,2025,...,2025-06-16 16:07:31,1,25-017216-002,SRP441379,NaN,CLOACAL/OROPHARYNGEAL SWAB POOL,SRS25388223,False,NaN,USA
9779,SRR33992697,WGS,148.65,174204267,PRJNA980729,SAMN49104544,Viral,63013857,USDA-NVSL,2025,...,2025-06-16 16:07:14,1,25-017216-001,SRP441379,NaN,CLOACAL/OROPHARYNGEAL SWAB POOL,SRS25388222,False,NaN,USA
9780,SRR33992698,WGS,148.81,190847180,PRJNA980729,SAMN49104543,Viral,68670191,USDA-NVSL,2025,...,2025-06-16 16:07:12,1,25-017017-005,SRP441379,NaN,OROPHARYNGEAL SWAB,SRS25388221,False,NaN,USA
9781,SRR33992699,WGS,149.03,157118049,PRJNA980729,SAMN49104542,Viral,56934198,USDA-NVSL,2025,...,2025-06-16 16:07:27,1,25-017017-004,SRP441379,NaN,OROPHARYNGEAL SWAB,SRS25388219,False,NaN,USA
9782,SRR33992700,WGS,149.39,85416600,PRJNA980729,SAMN49104541,Viral,30923309,USDA-NVSL,2025,...,2025-06-16 16:07:10,1,25-017017-003,SRP441379,NaN,OROPHARYNGEAL SWAB,SRS25388218,False,NaN,USA
9783,SRR33992701,WGS,148.74,215621548,PRJNA980729,SAMN49104540,Viral,77412197,USDA-NVSL,2025,...,2025-06-16 16:07:12,1,25-016340-002,SRP441379,NaN,OROPHARYNGEAL SWAB,SRS25388220,False,NaN,USA
9784,SRR33992702,WGS,148.58,164485298,PRJNA980729,SAMN49104539,Viral,59153989,USDA-NVSL,2025,...,2025-06-16 16:07:11,1,25-016340-001,SRP441379,NaN,OROPHARYNGEAL SWAB,SRS25388217,False,NaN,USA
9785,SRR33992703,WGS,147.69,108646876,PRJNA980729,SAMN49104538,Viral,35642264,USDA-NVSL,2025,...,2025-06-16 16:07:09,1,25-017017-002,SRP441379,NaN,OROPHARYNGEAL SWAB,SRS25388216,False,NaN,USA
9786,SRR33992704,WGS,147.91,73320377,PRJNA980729,SAMN49104537,Viral,24233116,USDA-NVSL,2025,...,2025-06-16 16:07:12,1,25-017017-001,SRP441379,NaN,OROPHARYNGEAL SWAB,SRS25388215,False,NaN,USA
9787,SRR33993166,WGS,147.75,60982523,PRJNA1219588,SAMN49104924,Viral,19939253,USDA-NVSL,2025,...,2025-06-16 16:08:50,1,25-016765-001,SRP561968,NaN,"MILK, BULK TANK",SRS25388683,False,NaN,USA
9788,SRR33993059,WGS,148.77,139963922,PRJNA1207547,SAMN49104770,Viral,50446456,USDA-NVSL,2025,...,2025-06-16 16:08:31,1,25-016857-001,SRP557452,NaN,BLOOD SWAB,SRS25388585,False,NaN,USA
9789,SRR33993060,WGS,148.46,159384958,PRJNA1207547,SAMN49104769,Viral,57552218,USDA-NVSL,2025,...,2025-06-16 16:08:35,1,25-017061-004,SRP557452,NaN,CLOACAL/TRACHEAL SWAB POOL,SRS25388584,False,NaN,USA
9790,SRR33993061,WGS,147.20,363257804,PRJNA1207547,SAMN49104768,Viral,129254335,USDA-NVSL,2025,...,2025-06-16 16:08:50,1,25-017245-001,SRP557452,NaN,brain,SRS25388583,False,NaN,USA
9791,SRR33993062,WGS,148.63,115123483,PRJNA1207547,SAMN49104767,Viral,41469704,USDA-NVSL,2025,...,2025-06-16 16:08:37,1,25-016855-001,SRP557452,NaN,BLOOD SWAB,SRS25388582,False,NaN,USA
9792,SRR33993063,WGS,145.42,526460773,PRJNA1207547,SAMN49104766,Viral,186161216,USDA-NVSL,2025,...,2025-06-16 16:08:36,1,25-017253-001,SRP557452,NaN,CLOACAL/TRACHEAL SWAB POOL,SRS25388581,False,NaN,USA
9793,SRR33993064,WGS,147.24,444362470,PRJNA1207547,SAMN49104765,Viral,157991689,USDA-NVSL,2025,...,2025-06-16 16:08:50,1,25-017251-001,SRP557452,NaN,CLOACAL/TRACHEAL SWAB POOL,SRS25388580,False,NaN,USA
9794,SRR33993065,WGS,148.27,105099746,PRJNA1207547,SAMN49104764,Viral,37665516,USDA-NVSL,2025,...,2025-06-16 16:08:23,1,25-017061-002,SRP557452,NaN,CLOACAL/TRACHEAL SWAB POOL,SRS25388579,False,NaN,USA
9795,SRR33993066,WGS,148.29,96593730,PRJNA1207547,SAMN49104763,Viral,34777840,USDA-NVSL,2025,...,2025-06-16 16:08:25,1,25-017061-001,SRP557452,NaN,CLOACAL/TRACHEAL SWAB POOL,SRS25388578,False,NaN,USA
9796,SRR33993029,WGS,147.61,522807379,PRJNA1102327,SAMN49104751,Viral,185607037,USDA-NVSL,2025,...,2025-06-16 16:08:52,1,25-017377-003,SRP503016,NaN,"MILK, BULK TANK",SRS25388566,False,NaN,USA
9797,SRR33993031,WGS,147.26,104663426,PRJNA1102327,SAMN49104750,Viral,37254008,USDA-NVSL,2025,...,2025-06-16 16:08:34,1,25-017376-009,SRP503016,NaN,"MILK, BULK TANK",SRS25388565,False,NaN,USA
9798,SRR33993032,WGS,147.52,235901105,PRJNA1102327,SAMN49104749,Viral,83722829,USDA-NVSL,2025,...,2025-06-16 16:08:37,1,25-017376-008,SRP503016,NaN,"MILK, BULK TANK",SRS25388563,False,NaN,USA
9799,SRR33993033,WGS,148.12,209453718,PRJNA1102327,SAMN49104748,Viral,74406813,USDA-NVSL,2025,...,2025-06-16 16:08:38,1,25-017376-007,SRP503016,NaN,"MILK, BULK TANK",SRS25388562,False,NaN,USA
9800,SRR33993034,WGS,148.01,200396122,PRJNA1102327,SAMN49104747,Viral,71084273,USDA-NVSL,2025,...,2025-06-16 16:08:20,1,25-017376-006,SRP503016,NaN,"MILK, BULK TANK",SRS25388561,False,NaN,USA
9801,SRR33993035,WGS,148.26,208159405,PRJNA1102327,SAMN49104746,Viral,74388676,USDA-NVSL,2025,...,2025-06-16 16:08:26,1,25-017376-005,SRP503016,NaN,"MILK, BULK TANK",SRS25388560,False,NaN,USA
9802,SRR33993036,WGS,148.05,209968472,PRJNA1102327,SAMN49104745,Viral,75064716,USDA-NVSL,2025,...,2025-06-16 16:08:19,1,25-017376-004,SRP503016,NaN,"MILK, BULK TANK",SRS25388559,False,NaN,USA
9803,SRR33993037,WGS,148.35,221485032,PRJNA1102327,SAMN49104744,Viral,78792165,USDA-NVSL,2025,...,2025-06-16 16:08:21,1,25-017376-003,SRP503016,NaN,"MILK, BULK TANK",SRS25388558,False,NaN,USA
9804,SRR33993038,WGS,148.07,190312401,PRJNA1102327,SAMN49104743,Viral,67965403,USDA-NVSL,2025,...,2025-06-16 19:54:22,1,25-017376-002,SRP503016,NaN,"MILK, BULK TANK",SRS25388557,False,NaN,USA
9805,SRR33993039,WGS,147.66,790397536,PRJNA1102327,SAMN49104742,Viral,282137009,USDA-NVSL,2025,...,2025-06-16 16:08:39,1,25-017376-001,SRP503016,NaN,"MILK, BULK TANK",SRS25388556,False,NaN,USA
9806,SRR33993040,WGS,148.06,535205498,PRJNA1102327,SAMN49104741,Viral,189952374,USDA-NVSL,2025,...,2025-06-16 16:08:29,1,25-017370-004,SRP503016,NaN,"MILK, BULK TANK",SRS25388555,False,NaN,USA
9807,SRR33993042,WGS,147.81,668807754,PRJNA1102327,SAMN49104740,Viral,236759389,USDA-NVSL,2025,...,2025-06-16 16:08:56,1,25-017370-003,SRP503016,NaN,"MILK, BULK TANK",SRS25388553,False,NaN,USA

9759    25-016878-002-original
9760    25-016866-004-original
9761    25-016866-002-original
9762    25-016847-007-original
9763    25-016847-006-original
9764    25-016847-004-original
9765    25-016846-001-original
9766    25-016745-002-original
9767    25-017370-002-original
9768    25-017369-001-original
9769    25-017364-002-original
9770    25-017364-001-original
9771    25-017354-001-original
9772        25-002509-001-tile
9773    25-017049-001-original
9774    25-016878-005-original
9775    25-016878-003-original
9776    25-016745-001-original
9777    25-016741-001-original
9778    25-017216-002-original
9779    25-017216-001-original
9780    25-017017-005-original
9781    25-017017-004-original
9782    25-017017-003-original
9783    25-016340-002-original
9784    25-016340-001-original
9785    25-017017-002-original
9786    25-017017-001-original
9787    25-016765-001-original
9788    25-016857-001-original
9789    25-017061-004-original
9790    25-017245-001-original
9791    25-016855-001-original
9792    25-017253-001-original
9793    25-017251-001-original
9794    25-017061-002-original
9795    25-017061-001-original
9796    25-017377-003-original
9797    25-017376-009-original
9798    25-017376-008-original
9799    25-017376-007-original
9800    25-017376-006-original
9801    25-017376-005-original
9802    25-017376-004-original
9803    25-017376-003-original
9804    25-017376-002-original
9805    25-017376-001-original
9806    25-017370-004-original
9807    25-017370-003-original
Name: Library Name, dtype: object

In [3]:
# Get list of genotypes

os.chdir(home + "references/")

# genotypes_df = pd.read_excel("genotype_key.xlsx")

# genotypes = list(genotypes_df["Genotype"])

# print(genotypes)

genotypes = ["B3.13", "D1.1"]

# genotypes = ["B3.2"] #, "B3.2", "B3.6", "B3.7", "B3.5", "A3"]

### Naming convention ###
>A/[host]/[geo_loc_name]/[isolate]/[year]|[serotype: H5N1]|[collection_date]|[host_type]|[genotype]

host_type is from manual animal reference

In metadata, we have: host, geo_loc_name, isolate, year

We need: geo_loc_name, collection_date, host_type, genotype

host = Host

geo_loc_name (primary) = geo_loc_name

geo_loc_name (secondary) = genbank_mapping.tsv > genbank_name

isolate = isolate

collection date (primary) = Collection_Date

collection date (secondary) = https://www.ncbi.nlm.nih.gov/genbank/ > BioSample (input: BioSample) > Nucleotide > [first result] > collection_date

serotype = serotype

host type = [from ref] 

genotype = [from genoflu] -- use genoflu_results.tsv

## Get genotype, specific geolocation

In [4]:
# Get genotype from genoflu_results.tsv

os.chdir(metadata_folder)

genoflu_results = pd.read_csv("genoflu_results.tsv", delimiter="\t")

genoflu_results["Run"] = genoflu_results["sample"]

metadata = metadata.merge(genoflu_results, on="Run", how="inner")
print(metadata)
# metadata = metadata[~metadata["Genotype"].str.contains('Not assigned')] # Do not include non-assigned genotypes
metadata = metadata[metadata["Genotype"].isin(genotypes)]

# Get only the genotypes we want: B3.13 and D1.1

# b313_and_d11_only = genoflu_results[(genoflu_results["Genotype"] == "B3.13") | (genoflu_results["Genotype"] == "D1.1")]
# b313_and_d11_only = b313_and_d11_only.rename(columns={"sample": "Run"})
# b313_and_d11_only = b313_and_d11_only.drop_duplicates(subset="Run", keep="last")

# metadata = metadata.merge(b313_and_d11_only, on=["Run", "Genotype"], how="inner")

print(len(metadata)) 

display(metadata)

            Run Assay Type  AvgSpotLen      Bases    BioProject     BioSample  \
0   SRR33993023        WGS      148.15   68132847  PRJNA1102327  SAMN49104730
1   SRR33993024        WGS      148.15   63105544  PRJNA1102327  SAMN49104729
2   SRR33993025        WGS      148.28   46180111  PRJNA1102327  SAMN49104728
3   SRR33993026        WGS      147.53   47042737  PRJNA1102327  SAMN49104727
4   SRR33993027        WGS      147.76   65389924  PRJNA1102327  SAMN49104726
5   SRR33993028        WGS      147.78   74054528  PRJNA1102327  SAMN49104725
6   SRR33993030        WGS      147.73   54441692  PRJNA1102327  SAMN49104724
7   SRR33993041        WGS      147.27   52474370  PRJNA1102327  SAMN49104723
8   SRR33993043        WGS      147.96  574015012  PRJNA1102327  SAMN49104739
9   SRR33993044        WGS      147.98  239374429  PRJNA1102327  SAMN49104738
10  SRR33993045        WGS      148.34  238793868  PRJNA1102327  SAMN49104737
11  SRR33993046        WGS      148.20  185103703  PRJNA1102327  SAMN49104736
12  SRR33993047        WGS      147.70  180096959  PRJNA1102327  SAMN49104735
13  SRR33993048        WGS      132.54   45692579  PRJNA1102327  SAMN49104734
14  SRR33993049        WGS      148.89  108836285  PRJNA1102327  SAMN49104733
15  SRR33993050        WGS      148.32   72069095  PRJNA1102327  SAMN49104732
16  SRR33993051        WGS      148.13   71854425  PRJNA1102327  SAMN49104731
17  SRR33993052        WGS      147.03   65353759  PRJNA1102327  SAMN49104722
18  SRR33993053        WGS      146.19   24058580  PRJNA1102327  SAMN49104721
19  SRR33992696        WGS      148.85  190626822   PRJNA980729  SAMN49104545
20  SRR33992697        WGS      148.65  174204267   PRJNA980729  SAMN49104544
21  SRR33992698        WGS      148.81  190847180   PRJNA980729  SAMN49104543
22  SRR33992699        WGS      149.03  157118049   PRJNA980729  SAMN49104542
23  SRR33992700        WGS      149.39   85416600   PRJNA980729  SAMN49104541
24  SRR33992701        WGS      148.74  215621548   PRJNA980729  SAMN49104540
25  SRR33992702        WGS      148.58  164485298   PRJNA980729  SAMN49104539
26  SRR33992703        WGS      147.69  108646876   PRJNA980729  SAMN49104538
27  SRR33992704        WGS      147.91   73320377   PRJNA980729  SAMN49104537
28  SRR33993166        WGS      147.75   60982523  PRJNA1219588  SAMN49104924
29  SRR33993059        WGS      148.77  139963922  PRJNA1207547  SAMN49104770
30  SRR33993060        WGS      148.46  159384958  PRJNA1207547  SAMN49104769
31  SRR33993061        WGS      147.20  363257804  PRJNA1207547  SAMN49104768
32  SRR33993062        WGS      148.63  115123483  PRJNA1207547  SAMN49104767
33  SRR33993063        WGS      145.42  526460773  PRJNA1207547  SAMN49104766
34  SRR33993064        WGS      147.24  444362470  PRJNA1207547  SAMN49104765
35  SRR33993065        WGS      148.27  105099746  PRJNA1207547  SAMN49104764
36  SRR33993066        WGS      148.29   96593730  PRJNA1207547  SAMN49104763
37  SRR33993029        WGS      147.61  522807379  PRJNA1102327  SAMN49104751
38  SRR33993031        WGS      147.26  104663426  PRJNA1102327  SAMN49104750
39  SRR33993032        WGS      147.52  235901105  PRJNA1102327  SAMN49104749
40  SRR33993033        WGS      148.12  209453718  PRJNA1102327  SAMN49104748
41  SRR33993034        WGS      148.01  200396122  PRJNA1102327  SAMN49104747
42  SRR33993035        WGS      148.26  208159405  PRJNA1102327  SAMN49104746
43  SRR33993036        WGS      148.05  209968472  PRJNA1102327  SAMN49104745
44  SRR33993037        WGS      148.35  221485032  PRJNA1102327  SAMN49104744
45  SRR33993038        WGS      148.07  190312401  PRJNA1102327  SAMN49104743
46  SRR33993039        WGS      147.66  790397536  PRJNA1102327  SAMN49104742
47  SRR33993040        WGS      148.06  535205498  PRJNA1102327  SAMN49104741
48  SRR33993042        WGS      147.81  668807754  PRJNA1102327  SAMN49104740

   BioSampleModel      Bytes Center Name Collection_Date  ... name_state  \
0           Viral   22640539   USDA-NVSL            2025  ...        USA
1           Viral   21290975   USDA-NVSL            2025  ...        USA
2           Viral   15373063   USDA-NVSL            2025  ...        USA
3           Viral   15677039   USDA-NVSL            2025  ...        USA
4           Viral   21557873   USDA-NVSL            2025  ...        USA
5           Viral   24486243   USDA-NVSL            2025  ...        USA
6           Viral   18006567   USDA-NVSL            2025  ...        USA
7           Viral   17356512   USDA-NVSL            2025  ...        USA
8           Viral  204462787   USDA-NVSL            2025  ...        USA
9           Viral   85820855   USDA-NVSL            2025  ...        USA
10          Viral   85355492   USDA-NVSL            2025  ...        USA
11          Viral   66232769   USDA-NVSL            2025  ...        USA
12          Viral   64905708   USDA-NVSL            2025  ...        USA
13          Viral   16380741   USDA-NVSL            2025  ...        USA
14          Viral   39521904   USDA-NVSL            2025  ...        USA
15          Viral   23887383   USDA-NVSL            2025  ...        USA
16          Viral   23685525   USDA-NVSL            2025  ...        USA
17          Viral   21469946   USDA-NVSL            2025  ...        USA
18          Viral    8111306   USDA-NVSL            2025  ...        USA
19          Viral   68848188   USDA-NVSL            2025  ...        USA
20          Viral   63013857   USDA-NVSL            2025  ...        USA
21          Viral   68670191   USDA-NVSL            2025  ...        USA
22          Viral   56934198   USDA-NVSL            2025  ...        USA
23          Viral   30923309   USDA-NVSL            2025  ...        USA
24          Viral   77412197   USDA-NVSL            2025  ...        USA
25          Viral   59153989   USDA-NVSL            2025  ...        USA
26          Viral   35642264   USDA-NVSL            2025  ...        USA
27          Viral   24233116   USDA-NVSL            2025  ...        USA
28          Viral   19939253   USDA-NVSL            2025  ...        USA
29          Viral   50446456   USDA-NVSL            2025  ...        USA
30          Viral   57552218   USDA-NVSL            2025  ...        USA
31          Viral  129254335   USDA-NVSL            2025  ...        USA
32          Viral   41469704   USDA-NVSL            2025  ...        USA
33          Viral  186161216   USDA-NVSL            2025  ...        USA
34          Viral  157991689   USDA-NVSL            2025  ...        USA
35          Viral   37665516   USDA-NVSL            2025  ...        USA
36          Viral   34777840   USDA-NVSL            2025  ...        USA
37          Viral  185607037   USDA-NVSL            2025  ...        USA
38          Viral   37254008   USDA-NVSL            2025  ...        USA
39          Viral   83722829   USDA-NVSL            2025  ...        USA
40          Viral   74406813   USDA-NVSL            2025  ...        USA
41          Viral   71084273   USDA-NVSL            2025  ...        USA
42          Viral   74388676   USDA-NVSL            2025  ...        USA
43          Viral   75064716   USDA-NVSL            2025  ...        USA
44          Viral   78792165   USDA-NVSL            2025  ...        USA
45          Viral   67965403   USDA-NVSL            2025  ...        USA
46          Viral  282137009   USDA-NVSL            2025  ...        USA
47          Viral  189952374   USDA-NVSL            2025  ...        USA
48          Viral  236759389   USDA-NVSL            2025  ...        USA

         sample                 date       File Name  \
0   SRR33993023  2025-06-20_06-23-56  SRR33993023.fa
1   SRR33993024  2025-06-20_06-23-56  SRR33993024.fa
2   SRR33993025  2025-06-20_06-23-56  SRR33993025.fa
3   SRR33993026  2025-06-20_06-23-56  SRR33993026.fa
4   SRR33993027  2025-06-20_06-23-56  SRR33993027.fa
5   SRR33993028  2025-06-20_06-23-56  SRR33993028.fa
6   SRR33993030  2025-06-20_06-23-56  SRR33993030.fa
7   SRR33993041  2025-06-20_06-23-56  SRR33993041.fa
8   SRR33993043  2025-06-20_06-23-56  SRR33993043.fa
9   SRR33993044  2025-06-20_06-23-56  SRR33993044.fa
10  SRR33993045  2025-06-20_06-23-56  SRR33993045.fa
11  SRR33993046  2025-06-20_06-23-56  SRR33993046.fa
12  SRR33993047  2025-06-20_06-23-56  SRR33993047.fa
13  SRR33993048  2025-06-20_06-23-56  SRR33993048.fa
14  SRR33993049  2025-06-20_06-23-56  SRR33993049.fa
15  SRR33993050  2025-06-20_06-23-56  SRR33993050.fa
16  SRR33993051  2025-06-20_06-23-56  SRR33993051.fa
17  SRR33993052  2025-06-20_06-23-56  SRR33993052.fa
18  SRR33993053  2025-06-20_06-23-56  SRR33993053.fa
19  SRR33992696  2025-06-20_06-23-56  SRR33992696.fa
20  SRR33992697  2025-06-20_06-23-56  SRR33992697.fa
21  SRR33992698  2025-06-20_06-23-56  SRR33992698.fa
22  SRR33992699  2025-06-20_06-23-56  SRR33992699.fa
23  SRR33992700  2025-06-20_06-23-56  SRR33992700.fa
24  SRR33992701  2025-06-20_06-23-56  SRR33992701.fa
25  SRR33992702  2025-06-20_06-23-56  SRR33992702.fa
26  SRR33992703  2025-06-20_06-23-56  SRR33992703.fa
27  SRR33992704  2025-06-20_06-23-56  SRR33992704.fa
28  SRR33993166  2025-06-21_06-23-00  SRR33993166.fa
29  SRR33993059  2025-06-21_06-23-00  SRR33993059.fa
30  SRR33993060  2025-06-21_06-23-00  SRR33993060.fa
31  SRR33993061  2025-06-21_06-23-00  SRR33993061.fa
32  SRR33993062  2025-06-21_06-23-00  SRR33993062.fa
33  SRR33993063  2025-06-21_06-23-00  SRR33993063.fa
34  SRR33993064  2025-06-21_06-23-00  SRR33993064.fa
35  SRR33993065  2025-06-21_06-23-00  SRR33993065.fa
36  SRR33993066  2025-06-21_06-23-00  SRR33993066.fa
37  SRR33993029  2025-06-21_06-23-00  SRR33993029.fa
38  SRR33993031  2025-06-21_06-23-00  SRR33993031.fa
39  SRR33993032  2025-06-21_06-23-00  SRR33993032.fa
40  SRR33993033  2025-06-21_06-23-00  SRR33993033.fa
41  SRR33993034  2025-06-21_06-23-00  SRR33993034.fa
42  SRR33993035  2025-06-21_06-23-00  SRR33993035.fa
43  SRR33993036  2025-06-21_06-23-00  SRR33993036.fa
44  SRR33993037  2025-06-21_06-23-00  SRR33993037.fa
45  SRR33993038  2025-06-21_06-23-00  SRR33993038.fa
46  SRR33993039  2025-06-21_06-23-00  SRR33993039.fa
47  SRR33993040  2025-06-21_06-23-00  SRR33993040.fa
48  SRR33993042  2025-06-21_06-23-00  SRR33993042.fa

                                             Genotype  \
0                                               B3.13
1                                               B3.13
2                                               B3.13
3                                               B3.13
4                                               B3.13
5                                               B3.13
6   Not assigned: Only 7 segments >98.0% match fou...
7                                               B3.13
8                                               B3.13
9   Not assigned: Only 7 segments >98.0% match fou...
10                                              B3.13
11                                              B3.13
12  Not assigned: Only 7 segments >98.0% match fou...
13                                              B3.13
14                                              B3.13
15                                              B3.13
16                                              B3.13
17                                              B3.13
18                                              B3.13
19                                               D1.1
20                                               D1.1
21                                               D1.1
22                                               D1.1
23                                               D1.1
24                                               D1.1
25                                               D1.1
26                                               D1.1
27                                               D1.1
28                                               D1.1
29                                               D1.1
30  Not assigned: Only 6 segments >98.0% match fou...
31                                               D1.1
32  Not assigned: Only 7 segments >98.0% match fou...
33                                               D1.1
34                                               D1.1
35                                               D1.1
36                                               D1.1
37                                              B3.13
38                                              B3.13
39                                              B3.13
40                                              B3.13
41                                              B3.13
42                                              B3.13
43                                              B3.13
44                                              B3.13
45                                              B3.13
46                                              B3.13
47                                              B3.13
48                                              B3.13

                          Genotype List Used, >=98.0%  \
0   PB1:am4, PA:ea1, NA:ea1, PB2:am2.2, HA:ea1, NP...
1   NS:am1.1, MP:ea1, PA:ea1, PB2:am2.2, NP:am8, N...
2   NA:ea1, HA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, P...
3   HA:ea1, MP:ea1, NS:am1.1, PA:ea1, NP:am8, NA:e...
4   PB2:am2.2, MP:ea1, NA:ea1, HA:ea1, NS:am1.1, N...
5   NS:am1.1, NA:ea1, MP:ea1, PA:ea1, HA:ea1, NP:a...
6   PB1:am4, NP:am8, NS:am1.1, MP:ea1, NA:ea1, PA:...
7   NP:am8, NA:ea1, NS:am1.1, MP:ea1, PA:ea1, HA:e...
8   PB1:am4, MP:ea1, NA:ea1, PB2:am2.2, HA:ea1, NP...
9   MP:ea1, PA:ea1, NP:am8, PB2:am2.2, NS:am1.1, N...
10  NP:am8, MP:ea1, NS:am1.1, PA:ea1, PB2:am2.2, H...
11  NS:am1.1, PB1:am4, NP:am8, HA:ea1, NA:ea1, PA:...
12  PB1:am4, PB2:am2.2, NA:ea1, MP:ea1, NS:am1.1, ...
13  MP:ea1, NA:ea1, HA:ea1, PB1:am4, PB2:am2.2, NS...
14  NP:am8, HA:ea1, PA:ea1, NA:ea1, NS:am1.1, MP:e...
15  NA:ea1, MP:ea1, HA:ea1, NS:am1.1, PB2:am2.2, N...
16  PA:ea1, NS:am1.1, NP:am8, NA:ea1, HA:ea1, MP:e...
17  NA:ea1, MP:ea1, PB2:am2.2, NP:am8, PB1:am4, HA...
18  PA:ea1, PB2:am2.2, HA:ea1, NA:ea1, PB1:am4, NP...
19  PB2:am24, NS:ea3, PB1:ea3, PA:am4, NP:am13, HA...
20  MP:ea3, PB1:ea3, NA:am4N1, NS:ea3, PB2:am24, P...
21  NP:am13, PB1:ea3, MP:ea3, NS:ea3, HA:ea3, PB2:...
22  NP:am13, HA:ea3, PB2:am24, PB1:ea3, NA:am4N1, ...
23  NA:am4N1, NS:ea3, PB1:ea3, HA:ea3, NP:am13, PB...
24  MP:ea3, PB1:ea3, NS:ea3, HA:ea3, NP:am13, NA:a...
25  PB2:am24, NS:ea3, NA:am4N1, NP:am13, PA:am4, M...
26  PB1:ea3, MP:ea3, HA:ea3, NP:am13, NA:am4N1, PB...
27  PB1:ea3, PB2:am24, NA:am4N1, MP:ea3, PA:am4, N...
28  NA:am4N1, NS:ea3, NP:am13, PB1:ea3, PB2:am24, ...
29  PB1:ea3, PB2:am24, MP:ea3, PA:am4, NP:am13, HA...
30    NP:ea6, PB2:ea6, NS:ea6, PA:ea6, MP:ea6, HA:ea6
31  NP:am13, NS:ea3, PA:am4, HA:ea3, PB2:am24, PB1...
32  NA:am4N1, HA:ea3, PA:am4, NP:am13, NS:ea3, MP:...
33  NP:am13, HA:ea3, MP:ea3, PB1:ea3, NA:am4N1, NS...
34  HA:ea3, PA:am4, NP:am13, NA:am4N1, NS:ea3, MP:...
35  NP:am13, HA:ea3, NA:am4N1, PB1:ea3, NS:ea3, MP...
36  HA:ea3, MP:ea3, PA:am4, NA:am4N1, NS:ea3, NP:a...
37  NP:am8, NS:am1.1, MP:ea1, NA:ea1, PB1:am4, PA:...
38  NS:am1.1, PA:ea1, MP:ea1, NP:am8, HA:ea1, NA:e...
39  MP:ea1, NA:ea1, PA:ea1, PB2:am2.2, HA:ea1, PB1...
40  PA:ea1, NP:am8, MP:ea1, PB2:am2.2, NA:ea1, PB1...
41  PA:ea1, NP:am8, HA:ea1, NS:am1.1, NA:ea1, PB2:...
42  NA:ea1, HA:ea1, NS:am1.1, PB1:am4, MP:ea1, PB2...
43  NA:ea1, HA:ea1, PA:ea1, MP:ea1, PB1:am4, NS:am...
44  HA:ea1, NA:ea1, PB2:am2.2, NP:am8, MP:ea1, PA:...
45  PB1:am4, NA:ea1, HA:ea1, PA:ea1, NP:am8, PB2:a...
46  MP:ea1, PB1:am4, PA:ea1, PB2:am2.2, NP:am8, HA...
47  PA:ea1, MP:ea1, PB2:am2.2, NS:am1.1, PB1:am4, ...
48  NS:am1.1, PB1:am4, HA:ea1, NA:ea1, PB2:am2.2, ...

                           Genotype Sample Title List  \
0   am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...
1   am1.1:22-010085-001:NS, ea1:22-003707-003:MP, ...
2   ea1:22-003707-003:NA, ea1:22-003707-003:HA, am...
3   ea1:22-003707-003:HA, ea1:22-003707-003:MP, am...
4   am2.2:22-010445-001:PB2, ea1:22-003707-003:MP,...
5   am1.1:22-010085-001:NS, ea1:22-003707-003:NA, ...
6   am4:23-001855-001:PB1, am8:23-032005-001:NP, e...
7   am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
8   am4:23-001855-001:PB1, ea1:22-003707-003:MP, e...
9   ea1:22-003707-003:HA, ea1:22-003707-003:MP, ea...
10  am8:23-032005-001:NP, ea1:22-003707-003:MP, am...
11  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
12  am4:23-001855-001:PB1, am2.2:22-010445-001:PB2...
13  ea1:22-003707-003:MP, ea1:22-003707-003:NA, ea...
14  am8:23-032005-001:NP, ea1:22-003707-003:HA, ea...
15  ea1:22-003707-003:NA, ea1:22-003707-003:MP, ea...
16  ea1:22-003707-003:PA, am1.1:22-010085-001:NS, ...
17  ea1:22-003707-003:NA, ea1:22-003707-003:MP, am...
18  ea1:22-003707-003:PA, am2.2:22-010445-001:PB2,...
19  am24:24-030039-001:PB2, ea3:22-013001-001:NS, ...
20  ea3:22-013001-001:MP, ea3:22-013001-001:PB1, a...
21  am13:24-030039-001:NP, ea3:22-013001-001:PB1, ...
22  am13:24-030039-001:NP, ea3:22-013001-001:HA, a...
23  am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
24  ea3:22-013001-001:MP, ea3:22-013001-001:PB1, e...
25  am24:24-030039-001:PB2, ea3:22-013001-001:NS, ...
26  ea3:22-013001-001:PB1, ea3:22-013001-001:MP, e...
27  ea3:22-013001-001:PB1, am24:24-030039-001:PB2,...
28  am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
29  ea3:22-013001-001:PB1, am24:24-030039-001:PB2,...
30  ea6:23-004612-001:NP, ea6:23-004612-001:PB2, e...
31  am13:24-030039-001:NP, ea3:22-013001-001:NS, a...
32  am4N1:24-030039-001:NA, ea3:22-013001-001:HA, ...
33  am13:24-030039-001:NP, ea3:22-013001-001:HA, e...
34  ea3:22-013001-001:HA, am4:24-030039-001:PA, am...
35  am13:24-030039-001:NP, ea3:22-013001-001:HA, a...
36  ea3:22-013001-001:HA, ea3:22-013001-001:MP, am...
37  am8:23-032005-001:NP, am1.1:22-010085-001:NS, ...
38  am1.1:22-010085-001:NS, ea1:22-003707-003:PA, ...
39  ea1:22-003707-003:MP, ea1:22-003707-003:NA, ea...
40  ea1:22-003707-003:PA, am8:23-032005-001:NP, ea...
41  ea1:22-003707-003:PA, am8:23-032005-001:NP, ea...
42  ea1:22-003707-003:NA, ea1:22-003707-003:HA, am...
43  ea1:22-003707-003:NA, ea1:22-003707-003:HA, ea...
44  ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...
45  am4:23-001855-001:PB1, ea1:22-003707-003:NA, e...
46  ea1:22-003707-003:MP, am4:23-001855-001:PB1, e...
47  ea1:22-003707-003:PA, ea1:22-003707-003:MP, am...
48  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...

                          Genotype Percent Match List  \
0   99.34%, 98.93%, 98.79%, 98.51%, 98.30%, 99.00%...
1   99.05%, 98.88%, 98.75%, 98.47%, 99.06%, 98.94%...
2   98.94%, 98.12%, 99.05%, 98.47%, 98.78%, 99.21%...
3   98.30%, 98.78%, 98.93%, 98.88%, 98.93%, 98.65%...
4   98.51%, 98.78%, 98.65%, 98.30%, 98.93%, 98.93%...
5   98.93%, 98.72%, 98.78%, 98.88%, 98.30%, 98.93%...
6   99.16%, 98.93%, 97.95%, 98.69%, 98.88%, 98.44%...
7   98.93%, 98.58%, 98.69%, 98.88%, 98.88%, 98.30%...
8   99.30%, 98.78%, 98.65%, 98.51%, 98.42%, 98.93%...
9   97.95%, 98.88%, 98.88%, 98.93%, 98.33%, 98.69%...
10  98.86%, 98.78%, 99.05%, 98.70%, 98.47%, 98.42%...
11  99.05%, 99.34%, 98.86%, 98.42%, 98.65%, 98.70%...
12  99.16%, 98.29%, 97.71%, 98.58%, 98.47%, 98.33%...
13  98.78%, 98.79%, 98.62%, 99.34%, 98.50%, 98.93%...
14  98.73%, 98.18%, 98.84%, 98.79%, 99.17%, 99.08%...
15  98.72%, 98.68%, 98.24%, 99.05%, 98.51%, 98.93%...
16  98.93%, 99.05%, 98.86%, 98.86%, 98.24%, 98.78%...
17  98.58%, 98.88%, 98.51%, 98.93%, 99.56%, 98.30%...
18  98.65%, 98.55%, 98.06%, 98.51%, 99.47%, 98.93%...
19  99.56%, 98.81%, 99.25%, 99.40%, 99.47%, 99.35%...
20  100.00%, 99.25%, 99.04%, 98.93%, 99.47%, 99.35...
21  99.53%, 99.03%, 100.00%, 98.93%, 99.47%, 99.56...
22  99.47%, 99.47%, 99.52%, 99.16%, 99.04%, 100.00...
23  99.04%, 98.81%, 99.16%, 99.41%, 99.40%, 99.52%...
24  100.00%, 99.25%, 98.93%, 99.41%, 99.53%, 99.04...
25  99.52%, 98.93%, 99.04%, 99.60%, 99.44%, 99.90%...
26  99.16%, 100.00%, 99.41%, 99.53%, 99.04%, 99.52...
27  99.16%, 99.56%, 99.04%, 100.00%, 99.49%, 99.60...
28  98.95%, 98.93%, 99.53%, 99.21%, 99.61%, 99.47%...

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,name_state,sample,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List
0,SRR33993023,WGS,148.15,68132847,PRJNA1102327,SAMN49104730,Viral,22640539,USDA-NVSL,2025,...,USA,SRR33993023,2025-06-20_06-23-56,SRR33993023.fa,B3.13,"PB1:am4, PA:ea1, NA:ea1, PB2:am2.2, HA:ea1, NP...","am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...","99.34%, 98.93%, 98.79%, 98.51%, 98.30%, 99.00%...","15, 23, 17, 34, 29, 15, 8, 12",Ran on FASTA - No Coverage Report
1,SRR33993024,WGS,148.15,63105544,PRJNA1102327,SAMN49104729,Viral,21290975,USDA-NVSL,2025,...,USA,SRR33993024,2025-06-20_06-23-56,SRR33993024.fa,B3.13,"NS:am1.1, MP:ea1, PA:ea1, PB2:am2.2, NP:am8, N...","am1.1:22-010085-001:NS, ea1:22-003707-003:MP, ...","99.05%, 98.88%, 98.75%, 98.47%, 99.06%, 98.94%...","8, 11, 27, 35, 14, 15, 18, 31",Ran on FASTA - No Coverage Report
2,SRR33993025,WGS,148.28,46180111,PRJNA1102327,SAMN49104728,Viral,15373063,USDA-NVSL,2025,...,USA,SRR33993025,2025-06-20_06-23-56,SRR33993025.fa,B3.13,"NA:ea1, HA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, P...","ea1:22-003707-003:NA, ea1:22-003707-003:HA, am...","98.94%, 98.12%, 99.05%, 98.47%, 98.78%, 99.21%...","15, 32, 8, 35, 12, 18, 14, 27",Ran on FASTA - No Coverage Report
3,SRR33993026,WGS,147.53,47042737,PRJNA1102327,SAMN49104727,Viral,15677039,USDA-NVSL,2025,...,USA,SRR33993026,2025-06-20_06-23-56,SRR33993026.fa,B3.13,"HA:ea1, MP:ea1, NS:am1.1, PA:ea1, NP:am8, NA:e...","ea1:22-003707-003:HA, ea1:22-003707-003:MP, am...","98.30%, 98.78%, 98.93%, 98.88%, 98.93%, 98.65%...","29, 12, 9, 24, 16, 19, 35, 32",Ran on FASTA - No Coverage Report
4,SRR33993027,WGS,147.76,65389924,PRJNA1102327,SAMN49104726,Viral,21557873,USDA-NVSL,2025,...,USA,SRR33993027,2025-06-20_06-23-56,SRR33993027.fa,B3.13,"PB2:am2.2, MP:ea1, NA:ea1, HA:ea1, NS:am1.1, N...","am2.2:22-010445-001:PB2, ea1:22-003707-003:MP,...","98.51%, 98.78%, 98.65%, 98.30%, 98.93%, 98.93%...","34, 12, 19, 29, 9, 16, 24, 16",Ran on FASTA - No Coverage Report
5,SRR33993028,WGS,147.78,74054528,PRJNA1102327,SAMN49104725,Viral,24486243,USDA-NVSL,2025,...,USA,SRR33993028,2025-06-20_06-23-56,SRR33993028.fa,B3.13,"NS:am1.1, NA:ea1, MP:ea1, PA:ea1, HA:ea1, NP:a...","am1.1:22-010085-001:NS, ea1:22-003707-003:NA, ...","98.93%, 98.72%, 98.78%, 98.88%, 98.30%, 98.93%...","9, 18, 12, 24, 29, 16, 15, 34",Ran on FASTA - No Coverage Report
7,SRR33993041,WGS,147.27,52474370,PRJNA1102327,SAMN49104723,Viral,17356512,USDA-NVSL,2025,...,USA,SRR33993041,2025-06-20_06-23-56,SRR33993041.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, MP:ea1, PA:ea1, HA:e...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","98.93%, 98.58%, 98.69%, 98.88%, 98.88%, 98.30%...","16, 20, 11, 11, 24, 29, 34, 10",Ran on FASTA - No Coverage Report
8,SRR33993043,WGS,147.96,574015012,PRJNA1102327,SAMN49104739,Viral,204462787,USDA-NVSL,2025,...,USA,SRR33993043,2025-06-20_06-23-56,SRR33993043.fa,B3.13,"PB1:am4, MP:ea1, NA:ea1, PB2:am2.2, HA:ea1, NP...","am4:23-001855-001:PB1, ea1:22-003707-003:MP, e...","99.30%, 98.78%, 98.65%, 98.51%, 98.42%, 98.93%...","16, 12, 19, 34, 27, 16, 28, 8",Ran on FASTA - No Coverage Report
10,SRR33993045,WGS,148.34,238793868,PRJNA1102327,SAMN49104737,Viral,85355492,USDA-NVSL,2025,...,USA,SRR33993045,2025-06-20_06-23-56,SRR33993045.fa,B3.13,"NP:am8, MP:ea1, NS:am1.1, PA:ea1, PB2:am2.2, H...","am8:23-032005-001:NP, ea1:22-003707-003:MP, am...","98.86%, 98.78%, 99.05%, 98.70%, 98.47%, 98.42%...","17, 12, 8, 28, 35, 27, 15, 19",Ran on FASTA - No Coverage Report
11,SRR33993046,WGS,148.20,185103703,PRJNA1102327,SAMN49104736,Viral,66232769,USDA-NVSL,2025,...,USA,SRR33993046,2025-06-20_06-23-56,SRR33993046.fa,B3.13,"NS:am1.1, PB1:am4, NP:am8, HA:ea1, NA:ea1, PA:...","am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...","99.05%, 99.34%, 98.86%, 98.42%, 98.65%, 98.70%...","8, 15, 17, 27, 19, 28, 35, 12",Ran on FASTA - No Coverage Report
13,SRR33993048,WGS,132.54,45692579,PRJNA1102327,SAMN49104734,Viral,16380741,USDA-NVSL,2025,...,USA,SRR33993048,2025-06-20_06-23-56,SRR33993048.fa,B3.13,"MP:ea1, NA:ea1, HA:ea1, PB1:am4, PB2:am2.2, NS...","ea1:22-003707-003:MP, ea1:22-003707-003:NA, ea...","98.78%, 98.79%, 98.62%, 99.34%, 98.50%, 98.93%...","12, 17, 14, 15, 34, 9, 16, 23",Ran on FASTA - No Coverage Report
14,SRR33993049,WGS,148.89,108836285,PRJNA1102327,SAMN49104733,Viral,39521904,USDA-NVSL,2025,...,USA,SRR33993049,2025-06-20_06-23-56,SRR33993049.fa,B3.13,"NP:am8, HA:ea1, PA:ea1, NA:ea1, NS:am1.1, MP:e...","am8:23-032005-001:NP, ea1:22-003707-003:HA, ea...","98.73%, 98.18%, 98.84%, 98.79%, 99.17%, 99.08%...","19, 31, 25, 17, 7, 9, 34, 14",Ran on FASTA - No Coverage Report
15,SRR33993050,WGS,148.32,72069095,PRJNA1102327,SAMN49104732,Viral,23887383,USDA-NVSL,2025,...,USA,SRR33993050,2025-06-20_06-23-56,SRR33993050.fa,B3.13,"NA:ea1, MP:ea1, HA:ea1, NS:am1.1, PB2:am2.2, N...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, ea...","98.72%, 98.68%, 98.24%, 99.05%, 98.51%, 98.93%...","18, 13, 30, 8, 34, 16, 23, 18",Ran on FASTA - No Coverage Report
16,SRR33993051,WGS,148.13,71854425,PRJNA1102327,SAMN49104731,Viral,23685525,USDA-NVSL,2025,...,USA,SRR33993051,2025-06-20_06-23-56,SRR33993051.fa,B3.13,"PA:ea1, NS:am1.1, NP:am8, NA:ea1, HA:ea1, MP:e...","ea1:22-003707-003:PA, am1.1:22-010085-001:NS, ...","98.93%, 99.05%, 98.86%, 98.86%, 98.24%, 98.78%...","23, 8, 17, 16, 30, 12, 34, 17",Ran on FASTA - No Coverage Report
17,SRR33993052,WGS,147.03,65353759,PRJNA1102327,SAMN49104722,Viral,21469946,USDA-NVSL,2025,...,USA,SRR33993052,2025-06-20_06-23-56,SRR33993052.fa,B3.13,"NA:ea1, MP:ea1, PB2:am2.2, NP:am8, PB1:am4, HA...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, am...","98.58%, 98.88%, 98.51%, 98.93%, 99.56%, 98.30%...","20, 11, 34, 16, 10, 29, 11, 25",Ran on FASTA - No Coverage Report
18,SRR33993053,WGS,146.19,24058580,PRJNA1102327,SAMN49104721,Viral,8111306,USDA-NVSL,2025,...,USA,SRR33993053,2025-06-20_06-23-56,SRR33993053.fa,B3.13,"PA:ea1, PB2:am2.2, HA:ea1, NA:ea1, PB1:am4, NP...","ea1:22-003707-003:PA, am2.2:22-010445-001:PB2,...","98.65%, 98.55%, 98.06%, 98.51%, 99.47%, 98.93%...","29, 33, 33, 21, 12, 16, 9, 12",Ran on FASTA - No Coverage Report
19,SRR33992696,WGS,148.85,190626822,PRJNA980729,SAMN49104545,Viral,68848188,USDA-NVSL,2025,...,USA,SRR33992696,2025-06-20_06-23-56,SRR33992696.fa,D1.1,"PB2:am24, NS:ea3, PB1:ea3, PA:am4, NP:am13, HA...","am24:24-030039-001:PB2, ea3:22-013001-001:NS, ...","99.56%, 98.81%, 99.25%, 99.40%, 99.47%, 99.35%...","10, 10, 17, 13, 8, 11, 10, 1",Ran on FASTA - No Coverage Report
20,SRR33992697,WGS,148.65,174204267,PRJNA980729,SAMN49104544,Viral,63013857,USDA-NVSL,2025,...,USA,SRR33992697,2025-06-20_06-23-56,SRR33992697.fa,D1.1,"MP:ea3, PB1:ea3, NA:am4N1, NS:ea3, PB2:am24, P...","ea3:22-013001-001:MP, ea3:22-013001-001:PB1, a...","100.00%, 99.25%, 99.04%, 98.93%, 99.47%, 99.35...","0, 17, 10, 9, 12, 14, 8, 9",Ran on FASTA - No Coverage Report
21,SRR33992698,WGS,148.81,190847180,PRJNA980729,SAMN49104543,Viral,68670191,USDA-NVSL,2025,...,USA,SRR33992698,2025-06-20_06-23-56,SRR33992698.fa,D1.1,"NP:am13, PB1:ea3, MP:ea3, NS:ea3, HA:ea3, PB2:...","am13:24-030039-001:NP, ea3:22-013001-001:PB1, ...","99.53%, 99.03%, 100.00%, 98.93%, 99.47%, 99.56...","7, 22, 0, 9, 9, 10, 7, 11",Ran on FASTA - No Coverage Report
22,SRR33992699,WGS,149.03,157118049,PRJNA980729,SAMN49104542,Viral,56934198,USDA-NVSL,2025,...,USA,SRR33992699,2025-06-20_06-23-56,SRR33992699.fa,D1.1,"NP:am13, HA:ea3, PB2:am24, PB1:ea3, NA:am4N1, ...","am13:24-030039-001:NP, ea3:22-013001-001:HA, a...","99.47%, 99.47%, 99.52%, 99.16%, 99.04%, 100.00...","8, 9, 11, 19, 10, 0, 10, 12",Ran on FASTA - No Coverage Report
23,SRR33992700,WGS,149.39,85416600,PRJNA980729,SAMN49104541,Viral,30923309,USDA-NVSL,2025,...,USA,SRR33992700,2025-06-20_06-23-56,SRR33992700.fa,D1.1,"NA:am4N1, NS:ea3, PB1:ea3, HA:ea3, NP:am13, PB...","am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...","99.04%, 98.81%, 99.16%, 99.41%, 99.40%, 99.52%...","10, 10, 19, 10, 9, 11, 1, 13",Ran on FASTA - No Coverage Report
24,SRR33992701,WGS,148.74,215621548,PRJNA980729,SAMN49104540,Viral,77412197,USDA-NVSL,2025,...,USA,SRR33992701,2025-06-20_06-23-56,SRR33992701.fa,D1.1,"MP:ea3, PB1:ea3, NS:ea3, HA:ea3, NP:am13, NA:a...","ea3:22-013001-001:MP, ea3:22-013001-001:PB1, e...","100.00%, 99.25%, 98.93%, 99.41%, 99.53%, 99.04...","0, 17, 9, 10, 7, 10, 11, 11",Ran on FASTA - No Coverage Report
25,SRR33992702,WGS,148.58,164485298,PRJNA980729,SAMN49104539,Viral,59153989,USDA-NVSL,2025,...,USA,SRR33992702,2025-06-20_06-23-56,SRR33992702.fa,D1.1,"PB2:am24, NS:ea3, NA:am4N1, NP:am13, PA:am4, M...","am24:24-030039-001:PB2, ea3:22-013001-001:NS, ...","99.52%, 98.93%, 99.04%, 99.60%, 99.44%, 99.90%...","11, 9, 10, 6, 12, 1, 9, 17",Ran on FASTA - No Coverage Report
26,SRR33992703,WGS,147.69,108646876,PRJNA980729,SAMN49104538,Viral,35642264,USDA-NVSL,2025,...,USA,SRR33992703,2025-06-20_06-23-56,SRR33992703.fa,D1.1,"PB1:ea3, MP:ea3, HA:ea3, NP:am13, NA:am4N1, PB...","ea3:22-013001-001:PB1, ea3:22-013001-001:MP, e...","99.16%, 100.00%, 99.41%, 99.53%, 99.04%, 99.52...","19, 0, 10, 7, 10, 11, 9, 12",Ran on FASTA - No Coverage Report
27,SRR33992704,WGS,147.91,73320377,PRJNA980729,SAMN49104537,Viral,24233116,USDA-NVSL,2025,...,USA,SRR33992704,2025-06-20_06-23-56,SRR33992704.fa,D1.1,"PB1:ea3, PB2:am24, NA:am4N1, MP:ea3, PA:am4, N...","ea3:22-013001-001:PB1, am24:24-030039-001:PB2,...","99.16%, 99.56%, 99.04%, 100.00%, 99.49%, 99.60...","19, 10, 10, 0, 11, 6, 10, 9",Ran on FASTA - No Coverage Report
28,SRR33993166,WGS,147.75,60982523,PRJNA1219588,SAMN49104924,Viral,19939253,USDA-NVSL,2025,...,USA,SRR33993166,2025-06-21_06-23-00,SRR33993166.fa,D1.1,"NA:am4N1, NS:ea3, NP:am13, PB1:ea3, PB2:am24, ...","am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...","98.95%, 98.93%, 99.53%, 99.21%, 99.61%, 99.47%...","11, 9, 7, 18, 9, 9, 1, 11",Ran on FASTA - No Coverage Report
29,SRR33993059,WGS,148.77,139963922,PRJNA1207547,SAMN49104770,Viral,50446456,USDA-NVSL,2025,...,USA,SRR33993059,2025-06-21_06-23-00,SRR33993059.fa,D1.1,"PB1:ea3, PB2:am24, MP:ea3, PA:am4, NP:am13, HA...","ea3:22-013001-001:PB1, am24:24-030039-001:PB2,...","99.25%, 99.74%, 99.69%, 99.63%, 99.87%, 99.41%...","17, 6, 3, 8, 2, 10, 7, 13",Ran on FASTA - No Coverage Report
31,SRR33993061,WGS,147.20,363257804,PRJNA1207547,SAMN49104768,Viral,129254335,USDA-NVSL,2025,...,USA,SRR33993061,2025-06-21_06-23-00,SRR33993061.fa,D1.1,"NP:am13, NS:ea3, PA:am4, HA:ea3, PB2:am24, PB1...","am13:24-030039-001:NP, ea3:22-013001-001:NS, a...","99.53%, 99.28%, 98.37%, 99.41%, 99.74%, 99.38%...","7, 6, 35, 10, 6, 14, 12, 2",Ran on FASTA - No Coverage Report
33,SRR33993063,WGS,145.42,526460773,PRJNA1207547,SAMN49104766,Viral,186161216,USDA-NVSL,2025,...,USA,SRR33993063,2025-06-21_06-23-00,SRR33993063.fa,D1.1,"NP:am13, HA:ea3, MP:ea3, PB1:ea3, NA:am4N1, NS...","am13:24-030039-001:NP, ea3:22-013001-001:HA, e...","99.80%, 99.18%, 99.90%, 99.34%, 99.30%, 99.17%...","3, 14, 1, 15, 8, 7, 3, 8",Ran on FASTA - No Coverage Report
34,SRR33993064,WGS,147.24,444362470,PRJNA1207547,SAMN49104765,Viral,157991689,USDA-NVSL,2025,...,USA,SRR33993064,2025-06-21_06-23-00,SRR33993064.fa,D1.1,"HA:ea3, PA:am4, NP:am13, NA:am4N1, NS:ea3, MP:...","ea3:22-013001-001:HA, am4:24-030039-001:PA, am...","99.24%, 99.60%, 99.80%, 99.04%, 99.17%, 99.90%...","13, 7, 3, 11, 7, 1, 15, 5",Ran on FASTA - No Coverage Report
35,SRR33993065,WGS,148.27,105099746,PRJNA1207547,SAMN49104764,Viral,37665516,USDA-NVSL,2025,...,USA,SRR33993065,2025-06-21_06-23-00,SRR33993065.fa,D1.1,"NP:am13, HA:ea3, NA:am4N1, PB1:ea3, NS:ea3, MP...","am13:24-030039-001:NP, ea3:22-013001-001:HA, a...","99.67%, 99.53%, 99.62%, 98.89%, 99.17%, 99.69%...","5, 8, 4, 9, 7, 3, 3, 2",Ran on FASTA - No Coverage Report
36,SRR33993066,WGS,148.29,96593730,PRJNA1207547,SAMN49104763,Viral,34777840,USDA-NVSL,2025,...,USA,SRR33993066,2025-06-21_06-23-00,SRR33993066.fa,D1.1,"HA:ea3, MP:ea3, PA:am4, NA:am4N1, NS:ea3, NP:a...","ea3:22-013001-001:HA, ea3:22-013001-001:MP, am...","99.65%, 99.90%, 100.00%, 99.23%, 98.81%, 99.93...","6, 1, 0, 8, 10, 1, 1, 1",Ran on FASTA - No Coverage Report
37,SRR33993029,WGS,147.61,522807379,PRJNA1102327,SAMN49104751,Viral,185607037,USDA-NVSL,2025,...,USA,SRR33993029,2025-06-21_06-23-00,SRR33993029.fa,B3.13,"NP:am8, NS:am1.1, MP:ea1, NA:ea1, PB1:am4, PA:...","am8:23-032005-001:NP, am1.1:22-010085-001:NS, ...","98.86%, 98.69%, 98.88%, 98.51%, 99.12%, 98.88%...","17, 11, 11, 21, 20, 24, 33, 38",Ran on FASTA - No Coverage Report
38,SRR33993031,WGS,147.26,104663426,PRJNA1102327,SAMN49104750,Viral,37254008,USDA-NVSL,2025,...,USA,SRR33993031,2025-06-21_06-23-00,SRR33993031.fa,B3.13,"NS:am1.1, PA:ea1, MP:ea1, NP:am8, HA:ea1, NA:e...","am1.1:22-010085-001:NS, ea1:22-003707-003:PA, ...","98.93%, 98.88%, 98.78%, 98.93%, 98.30%, 98.72%...","9, 24, 12, 16, 29, 18, 34, 15",Ran on FASTA - No Coverage Report
39,SRR33993032,WGS,147.52,235901105,PRJNA1102327,SAMN49104749,Viral,83722829,USDA-NVSL,2025,...,USA,SRR33993032,2025-06-21_06-23-00,SRR33993032.fa,B3.13,"MP:ea1, NA:ea1, PA:ea1, PB2:am2.2, HA:ea1, PB1...","ea1:22-003707-003:MP, ea1:22-003707-003:NA, ea...","98.78%, 98.72%, 98.88%, 98.51%, 98.30%, 99.38%...","12, 18, 24, 34, 29, 14, 16, 9",Ran on FASTA - No Coverage Report
40,SRR33993033,WGS,148.12,209453718,PRJNA1102327,SAMN49104748,Viral,74406813,USDA-NVSL,2025,...,USA,SRR33993033,2025-06-21_06-23-00,SRR33993033.fa,B3.13,"PA:ea1, NP:am8, MP:ea1, PB2:am2.2, NA:ea1, PB1...","ea1:22-003707-003:PA, am8:23-032005-001:NP, ea...","98.88%, 98.93%, 98.78%, 98.51%, 98.72%, 99.34%...","24, 16, 12, 34, 18, 15, 9, 29",Ran on FASTA - No Coverage Report
41,SRR33993034,WGS,148.01,200396122,PRJNA1102327,SAMN49104747,Viral,71084273,USDA-NVSL,2025,...,USA,SRR33993034,2025-06-21_06-23-00,SRR33993034.fa,B3.13,"PA:ea1, NP:am8, HA:ea1, NS:am1.1, NA:ea1, PB2:...","ea1:22-003707-003:PA, am8:23-032005-001:NP, ea...","98.88%, 98.93%, 98.30%, 98.93%, 98.72%, 98.51%...","24, 16, 29, 9, 18, 34, 12, 15",Ran on FASTA - No Coverage Report
42,SRR33993035,WGS,148.26,208159405,PRJNA1102327,SAMN49104746,Viral,74388676,USDA-NVSL,2025,...,USA,SRR33993035,2025-06-21_06-23-00,SRR33993035.fa,B3.13,"NA:ea1, HA:ea1, NS:am1.1, PB1:am4, MP:ea1, PB2...","ea1:22-003707-003:NA, ea1:22-003707-003:HA, am...","98.72%, 98.30%, 98.93%, 99.34%, 98.78%, 98.51%...","18, 29, 9, 15, 12, 34, 16, 24",Ran on FASTA - No Coverage Report
43,SRR33993036,WGS,148.05,209968472,PRJNA1102327,SAMN49104745,Viral,75064716,USDA-NVSL,2025,...,USA,SRR33993036,2025-06-21_06-23-00,SRR33993036.fa,B3.13,"NA:ea1, HA:ea1, PA:ea1, MP:ea1, PB1:am4, NS:am...","ea1:22-003707-003:NA, ea1:22-003707-003:HA, ea...","98.72%, 98.30%, 98.88%, 98.78%, 99.34%, 98.93%...","18, 29, 24, 12, 15, 9, 34, 16",Ran on FASTA - No Coverage Report
44,SRR33993037,WGS,148.35,221485032,PRJNA1102327,SAMN49104744,Viral,78792165,USDA-NVSL,2025,...,USA,SRR33993037,2025-06-21_06-23-00,SRR33993037.fa,B3.13,"HA:ea1, NA:ea1, PB2:am2.2, NP:am8, MP:ea1, PA:...","ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...","98.30%, 98.72%, 98.51%, 98.93%, 98.78%, 98.88%...","29, 18, 34, 16, 12, 24, 9, 15",Ran on FASTA - No Coverage Report
45,SRR33993038,WGS,148.07,190312401,PRJNA1102327,SAMN49104743,Viral,67965403,USDA-NVSL,2025,...,USA,SRR33993038,2025-06-21_06-23-00,SRR33993038.fa,B3.13,"PB1:am4, NA:ea1, HA:ea1, PA:ea1, NP:am8, PB2:a...","am4:23-001855-001:PB1, ea1:22-003707-003:NA, e...","99.34%, 98.72%, 98.30%, 98.88%, 98.93%, 98.51%...","15, 18, 29, 24, 16, 34, 12, 9",Ran on FASTA - No Coverage Report
46,SRR33993039,WGS,147.66,790397536,PRJNA1102327,SAMN49104742,Viral,282137009,USDA-NVSL,2025,...,USA,SRR33993039,2025-06-21_06-23-00,SRR33993039.fa,B3.13,"MP:ea1, PB1:am4, PA:ea1, PB2:am2.2, NP:am8, HA...","ea1:22-003707-003:MP, am4:23-001855-001:PB1, e...","98.78%, 99.34%, 98.88%, 98.51%, 98.93%, 98.30%...","12, 15, 24, 34, 16, 29, 18, 9",Ran on FASTA - No Coverage Report
47,SRR33993040,WGS,148.06,535205498,PRJNA1102327,SAMN49104741,Viral,189952374,USDA-NVSL,2025,...,USA,SRR33993040,2025-06-21_06-23-00,SRR33993040.fa,B3.13,"PA:ea1, MP:ea1, PB2:am2.2, NS:am1.1, PB1:am4, ...","ea1:22-003707-003:PA, ea1:22-003707-003:MP, am...","98.75%, 98.78%, 98.55%, 99.05%, 99.34%, 98.93%...","27, 12, 33, 8, 15, 16, 27, 19",Ran on FASTA - No Coverage Report
48,SRR33993042,WGS,147.81,668807754,PRJNA1102327,SAMN49104740,Viral,236759389,USDA-NVSL,2025,...,USA,SRR33993042,2025-06-21_06-23-00,SRR33993042.fa,B3.13,"NS:am1.1, PB1:am4, HA:ea1, NA:ea1, PB2:am2.2, ...","am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...","99.05%, 99.30%, 98.42%, 98.65%, 98.51%, 98.78%...","8, 16, 27, 19, 34, 12, 28, 16",Ran on FASTA - No Coverage Report

In [5]:
# Get specific geolocation and name_state from genbank_mapping.tsv

genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
genbank_mapping["Run"] = genbank_mapping["sra_run"]
genbank_mapping = genbank_mapping.drop_duplicates(subset="Run", keep="first") # Drop duplicates
genbank_mapping["name_state"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[2]) # Get the name of the state

# print(genbank_mapping)

# metadata_genbank = metadata.merge(genbank_mapping, on=["Run"]) # Only include data that has states

# Get geolocation for second state attribute

os.chdir(home + "references/")
state_ref = pd.read_csv("states_ref.csv")
metadata["Geo_Location"] = metadata["name_state"].apply(lambda x: 
                                                        state_ref.loc[state_ref["Abbreviation"] == x, 'Country'].iloc[0] 
                                                        + "-" + 
                                                        x if x in state_ref["Abbreviation"].values 
                                                        else state_ref.loc[state_ref['State'].str.contains('|'.join(x.replace(', ', ' ').split(' ')), regex=True), 'Country'].iloc[0]
                                                        + "-" + 
                                                        state_ref.loc[state_ref['State'].str.contains('|'.join(x.replace(', ', ' ').split(' ')), regex=True), 'Abbreviation'].iloc[0] 
                                                        if state_ref["State"].str.contains("|".join((x.replace(", ", " ").split(" "))), regex=True).any() 
                                                        else x)

print(state_ref.loc[state_ref['State'].str.contains('|'.join("Kentucky, whatever".replace(',', ' ').split(' ')), regex=True), 'Abbreviation'])
print(state_ref['State'].str.contains('|'.join("Kentucky, whatever".replace(', ', ' ').split(' ')), regex=True))
print(metadata["name_state"])
print(metadata["Geo_Location"])
print(len(metadata))
display(metadata) # Maybe there is no state information since 3/18/2025?

0     AL
1     AK
2     AZ
3     AR
4     AS
      ..
65    ON
66    PE
67    QC
68    SK
69    YT
Name: Abbreviation, Length: 70, dtype: object
0     False
1     False
2     False
3     False
4     False
      ...
65    False
66    False
67    False
68    False
69    False
Name: State, Length: 70, dtype: bool
0     USA
1     USA
2     USA
3     USA
4     USA
5     USA
7     USA
8     USA
10    USA
11    USA
13    USA
14    USA
15    USA
16    USA
17    USA
18    USA
19    USA
20    USA
21    USA
22    USA
23    USA
24    USA
25    USA
26    USA
27    USA
28    USA
29    USA
31    USA
33    USA
34    USA
35    USA
36    USA
37    USA
38    USA
39    USA
40    USA
41    USA
42    USA
43    USA
44    USA
45    USA
46    USA
47    USA
48    USA
Name: name_state, dtype: object
0     USA
1     USA
2     USA
3     USA
4     USA
5     USA
7     USA
8     USA
10    USA
11    USA
13    USA
14    USA
15    USA
16    USA
17    USA
18    USA
19    USA
20    USA
21    USA
22    USA
23    USA
24    USA
25    USA
26    USA
27    USA
28    USA
29    USA
31    USA
33    USA
34    USA
35    USA
36    USA
37    USA
38    USA
39    USA
40    USA
41    USA
42    USA
43    USA
44    USA
45    USA
46    USA
47    USA
48    USA
Name: Geo_Location, dtype: object
44

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,sample,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,Geo_Location
0,SRR33993023,WGS,148.15,68132847,PRJNA1102327,SAMN49104730,Viral,22640539,USDA-NVSL,2025,...,SRR33993023,2025-06-20_06-23-56,SRR33993023.fa,B3.13,"PB1:am4, PA:ea1, NA:ea1, PB2:am2.2, HA:ea1, NP...","am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...","99.34%, 98.93%, 98.79%, 98.51%, 98.30%, 99.00%...","15, 23, 17, 34, 29, 15, 8, 12",Ran on FASTA - No Coverage Report,USA
1,SRR33993024,WGS,148.15,63105544,PRJNA1102327,SAMN49104729,Viral,21290975,USDA-NVSL,2025,...,SRR33993024,2025-06-20_06-23-56,SRR33993024.fa,B3.13,"NS:am1.1, MP:ea1, PA:ea1, PB2:am2.2, NP:am8, N...","am1.1:22-010085-001:NS, ea1:22-003707-003:MP, ...","99.05%, 98.88%, 98.75%, 98.47%, 99.06%, 98.94%...","8, 11, 27, 35, 14, 15, 18, 31",Ran on FASTA - No Coverage Report,USA
2,SRR33993025,WGS,148.28,46180111,PRJNA1102327,SAMN49104728,Viral,15373063,USDA-NVSL,2025,...,SRR33993025,2025-06-20_06-23-56,SRR33993025.fa,B3.13,"NA:ea1, HA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, P...","ea1:22-003707-003:NA, ea1:22-003707-003:HA, am...","98.94%, 98.12%, 99.05%, 98.47%, 98.78%, 99.21%...","15, 32, 8, 35, 12, 18, 14, 27",Ran on FASTA - No Coverage Report,USA
3,SRR33993026,WGS,147.53,47042737,PRJNA1102327,SAMN49104727,Viral,15677039,USDA-NVSL,2025,...,SRR33993026,2025-06-20_06-23-56,SRR33993026.fa,B3.13,"HA:ea1, MP:ea1, NS:am1.1, PA:ea1, NP:am8, NA:e...","ea1:22-003707-003:HA, ea1:22-003707-003:MP, am...","98.30%, 98.78%, 98.93%, 98.88%, 98.93%, 98.65%...","29, 12, 9, 24, 16, 19, 35, 32",Ran on FASTA - No Coverage Report,USA
4,SRR33993027,WGS,147.76,65389924,PRJNA1102327,SAMN49104726,Viral,21557873,USDA-NVSL,2025,...,SRR33993027,2025-06-20_06-23-56,SRR33993027.fa,B3.13,"PB2:am2.2, MP:ea1, NA:ea1, HA:ea1, NS:am1.1, N...","am2.2:22-010445-001:PB2, ea1:22-003707-003:MP,...","98.51%, 98.78%, 98.65%, 98.30%, 98.93%, 98.93%...","34, 12, 19, 29, 9, 16, 24, 16",Ran on FASTA - No Coverage Report,USA
5,SRR33993028,WGS,147.78,74054528,PRJNA1102327,SAMN49104725,Viral,24486243,USDA-NVSL,2025,...,SRR33993028,2025-06-20_06-23-56,SRR33993028.fa,B3.13,"NS:am1.1, NA:ea1, MP:ea1, PA:ea1, HA:ea1, NP:a...","am1.1:22-010085-001:NS, ea1:22-003707-003:NA, ...","98.93%, 98.72%, 98.78%, 98.88%, 98.30%, 98.93%...","9, 18, 12, 24, 29, 16, 15, 34",Ran on FASTA - No Coverage Report,USA
7,SRR33993041,WGS,147.27,52474370,PRJNA1102327,SAMN49104723,Viral,17356512,USDA-NVSL,2025,...,SRR33993041,2025-06-20_06-23-56,SRR33993041.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, MP:ea1, PA:ea1, HA:e...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","98.93%, 98.58%, 98.69%, 98.88%, 98.88%, 98.30%...","16, 20, 11, 11, 24, 29, 34, 10",Ran on FASTA - No Coverage Report,USA
8,SRR33993043,WGS,147.96,574015012,PRJNA1102327,SAMN49104739,Viral,204462787,USDA-NVSL,2025,...,SRR33993043,2025-06-20_06-23-56,SRR33993043.fa,B3.13,"PB1:am4, MP:ea1, NA:ea1, PB2:am2.2, HA:ea1, NP...","am4:23-001855-001:PB1, ea1:22-003707-003:MP, e...","99.30%, 98.78%, 98.65%, 98.51%, 98.42%, 98.93%...","16, 12, 19, 34, 27, 16, 28, 8",Ran on FASTA - No Coverage Report,USA
10,SRR33993045,WGS,148.34,238793868,PRJNA1102327,SAMN49104737,Viral,85355492,USDA-NVSL,2025,...,SRR33993045,2025-06-20_06-23-56,SRR33993045.fa,B3.13,"NP:am8, MP:ea1, NS:am1.1, PA:ea1, PB2:am2.2, H...","am8:23-032005-001:NP, ea1:22-003707-003:MP, am...","98.86%, 98.78%, 99.05%, 98.70%, 98.47%, 98.42%...","17, 12, 8, 28, 35, 27, 15, 19",Ran on FASTA - No Coverage Report,USA
11,SRR33993046,WGS,148.20,185103703,PRJNA1102327,SAMN49104736,Viral,66232769,USDA-NVSL,2025,...,SRR33993046,2025-06-20_06-23-56,SRR33993046.fa,B3.13,"NS:am1.1, PB1:am4, NP:am8, HA:ea1, NA:ea1, PA:...","am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...","99.05%, 99.34%, 98.86%, 98.42%, 98.65%, 98.70%...","8, 15, 17, 27, 19, 28, 35, 12",Ran on FASTA - No Coverage Report,USA
13,SRR33993048,WGS,132.54,45692579,PRJNA1102327,SAMN49104734,Viral,16380741,USDA-NVSL,2025,...,SRR33993048,2025-06-20_06-23-56,SRR33993048.fa,B3.13,"MP:ea1, NA:ea1, HA:ea1, PB1:am4, PB2:am2.2, NS...","ea1:22-003707-003:MP, ea1:22-003707-003:NA, ea...","98.78%, 98.79%, 98.62%, 99.34%, 98.50%, 98.93%...","12, 17, 14, 15, 34, 9, 16, 23",Ran on FASTA - No Coverage Report,USA
14,SRR33993049,WGS,148.89,108836285,PRJNA1102327,SAMN49104733,Viral,39521904,USDA-NVSL,2025,...,SRR33993049,2025-06-20_06-23-56,SRR33993049.fa,B3.13,"NP:am8, HA:ea1, PA:ea1, NA:ea1, NS:am1.1, MP:e...","am8:23-032005-001:NP, ea1:22-003707-003:HA, ea...","98.73%, 98.18%, 98.84%, 98.79%, 99.17%, 99.08%...","19, 31, 25, 17, 7, 9, 34, 14",Ran on FASTA - No Coverage Report,USA
15,SRR33993050,WGS,148.32,72069095,PRJNA1102327,SAMN49104732,Viral,23887383,USDA-NVSL,2025,...,SRR33993050,2025-06-20_06-23-56,SRR33993050.fa,B3.13,"NA:ea1, MP:ea1, HA:ea1, NS:am1.1, PB2:am2.2, N...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, ea...","98.72%, 98.68%, 98.24%, 99.05%, 98.51%, 98.93%...","18, 13, 30, 8, 34, 16, 23, 18",Ran on FASTA - No Coverage Report,USA
16,SRR33993051,WGS,148.13,71854425,PRJNA1102327,SAMN49104731,Viral,23685525,USDA-NVSL,2025,...,SRR33993051,2025-06-20_06-23-56,SRR33993051.fa,B3.13,"PA:ea1, NS:am1.1, NP:am8, NA:ea1, HA:ea1, MP:e...","ea1:22-003707-003:PA, am1.1:22-010085-001:NS, ...","98.93%, 99.05%, 98.86%, 98.86%, 98.24%, 98.78%...","23, 8, 17, 16, 30, 12, 34, 17",Ran on FASTA - No Coverage Report,USA
17,SRR33993052,WGS,147.03,65353759,PRJNA1102327,SAMN49104722,Viral,21469946,USDA-NVSL,2025,...,SRR33993052,2025-06-20_06-23-56,SRR33993052.fa,B3.13,"NA:ea1, MP:ea1, PB2:am2.2, NP:am8, PB1:am4, HA...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, am...","98.58%, 98.88%, 98.51%, 98.93%, 99.56%, 98.30%...","20, 11, 34, 16, 10, 29, 11, 25",Ran on FASTA - No Coverage Report,USA
18,SRR33993053,WGS,146.19,24058580,PRJNA1102327,SAMN49104721,Viral,8111306,USDA-NVSL,2025,...,SRR33993053,2025-06-20_06-23-56,SRR33993053.fa,B3.13,"PA:ea1, PB2:am2.2, HA:ea1, NA:ea1, PB1:am4, NP...","ea1:22-003707-003:PA, am2.2:22-010445-001:PB2,...","98.65%, 98.55%, 98.06%, 98.51%, 99.47%, 98.93%...","29, 33, 33, 21, 12, 16, 9, 12",Ran on FASTA - No Coverage Report,USA
19,SRR33992696,WGS,148.85,190626822,PRJNA980729,SAMN49104545,Viral,68848188,USDA-NVSL,2025,...,SRR33992696,2025-06-20_06-23-56,SRR33992696.fa,D1.1,"PB2:am24, NS:ea3, PB1:ea3, PA:am4, NP:am13, HA...","am24:24-030039-001:PB2, ea3:22-013001-001:NS, ...","99.56%, 98.81%, 99.25%, 99.40%, 99.47%, 99.35%...","10, 10, 17, 13, 8, 11, 10, 1",Ran on FASTA - No Coverage Report,USA
20,SRR33992697,WGS,148.65,174204267,PRJNA980729,SAMN49104544,Viral,63013857,USDA-NVSL,2025,...,SRR33992697,2025-06-20_06-23-56,SRR33992697.fa,D1.1,"MP:ea3, PB1:ea3, NA:am4N1, NS:ea3, PB2:am24, P...","ea3:22-013001-001:MP, ea3:22-013001-001:PB1, a...","100.00%, 99.25%, 99.04%, 98.93%, 99.47%, 99.35...","0, 17, 10, 9, 12, 14, 8, 9",Ran on FASTA - No Coverage Report,USA
21,SRR33992698,WGS,148.81,190847180,PRJNA980729,SAMN49104543,Viral,68670191,USDA-NVSL,2025,...,SRR33992698,2025-06-20_06-23-56,SRR33992698.fa,D1.1,"NP:am13, PB1:ea3, MP:ea3, NS:ea3, HA:ea3, PB2:...","am13:24-030039-001:NP, ea3:22-013001-001:PB1, ...","99.53%, 99.03%, 100.00%, 98.93%, 99.47%, 99.56...","7, 22, 0, 9, 9, 10, 7, 11",Ran on FASTA - No Coverage Report,USA
22,SRR33992699,WGS,149.03,157118049,PRJNA980729,SAMN49104542,Viral,56934198,USDA-NVSL,2025,...,SRR33992699,2025-06-20_06-23-56,SRR33992699.fa,D1.1,"NP:am13, HA:ea3, PB2:am24, PB1:ea3, NA:am4N1, ...","am13:24-030039-001:NP, ea3:22-013001-001:HA, a...","99.47%, 99.47%, 99.52%, 99.16%, 99.04%, 100.00...","8, 9, 11, 19, 10, 0, 10, 12",Ran on FASTA - No Coverage Report,USA
23,SRR33992700,WGS,149.39,85416600,PRJNA980729,SAMN49104541,Viral,30923309,USDA-NVSL,2025,...,SRR33992700,2025-06-20_06-23-56,SRR33992700.fa,D1.1,"NA:am4N1, NS:ea3, PB1:ea3, HA:ea3, NP:am13, PB...","am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...","99.04%, 98.81%, 99.16%, 99.41%, 99.40%, 99.52%...","10, 10, 19, 10, 9, 11, 1, 13",Ran on FASTA - No Coverage Report,USA
24,SRR33992701,WGS,148.74,215621548,PRJNA980729,SAMN49104540,Viral,77412197,USDA-NVSL,2025,...,SRR33992701,2025-06-20_06-23-56,SRR33992701.fa,D1.1,"MP:ea3, PB1:ea3, NS:ea3, HA:ea3, NP:am13, NA:a...","ea3:22-013001-001:MP, ea3:22-013001-001:PB1, e...","100.00%, 99.25%, 98.93%, 99.41%, 99.53%, 99.04...","0, 17, 9, 10, 7, 10, 11, 11",Ran on FASTA - No Coverage Report,USA
25,SRR33992702,WGS,148.58,164485298,PRJNA980729,SAMN49104539,Viral,59153989,USDA-NVSL,2025,...,SRR33992702,2025-06-20_06-23-56,SRR33992702.fa,D1.1,"PB2:am24, NS:ea3, NA:am4N1, NP:am13, PA:am4, M...","am24:24-030039-001:PB2, ea3:22-013001-001:NS, ...","99.52%, 98.93%, 99.04%, 99.60%, 99.44%, 99.90%...","11, 9, 10, 6, 12, 1, 9, 17",Ran on FASTA - No Coverage Report,USA
26,SRR33992703,WGS,147.69,108646876,PRJNA980729,SAMN49104538,Viral,35642264,USDA-NVSL,2025,...,SRR33992703,2025-06-20_06-23-56,SRR33992703.fa,D1.1,"PB1:ea3, MP:ea3, HA:ea3, NP:am13, NA:am4N1, PB...","ea3:22-013001-001:PB1, ea3:22-013001-001:MP, e...","99.16%, 100.00%, 99.41%, 99.53%, 99.04%, 99.52...","19, 0, 10, 7, 10, 11, 9, 12",Ran on FASTA - No Coverage Report,USA
27,SRR33992704,WGS,147.91,73320377,PRJNA980729,SAMN49104537,Viral,24233116,USDA-NVSL,2025,...,SRR33992704,2025-06-20_06-23-56,SRR33992704.fa,D1.1,"PB1:ea3, PB2:am24, NA:am4N1, MP:ea3, PA:am4, N...","ea3:22-013001-001:PB1, am24:24-030039-001:PB2,...","99.16%, 99.56%, 99.04%, 100.00%, 99.49%, 99.60...","19, 10, 10, 0, 11, 6, 10, 9",Ran on FASTA - No Coverage Report,USA
28,SRR33993166,WGS,147.75,60982523,PRJNA1219588,SAMN49104924,Viral,19939253,USDA-NVSL,2025,...,SRR33993166,2025-06-21_06-23-00,SRR33993166.fa,D1.1,"NA:am4N1, NS:ea3, NP:am13, PB1:ea3, PB2:am24, ...","am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...","98.95%, 98.93%, 99.53%, 99.21%, 99.61%, 99.47%...","11, 9, 7, 18, 9, 9, 1, 11",Ran on FASTA - No Coverage Report,USA
29,SRR33993059,WGS,148.77,139963922,PRJNA1207547,SAMN49104770,Viral,50446456,USDA-NVSL,2025,...,SRR33993059,2025-06-21_06-23-00,SRR33993059.fa,D1.1,"PB1:ea3, PB2:am24, MP:ea3, PA:am4, NP:am13, HA...","ea3:22-013001-001:PB1, am24:24-030039-001:PB2,...","99.25%, 99.74%, 99.69%, 99.63%, 99.87%, 99.41%...","17, 6, 3, 8, 2, 10, 7, 13",Ran on FASTA - No Coverage Report,USA
31,SRR33993061,WGS,147.20,363257804,PRJNA1207547,SAMN49104768,Viral,129254335,USDA-NVSL,2025,...,SRR33993061,2025-06-21_06-23-00,SRR33993061.fa,D1.1,"NP:am13, NS:ea3, PA:am4, HA:ea3, PB2:am24, PB1...","am13:24-030039-001:NP, ea3:22-013001-001:NS, a...","99.53%, 99.28%, 98.37%, 99.41%, 99.74%, 99.38%...","7, 6, 35, 10, 6, 14, 12, 2",Ran on FASTA - No Coverage Report,USA
33,SRR33993063,WGS,145.42,526460773,PRJNA1207547,SAMN49104766,Viral,186161216,USDA-NVSL,2025,...,SRR33993063,2025-06-21_06-23-00,SRR33993063.fa,D1.1,"NP:am13, HA:ea3, MP:ea3, PB1:ea3, NA:am4N1, NS...","am13:24-030039-001:NP, ea3:22-013001-001:HA, e...","99.80%, 99.18%, 99.90%, 99.34%, 99.30%, 99.17%...","3, 14, 1, 15, 8, 7, 3, 8",Ran on FASTA - No Coverage Report,USA
34,SRR33993064,WGS,147.24,444362470,PRJNA1207547,SAMN49104765,Viral,157991689,USDA-NVSL,2025,...,SRR33993064,2025-06-21_06-23-00,SRR33993064.fa,D1.1,"HA:ea3, PA:am4, NP:am13, NA:am4N1, NS:ea3, MP:...","ea3:22-013001-001:HA, am4:24-030039-001:PA, am...","99.24%, 99.60%, 99.80%, 99.04%, 99.17%, 99.90%...","13, 7, 3, 11, 7, 1, 15, 5",Ran on FASTA - No Coverage Report,USA
35,SRR33993065,WGS,148.27,105099746,PRJNA1207547,SAMN49104764,Viral,37665516,USDA-NVSL,2025,...,SRR33993065,2025-06-21_06-23-00,SRR33993065.fa,D1.1,"NP:am13, HA:ea3, NA:am4N1, PB1:ea3, NS:ea3, MP...","am13:24-030039-001:NP, ea3:22-013001-001:HA, a...","99.67%, 99.53%, 99.62%, 98.89%, 99.17%, 99.69%...","5, 8, 4, 9, 7, 3, 3, 2",Ran on FASTA - No Coverage Report,USA
36,SRR33993066,WGS,148.29,96593730,PRJNA1207547,SAMN49104763,Viral,34777840,USDA-NVSL,2025,...,SRR33993066,2025-06-21_06-23-00,SRR33993066.fa,D1.1,"HA:ea3, MP:ea3, PA:am4, NA:am4N1, NS:ea3, NP:a...","ea3:22-013001-001:HA, ea3:22-013001-001:MP, am...","99.65%, 99.90%, 100.00%, 99.23%, 98.81%, 99.93...","6, 1, 0, 8, 10, 1, 1, 1",Ran on FASTA - No Coverage Report,USA
37,SRR33993029,WGS,147.61,522807379,PRJNA1102327,SAMN49104751,Viral,185607037,USDA-NVSL,2025,...,SRR33993029,2025-06-21_06-23-00,SRR33993029.fa,B3.13,"NP:am8, NS:am1.1, MP:ea1, NA:ea1, PB1:am4, PA:...","am8:23-032005-001:NP, am1.1:22-010085-001:NS, ...","98.86%, 98.69%, 98.88%, 98.51%, 99.12%, 98.88%...","17, 11, 11, 21, 20, 24, 33, 38",Ran on FASTA - No Coverage Report,USA
38,SRR33993031,WGS,147.26,104663426,PRJNA1102327,SAMN49104750,Viral,37254008,USDA-NVSL,2025,...,SRR33993031,2025-06-21_06-23-00,SRR33993031.fa,B3.13,"NS:am1.1, PA:ea1, MP:ea1, NP:am8, HA:ea1, NA:e...","am1.1:22-010085-001:NS, ea1:22-003707-003:PA, ...","98.93%, 98.88%, 98.78%, 98.93%, 98.30%, 98.72%...","9, 24, 12, 16, 29, 18, 34, 15",Ran on FASTA - No Coverage Report,USA
39,SRR33993032,WGS,147.52,235901105,PRJNA1102327,SAMN49104749,Viral,83722829,USDA-NVSL,2025,...,SRR33993032,2025-06-21_06-23-00,SRR33993032.fa,B3.13,"MP:ea1, NA:ea1, PA:ea1, PB2:am2.2, HA:ea1, PB1...","ea1:22-003707-003:MP, ea1:22-003707-003:NA, ea...","98.78%, 98.72%, 98.88%, 98.51%, 98.30%, 99.38%...","12, 18, 24, 34, 29, 14, 16, 9",Ran on FASTA - No Coverage Report,USA
40,SRR33993033,WGS,148.12,209453718,PRJNA1102327,SAMN49104748,Viral,74406813,USDA-NVSL,2025,...,SRR33993033,2025-06-21_06-23-00,SRR33993033.fa,B3.13,"PA:ea1, NP:am8, MP:ea1, PB2:am2.2, NA:ea1, PB1...","ea1:22-003707-003:PA, am8:23-032005-001:NP, ea...","98.88%, 98.93%, 98.78%, 98.51%, 98.72%, 99.34%...","24, 16, 12, 34, 18, 15, 9, 29",Ran on FASTA - No Coverage Report,USA
41,SRR33993034,WGS,148.01,200396122,PRJNA1102327,SAMN49104747,Viral,71084273,USDA-NVSL,2025,...,SRR33993034,2025-06-21_06-23-00,SRR33993034.fa,B3.13,"PA:ea1, NP:am8, HA:ea1, NS:am1.1, NA:ea1, PB2:...","ea1:22-003707-003:PA, am8:23-032005-001:NP, ea...","98.88%, 98.93%, 98.30%, 98.93%, 98.72%, 98.51%...","24, 16, 29, 9, 18, 34, 12, 15",Ran on FASTA - No Coverage Report,USA
42,SRR33993035,WGS,148.26,208159405,PRJNA1102327,SAMN49104746,Viral,74388676,USDA-NVSL,2025,...,SRR33993035,2025-06-21_06-23-00,SRR33993035.fa,B3.13,"NA:ea1, HA:ea1, NS:am1.1, PB1:am4, MP:ea1, PB2...","ea1:22-003707-003:NA, ea1:22-003707-003:HA, am...","98.72%, 98.30%, 98.93%, 99.34%, 98.78%, 98.51%...","18, 29, 9, 15, 12, 34, 16, 24",Ran on FASTA - No Coverage Report,USA
43,SRR33993036,WGS,148.05,209968472,PRJNA1102327,SAMN49104745,Viral,75064716,USDA-NVSL,2025,...,SRR33993036,2025-06-21_06-23-00,SRR33993036.fa,B3.13,"NA:ea1, HA:ea1, PA:ea1, MP:ea1, PB1:am4, NS:am...","ea1:22-003707-003:NA, ea1:22-003707-003:HA, ea...","98.72%, 98.30%, 98.88%, 98.78%, 99.34%, 98.93%...","18, 29, 24, 12, 15, 9, 34, 16",Ran on FASTA - No Coverage Report,USA
44,SRR33993037,WGS,148.35,221485032,PRJNA1102327,SAMN49104744,Viral,78792165,USDA-NVSL,2025,...,SRR33993037,2025-06-21_06-23-00,SRR33993037.fa,B3.13,"HA:ea1, NA:ea1, PB2:am2.2, NP:am8, MP:ea1, PA:...","ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...","98.30%, 98.72%, 98.51%, 98.93%, 98.78%, 98.88%...","29, 18, 34, 16, 12, 24, 9, 15",Ran on FASTA - No Coverage Report,USA
45,SRR33993038,WGS,148.07,190312401,PRJNA1102327,SAMN49104743,Viral,67965403,USDA-NVSL,2025,...,SRR33993038,2025-06-21_06-23-00,SRR33993038.fa,B3.13,"PB1:am4, NA:ea1, HA:ea1, PA:ea1, NP:am8, PB2:a...","am4:23-001855-001:PB1, ea1:22-003707-003:NA, e...","99.34%, 98.72%, 98.30%, 98.88%, 98.93%, 98.51%...","15, 18, 29, 24, 16, 34, 12, 9",Ran on FASTA - No Coverage Report,USA
46,SRR33993039,WGS,147.66,790397536,PRJNA1102327,SAMN49104742,Viral,282137009,USDA-NVSL,2025,...,SRR33993039,2025-06-21_06-23-00,SRR33993039.fa,B3.13,"MP:ea1, PB1:am4, PA:ea1, PB2:am2.2, NP:am8, HA...","ea1:22-003707-003:MP, am4:23-001855-001:PB1, e...","98.78%, 99.34%, 98.88%, 98.51%, 98.93%, 98.30%...","12, 15, 24, 34, 16, 29, 18, 9",Ran on FASTA - No Coverage Report,USA
47,SRR33993040,WGS,148.06,535205498,PRJNA1102327,SAMN49104741,Viral,189952374,USDA-NVSL,2025,...,SRR33993040,2025-06-21_06-23-00,SRR33993040.fa,B3.13,"PA:ea1, MP:ea1, PB2:am2.2, NS:am1.1, PB1:am4, ...","ea1:22-003707-003:PA, ea1:22-003707-003:MP, am...","98.75%, 98.78%, 98.55%, 99.05%, 99.34%, 98.93%...","27, 12, 33, 8, 15, 16, 27, 19",Ran on FASTA - No Coverage Report,USA
48,SRR33993042,WGS,147.81,668807754,PRJNA1102327,SAMN49104740,Viral,236759389,USDA-NVSL,2025,...,SRR33993042,2025-06-21_06-23-00,SRR33993042.fa,B3.13,"NS:am1.1, PB1:am4, HA:ea1, NA:ea1, PB2:am2.2, ...","am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...","99.05%, 99.30%, 98.42%, 98.65%, 98.51%, 98.78%...","8, 16, 27, 19, 34, 12, 28, 16",Ran on FASTA - No Coverage Report,USA

In [6]:
# # If no states

# metadata_genbank = metadata

# metadata_genbank["name_state"] = "USA"

# metadata_genbank["Geo_Location"] = "USA"

# display(metadata_genbank)

## Collection Dates

If date is N/A, try finding it first

In [7]:

# # Get all dates
# metadata["Collection_Date_Specific"] = metadata["BioSample"].apply(lambda x: search_collection_date(x, metadata) if "-" not in x else x)

# # Save this so we don't have to do it again

# # os.chdir(temp_files)
# metadata.to_csv("metadata_genbank.csv")

In [8]:
# os.chdir(saved)
# metadata = pd.read_csv("metadata_genbank_" + date_range + ".csv")
metadata = pd.read_csv("metadata_genbank.csv")

In [9]:
date = "2025" 

date = dateutil.parser.parse(date, default=datetime(2000, 1, 1))

print(date.month)

1

In [10]:
# # # Upload saved data -- if doing this, make sure the above cell is commented out
# # os.chdir(temp_files + "saved/")
# # metadata_genbank = pd.read_csv("metadata_genbank.csv")
# # os.chdir(temp_files)

# # Get only updated dates

# # unknown_dates = metadata[(metadata["Collection_Date"] == "2024") | (metadata["Collection_Date"] == "2025")] # Dates we don't have

# def find_known_dates(x, df):
    
#     try:
#         date = metadata[metadata["BioSample"] == x]["Collection_Date"].values[0]
#     # print(date)
#         # print(date)
#         # if len(str(date)) == 4: # If this is just a year
#         #     date = search_collection_date(x, df)
#         # else:
#         date = dateutil.parser.parse(date, default=datetime(2000, 1, 1)) # .strftime("%Y-%m-%d") # If a date already exists
#         if date.day == dateutil.parser.parse("1/1/2000").day and date.month == dateutil.parser.parse("1/1/2000").month:
#             print("year only")
#             date = search_collection_date(x, df)
#         print("Success", date)
#     except:
#         date = search_collection_date(x, df) # If it's not parseable as a date
#     return date # If statement in lambda function will search for the "just year" values
        

# # years = ["2021", "2022", "2023", "2024", "2025"]
# # unknown_dates = metadata[metadata["Collection_Date"].isin(years)]
# # # known_dates = metadata[(metadata["Collection_Date"] != "2024") & (metadata["Collection_Date"] != "2025")] # Dates we've already gotten
# # known_dates = metadata[~metadata["Collection_Date"].isin(years)]

# # Get new dates also 
# # new_dates = metadata["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank) if )

# updated_dates = metadata["BioSample"].apply(lambda x: find_known_dates(x, metadata)) # Update unknown dates, if possible
# metadata["Collection_Date"] = updated_dates

# # metadata = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # updated_unknown_dates = unknown_dates["BioSample"].apply(lambda x: search_collection_date(x, unknown_dates)) # Update unknown dates, if possible
# # unknown_dates["Collection_Date"] = updated_unknown_dates

# # metadata = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # Save this so we don't have to do it again

# # os.chdir(temp_files)
# # metadata.to_csv("metadata_genbank_" + date_range + ".csv")

# # display(metadata)

In [11]:
# os.chdir(temp_files)
# metadata.to_csv("metadata_genbank_" + date_range + ".csv")

# If no collection dates

# metadata_genbank["Collection_Date_Specific"] = metadata_genbank["Collection_Date"]

## Get host type

In [12]:
# create a mask, where is True if the host does not exist
print(metadata["Host"])

mask = metadata["Host"].isna()

# choose between the original value and split isolate using the mask
metadata["Host"] = np.where(mask, metadata["isolate"].apply(lambda x: x if x != x or "/" not in x or len(x.split("/")) < 2 else x.split("/")[1]), metadata["Host"]) #  if "/" in metadata["isolate"] else metadata["Host"])
metadata["Host"] = metadata["Host"].apply(lambda x: x.lower() if x == x else x)

# print(metadata["Host"])

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

# print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

os.chdir(home + "references/")

animals_ref = pd.read_csv("animals_ref.csv") # Upload animals ref

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort2.csv") # Make sure name is different to avoid overwriting the first reference 

print(metadata["Host"])
# print(metadata["isolate"])

0        TURKEY VULTURE
1        TURKEY VULTURE
2       RED-TAILED HAWK
3       RED-TAILED HAWK
4      GREAT HORNED OWL
             ...
106              CATTLE
107              CATTLE
108              CATTLE
109              CATTLE
110              CATTLE
Name: Host, Length: 111, dtype: object
[]
                  avian               cattle        feline   other_mammal  \
0      great_horned_owl            dairy_cow           cat     deer mouse
1          common_raven               cattle  domestic_cat    house_mouse
2         cooper's_hawk  cattle milk product     feral_cat          skunk
3          coopers_hawk          bovine_milk        feline  striped_skunk
4               peafowl              bovine   domestic-cat     norway rat
..                  ...                  ...           ...            ...
466         anser anser                  NaN           NaN            NaN
467    northern harrier                  NaN           NaN            NaN
468              mergus                  NaN           NaN            NaN
469  thalasseus maximus                  NaN           NaN            NaN
470       calidris alba                  NaN           NaN            NaN

          human         other  new
0    washington         mixed  NaN
1        nevada   environment  NaN
2       wyoming  multispecies  NaN
3    california       unknown  NaN
4      michigan             '  NaN
..          ...           ...  ...
466         NaN           NaN  NaN
467         NaN           NaN  NaN
468         NaN           NaN  NaN
469         NaN           NaN  NaN
470         NaN           NaN  NaN

[471 rows x 7 columns]
0        turkey vulture
1        turkey vulture
2       red-tailed hawk
3       red-tailed hawk
4      great horned owl
             ...
106              cattle
107              cattle
108              cattle
109              cattle
110              cattle
Name: Host, Length: 111, dtype: object

In [13]:
# Get animals from animal reference
os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")
fix_animals_andersen(metadata, animals_ref) # Get host type

metadata["years"] = metadata["Collection_Date"].apply(lambda x: str(x).split("-")[0]) # Get year only from collection date

## Make names using all the attributes we collected

In [14]:
for num, collection_date in enumerate(metadata["Collection_Date"]):
    if collection_date != collection_date: # if nan
         collection_date = "missing"
    try:
        print(collection_date)
        if collection_date.month == datetime.parser.parse("1/1/2000").month and collection_date.day == datetime.parser.parse("1/1/2000").day:
            # If not a valid collection date, but has year
            
            year = collection_date.year
            metadata.loc[num, "Collection_Date"] = year
            # if collection_date != collection_date: # If nan
        #     metadata.loc[num, "Collection_Date"] = metadata.loc[num, "years"]
        else: # If actual date
                
            # if len(str(collection_date)) == 4: # If it's a year
                # print("caught")
                metadata.loc[num, "Collection_Date"] = collection_date
    except:
         metadata.loc[num, "Collection_Date"] = collection_date
        # else:
        #     try:
        #         parsed_date = dateutil.parser.parse(collection_date)
        #         date = parsed_date.strftime("%Y-%m-%d") # Make sure it doesn't default to today, if just a year
        #         metadata.loc[num, "Collection_Date"] = date
        #     except: # If no date at all
        #         metadata.loc[num, "Collection_Date"] = collection_date

    # metadata = metadata.dropna(thresh=2)

2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2024
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2024
2025
2025
2025
2025
2025
2025
2025
2025
2025
2024
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2024
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2024
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2024
2025
2025
2025
2025
2025
2025
2025
2024
2024

In [15]:
# Make names

metadata = metadata.fillna("")

# + metadata["BioSample"] + "|" 
names = ">" + metadata["Run"] + "|" + "A/" + metadata["Host"] + "/" + metadata["name_state"] + "/" + metadata["Library Name"] + "/" + metadata["years"].apply(lambda x: str(x)) + "|" + metadata["serotype"] + "|" + metadata["Geo_Location"] + "|" + metadata["Collection_Date"].apply(lambda x: str(x)) + "|" + metadata["Host_Type"] + "|" + metadata["Genotype"]

metadata["Name"] = names

# metadata_genbank.to_csv("metadata_genbank_named.csv")

display(metadata["Name"])

0      >SRR33830324|A/turkey vulture/USA/25-013422-00...
1      >SRR33830325|A/turkey vulture/USA/25-015561-00...
2      >SRR33830326|A/red-tailed hawk/USA/25-013427-0...
3      >SRR33830327|A/red-tailed hawk/USA/25-013424-0...
4      >SRR33830328|A/great horned owl/USA/25-015870-...
                             ...
106    >SRR33830443|A/cattle/USA/25-015681-003-origin...
107    >SRR33830444|A/cattle/USA/25-015681-002-origin...
108    >SRR33830445|A/cattle/USA/25-015681-001-origin...
109    >SRR33830449|A/cattle/USA/24-036379-001-tile/2...
110    >SRR33830450|A/cattle/USA/24-034788-001-tile/2...
Name: Name, Length: 111, dtype: object

In [16]:
# Drop duplicate runs 
metadata = metadata.drop_duplicates(subset="Run", keep="first")

In [17]:
print(metadata)

     Unnamed: 0          Run Assay Type  AvgSpotLen      Bases    BioProject  \
0             0  SRR33830324        WGS      147.97   74609244  PRJNA1207547
1             1  SRR33830325        WGS      148.64  156899568  PRJNA1207547
2             2  SRR33830326        WGS      137.62     616674  PRJNA1207547
3             3  SRR33830327        WGS      148.23   57621808  PRJNA1207547
4             4  SRR33830328        WGS      148.93  140872576  PRJNA1207547
..          ...          ...        ...         ...        ...           ...
106         109  SRR33830443        WGS      148.11  100597029  PRJNA1102327
107         110  SRR33830444        WGS      148.50  131987248  PRJNA1102327
108         111  SRR33830445        WGS      148.12  115677479  PRJNA1102327
109         115  SRR33830449        WGS      131.52   67358891  PRJNA1102327
110         116  SRR33830450        WGS      131.13   69602732  PRJNA1102327

        BioSample BioSampleModel     Bytes Center Name  ...  \
0    SAMN48895309          Viral  27537881   USDA-NVSL  ...
1    SAMN48895308          Viral  62096192   USDA-NVSL  ...
2    SAMN48895307          Viral    313930   USDA-NVSL  ...
3    SAMN48895306          Viral  21591302   USDA-NVSL  ...
4    SAMN48895305          Viral  56890513   USDA-NVSL  ...
..            ...            ...       ...         ...  ...
106  SAMN48895429          Viral  39710063   USDA-NVSL  ...
107  SAMN48895428          Viral  51617990   USDA-NVSL  ...
108  SAMN48895427          Viral  45674405   USDA-NVSL  ...
109  SAMN48895415          Viral  26336550   USDA-NVSL  ...
110  SAMN48895414          Viral  27556171   USDA-NVSL  ...

                           Genotype List Used, >=98.0%  \
0    NP:am13, NS:ea3, PB2:am24, HA:ea3, PB1:ea3, MP...
1    PA:am4, PB2:am24, HA:ea3, PB1:ea3, MP:ea3, NS:...
2    MP:ea3, PB1:ea3, NA:am4N1, PB2:am24, HA:ea3, N...
3    PA:am4, MP:ea3, NP:am13, NS:ea3, NA:am4N1, PB2...
4    NS:ea3, NA:am4N1, PB1:ea3, MP:ea3, PB2:am24, H...
..                                                 ...
106  NA:ea1, PB1:am4, MP:ea1, PA:ea1, NP:am8, HA:ea...
107  PA:ea1, NA:ea1, PB2:am2.2, NP:am8, HA:ea1, MP:...
108  NP:am8, HA:ea1, PA:ea1, NS:am1.1, PB1:am4, PB2...
109  NP:am8, NA:ea1, PB1:am4, HA:ea1, NS:am1.1, MP:...
110  HA:ea1, NA:ea1, NP:am8, PB2:am2.2, MP:ea1, PB1...

                            Genotype Sample Title List  \
0    am13:24-030039-001:NP, ea3:22-013001-001:NS, a...
1    am4:24-030039-001:PA, am24:24-030039-001:PB2, ...
2    ea3:22-013001-001:MP, ea3:22-013001-001:PB1, a...
3    am4:24-030039-001:PA, ea3:22-013001-001:MP, am...
4    ea3:22-013001-001:NS, am4N1:24-030039-001:NA, ...
..                                                 ...
106  ea1:22-003707-003:NA, am4:23-001855-001:PB1, e...
107  ea1:22-003707-003:PA, ea1:22-003707-003:NA, am...
108  am8:23-032005-001:NP, ea1:22-003707-003:HA, ea...
109  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
110  ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...

                           Genotype Percent Match List  \
0    99.80%, 99.17%, 99.74%, 99.24%, 99.34%, 100.00...
1    99.60%, 99.65%, 99.41%, 99.16%, 99.90%, 98.93%...
2    99.90%, 99.68%, 99.33%, 99.78%, 99.41%, 98.93%...
3    99.81%, 99.90%, 99.87%, 99.28%, 99.52%, 99.69%...
4    99.17%, 99.03%, 99.30%, 99.90%, 99.61%, 99.41%...
..                                                 ...
106  98.72%, 99.52%, 98.98%, 98.88%, 98.86%, 98.06%...
107  98.88%, 98.65%, 98.20%, 98.93%, 98.06%, 98.98%...
108  98.93%, 98.24%, 98.79%, 98.93%, 99.56%, 98.51%...
109  98.93%, 98.86%, 99.47%, 98.43%, 99.17%, 98.95%...
110  98.92%, 98.71%, 99.00%, 98.55%, 98.74%, 99.47%...

            Genotype Mismatch List Genotype Average Depth of Coverage List  \
0        3, 7, 6, 13, 15, 0, 10, 7       Ran on FASTA - No Coverage Report
1         7, 8, 10, 19, 1, 9, 7, 2       Ran on FASTA - No Coverage Report
2          1, 2, 7, 5, 10, 9, 2, 5       Ran on FASTA - No Coverage Report
3         4, 1, 2, 6, 5, 7, 20, 11       Ran on FASTA - No Coverage Report
4       7, 11, 16, 1, 9, 10, 13, 5       Ran on FASTA - No Coverage Report
..                             ...                                     ...
106  18, 11, 10, 24, 17, 33, 38, 9       Ran on FASTA - No Coverage Report
107  24, 19, 41, 16, 33, 10, 12, 9       Ran on FASTA - No Coverage Report
108  16, 30, 26, 9, 10, 34, 19, 11       Ran on FASTA - No Coverage Report
109  16, 16, 12, 12, 7, 10, 31, 24       Ran on FASTA - No Coverage Report
110  11, 12, 15, 33, 12, 12, 8, 23       Ran on FASTA - No Coverage Report

    Geo_Location Collection_Date_Specific Host_Type years  \
0            USA                     2025     avian  2025
1            USA                     2025     avian  2025
2            USA                     2025     avian  2025
3            USA                     2025     avian  2025
4            USA                     2025     avian  2025
..           ...                      ...       ...   ...
106          USA                     2025    cattle  2025
107          USA                     2025    cattle  2025
108          USA                     2025    cattle  2025
109          USA                     2024    cattle  2024
110          USA                     2024    cattle  2024

                                                  Name
0    >SRR33830324|A/turkey vulture/USA/25-013422-00...
1    >SRR33830325|A/turkey vulture/USA/25-015561-00...
2    >SRR33830326|A/red-tailed hawk/USA/25-013427-0...
3    >SRR33830327|A/red-tailed hawk/USA/25-013424-0...
4    >SRR33830328|A/great horned owl/USA/25-015870-...
..                                                 ...
106  >SRR33830443|A/cattle/USA/25-015681-003-origin...
107  >SRR33830444|A/cattle/USA/25-015681-002-origin...
108  >SRR33830445|A/cattle/USA/25-015681-001-origin...
109  >SRR33830449|A/cattle/USA/24-036379-001-tile/2...
110  >SRR33830450|A/cattle/USA/24-034788-001-tile/2...

[111 rows x 53 columns]

## Make FASTA files

In [18]:
# Get information to create the fasta files

fasta_folder = originals + "avian-influenza/fasta/"

os.chdir(fasta_folder)

segments = ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]
pairs = []
fasta_files = {}

for genotype in genotypes: # ["B3.13", "D1.1"]:
    for segment in segments:
        pair = genotype + "_" + segment
        pairs.append(pair)

for pair in pairs:
    fasta_files[pair] = [] # List to hold fasta files

for run in metadata["Run"].values: # For each run 
    for dirpath, dirs, files in os.walk(fasta_folder): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            # print(file_name)
            if run in file_name: # Note that there will be ~8 files total with that run name
                # Make a fasta file and put it in the list
                with open(file_name) as f:
                    lines = f.readlines()
                    sequence = lines[1] 
                    # Each run/segment pair has one sequence -- it's placed into a file with other run/segment pairs with the same segment and genotype
                    header = metadata[metadata["Run"] == run].loc[:, "Name"].values[0]
                    genotype = metadata[metadata["Run"] == run].loc[:, "Genotype"].values[0]
                    # print(header)
                    # print(genotype)
                    # break 
                    segment = file_name.split("_")[-2]
                    # Find the pair that corresponds to 
                    pair_name = genotype + "_" + segment
                    this_specific_fasta = []
                    for pair in pairs:
                        # print(pair)
                        # print(pair_name)
                        if pair_name == pair:
                            this_specific_fasta.append(header)
                            this_specific_fasta.append(sequence)
                            fasta_files[pair].append(this_specific_fasta)
                f.close()
        break

In [19]:
# print(fasta_files.keys())

In [20]:
# Create fasta files 

# os.chdir(complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/")
os.chdir(originals + "complete/")
names = []
for pair in fasta_files.keys():
    # output_path = complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/" + pair + "_andersen_updated_" + update_date + ".fasta" 
    output_path = originals + "complete/" + pair + "_" + date_range + "_andersen_updated.fasta"

    output_file = open(output_path, "w")
    for item in fasta_files[pair]:
        # for item in item:
        # item = fasta_files[pair]
        try:
            name = str(item[0].values[0]) # See if this is one we didn't have a collection date for
        except:
            name = str(item[0])
        print(name)
        names.append(name)
        # First is header, second is sequence
        # print(value)
        output_file.write(name + "\n")
        output_file.write(item[1])
    output_file.close()

print(len(names)/8)

>SRR33830355|A/cattle/USA/25-016216-005-original/2025||USA|2025|cattle|B3.13
>SRR33830356|A/cattle/USA/25-016216-004-original/2025||USA|2025|cattle|B3.13
>SRR33830357|A/cattle/USA/25-016216-003-original/2025||USA|2025|cattle|B3.13
>SRR33830358|A/cattle/USA/25-016216-002-original/2025||USA|2025|cattle|B3.13
>SRR33830359|A/cattle/USA/25-016216-001-original/2025||USA|2025|cattle|B3.13
>SRR33830360|A/cattle/USA/25-016215-002-original/2025||USA|2025|cattle|B3.13
>SRR33830362|A/cattle/USA/25-016215-001-original/2025||USA|2025|cattle|B3.13
>SRR33830363|A/cattle/USA/25-016214-001-original/2025||USA|2025|cattle|B3.13
>SRR33830364|A/cattle/USA/25-016212-002-original/2025||USA|2025|cattle|B3.13
>SRR33830365|A/cattle/USA/25-016212-001-original/2025||USA|2025|cattle|B3.13
>SRR33830366|A/cattle/USA/25-016210-002-original/2025||USA|2025|cattle|B3.13
>SRR33830367|A/cattle/USA/25-016210-001-original/2025||USA|2025|cattle|B3.13
>SRR33830368|A/cattle/USA/25-016209-001-original/2025||USA|2025|cattle|B3.13
>SRR33830369|A/cattle/USA/25-016208-001-original/2025||USA|2025|cattle|B3.13
>SRR33830370|A/cattle/USA/25-016207-001-original/2025||USA|2025|cattle|B3.13
>SRR33830371|A/cattle/USA/25-016205-001-original/2025||USA|2025|cattle|B3.13
>SRR33830372|A/cattle/USA/25-015655-001-original/2025||USA|2025|cattle|B3.13
>SRR33830373|A/cattle/USA/25-016204-001-original/2025||USA|2025|cattle|B3.13
>SRR33830374|A/cattle/USA/25-016202-001-original/2025||USA|2025|cattle|B3.13
>SRR33830375|A/cattle/USA/25-016201-001-original/2025||USA|2025|cattle|B3.13
>SRR33830376|A/cattle/USA/25-016200-002-original/2025||USA|2025|cattle|B3.13
>SRR33830377|A/cattle/USA/25-016200-001-original/2025||USA|2025|cattle|B3.13
>SRR33830378|A/cattle/USA/25-016199-001-original/2025||USA|2025|cattle|B3.13
>SRR33830379|A/cattle/USA/25-016198-001-original/2025||USA|2025|cattle|B3.13
>SRR33830380|A/cattle/USA/25-016196-002-original/2025||USA|2025|cattle|B3.13
>SRR33830381|A/cattle/USA/25-016196-001-original/2025||USA|2025|cattle|B3.13
>SRR33830383|A/cattle/USA/24-038352-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830384|A/cattle/USA/25-010490-001-v/2025||USA|2025|cattle|B3.13
>SRR33830385|A/cattle/USA/25-015748-002-original/2025||USA|2025|cattle|B3.13
>SRR33830386|A/cattle/USA/25-015739-002-original/2025||USA|2025|cattle|B3.13
>SRR33830387|A/cattle/USA/25-015739-001-original/2025||USA|2025|cattle|B3.13
>SRR33830388|A/cattle/USA/25-015738-001-original/2025||USA|2025|cattle|B3.13
>SRR33830389|A/cattle/USA/25-015736-002-original/2025||USA|2025|cattle|B3.13
>SRR33830390|A/cattle/USA/25-015734-004-original/2025||USA|2025|cattle|B3.13
>SRR33830391|A/cattle/USA/25-015734-002-original/2025||USA|2025|cattle|B3.13
>SRR33830392|A/cattle/USA/25-015730-002-original/2025||USA|2025|cattle|B3.13
>SRR33830393|A/cattle/USA/25-015724-003-original/2025||USA|2025|cattle|B3.13
>SRR33830394|A/cattle/USA/24-037350-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830396|A/cattle/USA/25-015723-001-original/2025||USA|2025|cattle|B3.13
>SRR33830397|A/cattle/USA/25-015713-005-original/2025||USA|2025|cattle|B3.13
>SRR33830398|A/cattle/USA/25-015713-004-original/2025||USA|2025|cattle|B3.13
>SRR33830399|A/cattle/USA/25-015704-001-original/2025||USA|2025|cattle|B3.13
>SRR33830400|A/cattle/USA/25-015696-002-original/2025||USA|2025|cattle|B3.13
>SRR33830401|A/cattle/USA/25-015696-001-original/2025||USA|2025|cattle|B3.13
>SRR33830402|A/cattle/USA/25-015689-004-original/2025||USA|2025|cattle|B3.13
>SRR33830403|A/cattle/USA/25-015689-003-original/2025||USA|2025|cattle|B3.13
>SRR33830404|A/cattle/USA/25-015689-002-original/2025||USA|2025|cattle|B3.13
>SRR33830405|A/cattle/USA/24-036764-003-tile/2024||USA|2024|cattle|B3.13
>SRR33830406|A/cattle/USA/25-015689-001-original/2025||USA|2025|cattle|B3.13
>SRR33830407|A/cattle/USA/25-015688-002-original/2025||USA|2025|cattle|B3.13
>SRR33830408|A/cattle/USA/25-015686-009-original/2025||USA|2025|cattle|B3.13
>SRR33830409|A/cattle/USA/25-015686-008-original/2025||USA|2025|cattle|B3.13
>SRR33830410|A/cattle/USA/25-015686-007-original/2025||USA|2025|cattle|B3.13
>SRR33830411|A/cattle/USA/25-015686-006-original/2025||USA|2025|cattle|B3.13
>SRR33830412|A/cattle/USA/25-015686-005-original/2025||USA|2025|cattle|B3.13
>SRR33830413|A/cattle/USA/25-015686-004-original/2025||USA|2025|cattle|B3.13
>SRR33830414|A/cattle/USA/25-015686-003-original/2025||USA|2025|cattle|B3.13
>SRR33830415|A/cattle/USA/25-015686-002-original/2025||USA|2025|cattle|B3.13
>SRR33830416|A/cattle/USA/24-036764-002-tile/2024||USA|2024|cattle|B3.13
>SRR33830417|A/cattle/USA/25-015686-001-original/2025||USA|2025|cattle|B3.13
>SRR33830418|A/cattle/USA/25-015684-008-original/2025||USA|2025|cattle|B3.13
>SRR33830419|A/cattle/USA/25-015684-007-original/2025||USA|2025|cattle|B3.13
>SRR33830420|A/cattle/USA/25-015684-006-original/2025||USA|2025|cattle|B3.13
>SRR33830421|A/cattle/USA/25-015684-005-original/2025||USA|2025|cattle|B3.13
>SRR33830422|A/cattle/USA/25-015684-004-original/2025||USA|2025|cattle|B3.13
>SRR33830423|A/cattle/USA/25-015684-003-original/2025||USA|2025|cattle|B3.13
>SRR33830424|A/cattle/USA/25-015684-002-original/2025||USA|2025|cattle|B3.13
>SRR33830425|A/cattle/USA/25-015684-001-original/2025||USA|2025|cattle|B3.13
>SRR33830426|A/cattle/USA/25-015683-001-original/2025||USA|2025|cattle|B3.13
>SRR33830427|A/cattle/USA/24-036419-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830428|A/cattle/USA/25-015682-003-original/2025||USA|2025|cattle|B3.13
>SRR33830429|A/cattle/USA/25-015682-002-original/2025||USA|2025|cattle|B3.13
>SRR33830430|A/cattle/USA/25-015682-001-original/2025||USA|2025|cattle|B3.13
>SRR33830431|A/cattle/USA/25-015681-014-original/2025||USA|2025|cattle|B3.13
>SRR33830432|A/cattle/USA/25-015681-013-original/2025||USA|2025|cattle|B3.13
>SRR33830433|A/cattle/USA/25-015681-012-original/2025||USA|2025|cattle|B3.13
>SRR33830434|A/cattle/USA/25-015681-011-original/2025||USA|2025|cattle|B3.13
>SRR33830435|A/cattle/USA/25-015681-010-original/2025||USA|2025|cattle|B3.13
>SRR33830436|A/cattle/USA/25-015681-009-original/2025||USA|2025|cattle|B3.13
>SRR33830437|A/cattle/USA/25-015681-008-original/2025||USA|2025|cattle|B3.13
>SRR33830438|A/cattle/USA/24-036414-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830439|A/cattle/USA/25-015681-007-original/2025||USA|2025|cattle|B3.13
>SRR33830440|A/cattle/USA/25-015681-006-original/2025||USA|2025|cattle|B3.13
>SRR33830441|A/cattle/USA/25-015681-005-original/2025||USA|2025|cattle|B3.13
>SRR33830442|A/cattle/USA/25-015681-004-original/2025||USA|2025|cattle|B3.13
>SRR33830443|A/cattle/USA/25-015681-003-original/2025||USA|2025|cattle|B3.13
>SRR33830444|A/cattle/USA/25-015681-002-original/2025||USA|2025|cattle|B3.13
>SRR33830445|A/cattle/USA/25-015681-001-original/2025||USA|2025|cattle|B3.13
>SRR33830449|A/cattle/USA/24-036379-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830450|A/cattle/USA/24-034788-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830355|A/cattle/USA/25-016216-005-original/2025||USA|2025|cattle|B3.13
>SRR33830356|A/cattle/USA/25-016216-004-original/2025||USA|2025|cattle|B3.13
>SRR33830357|A/cattle/USA/25-016216-003-original/2025||USA|2025|cattle|B3.13
>SRR33830358|A/cattle/USA/25-016216-002-original/2025||USA|2025|cattle|B3.13
>SRR33830359|A/cattle/USA/25-016216-001-original/2025||USA|2025|cattle|B3.13
>SRR33830360|A/cattle/USA/25-016215-002-original/2025||USA|2025|cattle|B3.13
>SRR33830362|A/cattle/USA/25-016215-001-original/2025||USA|2025|cattle|B3.13
>SRR33830363|A/cattle/USA/25-016214-001-original/2025||USA|2025|cattle|B3.13
>SRR33830364|A/cattle/USA/25-016212-002-original/2025||USA|2025|cattle|B3.13
>SRR33830365|A/cattle/USA/25-016212-001-original/2025||USA|2025|cattle|B3.13
>SRR33830366|A/cattle/USA/25-016210-002-original/2025||USA|2025|cattle|B3.13
>SRR33830367|A/cattle/USA/25-016210-001-original/2025||USA|2025|cattle|B3.13
>SRR33830368|A/cattle/USA/25-016209-001-original/2025||USA|2025|cattle|B3.13
>SRR33830369|A/cattle/USA/25-016208-001-original/2025||USA|2025|cattle|B3.13
>SRR33830370|A/cattle/USA/25-016207-001-original/2025||USA|2025|cattle|B3.13
>SRR33830371|A/cattle/USA/25-016205-001-original/2025||USA|2025|cattle|B3.13
>SRR33830372|A/cattle/USA/25-015655-001-original/2025||USA|2025|cattle|B3.13
>SRR33830373|A/cattle/USA/25-016204-001-original/2025||USA|2025|cattle|B3.13
>SRR33830374|A/cattle/USA/25-016202-001-original/2025||USA|2025|cattle|B3.13
>SRR33830375|A/cattle/USA/25-016201-001-original/2025||USA|2025|cattle|B3.13
>SRR33830376|A/cattle/USA/25-016200-002-original/2025||USA|2025|cattle|B3.13
>SRR33830377|A/cattle/USA/25-016200-001-original/2025||USA|2025|cattle|B3.13
>SRR33830378|A/cattle/USA/25-016199-001-original/2025||USA|2025|cattle|B3.13
>SRR33830379|A/cattle/USA/25-016198-001-original/2025||USA|2025|cattle|B3.13
>SRR33830380|A/cattle/USA/25-016196-002-original/2025||USA|2025|cattle|B3.13
>SRR33830381|A/cattle/USA/25-016196-001-original/2025||USA|2025|cattle|B3.13
>SRR33830383|A/cattle/USA/24-038352-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830384|A/cattle/USA/25-010490-001-v/2025||USA|2025|cattle|B3.13
>SRR33830385|A/cattle/USA/25-015748-002-original/2025||USA|2025|cattle|B3.13
>SRR33830386|A/cattle/USA/25-015739-002-original/2025||USA|2025|cattle|B3.13
>SRR33830387|A/cattle/USA/25-015739-001-original/2025||USA|2025|cattle|B3.13
>SRR33830388|A/cattle/USA/25-015738-001-original/2025||USA|2025|cattle|B3.13
>SRR33830389|A/cattle/USA/25-015736-002-original/2025||USA|2025|cattle|B3.13
>SRR33830390|A/cattle/USA/25-015734-004-original/2025||USA|2025|cattle|B3.13
>SRR33830391|A/cattle/USA/25-015734-002-original/2025||USA|2025|cattle|B3.13
>SRR33830392|A/cattle/USA/25-015730-002-original/2025||USA|2025|cattle|B3.13
>SRR33830393|A/cattle/USA/25-015724-003-original/2025||USA|2025|cattle|B3.13
>SRR33830394|A/cattle/USA/24-037350-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830396|A/cattle/USA/25-015723-001-original/2025||USA|2025|cattle|B3.13
>SRR33830397|A/cattle/USA/25-015713-005-original/2025||USA|2025|cattle|B3.13
>SRR33830398|A/cattle/USA/25-015713-004-original/2025||USA|2025|cattle|B3.13
>SRR33830399|A/cattle/USA/25-015704-001-original/2025||USA|2025|cattle|B3.13
>SRR33830400|A/cattle/USA/25-015696-002-original/2025||USA|2025|cattle|B3.13
>SRR33830401|A/cattle/USA/25-015696-001-original/2025||USA|2025|cattle|B3.13
>SRR33830402|A/cattle/USA/25-015689-004-original/2025||USA|2025|cattle|B3.13
>SRR33830403|A/cattle/USA/25-015689-003-original/2025||USA|2025|cattle|B3.13
>SRR33830404|A/cattle/USA/25-015689-002-original/2025||USA|2025|cattle|B3.13
>SRR33830405|A/cattle/USA/24-036764-003-tile/2024||USA|2024|cattle|B3.13
>SRR33830406|A/cattle/USA/25-015689-001-original/2025||USA|2025|cattle|B3.13
>SRR33830407|A/cattle/USA/25-015688-002-original/2025||USA|2025|cattle|B3.13
>SRR33830408|A/cattle/USA/25-015686-009-original/2025||USA|2025|cattle|B3.13
>SRR33830409|A/cattle/USA/25-015686-008-original/2025||USA|2025|cattle|B3.13
>SRR33830410|A/cattle/USA/25-015686-007-original/2025||USA|2025|cattle|B3.13
>SRR33830411|A/cattle/USA/25-015686-006-original/2025||USA|2025|cattle|B3.13
>SRR33830412|A/cattle/USA/25-015686-005-original/2025||USA|2025|cattle|B3.13
>SRR33830413|A/cattle/USA/25-015686-004-original/2025||USA|2025|cattle|B3.13
>SRR33830414|A/cattle/USA/25-015686-003-original/2025||USA|2025|cattle|B3.13
>SRR33830415|A/cattle/USA/25-015686-002-original/2025||USA|2025|cattle|B3.13
>SRR33830416|A/cattle/USA/24-036764-002-tile/2024||USA|2024|cattle|B3.13
>SRR33830417|A/cattle/USA/25-015686-001-original/2025||USA|2025|cattle|B3.13
>SRR33830418|A/cattle/USA/25-015684-008-original/2025||USA|2025|cattle|B3.13
>SRR33830419|A/cattle/USA/25-015684-007-original/2025||USA|2025|cattle|B3.13
>SRR33830420|A/cattle/USA/25-015684-006-original/2025||USA|2025|cattle|B3.13
>SRR33830421|A/cattle/USA/25-015684-005-original/2025||USA|2025|cattle|B3.13
>SRR33830422|A/cattle/USA/25-015684-004-original/2025||USA|2025|cattle|B3.13
>SRR33830423|A/cattle/USA/25-015684-003-original/2025||USA|2025|cattle|B3.13
>SRR33830424|A/cattle/USA/25-015684-002-original/2025||USA|2025|cattle|B3.13
>SRR33830425|A/cattle/USA/25-015684-001-original/2025||USA|2025|cattle|B3.13
>SRR33830426|A/cattle/USA/25-015683-001-original/2025||USA|2025|cattle|B3.13
>SRR33830427|A/cattle/USA/24-036419-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830428|A/cattle/USA/25-015682-003-original/2025||USA|2025|cattle|B3.13
>SRR33830429|A/cattle/USA/25-015682-002-original/2025||USA|2025|cattle|B3.13
>SRR33830430|A/cattle/USA/25-015682-001-original/2025||USA|2025|cattle|B3.13
>SRR33830431|A/cattle/USA/25-015681-014-original/2025||USA|2025|cattle|B3.13
>SRR33830432|A/cattle/USA/25-015681-013-original/2025||USA|2025|cattle|B3.13
>SRR33830433|A/cattle/USA/25-015681-012-original/2025||USA|2025|cattle|B3.13
>SRR33830434|A/cattle/USA/25-015681-011-original/2025||USA|2025|cattle|B3.13
>SRR33830435|A/cattle/USA/25-015681-010-original/2025||USA|2025|cattle|B3.13
>SRR33830436|A/cattle/USA/25-015681-009-original/2025||USA|2025|cattle|B3.13
>SRR33830437|A/cattle/USA/25-015681-008-original/2025||USA|2025|cattle|B3.13
>SRR33830438|A/cattle/USA/24-036414-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830439|A/cattle/USA/25-015681-007-original/2025||USA|2025|cattle|B3.13
>SRR33830440|A/cattle/USA/25-015681-006-original/2025||USA|2025|cattle|B3.13
>SRR33830441|A/cattle/USA/25-015681-005-original/2025||USA|2025|cattle|B3.13
>SRR33830442|A/cattle/USA/25-015681-004-original/2025||USA|2025|cattle|B3.13
>SRR33830443|A/cattle/USA/25-015681-003-original/2025||USA|2025|cattle|B3.13
>SRR33830444|A/cattle/USA/25-015681-002-original/2025||USA|2025|cattle|B3.13
>SRR33830445|A/cattle/USA/25-015681-001-original/2025||USA|2025|cattle|B3.13
>SRR33830449|A/cattle/USA/24-036379-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830450|A/cattle/USA/24-034788-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830355|A/cattle/USA/25-016216-005-original/2025||USA|2025|cattle|B3.13
>SRR33830356|A/cattle/USA/25-016216-004-original/2025||USA|2025|cattle|B3.13
>SRR33830357|A/cattle/USA/25-016216-003-original/2025||USA|2025|cattle|B3.13
>SRR33830358|A/cattle/USA/25-016216-002-original/2025||USA|2025|cattle|B3.13
>SRR33830359|A/cattle/USA/25-016216-001-original/2025||USA|2025|cattle|B3.13
>SRR33830360|A/cattle/USA/25-016215-002-original/2025||USA|2025|cattle|B3.13
>SRR33830362|A/cattle/USA/25-016215-001-original/2025||USA|2025|cattle|B3.13
>SRR33830363|A/cattle/USA/25-016214-001-original/2025||USA|2025|cattle|B3.13
>SRR33830364|A/cattle/USA/25-016212-002-original/2025||USA|2025|cattle|B3.13
>SRR33830365|A/cattle/USA/25-016212-001-original/2025||USA|2025|cattle|B3.13
>SRR33830366|A/cattle/USA/25-016210-002-original/2025||USA|2025|cattle|B3.13
>SRR33830367|A/cattle/USA/25-016210-001-original/2025||USA|2025|cattle|B3.13
>SRR33830368|A/cattle/USA/25-016209-001-original/2025||USA|2025|cattle|B3.13
>SRR33830369|A/cattle/USA/25-016208-001-original/2025||USA|2025|cattle|B3.13
>SRR33830370|A/cattle/USA/25-016207-001-original/2025||USA|2025|cattle|B3.13
>SRR33830371|A/cattle/USA/25-016205-001-original/2025||USA|2025|cattle|B3.13
>SRR33830372|A/cattle/USA/25-015655-001-original/2025||USA|2025|cattle|B3.13
>SRR33830373|A/cattle/USA/25-016204-001-original/2025||USA|2025|cattle|B3.13
>SRR33830374|A/cattle/USA/25-016202-001-original/2025||USA|2025|cattle|B3.13
>SRR33830375|A/cattle/USA/25-016201-001-original/2025||USA|2025|cattle|B3.13
>SRR33830376|A/cattle/USA/25-016200-002-original/2025||USA|2025|cattle|B3.13
>SRR33830377|A/cattle/USA/25-016200-001-original/2025||USA|2025|cattle|B3.13
>SRR33830378|A/cattle/USA/25-016199-001-original/2025||USA|2025|cattle|B3.13
>SRR33830379|A/cattle/USA/25-016198-001-original/2025||USA|2025|cattle|B3.13
>SRR33830380|A/cattle/USA/25-016196-002-original/2025||USA|2025|cattle|B3.13
>SRR33830381|A/cattle/USA/25-016196-001-original/2025||USA|2025|cattle|B3.13
>SRR33830383|A/cattle/USA/24-038352-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830384|A/cattle/USA/25-010490-001-v/2025||USA|2025|cattle|B3.13
>SRR33830385|A/cattle/USA/25-015748-002-original/2025||USA|2025|cattle|B3.13
>SRR33830386|A/cattle/USA/25-015739-002-original/2025||USA|2025|cattle|B3.13
>SRR33830387|A/cattle/USA/25-015739-001-original/2025||USA|2025|cattle|B3.13
>SRR33830388|A/cattle/USA/25-015738-001-original/2025||USA|2025|cattle|B3.13
>SRR33830389|A/cattle/USA/25-015736-002-original/2025||USA|2025|cattle|B3.13
>SRR33830390|A/cattle/USA/25-015734-004-original/2025||USA|2025|cattle|B3.13
>SRR33830391|A/cattle/USA/25-015734-002-original/2025||USA|2025|cattle|B3.13
>SRR33830392|A/cattle/USA/25-015730-002-original/2025||USA|2025|cattle|B3.13
>SRR33830393|A/cattle/USA/25-015724-003-original/2025||USA|2025|cattle|B3.13
>SRR33830394|A/cattle/USA/24-037350-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830396|A/cattle/USA/25-015723-001-original/2025||USA|2025|cattle|B3.13
>SRR33830397|A/cattle/USA/25-015713-005-original/2025||USA|2025|cattle|B3.13
>SRR33830398|A/cattle/USA/25-015713-004-original/2025||USA|2025|cattle|B3.13
>SRR33830399|A/cattle/USA/25-015704-001-original/2025||USA|2025|cattle|B3.13
>SRR33830400|A/cattle/USA/25-015696-002-original/2025||USA|2025|cattle|B3.13
>SRR33830401|A/cattle/USA/25-015696-001-original/2025||USA|2025|cattle|B3.13
>SRR33830402|A/cattle/USA/25-015689-004-original/2025||USA|2025|cattle|B3.13
>SRR33830403|A/cattle/USA/25-015689-003-original/2025||USA|2025|cattle|B3.13
>SRR33830404|A/cattle/USA/25-015689-002-original/2025||USA|2025|cattle|B3.13
>SRR33830405|A/cattle/USA/24-036764-003-tile/2024||USA|2024|cattle|B3.13
>SRR33830406|A/cattle/USA/25-015689-001-original/2025||USA|2025|cattle|B3.13
>SRR33830407|A/cattle/USA/25-015688-002-original/2025||USA|2025|cattle|B3.13
>SRR33830408|A/cattle/USA/25-015686-009-original/2025||USA|2025|cattle|B3.13
>SRR33830409|A/cattle/USA/25-015686-008-original/2025||USA|2025|cattle|B3.13
>SRR33830410|A/cattle/USA/25-015686-007-original/2025||USA|2025|cattle|B3.13
>SRR33830411|A/cattle/USA/25-015686-006-original/2025||USA|2025|cattle|B3.13
>SRR33830412|A/cattle/USA/25-015686-005-original/2025||USA|2025|cattle|B3.13
>SRR33830413|A/cattle/USA/25-015686-004-original/2025||USA|2025|cattle|B3.13
>SRR33830414|A/cattle/USA/25-015686-003-original/2025||USA|2025|cattle|B3.13
>SRR33830415|A/cattle/USA/25-015686-002-original/2025||USA|2025|cattle|B3.13
>SRR33830416|A/cattle/USA/24-036764-002-tile/2024||USA|2024|cattle|B3.13
>SRR33830417|A/cattle/USA/25-015686-001-original/2025||USA|2025|cattle|B3.13
>SRR33830418|A/cattle/USA/25-015684-008-original/2025||USA|2025|cattle|B3.13
>SRR33830419|A/cattle/USA/25-015684-007-original/2025||USA|2025|cattle|B3.13
>SRR33830420|A/cattle/USA/25-015684-006-original/2025||USA|2025|cattle|B3.13
>SRR33830421|A/cattle/USA/25-015684-005-original/2025||USA|2025|cattle|B3.13
>SRR33830422|A/cattle/USA/25-015684-004-original/2025||USA|2025|cattle|B3.13
>SRR33830423|A/cattle/USA/25-015684-003-original/2025||USA|2025|cattle|B3.13
>SRR33830424|A/cattle/USA/25-015684-002-original/2025||USA|2025|cattle|B3.13
>SRR33830425|A/cattle/USA/25-015684-001-original/2025||USA|2025|cattle|B3.13
>SRR33830426|A/cattle/USA/25-015683-001-original/2025||USA|2025|cattle|B3.13
>SRR33830427|A/cattle/USA/24-036419-001-tile/2024||USA|2024|cattle|B3.13
>SRR33830428|A/cattle/USA/25-015682-003-original/2025||USA|2025|cattle|B3.13
>SRR33830429|A/cattle/USA/25-015682-002-original/2025||USA|2025|cattle|B3.13
>SRR33830430|A/cattle/USA/25-015682-001-original/2025||USA|2025|cattle|B3.13
>SRR33830431|A/cattle/USA/25-015681-014-original/2025||USA|2025|cattle|B3.13
>SRR33830432|A/cattle/USA/25-015681-013-original/2025||USA|2025|cattle|B3.13
>SRR33830433|A/cattle/USA/25-015681-012-original/2025||USA|2025|cattle|B3.13
>SRR33830434|A/cattle/USA/25-015681-011-original/2025||USA|2025|cattle|B3.13
>SRR33830435|A/cattle/USA/25-015681-010-original/2025||USA|2025|cattle|B3.13
>SRR33830436|A/cattle/USA/25-015681-009-original/2025||USA|2025|cattle|B3.13
>SRR33830437|A/cattle/USA/25-015681-008-original/2025||USA|2025|cattle|B3.13
>SRR33830438|A/cattle/USA/24-036414-001-tile/2024||USA|2024|cattle|B3.13

## De-Duplication

In [21]:
# De-duplication 

# gisaid = downloads + "GISAID/complete/all_genotypes/11-01-2021--06-13-2025_all_genotypes_Antarctica_North_America_South_America/"
    # gisaid = downloads + "Cats/Datasets/GISAID/"

for genotype in genotypes:

    # gisaid = downloads + "GISAID/complete/" + genotype.replace(".", "_") + "/" + date_range + "_" + genotype.replace(".", "_") + "_Antarctica_North_America_South_America/"
    
    gisaid = downloads + "GISAID/complete/2025-06-14--2025-06-20_" + genotype.replace(".", "_") + "_Antarctica_North_America_South_America/"

    os.chdir(gisaid)

    # Gisaid 
    dfs_gisaid_list = []
    dfs_gisaid = create_dataframes(gisaid)
    dfs_gisaid_list.append(dfs_gisaid)

# dfs_gisaid = {}
# for df_gisaid in dfs_gisaid_list:
#     dfs_gisaid = dfs_gisaid | df_gisaid
# # dfs_gisaid2 = create_dataframes(gisaid2)

B3.13_HA
B3.13_HA
B3.13_MP
B3.13_MP
B3.13_NA
B3.13_NA
B3.13_NP
B3.13_NP
B3.13_NS
B3.13_NS
B3.13_PA
B3.13_PA
B3.13_PB1
B3.13_PB1
B3.13_PB2
B3.13_PB2
D1.1_HA
D1.1_HA
D1.1_MP
D1.1_MP
D1.1_NA
D1.1_NA
D1.1_NP
D1.1_NP
D1.1_NS
D1.1_NS
D1.1_PA
D1.1_PA
D1.1_PB1
D1.1_PB1
D1.1_PB2
D1.1_PB2

In [22]:
# Do the same with Andersen 

# dfs_andersen = create_dataframes(complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/")
dfs_andersen = create_dataframes(originals + "complete/")

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
D2.1_HA
D2.1_MP
D2.1_NA
D2.1_NP
D2.1_NS
D2.1_PA
D2.1_PB1
D2.1_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor101_HA
Minor101_MP
Minor101_NA
Minor101_NP
Minor101_NS
Minor101_PA
Minor101_PB1
Minor101_PB2
Minor102_HA
Minor102_MP
Minor102_NA
Minor102_NP
Minor102_NS
Minor102_PA
Minor102_PB1
Minor102_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor104_HA
Minor104_MP
Minor104_NA
Minor104_NP
Minor104_NS
Minor104_PA
Minor104_PB1
Minor104_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor106_HA
Minor106_MP
Minor106_NA
Minor106_NP
Minor106_NS
Minor106_PA
Minor106_PB1
Minor106_PB2
Minor10_HA
Minor10_MP
Minor10_NA
Minor10_NP
Minor10_NS
Minor10_PA
Minor10_PB1
Minor10_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor16_HA
Minor16_MP
Minor16_NA
Minor16_NP
Minor16_NS
Minor16_PA
Minor16_PB1
Minor16_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor18_HA
Minor18_MP
Minor18_NA
Minor18_NP
Minor18_NS
Minor18_PA
Minor18_PB1
Minor18_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor24_HA
Minor24_MP
Minor24_NA
Minor24_NP
Minor24_NS
Minor24_PA
Minor24_PB1
Minor24_PB2
Minor25_HA
Minor25_MP
Minor25_NA
Minor25_NP
Minor25_NS
Minor25_PA
Minor25_PB1
Minor25_PB2
Minor26_HA
Minor26_MP
Minor26_NA
Minor26_NP
Minor26_NS
Minor26_PA
Minor26_PB1
Minor26_PB2
Minor27_HA
Minor27_MP
Minor27_NA
Minor27_NP
Minor27_NS
Minor27_PA
Minor27_PB1
Minor27_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor29_HA
Minor29_MP
Minor29_NA
Minor29_NP
Minor29_NS
Minor29_PA
Minor29_PB1
Minor29_PB2
Minor30_HA
Minor30_MP
Minor30_NA
Minor30_NP
Minor30_NS
Minor30_PA
Minor30_PB1
Minor30_PB2
Minor31_HA
Minor31_MP
Minor31_NA
Minor31_NP
Minor31_NS
Minor31_PA
Minor31_PB1
Minor31_PB2
Minor32_HA
Minor32_MP
Minor32_NA
Minor32_NP
Minor32_NS
Minor32_PA
Minor32_PB1
Minor32_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor37_HA
Minor37_MP
Minor37_NA
Minor37_NP
Minor37_NS
Minor37_PA
Minor37_PB1
Minor37_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor39_HA
Minor39_MP
Minor39_NA
Minor39_NP
Minor39_NS
Minor39_PA
Minor39_PB1
Minor39_PB2
Minor40_HA
Minor40_MP
Minor40_NA
Minor40_NP
Minor40_NS
Minor40_PA
Minor40_PB1
Minor40_PB2
Minor41_HA
Minor41_MP
Minor41_NA
Minor41_NP
Minor41_NS
Minor41_PA
Minor41_PB1
Minor41_PB2
Minor42_HA
Minor42_MP
Minor42_NA
Minor42_NP
Minor42_NS
Minor42_PA
Minor42_PB1
Minor42_PB2
Minor43_HA
Minor43_MP
Minor43_NA
Minor43_NP
Minor43_NS
Minor43_PA
Minor43_PB1
Minor43_PB2
Minor44_HA
Minor44_MP
Minor44_NA
Minor44_NP
Minor44_NS
Minor44_PA
Minor44_PB1
Minor44_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor46_HA
Minor46_MP
Minor46_NA
Minor46_NP
Minor46_NS
Minor46_PA
Minor46_PB1
Minor46_PB2
Minor47_HA
Minor47_MP
Minor47_NA
Minor47_NP
Minor47_NS
Minor47_PA
Minor47_PB1
Minor47_PB2
Minor48_HA
Minor48_MP
Minor48_NA
Minor48_NP
Minor48_NS
Minor48_PA
Minor48_PB1
Minor48_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor52_HA
Minor52_MP
Minor52_NA
Minor52_NP
Minor52_NS
Minor52_PA
Minor52_PB1
Minor52_PB2
Minor53_HA
Minor53_MP
Minor53_NA
Minor53_NP
Minor53_NS
Minor53_PA
Minor53_PB1
Minor53_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor56_HA
Minor56_MP
Minor56_NA
Minor56_NP
Minor56_NS
Minor56_PA
Minor56_PB1
Minor56_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor67_HA
Minor67_MP
Minor67_NA
Minor67_NP
Minor67_NS
Minor67_PA
Minor67_PB1
Minor67_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor71_HA
Minor71_MP
Minor71_NA
Minor71_NP
Minor71_NS
Minor71_PA
Minor71_PB1
Minor71_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor74_HA
Minor74_MP
Minor74_NA
Minor74_NP
Minor74_NS
Minor74_PA
Minor74_PB1
Minor74_PB2
Minor75_HA
Minor75_MP
Minor75_NA
Minor75_NP
Minor75_NS
Minor75_PA
Minor75_PB1
Minor75_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor78_HA
Minor78_MP
Minor78_NA
Minor78_NP
Minor78_NS
Minor78_PA
Minor78_PB1
Minor78_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor80_HA
Minor80_MP
Minor80_NA
Minor80_NP
Minor80_NS
Minor80_PA
Minor80_PB1
Minor80_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor82_HA
Minor82_MP
Minor82_NA
Minor82_NP
Minor82_NS
Minor82_PA
Minor82_PB1
Minor82_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor84_HA
Minor84_MP
Minor84_NA
Minor84_NP
Minor84_NS
Minor84_PA
Minor84_PB1
Minor84_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor92_HA
Minor92_MP
Minor92_NA
Minor92_NP
Minor92_NS
Minor92_PA
Minor92_PB1
Minor92_PB2
Minor93_HA
Minor93_MP
Minor93_NA
Minor93_NP
Minor93_NS
Minor93_PA
Minor93_PB1
Minor93_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor95_HA
Minor95_MP
Minor95_NA
Minor95_NP
Minor95_NS
Minor95_PA
Minor95_PB1
Minor95_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
Minor98_HA
Minor98_MP
Minor98_NA
Minor98_NP
Minor98_NS
Minor98_PA
Minor98_PB1
Minor98_PB2
Minor99_HA
Minor99_MP
Minor99_NA
Minor99_NP
Minor99_NS
Minor99_PA
Minor99_PB1
Minor99_PB2

In [23]:
# os.chdir(downloads)
# dfs_gisaid["B3.13_HA"].to_csv

In [24]:
for key in dfs_andersen.keys():
    dataframes = dfs_andersen[key]
    print(key)

print(dfs_andersen)

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
D2.1_HA
D2.1_MP
D2.1_NA
D2.1_NP
D2.1_NS
D2.1_PA
D2.1_PB1
D2.1_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor101_HA
Minor101_MP
Minor101_NA
Minor101_NP
Minor101_NS
Minor101_PA
Minor101_PB1
Minor101_PB2
Minor102_HA
Minor102_MP
Minor102_NA
Minor102_NP
Minor102_NS
Minor102_PA
Minor102_PB1
Minor102_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor104_HA
Minor104_MP
Minor104_NA
Minor104_NP
Minor104_NS
Minor104_PA
Minor104_PB1
Minor104_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor106_HA
Minor106_MP
Minor106_NA
Minor106_NP
Minor106_NS
Minor106_PA
Minor106_PB1
Minor106_PB2
Minor10_HA
Minor10_MP
Minor10_NA
Minor10_NP
Minor10_NS
Minor10_PA
Minor10_PB1
Minor10_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor16_HA
Minor16_MP
Minor16_NA
Minor16_NP
Minor16_NS
Minor16_PA
Minor16_PB1
Minor16_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor18_HA
Minor18_MP
Minor18_NA
Minor18_NP
Minor18_NS
Minor18_PA
Minor18_PB1
Minor18_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor24_HA
Minor24_MP
Minor24_NA
Minor24_NP
Minor24_NS
Minor24_PA
Minor24_PB1
Minor24_PB2
Minor25_HA
Minor25_MP
Minor25_NA
Minor25_NP
Minor25_NS
Minor25_PA
Minor25_PB1
Minor25_PB2
Minor26_HA
Minor26_MP
Minor26_NA
Minor26_NP
Minor26_NS
Minor26_PA
Minor26_PB1
Minor26_PB2
Minor27_HA
Minor27_MP
Minor27_NA
Minor27_NP
Minor27_NS
Minor27_PA
Minor27_PB1
Minor27_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor29_HA
Minor29_MP
Minor29_NA
Minor29_NP
Minor29_NS
Minor29_PA
Minor29_PB1
Minor29_PB2
Minor30_HA
Minor30_MP
Minor30_NA
Minor30_NP
Minor30_NS
Minor30_PA
Minor30_PB1
Minor30_PB2
Minor31_HA
Minor31_MP
Minor31_NA
Minor31_NP
Minor31_NS
Minor31_PA
Minor31_PB1
Minor31_PB2
Minor32_HA
Minor32_MP
Minor32_NA
Minor32_NP
Minor32_NS
Minor32_PA
Minor32_PB1
Minor32_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor37_HA
Minor37_MP
Minor37_NA
Minor37_NP
Minor37_NS
Minor37_PA
Minor37_PB1
Minor37_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor39_HA
Minor39_MP
Minor39_NA
Minor39_NP
Minor39_NS
Minor39_PA
Minor39_PB1
Minor39_PB2
Minor40_HA
Minor40_MP
Minor40_NA
Minor40_NP
Minor40_NS
Minor40_PA
Minor40_PB1
Minor40_PB2
Minor41_HA
Minor41_MP
Minor41_NA
Minor41_NP
Minor41_NS
Minor41_PA
Minor41_PB1
Minor41_PB2
Minor42_HA
Minor42_MP
Minor42_NA
Minor42_NP
Minor42_NS
Minor42_PA
Minor42_PB1
Minor42_PB2
Minor43_HA
Minor43_MP
Minor43_NA
Minor43_NP
Minor43_NS
Minor43_PA
Minor43_PB1
Minor43_PB2
Minor44_HA
Minor44_MP
Minor44_NA
Minor44_NP
Minor44_NS
Minor44_PA
Minor44_PB1
Minor44_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor46_HA
Minor46_MP
Minor46_NA
Minor46_NP
Minor46_NS
Minor46_PA
Minor46_PB1
Minor46_PB2
Minor47_HA
Minor47_MP
Minor47_NA
Minor47_NP
Minor47_NS
Minor47_PA
Minor47_PB1
Minor47_PB2
Minor48_HA
Minor48_MP
Minor48_NA
Minor48_NP
Minor48_NS
Minor48_PA
Minor48_PB1
Minor48_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor52_HA
Minor52_MP
Minor52_NA
Minor52_NP
Minor52_NS
Minor52_PA
Minor52_PB1
Minor52_PB2
Minor53_HA
Minor53_MP
Minor53_NA
Minor53_NP
Minor53_NS
Minor53_PA
Minor53_PB1
Minor53_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor56_HA
Minor56_MP
Minor56_NA
Minor56_NP
Minor56_NS
Minor56_PA
Minor56_PB1
Minor56_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor67_HA
Minor67_MP
Minor67_NA
Minor67_NP
Minor67_NS
Minor67_PA
Minor67_PB1
Minor67_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor71_HA
Minor71_MP
Minor71_NA
Minor71_NP
Minor71_NS
Minor71_PA
Minor71_PB1
Minor71_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor74_HA
Minor74_MP
Minor74_NA
Minor74_NP
Minor74_NS
Minor74_PA
Minor74_PB1
Minor74_PB2
Minor75_HA
Minor75_MP
Minor75_NA
Minor75_NP
Minor75_NS
Minor75_PA
Minor75_PB1
Minor75_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor78_HA
Minor78_MP
Minor78_NA
Minor78_NP
Minor78_NS
Minor78_PA
Minor78_PB1
Minor78_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor80_HA
Minor80_MP
Minor80_NA
Minor80_NP
Minor80_NS
Minor80_PA
Minor80_PB1
Minor80_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor82_HA
Minor82_MP
Minor82_NA
Minor82_NP
Minor82_NS
Minor82_PA
Minor82_PB1
Minor82_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor84_HA
Minor84_MP
Minor84_NA
Minor84_NP
Minor84_NS
Minor84_PA
Minor84_PB1
Minor84_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor92_HA
Minor92_MP
Minor92_NA
Minor92_NP
Minor92_NS
Minor92_PA
Minor92_PB1
Minor92_PB2
Minor93_HA
Minor93_MP
Minor93_NA
Minor93_NP
Minor93_NS
Minor93_PA
Minor93_PB1
Minor93_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor95_HA
Minor95_MP
Minor95_NA
Minor95_NP
Minor95_NS
Minor95_PA
Minor95_PB1
Minor95_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
Minor98_HA
Minor98_MP
Minor98_NA
Minor98_NP
Minor98_NS
Minor98_PA
Minor98_PB1
Minor98_PB2
Minor99_HA
Minor99_MP
Minor99_NA
Minor99_NP
Minor99_NS
Minor99_PA
Minor99_PB1
Minor99_PB2
defaultdict(<class 'list'>, {'A1_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A3_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A3_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A3_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A3_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A3_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A3_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A3_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A3_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.11_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.11_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.11_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.11_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.11_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.11_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.11_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.11_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.12_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.12_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.12_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.12_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.12_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.12_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]

In [25]:
print(len(list(dfs_gisaid.keys())))
print(len(list(dfs_andersen.keys())))

8
968

In [26]:
# Merge dataframes and drop duplicates

full_dfs = defaultdict(list)
# same = []
# andersen = set()
# gisaid = set()

for i, andersen_key in enumerate(dfs_andersen.keys()):
    if len(dfs_andersen[andersen_key]) > 0:
        for j, gisaid_key in enumerate(dfs_gisaid.keys()):
            if andersen_key == gisaid_key:
                # same.append(gisaid_key)
        # gisaid_key = list(dfs_gisaid.keys())[i]
        # gisaid2_key = list(dfs_gisaid2.keys())[i]

                andersen_df = dfs_andersen[andersen_key][0]
                print(len(andersen_df))
                # print(andersen_df)
                gisaid_df = dfs_gisaid[gisaid_key][0]
                print(len(gisaid_df))
                # gisaid2_df = dfs_gisaid2[gisaid2_key][0]

                print(pd.concat([gisaid_df, andersen_df]).drop_duplicates())

                full_df = pd.concat([andersen_df, gisaid_df], ignore_index=True)
                print("len full df:", len(full_df))
                test = len(full_df.drop_duplicates(subset="isolate_partial"))

                dedup_df = full_df.drop_duplicates(subset="isolate_partial", keep="last")

                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print(full_df)
                
                print("Keeping nothing: ", test)
                
                print("len deduplicated:", len(dedup_df))
                full_dfs[andersen_key].append(dedup_df)
            # else:
                # gisaid.add(gisaid_key)
                # andersen.add(andersen_key)
    
    # break 


# print(full_dfs)
# print(len(full_dfs))
# print(319*8)
# print(len(same))
# print(len(andersen))
# print(len(gisaid))

21
16
   isolate_partial                                        full_header  \
0       011565-001  >EPI_ISL_19909395|A/dairy_cow/Nevada/25_011565...
1       007985-001  >EPI_ISL_19909344|A/dairy_cow/Nevada/25_007985...
2       016340-002  >EPI_ISL_20049107|A/chicken/USA/016340-002/202...
3       017017-005  >EPI_ISL_20049106|A/chicken/USA/017017-005/202...
4       017216-002  >EPI_ISL_20049109|A/chicken/USA/017216-002/202...
5       017216-001  >EPI_ISL_20049108|A/chicken/USA/017216-001/202...
6       017017-003  >EPI_ISL_20049111|A/chicken/USA/017017-003/202...
7       017017-004  >EPI_ISL_20049110|A/chicken/USA/017017-004/202...
8       017017-002  >EPI_ISL_20049113|A/chicken/USA/017017-002/202...
9       016340-001  >EPI_ISL_20049112|A/chicken/USA/016340-001/202...
10      017017-001  >EPI_ISL_20049114|A/chicken/USA/017017-001/202...
11      012798-007  >EPI_ISL_19909343|A/duck/New_York/25-012798-00...
12      016765-001  >EPI_ISL_20049096|A/dairy_cow/USA/016765-001/2...
13      016857-001  >EPI_ISL_20049099|A/turkey_vulture/USA/016857-...
14      017245-001  >EPI_ISL_20049101|A/red_fox/USA/017245-001/202...
15      017251-001  >EPI_ISL_20049103|A/black_vulture/USA/017251-0...
0       013422-001  >SRR33830324|A/turkey vulture/USA/25-013422-00...
1       015561-001  >SRR33830325|A/turkey vulture/USA/25-015561-00...
2       013427-001  >SRR33830326|A/red-tailed hawk/USA/25-013427-0...
3       013424-001  >SRR33830327|A/red-tailed hawk/USA/25-013424-0...
4       015870-001  >SRR33830328|A/great horned owl/USA/25-015870-...
5       015755-001  >SRR33830329|A/common grackle/USA/25-015755-00...
6       015563-001  >SRR33830330|A/black vulture/USA/25-015563-001...
7       013426-001  >SRR33830331|A/bald eagle/USA/25-013426-001-or...
8       013422-002  >SRR33830332|A/turkey vulture/USA/25-013422-00...
9       015562-001  >SRR33830333|A/bald eagle/USA/25-015562-001-or...
10      015759-001  >SRR33830334|A/bald eagle/USA/25-015759-001-or...
11      016339-009  >SRR33830340|A/chicken/USA/25-016339-009-origi...
12      016339-008  >SRR33830341|A/chicken/USA/25-016339-008-origi...
13      016339-007  >SRR33830342|A/chicken/USA/25-016339-007-origi...
14      016339-006  >SRR33830343|A/chicken/USA/25-016339-006-origi...
15      016339-005  >SRR33830344|A/chicken/USA/25-016339-005-origi...
16      016339-004  >SRR33830345|A/chicken/USA/25-016339-004-origi...
17      016339-003  >SRR33830346|A/chicken/USA/25-016339-003-origi...
18      016339-002  >SRR33830347|A/chicken/USA/25-016339-002-origi...
19      016339-001  >SRR33830348|A/chicken/USA/25-016339-001-origi...
20      016338-002  >SRR33830349|A/chicken/USA/25-016338-002-origi...

                                             sequence
0   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
1   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
2   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
3   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
4   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
5   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
6   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
7   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
8   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
9   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
10  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
11  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
12  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
13  atggaaaacatagtacttcttcttgcaataattagccttgttaaag...
14  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
15  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
0   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
3   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
5   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
6   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
7   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
8   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
9   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
10  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
11  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
12  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
13  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
14  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
15  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
16  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
17  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
18  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
19  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
20  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
len full df: 37
Keeping nothing:  37
len deduplicated: 37
21
16
   isolate_partial                                        full_header  \
0       011565-001  >EPI_ISL_19909395|A/dairy_cow/Nevada/25_011565...
1       007985-001  >EPI_ISL_19909344|A/dairy_cow/Nevada/25_007985...
2       016340-002  >EPI_ISL_20049107|A/chicken/USA/016340-002/202...
3       017017-005  >EPI_ISL_20049106|A/chicken/USA/017017-005/202...
4       017216-002  >EPI_ISL_20049109|A/chicken/USA/017216-002/202...
5       017216-001  >EPI_ISL_20049108|A/chicken/USA/017216-001/202...
6       017017-003  >EPI_ISL_20049111|A/chicken/USA/017017-003/202...
7       017017-004  >EPI_ISL_20049110|A/chicken/USA/017017-004/202...
8       017017-002  >EPI_ISL_20049113|A/chicken/USA/017017-002/202...
9       016340-001  >EPI_ISL_20049112|A/chicken/USA/016340-001/202...
10      017017-001  >EPI_ISL_20049114|A/chicken/USA/017017-001/202...
11      012798-007  >EPI_ISL_19909343|A/duck/New_York/25-012798-00...
12      016765-001  >EPI_ISL_20049096|A/dairy_cow/USA/016765-001/2...
13      016857-001  >EPI_ISL_20049099|A/turkey_vulture/USA/016857-...
14      017245-001  >EPI_ISL_20049101|A/red_fox/USA/017245-001/202...
15      017251-001  >EPI_ISL_20049103|A/black_vulture/USA/017251-0...
0       013422-001  >SRR33830324|A/turkey vulture/USA/25-013422-00...
1       015561-001  >SRR33830325|A/turkey vulture/USA/25-015561-00...
2       013427-001  >SRR33830326|A/red-tailed hawk/USA/25-013427-0...
3       013424-001  >SRR33830327|A/red-tailed hawk/USA/25-013424-0...
4       015870-001  >SRR33830328|A/great horned owl/USA/25-015870-...
5       015755-001  >SRR33830329|A/common grackle/USA/25-015755-00...
6       015563-001  >SRR33830330|A/black vulture/USA/25-015563-001...
7       013426-001  >SRR33830331|A/bald eagle/USA/25-013426-001-or...
8       013422-002  >SRR33830332|A/turkey vulture/USA/25-013422-00...
9       015562-001  >SRR33830333|A/bald eagle/USA/25-015562-001-or...
10      015759-001  >SRR33830334|A/bald eagle/USA/25-015759-001-or...
11      016339-009  >SRR33830340|A/chicken/USA/25-016339-009-origi...
12      016339-008  >SRR33830341|A/chicken/USA/25-016339-008-origi...
13      016339-007  >SRR33830342|A/chicken/USA/25-016339-007-origi...
14      016339-006  >SRR33830343|A/chicken/USA/25-016339-006-origi...
15      016339-005  >SRR33830344|A/chicken/USA/25-016339-005-origi...
16      016339-004  >SRR33830345|A/chicken/USA/25-016339-004-origi...
17      016339-003  >SRR33830346|A/chicken/USA/25-016339-003-origi...
18      016339-002  >SRR33830347|A/chicken/USA/25-016339-002-origi...
19      016339-001  >SRR33830348|A/chicken/USA/25-016339-001-origi...
20      016338-002  >SRR33830349|A/chicken/USA/25-016338-002-origi...

                                             sequence
0   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
1   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
2   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
3   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
4   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
5   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
6   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
7   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
8   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
9   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
10  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
11  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
12  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
13  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
14  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
15  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
0   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
5   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
6   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
7   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
8   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
9   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
10  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCATCC...
11  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
12  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
13  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
14  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
15  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
16  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
17  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
18  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
19  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
20  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
len full df: 37
Keeping nothing:  37
len deduplicated: 37
21
16
   isolate_partial                                        full_header  \
0       011565-001  >EPI_ISL_19909395|A/dairy_cow/Nevada/25_011565...
1       007985-001  >EPI_ISL_19909344|A/dairy_cow/Nevada/25_007985...
2       016340-002  >EPI_ISL_20049107|A/chicken/USA/016340-002/202...
3       017017-005  >EPI_ISL_20049106|A/chicken/USA/017017-005/202...
4       017216-002  >EPI_ISL_20049109|A/chicken/USA/017216-002/202...
5       017216-001  >EPI_ISL_20049108|A/chicken/USA/017216-001/202...
6       017017-003  >EPI_ISL_20049111|A/chicken/USA/017017-003/202...
7       017017-004  >EPI_ISL_20049110|A/chicken/USA/017017-004/202...
8       017017-002  >EPI_ISL_20049113|A/chicken/USA/017017-002/202...
9       016340-001  >EPI_ISL_20049112|A/chicken/USA/016340-001/202...
10      017017-001  >EPI_ISL_20049114|A/chicken/USA/017017-001/202...
11      012798-007  >EPI_ISL_19909343|A/duck/New_York/25-012798-00...
12      016765-001  >EPI_ISL_20049096|A/dairy_cow/USA/016765-001/2...
13      016857-001  >EPI_ISL_20049099|A/turkey_vulture/USA/016857-...
14      017245-001  >EPI_ISL_20049101|A/red_fox/USA/017245-001/202...
15      017251-001  >EPI_ISL_20049103|A/black_vulture/USA/017251-0...
0       013422-001  >SRR33830324|A/turkey vulture/USA/25-013422-00...
1       015561-001  >SRR33830325|A/turkey vulture/USA/25-015561-00...
2       013427-001  >SRR33830326|A/red-tailed hawk/USA/25-013427-0...
3       013424-001  >SRR33830327|A/red-tailed hawk/USA/25-013424-0...
4       015870-001  >SRR33830328|A/great horned owl/USA/25-015870-...
5       015755-001  >SRR33830329|A/common grackle/USA/25-015755-00...
6       015563-001  >SRR33830330|A/black vulture/USA/25-015563-001...
7       013426-001  >SRR33830331|A/bald eagle/USA/25-013426-001-or...
8       013422-002  >SRR33830332|A/turkey vulture/USA/25-013422-00...
9       015562-001  >SRR33830333|A/bald eagle/USA/25-015562-001-or...
10      015759-001  >SRR33830334|A/bald eagle/USA/25-015759-001-or...
11      016339-009  >SRR33830340|A/chicken/USA/25-016339-009-origi...
12      016339-008  >SRR33830341|A/chicken/USA/25-016339-008-origi...
13      016339-007  >SRR33830342|A/chicken/USA/25-016339-007-origi...
14      016339-006  >SRR33830343|A/chicken/USA/25-016339-006-origi...
15      016339-005  >SRR33830344|A/chicken/USA/25-016339-005-origi...
16      016339-004  >SRR33830345|A/chicken/USA/25-016339-004-origi...
17      016339-003  >SRR33830346|A/chicken/USA/25-016339-003-origi...
18      016339-002  >SRR33830347|A/chicken/USA/25-016339-002-origi...
19      016339-001  >SRR33830348|A/chicken/USA/25-016339-001-origi...
20      016338-002  >SRR33830349|A/chicken/USA/25-016338-002-origi...

                                             sequence
0   atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
1   atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
2   atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
3   atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
4   atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
5   atgaatccaaaycaaaagataataacyatcgggtcaatctgcatgg...
6   atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
7   atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
8   atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
9   atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
10  atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
11  atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
12  atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
13  atgaatccaaatcaaaagataataactatcgggtcattctgcatgg...
14  atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
15  atgaatccaaatcaaaaaataataactatcgggtcaatctgcatga...
0   ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGA...
1   ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCGTGG...
2   ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
3   ATGAATCCAAATCAAAAGATAATAACTATAGGGTCAATCTGCATGG...
4   ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
5   ATGAATCCAAATCAGAAGATAATAACTATCGGGTCAATCTGCATGG...
6   ATGAATCCAAATCAAAAAATAATAACTATCGGGTCAATCTGCATGA...
7   ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
8   ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGA...
9   ATGAATCCAAATCAAAAGATAATAACCATCGGGTCAATCTGCATGG...
10  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
11  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
12  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
13  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
14  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
15  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
16  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
17  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
18  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
19  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
20  ATGAAGCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
len full df: 37
Keeping nothing:  37
len deduplicated: 37
21
16
   isolate_partial                                        full_header  \
0       011565-001  >EPI_ISL_19909395|A/dairy_cow/Nevada/25_011565...
1       007985-001  >EPI_ISL_19909344|A/dairy_cow/Nevada/25_007985...
2       016340-002  >EPI_ISL_20049107|A/chicken/USA/016340-002/202...
3       017017-005  >EPI_ISL_20049106|A/chicken/USA/017017-005/202...
4       017216-002  >EPI_ISL_20049109|A/chicken/USA/017216-002/202...
5       017216-001  >EPI_ISL_20049108|A/chicken/USA/017216-001/202...
6       017017-003  >EPI_ISL_20049111|A/chicken/USA/017017-003/202...
7       017017-004  >EPI_ISL_20049110|A/chicken/USA/017017-004/202...
8       017017-002  >EPI_ISL_20049113|A/chicken/USA/017017-002/202...
9       016340-001  >EPI_ISL_20049112|A/chicken/USA/016340-001/202...
10      017017-001  >EPI_ISL_20049114|A/chicken/USA/017017-001/202...
11      012798-007  >EPI_ISL_19909343|A/duck/New_York/25-012798-00...
12      016765-001  >EPI_ISL_20049096|A/dairy_cow/USA/016765-001/2...
13      016857-001  >EPI_ISL_20049099|A/turkey_vulture/USA/016857-...
14      017245-001  >EPI_ISL_20049101|A/red_fox/USA/017245-001/202...
15      017251-001  >EPI_ISL_20049103|A/black_vulture/USA/017251-0...
0       013422-001  >SRR33830324|A/turkey vulture/USA/25-013422-00...
1       015561-001  >SRR33830325|A/turkey vulture/USA/25-015561-00...
2       013427-001  >SRR33830326|A/red-tailed hawk/USA/25-013427-0...
3       013424-001  >SRR33830327|A/red-tailed hawk/USA/25-013424-0...
4       015870-001  >SRR33830328|A/great horned owl/USA/25-015870-...
5       015755-001  >SRR33830329|A/common grackle/USA/25-015755-00...
6       015563-001  >SRR33830330|A/black vulture/USA/25-015563-001...
7       013426-001  >SRR33830331|A/bald eagle/USA/25-013426-001-or...
8       013422-002  >SRR33830332|A/turkey vulture/USA/25-013422-00...
9       015562-001  >SRR33830333|A/bald eagle/USA/25-015562-001-or...
10      015759-001  >SRR33830334|A/bald eagle/USA/25-015759-001-or...
11      016339-009  >SRR33830340|A/chicken/USA/25-016339-009-origi...
12      016339-008  >SRR33830341|A/chicken/USA/25-016339-008-origi...
13      016339-007  >SRR33830342|A/chicken/USA/25-016339-007-origi...
14      016339-006  >SRR33830343|A/chicken/USA/25-016339-006-origi...
15      016339-005  >SRR33830344|A/chicken/USA/25-016339-005-origi...
16      016339-004  >SRR33830345|A/chicken/USA/25-016339-004-origi...
17      016339-003  >SRR33830346|A/chicken/USA/25-016339-003-origi...
18      016339-002  >SRR33830347|A/chicken/USA/25-016339-002-origi...
19      016339-001  >SRR33830348|A/chicken/USA/25-016339-001-origi...
20      016338-002  >SRR33830349|A/chicken/USA/25-016338-002-origi...

                                             sequence
0   atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
1   atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
2   atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
3   atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
4   atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
5   atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
6   atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
7   atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
8   atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
9   atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
10  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
11  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
12  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
13  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
14  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
15  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
0   ATGGCGTCTCAAGGCACCAAGCGATCCTATGAACAAATGGAAACTG...
1   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
2   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
3   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
4   ATGGCGTCTCAAGGCACCAAACGATCTTATGAACAAATGGAAACTG...
5   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
6   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
7   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
8   ATGGCGTCTCAAGGCACCAAGCGATCCTATGAACAAATGGAAACTG...
9   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
10  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
11  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
12  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
13  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
14  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
15  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
16  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
17  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
18  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
19  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
20  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
len full df: 37
Keeping nothing:  37
len deduplicated: 37
21
16
   isolate_partial                                        full_header  \
0       011565-001  >EPI_ISL_19909395|A/dairy_cow/Nevada/25_011565...
1       007985-001  >EPI_ISL_19909344|A/dairy_cow/Nevada/25_007985...
2       016340-002  >EPI_ISL_20049107|A/chicken/USA/016340-002/202...
3       017017-005  >EPI_ISL_20049106|A/chicken/USA/017017-005/202...
4       017216-002  >EPI_ISL_20049109|A/chicken/USA/017216-002/202...
5       017216-001  >EPI_ISL_20049108|A/chicken/USA/017216-001/202...
6       017017-003  >EPI_ISL_20049111|A/chicken/USA/017017-003/202...
7       017017-004  >EPI_ISL_20049110|A/chicken/USA/017017-004/202...
8       017017-002  >EPI_ISL_20049113|A/chicken/USA/017017-002/202...
9       016340-001  >EPI_ISL_20049112|A/chicken/USA/016340-001/202...
10      017017-001  >EPI_ISL_20049114|A/chicken/USA/017017-001/202...

In [27]:
# # If none in one database, only use the other and drop duplicates

# full_dfs = defaultdict(list)
# for key in dfs_andersen.keys():
#     print(key)
# # for key in ["D1.3"]:
#     dataframes = dfs_andersen[key]
#     for i, df in enumerate(dataframes):
#         print(i)
#         try:
#             full_df = df.merge(dfs_gisaid[key][i], how="outer")
#             # print(full_df)
#             full_df = full_df.drop_duplicates(subset=["isolate_partial"])
#             full_dfs[key].append(full_df)
#         except:
#             print("Failed to merge dataframes in ", key)
#             full_dfs[key].append(dataframes[i])

## Create FASTA files combining Andersen and GISAID

In [28]:
# Create FASTA files per segment

combined_files = downloads + "Combinations/GISAID_Andersen/" # B3_13_D1_1/" + date_range + "_B3_13_D1_1/"

os.chdir(combined_files)
for pair in full_dfs.keys():
    print(pair)
    output_path = combined_files + pair + "_combined_" + date_range + ".fasta" 

    output_file = open(output_path, "w")
    for item in full_dfs[pair]:
        # for item in item:
        # item = fasta_files[pair]
        for index, row in item.iterrows():
            name = item.loc[index, "full_header"]
            sequence = item.loc[index, "sequence"]
            # print(name)
        # First is header, second is sequence
        # print(value)
            output_file.write(name)
            output_file.write(sequence)
    output_file.close()

D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2