# Cleaning Downloaded Data from avian-flu

Author: Alexander Maksiaev

Purpose: Clean downloaded data from avian-flu, rename sequences according to convention, de-duplicate from GISAID

In [1]:
# Housekeeping

import os
import glob 
import pandas as pd
import xml.etree.ElementTree as ET
import requests
import time
import numpy as np
import dateutil 
from datetime import datetime
from collections import defaultdict 
import importlib
import utils  
importlib.reload(utils)
from utils import * 

# Make sure you have the correct paths

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu"
# downloads = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
originals = downloads + "Andersen_Downloads/"
temp_files = downloads + "Andersen_Temp_Files/"
complete_files = downloads + "Andersen_Complete_Files/"

# Day we're updating data
update_date = "04-21-2025"

os.chdir(downloads)

## Read Metadata

In [2]:
# Read metadata

metadata_folder = originals + "avian-influenza/metadata/"
os.chdir(metadata_folder)

metadata = pd.read_csv("SraRunTable_automated.csv")

# print(len(metadata)) # 7397 rows

# Get rid of missing dates; they won't be counted anyway
for date in metadata["Collection_Date"]:
    if "/" in date or date == "missing":
        metadata = metadata[metadata["Collection_Date"] != date]

# Find only >= 2024 to start
metadata["Collection_Date_Compare"] = metadata["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
metadata = metadata[metadata["Collection_Date_Compare"] >= datetime(2024, 1, 1).strftime("%Y-%m-%d")]

# Find only >= last date using Release Date from metadata 
metadata["ReleaseDate"] = metadata["ReleaseDate"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
metadata = metadata[metadata["ReleaseDate"] >= datetime(2024, 1, 1).strftime("%Y-%m-%d")]

print(len(metadata)) # 6053 rows between 1/1/2024 and 4/14/2025

7044

In [ ]:
# # Get list of genotypes

# os.chdir(home)

# genotypes_df = pd.read_excel("genotype_key.xlsx")

# genotypes = list(genotypes_df["Genotype"])

# print(genotypes)

### Naming convention ###
>A/[host]/[geo_loc_name]/[isolate]/[year]|[serotype: H5N1]|[collection_date]|[host_type]|[genotype]

host_type is from manual animal reference

In metadata, we have: host, geo_loc_name, isolate, year

We need: geo_loc_name, collection_date, host_type, genotype

host = Host

geo_loc_name (primary) = geo_loc_name

geo_loc_name (secondary) = genbank_mapping.tsv > genbank_name

isolate = isolate

collection date (primary) = Collection_Date

collection date (secondary) = https://www.ncbi.nlm.nih.gov/genbank/ > BioSample (input: BioSample) > Nucleotide > [first result] > collection_date

serotype = serotype

host type = [from ref] 

genotype = [from genoflu] -- use genoflu_results.tsv

## Get genotype, specific geolocation

In [4]:
# Get genotype from genoflu_results.tsv

os.chdir(metadata_folder)

genoflu_results = pd.read_csv("genoflu_results.tsv", delimiter="\t")

metadata["Genotype"] = genoflu_results["Genotype"]
metadata = metadata[~metadata["Genotype"].str.contains('Not assigned')] # Do not include non-assigned genotypes

# Get only the genotypes we want: B3.13 and D1.1

b313_and_d11_only = genoflu_results[(genoflu_results["Genotype"] == "B3.13") | (genoflu_results["Genotype"] == "D1.1")]
b313_and_d11_only = b313_and_d11_only.rename(columns={"sample": "Run"})
b313_and_d11_only = b313_and_d11_only.drop_duplicates(subset="Run", keep="last")

metadata = metadata.merge(b313_and_d11_only, on="Run", how="inner")

print(len(metadata))

5829

In [5]:
# Get specific geolocation from genbank_mapping.tsv

genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
genbank_mapping["Run"] = genbank_mapping["sra_run"]
genbank_mapping = genbank_mapping.drop_duplicates(subset="Run", keep="first") # Drop duplicates
genbank_mapping["name_state"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[2]) # Get the name of the state

metadata_genbank = metadata.merge(genbank_mapping, on=["Run"], how="inner") # Only include data that has states

print(genbank_mapping["name_state"])
print(len(metadata_genbank))
display(metadata_genbank)

0        Texas
8        Texas
16       Texas
24       Texas
32       Texas
         ...
38678       OH
38686       OH
38694       OH
38702       OH
38710       MT
Name: name_state, Length: 4279, dtype: object
3692

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,Genotype Mismatch List,Genotype Average Depth of Coverage List,seg_file,seg_seq_name,sra_run,seg,genbank_acc,genbank_seg,genbank_name,name_state
0,SRR28752447,WGS,241.29,86080323,PRJNA1102327,SAMN41019237,Viral,28164109,USDA-NVSL,2024,...,"26, 10, 18, 21, 9, 13, 11, 6",Ran on FASTA - No Coverage Report,SRR28752447_HA_cns.fa,Consensus_SRR28752447_HA_cns_threshold_0.5_qua...,SRR28752447,HA,PP752829.1,4,A/cattle/Texas/24-009108-005/2024,Texas
1,SRR28752448,WGS,250.30,75035343,PRJNA1102327,SAMN41019236,Viral,24547283,USDA-NVSL,2024,...,"26, 10, 17, 21, 10, 13, 11, 7",Ran on FASTA - No Coverage Report,SRR28752448_HA_cns.fa,Consensus_SRR28752448_HA_cns_threshold_0.5_qua...,SRR28752448,HA,PP752821.1,4,A/cattle/Texas/24-009108-004/2024,Texas
2,SRR28752449,WGS,146.61,59363690,PRJNA1102327,SAMN41019235,Viral,19686302,USDA-NVSL,2024,...,"26, 10, 18, 21, 9, 13, 11, 6",Ran on FASTA - No Coverage Report,SRR28752449_HA_cns.fa,Consensus_SRR28752449_HA_cns_threshold_0.5_qua...,SRR28752449,HA,PP752813.1,4,A/cattle/Texas/24-009108-003/2024,Texas
3,SRR28752450,WGS,251.31,119232569,PRJNA1102327,SAMN41019234,Viral,38846827,USDA-NVSL,2024,...,"27, 10, 17, 21, 10, 13, 11, 7",Ran on FASTA - No Coverage Report,SRR28752450_HA_cns.fa,Consensus_SRR28752450_HA_cns_threshold_0.5_qua...,SRR28752450,HA,PP752805.1,4,A/cattle/Texas/24-009108-002/2024,Texas
4,SRR28752453,WGS,144.71,37055919,PRJNA1102327,SAMN41019231,Viral,12938409,USDA-NVSL,2024,...,"26, 12, 16, 24, 9, 12, 12, 7",Ran on FASTA - No Coverage Report,SRR28752453_HA_cns.fa,Consensus_SRR28752453_HA_cns_threshold_0.5_qua...,SRR28752453,HA,PP752677.1,4,A/cattle/Texas/24-009088-001/2024,Texas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3687,SRR32633088,WGS,145.11,67016467,PRJNA1102327,SAMN47290851,Viral,25388495,USDA-NVSL,2025,...,"32, 11, 21, 24, 17, 15, 11, 9",Ran on FASTA - No Coverage Report,SRR32633088_HA_cns.fa,Consensus_SRR32633088_HA_cns_threshold_0.5_qua...,SRR32633088,HA,PV456280.1,4,A/cat/OR/25-005913-003-original/2025,OR
3688,SRR32633089,WGS,148.14,140023511,PRJNA1102327,SAMN47290850,Viral,52157519,USDA-NVSL,2025,...,"33, 11, 22, 25, 16, 15, 11, 9",Ran on FASTA - No Coverage Report,SRR32633089_HA_cns.fa,Consensus_SRR32633089_HA_cns_threshold_0.5_qua...,SRR32633089,HA,PV456272.1,4,A/cat/OR/25-005800-002-original/2025,OR
3689,SRR32633090,WGS,148.49,83727737,PRJNA1102327,SAMN47290849,Viral,31619233,USDA-NVSL,2025,...,"33, 12, 23, 25, 16, 16, 11, 8",Ran on FASTA - No Coverage Report,SRR32633090_HA_cns.fa,Consensus_SRR32633090_HA_cns_threshold_0.5_qua...,SRR32633090,HA,PV456264.1,4,A/cat/OR/25-005800-001-original/2025,OR
3690,SRR32633093,WGS,148.10,105910536,PRJNA1102327,SAMN47290846,Viral,39757708,USDA-NVSL,2025,...,"32, 16, 23, 29, 18, 18, 10, 7",Ran on FASTA - No Coverage Report,SRR32633093_HA_cns.fa,Consensus_SRR32633093_HA_cns_threshold_0.5_qua...,SRR32633093,HA,PV457240.1,4,A/cattle/CA/25-005677-001-original/2025,CA
3691,SRR32633094,WGS,148.09,109655942,PRJNA1102327,SAMN47290845,Viral,41506380,USDA-NVSL,2025,...,"32, 12, 23, 31, 17, 15, 10, 8",Ran on FASTA - No Coverage Report,SRR32633094_HA_cns.fa,Consensus_SRR32633094_HA_cns_threshold_0.5_qua...,SRR32633094,HA,PV457232.1,4,A/cattle/CA/25-005648-001-original/2025,CA

## Get and save collection date

In [6]:

# Get all dates
# metadata_genbank["Collection_Date_Specific"] = metadata_genbank["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank))

# Save this so we don't have to do it again

# os.chdir(temp_files)
# metadata_genbank.to_csv("metadata_genbank.csv")

In [ ]:
# Upload saved data -- if doing this, make sure the above cell is commented out
os.chdir(temp_files + "saved/")
metadata_genbank_dates = pd.read_csv("metadata_genbank_4-18-2025.csv")
os.chdir(temp_files)

# Get only updated dates

unknown_dates = metadata_genbank_dates[(metadata_genbank_dates["Collection_Date_Specific"] == "2024") | (metadata_genbank_dates["Collection_Date_Specific"] == "2025")] # Dates we don't have
known_dates = metadata_genbank_dates[(metadata_genbank_dates["Collection_Date_Specific"] != "2024") & (metadata_genbank_dates["Collection_Date_Specific"] != "2025")] # Dates we've already gotten

# Get new dates also 
# new_dates = metadata_genbank["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank) if )

updated_unknown_dates = unknown_dates["BioSample"].apply(lambda x: search_collection_date(x, unknown_dates)) # Update unknown dates, if possible

metadata_genbank = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)


display(metadata_genbank)

SAMN41019181
Unable to find collection date.
SAMN41106834
Unable to find collection date.
SAMN41106833
Unable to find collection date.
SAMN41106832
Unable to find collection date.
SAMN41106831
Unable to find collection date.
SAMN41106830
Unable to find collection date.
SAMN41106829
Unable to find collection date.
SAMN41106828
Unable to find collection date.
SAMN41106827
Unable to find collection date.
SAMN41106826
Unable to find collection date.
SAMN41106825
Unable to find collection date.
SAMN41106783
Unable to find collection date.
SAMN41106780
Unable to find collection date.
SAMN41106820
Unable to find collection date.
SAMN41106819
Unable to find collection date.
SAMN41106815
Unable to find collection date.
SAMN41106808
Unable to find collection date.
SAMN41106755
Unable to find collection date.
SAMN41489080
Unable to find collection date.
SAMN41489095
Unable to find collection date.
SAMN41489094
Unable to find collection date.
SAMN41489093
Unable to find collection date.
SAMN41489091
Unable to find collection date.
SAMN41489090
Unable to find collection date.
SAMN41489089
Unable to find collection date.
SAMN41489088
Unable to find collection date.
SAMN41489087
Unable to find collection date.
SAMN42535324
SAMN42535322
SAMN43274409
Unable to find collection date.
SAMN43274408
Unable to find collection date.
SAMN43274407
Unable to find collection date.
SAMN43274466
Unable to find collection date.
SAMN43274465
Unable to find collection date.
SAMN43274464
Unable to find collection date.
SAMN43274462
Unable to find collection date.
SAMN43274461
Unable to find collection date.
SAMN43274460
Unable to find collection date.
SAMN43274406
Unable to find collection date.
SAMN43274459
Unable to find collection date.
SAMN43274458
Unable to find collection date.
SAMN43274457
Unable to find collection date.
SAMN43274456
Unable to find collection date.
SAMN43274455
Unable to find collection date.
SAMN43274454
Unable to find collection date.
SAMN43274453
Unable to find collection date.
SAMN43274452
Unable to find collection date.
SAMN43274451
Unable to find collection date.
SAMN43274450
Unable to find collection date.
SAMN43274405
Unable to find collection date.
SAMN43274449
Unable to find collection date.
SAMN43274448
Unable to find collection date.
SAMN43274447
Unable to find collection date.
SAMN43274446
Unable to find collection date.
SAMN43274445
Unable to find collection date.
SAMN43274444
Unable to find collection date.
SAMN43274443
Unable to find collection date.
SAMN43274442
Unable to find collection date.
SAMN43274441
Unable to find collection date.
SAMN43274440
Unable to find collection date.
SAMN43274404
Unable to find collection date.
SAMN43274439
Unable to find collection date.
SAMN43274438
Unable to find collection date.
SAMN43274437
Unable to find collection date.
SAMN43274436
Unable to find collection date.
SAMN43274434
Unable to find collection date.
SAMN43274433
Unable to find collection date.
SAMN43274432
Unable to find collection date.
SAMN43274431
Unable to find collection date.
SAMN43274430
Unable to find collection date.
SAMN43274403
Unable to find collection date.
SAMN43274429
Unable to find collection date.
SAMN43274428
Unable to find collection date.
SAMN43274427
Unable to find collection date.
SAMN43274426
Unable to find collection date.
SAMN43274425
Unable to find collection date.
SAMN43274424
Unable to find collection date.
SAMN43274423
Unable to find collection date.
SAMN43274422
Unable to find collection date.
SAMN43274421
Unable to find collection date.
SAMN43274420
Unable to find collection date.
SAMN43274402
Unable to find collection date.
SAMN43274419
Unable to find collection date.
SAMN43274418
Unable to find collection date.
SAMN43274417
Unable to find collection date.
SAMN43274416
Unable to find collection date.
SAMN43274415
Unable to find collection date.
SAMN43274414
Unable to find collection date.
SAMN43274413
Unable to find collection date.
SAMN43274411
Unable to find collection date.
SAMN43274410
Unable to find collection date.
SAMN43274401
Unable to find collection date.
SAMN43274400
Unable to find collection date.
SAMN44493006
SAMN44493005
SAMN44493004
SAMN44611619
SAMN45128649
SAMN45128648
SAMN45163990
SAMN45164381
SAMN45164314
SAMN45164313
SAMN45164290
SAMN45164289
SAMN45164097
SAMN45164098
SAMN45164099
SAMN45164106
SAMN45164107
SAMN45164108
SAMN45164109
SAMN45128858
Unable to find collection date.
SAMN45128857
Unable to find collection date.
SAMN45128856
Unable to find collection date.
SAMN45128855
Unable to find collection date.
SAMN45128853
Unable to find collection date.
SAMN45128852
Unable to find collection date.
SAMN45128851
Unable to find collection date.
SAMN45128850
Unable to find collection date.
SAMN45128849
Unable to find collection date.
SAMN45128771
Unable to find collection date.
SAMN45128848
Unable to find collection date.
SAMN45128770
Unable to find collection date.
SAMN45128841
Unable to find collection date.
SAMN45128840
Unable to find collection date.
SAMN45128839
Unable to find collection date.
SAMN45128765
Unable to find collection date.
SAMN45128791
Unable to find collection date.
SAMN45128790
Unable to find collection date.
SAMN45128786
Unable to find collection date.
SAMN45128991
Unable to find collection date.
SAMN45128990
Unable to find collection date.
SAMN45128785
Unable to find collection date.
SAMN45128977
Unable to find collection date.
SAMN45128975
Unable to find collection date.
SAMN45128974
Unable to find collection date.
SAMN45128972
Unable to find collection date.
SAMN45128971
Unable to find collection date.
SAMN45128989
Unable to find collection date.
SAMN45128988
Unable to find collection date.
SAMN45128987
Unable to find collection date.
SAMN45128784
Unable to find collection date.
SAMN45128986
Unable to find collection date.
SAMN45128985
Unable to find collection date.
SAMN45128970
Unable to find collection date.
SAMN45128984
Unable to find collection date.
SAMN45128983
Unable to find collection date.
SAMN45128982
Unable to find collection date.
SAMN45128981
Unable to find collection date.
SAMN45128838
Unable to find collection date.
SAMN45128769
Unable to find collection date.
SAMN45128829
Unable to find collection date.
SAMN45128828
Unable to find collection date.
SAMN45128827
Unable to find collection date.
SAMN45128826
Unable to find collection date.
SAMN45128825
Unable to find collection date.
SAMN45128824
Unable to find collection date.
SAMN45128823
Unable to find collection date.
SAMN45128822
Unable to find collection date.
SAMN45128768
Unable to find collection date.
SAMN45128817
Unable to find collection date.
SAMN45128816
Unable to find collection date.
SAMN45128815
Unable to find collection date.
SAMN45128814
Unable to find collection date.
SAMN45128812
Unable to find collection date.
SAMN45128767
Unable to find collection date.
SAMN45128811
Unable to find collection date.
SAMN45128810
Unable to find collection date.
SAMN45128788
Unable to find collection date.
SAMN45128787
Unable to find collection date.
SAMN45128980
Unable to find collection date.
SAMN45128979
Unable to find collection date.
SAMN45128783
Unable to find collection date.
SAMN45128966
Unable to find collection date.
SAMN45128965
Unable to find collection date.
SAMN45128964
Unable to find collection date.
SAMN45128936
Unable to find collection date.
SAMN45128782
Unable to find collection date.
SAMN45128764
Unable to find collection date.
SAMN45128935
Unable to find collection date.
SAMN45128934
Unable to find collection date.
SAMN45128933
Unable to find collection date.
SAMN45128932
Unable to find collection date.
SAMN45128963
Unable to find collection date.
SAMN45128962
Unable to find collection date.
SAMN45128961
Unable to find collection date.
SAMN45128781
Unable to find collection date.
SAMN45128958
Unable to find collection date.
SAMN45128930
Unable to find collection date.
SAMN45128929
Unable to find collection date.
SAMN45128928
Unable to find collection date.
SAMN45128927
Unable to find collection date.
SAMN45128797
Unable to find collection date.
SAMN45128796
Unable to find collection date.
SAMN45128795
Unable to find collection date.
SAMN45128794
Unable to find collection date.
SAMN45128793
Unable to find collection date.
SAMN45128792
Unable to find collection date.
SAMN45128945
Unable to find collection date.
SAMN45128777
Unable to find collection date.
SAMN45128944
Unable to find collection date.
SAMN45128943
Unable to find collection date.
SAMN45128942
Unable to find collection date.
SAMN45128941
Unable to find collection date.
SAMN45128904
Unable to find collection date.
SAMN45128903
Unable to find collection date.
SAMN45128902
Unable to find collection date.
SAMN45128901
Unable to find collection date.
SAMN45128900
Unable to find collection date.
SAMN45128776
Unable to find collection date.
SAMN45128898
Unable to find collection date.
SAMN45128897
Unable to find collection date.
SAMN45128896
Unable to find collection date.
SAMN45128895
Unable to find collection date.
SAMN45128894
Unable to find collection date.
SAMN45128893
Unable to find collection date.
SAMN45128892
Unable to find collection date.
SAMN45128891
Unable to find collection date.
SAMN45128890
Unable to find collection date.
SAMN45128775
Unable to find collection date.
SAMN45128888
Unable to find collection date.
SAMN45128887
Unable to find collection date.
SAMN45128886
Unable to find collection date.
SAMN45128809
Unable to find collection date.
SAMN45128807
Unable to find collection date.
SAMN45128806
Unable to find collection date.
SAMN45128805
Unable to find collection date.
SAMN45128804
Unable to find collection date.
SAMN45128802
Unable to find collection date.
SAMN45128766
Unable to find collection date.
SAMN45128800
Unable to find collection date.
SAMN45128798
Unable to find collection date.
SAMN45128925
Unable to find collection date.
SAMN45128923
Unable to find collection date.
SAMN45128922
Unable to find collection date.
SAMN45128780
Unable to find collection date.
SAMN45128921
Unable to find collection date.
SAMN45128957
Unable to find collection date.
SAMN45128956
Unable to find collection date.
SAMN45128915
Unable to find collection date.
SAMN45128914
Unable to find collection date.
SAMN45128912
Unable to find collection date.
SAMN45128955
Unable to find collection date.
SAMN45128954
Unable to find collection date.
SAMN45128953
Unable to find collection date.
SAMN45128911
Unable to find collection date.
SAMN45128910
Unable to find collection date.
SAMN45128909
Unable to find collection date.
SAMN45128778
Unable to find collection date.
SAMN45128908
Unable to find collection date.
SAMN45128907
Unable to find collection date.
SAMN45128906
Unable to find collection date.
SAMN45128905
Unable to find collection date.
SAMN45128885
Unable to find collection date.
SAMN45128884
Unable to find collection date.
SAMN45128883
Unable to find collection date.
SAMN45128882
Unable to find collection date.
SAMN45128881
Unable to find collection date.
SAMN45128880
Unable to find collection date.
SAMN45128879
Unable to find collection date.
SAMN45128774
Unable to find collection date.
SAMN45128878
Unable to find collection date.
SAMN45128877
Unable to find collection date.
SAMN45128876
Unable to find collection date.
SAMN45128875
Unable to find collection date.
SAMN45128874
Unable to find collection date.
SAMN45128873
Unable to find collection date.
SAMN45128872
Unable to find collection date.
SAMN45128871
Unable to find collection date.
SAMN45128870
Unable to find collection date.
SAMN45128869
Unable to find collection date.
SAMN45128773
Unable to find collection date.
SAMN45128868
Unable to find collection date.
SAMN45128867
Unable to find collection date.
SAMN45128866
Unable to find collection date.
SAMN45128865
Unable to find collection date.
SAMN45128864
Unable to find collection date.
SAMN45128863
Unable to find collection date.
SAMN45128862
Unable to find collection date.
SAMN45128861
Unable to find collection date.
SAMN45128860
Unable to find collection date.
SAMN45128859
Unable to find collection date.
SAMN45128772
Unable to find collection date.
SAMN45128763
Unable to find collection date.
SAMN45128762
Unable to find collection date.
SAMN46070114
SAMN46070084
SAMN46070082
SAMN46070081
SAMN46070080
SAMN46070079
SAMN46070078
SAMN46070077
SAMN46070076
SAMN46070075
SAMN46070074
SAMN46133391
SAMN46133389
SAMN46133358
SAMN46133357
SAMN46133356
SAMN46133351
SAMN46133345
SAMN46133344
SAMN46133341
SAMN46133340
SAMN46133339
SAMN46201490
Unable to find collection date.
SAMN46201469
SAMN46201468
SAMN46201411
SAMN46201410
SAMN46259211
Unable to find collection date.
SAMN46369303
SAMN46369302
SAMN46369247
SAMN46369352
SAMN46541210
SAMN46541209
SAMN46541189
SAMN46541188
SAMN46541184
SAMN46541183
SAMN46541181
SAMN46541180
SAMN46541178
SAMN46541174
SAMN46541426
SAMN46541425
SAMN46541424
SAMN46541423
SAMN46541467
SAMN46541422
SAMN46541466
SAMN46541465
SAMN46541464
SAMN46541463
SAMN46541462
SAMN46541461
SAMN46541460
SAMN46541459
SAMN46541458
SAMN46541457
SAMN46541421
SAMN46541456
SAMN46541455
SAMN46541454
SAMN46541453
SAMN46541452
SAMN46541451
SAMN46541450
SAMN46541449
SAMN46541448
SAMN46541447
SAMN46541420
SAMN46541446
SAMN46541445
SAMN46541444
SAMN46541443
SAMN46541442
SAMN46541441
SAMN46541439
SAMN46541438
SAMN46541437
SAMN46541419
SAMN46541436
SAMN46541435
SAMN46541434
SAMN46541433
SAMN46541432
SAMN46541431
SAMN46541430
SAMN46541428
SAMN46541427
SAMN46541418
SAMN46541390
SAMN46541389
SAMN46541388
SAMN46541386
SAMN46541385
SAMN46541406
SAMN46541405
SAMN46541404
SAMN46541403
SAMN46541402
SAMN46541384
SAMN46541400
SAMN46541398
SAMN46541397
SAMN46541395
SAMN46541394
SAMN46541392
SAMN46541382
SAMN46200743
SAMN46200742
SAMN44618603
Unable to find collection date.
SAMN46923570
SAMN46921974
SAMN46921973
SAMN46921972
SAMN46921971
SAMN46921970
SAMN46921969
SAMN46921968
SAMN46921967
SAMN46921966
SAMN46921965
SAMN46921964
SAMN46921963
SAMN46921962
SAMN46921961
SAMN46921960
SAMN46921959
SAMN46921958
SAMN46921956
SAMN46921955
SAMN46921954

,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSample Accession,BioSampleModel,Bytes,Center Name,Collection_Date,...,isolate,isolation_source,name_state,retraction_detection_date_utc,seg,seg_file,seg_seq_name,serotype,sra_run,version
0,WGS,241.29,86080323,PRJNA1102327,SAMN41019237,SRS21079811,Viral,28164109,USDA-NVSL,2024,...,24-009108-005-original,NaN,Texas,NaN,HA,SRR28752447_HA_cns.fa,Consensus_SRR28752447_HA_cns_threshold_0.5_qua...,H5N1,SRR28752447,1
1,WGS,250.30,75035343,PRJNA1102327,SAMN41019236,SRS21079810,Viral,24547283,USDA-NVSL,2024,...,24-009108-004-original,NaN,Texas,NaN,HA,SRR28752448_HA_cns.fa,Consensus_SRR28752448_HA_cns_threshold_0.5_qua...,H5N1,SRR28752448,1
2,WGS,146.61,59363690,PRJNA1102327,SAMN41019235,SRS21079809,Viral,19686302,USDA-NVSL,2024,...,24-009108-003-original,NaN,Texas,NaN,HA,SRR28752449_HA_cns.fa,Consensus_SRR28752449_HA_cns_threshold_0.5_qua...,H5N1,SRR28752449,1
3,WGS,251.31,119232569,PRJNA1102327,SAMN41019234,SRS21079808,Viral,38846827,USDA-NVSL,2024,...,24-009108-002-original,NaN,Texas,NaN,HA,SRR28752450_HA_cns.fa,Consensus_SRR28752450_HA_cns_threshold_0.5_qua...,H5N1,SRR28752450,1
4,WGS,144.71,37055919,PRJNA1102327,SAMN41019231,SRS21079806,Viral,12938409,USDA-NVSL,2024,...,24-009088-001-original,NaN,Texas,NaN,HA,SRR28752453_HA_cns.fa,Consensus_SRR28752453_HA_cns_threshold_0.5_qua...,H5N1,SRR28752453,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4058,WGS,146.98,106556038,PRJNA1102327,SAMN46921959,SRS24134530,Viral,39746392,USDA-NVSL,2025,...,25-003807-006,food sample,CO,NaN,HA,SRR32415259_HA_cns.fa,Consensus_SRR32415259_HA_cns_threshold_0.5_qua...,NaN,SRR32415259,1
4059,WGS,144.20,18361062,PRJNA1102327,SAMN46921958,SRS24134528,Viral,6990746,USDA-NVSL,2025,...,25-003807-005,food sample,CO,NaN,HA,SRR32415260_HA_cns.fa,Consensus_SRR32415260_HA_cns_threshold_0.5_qua...,NaN,SRR32415260,1
4060,WGS,146.80,49731175,PRJNA1102327,SAMN46921956,SRS24134526,Viral,18679978,USDA-NVSL,2025,...,25-003807-003,food sample,CO,NaN,HA,SRR32415262_HA_cns.fa,Consensus_SRR32415262_HA_cns_threshold_0.5_qua...,NaN,SRR32415262,1
4061,WGS,146.76,50267804,PRJNA1102327,SAMN46921955,SRS24134525,Viral,18729119,USDA-NVSL,2025,...,25-003807-002,food sample,CO,NaN,HA,SRR32415263_HA_cns.fa,Consensus_SRR32415263_HA_cns_threshold_0.5_qua...,NaN,SRR32415263,1
4062,WGS,145.54,56228387,PRJNA1102327,SAMN46921954,SRS24134524,Viral,21029434,USDA-NVSL,2025,...,25-003807-001,food sample,CO,NaN,HA,SRR32415264_HA_cns.fa,Consensus_SRR32415264_HA_cns_threshold_0.5_qua...,NaN,SRR32415264,1

In [12]:
print(metadata_genbank[["Collection_Date_Specific"]])

     Collection_Date_Specific
0                 20-Mar-2024
1                 20-Mar-2024
2                 20-Mar-2024
3                 20-Mar-2024
4                 13-Mar-2024
...                       ...
4058                     2025
4059                     2025
4060                     2025
4061                     2025
4062                     2025

[4063 rows x 1 columns]

## Get host type

In [13]:
# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genbank)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

os.chdir(downloads)

animals_ref = pd.read_csv("animals_ref.csv") # Upload animals ref

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['barn owl', 'hosp', 'cat', 'common raven', 'quail', 'bottlenose dolphin', 'ganada goose', 'hawk', 'eurasian collared dove', 'western sandpiper', 'rock pigeon', 'cattle milk product', 'cago', 'red-shouldered hawk', 'pefa', 'merganser', 'serval', 'hooded merganser', 'lion', "cooper's hawk", 'savannah cat', 'wood duck', 'black-crowned night-heron', 'vulture', 'falcon', 'owl', 'fox', 'great horned owl', 'american crow', 'raccoon', 'pheasant', 'dove', 'domestic cat', 'red tailed hawk', 'pig', 'emu', 'gadwall', 'peafowl', 'cackling goose', 'blackbird', 'snow goose', "geoffroy's cat", 'red fox', 'great blue heron', 'american wigeon', 'goat', 'burrowing owl', 'western gull', 'swan', 'crane', 'guinea fowl', 'goose', 'house-mouse', 'avian', 'skunk', 'pet food', 'lynx', 'tiger', 'grackle', 'green-winged teal', 'american robin', 'snowy owl', 'pigeon', 'domestic-cat', 'raw pet food', 'ermine', 'red-breasted merganser', 'bald eagle', 'chicken', 'mountain lion', 'turkey vulture', 'house mouse', 'comon-grackle', 'harris hawk', 'flamingo', 'alpaca', 'crow', 'red-tailed hawk', 'mute swan', 'guineafowl', 'feline', 'white-winged dove', 'duck', 'cattle', 'pelican', 'american woodcock', 'mallard', 'turkey', 'trumpeter swan', 'bobcat', 'canada goose', 'house sparrow']
[]
                 avian               cattle        feline   other_mammal  \
0     great_horned_owl            dairy_cow           cat         bobcat
1         common_raven               cattle  domestic_cat    house_mouse
2        cooper's_hawk  cattle milk product     feral_cat          skunk
3         coopers_hawk                  NaN        feline         cougar
4              peafowl                  NaN  domestic-cat  geoffroys_cat
..                 ...                  ...           ...            ...
284        guinea fowl                  NaN           NaN            NaN
285    red tailed hawk                  NaN           NaN            NaN
286  western sandpiper                  NaN           NaN            NaN
287       ganada goose                  NaN           NaN            NaN
288        harris hawk                  NaN           NaN            NaN

          human         other  new
0    washington         mixed  NaN
1        nevada   environment  NaN
2       wyoming  multispecies  NaN
3    california      pet food  NaN
4      michigan  raw pet food  NaN
..          ...           ...  ...
284         NaN           NaN  NaN
285         NaN           NaN  NaN
286         NaN           NaN  NaN
287         NaN           NaN  NaN
288         NaN           NaN  NaN

[289 rows x 7 columns]

In [14]:
# Get animals from animal reference
os.chdir(downloads)
animals_ref = pd.read_csv("animals_ref.csv")
fix_animals_andersen(metadata_genbank, animals_ref) # Get host type

metadata_genbank["years"] = metadata_genbank["Collection_Date"].apply(lambda x: str(x).split("-")[0]) # Get year only from collection date

## Make names using all the attributes we collected

In [15]:
for num, collection_date in enumerate(metadata_genbank["Collection_Date_Specific"]):
    if collection_date != collection_date: # If nan
        metadata_genbank.loc[num, "Collection_Date_Specific"] = metadata_genbank.loc[num, "years"]
    else: # If actual date
        if len(str(collection_date)) == 4: # If it's a year
            # print("caught")
            metadata_genbank.loc[num, "Collection_Date_Specific"] = collection_date
        else:
            parsed_date = dateutil.parser.parse(collection_date)
            date = parsed_date.strftime("%Y-%m-%d") # Make sure it doesn't default to today, if just a year
            metadata_genbank.loc[num, "Collection_Date_Specific"] = date

# Make names

names = ">A/" + metadata_genbank["Host"] + "/" + metadata_genbank["name_state"] + "/" + metadata_genbank["isolate"] + "/" + metadata_genbank["years"].apply(lambda x: str(x)) + "|H5N1|" + metadata_genbank["Collection_Date_Specific"].apply(lambda x: str(x)) + "|" + metadata_genbank["Host_Type"] + "|" + metadata_genbank["Genotype"]

metadata_genbank["Name"] = names

# metadata_genbank.to_csv("metadata_genbank_named.csv")

# display(metadata_genbank)

## Make FASTA files

In [16]:
# Get information to create the fasta files

fasta_folder = originals + "avian-influenza/fasta/"

os.chdir(fasta_folder)

segments = ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]
pairs = []
fasta_files = {}

for genotype in ["B3.13", "D1.1"]:
    for segment in segments:
        pair = genotype + "_" + segment
        pairs.append(pair)

for pair in pairs:
    fasta_files[pair] = [] # List to hold fasta files

for run in metadata_genbank["Run"].values: # For each run 
    for dirpath, dirs, files in os.walk(fasta_folder): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            # print(file_name)
            if run in file_name: # Note that there will be ~8 files total with that run name
                # Make a fasta file and put it in the list
                with open(file_name) as f:
                    lines = f.readlines()
                    sequence = lines[1] 
                    # Each run/segment pair has one sequence -- it's placed into a file with other run/segment pairs with the same segment and genotype
                    header = metadata_genbank[metadata_genbank["Run"] == run].loc[:, "Name"].values[0]
                    genotype = metadata_genbank[metadata_genbank["Run"] == run].loc[:, "Genotype"].values[0]
                    # print(header)
                    # print(genotype)
                    # break 
                    segment = file_name.split("_")[-2]
                    # Find the pair that corresponds to 
                    pair_name = genotype + "_" + segment
                    this_specific_fasta = []
                    for pair in pairs:
                        # print(pair)
                        # print(pair_name)
                        if pair_name == pair:
                            this_specific_fasta.append(header)
                            this_specific_fasta.append(sequence)
                            fasta_files[pair].append(this_specific_fasta)
                f.close()

D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
A1
A1
A1
A1
A1
A1
A1
A1
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
A1
A1
A1
A1
A1
A1
A1
A1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.2
B3.2
B3.2
B3.2
B3.2
B3.2
B3.2
B3.2
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
A3
A3
A3
A3
A3
A3
A3
A3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
A1
A1
A1
A1
A1
A1
A1
A1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
A1
A1
A1
A1
A1
A1
A1
A1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B2.2
B2.2
B2.2
B2.2
B2.2
B2.2
B2.2
B2.2
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
A1
A1
A1
A1
A1
A1
A1
A1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
A1
A1
A1
A1
A1
A1
A1
A1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
A1
A1
A1
A1
A1
A1
A1
A1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
A1
A1
A1
A1
A1
A1
A1
A1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
A2
A2
A2
A2
A2
A2
A2
A2
A1
A1
A1
A1
A1
A1
A1
A1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
A1
A1
A1
A1
A1
A1
A1
A1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
A3
A3
A3
A3
A3
A3
A3
A3
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
A1
A1
A1
A1
A1
A1
A1
A1
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
A1
A1
A1
A1
A1
A1
A1
A1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
A3
A3
A3
A3
A3
A3
A3
A3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.2
B3.2
B3.2
B3.2
B3.2
B3.2
B3.2
B3.2
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
A1
A1
A1
A1
A1
A1
A1
A1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.6
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
A3
A3
A3
A3
A3
A3
A3
A3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
A3
A3
A3
A3
A3
A3
A3
A3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
A1
A1
A1
A1
A1
A1
A1
A1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.12
B3.12
B3.12
B3.12
B3.12
B3.12
B3.12
B3.12
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.7
B3.7
B3.7
B3.7
B3.7
B3.7
B3.7
B3.7
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
B1.2
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
C2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
D1.3
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
A1
A1
A1
A1
A1
A1
A1
A1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B2.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
B1.1
A1
A1
A1
A1
A1
A1
A1
A1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
B3.13
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
D1.1
B3.13
B3.13

In [17]:
# Create fasta files 

os.chdir(temp_files)

for pair in fasta_files.keys():
    output_path = temp_files + pair + "_andersen_" + update_date + ".fasta" 

    output_file = open(output_path, "w")
    for item in fasta_files[pair]:
        # for item in item:
        # item = fasta_files[pair]
        try:
            name = str(item[0].values[0]) # See if this is one we didn't have a collection date for
        except:
            name = str(item[0])
        print(name)
        # First is header, second is sequence
        # print(value)
        output_file.write(name + "\n")
        output_file.write(item[1])
    output_file.close()

>A/Cattle/Texas/24-009108-004-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Texas/24-009108-003-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Texas/24-009108-002-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Texas/24-009088-001-original/2024|H5N1|2024-03-13|cattle|B3.13
>A/Cattle/Texas/24-009029-001-original/2024|H5N1|2024-03-21|cattle|B3.13
>A/Cattle/Texas/24-009028-009-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Texas/24-009028-008-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Texas/24-009028-007-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Texas/24-009028-005-original-repeat/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Texas/24-009028-002-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Texas/24-009028-001-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Michigan/24-009027-005-original-MTM/2024|H5N1|2024-03-24|cattle|B3.13
>A/Cattle/Michigan/24-009027-004-original-repeat/2024|H5N1|2024-03-24|cattle|B3.13
>A/Chicken/Texas/24-007264-001-original/2024|H5N1|2024-03-07|avian|B3.13
>A/Cattle/New Mexico/24-010193-003-original/2024|H5N1|2024-03-29|cattle|B3.13
>A/Cattle/New Mexico/24-010192-006-original/2024|H5N1|2024-04-01|cattle|B3.13
>A/Cattle/Michigan/24-010071-010-original/2024|H5N1|2024-04-01|cattle|B3.13
>A/Cattle/Michigan/24-010071-007-original/2024|H5N1|2024-04-01|cattle|B3.13
>A/Cattle/Michigan/24-010071-005-original/2024|H5N1|2024-04-01|cattle|B3.13
>A/Cattle/Michigan/24-010071-003-original/2024|H5N1|2024-04-01|cattle|B3.13
>A/Cattle/Texas/24-008749-001-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Michigan/24-010071-002-original/2024|H5N1|2024-04-01|cattle|B3.13
>A/Cattle/Texas/24-009776-004-original/2024|H5N1|2024-03-10|cattle|B3.13
>A/Cattle/Texas/24-009776-002-original/2024|H5N1|2024-03-10|cattle|B3.13
>A/Cattle/Ohio/24-009586-008-original/2024|H5N1|2024-03-29|cattle|B3.13
>A/Cattle/Ohio/24-009586-006-original/2024|H5N1|2024-03-29|cattle|B3.13
>A/Cattle/Ohio/24-009586-005-original/2024|H5N1|2024-03-29|cattle|B3.13
>A/Cattle/Ohio/24-009586-002-original/2024|H5N1|2024-03-29|cattle|B3.13
>A/Cattle/Ohio/24-009586-001-original/2024|H5N1|2024-03-29|cattle|B3.13
>A/Chicken/Michigan/24-009582-003-original/2024|H5N1|2024-04-01|avian|B3.13
>A/Chicken/Michigan/24-009582-002-original/2024|H5N1|2024-04-01|avian|B3.13
>A/Cattle/Texas/24-009290-001-original/2024|H5N1|2024-03-13|cattle|B3.13
>A/Cat/New Mexico/24-009116-002-original/2024|H5N1|2024-03-20|feline|B3.13
>A/Cattle/Texas/24-009110-024-original/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cattle/Texas/24-009110-022-original/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cat/Texas/24-008764-001-original/2024|H5N1|2024-03-22|feline|B3.13
>A/Cattle/Texas/24-008749-006-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Texas/24-010514-002-original/2024|H5N1|2024-04-03|cattle|B3.13
>A/Cattle/Texas/24-010513-006-original/2024|H5N1|2024-03-28|cattle|B3.13
>A/Cattle/Texas/24-010513-003-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/South Dakota/24-010354-018-original-300/2024|H5N1|2024-04-05|cattle|B3.13
>A/Cattle/South Dakota/24-010354-016-original-300/2024|H5N1|2024-04-05|cattle|B3.13
>A/Cattle/South Dakota/24-010354-011-original/2024|H5N1|2024-04-05|cattle|B3.13
>A/Cattle/South Dakota/24-010354-009-original-300/2024|H5N1|2024-04-05|cattle|B3.13
>A/Cattle/South Dakota/24-010354-006-original-300/2024|H5N1|2024-04-05|cattle|B3.13
>A/Chicken/Michigan/24-009582-001-original/2024|H5N1|2024-04-01|avian|B3.13
>A/Cattle/Texas/24-009499-001-original/2024|H5N1|2024-03-17|cattle|B3.13
>A/Cattle/Kansas/24-009497-014-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Cattle/Kansas/24-009497-011-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Cattle/Kansas/24-009497-010-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Cattle/Kansas/24-009497-008-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Cattle/Kansas/24-009497-007-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Blackbird/Texas/24-008357-001-original/2024|H5N1|2024-03-16|avian|B3.13
>A/Cattle/Kansas/24-009497-004-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Cattle/Texas/24-009495-012-original/2024|H5N1|2024-03-21|cattle|B3.13
>A/Cattle/Texas/24-009495-011-original/2024|H5N1|2024-03-21|cattle|B3.13
>A/Cattle/Texas/24-009495-010-original/2024|H5N1|2024-03-21|cattle|B3.13
>A/Cattle/Texas/24-009495-003-original/2024|H5N1|2024-03-21|cattle|B3.13
>A/Cattle/Texas/24-009495-002-original/2024|H5N1|2024-03-21|cattle|B3.13
>A/Cattle/Idaho/24-009491-005-original/2024|H5N1|2024-03-27|cattle|B3.13
>A/Cattle/Idaho/24-009491-003-original/2024|H5N1|2024-03-27|cattle|B3.13
>A/Cattle/Texas/24-009367-023-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Cattle/Texas/24-009110-021-original/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cattle/Texas/24-009110-020-original/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cattle/Texas/24-009110-018-original/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cattle/Texas/24-009110-016-original/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cattle/Texas/24-009110-015-original/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cattle/Texas/24-009110-012-original/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cattle/Texas/24-009110-010-original/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cattle/Texas/24-009110-007-original/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cattle/Texas/24-009110-005-original/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cattle/Texas/24-009110-004-original/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cattle/Texas/24-009110-003-original-repeat/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cattle/Texas/24-009110-001-original/2024|H5N1|2024-03-14|cattle|B3.13
>A/Cattle/Texas/24-009109-008-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Texas/24-009109-006-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Texas/24-009109-003-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Texas/24-009109-002-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/Texas/24-009108-006-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/New Mexico/24-010330-013-original-300/2024|H5N1|2024-04-01|cattle|B3.13
>A/Cattle/Texas/24-008749-004-original/2024|H5N1|2024-03-20|cattle|B3.13
>A/Cattle/New Mexico/24-010330-011-original-300/2024|H5N1|2024-04-01|cattle|B3.13
>A/Cattle/New Mexico/24-010330-008-original/2024|H5N1|2024-04-01|cattle|B3.13
>A/Cattle/New Mexico/24-010330-007-original/2024|H5N1|2024-04-01|cattle|B3.13
>A/Cattle/New Mexico/24-010330-005-original/2024|H5N1|2024-04-01|cattle|B3.13
>A/Cattle/New Mexico/24-010330-003-original/2024|H5N1|2024-04-01|cattle|B3.13
>A/PEFA/California/24-005915-001-original/2024|H5N1|2024-02-14|avian|B3.13
>A/Cattle/North Carolina/24-010327-003-original/2024|H5N1|2024-04-04|cattle|B3.13
>A/Chicken/Michigan/24-010308-012-original/2024|H5N1|2024-04-06|avian|B3.13
>A/Chicken/Michigan/24-010308-006-original-300/2024|H5N1|2024-04-06|avian|B3.13
>A/Cattle/New Mexico/24-010195-001-original/2024|H5N1|2024-03-15|cattle|B3.13
>A/Cattle/New Mexico/24-010194-001-original/2024|H5N1|2024-03-15|cattle|B3.13
>A/Cattle/New Mexico/24-010193-006-original/2024|H5N1|2024-03-29|cattle|B3.13
>A/Grackle/Texas/24-008356-001-original/2024|H5N1|2024-03-18|avian|B3.13
>A/Cattle/Texas/24-009367-018-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Cattle/Texas/24-009367-016-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Cattle/Texas/24-009367-013-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Cattle/Texas/24-009367-012-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Cattle/Texas/24-009367-011-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Cattle/Texas/24-009367-009-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Chicken/Texas/24-008355-006-original/2024|H5N1|2024-03-16|avian|B3.13
>A/Cattle/Texas/24-009367-004-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Cattle/Texas/24-009367-003-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Cattle/Texas/24-009367-001-original/2024|H5N1|2024-03-21|cattle|B3.13
>A/Cat/United States/24-009311-006-original/2024|H5N1|2024-03-16|feline|B3.13
>A/Cat/Texas/24-009311-004-original/2024|H5N1|2024-03-16|feline|B3.13
>A/Cattle/Texas/24-009310-007-original-repeat/2024|H5N1|2024-03-21|cattle|B3.13
>A/Cattle/Texas/24-009310-006-original/2024|H5N1|2024-03-21|cattle|B3.13
>A/Cattle/New Mexico/24-009309-004-original/2024|H5N1|2024-03-16|cattle|B3.13
>A/Cattle/New Mexico/24-009309-002-original/2024|H5N1|2024-03-16|cattle|B3.13
>A/Cattle/Texas/24-009308-008-original/2024|H5N1|2024-03-19|cattle|B3.13
>A/Cattle/New Mexico/24-009306-004-original/2024|H5N1|2024-03-25|cattle|B3.13
>A/Chicken/Texas/24-008355-004-original/2024|H5N1|2024-03-16|avian|B3.13
>A/CATTLE/North Carolina/24-010327-002/2024|H5N1|2024-04-04|cattle|B3.13
>A/PIGEON/Texas/24-008765-001/2024|H5N1|2024-03-20|avian|B3.13
>A/Chicken/Ohio/24-005334-001-original/2024|H5N1|2024-02-18|avian|B3.13
>A/GOAT/Minnesota/24-007234-003-original/2024|H5N1|2024-03-08|other_mammal|B3.13
>A/American Crow/Iowa/24-006634-001-original-repeat/2024|H5N1|2024-03-01|avian|B3.13
>A/Ganada Goose/Missouri/24-006385-003-original-repeat/2024|H5N1|2024-02-22|avian|B3.13
>A/Great Horned Owl/Oregon/24-006223-001-original/2024|H5N1|2024-02-21|avian|B3.13
>A/Bald Eagle/Virginia/24-006061-001-original/2024|H5N1|2023-02-05|avian|B3.13
>A/Red Tailed Hawk/South Carolina/24-005993-001-original/2024|H5N1|2024-01-09|avian|B3.13
>A/Mute Swan/California/24-005918-001-original/2024|H5N1|2024-02-06|avian|B3.13
>A/Chicken/Minnesota/24-005907-001-original/2024|H5N1|2024-02-24|avian|B3.13
>A/Chicken/Indiana/24-005716-003-original/2024|H5N1|2024-02-21|avian|B3.13
>A/Chicken/Maryland/24-005539-002-original/2024|H5N1|2024-02-16|avian|B3.13
>A/Turkey/Missouri/24-005372-001-original/2024|H5N1|2024-02-17|avian|B3.13
>A/Turkey/Missouri/24-005371-002-original/2024|H5N1|2024-02-17|avian|B3.13
>A/Turkey/Missouri/24-005369-002-original/2024|H5N1|2024-02-07|avian|B3.13
>A/Snow Goose/California/24-004881-004-original/2024|H5N1|2024-01-18|avian|B3.13
>A/American Wigeon/Ohio/24-008552-021-original/2024|H5N1|2023-11-10|avian|B3.13
>A/Skunk/Montana/24-007939-001-original/2024|H5N1|2024-03-11|other_mammal|B3.13
>A/Snow Goose/California/24-004881-002-original/2024|H5N1|2024-01-18|avian|B3.13
>A/Common Raven/California/24-007417-001-original/2024|H5N1|2024-02-20|avian|B3.13
>A/Turkey/South Dakota/24-007379-002-original/2024|H5N1|2024-03-08|avian|B3.13
>A/Chicken/Minnesota/24-007263-003-original/2024|H5N1|2024-03-07|avian|B3.13
>A/Chicken/Minnesota/24-007263-002-original/2024|H5N1|2024-03-07|avian|B3.13
>A/GOAT/Minnesota/24-007234-047/2024|H5N1|2024-03-08|other_mammal|B3.13
>A/Western Gull/California/24-004708-001-original/2024|H5N1|2024-01-30|avian|B3.13
>A/GOAT/Minnesota/24-007234-044/2024|H5N1|2024-03-08|other_mammal|B3.13
>A/GOAT/Minnesota/24-007234-037/2024|H5N1|2024-03-08|other_mammal|B3.13
>A/GOAT/Minnesota/24-007234-036/2024|H5N1|2024-03-08|other_mammal|B3.13
>A/GOAT/Minnesota/24-007234-035/2024|H5N1|2024-03-08|other_mammal|B3.13
>A/GOAT/Minnesota/24-007234-034/2024|H5N1|2024-03-08|other_mammal|B3.13
>A/GOAT/Minnesota/24-007234-032/2024|H5N1|2024-03-08|other_mammal|B3.13
>A/GOAT/Minnesota/24-007234-029/2024|H5N1|2024-03-08|other_mammal|B3.13
>A/CATTLE/MI/24-013021-003/2024|H5N1|2024-04-29|cattle|B3.13
>A/CATTLE/MI/24-013021-002/2024|H5N1|2024-04-29|cattle|B3.13
>A/DOMESTIC-CAT/NM/24-012046-004/2024|H5N1|2024-04-17|feline|B3.13
>A/RED FOX/MI/24-013016-004/2024|H5N1|2024-04-24|other_mammal|B3.13
>A/RED FOX/MI/24-013016-003/2024|H5N1|2024-04-24|other_mammal|B3.13
>A/RED FOX/MI/24-013016-001/2024|H5N1|2024-04-24|other_mammal|B3.13
>A/HAWK/New Mexico/24-012607-001/2024|H5N1|2024-04-23|avian|B3.13
>A/DOMESTIC-CAT/NM/24-012046-002/2024|H5N1|2024-04-17|feline|B3.13
>A/CATTLE/Idaho/24-013170-006/2024|H5N1|2024-05-01|cattle|B3.13
>A/CATTLE/MI/24-013172-002/2024|H5N1|2024-04-30|cattle|B3.13
>A/CATTLE/MI/24-013021-010/2024|H5N1|2024-04-29|cattle|B3.13
>A/CATTLE/MI/24-013021-009/2024|H5N1|2024-04-29|cattle|B3.13
>A/CATTLE/MI/24-013021-008/2024|H5N1|2024-04-29|cattle|B3.13
>A/CATTLE/MI/24-013021-004/2024|H5N1|2024-04-29|cattle|B3.13
>A/DOMESTIC-CAT/NM/24-012046-001/2024|H5N1|2024-04-17|feline|B3.13
>A/CATTLE/Idaho/24-012341-002/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/Idaho/24-011573-017-original-repeat/2024|H5N1|2024-04-15|cattle|B3.13
>A/CATTLE/MI/24-012377-010-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/MI/24-012377-009-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/MI/24-012377-006-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/MI/24-012377-004-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/MI/24-012377-003-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/MI/24-012377-001-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/Colorado/24-012346-021-original/2024|H5N1|2024-04-24|cattle|B3.13
>A/CATTLE/Idaho/24-011573-008-original-repeat/2024|H5N1|2024-04-15|cattle|B3.13
>A/CATTLE/Colorado/24-012346-005-original/2024|H5N1|2024-04-24|cattle|B3.13
>A/CATTLE/Colorado/24-012346-001-original/2024|H5N1|2024-04-24|cattle|B3.13
>A/CATTLE/Idaho/24-012341-021-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/Idaho/24-012341-020-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/Idaho/24-012341-018-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/Idaho/24-012341-014-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/Idaho/24-012341-013-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/Idaho/24-012341-010-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/Idaho/24-012341-004-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/Idaho/24-012341-001-original/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/MI/24-012314-003-original/2024|H5N1|2024-04-24|cattle|B3.13
>A/CATTLE/MI/24-012314-002-original/2024|H5N1|2024-04-24|cattle|B3.13
>A/TURKEY/MI/24-011958-001-original/2024|H5N1|2024-04-22|avian|B3.13
>A/DOMESTIC CAT/SD/24-011929-002-original/2024|H5N1|2024-04-19|feline|B3.13
>A/CATTLE/South Dakota/24-011802-001-original/2024|H5N1|2024-04-10|cattle|B3.13
>A/CATTLE/Idaho/24-011573-007/2024|H5N1|2024-04-15|cattle|B3.13
>A/CATTLE/Idaho/24-011573-004/2024|H5N1|2024-04-15|cattle|B3.13
>A/TURKEY/Minnesota/24-011426-001/2024|H5N1|2024-04-12|avian|B3.13
>A/CHICKEN/NM/24-011263-003/2024|H5N1|2024-04-15|avian|B3.13
>A/CHICKEN/NM/24-011263-002/2024|H5N1|2024-04-15|avian|B3.13
>A/CHICKEN/NM/24-011263-001/2024|H5N1|2024-04-15|avian|B3.13
>A/CATTLE/Michigan/24-010071-015/2024|H5N1|2024-04-01|cattle|B3.13
>A/CATTLE/MI/24-011231-004/2024|H5N1|2024-04-12|cattle|B3.13
>A/CATTLE/MI/24-011231-003/2024|H5N1|2024-04-12|cattle|B3.13
>A/CATTLE/MI/24-011231-002/2024|H5N1|2024-04-12|cattle|B3.13
>A/CATTLE/MI/24-011231-001/2024|H5N1|2024-04-12|cattle|B3.13
>A/DOMESTIC-CAT/New Mexico/24-010948-001/2024|H5N1|2024-04-09|feline|B3.13
>A/CHICKEN/NM/24-010947-003/2024|H5N1|2024-04-12|avian|B3.13
>A/CHICKEN/NM/24-010947-002/2024|H5N1|2024-04-12|avian|B3.13
>A/CHICKEN/NM/24-010947-001/2024|H5N1|2024-04-12|avian|B3.13
>A/CATTLE/MI/24-010930-002/2024|H5N1|2024-04-10|cattle|B3.13
>A/CHICKEN/NM/24-010832-002/2024|H5N1|2024-04-10|avian|B3.13
>A/CATTLE/MI/24-010786-002/2024|H5N1|2024-04-09|cattle|B3.13
>A/CATTLE/MI/24-010661-014/2024|H5N1|2024-04-08|cattle|B3.13
>A/CATTLE/MI/24-010661-013/2024|H5N1|2024-04-08|cattle|B3.13
>A/CATTLE/Michigan/24-010071-013/2024|H5N1|2024-04-01|cattle|B3.13
>A/CATTLE/Colorado/24-012225-029/2024|H5N1|2024-04-23|cattle|B3.13
>A/CATTLE/Michigan/24-010071-017/2024|H5N1|2024-04-01|cattle|B3.13
>A/CATTLE/Colorado/24-012225-019/2024|H5N1|2024-04-23|cattle|B3.13
>A/DOMESTIC-CAT/MI/24-011797-001/2024|H5N1|2024-04-19|feline|B3.13
>A/DOMESTIC-CAT/MI/24-011659-004/2024|H5N1|2024-04-18|feline|B3.13
>A/RACCOON/MI/24-011659-002/2024|H5N1|2024-04-18|other_mammal|B3.13
>A/RACCOON/MI/24-011659-001/2024|H5N1|2024-04-18|other_mammal|B3.13
>A/CATTLE/MI/24-010661-007/2024|H5N1|2024-04-08|cattle|B3.13
>A/CATTLE/MI/24-010661-003/2024|H5N1|2024-04-08|cattle|B3.13
>A/TURKEY/Minnesota/24-010655-003/2024|H5N1|2024-04-10|avian|B3.13
>A/TURKEY/Minnesota/24-010655-002/2024|H5N1|2024-04-10|avian|B3.13
>A/CATTLE/Michigan/24-010071-012/2024|H5N1|2024-04-01|cattle|B3.13
>A/TURKEY/Minnesota/24-010654-003/2024|H5N1|2024-04-09|avian|B3.13
>A/TURKEY/Minnesota/24-010654-001/2024|H5N1|2024-04-09|avian|B3.13
>A/CHICKEN/MI/24-010651-001/2024|H5N1|2024-04-09|avian|B3.13
>A/CATTLE/Michigan/24-010231-002/2024|H5N1|2024-04-03|cattle|B3.13
>A/CATTLE/Ohio/24-010202-014/2024|H5N1|2024-04-03|cattle|B3.13
>A/CATTLE/Ohio/24-010202-013/2024|H5N1|2024-03-30|cattle|B3.13
>A/Cattle/Texas/24-009810-001/2024|H5N1|2024-03-15|cattle|B3.13
>A/CATTLE/Ohio/24-010202-009/2024|H5N1|2024-03-30|cattle|B3.13
>A/CATTLE/Ohio/24-010202-005/2024|H5N1|2024-03-30|cattle|B3.13
>A/CATTLE/Ohio/24-010202-004/2024|H5N1|2024-04-03|cattle|B3.13
>A/CATTLE/Ohio/24-010202-002/2024|H5N1|2024-04-03|cattle|B3.13
>A/CATTLE/Ohio/24-010202-001/2024|H5N1|2024-03-30|cattle|B3.13
>A/DOMESTIC-CAT/Texas/24-009311-002/2024|H5N1|2024-03-19|feline|B3.13
>A/CATTLE/MI/24-013789-003/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/MI/24-013789-002/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/Idaho/24-014769-003/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/Idaho/24-014769-001/2024|H5N1|2024|cattle|B3.13
>A/CHICKEN/Minnesota/24-014761-001/2024|H5N1|2024|avian|B3.13
>A/TURKEY/Minnesota/24-014760-001/2024|H5N1|2024|avian|B3.13
>A/TURKEY/Minnesota/24-014759-002/2024|H5N1|2024|avian|B3.13
>A/TURKEY/Minnesota/24-014759-001/2024|H5N1|2024|avian|B3.13
>A/TURKEY/Minnesota/24-014687-003/2024|H5N1|2024|avian|B3.13
>A/TURKEY/Minnesota/24-014685-003/2024|H5N1|2024|avian|B3.13
>A/TURKEY/Minnesota/24-014685-002/2024|H5N1|2024|avian|B3.13
>A/CATTLE/SD/24-014510-007/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/SD/24-014510-003/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/ID/24-014336-012/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/ID/24-014336-010/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/ID/24-014336-008/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/ID/24-014336-007/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/ID/24-014336-006/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/ID/24-014336-004/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/ID/24-014336-002/2024|H5N1|2024|cattle|B3.13
>A/CHICKEN/MI/24-013788-002/2024|H5N1|2024|avian|B3.13
>A/ALPACA/Idaho/24-014328-007/2024|H5N1|2024|other_mammal|B3.13
>A/CATTLE/MI/24-014001-002/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/MI/24-014001-001/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/MI/24-013999-006/2024|H5N1|2024|cattle|B3.13
>A/TURKEY/MI/24-013788-001/2024|H5N1|2024|avian|B3.13
>A/CATTLE/MI/24-013999-005/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/MI/24-013999-001/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/MI/24-013789-011/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/MI/24-013789-010/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/MI/24-013789-007/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/MI/24-013789-006/2024|H5N1|2024|cattle|B3.13
>A/CHICKEN/Idaho/24-013706-002/2024|H5N1|2024-05-07|avian|B3.13
>A/CHICKEN/Idaho/24-013706-001/2024|H5N1|2024-05-07|avian|B3.13
>A/CATTLE/MI/24-013393-004/2024|H5N1|2024-04-24|cattle|B3.13
>A/GOOSE/Idaho/24-013169-003/2024|H5N1|2024-05-01|avian|B3.13
>A/CHICKEN/Idaho/24-013169-002/2024|H5N1|2024-05-01|avian|B3.13
>A/CHICKEN/Idaho/24-013169-001/2024|H5N1|2024-05-01|avian|B3.13
>A/CATTLE/ID/24-014338-006/2024|H5N1|2024-05-12|cattle|B3.13
>A/CATTLE/ID/24-014338-004/2024|H5N1|2024-05-12|cattle|B3.13
>A/CATTLE/ID/24-014338-003/2024|H5N1|2024-05-12|cattle|B3.13
>A/CATTLE/SD/24-015059-003/2024|H5N1|2024-05-21|cattle|B3.13
>A/CATTLE/SD/24-015059-002/2024|H5N1|2024-05-21|cattle|B3.13
>A/CATTLE/MI/24-015041-007/2024|H5N1|2024-05-17|cattle|B3.13
>A/CATTLE/MI/24-015041-004/2024|H5N1|2024-05-17|cattle|B3.13
>A/CATTLE/MI/24-015041-002/2024|H5N1|2024-05-17|cattle|B3.13
>A/FELINE/MI/24-015040-001/2024|H5N1|2024-05-17|feline|B3.13
>A/CHICKEN/Iowa/24-015328-001/2024|H5N1|2024-05-27|avian|B3.13
>A/CATTLE/Colorado/24-014901-008/2024|H5N1|2024-05-20|cattle|B3.13
>A/CATTLE/Colorado/24-014901-007/2024|H5N1|2024-05-20|cattle|B3.13
>A/CATTLE/MI/24-014883-003/2024|H5N1|2024-05-15|cattle|B3.13
>A/CATTLE/MI/24-014882-004/2024|H5N1|2024-05-16|cattle|B3.13
>A/CATTLE/MI/24-014881-013/2024|H5N1|2024-05-16|cattle|B3.13
>A/CATTLE/MI/24-014881-009/2024|H5N1|2024-05-16|cattle|B3.13
>A/CATTLE/ID/24-014338-009/2024|H5N1|2024-05-12|cattle|B3.13

## De-Duplication

In [2]:
# De-duplication 

# Gisaid 

gisaid = downloads + "GISAID_Complete_Fasta_Files/04-01-2025--04-14-2025_renamed/"

os.chdir(gisaid)

dfs_gisaid = create_dataframes(gisaid)

In [7]:
for key in dfs_gisaid.keys():
    dataframes = dfs_gisaid[key]
    print(dataframes)

[    isolate_partial                                        full_header  \
0                P-  >A/dairy_cow/Idaho/W241290019-18-P/2024|H5N1|2...
1                P-  >A/dairy_cow/Idaho/W241290019-19-P/2024|H5N1|2...
2      W241220059-8  >A/dairy_cow/Idaho/W241220059-8/2024|H5N1|2024...
3      W241220059-9  >A/dairy_cow/Idaho/W241220059-9/2024|H5N1|2024...
4     W240870066-26  >A/dairy_cow/Idaho/W240870066-26/2024|H5N1|202...
..              ...                                                ...
202      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
203      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
204      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
205      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
206      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
1    agtactacttcttgcaatagttagccttgttaaaagtgatcagatt...
2    atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
3    atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
4    atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
..                                                 ...
202  atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
203  atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
204  atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
205  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
206  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...

[207 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0                P-  >A/dairy_cow/Idaho/W241290019-18-P/2024|H5N1|2...
1                P-  >A/dairy_cow/Idaho/W241290019-19-P/2024|H5N1|2...
2      W241220059-8  >A/dairy_cow/Idaho/W241220059-8/2024|H5N1|2024...
3      W241220059-9  >A/dairy_cow/Idaho/W241220059-9/2024|H5N1|2024...
4     W240870066-26  >A/dairy_cow/Idaho/W240870066-26/2024|H5N1|202...
..              ...                                                ...
202      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
203      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
204      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
205      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
206      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
1    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
2    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
3    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
4    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
..                                                 ...
202  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
203  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
204  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
205  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
206  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...

[207 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0                P-  >A/dairy_cow/Idaho/W241290019-18-P/2024|H5N1|2...
1                P-  >A/dairy_cow/Idaho/W241290019-19-P/2024|H5N1|2...
2      W241220059-8  >A/dairy_cow/Idaho/W241220059-8/2024|H5N1|2024...
3      W241220059-9  >A/dairy_cow/Idaho/W241220059-9/2024|H5N1|2024...
4     W240870066-26  >A/dairy_cow/Idaho/W240870066-26/2024|H5N1|202...
..              ...                                                ...
202      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
203      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
204      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
205      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
206      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
1    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
2    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
3    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
4    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
..                                                 ...
202  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
203  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
204  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
205  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
206  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...

[207 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0                P-  >A/dairy_cow/Idaho/W241290019-18-P/2024|H5N1|2...
1                P-  >A/dairy_cow/Idaho/W241290019-19-P/2024|H5N1|2...
2      W241220059-8  >A/dairy_cow/Idaho/W241220059-8/2024|H5N1|2024...
3      W241220059-9  >A/dairy_cow/Idaho/W241220059-9/2024|H5N1|2024...
4     W240870066-26  >A/dairy_cow/Idaho/W240870066-26/2024|H5N1|202...
..              ...                                                ...
202      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
203      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
204      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
205      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
206      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
1    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
2    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
3    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
4    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
..                                                 ...
202  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
203  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
204  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
205  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
206  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...

[207 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0                P-  >A/dairy_cow/Idaho/W241290019-18-P/2024|H5N1|2...
1                P-  >A/dairy_cow/Idaho/W241290019-19-P/2024|H5N1|2...
2      W241220059-8  >A/dairy_cow/Idaho/W241220059-8/2024|H5N1|2024...
3      W241220059-9  >A/dairy_cow/Idaho/W241220059-9/2024|H5N1|2024...
4     W240870066-26  >A/dairy_cow/Idaho/W240870066-26/2024|H5N1|202...
..              ...                                                ...
202      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
203      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
204      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
205      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
206      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    atggattccaacactgtgttaagctttcaggtagactgctttcttt...
1    atggattccaacactgtgttaagctttcaggtagactgctttcttt...
2    atggattccaacactgtgttaagctttcaggtagactgctttcttt...
3    atggattccaacactgtgttaagctttcaggtagactgctttcttt...
4    atggattccaacactgtgttaagctttcaggtagactgctttcttt...
..                                                 ...
202  atggattccaacactgtgttaagctttcaggtagactgctttcttt...
203  atggattccaacactgtgttaagctttcaggtagactgctttcttt...
204  atggattccaacactgtgttaagctttcaggtagactgctttcttt...
205  atggattccaacactgtgttaagctttcaggtagactgctttcttt...
206  atggattccaacactgtgttaagctttcaggtagactgctttcttt...

[207 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0                P-  >A/dairy_cow/Idaho/W241290019-18-P/2024|H5N1|2...
1                P-  >A/dairy_cow/Idaho/W241290019-19-P/2024|H5N1|2...
2      W241220059-8  >A/dairy_cow/Idaho/W241220059-8/2024|H5N1|2024...
3      W241220059-9  >A/dairy_cow/Idaho/W241220059-9/2024|H5N1|2024...
4     W240870066-26  >A/dairy_cow/Idaho/W240870066-26/2024|H5N1|202...
..              ...                                                ...
202      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
203      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
204      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
205      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
206      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
1    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
2    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
3    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
4    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
..                                                 ...
202  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
203  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
204  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
205  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
206  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...

[207 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0                P-  >A/dairy_cow/Idaho/W241290019-18-P/2024|H5N1|2...
1                P-  >A/dairy_cow/Idaho/W241290019-19-P/2024|H5N1|2...
2      W241220059-8  >A/dairy_cow/Idaho/W241220059-8/2024|H5N1|2024...
3      W241220059-9  >A/dairy_cow/Idaho/W241220059-9/2024|H5N1|2024...
4     W240870066-26  >A/dairy_cow/Idaho/W240870066-26/2024|H5N1|202...
..              ...                                                ...
202      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
203      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
204      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
205      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
206      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
1    atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
2    atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
3    atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
4    atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
..                                                 ...
202  atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
203  atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
204  atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
205  atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
206  atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...

[207 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0                P-  >A/dairy_cow/Idaho/W241290019-18-P/2024|H5N1|2...
1                P-  >A/dairy_cow/Idaho/W241290019-19-P/2024|H5N1|2...
2      W241220059-8  >A/dairy_cow/Idaho/W241220059-8/2024|H5N1|2024...
3      W241220059-9  >A/dairy_cow/Idaho/W241220059-9/2024|H5N1|2024...
4     W240870066-26  >A/dairy_cow/Idaho/W240870066-26/2024|H5N1|202...
..              ...                                                ...
202      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
203      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
204      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
205      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
206      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
1    atggagagaataaaagaacggagagatctaatgtcacagtctcgca...
2    atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
3    atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
4    atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
..                                                 ...
202  atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
203  atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
204  atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
205  atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
206  atggagagaataaaagaactgagagatctaatgtcacagtctcgca...

[207 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0        009499-001  >A/quail/USA/009499-001/2025|H5N1|2025|avian|D...
1        005292-001  >A/turkey/USA/005292-001-R2/2025|H5N1|2025|avi...
2        005224-001  >A/chicken/USA/005224-001-R2/2025|H5N1|2025|av...
3        009378-003  >A/chicken/USA/009378-003/2025|H5N1|2025|avian...
4        009378-001  >A/chicken/USA/009378-001/2025|H5N1|2025|avian...
..              ...                                                ...
179      002644-003  >A/dairy_cow/USA/002644-003-v/2025|H5N1|2025|c...
180      010142-001  >A/dairy_cow/USA/010142-001/2025|H5N1|2025|cat...
181      007062-003  >A/canada_goose/USA/007062-003-R/2025|H5N1|202...
182      007116-001  >A/bald_eagle/USA/007116-001-R/2025|H5N1|2025|...
183      008325-001  >A/bald_eagle/USA/008325-001/2025|H5N1|2025|av...

                                              sequence
0    atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
1    atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
2    atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
3    atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
4    atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
..                                                 ...
179  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
180  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
181  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
182  atggaaaacatagtacttcttcttgcaatatttagccttgttaaaa...
183  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...

[184 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0        009499-001  >A/quail/USA/009499-001/2025|H5N1|2025|avian|D...
1        005292-001  >A/turkey/USA/005292-001-R2/2025|H5N1|2025|avi...
2        005224-001  >A/chicken/USA/005224-001-R2/2025|H5N1|2025|av...
3        009378-003  >A/chicken/USA/009378-003/2025|H5N1|2025|avian...
4        009378-001  >A/chicken/USA/009378-001/2025|H5N1|2025|avian...
..              ...                                                ...
179      002644-003  >A/dairy_cow/USA/002644-003-v/2025|H5N1|2025|c...
180      010142-001  >A/dairy_cow/USA/010142-001/2025|H5N1|2025|cat...
181      007062-003  >A/canada_goose/USA/007062-003-R/2025|H5N1|202...
182      007116-001  >A/bald_eagle/USA/007116-001-R/2025|H5N1|2025|...
183      008325-001  >A/bald_eagle/USA/008325-001/2025|H5N1|2025|av...

                                              sequence
0    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
1    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
2    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
3    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
4    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
..                                                 ...
179  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
180  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
181  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
182  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
183  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...

[184 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0        009499-001  >A/quail/USA/009499-001/2025|H5N1|2025|avian|D...
1        005292-001  >A/turkey/USA/005292-001-R2/2025|H5N1|2025|avi...
2        005224-001  >A/chicken/USA/005224-001-R2/2025|H5N1|2025|av...
3        009378-003  >A/chicken/USA/009378-003/2025|H5N1|2025|avian...
4        009378-001  >A/chicken/USA/009378-001/2025|H5N1|2025|avian...
..              ...                                                ...
179      002644-003  >A/dairy_cow/USA/002644-003-v/2025|H5N1|2025|c...
180      010142-001  >A/dairy_cow/USA/010142-001/2025|H5N1|2025|cat...
181      007062-003  >A/canada_goose/USA/007062-003-R/2025|H5N1|202...
182      007116-001  >A/bald_eagle/USA/007116-001-R/2025|H5N1|2025|...
183      008325-001  >A/bald_eagle/USA/008325-001/2025|H5N1|2025|av...

                                              sequence
0    atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
1    atgaattcaaatcaaaagataataactatcgggtcaatctgcatgg...
2    atgaatccaaatcaaaagatgataactatcgggtcaatctgcatgg...
3    atgaatccaaatcaaaagacaataatcatcgggtcaatctgcatgg...
4    atgaatccaaatcaaaagacaataatcatcgggtcaatctgcatgg...
..                                                 ...
179  atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
180  atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
181  atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
182  atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
183  atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...

[184 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0        009499-001  >A/quail/USA/009499-001/2025|H5N1|2025|avian|D...
1        005292-001  >A/turkey/USA/005292-001-R2/2025|H5N1|2025|avi...
2        005224-001  >A/chicken/USA/005224-001-R2/2025|H5N1|2025|av...
3        009378-003  >A/chicken/USA/009378-003/2025|H5N1|2025|avian...
4        009378-001  >A/chicken/USA/009378-001/2025|H5N1|2025|avian...
..              ...                                                ...
179      002644-003  >A/dairy_cow/USA/002644-003-v/2025|H5N1|2025|c...
180      010142-001  >A/dairy_cow/USA/010142-001/2025|H5N1|2025|cat...
181      007062-003  >A/canada_goose/USA/007062-003-R/2025|H5N1|202...
182      007116-001  >A/bald_eagle/USA/007116-001-R/2025|H5N1|2025|...
183      008325-001  >A/bald_eagle/USA/008325-001/2025|H5N1|2025|av...

                                              sequence
0    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
1    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
2    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
3    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
4    atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
..                                                 ...
179  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
180  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
181  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
182  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
183  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...

[184 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0        009499-001  >A/quail/USA/009499-001/2025|H5N1|2025|avian|D...
1        005292-001  >A/turkey/USA/005292-001-R2/2025|H5N1|2025|avi...
2        005224-001  >A/chicken/USA/005224-001-R2/2025|H5N1|2025|av...
3        009378-003  >A/chicken/USA/009378-003/2025|H5N1|2025|avian...
4        009378-001  >A/chicken/USA/009378-001/2025|H5N1|2025|avian...
..              ...                                                ...
179      002644-003  >A/dairy_cow/USA/002644-003-v/2025|H5N1|2025|c...
180      010142-001  >A/dairy_cow/USA/010142-001/2025|H5N1|2025|cat...
181      007062-003  >A/canada_goose/USA/007062-003-R/2025|H5N1|202...
182      007116-001  >A/bald_eagle/USA/007116-001-R/2025|H5N1|2025|...
183      008325-001  >A/bald_eagle/USA/008325-001/2025|H5N1|2025|av...

                                              sequence
0    atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
1    atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
2    atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
3    atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
4    atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
..                                                 ...
179  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
180  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
181  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
182  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...

In [3]:
# Do the same with Andersen 

dfs_andersen = create_dataframes(temp_files)

In [4]:
for key in dfs_andersen.keys():
    dataframes = dfs_andersen[key]
    print(dataframes)

[     isolate_partial                                        full_header  \
0         009108-004  >A/Cattle/Texas/24-009108-004-original/2024|H5...
1         009108-003  >A/Cattle/Texas/24-009108-003-original/2024|H5...
2         009108-002  >A/Cattle/Texas/24-009108-002-original/2024|H5...
3         009088-001  >A/Cattle/Texas/24-009088-001-original/2024|H5...
4         009029-001  >A/Cattle/Texas/24-009029-001-original/2024|H5...
...              ...                                                ...
2138      003807-010  >A/PET FOOD/CO/25-003807-010/2025|H5N1|2025|ot...
2139      003807-009  >A/PET FOOD/CO/25-003807-009/2025|H5N1|2025|ot...
2140      003807-008  >A/PET FOOD/CO/25-003807-008/2025|H5N1|2025|ot...
2141      003807-005  >A/PET FOOD/CO/25-003807-005/2025|H5N1|2025|ot...
2142      003807-003  >A/PET FOOD/CO/25-003807-003/2025|H5N1|2025|ot...

                                               sequence
0     ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
1     ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
2     ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
3     ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
4     ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
...                                                 ...
2138  ATGAAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
2139  ATGAAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
2140  ATGAAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
2141  ATGAAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
2142  ATGAAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...

[2143 rows x 3 columns]]
[     isolate_partial                                        full_header  \
0         009108-004  >A/Cattle/Texas/24-009108-004-original/2024|H5...
1         009108-003  >A/Cattle/Texas/24-009108-003-original/2024|H5...
2         009108-002  >A/Cattle/Texas/24-009108-002-original/2024|H5...
3         009088-001  >A/Cattle/Texas/24-009088-001-original/2024|H5...
4         009029-001  >A/Cattle/Texas/24-009029-001-original/2024|H5...
...              ...                                                ...
2138      003807-010  >A/PET FOOD/CO/25-003807-010/2025|H5N1|2025|ot...
2139      003807-009  >A/PET FOOD/CO/25-003807-009/2025|H5N1|2025|ot...
2140      003807-008  >A/PET FOOD/CO/25-003807-008/2025|H5N1|2025|ot...
2141      003807-005  >A/PET FOOD/CO/25-003807-005/2025|H5N1|2025|ot...
2142      003807-003  >A/PET FOOD/CO/25-003807-003/2025|H5N1|2025|ot...

                                               sequence
0     ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1     ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2     ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3     ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4     ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
...                                                 ...
2138  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2139  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2140  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2141  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2142  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...

[2143 rows x 3 columns]]
[     isolate_partial                                        full_header  \
0         009108-004  >A/Cattle/Texas/24-009108-004-original/2024|H5...
1         009108-003  >A/Cattle/Texas/24-009108-003-original/2024|H5...
2         009108-002  >A/Cattle/Texas/24-009108-002-original/2024|H5...
3         009088-001  >A/Cattle/Texas/24-009088-001-original/2024|H5...
4         009029-001  >A/Cattle/Texas/24-009029-001-original/2024|H5...
...              ...                                                ...
2138      003807-010  >A/PET FOOD/CO/25-003807-010/2025|H5N1|2025|ot...
2139      003807-009  >A/PET FOOD/CO/25-003807-009/2025|H5N1|2025|ot...
2140      003807-008  >A/PET FOOD/CO/25-003807-008/2025|H5N1|2025|ot...
2141      003807-005  >A/PET FOOD/CO/25-003807-005/2025|H5N1|2025|ot...
2142      003807-003  >A/PET FOOD/CO/25-003807-003/2025|H5N1|2025|ot...

                                               sequence
0     ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
1     ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
2     ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
3     ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
4     ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
...                                                 ...
2138  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
2139  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
2140  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
2141  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
2142  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...

[2143 rows x 3 columns]]
[     isolate_partial                                        full_header  \
0         009108-004  >A/Cattle/Texas/24-009108-004-original/2024|H5...
1         009108-003  >A/Cattle/Texas/24-009108-003-original/2024|H5...
2         009108-002  >A/Cattle/Texas/24-009108-002-original/2024|H5...
3         009088-001  >A/Cattle/Texas/24-009088-001-original/2024|H5...
4         009029-001  >A/Cattle/Texas/24-009029-001-original/2024|H5...
...              ...                                                ...
2138      003807-010  >A/PET FOOD/CO/25-003807-010/2025|H5N1|2025|ot...
2139      003807-009  >A/PET FOOD/CO/25-003807-009/2025|H5N1|2025|ot...
2140      003807-008  >A/PET FOOD/CO/25-003807-008/2025|H5N1|2025|ot...
2141      003807-005  >A/PET FOOD/CO/25-003807-005/2025|H5N1|2025|ot...
2142      003807-003  >A/PET FOOD/CO/25-003807-003/2025|H5N1|2025|ot...

                                               sequence
0     ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
1     ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
2     ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
3     ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
4     ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
...                                                 ...
2138  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
2139  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
2140  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
2141  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
2142  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...

[2143 rows x 3 columns]]
[     isolate_partial                                        full_header  \
0         009108-004  >A/Cattle/Texas/24-009108-004-original/2024|H5...
1         009108-003  >A/Cattle/Texas/24-009108-003-original/2024|H5...
2         009108-002  >A/Cattle/Texas/24-009108-002-original/2024|H5...
3         009088-001  >A/Cattle/Texas/24-009088-001-original/2024|H5...
4         009029-001  >A/Cattle/Texas/24-009029-001-original/2024|H5...
...              ...                                                ...
2138      003807-010  >A/PET FOOD/CO/25-003807-010/2025|H5N1|2025|ot...
2139      003807-009  >A/PET FOOD/CO/25-003807-009/2025|H5N1|2025|ot...
2140      003807-008  >A/PET FOOD/CO/25-003807-008/2025|H5N1|2025|ot...
2141      003807-005  >A/PET FOOD/CO/25-003807-005/2025|H5N1|2025|ot...
2142      003807-003  >A/PET FOOD/CO/25-003807-003/2025|H5N1|2025|ot...

                                               sequence
0     ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
1     ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
2     ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
3     ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
4     ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
...                                                 ...
2138  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
2139  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
2140  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
2141  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
2142  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...

[2143 rows x 3 columns]]
[     isolate_partial                                        full_header  \
0         009108-004  >A/Cattle/Texas/24-009108-004-original/2024|H5...
1         009108-003  >A/Cattle/Texas/24-009108-003-original/2024|H5...
2         009108-002  >A/Cattle/Texas/24-009108-002-original/2024|H5...
3         009088-001  >A/Cattle/Texas/24-009088-001-original/2024|H5...
4         009029-001  >A/Cattle/Texas/24-009029-001-original/2024|H5...
...              ...                                                ...
2138      003807-010  >A/PET FOOD/CO/25-003807-010/2025|H5N1|2025|ot...
2139      003807-009  >A/PET FOOD/CO/25-003807-009/2025|H5N1|2025|ot...
2140      003807-008  >A/PET FOOD/CO/25-003807-008/2025|H5N1|2025|ot...
2141      003807-005  >A/PET FOOD/CO/25-003807-005/2025|H5N1|2025|ot...
2142      003807-003  >A/PET FOOD/CO/25-003807-003/2025|H5N1|2025|ot...

                                               sequence
0     ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
1     ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
2     ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
3     ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
4     ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
...                                                 ...
2138  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
2139  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
2140  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
2141  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
2142  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...

[2143 rows x 3 columns]]
[     isolate_partial                                        full_header  \
0         009108-004  >A/Cattle/Texas/24-009108-004-original/2024|H5...
1         009108-003  >A/Cattle/Texas/24-009108-003-original/2024|H5...
2         009108-002  >A/Cattle/Texas/24-009108-002-original/2024|H5...
3         009088-001  >A/Cattle/Texas/24-009088-001-original/2024|H5...
4         009029-001  >A/Cattle/Texas/24-009029-001-original/2024|H5...
...              ...                                                ...
2138      003807-010  >A/PET FOOD/CO/25-003807-010/2025|H5N1|2025|ot...
2139      003807-009  >A/PET FOOD/CO/25-003807-009/2025|H5N1|2025|ot...
2140      003807-008  >A/PET FOOD/CO/25-003807-008/2025|H5N1|2025|ot...
2141      003807-005  >A/PET FOOD/CO/25-003807-005/2025|H5N1|2025|ot...
2142      003807-003  >A/PET FOOD/CO/25-003807-003/2025|H5N1|2025|ot...

                                               sequence
0     ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
1     ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
2     ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
3     ATGGATGTCAACCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
4     ATGGATGTCAATCCGACTTTACTCTTCTTGAAAGTTCCAGCGCAAA...
...                                                 ...
2138  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
2139  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
2140  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
2141  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
2142  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...

[2143 rows x 3 columns]]
[     isolate_partial                                        full_header  \
0         009108-004  >A/Cattle/Texas/24-009108-004-original/2024|H5...
1         009108-003  >A/Cattle/Texas/24-009108-003-original/2024|H5...
2         009108-002  >A/Cattle/Texas/24-009108-002-original/2024|H5...
3         009088-001  >A/Cattle/Texas/24-009088-001-original/2024|H5...
4         009029-001  >A/Cattle/Texas/24-009029-001-original/2024|H5...
...              ...                                                ...
2138      003807-010  >A/PET FOOD/CO/25-003807-010/2025|H5N1|2025|ot...
2139      003807-009  >A/PET FOOD/CO/25-003807-009/2025|H5N1|2025|ot...
2140      003807-008  >A/PET FOOD/CO/25-003807-008/2025|H5N1|2025|ot...
2141      003807-005  >A/PET FOOD/CO/25-003807-005/2025|H5N1|2025|ot...
2142      003807-003  >A/PET FOOD/CO/25-003807-003/2025|H5N1|2025|ot...

                                               sequence
0     ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
1     ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
2     ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
3     ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
4     ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
...                                                 ...
2138  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
2139  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
2140  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
2141  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
2142  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...

[2143 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0        009087-001  >A/Cattle/Texas/24-009087-001-original/2024|H5...
1        009027-010  >A/Cattle/Michigan/24-009027-010-original-repe...
2        008850-001  >A/Cat/Texas/24-008850-001-original/2024|H5N1|...
3        010071-008  >A/Cattle/Michigan/24-010071-008-original/2024...
4        009776-015  >A/Cattle/Texas/24-009776-015-original/2024|H5...
..              ...                                                ...
955      000616-007  >A/CANADA GOOSE/IL/25-000616-007/2025|H5N1|202...
956      000616-002  >A/CANADA GOOSE/IL/25-000616-002/2025|H5N1|202...
957      003807-019  >A/PET FOOD/CO/25-003807-019/2025|H5N1|2025|ot...
958      003807-013  >A/PET FOOD/CO/25-003807-013/2025|H5N1|2025|ot...
959      003807-001  >A/PET FOOD/CO/25-003807-001/2025|H5N1|2025|ot...

                                              sequence
0    ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
1    ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
2    ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
3    ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
4    ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
..                                                 ...
955  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
956  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
957  ATGAAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
958  ATGAAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
959  ATGAAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...

[960 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0        009087-001  >A/Cattle/Texas/24-009087-001-original/2024|H5...
1        009027-010  >A/Cattle/Michigan/24-009027-010-original-repe...
2        008850-001  >A/Cat/Texas/24-008850-001-original/2024|H5N1|...
3        010071-008  >A/Cattle/Michigan/24-010071-008-original/2024...
4        009776-015  >A/Cattle/Texas/24-009776-015-original/2024|H5...
..              ...                                                ...
955      000616-007  >A/CANADA GOOSE/IL/25-000616-007/2025|H5N1|202...
956      000616-002  >A/CANADA GOOSE/IL/25-000616-002/2025|H5N1|202...
957      003807-019  >A/PET FOOD/CO/25-003807-019/2025|H5N1|2025|ot...
958      003807-013  >A/PET FOOD/CO/25-003807-013/2025|H5N1|2025|ot...
959      003807-001  >A/PET FOOD/CO/25-003807-001/2025|H5N1|2025|ot...

                                              sequence
0    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
..                                                 ...
955  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
956  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
957  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
958  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
959  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...

[960 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0        009087-001  >A/Cattle/Texas/24-009087-001-original/2024|H5...
1        009027-010  >A/Cattle/Michigan/24-009027-010-original-repe...
2        008850-001  >A/Cat/Texas/24-008850-001-original/2024|H5N1|...
3        010071-008  >A/Cattle/Michigan/24-010071-008-original/2024...
4        009776-015  >A/Cattle/Texas/24-009776-015-original/2024|H5...
..              ...                                                ...
955      000616-007  >A/CANADA GOOSE/IL/25-000616-007/2025|H5N1|202...
956      000616-002  >A/CANADA GOOSE/IL/25-000616-002/2025|H5N1|202...
957      003807-019  >A/PET FOOD/CO/25-003807-019/2025|H5N1|2025|ot...
958      003807-013  >A/PET FOOD/CO/25-003807-013/2025|H5N1|2025|ot...
959      003807-001  >A/PET FOOD/CO/25-003807-001/2025|H5N1|2025|ot...

                                              sequence
0    ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
1    ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
2    ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
3    ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
4    ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
..                                                 ...
955  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
956  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
957  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
958  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
959  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...

[960 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0        009087-001  >A/Cattle/Texas/24-009087-001-original/2024|H5...
1        009027-010  >A/Cattle/Michigan/24-009027-010-original-repe...
2        008850-001  >A/Cat/Texas/24-008850-001-original/2024|H5N1|...
3        010071-008  >A/Cattle/Michigan/24-010071-008-original/2024...
4        009776-015  >A/Cattle/Texas/24-009776-015-original/2024|H5...
..              ...                                                ...
955      000616-007  >A/CANADA GOOSE/IL/25-000616-007/2025|H5N1|202...
956      000616-002  >A/CANADA GOOSE/IL/25-000616-002/2025|H5N1|202...
957      003807-019  >A/PET FOOD/CO/25-003807-019/2025|H5N1|2025|ot...
958      003807-013  >A/PET FOOD/CO/25-003807-013/2025|H5N1|2025|ot...
959      003807-001  >A/PET FOOD/CO/25-003807-001/2025|H5N1|2025|ot...

                                              sequence
0    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
1    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
2    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
3    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
4    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
..                                                 ...
955  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
956  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
957  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
958  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
959  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...

[960 rows x 3 columns]]
[    isolate_partial                                        full_header  \
0        009087-001  >A/Cattle/Texas/24-009087-001-original/2024|H5...
1        009027-010  >A/Cattle/Michigan/24-009027-010-original-repe...
2        008850-001  >A/Cat/Texas/24-008850-001-original/2024|H5N1|...
3        010071-008  >A/Cattle/Michigan/24-010071-008-original/2024...
4        009776-015  >A/Cattle/Texas/24-009776-015-original/2024|H5...
..              ...                                                ...
955      000616-007  >A/CANADA GOOSE/IL/25-000616-007/2025|H5N1|202...
956      000616-002  >A/CANADA GOOSE/IL/25-000616-002/2025|H5N1|202...
957      003807-019  >A/PET FOOD/CO/25-003807-019/2025|H5N1|2025|ot...
958      003807-013  >A/PET FOOD/CO/25-003807-013/2025|H5N1|2025|ot...
959      003807-001  >A/PET FOOD/CO/25-003807-001/2025|H5N1|2025|ot...

                                              sequence
0    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
1    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
2    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
3    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
4    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
..                                                 ...

In [ ]:
# Merge dataframes and drop duplicates

full_dfs = defaultdict(list)

# for key in dfs_andersen.keys():
#     dataframes = dfs_andersen[key]
#     for i, df in enumerate(dataframes):
#         print(i)
#         try:
#             full_df = df.merge(dfs_gisaid[key][i], how="outer")
#             # print(full_df)
#             full_df = full_df.drop_duplicates(subset=["isolate_partial"])
#             full_dfs[key].append(full_df)
#         except:
#             print("Failed to merge dataframes in ", key)

0
Failed to merge dataframes in  D1.1_PB2_andersen_04-21-2025

In [ ]:
# If none in one database, only use the other and drop duplicates

full_dfs = defaultdict(list)
for key in dfs_andersen.keys():
    print(key)
# for key in ["D1.3"]:
    dataframes = dfs_andersen[key]
    for i, df in enumerate(dataframes):
        print(i)
        try:
            # full_df = df.merge(dfs_gisaid[key][i], how="outer")
            # print(full_df)
            full_df = full_df.drop_duplicates(subset=["isolate_partial"])
            full_dfs[key].append(full_df)
        except:
            print("Failed to merge dataframes in ", key)

A1_HA_andersen_2025-04-14
0
Failed to merge dataframes in  A1_HA_andersen_2025-04-14
A1_MP_andersen_2025-04-14
0
Failed to merge dataframes in  A1_MP_andersen_2025-04-14
A1_NA_andersen_2025-04-14
0
Failed to merge dataframes in  A1_NA_andersen_2025-04-14
A1_NP_andersen_2025-04-14
0
Failed to merge dataframes in  A1_NP_andersen_2025-04-14
A1_NS_andersen_2025-04-14
0
Failed to merge dataframes in  A1_NS_andersen_2025-04-14
A1_PA_andersen_2025-04-14
0
Failed to merge dataframes in  A1_PA_andersen_2025-04-14
A1_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  A1_PB1_andersen_2025-04-14
A1_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  A1_PB2_andersen_2025-04-14
A2_HA_andersen_2025-04-14
0
Failed to merge dataframes in  A2_HA_andersen_2025-04-14
A2_MP_andersen_2025-04-14
0
Failed to merge dataframes in  A2_MP_andersen_2025-04-14
A2_NA_andersen_2025-04-14
0
Failed to merge dataframes in  A2_NA_andersen_2025-04-14
A2_NP_andersen_2025-04-14
0
Failed to merge dataframes in  A2_NP_andersen_2025-04-14
A2_NS_andersen_2025-04-14
0
Failed to merge dataframes in  A2_NS_andersen_2025-04-14
A2_PA_andersen_2025-04-14
0
Failed to merge dataframes in  A2_PA_andersen_2025-04-14
A2_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  A2_PB1_andersen_2025-04-14
A2_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  A2_PB2_andersen_2025-04-14
A3_HA_andersen_2025-04-14
0
Failed to merge dataframes in  A3_HA_andersen_2025-04-14
A3_MP_andersen_2025-04-14
0
Failed to merge dataframes in  A3_MP_andersen_2025-04-14
A3_NA_andersen_2025-04-14
0
Failed to merge dataframes in  A3_NA_andersen_2025-04-14
A3_NP_andersen_2025-04-14
0
Failed to merge dataframes in  A3_NP_andersen_2025-04-14
A3_NS_andersen_2025-04-14
0
Failed to merge dataframes in  A3_NS_andersen_2025-04-14
A3_PA_andersen_2025-04-14
0
Failed to merge dataframes in  A3_PA_andersen_2025-04-14
A3_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  A3_PB1_andersen_2025-04-14
A3_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  A3_PB2_andersen_2025-04-14
A4_HA_andersen_2025-04-14
0
Failed to merge dataframes in  A4_HA_andersen_2025-04-14
A4_MP_andersen_2025-04-14
0
Failed to merge dataframes in  A4_MP_andersen_2025-04-14
A4_NA_andersen_2025-04-14
0
Failed to merge dataframes in  A4_NA_andersen_2025-04-14
A4_NP_andersen_2025-04-14
0
Failed to merge dataframes in  A4_NP_andersen_2025-04-14
A4_NS_andersen_2025-04-14
0
Failed to merge dataframes in  A4_NS_andersen_2025-04-14
A4_PA_andersen_2025-04-14
0
Failed to merge dataframes in  A4_PA_andersen_2025-04-14
A4_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  A4_PB1_andersen_2025-04-14
A4_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  A4_PB2_andersen_2025-04-14
A5_HA_andersen_2025-04-14
0
Failed to merge dataframes in  A5_HA_andersen_2025-04-14
A5_MP_andersen_2025-04-14
0
Failed to merge dataframes in  A5_MP_andersen_2025-04-14
A5_NA_andersen_2025-04-14
0
Failed to merge dataframes in  A5_NA_andersen_2025-04-14
A5_NP_andersen_2025-04-14
0
Failed to merge dataframes in  A5_NP_andersen_2025-04-14
A5_NS_andersen_2025-04-14
0
Failed to merge dataframes in  A5_NS_andersen_2025-04-14
A5_PA_andersen_2025-04-14
0
Failed to merge dataframes in  A5_PA_andersen_2025-04-14
A5_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  A5_PB1_andersen_2025-04-14
A5_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  A5_PB2_andersen_2025-04-14
A6_HA_andersen_2025-04-14
0
Failed to merge dataframes in  A6_HA_andersen_2025-04-14
A6_MP_andersen_2025-04-14
0
Failed to merge dataframes in  A6_MP_andersen_2025-04-14
A6_NA_andersen_2025-04-14
0
Failed to merge dataframes in  A6_NA_andersen_2025-04-14
A6_NP_andersen_2025-04-14
0
Failed to merge dataframes in  A6_NP_andersen_2025-04-14
A6_NS_andersen_2025-04-14
0
Failed to merge dataframes in  A6_NS_andersen_2025-04-14
A6_PA_andersen_2025-04-14
0
Failed to merge dataframes in  A6_PA_andersen_2025-04-14
A6_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  A6_PB1_andersen_2025-04-14
A6_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  A6_PB2_andersen_2025-04-14
B1.1_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B1.1_HA_andersen_2025-04-14
B1.1_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B1.1_MP_andersen_2025-04-14
B1.1_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B1.1_NA_andersen_2025-04-14
B1.1_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B1.1_NP_andersen_2025-04-14
B1.1_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B1.1_NS_andersen_2025-04-14
B1.1_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B1.1_PA_andersen_2025-04-14
B1.1_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B1.1_PB1_andersen_2025-04-14
B1.1_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B1.1_PB2_andersen_2025-04-14
B1.2_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B1.2_HA_andersen_2025-04-14
B1.2_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B1.2_MP_andersen_2025-04-14
B1.2_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B1.2_NA_andersen_2025-04-14
B1.2_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B1.2_NP_andersen_2025-04-14
B1.2_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B1.2_NS_andersen_2025-04-14
B1.2_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B1.2_PA_andersen_2025-04-14
B1.2_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B1.2_PB1_andersen_2025-04-14
B1.2_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B1.2_PB2_andersen_2025-04-14
B1.3_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B1.3_HA_andersen_2025-04-14
B1.3_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B1.3_MP_andersen_2025-04-14
B1.3_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B1.3_NA_andersen_2025-04-14
B1.3_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B1.3_NP_andersen_2025-04-14
B1.3_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B1.3_NS_andersen_2025-04-14
B1.3_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B1.3_PA_andersen_2025-04-14
B1.3_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B1.3_PB1_andersen_2025-04-14
B1.3_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B1.3_PB2_andersen_2025-04-14
B2.1_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B2.1_HA_andersen_2025-04-14
B2.1_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B2.1_MP_andersen_2025-04-14
B2.1_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B2.1_NA_andersen_2025-04-14
B2.1_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B2.1_NP_andersen_2025-04-14
B2.1_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B2.1_NS_andersen_2025-04-14
B2.1_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B2.1_PA_andersen_2025-04-14
B2.1_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B2.1_PB1_andersen_2025-04-14
B2.1_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B2.1_PB2_andersen_2025-04-14
B2.2_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B2.2_HA_andersen_2025-04-14
B2.2_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B2.2_MP_andersen_2025-04-14
B2.2_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B2.2_NA_andersen_2025-04-14
B2.2_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B2.2_NP_andersen_2025-04-14
B2.2_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B2.2_NS_andersen_2025-04-14
B2.2_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B2.2_PA_andersen_2025-04-14
B2.2_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B2.2_PB1_andersen_2025-04-14
B2.2_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B2.2_PB2_andersen_2025-04-14
B3.10_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.10_HA_andersen_2025-04-14
B3.10_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.10_MP_andersen_2025-04-14
B3.10_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.10_NA_andersen_2025-04-14
B3.10_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.10_NP_andersen_2025-04-14
B3.10_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B3.10_NS_andersen_2025-04-14
B3.10_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.10_PA_andersen_2025-04-14
B3.10_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B3.10_PB1_andersen_2025-04-14
B3.10_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B3.10_PB2_andersen_2025-04-14
B3.11_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.11_HA_andersen_2025-04-14
B3.11_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.11_MP_andersen_2025-04-14
B3.11_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.11_NA_andersen_2025-04-14
B3.11_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.11_NP_andersen_2025-04-14
B3.11_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B3.11_NS_andersen_2025-04-14
B3.11_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.11_PA_andersen_2025-04-14
B3.11_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B3.11_PB1_andersen_2025-04-14
B3.11_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B3.11_PB2_andersen_2025-04-14
B3.12_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.12_HA_andersen_2025-04-14
B3.12_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.12_MP_andersen_2025-04-14
B3.12_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.12_NA_andersen_2025-04-14
B3.12_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.12_NP_andersen_2025-04-14
B3.12_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B3.12_NS_andersen_2025-04-14
B3.12_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.12_PA_andersen_2025-04-14
B3.12_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B3.12_PB1_andersen_2025-04-14
B3.12_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B3.12_PB2_andersen_2025-04-14
B3.13_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.13_HA_andersen_2025-04-14
B3.13_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.13_MP_andersen_2025-04-14
B3.13_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.13_NA_andersen_2025-04-14
B3.13_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.13_NP_andersen_2025-04-14
B3.13_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B3.13_NS_andersen_2025-04-14
B3.13_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.13_PA_andersen_2025-04-14
B3.13_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B3.13_PB1_andersen_2025-04-14
B3.13_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B3.13_PB2_andersen_2025-04-14
B3.1_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.1_HA_andersen_2025-04-14
B3.1_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.1_MP_andersen_2025-04-14
B3.1_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.1_NA_andersen_2025-04-14
B3.1_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.1_NP_andersen_2025-04-14
B3.1_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B3.1_NS_andersen_2025-04-14
B3.1_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.1_PA_andersen_2025-04-14
B3.1_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B3.1_PB1_andersen_2025-04-14
B3.1_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B3.1_PB2_andersen_2025-04-14
B3.2_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.2_HA_andersen_2025-04-14
B3.2_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.2_MP_andersen_2025-04-14
B3.2_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.2_NA_andersen_2025-04-14
B3.2_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.2_NP_andersen_2025-04-14
B3.2_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B3.2_NS_andersen_2025-04-14
B3.2_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.2_PA_andersen_2025-04-14
B3.2_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B3.2_PB1_andersen_2025-04-14
B3.2_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B3.2_PB2_andersen_2025-04-14
B3.3_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.3_HA_andersen_2025-04-14
B3.3_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.3_MP_andersen_2025-04-14
B3.3_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.3_NA_andersen_2025-04-14
B3.3_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.3_NP_andersen_2025-04-14
B3.3_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B3.3_NS_andersen_2025-04-14
B3.3_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.3_PA_andersen_2025-04-14
B3.3_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B3.3_PB1_andersen_2025-04-14
B3.3_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B3.3_PB2_andersen_2025-04-14
B3.4_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.4_HA_andersen_2025-04-14
B3.4_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.4_MP_andersen_2025-04-14
B3.4_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.4_NA_andersen_2025-04-14
B3.4_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.4_NP_andersen_2025-04-14
B3.4_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B3.4_NS_andersen_2025-04-14
B3.4_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.4_PA_andersen_2025-04-14
B3.4_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B3.4_PB1_andersen_2025-04-14
B3.4_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B3.4_PB2_andersen_2025-04-14
B3.5_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.5_HA_andersen_2025-04-14
B3.5_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.5_MP_andersen_2025-04-14
B3.5_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.5_NA_andersen_2025-04-14
B3.5_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.5_NP_andersen_2025-04-14
B3.5_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B3.5_NS_andersen_2025-04-14
B3.5_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.5_PA_andersen_2025-04-14
B3.5_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B3.5_PB1_andersen_2025-04-14
B3.5_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B3.5_PB2_andersen_2025-04-14
B3.6_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.6_HA_andersen_2025-04-14
B3.6_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.6_MP_andersen_2025-04-14
B3.6_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.6_NA_andersen_2025-04-14
B3.6_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.6_NP_andersen_2025-04-14
B3.6_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B3.6_NS_andersen_2025-04-14
B3.6_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.6_PA_andersen_2025-04-14
B3.6_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B3.6_PB1_andersen_2025-04-14
B3.6_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B3.6_PB2_andersen_2025-04-14
B3.7_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.7_HA_andersen_2025-04-14
B3.7_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.7_MP_andersen_2025-04-14
B3.7_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.7_NA_andersen_2025-04-14
B3.7_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.7_NP_andersen_2025-04-14
B3.7_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B3.7_NS_andersen_2025-04-14
B3.7_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.7_PA_andersen_2025-04-14
B3.7_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B3.7_PB1_andersen_2025-04-14
B3.7_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B3.7_PB2_andersen_2025-04-14
B3.8_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.8_HA_andersen_2025-04-14
B3.8_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.8_MP_andersen_2025-04-14
B3.8_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.8_NA_andersen_2025-04-14
B3.8_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.8_NP_andersen_2025-04-14
B3.8_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B3.8_NS_andersen_2025-04-14
B3.8_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.8_PA_andersen_2025-04-14
B3.8_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B3.8_PB1_andersen_2025-04-14
B3.8_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B3.8_PB2_andersen_2025-04-14
B3.9_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.9_HA_andersen_2025-04-14
B3.9_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.9_MP_andersen_2025-04-14
B3.9_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.9_NA_andersen_2025-04-14
B3.9_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B3.9_NP_andersen_2025-04-14
B3.9_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B3.9_NS_andersen_2025-04-14
B3.9_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B3.9_PA_andersen_2025-04-14
B3.9_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B3.9_PB1_andersen_2025-04-14
B3.9_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B3.9_PB2_andersen_2025-04-14
B4.1_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B4.1_HA_andersen_2025-04-14
B4.1_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B4.1_MP_andersen_2025-04-14
B4.1_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B4.1_NA_andersen_2025-04-14
B4.1_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B4.1_NP_andersen_2025-04-14
B4.1_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B4.1_NS_andersen_2025-04-14
B4.1_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B4.1_PA_andersen_2025-04-14
B4.1_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B4.1_PB1_andersen_2025-04-14
B4.1_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B4.1_PB2_andersen_2025-04-14
B5.1_HA_andersen_2025-04-14
0
Failed to merge dataframes in  B5.1_HA_andersen_2025-04-14
B5.1_MP_andersen_2025-04-14
0
Failed to merge dataframes in  B5.1_MP_andersen_2025-04-14
B5.1_NA_andersen_2025-04-14
0
Failed to merge dataframes in  B5.1_NA_andersen_2025-04-14
B5.1_NP_andersen_2025-04-14
0
Failed to merge dataframes in  B5.1_NP_andersen_2025-04-14
B5.1_NS_andersen_2025-04-14
0
Failed to merge dataframes in  B5.1_NS_andersen_2025-04-14
B5.1_PA_andersen_2025-04-14
0
Failed to merge dataframes in  B5.1_PA_andersen_2025-04-14
B5.1_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  B5.1_PB1_andersen_2025-04-14
B5.1_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  B5.1_PB2_andersen_2025-04-14
C1.1_HA_andersen_2025-04-14
0
Failed to merge dataframes in  C1.1_HA_andersen_2025-04-14
C1.1_MP_andersen_2025-04-14
0
Failed to merge dataframes in  C1.1_MP_andersen_2025-04-14
C1.1_NA_andersen_2025-04-14
0
Failed to merge dataframes in  C1.1_NA_andersen_2025-04-14
C1.1_NP_andersen_2025-04-14
0
Failed to merge dataframes in  C1.1_NP_andersen_2025-04-14
C1.1_NS_andersen_2025-04-14
0
Failed to merge dataframes in  C1.1_NS_andersen_2025-04-14
C1.1_PA_andersen_2025-04-14
0
Failed to merge dataframes in  C1.1_PA_andersen_2025-04-14
C1.1_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  C1.1_PB1_andersen_2025-04-14
C1.1_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  C1.1_PB2_andersen_2025-04-14
C2.1_HA_andersen_2025-04-14
0
Failed to merge dataframes in  C2.1_HA_andersen_2025-04-14
C2.1_MP_andersen_2025-04-14
0
Failed to merge dataframes in  C2.1_MP_andersen_2025-04-14
C2.1_NA_andersen_2025-04-14
0
Failed to merge dataframes in  C2.1_NA_andersen_2025-04-14
C2.1_NP_andersen_2025-04-14
0
Failed to merge dataframes in  C2.1_NP_andersen_2025-04-14
C2.1_NS_andersen_2025-04-14
0
Failed to merge dataframes in  C2.1_NS_andersen_2025-04-14
C2.1_PA_andersen_2025-04-14
0
Failed to merge dataframes in  C2.1_PA_andersen_2025-04-14
C2.1_PB1_andersen_2025-04-14
0
Failed to merge dataframes in  C2.1_PB1_andersen_2025-04-14
C2.1_PB2_andersen_2025-04-14
0
Failed to merge dataframes in  C2.1_PB2_andersen_2025-04-14
C3.1_HA_andersen_2025-04-14
0

## Create FASTA files combining Andersen and GISAID

In [ ]:
# # Create fasta files 

# os.chdir(complete_files)
# for pair in full_dfs.keys():
#     output_path = complete_files + pair + "_combined_" + update_date + ".fasta" 

#     output_file = open(output_path, "w")
#     for item in full_dfs[pair]:
#         # for item in item:
#         # item = fasta_files[pair]
#         for index, row in item.iterrows():
#             name = item.loc[index, "full_header"]
#             sequence = item.loc[index, "sequence"]
#         # print(name)
#         # First is header, second is sequence
#         # print(value)
#             output_file.write(name)
#             output_file.write(sequence)
#     output_file.close()

In [ ]:
# os.chdir(complete_files)

# segment_files = []
# for dirpath, dirs, files in os.walk(temp_files): # + "01-01-2024--03-31-2025_renamed/"):
#     for segment in ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]:
#         base = []
#         for file in files:
#             file_name = os.path.join(dirpath, file)
#             # print(file_name)
#             if segment in file_name:
#                 with open(file_name) as f:
#                     lines = f.readlines()
#                     for line in lines:
#                         base.append(line)
#                 f.close()
#         os.chdir(complete_files)
#         output_path = complete_files + segment + "_andersen_" + update_date + ".fasta" # Genotype and Segment should all be the same
#         output_file = open(output_path, "w")
#         for b in base:
#             output_file.write(b)
#         output_file.close()