# Cleaning Downloaded Data from avian-flu

Author: Alexander Maksiaev

Purpose: Clean downloaded data from avian-flu, rename sequences according to convention, de-duplicate from GISAID

In [1]:
# Housekeeping

import os
import glob 
import pandas as pd
import xml.etree.ElementTree as ET
import requests
import time
import numpy as np
import dateutil 
from datetime import datetime
from collections import defaultdict 
import importlib
import utils  
importlib.reload(utils)
from utils import * 

# Make sure you have the correct paths

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu"
# downloads = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
originals = downloads + "Andersen_Downloads/"
temp_files = downloads + "Andersen_Temp_Files/"
complete_files = downloads + "Andersen_Complete_Files/"

# Day we're updating data
update_date = "04-14-2025"

os.chdir(downloads)

## Read Metadata

In [2]:
# Read metadata

metadata_folder = originals + "avian-influenza/metadata/"
os.chdir(metadata_folder)

metadata = pd.read_csv("SraRunTable_automated.csv")

# print(len(metadata)) # 7397 rows

# Get rid of missing dates; they won't be counted anyway
for date in metadata["Collection_Date"]:
    if "/" in date or date == "missing":
        metadata = metadata[metadata["Collection_Date"] != date]

# # Find only >= 2024 to start
# metadata["Collection_Date_Compare"] = metadata["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
# metadata = metadata[metadata["Collection_Date_Compare"] >= datetime(2021, 11, 1).strftime("%Y-%m-%d")] # Note that those with only years will default to today

# Find only >= last date using Release Date from metadata 
metadata["ReleaseDate"] = metadata["ReleaseDate"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
metadata = metadata[metadata["ReleaseDate"] >= datetime(2021, 11, 1).strftime("%Y-%m-%d")]
# Find only <= update date using Release Date from metadata
metadata = metadata[metadata["ReleaseDate"] <= datetime(2025, 4, 14).strftime("%Y-%m-%d")]

print(len(metadata)) # 6053 rows between 1/1/2024 and 4/14/2025

8576

In [3]:
# Get list of genotypes

os.chdir(home)

genotypes_df = pd.read_excel("genotype_key.xlsx")

genotypes = list(genotypes_df["Genotype"])

print(genotypes)

['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'B1.1', 'B1.2', 'B1.3', 'B2.1', 'B2.2', 'B3.1', 'B3.2', 'B3.3', 'B3.4', 'B3.5', 'B3.6', 'B4.1', 'B5.1', 'Minor01', 'Minor04', 'Minor07', 'Minor08', 'Minor09', 'Minor10', 'Minor11', 'Minor12', 'Minor13', 'Minor14', 'Minor15', 'Minor16', 'Minor17', 'Minor18', 'Minor19', 'Minor24', 'Minor25', 'Minor26', 'Minor27', 'Minor28', 'Minor29', 'Minor30', 'Minor31', 'Minor32', 'Minor33', 'Minor34', 'Minor35', 'Minor36', 'Minor37', 'Minor38', 'Minor39', 'Minor40', 'Minor41', 'Minor42', 'Minor43', 'Minor44', 'Minor45', 'Minor46', 'Minor47', 'Minor48', 'B3.7', 'Minor50', 'Minor51', 'C1.1', 'Minor52', 'Minor53', 'B3.11', 'Minor55', 'Minor56', 'Minor57', 'Minor58', 'B3.10', 'C2.1', 'Minor60', 'Minor61', 'B3.8', 'Minor62', 'Minor63', 'B3.12', 'Minor65', 'Minor66', 'Minor67', 'B3.9', 'Minor70', 'Minor71', 'B3.13', 'Minor73', 'Minor74', 'Minor75', 'Minor76', 'Minor77', 'Minor78', 'Minor79', 'Minor80', 'Minor81', 'Minor82', 'Minor83', 'Minor84', 'C3.1', 'Minor86', 'Minor87', 'Minor89', 'Minor90', 'Minor91', 'Minor92', 'Minor93', 'Minor94', 'D1.1', 'D1.2', 'D2.1', 'Minor95', 'D1.3', 'Minor98', 'Minor99', 'Minor100', 'Minor101', 'Minor97', 'Minor102', 'Minor103', 'Minor104', 'Minor105', 'Minor106']

### Naming convention ###
>A/[host]/[geo_loc_name]/[isolate]/[year]|[serotype: H5N1]|[collection_date]|[host_type]|[genotype]

host_type is from manual animal reference

In metadata, we have: host, geo_loc_name, isolate, year

We need: geo_loc_name, collection_date, host_type, genotype

host = Host

geo_loc_name (primary) = geo_loc_name

geo_loc_name (secondary) = genbank_mapping.tsv > genbank_name

isolate = isolate

collection date (primary) = Collection_Date

collection date (secondary) = https://www.ncbi.nlm.nih.gov/genbank/ > BioSample (input: BioSample) > Nucleotide > [first result] > collection_date

serotype = serotype

host type = [from ref] 

genotype = [from genoflu] -- use genoflu_results.tsv

## Get genotype, specific geolocation

In [4]:
# Get genotype from genoflu_results.tsv

os.chdir(metadata_folder)

genoflu_results = pd.read_csv("genoflu_results.tsv", delimiter="\t")

metadata["Genotype"] = genoflu_results["Genotype"]
metadata = metadata[~metadata["Genotype"].str.contains('Not assigned')] # Do not include non-assigned genotypes

# Get only the genotypes we want: B3.13 and D1.1

# b313_and_d11_only = genoflu_results[(genoflu_results["Genotype"] == "B3.13") | (genoflu_results["Genotype"] == "D1.1")]
# b313_and_d11_only = b313_and_d11_only.rename(columns={"sample": "Run"})
# b313_and_d11_only = b313_and_d11_only.drop_duplicates(subset="Run", keep="last")

# metadata = metadata.merge(b313_and_d11_only, on=["Run", "Genotype"], how="inner")

print(len(metadata)) 

display(metadata)

8163

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,create_date,version,Sample Name,SRA Study,serotype,isolation_source,BioSample Accession,is_retracted,retraction_detection_date_utc,Genotype
1,SRR28752447,WGS,241.29,86080323,PRJNA1102327,SAMN41019237,Viral,28164109,USDA-NVSL,2024,...,2024-04-20T18:12:00Z,1,24-009108-005-original,SRP503016,H5N1,NaN,SRS21079811,False,NaN,D1.3
2,SRR28752448,WGS,250.30,75035343,PRJNA1102327,SAMN41019236,Viral,24547283,USDA-NVSL,2024,...,2024-04-20T18:12:00Z,1,24-009108-004-original,SRP503016,H5N1,NaN,SRS21079810,False,NaN,B3.13
3,SRR28752449,WGS,146.61,59363690,PRJNA1102327,SAMN41019235,Viral,19686302,USDA-NVSL,2024,...,2024-04-20T18:12:00Z,1,24-009108-003-original,SRP503016,H5N1,NaN,SRS21079809,False,NaN,B3.13
4,SRR28752450,WGS,251.31,119232569,PRJNA1102327,SAMN41019234,Viral,38846827,USDA-NVSL,2024,...,2024-04-20T18:12:00Z,1,24-009108-002-original,SRP503016,H5N1,NaN,SRS21079808,False,NaN,B3.13
7,SRR28752453,WGS,144.71,37055919,PRJNA1102327,SAMN41019231,Viral,12938409,USDA-NVSL,2024,...,2024-04-20T18:12:00Z,1,24-009088-001-original,SRP503016,H5N1,NaN,SRS21079806,False,NaN,B3.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8671,SRR33124635,WGS,256.70,71164848,PRJNA1102327,SAMN47941268,Viral,24819306,USDA-NVSL,2025,...,2025-04-14 15:20:53,1,25-006248-005,SRP503016,NaN,"MILK, BULK TANK",SRS24711952,False,NaN,D1.1
8672,SRR33124636,WGS,238.91,29071970,PRJNA1102327,SAMN47941267,Viral,10215386,USDA-NVSL,2025,...,2025-04-14 15:20:58,1,25-006248-004,SRP503016,NaN,"MILK, BULK TANK",SRS24711951,False,NaN,D1.1
8673,SRR33124637,WGS,251.06,97654207,PRJNA1102327,SAMN47941266,Viral,34439987,USDA-NVSL,2025,...,2025-04-14 15:21:25,1,25-006248-002,SRP503016,NaN,"MILK, BULK TANK",SRS24711950,False,NaN,D1.1
8674,SRR33124638,WGS,251.54,56712279,PRJNA1102327,SAMN47941265,Viral,20010970,USDA-NVSL,2025,...,2025-04-14 15:20:40,1,25-006243-006,SRP503016,NaN,"MILK, BULK TANK",SRS24711949,False,NaN,D1.1
8675,SRR33124639,WGS,241.04,104552916,PRJNA1102327,SAMN47941256,Viral,36724241,USDA-NVSL,2025,...,2025-04-14 15:21:06,1,25-006020-002,SRP503016,NaN,"MILK, BULK TANK",SRS24711948,False,NaN,D1.1

In [5]:
# Get specific geolocation from genbank_mapping.tsv

genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
genbank_mapping["Run"] = genbank_mapping["sra_run"]
genbank_mapping = genbank_mapping.drop_duplicates(subset="Run", keep="first") # Drop duplicates
genbank_mapping["name_state"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[2]) # Get the name of the state

print(genbank_mapping)

metadata_genbank = metadata.merge(genbank_mapping, on=["Run"]) # Only include data that has states

print(genbank_mapping["name_state"])
print(len(metadata_genbank))
display(metadata_genbank) # Maybe there is no state information since 3/18/2025?

                    seg_file  \
0      SRR28752446_HA_cns.fa
8      SRR28752447_HA_cns.fa
16     SRR28752448_HA_cns.fa
24     SRR28752449_HA_cns.fa
32     SRR28752450_HA_cns.fa
...                      ...
38678  SRR32654211_HA_cns.fa
38686  SRR32654212_HA_cns.fa
38694  SRR32654213_HA_cns.fa
38702  SRR32654214_HA_cns.fa
38710  SRR32654216_HA_cns.fa

                                            seg_seq_name      sra_run seg  \
0      Consensus_SRR28752446_HA_cns_threshold_0.5_qua...  SRR28752446  HA
8      Consensus_SRR28752447_HA_cns_threshold_0.5_qua...  SRR28752447  HA
16     Consensus_SRR28752448_HA_cns_threshold_0.5_qua...  SRR28752448  HA
24     Consensus_SRR28752449_HA_cns_threshold_0.5_qua...  SRR28752449  HA
32     Consensus_SRR28752450_HA_cns_threshold_0.5_qua...  SRR28752450  HA
...                                                  ...          ...  ..
38678  Consensus_SRR32654211_HA_cns_threshold_0.5_qua...  SRR32654211  HA
38686  Consensus_SRR32654212_HA_cns_threshold_0.5_qua...  SRR32654212  HA
38694  Consensus_SRR32654213_HA_cns_threshold_0.5_qua...  SRR32654213  HA
38702  Consensus_SRR32654214_HA_cns_threshold_0.5_qua...  SRR32654214  HA
38710  Consensus_SRR32654216_HA_cns_threshold_0.5_qua...  SRR32654216  HA

      genbank_acc  genbank_seg                              genbank_name  \
0      PP740722.1            4      A/blackbird/Texas/24-008354-001/2024
8      PP752829.1            4         A/cattle/Texas/24-009108-005/2024
16     PP752821.1            4         A/cattle/Texas/24-009108-004/2024
24     PP752813.1            4         A/cattle/Texas/24-009108-003/2024
32     PP752805.1            4         A/cattle/Texas/24-009108-002/2024
...           ...          ...                                       ...
38678  PV338372.1            4   A/Turkey/OH/25-003389-002-original/2025
38686  PV339220.1            4  A/chicken/OH/25-003389-001-original/2025
38694  PV338364.1            4   A/Turkey/OH/25-003388-002-original/2025
38702  PV338092.1            4   A/Turkey/OH/25-002649-002-original/2025
38710  PV338484.1            4      A/cat/MT/24-006142-001-original/2023

               Run name_state
0      SRR28752446      Texas
8      SRR28752447      Texas
16     SRR28752448      Texas
24     SRR28752449      Texas
32     SRR28752450      Texas
...            ...        ...
38678  SRR32654211         OH
38686  SRR32654212         OH
38694  SRR32654213         OH
38702  SRR32654214         OH
38710  SRR32654216         MT

[4279 rows x 9 columns]
0        Texas
8        Texas
16       Texas
24       Texas
32       Texas
         ...
38678       OH
38686       OH
38694       OH
38702       OH
38710       MT
Name: name_state, Length: 4279, dtype: object
4064

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,retraction_detection_date_utc,Genotype,seg_file,seg_seq_name,sra_run,seg,genbank_acc,genbank_seg,genbank_name,name_state
0,SRR28752447,WGS,241.29,86080323,PRJNA1102327,SAMN41019237,Viral,28164109,USDA-NVSL,2024,...,NaN,D1.3,SRR28752447_HA_cns.fa,Consensus_SRR28752447_HA_cns_threshold_0.5_qua...,SRR28752447,HA,PP752829.1,4,A/cattle/Texas/24-009108-005/2024,Texas
1,SRR28752448,WGS,250.30,75035343,PRJNA1102327,SAMN41019236,Viral,24547283,USDA-NVSL,2024,...,NaN,B3.13,SRR28752448_HA_cns.fa,Consensus_SRR28752448_HA_cns_threshold_0.5_qua...,SRR28752448,HA,PP752821.1,4,A/cattle/Texas/24-009108-004/2024,Texas
2,SRR28752449,WGS,146.61,59363690,PRJNA1102327,SAMN41019235,Viral,19686302,USDA-NVSL,2024,...,NaN,B3.13,SRR28752449_HA_cns.fa,Consensus_SRR28752449_HA_cns_threshold_0.5_qua...,SRR28752449,HA,PP752813.1,4,A/cattle/Texas/24-009108-003/2024,Texas
3,SRR28752450,WGS,251.31,119232569,PRJNA1102327,SAMN41019234,Viral,38846827,USDA-NVSL,2024,...,NaN,B3.13,SRR28752450_HA_cns.fa,Consensus_SRR28752450_HA_cns_threshold_0.5_qua...,SRR28752450,HA,PP752805.1,4,A/cattle/Texas/24-009108-002/2024,Texas
4,SRR28752453,WGS,144.71,37055919,PRJNA1102327,SAMN41019231,Viral,12938409,USDA-NVSL,2024,...,NaN,B3.13,SRR28752453_HA_cns.fa,Consensus_SRR28752453_HA_cns_threshold_0.5_qua...,SRR28752453,HA,PP752677.1,4,A/cattle/Texas/24-009088-001/2024,Texas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4059,SRR32633088,WGS,145.11,67016467,PRJNA1102327,SAMN47290851,Viral,25388495,USDA-NVSL,2025,...,NaN,B3.13,SRR32633088_HA_cns.fa,Consensus_SRR32633088_HA_cns_threshold_0.5_qua...,SRR32633088,HA,PV456280.1,4,A/cat/OR/25-005913-003-original/2025,OR
4060,SRR32633089,WGS,148.14,140023511,PRJNA1102327,SAMN47290850,Viral,52157519,USDA-NVSL,2025,...,NaN,B3.13,SRR32633089_HA_cns.fa,Consensus_SRR32633089_HA_cns_threshold_0.5_qua...,SRR32633089,HA,PV456272.1,4,A/cat/OR/25-005800-002-original/2025,OR
4061,SRR32633090,WGS,148.49,83727737,PRJNA1102327,SAMN47290849,Viral,31619233,USDA-NVSL,2025,...,NaN,D1.3,SRR32633090_HA_cns.fa,Consensus_SRR32633090_HA_cns_threshold_0.5_qua...,SRR32633090,HA,PV456264.1,4,A/cat/OR/25-005800-001-original/2025,OR
4062,SRR32633093,WGS,148.10,105910536,PRJNA1102327,SAMN47290846,Viral,39757708,USDA-NVSL,2025,...,NaN,B3.2,SRR32633093_HA_cns.fa,Consensus_SRR32633093_HA_cns_threshold_0.5_qua...,SRR32633093,HA,PV457240.1,4,A/cattle/CA/25-005677-001-original/2025,CA
4063,SRR32633094,WGS,148.09,109655942,PRJNA1102327,SAMN47290845,Viral,41506380,USDA-NVSL,2025,...,NaN,B2.1,SRR32633094_HA_cns.fa,Consensus_SRR32633094_HA_cns_threshold_0.5_qua...,SRR32633094,HA,PV457232.1,4,A/cattle/CA/25-005648-001-original/2025,CA

In [6]:
# # If no states

# metadata_genbank = metadata

# metadata_genbank["name_state"] = "USA"

## Get and save collection date

In [ ]:

# # Get all dates
# metadata_genbank["Collection_Date_Specific"] = metadata_genbank["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank))

# # Save this so we don't have to do it again

# os.chdir(temp_files)
# metadata_genbank.to_csv("metadata_genbank.csv")

SAMN41019237
SAMN41019236
SAMN41019235
SAMN41019234
SAMN41019231
SAMN41019230
SAMN41019229
SAMN41019228
SAMN41019183
SAMN41019227
SAMN41019226
SAMN41019225
SAMN41019224
SAMN41019222
SAMN41019221
SAMN41019220
SAMN41019219
SAMN41019218
SAMN41019182
SAMN41019217
SAMN41019215
SAMN41019213
SAMN41019212
SAMN41019209
SAMN41019366
SAMN41019365
SAMN41019364
SAMN41019363
SAMN41019362
SAMN41019361
SAMN41019359
SAMN41019358
SAMN41019196
SAMN41019357
SAMN41019355
SAMN41019354
SAMN41019353
SAMN41019352
SAMN41019351
SAMN41019350
SAMN41019349
SAMN41019348
SAMN41019195
SAMN41019347
SAMN41019346
SAMN41019345
SAMN41019344
SAMN41019343
SAMN41019342
SAMN41019341
SAMN41019340
SAMN41019339
SAMN41019338
SAMN41019277
SAMN41019274
SAMN41019273
SAMN41019272
SAMN41019271
SAMN41019270
SAMN41019269
SAMN41019268
SAMN41019187
SAMN41019208
SAMN41019181
Unable to find collection date.
SAMN41019207
SAMN41019206
SAMN41019205
SAMN41019204
SAMN41019202
SAMN41019416
SAMN41019415
SAMN41019414
SAMN41019413
SAMN41019412
SAMN41019411
SAMN41019410
SAMN41019409
SAMN41019408
SAMN41019201
SAMN41019407
SAMN41019406
SAMN41019405
SAMN41019404
SAMN41019403
SAMN41019402
SAMN41019401
SAMN41019400
SAMN41019399
SAMN41019398
SAMN41019397
SAMN41019396
SAMN41019395
SAMN41019337
SAMN41019335
SAMN41019334
SAMN41019333
SAMN41019332
SAMN41019331
SAMN41019330
SAMN41019329
SAMN41019328
SAMN41019193
SAMN41019327
SAMN41019326
SAMN41019325
SAMN41019324
SAMN41019323
SAMN41019322
SAMN41019321
SAMN41019320
SAMN41019319
SAMN41019318
SAMN41019317
SAMN41019316
SAMN41019315
SAMN41019314
SAMN41019313
SAMN41019312
SAMN41019311
SAMN41019310
SAMN41019309
SAMN41019308
SAMN41019267
SAMN41019266
SAMN41019265
SAMN41019264
SAMN41019263
SAMN41019262
SAMN41019261
SAMN41019260
SAMN41019259
SAMN41019258
SAMN41019186
SAMN41019257
SAMN41019255
SAMN41019254
SAMN41019253
SAMN41019252
SAMN41019251
SAMN41019250
SAMN41019249
SAMN41019248
SAMN41019185
SAMN41019247
SAMN41019246
SAMN41019245
SAMN41019244
SAMN41019243
SAMN41019242
SAMN41019241
SAMN41019240
SAMN41019239
SAMN41019238
SAMN41019394
SAMN41019392
SAMN41019391
SAMN41019390
SAMN41019389
SAMN41019388
SAMN41019199
SAMN41019387
SAMN41019386
SAMN41019385
SAMN41019384
SAMN41019383
SAMN41019382
SAMN41019381
SAMN41019380
SAMN41019379
SAMN41019378
SAMN41019198
SAMN41019180
SAMN41019377
SAMN41019376
SAMN41019375
SAMN41019374
SAMN41019373
SAMN41019371
SAMN41019370
SAMN41019369
SAMN41019368
SAMN41019367
SAMN41019191
SAMN41019307
SAMN41019306
SAMN41019305
SAMN41019304
SAMN41019303
SAMN41019302
SAMN41019301
SAMN41019300
SAMN41019299
SAMN41019298
SAMN41019190
SAMN41019297
SAMN41019296
SAMN41019294
SAMN41019293
SAMN41019292
SAMN41019291
SAMN41019290
SAMN41019289
SAMN41019288
SAMN41019189
SAMN41019287
SAMN41019286
SAMN41019285
SAMN41019284
SAMN41019283
SAMN41019282
SAMN41019281
SAMN41019280
SAMN41019279
SAMN41019278
SAMN41019188
SAMN41019179
SAMN41019178
SAMN41100355
SAMN41100354
SAMN41100353
SAMN41100352
SAMN41100350
SAMN41106764
SAMN41106835
SAMN41106763
SAMN41106834
Unable to find collection date.
SAMN41106833
Unable to find collection date.
SAMN41106832
Unable to find collection date.
SAMN41106831
Unable to find collection date.
SAMN41106830
Unable to find collection date.
SAMN41106829
Unable to find collection date.
SAMN41106828
Unable to find collection date.
SAMN41106827
Unable to find collection date.
SAMN41106826
Unable to find collection date.
SAMN41106825
Unable to find collection date.
SAMN41106795
SAMN41106759
SAMN41106794
SAMN41106793
SAMN41106792
SAMN41106791
SAMN41106790
SAMN41106789
SAMN41106788
SAMN41106787
SAMN41106785
SAMN41106758
SAMN41106784
SAMN41106783
Unable to find collection date.
SAMN41106782
SAMN41106781
SAMN41106780
Unable to find collection date.
SAMN41106779
SAMN41106778
SAMN41106776
SAMN41106775
SAMN41106757
SAMN41106773
SAMN41106772
SAMN41106771
SAMN41106770
SAMN41106769
SAMN41106767
SAMN41106762
SAMN41106824
SAMN41106823
SAMN41106822
SAMN41106821
SAMN41106820
Unable to find collection date.
SAMN41106819
Unable to find collection date.
SAMN41106818
SAMN41106817
SAMN41106816
SAMN41106815
Unable to find collection date.
SAMN41106761
SAMN41106814
SAMN41106813
SAMN41106812
SAMN41106811
SAMN41106810
SAMN41106809
SAMN41106808
Unable to find collection date.
SAMN41106807
SAMN41106806
SAMN41106805
SAMN41106760
SAMN41106804
SAMN41106803
SAMN41106802
SAMN41106801
SAMN41106800
SAMN41106799
SAMN41106798
SAMN41106797
SAMN41106796
SAMN41106756
SAMN41106755
Unable to find collection date.
SAMN41390792
SAMN41390791
SAMN41390790
SAMN41390788
SAMN41390787
SAMN41390786
SAMN41390812
SAMN41390811
SAMN41390810
SAMN41390809
SAMN41390808
SAMN41390807
SAMN41390806
SAMN41390805
SAMN41390804
SAMN41390785
SAMN41390802
SAMN41390801
SAMN41390800
SAMN41390799
SAMN41390798
SAMN41390797
SAMN41390796
SAMN41390795
SAMN41390794
SAMN41390793
SAMN41390784
SAMN41390783
SAMN41267476
SAMN41267486
SAMN41267485
SAMN41267484
SAMN41267496
SAMN41267475
SAMN41267474
SAMN41267473
SAMN41267472
SAMN41267483
SAMN41267471
SAMN41267470
SAMN41267469
SAMN41267468
SAMN41267467
SAMN41267466
SAMN41267465
SAMN41267482
SAMN41267461
SAMN41267460
SAMN41267459
SAMN41267458
SAMN41267457
SAMN41267456
SAMN41267455
SAMN41267454
SAMN41267452
SAMN41267487
SAMN41267451
SAMN41267450
SAMN41267449
SAMN41267448
SAMN41267447
SAMN41267446
SAMN41267445
SAMN41267444
SAMN41267443
SAMN41267481
SAMN41267441
SAMN41267494
SAMN41267493
SAMN41267491
SAMN41267490
SAMN41267489
SAMN41267478
SAMN41267477
SAMN41267479
SAMN41267488
Unable to find collection date.
SAMN41189790
SAMN41189789
SAMN41189796
SAMN41189779
Unable to find collection date.
SAMN41189778
SAMN41189777
SAMN41189776
SAMN41189742
SAMN41189775
Unable to find collection date.
SAMN41189774
SAMN41189773
SAMN41189772
SAMN41189771
SAMN41189770
SAMN41189768
SAMN41189767
SAMN41189765
SAMN41189741
SAMN41189764
Unable to find collection date.
SAMN41189763
SAMN41189762
SAMN41189738
SAMN41189737
Unable to find collection date.
SAMN41189736
SAMN41189735
SAMN41189788
SAMN41189787
SAMN41189786
SAMN41189740
SAMN41189785
SAMN41189784
SAMN41189745
SAMN41189807
SAMN41189806
SAMN41189744
SAMN41189805
SAMN41189804
SAMN41189803
SAMN41189802
SAMN41189801
SAMN41189800
SAMN41189798
SAMN41189797
SAMN41189793
SAMN41189743
Unable to find collection date.
SAMN41189794
SAMN41189792
SAMN41189791
SAMN41189783
SAMN41189782
SAMN41189781
SAMN41189734
SAMN41189733
SAMN41189732
SAMN41189731
SAMN41189730
SAMN41189739
SAMN41189729
SAMN41189728
SAMN41189727
SAMN41189726
SAMN41189769
SAMN41189759
SAMN41189758
SAMN41189757
SAMN41189756
SAMN41189760
SAMN41189755
SAMN41189754
SAMN41189753
SAMN41189752
SAMN41189751
SAMN41189750
SAMN41189749
SAMN41189748
SAMN41189747
SAMN41189746
SAMN41189761
SAMN41189795
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
SAMN41489086
SAMN41489085
SAMN41489084
SAMN41489083
SAMN41489081
SAMN41489080
Unable to find collection date.
SAMN41489079
SAMN41489095
Unable to find collection date.
SAMN41489094
Unable to find collection date.
SAMN41489093
Unable to find collection date.
SAMN41489091
Unable to find collection date.
SAMN41489090
Unable to find collection date.
SAMN41489089
Unable to find collection date.
SAMN41489088
Unable to find collection date.
SAMN41489087
Unable to find collection date.
SAMN41489078
SAMN41489077
SAMN41656648
SAMN41656647
SAMN41656646
SAMN41656645
SAMN41656644
SAMN41656684
SAMN41656683
SAMN41656682
SAMN41656680
SAMN41656679
SAMN41656678
SAMN41656677
SAMN41656676
SAMN41656675
SAMN41656674
SAMN41656673
SAMN41656672
SAMN41656671
SAMN41656670
SAMN41656669
SAMN41656668
SAMN41656667
SAMN41656666
SAMN41656665
SAMN41656664
SAMN41656663
SAMN41656662
SAMN41656661
SAMN41656660
SAMN41656659
SAMN41656658
SAMN41656657
SAMN41656656
SAMN41656655
SAMN41656654
SAMN41656653
SAMN41656652
SAMN41656651
SAMN41656650
SAMN41656649
SAMN41656639
SAMN41805887
SAMN41805886
SAMN41805885
SAMN41805884
SAMN41805883
SAMN41805882
SAMN41805881
SAMN41805880
SAMN41805798
SAMN41805879
SAMN41805878
SAMN41805877
SAMN41805876
SAMN41805875
SAMN41805874
SAMN41805873
SAMN41805872
SAMN41805871
SAMN41805870
SAMN41805797
SAMN41805869
SAMN41805868
SAMN41805867
SAMN41805865
SAMN41805864
SAMN41805863
SAMN41805862
SAMN41805861
SAMN41805860
SAMN41805796
SAMN41805859
SAMN41805858
SAMN41805857
SAMN41805855
SAMN41805854
SAMN41805853
SAMN41805852
SAMN41805851
SAMN41805850
SAMN41805795
SAMN41805849
SAMN41805848
SAMN41805847
SAMN41805846
SAMN41805845
SAMN41805844
SAMN41805843
SAMN41805842
SAMN41805841
SAMN41805840
SAMN41805794
SAMN41805838
SAMN41805837
SAMN41805836
SAMN41805835
SAMN41805832
SAMN41805831
SAMN41805830
SAMN41805829
SAMN41805793
SAMN41805828
SAMN41805827
SAMN41805826
SAMN41805825
SAMN41805824
SAMN41805823
SAMN41805822
SAMN41805821
SAMN41805820
SAMN41805819
SAMN41805792
SAMN41805818
SAMN41805817
SAMN41805816
SAMN41805815
SAMN41805814
SAMN41805813
SAMN41805812
SAMN41805811
SAMN41805810
SAMN41805809
SAMN41805791
SAMN41805808
SAMN41805807
SAMN41805805
SAMN41805804
SAMN41805803
SAMN41805802
SAMN41805801
SAMN41805800
SAMN41805799
SAMN41805790
SAMN41892128
SAMN41892127
SAMN41892193
SAMN41892192
SAMN41892191
SAMN41892189
SAMN41892126
SAMN41892188
SAMN41892187
SAMN41892186
SAMN41892185
SAMN41892184
SAMN41892183
SAMN41892182
SAMN41892181
SAMN41892180
SAMN41892179
SAMN41892178
SAMN41892177
SAMN41892176
SAMN41892175
SAMN41892174
SAMN41892172
SAMN41892171
SAMN41892170
SAMN41892169
SAMN41892124
SAMN41892168
SAMN41892167
SAMN41892166
SAMN41892165
SAMN41892164
SAMN41892163
SAMN41892162
SAMN41892161
SAMN41892160
SAMN41892159
SAMN41892123
SAMN41892158
SAMN41892156
SAMN41892155
SAMN41892154
SAMN41892153
SAMN41892152
SAMN41892151
SAMN41892150
SAMN41892149
SAMN41892122
SAMN41892148
SAMN41892146
SAMN41892145
SAMN41892144
SAMN41892143
SAMN41892140
SAMN41892139
SAMN41892121
SAMN41892138
SAMN41892137
SAMN41892136
SAMN41892135
SAMN41892134
SAMN41892133
SAMN41892132
SAMN41892131
SAMN41892130
SAMN41892129
SAMN41892120
SAMN41892119
SAMN41805958
SAMN41805957
SAMN41805956
SAMN41805955
SAMN42027875
SAMN42027873
SAMN42027872
SAMN42027871
SAMN42027870
SAMN42027869
SAMN42027868
SAMN42027866
SAMN42027785
SAMN42027865
SAMN42027864
SAMN42027863
SAMN42027862
SAMN42027861
SAMN42027860
SAMN42027859
SAMN42027858
SAMN42027857
SAMN42027856
SAMN42027784
SAMN42027855
SAMN42027854
SAMN42027853
SAMN42027852
SAMN42027851
SAMN42027850
SAMN42027849
SAMN42027848
SAMN42027847
SAMN42027846
SAMN42027783
SAMN42027845
SAMN42027844
SAMN42027843
SAMN42027842
SAMN42027841
SAMN42027840
SAMN42027839
SAMN42027838
SAMN42027837
SAMN42027782
SAMN42027835
SAMN42027834
SAMN42027833
SAMN42027832
SAMN42027831
SAMN42027830
SAMN42027829
SAMN42027828
SAMN42027827
SAMN42027826
SAMN42027781
SAMN42027825
SAMN42027824
SAMN42027823
SAMN42027822
SAMN42027821
SAMN42027820
SAMN42027819
SAMN42027818
SAMN42027817
SAMN42027816
SAMN42027780
SAMN42027815
SAMN42027814
SAMN42027812
SAMN42027811
SAMN42027810
SAMN42027809
SAMN42027808
SAMN42027807
SAMN42027806
SAMN42027779
SAMN42027805
SAMN42027804
SAMN42027803
SAMN42027802
SAMN42027801
SAMN42027800
SAMN42027799
SAMN42027798
SAMN42027797
SAMN42027778
SAMN42027795
SAMN42027794
SAMN42027793
SAMN42027792
SAMN42027791
SAMN42027790
SAMN42027789
SAMN42027788
SAMN42027787
SAMN42027877
SAMN42027876
SAMN42027786
SAMN42027777
SAMN42027776
SAMN42278923
SAMN42278994
SAMN42278993
SAMN42278992
SAMN42278991
SAMN42278990
SAMN42278989
SAMN42278988
SAMN42278987
SAMN42278986
SAMN42278985
SAMN42278922
SAMN42278984
SAMN42278983
SAMN42278982
SAMN42278981
SAMN42278977
SAMN42278976
SAMN42278975
SAMN42278921
SAMN42278974
SAMN42278973
SAMN42278972
SAMN42278971
SAMN42278970
SAMN42278969
SAMN42278967
SAMN42278966
SAMN42278965
SAMN42278920
SAMN42278957
SAMN42278956
SAMN42278955
SAMN42278919
SAMN42278954
SAMN42278953
SAMN42278952
SAMN42278951
SAMN42278950
SAMN42278949
SAMN42278948
SAMN42278947
SAMN42278946
SAMN42278945
SAMN42278944
SAMN42278942
SAMN42278941
SAMN42278940
SAMN42278939
SAMN42278938
SAMN42278937
SAMN42279013
SAMN42279012
SAMN42279011
SAMN42279010
SAMN42279009
SAMN42279008
SAMN42279007
SAMN42279006
SAMN42279005
SAMN42278924
SAMN42279004
SAMN42279002
SAMN42279000
SAMN42278999
SAMN42278998
SAMN42278997
SAMN42278996
SAMN42278995
SAMN42278936
SAMN42278935
SAMN42278917
SAMN42278934
SAMN42278933
SAMN42278932
SAMN42278931
SAMN42278930
SAMN42278929
SAMN42278928
SAMN42278927
SAMN42279031
SAMN42279030
SAMN42279029
SAMN42279028
SAMN42279026
SAMN42279025
SAMN42278926
SAMN42279024
SAMN42279023
SAMN42279022
SAMN42279021
SAMN42279020
SAMN42279019
SAMN42279018
SAMN42279016
SAMN42278925
SAMN42278916
SAMN42278915
SAMN42361170
SAMN42361232
SAMN42361231
SAMN42361230
SAMN42361229
SAMN42361228
SAMN42361227
SAMN42361226
SAMN42361225
SAMN42361224
SAMN42361223
SAMN42361169
SAMN42361222
SAMN42361221
SAMN42361220
SAMN42361219
SAMN42361218
SAMN42361217
SAMN42361216
SAMN42361215
SAMN42361214
SAMN42361213
SAMN42361212
SAMN42361211
SAMN42361208
SAMN42361207
SAMN42361206
SAMN42361205
SAMN42361204
SAMN42361172
SAMN42361171
SAMN42361242
SAMN42361241
SAMN42361240
SAMN42361239
SAMN42361238
SAMN42361237
SAMN42361236
SAMN42361235
SAMN42361233
SAMN42361203
SAMN42361167
SAMN42361202
SAMN42361201
SAMN42361200
SAMN42361199
SAMN42361198
SAMN42361197
SAMN42361196
SAMN42361195
SAMN42361194
SAMN42361193
SAMN42361166
SAMN42361192
SAMN42361190
SAMN42361189
SAMN42361188
SAMN42361187
SAMN42361186
SAMN42361185
SAMN42361184
SAMN42361183
SAMN42361165
SAMN42361182
SAMN42361181
SAMN42361180
SAMN42361179
SAMN42361178
SAMN42361177
SAMN42361176
SAMN42361175
SAMN42361173
SAMN42361164
SAMN42535327
SAMN42535326
SAMN42535325
SAMN42535324
SAMN42535323
SAMN42535322
SAMN42535321
SAMN42535341
SAMN42535340
SAMN42535339
SAMN42535338
SAMN42535320
SAMN42535337
SAMN42535336
SAMN42535335
SAMN42535334
SAMN42535333
SAMN42535329
SAMN42535328
SAMN42535319
SAMN42535318
SAMN42535348
SAMN42535347
SAMN42535346
SAMN42762588
SAMN42762662
SAMN42762661
SAMN42762660
SAMN42762659
SAMN42762587
SAMN42762658
SAMN42762657
SAMN42762656
SAMN42762655
SAMN42762654
SAMN42762653
SAMN42762652
SAMN42762651
SAMN42762586
SAMN42762648
SAMN42762647
SAMN42762646
SAMN42762645
SAMN42762644
SAMN42762643
SAMN42762642
SAMN42762641
SAMN42762640
SAMN42762639
SAMN42762585
SAMN42762630
SAMN42762629
SAMN42762584
SAMN42762628
SAMN42762627
SAMN42762626
SAMN42762625
SAMN42762624
SAMN42762622
SAMN42762621
SAMN42762620
SAMN42762619
SAMN42762583
SAMN42762618
SAMN42762617
SAMN42762616
SAMN42762615
SAMN42762614
SAMN42762613
SAMN42762612
SAMN42762611
SAMN42762610
SAMN42762609
SAMN42762582
SAMN42762608
SAMN42762607
SAMN42762606
SAMN42762605
SAMN42762604
SAMN42762603
SAMN42762602
SAMN42762601
SAMN42762600
SAMN42762599
SAMN42762581
SAMN42762598
SAMN42762597
SAMN42762596
SAMN42762595
SAMN42762594
SAMN42762593
SAMN42762592
SAMN42762591
SAMN42762589
SAMN42762579
SAMN42944632
SAMN42944631
SAMN42944630
SAMN42944688
SAMN42944687
SAMN42944686
SAMN42944685
SAMN42944684
SAMN42944683
SAMN42944682
SAMN42944681
SAMN42944680
SAMN42944677
SAMN42944676
SAMN42944628
SAMN42944675
SAMN42944674
SAMN42944679
SAMN42944678
SAMN42944672
SAMN42944671
SAMN42944659
SAMN42944669
SAMN42944668
SAMN42944648
SAMN42944658
SAMN42944667
SAMN42944657
SAMN42944656
SAMN42944666
SAMN42944655
SAMN42944654
SAMN42944665
SAMN42944653
SAMN42944652
SAMN42944661
SAMN42944651
SAMN42944663
SAMN42944662
SAMN42944647
SAMN42944646
SAMN42944645
SAMN42944644
SAMN42944643
SAMN42944660
SAMN42944642
SAMN42944641
SAMN42944640
SAMN42944639
SAMN42944638
SAMN42944637
SAMN42944636
SAMN42944635
SAMN42944634
SAMN42944633
SAMN42944650
SAMN43033063
SAMN43033062
SAMN43033061
SAMN43033060
SAMN43033059
SAMN43033058
SAMN43033084
SAMN43033057
SAMN43033083
SAMN43033082
SAMN43033081
SAMN43033080
SAMN43033079
SAMN43033078
SAMN43033077
SAMN43033076
SAMN43033075
SAMN43033074
SAMN43033056
SAMN43033073
SAMN43033072
SAMN43033071
SAMN43033070
SAMN43033069
SAMN43033068
SAMN43033067
SAMN43033066
SAMN43033065
SAMN43033064
SAMN43033055
SAMN43033054
SAMN43033085
SAMN43168344
SAMN43168345
SAMN43168346
SAMN43168349
SAMN43168351
SAMN43168356
SAMN43168332
SAMN43168331
SAMN43168330
SAMN43168329
SAMN43168328
SAMN43168327
SAMN43168358
SAMN43168357
SAMN43168353
SAMN43168326
SAMN43168352
SAMN43168348
SAMN43168347
SAMN43168343
SAMN43168325
SAMN43168342
SAMN43168340
SAMN43168339
SAMN43168338
SAMN43168337
SAMN43168336
SAMN43168335
SAMN43168334
SAMN43168333
SAMN43168324
SAMN43168323
SAMN43274409
Unable to find collection date.
SAMN43274408
Unable to find collection date.
SAMN43274407
Unable to find collection date.
SAMN43274466
Unable to find collection date.
SAMN43274465
Unable to find collection date.
SAMN43274464
Unable to find collection date.
SAMN43274462
Unable to find collection date.
SAMN43274461
Unable to find collection date.
SAMN43274460
Unable to find collection date.
SAMN43274406
Unable to find collection date.
SAMN43274459
Unable to find collection date.
SAMN43274458
Unable to find collection date.
SAMN43274457
Unable to find collection date.
SAMN43274456
Unable to find collection date.
SAMN43274455
Unable to find collection date.
SAMN43274454
Unable to find collection date.
SAMN43274453
Unable to find collection date.
SAMN43274452
Unable to find collection date.
SAMN43274451
Unable to find collection date.
SAMN43274450
Unable to find collection date.
SAMN43274405
Unable to find collection date.
SAMN43274449
Unable to find collection date.
SAMN43274448
Unable to find collection date.
SAMN43274447
Unable to find collection date.
SAMN43274446
Unable to find collection date.
SAMN43274445
Unable to find collection date.
SAMN43274444
Unable to find collection date.
SAMN43274443
Unable to find collection date.
SAMN43274442
Unable to find collection date.
SAMN43274441
Unable to find collection date.
SAMN43274440
Unable to find collection date.
SAMN43274404
Unable to find collection date.
SAMN43274439
Unable to find collection date.
SAMN43274438
Unable to find collection date.
SAMN43274437
Unable to find collection date.
SAMN43274436
Unable to find collection date.
SAMN43274434
Unable to find collection date.
SAMN43274433
Unable to find collection date.
SAMN43274432
Unable to find collection date.
SAMN43274431
Unable to find collection date.
SAMN43274430
Unable to find collection date.
SAMN43274403
Unable to find collection date.
SAMN43274429

In [ ]:
# Upload saved data -- if doing this, make sure the above cell is commented out
os.chdir(temp_files + "saved/")
metadata_genbank = pd.read_csv("metadata_genbank_4-18-2025.csv")
os.chdir(temp_files)

# # Get only updated dates

# unknown_dates = metadata_genbank[(metadata_genbank["Collection_Date_Specific"] == "2024") | (metadata_genbank["Collection_Date_Specific"] == "2025")] # Dates we don't have
# known_dates = metadata_genbank[(metadata_genbank["Collection_Date_Specific"] != "2024") & (metadata_genbank["Collection_Date_Specific"] != "2025")] # Dates we've already gotten

# # Get new dates also 
# # new_dates = metadata_genbank["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank) if )

# updated_unknown_dates = unknown_dates["BioSample"].apply(lambda x: search_collection_date(x, unknown_dates)) # Update unknown dates, if possible

# metadata_genbank = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # Remove pre-2024 dates

# metadata_genbank["Collection_Date_Compare"] = metadata_genbank["Collection_Date_Specific"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
# metadata_genbank = metadata_genbank[metadata_genbank["Collection_Date_Compare"] >= datetime(2024, 1, 1).strftime("%Y-%m-%d")]

# print(metadata_genbank[["Collection_Date_Specific"]])

# display(metadata_genbank)

## Get host type

In [8]:
# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genbank)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

os.chdir(downloads)

animals_ref = pd.read_csv("animals_ref.csv") # Upload animals ref

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['burrowing owl', 'bald eagle', 'hooded merganser', 'cattle', 'american woodcock', 'guineafowl', 'house-mouse', 'rock pigeon', 'pet food', 'goat', 'black-crowned night-heron', 'flamingo', 'cackling goose', 'barn owl', 'domestic-cat', "cooper's hawk", 'house sparrow', 'cattle milk product', 'red-tailed hawk', 'feline', 'dove', 'fox', 'cago', 'common raven', 'turkey', 'savannah cat', 'quail', 'chicken', 'merganser', 'red-breasted merganser', 'cat', 'eurasian collared dove', 'guinea fowl', 'emu', 'mute swan', 'bobcat', 'owl', 'duck', 'american robin', 'lion', 'pelican', 'crow', 'goose', 'american wigeon', 'great blue heron', 'american crow', 'gadwall', 'canada goose', 'trumpeter swan', 'red-shouldered hawk', 'blackbird', 'domestic cat', 'snowy owl', 'snow goose', 'comon-grackle', 'skunk', 'swan', 'turkey vulture', 'green-winged teal', 'mountain lion', 'great horned owl', 'serval', 'pefa', "geoffroy's cat", 'red fox', 'raccoon', 'lynx', 'peafowl', 'raw pet food', 'vulture', 'hawk', 'western sandpiper', 'bottlenose dolphin', 'red tailed hawk', 'white-winged dove', 'grackle', 'mallard', 'pigeon', 'crane', 'ermine', 'hosp', 'pig', 'falcon', 'alpaca', 'western gull', 'tiger', 'wood duck', 'harris hawk', 'house mouse', 'avian', 'ganada goose', 'pheasant']
[]
                         avian               cattle        feline  \
0             great_horned_owl            dairy_cow           cat
1                 common_raven               cattle  domestic_cat
2                cooper's_hawk  cattle milk product     feral_cat
3                 coopers_hawk          bovine_milk        feline
4                      peafowl              bovine   domestic-cat
..                         ...                  ...           ...
335    lady_amherst's_pheasant                  NaN           NaN
336                     parrot                  NaN           NaN
337  chinese_ringneck_pheasant                  NaN           NaN
338            silver_pheasant                  NaN           NaN
339                       rhea                  NaN           NaN

      other_mammal       human         other  new
0       deer mouse  washington         mixed  NaN
1      house_mouse      nevada   environment  NaN
2            skunk     wyoming  multispecies  NaN
3    striped_skunk  california           NaN  NaN
4       norway rat    michigan           NaN  NaN
..             ...         ...           ...  ...
335            NaN         NaN           NaN  NaN
336            NaN         NaN           NaN  NaN
337            NaN         NaN           NaN  NaN
338            NaN         NaN           NaN  NaN
339            NaN         NaN           NaN  NaN

[340 rows x 7 columns]

In [9]:
# Get animals from animal reference
os.chdir(downloads)
animals_ref = pd.read_csv("animals_ref.csv")
fix_animals_andersen(metadata_genbank, animals_ref) # Get host type

metadata_genbank["years"] = metadata_genbank["Collection_Date"].apply(lambda x: str(x).split("-")[0]) # Get year only from collection date

## Make names using all the attributes we collected

In [10]:
for num, collection_date in enumerate(metadata_genbank["Collection_Date_Specific"]):
    if collection_date != collection_date: # If nan
        metadata_genbank.loc[num, "Collection_Date_Specific"] = metadata_genbank.loc[num, "years"]
    else: # If actual date
        if len(str(collection_date)) == 4: # If it's a year
            # print("caught")
            metadata_genbank.loc[num, "Collection_Date_Specific"] = collection_date
        else:
            parsed_date = dateutil.parser.parse(collection_date)
            date = parsed_date.strftime("%Y-%m-%d") # Make sure it doesn't default to today, if just a year
            metadata_genbank.loc[num, "Collection_Date_Specific"] = date

# Make names

names = ">A/" + metadata_genbank["Host"] + "/" + metadata_genbank["name_state"] + "/" + metadata_genbank["isolate"] + "/" + metadata_genbank["years"].apply(lambda x: str(x)) + "|H5N1|" + metadata_genbank["Collection_Date_Specific"].apply(lambda x: str(x)) + "|" + metadata_genbank["Host_Type"] + "|" + metadata_genbank["Genotype"]

metadata_genbank["Name"] = names

# metadata_genbank.to_csv("metadata_genbank_named.csv")

# display(metadata_genbank)

In [11]:
print(metadata_genbank)

              Run Assay Type  AvgSpotLen      Bases    BioProject  \
0     SRR28752447        WGS      241.29   86080323  PRJNA1102327
1     SRR28752448        WGS      250.30   75035343  PRJNA1102327
2     SRR28752449        WGS      146.61   59363690  PRJNA1102327
3     SRR28752450        WGS      251.31  119232569  PRJNA1102327
4     SRR28752453        WGS      144.71   37055919  PRJNA1102327
...           ...        ...         ...        ...           ...
4059  SRR32633088        WGS      145.11   67016467  PRJNA1102327
4060  SRR32633089        WGS      148.14  140023511  PRJNA1102327
4061  SRR32633090        WGS      148.49   83727737  PRJNA1102327
4062  SRR32633093        WGS      148.10  105910536  PRJNA1102327
4063  SRR32633094        WGS      148.09  109655942  PRJNA1102327

         BioSample BioSampleModel     Bytes Center Name Collection_Date  ...  \
0     SAMN41019237          Viral  28164109   USDA-NVSL            2024  ...
1     SAMN41019236          Viral  24547283   USDA-NVSL            2024  ...
2     SAMN41019235          Viral  19686302   USDA-NVSL            2024  ...
3     SAMN41019234          Viral  38846827   USDA-NVSL            2024  ...
4     SAMN41019231          Viral  12938409   USDA-NVSL            2024  ...
...            ...            ...       ...         ...             ...  ...
4059  SAMN47290851          Viral  25388495   USDA-NVSL            2025  ...
4060  SAMN47290850          Viral  52157519   USDA-NVSL            2025  ...
4061  SAMN47290849          Viral  31619233   USDA-NVSL            2025  ...
4062  SAMN47290846          Viral  39757708   USDA-NVSL            2025  ...
4063  SAMN47290845          Viral  41506380   USDA-NVSL            2025  ...

          sra_run seg genbank_acc genbank_seg  \
0     SRR28752447  HA  PP752829.1           4
1     SRR28752448  HA  PP752821.1           4
2     SRR28752449  HA  PP752813.1           4
3     SRR28752450  HA  PP752805.1           4
4     SRR28752453  HA  PP752677.1           4
...           ...  ..         ...         ...
4059  SRR32633088  HA  PV456280.1           4
4060  SRR32633089  HA  PV456272.1           4
4061  SRR32633090  HA  PV456264.1           4
4062  SRR32633093  HA  PV457240.1           4
4063  SRR32633094  HA  PV457232.1           4

                                 genbank_name name_state  \
0           A/cattle/Texas/24-009108-005/2024      Texas
1           A/cattle/Texas/24-009108-004/2024      Texas
2           A/cattle/Texas/24-009108-003/2024      Texas
3           A/cattle/Texas/24-009108-002/2024      Texas
4           A/cattle/Texas/24-009088-001/2024      Texas
...                                       ...        ...
4059     A/cat/OR/25-005913-003-original/2025         OR
4060     A/cat/OR/25-005800-002-original/2025         OR
4061     A/cat/OR/25-005800-001-original/2025         OR
4062  A/cattle/CA/25-005677-001-original/2025         CA
4063  A/cattle/CA/25-005648-001-original/2025         CA

     Collection_Date_Specific Host_Type years  \
0                  2024-03-20    cattle  2024
1                  2024-03-20    cattle  2024
2                  2024-03-20    cattle  2024
3                  2024-03-20    cattle  2024
4                  2024-03-13    cattle  2024
...                       ...       ...   ...
4059               2025-02-14    feline  2025
4060               2025-02-12    feline  2025
4061               2025-02-12    feline  2025
4062               2025-02-11    cattle  2025
4063               2025-02-10    cattle  2025

                                                   Name
0     >A/Cattle/Texas/24-009108-005-original/2024|H5...
1     >A/Cattle/Texas/24-009108-004-original/2024|H5...
2     >A/Cattle/Texas/24-009108-003-original/2024|H5...
3     >A/Cattle/Texas/24-009108-002-original/2024|H5...
4     >A/Cattle/Texas/24-009088-001-original/2024|H5...
...                                                 ...
4059  >A/CAT/OR/25-005913-003/2025|H5N1|2025-02-14|f...
4060  >A/CAT/OR/25-005800-002/2025|H5N1|2025-02-12|f...
4061  >A/CAT/OR/25-005800-001/2025|H5N1|2025-02-12|f...
4062  >A/CATTLE/CA/25-005677-001/2025|H5N1|2025-02-1...
4063  >A/CATTLE/CA/25-005648-001/2025|H5N1|2025-02-1...

[4064 rows x 50 columns]

## Make FASTA files

In [12]:
# Get information to create the fasta files

fasta_folder = originals + "avian-influenza/fasta/"

os.chdir(fasta_folder)

segments = ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]
pairs = []
fasta_files = {}

for genotype in genotypes: # ["B3.13", "D1.1"]:
    for segment in segments:
        pair = genotype + "_" + segment
        pairs.append(pair)

for pair in pairs:
    fasta_files[pair] = [] # List to hold fasta files

for run in metadata_genbank["Run"].values: # For each run 
    for dirpath, dirs, files in os.walk(fasta_folder): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            # print(file_name)
            if run in file_name: # Note that there will be ~8 files total with that run name
                # Make a fasta file and put it in the list
                with open(file_name) as f:
                    lines = f.readlines()
                    sequence = lines[1] 
                    # Each run/segment pair has one sequence -- it's placed into a file with other run/segment pairs with the same segment and genotype
                    header = metadata_genbank[metadata_genbank["Run"] == run].loc[:, "Name"].values[0]
                    genotype = metadata_genbank[metadata_genbank["Run"] == run].loc[:, "Genotype"].values[0]
                    # print(header)
                    # print(genotype)
                    # break 
                    segment = file_name.split("_")[-2]
                    # Find the pair that corresponds to 
                    pair_name = genotype + "_" + segment
                    this_specific_fasta = []
                    for pair in pairs:
                        # print(pair)
                        # print(pair_name)
                        if pair_name == pair:
                            this_specific_fasta.append(header)
                            this_specific_fasta.append(sequence)
                            fasta_files[pair].append(this_specific_fasta)
                f.close()
        break

In [15]:
# Create fasta files 

os.chdir(complete_files + "2021-11-01--2025-04-14/")

for pair in fasta_files.keys():
    output_path = complete_files + pair + "_andersen_" + update_date + ".fasta" 

    output_file = open(output_path, "w")
    for item in fasta_files[pair]:
        # for item in item:
        # item = fasta_files[pair]
        try:
            name = str(item[0].values[0]) # See if this is one we didn't have a collection date for
        except:
            name = str(item[0])
        print(name)
        # First is header, second is sequence
        # print(value)
        output_file.write(name + "\n")
        output_file.write(item[1])
    output_file.close()

>A/Cattle/Texas/24-009028-019-original/2024|H5N1|2024-03-20|cattle|A1
>A/Cattle/Texas/24-009775-001-original/2024|H5N1|2024-03-10|cattle|A1
>A/Cattle/New Mexico/24-010512-001-original/2024|H5N1|2024-04-02|cattle|A1
>A/Cattle/South Dakota/24-010354-020-original/2024|H5N1|2024-04-05|cattle|A1
>A/Cattle/Texas/24-009110-019-original/2024|H5N1|2024-03-14|cattle|A1
>A/Chicken/Texas/24-008355-002-original/2024|H5N1|2024-03-16|avian|A1
>A/Cattle/South Dakota/24-010354-001-original/2024|H5N1|2024-04-05|cattle|A1
>A/Cattle/Texas/24-009367-005-original/2024|H5N1|2024-03-25|cattle|A1
>A/CATTLE/New Mexico/24-010192-003/2024|H5N1|2024-04-01|cattle|A1
>A/American Crow/Illinois/24-004479-002-original/2024|H5N1|2024-02-08|avian|A1
>A/DOMESTIC-CAT/NM/24-012046-003/2024|H5N1|2024-04-17|feline|A1
>A/TURKEY/MI/24-012707-001/2024|H5N1|2024-04-29|avian|A1
>A/CATTLE/Idaho/24-012341-022-original/2024|H5N1|2024-04-23|cattle|A1
>A/CATTLE/Colorado/24-012225-014/2024|H5N1|2024-04-23|cattle|A1
>A/CHICKEN/Minnesota/24-014761-002/2024|H5N1|2024|avian|A1
>A/TURKEY/Minnesota/24-014687-001/2024|H5N1|2024|avian|A1
>A/CATTLE/MI/24-015041-001/2024|H5N1|2024-05-17|cattle|A1
>A/Cattle/ID/24-015676-002/2024|H5N1|2024-05-27|cattle|A1
>A/Turkey/MN/24-015549-002/2024|H5N1|2024-05-27|avian|A1
>A/Cattle/MN/24-016511-002/2024|H5N1|2024-06-03|cattle|A1
>A/Cattle/WY/24-016134-078/2024|H5N1|2024-04-29|cattle|A1
>A/Cattle/TX/24-015975-009/2024|H5N1|2024-04-30|cattle|A1
>A/Cattle/TX/24-015975-005/2024|H5N1|2024-04-30|cattle|A1
>A/CATTLE/TX/24-016681-004/2024|H5N1|2024-06-04|cattle|A1
>A/CATTLE/MN/24-016523-020/2024|H5N1|2024-06-04|cattle|A1
>A/CATTLE/ID/24-016437-029/2024|H5N1|2024-05-30|cattle|A1
>A/CATTLE/NM/24-015840-001/2024|H5N1|2024-04-04|cattle|A1
>A/CATTLE/CO/24-017154-006/2024|H5N1|2024-06-10|cattle|A1
>A/CATTLE/CO/24-017048-007/2024|H5N1|2024-06-10|cattle|A1
>A/Cattle/IA/24-017584-010-original/2024|H5N1|2024-06-15|cattle|A1
>A/Cattle/IA/24-017490-001-original/2024|H5N1|2024-06-12|cattle|A1
>A/Cattle/MN/24-017652-010-original/2024|H5N1|2024-06-14|cattle|A1
>A/Cattle/MN/24-017652-001-original/2024|H5N1|2024-06-14|cattle|A1
>A/Cattle/IA/24-017584-019-original/2024|H5N1|2024-06-15|cattle|A1
>A/Cattle/CO/24-017152-014-original/2024|H5N1|2024-06-11|cattle|A1
>A/Cattle/TX/24-017473-005-original/2024|H5N1|2024-05-27|cattle|A1
>A/Cattle/CO/24-018334-004/2024|H5N1|2024-06-20|cattle|A1
>A/Cattle/CO/24-018029-004/2024|H5N1|2024-06-17|cattle|A1
>A/Cattle/CO/24-020027-006/2024|H5N1|2024-07-09|cattle|A1
>A/Chicken/CO/24-020285-011-original/2024|H5N1|2024-07-11|avian|A1
>A/House Sparrow/IA/24-019375-001-original-repeat2/2024|H5N1|2024-06-19|avian|A1
>A/Chicken/CO/24-020285-007-original/2024|H5N1|2024-07-11|avian|A1
>A/Chicken/CO/24-020285-002-original/2024|H5N1|2024-07-11|avian|A1
>A/CATTLE/CO/24-021340-002/2024|H5N1|2024-07-17|cattle|A1
>A/CATTLE/CO/24-020797-004/2024|H5N1|2024-07-17|cattle|A1
>A/Cattle/CO/24-020797-014/2024|H5N1|2024|cattle|A1
>A/Cattle/NM/24-023930-002-original/2024|H5N1|2024-04-22|cattle|A1
>A/CATTLE/CO/24-023564-001/2024|H5N1|2024-08-12|cattle|A1
>A/CATTLE/CA/24-025748-002/2024|H5N1|2024-09-02|cattle|A1
>A/CATTLE/CA/24-025747-001/2024|H5N1|2024-09-03|cattle|A1
>A/Cattle/CA/24-028502-001/2024|H5N1|2024-09-23|cattle|A1
>A/CATTLE/CA/24-029379-003/2024|H5N1|2024-10-03|cattle|A1
>A/CATTLE/CA/24-029616-001/2024|H5N1|2024-10-07|cattle|A1
>A/Emu/CA/24-031663-002/2024|H5N1|2024-10-23|avian|A1
>A/Chicken/CA/24-031078-001/2024|H5N1|2024-10-18|avian|A1
>A/CATTLE/CA/24-032017-001/2024|H5N1|2024-10-21|cattle|A1
>A/CATTLE/CA/24-032046-002/2024|H5N1|2024-10-23|cattle|A1
>A/CATTLE/CA/24-032013-003/2024|H5N1|2024-10-22|cattle|A1
>A/CHICKEN/CA/24-031862-005/2024|H5N1|2024-10-27|avian|A1
>A/Duck/HI/24-033876-004/2024|H5N1|2024-11-12|avian|A1
>A/Cattle/CA/24-033529-004/2024|H5N1|2024-10-29|cattle|A1
>A/Cattle/CA/24-033984-002/2024|H5N1|2024-11-13|cattle|A1
>A/Cattle/CA/24-033988-003/2024|H5N1|2024-11-11|cattle|A1
>A/Cattle/CA/24-033987-001/2024|H5N1|2024-11-11|cattle|A1
>A/Chicken/CA/24-033224-003/2024|H5N1|2024-11-04|avian|A1
>A/Cattle/CA/24-033840-001/2024|H5N1|2024|cattle|A1
>A/Cattle/CA/24-033854-001/2024|H5N1|2024-11-02|cattle|A1
>A/Cattle/CA/24-033520-004/2024|H5N1|2024-10-30|cattle|A1
>A/Cattle/CA/24-033520-003/2024|H5N1|2024-10-30|cattle|A1
>A/Cattle/CA/24-033505-001/2024|H5N1|2024-10-30|cattle|A1
>A/Cattle/CA/24-034224-001/2024|H5N1|2024-11-05|cattle|A1
>A/Cattle/CA/24-034025-002/2024|H5N1|2024-11-12|cattle|A1
>A/Chicken/WA/24-032191-001/2024|H5N1|2024|avian|A1
>A/Turkey/CA/24-031284-008/2024|H5N1|2024|avian|A1
>A/Cattle/CA/24-032048-002/2024|H5N1|2024|cattle|A1
>A/Chicken/CA/24-031285-010/2024|H5N1|2024|avian|A1
>A/Cattle/CA/24-032013-002/2024|H5N1|2024|cattle|A1
>A/Cattle/CA/24-031959-001/2024|H5N1|2024|cattle|A1
>A/Chicken/CA/24-031862-016/2024|H5N1|2024|avian|A1
>A/Turkey/CA/24-031284-017/2024|H5N1|2024|avian|A1
>A/Cattle/CA/24-032035-002/2024|H5N1|2024|cattle|A1
>A/Cattle/CA/24-032030-001/2024|H5N1|2024|cattle|A1
>A/Chicken/CA/24-031667-005/2024|H5N1|2024|avian|A1
>A/CATTLE/CA/24-036768-001/2024|H5N1|2024-11-30|cattle|A1
>A/CATTLE/CA/24-036763-003/2024|H5N1|2024-12-02|cattle|A1
>A/CHICKEN/CA/24-036644-001/2024|H5N1|2024-12-05|avian|A1
>A/CATTLE/CA/24-036371-001/2024|H5N1|2024-12-04|cattle|A1
>A/CATTLE/CA/24-036571-002/2024|H5N1|2024-12-05|cattle|A1
>A/CATTLE/CA/24-036354-002/2024|H5N1|2024-12-04|cattle|A1
>A/CATTLE/CA/24-036561-001/2024|H5N1|2024-12-03|cattle|A1
>A/CATTLE/CA/24-036395-002/2024|H5N1|2024-12-04|cattle|A1
>A/CATTLE/CA/24-036377-001/2024|H5N1|2024-12-04|cattle|A1
>A/CHICKEN/CA/24-036326-001/2024|H5N1|2024-12-02|avian|A1
>A/CHICKEN/CA/24-037219-030/2024|H5N1|2024-12-10|avian|A1
>A/CHICKEN/CA/24-037219-021/2024|H5N1|2024-12-10|avian|A1
>A/CATTLE/CA/24-036819-003/2024|H5N1|2024-11-28|cattle|A1
>A/CATTLE/CA/24-036817-001/2024|H5N1|2024-11-26|cattle|A1
>A/CATTLE/CA/24-036553-006/2024|H5N1|2024-12-05|cattle|A1
>A/CATTLE/CA/24-037202-006/2024|H5N1|2024-12-02|cattle|A1
>A/CHICKEN/CA/24-037427-001/2024|H5N1|2024-12-11|avian|A1
>A/MOUNTAIN LION/WA/24-037410-007/2024|H5N1|2024|feline|A1
>A/GEOFFROY'S CAT/WA/24-037410-004/2024|H5N1|2024|feline|A1
>A/CATTLE/CA/24-037031-002/2024|H5N1|2024-12-09|cattle|A1
>A/CATTLE/CA/24-034970-001/2024|H5N1|2024-11-18|cattle|A1
>A/CATTLE/CA/24-038350-002/2024|H5N1|2024-12-18|cattle|A1
>A/CATTLE/CA/24-038335-002/2024|H5N1|2024-12-17|cattle|A1
>A/CATTLE/CA/24-038303-003/2024|H5N1|2024|cattle|A1
>A/CATTLE/CA/24-030025-001/2024|H5N1|2024-10-08|cattle|A1
>A/CATTLE/CA/24-036117-002/2024|H5N1|2024-12-02|cattle|A1
>A/GREAT HORNED OWL/IA/25-000440-001/2025|H5N1|2025|avian|A1
>A/CHICKEN/DE/25-000536-001/2025|H5N1|2025-01-07|avian|A1
>A/DUCK/TX/25-000377-001/2025|H5N1|2025-01-03|avian|A1
>A/CHICKEN/NC/25-000300-001/2025|H5N1|2025-01-06|avian|A1
>A/TURKEY/MI/25-000204-002/2025|H5N1|2025-01-02|avian|A1
>A/PHEASANT/CA/25-000138-002/2025|H5N1|2024-12-30|avian|A1
>A/CHICKEN/ID/25-000073-001/2025|H5N1|2024-12-26|avian|A1
>A/GUINEAFOWL/WV/25-000050-001/2025|H5N1|2024-12-31|avian|A1
>A/PHEASANT/KS/24-037794-006/2024|H5N1|2024-12-16|avian|A1
>A/TURKEY/SD/24-037530-001/2024|H5N1|2024-12-13|avian|A1
>A/CHICKEN/NE/24-037518-001/2024|H5N1|2024-12-13|avian|A1
>A/Duck/HI/24-033968-002/2024|H5N1|2024-11-07|avian|A1
>A/CHICKEN/WA/24-030039-001/2024|H5N1|2024-10-11|avian|A1
>A/CHICKEN/FL/24-027090-001/2024|H5N1|2024-09-16|avian|A1
>A/CANADA GOOSE/PA/25-003377-001/2025|H5N1|2025-01-28|avian|A1
>A/BURROWING OWL/CA/25-003486-001/2025|H5N1|2025-01-17|avian|A1
>A/MALLARD/WY/25-002131-012/2025|H5N1|2025-01-15|avian|A1
>A/CATTLE/CA/25-003619-002/2025|H5N1|2025-01-27|cattle|A1
>A/QUAIL/NY/25-004295-002/2025|H5N1|2025-02-03|avian|A1
>A/CHICKEN/AZ/25-003936-003/2025|H5N1|2025-02-03|avian|A1
>A/CHICKEN/NY/25-003808-002/2025|H5N1|2025-01-30|avian|A1
>A/TURKEY/OH/25-004218-004/2025|H5N1|2025-02-03|avian|A1
>A/TURKEY/MO/25-003821-002/2025|H5N1|2025-02-02|avian|A1
>A/CHICKEN/OR/25-003575-001/2025|H5N1|2025-01-23|avian|A1
>A/CATTLE/CA/25-004457-001/2025|H5N1|2025-02-04|cattle|A1
>A/CHICKEN/IN/25-004773-002/2025|H5N1|2025-02-09|avian|A1
>A/CAT/OR/25-004391-001/2025|H5N1|2025-02-05|feline|A1
>A/CHICKEN/IN/25-002876-001/2025|H5N1|2025-01-25|avian|A1
>A/TURKEY/IN/25-002660-003/2025|H5N1|2025-01-03|avian|A1
>A/TURKEY/MO/25-003392-001/2025|H5N1|2025-01-29|avian|A1
>A/GREAT HORNED OWL/PA/25-002837-001/2025|H5N1|2025-01-17|avian|A1
>A/MALLARD/NY/25-002741-006/2025|H5N1|2025-01-16|avian|A1
>A/CANADA GOOSE/NY/25-002739-001/2025|H5N1|2025-01-23|avian|A1
>A/CATTLE/CA/25-002697-001/2025|H5N1|2025-01-21|cattle|A1
>A/TURKEY/IA/25-005857-004/2025|H5N1|2025-02-18|avian|A1
>A/CHICKEN/ME/25-005928-005/2025|H5N1|2025-02-14|avian|A1
>A/CHICKEN/AZ/25-005798-004/2025|H5N1|2025-02-13|avian|A1
>A/Cattle/Texas/24-009028-019-original/2024|H5N1|2024-03-20|cattle|A1
>A/Cattle/Texas/24-009775-001-original/2024|H5N1|2024-03-10|cattle|A1
>A/Cattle/New Mexico/24-010512-001-original/2024|H5N1|2024-04-02|cattle|A1
>A/Cattle/South Dakota/24-010354-020-original/2024|H5N1|2024-04-05|cattle|A1
>A/Cattle/Texas/24-009110-019-original/2024|H5N1|2024-03-14|cattle|A1
>A/Chicken/Texas/24-008355-002-original/2024|H5N1|2024-03-16|avian|A1
>A/Cattle/South Dakota/24-010354-001-original/2024|H5N1|2024-04-05|cattle|A1
>A/Cattle/Texas/24-009367-005-original/2024|H5N1|2024-03-25|cattle|A1
>A/CATTLE/New Mexico/24-010192-003/2024|H5N1|2024-04-01|cattle|A1
>A/American Crow/Illinois/24-004479-002-original/2024|H5N1|2024-02-08|avian|A1
>A/DOMESTIC-CAT/NM/24-012046-003/2024|H5N1|2024-04-17|feline|A1
>A/TURKEY/MI/24-012707-001/2024|H5N1|2024-04-29|avian|A1
>A/CATTLE/Idaho/24-012341-022-original/2024|H5N1|2024-04-23|cattle|A1
>A/CATTLE/Colorado/24-012225-014/2024|H5N1|2024-04-23|cattle|A1
>A/CHICKEN/Minnesota/24-014761-002/2024|H5N1|2024|avian|A1
>A/TURKEY/Minnesota/24-014687-001/2024|H5N1|2024|avian|A1
>A/CATTLE/MI/24-015041-001/2024|H5N1|2024-05-17|cattle|A1
>A/Cattle/ID/24-015676-002/2024|H5N1|2024-05-27|cattle|A1
>A/Turkey/MN/24-015549-002/2024|H5N1|2024-05-27|avian|A1
>A/Cattle/MN/24-016511-002/2024|H5N1|2024-06-03|cattle|A1
>A/Cattle/WY/24-016134-078/2024|H5N1|2024-04-29|cattle|A1
>A/Cattle/TX/24-015975-009/2024|H5N1|2024-04-30|cattle|A1
>A/Cattle/TX/24-015975-005/2024|H5N1|2024-04-30|cattle|A1
>A/CATTLE/TX/24-016681-004/2024|H5N1|2024-06-04|cattle|A1
>A/CATTLE/MN/24-016523-020/2024|H5N1|2024-06-04|cattle|A1
>A/CATTLE/ID/24-016437-029/2024|H5N1|2024-05-30|cattle|A1
>A/CATTLE/NM/24-015840-001/2024|H5N1|2024-04-04|cattle|A1
>A/CATTLE/CO/24-017154-006/2024|H5N1|2024-06-10|cattle|A1
>A/CATTLE/CO/24-017048-007/2024|H5N1|2024-06-10|cattle|A1
>A/Cattle/IA/24-017584-010-original/2024|H5N1|2024-06-15|cattle|A1
>A/Cattle/IA/24-017490-001-original/2024|H5N1|2024-06-12|cattle|A1
>A/Cattle/MN/24-017652-010-original/2024|H5N1|2024-06-14|cattle|A1
>A/Cattle/MN/24-017652-001-original/2024|H5N1|2024-06-14|cattle|A1
>A/Cattle/IA/24-017584-019-original/2024|H5N1|2024-06-15|cattle|A1
>A/Cattle/CO/24-017152-014-original/2024|H5N1|2024-06-11|cattle|A1
>A/Cattle/TX/24-017473-005-original/2024|H5N1|2024-05-27|cattle|A1
>A/Cattle/CO/24-018334-004/2024|H5N1|2024-06-20|cattle|A1
>A/Cattle/CO/24-018029-004/2024|H5N1|2024-06-17|cattle|A1
>A/Cattle/CO/24-020027-006/2024|H5N1|2024-07-09|cattle|A1
>A/Chicken/CO/24-020285-011-original/2024|H5N1|2024-07-11|avian|A1
>A/House Sparrow/IA/24-019375-001-original-repeat2/2024|H5N1|2024-06-19|avian|A1
>A/Chicken/CO/24-020285-007-original/2024|H5N1|2024-07-11|avian|A1
>A/Chicken/CO/24-020285-002-original/2024|H5N1|2024-07-11|avian|A1
>A/CATTLE/CO/24-021340-002/2024|H5N1|2024-07-17|cattle|A1
>A/CATTLE/CO/24-020797-004/2024|H5N1|2024-07-17|cattle|A1
>A/Cattle/CO/24-020797-014/2024|H5N1|2024|cattle|A1
>A/Cattle/NM/24-023930-002-original/2024|H5N1|2024-04-22|cattle|A1
>A/CATTLE/CO/24-023564-001/2024|H5N1|2024-08-12|cattle|A1
>A/CATTLE/CA/24-025748-002/2024|H5N1|2024-09-02|cattle|A1
>A/CATTLE/CA/24-025747-001/2024|H5N1|2024-09-03|cattle|A1
>A/Cattle/CA/24-028502-001/2024|H5N1|2024-09-23|cattle|A1
>A/CATTLE/CA/24-029379-003/2024|H5N1|2024-10-03|cattle|A1
>A/CATTLE/CA/24-029616-001/2024|H5N1|2024-10-07|cattle|A1
>A/Emu/CA/24-031663-002/2024|H5N1|2024-10-23|avian|A1
>A/Chicken/CA/24-031078-001/2024|H5N1|2024-10-18|avian|A1
>A/CATTLE/CA/24-032017-001/2024|H5N1|2024-10-21|cattle|A1
>A/CATTLE/CA/24-032046-002/2024|H5N1|2024-10-23|cattle|A1
>A/CATTLE/CA/24-032013-003/2024|H5N1|2024-10-22|cattle|A1
>A/CHICKEN/CA/24-031862-005/2024|H5N1|2024-10-27|avian|A1
>A/Duck/HI/24-033876-004/2024|H5N1|2024-11-12|avian|A1
>A/Cattle/CA/24-033529-004/2024|H5N1|2024-10-29|cattle|A1
>A/Cattle/CA/24-033984-002/2024|H5N1|2024-11-13|cattle|A1
>A/Cattle/CA/24-033988-003/2024|H5N1|2024-11-11|cattle|A1
>A/Cattle/CA/24-033987-001/2024|H5N1|2024-11-11|cattle|A1
>A/Chicken/CA/24-033224-003/2024|H5N1|2024-11-04|avian|A1
>A/Cattle/CA/24-033840-001/2024|H5N1|2024|cattle|A1
>A/Cattle/CA/24-033854-001/2024|H5N1|2024-11-02|cattle|A1
>A/Cattle/CA/24-033520-004/2024|H5N1|2024-10-30|cattle|A1
>A/Cattle/CA/24-033520-003/2024|H5N1|2024-10-30|cattle|A1
>A/Cattle/CA/24-033505-001/2024|H5N1|2024-10-30|cattle|A1
>A/Cattle/CA/24-034224-001/2024|H5N1|2024-11-05|cattle|A1
>A/Cattle/CA/24-034025-002/2024|H5N1|2024-11-12|cattle|A1
>A/Chicken/WA/24-032191-001/2024|H5N1|2024|avian|A1
>A/Turkey/CA/24-031284-008/2024|H5N1|2024|avian|A1
>A/Cattle/CA/24-032048-002/2024|H5N1|2024|cattle|A1
>A/Chicken/CA/24-031285-010/2024|H5N1|2024|avian|A1
>A/Cattle/CA/24-032013-002/2024|H5N1|2024|cattle|A1
>A/Cattle/CA/24-031959-001/2024|H5N1|2024|cattle|A1
>A/Chicken/CA/24-031862-016/2024|H5N1|2024|avian|A1
>A/Turkey/CA/24-031284-017/2024|H5N1|2024|avian|A1
>A/Cattle/CA/24-032035-002/2024|H5N1|2024|cattle|A1
>A/Cattle/CA/24-032030-001/2024|H5N1|2024|cattle|A1
>A/Chicken/CA/24-031667-005/2024|H5N1|2024|avian|A1
>A/CATTLE/CA/24-036768-001/2024|H5N1|2024-11-30|cattle|A1
>A/CATTLE/CA/24-036763-003/2024|H5N1|2024-12-02|cattle|A1
>A/CHICKEN/CA/24-036644-001/2024|H5N1|2024-12-05|avian|A1
>A/CATTLE/CA/24-036371-001/2024|H5N1|2024-12-04|cattle|A1
>A/CATTLE/CA/24-036571-002/2024|H5N1|2024-12-05|cattle|A1
>A/CATTLE/CA/24-036354-002/2024|H5N1|2024-12-04|cattle|A1
>A/CATTLE/CA/24-036561-001/2024|H5N1|2024-12-03|cattle|A1
>A/CATTLE/CA/24-036395-002/2024|H5N1|2024-12-04|cattle|A1
>A/CATTLE/CA/24-036377-001/2024|H5N1|2024-12-04|cattle|A1
>A/CHICKEN/CA/24-036326-001/2024|H5N1|2024-12-02|avian|A1
>A/CHICKEN/CA/24-037219-030/2024|H5N1|2024-12-10|avian|A1
>A/CHICKEN/CA/24-037219-021/2024|H5N1|2024-12-10|avian|A1
>A/CATTLE/CA/24-036819-003/2024|H5N1|2024-11-28|cattle|A1
>A/CATTLE/CA/24-036817-001/2024|H5N1|2024-11-26|cattle|A1
>A/CATTLE/CA/24-036553-006/2024|H5N1|2024-12-05|cattle|A1
>A/CATTLE/CA/24-037202-006/2024|H5N1|2024-12-02|cattle|A1
>A/CHICKEN/CA/24-037427-001/2024|H5N1|2024-12-11|avian|A1
>A/MOUNTAIN LION/WA/24-037410-007/2024|H5N1|2024|feline|A1
>A/GEOFFROY'S CAT/WA/24-037410-004/2024|H5N1|2024|feline|A1
>A/CATTLE/CA/24-037031-002/2024|H5N1|2024-12-09|cattle|A1
>A/CATTLE/CA/24-034970-001/2024|H5N1|2024-11-18|cattle|A1
>A/CATTLE/CA/24-038350-002/2024|H5N1|2024-12-18|cattle|A1
>A/CATTLE/CA/24-038335-002/2024|H5N1|2024-12-17|cattle|A1
>A/CATTLE/CA/24-038303-003/2024|H5N1|2024|cattle|A1
>A/CATTLE/CA/24-030025-001/2024|H5N1|2024-10-08|cattle|A1
>A/CATTLE/CA/24-036117-002/2024|H5N1|2024-12-02|cattle|A1
>A/GREAT HORNED OWL/IA/25-000440-001/2025|H5N1|2025|avian|A1
>A/CHICKEN/DE/25-000536-001/2025|H5N1|2025-01-07|avian|A1
>A/DUCK/TX/25-000377-001/2025|H5N1|2025-01-03|avian|A1
>A/CHICKEN/NC/25-000300-001/2025|H5N1|2025-01-06|avian|A1
>A/TURKEY/MI/25-000204-002/2025|H5N1|2025-01-02|avian|A1
>A/PHEASANT/CA/25-000138-002/2025|H5N1|2024-12-30|avian|A1
>A/CHICKEN/ID/25-000073-001/2025|H5N1|2024-12-26|avian|A1
>A/GUINEAFOWL/WV/25-000050-001/2025|H5N1|2024-12-31|avian|A1
>A/PHEASANT/KS/24-037794-006/2024|H5N1|2024-12-16|avian|A1
>A/TURKEY/SD/24-037530-001/2024|H5N1|2024-12-13|avian|A1
>A/CHICKEN/NE/24-037518-001/2024|H5N1|2024-12-13|avian|A1
>A/Duck/HI/24-033968-002/2024|H5N1|2024-11-07|avian|A1
>A/CHICKEN/WA/24-030039-001/2024|H5N1|2024-10-11|avian|A1
>A/CHICKEN/FL/24-027090-001/2024|H5N1|2024-09-16|avian|A1
>A/CANADA GOOSE/PA/25-003377-001/2025|H5N1|2025-01-28|avian|A1
>A/BURROWING OWL/CA/25-003486-001/2025|H5N1|2025-01-17|avian|A1
>A/MALLARD/WY/25-002131-012/2025|H5N1|2025-01-15|avian|A1
>A/CATTLE/CA/25-003619-002/2025|H5N1|2025-01-27|cattle|A1
>A/QUAIL/NY/25-004295-002/2025|H5N1|2025-02-03|avian|A1
>A/CHICKEN/AZ/25-003936-003/2025|H5N1|2025-02-03|avian|A1
>A/CHICKEN/NY/25-003808-002/2025|H5N1|2025-01-30|avian|A1
>A/TURKEY/OH/25-004218-004/2025|H5N1|2025-02-03|avian|A1
>A/TURKEY/MO/25-003821-002/2025|H5N1|2025-02-02|avian|A1
>A/CHICKEN/OR/25-003575-001/2025|H5N1|2025-01-23|avian|A1
>A/CATTLE/CA/25-004457-001/2025|H5N1|2025-02-04|cattle|A1
>A/CHICKEN/IN/25-004773-002/2025|H5N1|2025-02-09|avian|A1
>A/CAT/OR/25-004391-001/2025|H5N1|2025-02-05|feline|A1
>A/CHICKEN/IN/25-002876-001/2025|H5N1|2025-01-25|avian|A1
>A/TURKEY/IN/25-002660-003/2025|H5N1|2025-01-03|avian|A1
>A/TURKEY/MO/25-003392-001/2025|H5N1|2025-01-29|avian|A1
>A/GREAT HORNED OWL/PA/25-002837-001/2025|H5N1|2025-01-17|avian|A1
>A/MALLARD/NY/25-002741-006/2025|H5N1|2025-01-16|avian|A1
>A/CANADA GOOSE/NY/25-002739-001/2025|H5N1|2025-01-23|avian|A1
>A/CATTLE/CA/25-002697-001/2025|H5N1|2025-01-21|cattle|A1
>A/TURKEY/IA/25-005857-004/2025|H5N1|2025-02-18|avian|A1
>A/CHICKEN/ME/25-005928-005/2025|H5N1|2025-02-14|avian|A1
>A/CHICKEN/AZ/25-005798-004/2025|H5N1|2025-02-13|avian|A1
>A/Cattle/Texas/24-009028-019-original/2024|H5N1|2024-03-20|cattle|A1
>A/Cattle/Texas/24-009775-001-original/2024|H5N1|2024-03-10|cattle|A1
>A/Cattle/New Mexico/24-010512-001-original/2024|H5N1|2024-04-02|cattle|A1
>A/Cattle/South Dakota/24-010354-020-original/2024|H5N1|2024-04-05|cattle|A1
>A/Cattle/Texas/24-009110-019-original/2024|H5N1|2024-03-14|cattle|A1
>A/Chicken/Texas/24-008355-002-original/2024|H5N1|2024-03-16|avian|A1
>A/Cattle/South Dakota/24-010354-001-original/2024|H5N1|2024-04-05|cattle|A1
>A/Cattle/Texas/24-009367-005-original/2024|H5N1|2024-03-25|cattle|A1
>A/CATTLE/New Mexico/24-010192-003/2024|H5N1|2024-04-01|cattle|A1
>A/American Crow/Illinois/24-004479-002-original/2024|H5N1|2024-02-08|avian|A1
>A/DOMESTIC-CAT/NM/24-012046-003/2024|H5N1|2024-04-17|feline|A1
>A/TURKEY/MI/24-012707-001/2024|H5N1|2024-04-29|avian|A1
>A/CATTLE/Idaho/24-012341-022-original/2024|H5N1|2024-04-23|cattle|A1
>A/CATTLE/Colorado/24-012225-014/2024|H5N1|2024-04-23|cattle|A1
>A/CHICKEN/Minnesota/24-014761-002/2024|H5N1|2024|avian|A1
>A/TURKEY/Minnesota/24-014687-001/2024|H5N1|2024|avian|A1
>A/CATTLE/MI/24-015041-001/2024|H5N1|2024-05-17|cattle|A1
>A/Cattle/ID/24-015676-002/2024|H5N1|2024-05-27|cattle|A1
>A/Turkey/MN/24-015549-002/2024|H5N1|2024-05-27|avian|A1
>A/Cattle/MN/24-016511-002/2024|H5N1|2024-06-03|cattle|A1
>A/Cattle/WY/24-016134-078/2024|H5N1|2024-04-29|cattle|A1
>A/Cattle/TX/24-015975-009/2024|H5N1|2024-04-30|cattle|A1
>A/Cattle/TX/24-015975-005/2024|H5N1|2024-04-30|cattle|A1
>A/CATTLE/TX/24-016681-004/2024|H5N1|2024-06-04|cattle|A1
>A/CATTLE/MN/24-016523-020/2024|H5N1|2024-06-04|cattle|A1
>A/CATTLE/ID/24-016437-029/2024|H5N1|2024-05-30|cattle|A1
>A/CATTLE/NM/24-015840-001/2024|H5N1|2024-04-04|cattle|A1
>A/CATTLE/CO/24-017154-006/2024|H5N1|2024-06-10|cattle|A1
>A/CATTLE/CO/24-017048-007/2024|H5N1|2024-06-10|cattle|A1
>A/Cattle/IA/24-017584-010-original/2024|H5N1|2024-06-15|cattle|A1
>A/Cattle/IA/24-017490-001-original/2024|H5N1|2024-06-12|cattle|A1
>A/Cattle/MN/24-017652-010-original/2024|H5N1|2024-06-14|cattle|A1
>A/Cattle/MN/24-017652-001-original/2024|H5N1|2024-06-14|cattle|A1
>A/Cattle/IA/24-017584-019-original/2024|H5N1|2024-06-15|cattle|A1
>A/Cattle/CO/24-017152-014-original/2024|H5N1|2024-06-11|cattle|A1
>A/Cattle/TX/24-017473-005-original/2024|H5N1|2024-05-27|cattle|A1
>A/Cattle/CO/24-018334-004/2024|H5N1|2024-06-20|cattle|A1
>A/Cattle/CO/24-018029-004/2024|H5N1|2024-06-17|cattle|A1
>A/Cattle/CO/24-020027-006/2024|H5N1|2024-07-09|cattle|A1
>A/Chicken/CO/24-020285-011-original/2024|H5N1|2024-07-11|avian|A1

## De-Duplication

In [3]:
# De-duplication 

# Gisaid 

gisaid = downloads + "GISAID_Complete_Fasta_Files/11-01-2021--04-14-2025_all_genotypes_namerica/"

os.chdir(gisaid)

dfs_gisaid = create_dataframes(gisaid)
# dfs_gisaid2 = create_dataframes(gisaid2)

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2

In [4]:
# Do the same with Andersen 

dfs_andersen = create_dataframes(complete_files + "11-01-2021--04-14-2025_all_genotypes/")

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2

In [5]:
for key in dfs_andersen.keys():
    dataframes = dfs_andersen[key]
    print(key)

print(dfs_andersen)

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
defaultdict(<class 'list'>, {'A1_HA': [    isolate_partial                                        full_header  \
0        017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
1        017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
2        030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
3        024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
4        024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
..              ...                                                ...
713      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
714      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
715      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
716      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
717      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                              sequence
0    atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
1    atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
2    atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
3    atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
4    atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
..                                                 ...
713  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
714  atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
715  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
716  atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
717  atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...

[718 rows x 3 columns]], 'A1_MP': [    isolate_partial                                        full_header  \
0        017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
1        017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
2        030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
3        024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
4        024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
..              ...                                                ...
713      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
714      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
715      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
716      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
717      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                              sequence
0    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
1    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
2    atgagtcttctaaccgaggtcgaaacgtacgttctctccatcgtcc...
3    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
4    atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
..                                                 ...
713  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
714  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
715  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
716  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
717  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...

[718 rows x 3 columns]], 'A1_NA': [    isolate_partial                                        full_header  \
0        017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
1        017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
2        030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
3        024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
4        024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
..              ...                                                ...
713      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
714      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
715      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
716      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
717      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                              sequence
0    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
1    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
2    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
3    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
4    atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
..                                                 ...
713  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
714  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
715  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
716  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
717  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...

[718 rows x 3 columns]], 'A1_NP': [    isolate_partial                                        full_header  \
0        017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
1        017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
2        030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
3        024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
4        024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
..              ...                                                ...
713      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
714      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
715      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
716      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
717      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                              sequence
0    atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
1    atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
2    atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
3    atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
4    atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
..                                                 ...
713  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
714  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
715  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
716  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
717  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...

[718 rows x 3 columns]], 'A1_NS': [    isolate_partial                                        full_header  \
0        017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
1        017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
2        030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
3        024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
4        024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
..              ...                                                ...
713      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
714      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
715      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
716      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
717      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                              sequence
0    atggattccaacactgtgtcaagctttcaggtagactgcttccttt...
1    atggattccaacactgtgtcaagctttcaggtagactgcttccttt...
2    atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
3    atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
4    atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
..                                                 ...
713  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
714  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
715  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
716  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
717  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...

[718 rows x 3 columns]], 'A1_PA': [    isolate_partial                                        full_header  \
0        017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
1        017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
2        030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
3        024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
4        024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
..              ...                                                ...
713      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
714      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
715      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
716      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
717      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                              sequence
0    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
1    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
2    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
3    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
4    atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
..                                                 ...
713  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
714  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
715  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
716  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
717  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...

[718 rows x 3 columns]], 'A1_PB1': [    isolate_partial                                        full_header  \
0        017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
1        017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
2        030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
3        024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
4        024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
..              ...                                                ...
713      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
714      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
715      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
716      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
717      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                              sequence
0    atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
1    atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
2    atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
3    atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
4    atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
..                                                 ...
713  atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
714  atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
715  atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
716  atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
717  atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...

[718 rows x 3 columns]], 'A1_PB2': [    isolate_partial                                        full_header  \
0        017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
1        017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
2        030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
3        024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
4        024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
..              ...                                                ...
713      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
714      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
715      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
716      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
717      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                              sequence
0    atggagagaataagagagctaagagatttgatgtcgcaatctcgca...
1    atggagagaataagagagctaagagatttgatgtcgcaatctcgca...
2    atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...
3    atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...
4    atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...
..                                                 ...
713  atggagagaataaaagagctaagaaatttgatgtcgcaatctcgca...
714  atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...
715  atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...
716  atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...
717  atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...

[718 rows x 3 columns]], 'A2_HA': [    isolate_partial                                        full_header  \
0        016611-015  >A/gannet/Massachusetts/22-016611-015/2022|H5N...
1        016611-009  >A/gull/Massachusetts/22-016611-009/2022|H5N1|...
2        016611-006  >A/gull/Massachusetts/22-016611-006/2022|H5N1|...
3        020652-001  >A/herring_gull/New_Hampshire/22-020652-001/20...
4        015021-001  >A/herring_gull/New_York/22-015021-001/2022|H5...
..              ...                                                ...
419      010181-001  >A/guinea_fowl/Maine/22-010181-001/2022|H5N1|2...
420      010181-002  >A/goose/Maine/22-010181-002/2022|H5N1|2022-04...
421      008366-001  >A/chicken/Maine/22-008366-001/2022|H5N1|2022-...
422      008064-002  >A/chicken/Maine/22-008064-002/2022|H5N1|2022-...
423      008064-001  >A/guinea_fowl/Maine/22-008064-001/2022|H5N1|2...

                                              sequence
0    atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
1    atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
2    atggagaacatagtactacttcttgcaacagtcagccttgttaaaa...
3    atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
4    atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
..                                                 ...
419  atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
420  atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
421  atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
422  atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
423  atggagaacatagtactacttcttgcaacagttagccttgttaaaa...

[424 rows x 3 columns]], 'A2_MP': [    isolate_partial                                        full_header  \
0        016611-015  >A/gannet/Massachusetts/22-016611-015/2022|H5N...

In [6]:
print(len(list(dfs_gisaid.keys())))
print(len(list(dfs_andersen.keys())))

592
592

In [7]:
# Merge dataframes and drop duplicates

full_dfs = defaultdict(list)

for i, andersen_key in enumerate(dfs_andersen.keys()):
    if len(dfs_andersen[andersen_key]) > 0:
        for j, gisaid_key in enumerate(dfs_gisaid.keys()):
            if andersen_key == gisaid_key:
        # gisaid_key = list(dfs_gisaid.keys())[i]
        # gisaid2_key = list(dfs_gisaid2.keys())[i]

                andersen_df = dfs_andersen[andersen_key][0]
                gisaid_df = dfs_gisaid[gisaid_key][0]
                # gisaid2_df = dfs_gisaid2[gisaid2_key][0]

                full_df = pd.concat([andersen_df, gisaid_df], ignore_index=True)
                full_df = full_df.drop_duplicates(subset="isolate_partial", keep="last")
                full_dfs[andersen_key].append(full_df)

print(full_dfs)

defaultdict(<class 'list'>, {'A1_HA': [     isolate_partial                                        full_header  \
718       017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
719       017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
720       030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
721       024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
722       024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
...              ...                                                ...
1431      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
1432      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
1433      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
1434      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
1435      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                               sequence
718   atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
719   atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
720   atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
721   atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
722   atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
...                                                 ...
1431  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
1432  atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
1433  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
1434  atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
1435  atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...

[597 rows x 3 columns]], 'A1_MP': [     isolate_partial                                        full_header  \
718       017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
719       017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
720       030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
721       024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
722       024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
...              ...                                                ...
1431      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
1432      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
1433      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
1434      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
1435      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                               sequence
718   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
719   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
720   atgagtcttctaaccgaggtcgaaacgtacgttctctccatcgtcc...
721   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
722   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
...                                                 ...
1431  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
1432  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
1433  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
1434  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
1435  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...

[597 rows x 3 columns]], 'A1_NA': [     isolate_partial                                        full_header  \
718       017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
719       017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
720       030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
721       024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
722       024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
...              ...                                                ...
1431      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
1432      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
1433      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
1434      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
1435      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                               sequence
718   atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
719   atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
720   atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
721   atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
722   atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
...                                                 ...
1431  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
1432  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
1433  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
1434  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
1435  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...

[597 rows x 3 columns]], 'A1_NP': [     isolate_partial                                        full_header  \
718       017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
719       017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
720       030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
721       024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
722       024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
...              ...                                                ...
1431      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
1432      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
1433      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
1434      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
1435      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                               sequence
718   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
719   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
720   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
721   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
722   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
...                                                 ...
1431  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
1432  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
1433  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
1434  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
1435  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...

[597 rows x 3 columns]], 'A1_NS': [     isolate_partial                                        full_header  \
718       017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
719       017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
720       030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
721       024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
722       024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
...              ...                                                ...
1431      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
1432      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
1433      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
1434      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
1435      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                               sequence
718   atggattccaacactgtgtcaagctttcaggtagactgcttccttt...
719   atggattccaacactgtgtcaagctttcaggtagactgcttccttt...
720   atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
721   atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
722   atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
...                                                 ...
1431  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
1432  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
1433  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
1434  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
1435  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...

[597 rows x 3 columns]], 'A1_PA': [     isolate_partial                                        full_header  \
718       017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
719       017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
720       030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
721       024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
722       024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
...              ...                                                ...
1431      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
1432      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
1433      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
1434      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
1435      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                               sequence
718   atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
719   atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
720   atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
721   atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
722   atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
...                                                 ...
1431  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
1432  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
1433  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
1434  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
1435  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...

[597 rows x 3 columns]], 'A1_PB1': [     isolate_partial                                        full_header  \
718       017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
719       017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
720       030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
721       024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
722       024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
...              ...                                                ...
1431      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
1432      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
1433      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
1434      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
1435      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                               sequence
718   atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
719   atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
720   atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
721   atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
722   atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
...                                                 ...
1431  atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
1432  atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
1433  atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
1434  atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
1435  atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...

[597 rows x 3 columns]], 'A1_PB2': [     isolate_partial                                        full_header  \
718       017947-002  >A/eared_grebe/Wyoming/22-017947-002/2022|H5N1...
719       017947-001  >A/eared_grebe/Wyoming/22-017947-001/2022|H5N1...
720       030264-001  >A/double_crested_cormorant/Wisconsin/22-03026...
721       024871-012  >A/gadwall/Tennessee/22-024871-012/2022|H5N1|2...
722       024871-011  >A/gadwall/Tennessee/22-024871-011/2022|H5N1|2...
...              ...                                                ...
1431      007087-002  >A/turkey/Missouri/22-007087-002/2022|H5N1|202...
1432      006945-001  >A/chicken/Delaware/22-006945-001/2022|H5N1|20...
1433      006944-002  >A/turkey/Missouri/22-006944-002/2022|H5N1|202...
1434      006948-001  >A/chicken/Maryland/22-006948-001/2022|H5N1|20...
1435      006945-002  >A/chicken/Delaware/22-006945-002/2022|H5N1|20...

                                               sequence
718   atggagagaataagagagctaagagatttgatgtcgcaatctcgca...
719   atggagagaataagagagctaagagatttgatgtcgcaatctcgca...
720   atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...
721   atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...
722   atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...
...                                                 ...
1431  atggagagaataaaagagctaagaaatttgatgtcgcaatctcgca...
1432  atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...
1433  atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...
1434  atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...
1435  atggagagaataaaagagctaagagatttgatgtcgcaatctcgca...

[597 rows x 3 columns]], 'A2_HA': [    isolate_partial                                        full_header  \
424      016611-015  >A/gannet/Massachusetts/22-016611-015/2022|H5N...
425      016611-009  >A/gull/Massachusetts/22-016611-009/2022|H5N1|...
426      016611-006  >A/gull/Massachusetts/22-016611-006/2022|H5N1|...
427      020652-001  >A/herring_gull/New_Hampshire/22-020652-001/20...
428      015021-001  >A/herring_gull/New_York/22-015021-001/2022|H5...
..              ...                                                ...
843      010181-001  >A/guinea_fowl/Maine/22-010181-001/2022|H5N1|2...
844      010181-002  >A/goose/Maine/22-010181-002/2022|H5N1|2022-04...
845      008366-001  >A/chicken/Maine/22-008366-001/2022|H5N1|2022-...
846      008064-002  >A/chicken/Maine/22-008064-002/2022|H5N1|2022-...
847      008064-001  >A/guinea_fowl/Maine/22-008064-001/2022|H5N1|2...

                                              sequence
424  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
425  atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
426  atggagaacatagtactacttcttgcaacagtcagccttgttaaaa...
427  atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
428  atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
..                                                 ...
843  atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
844  atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
845  atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
846  atggagaacatagtactacttcttgcaacagttagccttgttaaaa...
847  atggagaacatagtactacttcttgcaacagttagccttgttaaaa...

[417 rows x 3 columns]], 'A2_MP': [    isolate_partial                                        full_header  \
424      016611-015  >A/gannet/Massachusetts/22-016611-015/2022|H5N...
425      016611-009  >A/gull/Massachusetts/22-016611-009/2022|H5N1|...
426      016611-006  >A/gull/Massachusetts/22-016611-006/2022|H5N1|...
427      020652-001  >A/herring_gull/New_Hampshire/22-020652-001/20...
428      015021-001  >A/herring_gull/New_York/22-015021-001/2022|H5...
..              ...                                                ...
843      010181-001  >A/guinea_fowl/Maine/22-010181-001/2022|H5N1|2...
844      010181-002  >A/goose/Maine/22-010181-002/2022|H5N1|2022-04...
845      008366-001  >A/chicken/Maine/22-008366-001/2022|H5N1|2022-...
846      008064-002  >A/chicken/Maine/22-008064-002/2022|H5N1|2022-...
847      008064-001  >A/guinea_fowl/Maine/22-008064-001/2022|H5N1|2...

                                              sequence
424  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
425  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
426  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
427  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
428  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
..                                                 ...
843  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
844  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
845  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
846  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
847  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...

[417 rows x 3 columns]], 'A2_NA': [    isolate_partial                                        full_header  \
424      016611-015  >A/gannet/Massachusetts/22-016611-015/2022|H5N...
425      016611-009  >A/gull/Massachusetts/22-016611-009/2022|H5N1|...
426      016611-006  >A/gull/Massachusetts/22-016611-006/2022|H5N1|...
427      020652-001  >A/herring_gull/New_Hampshire/22-020652-001/20...
428      015021-001  >A/herring_gull/New_York/22-015021-001/2022|H5...
..              ...                                                ...
843      010181-001  >A/guinea_fowl/Maine/22-010181-001/2022|H5N1|2...
844      010181-002  >A/goose/Maine/22-010181-002/2022|H5N1|2022-04...
845      008366-001  >A/chicken/Maine/22-008366-001/2022|H5N1|2022-...
846      008064-002  >A/chicken/Maine/22-008064-002/2022|H5N1|2022-...
847      008064-001  >A/guinea_fowl/Maine/22-008064-001/2022|H5N1|2...

                                              sequence
424  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
425  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
426  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
427  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
428  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
..                                                 ...
843  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
844  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
845  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
846  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
847  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...

[417 rows x 3 columns]], 'A2_NP': [    isolate_partial                                        full_header  \
424      016611-015  >A/gannet/Massachusetts/22-016611-015/2022|H5N...
425      016611-009  >A/gull/Massachusetts/22-016611-009/2022|H5N1|...
426      016611-006  >A/gull/Massachusetts/22-016611-006/2022|H5N1|...
427      020652-001  >A/herring_gull/New_Hampshire/22-020652-001/20...
428      015021-001  >A/herring_gull/New_York/22-015021-001/2022|H5...
..              ...                                                ...
843      010181-001  >A/guinea_fowl/Maine/22-010181-001/2022|H5N1|2...
844      010181-002  >A/goose/Maine/22-010181-002/2022|H5N1|2022-04...
845      008366-001  >A/chicken/Maine/22-008366-001/2022|H5N1|2022-...
846      008064-002  >A/chicken/Maine/22-008064-002/2022|H5N1|2022-...
847      008064-001  >A/guinea_fowl/Maine/22-008064-001/2022|H5N1|2...

                                              sequence
424  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
425  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
426  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
427  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
428  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
..                                                 ...
843  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
844  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
845  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
846  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
847  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...

[417 rows x 3 columns]], 'A2_NS': [    isolate_partial                                        full_header  \
424      016611-015  >A/gannet/Massachusetts/22-016611-015/2022|H5N...
425      016611-009  >A/gull/Massachusetts/22-016611-009/2022|H5N1|...
426      016611-006  >A/gull/Massachusetts/22-016611-006/2022|H5N1|...
427      020652-001  >A/herring_gull/New_Hampshire/22-020652-001/20...
428      015021-001  >A/herring_gull/New_York/22-015021-001/2022|H5...
..              ...                                                ...
843      010181-001  >A/guinea_fowl/Maine/22-010181-001/2022|H5N1|2...
844      010181-002  >A/goose/Maine/22-010181-002/2022|H5N1|2022-04...
845      008366-001  >A/chicken/Maine/22-008366-001/2022|H5N1|2022-...
846      008064-002  >A/chicken/Maine/22-008064-002/2022|H5N1|2022-...
847      008064-001  >A/guinea_fowl/Maine/22-008064-001/2022|H5N1|2...

                                              sequence
424  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
425  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
426  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
427  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...

In [8]:
# If none in one database, only use the other and drop duplicates

# full_dfs = defaultdict(list)
# for key in dfs_andersen.keys():
#     print(key)
# # for key in ["D1.3"]:
#     dataframes = dfs_andersen[key]
#     for i, df in enumerate(dataframes):
#         print(i)
#         try:
#             # full_df = df.merge(dfs_gisaid[key][i], how="outer")
#             # print(full_df)
#             full_df = full_df.drop_duplicates(subset=["isolate_partial"])
#             full_dfs[key].append(full_df)
#         except:
#             print("Failed to merge dataframes in ", key)

## Create FASTA files combining Andersen and GISAID

In [9]:
# Create FASTA files per segment

combined_files = downloads + "Combined_Files/"

os.chdir(combined_files)
for pair in full_dfs.keys():
    print(pair)
    output_path = combined_files + pair + "_combined_" + update_date + ".fasta" 

    output_file = open(output_path, "w")
    for item in full_dfs[pair]:
        # for item in item:
        # item = fasta_files[pair]
        for index, row in item.iterrows():
            name = item.loc[index, "full_header"]
            sequence = item.loc[index, "sequence"]
            # print(name)
        # First is header, second is sequence
        # print(value)
            output_file.write(name)
            output_file.write(sequence)
    output_file.close()

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2