# Cleaning Downloaded Data from avian-flu

Author: Alexander Maksiaev

Purpose: Clean downloaded data from avian-flu, rename sequences according to convention, de-duplicate from GISAID

In [1]:
# Housekeeping

import os
import glob 
import pandas as pd
import xml.etree.ElementTree as ET
import requests
import time
import numpy as np
import dateutil 
from datetime import datetime
from collections import defaultdict 
import importlib
import utils  
importlib.reload(utils)
from utils import * 

# Make sure you have the correct paths

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu"
# downloads = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
originals = downloads + "Andersen_Downloads/"
temp_files = downloads + "Andersen_Temp_Files/"
complete_files = downloads + "Andersen_Complete_Files/"

# Day we're updating data
update_date = "04-14-2025"

os.chdir(downloads)

## Read Metadata

In [2]:
# Read metadata

metadata_folder = originals + "avian-influenza/metadata/"
os.chdir(metadata_folder)

metadata = pd.read_csv("SraRunTable_automated.csv")

# print(len(metadata)) # 7397 rows

# Get rid of missing dates; they won't be counted anyway
for date in metadata["Collection_Date"]:
    if "/" in date or date == "missing":
        metadata = metadata[metadata["Collection_Date"] != date]

# Find only >= 2024 to start
metadata["Collection_Date_Compare"] = metadata["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
metadata = metadata[metadata["Collection_Date_Compare"] >= datetime(2024, 1, 1).strftime("%Y-%m-%d")] # Note that those with only years will default to today

# Find only >= last date using Release Date from metadata 
metadata["ReleaseDate"] = metadata["ReleaseDate"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
metadata = metadata[metadata["ReleaseDate"] >= datetime(2025, 3, 18).strftime("%Y-%m-%d")]

print(len(metadata)) # 6053 rows between 1/1/2024 and 4/14/2025

991

In [3]:
# # Get list of genotypes

# os.chdir(home)

# genotypes_df = pd.read_excel("genotype_key.xlsx")

# genotypes = list(genotypes_df["Genotype"])

# print(genotypes)

### Naming convention ###
>A/[host]/[geo_loc_name]/[isolate]/[year]|[serotype: H5N1]|[collection_date]|[host_type]|[genotype]

host_type is from manual animal reference

In metadata, we have: host, geo_loc_name, isolate, year

We need: geo_loc_name, collection_date, host_type, genotype

host = Host

geo_loc_name (primary) = geo_loc_name

geo_loc_name (secondary) = genbank_mapping.tsv > genbank_name

isolate = isolate

collection date (primary) = Collection_Date

collection date (secondary) = https://www.ncbi.nlm.nih.gov/genbank/ > BioSample (input: BioSample) > Nucleotide > [first result] > collection_date

serotype = serotype

host type = [from ref] 

genotype = [from genoflu] -- use genoflu_results.tsv

## Get genotype, specific geolocation

In [4]:
# Get genotype from genoflu_results.tsv

os.chdir(metadata_folder)

genoflu_results = pd.read_csv("genoflu_results.tsv", delimiter="\t")

metadata["Genotype"] = genoflu_results["Genotype"]
metadata = metadata[~metadata["Genotype"].str.contains('Not assigned')] # Do not include non-assigned genotypes

# Get only the genotypes we want: B3.13 and D1.1

b313_and_d11_only = genoflu_results[(genoflu_results["Genotype"] == "B3.13") | (genoflu_results["Genotype"] == "D1.1")]
b313_and_d11_only = b313_and_d11_only.rename(columns={"sample": "Run"})
b313_and_d11_only = b313_and_d11_only.drop_duplicates(subset="Run", keep="last")

metadata = metadata.merge(b313_and_d11_only, on=["Run", "Genotype"], how="inner")

print(len(metadata)) 

display(metadata)

303

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,retraction_detection_date_utc,Collection_Date_Compare,Genotype,date,File Name,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List
0,SRR32804537,WGS,148.60,157337234,PRJNA1207547,SAMN47505727,Viral,55371987,USDA-NVSL,2025,...,NaN,2025-04-22,D1.1,2025-04-08_16-17-04,SRR32804537.fa,"PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...","am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...","99.87%, 99.34%, 99.49%, 99.35%, 99.80%, 98.85%...","3, 15, 9, 11, 3, 11, 1, 7",Ran on FASTA - No Coverage Report
1,SRR32804540,WGS,146.83,125026759,PRJNA1207547,SAMN47505724,Viral,45700705,USDA-NVSL,2025,...,NaN,2025-04-22,D1.1,2025-04-08_16-17-07,SRR32804540.fa,"PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...","am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...","99.69%, 99.39%, 99.83%, 99.41%, 99.67%, 99.42%...","7, 11, 3, 10, 5, 6, 0, 10",Ran on FASTA - No Coverage Report
2,SRR32804544,WGS,145.13,75849086,PRJNA1207547,SAMN47505721,Viral,27735348,USDA-NVSL,2025,...,NaN,2025-04-22,D1.1,2025-04-08_16-17-10,SRR32804544.fa,"PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...","am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...","99.69%, 99.50%, 99.60%, 99.65%, 99.60%, 99.05%...","7, 9, 7, 6, 6, 10, 2, 10",Ran on FASTA - No Coverage Report
3,SRR32804545,WGS,148.43,284460923,PRJNA1207547,SAMN47505720,Viral,98766118,USDA-NVSL,2025,...,NaN,2025-04-22,D1.1,2025-04-08_16-17-11,SRR32804545.fa,"PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...","am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...","99.87%, 99.39%, 99.77%, 99.41%, 99.67%, 99.11%...","3, 11, 5, 10, 5, 10, 0, 9",Ran on FASTA - No Coverage Report
4,SRR32804546,WGS,148.88,213319278,PRJNA1207547,SAMN47505719,Viral,74543339,USDA-NVSL,2025,...,NaN,2025-04-22,D1.1,2025-04-08_16-17-12,SRR32804546.fa,"PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...","am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...","99.83%, 99.40%, 99.83%, 99.47%, 99.73%, 99.42%...","4, 11, 3, 9, 4, 6, 0, 9",Ran on FASTA - No Coverage Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,SRR33029747,WGS,147.87,245673050,PRJNA980729,SAMN47843702,Viral,85653750,USDA-NVSL,2025,...,NaN,2025-04-22,D1.1,2025-04-11_06-46-48,SRR33029747.fa,"PB1:ea3, MP:ea3, NA:am4N1, NS:ea3, NP:am13, PA...","ea3:22-013001-001:PB1, ea3:22-013001-001:MP, a...","99.45%, 99.80%, 99.42%, 98.93%, 99.60%, 98.56%...","10, 2, 6, 9, 6, 31, 8, 9",Ran on FASTA - No Coverage Report
299,SRR33029749,WGS,147.88,167615693,PRJNA980729,SAMN47843700,Viral,58998925,USDA-NVSL,2025,...,NaN,2025-04-22,D1.1,2025-04-11_06-46-48,SRR33029749.fa,"PA:am4, NA:am4N1, HA:ea3, NS:ea3, PB1:ea3, MP:...","am4:24-030039-001:PA, am4N1:24-030039-001:NA, ...","98.37%, 99.42%, 99.53%, 98.93%, 99.39%, 99.80%...","35, 6, 8, 9, 11, 2, 9, 6",Ran on FASTA - No Coverage Report
300,SRR33029750,WGS,146.73,95329644,PRJNA980729,SAMN47843699,Viral,33874309,USDA-NVSL,2025,...,NaN,2025-04-22,D1.1,2025-04-11_06-46-48,SRR33029750.fa,"HA:ea3, NA:am4N1, NS:ea3, PB1:ea3, NP:am13, MP...","ea3:22-013001-001:HA, am4N1:24-030039-001:NA, ...","99.53%, 99.42%, 98.93%, 99.44%, 99.60%, 99.80%...","8, 6, 9, 10, 6, 2, 9, 9",Ran on FASTA - No Coverage Report
301,SRR33029751,WGS,146.12,269328456,PRJNA980729,SAMN47843690,Viral,99122459,USDA-NVSL,2025,...,NaN,2025-04-22,D1.1,2025-04-11_06-46-49,SRR33029751.fa,"PA:am4, HA:ea3, NP:am13, MP:ea3, PB2:am24, PB1...","am4:24-030039-001:PA, ea3:22-013001-001:HA, am...","99.30%, 99.06%, 99.73%, 100.00%, 99.74%, 99.12...","15, 16, 4, 0, 6, 20, 10, 7",Ran on FASTA - No Coverage Report
302,SRR33029752,WGS,145.33,270721593,PRJNA980729,SAMN47843689,Viral,99238613,USDA-NVSL,2025,...,NaN,2025-04-22,D1.1,2025-04-11_06-46-48,SRR33029752.fa,"NP:am13, NA:am4N1, PA:am4, PB1:ea3, PB2:am24, ...","am13:24-030039-001:NP, am4N1:24-030039-001:NA,...","99.73%, 99.14%, 99.43%, 99.12%, 99.74%, 100.00...","4, 8, 10, 20, 6, 0, 16, 10",Ran on FASTA - No Coverage Report

In [ ]:
# # Get specific geolocation from genbank_mapping.tsv

# genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
# genbank_mapping["Run"] = genbank_mapping["sra_run"]
# genbank_mapping = genbank_mapping.drop_duplicates(subset="Run", keep="first") # Drop duplicates
# genbank_mapping["name_state"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[2]) # Get the name of the state

# print(genbank_mapping)

# metadata_genbank = metadata.merge(genbank_mapping, on=["Run"]) # Only include data that has states

# print(genbank_mapping["name_state"])
# print(len(metadata_genbank))
# display(metadata_genbank) # Maybe there is no state information since 3/18/2025?

                    seg_file  \
0      SRR28752446_HA_cns.fa
8      SRR28752447_HA_cns.fa
16     SRR28752448_HA_cns.fa
24     SRR28752449_HA_cns.fa
32     SRR28752450_HA_cns.fa
...                      ...
38678  SRR32654211_HA_cns.fa
38686  SRR32654212_HA_cns.fa
38694  SRR32654213_HA_cns.fa
38702  SRR32654214_HA_cns.fa
38710  SRR32654216_HA_cns.fa

                                            seg_seq_name      sra_run seg  \
0      Consensus_SRR28752446_HA_cns_threshold_0.5_qua...  SRR28752446  HA
8      Consensus_SRR28752447_HA_cns_threshold_0.5_qua...  SRR28752447  HA
16     Consensus_SRR28752448_HA_cns_threshold_0.5_qua...  SRR28752448  HA
24     Consensus_SRR28752449_HA_cns_threshold_0.5_qua...  SRR28752449  HA
32     Consensus_SRR28752450_HA_cns_threshold_0.5_qua...  SRR28752450  HA
...                                                  ...          ...  ..
38678  Consensus_SRR32654211_HA_cns_threshold_0.5_qua...  SRR32654211  HA
38686  Consensus_SRR32654212_HA_cns_threshold_0.5_qua...  SRR32654212  HA
38694  Consensus_SRR32654213_HA_cns_threshold_0.5_qua...  SRR32654213  HA
38702  Consensus_SRR32654214_HA_cns_threshold_0.5_qua...  SRR32654214  HA
38710  Consensus_SRR32654216_HA_cns_threshold_0.5_qua...  SRR32654216  HA

      genbank_acc  genbank_seg                              genbank_name  \
0      PP740722.1            4      A/blackbird/Texas/24-008354-001/2024
8      PP752829.1            4         A/cattle/Texas/24-009108-005/2024
16     PP752821.1            4         A/cattle/Texas/24-009108-004/2024
24     PP752813.1            4         A/cattle/Texas/24-009108-003/2024
32     PP752805.1            4         A/cattle/Texas/24-009108-002/2024
...           ...          ...                                       ...
38678  PV338372.1            4   A/Turkey/OH/25-003389-002-original/2025
38686  PV339220.1            4  A/chicken/OH/25-003389-001-original/2025
38694  PV338364.1            4   A/Turkey/OH/25-003388-002-original/2025
38702  PV338092.1            4   A/Turkey/OH/25-002649-002-original/2025
38710  PV338484.1            4      A/cat/MT/24-006142-001-original/2023

               Run name_state
0      SRR28752446      Texas
8      SRR28752447      Texas
16     SRR28752448      Texas
24     SRR28752449      Texas
32     SRR28752450      Texas
...            ...        ...
38678  SRR32654211         OH
38686  SRR32654212         OH
38694  SRR32654213         OH
38702  SRR32654214         OH
38710  SRR32654216         MT

[4279 rows x 9 columns]
0        Texas
8        Texas
16       Texas
24       Texas
32       Texas
         ...
38678       OH
38686       OH
38694       OH
38702       OH
38710       MT
Name: name_state, Length: 4279, dtype: object
0

Empty DataFrame
Columns: [Run, Assay Type, AvgSpotLen, Bases, BioProject, BioSample, BioSampleModel, Bytes, Center Name, Collection_Date, Consent, DATASTORE filetype, DATASTORE provider, DATASTORE region, Experiment, geo_loc_name_country, geo_loc_name_country_continent, geo_loc_name, Host, Instrument, isolate, Library Name, LibraryLayout, LibrarySelection, LibrarySource, Organism, Platform, ReleaseDate, create_date, version, Sample Name, SRA Study, serotype, isolation_source, BioSample Accession, is_retracted, retraction_detection_date_utc, Collection_Date_Compare, Genotype, date, File Name, Genotype List Used, >=98.0%, Genotype Sample Title List, Genotype Percent Match List, Genotype Mismatch List, Genotype Average Depth of Coverage List, seg_file, seg_seq_name, sra_run, seg, genbank_acc, genbank_seg, genbank_name, name_state]
Index: []

[0 rows x 54 columns]

In [ ]:
# If no states

metadata_genbank = metadata

metadata_genbank["name_state"] = "USA"

## Get and save collection date

In [7]:

# Get all dates
metadata_genbank["Collection_Date_Specific"] = metadata_genbank["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank))

# Save this so we don't have to do it again

os.chdir(temp_files)
metadata_genbank.to_csv("metadata_genbank.csv")

SAMN47505727
Unable to find collection date.
SAMN47505724
Unable to find collection date.
SAMN47505721
Unable to find collection date.
SAMN47505720
Unable to find collection date.
SAMN47505719
Unable to find collection date.
SAMN47505712
Unable to find collection date.
SAMN47505711
Unable to find collection date.
SAMN47505706
Unable to find collection date.
SAMN47505705
Unable to find collection date.
SAMN47505700
Unable to find collection date.
SAMN47505695
Unable to find collection date.
SAMN47505687
Unable to find collection date.
SAMN47505686
Unable to find collection date.
SAMN47505684
Unable to find collection date.
SAMN47505681
Unable to find collection date.
SAMN47505676
Unable to find collection date.
SAMN47505636
Unable to find collection date.
SAMN47505671
Unable to find collection date.
SAMN47505669
Unable to find collection date.
SAMN47505666
Unable to find collection date.
SAMN47505653
Unable to find collection date.
SAMN47505647
Unable to find collection date.
SAMN47505764
Unable to find collection date.
SAMN47505762
Unable to find collection date.
SAMN47505645
Unable to find collection date.
SAMN47505756
Unable to find collection date.
SAMN47505732
Unable to find collection date.
SAMN47505611
Unable to find collection date.
SAMN47505609
Unable to find collection date.
SAMN47505608
Unable to find collection date.
SAMN47505606
Unable to find collection date.
SAMN47505605
Unable to find collection date.
SAMN47505631
Unable to find collection date.
SAMN47505630
Unable to find collection date.
SAMN47505629
Unable to find collection date.
SAMN47505628
Unable to find collection date.
SAMN47505626
Unable to find collection date.
SAMN47505625
Unable to find collection date.
SAMN47505623
Unable to find collection date.
SAMN47505621
Unable to find collection date.
SAMN47505619
Unable to find collection date.
SAMN47505618
Unable to find collection date.
SAMN47505616
Unable to find collection date.
SAMN47505615
Unable to find collection date.
SAMN47505613
Unable to find collection date.
SAMN47505603
Unable to find collection date.
SAMN47505498
Unable to find collection date.
SAMN47505537
Unable to find collection date.
SAMN47505536
Unable to find collection date.
SAMN47505526
Unable to find collection date.
SAMN47505525
Unable to find collection date.
SAMN47505496
Unable to find collection date.
SAMN47505513
Unable to find collection date.
SAMN47505504
Unable to find collection date.
SAMN47505493
Unable to find collection date.
SAMN47586751
Unable to find collection date.
SAMN47586748
Unable to find collection date.
SAMN47586684
Unable to find collection date.
SAMN47586729
Unable to find collection date.
SAMN47586727
Unable to find collection date.
SAMN47586725
Unable to find collection date.
SAMN47586866
Unable to find collection date.
SAMN47586862
Unable to find collection date.
SAMN47586854
Unable to find collection date.
SAMN47586850
Unable to find collection date.
SAMN47586847
Unable to find collection date.
SAMN47586845
Unable to find collection date.
SAMN47586839
Unable to find collection date.
SAMN47586838
Unable to find collection date.
SAMN47586893
Unable to find collection date.
SAMN47586890
Unable to find collection date.
SAMN47586885
Unable to find collection date.
SAMN47586879
Unable to find collection date.
SAMN47586878
Unable to find collection date.
SAMN47586874
Unable to find collection date.
SAMN47586869
Unable to find collection date.
SAMN47586697
Unable to find collection date.
SAMN47586867
Unable to find collection date.
SAMN47586830
Unable to find collection date.
SAMN47586693
Unable to find collection date.
SAMN47586823
Unable to find collection date.
SAMN47586820
Unable to find collection date.
SAMN47586692
Unable to find collection date.
SAMN47586817
Unable to find collection date.
SAMN47586813
Unable to find collection date.
SAMN47586810
Unable to find collection date.
SAMN47586776
Unable to find collection date.
SAMN47586774
Unable to find collection date.
SAMN47586771
Unable to find collection date.
SAMN47586766
Unable to find collection date.
SAMN47586764
Unable to find collection date.
SAMN47586763
Unable to find collection date.
SAMN47586762
Unable to find collection date.
SAMN47586760
Unable to find collection date.
SAMN47586721
Unable to find collection date.
SAMN47586714
Unable to find collection date.
SAMN47586711
Unable to find collection date.
SAMN47586709
Unable to find collection date.
SAMN47586708
Unable to find collection date.
SAMN47586704
Unable to find collection date.
SAMN47586703
Unable to find collection date.
SAMN47586899
Unable to find collection date.
SAMN47586804
Unable to find collection date.
SAMN47586690
Unable to find collection date.
SAMN47586796
Unable to find collection date.
SAMN47586794
Unable to find collection date.
SAMN47586791
Unable to find collection date.
SAMN47586790
Unable to find collection date.
SAMN47586789
Unable to find collection date.
SAMN47586689
Unable to find collection date.
SAMN47586785
Unable to find collection date.
SAMN47586784
Unable to find collection date.
SAMN47586779
Unable to find collection date.
SAMN47586688
Unable to find collection date.
SAMN47586630
Unable to find collection date.
SAMN47586628
Unable to find collection date.
SAMN47586676
Unable to find collection date.
SAMN47586675
Unable to find collection date.
SAMN47586627
Unable to find collection date.
SAMN47586671
Unable to find collection date.
SAMN47586670
Unable to find collection date.
SAMN47586669
Unable to find collection date.
SAMN47586667
Unable to find collection date.
SAMN47586666
Unable to find collection date.
SAMN47586664
Unable to find collection date.
SAMN47586663
Unable to find collection date.
SAMN47586662
Unable to find collection date.
SAMN47586660
Unable to find collection date.
SAMN47586654
Unable to find collection date.
SAMN47586653
Unable to find collection date.
SAMN47586625
Unable to find collection date.
SAMN47586651
Unable to find collection date.
SAMN47586647
Unable to find collection date.
SAMN47586646
Unable to find collection date.
SAMN47586638
Unable to find collection date.
SAMN47586634
Unable to find collection date.
SAMN47586633
Unable to find collection date.
SAMN47586632
Unable to find collection date.
SAMN47586623
Unable to find collection date.
SAMN47586963
Unable to find collection date.
SAMN47586960
Unable to find collection date.
SAMN47586955
Unable to find collection date.
SAMN47586953
Unable to find collection date.
SAMN47586944
Unable to find collection date.
SAMN47586906
Unable to find collection date.
SAMN47586939
Unable to find collection date.
SAMN47586936
Unable to find collection date.
SAMN47586933
Unable to find collection date.
SAMN47586932
Unable to find collection date.
SAMN47586931
Unable to find collection date.
SAMN47586928
Unable to find collection date.
SAMN47586923
Unable to find collection date.
SAMN47586922
Unable to find collection date.
SAMN47586917
Unable to find collection date.
SAMN47777887
Unable to find collection date.
SAMN47777776
Unable to find collection date.
SAMN47777775
Unable to find collection date.
SAMN47777829
Unable to find collection date.
SAMN47777828
Unable to find collection date.
SAMN47777809
Unable to find collection date.
SAMN47777808
Unable to find collection date.
SAMN47777767
Unable to find collection date.
SAMN47777765
Unable to find collection date.
SAMN47777763
Unable to find collection date.
SAMN47777744
Unable to find collection date.
SAMN47777885
Unable to find collection date.
SAMN47777883
Unable to find collection date.
SAMN47777882
Unable to find collection date.
SAMN47777877
Unable to find collection date.
SAMN47777841
Unable to find collection date.
SAMN47777832
Unable to find collection date.
SAMN47777751
Unable to find collection date.
SAMN47777871
Unable to find collection date.
SAMN47777868
Unable to find collection date.
SAMN47777862
Unable to find collection date.
SAMN47777858
Unable to find collection date.
SAMN47777843
Unable to find collection date.
SAMN47777675
Unable to find collection date.
SAMN47777674
Unable to find collection date.
SAMN47777671
Unable to find collection date.
SAMN47777665
Unable to find collection date.
SAMN47777664
Unable to find collection date.
SAMN47777592
Unable to find collection date.
SAMN47777662
Unable to find collection date.
SAMN47777661
Unable to find collection date.
SAMN47777658
Unable to find collection date.
SAMN47777657
Unable to find collection date.
SAMN47777655
Unable to find collection date.
SAMN47777654
Unable to find collection date.
SAMN47777591
Unable to find collection date.
SAMN47777652
Unable to find collection date.
SAMN47777650
Unable to find collection date.
SAMN47777649
Unable to find collection date.
SAMN47777648
Unable to find collection date.
SAMN47777647
Unable to find collection date.
SAMN47777645
Unable to find collection date.
SAMN47777640
Unable to find collection date.
SAMN47777639
Unable to find collection date.
SAMN47777638
Unable to find collection date.
SAMN47777636
Unable to find collection date.
SAMN47777635
Unable to find collection date.
SAMN47777634
Unable to find collection date.
SAMN47777631
Unable to find collection date.
SAMN47777626
Unable to find collection date.
SAMN47777588
Unable to find collection date.
SAMN47777623
Unable to find collection date.
SAMN47777622
Unable to find collection date.
SAMN47777621
Unable to find collection date.
SAMN47777619
Unable to find collection date.
SAMN47777618
Unable to find collection date.
SAMN47777616
Unable to find collection date.
SAMN47777615
Unable to find collection date.
SAMN47777587
Unable to find collection date.
SAMN47777611
Unable to find collection date.
SAMN47777609
Unable to find collection date.
SAMN47777608
Unable to find collection date.
SAMN47777607
Unable to find collection date.
SAMN47777606
Unable to find collection date.
SAMN47777604
Unable to find collection date.
SAMN47777586
Unable to find collection date.
SAMN47777602
Unable to find collection date.
SAMN47777601
Unable to find collection date.
SAMN47777600
Unable to find collection date.
SAMN47777599
Unable to find collection date.
SAMN47777598
Unable to find collection date.
SAMN47777715
Unable to find collection date.
SAMN47777714
Unable to find collection date.
SAMN47777684
Unable to find collection date.
SAMN47777594
Unable to find collection date.
SAMN47777585
Unable to find collection date.
SAMN47777597
Unable to find collection date.
SAMN47777712
Unable to find collection date.
SAMN47777709
Unable to find collection date.
SAMN47777706
Unable to find collection date.
SAMN47777705
Unable to find collection date.
SAMN47777596
Unable to find collection date.
SAMN47777703
Unable to find collection date.
SAMN47777702
Unable to find collection date.
SAMN47777700
Unable to find collection date.
SAMN47777699
Unable to find collection date.
SAMN47777697
Unable to find collection date.
SAMN47777595
Unable to find collection date.
SAMN47777693
Unable to find collection date.
SAMN47777692
Unable to find collection date.
SAMN47777690
Unable to find collection date.
SAMN47777689
Unable to find collection date.
SAMN47777688
Unable to find collection date.
SAMN47777687
Unable to find collection date.
SAMN47777686
Unable to find collection date.
SAMN47777583
Unable to find collection date.
SAMN47777575
Unable to find collection date.
SAMN47777573
Unable to find collection date.
SAMN47777571
Unable to find collection date.
SAMN47777568
Unable to find collection date.
SAMN47777567
Unable to find collection date.
SAMN47777563
Unable to find collection date.
SAMN47777562
Unable to find collection date.
SAMN47843961
Unable to find collection date.
SAMN47843960
Unable to find collection date.
SAMN47843959
Unable to find collection date.
SAMN47843958
Unable to find collection date.
SAMN47843957
Unable to find collection date.
SAMN47843956
Unable to find collection date.
SAMN47843893
Unable to find collection date.
SAMN47843955
Unable to find collection date.
SAMN47843954
Unable to find collection date.
SAMN47843952
Unable to find collection date.
SAMN47843951
Unable to find collection date.
SAMN47843950
Unable to find collection date.
SAMN47843949
Unable to find collection date.
SAMN47843920
Unable to find collection date.
SAMN47843919
Unable to find collection date.
SAMN47843918
Unable to find collection date.
SAMN47843917
Unable to find collection date.
SAMN47843916
Unable to find collection date.
SAMN47843889
Unable to find collection date.
SAMN47843915
Unable to find collection date.
SAMN47843914
Unable to find collection date.
SAMN47843913
Unable to find collection date.
SAMN47843912
Unable to find collection date.
SAMN47843911
Unable to find collection date.
SAMN47843910
Unable to find collection date.
SAMN47843909
Unable to find collection date.
SAMN47843908
Unable to find collection date.
SAMN47843907
Unable to find collection date.
SAMN47843904
Unable to find collection date.
SAMN47843903
Unable to find collection date.
SAMN47843902
Unable to find collection date.
SAMN47843901
Unable to find collection date.
SAMN47843900
Unable to find collection date.
SAMN47843887
Unable to find collection date.
SAMN47843886
Unable to find collection date.
SAMN47843697
Unable to find collection date.
SAMN47843696
Unable to find collection date.
SAMN47843693
Unable to find collection date.
SAMN47843692
Unable to find collection date.
SAMN47843691
Unable to find collection date.
SAMN47843703
Unable to find collection date.
SAMN47843702
Unable to find collection date.
SAMN47843700
Unable to find collection date.
SAMN47843699
Unable to find collection date.
SAMN47843690
Unable to find collection date.
SAMN47843689
Unable to find collection date.

In [8]:
# # Upload saved data -- if doing this, make sure the above cell is commented out
# os.chdir(temp_files + "saved/")
# metadata_genbank = pd.read_csv("metadata_genbank_4-18-2025.csv")
# os.chdir(temp_files)

# # Get only updated dates

# unknown_dates = metadata_genbank[(metadata_genbank["Collection_Date_Specific"] == "2024") | (metadata_genbank["Collection_Date_Specific"] == "2025")] # Dates we don't have
# known_dates = metadata_genbank[(metadata_genbank["Collection_Date_Specific"] != "2024") & (metadata_genbank["Collection_Date_Specific"] != "2025")] # Dates we've already gotten

# # Get new dates also 
# # new_dates = metadata_genbank["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank) if )

# updated_unknown_dates = unknown_dates["BioSample"].apply(lambda x: search_collection_date(x, unknown_dates)) # Update unknown dates, if possible

# metadata_genbank = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # Remove pre-2024 dates

# metadata_genbank["Collection_Date_Compare"] = metadata_genbank["Collection_Date_Specific"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
# metadata_genbank = metadata_genbank[metadata_genbank["Collection_Date_Compare"] >= datetime(2024, 1, 1).strftime("%Y-%m-%d")]

# print(metadata_genbank[["Collection_Date_Specific"]])

# display(metadata_genbank)

## Get host type

In [9]:
# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genbank)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

os.chdir(downloads)

animals_ref = pd.read_csv("animals_ref.csv") # Upload animals ref

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['great horned owl', 'bald eagle', 'guineafowl', 'vulture', 'herring gull', 'cattle', 'falco peregrinus', 'red-shouldered hawk', 'black vulture', 'barn owl', 'falcon', 'sparrow', 'cackling goose', 'duck', 'merganser', 'cat', 'chicken', 'pet food', 'dolphin', 'quail', 'mallard', 'bufflehead', 'common eider', 'goose', 'american black duck', "cooper's hawk", 'common raven', 'bear', 'great black-backed gull', 'turkey', 'turkey vulture', 'skunk', 'snow goose', 'trumpeter swan', 'red-breasted merganser', 'canada goose', 'swan', 'red-tailed hawk', 'common merganser', 'snowy owl']
['falco peregrinus', 'common eider', 'great black-backed gull', 'common merganser']
                 avian               cattle        feline   other_mammal  \
0     great_horned_owl            dairy_cow           cat         bobcat
1         common_raven               cattle  domestic_cat    house_mouse
2        cooper's_hawk  cattle milk product     feral_cat          skunk
3         coopers_hawk                  NaN        feline         cougar
4              peafowl                  NaN  domestic-cat  geoffroys_cat
..                 ...                  ...           ...            ...
284        guinea fowl                  NaN           NaN            NaN
285    red tailed hawk                  NaN           NaN            NaN
286  western sandpiper                  NaN           NaN            NaN
287       ganada goose                  NaN           NaN            NaN
288        harris hawk                  NaN           NaN            NaN

          human         other                      new
0    washington         mixed         falco peregrinus
1        nevada   environment             common eider
2       wyoming  multispecies  great black-backed gull
3    california      pet food         common merganser
4      michigan  raw pet food                      NaN
..          ...           ...                      ...
284         NaN           NaN                      NaN
285         NaN           NaN                      NaN
286         NaN           NaN                      NaN
287         NaN           NaN                      NaN
288         NaN           NaN                      NaN

[289 rows x 7 columns]

In [10]:
# Get animals from animal reference
os.chdir(downloads)
animals_ref = pd.read_csv("animals_ref.csv")
fix_animals_andersen(metadata_genbank, animals_ref) # Get host type

metadata_genbank["years"] = metadata_genbank["Collection_Date"].apply(lambda x: str(x).split("-")[0]) # Get year only from collection date

## Make names using all the attributes we collected

In [11]:
for num, collection_date in enumerate(metadata_genbank["Collection_Date_Specific"]):
    if collection_date != collection_date: # If nan
        metadata_genbank.loc[num, "Collection_Date_Specific"] = metadata_genbank.loc[num, "years"]
    else: # If actual date
        if len(str(collection_date)) == 4: # If it's a year
            # print("caught")
            metadata_genbank.loc[num, "Collection_Date_Specific"] = collection_date
        else:
            parsed_date = dateutil.parser.parse(collection_date)
            date = parsed_date.strftime("%Y-%m-%d") # Make sure it doesn't default to today, if just a year
            metadata_genbank.loc[num, "Collection_Date_Specific"] = date

# Make names

names = ">A/" + metadata_genbank["Host"] + "/" + metadata_genbank["name_state"] + "/" + metadata_genbank["isolate"] + "/" + metadata_genbank["years"].apply(lambda x: str(x)) + "|H5N1|" + metadata_genbank["Collection_Date_Specific"].apply(lambda x: str(x)) + "|" + metadata_genbank["Host_Type"] + "|" + metadata_genbank["Genotype"]

metadata_genbank["Name"] = names

# metadata_genbank.to_csv("metadata_genbank_named.csv")

# display(metadata_genbank)

In [12]:
print(metadata_genbank)

             Run Assay Type  AvgSpotLen      Bases    BioProject  \
0    SRR32804537        WGS      148.60  157337234  PRJNA1207547
1    SRR32804540        WGS      146.83  125026759  PRJNA1207547
2    SRR32804544        WGS      145.13   75849086  PRJNA1207547
3    SRR32804545        WGS      148.43  284460923  PRJNA1207547
4    SRR32804546        WGS      148.88  213319278  PRJNA1207547
..           ...        ...         ...        ...           ...
298  SRR33029747        WGS      147.87  245673050   PRJNA980729
299  SRR33029749        WGS      147.88  167615693   PRJNA980729
300  SRR33029750        WGS      146.73   95329644   PRJNA980729
301  SRR33029751        WGS      146.12  269328456   PRJNA980729
302  SRR33029752        WGS      145.33  270721593   PRJNA980729

        BioSample BioSampleModel     Bytes Center Name Collection_Date  ...  \
0    SAMN47505727          Viral  55371987   USDA-NVSL            2025  ...
1    SAMN47505724          Viral  45700705   USDA-NVSL            2025  ...
2    SAMN47505721          Viral  27735348   USDA-NVSL            2025  ...
3    SAMN47505720          Viral  98766118   USDA-NVSL            2025  ...
4    SAMN47505719          Viral  74543339   USDA-NVSL            2025  ...
..            ...            ...       ...         ...             ...  ...
298  SAMN47843702          Viral  85653750   USDA-NVSL            2025  ...
299  SAMN47843700          Viral  58998925   USDA-NVSL            2025  ...
300  SAMN47843699          Viral  33874309   USDA-NVSL            2025  ...
301  SAMN47843690          Viral  99122459   USDA-NVSL            2025  ...
302  SAMN47843689          Viral  99238613   USDA-NVSL            2025  ...

                           Genotype List Used, >=98.0%  \
0    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
2    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
..                                                 ...
298  PB1:ea3, MP:ea3, NA:am4N1, NS:ea3, NP:am13, PA...
299  PA:am4, NA:am4N1, HA:ea3, NS:ea3, PB1:ea3, MP:...
300  HA:ea3, NA:am4N1, NS:ea3, PB1:ea3, NP:am13, MP...
301  PA:am4, HA:ea3, NP:am13, MP:ea3, PB2:am24, PB1...
302  NP:am13, NA:am4N1, PA:am4, PB1:ea3, PB2:am24, ...

                            Genotype Sample Title List  \
0    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
..                                                 ...
298  ea3:22-013001-001:PB1, ea3:22-013001-001:MP, a...
299  am4:24-030039-001:PA, am4N1:24-030039-001:NA, ...
300  ea3:22-013001-001:HA, am4N1:24-030039-001:NA, ...
301  am4:24-030039-001:PA, ea3:22-013001-001:HA, am...
302  am13:24-030039-001:NP, am4N1:24-030039-001:NA,...

                           Genotype Percent Match List  \
0    99.87%, 99.34%, 99.49%, 99.35%, 99.80%, 98.85%...
1    99.69%, 99.39%, 99.83%, 99.41%, 99.67%, 99.42%...
2    99.69%, 99.50%, 99.60%, 99.65%, 99.60%, 99.05%...
3    99.87%, 99.39%, 99.77%, 99.41%, 99.67%, 99.11%...
4    99.83%, 99.40%, 99.83%, 99.47%, 99.73%, 99.42%...
..                                                 ...
298  99.45%, 99.80%, 99.42%, 98.93%, 99.60%, 98.56%...
299  98.37%, 99.42%, 99.53%, 98.93%, 99.39%, 99.80%...
300  99.53%, 99.42%, 98.93%, 99.44%, 99.60%, 99.80%...
301  99.30%, 99.06%, 99.73%, 100.00%, 99.74%, 99.12...
302  99.73%, 99.14%, 99.43%, 99.12%, 99.74%, 100.00...

         Genotype Mismatch List Genotype Average Depth of Coverage List  \
0     3, 15, 9, 11, 3, 11, 1, 7       Ran on FASTA - No Coverage Report
1     7, 11, 3, 10, 5, 6, 0, 10       Ran on FASTA - No Coverage Report
2      7, 9, 7, 6, 6, 10, 2, 10       Ran on FASTA - No Coverage Report
3     3, 11, 5, 10, 5, 10, 0, 9       Ran on FASTA - No Coverage Report
4       4, 11, 3, 9, 4, 6, 0, 9       Ran on FASTA - No Coverage Report
..                          ...                                     ...
298    10, 2, 6, 9, 6, 31, 8, 9       Ran on FASTA - No Coverage Report
299    35, 6, 8, 9, 11, 2, 9, 6       Ran on FASTA - No Coverage Report
300     8, 6, 9, 10, 6, 2, 9, 9       Ran on FASTA - No Coverage Report
301  15, 16, 4, 0, 6, 20, 10, 7       Ran on FASTA - No Coverage Report
302  4, 8, 10, 20, 6, 0, 16, 10       Ran on FASTA - No Coverage Report

    name_state Collection_Date_Specific Host_Type years  \
0      unknown                     2025     avian  2025
1      unknown                     2025     avian  2025
2      unknown                     2025     avian  2025
3      unknown                     2025     avian  2025
4      unknown                     2025     avian  2025
..         ...                      ...       ...   ...
298    unknown                     2025     avian  2025
299    unknown                     2025     avian  2025
300    unknown                     2025     avian  2025
301    unknown                     2025     avian  2025
302    unknown                     2025     avian  2025

                                                  Name
0    >A/GREAT HORNED OWL/unknown/25-006998-001/2025...
1    >A/BALD EAGLE/unknown/25-006941-001/2025|H5N1|...
2    >A/CANADA GOOSE/unknown/25-006940-002/2025|H5N...
3    >A/BALD EAGLE/unknown/25-006940-001/2025|H5N1|...
4    >A/RED-TAILED HAWK/unknown/25-006939-002/2025|...
..                                                 ...
298  >A/DUCK/unknown/25-010293-004/2025|H5N1|2025|a...
299  >A/CHICKEN/unknown/25-010293-002/2025|H5N1|202...
300  >A/CHICKEN/unknown/25-010293-001/2025|H5N1|202...
301  >A/CHICKEN/unknown/25-009496-002/2025|H5N1|202...
302  >A/CHICKEN/unknown/25-009496-001/2025|H5N1|202...

[303 rows x 51 columns]

## Make FASTA files

In [13]:
# Get information to create the fasta files

fasta_folder = originals + "avian-influenza/fasta/"

os.chdir(fasta_folder)

segments = ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]
pairs = []
fasta_files = {}

for genotype in ["B3.13", "D1.1"]:
    for segment in segments:
        pair = genotype + "_" + segment
        pairs.append(pair)

for pair in pairs:
    fasta_files[pair] = [] # List to hold fasta files

for run in metadata_genbank["Run"].values: # For each run 
    for dirpath, dirs, files in os.walk(fasta_folder): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            # print(file_name)
            if run in file_name: # Note that there will be ~8 files total with that run name
                # Make a fasta file and put it in the list
                with open(file_name) as f:
                    lines = f.readlines()
                    sequence = lines[1] 
                    # Each run/segment pair has one sequence -- it's placed into a file with other run/segment pairs with the same segment and genotype
                    header = metadata_genbank[metadata_genbank["Run"] == run].loc[:, "Name"].values[0]
                    genotype = metadata_genbank[metadata_genbank["Run"] == run].loc[:, "Genotype"].values[0]
                    # print(header)
                    # print(genotype)
                    # break 
                    segment = file_name.split("_")[-2]
                    # Find the pair that corresponds to 
                    pair_name = genotype + "_" + segment
                    this_specific_fasta = []
                    for pair in pairs:
                        # print(pair)
                        # print(pair_name)
                        if pair_name == pair:
                            this_specific_fasta.append(header)
                            this_specific_fasta.append(sequence)
                            fasta_files[pair].append(this_specific_fasta)
                f.close()
        break

In [14]:
# Create fasta files 

os.chdir(temp_files)

for pair in fasta_files.keys():
    output_path = temp_files + pair + "_andersen_" + update_date + ".fasta" 

    output_file = open(output_path, "w")
    for item in fasta_files[pair]:
        # for item in item:
        # item = fasta_files[pair]
        try:
            name = str(item[0].values[0]) # See if this is one we didn't have a collection date for
        except:
            name = str(item[0])
        print(name)
        # First is header, second is sequence
        # print(value)
        output_file.write(name + "\n")
        output_file.write(item[1])
    output_file.close()

>A/CAT/unknown/25-005779-001/2025|H5N1|2025|feline|B3.13
>A/CATTLE/unknown/25-007943-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007915-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007201-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007185-006/2025|H5N1|2025|cattle|B3.13
>A/TURKEY/unknown/25-007640-001/2025|H5N1|2025|avian|B3.13
>A/PET FOOD/unknown/25-007637-012/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-011/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-010/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-007/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-006/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-003/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005370-008/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005370-006/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005370-004/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005370-002/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005350-004/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005350-002/2025|H5N1|2025|other|B3.13
>A/CATTLE/unknown/25-007185-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007931-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007931-001/2025|H5N1|2025|cattle|B3.13
>A/CAT/unknown/25-008596-001/2025|H5N1|2025|feline|B3.13
>A/CAT/unknown/25-008557-001/2025|H5N1|2025|feline|B3.13
>A/CATTLE/unknown/25-007921-009/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008835-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-047/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-045/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-041/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-039/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-036/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-035/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-034/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-031/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-024/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-022/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007921-006/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-019/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-015/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-014/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-006/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007939-007/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007939-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007935-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007901-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-118/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-110/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009258-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009058-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009058-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-059/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009050-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009050-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009049-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009049-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009041-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008882-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-058/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-010/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-008/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-007/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-010/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-009/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-008/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-006/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006507-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006506-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-055/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-090/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-089/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-088/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-086/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-085/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-083/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-082/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-054/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-078/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-076/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-075/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-074/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-073/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-071/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-053/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-069/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-068/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-067/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-066/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-065/2025|H5N1|2025|cattle|B3.13
>A/PET FOOD/unknown/25-009619-009/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-009619-008/2025|H5N1|2025|other|B3.13
>A/CATTLE/unknown/25-007549-127/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-061/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-049/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-064/2025|H5N1|2025|cattle|B3.13
>A/PET FOOD/unknown/25-009619-006/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-009619-002/2025|H5N1|2025|other|B3.13
>A/CATTLE/unknown/25-009497-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007185-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-063/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-004631-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-003670-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/24-033204-002/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/unknown/25-006511-006/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006511-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-062/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-012/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-135/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-133/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-132/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-131/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-130/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-129/2025|H5N1|2025|cattle|B3.13
>A/CAT/unknown/25-005779-001/2025|H5N1|2025|feline|B3.13
>A/CATTLE/unknown/25-007943-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007915-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007201-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007185-006/2025|H5N1|2025|cattle|B3.13
>A/TURKEY/unknown/25-007640-001/2025|H5N1|2025|avian|B3.13
>A/PET FOOD/unknown/25-007637-012/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-011/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-010/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-007/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-006/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-003/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005370-008/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005370-006/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005370-004/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005370-002/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005350-004/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005350-002/2025|H5N1|2025|other|B3.13
>A/CATTLE/unknown/25-007185-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007931-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007931-001/2025|H5N1|2025|cattle|B3.13
>A/CAT/unknown/25-008596-001/2025|H5N1|2025|feline|B3.13
>A/CAT/unknown/25-008557-001/2025|H5N1|2025|feline|B3.13
>A/CATTLE/unknown/25-007921-009/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008835-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-047/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-045/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-041/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-039/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-036/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-035/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-034/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-031/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-024/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-022/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007921-006/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-019/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-015/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-014/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-006/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007939-007/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007939-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007935-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007901-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-118/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-110/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009258-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009058-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009058-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-059/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009050-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009050-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009049-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009049-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009041-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008882-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-058/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-010/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-008/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-007/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-010/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-009/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-008/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-006/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006507-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006506-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-055/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-090/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-089/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-088/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-086/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-085/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-083/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-082/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-054/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-078/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-076/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-075/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-074/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-073/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-071/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-053/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-069/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-068/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-067/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-066/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-065/2025|H5N1|2025|cattle|B3.13
>A/PET FOOD/unknown/25-009619-009/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-009619-008/2025|H5N1|2025|other|B3.13
>A/CATTLE/unknown/25-007549-127/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-061/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-049/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-064/2025|H5N1|2025|cattle|B3.13
>A/PET FOOD/unknown/25-009619-006/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-009619-002/2025|H5N1|2025|other|B3.13
>A/CATTLE/unknown/25-009497-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007185-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-063/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-004631-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-003670-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/24-033204-002/2024|H5N1|2024|cattle|B3.13
>A/CATTLE/unknown/25-006511-006/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006511-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-062/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-012/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-135/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-133/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-132/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-131/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-130/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-129/2025|H5N1|2025|cattle|B3.13
>A/CAT/unknown/25-005779-001/2025|H5N1|2025|feline|B3.13
>A/CATTLE/unknown/25-007943-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007915-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007201-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007185-006/2025|H5N1|2025|cattle|B3.13
>A/TURKEY/unknown/25-007640-001/2025|H5N1|2025|avian|B3.13
>A/PET FOOD/unknown/25-007637-012/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-011/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-010/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-007/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-006/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-007637-003/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005370-008/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005370-006/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005370-004/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005370-002/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005350-004/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-005350-002/2025|H5N1|2025|other|B3.13
>A/CATTLE/unknown/25-007185-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007931-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007931-001/2025|H5N1|2025|cattle|B3.13
>A/CAT/unknown/25-008596-001/2025|H5N1|2025|feline|B3.13
>A/CAT/unknown/25-008557-001/2025|H5N1|2025|feline|B3.13
>A/CATTLE/unknown/25-007921-009/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008835-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-047/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-045/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-041/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-039/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-036/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-035/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-034/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-031/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-024/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-022/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007921-006/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-019/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-015/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-014/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-006/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007939-007/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007939-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007935-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007901-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-118/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-110/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009258-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009058-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009058-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-059/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009050-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009050-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009049-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009049-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-009041-001/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008882-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-058/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-010/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-008/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-007/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-004/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-008872-002/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-010/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-009/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-008/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-006/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006508-003/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006507-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-006506-005/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-055/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-090/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-089/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-088/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-086/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-085/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-083/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-082/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-054/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-078/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-076/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-075/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-074/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-073/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-071/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-053/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-069/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-068/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-067/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-066/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-065/2025|H5N1|2025|cattle|B3.13
>A/PET FOOD/unknown/25-009619-009/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-009619-008/2025|H5N1|2025|other|B3.13
>A/CATTLE/unknown/25-007549-127/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-061/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-049/2025|H5N1|2025|cattle|B3.13
>A/CATTLE/unknown/25-007549-064/2025|H5N1|2025|cattle|B3.13
>A/PET FOOD/unknown/25-009619-006/2025|H5N1|2025|other|B3.13
>A/PET FOOD/unknown/25-009619-002/2025|H5N1|2025|other|B3.13
>A/CATTLE/unknown/25-009497-001/2025|H5N1|2025|cattle|B3.13

## De-Duplication

In [21]:
# De-duplication 

# Gisaid 

# gisaid1 = downloads + "GISAID_Complete_Fasta_Files/01-01-2024--03-31-2025/"
# gisaid2 = downloads + "GISAID_Complete_Fasta_Files/04-01-2025--04-14-2025/"
gisaid = downloads + "GISAID_Complete_Fasta_Files/03-19-2025--04-14-2025/"

os.chdir(gisaid)

dfs_gisaid = create_dataframes(gisaid)
# dfs_gisaid2 = create_dataframes(gisaid2)

B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2

In [22]:
# for key in dfs_gisaid.keys():
#     dataframes = dfs_gisaid[key]
#     print(dataframes)

# print(dfs_gisaid.keys())

In [23]:
# Do the same with Andersen 

dfs_andersen = create_dataframes(temp_files)

B3.13_HA
B3.13_HA
B3.13_MP
B3.13_MP
B3.13_NA
B3.13_NA
B3.13_NP
B3.13_NP
B3.13_NS
B3.13_NS
B3.13_PA
B3.13_PA
B3.13_PB1
B3.13_PB1
B3.13_PB2
B3.13_PB2
D1.1_HA
D1.1_HA
D1.1_MP
D1.1_MP
D1.1_NA
D1.1_NA
D1.1_NP
D1.1_NP
D1.1_NS
D1.1_NS
D1.1_PA
D1.1_PA
D1.1_PB1
D1.1_PB1
D1.1_PB2
D1.1_PB2

In [24]:
for key in dfs_andersen.keys():
    dataframes = dfs_andersen[key]
    print(key)

B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2

In [26]:
# Merge dataframes and drop duplicates

full_dfs = defaultdict(list)

for i, andersen_key in enumerate(dfs_andersen.keys()):
    gisaid_key = list(dfs_gisaid.keys())[i]
    # gisaid2_key = list(dfs_gisaid2.keys())[i]

    andersen_df = dfs_andersen[andersen_key][0]
    gisaid_df = dfs_gisaid[gisaid_key][0]
    # gisaid2_df = dfs_gisaid2[gisaid2_key][0]

    full_df = pd.concat([andersen_df, gisaid_df], ignore_index=True)
    full_df = full_df.drop_duplicates(subset="isolate_partial", keep="last")
    full_dfs[andersen_key].append(full_df)

# for andersen_key in dfs_andersen.keys():
#     # print("Andersen: ", andersen_key)
#     for gisaid_key in dfs_gisaid.keys():
#         # print("GISAID: ", gisaid_key)
#         if andersen_key == gisaid_key:
#             print(gisaid_key)
#             andersen_df = dfs_andersen[key][0]
#             # print(andersen_df)
#             gisaid_df = dfs_gisaid[key][0]
#             full_df = andersen_df.merge(gisaid_df, how = "outer")
#             # print(full_df)
#             full_df = full_df.drop_duplicates(subset=["isolate_partial"], keep="last")
#             full_dfs[andersen_key].append(full_df)

# print(full_dfs.keys())

# for key in dfs_andersen.keys():
#     dataframes = dfs_andersen[key]
#     for i, df in enumerate(dataframes):
#         print(i)
#         try:
#             full_df = df.merge(dfs_gisaid[key][i], how="outer")
#             # print(full_df)
#             full_df = full_df.drop_duplicates(subset=["isolate_partial"])
#             full_dfs[key].append(full_df)
#         except:
#             print("Failed to merge dataframes in ", key)

print(full_dfs)

defaultdict(<class 'list'>, {'B3.13_HA': [    isolate_partial                                        full_header  \
0        005779-001  >A/CAT/unknown/25-005779-001/2025|H5N1|2025|fe...
1        007943-001  >A/CATTLE/unknown/25-007943-001/2025|H5N1|2025...
3        007201-004  >A/CATTLE/unknown/25-007201-004/2025|H5N1|2025...
4        007185-006  >A/CATTLE/unknown/25-007185-006/2025|H5N1|2025...
9        007637-007  >A/PET FOOD/unknown/25-007637-007/2025|H5N1|20...
..              ...                                                ...
384      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
385      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
386      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
387      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
388      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    ATGAAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
1    ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
3    ATGGAGAACATAGTACTGCTCTTTGCAATAGTTAGCCTTGTTAAAA...
4    ATGGAGAACATAGTACTGCTCTTTGCAATAGTTAGCCTTGTTAAAA...
9    ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
..                                                 ...
384  atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
385  atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
386  atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
387  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
388  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...

[306 rows x 3 columns]], 'B3.13_MP': [    isolate_partial                                        full_header  \
0        005779-001  >A/CAT/unknown/25-005779-001/2025|H5N1|2025|fe...
1        007943-001  >A/CATTLE/unknown/25-007943-001/2025|H5N1|2025...
3        007201-004  >A/CATTLE/unknown/25-007201-004/2025|H5N1|2025...
4        007185-006  >A/CATTLE/unknown/25-007185-006/2025|H5N1|2025...
9        007637-007  >A/PET FOOD/unknown/25-007637-007/2025|H5N1|20...
..              ...                                                ...
384      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
385      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
386      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
387      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
388      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
9    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
..                                                 ...
384  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
385  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
386  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
387  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
388  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...

[306 rows x 3 columns]], 'B3.13_NA': [    isolate_partial                                        full_header  \
0        005779-001  >A/CAT/unknown/25-005779-001/2025|H5N1|2025|fe...
1        007943-001  >A/CATTLE/unknown/25-007943-001/2025|H5N1|2025...
3        007201-004  >A/CATTLE/unknown/25-007201-004/2025|H5N1|2025...
4        007185-006  >A/CATTLE/unknown/25-007185-006/2025|H5N1|2025...
9        007637-007  >A/PET FOOD/unknown/25-007637-007/2025|H5N1|20...
..              ...                                                ...
384      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
385      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
386      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
387      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
388      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    ATGAATCCAAATCAGAAGATAACAACCATTGGATCAATCTGTATGG...
1    ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
3    ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
4    ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
9    ATGAATCCAAATCAGAAGATAACAACCATTGGATCAATCTGTATGG...
..                                                 ...
384  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
385  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
386  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
387  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
388  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...

[306 rows x 3 columns]], 'B3.13_NP': [    isolate_partial                                        full_header  \
0        005779-001  >A/CAT/unknown/25-005779-001/2025|H5N1|2025|fe...
1        007943-001  >A/CATTLE/unknown/25-007943-001/2025|H5N1|2025...
3        007201-004  >A/CATTLE/unknown/25-007201-004/2025|H5N1|2025...
4        007185-006  >A/CATTLE/unknown/25-007185-006/2025|H5N1|2025...
9        007637-007  >A/PET FOOD/unknown/25-007637-007/2025|H5N1|20...
..              ...                                                ...
384      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
385      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
386      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
387      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
388      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
1    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
3    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
4    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
9    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
..                                                 ...
384  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
385  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
386  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
387  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
388  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...

[306 rows x 3 columns]], 'B3.13_NS': [    isolate_partial                                        full_header  \
0        005779-001  >A/CAT/unknown/25-005779-001/2025|H5N1|2025|fe...
1        007943-001  >A/CATTLE/unknown/25-007943-001/2025|H5N1|2025...
3        007201-004  >A/CATTLE/unknown/25-007201-004/2025|H5N1|2025...
4        007185-006  >A/CATTLE/unknown/25-007185-006/2025|H5N1|2025...
9        007637-007  >A/PET FOOD/unknown/25-007637-007/2025|H5N1|20...
..              ...                                                ...
384      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
385      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
386      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
387      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
388      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
1    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
3    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
4    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
9    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
..                                                 ...
384  atggattccaacactgtgttaagctttcaggtagactgctttcttt...
385  atggattccaacactgtgttaagctttcaggtagactgctttcttt...
386  atggattccaacactgtgttaagctttcaggtagactgctttcttt...
387  atggattccaacactgtgttaagctttcaggtagactgctttcttt...
388  atggattccaacactgtgttaagctttcaggtagactgctttcttt...

[306 rows x 3 columns]], 'B3.13_PA': [    isolate_partial                                        full_header  \
0        005779-001  >A/CAT/unknown/25-005779-001/2025|H5N1|2025|fe...
1        007943-001  >A/CATTLE/unknown/25-007943-001/2025|H5N1|2025...
3        007201-004  >A/CATTLE/unknown/25-007201-004/2025|H5N1|2025...
4        007185-006  >A/CATTLE/unknown/25-007185-006/2025|H5N1|2025...
9        007637-007  >A/PET FOOD/unknown/25-007637-007/2025|H5N1|20...
..              ...                                                ...
384      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
385      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
386      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
387      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
388      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
1    ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
3    ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
4    ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
9    ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
..                                                 ...
384  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
385  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
386  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
387  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
388  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...

[306 rows x 3 columns]], 'B3.13_PB1': [    isolate_partial                                        full_header  \
0        005779-001  >A/CAT/unknown/25-005779-001/2025|H5N1|2025|fe...
1        007943-001  >A/CATTLE/unknown/25-007943-001/2025|H5N1|2025...
3        007201-004  >A/CATTLE/unknown/25-007201-004/2025|H5N1|2025...
4        007185-006  >A/CATTLE/unknown/25-007185-006/2025|H5N1|2025...
9        007637-007  >A/PET FOOD/unknown/25-007637-007/2025|H5N1|20...
..              ...                                                ...
384      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
385      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
386      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
387      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
388      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
1    ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
3    ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
4    ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
9    ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
..                                                 ...
384  atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
385  atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
386  atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
387  atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...
388  atggatgtcaatccgaccttactcttcttgaaagttccagcgcaaa...

[306 rows x 3 columns]], 'B3.13_PB2': [    isolate_partial                                        full_header  \
0        005779-001  >A/CAT/unknown/25-005779-001/2025|H5N1|2025|fe...
1        007943-001  >A/CATTLE/unknown/25-007943-001/2025|H5N1|2025...
3        007201-004  >A/CATTLE/unknown/25-007201-004/2025|H5N1|2025...
4        007185-006  >A/CATTLE/unknown/25-007185-006/2025|H5N1|2025...
9        007637-007  >A/PET FOOD/unknown/25-007637-007/2025|H5N1|20...
..              ...                                                ...
384      000600-002  >A/dairy_cow/California/25_000600-002/2024|H5N...
385      000590-002  >A/dairy_cow/California/25_000590-002/2024|H5N...
386      005209-001  >A/dairy_cow/California/25_005209-001/2024|H5N...
387      004920-005  >A/dairy_cow/California/25_004920-005/2024|H5N...
388      004920-004  >A/dairy_cow/California/25_004920-004/2024|H5N...

                                              sequence
0    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
1    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGCCTCGCA...
3    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
4    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
9    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
..                                                 ...
384  atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
385  atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
386  atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
387  atggagagaataaaagaactgagagatctaatgtcacagtctcgca...
388  atggagagaataaaagaactgagagatctaatgtcacagtctcgca...

[306 rows x 3 columns]], 'D1.1_HA': [    isolate_partial                                        full_header  \
0        006998-001  >A/GREAT HORNED OWL/unknown/25-006998-001/2025...
1        006941-001  >A/BALD EAGLE/unknown/25-006941-001/2025|H5N1|...
2        006940-002  >A/CANADA GOOSE/unknown/25-006940-002/2025|H5N...
4        006939-002  >A/RED-TAILED HAWK/unknown/25-006939-002/2025|...
5        006937-001  >A/COOPER'S HAWK/unknown/25-006937-001/2025|H5...
..              ...                                                ...
783      007069-001  >A/chicken/USA/007069-001/2025|H5N1|2025|avian...
784      006674-004  >A/duck/USA/006674-004/2025|H5N1|2025|avian|D1...
785      007078-003  >A/duck/USA/007078-003/2025|H5N1|2025|avian|D1...
786      006346-001  >A/goose/USA/006346-001/2025|H5N1|2025|avian|D...
787      007078-004  >A/duck/USA/007078-004/2025|H5N1|2025|avian|D1...

                                              sequence
0    ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1    ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2    ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4    ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
5    ATGGAAAACATAGTACTTCTTCTTGCAATATTTAGCCTTGTTAAAA...
..                                                 ...
783  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
784  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
785  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
786  atggaaaacatagtacttcttcttgcaatatttagccttgttaaag...
787  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...

[673 rows x 3 columns]], 'D1.1_MP': [    isolate_partial                                        full_header  \
0        006998-001  >A/GREAT HORNED OWL/unknown/25-006998-001/2025...
1        006941-001  >A/BALD EAGLE/unknown/25-006941-001/2025|H5N1|...
2        006940-002  >A/CANADA GOOSE/unknown/25-006940-002/2025|H5N...
4        006939-002  >A/RED-TAILED HAWK/unknown/25-006939-002/2025|...
5        006937-001  >A/COOPER'S HAWK/unknown/25-006937-001/2025|H5...
..              ...                                                ...
783      007069-001  >A/chicken/USA/007069-001/2025|H5N1|2025|avian...
784      006674-004  >A/duck/USA/006674-004/2025|H5N1|2025|avian|D1...
785      007078-003  >A/duck/USA/007078-003/2025|H5N1|2025|avian|D1...
786      006346-001  >A/goose/USA/006346-001/2025|H5N1|2025|avian|D...
787      007078-004  >A/duck/USA/007078-004/2025|H5N1|2025|avian|D1...

                                              sequence
0    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
5    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
..                                                 ...
783  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
784  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
785  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
786  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
787  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...

[673 rows x 3 columns]], 'D1.1_NA': [    isolate_partial                                        full_header  \
0        006998-001  >A/GREAT HORNED OWL/unknown/25-006998-001/2025...
1        006941-001  >A/BALD EAGLE/unknown/25-006941-001/2025|H5N1|...
2        006940-002  >A/CANADA GOOSE/unknown/25-006940-002/2025|H5N...
4        006939-002  >A/RED-TAILED HAWK/unknown/25-006939-002/2025|...
5        006937-001  >A/COOPER'S HAWK/unknown/25-006937-001/2025|H5...
..              ...                                                ...
783      007069-001  >A/chicken/USA/007069-001/2025|H5N1|2025|avian...
784      006674-004  >A/duck/USA/006674-004/2025|H5N1|2025|avian|D1...
785      007078-003  >A/duck/USA/007078-003/2025|H5N1|2025|avian|D1...
786      006346-001  >A/goose/USA/006346-001/2025|H5N1|2025|avian|D...
787      007078-004  >A/duck/USA/007078-004/2025|H5N1|2025|avian|D1...

                                              sequence
0    ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
1    ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
2    ATGAATCCAAATCAAAAGGTAATAACTATCGGGTCAATCTGCATGG...
4    ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
5    ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
..                                                 ...
783  atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
784  atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
785  atgaatccaaatcaaaagataataactatcgggtcaatctgcatga...
786  atgaatccaaatcaaaagataataactatcgggtcaatctgcatgg...
787  atgaatccaaatcaaaagataataactatcgggtcaatctgcatga...

[673 rows x 3 columns]], 'D1.1_NP': [    isolate_partial                                        full_header  \
0        006998-001  >A/GREAT HORNED OWL/unknown/25-006998-001/2025...
1        006941-001  >A/BALD EAGLE/unknown/25-006941-001/2025|H5N1|...
2        006940-002  >A/CANADA GOOSE/unknown/25-006940-002/2025|H5N...
4        006939-002  >A/RED-TAILED HAWK/unknown/25-006939-002/2025|...
5        006937-001  >A/COOPER'S HAWK/unknown/25-006937-001/2025|H5...
..              ...                                                ...
783      007069-001  >A/chicken/USA/007069-001/2025|H5N1|2025|avian...
784      006674-004  >A/duck/USA/006674-004/2025|H5N1|2025|avian|D1...
785      007078-003  >A/duck/USA/007078-003/2025|H5N1|2025|avian|D1...
786      006346-001  >A/goose/USA/006346-001/2025|H5N1|2025|avian|D...
787      007078-004  >A/duck/USA/007078-004/2025|H5N1|2025|avian|D1...

                                              sequence
0    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
1    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
2    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
4    ATGGCATCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
5    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
..                                                 ...
783  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
784  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
785  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
786  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...
787  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...

[673 rows x 3 columns]], 'D1.1_NS': [    isolate_partial                                        full_header  \
0        006998-001  >A/GREAT HORNED OWL/unknown/25-006998-001/2025...
1        006941-001  >A/BALD EAGLE/unknown/25-006941-001/2025|H5N1|...
2        006940-002  >A/CANADA GOOSE/unknown/25-006940-002/2025|H5N...
4        006939-002  >A/RED-TAILED HAWK/unknown/25-006939-002/2025|...
5        006937-001  >A/COOPER'S HAWK/unknown/25-006937-001/2025|H5...
..              ...                                                ...
783      007069-001  >A/chicken/USA/007069-001/2025|H5N1|2025|avian...
784      006674-004  >A/duck/USA/006674-004/2025|H5N1|2025|avian|D1...
785      007078-003  >A/duck/USA/007078-003/2025|H5N1|2025|avian|D1...
786      006346-001  >A/goose/USA/006346-001/2025|H5N1|2025|avian|D...
787      007078-004  >A/duck/USA/007078-004/2025|H5N1|2025|avian|D1...

                                              sequence
0    ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
1    ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
2    ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
4    ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
5    ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
..                                                 ...
783  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...

In [27]:
# If none in one database, only use the other and drop duplicates

# full_dfs = defaultdict(list)
# for key in dfs_andersen.keys():
#     print(key)
# # for key in ["D1.3"]:
#     dataframes = dfs_andersen[key]
#     for i, df in enumerate(dataframes):
#         print(i)
#         try:
#             # full_df = df.merge(dfs_gisaid[key][i], how="outer")
#             # print(full_df)
#             full_df = full_df.drop_duplicates(subset=["isolate_partial"])
#             full_dfs[key].append(full_df)
#         except:
#             print("Failed to merge dataframes in ", key)

## Create FASTA files combining Andersen and GISAID

In [28]:
# Create FASTA files per segment

combined_files = downloads + "Combined_Files/"

os.chdir(combined_files)
for pair in full_dfs.keys():
    print(pair)
    output_path = combined_files + pair + "_combined_" + update_date + ".fasta" 

    output_file = open(output_path, "w")
    for item in full_dfs[pair]:
        # for item in item:
        # item = fasta_files[pair]
        for index, row in item.iterrows():
            name = item.loc[index, "full_header"]
            sequence = item.loc[index, "sequence"]
            # print(name)
        # First is header, second is sequence
        # print(value)
            output_file.write(name)
            output_file.write(sequence)
    output_file.close()

B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2

In [21]:
# os.chdir(complete_files)

# segment_files = []
# for dirpath, dirs, files in os.walk(temp_files): # + "01-01-2024--03-31-2025_renamed/"):
#     for segment in ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]:
#         base = []
#         for file in files:
#             file_name = os.path.join(dirpath, file)
#             # print(file_name)
#             if segment in file_name:
#                 with open(file_name) as f:
#                     lines = f.readlines()
#                     for line in lines:
#                         base.append(line)
#                 f.close()
#         os.chdir(complete_files)
#         output_path = complete_files + segment + "_andersen_" + update_date + ".fasta" # Genotype and Segment should all be the same
#         output_file = open(output_path, "w")
#         for b in base:
#             output_file.write(b)
#         output_file.close()
#     break