# Cleaning Downloaded Data from avian-flu

Author: Alexander Maksiaev

Purpose: Clean downloaded data from avian-flu, rename sequences according to convention, de-duplicate from GISAID

In [1]:
# Housekeeping

import os
import pandas as pd
import numpy as np
import dateutil 
from datetime import datetime
from collections import defaultdict 
import importlib
import utils  
importlib.reload(utils)
from utils import * 


# Dates
start_date = "04-14-2025"
end_date = "06-13-2025"
date_range = start_date + "--" + end_date

# Make sure you have the correct paths

home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/"
downloads = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/"
# downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
references = home + "references/"
originals = downloads + "Andersen/"
saved = originals + "saved/"
temp_files = originals + "temp/"
complete_files = downloads + "complete/"

os.chdir(downloads)

## Read Metadata

In [2]:
# Read metadata

# os.chdir(saved)
# metadata_normalized = pd.read_csv("metadata_normalized.tsv", delimiter="\t") # Collection dates

metadata_folder = originals + "avian-influenza/metadata/"
os.chdir(metadata_folder)

metadata = pd.read_csv("SraRunTable_automated.csv")

print(len(metadata)) 

# metadata = metadata.merge(metadata_normalized, how="outer")
print(metadata.columns)

# Find the name of the state sample was collected in
metadata["name_state"] = metadata["geo_loc_name"].apply(lambda x: x.split("/")[1] if len(x.split("/")) > 1 else x.split("/")[0])

# Convert the dates to date format so we can compare
metadata["ReleaseDate"] = metadata["ReleaseDate"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))

metadata = metadata[metadata["ReleaseDate"] >= dateutil.parser.parse(start_date).strftime("%Y-%m-%d")] # Find only >= last date using Release Date from metadata 
metadata = metadata[metadata["ReleaseDate"] <= dateutil.parser.parse(end_date).strftime("%Y-%m-%d")] # Find only <= update date using Release Date from metadata

# # Get rid of certain runs
# os.chdir(saved)
# runs_to_remove = pd.read_csv("andersen-lab-seqs-to-filter.csv")
# print(runs_to_remove)
# for run in runs_to_remove["Run"].values:
#     metadata = metadata[metadata["Run"] != run]

print(len(metadata)) 
display(metadata)
print(metadata["Library Name"])

9899
Index(['Run', 'Assay Type', 'AvgSpotLen', 'Bases', 'BioProject', 'BioSample',
       'BioSampleModel', 'Bytes', 'Center Name', 'Collection_Date', 'Consent',
       'DATASTORE filetype', 'DATASTORE provider', 'DATASTORE region',
       'Experiment', 'geo_loc_name_country', 'geo_loc_name_country_continent',
       'geo_loc_name', 'Host', 'Instrument', 'isolate', 'Library Name',
       'LibraryLayout', 'LibrarySelection', 'LibrarySource', 'Organism',
       'Platform', 'ReleaseDate', 'create_date', 'version', 'Sample Name',
       'SRA Study', 'serotype', 'isolation_source', 'BioSample Accession',
       'is_retracted', 'retraction_detection_date_utc'],
      dtype='object')
1371

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,create_date,version,Sample Name,SRA Study,serotype,isolation_source,BioSample Accession,is_retracted,retraction_detection_date_utc,name_state
8388,SRR33125012,WGS,148.14,103837402,PRJNA1207547,SAMN47941494,Viral,38567600,USDA-NVSL,2025,...,2025-04-14 15:01:46,1,25-004426-001,SRP557452,NaN,CLOACAL/OROPHARYNGEAL SWAB POOL,SRS24712538,False,NaN,USA
8389,SRR33125013,WGS,148.47,151899011,PRJNA1207547,SAMN47941493,Viral,55900173,USDA-NVSL,2025,...,2025-04-14 14:59:12,1,25-004499-002,SRP557452,NaN,CLOACAL/OROPHARYNGEAL SWAB POOL,SRS24712537,False,NaN,USA
8390,SRR33125014,WGS,147.45,166656358,PRJNA1207547,SAMN47941492,Viral,60793010,USDA-NVSL,2025,...,2025-04-14 14:59:27,1,25-004497-005,SRP557452,NaN,CLOACAL/OROPHARYNGEAL SWAB POOL,SRS24712536,False,NaN,USA
8391,SRR33125015,WGS,148.33,107664413,PRJNA1207547,SAMN47941491,Viral,39666477,USDA-NVSL,2025,...,2025-04-14 15:00:01,1,25-004497-004,SRP557452,NaN,CLOACAL/OROPHARYNGEAL SWAB POOL,SRS24712534,False,NaN,USA
8392,SRR33125016,WGS,120.38,2476776,PRJNA1207547,SAMN47941490,Viral,986034,USDA-NVSL,2025,...,2025-04-14 14:59:20,1,25-004480-001,SRP557452,NaN,tracheal swab,SRS24712535,False,NaN,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,SRR33943358,WGS,148.58,145468815,PRJNA1102327,SAMN49008963,Viral,50309372,USDA-NVSL,2025,...,2025-06-11 17:51:42,1,25-013594-001,SRP503016,NaN,milk,SRS25347775,False,NaN,USA
9755,SRR33943359,WGS,148.65,141682464,PRJNA1102327,SAMN49008954,Viral,52273363,USDA-NVSL,2025,...,2025-06-11 17:51:39,1,25-016317-001,SRP503016,NaN,milk,SRS25347774,False,NaN,USA
9756,SRR33943360,WGS,148.56,109583296,PRJNA1102327,SAMN49008953,Viral,40873907,USDA-NVSL,2025,...,2025-06-11 17:51:39,1,25-015080-001,SRP503016,NaN,"MILK, BULK TANK",SRS25347773,False,NaN,USA
9757,SRR33943301,WGS,148.82,146047742,PRJNA980729,SAMN49008919,Viral,51264801,USDA-NVSL,2025,...,2025-06-11 17:50:24,1,25-016837-002,SRP441379,NaN,OROPHARYNGEAL SWAB,SRS25347770,False,NaN,USA
9758,SRR33943302,WGS,148.87,176312039,PRJNA980729,SAMN49008918,Viral,61802719,USDA-NVSL,2025,...,2025-06-11 17:50:27,1,25-016837-001,SRP441379,NaN,OROPHARYNGEAL SWAB,SRS25347769,False,NaN,USA

8388            25-004426-001-original
8389            25-004499-002-original
8390            25-004497-005-original
8391            25-004497-004-original
8392            25-004480-001-original
                     ...
9754    25-013594-001-original-repeat2
9755            25-016317-001-original
9756            25-015080-001-original
9757            25-016837-002-original
9758            25-016837-001-original
Name: Library Name, Length: 1371, dtype: object

In [3]:
# Get list of genotypes

os.chdir(home + "references/")

# genotypes_df = pd.read_excel("genotype_key.xlsx")

# genotypes = list(genotypes_df["Genotype"])

# print(genotypes)

genotypes = ["B3.13", "D1.1"]

# genotypes = ["B3.2"] #, "B3.2", "B3.6", "B3.7", "B3.5", "A3"]

### Naming convention ###
>A/[host]/[geo_loc_name]/[isolate]/[year]|[serotype: H5N1]|[collection_date]|[host_type]|[genotype]

host_type is from manual animal reference

In metadata, we have: host, geo_loc_name, isolate, year

We need: geo_loc_name, collection_date, host_type, genotype

host = Host

geo_loc_name (primary) = geo_loc_name

geo_loc_name (secondary) = genbank_mapping.tsv > genbank_name

isolate = isolate

collection date (primary) = Collection_Date

collection date (secondary) = https://www.ncbi.nlm.nih.gov/genbank/ > BioSample (input: BioSample) > Nucleotide > [first result] > collection_date

serotype = serotype

host type = [from ref] 

genotype = [from genoflu] -- use genoflu_results.tsv

## Get genotype, specific geolocation

In [4]:
# Get genotype from genoflu_results.tsv

os.chdir(metadata_folder)

genoflu_results = pd.read_csv("genoflu_results.tsv", delimiter="\t")

genoflu_results["Run"] = genoflu_results["sample"]

metadata = metadata.merge(genoflu_results, on="Run", how="inner")
print(metadata)
# metadata = metadata[~metadata["Genotype"].str.contains('Not assigned')] # Do not include non-assigned genotypes
metadata = metadata[metadata["Genotype"].isin(genotypes)]

print(len(metadata)) 
display(metadata)

              Run Assay Type  AvgSpotLen      Bases    BioProject  \
0     SRR33125012        WGS      148.14  103837402  PRJNA1207547
1     SRR33125013        WGS      148.47  151899011  PRJNA1207547
2     SRR33125014        WGS      147.45  166656358  PRJNA1207547
3     SRR33125015        WGS      148.33  107664413  PRJNA1207547
4     SRR33125016        WGS      120.38    2476776  PRJNA1207547
...           ...        ...         ...        ...           ...
1366  SRR33943358        WGS      148.58  145468815  PRJNA1102327
1367  SRR33943359        WGS      148.65  141682464  PRJNA1102327
1368  SRR33943360        WGS      148.56  109583296  PRJNA1102327
1369  SRR33943301        WGS      148.82  146047742   PRJNA980729
1370  SRR33943302        WGS      148.87  176312039   PRJNA980729

         BioSample BioSampleModel     Bytes Center Name Collection_Date  ...  \
0     SAMN47941494          Viral  38567600   USDA-NVSL            2025  ...
1     SAMN47941493          Viral  55900173   USDA-NVSL            2025  ...
2     SAMN47941492          Viral  60793010   USDA-NVSL            2025  ...
3     SAMN47941491          Viral  39666477   USDA-NVSL            2025  ...
4     SAMN47941490          Viral    986034   USDA-NVSL            2025  ...
...            ...            ...       ...         ...             ...  ...
1366  SAMN49008963          Viral  50309372   USDA-NVSL            2025  ...
1367  SAMN49008954          Viral  52273363   USDA-NVSL            2025  ...
1368  SAMN49008953          Viral  40873907   USDA-NVSL            2025  ...
1369  SAMN49008919          Viral  51264801   USDA-NVSL            2025  ...
1370  SAMN49008918          Viral  61802719   USDA-NVSL            2025  ...

     name_state       sample                 date       File Name Genotype  \
0           USA  SRR33125012  2025-05-09_10-52-38  SRR33125012.fa     D1.1
1           USA  SRR33125013  2025-05-09_10-52-46  SRR33125013.fa     D1.1
2           USA  SRR33125014  2025-05-09_10-49-25  SRR33125014.fa     D1.1
3           USA  SRR33125015  2025-05-09_10-48-50  SRR33125015.fa     D1.1
4           USA  SRR33125016  2025-05-09_10-52-46  SRR33125016.fa     D1.1
...         ...          ...                  ...             ...      ...
1366        USA  SRR33943358  2025-06-13_07-18-34  SRR33943358.fa    B3.13
1367        USA  SRR33943359  2025-06-13_07-18-34  SRR33943359.fa    B3.13
1368        USA  SRR33943360  2025-06-13_07-18-34  SRR33943360.fa    B3.13
1369        USA  SRR33943301  2025-06-13_07-18-34  SRR33943301.fa     D1.1
1370        USA  SRR33943302  2025-06-13_07-18-34  SRR33943302.fa     D1.1

                            Genotype List Used, >=98.0%  \
0     NP:am13, NS:ea3, PA:am4, PB2:am24, MP:ea3, PB1...
1     NA:am4N1, NS:ea3, PB2:am24, MP:ea3, PB1:ea3, P...
2     PB2:am24, MP:ea3, PB1:ea3, NP:am13, NA:am4N1, ...
3     PA:am4, NA:am4N1, NP:am13, PB1:ea3, NS:ea3, MP...
4     NA:am4N1, PB1:ea3, NS:ea3, MP:ea3, NP:am13, PA...
...                                                 ...
1366  PA:ea1, NA:ea1, PB2:am2.2, NP:am8, HA:ea1, PB1...
1367  HA:ea1, PB1:am4, NA:ea1, MP:ea1, NP:am8, PA:ea...
1368  PB1:am4, MP:ea1, NP:am8, NA:ea1, PB2:am2.2, HA...
1369  PB2:am24, NA:am4N1, MP:ea3, NS:ea3, PA:am4, HA...
1370  NS:ea3, PB2:am24, PB1:ea3, MP:ea3, HA:ea3, PA:...

                             Genotype Sample Title List  \
0     am13:24-030039-001:NP, ea3:22-013001-001:NS, a...
1     am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
2     am24:24-030039-001:PB2, ea3:22-013001-001:MP, ...
3     am4:24-030039-001:PA, am4N1:24-030039-001:NA, ...
4     am4N1:24-030039-001:NA, ea3:22-013001-001:PB1,...
...                                                 ...
1366  ea1:22-003707-003:PA, ea1:22-003707-003:NA, am...
1367  ea1:22-003707-003:HA, am4:23-001855-001:PB1, e...
1368  am4:23-001855-001:PB1, ea1:22-003707-003:MP, a...
1369  am24:24-030039-001:PB2, am4N1:24-030039-001:NA...
1370  ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...

                            Genotype Percent Match List  \
0     99.87%, 98.93%, 99.72%, 99.61%, 99.80%, 99.39%...
1     98.87%, 99.17%, 99.83%, 99.90%, 99.16%, 99.58%...
2     99.83%, 99.90%, 99.25%, 99.87%, 98.96%, 99.41%...
3     99.58%, 99.03%, 99.87%, 98.99%, 99.28%, 99.90%...
4     99.62%, 99.28%, 99.28%, 99.69%, 99.93%, 98.34%...
...                                                 ...
1366  98.84%, 98.65%, 98.51%, 98.86%, 98.12%, 99.56%...
1367  98.42%, 99.34%, 98.58%, 98.78%, 98.93%, 98.79%...
1368  99.12%, 98.98%, 98.93%, 98.72%, 98.51%, 98.30%...
1369  99.56%, 99.04%, 100.00%, 98.93%, 98.75%, 99.47...
1370  98.81%, 99.47%, 99.16%, 99.90%, 99.41%, 99.44%...

              Genotype Mismatch List Genotype Average Depth of Coverage List
0           2, 9, 6, 9, 2, 11, 8, 12       Ran on FASTA - No Coverage Report
1           13, 7, 4, 1, 19, 9, 9, 2       Ran on FASTA - No Coverage Report
2         4, 1, 17, 2, 12, 10, 6, 11       Ran on FASTA - No Coverage Report
3           9, 11, 2, 23, 6, 1, 3, 9       Ran on FASTA - No Coverage Report
4            4, 7, 6, 3, 1, 29, 9, 9       Ran on FASTA - No Coverage Report
...                              ...                                     ...
1366   25, 19, 34, 17, 32, 10, 9, 10       Ran on FASTA - No Coverage Report
1367   27, 15, 20, 12, 16, 26, 33, 8       Ran on FASTA - No Coverage Report
1368  20, 10, 16, 18, 34, 29, 22, 11       Ran on FASTA - No Coverage Report
1369      10, 10, 0, 9, 27, 9, 17, 7       Ran on FASTA - No Coverage Report
1370    10, 12, 19, 1, 10, 12, 6, 12       Ran on FASTA - No Coverage Report

[1371 rows x 47 columns]
1184

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,name_state,sample,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List
0,SRR33125012,WGS,148.14,103837402,PRJNA1207547,SAMN47941494,Viral,38567600,USDA-NVSL,2025,...,USA,SRR33125012,2025-05-09_10-52-38,SRR33125012.fa,D1.1,"NP:am13, NS:ea3, PA:am4, PB2:am24, MP:ea3, PB1...","am13:24-030039-001:NP, ea3:22-013001-001:NS, a...","99.87%, 98.93%, 99.72%, 99.61%, 99.80%, 99.39%...","2, 9, 6, 9, 2, 11, 8, 12",Ran on FASTA - No Coverage Report
1,SRR33125013,WGS,148.47,151899011,PRJNA1207547,SAMN47941493,Viral,55900173,USDA-NVSL,2025,...,USA,SRR33125013,2025-05-09_10-52-46,SRR33125013.fa,D1.1,"NA:am4N1, NS:ea3, PB2:am24, MP:ea3, PB1:ea3, P...","am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...","98.87%, 99.17%, 99.83%, 99.90%, 99.16%, 99.58%...","13, 7, 4, 1, 19, 9, 9, 2",Ran on FASTA - No Coverage Report
2,SRR33125014,WGS,147.45,166656358,PRJNA1207547,SAMN47941492,Viral,60793010,USDA-NVSL,2025,...,USA,SRR33125014,2025-05-09_10-49-25,SRR33125014.fa,D1.1,"PB2:am24, MP:ea3, PB1:ea3, NP:am13, NA:am4N1, ...","am24:24-030039-001:PB2, ea3:22-013001-001:MP, ...","99.83%, 99.90%, 99.25%, 99.87%, 98.96%, 99.41%...","4, 1, 17, 2, 12, 10, 6, 11",Ran on FASTA - No Coverage Report
3,SRR33125015,WGS,148.33,107664413,PRJNA1207547,SAMN47941491,Viral,39666477,USDA-NVSL,2025,...,USA,SRR33125015,2025-05-09_10-48-50,SRR33125015.fa,D1.1,"PA:am4, NA:am4N1, NP:am13, PB1:ea3, NS:ea3, MP...","am4:24-030039-001:PA, am4N1:24-030039-001:NA, ...","99.58%, 99.03%, 99.87%, 98.99%, 99.28%, 99.90%...","9, 11, 2, 23, 6, 1, 3, 9",Ran on FASTA - No Coverage Report
4,SRR33125016,WGS,120.38,2476776,PRJNA1207547,SAMN47941490,Viral,986034,USDA-NVSL,2025,...,USA,SRR33125016,2025-05-09_10-52-46,SRR33125016.fa,D1.1,"NA:am4N1, PB1:ea3, NS:ea3, MP:ea3, NP:am13, PA...","am4N1:24-030039-001:NA, ea3:22-013001-001:PB1,...","99.62%, 99.28%, 99.28%, 99.69%, 99.93%, 98.34%...","4, 7, 6, 3, 1, 29, 9, 9",Ran on FASTA - No Coverage Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1366,SRR33943358,WGS,148.58,145468815,PRJNA1102327,SAMN49008963,Viral,50309372,USDA-NVSL,2025,...,USA,SRR33943358,2025-06-13_07-18-34,SRR33943358.fa,B3.13,"PA:ea1, NA:ea1, PB2:am2.2, NP:am8, HA:ea1, PB1...","ea1:22-003707-003:PA, ea1:22-003707-003:NA, am...","98.84%, 98.65%, 98.51%, 98.86%, 98.12%, 99.56%...","25, 19, 34, 17, 32, 10, 9, 10",Ran on FASTA - No Coverage Report
1367,SRR33943359,WGS,148.65,141682464,PRJNA1102327,SAMN49008954,Viral,52273363,USDA-NVSL,2025,...,USA,SRR33943359,2025-06-13_07-18-34,SRR33943359.fa,B3.13,"HA:ea1, PB1:am4, NA:ea1, MP:ea1, NP:am8, PA:ea...","ea1:22-003707-003:HA, am4:23-001855-001:PB1, e...","98.42%, 99.34%, 98.58%, 98.78%, 98.93%, 98.79%...","27, 15, 20, 12, 16, 26, 33, 8",Ran on FASTA - No Coverage Report
1368,SRR33943360,WGS,148.56,109583296,PRJNA1102327,SAMN49008953,Viral,40873907,USDA-NVSL,2025,...,USA,SRR33943360,2025-06-13_07-18-34,SRR33943360.fa,B3.13,"PB1:am4, MP:ea1, NP:am8, NA:ea1, PB2:am2.2, HA...","am4:23-001855-001:PB1, ea1:22-003707-003:MP, a...","99.12%, 98.98%, 98.93%, 98.72%, 98.51%, 98.30%...","20, 10, 16, 18, 34, 29, 22, 11",Ran on FASTA - No Coverage Report
1369,SRR33943301,WGS,148.82,146047742,PRJNA980729,SAMN49008919,Viral,51264801,USDA-NVSL,2025,...,USA,SRR33943301,2025-06-13_07-18-34,SRR33943301.fa,D1.1,"PB2:am24, NA:am4N1, MP:ea3, NS:ea3, PA:am4, HA...","am24:24-030039-001:PB2, am4N1:24-030039-001:NA...","99.56%, 99.04%, 100.00%, 98.93%, 98.75%, 99.47...","10, 10, 0, 9, 27, 9, 17, 7",Ran on FASTA - No Coverage Report
1370,SRR33943302,WGS,148.87,176312039,PRJNA980729,SAMN49008918,Viral,61802719,USDA-NVSL,2025,...,USA,SRR33943302,2025-06-13_07-18-34,SRR33943302.fa,D1.1,"NS:ea3, PB2:am24, PB1:ea3, MP:ea3, HA:ea3, PA:...","ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...","98.81%, 99.47%, 99.16%, 99.90%, 99.41%, 99.44%...","10, 12, 19, 1, 10, 12, 6, 12",Ran on FASTA - No Coverage Report

In [ ]:
# Get specific geolocation and name_state from genbank_mapping.tsv
os.chdir(metadata_folder)
genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
genbank_mapping = genbank_mapping.rename(columns={"sra_run": "Run"})
# genbank_mapping["Run"] = genbank_mapping["sra_run"]
genbank_mapping.drop_duplicates(subset="Run", keep="first", inplace=True) # Drop duplicates
genbank_mapping["name_state"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[2]) # Get the name of the state

print(genbank_mapping)

metadata_genbank = pd.concat([metadata, genbank_mapping], join="inner")

print(metadata_genbank)

# print(metadata["name_state"])

# Get geolocation for second state attribute

os.chdir(home + "references/")
state_ref = pd.read_csv("states_ref.csv")
# Format: USA-[state abbreviation], e.g. USA-MD
metadata_genbank["Geo_Location"] = metadata_genbank["name_state"].apply(lambda x: 
                                                        # If "x" has the state abbreviation (e.g. "MD")
                                                        state_ref.loc[state_ref["Abbreviation"].str.contains('|'.join(x.replace(', ', ' ').split(' ')), regex=True), 'Country'].iloc[0] 
                                                        + "-" + 
                                                        x
                                                        if state_ref["Abbreviation"].str.contains("|".join((x.replace(", ", " ").split(" "))), regex=True).any()
                                                        # If "x" has the full state name (e.g. "Maryland")
                                                        else state_ref.loc[state_ref['State'].str.contains('|'.join(x.replace(', ', ' ').split(' ')), regex=True), 'Country'].iloc[0]
                                                        + "-" + 
                                                        state_ref.loc[state_ref['State'].str.contains('|'.join(x.replace(', ', ' ').split(' ')), regex=True), 'Abbreviation'].iloc[0] 
                                                        if state_ref["State"].str.contains("|".join((x.replace(", ", " ").split(" "))), regex=True).any() 
                                                        # If "x" has neither the state abbreviation nor the full state name
                                                        else 
                                                        x)

# Tests
print(state_ref.loc[state_ref['State'].str.contains('|'.join("Kentucky, whatever".replace(',', ' ').split(' ')), regex=True), 'Abbreviation'])
print(state_ref['State'].str.contains('|'.join("Kentucky, whatever".replace(', ', ' ').split(' ')), regex=True))
# print(metadata["name_state"])
print(metadata_genbank)
print(len(metadata))
metadata = metadata.merge(metadata_genbank, on="Run")
# metadata = pd.concat([metadata, metadata_genbank], join="inner")
# print(metadata[metadata["Geo_Location"] != "USA"])
display(metadata)

                    seg_file  \
0      SRR28752446_HA_cns.fa
8      SRR28752447_HA_cns.fa
16     SRR28752448_HA_cns.fa
24     SRR28752449_HA_cns.fa
32     SRR28752450_HA_cns.fa
...                      ...
44878  SRR33764571_HA_cns.fa
44886  SRR33764572_HA_cns.fa
44894  SRR33764573_HA_cns.fa
44902  SRR33764574_HA_cns.fa
44910  SRR33764575_HA_cns.fa

                                            seg_seq_name          Run seg  \
0      Consensus_SRR28752446_HA_cns_threshold_0.5_qua...  SRR28752446  HA
8      Consensus_SRR28752447_HA_cns_threshold_0.5_qua...  SRR28752447  HA
16     Consensus_SRR28752448_HA_cns_threshold_0.5_qua...  SRR28752448  HA
24     Consensus_SRR28752449_HA_cns_threshold_0.5_qua...  SRR28752449  HA
32     Consensus_SRR28752450_HA_cns_threshold_0.5_qua...  SRR28752450  HA
...                                                  ...          ...  ..
44878  Consensus_SRR33764571_HA_cns_threshold_0.5_qua...  SRR33764571  HA
44886  Consensus_SRR33764572_HA_cns_threshold_0.5_qua...  SRR33764572  HA
44894  Consensus_SRR33764573_HA_cns_threshold_0.5_qua...  SRR33764573  HA
44902  Consensus_SRR33764574_HA_cns_threshold_0.5_qua...  SRR33764574  HA
44910  Consensus_SRR33764575_HA_cns_threshold_0.5_qua...  SRR33764575  HA

      genbank_acc  genbank_seg                             genbank_name  \
0      PP740722.1            4     A/blackbird/Texas/24-008354-001/2024
8      PP752829.1            4        A/cattle/Texas/24-009108-005/2024
16     PP752821.1            4        A/cattle/Texas/24-009108-004/2024
24     PP752813.1            4        A/cattle/Texas/24-009108-003/2024
32     PP752805.1            4        A/cattle/Texas/24-009108-002/2024
...           ...          ...                                      ...
44878  PV847341.1            4  A/cattle/ID/25-015132-002-original/2025
44886  PV847333.1            4  A/cattle/ID/25-015132-001-original/2025
44894  PV847325.1            4  A/cattle/ID/25-015131-001-original/2025
44902  PV847317.1            4  A/cattle/ID/25-015130-002-original/2025
44910  PV847309.1            4  A/cattle/ID/25-015130-001-original/2025

      name_state
0          Texas
8          Texas
16         Texas
24         Texas
32         Texas
...          ...
44878         ID
44886         ID
44894         ID
44902         ID
44910         ID

[5054 rows x 8 columns]
               Run name_state
0      SRR33125012        USA
1      SRR33125013        USA
2      SRR33125014        USA
3      SRR33125015        USA
4      SRR33125016        USA
...            ...        ...
44878  SRR33764571         ID
44886  SRR33764572         ID
44894  SRR33764573         ID
44902  SRR33764574         ID
44910  SRR33764575         ID

[6238 rows x 2 columns]
0     AL
1     AK
2     AZ
3     AR
4     AS
      ..
65    ON
66    PE
67    QC
68    SK
69    YT
Name: Abbreviation, Length: 70, dtype: object
0     False
1     False
2     False
3     False
4     False
      ...
65    False
66    False
67    False
68    False
69    False
Name: State, Length: 70, dtype: bool
               Run name_state Geo_Location
0      SRR33125012        USA          USA
1      SRR33125013        USA          USA
2      SRR33125014        USA          USA
3      SRR33125015        USA          USA
4      SRR33125016        USA          USA
...            ...        ...          ...
44878  SRR33764571         ID       USA-ID
44886  SRR33764572         ID       USA-ID
44894  SRR33764573         ID       USA-ID
44902  SRR33764574         ID       USA-ID
44910  SRR33764575         ID       USA-ID

[6238 rows x 3 columns]
1184

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,name_state_y,Geo_Location
0,SRR33125012,WGS,148.14,103837402,PRJNA1207547,SAMN47941494,Viral,38567600,USDA-NVSL,2025,...,2025-05-09_10-52-38,SRR33125012.fa,D1.1,"NP:am13, NS:ea3, PA:am4, PB2:am24, MP:ea3, PB1...","am13:24-030039-001:NP, ea3:22-013001-001:NS, a...","99.87%, 98.93%, 99.72%, 99.61%, 99.80%, 99.39%...","2, 9, 6, 9, 2, 11, 8, 12",Ran on FASTA - No Coverage Report,USA,USA
1,SRR33125013,WGS,148.47,151899011,PRJNA1207547,SAMN47941493,Viral,55900173,USDA-NVSL,2025,...,2025-05-09_10-52-46,SRR33125013.fa,D1.1,"NA:am4N1, NS:ea3, PB2:am24, MP:ea3, PB1:ea3, P...","am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...","98.87%, 99.17%, 99.83%, 99.90%, 99.16%, 99.58%...","13, 7, 4, 1, 19, 9, 9, 2",Ran on FASTA - No Coverage Report,USA,USA
2,SRR33125014,WGS,147.45,166656358,PRJNA1207547,SAMN47941492,Viral,60793010,USDA-NVSL,2025,...,2025-05-09_10-49-25,SRR33125014.fa,D1.1,"PB2:am24, MP:ea3, PB1:ea3, NP:am13, NA:am4N1, ...","am24:24-030039-001:PB2, ea3:22-013001-001:MP, ...","99.83%, 99.90%, 99.25%, 99.87%, 98.96%, 99.41%...","4, 1, 17, 2, 12, 10, 6, 11",Ran on FASTA - No Coverage Report,USA,USA
3,SRR33125015,WGS,148.33,107664413,PRJNA1207547,SAMN47941491,Viral,39666477,USDA-NVSL,2025,...,2025-05-09_10-48-50,SRR33125015.fa,D1.1,"PA:am4, NA:am4N1, NP:am13, PB1:ea3, NS:ea3, MP...","am4:24-030039-001:PA, am4N1:24-030039-001:NA, ...","99.58%, 99.03%, 99.87%, 98.99%, 99.28%, 99.90%...","9, 11, 2, 23, 6, 1, 3, 9",Ran on FASTA - No Coverage Report,USA,USA
4,SRR33125016,WGS,120.38,2476776,PRJNA1207547,SAMN47941490,Viral,986034,USDA-NVSL,2025,...,2025-05-09_10-52-46,SRR33125016.fa,D1.1,"NA:am4N1, PB1:ea3, NS:ea3, MP:ea3, NP:am13, PA...","am4N1:24-030039-001:NA, ea3:22-013001-001:PB1,...","99.62%, 99.28%, 99.28%, 99.69%, 99.93%, 98.34%...","4, 7, 6, 3, 1, 29, 9, 9",Ran on FASTA - No Coverage Report,USA,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1513,SRR33943358,WGS,148.58,145468815,PRJNA1102327,SAMN49008963,Viral,50309372,USDA-NVSL,2025,...,2025-06-13_07-18-34,SRR33943358.fa,B3.13,"PA:ea1, NA:ea1, PB2:am2.2, NP:am8, HA:ea1, PB1...","ea1:22-003707-003:PA, ea1:22-003707-003:NA, am...","98.84%, 98.65%, 98.51%, 98.86%, 98.12%, 99.56%...","25, 19, 34, 17, 32, 10, 9, 10",Ran on FASTA - No Coverage Report,USA,USA
1514,SRR33943359,WGS,148.65,141682464,PRJNA1102327,SAMN49008954,Viral,52273363,USDA-NVSL,2025,...,2025-06-13_07-18-34,SRR33943359.fa,B3.13,"HA:ea1, PB1:am4, NA:ea1, MP:ea1, NP:am8, PA:ea...","ea1:22-003707-003:HA, am4:23-001855-001:PB1, e...","98.42%, 99.34%, 98.58%, 98.78%, 98.93%, 98.79%...","27, 15, 20, 12, 16, 26, 33, 8",Ran on FASTA - No Coverage Report,USA,USA
1515,SRR33943360,WGS,148.56,109583296,PRJNA1102327,SAMN49008953,Viral,40873907,USDA-NVSL,2025,...,2025-06-13_07-18-34,SRR33943360.fa,B3.13,"PB1:am4, MP:ea1, NP:am8, NA:ea1, PB2:am2.2, HA...","am4:23-001855-001:PB1, ea1:22-003707-003:MP, a...","99.12%, 98.98%, 98.93%, 98.72%, 98.51%, 98.30%...","20, 10, 16, 18, 34, 29, 22, 11",Ran on FASTA - No Coverage Report,USA,USA
1516,SRR33943301,WGS,148.82,146047742,PRJNA980729,SAMN49008919,Viral,51264801,USDA-NVSL,2025,...,2025-06-13_07-18-34,SRR33943301.fa,D1.1,"PB2:am24, NA:am4N1, MP:ea3, NS:ea3, PA:am4, HA...","am24:24-030039-001:PB2, am4N1:24-030039-001:NA...","99.56%, 99.04%, 100.00%, 98.93%, 98.75%, 99.47...","10, 10, 0, 9, 27, 9, 17, 7",Ran on FASTA - No Coverage Report,USA,USA
1517,SRR33943302,WGS,148.87,176312039,PRJNA980729,SAMN49008918,Viral,61802719,USDA-NVSL,2025,...,2025-06-13_07-18-34,SRR33943302.fa,D1.1,"NS:ea3, PB2:am24, PB1:ea3, MP:ea3, HA:ea3, PA:...","ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...","98.81%, 99.47%, 99.16%, 99.90%, 99.41%, 99.44%...","10, 12, 19, 1, 10, 12, 6, 12",Ran on FASTA - No Coverage Report,USA,USA

In [6]:
# # If no states

# metadata_genbank = metadata

# metadata_genbank["name_state"] = "USA"

# metadata_genbank["Geo_Location"] = "USA"

# display(metadata_genbank)

## Collection Dates

If date is N/A, try finding it first. If saved dates are available, do NOT run the next cell. Comment it out and run the cell after.

In [ ]:

# Get all dates
metadata["Collection_Date_Specific"] = metadata["BioSample"].apply(lambda x: search_collection_date(x, metadata) if "-" not in x else x) # Real dates have dashes

# Save this so we don't have to do it again

# os.chdir(temp_files)
metadata.to_csv("metadata_genbank.csv")

Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.

In [10]:
# os.chdir(saved)

# metadata_to_merge = pd.read_csv("metadata_genbank_" + date_range + ".csv")
# metadata = pd.merge(metadata, metadata_to_merge, how="left")
# # metadata = pd.read_csv("metadata_genbank.csv")
# print(len(metadata))

If saved dates are available, un-comment and run the next cell

In [ ]:
# # # Upload saved data -- if doing this, make sure the above cell is commented out
# # os.chdir(temp_files + "saved/")
# # metadata_genbank = pd.read_csv("metadata_genbank.csv")
# # os.chdir(temp_files)

# # Get only updated dates

# # unknown_dates = metadata[(metadata["Collection_Date"] == "2024") | (metadata["Collection_Date"] == "2025")] # Dates we don't have

# def find_known_dates(x, df):
    
#     try:
#         date = metadata[metadata["BioSample"] == x]["Collection_Date"].values[0]
#     # print(date)
#         # print(date)
#         # if len(str(date)) == 4: # If this is just a year
#         #     date = search_collection_date(x, df)
#         # else:
#         date = dateutil.parser.parse(date, default=datetime(2000, 1, 1)) # .strftime("%Y-%m-%d") # If a date already exists
#         if date.day == dateutil.parser.parse("1/1/2000").day and date.month == dateutil.parser.parse("1/1/2000").month:
#             print("year only")
#             date = search_collection_date(x, df)
#         print("Success", date)
#     except:
#         date = search_collection_date(x, df) # If it's not parseable as a date
#     return date # If statement in lambda function will search for the "just year" values
        

# # years = ["2021", "2022", "2023", "2024", "2025"]
# # unknown_dates = metadata[metadata["Collection_Date"].isin(years)]
# # known_dates = metadata[~metadata["Collection_Date"].isin(years)]

# # Get new dates also 
# # new_dates = metadata["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank) if )

# updated_dates = metadata["BioSample"].apply(lambda x: find_known_dates(x, metadata)) # Update unknown dates, if possible
# metadata["Collection_Date"] = updated_dates

# # metadata = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # updated_unknown_dates = unknown_dates["BioSample"].apply(lambda x: search_collection_date(x, unknown_dates)) # Update unknown dates, if possible
# # unknown_dates["Collection_Date"] = updated_unknown_dates

# # metadata = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # Save this so we don't have to do it again

# # os.chdir(temp_files)
# # metadata.to_csv("metadata_genbank_" + date_range + ".csv")

# # display(metadata)

In [13]:
# os.chdir(temp_files)
# metadata.to_csv("metadata_genbank_" + date_range + ".csv")

# If no collection dates

# metadata_genbank["Collection_Date_Specific"] = metadata_genbank["Collection_Date"]

## Get host type

In [ ]:
# create a mask, where is True if the host does not exist
print(metadata["Host"])

mask = metadata["Host"].isna()

# choose between the original value and split isolate using the mask
metadata["Host"] = np.where(mask, metadata["isolate"].apply(lambda x: x if x != x or "/" not in x or len(x.split("/")) < 2 else x.split("/")[1]), metadata["Host"]) #  if "/" in metadata["isolate"] else metadata["Host"])
metadata["Host"] = metadata["Host"].apply(lambda x: x.lower() if x == x else x)

# print(metadata["Host"])

# Create animals ref if needed
unique_animals_all = sort_animals_andersen(metadata)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

# print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

os.chdir(home + "references/")

animals_ref = pd.read_csv("animals_ref.csv") # Upload animals ref

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# Unlikely for different_animals to be longer than the dataframe

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference 

print(metadata["Host"])
# print(metadata["isolate"])

0       cattle
1       cattle
2       cattle
3       cattle
4       cattle
        ...
135    chicken
136    chicken
137    chicken
138       duck
6
Name: Host, Length: 125, dtype: object
[]
                      avian               cattle        feline   other_mammal  \
0          great_horned_owl            dairy_cow           cat     deer mouse
1              common_raven               cattle  domestic_cat    house_mouse
2             cooper's_hawk  cattle milk product     feral_cat          skunk
3              coopers_hawk          bovine_milk        feline  striped_skunk
4                   peafowl              bovine   domestic-cat     norway rat
..                      ...                  ...           ...            ...
797               raxorbill                  NaN           NaN            NaN
798  von_schrenck's_bittern                  NaN           NaN            NaN
799           harris's_hawk                  NaN           NaN            NaN
800           eurasian_coot                  NaN           NaN            NaN
801                   layer                  NaN           NaN            NaN

          human         other  new
0    washington         mixed  NaN
1        nevada   environment  NaN
2       wyoming  multispecies  NaN
3    california       unknown  NaN
4      michigan             '  NaN
..          ...           ...  ...
797         NaN           NaN  NaN
798         NaN           NaN  NaN
799         NaN           NaN  NaN
800         NaN           NaN  NaN
801         NaN           NaN  NaN

[802 rows x 7 columns]
0       cattle
1       cattle
2       cattle
3       cattle
4       cattle
        ...
135    chicken
136    chicken
137    chicken
138       duck
6
Name: Host, Length: 125, dtype: object

In [36]:
# Get animals from animal reference
os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")
fix_animals_andersen(metadata, animals_ref) # Get host type

metadata["years"] = metadata["Collection_Date"].apply(lambda x: str(x).split("-")[0]) # Get year only from collection date

## Make names using all the attributes we collected

In [ ]:
for num, collection_date in enumerate(metadata["Collection_Date"]):
    if collection_date != collection_date: # if nan
         collection_date = "missing"
    try:
        print(collection_date)
        # If not a valid date, but has a year
        if collection_date.month == datetime.parser.parse("1/1/2000").month and collection_date.day == datetime.parser.parse("1/1/2000").day:
            year = collection_date.year
            metadata.loc[num, "Collection_Date"] = year
        else: # If actual date
            metadata.loc[num, "Collection_Date"] = collection_date
    except:
         metadata.loc[num, "Collection_Date"] = collection_date
        # else:
        #     try:
        #         parsed_date = dateutil.parser.parse(collection_date)
        #         date = parsed_date.strftime("%Y-%m-%d") # Make sure it doesn't default to today, if just a year
        #         metadata.loc[num, "Collection_Date"] = date
        #     except: # If no date at all
        #         metadata.loc[num, "Collection_Date"] = collection_date

    # metadata = metadata.dropna(thresh=2)

2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2024
2024
2024
2024
2025
2024
2024
2024
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2024
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2024
2024
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2024
2024
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025

In [ ]:
# Make names

metadata = metadata.fillna("") # Make sure the entire name does not become "NaN"

# + metadata["BioSample"] + "|" 
names = ">" + metadata["Run"] + "|" + "A/" + metadata["Host"] + "/" + metadata["name_state"] + "/" + metadata["Sample Name"] + "/" + metadata["years"].apply(lambda x: str(x)) + "|" + metadata["serotype"] + "|" + metadata["Geo_Location"] + "|" + metadata["Collection_Date"].apply(lambda x: str(x)) + "|" + metadata["Host_Type"] + "|" + metadata["Genotype"]

metadata["Name"] = names

# metadata_genbank.to_csv("metadata_genbank_named.csv")

display(metadata["Name"])

0      >SRR33993023|A/cattle/USA/25-016878-002/2025||...
1      >SRR33993024|A/cattle/USA/25-016866-004/2025||...
2      >SRR33993025|A/cattle/USA/25-016866-002/2025||...
3      >SRR33993026|A/cattle/USA/25-016847-007/2025||...
4      >SRR33993027|A/cattle/USA/25-016847-006/2025||...
                             ...
64                                      >|A////|||2025||
99                                      >|A////|||2024||
100                                     >|A////|||2025||
101                                     >|A////|||2025||
102                                     >|A////|||2025||
Name: Name, Length: 139, dtype: object

In [39]:
# Drop duplicate runs 
metadata = metadata.drop_duplicates(subset="Run", keep="first")

In [ ]:
print(metadata)
# metadata.to_csv("metadata_test.csv")

             Run Assay Type AvgSpotLen        Bases    BioProject  \
0    SRR33993023        WGS     148.15   68132847.0  PRJNA1102327
1    SRR33993024        WGS     148.15   63105544.0  PRJNA1102327
2    SRR33993025        WGS     148.28   46180111.0  PRJNA1102327
3    SRR33993026        WGS     147.53   47042737.0  PRJNA1102327
4    SRR33993027        WGS     147.76   65389924.0  PRJNA1102327
..           ...        ...        ...          ...           ...
135  SRR34270141        WGS     148.49  110079404.0   PRJNA980729
136  SRR34270142        WGS     146.95  112507279.0   PRJNA980729
137  SRR34270143        WGS     148.02  142063798.0   PRJNA980729
138  SRR34270144        WGS     147.58  379458191.0   PRJNA980729
6

        BioSample BioSampleModel        Bytes Center Name Collection_Date  \
0    SAMN49104730          Viral   22640539.0   USDA-NVSL            2025
1    SAMN49104729          Viral   21290975.0   USDA-NVSL            2025
2    SAMN49104728          Viral   15373063.0   USDA-NVSL            2025
3    SAMN49104727          Viral   15677039.0   USDA-NVSL            2025
4    SAMN49104726          Viral   21557873.0   USDA-NVSL            2025
..            ...            ...          ...         ...             ...
135  SAMN49684768          Viral   44080477.0   USDA-NVSL            2025
136  SAMN49684767          Viral   39407889.0   USDA-NVSL            2025
137  SAMN49684766          Viral   49911910.0   USDA-NVSL            2025
138  SAMN49684765          Viral  133079770.0   USDA-NVSL            2025
6                                                                    2025

     ...                        Genotype List Used, >=98.0%  \
0    ...  PB1:am4, PA:ea1, NA:ea1, PB2:am2.2, HA:ea1, NP...
1    ...  NS:am1.1, MP:ea1, PA:ea1, PB2:am2.2, NP:am8, N...
2    ...  NA:ea1, HA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, P...
3    ...  HA:ea1, MP:ea1, NS:am1.1, PA:ea1, NP:am8, NA:e...
4    ...  PB2:am2.2, MP:ea1, NA:ea1, HA:ea1, NS:am1.1, N...
..   ...                                                ...
135  ...  NP:am13, HA:ea3, NA:am4N1, PB1:ea3, PA:am4, MP...
136  ...  NS:ea3, MP:ea3, PA:am4, NP:am13, PB1:ea3, HA:e...
137  ...  NA:am4N1, NP:am13, HA:ea3, PB2:am24, MP:ea3, P...
138  ...  PB2:am24, NP:am13, NA:am4N1, PB1:ea3, PA:am4, ...
6    ...

                            Genotype Sample Title List  \
0    am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...
1    am1.1:22-010085-001:NS, ea1:22-003707-003:MP, ...
2    ea1:22-003707-003:NA, ea1:22-003707-003:HA, am...
3    ea1:22-003707-003:HA, ea1:22-003707-003:MP, am...
4    am2.2:22-010445-001:PB2, ea1:22-003707-003:MP,...
..                                                 ...
135  am13:24-030039-001:NP, ea3:22-013001-001:HA, a...
136  ea3:22-013001-001:NS, ea3:22-013001-001:MP, am...
137  am4N1:24-030039-001:NA, am13:24-030039-001:NP,...
138  am24:24-030039-001:PB2, am13:24-030039-001:NP,...
6

                           Genotype Percent Match List  \
0    99.34%, 98.93%, 98.79%, 98.51%, 98.30%, 99.00%...
1    99.05%, 98.88%, 98.75%, 98.47%, 99.06%, 98.94%...
2    98.94%, 98.12%, 99.05%, 98.47%, 98.78%, 99.21%...
3    98.30%, 98.78%, 98.93%, 98.88%, 98.93%, 98.65%...
4    98.51%, 98.78%, 98.65%, 98.30%, 98.93%, 98.93%...
..                                                 ...
135  99.80%, 99.24%, 99.29%, 99.34%, 99.54%, 99.90%...
136  98.81%, 100.00%, 99.89%, 99.73%, 99.33%, 99.35...
137  99.38%, 99.73%, 99.41%, 99.65%, 100.00%, 99.81...
138  99.65%, 99.73%, 99.39%, 99.28%, 99.89%, 100.00...
6

            Genotype Mismatch List Genotype Average Depth of Coverage List  \
0    15, 23, 17, 34, 29, 15, 8, 12       Ran on FASTA - No Coverage Report
1    8, 11, 27, 35, 14, 15, 18, 31       Ran on FASTA - No Coverage Report
2    15, 32, 8, 35, 12, 18, 14, 27       Ran on FASTA - No Coverage Report
3    29, 12, 9, 24, 16, 19, 35, 32       Ran on FASTA - No Coverage Report
4    34, 12, 19, 29, 9, 16, 24, 16       Ran on FASTA - No Coverage Report
..                             ...                                     ...
135       3, 13, 8, 15, 8, 1, 5, 7       Ran on FASTA - No Coverage Report
136      10, 0, 2, 4, 12, 11, 5, 8       Ran on FASTA - No Coverage Report
137      7, 4, 10, 8, 0, 4, 11, 13       Ran on FASTA - No Coverage Report
138      8, 4, 7, 13, 2, 0, 10, 11       Ran on FASTA - No Coverage Report
6

    Geo_Location Collection_Date_Specific Host_Type years  \
0            USA                     2025    cattle  2025
1            USA                     2025    cattle  2025
2            USA                     2025    cattle  2025
3            USA                     2025    cattle  2025
4            USA                     2025    cattle  2025
..           ...                      ...       ...   ...
135          USA                     2025     avian  2025
136          USA                     2025     avian  2025
137          USA                     2025     avian  2025
138          USA                     2025     avian  2025
6                                             other  2025

                                                  Name
0    >SRR33993023|A/cattle/USA/25-016878-002/2025||...
1    >SRR33993024|A/cattle/USA/25-016866-004/2025||...
2    >SRR33993025|A/cattle/USA/25-016866-002/2025||...
3    >SRR33993026|A/cattle/USA/25-016847-007/2025||...
4    >SRR33993027|A/cattle/USA/25-016847-006/2025||...
..                                                 ...
135  >SRR34270141|A/chicken/USA/25-015646-001/2025|...
136  >SRR34270142|A/chicken/USA/25-010529-003/2025|...
137  >SRR34270143|A/chicken/USA/25-010529-002/2025|...
138  >SRR34270144|A/duck/USA/25-010529-001/2025||US...
6                            >|A////2025|||2025|other|

[125 rows x 52 columns]

## Make FASTA files

In [42]:
# Get information to create the fasta files

fasta_folder = originals + "avian-influenza/fasta/"

os.chdir(fasta_folder)

segments = ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]
pairs = []
fasta_files = {}

for genotype in genotypes: # ["B3.13", "D1.1"]:
    for segment in segments:
        pair = genotype + "_" + segment
        pairs.append(pair)

for pair in pairs:
    fasta_files[pair] = [] # List to hold fasta files

for run in metadata["Run"].values: # For each run 
    for dirpath, dirs, files in os.walk(fasta_folder): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            # print(file_name)
            if run in file_name: # Note that there will be ~8 files total with that run name
                # Make a fasta file and put it in the list
                with open(file_name) as f:
                    lines = f.readlines()
                    sequence = lines[1] 
                    # Each run/segment pair has one sequence -- it's placed into a file with other run/segment pairs with the same segment and genotype
                    header = metadata[metadata["Run"] == run].loc[:, "Name"].values[0]
                    genotype = metadata[metadata["Run"] == run].loc[:, "Genotype"].values[0]
                    # print(header)
                    # print(genotype)
                    # break 
                    segment = file_name.split("_")[-2]
                    # Find the pair that corresponds to 
                    pair_name = genotype + "_" + segment
                    this_specific_fasta = []
                    for pair in pairs:
                        # print(pair)
                        # print(pair_name)
                        if pair_name == pair:
                            this_specific_fasta.append(header)
                            this_specific_fasta.append(sequence)
                            fasta_files[pair].append(this_specific_fasta)
                f.close()
        break

In [43]:
# print(fasta_files.keys())

In [ ]:
# Create fasta files 

os.chdir(originals + "complete/")
names = []
for pair in fasta_files.keys():
    output_path = originals + "complete/" + pair + "_" + date_range + "_andersen_updated.fasta"

    output_file = open(output_path, "w")
    for item in fasta_files[pair]:
        # for item in item:
        # item = fasta_files[pair]
        try:
            name = str(item[0].values[0]) # See if this is one we didn't have a collection date for
        except:
            name = str(item[0])
        print(name)
        names.append(name)
        # First is header, second is sequence
        # print(value)
        output_file.write(name + "\n")
        output_file.write(item[1])
    output_file.close()

print(len(names)/8)

>SRR34270263|A/red fox/USA/24-028269-001/2025||USA|2025|other_mammal|A3
>SRR34270263|A/red fox/USA/24-028269-001/2025||USA|2025|other_mammal|A3
>SRR34270263|A/red fox/USA/24-028269-001/2025||USA|2025|other_mammal|A3
>SRR34270263|A/red fox/USA/24-028269-001/2025||USA|2025|other_mammal|A3
>SRR34270263|A/red fox/USA/24-028269-001/2025||USA|2025|other_mammal|A3
>SRR34270263|A/red fox/USA/24-028269-001/2025||USA|2025|other_mammal|A3
>SRR34270263|A/red fox/USA/24-028269-001/2025||USA|2025|other_mammal|A3
>SRR34270263|A/red fox/USA/24-028269-001/2025||USA|2025|other_mammal|A3
>SRR34270253|A/red fox/USA/24-020141-001/2024||USA|2025|other_mammal|B3.2
>SRR34270253|A/red fox/USA/24-020141-001/2024||USA|2025|other_mammal|B3.2
>SRR34270253|A/red fox/USA/24-020141-001/2024||USA|2025|other_mammal|B3.2
>SRR34270253|A/red fox/USA/24-020141-001/2024||USA|2025|other_mammal|B3.2
>SRR34270253|A/red fox/USA/24-020141-001/2024||USA|2025|other_mammal|B3.2
>SRR34270253|A/red fox/USA/24-020141-001/2024||USA|2025|other_mammal|B3.2
>SRR34270253|A/red fox/USA/24-020141-001/2024||USA|2025|other_mammal|B3.2
>SRR34270253|A/red fox/USA/24-020141-001/2024||USA|2025|other_mammal|B3.2
>SRR34270254|A/red fox/USA/24-017742-001/2024||USA|2025|other_mammal|C2.1
>SRR34270256|A/bobcat/USA/24-009317-002/2025||USA|2025|feline|C2.1
>SRR34270257|A/bobcat/USA/24-009317-001/2025||USA|2025|feline|C2.1
>SRR34270264|A/harbor seal/USA/24-026395-001/2025||USA|2025|other_mammal|C2.1
>SRR34270254|A/red fox/USA/24-017742-001/2024||USA|2025|other_mammal|C2.1
>SRR34270256|A/bobcat/USA/24-009317-002/2025||USA|2025|feline|C2.1
>SRR34270257|A/bobcat/USA/24-009317-001/2025||USA|2025|feline|C2.1
>SRR34270264|A/harbor seal/USA/24-026395-001/2025||USA|2025|other_mammal|C2.1
>SRR34270254|A/red fox/USA/24-017742-001/2024||USA|2025|other_mammal|C2.1
>SRR34270256|A/bobcat/USA/24-009317-002/2025||USA|2025|feline|C2.1
>SRR34270257|A/bobcat/USA/24-009317-001/2025||USA|2025|feline|C2.1
>SRR34270264|A/harbor seal/USA/24-026395-001/2025||USA|2025|other_mammal|C2.1
>SRR34270254|A/red fox/USA/24-017742-001/2024||USA|2025|other_mammal|C2.1
>SRR34270256|A/bobcat/USA/24-009317-002/2025||USA|2025|feline|C2.1
>SRR34270257|A/bobcat/USA/24-009317-001/2025||USA|2025|feline|C2.1
>SRR34270264|A/harbor seal/USA/24-026395-001/2025||USA|2025|other_mammal|C2.1
>SRR34270254|A/red fox/USA/24-017742-001/2024||USA|2025|other_mammal|C2.1
>SRR34270256|A/bobcat/USA/24-009317-002/2025||USA|2025|feline|C2.1
>SRR34270257|A/bobcat/USA/24-009317-001/2025||USA|2025|feline|C2.1
>SRR34270264|A/harbor seal/USA/24-026395-001/2025||USA|2025|other_mammal|C2.1
>SRR34270254|A/red fox/USA/24-017742-001/2024||USA|2025|other_mammal|C2.1
>SRR34270256|A/bobcat/USA/24-009317-002/2025||USA|2025|feline|C2.1
>SRR34270257|A/bobcat/USA/24-009317-001/2025||USA|2025|feline|C2.1
>SRR34270264|A/harbor seal/USA/24-026395-001/2025||USA|2025|other_mammal|C2.1
>SRR34270254|A/red fox/USA/24-017742-001/2024||USA|2025|other_mammal|C2.1
>SRR34270256|A/bobcat/USA/24-009317-002/2025||USA|2025|feline|C2.1
>SRR34270257|A/bobcat/USA/24-009317-001/2025||USA|2025|feline|C2.1
>SRR34270264|A/harbor seal/USA/24-026395-001/2025||USA|2025|other_mammal|C2.1
>SRR34270254|A/red fox/USA/24-017742-001/2024||USA|2025|other_mammal|C2.1
>SRR34270256|A/bobcat/USA/24-009317-002/2025||USA|2025|feline|C2.1
>SRR34270257|A/bobcat/USA/24-009317-001/2025||USA|2025|feline|C2.1
>SRR34270264|A/harbor seal/USA/24-026395-001/2025||USA|2025|other_mammal|C2.1
>SRR33993023|A/cattle/USA/25-016878-002/2025||USA|2025|cattle|B3.13
>SRR33993024|A/cattle/USA/25-016866-004/2025||USA|2025|cattle|B3.13
>SRR33993025|A/cattle/USA/25-016866-002/2025||USA|2025|cattle|B3.13
>SRR33993026|A/cattle/USA/25-016847-007/2025||USA|2025|cattle|B3.13
>SRR33993027|A/cattle/USA/25-016847-006/2025||USA|2025|cattle|B3.13
>SRR33993028|A/cattle/USA/25-016847-004/2025||USA|2025|cattle|B3.13
>SRR33993041|A/cattle/USA/25-016745-002/2025||USA|2025|cattle|B3.13
>SRR33993043|A/cattle/USA/25-017370-002/2025||USA|2025|cattle|B3.13
>SRR33993045|A/cattle/USA/25-017364-002/2025||USA|2025|cattle|B3.13
>SRR33993046|A/cattle/USA/25-017364-001/2025||USA|2025|cattle|B3.13
>SRR33993048|A/cattle/USA/25-002509-001-tile/2025||USA|2025|cattle|B3.13
>SRR33993049|A/cattle/USA/25-017049-001/2025||USA|2025|cattle|B3.13
>SRR33993050|A/cattle/USA/25-016878-005/2025||USA|2025|cattle|B3.13
>SRR33993051|A/cattle/USA/25-016878-003/2025||USA|2025|cattle|B3.13
>SRR33993052|A/cattle/USA/25-016745-001/2025||USA|2025|cattle|B3.13
>SRR33993053|A/cattle/USA/25-016741-001/2025||USA|2025|cattle|B3.13
>SRR33993029|A/cattle/USA/25-017377-003/2025||USA|2025|cattle|B3.13
>SRR33993031|A/cattle/USA/25-017376-009/2025||USA|2025|cattle|B3.13
>SRR33993032|A/cattle/USA/25-017376-008/2025||USA|2025|cattle|B3.13
>SRR33993033|A/cattle/USA/25-017376-007/2025||USA|2025|cattle|B3.13
>SRR33993034|A/cattle/USA/25-017376-006/2025||USA|2024|cattle|B3.13
>SRR33993035|A/cattle/USA/25-017376-005/2025||USA|2024|cattle|B3.13
>SRR33993036|A/cattle/USA/25-017376-004/2025||USA|2024|cattle|B3.13
>SRR33993037|A/cattle/USA/25-017376-003/2025||USA|2024|cattle|B3.13
>SRR33993038|A/cattle/USA/25-017376-002/2025||USA|2025|cattle|B3.13
>SRR33993039|A/cattle/USA/25-017376-001/2024||USA|2024|cattle|B3.13
>SRR33993040|A/cattle/USA/25-017370-004/2024||USA|2024|cattle|B3.13
>SRR33993042|A/cattle/USA/25-017370-003/2024||USA|2024|cattle|B3.13
>SRR34270243|A/opossum/USA/24-011942-046/2025||USA|2025|other_mammal|B3.13
>SRR34270146|A/cattle/USA/25-014358-002/2025||USA|2025|cattle|B3.13
>SRR34270147|A/cattle/USA/25-014354-002/2025||USA|2025|cattle|B3.13
>SRR34270148|A/cattle/USA/25-013618-007/2025||USA|2025|cattle|B3.13
>SRR34270149|A/cattle/USA/25-012945-002/2025||USA|2025|cattle|B3.13
>SRR34270150|A/cattle/USA/25-017893-002/2025||USA|2025|cattle|B3.13
>SRR34270151|A/cattle/USA/25-017892-004/2025||USA|2025|cattle|B3.13
>SRR34270152|A/cattle/USA/25-017891-001/2025||USA|2025|cattle|B3.13
>SRR34270153|A/cattle/USA/25-017889-001/2025||USA|2025|cattle|B3.13
>SRR34270154|A/cattle/USA/25-017887-001/2025||USA|2025|cattle|B3.13
>SRR34270155|A/cattle/USA/25-017884-002/2025||USA|2025|cattle|B3.13
>SRR34270156|A/cattle/USA/25-017880-004/2025||USA|2024|cattle|B3.13
>SRR34270157|A/cattle/USA/25-017874-001/2025||USA|2025|cattle|B3.13
>SRR34270158|A/chicken/USA/25-017727-003/2025||USA|2025|avian|B3.13
>SRR34270159|A/duck/USA/25-017727-002/2025||USA|2025|avian|B3.13
>SRR34270160|A/cattle/USA/25-012939-004/2025||USA|2025|cattle|B3.13
>SRR34270161|A/chicken/USA/25-017727-001/2025||USA|2025|avian|B3.13
>SRR34270162|A/cattle/USA/25-017520-001/2025||USA|2025|cattle|B3.13
>SRR34270163|A/cattle/USA/25-017518-001/2025||USA|2025|cattle|B3.13
>SRR34270164|A/cattle/USA/25-017516-005/2025||USA|2025|cattle|B3.13
>SRR34270165|A/cattle/USA/25-017516-003/2025||USA|2025|cattle|B3.13
>SRR34270166|A/cattle/USA/25-017516-002/2025||USA|2025|cattle|B3.13
>SRR34270167|A/cattle/USA/25-017516-001/2024||USA|2025|cattle|B3.13
>SRR34270168|A/cattle/USA/25-017515-006/2025||USA|2025|cattle|B3.13
>SRR34270169|A/cattle/USA/25-017515-005/2025||USA|2025|cattle|B3.13
>SRR34270170|A/cattle/USA/25-017515-004/2025||USA|2025|cattle|B3.13
>SRR34270171|A/cattle/USA/25-010022-001/2025||USA|2025|cattle|B3.13
>SRR34270172|A/cattle/USA/25-017515-002/2025||USA|2025|cattle|B3.13
>SRR34270173|A/cattle/USA/25-017504-003/2025||USA|2025|cattle|B3.13
>SRR34270174|A/cattle/USA/25-017504-002/2025||USA|2024|cattle|B3.13
>SRR34270179|A/cattle/USA/25-017500-001/2025||USA|2025|cattle|B3.13
>SRR34270180|A/cattle/USA/25-015748-001/2025||USA|2025|cattle|B3.13
>SRR34270181|A/cattle/USA/25-015745-001/2025||USA|2025|cattle|B3.13
>SRR34270182|A/cattle/USA/24-036392-001/2025||USA|2025|cattle|B3.13
>SRR34270183|A/cattle/USA/25-015742-004/2025||USA|2025|cattle|B3.13
>SRR34270184|A/cattle/USA/25-015741-001/2025||USA|2025|cattle|B3.13
>SRR34270185|A/cattle/USA/25-015739-005/2025||USA|2025|cattle|B3.13
>SRR34270186|A/cattle/USA/25-015739-003/2025||USA|2025|cattle|B3.13
>SRR34270187|A/cattle/USA/25-015738-002/2025||USA|2025|cattle|B3.13
>SRR34270188|A/cattle/USA/25-015736-001/2025||USA|2025|cattle|B3.13
>SRR34270189|A/cattle/USA/25-015734-005/2024||USA|2024|cattle|B3.13
>SRR34270190|A/cattle/USA/25-015734-001/2024||USA|2024|cattle|B3.13
>SRR34270191|A/cattle/USA/25-015733-003/2025||USA|2025|cattle|B3.13
>SRR34270192|A/cattle/USA/25-015733-002/2025||USA|2025|cattle|B3.13
>SRR34270193|A/cattle/USA/24-033994-003/2025||USA|2025|cattle|B3.13
>SRR34270194|A/cattle/USA/25-015733-001/2025||USA|2025|cattle|B3.13
>SRR34270195|A/cattle/USA/25-015732-001/2025||USA|2025|cattle|B3.13
>SRR34270196|A/cattle/USA/25-015120-002/2025||USA|2025|cattle|B3.13
>SRR34270197|A/cattle/USA/25-015108-002/2025||USA|2025|cattle|B3.13
>SRR34270198|A/cattle/USA/25-015108-001/2025||USA|2025|cattle|B3.13
>SRR34270199|A/cattle/USA/25-015015-001/2025||USA|2025|cattle|B3.13
>SRR34270200|A/cattle/USA/25-015008-001/2025||USA|2025|cattle|B3.13
>SRR34270201|A/cattle/USA/25-015005-001/2025||USA|2025|cattle|B3.13
>SRR34270202|A/cattle/USA/25-015002-001/2025||USA|2025|cattle|B3.13
>SRR34270203|A/cattle/USA/25-014358-003/2025||USA|2025|cattle|B3.13
>SRR34270204|A/cattle/USA/24-033523-004/2024||USA|2024|cattle|B3.13
>SRR34270205|A/cattle/USA/24-030030-004/2024||USA|2024|cattle|B3.13
>SRR33993023|A/cattle/USA/25-016878-002/2025||USA|2025|cattle|B3.13
>SRR33993024|A/cattle/USA/25-016866-004/2025||USA|2025|cattle|B3.13
>SRR33993025|A/cattle/USA/25-016866-002/2025||USA|2025|cattle|B3.13
>SRR33993026|A/cattle/USA/25-016847-007/2025||USA|2025|cattle|B3.13
>SRR33993027|A/cattle/USA/25-016847-006/2025||USA|2025|cattle|B3.13
>SRR33993028|A/cattle/USA/25-016847-004/2025||USA|2025|cattle|B3.13
>SRR33993041|A/cattle/USA/25-016745-002/2025||USA|2025|cattle|B3.13
>SRR33993043|A/cattle/USA/25-017370-002/2025||USA|2025|cattle|B3.13
>SRR33993045|A/cattle/USA/25-017364-002/2025||USA|2025|cattle|B3.13
>SRR33993046|A/cattle/USA/25-017364-001/2025||USA|2025|cattle|B3.13
>SRR33993048|A/cattle/USA/25-002509-001-tile/2025||USA|2025|cattle|B3.13
>SRR33993049|A/cattle/USA/25-017049-001/2025||USA|2025|cattle|B3.13
>SRR33993050|A/cattle/USA/25-016878-005/2025||USA|2025|cattle|B3.13
>SRR33993051|A/cattle/USA/25-016878-003/2025||USA|2025|cattle|B3.13
>SRR33993052|A/cattle/USA/25-016745-001/2025||USA|2025|cattle|B3.13
>SRR33993053|A/cattle/USA/25-016741-001/2025||USA|2025|cattle|B3.13
>SRR33993029|A/cattle/USA/25-017377-003/2025||USA|2025|cattle|B3.13
>SRR33993031|A/cattle/USA/25-017376-009/2025||USA|2025|cattle|B3.13
>SRR33993032|A/cattle/USA/25-017376-008/2025||USA|2025|cattle|B3.13
>SRR33993033|A/cattle/USA/25-017376-007/2025||USA|2025|cattle|B3.13
>SRR33993034|A/cattle/USA/25-017376-006/2025||USA|2024|cattle|B3.13
>SRR33993035|A/cattle/USA/25-017376-005/2025||USA|2024|cattle|B3.13
>SRR33993036|A/cattle/USA/25-017376-004/2025||USA|2024|cattle|B3.13
>SRR33993037|A/cattle/USA/25-017376-003/2025||USA|2024|cattle|B3.13
>SRR33993038|A/cattle/USA/25-017376-002/2025||USA|2025|cattle|B3.13
>SRR33993039|A/cattle/USA/25-017376-001/2024||USA|2024|cattle|B3.13
>SRR33993040|A/cattle/USA/25-017370-004/2024||USA|2024|cattle|B3.13
>SRR33993042|A/cattle/USA/25-017370-003/2024||USA|2024|cattle|B3.13
>SRR34270243|A/opossum/USA/24-011942-046/2025||USA|2025|other_mammal|B3.13
>SRR34270146|A/cattle/USA/25-014358-002/2025||USA|2025|cattle|B3.13
>SRR34270147|A/cattle/USA/25-014354-002/2025||USA|2025|cattle|B3.13
>SRR34270148|A/cattle/USA/25-013618-007/2025||USA|2025|cattle|B3.13
>SRR34270149|A/cattle/USA/25-012945-002/2025||USA|2025|cattle|B3.13
>SRR34270150|A/cattle/USA/25-017893-002/2025||USA|2025|cattle|B3.13
>SRR34270151|A/cattle/USA/25-017892-004/2025||USA|2025|cattle|B3.13
>SRR34270152|A/cattle/USA/25-017891-001/2025||USA|2025|cattle|B3.13
>SRR34270153|A/cattle/USA/25-017889-001/2025||USA|2025|cattle|B3.13
>SRR34270154|A/cattle/USA/25-017887-001/2025||USA|2025|cattle|B3.13
>SRR34270155|A/cattle/USA/25-017884-002/2025||USA|2025|cattle|B3.13
>SRR34270156|A/cattle/USA/25-017880-004/2025||USA|2024|cattle|B3.13
>SRR34270157|A/cattle/USA/25-017874-001/2025||USA|2025|cattle|B3.13
>SRR34270158|A/chicken/USA/25-017727-003/2025||USA|2025|avian|B3.13
>SRR34270159|A/duck/USA/25-017727-002/2025||USA|2025|avian|B3.13
>SRR34270160|A/cattle/USA/25-012939-004/2025||USA|2025|cattle|B3.13
>SRR34270161|A/chicken/USA/25-017727-001/2025||USA|2025|avian|B3.13
>SRR34270162|A/cattle/USA/25-017520-001/2025||USA|2025|cattle|B3.13
>SRR34270163|A/cattle/USA/25-017518-001/2025||USA|2025|cattle|B3.13
>SRR34270164|A/cattle/USA/25-017516-005/2025||USA|2025|cattle|B3.13
>SRR34270165|A/cattle/USA/25-017516-003/2025||USA|2025|cattle|B3.13
>SRR34270166|A/cattle/USA/25-017516-002/2025||USA|2025|cattle|B3.13
>SRR34270167|A/cattle/USA/25-017516-001/2024||USA|2025|cattle|B3.13
>SRR34270168|A/cattle/USA/25-017515-006/2025||USA|2025|cattle|B3.13
>SRR34270169|A/cattle/USA/25-017515-005/2025||USA|2025|cattle|B3.13
>SRR34270170|A/cattle/USA/25-017515-004/2025||USA|2025|cattle|B3.13
>SRR34270171|A/cattle/USA/25-010022-001/2025||USA|2025|cattle|B3.13
>SRR34270172|A/cattle/USA/25-017515-002/2025||USA|2025|cattle|B3.13
>SRR34270173|A/cattle/USA/25-017504-003/2025||USA|2025|cattle|B3.13
>SRR34270174|A/cattle/USA/25-017504-002/2025||USA|2024|cattle|B3.13
>SRR34270179|A/cattle/USA/25-017500-001/2025||USA|2025|cattle|B3.13
>SRR34270180|A/cattle/USA/25-015748-001/2025||USA|2025|cattle|B3.13
>SRR34270181|A/cattle/USA/25-015745-001/2025||USA|2025|cattle|B3.13
>SRR34270182|A/cattle/USA/24-036392-001/2025||USA|2025|cattle|B3.13
>SRR34270183|A/cattle/USA/25-015742-004/2025||USA|2025|cattle|B3.13
>SRR34270184|A/cattle/USA/25-015741-001/2025||USA|2025|cattle|B3.13
>SRR34270185|A/cattle/USA/25-015739-005/2025||USA|2025|cattle|B3.13
>SRR34270186|A/cattle/USA/25-015739-003/2025||USA|2025|cattle|B3.13
>SRR34270187|A/cattle/USA/25-015738-002/2025||USA|2025|cattle|B3.13
>SRR34270188|A/cattle/USA/25-015736-001/2025||USA|2025|cattle|B3.13
>SRR34270189|A/cattle/USA/25-015734-005/2024||USA|2024|cattle|B3.13
>SRR34270190|A/cattle/USA/25-015734-001/2024||USA|2024|cattle|B3.13
>SRR34270191|A/cattle/USA/25-015733-003/2025||USA|2025|cattle|B3.13
>SRR34270192|A/cattle/USA/25-015733-002/2025||USA|2025|cattle|B3.13
>SRR34270193|A/cattle/USA/24-033994-003/2025||USA|2025|cattle|B3.13
>SRR34270194|A/cattle/USA/25-015733-001/2025||USA|2025|cattle|B3.13
>SRR34270195|A/cattle/USA/25-015732-001/2025||USA|2025|cattle|B3.13
>SRR34270196|A/cattle/USA/25-015120-002/2025||USA|2025|cattle|B3.13
>SRR34270197|A/cattle/USA/25-015108-002/2025||USA|2025|cattle|B3.13
>SRR34270198|A/cattle/USA/25-015108-001/2025||USA|2025|cattle|B3.13
>SRR34270199|A/cattle/USA/25-015015-001/2025||USA|2025|cattle|B3.13
>SRR34270200|A/cattle/USA/25-015008-001/2025||USA|2025|cattle|B3.13
>SRR34270201|A/cattle/USA/25-015005-001/2025||USA|2025|cattle|B3.13
>SRR34270202|A/cattle/USA/25-015002-001/2025||USA|2025|cattle|B3.13
>SRR34270203|A/cattle/USA/25-014358-003/2025||USA|2025|cattle|B3.13
>SRR34270204|A/cattle/USA/24-033523-004/2024||USA|2024|cattle|B3.13
>SRR34270205|A/cattle/USA/24-030030-004/2024||USA|2024|cattle|B3.13
>SRR33993023|A/cattle/USA/25-016878-002/2025||USA|2025|cattle|B3.13
>SRR33993024|A/cattle/USA/25-016866-004/2025||USA|2025|cattle|B3.13
>SRR33993025|A/cattle/USA/25-016866-002/2025||USA|2025|cattle|B3.13
>SRR33993026|A/cattle/USA/25-016847-007/2025||USA|2025|cattle|B3.13
>SRR33993027|A/cattle/USA/25-016847-006/2025||USA|2025|cattle|B3.13
>SRR33993028|A/cattle/USA/25-016847-004/2025||USA|2025|cattle|B3.13
>SRR33993041|A/cattle/USA/25-016745-002/2025||USA|2025|cattle|B3.13
>SRR33993043|A/cattle/USA/25-017370-002/2025||USA|2025|cattle|B3.13
>SRR33993045|A/cattle/USA/25-017364-002/2025||USA|2025|cattle|B3.13
>SRR33993046|A/cattle/USA/25-017364-001/2025||USA|2025|cattle|B3.13
>SRR33993048|A/cattle/USA/25-002509-001-tile/2025||USA|2025|cattle|B3.13
>SRR33993049|A/cattle/USA/25-017049-001/2025||USA|2025|cattle|B3.13
>SRR33993050|A/cattle/USA/25-016878-005/2025||USA|2025|cattle|B3.13
>SRR33993051|A/cattle/USA/25-016878-003/2025||USA|2025|cattle|B3.13
>SRR33993052|A/cattle/USA/25-016745-001/2025||USA|2025|cattle|B3.13
>SRR33993053|A/cattle/USA/25-016741-001/2025||USA|2025|cattle|B3.13
>SRR33993029|A/cattle/USA/25-017377-003/2025||USA|2025|cattle|B3.13
>SRR33993031|A/cattle/USA/25-017376-009/2025||USA|2025|cattle|B3.13
>SRR33993032|A/cattle/USA/25-017376-008/2025||USA|2025|cattle|B3.13
>SRR33993033|A/cattle/USA/25-017376-007/2025||USA|2025|cattle|B3.13
>SRR33993034|A/cattle/USA/25-017376-006/2025||USA|2024|cattle|B3.13
>SRR33993035|A/cattle/USA/25-017376-005/2025||USA|2024|cattle|B3.13
>SRR33993036|A/cattle/USA/25-017376-004/2025||USA|2024|cattle|B3.13
>SRR33993037|A/cattle/USA/25-017376-003/2025||USA|2024|cattle|B3.13
>SRR33993038|A/cattle/USA/25-017376-002/2025||USA|2025|cattle|B3.13
>SRR33993039|A/cattle/USA/25-017376-001/2024||USA|2024|cattle|B3.13
>SRR33993040|A/cattle/USA/25-017370-004/2024||USA|2024|cattle|B3.13
>SRR33993042|A/cattle/USA/25-017370-003/2024||USA|2024|cattle|B3.13
>SRR34270243|A/opossum/USA/24-011942-046/2025||USA|2025|other_mammal|B3.13
>SRR34270146|A/cattle/USA/25-014358-002/2025||USA|2025|cattle|B3.13
>SRR34270147|A/cattle/USA/25-014354-002/2025||USA|2025|cattle|B3.13
>SRR34270148|A/cattle/USA/25-013618-007/2025||USA|2025|cattle|B3.13
>SRR34270149|A/cattle/USA/25-012945-002/2025||USA|2025|cattle|B3.13
>SRR34270150|A/cattle/USA/25-017893-002/2025||USA|2025|cattle|B3.13
>SRR34270151|A/cattle/USA/25-017892-004/2025||USA|2025|cattle|B3.13
>SRR34270152|A/cattle/USA/25-017891-001/2025||USA|2025|cattle|B3.13
>SRR34270153|A/cattle/USA/25-017889-001/2025||USA|2025|cattle|B3.13
>SRR34270154|A/cattle/USA/25-017887-001/2025||USA|2025|cattle|B3.13
>SRR34270155|A/cattle/USA/25-017884-002/2025||USA|2025|cattle|B3.13
>SRR34270156|A/cattle/USA/25-017880-004/2025||USA|2024|cattle|B3.13
>SRR34270157|A/cattle/USA/25-017874-001/2025||USA|2025|cattle|B3.13
>SRR34270158|A/chicken/USA/25-017727-003/2025||USA|2025|avian|B3.13
>SRR34270159|A/duck/USA/25-017727-002/2025||USA|2025|avian|B3.13
>SRR34270160|A/cattle/USA/25-012939-004/2025||USA|2025|cattle|B3.13
>SRR34270161|A/chicken/USA/25-017727-001/2025||USA|2025|avian|B3.13
>SRR34270162|A/cattle/USA/25-017520-001/2025||USA|2025|cattle|B3.13
>SRR34270163|A/cattle/USA/25-017518-001/2025||USA|2025|cattle|B3.13
>SRR34270164|A/cattle/USA/25-017516-005/2025||USA|2025|cattle|B3.13
>SRR34270165|A/cattle/USA/25-017516-003/2025||USA|2025|cattle|B3.13
>SRR34270166|A/cattle/USA/25-017516-002/2025||USA|2025|cattle|B3.13
>SRR34270167|A/cattle/USA/25-017516-001/2024||USA|2025|cattle|B3.13
>SRR34270168|A/cattle/USA/25-017515-006/2025||USA|2025|cattle|B3.13
>SRR34270169|A/cattle/USA/25-017515-005/2025||USA|2025|cattle|B3.13
>SRR34270170|A/cattle/USA/25-017515-004/2025||USA|2025|cattle|B3.13
>SRR34270171|A/cattle/USA/25-010022-001/2025||USA|2025|cattle|B3.13
>SRR34270172|A/cattle/USA/25-017515-002/2025||USA|2025|cattle|B3.13
>SRR34270173|A/cattle/USA/25-017504-003/2025||USA|2025|cattle|B3.13
>SRR34270174|A/cattle/USA/25-017504-002/2025||USA|2024|cattle|B3.13
>SRR34270179|A/cattle/USA/25-017500-001/2025||USA|2025|cattle|B3.13
>SRR34270180|A/cattle/USA/25-015748-001/2025||USA|2025|cattle|B3.13
>SRR34270181|A/cattle/USA/25-015745-001/2025||USA|2025|cattle|B3.13
>SRR34270182|A/cattle/USA/24-036392-001/2025||USA|2025|cattle|B3.13
>SRR34270183|A/cattle/USA/25-015742-004/2025||USA|2025|cattle|B3.13
>SRR34270184|A/cattle/USA/25-015741-001/2025||USA|2025|cattle|B3.13
>SRR34270185|A/cattle/USA/25-015739-005/2025||USA|2025|cattle|B3.13
>SRR34270186|A/cattle/USA/25-015739-003/2025||USA|2025|cattle|B3.13
>SRR34270187|A/cattle/USA/25-015738-002/2025||USA|2025|cattle|B3.13
>SRR34270188|A/cattle/USA/25-015736-001/2025||USA|2025|cattle|B3.13
>SRR34270189|A/cattle/USA/25-015734-005/2024||USA|2024|cattle|B3.13
>SRR34270190|A/cattle/USA/25-015734-001/2024||USA|2024|cattle|B3.13
>SRR34270191|A/cattle/USA/25-015733-003/2025||USA|2025|cattle|B3.13
>SRR34270192|A/cattle/USA/25-015733-002/2025||USA|2025|cattle|B3.13

## De-Duplication

In [ ]:
# De-duplication 

gisaid = downloads + "GISAID/complete/all_genotypes/" + date_range + "_all_genotypes_Antarctica_North_America_South_America/"

os.chdir(gisaid)

# Gisaid 
dfs_gisaid_list = []
dfs_gisaid = create_dataframes(gisaid)
dfs_gisaid_list.append(dfs_gisaid)

# dfs_gisaid = {}
# for df_gisaid in dfs_gisaid_list:
#     dfs_gisaid = dfs_gisaid | df_gisaid
# # dfs_gisaid2 = create_dataframes(gisaid2)

A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
Minor92_HA
Minor92_MP
Minor92_NA
Minor92_NP
Minor92_NS
Minor92_PA
Minor92_PB1
Minor92_PB2

In [ ]:
# Do the same with Andersen 

dfs_andersen = create_dataframes(originals + "complete/all_genotypes/" + date_range + "_all_genotypes/")

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
D2.1_HA
D2.1_MP
D2.1_NA
D2.1_NP
D2.1_NS
D2.1_PA
D2.1_PB1
D2.1_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor101_HA
Minor101_MP
Minor101_NA
Minor101_NP
Minor101_NS
Minor101_PA
Minor101_PB1
Minor101_PB2
Minor102_HA
Minor102_MP
Minor102_NA
Minor102_NP
Minor102_NS
Minor102_PA
Minor102_PB1
Minor102_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor104_HA
Minor104_MP
Minor104_NA
Minor104_NP
Minor104_NS
Minor104_PA
Minor104_PB1
Minor104_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor106_HA
Minor106_MP
Minor106_NA
Minor106_NP
Minor106_NS
Minor106_PA
Minor106_PB1
Minor106_PB2
Minor10_HA
Minor10_MP
Minor10_NA
Minor10_NP
Minor10_NS
Minor10_PA
Minor10_PB1
Minor10_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor16_HA
Minor16_MP
Minor16_NA
Minor16_NP
Minor16_NS
Minor16_PA
Minor16_PB1
Minor16_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor18_HA
Minor18_MP
Minor18_NA
Minor18_NP
Minor18_NS
Minor18_PA
Minor18_PB1
Minor18_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor24_HA
Minor24_MP
Minor24_NA
Minor24_NP
Minor24_NS
Minor24_PA
Minor24_PB1
Minor24_PB2
Minor25_HA
Minor25_MP
Minor25_NA
Minor25_NP
Minor25_NS
Minor25_PA
Minor25_PB1
Minor25_PB2
Minor26_HA
Minor26_MP
Minor26_NA
Minor26_NP
Minor26_NS
Minor26_PA
Minor26_PB1
Minor26_PB2
Minor27_HA
Minor27_MP
Minor27_NA
Minor27_NP
Minor27_NS
Minor27_PA
Minor27_PB1
Minor27_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor29_HA
Minor29_MP
Minor29_NA
Minor29_NP
Minor29_NS
Minor29_PA
Minor29_PB1
Minor29_PB2
Minor30_HA
Minor30_MP
Minor30_NA
Minor30_NP
Minor30_NS
Minor30_PA
Minor30_PB1
Minor30_PB2
Minor31_HA
Minor31_MP
Minor31_NA
Minor31_NP
Minor31_NS
Minor31_PA
Minor31_PB1
Minor31_PB2
Minor32_HA
Minor32_MP
Minor32_NA
Minor32_NP
Minor32_NS
Minor32_PA
Minor32_PB1
Minor32_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor37_HA
Minor37_MP
Minor37_NA
Minor37_NP
Minor37_NS
Minor37_PA
Minor37_PB1
Minor37_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor39_HA
Minor39_MP
Minor39_NA
Minor39_NP
Minor39_NS
Minor39_PA
Minor39_PB1
Minor39_PB2
Minor40_HA
Minor40_MP
Minor40_NA
Minor40_NP
Minor40_NS
Minor40_PA
Minor40_PB1
Minor40_PB2
Minor41_HA
Minor41_MP
Minor41_NA
Minor41_NP
Minor41_NS
Minor41_PA
Minor41_PB1
Minor41_PB2
Minor42_HA
Minor42_MP
Minor42_NA
Minor42_NP
Minor42_NS
Minor42_PA
Minor42_PB1
Minor42_PB2
Minor43_HA
Minor43_MP
Minor43_NA
Minor43_NP
Minor43_NS
Minor43_PA
Minor43_PB1
Minor43_PB2
Minor44_HA
Minor44_MP
Minor44_NA
Minor44_NP
Minor44_NS
Minor44_PA
Minor44_PB1
Minor44_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor46_HA
Minor46_MP
Minor46_NA
Minor46_NP
Minor46_NS
Minor46_PA
Minor46_PB1
Minor46_PB2
Minor47_HA
Minor47_MP
Minor47_NA
Minor47_NP
Minor47_NS
Minor47_PA
Minor47_PB1
Minor47_PB2
Minor48_HA
Minor48_MP
Minor48_NA
Minor48_NP
Minor48_NS
Minor48_PA
Minor48_PB1
Minor48_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor52_HA
Minor52_MP
Minor52_NA
Minor52_NP
Minor52_NS
Minor52_PA
Minor52_PB1
Minor52_PB2
Minor53_HA
Minor53_MP
Minor53_NA
Minor53_NP
Minor53_NS
Minor53_PA
Minor53_PB1
Minor53_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor56_HA
Minor56_MP
Minor56_NA
Minor56_NP
Minor56_NS
Minor56_PA
Minor56_PB1
Minor56_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor67_HA
Minor67_MP
Minor67_NA
Minor67_NP
Minor67_NS
Minor67_PA
Minor67_PB1
Minor67_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor71_HA
Minor71_MP
Minor71_NA
Minor71_NP
Minor71_NS
Minor71_PA
Minor71_PB1
Minor71_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor74_HA
Minor74_MP
Minor74_NA
Minor74_NP
Minor74_NS
Minor74_PA
Minor74_PB1
Minor74_PB2
Minor75_HA
Minor75_MP
Minor75_NA
Minor75_NP
Minor75_NS
Minor75_PA
Minor75_PB1
Minor75_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor78_HA
Minor78_MP
Minor78_NA
Minor78_NP
Minor78_NS
Minor78_PA
Minor78_PB1
Minor78_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor80_HA
Minor80_MP
Minor80_NA
Minor80_NP
Minor80_NS
Minor80_PA
Minor80_PB1
Minor80_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor82_HA
Minor82_MP
Minor82_NA
Minor82_NP
Minor82_NS
Minor82_PA
Minor82_PB1
Minor82_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor84_HA
Minor84_MP
Minor84_NA
Minor84_NP
Minor84_NS
Minor84_PA
Minor84_PB1
Minor84_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor92_HA
Minor92_MP
Minor92_NA
Minor92_NP
Minor92_NS
Minor92_PA
Minor92_PB1
Minor92_PB2
Minor93_HA
Minor93_MP
Minor93_NA
Minor93_NP
Minor93_NS
Minor93_PA
Minor93_PB1
Minor93_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor95_HA
Minor95_MP
Minor95_NA
Minor95_NP
Minor95_NS
Minor95_PA
Minor95_PB1
Minor95_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
Minor98_HA
Minor98_MP
Minor98_NA
Minor98_NP
Minor98_NS
Minor98_PA
Minor98_PB1
Minor98_PB2
Minor99_HA
Minor99_MP
Minor99_NA
Minor99_NP
Minor99_NS
Minor99_PA
Minor99_PB1
Minor99_PB2

In [50]:
for key in dfs_andersen.keys():
    dataframes = dfs_andersen[key]
    print(key)

print(dfs_andersen)

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
D2.1_HA
D2.1_MP
D2.1_NA
D2.1_NP
D2.1_NS
D2.1_PA
D2.1_PB1
D2.1_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor101_HA
Minor101_MP
Minor101_NA
Minor101_NP
Minor101_NS
Minor101_PA
Minor101_PB1
Minor101_PB2
Minor102_HA
Minor102_MP
Minor102_NA
Minor102_NP
Minor102_NS
Minor102_PA
Minor102_PB1
Minor102_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor104_HA
Minor104_MP
Minor104_NA
Minor104_NP
Minor104_NS
Minor104_PA
Minor104_PB1
Minor104_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor106_HA
Minor106_MP
Minor106_NA
Minor106_NP
Minor106_NS
Minor106_PA
Minor106_PB1
Minor106_PB2
Minor10_HA
Minor10_MP
Minor10_NA
Minor10_NP
Minor10_NS
Minor10_PA
Minor10_PB1
Minor10_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor16_HA
Minor16_MP
Minor16_NA
Minor16_NP
Minor16_NS
Minor16_PA
Minor16_PB1
Minor16_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor18_HA
Minor18_MP
Minor18_NA
Minor18_NP
Minor18_NS
Minor18_PA
Minor18_PB1
Minor18_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor24_HA
Minor24_MP
Minor24_NA
Minor24_NP
Minor24_NS
Minor24_PA
Minor24_PB1
Minor24_PB2
Minor25_HA
Minor25_MP
Minor25_NA
Minor25_NP
Minor25_NS
Minor25_PA
Minor25_PB1
Minor25_PB2
Minor26_HA
Minor26_MP
Minor26_NA
Minor26_NP
Minor26_NS
Minor26_PA
Minor26_PB1
Minor26_PB2
Minor27_HA
Minor27_MP
Minor27_NA
Minor27_NP
Minor27_NS
Minor27_PA
Minor27_PB1
Minor27_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor29_HA
Minor29_MP
Minor29_NA
Minor29_NP
Minor29_NS
Minor29_PA
Minor29_PB1
Minor29_PB2
Minor30_HA
Minor30_MP
Minor30_NA
Minor30_NP
Minor30_NS
Minor30_PA
Minor30_PB1
Minor30_PB2
Minor31_HA
Minor31_MP
Minor31_NA
Minor31_NP
Minor31_NS
Minor31_PA
Minor31_PB1
Minor31_PB2
Minor32_HA
Minor32_MP
Minor32_NA
Minor32_NP
Minor32_NS
Minor32_PA
Minor32_PB1
Minor32_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor37_HA
Minor37_MP
Minor37_NA
Minor37_NP
Minor37_NS
Minor37_PA
Minor37_PB1
Minor37_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor39_HA
Minor39_MP
Minor39_NA
Minor39_NP
Minor39_NS
Minor39_PA
Minor39_PB1
Minor39_PB2
Minor40_HA
Minor40_MP
Minor40_NA
Minor40_NP
Minor40_NS
Minor40_PA
Minor40_PB1
Minor40_PB2
Minor41_HA
Minor41_MP
Minor41_NA
Minor41_NP
Minor41_NS
Minor41_PA
Minor41_PB1
Minor41_PB2
Minor42_HA
Minor42_MP
Minor42_NA
Minor42_NP
Minor42_NS
Minor42_PA
Minor42_PB1
Minor42_PB2
Minor43_HA
Minor43_MP
Minor43_NA
Minor43_NP
Minor43_NS
Minor43_PA
Minor43_PB1
Minor43_PB2
Minor44_HA
Minor44_MP
Minor44_NA
Minor44_NP
Minor44_NS
Minor44_PA
Minor44_PB1
Minor44_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor46_HA
Minor46_MP
Minor46_NA
Minor46_NP
Minor46_NS
Minor46_PA
Minor46_PB1
Minor46_PB2
Minor47_HA
Minor47_MP
Minor47_NA
Minor47_NP
Minor47_NS
Minor47_PA
Minor47_PB1
Minor47_PB2
Minor48_HA
Minor48_MP
Minor48_NA
Minor48_NP
Minor48_NS
Minor48_PA
Minor48_PB1
Minor48_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor52_HA
Minor52_MP
Minor52_NA
Minor52_NP
Minor52_NS
Minor52_PA
Minor52_PB1
Minor52_PB2
Minor53_HA
Minor53_MP
Minor53_NA
Minor53_NP
Minor53_NS
Minor53_PA
Minor53_PB1
Minor53_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor56_HA
Minor56_MP
Minor56_NA
Minor56_NP
Minor56_NS
Minor56_PA
Minor56_PB1
Minor56_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor67_HA
Minor67_MP
Minor67_NA
Minor67_NP
Minor67_NS
Minor67_PA
Minor67_PB1
Minor67_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor71_HA
Minor71_MP
Minor71_NA
Minor71_NP
Minor71_NS
Minor71_PA
Minor71_PB1
Minor71_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor74_HA
Minor74_MP
Minor74_NA
Minor74_NP
Minor74_NS
Minor74_PA
Minor74_PB1
Minor74_PB2
Minor75_HA
Minor75_MP
Minor75_NA
Minor75_NP
Minor75_NS
Minor75_PA
Minor75_PB1
Minor75_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor78_HA
Minor78_MP
Minor78_NA
Minor78_NP
Minor78_NS
Minor78_PA
Minor78_PB1
Minor78_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor80_HA
Minor80_MP
Minor80_NA
Minor80_NP
Minor80_NS
Minor80_PA
Minor80_PB1
Minor80_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor82_HA
Minor82_MP
Minor82_NA
Minor82_NP
Minor82_NS
Minor82_PA
Minor82_PB1
Minor82_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor84_HA
Minor84_MP
Minor84_NA
Minor84_NP
Minor84_NS
Minor84_PA
Minor84_PB1
Minor84_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor92_HA
Minor92_MP
Minor92_NA
Minor92_NP
Minor92_NS
Minor92_PA
Minor92_PB1
Minor92_PB2
Minor93_HA
Minor93_MP
Minor93_NA
Minor93_NP
Minor93_NS
Minor93_PA
Minor93_PB1
Minor93_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor95_HA
Minor95_MP
Minor95_NA
Minor95_NP
Minor95_NS
Minor95_PA
Minor95_PB1
Minor95_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
Minor98_HA
Minor98_MP
Minor98_NA
Minor98_NP
Minor98_NS
Minor98_PA
Minor98_PB1
Minor98_PB2
Minor99_HA
Minor99_MP
Minor99_NA
Minor99_NP
Minor99_NS
Minor99_PA
Minor99_PB1
Minor99_PB2
defaultdict(<class 'list'>, {'A1_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A3_HA': [  isolate_partial                                        full_header  \
0      028269-001  >SRR34270263|A/red fox/USA/24-028269-001/2025|...

                                            sequence
0  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...  ], 'A3_MP': [  isolate_partial                                        full_header  \
0      028269-001  >SRR34270263|A/red fox/USA/24-028269-001/2025|...

                                            sequence
0  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...  ], 'A3_NA': [  isolate_partial                                        full_header  \
0      028269-001  >SRR34270263|A/red fox/USA/24-028269-001/2025|...

                                            sequence
0  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...  ], 'A3_NP': [  isolate_partial                                        full_header  \
0      028269-001  >SRR34270263|A/red fox/USA/24-028269-001/2025|...

                                            sequence
0  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...  ], 'A3_NS': [  isolate_partial                                        full_header  \
0      028269-001  >SRR34270263|A/red fox/USA/24-028269-001/2025|...

                                            sequence
0  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...  ], 'A3_PA': [  isolate_partial                                        full_header  \
0      028269-001  >SRR34270263|A/red fox/USA/24-028269-001/2025|...

                                            sequence
0  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...  ], 'A3_PB1': [  isolate_partial                                        full_header  \
0      028269-001  >SRR34270263|A/red fox/USA/24-028269-001/2025|...

                                            sequence
0  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...  ], 'A3_PB2': [  isolate_partial                                        full_header  \
0      028269-001  >SRR34270263|A/red fox/USA/24-028269-001/2025|...

                                            sequence
0  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...  ], 'A4_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A4_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A5_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A6_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.1_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.2_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B1.3_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.1_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B2.2_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'B3.10_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]

In [51]:
print(len(list(dfs_gisaid.keys())))
print(len(list(dfs_andersen.keys())))

56
968

In [ ]:
# Merge dataframes and drop duplicates

full_dfs = defaultdict(list)

for i, andersen_key in enumerate(dfs_andersen.keys()):
    if len(dfs_andersen[andersen_key]) > 0:
        for j, gisaid_key in enumerate(dfs_gisaid.keys()):
            if andersen_key == gisaid_key:
                andersen_df = dfs_andersen[andersen_key][0]
                print(len(andersen_df))
                # print(andersen_df)
                gisaid_df = dfs_gisaid[gisaid_key][0]
                print(len(gisaid_df))
                # gisaid2_df = dfs_gisaid2[gisaid2_key][0]

                # print(pd.concat([gisaid_df, andersen_df]).drop_duplicates())

                full_df = pd.concat([andersen_df, gisaid_df], ignore_index=True)
                print("len full df:", len(full_df))
                # test = len(full_df.drop_duplicates(subset="isolate_partial"))

                dedup_df = full_df.drop_duplicates(subset="isolate_partial", keep="last")

                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print(full_df)
                
                # print("Keeping nothing: ", test)
                
                print("len deduplicated:", len(dedup_df))
                full_dfs[andersen_key].append(dedup_df)
            # else:
                # gisaid.add(gisaid_key)
                # andersen.add(andersen_key)
    
    # break 


# print(full_dfs)
# print(len(full_dfs))
# print(319*8)
# print(len(same))
# print(len(andersen))
# print(len(gisaid))

1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
85
91
len full df: 176
len deduplicated: 108
85
91
len full df: 176
len deduplicated: 108
85
91
len full df: 176
len deduplicated: 108
85
91
len full df: 176
len deduplicated: 108
85
91
len full df: 176
len deduplicated: 108
85
91
len full df: 176
len deduplicated: 108
85
91
len full df: 176
len deduplicated: 108
85
91
len full df: 176
len deduplicated: 108
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
31
27
len full df: 58
len deduplicated: 35
31
27
len full df: 58
len deduplicated: 35
31
27
len full df: 58
len deduplicated: 35
31
27
len full df: 58
len deduplicated: 35
31
27
len full df: 58
len deduplicated: 35
31
27
len full df: 58
len deduplicated: 35
31
27
len full df: 58
len deduplicated: 35
31
27
len full df: 58
len deduplicated: 35
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1

In [53]:
# # If none in one database, only use the other and drop duplicates

# full_dfs = defaultdict(list)
# for key in dfs_andersen.keys():
#     print(key)
# # for key in ["D1.3"]:
#     dataframes = dfs_andersen[key]
#     for i, df in enumerate(dataframes):
#         print(i)
#         try:
#             full_df = df.merge(dfs_gisaid[key][i], how="outer")
#             # print(full_df)
#             full_df = full_df.drop_duplicates(subset=["isolate_partial"])
#             full_dfs[key].append(full_df)
#         except:
#             print("Failed to merge dataframes in ", key)
#             full_dfs[key].append(dataframes[i])

## Create FASTA files combining Andersen and GISAID

In [54]:
# Create FASTA files per segment

combined_files = downloads + "Combinations/GISAID_Andersen/" # B3_13_D1_1/" + date_range + "_B3_13_D1_1/"

os.chdir(combined_files)
for pair in full_dfs.keys():
    print(pair)
    output_path = combined_files + pair + "_combined_" + date_range + ".fasta" 

    output_file = open(output_path, "w")
    for item in full_dfs[pair]:
        # for item in item:
        # item = fasta_files[pair]
        for index, row in item.iterrows():
            name = item.loc[index, "full_header"]
            sequence = item.loc[index, "sequence"]
            # print(name)
        # First is header, second is sequence
        # print(value)
            output_file.write(name)
            output_file.write(sequence)
    output_file.close()

A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
Minor92_HA
Minor92_MP
Minor92_NA
Minor92_NP
Minor92_NS
Minor92_PA
Minor92_PB1
Minor92_PB2