# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI, by de-duplicating from Andersen/GISAID, and relabeling sequences.

In [1]:
# Housekeeping

import os
import pandas as pd
import dateutil
import importlib
import utils  
importlib.reload(utils)
from utils import *

In [2]:
# Paths

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = home + "NCBI_Virus/downloads/04-14-2025--05-14-2025/"
temp_files = home + "NCBI_Virus/temp/"
complete_files = home + "NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/"
gisaid_andersen = home + "Combinations/GISAID_Andersen/B3_13_D1_1/04-14-2025--05-14-2025_B3_13/"
combined_files = home + "Combinations/GISAID_Andersen_NCBI_Virus/04-14-2025--05-14-2025_B3_13/"

# Day we're updating data
update_date = "05-14-2025"

os.chdir(downloads)

## De-Duplication

In [3]:
metadata = pd.read_csv("sequences.csv")

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.SRA_Accession, as_index=False).size()

print(metadata_counts)

metadata_counted = metadata.merge(metadata_counts, on="SRA_Accession")

# Only keep those with size=8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates

metadata_complete_segs = metadata_complete_segs.drop_duplicates(subset="GenBank_Title", keep="first") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]

metadata_segments

    SRA_Accession  size
0     SRR31254292     8
1     SRR31254312     8
2     SRR31254355     8
3     SRR31254366     8
4     SRR31254377     8
..            ...   ...
521   SRR33124773     8
522   SRR33124774     8
523   SRR33124775     8
524   SRR33124776     8
525   SRR33124777     8

[526 rows x 2 columns]

,Accession,Organism_Name,GenBank_RefSeq,Assembly,SRA_Accession,Submitters,Organization,Org_location,Release_Date,Isolate,...,Geo_Location,Country,USA,Host,Tissue_Specimen_Source,Collection_Date,BioSample,BioProject,GenBank_Title,size
0,PV625126.1,Influenza A virus,GenBank,NaN,SRR33029744,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-09,25-002734-001-original-repeat,...,USA: NY,USA,NY,Gallus gallus,swab,2025-01-22,SAMN47843691,PRJNA980729,Influenza A virus (A/chicken/NY/25-002734-001-...,8
1,PV625127.1,Influenza A virus,GenBank,NaN,SRR33029744,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-09,25-002734-001-original-repeat,...,USA: NY,USA,NY,Gallus gallus,swab,2025-01-22,SAMN47843691,PRJNA980729,Influenza A virus (A/chicken/NY/25-002734-001-...,8
2,PV625128.1,Influenza A virus,GenBank,NaN,SRR33029744,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-09,25-002734-001-original-repeat,...,USA: NY,USA,NY,Gallus gallus,swab,2025-01-22,SAMN47843691,PRJNA980729,Influenza A virus (A/chicken/NY/25-002734-001-...,8
3,PV625129.1,Influenza A virus,GenBank,NaN,SRR33029744,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-09,25-002734-001-original-repeat,...,USA: NY,USA,NY,Gallus gallus,swab,2025-01-22,SAMN47843691,PRJNA980729,Influenza A virus (A/chicken/NY/25-002734-001-...,8
4,PV625130.1,Influenza A virus,GenBank,NaN,SRR33029744,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-09,25-002734-001-original-repeat,...,USA: NY,USA,NY,Gallus gallus,swab,2025-01-22,SAMN47843691,PRJNA980729,Influenza A virus (A/chicken/NY/25-002734-001-...,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4203,PV494554.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,USA: CA,USA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
4204,PV494555.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,USA: CA,USA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
4205,PV494556.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,USA: CA,USA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
4206,PV494557.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,USA: CA,USA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
4207,PV494558.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,USA: CA,USA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8

In [4]:
# De-duplicate from Andersen/GISAID using isolate

# If even one isolate in this list exists in the NCBI Virus dataframe, remove it from NCBI Virus dataframe
gisaid_andersen_isolates = []
# Grab files
for dirpath, dirs, files in os.walk(gisaid_andersen):
    for file in files:
        file_name = os.path.join(dirpath, file)
        # print(file_name)
        if ".fasta" in file_name:
            fasta_file = fasta_df(file_name) # Convert fasta file to dataframe
            isolates = fasta_file["Isolate_Id"].apply(lambda x: x.split("/")[3])
            for index, value in isolates.items():
                gisaid_andersen_isolates.append(value)
         
    break 

gisaid_andersen_isolates = list(set(gisaid_andersen_isolates))

print(gisaid_andersen_isolates)

['25-012508-004', '012127-002', '006248-005', '012131-004', '012909-004', '010525-003', '012934-002', '25-012365-020', '012128-004', '012934-004', '25-012269-016', '006251-005', '010526-003', '010998-001', '25-012365-048', '25-012269-008', '25-012365-050', '25-004431-001', '25-004499-002', '012902-004', '011373-001', '011000-001', '25-011759-032', '25_000604-002', '25-002735-001', '012130-003', '012902-003', '010525-002', '25-012269-003', '006260-005', '012128-002', '25-005882-001', '25-012116-001', '012128-003', '25-006076-002', '25-006491-001', '25-004417-001', '25-006142-008', '25_000610-001', '012909-003', '25-012269-004', '011299-002', '25-011691-001', '25-002623-001', '25-011759-034', '25-004415-016', 'Inoc-TX-24-029328-01', '006276-002', '25-011759-044', '25-005879-001', '011010-001', '25-004378-001', '25-012105-003', '25-011667-003', '011296-005', '012127-003', '25-011424-002', '25-005865-001', '25-012363-001', '012114-001', '25-012058-002', '25-012105-001', '25-004425-001', '25-012508-006', '011002-002', '010637-003', '25-012104-001', '010524-003', '011907-003', '012902-011', '25_004923-001', '011002-001', '010642-003', '25-011519-001', '25-012741-002', '010525-001', '010008-007-v', '006543-001', '011318-003', '012903-001', '25-006140-002', '25-005883-001', '012129-001', '010008-004-v', '036187-001-R2', '25-005880-001', '012928-002', '010526-002', '25-006343-005', '25-012178-003', '006243-001', '006029-002', '24_033172-002', '25-012365-043', '012189-005', '011318-001', '012113-002', '25-004498-005', '25-012104-002', '036208-002-R2', '006260-002', '011010-002', '24_033172-001', '25-004415-012', '012910-001', '006638-001', '012902-012', '011320-002', '011298-001-tile', '25-012246-029', '012187-005', '012089-004', '25-011759-055', '25_004923-002', '011474-002', '25-011283-001', '011387-001', '012911-004', '25-012115-002', '25-012365-030', '012111-002', '25-012178-001', '25-011667-002', '25-006331-001', '25-004497-004', '010521-001', '25-011024-001', '012909-001', '25-005882-007', '011907-008', '25-011693-001', '25-010933-001', '25-012397-002', '25-012269-009', '25-004477-001', '25-012364-001', '012911-003', '25-012365-027', '25-006283-001', '006260-003', '010626-003', '006274-003', '012089-001', '010637-001', '25-011672-001', '006544-001', '25-011271-008', '25-007118-068', '25-005866-001', '010517-002', '010642-004', '012948-001', '25-006220-001', '012118-001', '25_000112-002', '25-005882-008', '006243-006', '25_000604-001', '006260-001', '25-004426-001', '010999-001', '011468-001', '010526-004', '012934-001', '006274-001', '25-006332-001', '25-012105-002', '25-012249-001', '011318-002', '006263-005', '011320-001', '011907-007', '007097-001', '012187-004', '012189-002', '012902-007', '010626-001', '006243-005', '012902-005', '012928-001', '011373-003', '25-011759-031', '036203-001-R2', '25-011759-022', '010626-002', '012125-001', '25-012365-042', '011907-009', '25-012246-009', '24-037947-001', '011296-004', '25-005882-003', '012183-002', '24_034835-001-R2', '25-011024-006', '036187-002-R2', '010524-004', '010642-005', '25-012365-014', '25-011759-036', '25-012059-002', '010517-003', '011296-003', '012113-001', '25-005882-009', '010524-001', '25-005869-001', '012115-001', '010523-001', '25-012328-001', '25-012365-022', '012949-002', '036203-002-R2', '012903-003', '25-012246-013', '25-012269-006', '010626-004', '25-012050-001', '012089-003', '24_033172-003', '006274-004', '25-012058-001', '25-005882-005', '25-011178-001', '25-011759-037', '011299-001', '25-012246-005', '011907-006', '012111-001', '011372-001', '25-011816-001', '006248-004', '036182-002-R2', '011373-002', '012903-002', '012127-001', '007097-002', '25-011759-019', '012112-002', '012902-002', '25-012510-002', '012909-002', '036208-001-R2', '006251-007', '25-012694-001', '012911-002', '25-012365-012', '25-012510-001', '25-011024-005', '012127-004', '012112-001', '012132-001', '006020-001', '010524-002', '012089-005', '25-004480-001', '036138-001-R2', '25-011694-001', '25-005927-005', '012902-009', '25-004415-006', '25-006047-001', '25-012105-004', '006251-002', '010525-004', '006251-004', '010626-005', '25-011423-001', '010008-011-v', '012902-010', '25-004497-005', '012183-004', '25-012695-001', '25-012740-001', '012902-006', '012133-001', '25-011759-021', '25-006331-003', '010637-002', '25-004376-001', '25-004424-001', '25-012365-037', '006026-001', '25-012269-001', '012911-001', '011373-004', '012952-003', '25-012269-011', '25-012246-007', '012910-002', '25-011541-003', '006260-004', '012124-001', '25-004415-011', '012905-001', '012178-002', '006028-001', '012902-001', '011373-005', '012902-008', '012130-002', '012906-001', '25-006139-001', '25-011541-001', '25-004415-005', '25-006823-001', '25-002583-006', '25-012269-013', '25-011424-001', '012130-001', '25-006145-001', '006020-002', '010008-005-v', '25-006499-001', '011387-003', '25-012268-015', '25-005882-006', '011387-002', '012934-003']

In [5]:
# Remove duplicates from GISAID/Andersen

print(len(metadata_segments))

for index, value in metadata_segments["Isolate"].items():
    if value in gisaid_andersen_isolates:
        metadata_segments = metadata_segments.drop(index)

print(len(metadata_segments))

metadata_segments

4208
4208

,Accession,Organism_Name,GenBank_RefSeq,Assembly,SRA_Accession,Submitters,Organization,Org_location,Release_Date,Isolate,...,Geo_Location,Country,USA,Host,Tissue_Specimen_Source,Collection_Date,BioSample,BioProject,GenBank_Title,size
0,PV625126.1,Influenza A virus,GenBank,NaN,SRR33029744,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-09,25-002734-001-original-repeat,...,USA: NY,USA,NY,Gallus gallus,swab,2025-01-22,SAMN47843691,PRJNA980729,Influenza A virus (A/chicken/NY/25-002734-001-...,8
1,PV625127.1,Influenza A virus,GenBank,NaN,SRR33029744,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-09,25-002734-001-original-repeat,...,USA: NY,USA,NY,Gallus gallus,swab,2025-01-22,SAMN47843691,PRJNA980729,Influenza A virus (A/chicken/NY/25-002734-001-...,8
2,PV625128.1,Influenza A virus,GenBank,NaN,SRR33029744,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-09,25-002734-001-original-repeat,...,USA: NY,USA,NY,Gallus gallus,swab,2025-01-22,SAMN47843691,PRJNA980729,Influenza A virus (A/chicken/NY/25-002734-001-...,8
3,PV625129.1,Influenza A virus,GenBank,NaN,SRR33029744,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-09,25-002734-001-original-repeat,...,USA: NY,USA,NY,Gallus gallus,swab,2025-01-22,SAMN47843691,PRJNA980729,Influenza A virus (A/chicken/NY/25-002734-001-...,8
4,PV625130.1,Influenza A virus,GenBank,NaN,SRR33029744,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-09,25-002734-001-original-repeat,...,USA: NY,USA,NY,Gallus gallus,swab,2025-01-22,SAMN47843691,PRJNA980729,Influenza A virus (A/chicken/NY/25-002734-001-...,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4203,PV494554.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,USA: CA,USA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
4204,PV494555.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,USA: CA,USA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
4205,PV494556.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,USA: CA,USA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
4206,PV494557.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,USA: CA,USA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
4207,PV494558.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,USA: CA,USA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8

In [6]:
# NCBI Virus Naming Convention Example:
# Influenza A virus |USA: IN|25-006338-001-original|H5N1|2025-02-20|Meleagris gallopavo|GenBank|SRR33124721|SAMN47941411|PRJNA980729|Influenza A virus (A/Turkey/IN/25-006338-001-original/2025(H5N1)) segment 1 polymerase PB2 (PB2) gene, complete cds
# Organism_Name | Geo_Location | Isolate | Genotype | Collection_Date | Host | GenBank_RefSeq | SRA_Accession | BioSample | BioProject | GenBank_Title


# print(metadata_segments["GenBank_Title"].iloc[0])

# Get sequences and headers together
headers = []
isolates = []
sras = []
headers_seqs = {}
with open("sequences.fasta") as f:
    lines = f.readlines()
    for num, line in enumerate(lines):
        if line[0] == ">": # If this is a header
            if line.strip() not in headers: # And is not a header we've seen before
                header = line.strip() 
                # print(header)
                split_header = header.split("|")
                # print(split_header)
                headers.append(header) 
                if num < len(lines): # If we're not at the last line
                    # for i, l in enumerate(lines[num + 1:]):
                    i = num
                    sequence = ""
                    # print(lines[i])
                    # print(lines[i + 1])
                    while i < len(lines) - 1 and lines[i + 1][0] != ">": # While the next line is part of a sequence
                        sequence = sequence + lines[i + 1].strip()
                        i += 1
                    headers_seqs[header] = sequence # Add next lines to sequences
                # name = split_header[-1] # Last part gives GenBank name, with segment and isolate
                isolate = split_header[2]
                isolates.append(isolate)
                sra = split_header[7]
                sras.append(sra)
    f.close()



# print(mask_all.all(axis=1))

In [7]:
# Double-check de-duplication
mask = metadata_segments["Isolate"].isin(isolates) # Check if isolate is in fasta
mask_sra = metadata_segments["SRA_Accession"].isin(sras) # Check if sra is in fasta

metadata_masked = metadata_segments[mask] # Some do not have isolates, so check sra too
metadata_masked_sra = metadata_segments[mask_sra]

merged_metadata = metadata_masked.merge(metadata_masked_sra, how="outer")
merged_metadata = merged_metadata.drop_duplicates(keep="first")

print(len(headers_seqs))
print(len(merged_metadata))

4607
4208

In [8]:
# Add sequences to a dataframe 
headers_seqs_df = pd.DataFrame.from_dict(headers_seqs, orient="index")
headers_seqs_df = headers_seqs_df.reset_index()
headers_seqs_df["GenBank_Title"] = headers_seqs_df["index"].apply(lambda x: x[1:].split("|")[-1])
headers_seqs_df = headers_seqs_df.rename(columns={0: "Sequence", "index": "Header"})

# Add sequences to the dataframe
metadata_seqs = merged_metadata.merge(headers_seqs_df, on="GenBank_Title", how="left")

print(metadata_seqs)

       Accession      Organism_Name GenBank_RefSeq         Assembly  \
0     PV493074.1  Influenza A virus        GenBank  GCA_049650035.1
1     PV493075.1  Influenza A virus        GenBank  GCA_049650035.1
2     PV493076.1  Influenza A virus        GenBank  GCA_049650035.1
3     PV493077.1  Influenza A virus        GenBank  GCA_049650035.1
4     PV493078.1  Influenza A virus        GenBank  GCA_049650035.1
...          ...                ...            ...              ...
4203  PV625457.1  Influenza A virus        GenBank              NaN
4204  PV625458.1  Influenza A virus        GenBank              NaN
4205  PV625459.1  Influenza A virus        GenBank              NaN
4206  PV625460.1  Influenza A virus        GenBank              NaN
4207  PV625461.1  Influenza A virus        GenBank              NaN

     SRA_Accession                                         Submitters  \
0      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
1      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
2      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
3      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
4203   SRR33029746  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
4204   SRR33029746  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
4205   SRR33029746  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
4206   SRR33029746  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
4207   SRR33029746  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...

                                           Organization Org_location  \
0     USDA Animal Plant Health Inspection Service-Na...          USA
1     USDA Animal Plant Health Inspection Service-Na...          USA
2     USDA Animal Plant Health Inspection Service-Na...          USA
3     USDA Animal Plant Health Inspection Service-Na...          USA
4     USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
4203  USDA Animal Plant Health Inspection Service-Na...          USA
4204  USDA Animal Plant Health Inspection Service-Na...          USA
4205  USDA Animal Plant Health Inspection Service-Na...          USA
4206  USDA Animal Plant Health Inspection Service-Na...          USA
4207  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ... USA           Host  \
0      2025-04-14  25-005339-003-original  ...  IN  Gallus gallus
1      2025-04-14  25-005339-003-original  ...  IN  Gallus gallus
2      2025-04-14  25-005339-003-original  ...  IN  Gallus gallus
3      2025-04-14  25-005339-003-original  ...  IN  Gallus gallus
4      2025-04-14  25-005339-003-original  ...  IN  Gallus gallus
...           ...                     ...  ...  ..            ...
4203   2025-05-09  24-035866-001-original  ...  CA       Anatidae
4204   2025-05-09  24-035866-001-original  ...  CA       Anatidae
4205   2025-05-09  24-035866-001-original  ...  CA       Anatidae
4206   2025-05-09  24-035866-001-original  ...  CA       Anatidae
4207   2025-05-09  24-035866-001-original  ...  CA       Anatidae

     Tissue_Specimen_Source Collection_Date     BioSample   BioProject  \
0            oronasopharynx      2025-02-12  SAMN47130968  PRJNA980729
1            oronasopharynx      2025-02-12  SAMN47130968  PRJNA980729
2            oronasopharynx      2025-02-12  SAMN47130968  PRJNA980729
3            oronasopharynx      2025-02-12  SAMN47130968  PRJNA980729
4            oronasopharynx      2025-02-12  SAMN47130968  PRJNA980729
...                     ...             ...           ...          ...
4203                    NaN      2024-11-20  SAMN47843703  PRJNA980729
4204                    NaN      2024-11-20  SAMN47843703  PRJNA980729
4205                    NaN      2024-11-20  SAMN47843703  PRJNA980729
4206                    NaN      2024-11-20  SAMN47843703  PRJNA980729
4207                    NaN      2024-11-20  SAMN47843703  PRJNA980729

                                          GenBank_Title size  \
0     Influenza A virus (A/chicken/IN/25-005339-003-...    8
1     Influenza A virus (A/chicken/IN/25-005339-003-...    8
2     Influenza A virus (A/chicken/IN/25-005339-003-...    8
3     Influenza A virus (A/chicken/IN/25-005339-003-...    8
4     Influenza A virus (A/chicken/IN/25-005339-003-...    8
...                                                 ...  ...
4203  Influenza A virus (A/goose/CA/24-035866-001-or...    8
4204  Influenza A virus (A/goose/CA/24-035866-001-or...    8
4205  Influenza A virus (A/goose/CA/24-035866-001-or...    8
4206  Influenza A virus (A/goose/CA/24-035866-001-or...    8
4207  Influenza A virus (A/goose/CA/24-035866-001-or...    8

                                                 Header  \
0     >Influenza A virus |USA: IN|25-005339-003-orig...
1     >Influenza A virus |USA: IN|25-005339-003-orig...
2     >Influenza A virus |USA: IN|25-005339-003-orig...
3     >Influenza A virus |USA: IN|25-005339-003-orig...
4     >Influenza A virus |USA: IN|25-005339-003-orig...
...                                                 ...
4203  >Influenza A virus |USA: CA|24-035866-001-orig...
4204  >Influenza A virus |USA: CA|24-035866-001-orig...
4205  >Influenza A virus |USA: CA|24-035866-001-orig...
4206  >Influenza A virus |USA: CA|24-035866-001-orig...
4207  >Influenza A virus |USA: CA|24-035866-001-orig...

                                               Sequence
0     ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
1     ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
2     ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
3     ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4     ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
...                                                 ...
4203  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4204  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
4205  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
4206  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4207  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...

[4208 rows x 27 columns]

In [9]:
# Create FASTA files per Header

metadata_seqs["Partial_Header"] = metadata_seqs["Header"].apply(lambda x: "|".join(x.split("|")[:-1]))

unique_partial_headers = []

# Each header should repeat 8 times
for partial_header in metadata_seqs["Partial_Header"].values:
    if partial_header not in unique_partial_headers: # Only use the first occurence
        unique_partial_headers.append(partial_header)

print(len(unique_partial_headers)) # Sanity check

526

In [10]:
df_list = []
for partial_header in unique_partial_headers:
    # Get smaller dataframe
    df = metadata_seqs[metadata_seqs["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    df = df[["Header", "Sequence"]]
    df = df.rename(columns={"Header": "full_header", "Sequence": "sequence"}) # For utils function
    df["full_header"] = df["full_header"].apply(lambda x: ">" + x.split("|")[-1].replace(" ", "_"))
    # Make sure there are 8 segments
    if len(df) == 8:
        df_list.append(df)

In [11]:
print(df_list[0])
print(len(df_list))

                                         full_header  \
0  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
1  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
2  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
3  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
4  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
5  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
6  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
7  >Influenza_A_virus_(A/chicken/IN/25-005339-003...

                                            sequence
0  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
1  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
2  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
3  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
5  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
6  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
7  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
526

In [12]:
# Make fasta files. Finally

os.chdir(temp_files)

for df in df_list:
    # print(df)
    file_name = df["full_header"].apply(lambda x: x.split("|")[-1]).values[0] + "_temp.fasta"
    # Forbidden characters
    for c in [">", "/", "|", " ", ":", ",", "(", ")", "-"]:
        file_name = file_name.replace(c, "")
    # print(file_name)
    output_file = open(temp_files + file_name, "w")

    for index, row in df.iterrows():
        name = df.loc[index, "full_header"]
        # print(name)
        sequence = df.loc[index, "sequence"]
        # print(sequence)
        # break 
    # First is header, second is sequence
        output_file.write(name + "\n")
        output_file.write(sequence + "\n")
    output_file.close()

## Re-Labeling Using GenoFlu

In [13]:
# Merging

os.chdir(downloads)

output_genoflu = pd.read_csv("output.tsv", delimiter="\t")

# print(output_genoflu)

# print(metadata_seqs["Header"])

file_name = metadata_seqs["Header"].apply(lambda x: x.split("|")[-1].replace(" ", "_") + "_temp.fasta")
for c in [">", "/", "|", " ", ":", ",", "(", ")", "-"]:
    file_name = file_name.apply(lambda x: x.replace(c, ""))

metadata_seqs["File Name"] = file_name

metadata_genoflu = metadata_seqs.merge(output_genoflu, how="outer", on="File Name")

metadata_genoflu = metadata_genoflu.ffill()

print(metadata_genoflu)

       Accession      Organism_Name GenBank_RefSeq         Assembly  \
0     PV571974.1  Influenza A virus        GenBank  GCA_049972745.1
1     PV571975.1  Influenza A virus        GenBank  GCA_049972745.1
2     PV571976.1  Influenza A virus        GenBank  GCA_049972745.1
3     PV571977.1  Influenza A virus        GenBank  GCA_049972745.1
4     PV571978.1  Influenza A virus        GenBank  GCA_049972745.1
...          ...                ...            ...              ...
4203  PV573369.1  Influenza A virus        GenBank  GCA_049972655.1
4204  PV573370.1  Influenza A virus        GenBank  GCA_049972655.1
4205  PV573371.1  Influenza A virus        GenBank  GCA_049972655.1
4206  PV573372.1  Influenza A virus        GenBank  GCA_049972655.1
4207  PV573373.1  Influenza A virus        GenBank  GCA_049972655.1

     SRA_Accession                                         Submitters  \
0      SRR33124746  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
1      SRR33124746  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
2      SRR33124746  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
3      SRR33124746  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4      SRR33124746  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
4203   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4204   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4205   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4206   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4207   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....

                                           Organization Org_location  \
0     USDA Animal Plant Health Inspection Service-Na...          USA
1     USDA Animal Plant Health Inspection Service-Na...          USA
2     USDA Animal Plant Health Inspection Service-Na...          USA
3     USDA Animal Plant Health Inspection Service-Na...          USA
4     USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
4203  USDA Animal Plant Health Inspection Service-Na...          USA
4204  USDA Animal Plant Health Inspection Service-Na...          USA
4205  USDA Animal Plant Health Inspection Service-Na...          USA
4206  USDA Animal Plant Health Inspection Service-Na...          USA
4207  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ...  \
0      2025-04-28  25-006346-010-original  ...
1      2025-04-28  25-006346-010-original  ...
2      2025-04-28  25-006346-010-original  ...
3      2025-04-28  25-006346-010-original  ...
4      2025-04-28  25-006346-010-original  ...
...           ...                     ...  ...
4203   2025-04-28  25-006346-001-original  ...
4204   2025-04-28  25-006346-001-original  ...
4205   2025-04-28  25-006346-001-original  ...
4206   2025-04-28  25-006346-001-original  ...
4207   2025-04-28  25-006346-001-original  ...

                                         Partial_Header  \
0     >Influenza A virus |USA: PA|25-006346-010-orig...
1     >Influenza A virus |USA: PA|25-006346-010-orig...
2     >Influenza A virus |USA: PA|25-006346-010-orig...
3     >Influenza A virus |USA: PA|25-006346-010-orig...
4     >Influenza A virus |USA: PA|25-006346-010-orig...
...                                                 ...
4203  >Influenza A virus |USA: PA|25-006346-001-orig...
4204  >Influenza A virus |USA: PA|25-006346-001-orig...
4205  >Influenza A virus |USA: PA|25-006346-001-orig...
4206  >Influenza A virus |USA: PA|25-006346-001-orig...
4207  >Influenza A virus |USA: PA|25-006346-001-orig...

                                              File Name     sample  \
0     Influenza_A_virus_AChukarPA25006346010original...  Influenza
1     Influenza_A_virus_AChukarPA25006346010original...  Influenza
2     Influenza_A_virus_AChukarPA25006346010original...  Influenza
3     Influenza_A_virus_AChukarPA25006346010original...  Influenza
4     Influenza_A_virus_AChukarPA25006346010original...  Influenza
...                                                 ...        ...
4203  Influenza_A_virus_AgoosePA25006346001original2...  Influenza
4204  Influenza_A_virus_AgoosePA25006346001original2...  Influenza
4205  Influenza_A_virus_AgoosePA25006346001original2...  Influenza
4206  Influenza_A_virus_AgoosePA25006346001original2...  Influenza
4207  Influenza_A_virus_AgoosePA25006346001original2...  Influenza

                     date  Genotype_y  \
0     2025-05-14_15-32-59        D1.1
1     2025-05-14_15-32-59        D1.1
2     2025-05-14_15-32-59        D1.1
3     2025-05-14_15-32-59        D1.1
4     2025-05-14_15-32-59        D1.1
...                   ...         ...
4203  2025-05-14_15-51-11        D1.1
4204  2025-05-14_15-51-11        D1.1
4205  2025-05-14_15-51-11        D1.1
4206  2025-05-14_15-51-11        D1.1
4207  2025-05-14_15-51-11        D1.1

                            Genotype List Used, >=98.0%  \
0     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
2     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
...                                                 ...
4203  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4204  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4205  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4206  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4207  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
0     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
...                                                 ...
4203  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4204  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4205  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4206  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4207  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
0     99.78%, 99.25%, 99.63%, 99.35%, 99.53%, 99.50%...
1     99.78%, 99.25%, 99.63%, 99.35%, 99.53%, 99.50%...
2     99.78%, 99.25%, 99.63%, 99.35%, 99.53%, 99.50%...
3     99.78%, 99.25%, 99.63%, 99.35%, 99.53%, 99.50%...
4     99.78%, 99.25%, 99.63%, 99.35%, 99.53%, 99.50%...
...                                                 ...
4203  99.74%, 99.25%, 99.67%, 99.35%, 99.53%, 99.50%...
4204  99.74%, 99.25%, 99.67%, 99.35%, 99.53%, 99.50%...
4205  99.74%, 99.25%, 99.67%, 99.35%, 99.53%, 99.50%...
4206  99.74%, 99.25%, 99.67%, 99.35%, 99.53%, 99.50%...
4207  99.74%, 99.25%, 99.67%, 99.35%, 99.53%, 99.50%...

        Genotype Mismatch List Genotype Average Depth of Coverage List
0     5, 17, 8, 11, 7, 7, 1, 9       Ran on FASTA - No Coverage Report
1     5, 17, 8, 11, 7, 7, 1, 9       Ran on FASTA - No Coverage Report
2     5, 17, 8, 11, 7, 7, 1, 9       Ran on FASTA - No Coverage Report
3     5, 17, 8, 11, 7, 7, 1, 9       Ran on FASTA - No Coverage Report
4     5, 17, 8, 11, 7, 7, 1, 9       Ran on FASTA - No Coverage Report
...                        ...                                     ...
4203  6, 17, 7, 11, 7, 7, 0, 9       Ran on FASTA - No Coverage Report
4204  6, 17, 7, 11, 7, 7, 0, 9       Ran on FASTA - No Coverage Report
4205  6, 17, 7, 11, 7, 7, 0, 9       Ran on FASTA - No Coverage Report
4206  6, 17, 7, 11, 7, 7, 0, 9       Ran on FASTA - No Coverage Report
4207  6, 17, 7, 11, 7, 7, 0, 9       Ran on FASTA - No Coverage Report

[4208 rows x 37 columns]

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

In [14]:
# Re-Labeling

os.chdir(home)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

fix_animals_andersen(metadata_genoflu, animals_ref)

metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

# print(metadata_genoflu["Host_Type"])

names = ">A/" + metadata_genoflu["Host"] + "/" + metadata_genoflu["Geo_Location"] + "/" + metadata_genoflu["Isolate"] + "/" + metadata_genoflu["Years"].apply(lambda x: str(x)) + "|" + metadata_genoflu["Genotype_x"] + "|" + metadata_genoflu["Collection_Date"] + "|" + metadata_genoflu["Host_Type"] + "|" + metadata_genoflu["Genotype_y"]

metadata_genoflu["Name"] = names

print(metadata_genoflu["Name"])

0       >A/alectoris chukar/USA: PA/25-006346-010-orig...
1       >A/alectoris chukar/USA: PA/25-006346-010-orig...
2       >A/alectoris chukar/USA: PA/25-006346-010-orig...
3       >A/alectoris chukar/USA: PA/25-006346-010-orig...
4       >A/alectoris chukar/USA: PA/25-006346-010-orig...
                              ...
4203    >A/anatidae/USA: PA/25-006346-001-original/202...
4204    >A/anatidae/USA: PA/25-006346-001-original/202...
4205    >A/anatidae/USA: PA/25-006346-001-original/202...
4206    >A/anatidae/USA: PA/25-006346-001-original/202...
4207    >A/anatidae/USA: PA/25-006346-001-original/202...
Name: Name, Length: 4208, dtype: object

## Merge all datasets and de-duplicate again

In [ ]:
# Set up segments

segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"}

metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].map(segments)

# print(metadata_genoflu["Segment_Name"])

# Separate into several dataframes based on genotype + segment
segment_genotype_dfs = []
for segment in segments.values():
    print(segment)
    m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
    print(m_g)
    for genotype in list(set(m_g["Genotype_y"].values)):
        if "Not assigned:" not in genotype:
            df = m_g[(m_g["Genotype_y"] == genotype)] # & (metadata_genoflu["Segment"] == segment)]
            segment_genotype_dfs.append(df)
            # pair = genotype + "_" + segment
            # print(pair)

print(segment_genotype_dfs[3])

# print(metadata_genoflu["Header"].apply(lambda x: x.split("|")[-1].split("/")[-1].split(")")[2:]))

PB2
       Accession      Organism_Name GenBank_RefSeq         Assembly  \
0     PV571974.1  Influenza A virus        GenBank  GCA_049972745.1
8     PV571982.1  Influenza A virus        GenBank  GCA_049972255.1
16    PV571990.1  Influenza A virus        GenBank  GCA_049972565.1
24    PV571998.1  Influenza A virus        GenBank  GCA_049972785.1
32    PV572006.1  Influenza A virus        GenBank  GCA_049972795.1
...          ...                ...            ...              ...
4168  PV494090.1  Influenza A virus        GenBank  GCA_049649415.1
4176  PV573342.1  Influenza A virus        GenBank  GCA_049973825.1
4184  PV573350.1  Influenza A virus        GenBank  GCA_049973855.1
4192  PV573358.1  Influenza A virus        GenBank  GCA_049973145.1
4200  PV573366.1  Influenza A virus        GenBank  GCA_049972655.1

     SRA_Accession                                         Submitters  \
0      SRR33124746  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
8      SRR33124743  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
16     SRR33124740  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
24     SRR33124739  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
32     SRR33124738  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
4168   SRR32512867  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4176   SRR32868573  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4184   SRR32868572  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4192   SRR33124727  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4200   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....

                                           Organization Org_location  \
0     USDA Animal Plant Health Inspection Service-Na...          USA
8     USDA Animal Plant Health Inspection Service-Na...          USA
16    USDA Animal Plant Health Inspection Service-Na...          USA
24    USDA Animal Plant Health Inspection Service-Na...          USA
32    USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
4168  USDA Animal Plant Health Inspection Service-Na...          USA
4176  USDA Animal Plant Health Inspection Service-Na...          USA
4184  USDA Animal Plant Health Inspection Service-Na...          USA
4192  USDA Animal Plant Health Inspection Service-Na...          USA
4200  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ... Genotype_y  \
0      2025-04-28  25-006346-010-original  ...       D1.1
8      2025-04-28  25-006288-001-original  ...       D1.3
16     2025-04-28  25-006492-001-original  ...       D1.3
24     2025-04-28  25-006496-001-original  ...       D1.3
32     2025-04-28  25-006496-002-original  ...       D1.3
...           ...                     ...  ...        ...
4168   2025-04-14  25-004777-004-original  ...       D1.1
4176   2025-04-28  25-008296-001-original  ...       D1.1
4184   2025-04-28  25-008296-002-original  ...       D1.1
4192   2025-04-28  25-007078-005-original  ...       D1.1
4200   2025-04-28  25-006346-001-original  ...       D1.1

                            Genotype List Used, >=98.0%  \
0     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
8     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
16    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
24    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
32    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
...                                                 ...
4168  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4176  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4184  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4192  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4200  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
0     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
8     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
16    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
24    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
32    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
...                                                 ...
4168  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4176  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4184  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4192  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4200  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
0     99.78%, 99.25%, 99.63%, 99.35%, 99.53%, 99.50%...
8     99.52%, 99.34%, 99.58%, 99.18%, 99.80%, 99.01%...
16    99.74%, 99.34%, 99.63%, 99.18%, 99.87%, 99.01%...
24    99.74%, 99.30%, 99.63%, 99.18%, 99.87%, 99.01%...
32    99.74%, 99.34%, 99.63%, 99.18%, 99.87%, 99.01%...
...                                                 ...
4168  99.69%, 99.34%, 99.67%, 99.47%, 99.53%, 99.29%...
4176  99.78%, 99.21%, 99.86%, 99.47%, 99.80%, 99.57%...
4184  99.78%, 99.21%, 99.81%, 99.41%, 99.80%, 99.57%...
4192  99.69%, 99.43%, 99.63%, 99.24%, 99.80%, 99.50%...
4200  99.74%, 99.25%, 99.67%, 99.35%, 99.53%, 99.50%...

          Genotype Mismatch List Genotype Average Depth of Coverage List  \
0       5, 17, 8, 11, 7, 7, 1, 9       Ran on FASTA - No Coverage Report
8     11, 15, 9, 14, 3, 14, 2, 8       Ran on FASTA - No Coverage Report
16     6, 15, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report
24     6, 16, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report
32     6, 15, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report
...                          ...                                     ...
4168   7, 15, 7, 9, 7, 10, 3, 10       Ran on FASTA - No Coverage Report
4176    5, 18, 3, 9, 3, 6, 0, 10       Ran on FASTA - No Coverage Report
4184   5, 18, 4, 10, 3, 6, 0, 11       Ran on FASTA - No Coverage Report
4192    7, 13, 8, 13, 3, 7, 0, 8       Ran on FASTA - No Coverage Report
4200    6, 17, 7, 11, 7, 7, 0, 9       Ran on FASTA - No Coverage Report

     Host_Type Years                                               Name  \
0        avian  2025  >A/alectoris chukar/USA: PA/25-006346-010-orig...
8        avian  2025  >A/anatidae/USA: IN/25-006288-001-original/202...
16       avian  2025  >A/anatidae/USA: IN/25-006492-001-original/202...
24       avian  2025  >A/anatidae/USA: IN/25-006496-001-original/202...
32       avian  2025  >A/anatidae/USA: IN/25-006496-002-original/202...
...        ...   ...                                                ...
4168     avian  2025  >A/anatidae/USA: NY/25-004777-004-original/202...
4176     avian  2025  >A/anatidae/USA: NY/25-008296-001-original/202...
4184     avian  2025  >A/anatidae/USA: NY/25-008296-002-original/202...
4192     avian  2025  >A/anatidae/USA: OH/25-007078-005-original/202...
4200     avian  2025  >A/anatidae/USA: PA/25-006346-001-original/202...

     Segment_Name
0             PB2
8             PB2
16            PB2
24            PB2
32            PB2
...           ...
4168          PB2
4176          PB2
4184          PB2
4192          PB2
4200          PB2

[526 rows x 41 columns]
PB1
       Accession      Organism_Name GenBank_RefSeq         Assembly  \
1     PV571975.1  Influenza A virus        GenBank  GCA_049972745.1
9     PV571983.1  Influenza A virus        GenBank  GCA_049972255.1
17    PV571991.1  Influenza A virus        GenBank  GCA_049972565.1
25    PV571999.1  Influenza A virus        GenBank  GCA_049972785.1
33    PV572007.1  Influenza A virus        GenBank  GCA_049972795.1
...          ...                ...            ...              ...
4169  PV494091.1  Influenza A virus        GenBank  GCA_049649415.1
4177  PV573343.1  Influenza A virus        GenBank  GCA_049973825.1
4185  PV573351.1  Influenza A virus        GenBank  GCA_049973855.1
4193  PV573359.1  Influenza A virus        GenBank  GCA_049973145.1
4201  PV573367.1  Influenza A virus        GenBank  GCA_049972655.1

     SRA_Accession                                         Submitters  \
1      SRR33124746  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
9      SRR33124743  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
17     SRR33124740  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
25     SRR33124739  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
33     SRR33124738  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
4169   SRR32512867  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4177   SRR32868573  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4185   SRR32868572  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4193   SRR33124727  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4201   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....

                                           Organization Org_location  \
1     USDA Animal Plant Health Inspection Service-Na...          USA
9     USDA Animal Plant Health Inspection Service-Na...          USA
17    USDA Animal Plant Health Inspection Service-Na...          USA
25    USDA Animal Plant Health Inspection Service-Na...          USA
33    USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
4169  USDA Animal Plant Health Inspection Service-Na...          USA
4177  USDA Animal Plant Health Inspection Service-Na...          USA
4185  USDA Animal Plant Health Inspection Service-Na...          USA
4193  USDA Animal Plant Health Inspection Service-Na...          USA
4201  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ... Genotype_y  \
1      2025-04-28  25-006346-010-original  ...       D1.1
9      2025-04-28  25-006288-001-original  ...       D1.3
17     2025-04-28  25-006492-001-original  ...       D1.3
25     2025-04-28  25-006496-001-original  ...       D1.3
33     2025-04-28  25-006496-002-original  ...       D1.3
...           ...                     ...  ...        ...
4169   2025-04-14  25-004777-004-original  ...       D1.1
4177   2025-04-28  25-008296-001-original  ...       D1.1
4185   2025-04-28  25-008296-002-original  ...       D1.1
4193   2025-04-28  25-007078-005-original  ...       D1.1
4201   2025-04-28  25-006346-001-original  ...       D1.1

                            Genotype List Used, >=98.0%  \
1     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
9     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
17    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
25    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
33    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
...                                                 ...
4169  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4177  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4185  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4193  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4201  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
1     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
9     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
17    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
25    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
33    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
...                                                 ...
4169  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4177  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4185  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4193  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4201  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
1     99.78%, 99.25%, 99.63%, 99.35%, 99.53%, 99.50%...
9     99.52%, 99.34%, 99.58%, 99.18%, 99.80%, 99.01%...
17    99.74%, 99.34%, 99.63%, 99.18%, 99.87%, 99.01%...
25    99.74%, 99.30%, 99.63%, 99.18%, 99.87%, 99.01%...
33    99.74%, 99.34%, 99.63%, 99.18%, 99.87%, 99.01%...
...                                                 ...
4169  99.69%, 99.34%, 99.67%, 99.47%, 99.53%, 99.29%...
4177  99.78%, 99.21%, 99.86%, 99.47%, 99.80%, 99.57%...
4185  99.78%, 99.21%, 99.81%, 99.41%, 99.80%, 99.57%...
4193  99.69%, 99.43%, 99.63%, 99.24%, 99.80%, 99.50%...
4201  99.74%, 99.25%, 99.67%, 99.35%, 99.53%, 99.50%...

          Genotype Mismatch List Genotype Average Depth of Coverage List  \
1       5, 17, 8, 11, 7, 7, 1, 9       Ran on FASTA - No Coverage Report
9     11, 15, 9, 14, 3, 14, 2, 8       Ran on FASTA - No Coverage Report
17     6, 15, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report
25     6, 16, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report
33     6, 15, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report
...                          ...                                     ...
4169   7, 15, 7, 9, 7, 10, 3, 10       Ran on FASTA - No Coverage Report
4177    5, 18, 3, 9, 3, 6, 0, 10       Ran on FASTA - No Coverage Report
4185   5, 18, 4, 10, 3, 6, 0, 11       Ran on FASTA - No Coverage Report
4193    7, 13, 8, 13, 3, 7, 0, 8       Ran on FASTA - No Coverage Report
4201    6, 17, 7, 11, 7, 7, 0, 9       Ran on FASTA - No Coverage Report

     Host_Type Years                                               Name  \
1        avian  2025  >A/alectoris chukar/USA: PA/25-006346-010-orig...
9        avian  2025  >A/anatidae/USA: IN/25-006288-001-original/202...
17       avian  2025  >A/anatidae/USA: IN/25-006492-001-original/202...
25       avian  2025  >A/anatidae/USA: IN/25-006496-001-original/202...
33       avian  2025  >A/anatidae/USA: IN/25-006496-002-original/202...
...        ...   ...                                                ...
4169     avian  2025  >A/anatidae/USA: NY/25-004777-004-original/202...
4177     avian  2025  >A/anatidae/USA: NY/25-008296-001-original/202...
4185     avian  2025  >A/anatidae/USA: NY/25-008296-002-original/202...
4193     avian  2025  >A/anatidae/USA: OH/25-007078-005-original/202...
4201     avian  2025  >A/anatidae/USA: PA/25-006346-001-original/202...

     Segment_Name
1             PB1
9             PB1
17            PB1
25            PB1
33            PB1
...           ...
4169          PB1
4177          PB1
4185          PB1
4193          PB1
4201          PB1

[526 rows x 41 columns]
PA
       Accession      Organism_Name GenBank_RefSeq         Assembly  \
2     PV571976.1  Influenza A virus        GenBank  GCA_049972745.1
10    PV571984.1  Influenza A virus        GenBank  GCA_049972255.1
18    PV571992.1  Influenza A virus        GenBank  GCA_049972565.1
26    PV572000.1  Influenza A virus        GenBank  GCA_049972785.1
34    PV572008.1  Influenza A virus        GenBank  GCA_049972795.1
...          ...                ...            ...              ...
4170  PV494092.1  Influenza A virus        GenBank  GCA_049649415.1
4178  PV573344.1  Influenza A virus        GenBank  GCA_049973825.1
4186  PV573352.1  Influenza A virus        GenBank  GCA_049973855.1
4194  PV573360.1  Influenza A virus        GenBank  GCA_049973145.1
4202  PV573368.1  Influenza A virus        GenBank  GCA_049972655.1

     SRA_Accession                                         Submitters  \
2      SRR33124746  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
10     SRR33124743  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
18     SRR33124740  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
26     SRR33124739  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
34     SRR33124738  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
4170   SRR32512867  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4178   SRR32868573  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4186   SRR32868572  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4194   SRR33124727  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4202   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....

                                           Organization Org_location  \
2     USDA Animal Plant Health Inspection Service-Na...          USA
10    USDA Animal Plant Health Inspection Service-Na...          USA
18    USDA Animal Plant Health Inspection Service-Na...          USA
26    USDA Animal Plant Health Inspection Service-Na...          USA
34    USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
4170  USDA Animal Plant Health Inspection Service-Na...          USA
4178  USDA Animal Plant Health Inspection Service-Na...          USA
4186  USDA Animal Plant Health Inspection Service-Na...          USA
4194  USDA Animal Plant Health Inspection Service-Na...          USA
4202  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ... Genotype_y  \
2      2025-04-28  25-006346-010-original  ...       D1.1
10     2025-04-28  25-006288-001-original  ...       D1.3
18     2025-04-28  25-006492-001-original  ...       D1.3
26     2025-04-28  25-006496-001-original  ...       D1.3
34     2025-04-28  25-006496-002-original  ...       D1.3
...           ...                     ...  ...        ...
4170   2025-04-14  25-004777-004-original  ...       D1.1
4178   2025-04-28  25-008296-001-original  ...       D1.1
4186   2025-04-28  25-008296-002-original  ...       D1.1
4194   2025-04-28  25-007078-005-original  ...       D1.1
4202   2025-04-28  25-006346-001-original  ...       D1.1

                            Genotype List Used, >=98.0%  \
2     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
10    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
18    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
26    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
34    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
...                                                 ...
4170  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4178  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4186  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4194  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4202  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
2     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
10    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
18    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
26    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
34    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
...                                                 ...
4170  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4178  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4186  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4194  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4202  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
2     99.78%, 99.25%, 99.63%, 99.35%, 99.53%, 99.50%...
10    99.52%, 99.34%, 99.58%, 99.18%, 99.80%, 99.01%...
18    99.74%, 99.34%, 99.63%, 99.18%, 99.87%, 99.01%...
26    99.74%, 99.30%, 99.63%, 99.18%, 99.87%, 99.01%...
34    99.74%, 99.34%, 99.63%, 99.18%, 99.87%, 99.01%...
...                                                 ...
4170  99.69%, 99.34%, 99.67%, 99.47%, 99.53%, 99.29%...
4178  99.78%, 99.21%, 99.86%, 99.47%, 99.80%, 99.57%...
4186  99.78%, 99.21%, 99.81%, 99.41%, 99.80%, 99.57%...
4194  99.69%, 99.43%, 99.63%, 99.24%, 99.80%, 99.50%...
4202  99.74%, 99.25%, 99.67%, 99.35%, 99.53%, 99.50%...

          Genotype Mismatch List Genotype Average Depth of Coverage List  \
2       5, 17, 8, 11, 7, 7, 1, 9       Ran on FASTA - No Coverage Report
10    11, 15, 9, 14, 3, 14, 2, 8       Ran on FASTA - No Coverage Report
18     6, 15, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report

In [36]:
# B3.13 only

# Set up segments

segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"}

metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].map(segments)

# print(metadata_genoflu["Segment_Name"])

# Separate into several dataframes based on genotype + segment
b313_count = 0
segment_genotype_dfs = []
for segment in segments.values():
    print(segment)
    m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
    print(m_g)
    for genotype in list(set(m_g["Genotype_y"].values)):
        if "B3.13" in genotype:
            # b313_count += 1
            df = m_g[(m_g["Genotype_y"] == genotype)] # & (metadata_genoflu["Segment"] == segment)]
            b313_count += len(df)
            segment_genotype_dfs.append(df)
            # pair = genotype + "_" + segment
            # print(pair)

print(b313_count)
# print(segment_genotype_dfs[3])

PB2
       Accession      Organism_Name GenBank_RefSeq         Assembly  \
0     PV571974.1  Influenza A virus        GenBank  GCA_049972745.1
8     PV571982.1  Influenza A virus        GenBank  GCA_049972255.1
16    PV571990.1  Influenza A virus        GenBank  GCA_049972565.1
24    PV571998.1  Influenza A virus        GenBank  GCA_049972785.1
32    PV572006.1  Influenza A virus        GenBank  GCA_049972795.1
...          ...                ...            ...              ...
4168  PV494090.1  Influenza A virus        GenBank  GCA_049649415.1
4176  PV573342.1  Influenza A virus        GenBank  GCA_049973825.1
4184  PV573350.1  Influenza A virus        GenBank  GCA_049973855.1
4192  PV573358.1  Influenza A virus        GenBank  GCA_049973145.1
4200  PV573366.1  Influenza A virus        GenBank  GCA_049972655.1

     SRA_Accession                                         Submitters  \
0      SRR33124746  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
8      SRR33124743  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
16     SRR33124740  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
24     SRR33124739  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
32     SRR33124738  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
4168   SRR32512867  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4176   SRR32868573  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4184   SRR32868572  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4192   SRR33124727  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4200   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....

                                           Organization Org_location  \
0     USDA Animal Plant Health Inspection Service-Na...          USA
8     USDA Animal Plant Health Inspection Service-Na...          USA
16    USDA Animal Plant Health Inspection Service-Na...          USA
24    USDA Animal Plant Health Inspection Service-Na...          USA
32    USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
4168  USDA Animal Plant Health Inspection Service-Na...          USA
4176  USDA Animal Plant Health Inspection Service-Na...          USA
4184  USDA Animal Plant Health Inspection Service-Na...          USA
4192  USDA Animal Plant Health Inspection Service-Na...          USA
4200  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ... Genotype_y  \
0      2025-04-28  25-006346-010-original  ...       D1.1
8      2025-04-28  25-006288-001-original  ...       D1.3
16     2025-04-28  25-006492-001-original  ...       D1.3
24     2025-04-28  25-006496-001-original  ...       D1.3
32     2025-04-28  25-006496-002-original  ...       D1.3
...           ...                     ...  ...        ...
4168   2025-04-14  25-004777-004-original  ...       D1.1
4176   2025-04-28  25-008296-001-original  ...       D1.1
4184   2025-04-28  25-008296-002-original  ...       D1.1
4192   2025-04-28  25-007078-005-original  ...       D1.1
4200   2025-04-28  25-006346-001-original  ...       D1.1

                            Genotype List Used, >=98.0%  \
0     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
8     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
16    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
24    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
32    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
...                                                 ...
4168  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4176  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4184  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4192  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4200  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
0     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
8     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
16    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
24    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
32    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
...                                                 ...
4168  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4176  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4184  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4192  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4200  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
0     99.78%, 99.25%, 99.63%, 99.35%, 99.53%, 99.50%...
8     99.52%, 99.34%, 99.58%, 99.18%, 99.80%, 99.01%...
16    99.74%, 99.34%, 99.63%, 99.18%, 99.87%, 99.01%...
24    99.74%, 99.30%, 99.63%, 99.18%, 99.87%, 99.01%...
32    99.74%, 99.34%, 99.63%, 99.18%, 99.87%, 99.01%...
...                                                 ...
4168  99.69%, 99.34%, 99.67%, 99.47%, 99.53%, 99.29%...
4176  99.78%, 99.21%, 99.86%, 99.47%, 99.80%, 99.57%...
4184  99.78%, 99.21%, 99.81%, 99.41%, 99.80%, 99.57%...
4192  99.69%, 99.43%, 99.63%, 99.24%, 99.80%, 99.50%...
4200  99.74%, 99.25%, 99.67%, 99.35%, 99.53%, 99.50%...

          Genotype Mismatch List Genotype Average Depth of Coverage List  \
0       5, 17, 8, 11, 7, 7, 1, 9       Ran on FASTA - No Coverage Report
8     11, 15, 9, 14, 3, 14, 2, 8       Ran on FASTA - No Coverage Report
16     6, 15, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report
24     6, 16, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report
32     6, 15, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report
...                          ...                                     ...
4168   7, 15, 7, 9, 7, 10, 3, 10       Ran on FASTA - No Coverage Report
4176    5, 18, 3, 9, 3, 6, 0, 10       Ran on FASTA - No Coverage Report
4184   5, 18, 4, 10, 3, 6, 0, 11       Ran on FASTA - No Coverage Report
4192    7, 13, 8, 13, 3, 7, 0, 8       Ran on FASTA - No Coverage Report
4200    6, 17, 7, 11, 7, 7, 0, 9       Ran on FASTA - No Coverage Report

     Host_Type Years                                               Name  \
0        avian  2025  >A/alectoris chukar/USA: PA/25-006346-010-orig...
8        avian  2025  >A/anatidae/USA: IN/25-006288-001-original/202...
16       avian  2025  >A/anatidae/USA: IN/25-006492-001-original/202...
24       avian  2025  >A/anatidae/USA: IN/25-006496-001-original/202...
32       avian  2025  >A/anatidae/USA: IN/25-006496-002-original/202...
...        ...   ...                                                ...
4168     avian  2025  >A/anatidae/USA: NY/25-004777-004-original/202...
4176     avian  2025  >A/anatidae/USA: NY/25-008296-001-original/202...
4184     avian  2025  >A/anatidae/USA: NY/25-008296-002-original/202...
4192     avian  2025  >A/anatidae/USA: OH/25-007078-005-original/202...
4200     avian  2025  >A/anatidae/USA: PA/25-006346-001-original/202...

     Segment_Name
0             PB2
8             PB2
16            PB2
24            PB2
32            PB2
...           ...
4168          PB2
4176          PB2
4184          PB2
4192          PB2
4200          PB2

[526 rows x 41 columns]
PB1
       Accession      Organism_Name GenBank_RefSeq         Assembly  \
1     PV571975.1  Influenza A virus        GenBank  GCA_049972745.1
9     PV571983.1  Influenza A virus        GenBank  GCA_049972255.1
17    PV571991.1  Influenza A virus        GenBank  GCA_049972565.1
25    PV571999.1  Influenza A virus        GenBank  GCA_049972785.1
33    PV572007.1  Influenza A virus        GenBank  GCA_049972795.1
...          ...                ...            ...              ...
4169  PV494091.1  Influenza A virus        GenBank  GCA_049649415.1
4177  PV573343.1  Influenza A virus        GenBank  GCA_049973825.1
4185  PV573351.1  Influenza A virus        GenBank  GCA_049973855.1
4193  PV573359.1  Influenza A virus        GenBank  GCA_049973145.1
4201  PV573367.1  Influenza A virus        GenBank  GCA_049972655.1

     SRA_Accession                                         Submitters  \
1      SRR33124746  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
9      SRR33124743  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
17     SRR33124740  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
25     SRR33124739  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
33     SRR33124738  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
4169   SRR32512867  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4177   SRR32868573  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4185   SRR32868572  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4193   SRR33124727  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4201   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....

                                           Organization Org_location  \
1     USDA Animal Plant Health Inspection Service-Na...          USA
9     USDA Animal Plant Health Inspection Service-Na...          USA
17    USDA Animal Plant Health Inspection Service-Na...          USA
25    USDA Animal Plant Health Inspection Service-Na...          USA
33    USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
4169  USDA Animal Plant Health Inspection Service-Na...          USA
4177  USDA Animal Plant Health Inspection Service-Na...          USA
4185  USDA Animal Plant Health Inspection Service-Na...          USA
4193  USDA Animal Plant Health Inspection Service-Na...          USA
4201  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ... Genotype_y  \
1      2025-04-28  25-006346-010-original  ...       D1.1
9      2025-04-28  25-006288-001-original  ...       D1.3
17     2025-04-28  25-006492-001-original  ...       D1.3
25     2025-04-28  25-006496-001-original  ...       D1.3
33     2025-04-28  25-006496-002-original  ...       D1.3
...           ...                     ...  ...        ...
4169   2025-04-14  25-004777-004-original  ...       D1.1
4177   2025-04-28  25-008296-001-original  ...       D1.1
4185   2025-04-28  25-008296-002-original  ...       D1.1
4193   2025-04-28  25-007078-005-original  ...       D1.1
4201   2025-04-28  25-006346-001-original  ...       D1.1

                            Genotype List Used, >=98.0%  \
1     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
9     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
17    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
25    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
33    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
...                                                 ...
4169  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4177  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4185  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4193  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4201  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
1     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
9     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
17    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
25    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
33    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
...                                                 ...
4169  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4177  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4185  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4193  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4201  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
1     99.78%, 99.25%, 99.63%, 99.35%, 99.53%, 99.50%...
9     99.52%, 99.34%, 99.58%, 99.18%, 99.80%, 99.01%...
17    99.74%, 99.34%, 99.63%, 99.18%, 99.87%, 99.01%...
25    99.74%, 99.30%, 99.63%, 99.18%, 99.87%, 99.01%...
33    99.74%, 99.34%, 99.63%, 99.18%, 99.87%, 99.01%...
...                                                 ...
4169  99.69%, 99.34%, 99.67%, 99.47%, 99.53%, 99.29%...
4177  99.78%, 99.21%, 99.86%, 99.47%, 99.80%, 99.57%...
4185  99.78%, 99.21%, 99.81%, 99.41%, 99.80%, 99.57%...
4193  99.69%, 99.43%, 99.63%, 99.24%, 99.80%, 99.50%...
4201  99.74%, 99.25%, 99.67%, 99.35%, 99.53%, 99.50%...

          Genotype Mismatch List Genotype Average Depth of Coverage List  \
1       5, 17, 8, 11, 7, 7, 1, 9       Ran on FASTA - No Coverage Report
9     11, 15, 9, 14, 3, 14, 2, 8       Ran on FASTA - No Coverage Report
17     6, 15, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report
25     6, 16, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report
33     6, 15, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report
...                          ...                                     ...
4169   7, 15, 7, 9, 7, 10, 3, 10       Ran on FASTA - No Coverage Report
4177    5, 18, 3, 9, 3, 6, 0, 10       Ran on FASTA - No Coverage Report
4185   5, 18, 4, 10, 3, 6, 0, 11       Ran on FASTA - No Coverage Report
4193    7, 13, 8, 13, 3, 7, 0, 8       Ran on FASTA - No Coverage Report
4201    6, 17, 7, 11, 7, 7, 0, 9       Ran on FASTA - No Coverage Report

     Host_Type Years                                               Name  \
1        avian  2025  >A/alectoris chukar/USA: PA/25-006346-010-orig...
9        avian  2025  >A/anatidae/USA: IN/25-006288-001-original/202...
17       avian  2025  >A/anatidae/USA: IN/25-006492-001-original/202...
25       avian  2025  >A/anatidae/USA: IN/25-006496-001-original/202...
33       avian  2025  >A/anatidae/USA: IN/25-006496-002-original/202...
...        ...   ...                                                ...
4169     avian  2025  >A/anatidae/USA: NY/25-004777-004-original/202...
4177     avian  2025  >A/anatidae/USA: NY/25-008296-001-original/202...
4185     avian  2025  >A/anatidae/USA: NY/25-008296-002-original/202...
4193     avian  2025  >A/anatidae/USA: OH/25-007078-005-original/202...
4201     avian  2025  >A/anatidae/USA: PA/25-006346-001-original/202...

     Segment_Name
1             PB1
9             PB1
17            PB1
25            PB1
33            PB1
...           ...
4169          PB1
4177          PB1
4185          PB1
4193          PB1
4201          PB1

[526 rows x 41 columns]
PA
       Accession      Organism_Name GenBank_RefSeq         Assembly  \
2     PV571976.1  Influenza A virus        GenBank  GCA_049972745.1
10    PV571984.1  Influenza A virus        GenBank  GCA_049972255.1
18    PV571992.1  Influenza A virus        GenBank  GCA_049972565.1
26    PV572000.1  Influenza A virus        GenBank  GCA_049972785.1
34    PV572008.1  Influenza A virus        GenBank  GCA_049972795.1
...          ...                ...            ...              ...
4170  PV494092.1  Influenza A virus        GenBank  GCA_049649415.1
4178  PV573344.1  Influenza A virus        GenBank  GCA_049973825.1
4186  PV573352.1  Influenza A virus        GenBank  GCA_049973855.1
4194  PV573360.1  Influenza A virus        GenBank  GCA_049973145.1
4202  PV573368.1  Influenza A virus        GenBank  GCA_049972655.1

     SRA_Accession                                         Submitters  \
2      SRR33124746  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
10     SRR33124743  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
18     SRR33124740  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
26     SRR33124739  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
34     SRR33124738  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
4170   SRR32512867  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4178   SRR32868573  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4186   SRR32868572  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4194   SRR33124727  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4202   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....

                                           Organization Org_location  \
2     USDA Animal Plant Health Inspection Service-Na...          USA
10    USDA Animal Plant Health Inspection Service-Na...          USA
18    USDA Animal Plant Health Inspection Service-Na...          USA
26    USDA Animal Plant Health Inspection Service-Na...          USA
34    USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
4170  USDA Animal Plant Health Inspection Service-Na...          USA
4178  USDA Animal Plant Health Inspection Service-Na...          USA
4186  USDA Animal Plant Health Inspection Service-Na...          USA
4194  USDA Animal Plant Health Inspection Service-Na...          USA
4202  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ... Genotype_y  \
2      2025-04-28  25-006346-010-original  ...       D1.1
10     2025-04-28  25-006288-001-original  ...       D1.3
18     2025-04-28  25-006492-001-original  ...       D1.3
26     2025-04-28  25-006496-001-original  ...       D1.3
34     2025-04-28  25-006496-002-original  ...       D1.3
...           ...                     ...  ...        ...
4170   2025-04-14  25-004777-004-original  ...       D1.1
4178   2025-04-28  25-008296-001-original  ...       D1.1
4186   2025-04-28  25-008296-002-original  ...       D1.1
4194   2025-04-28  25-007078-005-original  ...       D1.1
4202   2025-04-28  25-006346-001-original  ...       D1.1

                            Genotype List Used, >=98.0%  \
2     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
10    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
18    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
26    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
34    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
...                                                 ...
4170  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4178  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4186  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4194  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4202  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
2     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
10    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
18    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
26    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
34    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
...                                                 ...
4170  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4178  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4186  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4194  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4202  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
2     99.78%, 99.25%, 99.63%, 99.35%, 99.53%, 99.50%...
10    99.52%, 99.34%, 99.58%, 99.18%, 99.80%, 99.01%...
18    99.74%, 99.34%, 99.63%, 99.18%, 99.87%, 99.01%...
26    99.74%, 99.30%, 99.63%, 99.18%, 99.87%, 99.01%...
34    99.74%, 99.34%, 99.63%, 99.18%, 99.87%, 99.01%...
...                                                 ...
4170  99.69%, 99.34%, 99.67%, 99.47%, 99.53%, 99.29%...
4178  99.78%, 99.21%, 99.86%, 99.47%, 99.80%, 99.57%...
4186  99.78%, 99.21%, 99.81%, 99.41%, 99.80%, 99.57%...
4194  99.69%, 99.43%, 99.63%, 99.24%, 99.80%, 99.50%...
4202  99.74%, 99.25%, 99.67%, 99.35%, 99.53%, 99.50%...

          Genotype Mismatch List Genotype Average Depth of Coverage List  \
2       5, 17, 8, 11, 7, 7, 1, 9       Ran on FASTA - No Coverage Report
10    11, 15, 9, 14, 3, 14, 2, 8       Ran on FASTA - No Coverage Report
18     6, 15, 8, 14, 2, 14, 3, 9       Ran on FASTA - No Coverage Report

In [17]:
# Create FASTA files

os.chdir(complete_files)

names = []

for df in segment_genotype_dfs:
    if len(df["Genotype_y"].values[0]) > 0:
        file_name = df["Genotype_y"].values[0] + "_" + df["Segment_Name"].values[0] + "_" + update_date + ".fasta"
        output_file = open(complete_files + file_name, "w")

        for index, row in df.iterrows():
            name = df.loc[index, "Name"]
            names.append(name)
            # print(name)
            sequence = df.loc[index, "Sequence"]
            # print(sequence)
            # break 
        # First is header, second is sequence
            output_file.write(name + "\n")
            output_file.write(sequence + "\n")
        output_file.close()

print(len(names))

2352

In [ ]:
# Concatenate

os.chdir(combined_files)

filenames_gisaid_andersen = []
for dirpath, dirs, files in os.walk(gisaid_andersen): # Find the fasta file
    for file in files:
        file_name = os.path.join(dirpath, file) # Get file name
        filenames_gisaid_andersen.append(file_name)
    break 

print(filenames_gisaid_andersen)

filenames_ncbi = []
for dirpath, dirs, files in os.walk(complete_files): # Find the fasta file
    for file in files:
        file_name = os.path.join(dirpath, file) # Get file name
        filenames_ncbi.append(file_name)
    break 

print(filenames_ncbi)

lines = 0

for filename in filenames_gisaid_andersen:
    # lines = 0
    partial_filename = filename.split("_")[-5] + "_" + filename.split("_")[-4] + "_" + filename.split("_")[-3]
    print(partial_filename)
    for fn in filenames_ncbi:
        if partial_filename in fn:
            # print("hi")
            filenames = [filename, fn]
            with open(combined_files + partial_filename + "_combined_" + update_date + ".fasta", 'w') as outfile1:
                for fname in filenames:
                    with open(fname) as infile1:
                        for line in infile1:
                            outfile1.write(line)
                            if line[0] == ">":
                                lines += 1
            #         infile.close()
            # outfile.close()
        else: # Save the ones that aren't shared
            # print("hello")
            with open(combined_files + partial_filename + "_combined_" + update_date + ".fasta", 'w') as outfile2:
                # Copy
                with open(filename) as infile2:
                    for line in infile2:
                        outfile2.write(line)
                        if line[0] == ">":
                                lines += 1
                    # infile.close()
                with open(fn) as infile3:
                    for line in infile3:
                        outfile2.write(line)
                        if line[0] == ">":
                                lines += 1
            #     infile.close()
            # outfile.close()
    # break 

    print(lines)

['C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13_D1_1/04-14-2025--05-14-2025_B3_13/04-14-2025--05-14-2025_B3_13_HA_combined_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13_D1_1/04-14-2025--05-14-2025_B3_13/04-14-2025--05-14-2025_B3_13_MP_combined_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13_D1_1/04-14-2025--05-14-2025_B3_13/04-14-2025--05-14-2025_B3_13_NA_combined_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13_D1_1/04-14-2025--05-14-2025_B3_13/04-14-2025--05-14-2025_B3_13_NP_combined_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13_D1_1/04-14-2025--05-14-2025_B3_13/04-14-2025--05-14-2025_B3_13_NS_combined_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13_D1_1/04-14-2025--05-14-2025_B3_13/04-14-2025--05-14-2025_B3_13_PA_combined_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13_D1_1/04-14-2025--05-14-2025_B3_13/04-14-2025--05-14-2025_B3_13_PB1_combined_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13_D1_1/04-14-2025--05-14-2025_B3_13/04-14-2025--05-14-2025_B3_13_PB2_combined_05-14-2025.fasta']
['C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.13_HA_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.13_MP_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.13_NA_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.13_NP_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.13_NS_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.13_PA_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.13_PB1_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.13_PB2_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.6_HA_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.6_MP_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.6_NA_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.6_NP_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.6_NS_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.6_PA_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.6_PB1_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/B3.6_PB2_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.1_HA_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.1_MP_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.1_NA_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.1_NP_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.1_NS_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.1_PA_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.1_PB1_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.1_PB2_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.3_HA_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.3_MP_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.3_NA_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.3_NP_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.3_NS_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.3_PA_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.3_PB1_05-14-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--05-14-2025_B3_13/D1.3_PB2_05-14-2025.fasta']
B3_13_HA
14416
B3_13_MP
28832
B3_13_NA
43248
B3_13_NP
57664
B3_13_NS
72080
B3_13_PA
86496
B3_13_PB1
100912
B3_13_PB2
115328

In [19]:
# # Mega fasta file
# all_files = []
# for dirpath, dirs, files in os.walk(combined_files):
#     for file in files:
#         file_name = os.path.join(dirpath, file)
#         all_files.append(file_name)

# with open(combined_files + "all_files_combined_" + update_date + ".fasta", 'w') as outfile3:
#     for fname in all_files:
#         with open(fname) as infile4:
#             for line in infile4:
#                 outfile3.write(line)
# #         infile.close()
# # outfile.close()

In [20]:
# Animals 

os.chdir(home)
animals_ref = pd.read_csv("animals_ref.csv")

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genoflu)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['anatidae', 'bos taurus', 'galliformes', 'felis catus', 'meleagris gallopavo', 'alectoris chukar', 'gallus gallus', 'numididae sp.']
[]
                 avian               cattle        feline   other_mammal  \
0     great_horned_owl            dairy_cow           cat     deer mouse
1         common_raven               cattle  domestic_cat    house_mouse
2        cooper's_hawk  cattle milk product     feral_cat          skunk
3         coopers_hawk          bovine_milk        feline  striped_skunk
4              peafowl              bovine   domestic-cat     norway rat
..                 ...                  ...           ...            ...
403   blue-winged teal                  NaN           NaN            NaN
404       lesser scaup                  NaN           NaN            NaN
405   bonaparte's gull                  NaN           NaN            NaN
406  rough-legged hawk                  NaN           NaN            NaN
407         sand crane                  NaN           NaN            NaN

          human         other  new
0    washington         mixed  NaN
1        nevada   environment  NaN
2       wyoming  multispecies  NaN
3    california           NaN  NaN
4      michigan           NaN  NaN
..          ...           ...  ...
403         NaN           NaN  NaN
404         NaN           NaN  NaN
405         NaN           NaN  NaN
406         NaN           NaN  NaN
407         NaN           NaN  NaN

[408 rows x 7 columns]