# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI and relabeling sequences.

In [1]:
# Housekeeping

import os
import pandas as pd
import dateutil
import re
import shutil 
import numpy as np
import importlib
import utils  
importlib.reload(utils)
from utils import *

In [3]:
# Paths and input

# Input
browser = input("Browser (Firefox, Chrome, or Edge): ")
sleep_time = input("Seconds to wait in between clicks (recommended 3): ")
# locations = input("Locations (separate with commas and no spaces in between locations): ")
# start_date = input("Start date (format: MM-DD-YYYY): ")
# end_date = input("End date: (format: MM-DD-YYYY): ")

# Dates and locations
start_date = "11-01-2021"
end_date = "11-14-2025"
date_range = start_date + "--" + end_date
locations = "Antarctica,North America,South America"

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# downloads = "C:/Users/maksi/Downloads/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Downloads/" # MUST be downloads folder. Clean out downloads folder after each use. 
downloads_saved = home + "NCBI_Virus/downloads/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/" # "_Antarctica_North_America_South_America/"
andersen = home + "Andersen/avian-influenza/metadata/"
temp_files = home + "NCBI_Virus/temp/"
complete_files = home + "NCBI_Virus/complete/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/"
if not os.path.exists(complete_files): # checking if the directory exists or not
    os.makedirs(complete_files) # if the directory is not present then create it

references = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/references/"
# references = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/references/"
os.chdir(references)
states_ref = pd.read_csv("states_ref.csv")

# genotypes_df = pd.read_excel("genotype_key.xlsx")
# genotypes = list_df["Genotype"])

# serotype = "H5N1"
genotypes = ["B3.13", "D1.1", "D1.3"]
# genotypes = ["B3.2", "B3.6", "B3.7", "B3.5", "A3", "B3.13", "D1.1", "D1.3"]

## Downloading Data

In [4]:


# browser = "Chrome"
# sleep_time = "3"
# locations = "South America"
# start_date = "07-01-2025"
# end_date = "07-25-2025"

In [5]:
os.chdir(downloads)

if not os.path.exists(downloads_saved): # checking if the directory exists or not
    os.makedirs(downloads_saved) # if the directory is not present then create it

    # Move downloaded files to saved downloads
    for dirpath, dirs, files in os.walk(downloads):
        if len(files) > 0: # If we have any files that need to be moved
            for file in files:
                file_name = os.path.join(dirpath, file)
                destination_path = os.path.join(downloads_saved, os.path.basename(file_name))
                try:
                    shutil.move(file_name, destination_path)
                except:
                    print("Error moving file", file_name)
                    continue 
        else: # If we don't have any downloaded files
            # Get files
            open_ncbi_virus(browser, sleep_time, locations, start_date, end_date)

            # Re-try 
            for dirpath, dirs, files in os.walk(downloads):
                if len(files) > 0: # If we have any files that need to be moved
                    for file in files:
                        file_name = os.path.join(dirpath, file)
                        destination_path = os.path.join(downloads_saved, os.path.basename(file_name))
                        try:
                            shutil.move(file_name, destination_path)
                        except:
                            print("Error moving file", file_name)
                            continue 
                break 
        break

## De-Duplication

In [6]:
os.chdir(downloads_saved)
metadata = pd.read_csv("sequences.csv")
print(len(metadata))

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.Isolate, as_index=False).size()
# print(metadata_counts)
metadata_counted = metadata.merge(metadata_counts, on="Isolate")

# Only keep those with size >= 8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates
metadata_complete_segs = metadata_complete_segs.drop_duplicates(subset="GenBank_Title", keep="last") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]
metadata_segments.head()

117090

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Host,Tissue_Specimen_Source,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size
0,PX508201.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Homo sapiens,NaN,"Goya,S., Nunley,E., Greninger,A.L.","Greninger, Virology",USA,NaN,2025-11-10,2025-11-14,ssRNA(-),8
1,PX508202.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Homo sapiens,NaN,"Goya,S., Nunley,E., Greninger,A.L.","Greninger, Virology",USA,NaN,2025-11-10,2025-11-14,ssRNA(-),8
2,PX508203.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Homo sapiens,NaN,"Goya,S., Nunley,E., Greninger,A.L.","Greninger, Virology",USA,NaN,2025-11-10,2025-11-14,ssRNA(-),8
3,PX508204.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Homo sapiens,NaN,"Goya,S., Nunley,E., Greninger,A.L.","Greninger, Virology",USA,NaN,2025-11-10,2025-11-14,ssRNA(-),8
4,PX508205.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Homo sapiens,NaN,"Goya,S., Nunley,E., Greninger,A.L.","Greninger, Virology",USA,NaN,2025-11-10,2025-11-14,ssRNA(-),8

In [7]:
# # De-duplicate from Andersen using SRA Accession

# # If even one SRA Accession in this list exists in the NCBI Virus dataframe, remove it from NCBI Virus dataframe
# andersen_sras = []
# # Grab files
# for dirpath, dirs, files in os.walk(andersen):
#     for file in files:
#         file_name = os.path.join(dirpath, file)
#         if ".fasta" in file_name:
#             fasta_file = fasta_df_complete(file_name, states_ref) # Convert fasta file to dataframe
#             sra_accessions = fasta_file["Identifier"]
#             for value in sra_accessions.values:
#                 if "SRR" in value:
#                     andersen_sras.append(value)
#             isolates = fasta_file["Isolate_Id"]
#             for value in isolates.values:
#                 andersen_sras.append(value)
#             partials = fasta_file["Partials"]
#             for value in partials.values:
#                 andersen_sras.append(value)
#     break 

# # Grab more files
# # for dirpath, dirs, files in os.walk(andersen_dedup):
# #     for file in files:
# #         file_name = os.path.join(dirpath, file)
# #         if ".fasta" in file_name:
# #             fasta_file = fasta_df_complete(file_name, states_ref) # Convert fasta file to dataframe
# #             sra_accessions = fasta_file["Identifier"]
# #             for value in sra_accessions.values:
# #                 if "SRR" in value:
# #                     andersen_sras.append(value)
            
# metadata_segments["Partials"] = metadata_segments["Isolate"].apply(lambda x: partial_isolate(x) if x == x else x)
# # Remove duplicates from Andersen
# for value in andersen_sras: # to remove
#     if "SRR" in value:
#         metadata_segments = metadata_segments[metadata_segments["SRA_Accession"] != value]
    
#     metadata_segments = metadata_segments[metadata_segments["Isolate"] != value]
#     metadata_segments = metadata_segments[metadata_segments["Partials"] != value]
#     # print(value)
    
# print(len(metadata_segments))
# # metadata_segments
# # print(count)

## Add sequences to dataframe

In [8]:
# NCBI Virus Naming Convention Example:
# Influenza A virus |USA: IN|25-006338-001-original|H5N1|2025-02-20|Meleagris gallopavo|GenBank|SRR33124721|SAMN47941411|PRJNA980729|Influenza A virus (A/Turkey/IN/25-006338-001-original/2025(H5N1)) segment 1 polymerase PB2 (PB2) gene, complete cds
# Organism_Name | Geo_Location | Isolate | Genotype | Collection_Date | Host | GenBank_RefSeq | SRA_Accession | BioSample | BioProject | GenBank_Title | Accession

# Get sequences and headers together
# headers = []
# isolates = []
# sras = []
# headers_seqs = {}

os.chdir(downloads_saved)

sequences_fasta = df_from_fasta("sequences.fasta") # Turn fasta into a dataframe

# Filter dataframe to only include filtered SRA accessions
# sequences_fasta = sequences_fasta[sequences_fasta["full_header"].str.contains("|".join(list(metadata_segments["SRA_Accession"].values)))]
# sequences_fasta["SRA_Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split("|")[-4])
sequences_fasta["Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split("|")[-1][:-1])

# Extract segment number so that we can add the correct sequences to the correct sample
sequences_fasta["Segment"] = sequences_fasta["full_header"].apply(lambda x: int(re.search(r'segment (.?) ', x.split("|")[-2]).group(1)))

# Double-check the de-duplication
print(len(sequences_fasta)) 
print(sequences_fasta.head())
print(len(metadata_segments))

# Add sequences to the dataframe
metadata_segments = pd.merge(metadata_segments, sequences_fasta, on=["Accession", "Segment"])

117090
                                         full_header  \
0  >Influenza A virus |USA: Washington|2148|H5N5|...
1  >Influenza A virus |USA: Washington|2148|H5N5|...
2  >Influenza A virus |USA: Washington|2148|H5N5|...
3  >Influenza A virus |USA: Washington|2148|H5N5|...
4  >Influenza A virus |USA: Washington|2148|H5N5|...

                                            sequence   Accession  Segment
0  GGTTCAATCTGTCAAAATGGAGAACATAGTACTTCTTCTTGCAACA...  PX508201.1        4
1  TAGATATTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTT...  PX508202.1        7
2  GTAGATAATCACTCACTGAGTGACATCAACATCATGGCGTCTCAAG...  PX508203.1        5
3  GTGACAAAAACATAATGGATTTCAACACAGTGTCAAGCTTCCAGGT...  PX508204.1        8
4  TACTGATCCAAAATGGAAGACTTTGTGCGACAATGCTTCAATCCAA...  PX508205.1        3
100808

In [9]:
# # Make sure H5N1 is the only serotype we have

# metadata_segments["serotype"] = metadata_segments["full_header"].apply(lambda x: re.search(r'H.N.', x).group(0))

# metadata_segments = metadata_segments[metadata_segments["serotype"] == serotype]

## Find genotype using old genoflu results or Andersen Lab genoflu output

In [10]:
''' Add old genoflu results manually from previous folder to this one (downloads_saved), named "output_old.tsv" '''

' Add old genoflu results manually from previous folder to this one (downloads_saved), named "output_old.tsv" '

In [11]:
metadata_segments

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size,full_header,sequence
0,PX508201.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Goya,S., Nunley,E., Greninger,A.L.","Greninger, Virology",USA,NaN,2025-11-10,2025-11-14,ssRNA(-),8,>Influenza A virus |USA: Washington|2148|H5N5|...,GGTTCAATCTGTCAAAATGGAGAACATAGTACTTCTTCTTGCAACA...
1,PX508202.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Goya,S., Nunley,E., Greninger,A.L.","Greninger, Virology",USA,NaN,2025-11-10,2025-11-14,ssRNA(-),8,>Influenza A virus |USA: Washington|2148|H5N5|...,TAGATATTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTT...
2,PX508203.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Goya,S., Nunley,E., Greninger,A.L.","Greninger, Virology",USA,NaN,2025-11-10,2025-11-14,ssRNA(-),8,>Influenza A virus |USA: Washington|2148|H5N5|...,GTAGATAATCACTCACTGAGTGACATCAACATCATGGCGTCTCAAG...
3,PX508204.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Goya,S., Nunley,E., Greninger,A.L.","Greninger, Virology",USA,NaN,2025-11-10,2025-11-14,ssRNA(-),8,>Influenza A virus |USA: Washington|2148|H5N5|...,GTGACAAAAACATAATGGATTTCAACACAGTGTCAAGCTTCCAGGT...
4,PX508205.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Goya,S., Nunley,E., Greninger,A.L.","Greninger, Virology",USA,NaN,2025-11-10,2025-11-14,ssRNA(-),8,>Influenza A virus |USA: Washington|2148|H5N5|...,TACTGATCCAAAATGGAAGACTTTGTGCGACAATGCTTCAATCCAA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100803,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...
100804,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...
100805,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...
100806,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...
100807,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...

In [12]:
genoflu_old = pd.read_csv("output_old.tsv", delimiter="\t")
genoflu_old = genoflu_old.rename(columns={"Strain":"Accession_Root"})
metadata_segments["Accession_Root"] = metadata_segments["Accession"].values[0].split(".")[0]

metadata_segments_old = metadata_segments.merge(genoflu_old, how="inner", on="Accession_Root")
metadata_segments_new = metadata_segments.merge(genoflu_old,indicator = True, how='left').loc[lambda x : x['_merge']!='both']

print(len(metadata_segments_old))
print(len(metadata_segments_new))

0
100808

In [13]:
os.chdir(andersen)

genoflu_andersen = pd.read_csv("genoflu_results.tsv", delimiter="\t")
genoflu_andersen = genoflu_andersen.rename(columns={"sample":"SRA_Accession"})

metadata_segments_known = metadata_segments.merge(genoflu_andersen, how="inner", on="SRA_Accession")

metadata_segments_unknown = metadata_segments.merge(genoflu_andersen, indicator = True, how='left', on="SRA_Accession").loc[lambda x : x['_merge']!='both']

print(genoflu_andersen)

      SRA_Accession                 date       File Name  \
0       SRR30789580  2025-05-09_10-49-10  SRR30789580.fa
1       SRR32973809  2025-05-09_10-52-30  SRR32973809.fa
2       SRR32125669  2025-05-09_10-47-22  SRR32125669.fa
3       SRR31597237  2025-05-09_10-47-24  SRR31597237.fa
4       SRR31605135  2025-05-09_10-47-38  SRR31605135.fa
...             ...                  ...             ...
11680   SRR35950025  2025-11-07_05-15-50  SRR35950025.fa
11681   SRR35950026  2025-11-07_05-15-51  SRR35950026.fa
11682   SRR35950027  2025-11-07_05-15-50  SRR35950027.fa
11683   SRR35950028  2025-11-07_05-15-50  SRR35950028.fa
11684   SRR35950029  2025-11-07_05-15-50  SRR35950029.fa

                                                Genotype  \
0      Not assigned: Only 0 segments >98.0% match fou...
1                                                   D1.3
2                                                  B3.13
3                                                  B3.13
4                                                  B3.13
...                                                  ...
11680  Not assigned: Only 3 segments >98.0% match fou...
11681  Not assigned: Only 2 segments >98.0% match fou...
11682  Not assigned: Only 3 segments >98.0% match fou...
11683                                               D1.1
11684                                               D1.1

                             Genotype List Used, >=98.0%  \
0                                        PB1:am4, PA:ea1
1      PB1:ea3, HA:ea3, PB2:am24, NP:am13, NS:ea3, PA...
2      MP:ea1, PA:ea1, HA:ea1, NP:am8, PB2:am2.2, NA:...
3      NP:am8, PB2:am2.2, NA:ea1, MP:ea1, NS:am1.1, P...
4      HA:ea1, NP:am8, PB1:am4, NS:am1.1, PA:ea1, MP:...
...                                                  ...
11680                       NS:am1.2, NP:am1.3, PB2:am19
11681                                 PB1:am20, NP:am1.3
11682                           MP:am1, NP:am1.1, NS:am5
11683  MP:ea3, NA:am4N1, HA:ea3, NS:ea3, PA:am4, NP:a...
11684  NS:ea3, HA:ea3, PB1:ea3, PB2:am24, NP:am13, MP...

                              Genotype Sample Title List  \
0      am4:23-001855-001:PB1, ea1:22-003707-003:PA, a...
1      ea3:22-013001-001:PB1, ea3:22-013001-001:HA, a...
2      ea1:22-003707-003:MP, ea1:22-003707-003:PA, ea...
3      am8:23-032005-001:NP, am2.2:22-010445-001:PB2,...
4      ea1:22-003707-003:HA, am8:23-032005-001:NP, am...
...                                                  ...
11680  am8:24-036222-001:PA, am9:22-037654-001:PB1, a...
11681  am20:23-036657-001:PB1, am1.3:22-010445-001:NP...
11682  am1:24-032138-001:MP, am2.2:22-010445-001:PB2,...
11683  ea3:22-013001-001:MP, am4N1:24-030039-001:NA, ...
11684  ea3:22-013001-001:NS, ea3:22-013001-001:HA, ea...

                             Genotype Percent Match List  \
0         98.12%, 98.31%, 93.08%, 97.57%, 97.44%, 96.58%
1      99.21%, 99.59%, 99.56%, 99.47%, 98.93%, 99.58%...
2      98.98%, 98.88%, 98.41%, 98.93%, 98.68%, 98.86%...
3      99.06%, 98.60%, 98.86%, 98.98%, 99.05%, 99.07%...
4      98.47%, 99.06%, 99.47%, 99.17%, 99.02%, 98.98%...
...                                                  ...
11680     96.47%, 97.76%, 96.33%, 98.81%, 98.06%, 98.73%
11681  98.06%, 98.06%, 87.69%, 96.10%, 97.35%, 95.75%...
11682     98.06%, 97.98%, 98.46%, 97.17%, 97.14%, 99.00%
11683  99.69%, 99.29%, 99.00%, 99.05%, 99.49%, 99.53%...
11684  99.28%, 99.35%, 98.95%, 99.47%, 99.87%, 99.90%...

              Genotype Mismatch List Genotype Average Depth of Coverage List
0                  3, 3, 13, 5, 3, 4       Ran on FASTA - No Coverage Report
1          18, 7, 10, 8, 9, 9, 0, 19       Ran on FASTA - No Coverage Report
2      10, 24, 27, 16, 30, 16, 7, 12       Ran on FASTA - No Coverage Report
3      14, 32, 16, 10, 8, 20, 11, 26       Ran on FASTA - No Coverage Report
4      26, 14, 12, 7, 21, 10, 31, 15       Ran on FASTA - No Coverage Report
...                              ...                                     ...
11680         76, 51, 36, 10, 29, 29       Ran on FASTA - No Coverage Report
11681      44, 29, 8, 89, 26, 56, 20       Ran on FASTA - No Coverage Report
11682          19, 46, 23, 33, 63, 2       Ran on FASTA - No Coverage Report
11683      3, 8, 17, 8, 11, 7, 18, 5       Ran on FASTA - No Coverage Report
11684     6, 11, 19, 12, 2, 1, 9, 11       Ran on FASTA - No Coverage Report

[11685 rows x 9 columns]

In [14]:
metadata_segments_known

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,sequence,Accession_Root,date,File Name,Genotype_y,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List
0,PX440412.1,GenBank,GCA_052945965.1,SRR35150543,SAMN50804733,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...,PX508201,2025-08-29_06-15-55,SRR35150543.fa,B3.13,"NA:ea1, MP:ea1, HA:ea1, PB2:am2.2, NS:am1.1, N...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, ea...","98.65%, 98.98%, 98.18%, 98.42%, 98.81%, 98.40%...","19, 10, 31, 36, 10, 24, 27, 21",Ran on FASTA - No Coverage Report
1,PX440413.1,GenBank,GCA_052945965.1,SRR35150543,SAMN50804733,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...,PX508201,2025-08-29_06-15-55,SRR35150543.fa,B3.13,"NA:ea1, MP:ea1, HA:ea1, PB2:am2.2, NS:am1.1, N...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, ea...","98.65%, 98.98%, 98.18%, 98.42%, 98.81%, 98.40%...","19, 10, 31, 36, 10, 24, 27, 21",Ran on FASTA - No Coverage Report
2,PX440414.1,GenBank,GCA_052945965.1,SRR35150543,SAMN50804733,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...,PX508201,2025-08-29_06-15-55,SRR35150543.fa,B3.13,"NA:ea1, MP:ea1, HA:ea1, PB2:am2.2, NS:am1.1, N...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, ea...","98.65%, 98.98%, 98.18%, 98.42%, 98.81%, 98.40%...","19, 10, 31, 36, 10, 24, 27, 21",Ran on FASTA - No Coverage Report
3,PX440415.1,GenBank,GCA_052945965.1,SRR35150543,SAMN50804733,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGAAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...,PX508201,2025-08-29_06-15-55,SRR35150543.fa,B3.13,"NA:ea1, MP:ea1, HA:ea1, PB2:am2.2, NS:am1.1, N...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, ea...","98.65%, 98.98%, 98.18%, 98.42%, 98.81%, 98.40%...","19, 10, 31, 36, 10, 24, 27, 21",Ran on FASTA - No Coverage Report
4,PX440416.1,GenBank,GCA_052945965.1,SRR35150543,SAMN50804733,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...,PX508201,2025-08-29_06-15-55,SRR35150543.fa,B3.13,"NA:ea1, MP:ea1, HA:ea1, PB2:am2.2, NS:am1.1, N...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, ea...","98.65%, 98.98%, 98.18%, 98.42%, 98.81%, 98.40%...","19, 10, 31, 36, 10, 24, 27, 21",Ran on FASTA - No Coverage Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38235,PQ012131.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...,PX508201,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report
38236,PQ012132.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...,PX508201,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report
38237,PQ012133.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...,PX508201,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report
38238,PQ012134.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...,PX508201,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report
38239,PQ012135.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...,PX508201,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report

In [15]:
metadata_segments_unknown

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Accession_Root,date,File Name,Genotype_y,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,_merge
0,PX508201.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,PX508201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,PX508202.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,PX508201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,PX508203.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,PX508201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,PX508204.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,PX508201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,PX508205.1,GenBank,GCA_053491305.1,SRR36016324,NaN,PRJNA1363857,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,PX508201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100803,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,PX508201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100804,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,PX508201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100805,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,PX508201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100806,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,PX508201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100807,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,PX508201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

## Create FASTA files of unknown genotypes using deduplicated sequences

In [16]:
# # Create 1 fasta file per header
# metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["full_header"].apply(lambda x: "|".join(x.split("|")[:-2]))

# # Create list of dataframes
# df_list = []
# for partial_header in list(set(metadata_segments_unknown["Partial_Header"].values)): # Unique partial headers only
#     # Get smaller dataframe
#     df = metadata_segments_unknown[metadata_segments_unknown["Partial_Header"] == partial_header]
#     df = df.sort_values(by="Segment")
#     # Make sure there are 8 segments
#     if len(df) == 8:
#         # Forbidden characters in headers
#         for c in ["/", "|", " ", ":", ",", "(", ")", "-"]:
#             df["full_header"] = df["full_header"].apply(lambda x: x.replace(c, "_"))
#             df_list.append(df)

# # Make fasta files
# for df in df_list:
#     # Forbidden characters in file name 
#     title = df["Accession"].values[0].split(".")[0]
#     # for c in [">", "/", "|", " ", ":", ",", "(", ")", "-"]:
#     #     title = title.replace(c, "_")
#     df_to_fasta(df, title + ".fasta", temp_files)

In [17]:
# Create 8 fasta files per segment

# Get all the segments
metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["full_header"].apply(lambda x: "|".join(x.split("|")[:-2]))

# Create list of dataframes
df_list = []
for partial_header in list(set(metadata_segments_unknown["Partial_Header"].values)): # Unique partial headers only
    # Get smaller dataframe
    df = metadata_segments_unknown[metadata_segments_unknown["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    # print(partial_header)
    # print(df["Segment"])
    # break 
    # Make sure there are 8 segments
    if len(df) == 8:
        # Forbidden characters in headers
        for c in ["/", "|", " ", ":", ",", "(", ")", "-"]:
            df["Partial_Header"] = df["Partial_Header"].apply(lambda x: x.replace(c, "_"))
            # if c == "-":
        df["full_header"] = df["Partial_Header"]
        df_list.append(df)

print(df_list[0]["full_header"])

# Make fasta files
for df in df_list:
    # Forbidden characters in file name 
    # title = df["Accession"].values[0].split(".")[0]
    segments = list(set(df["Segment"].apply(lambda x: int(x)).values))
    # print(df)
    # print(segments)
    # break 
    # for c in [">", "/", "|", " ", ":", ",", "(", ")", "-"]:
    #     title = title.replace(c, "_")
    for segment in segments:
        one_row = df[df["Segment"] == segment]
        # print(one_row["full_header"])
        # print(segment)
        # break 
        df_to_fasta(one_row, str(segment) + "_seg.fasta", temp_files)
    # break

29856    >Influenza_A_virus__Canada__SK_FAV_1386_1_2022...
29857    >Influenza_A_virus__Canada__SK_FAV_1386_1_2022...
29858    >Influenza_A_virus__Canada__SK_FAV_1386_1_2022...
29859    >Influenza_A_virus__Canada__SK_FAV_1386_1_2022...
29860    >Influenza_A_virus__Canada__SK_FAV_1386_1_2022...
29861    >Influenza_A_virus__Canada__SK_FAV_1386_1_2022...
29862    >Influenza_A_virus__Canada__SK_FAV_1386_1_2022...
29863    >Influenza_A_virus__Canada__SK_FAV_1386_1_2022...
Name: full_header, dtype: object

## Re-Labeling Using GenoFlu

**STOP HERE AND USE GENOFLU TO FIND NEW GENOTYPES.** Then, make sure "output.tsv" is in the downloads directory.

In [ ]:
'''
To run GenoFLU-multi, first change directories (and activate genoflu conda environment):

conda activate genoflu
cd GenoFLU-multi

And then call the python script:

python bin/genoflu-multi.py -f <FASTA_directory>
'''

'\n## In Ubuntu 22.04.3 LTS ##\n\nconda activate genoflu\n\n## Genoflu.py iteratively through all FASTAs in directory ##\n\nfor file in *.fasta; do genoflu.py -f "$file"; sleep 0.75; done\n\n## Concatenate output files ##\n\n awk \'(NR == 1) || (FNR > 1)\' *.tsv > output.tsv\n'

In [18]:
metadata_segments_known

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,serotype,Accession_Root,date,File Name,Genotype_y,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List
0,PX440412.1,GenBank,GCA_052945965.1,SRR35150543,SAMN50804733,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,H5N1,PX440412,2025-08-29_06-15-55,SRR35150543.fa,B3.13,"NA:ea1, MP:ea1, HA:ea1, PB2:am2.2, NS:am1.1, N...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, ea...","98.65%, 98.98%, 98.18%, 98.42%, 98.81%, 98.40%...","19, 10, 31, 36, 10, 24, 27, 21",Ran on FASTA - No Coverage Report
1,PX440413.1,GenBank,GCA_052945965.1,SRR35150543,SAMN50804733,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,H5N1,PX440412,2025-08-29_06-15-55,SRR35150543.fa,B3.13,"NA:ea1, MP:ea1, HA:ea1, PB2:am2.2, NS:am1.1, N...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, ea...","98.65%, 98.98%, 98.18%, 98.42%, 98.81%, 98.40%...","19, 10, 31, 36, 10, 24, 27, 21",Ran on FASTA - No Coverage Report
2,PX440414.1,GenBank,GCA_052945965.1,SRR35150543,SAMN50804733,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,H5N1,PX440412,2025-08-29_06-15-55,SRR35150543.fa,B3.13,"NA:ea1, MP:ea1, HA:ea1, PB2:am2.2, NS:am1.1, N...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, ea...","98.65%, 98.98%, 98.18%, 98.42%, 98.81%, 98.40%...","19, 10, 31, 36, 10, 24, 27, 21",Ran on FASTA - No Coverage Report
3,PX440415.1,GenBank,GCA_052945965.1,SRR35150543,SAMN50804733,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,H5N1,PX440412,2025-08-29_06-15-55,SRR35150543.fa,B3.13,"NA:ea1, MP:ea1, HA:ea1, PB2:am2.2, NS:am1.1, N...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, ea...","98.65%, 98.98%, 98.18%, 98.42%, 98.81%, 98.40%...","19, 10, 31, 36, 10, 24, 27, 21",Ran on FASTA - No Coverage Report
4,PX440416.1,GenBank,GCA_052945965.1,SRR35150543,SAMN50804733,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,H5N1,PX440412,2025-08-29_06-15-55,SRR35150543.fa,B3.13,"NA:ea1, MP:ea1, HA:ea1, PB2:am2.2, NS:am1.1, N...","ea1:22-003707-003:NA, ea1:22-003707-003:MP, ea...","98.65%, 98.98%, 98.18%, 98.42%, 98.81%, 98.40%...","19, 10, 31, 36, 10, 24, 27, 21",Ran on FASTA - No Coverage Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38179,PQ012131.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,H5N1,PX440412,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report
38180,PQ012132.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,H5N1,PX440412,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report
38181,PQ012133.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,H5N1,PX440412,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report
38182,PQ012134.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,H5N1,PX440412,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report
38183,PQ012135.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,H5N1,PX440412,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report

In [32]:
# Merging

os.chdir(downloads_saved)

# Read in genoflu results
output_genoflu = pd.read_csv("output.tsv", delimiter="\t")

metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["full_header"].apply(lambda x: "|".join(x.split("|")[:-2]))
for c in ["/", "|", " ", ":", ",", "(", ")", "-"]:
    metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["Partial_Header"].apply(lambda x: x.replace(c, "_"))

metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["Partial_Header"].apply(lambda x: x.replace(">", ""))

metadata_segments_unknown["Strain"] = metadata_segments_unknown["Partial_Header"]

metadata_genoflu = metadata_segments_unknown.merge(output_genoflu, how="left", on="Strain") 

# Fill the rest of the 8 segments with the same genotype
metadata_genoflu = metadata_genoflu.ffill()

print(metadata_genoflu)

print(metadata_genoflu["Genotype_x"])

print(metadata_genoflu.columns)

        Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0      PX508201.1        GenBank  GCA_053491305.1   SRR36016324           NaN
1      PX508202.1        GenBank  GCA_053491305.1   SRR36016324           NaN
2      PX508203.1        GenBank  GCA_053491305.1   SRR36016324           NaN
3      PX508204.1        GenBank  GCA_053491305.1   SRR36016324           NaN
4      PX508205.1        GenBank  GCA_053491305.1   SRR36016324           NaN
...           ...            ...              ...           ...           ...
62563  OK205883.1        GenBank  GCA_038165665.1   SRR23852495  SAMN33745292
62564  OK205884.1        GenBank  GCA_038165665.1   SRR23852495  SAMN33745292
62565  OK205885.1        GenBank  GCA_038165665.1   SRR23852495  SAMN33745292
62566  OK205886.1        GenBank  GCA_038165665.1   SRR23852495  SAMN33745292
62567  OK205887.1        GenBank  GCA_038165665.1   SRR23852495  SAMN33745292

         BioProject      Organism_Name                         Species  \
0      PRJNA1363857  Influenza A virus  Alphainfluenzavirus influenzae
1      PRJNA1363857  Influenza A virus  Alphainfluenzavirus influenzae
2      PRJNA1363857  Influenza A virus  Alphainfluenzavirus influenzae
3      PRJNA1363857  Influenza A virus  Alphainfluenzavirus influenzae
4      PRJNA1363857  Influenza A virus  Alphainfluenzavirus influenzae
...             ...                ...                             ...
62563   PRJNA944237  Influenza A virus  Alphainfluenzavirus influenzae
62564   PRJNA944237  Influenza A virus  Alphainfluenzavirus influenzae
62565   PRJNA944237  Influenza A virus  Alphainfluenzavirus influenzae
62566   PRJNA944237  Influenza A virus  Alphainfluenzavirus influenzae
62567   PRJNA944237  Influenza A virus  Alphainfluenzavirus influenzae

                     Genus            Family  ...     _merge  \
0      Alphainfluenzavirus  Orthomyxoviridae  ...  left_only
1      Alphainfluenzavirus  Orthomyxoviridae  ...  left_only
2      Alphainfluenzavirus  Orthomyxoviridae  ...  left_only
3      Alphainfluenzavirus  Orthomyxoviridae  ...  left_only
4      Alphainfluenzavirus  Orthomyxoviridae  ...  left_only
...                    ...               ...  ...        ...
62563  Alphainfluenzavirus  Orthomyxoviridae  ...  left_only
62564  Alphainfluenzavirus  Orthomyxoviridae  ...  left_only
62565  Alphainfluenzavirus  Orthomyxoviridae  ...  left_only
62566  Alphainfluenzavirus  Orthomyxoviridae  ...  left_only
62567  Alphainfluenzavirus  Orthomyxoviridae  ...  left_only

                                          Partial_Header  \
0      Influenza_A_virus__USA__Washington_2148_H5N5_2...
1      Influenza_A_virus__USA__Washington_2148_H5N5_2...
2      Influenza_A_virus__USA__Washington_2148_H5N5_2...
3      Influenza_A_virus__USA__Washington_2148_H5N5_2...
4      Influenza_A_virus__USA__Washington_2148_H5N5_2...
...                                                  ...
62563  Influenza_A_virus__Mexico__Veracruz_28159_398_...
62564  Influenza_A_virus__Mexico__Veracruz_28159_398_...
62565  Influenza_A_virus__Mexico__Veracruz_28159_398_...
62566  Influenza_A_virus__Mexico__Veracruz_28159_398_...
62567  Influenza_A_virus__Mexico__Veracruz_28159_398_...

                                                  Strain  \
0      Influenza_A_virus__USA__Washington_2148_H5N5_2...
1      Influenza_A_virus__USA__Washington_2148_H5N5_2...
2      Influenza_A_virus__USA__Washington_2148_H5N5_2...
3      Influenza_A_virus__USA__Washington_2148_H5N5_2...
4      Influenza_A_virus__USA__Washington_2148_H5N5_2...
...                                                  ...
62563  Influenza_A_virus__Mexico__Veracruz_28159_398_...
62564  Influenza_A_virus__Mexico__Veracruz_28159_398_...
62565  Influenza_A_virus__Mexico__Veracruz_28159_398_...
62566  Influenza_A_virus__Mexico__Veracruz_28159_398_...
62567  Influenza_A_virus__Mexico__Veracruz_28159_398_...

                                                Genotype  \
0                                                     A6
1                                                     A6
2                                                     A6
3                                                     A6
4                                                     A6
...                                                  ...
62563  Not assigned: Only 0 segments >98.0% match fou...
62564  Not assigned: Only 0 segments >98.0% match fou...
62565  Not assigned: Only 0 segments >98.0% match fou...
62566  Not assigned: Only 0 segments >98.0% match fou...
62567  Not assigned: Only 0 segments >98.0% match fou...

                           Genotype List Used, >=98.0%_y  \
0      PB2:ea6, PB1:ea6, PA:ea6, HA:ea6, NP:ea6, NA:e...
1      PB2:ea6, PB1:ea6, PA:ea6, HA:ea6, NP:ea6, NA:e...
2      PB2:ea6, PB1:ea6, PA:ea6, HA:ea6, NP:ea6, NA:e...
3      PB2:ea6, PB1:ea6, PA:ea6, HA:ea6, NP:ea6, NA:e...
4      PB2:ea6, PB1:ea6, PA:ea6, HA:ea6, NP:ea6, NA:e...
...                                                  ...
62563               PB2:am5, PB1:am4, NA:am1N4, NS:am1.2
62564               PB2:am5, PB1:am4, NA:am1N4, NS:am1.2
62565               PB2:am5, PB1:am4, NA:am1N4, NS:am1.2
62566               PB2:am5, PB1:am4, NA:am1N4, NS:am1.2
62567               PB2:am5, PB1:am4, NA:am1N4, NS:am1.2

                            Genotype Sample Title List_y  \
0      ea6:23-004612-001:PB2, ea6:23-004612-001:PB1, ...
1      ea6:23-004612-001:PB2, ea6:23-004612-001:PB1, ...
2      ea6:23-004612-001:PB2, ea6:23-004612-001:PB1, ...
3      ea6:23-004612-001:PB2, ea6:23-004612-001:PB1, ...
4      ea6:23-004612-001:PB2, ea6:23-004612-001:PB1, ...
...                                                  ...
62563  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...
62564  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...
62565  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...
62566  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...
62567  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...

                           Genotype Percent Match List_y  \
0      99.65%, 99.30%, 99.12%, 98.89%, 99.47%, 99.11%...
1      99.65%, 99.30%, 99.12%, 98.89%, 99.47%, 99.11%...
2      99.65%, 99.30%, 99.12%, 98.89%, 99.47%, 99.11%...
3      99.65%, 99.30%, 99.12%, 98.89%, 99.47%, 99.11%...
4      99.65%, 99.30%, 99.12%, 98.89%, 99.47%, 99.11%...
...                                                  ...
62563  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...
62564  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...
62565  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...
62566  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...
62567  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...

                  Genotype Mismatch List_y  \
0               8, 16, 19, 19, 8, 12, 3, 6
1               8, 16, 19, 19, 8, 12, 3, 6
2               8, 16, 19, 19, 8, 12, 3, 6
3               8, 16, 19, 19, 8, 12, 3, 6
4               8, 16, 19, 19, 8, 12, 3, 6
...                                    ...
62563  194, 103, 194, 319, 91, 134, 39, 40
62564  194, 103, 194, 319, 91, 134, 39, 40
62565  194, 103, 194, 319, 91, 134, 39, 40
62566  194, 103, 194, 319, 91, 134, 39, 40
62567  194, 103, 194, 319, 91, 134, 39, 40

      Genotype Average Depth of Coverage List_y             Date run
0             Ran on FASTA - No Coverage Report  2025-11-18_11-54-55
1             Ran on FASTA - No Coverage Report  2025-11-18_11-54-55
2             Ran on FASTA - No Coverage Report  2025-11-18_11-54-55
3             Ran on FASTA - No Coverage Report  2025-11-18_11-54-55
4             Ran on FASTA - No Coverage Report  2025-11-18_11-54-55
...                                         ...                  ...
62563         Ran on FASTA - No Coverage Report  2025-11-18_11-53-35
62564         Ran on FASTA - No Coverage Report  2025-11-18_11-53-35
62565         Ran on FASTA - No Coverage Report  2025-11-18_11-53-35
62566         Ran on FASTA - No Coverage Report  2025-11-18_11-53-35
62567         Ran on FASTA - No Coverage Report  2025-11-18_11-53-35

[62568 rows x 50 columns]
0        H5N5
1        H5N5
2        H5N5
3        H5N5
4        H5N5
         ...
62563    H5N2
62564    H5N2
62565    H5N2
62566    H5N2
62567    H5N2
Name: Genotype_x, Length: 62568, dtype: object
Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Accession_Root', 'date',
       'File Name', 'Genotype_y', 'Genotype List Used, >=98.0%_x',
       'Genotype Sample Title List_x', 'Genotype Percent Match List_x',
       'Genotype Mismatch List_x', 'Genotype Average Depth of Coverage List_x',
       '_merge', 'Partial_Header', 'Strain', 'Genotype',
       'Genotype List Used, >=98.0%_y', 'Genotype Sample Title List_y',
       'Genotype Percent Match List_y', 'Genotype Mismatch List_y',
       'Genotype Average Depth of Coverage List_y', 'Date run'],
      dtype='object')

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_16096\1490668429.py:19: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  metadata_genoflu = metadata_genoflu.ffill()

# Concatenate with known genotypes

In [33]:
metadata_segments_known["Genotype"] = metadata_segments_known["Genotype_y"]
metadata_segments_known["Serotype"] = metadata_segments_known["Genotype_x"]

metadata_genoflu = pd.concat([metadata_genoflu, metadata_segments_known])

metadata_genoflu.columns

Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Accession_Root', 'date',
       'File Name', 'Genotype_y', 'Genotype List Used, >=98.0%_x',
       'Genotype Sample Title List_x', 'Genotype Percent Match List_x',
       'Genotype Mismatch List_x', 'Genotype Average Depth of Coverage List_x',
       '_merge', 'Partial_Header', 'Strain', 'Genotype',
       'Genotype List Used, >=98.0%_y', 'Genotype Sample Title List_y',
       'Genotype Percent Match List_y', 'Genotype Mismatch List_y',
       'Genotype Average Depth of Coverage List_y', 'Date run',
       'Genotype List Used, >=98.0%', 'Genotype Sample Title List',
       'Genotype Percent Match List', 'Genotype Mismatch List',
       'Genotype Average Depth of Coverage List', 'Serotype'],
      dtype='object')

In [37]:
metadata_genoflu = metadata_genoflu[["Accession", "GenBank_Title", "Host", "Collection_Date", "SRA_Accession", "Isolate", "Genotype", "Geo_Location", "full_header", "sequence", "Serotype", "Segment", "File Name", "Partial_Header", "Strain"]]

metadata_genoflu["genbank_name"] = metadata_genoflu["GenBank_Title"].apply(lambda x: x.split("(")[1] )
metadata_genoflu["Host"] = metadata_genoflu["genbank_name"].apply(lambda x: x.split("/")[1])

metadata_genoflu = metadata_genoflu.dropna(subset="SRA_Accession")
# metadata_genoflu = metadata_genoflu[~metadata_genoflu.duplicated(["Segment", "SRA_Accession"], keep=False).groupby(df["SRA_Accession"]).transform('sum').ge(8)]
# metadata_genoflu = metadata_genoflu.drop_duplicates(subset=["SRA_Accession", "Segment"], keep="first", inplace=True)

metadata_genoflu # [metadata_genoflu["Genotype"]  == "B3.13"]

,Accession,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype,Geo_Location,full_header,sequence,Serotype,Segment,File Name,Partial_Header,Strain,genbank_name
0,PX508201.1,Influenza A virus (A/Washington/2148/2025(H5N5...,Washington,2025-11-10,SRR36016324,2148,A6,USA: Washington,>Influenza A virus |USA: Washington|2148|H5N5|...,GGTTCAATCTGTCAAAATGGAGAACATAGTACTTCTTCTTGCAACA...,NaN,4,NaN,Influenza_A_virus__USA__Washington_2148_H5N5_2...,Influenza_A_virus__USA__Washington_2148_H5N5_2...,A/Washington/2148/2025
1,PX508202.1,Influenza A virus (A/Washington/2148/2025(H5N5...,Washington,2025-11-10,SRR36016324,2148,A6,USA: Washington,>Influenza A virus |USA: Washington|2148|H5N5|...,TAGATATTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTT...,NaN,7,NaN,Influenza_A_virus__USA__Washington_2148_H5N5_2...,Influenza_A_virus__USA__Washington_2148_H5N5_2...,A/Washington/2148/2025
2,PX508203.1,Influenza A virus (A/Washington/2148/2025(H5N5...,Washington,2025-11-10,SRR36016324,2148,A6,USA: Washington,>Influenza A virus |USA: Washington|2148|H5N5|...,GTAGATAATCACTCACTGAGTGACATCAACATCATGGCGTCTCAAG...,NaN,5,NaN,Influenza_A_virus__USA__Washington_2148_H5N5_2...,Influenza_A_virus__USA__Washington_2148_H5N5_2...,A/Washington/2148/2025
3,PX508204.1,Influenza A virus (A/Washington/2148/2025(H5N5...,Washington,2025-11-10,SRR36016324,2148,A6,USA: Washington,>Influenza A virus |USA: Washington|2148|H5N5|...,GTGACAAAAACATAATGGATTTCAACACAGTGTCAAGCTTCCAGGT...,NaN,8,NaN,Influenza_A_virus__USA__Washington_2148_H5N5_2...,Influenza_A_virus__USA__Washington_2148_H5N5_2...,A/Washington/2148/2025
4,PX508205.1,Influenza A virus (A/Washington/2148/2025(H5N5...,Washington,2025-11-10,SRR36016324,2148,A6,USA: Washington,>Influenza A virus |USA: Washington|2148|H5N5|...,TACTGATCCAAAATGGAAGACTTTGTGCGACAATGCTTCAATCCAA...,NaN,3,NaN,Influenza_A_virus__USA__Washington_2148_H5N5_2...,Influenza_A_virus__USA__Washington_2148_H5N5_2...,A/Washington/2148/2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38235,PQ012131.1,Influenza A virus (A/Turkey/Minnesota/24-01468...,Turkey,2024-05-18,SRR29281472,24-014685-001-original,B3.13,USA:MN,>Influenza A virus |USA:MN|24-014685-001-origi...,ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...,H5N1,4,SRR29281472.fa,NaN,NaN,A/Turkey/Minnesota/24-014685-001-original/2024
38236,PQ012132.1,Influenza A virus (A/Turkey/Minnesota/24-01468...,Turkey,2024-05-18,SRR29281472,24-014685-001-original,B3.13,USA:MN,>Influenza A virus |USA:MN|24-014685-001-origi...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...,H5N1,5,SRR29281472.fa,NaN,NaN,A/Turkey/Minnesota/24-014685-001-original/2024
38237,PQ012133.1,Influenza A virus (A/Turkey/Minnesota/24-01468...,Turkey,2024-05-18,SRR29281472,24-014685-001-original,B3.13,USA:MN,>Influenza A virus |USA:MN|24-014685-001-origi...,ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...,H5N1,6,SRR29281472.fa,NaN,NaN,A/Turkey/Minnesota/24-014685-001-original/2024
38238,PQ012134.1,Influenza A virus (A/Turkey/Minnesota/24-01468...,Turkey,2024-05-18,SRR29281472,24-014685-001-original,B3.13,USA:MN,>Influenza A virus |USA:MN|24-014685-001-origi...,ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...,H5N1,7,SRR29281472.fa,NaN,NaN,A/Turkey/Minnesota/24-014685-001-original/2024
38239,PQ012135.1,Influenza A virus (A/Turkey/Minnesota/24-01468...,Turkey,2024-05-18,SRR29281472,24-014685-001-original,B3.13,USA:MN,>Influenza A virus |USA:MN|24-014685-001-origi...,ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...,H5N1,8,SRR29281472.fa,NaN,NaN,A/Turkey/Minnesota/24-014685-001-original/2024

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

In [39]:
# Animals 

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genoflu)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['red-breasted merganser', 'mergus', 'common eider', 'eared grebe', 'white-winged scoter', 'pheasant', 'glaucous gull', 'long-eared owl', 'greater scaup', 'white-winged dove', 'otaria flavescens', 'crane', 'savannah cat', 'nevada', 'wyoming', 'nannopterum brasilianus', 'greater white-fronted goose', 'red-necked grebe', 'cattle milk product', 'snowy egret', 'duck', 'raccoon', 'rock pigeon', 'green heron', 'domestic cat', 'michigan', 'great-horned owl', 'bos taurus', 'antofagasta', 'bobcat', 'american crow', 'thayers gull', 'anatinae', 'lynx', 'dunlin', 'gallus', 'american goshawk', 'goose', 'hawk', 'emu', 'cat', 'gyrfalcon', 'wild bird', 'serval', 'thalasseus maximus', 'western sandpiper', 'common merganser', 'black-billed magpie', 'american black duck', 'guinea fowl', 'broad-winged hawk', 'gray seal', 'domestic turkey', 'atlantic puffin', 'california condor', 'surf scoter', 'heron', 'american kestrel', 'rosy-billed pochard', 'crested caracara', 'great egret', 'mottled duck', 'bald eagle', 'black-crowned night heron', 'red fox', 'red-shouldered hawk', 'partridge', 'black brant', 'swan', 'black skimmer', 'black turnstone', 'eurasian collared dove', 'thalasseus acuflavidus', 'domestic bird', 'crow', 'western snowy plover', 'california gull', 'snowy owl', 'great horned owl', 'swine', 'fancy chicken', 'south american sea lion', 'quail', 'green-winged teal', 'backyard bird', 'pelecanus thagus', 'southern elephant seal', 'short-billed gull', 'numida meleagris', 'blue-winged and cinnamon teal', 'eider', 'skunk', 'sanderling', 'backyard duck', 'royal tern', 'laridae', 'wild duck', 'south american fur seal', 'owl', 'brant', 'pelecanus', 'taiwanese chicken', 'vulture', 'house sparrow', 'dog', 'guanay cormorant', 'chukar', 'pig', 'lesser white-fronted goose', 'tundra swan', 'blue jay', 'louisiana', 'black-necked swan', 'raw pet food', 'aves', 'striped skunk', 'american wood stork', 'snow goose', 'mute swan', 'backyard turkey', 'sandhill crane', 'black bear', 'neotropic cormorant', 'guinea', 'rosss goose', 'caspian tern', 'willet', 'raptor', 'redhead duck', 'dolphin', 'bufflehead', 'pintail', 'avian', 'great grey owl', 'roseate spoonbill', 'fregata magnificens', 'mallard', 'ohio', 'magpie', 'western gull', 'arctic tern', 'gallus gallus', 'common murre', 'razorbill', 'northern gannet', 'lesser snow goose blue-morph', 'waterfowl', 'burrowing owl', 'double-crested cormorant', 'american wigeon', 'northern pintail', 'gannet', 'washington', 'brown pelican', 'ruffed grouse', 'peruvian booby', 'raven', 'backyard chicken', 'fisher', 'dairy cow', 'emperor goose', 'sterna hirundo', 'western grebe', 'muscovy duck', 'layer chicken', 'mink', 'cinnamon teal', 'merganser', 'polar bear', 'sula leucogaster', 'lesser snow goose white-morph', 'common raven', 'ring-necked duck', 'hooded merganser', 'fish crow', 'red-tailed hawk', 'sandwich tern', 'red-necked phalarope', 'eagle', 'iceland gull', 'mallard duck', 'chicken', 'trumpeter swan', 'gull', 'irere', 'lesser scaup', 'parasitic jaeger', 'house mouse', 'snowy plover', 'gadwall', 'dairy cattle', 'osprey', 'alpaca', 'pet food', 'turkey vulture', 'cackling goose', 'wood duck', 'barn owl', 'grackle', 'greater yellowlegs', 'blue-winged teal', 'sharp-shinned hawk', 'great-tailed grackle', 'ring-billed gull', 'goat', 'northern shoveler', 'vulpes vulpes', 'common barn owl', 'coopers hawk', 'american coot', 'peregrine falcon', 'pinniped', 'baikal teal', 'ferruginous hawk', 'black scoter', 'american blue-winged teal', 'poultry', 'rough-legged hawk', 'black swift', 'broiler breeders chicken', 'sparrow', 'teal', 'tiger', 'american green-winged teal', 'texas', 'common goldeneye', 'bovine', 'dovekie', 'ostrich', 'nasua nasua', 'harbor seal', 'ring-necked pheasant', 'buteogallus urubitinga', 'peafowl', 'american robin', 'common tern', 'short-eared owl', 'american-kestrel', 'great black-backed gull', 'south american tern', 'atlantic white-sided dolphin', 'redhead', 'california', 'great blue heron', 'pekin duck', 'swainsons hawk', 'franklins gull', 'pluvialis dominica', 'mountain lion', 'graylag goose', 'peacock', 'colorado', 'american pelican', 'black-legged kittiwake', 'guineafowl', 'northern harrier', 'turkey', 'black-crowned night-heron', 'environment', 'unknown', 'collared plover', 'wild turkey', 'flamingo', 'pigeon', 'black vulture', 'feral cat', 'northern fulmar', 'common loon', 'american white pelican', 'canada goose', 'gadwall duck', 'cattle', 'lesser snow goose', 'western screech owl', 'glaucous-winged gull', 'megascops choliba', 'parrot', 'cormorant', 'golden eagle', 'horned grebe', 'dove', 'south polar skua', 'pelican', 'feline', 'great shearwater', 'panthera leo', 'procellaria aequinoctialis', 'barred owl', 'eastern screech owl', 'herring gull', 'seabird', 'gallus gallus domesticus', 'green winged teal', 'manx shearwater', 'merlin', 'silver pheasant', 'american woodcock', 'northwestern crow', 'black swan']
[]
            wild_avian domestic_avian               cattle        feline  \
0     great_horned_owl       pheasant            dairy_cow           cat
1         common_raven         turkey               cattle  domestic_cat
2        cooper's_hawk        chicken  cattle milk product     feral_cat
3         coopers_hawk          goose          bovine_milk        feline
4              peafowl    guinea_fowl              bovine   domestic-cat
...                ...            ...                  ...           ...
1031      common murre            NaN                  NaN           NaN
1032     ruffed grouse            NaN                  NaN           NaN
1033     emperor goose            NaN                  NaN           NaN
1034      iceland gull            NaN                  NaN           NaN
1035             irere            NaN                  NaN           NaN

       other_mammal       human         other  new
0        deer mouse  washington         mixed  NaN
1       house_mouse      nevada   environment  NaN
2             skunk     wyoming  multispecies  NaN
3     striped_skunk  california       unknown  NaN
4        norway rat    michigan             '  NaN
...             ...         ...           ...  ...
1031            NaN         NaN           NaN  NaN
1032            NaN         NaN           NaN  NaN
1033            NaN         NaN           NaN  NaN
1034            NaN         NaN           NaN  NaN
1035            NaN         NaN           NaN  NaN

[1036 rows x 8 columns]

In [40]:
metadata_genoflu

,Accession,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype,Geo_Location,full_header,sequence,Serotype,Segment,File Name,Partial_Header,Strain,genbank_name
0,PX508201.1,Influenza A virus (A/Washington/2148/2025(H5N5...,Washington,2025-11-10,SRR36016324,2148,A6,USA: Washington,>Influenza A virus |USA: Washington|2148|H5N5|...,GGTTCAATCTGTCAAAATGGAGAACATAGTACTTCTTCTTGCAACA...,NaN,4,NaN,Influenza_A_virus__USA__Washington_2148_H5N5_2...,Influenza_A_virus__USA__Washington_2148_H5N5_2...,A/Washington/2148/2025
1,PX508202.1,Influenza A virus (A/Washington/2148/2025(H5N5...,Washington,2025-11-10,SRR36016324,2148,A6,USA: Washington,>Influenza A virus |USA: Washington|2148|H5N5|...,TAGATATTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTT...,NaN,7,NaN,Influenza_A_virus__USA__Washington_2148_H5N5_2...,Influenza_A_virus__USA__Washington_2148_H5N5_2...,A/Washington/2148/2025
2,PX508203.1,Influenza A virus (A/Washington/2148/2025(H5N5...,Washington,2025-11-10,SRR36016324,2148,A6,USA: Washington,>Influenza A virus |USA: Washington|2148|H5N5|...,GTAGATAATCACTCACTGAGTGACATCAACATCATGGCGTCTCAAG...,NaN,5,NaN,Influenza_A_virus__USA__Washington_2148_H5N5_2...,Influenza_A_virus__USA__Washington_2148_H5N5_2...,A/Washington/2148/2025
3,PX508204.1,Influenza A virus (A/Washington/2148/2025(H5N5...,Washington,2025-11-10,SRR36016324,2148,A6,USA: Washington,>Influenza A virus |USA: Washington|2148|H5N5|...,GTGACAAAAACATAATGGATTTCAACACAGTGTCAAGCTTCCAGGT...,NaN,8,NaN,Influenza_A_virus__USA__Washington_2148_H5N5_2...,Influenza_A_virus__USA__Washington_2148_H5N5_2...,A/Washington/2148/2025
4,PX508205.1,Influenza A virus (A/Washington/2148/2025(H5N5...,Washington,2025-11-10,SRR36016324,2148,A6,USA: Washington,>Influenza A virus |USA: Washington|2148|H5N5|...,TACTGATCCAAAATGGAAGACTTTGTGCGACAATGCTTCAATCCAA...,NaN,3,NaN,Influenza_A_virus__USA__Washington_2148_H5N5_2...,Influenza_A_virus__USA__Washington_2148_H5N5_2...,A/Washington/2148/2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38235,PQ012131.1,Influenza A virus (A/Turkey/Minnesota/24-01468...,Turkey,2024-05-18,SRR29281472,24-014685-001-original,B3.13,USA:MN,>Influenza A virus |USA:MN|24-014685-001-origi...,ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...,H5N1,4,SRR29281472.fa,NaN,NaN,A/Turkey/Minnesota/24-014685-001-original/2024
38236,PQ012132.1,Influenza A virus (A/Turkey/Minnesota/24-01468...,Turkey,2024-05-18,SRR29281472,24-014685-001-original,B3.13,USA:MN,>Influenza A virus |USA:MN|24-014685-001-origi...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...,H5N1,5,SRR29281472.fa,NaN,NaN,A/Turkey/Minnesota/24-014685-001-original/2024
38237,PQ012133.1,Influenza A virus (A/Turkey/Minnesota/24-01468...,Turkey,2024-05-18,SRR29281472,24-014685-001-original,B3.13,USA:MN,>Influenza A virus |USA:MN|24-014685-001-origi...,ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...,H5N1,6,SRR29281472.fa,NaN,NaN,A/Turkey/Minnesota/24-014685-001-original/2024
38238,PQ012134.1,Influenza A virus (A/Turkey/Minnesota/24-01468...,Turkey,2024-05-18,SRR29281472,24-014685-001-original,B3.13,USA:MN,>Influenza A virus |USA:MN|24-014685-001-origi...,ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...,H5N1,7,SRR29281472.fa,NaN,NaN,A/Turkey/Minnesota/24-014685-001-original/2024
38239,PQ012135.1,Influenza A virus (A/Turkey/Minnesota/24-01468...,Turkey,2024-05-18,SRR29281472,24-014685-001-original,B3.13,USA:MN,>Influenza A virus |USA:MN|24-014685-001-origi...,ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...,H5N1,8,SRR29281472.fa,NaN,NaN,A/Turkey/Minnesota/24-014685-001-original/2024

In [42]:
# Re-Labeling

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

# Fix animals
fix_animals_andersen(metadata_genoflu, animals_ref)

# Get the years
metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location"].apply(lambda x: 
                                                                        # If "x" has the state abbreviation (e.g. "MD")
                                                                        states_ref.loc[states_ref["Abbreviation"].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0] 
                                                                        + "-" + 
                                                                        x.split(" ")[-1]
                                                                        if states_ref["Abbreviation"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has the full state name (e.g. "Maryland")
                                                                        else states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0]
                                                                        + "-" + 
                                                                        states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Abbreviation'].iloc[0] 
                                                                        if states_ref["State"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has neither the state abbreviation nor the full state name nor is "USA"
                                                                        else 
                                                                        "USA"
                                                                        )

metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location_Abrv"].apply(lambda x: x.split("-")[0] if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] else x)


# Make new labels
names = ">" + metadata_genoflu["SRA_Accession"].apply(lambda x: x.split(",")[0]) + "|" + metadata_genoflu["genbank_name"] + "|" + metadata_genoflu["Serotype"] + "|" + metadata_genoflu["Geo_Location_Abrv"] + "|" + metadata_genoflu["Collection_Date"] + "|" + metadata_genoflu["Host_Type"] + "|" + metadata_genoflu["Genotype"]

metadata_genoflu["Name"] = names

print(metadata_genoflu["Geo_Location_Abrv"])

0        USA-WA
1        USA-WA
2        USA-WA
3        USA-WA
4        USA-WA
          ...
38235       USA
38236       USA
38237       USA
38238       USA
38239       USA
Name: Geo_Location_Abrv, Length: 100808, dtype: object

## Rename segments and make complete FASTA files

In [50]:
# Set up segments

segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"}
metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].apply(lambda x: int(x)).map(segments)

# Separate into several dataframes based on genotype + segment
segment_genotype_dfs = []
for segment in segments.values():
    m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
    for genotype in list(set(m_g["Genotype"].values)):
        if genotype in genotypes:
            df = m_g[(m_g["Genotype"] == genotype)] 
            df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
            segment_genotype_dfs.append(df)
            pair = genotype + "_" + segment
            print(pair)
        elif "Not assigned" in genotype:
            print(genotype)
            df = m_g[(m_g["Genotype"].str.contains("Not assigned"))] 
            df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
            segment_genotype_dfs.append(df)
            pair = "Unassigned_" + segment
            print(pair)

Not assigned: No Matching Genotypes
Unassigned_PB2
Not assigned: Only 7 segments >98.0% match found of total 8 segments in input file
Unassigned_PB2
Not assigned: Only 1 segments >98.0% match found of total 8 segments in input file
Unassigned_PB2
Not assigned: Only 4 segments >98.0% match found of total 8 segments in input file
Unassigned_PB2
Not assigned: Only 5 segments >98.0% match found of total 8 segments in input file
Unassigned_PB2
Not assigned: Only 2 segments >98.0% match found of total 8 segments in input file
Unassigned_PB2
D1.1_PB2
D1.3_PB2
B3.13_PB2
Not assigned: Only 0 segments >98.0% match found of total 8 segments in input file
Unassigned_PB2
Not assigned: Only 3 segments >98.0% match found of total 8 segments in input file
Unassigned_PB2
Not assigned: Only 6 segments >98.0% match found of total 8 segments in input file
Unassigned_PB2
Not assigned: No Matching Genotypes
Unassigned_PB1
Not assigned: Only 7 segments >98.0% match found of total 8 segments in input file
Unassigned_PB1
Not assigned: Only 1 segments >98.0% match found of total 8 segments in input file
Unassigned_PB1
Not assigned: Only 4 segments >98.0% match found of total 8 segments in input file
Unassigned_PB1
Not assigned: Only 5 segments >98.0% match found of total 8 segments in input file
Unassigned_PB1
Not assigned: Only 2 segments >98.0% match found of total 8 segments in input file
Unassigned_PB1
D1.1_PB1
D1.3_PB1
B3.13_PB1
Not assigned: Only 0 segments >98.0% match found of total 8 segments in input file
Unassigned_PB1
Not assigned: Only 3 segments >98.0% match found of total 8 segments in input file
Unassigned_PB1
Not assigned: Only 6 segments >98.0% match found of total 8 segments in input file
Unassigned_PB1
Not assigned: No Matching Genotypes

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_16096\3807190993.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_16096\3807190993.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)

Unassigned_PA
Not assigned: Only 7 segments >98.0% match found of total 8 segments in input file
Unassigned_PA
Not assigned: Only 1 segments >98.0% match found of total 8 segments in input file
Unassigned_PA
Not assigned: Only 4 segments >98.0% match found of total 8 segments in input file
Unassigned_PA
Not assigned: Only 5 segments >98.0% match found of total 8 segments in input file
Unassigned_PA
Not assigned: Only 2 segments >98.0% match found of total 8 segments in input file
Unassigned_PA
D1.1_PA
D1.3_PA
B3.13_PA
Not assigned: Only 0 segments >98.0% match found of total 8 segments in input file
Unassigned_PA
Not assigned: Only 3 segments >98.0% match found of total 8 segments in input file
Unassigned_PA
Not assigned: Only 6 segments >98.0% match found of total 8 segments in input file
Unassigned_PA
Not assigned: No Matching Genotypes
Unassigned_HA
Not assigned: Only 7 segments >98.0% match found of total 8 segments in input file
Unassigned_HA
Not assigned: Only 1 segments >98.0% match found of total 8 segments in input file
Unassigned_HA
Not assigned: Only 4 segments >98.0% match found of total 8 segments in input file
Unassigned_HA
Not assigned: Only 5 segments >98.0% match found of total 8 segments in input file
Unassigned_HA
Not assigned: Only 2 segments >98.0% match found of total 8 segments in input file
Unassigned_HA
D1.1_HA
D1.3_HA
B3.13_HA
Not assigned: Only 0 segments >98.0% match found of total 8 segments in input file
Unassigned_HA
Not assigned: Only 3 segments >98.0% match found of total 8 segments in input file
Unassigned_HA
Not assigned: Only 6 segments >98.0% match found of total 8 segments in input file
Unassigned_HA
Not assigned: No Matching Genotypes
Unassigned_NP
Not assigned: Only 7 segments >98.0% match found of total 8 segments in input file
Unassigned_NP
Not assigned: Only 1 segments >98.0% match found of total 8 segments in input file
Unassigned_NP
Not assigned: Only 4 segments >98.0% match found of total 8 segments in input file
Unassigned_NP
Not assigned: Only 5 segments >98.0% match found of total 8 segments in input file
Unassigned_NP
Not assigned: Only 2 segments >98.0% match found of total 8 segments in input file
Unassigned_NP
D1.1_NP
D1.3_NP
B3.13_NP
Not assigned: Only 0 segments >98.0% match found of total 8 segments in input file
Unassigned_NP
Not assigned: Only 3 segments >98.0% match found of total 8 segments in input file
Unassigned_NP
Not assigned: Only 6 segments >98.0% match found of total 8 segments in input file
Unassigned_NP
Not assigned: No Matching Genotypes
Unassigned_NA
Not assigned: Only 7 segments >98.0% match found of total 8 segments in input file
Unassigned_NA
Not assigned: Only 1 segments >98.0% match found of total 8 segments in input file
Unassigned_NA
Not assigned: Only 4 segments >98.0% match found of total 8 segments in input file
Unassigned_NA
Not assigned: Only 5 segments >98.0% match found of total 8 segments in input file
Unassigned_NA
Not assigned: Only 2 segments >98.0% match found of total 8 segments in input file
Unassigned_NA
D1.1_NA
D1.3_NA
B3.13_NA
Not assigned: Only 0 segments >98.0% match found of total 8 segments in input file
Unassigned_NA
Not assigned: Only 3 segments >98.0% match found of total 8 segments in input file
Unassigned_NA
Not assigned: Only 6 segments >98.0% match found of total 8 segments in input file
Unassigned_NA
Not assigned: No Matching Genotypes
Unassigned_MP
Not assigned: Only 7 segments >98.0% match found of total 8 segments in input file
Unassigned_MP
Not assigned: Only 1 segments >98.0% match found of total 8 segments in input file
Unassigned_MP
Not assigned: Only 4 segments >98.0% match found of total 8 segments in input file
Unassigned_MP
Not assigned: Only 5 segments >98.0% match found of total 8 segments in input file
Unassigned_MP
Not assigned: Only 2 segments >98.0% match found of total 8 segments in input file
Unassigned_MP
D1.1_MP
D1.3_MP
B3.13_MP
Not assigned: Only 0 segments >98.0% match found of total 8 segments in input file
Unassigned_MP
Not assigned: Only 3 segments >98.0% match found of total 8 segments in input file
Unassigned_MP
Not assigned: Only 6 segments >98.0% match found of total 8 segments in input file
Unassigned_MP
Not assigned: No Matching Genotypes
Unassigned_NS
Not assigned: Only 7 segments >98.0% match found of total 8 segments in input file
Unassigned_NS
Not assigned: Only 1 segments >98.0% match found of total 8 segments in input file
Unassigned_NS
Not assigned: Only 4 segments >98.0% match found of total 8 segments in input file
Unassigned_NS
Not assigned: Only 5 segments >98.0% match found of total 8 segments in input file
Unassigned_NS
Not assigned: Only 2 segments >98.0% match found of total 8 segments in input file
Unassigned_NS
D1.1_NS
D1.3_NS
B3.13_NS
Not assigned: Only 0 segments >98.0% match found of total 8 segments in input file
Unassigned_NS
Not assigned: Only 3 segments >98.0% match found of total 8 segments in input file
Unassigned_NS
Not assigned: Only 6 segments >98.0% match found of total 8 segments in input file
Unassigned_NS

In [51]:
# print(metadata_genoflu[metadata_genoflu["Genotype"] == "B3.2"])

In [53]:
# Create FASTA files

os.chdir(complete_files)

# names = []

for df in segment_genotype_dfs:
    print(df)
    df = df.reset_index()
    if len(df["Genotype"].values[0]) > 0:
        # print(df)
        if "Not assigned" not in df["Genotype"].values[0]:
            file_name = df["Genotype"].values[0] + "_" + df["Segment_Name"].values[0] + "_" + date_range + ".fasta"
            output_file = open(complete_files + file_name, "w")

            for index, row in df.iterrows():
                name = df.loc[index, "Name"]
                name = name.replace(" ", "_")
                # names.append(name)
                sequence = df.loc[index, "sequence"]
                # First is header, second is sequence
                output_file.write(name + "\n")
                output_file.write(sequence + "\n")
        else:
            file_name = "Unassigned_" + df["Segment_Name"].values[0] + "_" + date_range + ".fasta"
            output_file = open(complete_files + file_name, "w")

            for index, row in df.iterrows():
                name = df.loc[index, "Name"]
                name = name.replace(" ", "_")
                # names.append(name)
                sequence = df.loc[index, "sequence"]
                # First is header, second is sequence
                output_file.write(name + "\n")
                output_file.write(sequence + "\n")
    output_file.close()

        Accession                                      GenBank_Title  \
8      PX499386.1  Influenza A virus (A/Aves/Queretaro/CPA-19313-...
856    PV949116.1  Influenza A virus (A/Duck/NY/24-035330-001-ori...
864    PV949132.1  Influenza A virus (A/Duck/PA/24-034866-001-ori...
872    PV949140.1  Influenza A virus (A/Duck/PA/24-035135-002-ori...
880    PV949148.1  Influenza A virus (A/Duck/PA/24-035135-004-ori...
...           ...                                                ...
33824  PQ379372.1  Influenza A virus (A/cattle/MI/24-019382-007-o...
34736  PQ197155.1  Influenza A virus (A/Turkey/MN/24-019077-001-o...
35768  PQ109564.1  Influenza A virus (A/cattle/ID/24-016688-001-o...
35792  PQ109604.1  Influenza A virus (A/cattle/SD/24-015059-001-o...
35944  PQ051159.1  Influenza A virus (A/House Sparrow/NM/24-01478...

                Host Collection_Date SRA_Accession  \
8               aves      2022-09-26   SRR36016324
856             duck      2024-11-25   SRR34270367
864             duck      2024-11-19   SRR34270372
872             duck      2024-11-22   SRR34270370
880             duck      2024-11-22   SRR34270368
...              ...             ...           ...
33824         cattle      2024-07-03   SRR29953275
34736         turkey      2024-06-26   SRR29851700
35768         cattle      2024-06-06   SRR29543300
35792         cattle      2024-05-21   SRR29281435
35944  house sparrow      2024-05-12   SRR29377775

                              Isolate  \
8                        CPA-19313-22
856            24-035330-001-original
864    24-034866-001-original-repeat2
872            24-035135-002-original
880            24-035135-004-original
...                               ...
33824  24-019382-007-original-repeat2
34736          24-019077-001-original
35768          24-016688-001-original
35792          24-015059-001-original
35944          24-014786-002-original

                                                Genotype       Geo_Location  \
8      Not assigned: Only 0 segments >98.0% match fou...  Mexico: Queretaro
856    Not assigned: Only 6 segments >98.0% match fou...            USA: NY
864    Not assigned: Only 6 segments >98.0% match fou...            USA: PA
872    Not assigned: Only 6 segments >98.0% match fou...            USA: PA
880    Not assigned: Only 6 segments >98.0% match fou...            USA: PA
...                                                  ...                ...
33824  Not assigned: Only 7 segments >98.0% match fou...            USA: MI
34736  Not assigned: Only 7 segments >98.0% match fou...            USA: MN
35768  Not assigned: Only 7 segments >98.0% match fou...            USA: ID
35792  Not assigned: Only 7 segments >98.0% match fou...            USA: SD
35944  Not assigned: Only 6 segments >98.0% match fou...            USA: NM

                                             full_header  \
8      >Influenza A virus |Mexico: Queretaro|CPA-1931...
856    >Influenza A virus |USA: NY|24-035330-001-orig...
864    >Influenza A virus |USA: PA|24-034866-001-orig...
872    >Influenza A virus |USA: PA|24-035135-002-orig...
880    >Influenza A virus |USA: PA|24-035135-004-orig...
...                                                  ...
33824  >Influenza A virus |USA: MI|24-019382-007-orig...
34736  >Influenza A virus |USA: MN|24-019077-001-orig...
35768  >Influenza A virus |USA: ID|24-016688-001-orig...
35792  >Influenza A virus |USA: SD|24-015059-001-orig...
35944  >Influenza A virus |USA: NM|24-014786-002-orig...

                                                sequence  ... Segment  \
8      AAAAGCAGGTCAAATATATTCAGTATGGAGAGAATAAAAGAATTAA...  ...       1
856    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...       1
864    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...       1
872    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...       1
880    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...       1
...                                                  ...  ...     ...
33824  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1
34736  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1
35768  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1
35792  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1
35944  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1

            File Name                                     Partial_Header  \
8                      Influenza_A_virus__Mexico__Queretaro_CPA_19313...
856                    Influenza_A_virus__USA__NY_24_035330_001_origi...
864                    Influenza_A_virus__USA__PA_24_034866_001_origi...
872                    Influenza_A_virus__USA__PA_24_035135_002_origi...
880                    Influenza_A_virus__USA__PA_24_035135_004_origi...
...               ...                                                ...
33824  SRR29953275.fa
34736  SRR29851700.fa
35768  SRR29543300.fa
35792  SRR29281435.fa
35944  SRR29377775.fa

                                                  Strain  \
8      Influenza_A_virus__Mexico__Queretaro_CPA_19313...
856    Influenza_A_virus__USA__NY_24_035330_001_origi...
864    Influenza_A_virus__USA__PA_24_034866_001_origi...
872    Influenza_A_virus__USA__PA_24_035135_002_origi...
880    Influenza_A_virus__USA__PA_24_035135_004_origi...
...                                                  ...
33824
34736
35768
35792
35944

                                          genbank_name       Host_Type Years  \
8                   A/Aves/Queretaro/CPA-19313-22/2022      wild_avian  2022
856              A/Duck/NY/24-035330-001-original/2024  domestic_avian  2024
864      A/Duck/PA/24-034866-001-original-repeat2/2024  domestic_avian  2024
872              A/Duck/PA/24-035135-002-original/2024  domestic_avian  2024
880              A/Duck/PA/24-035135-004-original/2024  domestic_avian  2024
...                                                ...             ...   ...
33824  A/cattle/MI/24-019382-007-original-repeat2/2024          cattle  2024
34736          A/Turkey/MN/24-019077-001-original/2024  domestic_avian  2024
35768          A/cattle/ID/24-016688-001-original/2024          cattle  2024
35792          A/cattle/SD/24-015059-001-original/2024          cattle  2024
35944   A/House Sparrow/NM/24-014786-002-original/2024      wild_avian  2024

      Geo_Location_Abrv                                               Name  \
8                USA-NM  >SRR36016324|A/Aves/Queretaro/CPA-19313-22/202...
856              USA-NY  >SRR34270367|A/Duck/NY/24-035330-001-original/...
864              USA-PA  >SRR34270372|A/Duck/PA/24-034866-001-original-...
872              USA-PA  >SRR34270370|A/Duck/PA/24-035135-002-original/...
880              USA-PA  >SRR34270368|A/Duck/PA/24-035135-004-original/...
...                 ...                                                ...
33824            USA-MI  >SRR29953275|A/cattle/MI/24-019382-007-origina...
34736            USA-MN  >SRR29851700|A/Turkey/MN/24-019077-001-origina...
35768            USA-ID  >SRR29543300|A/cattle/ID/24-016688-001-origina...
35792            USA-SD  >SRR29281435|A/cattle/SD/24-015059-001-origina...
35944            USA-NM  >SRR29377775|A/House Sparrow/NM/24-014786-002-...

      Segment_Name
8              PB2
856            PB2
864            PB2
872            PB2
880            PB2
...            ...
33824          PB2
34736          PB2
35768          PB2
35792          PB2
35944          PB2

[116 rows x 21 columns]
        Accession                                      GenBank_Title  \
8      PX499386.1  Influenza A virus (A/Aves/Queretaro/CPA-19313-...
856    PV949116.1  Influenza A virus (A/Duck/NY/24-035330-001-ori...
864    PV949132.1  Influenza A virus (A/Duck/PA/24-034866-001-ori...
872    PV949140.1  Influenza A virus (A/Duck/PA/24-035135-002-ori...
880    PV949148.1  Influenza A virus (A/Duck/PA/24-035135-004-ori...
...           ...                                                ...
33824  PQ379372.1  Influenza A virus (A/cattle/MI/24-019382-007-o...
34736  PQ197155.1  Influenza A virus (A/Turkey/MN/24-019077-001-o...
35768  PQ109564.1  Influenza A virus (A/cattle/ID/24-016688-001-o...
35792  PQ109604.1  Influenza A virus (A/cattle/SD/24-015059-001-o...
35944  PQ051159.1  Influenza A virus (A/House Sparrow/NM/24-01478...

                Host Collection_Date SRA_Accession  \
8               aves      2022-09-26   SRR36016324
856             duck      2024-11-25   SRR34270367
864             duck      2024-11-19   SRR34270372
872             duck      2024-11-22   SRR34270370
880             duck      2024-11-22   SRR34270368
...              ...             ...           ...
33824         cattle      2024-07-03   SRR29953275
34736         turkey      2024-06-26   SRR29851700
35768         cattle      2024-06-06   SRR29543300
35792         cattle      2024-05-21   SRR29281435
35944  house sparrow      2024-05-12   SRR29377775

                              Isolate  \
8                        CPA-19313-22
856            24-035330-001-original
864    24-034866-001-original-repeat2
872            24-035135-002-original
880            24-035135-004-original
...                               ...
33824  24-019382-007-original-repeat2
34736          24-019077-001-original
35768          24-016688-001-original
35792          24-015059-001-original
35944          24-014786-002-original

                                                Genotype       Geo_Location  \
8      Not assigned: Only 0 segments >98.0% match fou...  Mexico: Queretaro
856    Not assigned: Only 6 segments >98.0% match fou...            USA: NY
864    Not assigned: Only 6 segments >98.0% match fou...            USA: PA
872    Not assigned: Only 6 segments >98.0% match fou...            USA: PA
880    Not assigned: Only 6 segments >98.0% match fou...            USA: PA
...                                                  ...                ...
33824  Not assigned: Only 7 segments >98.0% match fou...            USA: MI
34736  Not assigned: Only 7 segments >98.0% match fou...            USA: MN
35768  Not assigned: Only 7 segments >98.0% match fou...            USA: ID
35792  Not assigned: Only 7 segments >98.0% match fou...            USA: SD
35944  Not assigned: Only 6 segments >98.0% match fou...            USA: NM

                                             full_header  \
8      >Influenza A virus |Mexico: Queretaro|CPA-1931...
856    >Influenza A virus |USA: NY|24-035330-001-orig...
864    >Influenza A virus |USA: PA|24-034866-001-orig...
872    >Influenza A virus |USA: PA|24-035135-002-orig...
880    >Influenza A virus |USA: PA|24-035135-004-orig...
...                                                  ...
33824  >Influenza A virus |USA: MI|24-019382-007-orig...
34736  >Influenza A virus |USA: MN|24-019077-001-orig...
35768  >Influenza A virus |USA: ID|24-016688-001-orig...
35792  >Influenza A virus |USA: SD|24-015059-001-orig...
35944  >Influenza A virus |USA: NM|24-014786-002-orig...

                                                sequence  ... Segment  \
8      AAAAGCAGGTCAAATATATTCAGTATGGAGAGAATAAAAGAATTAA...  ...       1
856    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...       1
864    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...       1
872    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...       1
880    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...       1
...                                                  ...  ...     ...
33824  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1
34736  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1
35768  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1
35792  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1
35944  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1

            File Name                                     Partial_Header  \
8                      Influenza_A_virus__Mexico__Queretaro_CPA_19313...
856                    Influenza_A_virus__USA__NY_24_035330_001_origi...
864                    Influenza_A_virus__USA__PA_24_034866_001_origi...
872                    Influenza_A_virus__USA__PA_24_035135_002_origi...
880                    Influenza_A_virus__USA__PA_24_035135_004_origi...
...               ...                                                ...
33824  SRR29953275.fa
34736  SRR29851700.fa
35768  SRR29543300.fa
35792  SRR29281435.fa
35944  SRR29377775.fa

                                                  Strain  \
8      Influenza_A_virus__Mexico__Queretaro_CPA_19313...
856    Influenza_A_virus__USA__NY_24_035330_001_origi...
864    Influenza_A_virus__USA__PA_24_034866_001_origi...
872    Influenza_A_virus__USA__PA_24_035135_002_origi...
880    Influenza_A_virus__USA__PA_24_035135_004_origi...
...                                                  ...
33824
34736
35768
35792
35944

                                          genbank_name       Host_Type Years  \
8                   A/Aves/Queretaro/CPA-19313-22/2022      wild_avian  2022
856              A/Duck/NY/24-035330-001-original/2024  domestic_avian  2024
864      A/Duck/PA/24-034866-001-original-repeat2/2024  domestic_avian  2024
872              A/Duck/PA/24-035135-002-original/2024  domestic_avian  2024
880              A/Duck/PA/24-035135-004-original/2024  domestic_avian  2024
...                                                ...             ...   ...
33824  A/cattle/MI/24-019382-007-original-repeat2/2024          cattle  2024
34736          A/Turkey/MN/24-019077-001-original/2024  domestic_avian  2024
35768          A/cattle/ID/24-016688-001-original/2024          cattle  2024
35792          A/cattle/SD/24-015059-001-original/2024          cattle  2024
35944   A/House Sparrow/NM/24-014786-002-original/2024      wild_avian  2024

      Geo_Location_Abrv                                               Name  \
8                USA-NM  >SRR36016324|A/Aves/Queretaro/CPA-19313-22/202...
856              USA-NY  >SRR34270367|A/Duck/NY/24-035330-001-original/...
864              USA-PA  >SRR34270372|A/Duck/PA/24-034866-001-original-...
872              USA-PA  >SRR34270370|A/Duck/PA/24-035135-002-original/...
880              USA-PA  >SRR34270368|A/Duck/PA/24-035135-004-original/...
...                 ...                                                ...
33824            USA-MI  >SRR29953275|A/cattle/MI/24-019382-007-origina...
34736            USA-MN  >SRR29851700|A/Turkey/MN/24-019077-001-origina...
35768            USA-ID  >SRR29543300|A/cattle/ID/24-016688-001-origina...
35792            USA-SD  >SRR29281435|A/cattle/SD/24-015059-001-origina...
35944            USA-NM  >SRR29377775|A/House Sparrow/NM/24-014786-002-...

      Segment_Name
8              PB2
856            PB2
864            PB2
872            PB2
880            PB2
...            ...
33824          PB2
34736          PB2
35768          PB2
35792          PB2
35944          PB2

[116 rows x 21 columns]
        Accession                                      GenBank_Title  \
8      PX499386.1  Influenza A virus (A/Aves/Queretaro/CPA-19313-...
856    PV949116.1  Influenza A virus (A/Duck/NY/24-035330-001-ori...
864    PV949132.1  Influenza A virus (A/Duck/PA/24-034866-001-ori...
872    PV949140.1  Influenza A virus (A/Duck/PA/24-035135-002-ori...
880    PV949148.1  Influenza A virus (A/Duck/PA/24-035135-004-ori...
...           ...                                                ...
33824  PQ379372.1  Influenza A virus (A/cattle/MI/24-019382-007-o...
34736  PQ197155.1  Influenza A virus (A/Turkey/MN/24-019077-001-o...
35768  PQ109564.1  Influenza A virus (A/cattle/ID/24-016688-001-o...
35792  PQ109604.1  Influenza A virus (A/cattle/SD/24-015059-001-o...
35944  PQ051159.1  Influenza A virus (A/House Sparrow/NM/24-01478...

                Host Collection_Date SRA_Accession  \
8               aves      2022-09-26   SRR36016324
856             duck      2024-11-25   SRR34270367
864             duck      2024-11-19   SRR34270372
872             duck      2024-11-22   SRR34270370
880             duck      2024-11-22   SRR34270368
...              ...             ...           ...
33824         cattle      2024-07-03   SRR29953275
34736         turkey      2024-06-26   SRR29851700
35768         cattle      2024-06-06   SRR29543300
35792         cattle      2024-05-21   SRR29281435
35944  house sparrow      2024-05-12   SRR29377775

                              Isolate  \
8                        CPA-19313-22
856            24-035330-001-original
864    24-034866-001-original-repeat2
872            24-035135-002-original
880            24-035135-004-original
...                               ...
33824  24-019382-007-original-repeat2
34736          24-019077-001-original
35768          24-016688-001-original
35792          24-015059-001-original
35944          24-014786-002-original

                                                Genotype       Geo_Location  \
8      Not assigned: Only 0 segments >98.0% match fou...  Mexico: Queretaro
856    Not assigned: Only 6 segments >98.0% match fou...            USA: NY
864    Not assigned: Only 6 segments >98.0% match fou...            USA: PA
872    Not assigned: Only 6 segments >98.0% match fou...            USA: PA
880    Not assigned: Only 6 segments >98.0% match fou...            USA: PA
...                                                  ...                ...
33824  Not assigned: Only 7 segments >98.0% match fou...            USA: MI
34736  Not assigned: Only 7 segments >98.0% match fou...            USA: MN
35768  Not assigned: Only 7 segments >98.0% match fou...            USA: ID
35792  Not assigned: Only 7 segments >98.0% match fou...            USA: SD
35944  Not assigned: Only 6 segments >98.0% match fou...            USA: NM

                                             full_header  \
8      >Influenza A virus |Mexico: Queretaro|CPA-1931...
856    >Influenza A virus |USA: NY|24-035330-001-orig...
864    >Influenza A virus |USA: PA|24-034866-001-orig...
872    >Influenza A virus |USA: PA|24-035135-002-orig...
880    >Influenza A virus |USA: PA|24-035135-004-orig...
...                                                  ...
33824  >Influenza A virus |USA: MI|24-019382-007-orig...
34736  >Influenza A virus |USA: MN|24-019077-001-orig...
35768  >Influenza A virus |USA: ID|24-016688-001-orig...
35792  >Influenza A virus |USA: SD|24-015059-001-orig...
35944  >Influenza A virus |USA: NM|24-014786-002-orig...

                                                sequence  ... Segment  \
8      AAAAGCAGGTCAAATATATTCAGTATGGAGAGAATAAAAGAATTAA...  ...       1
856    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...       1
864    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...       1
872    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...       1
880    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...       1
...                                                  ...  ...     ...
33824  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1
34736  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1
35768  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1
35792  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1
35944  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...       1

            File Name                                     Partial_Header  \
8                      Influenza_A_virus__Mexico__Queretaro_CPA_19313...
856                    Influenza_A_virus__USA__NY_24_035330_001_origi...
864                    Influenza_A_virus__USA__PA_24_034866_001_origi...
872                    Influenza_A_virus__USA__PA_24_035135_002_origi...
880                    Influenza_A_virus__USA__PA_24_035135_004_origi...
...               ...                                                ...
33824  SRR29953275.fa
34736  SRR29851700.fa
35768  SRR29543300.fa
35792  SRR29281435.fa
35944  SRR29377775.fa


In [ ]:
# # Concatenate with new Andersen sequences

# os.chdir(combined_files)

# # andersen = home + "Andersen/complete/" + date_range + "/"

# # Andersen files
# filenames_andersen = []
# for genotype in genotypes:
#     # print(gisaid_andersen + genotype.replace(".", "_") + "/")
#     # for dirpath, dirs, files in os.walk(gisaid_andersen + genotype.replace(".", "_") + "/" + date_range + "_" + genotype.replace(".", "_") + "/"):
#     for dirpath, dirs, files in os.walk(andersen): # Find the fasta file
#         for file in files:
#             file_name = os.path.join(dirpath, file) # Get file name
#             filenames_andersen.append(file_name)
#         break 

# # NCBI Virus files
# filenames_ncbi = []
# for dirpath, dirs, files in os.walk(complete_files): # Find the fasta file
#     for file in files:
#         file_name = os.path.join(dirpath, file) # Get file name
#         filenames_ncbi.append(file_name)
#     break 

# print(filenames_ncbi)

# common_genotypes = set()
# # Concatenate the two -- should not have any overlap due to dates and deduplication 
# for a_file in filenames_andersen:
#     partial_filename_a = a_file.split("_")[-4].split("/")[-1] + "_" + a_file.split("_")[-3]
#     for nv_file in filenames_ncbi:
#         partial_filename_nv = nv_file.split("_")[-3].split("/")[-1] + "_" + nv_file.split("_")[-2]
#         if partial_filename_a == partial_filename_nv:
#             common_genotypes.add(partial_filename_a)
#             filenames = [a_file, nv_file]
#             with open(combined_files + partial_filename_a + "_combined_" + date_range + ".fasta", 'w') as outfile:
#                 for fname in filenames:
#                     with open(fname) as infile:
#                         for line in infile:
#                             outfile.write(line)
#                         infile.close()
#                 outfile.close()

# print(common_genotypes)

# for a_file in filenames_andersen:
#     partial_filename_a = a_file.split("_")[-4].split("/")[-1] + "_" + a_file.split("_")[-3]
#     # If genotype not found in NCBI Virus, include it as well
#     if partial_filename_a not in common_genotypes:
#         with open(combined_files + partial_filename_a + "_combined_" + date_range + ".fasta", 'w') as outfile2:
#             with open(a_file) as infile2:
#                 for line in infile2:
#                     outfile2.write(line)
#                 infile2.close()
#             outfile2.close()