# Cleaning Downloaded Data from avian-flu

Author: Alexander Maksiaev

Purpose: Clean downloaded data from avian-flu, rename sequences according to convention, de-duplicate from GISAID

In [27]:
# Housekeeping

import os
import glob 
import pandas as pd
import xml.etree.ElementTree as ET
import requests
import time
import numpy as np
import dateutil 
from datetime import datetime
from collections import defaultdict 
import importlib
import utils  
importlib.reload(utils)
from utils import * 


# Dates
start_date = "04-14-2025"
end_date = "06-13-2025"
date_range = start_date + "--" + end_date
update_date = "06-16-2025"

# Make sure you have the correct paths

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/"
# downloads = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
originals = downloads + "Andersen/"
saved = originals + "saved/"
temp_files = originals + "temp/"
complete_files = downloads + "complete/"

os.chdir(downloads)

ModuleNotFoundError: spec not found for the module 'utils'

## Read Metadata

In [28]:
# Read metadata

os.chdir(saved)
metadata_normalized = pd.read_csv("metadata_normalized.tsv", delimiter="\t") # Collection dates

metadata_folder = originals + "avian-influenza/metadata/"
os.chdir(metadata_folder)

metadata = pd.read_csv("SraRunTable_automated.csv")

print(len(metadata)) # 7397 rows

metadata = metadata.merge(metadata_normalized, how="outer")
print(metadata.columns)

metadata["name_state"] = metadata["geo_loc_name"].apply(lambda x: x.split("/")[1] if len(x.split("/")) > 1 else x.split("/")[0])

# Find only >= last date using Release Date from metadata 
metadata["ReleaseDate"] = metadata["ReleaseDate"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
metadata = metadata[metadata["ReleaseDate"] >= dateutil.parser.parse(start_date).strftime("%Y-%m-%d")]
# Find only <= update date using Release Date from metadata
metadata = metadata[metadata["ReleaseDate"] <= dateutil.parser.parse(end_date).strftime("%Y-%m-%d")]

print(len(metadata)) # 6053 rows between 1/1/2024 and 4/14/2025
display(metadata)

9697
Index(['Run', 'Assay Type', 'AvgSpotLen', 'Bases', 'BioProject', 'BioSample',
       'BioSampleModel', 'Bytes', 'Center Name', 'Collection_Date', 'Consent',
       'DATASTORE filetype', 'DATASTORE provider', 'DATASTORE region',
       'Experiment', 'geo_loc_name_country', 'geo_loc_name_country_continent',
       'geo_loc_name', 'Host', 'Instrument', 'isolate', 'Library Name',
       'LibraryLayout', 'LibrarySelection', 'LibrarySource', 'Organism',
       'Platform', 'ReleaseDate', 'create_date', 'version', 'Sample Name',
       'SRA Study', 'serotype', 'isolation_source', 'BioSample Accession',
       'is_retracted', 'retraction_detection_date_utc'],
      dtype='object')
2274

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,create_date,version,Sample Name,SRA Study,serotype,isolation_source,BioSample Accession,is_retracted,retraction_detection_date_utc,name_state
16776,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,2025-04-14 15:21:54,1,25-006243-005,SRP503016,NaN,"MILK, BULK TANK",SRS24711993,False,NaN,USA
16777,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,2025-04-14 15:21:54,1,25-006243-005,SRP503016,NaN,",",SRS24711993,False,NaN,
16778,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,2025-04-14 15:20:51,1,25-006243-002,SRP503016,NaN,"MILK, BULK TANK",SRS24711992,False,NaN,USA
16779,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,2025-04-14 15:20:51,1,25-006243-002,SRP503016,NaN,",",SRS24711992,False,NaN,
16780,SRR33124596,WGS,262.12,61927215,PRJNA1102327,SAMN47941262,Viral,21760157,USDA-NVSL,2025,...,2025-04-14 15:20:49,1,25-006243-001,SRP503016,NaN,"MILK, BULK TANK",SRS24711991,False,NaN,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19045,SRR33830446,WGS,148.77,95232771,PRJNA1102327,SAMN48895426,Viral,37952018,USDA-NVSL,2025,...,2025-06-04 14:24:56,1,25-015677-004,SRP503016,NaN,"MILK, BULK TANK",SRS25266464,False,NaN,USA
19046,SRR33830447,WGS,148.43,106145246,PRJNA1102327,SAMN48895425,Viral,42182759,USDA-NVSL,2025,...,2025-06-04 14:25:01,1,25-015677-003,SRP503016,NaN,"MILK, BULK TANK",SRS25266463,False,NaN,USA
19047,SRR33830448,WGS,148.30,110812426,PRJNA1102327,SAMN48895424,Viral,43738503,USDA-NVSL,2025,...,2025-06-04 14:24:55,1,25-015677-002,SRP503016,NaN,"MILK, BULK TANK",SRS25266462,False,NaN,USA
19048,SRR33830449,WGS,131.52,67358891,PRJNA1102327,SAMN48895415,Viral,26336550,USDA-NVSL,2024,...,2025-06-04 14:24:53,1,24-036379-001-tile,SRP503016,NaN,"MILK, BULK TANK",SRS25266461,False,NaN,USA
19049,SRR33830450,WGS,131.13,69602732,PRJNA1102327,SAMN48895414,Viral,27556171,USDA-NVSL,2024,...,2025-06-04 14:24:53,1,24-034788-001-tile,SRP503016,NaN,"MILK, BULK TANK",SRS25266460,False,NaN,USA

In [29]:
# Get list of genotypes

# os.chdir(home)

# genotypes_df = pd.read_excel("genotype_key.xlsx")

# genotypes = list(genotypes_df["Genotype"])

# print(genotypes)

genotypes = ["B3.2"] #, "B3.2", "B3.6", "B3.7", "B3.5", "A3"]

### Naming convention ###
>A/[host]/[geo_loc_name]/[isolate]/[year]|[serotype: H5N1]|[collection_date]|[host_type]|[genotype]

host_type is from manual animal reference

In metadata, we have: host, geo_loc_name, isolate, year

We need: geo_loc_name, collection_date, host_type, genotype

host = Host

geo_loc_name (primary) = geo_loc_name

geo_loc_name (secondary) = genbank_mapping.tsv > genbank_name

isolate = isolate

collection date (primary) = Collection_Date

collection date (secondary) = https://www.ncbi.nlm.nih.gov/genbank/ > BioSample (input: BioSample) > Nucleotide > [first result] > collection_date

serotype = serotype

host type = [from ref] 

genotype = [from genoflu] -- use genoflu_results.tsv

## Get genotype, specific geolocation

In [30]:
# Get genotype from genoflu_results.tsv

os.chdir(metadata_folder)

genoflu_results = pd.read_csv("genoflu_results.tsv", delimiter="\t")

genoflu_results["Run"] = genoflu_results["sample"]

metadata = metadata.merge(genoflu_results, on="Run", how="inner")
print(metadata)
# metadata = metadata[~metadata["Genotype"].str.contains('Not assigned')] # Do not include non-assigned genotypes
metadata = metadata[metadata["Genotype"].isin(genotypes)]

# Get only the genotypes we want: B3.13 and D1.1

# b313_and_d11_only = genoflu_results[(genoflu_results["Genotype"] == "B3.13") | (genoflu_results["Genotype"] == "D1.1")]
# b313_and_d11_only = b313_and_d11_only.rename(columns={"sample": "Run"})
# b313_and_d11_only = b313_and_d11_only.drop_duplicates(subset="Run", keep="last")

# metadata = metadata.merge(b313_and_d11_only, on=["Run", "Genotype"], how="inner")

print(len(metadata)) 

display(metadata)

              Run Assay Type  AvgSpotLen      Bases    BioProject  \
0     SRR33124594        WGS      246.43  145473401  PRJNA1102327
1     SRR33124594        WGS      246.43  145473401  PRJNA1102327
2     SRR33124595        WGS      240.38  139928333  PRJNA1102327
3     SRR33124595        WGS      240.38  139928333  PRJNA1102327
4     SRR33124596        WGS      262.12   61927215  PRJNA1102327
...           ...        ...         ...        ...           ...
2269  SRR33830446        WGS      148.77   95232771  PRJNA1102327
2270  SRR33830447        WGS      148.43  106145246  PRJNA1102327
2271  SRR33830448        WGS      148.30  110812426  PRJNA1102327
2272  SRR33830449        WGS      131.52   67358891  PRJNA1102327
2273  SRR33830450        WGS      131.13   69602732  PRJNA1102327

         BioSample BioSampleModel     Bytes Center Name Collection_Date  ...  \
0     SAMN47941264          Viral  50832578   USDA-NVSL            2025  ...
1     SAMN47941264          Viral  50832578   USDA-NVSL            2025  ...
2     SAMN47941263          Viral  48295907   USDA-NVSL            2025  ...
3     SAMN47941263          Viral  48295907   USDA-NVSL            2025  ...
4     SAMN47941262          Viral  21760157   USDA-NVSL            2025  ...
...            ...            ...       ...         ...             ...  ...
2269  SAMN48895426          Viral  37952018   USDA-NVSL            2025  ...
2270  SAMN48895425          Viral  42182759   USDA-NVSL            2025  ...
2271  SAMN48895424          Viral  43738503   USDA-NVSL            2025  ...
2272  SAMN48895415          Viral  26336550   USDA-NVSL            2024  ...
2273  SAMN48895414          Viral  27556171   USDA-NVSL            2024  ...

     name_state       sample                 date       File Name  \
0           USA  SRR33124594  2025-05-09_10-46-09  SRR33124594.fa
1                SRR33124594  2025-05-09_10-46-09  SRR33124594.fa
2           USA  SRR33124595  2025-05-09_10-52-41  SRR33124595.fa
3                SRR33124595  2025-05-09_10-52-41  SRR33124595.fa
4           USA  SRR33124596  2025-05-09_10-50-43  SRR33124596.fa
...         ...          ...                  ...             ...
2269        USA  SRR33830446  2025-06-06_07-56-21  SRR33830446.fa
2270        USA  SRR33830447  2025-06-06_07-56-21  SRR33830447.fa
2271        USA  SRR33830448  2025-06-06_07-56-21  SRR33830448.fa
2272        USA  SRR33830449  2025-06-06_07-56-20  SRR33830449.fa
2273        USA  SRR33830450  2025-06-06_07-56-20  SRR33830450.fa

                                               Genotype  \
0                                                 B3.13
1                                                 B3.13
2                                                 B3.13
3                                                 B3.13
4     Not assigned: Only 7 segments >98.0% match fou...
...                                                 ...
2269  Not assigned: Only 7 segments >98.0% match fou...
2270  Not assigned: Only 7 segments >98.0% match fou...
2271  Not assigned: Only 7 segments >98.0% match fou...
2272                                              B3.13
2273                                              B3.13

                            Genotype List Used, >=98.0%  \
0     NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...
1     NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...
2     HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...
3     HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...
4     HA:ea1, MP:ea1, PB2:am2.2, PB1:am4, NA:ea1, NS...
...                                                 ...
2269  PB1:am4, NA:ea1, NS:am1.1, PA:ea1, MP:ea1, NP:...
2270  PB1:am4, PB2:am2.2, NA:ea1, NS:am1.1, PA:ea1, ...
2271  NA:ea1, MP:ea1, PB2:am2.2, PA:ea1, PB1:am4, NP...
2272  NP:am8, NA:ea1, PB1:am4, HA:ea1, NS:am1.1, MP:...
2273  HA:ea1, NA:ea1, NP:am8, PB2:am2.2, MP:ea1, PB1...

                             Genotype Sample Title List  \
0     am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...
1     am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...
2     ea1:22-003707-003:HA, am8:23-032005-001:NP, am...
3     ea1:22-003707-003:HA, am8:23-032005-001:NP, am...
4     ea1:22-003707-003:HA, ea1:22-003707-003:MP, ea...
...                                                 ...
2269  am4:23-001855-001:PB1, ea1:22-003707-003:NA, e...
2270  am4:23-001855-001:PB1, am2.2:22-010445-001:PB2...
2271  ea1:22-003707-003:HA, ea1:22-003707-003:NA, ea...
2272  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
2273  ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...

                            Genotype Percent Match List  \
0     99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...
1     99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...
2     98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...
3     98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...
4     98.42%, 98.68%, 97.63%, 98.55%, 99.38%, 98.86%...
...                                                 ...
2269  99.34%, 98.79%, 97.95%, 98.33%, 98.70%, 98.88%...
2270  99.34%, 98.38%, 97.95%, 98.86%, 98.45%, 98.79%...
2271  97.95%, 98.86%, 98.88%, 98.38%, 98.79%, 99.34%...
2272  98.93%, 98.86%, 99.47%, 98.43%, 99.17%, 98.95%...
2273  98.92%, 98.71%, 99.00%, 98.55%, 98.74%, 99.47%...

              Genotype Mismatch List Genotype Average Depth of Coverage List
0      7, 20, 16, 12, 28, 13, 28, 33       Ran on FASTA - No Coverage Report
1      7, 20, 16, 12, 28, 13, 28, 33       Ran on FASTA - No Coverage Report
2      28, 20, 7, 33, 14, 16, 12, 28       Ran on FASTA - No Coverage Report
3      28, 20, 7, 33, 14, 16, 12, 28       Ran on FASTA - No Coverage Report
4      27, 13, 51, 33, 14, 16, 8, 18       Ran on FASTA - No Coverage Report
...                              ...                                     ...
2269  15, 17, 35, 14, 28, 11, 17, 37       Ran on FASTA - No Coverage Report
2270  15, 37, 35, 16, 13, 26, 11, 17       Ran on FASTA - No Coverage Report
2271  35, 16, 11, 37, 26, 15, 17, 13       Ran on FASTA - No Coverage Report
2272   16, 16, 12, 12, 7, 10, 31, 24       Ran on FASTA - No Coverage Report
2273   11, 12, 15, 33, 12, 12, 8, 23       Ran on FASTA - No Coverage Report

[2274 rows x 47 columns]
0

Empty DataFrame
Columns: [Run, Assay Type, AvgSpotLen, Bases, BioProject, BioSample, BioSampleModel, Bytes, Center Name, Collection_Date, Consent, DATASTORE filetype, DATASTORE provider, DATASTORE region, Experiment, geo_loc_name_country, geo_loc_name_country_continent, geo_loc_name, Host, Instrument, isolate, Library Name, LibraryLayout, LibrarySelection, LibrarySource, Organism, Platform, ReleaseDate, create_date, version, Sample Name, SRA Study, serotype, isolation_source, BioSample Accession, is_retracted, retraction_detection_date_utc, name_state, sample, date, File Name, Genotype, Genotype List Used, >=98.0%, Genotype Sample Title List, Genotype Percent Match List, Genotype Mismatch List, Genotype Average Depth of Coverage List]
Index: []

[0 rows x 47 columns]

In [5]:
# Get specific geolocation and name_state from genbank_mapping.tsv

genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
genbank_mapping["Run"] = genbank_mapping["sra_run"]
genbank_mapping = genbank_mapping.drop_duplicates(subset="Run", keep="first") # Drop duplicates
genbank_mapping["name_state"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[2]) # Get the name of the state

# print(genbank_mapping)

# metadata_genbank = metadata.merge(genbank_mapping, on=["Run"]) # Only include data that has states

# Get geolocation for second state attribute

os.chdir(home + "references/")
state_ref = pd.read_csv("states_ref.csv")
metadata["Geo_Location"] = metadata["name_state"].apply(lambda x: state_ref.loc[state_ref["Abbreviation"] == x, 'Country'].iloc[0] + "-" + x if x in state_ref["Abbreviation"].values else state_ref.loc[state_ref["State"] == x, 'Country'].iloc[0] + "-" + state_ref.loc[state_ref["State"] == x, 'Abbreviation'].iloc[0] if x in state_ref["State"].values else x)


print(metadata["name_state"])
print(len(metadata))
display(metadata) # Maybe there is no state information since 3/18/2025?

0       USA
1
2       USA
3
6       USA
       ...
2266    USA
2267    USA
2268    USA
2272    USA
2273    USA
Name: name_state, Length: 1975, dtype: object
1975

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,sample,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,Geo_Location
0,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,SRR33124594,2025-05-09_10-46-09,SRR33124594.fa,B3.13,"NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...","am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...","99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...","7, 20, 16, 12, 28, 13, 28, 33",Ran on FASTA - No Coverage Report,USA
1,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,SRR33124594,2025-05-09_10-46-09,SRR33124594.fa,B3.13,"NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...","am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...","99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...","7, 20, 16, 12, 28, 13, 28, 33",Ran on FASTA - No Coverage Report,
2,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,SRR33124595,2025-05-09_10-52-41,SRR33124595.fa,B3.13,"HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...","ea1:22-003707-003:HA, am8:23-032005-001:NP, am...","98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...","28, 20, 7, 33, 14, 16, 12, 28",Ran on FASTA - No Coverage Report,USA
3,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,SRR33124595,2025-05-09_10-52-41,SRR33124595.fa,B3.13,"HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...","ea1:22-003707-003:HA, am8:23-032005-001:NP, am...","98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...","28, 20, 7, 33, 14, 16, 12, 28",Ran on FASTA - No Coverage Report,
6,SRR33124597,WGS,264.06,73438935,PRJNA1102327,SAMN47941261,Viral,26040226,USDA-NVSL,2025,...,SRR33124597,2025-05-09_10-52-41,SRR33124597.fa,B3.13,"NP:am8, PA:ea1, MP:ea1, PB1:am4, PB2:am2.2, NA...","am8:23-032005-001:NP, ea1:22-003707-003:PA, ea...","99.00%, 98.75%, 98.78%, 99.38%, 98.64%, 98.86%...","15, 27, 12, 14, 31, 16, 7, 29",Ran on FASTA - No Coverage Report,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2266,SRR33830443,WGS,148.11,100597029,PRJNA1102327,SAMN48895429,Viral,39710063,USDA-NVSL,2025,...,SRR33830443,2025-06-06_07-56-21,SRR33830443.fa,B3.13,"NA:ea1, PB1:am4, MP:ea1, PA:ea1, NP:am8, HA:ea...","ea1:22-003707-003:NA, am4:23-001855-001:PB1, e...","98.72%, 99.52%, 98.98%, 98.88%, 98.86%, 98.06%...","18, 11, 10, 24, 17, 33, 38, 9",Ran on FASTA - No Coverage Report,USA
2267,SRR33830444,WGS,148.50,131987248,PRJNA1102327,SAMN48895428,Viral,51617990,USDA-NVSL,2025,...,SRR33830444,2025-06-06_07-56-20,SRR33830444.fa,B3.13,"PA:ea1, NA:ea1, PB2:am2.2, NP:am8, HA:ea1, MP:...","ea1:22-003707-003:PA, ea1:22-003707-003:NA, am...","98.88%, 98.65%, 98.20%, 98.93%, 98.06%, 98.98%...","24, 19, 41, 16, 33, 10, 12, 9",Ran on FASTA - No Coverage Report,USA
2268,SRR33830445,WGS,148.12,115677479,PRJNA1102327,SAMN48895427,Viral,45674405,USDA-NVSL,2025,...,SRR33830445,2025-06-06_07-56-21,SRR33830445.fa,B3.13,"NP:am8, HA:ea1, PA:ea1, NS:am1.1, PB1:am4, PB2...","am8:23-032005-001:NP, ea1:22-003707-003:HA, ea...","98.93%, 98.24%, 98.79%, 98.93%, 99.56%, 98.51%...","16, 30, 26, 9, 10, 34, 19, 11",Ran on FASTA - No Coverage Report,USA
2272,SRR33830449,WGS,131.52,67358891,PRJNA1102327,SAMN48895415,Viral,26336550,USDA-NVSL,2024,...,SRR33830449,2025-06-06_07-56-20,SRR33830449.fa,B3.13,"NP:am8, NA:ea1, PB1:am4, HA:ea1, NS:am1.1, MP:...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","98.93%, 98.86%, 99.47%, 98.43%, 99.17%, 98.95%...","16, 16, 12, 12, 7, 10, 31, 24",Ran on FASTA - No Coverage Report,USA
2273,SRR33830450,WGS,131.13,69602732,PRJNA1102327,SAMN48895414,Viral,27556171,USDA-NVSL,2024,...,SRR33830450,2025-06-06_07-56-20,SRR33830450.fa,B3.13,"HA:ea1, NA:ea1, NP:am8, PB2:am2.2, MP:ea1, PB1...","ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...","98.92%, 98.71%, 99.00%, 98.55%, 98.74%, 99.47%...","11, 12, 15, 33, 12, 12, 8, 23",Ran on FASTA - No Coverage Report,USA

In [6]:
# # If no states

# metadata_genbank = metadata

# metadata_genbank["name_state"] = "USA"

# metadata_genbank["Geo_Location"] = "USA"

# display(metadata_genbank)

## Collection Dates

If date is N/A, try finding it first

In [7]:

# # Get all dates
# metadata["Collection_Date_Specific"] = metadata["BioSample"].apply(lambda x: search_collection_date(x, metadata) if "-" not in x else x)

# # Save this so we don't have to do it again

# # os.chdir(temp_files)
# metadata.to_csv("metadata_genbank.csv")

In [8]:
# # Upload saved data -- if doing this, make sure the above cell is commented out
# os.chdir(temp_files + "saved/")
# metadata_genbank = pd.read_csv("metadata_genbank.csv")
# os.chdir(temp_files)

# Get only updated dates

unknown_dates = metadata[(metadata["Collection_Date"] == "2024") | (metadata["Collection_Date"] == "2025")] # Dates we don't have
known_dates = metadata[(metadata["Collection_Date"] != "2024") & (metadata["Collection_Date"] != "2025")] # Dates we've already gotten

# Get new dates also 
# new_dates = metadata["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank) if )

updated_unknown_dates = unknown_dates["BioSample"].apply(lambda x: search_collection_date(x, unknown_dates)) # Update unknown dates, if possible
unknown_dates["Collection_Date"] = updated_unknown_dates

metadata_genbank = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # Remove pre-2024 dates

# metadata_genbank["Collection_Date_Compare"] = metadata_genbank["Collection_Date_Specific"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
# metadata_genbank = metadata_genbank[metadata_genbank["Collection_Date_Compare"] >= datetime(2024, 1, 1).strftime("%Y-%m-%d")]

# print(metadata[["Collection_Date_Specific"]])

display(metadata)

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685060e08a0d775bfc0f318e&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685060e3f2c337a6e409a400&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685060e5f40edc29210fb4f1&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685060e8a4dd2c26630c3a02&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685060f0954e9785950883aa&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-22
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685060f2755f1d7361020aec&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-22
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685060f574e667ffb70daa80&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685060f8896d721da30c7aa2&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685060fa4a04c8162a07c137&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061005a1ced02e209a61e&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2024-11-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850610208afad56b00e61fb&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061055e3c48ba940b1ec9&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2024-11-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061072a17f01b6904551a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2024-11-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850610ae5077f426b046a7d&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2024-11-29
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850611769553c70cb0a7c9a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850611a97256c5784096498&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850611cc0df9d79cd094536&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850611fad288fcf5c00acc4&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_68506121fd2423efbe025178&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061245b5a10bab50c100a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_68506126c4eb52368005be20&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_68506129bc1172d8f905162a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850612bafa337ddd50a1f78&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061398fd4d87fe7004970&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061509c0d03a80f04f58e&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850615347b794f58103738a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061567e775f60fe0d22f2&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_68506158755f1d7361020af0&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-12
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850615e862c9e958605c8c9&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061636944fd7f5d071d27&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061661aef13b90b02e674&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_68506170d4b83a773b052116&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_68506173aef384433c01d76c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_68506175ec86890cfc0241d5&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_68506178847925d7840689a2&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850617ad58826d49a0c35de&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850617d0121cd592d05c6c5&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850617f26f4846ed6002990&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_68506182e39b9e9af70f986c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061844373ce9cd20c03dc&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_68506187e700f60142010f8a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850618a403c58d36d0c150e&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-18
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850618ceb4428066002818c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-19
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850618e20f7e9b2bd098dd1&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850619106c7eec76d04d3fc&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-22
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_68506194b9f4f1ef560911ee&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-17
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_68506197ea4b33df8a08d08a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_68506199fec4b49dfd07616b&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850619c872fdf97040ba452&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_6850619e451411353901869c&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-26
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061a17a4ef61efc01fd66&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-25
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061a456607978eb0601d6&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-25
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061a918dc571bd80653ec&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-25
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061ac534f69b11a0d2bd1&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061af1dcb6d11b801391b&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061b1ee41126de104f4bc&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061b483d2e9436b020058&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061ba56f6080b390f2ae3&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061bc5c3cd21720048a68&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-17
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061bf22511480400a4702&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-24
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061c1f73f1eb178014d04&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061c4036fe18a8b0f498a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
Unable to find collection date.
Unable to find collection date.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061caeb4428066002818e&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061cd0c848babe107f03a&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-20
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nuccore&query_key=1&WebEnv=MCID_685061cf2990eae6b009e11b&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809
2025-02-17
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.
Unable to find collection date.

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_17352\1076642909.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unknown_dates["Collection_Date"] = updated_unknown_dates

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,sample,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,Geo_Location
0,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,SRR33124594,2025-05-09_10-46-09,SRR33124594.fa,B3.13,"NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...","am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...","99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...","7, 20, 16, 12, 28, 13, 28, 33",Ran on FASTA - No Coverage Report,USA
1,SRR33124594,WGS,246.43,145473401,PRJNA1102327,SAMN47941264,Viral,50832578,USDA-NVSL,2025,...,SRR33124594,2025-05-09_10-46-09,SRR33124594.fa,B3.13,"NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...","am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...","99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...","7, 20, 16, 12, 28, 13, 28, 33",Ran on FASTA - No Coverage Report,
2,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,SRR33124595,2025-05-09_10-52-41,SRR33124595.fa,B3.13,"HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...","ea1:22-003707-003:HA, am8:23-032005-001:NP, am...","98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...","28, 20, 7, 33, 14, 16, 12, 28",Ran on FASTA - No Coverage Report,USA
3,SRR33124595,WGS,240.38,139928333,PRJNA1102327,SAMN47941263,Viral,48295907,USDA-NVSL,2025,...,SRR33124595,2025-05-09_10-52-41,SRR33124595.fa,B3.13,"HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...","ea1:22-003707-003:HA, am8:23-032005-001:NP, am...","98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...","28, 20, 7, 33, 14, 16, 12, 28",Ran on FASTA - No Coverage Report,
6,SRR33124597,WGS,264.06,73438935,PRJNA1102327,SAMN47941261,Viral,26040226,USDA-NVSL,2025,...,SRR33124597,2025-05-09_10-52-41,SRR33124597.fa,B3.13,"NP:am8, PA:ea1, MP:ea1, PB1:am4, PB2:am2.2, NA...","am8:23-032005-001:NP, ea1:22-003707-003:PA, ea...","99.00%, 98.75%, 98.78%, 99.38%, 98.64%, 98.86%...","15, 27, 12, 14, 31, 16, 7, 29",Ran on FASTA - No Coverage Report,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2266,SRR33830443,WGS,148.11,100597029,PRJNA1102327,SAMN48895429,Viral,39710063,USDA-NVSL,2025,...,SRR33830443,2025-06-06_07-56-21,SRR33830443.fa,B3.13,"NA:ea1, PB1:am4, MP:ea1, PA:ea1, NP:am8, HA:ea...","ea1:22-003707-003:NA, am4:23-001855-001:PB1, e...","98.72%, 99.52%, 98.98%, 98.88%, 98.86%, 98.06%...","18, 11, 10, 24, 17, 33, 38, 9",Ran on FASTA - No Coverage Report,USA
2267,SRR33830444,WGS,148.50,131987248,PRJNA1102327,SAMN48895428,Viral,51617990,USDA-NVSL,2025,...,SRR33830444,2025-06-06_07-56-20,SRR33830444.fa,B3.13,"PA:ea1, NA:ea1, PB2:am2.2, NP:am8, HA:ea1, MP:...","ea1:22-003707-003:PA, ea1:22-003707-003:NA, am...","98.88%, 98.65%, 98.20%, 98.93%, 98.06%, 98.98%...","24, 19, 41, 16, 33, 10, 12, 9",Ran on FASTA - No Coverage Report,USA
2268,SRR33830445,WGS,148.12,115677479,PRJNA1102327,SAMN48895427,Viral,45674405,USDA-NVSL,2025,...,SRR33830445,2025-06-06_07-56-21,SRR33830445.fa,B3.13,"NP:am8, HA:ea1, PA:ea1, NS:am1.1, PB1:am4, PB2...","am8:23-032005-001:NP, ea1:22-003707-003:HA, ea...","98.93%, 98.24%, 98.79%, 98.93%, 99.56%, 98.51%...","16, 30, 26, 9, 10, 34, 19, 11",Ran on FASTA - No Coverage Report,USA
2272,SRR33830449,WGS,131.52,67358891,PRJNA1102327,SAMN48895415,Viral,26336550,USDA-NVSL,2024,...,SRR33830449,2025-06-06_07-56-20,SRR33830449.fa,B3.13,"NP:am8, NA:ea1, PB1:am4, HA:ea1, NS:am1.1, MP:...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","98.93%, 98.86%, 99.47%, 98.43%, 99.17%, 98.95%...","16, 16, 12, 12, 7, 10, 31, 24",Ran on FASTA - No Coverage Report,USA
2273,SRR33830450,WGS,131.13,69602732,PRJNA1102327,SAMN48895414,Viral,27556171,USDA-NVSL,2024,...,SRR33830450,2025-06-06_07-56-20,SRR33830450.fa,B3.13,"HA:ea1, NA:ea1, NP:am8, PB2:am2.2, MP:ea1, PB1...","ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...","98.92%, 98.71%, 99.00%, 98.55%, 98.74%, 99.47%...","11, 12, 15, 33, 12, 12, 8, 23",Ran on FASTA - No Coverage Report,USA

In [9]:
# If no collection dates

# metadata_genbank["Collection_Date_Specific"] = metadata_genbank["Collection_Date"]

## Get host type

In [10]:
# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

os.chdir(downloads)

animals_ref = pd.read_csv("animals_ref.csv") # Upload animals ref

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['hooded merganser', 'common raven', 'fox', '-', 'partridge', 'barn owl', 'wood duck', 'owl', 'skunk', 'great black-backed gull', 'mallard x american black duck hybrid', 'cattle', 'sand crane', 'hawk', 'chukar', 'canada goose', 'american black duck', 'tundra swan', 'quail', 'raccoon', 'common grackle', 'trumpeter swan', 'flamingo', 'snowy egret', 'red-tailed hawk', 'turkey', "'", 'mallard', 'snowy owl', 'mink', 'common loon', 'barred owl', 'great blue heron', 'sanderling', 'goose', 'red-shouldered hawk', 'cat', 'black vulture', "bonaparte's gull", 'gull', 'greater scaup', 'western sandpiper', 'great horned owl', 'cackling goose', 'american coot', 'red fox', 'chicken', 'cougar', 'pet food', 'falcon', 'glaucous gull', 'swan', 'american crow', 'snow goose', 'peregrine', 'guineafowl', 'bufflehead', 'rock goose', 'vulture', 'duck', 'bald eagle', 'mute swan', 'blue jay', 'dunlin', 'herring gull', 'western gull', "cooper's hawk", 'turkey vulture', "ross's goose", 'red-breasted merganser', 'lesser scaup', nan, 'sharp-shinned hawk', 'crow', 'bobcat', 'great egret', 'gadwall', 'guinea', 'common merganser']
['snowy egret', "'", 'common loon', 'greater scaup', 'glaucous gull', 'rock goose', "ross's goose", nan, 'sharp-shinned hawk', 'great egret', 'guinea']
                avian               cattle        feline   other_mammal  \
0    great_horned_owl            dairy_cow           cat     deer mouse
1        common_raven               cattle  domestic_cat    house_mouse
2       cooper's_hawk  cattle milk product     feral_cat          skunk
3        coopers_hawk          bovine_milk        feline  striped_skunk
4             peafowl              bovine   domestic-cat     norway rat
..                ...                  ...           ...            ...
415         gyrfalcon                  NaN           NaN            NaN
416  american_goshawk                  NaN           NaN            NaN
417      king_vulture                  NaN           NaN            NaN
418     american coot                  NaN           NaN            NaN
419        barred owl                  NaN           NaN            NaN

          human         other            new
0    washington         mixed    snowy egret
1        nevada   environment              '
2       wyoming  multispecies    common loon
3    california       unknown  greater scaup
4      michigan             -  glaucous gull
..          ...           ...            ...
415         NaN           NaN            NaN
416         NaN           NaN            NaN
417         NaN           NaN            NaN
418         NaN           NaN            NaN
419         NaN           NaN            NaN

[420 rows x 7 columns]

In [11]:
# Get animals from animal reference
os.chdir(downloads)
animals_ref = pd.read_csv("animals_ref.csv")
fix_animals_andersen(metadata, animals_ref) # Get host type

metadata["years"] = metadata["Collection_Date"].apply(lambda x: str(x).split("-")[0]) # Get year only from collection date

## Make names using all the attributes we collected

In [12]:
for num, collection_date in enumerate(metadata["Collection_Date"]):
    
    if collection_date != collection_date: # If nan
        metadata.loc[num, "Collection_Date"] = metadata.loc[num, "years"]
    else: # If actual date
        if len(str(collection_date)) == 4: # If it's a year
            # print("caught")
            metadata.loc[num, "Collection_Date"] = collection_date
        else:
            parsed_date = dateutil.parser.parse(collection_date)
            date = parsed_date.strftime("%Y-%m-%d") # Make sure it doesn't default to today, if just a year
            metadata.loc[num, "Collection_Date"] = date

    metadata = metadata.dropna(thresh=2)

# Make names

# + metadata["BioSample"] + "|" 
names = ">" + metadata["Run"] + "|" + "A/" + metadata["Host"] + "/" + metadata["name_state"] + "/" + metadata["isolate"] + "/" + metadata["years"].apply(lambda x: str(x)) + "|H5N1|" + metadata["Geo_Location"] + "|" + metadata["Collection_Date"].apply(lambda x: str(x)) + "|" + metadata["Host_Type"] + "|" + metadata["Genotype"]

metadata["Name"] = names

# metadata_genbank.to_csv("metadata_genbank_named.csv")

display(metadata[["ReleaseDate", 'create_date', 'Collection_Date']])

     ReleaseDate          create_date Collection_Date
0     2025-04-14  2025-04-14 15:21:54            2025
1     2025-04-14  2025-04-14 15:21:54            2025
2     2025-04-14  2025-04-14 15:20:51            2025
3     2025-04-14  2025-04-14 15:20:51            2025
6     2025-04-14  2025-04-14 15:21:19            2025
...          ...                  ...             ...
2266  2025-06-06  2025-06-04 14:25:00            2025
2267  2025-06-06  2025-06-04 14:25:01            2025
2268  2025-06-06  2025-06-04 14:24:54            2025
2272  2025-06-06  2025-06-04 14:24:53            2024
2273  2025-06-06  2025-06-04 14:24:53            2024

[1975 rows x 3 columns]

In [13]:
# Drop duplicate runs 
metadata = metadata.drop_duplicates(subset="Run", keep="first")

In [14]:
print(metadata)

              Run Assay Type  AvgSpotLen        Bases    BioProject  \
0     SRR33124594        WGS      246.43  145473401.0  PRJNA1102327
2     SRR33124595        WGS      240.38  139928333.0  PRJNA1102327
6     SRR33124597        WGS      264.06   73438935.0  PRJNA1102327
8     SRR33124598        WGS      255.94   76531946.0  PRJNA1102327
10    SRR33124599        WGS      145.79   94820034.0  PRJNA1102327
...           ...        ...         ...          ...           ...
2266  SRR33830443        WGS      148.11  100597029.0  PRJNA1102327
2267  SRR33830444        WGS      148.50  131987248.0  PRJNA1102327
2268  SRR33830445        WGS      148.12  115677479.0  PRJNA1102327
2272  SRR33830449        WGS      131.52   67358891.0  PRJNA1102327
2273  SRR33830450        WGS      131.13   69602732.0  PRJNA1102327

         BioSample BioSampleModel       Bytes Center Name Collection_Date  \
0     SAMN47941264          Viral  50832578.0   USDA-NVSL            2025
2     SAMN47941263          Viral  48295907.0   USDA-NVSL            2025
6     SAMN47941261          Viral  26040226.0   USDA-NVSL            2025
8     SAMN47941260          Viral  27022104.0   USDA-NVSL            2025
10    SAMN47941301          Viral  34313048.0   USDA-NVSL            2025
...            ...            ...         ...         ...             ...
2266  SAMN48895429          Viral  39710063.0   USDA-NVSL            2025
2267  SAMN48895428          Viral  51617990.0   USDA-NVSL            2025
2268  SAMN48895427          Viral  45674405.0   USDA-NVSL            2025
2272  SAMN48895415          Viral  26336550.0   USDA-NVSL            2024
2273  SAMN48895414          Viral  27556171.0   USDA-NVSL            2024

      ... Genotype                        Genotype List Used, >=98.0%  \
0     ...    B3.13  NS:am1.1, NP:am8, NA:ea1, MP:ea1, PA:ea1, PB1:...
2     ...    B3.13  HA:ea1, NP:am8, NS:am1.1, PB2:am2.2, PB1:am4, ...
6     ...    B3.13  NP:am8, PA:ea1, MP:ea1, PB1:am4, PB2:am2.2, NA...
8     ...    B3.13  NS:am1.1, PB1:am4, HA:ea1, PB2:am2.2, PA:ea1, ...
10    ...    B3.13  NA:ea1, MP:ea1, NP:am8, PA:ea1, HA:ea1, PB2:am...
...   ...      ...                                                ...
2266  ...    B3.13  NA:ea1, PB1:am4, MP:ea1, PA:ea1, NP:am8, HA:ea...
2267  ...    B3.13  PA:ea1, NA:ea1, PB2:am2.2, NP:am8, HA:ea1, MP:...
2268  ...    B3.13  NP:am8, HA:ea1, PA:ea1, NS:am1.1, PB1:am4, PB2...
2272  ...    B3.13  NP:am8, NA:ea1, PB1:am4, HA:ea1, NS:am1.1, MP:...
2273  ...    B3.13  HA:ea1, NA:ea1, NP:am8, PB2:am2.2, MP:ea1, PB1...

                             Genotype Sample Title List  \
0     am1.1:22-010085-001:NS, am8:23-032005-001:NP, ...
2     ea1:22-003707-003:HA, am8:23-032005-001:NP, am...
6     am8:23-032005-001:NP, ea1:22-003707-003:PA, ea...
8     am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
10    ea1:22-003707-003:NA, ea1:22-003707-003:MP, am...
...                                                 ...
2266  ea1:22-003707-003:NA, am4:23-001855-001:PB1, e...
2267  ea1:22-003707-003:PA, ea1:22-003707-003:NA, am...
2268  am8:23-032005-001:NP, ea1:22-003707-003:HA, ea...
2272  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
2273  ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...

                            Genotype Percent Match List  \
0     99.17%, 98.66%, 98.86%, 98.78%, 98.70%, 99.43%...
2     98.36%, 98.66%, 99.17%, 98.55%, 99.38%, 98.86%...
6     99.00%, 98.75%, 98.78%, 99.38%, 98.64%, 98.86%...
8     99.17%, 99.38%, 98.42%, 98.68%, 98.75%, 98.98%...
10    98.94%, 98.88%, 98.93%, 99.02%, 98.53%, 98.60%...
...                                                 ...
2266  98.72%, 99.52%, 98.98%, 98.88%, 98.86%, 98.06%...
2267  98.88%, 98.65%, 98.20%, 98.93%, 98.06%, 98.98%...
2268  98.93%, 98.24%, 98.79%, 98.93%, 99.56%, 98.51%...
2272  98.93%, 98.86%, 99.47%, 98.43%, 99.17%, 98.95%...
2273  98.92%, 98.71%, 99.00%, 98.55%, 98.74%, 99.47%...

             Genotype Mismatch List Genotype Average Depth of Coverage List  \
0     7, 20, 16, 12, 28, 13, 28, 33       Ran on FASTA - No Coverage Report
2     28, 20, 7, 33, 14, 16, 12, 28       Ran on FASTA - No Coverage Report
6     15, 27, 12, 14, 31, 16, 7, 29       Ran on FASTA - No Coverage Report
8     7, 14, 27, 30, 27, 10, 18, 18       Ran on FASTA - No Coverage Report
10    15, 11, 16, 21, 25, 32, 8, 12       Ran on FASTA - No Coverage Report
...                             ...                                     ...
2266  18, 11, 10, 24, 17, 33, 38, 9       Ran on FASTA - No Coverage Report
2267  24, 19, 41, 16, 33, 10, 12, 9       Ran on FASTA - No Coverage Report
2268  16, 30, 26, 9, 10, 34, 19, 11       Ran on FASTA - No Coverage Report
2272  16, 16, 12, 12, 7, 10, 31, 24       Ran on FASTA - No Coverage Report
2273  11, 12, 15, 33, 12, 12, 8, 23       Ran on FASTA - No Coverage Report

     Geo_Location Host_Type years  \
0             USA    cattle  2025
2             USA    cattle  2025
6             USA    cattle  2025
8             USA    cattle  2025
10            USA    feline  2025
...           ...       ...   ...
2266          USA    cattle  2025
2267          USA    cattle  2025
2268          USA    cattle  2025
2272          USA    cattle  2024
2273          USA    cattle  2024

                                                   Name
0     >SRR33124594|A/CATTLE/USA/25-006243-005/2025|H...
2     >SRR33124595|A/CATTLE/USA/25-006243-002/2025|H...
6     >SRR33124597|A/CATTLE/USA/25-006240-005/2025|H...
8     >SRR33124598|A/CATTLE/USA/25-006031-002/2025|H...
10    >SRR33124599|A/CAT/USA/25-007097-002/2025|H5N1...
...                                                 ...
2266  >SRR33830443|A/CATTLE/USA/25-015681-003/2025|H...
2267  >SRR33830444|A/CATTLE/USA/25-015681-002/2025|H...
2268  >SRR33830445|A/CATTLE/USA/25-015681-001/2025|H...
2272  >SRR33830449|A/CATTLE/USA/24-036379-001-tile/2...
2273  >SRR33830450|A/CATTLE/USA/24-034788-001-tile/2...

[1147 rows x 51 columns]

## Make FASTA files

In [15]:
# Get information to create the fasta files

fasta_folder = originals + "avian-influenza/fasta/"

os.chdir(fasta_folder)

segments = ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]
pairs = []
fasta_files = {}

for genotype in genotypes: # ["B3.13", "D1.1"]:
    for segment in segments:
        pair = genotype + "_" + segment
        pairs.append(pair)

for pair in pairs:
    fasta_files[pair] = [] # List to hold fasta files

for run in metadata["Run"].values: # For each run 
    for dirpath, dirs, files in os.walk(fasta_folder): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            # print(file_name)
            if run in file_name: # Note that there will be ~8 files total with that run name
                # Make a fasta file and put it in the list
                with open(file_name) as f:
                    lines = f.readlines()
                    sequence = lines[1] 
                    # Each run/segment pair has one sequence -- it's placed into a file with other run/segment pairs with the same segment and genotype
                    header = metadata[metadata["Run"] == run].loc[:, "Name"].values[0]
                    genotype = metadata[metadata["Run"] == run].loc[:, "Genotype"].values[0]
                    # print(header)
                    # print(genotype)
                    # break 
                    segment = file_name.split("_")[-2]
                    # Find the pair that corresponds to 
                    pair_name = genotype + "_" + segment
                    this_specific_fasta = []
                    for pair in pairs:
                        # print(pair)
                        # print(pair_name)
                        if pair_name == pair:
                            this_specific_fasta.append(header)
                            this_specific_fasta.append(sequence)
                            fasta_files[pair].append(this_specific_fasta)
                f.close()
        break

In [16]:
# print(fasta_files.keys())

In [17]:
# Create fasta files 

# os.chdir(complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/")
os.chdir(originals + "complete/")
names = []
for pair in fasta_files.keys():
    # output_path = complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/" + pair + "_andersen_updated_" + update_date + ".fasta" 
    output_path = originals + "complete/" + pair + "_andersen_updated_" + update_date + ".fasta"

    output_file = open(output_path, "w")
    for item in fasta_files[pair]:
        # for item in item:
        # item = fasta_files[pair]
        try:
            name = str(item[0].values[0]) # See if this is one we didn't have a collection date for
        except:
            name = str(item[0])
        print(name)
        names.append(name)
        # First is header, second is sequence
        # print(value)
        output_file.write(name + "\n")
        output_file.write(item[1])
    output_file.close()

print(len(names)/8)

>SRR33682399|A/CHICKEN/USA/25-014787-002/2025|H5N1|USA|2025|avian|B3.6
>SRR33682399|A/CHICKEN/USA/25-014787-002/2025|H5N1|USA|2025|avian|B3.6
>SRR33682399|A/CHICKEN/USA/25-014787-002/2025|H5N1|USA|2025|avian|B3.6
>SRR33682399|A/CHICKEN/USA/25-014787-002/2025|H5N1|USA|2025|avian|B3.6
>SRR33682399|A/CHICKEN/USA/25-014787-002/2025|H5N1|USA|2025|avian|B3.6
>SRR33682399|A/CHICKEN/USA/25-014787-002/2025|H5N1|USA|2025|avian|B3.6
>SRR33682399|A/CHICKEN/USA/25-014787-002/2025|H5N1|USA|2025|avian|B3.6
>SRR33682399|A/CHICKEN/USA/25-014787-002/2025|H5N1|USA|2025|avian|B3.6
>SRR33125022|A/CROW/USA/25-004431-001/2025|H5N1|USA|2025|avian|A3
>SRR33125049|A/MALLARD/USA/25-005882-009/2025|H5N1|USA|2025|avian|A3
>SRR33125051|A/BALD EAGLE/USA/25-006076-002/2025|H5N1|USA|2025|avian|A3
>SRR33125053|A/MALLARD/USA/25-005882-006/2025|H5N1|USA|2025|avian|A3
>SRR33125055|A/MALLARD/USA/25-005882-003/2025|H5N1|USA|2025|avian|A3
>SRR33125062|A/BALD EAGLE/USA/25-006076-001/2025|H5N1|USA|2025|avian|A3
>SRR33125127|A/RED-TAILED HAWK/USA/25-004415-008/2025|H5N1|USA|2025|avian|A3
>SRR33319053|A/GREAT HORNED OWL/USA/25-011423-001/2025|H5N1|USA|2025|avian|A3
>SRR33319074|A/AMERICAN CROW/USA/25-011667-003/2025|H5N1|USA|2025|avian|A3
>SRR33319075|A/AMERICAN CROW/USA/25-011667-002/2025|H5N1|USA|2025|avian|A3
>SRR33476775|A/TRUMPETER SWAN/USA/25-011816-002/2025|H5N1|USA|2025|avian|A3
>SRR33508776|A/RED-TAILED HAWK/USA/25-010511-002/2025|H5N1|USA|2025|avian|A3
>SRR33508777|A/RED-TAILED HAWK/USA/25-010511-001/2025|H5N1|USA|2025|avian|A3
>SRR33508778|A/COMMON RAVEN/USA/25-010464-001/2025|H5N1|USA|2025|avian|A3
>SRR33508834|A/BARRED OWL/USA/25-005028-002/2025|H5N1|USA|2025|avian|A3
>SRR33508835|A/AMERICAN CROW/USA/25-005028-001/2025|H5N1|USA|2025|avian|A3
>SRR33565207|A/TURKEY VULTURE/USA/25-013489-001/2025|H5N1|USA|2025|avian|A3
>SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N1|USA|2025|avian|A3
>SRR33125022|A/CROW/USA/25-004431-001/2025|H5N1|USA|2025|avian|A3
>SRR33125049|A/MALLARD/USA/25-005882-009/2025|H5N1|USA|2025|avian|A3
>SRR33125051|A/BALD EAGLE/USA/25-006076-002/2025|H5N1|USA|2025|avian|A3
>SRR33125053|A/MALLARD/USA/25-005882-006/2025|H5N1|USA|2025|avian|A3
>SRR33125055|A/MALLARD/USA/25-005882-003/2025|H5N1|USA|2025|avian|A3
>SRR33125062|A/BALD EAGLE/USA/25-006076-001/2025|H5N1|USA|2025|avian|A3
>SRR33125127|A/RED-TAILED HAWK/USA/25-004415-008/2025|H5N1|USA|2025|avian|A3
>SRR33319053|A/GREAT HORNED OWL/USA/25-011423-001/2025|H5N1|USA|2025|avian|A3
>SRR33319074|A/AMERICAN CROW/USA/25-011667-003/2025|H5N1|USA|2025|avian|A3
>SRR33319075|A/AMERICAN CROW/USA/25-011667-002/2025|H5N1|USA|2025|avian|A3
>SRR33476775|A/TRUMPETER SWAN/USA/25-011816-002/2025|H5N1|USA|2025|avian|A3
>SRR33508776|A/RED-TAILED HAWK/USA/25-010511-002/2025|H5N1|USA|2025|avian|A3
>SRR33508777|A/RED-TAILED HAWK/USA/25-010511-001/2025|H5N1|USA|2025|avian|A3
>SRR33508778|A/COMMON RAVEN/USA/25-010464-001/2025|H5N1|USA|2025|avian|A3
>SRR33508834|A/BARRED OWL/USA/25-005028-002/2025|H5N1|USA|2025|avian|A3
>SRR33508835|A/AMERICAN CROW/USA/25-005028-001/2025|H5N1|USA|2025|avian|A3
>SRR33565207|A/TURKEY VULTURE/USA/25-013489-001/2025|H5N1|USA|2025|avian|A3
>SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N1|USA|2025|avian|A3
>SRR33125022|A/CROW/USA/25-004431-001/2025|H5N1|USA|2025|avian|A3
>SRR33125049|A/MALLARD/USA/25-005882-009/2025|H5N1|USA|2025|avian|A3
>SRR33125051|A/BALD EAGLE/USA/25-006076-002/2025|H5N1|USA|2025|avian|A3
>SRR33125053|A/MALLARD/USA/25-005882-006/2025|H5N1|USA|2025|avian|A3
>SRR33125055|A/MALLARD/USA/25-005882-003/2025|H5N1|USA|2025|avian|A3
>SRR33125062|A/BALD EAGLE/USA/25-006076-001/2025|H5N1|USA|2025|avian|A3
>SRR33125127|A/RED-TAILED HAWK/USA/25-004415-008/2025|H5N1|USA|2025|avian|A3
>SRR33319053|A/GREAT HORNED OWL/USA/25-011423-001/2025|H5N1|USA|2025|avian|A3
>SRR33319074|A/AMERICAN CROW/USA/25-011667-003/2025|H5N1|USA|2025|avian|A3
>SRR33319075|A/AMERICAN CROW/USA/25-011667-002/2025|H5N1|USA|2025|avian|A3
>SRR33476775|A/TRUMPETER SWAN/USA/25-011816-002/2025|H5N1|USA|2025|avian|A3
>SRR33508776|A/RED-TAILED HAWK/USA/25-010511-002/2025|H5N1|USA|2025|avian|A3
>SRR33508777|A/RED-TAILED HAWK/USA/25-010511-001/2025|H5N1|USA|2025|avian|A3
>SRR33508778|A/COMMON RAVEN/USA/25-010464-001/2025|H5N1|USA|2025|avian|A3
>SRR33508834|A/BARRED OWL/USA/25-005028-002/2025|H5N1|USA|2025|avian|A3
>SRR33508835|A/AMERICAN CROW/USA/25-005028-001/2025|H5N1|USA|2025|avian|A3
>SRR33565207|A/TURKEY VULTURE/USA/25-013489-001/2025|H5N1|USA|2025|avian|A3
>SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N1|USA|2025|avian|A3
>SRR33125022|A/CROW/USA/25-004431-001/2025|H5N1|USA|2025|avian|A3
>SRR33125049|A/MALLARD/USA/25-005882-009/2025|H5N1|USA|2025|avian|A3
>SRR33125051|A/BALD EAGLE/USA/25-006076-002/2025|H5N1|USA|2025|avian|A3
>SRR33125053|A/MALLARD/USA/25-005882-006/2025|H5N1|USA|2025|avian|A3
>SRR33125055|A/MALLARD/USA/25-005882-003/2025|H5N1|USA|2025|avian|A3
>SRR33125062|A/BALD EAGLE/USA/25-006076-001/2025|H5N1|USA|2025|avian|A3
>SRR33125127|A/RED-TAILED HAWK/USA/25-004415-008/2025|H5N1|USA|2025|avian|A3
>SRR33319053|A/GREAT HORNED OWL/USA/25-011423-001/2025|H5N1|USA|2025|avian|A3
>SRR33319074|A/AMERICAN CROW/USA/25-011667-003/2025|H5N1|USA|2025|avian|A3
>SRR33319075|A/AMERICAN CROW/USA/25-011667-002/2025|H5N1|USA|2025|avian|A3
>SRR33476775|A/TRUMPETER SWAN/USA/25-011816-002/2025|H5N1|USA|2025|avian|A3
>SRR33508776|A/RED-TAILED HAWK/USA/25-010511-002/2025|H5N1|USA|2025|avian|A3
>SRR33508777|A/RED-TAILED HAWK/USA/25-010511-001/2025|H5N1|USA|2025|avian|A3
>SRR33508778|A/COMMON RAVEN/USA/25-010464-001/2025|H5N1|USA|2025|avian|A3
>SRR33508834|A/BARRED OWL/USA/25-005028-002/2025|H5N1|USA|2025|avian|A3
>SRR33508835|A/AMERICAN CROW/USA/25-005028-001/2025|H5N1|USA|2025|avian|A3
>SRR33565207|A/TURKEY VULTURE/USA/25-013489-001/2025|H5N1|USA|2025|avian|A3
>SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N1|USA|2025|avian|A3
>SRR33125022|A/CROW/USA/25-004431-001/2025|H5N1|USA|2025|avian|A3
>SRR33125049|A/MALLARD/USA/25-005882-009/2025|H5N1|USA|2025|avian|A3
>SRR33125051|A/BALD EAGLE/USA/25-006076-002/2025|H5N1|USA|2025|avian|A3
>SRR33125053|A/MALLARD/USA/25-005882-006/2025|H5N1|USA|2025|avian|A3
>SRR33125055|A/MALLARD/USA/25-005882-003/2025|H5N1|USA|2025|avian|A3
>SRR33125062|A/BALD EAGLE/USA/25-006076-001/2025|H5N1|USA|2025|avian|A3
>SRR33125127|A/RED-TAILED HAWK/USA/25-004415-008/2025|H5N1|USA|2025|avian|A3
>SRR33319053|A/GREAT HORNED OWL/USA/25-011423-001/2025|H5N1|USA|2025|avian|A3
>SRR33319074|A/AMERICAN CROW/USA/25-011667-003/2025|H5N1|USA|2025|avian|A3
>SRR33319075|A/AMERICAN CROW/USA/25-011667-002/2025|H5N1|USA|2025|avian|A3
>SRR33476775|A/TRUMPETER SWAN/USA/25-011816-002/2025|H5N1|USA|2025|avian|A3
>SRR33508776|A/RED-TAILED HAWK/USA/25-010511-002/2025|H5N1|USA|2025|avian|A3
>SRR33508777|A/RED-TAILED HAWK/USA/25-010511-001/2025|H5N1|USA|2025|avian|A3
>SRR33508778|A/COMMON RAVEN/USA/25-010464-001/2025|H5N1|USA|2025|avian|A3
>SRR33508834|A/BARRED OWL/USA/25-005028-002/2025|H5N1|USA|2025|avian|A3
>SRR33508835|A/AMERICAN CROW/USA/25-005028-001/2025|H5N1|USA|2025|avian|A3
>SRR33565207|A/TURKEY VULTURE/USA/25-013489-001/2025|H5N1|USA|2025|avian|A3
>SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N1|USA|2025|avian|A3
>SRR33125022|A/CROW/USA/25-004431-001/2025|H5N1|USA|2025|avian|A3
>SRR33125049|A/MALLARD/USA/25-005882-009/2025|H5N1|USA|2025|avian|A3
>SRR33125051|A/BALD EAGLE/USA/25-006076-002/2025|H5N1|USA|2025|avian|A3
>SRR33125053|A/MALLARD/USA/25-005882-006/2025|H5N1|USA|2025|avian|A3
>SRR33125055|A/MALLARD/USA/25-005882-003/2025|H5N1|USA|2025|avian|A3
>SRR33125062|A/BALD EAGLE/USA/25-006076-001/2025|H5N1|USA|2025|avian|A3
>SRR33125127|A/RED-TAILED HAWK/USA/25-004415-008/2025|H5N1|USA|2025|avian|A3
>SRR33319053|A/GREAT HORNED OWL/USA/25-011423-001/2025|H5N1|USA|2025|avian|A3
>SRR33319074|A/AMERICAN CROW/USA/25-011667-003/2025|H5N1|USA|2025|avian|A3
>SRR33319075|A/AMERICAN CROW/USA/25-011667-002/2025|H5N1|USA|2025|avian|A3
>SRR33476775|A/TRUMPETER SWAN/USA/25-011816-002/2025|H5N1|USA|2025|avian|A3
>SRR33508776|A/RED-TAILED HAWK/USA/25-010511-002/2025|H5N1|USA|2025|avian|A3
>SRR33508777|A/RED-TAILED HAWK/USA/25-010511-001/2025|H5N1|USA|2025|avian|A3
>SRR33508778|A/COMMON RAVEN/USA/25-010464-001/2025|H5N1|USA|2025|avian|A3
>SRR33508834|A/BARRED OWL/USA/25-005028-002/2025|H5N1|USA|2025|avian|A3
>SRR33508835|A/AMERICAN CROW/USA/25-005028-001/2025|H5N1|USA|2025|avian|A3
>SRR33565207|A/TURKEY VULTURE/USA/25-013489-001/2025|H5N1|USA|2025|avian|A3
>SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N1|USA|2025|avian|A3
>SRR33125022|A/CROW/USA/25-004431-001/2025|H5N1|USA|2025|avian|A3
>SRR33125049|A/MALLARD/USA/25-005882-009/2025|H5N1|USA|2025|avian|A3
>SRR33125051|A/BALD EAGLE/USA/25-006076-002/2025|H5N1|USA|2025|avian|A3
>SRR33125053|A/MALLARD/USA/25-005882-006/2025|H5N1|USA|2025|avian|A3
>SRR33125055|A/MALLARD/USA/25-005882-003/2025|H5N1|USA|2025|avian|A3
>SRR33125062|A/BALD EAGLE/USA/25-006076-001/2025|H5N1|USA|2025|avian|A3
>SRR33125127|A/RED-TAILED HAWK/USA/25-004415-008/2025|H5N1|USA|2025|avian|A3
>SRR33319053|A/GREAT HORNED OWL/USA/25-011423-001/2025|H5N1|USA|2025|avian|A3
>SRR33319074|A/AMERICAN CROW/USA/25-011667-003/2025|H5N1|USA|2025|avian|A3
>SRR33319075|A/AMERICAN CROW/USA/25-011667-002/2025|H5N1|USA|2025|avian|A3
>SRR33476775|A/TRUMPETER SWAN/USA/25-011816-002/2025|H5N1|USA|2025|avian|A3
>SRR33508776|A/RED-TAILED HAWK/USA/25-010511-002/2025|H5N1|USA|2025|avian|A3
>SRR33508777|A/RED-TAILED HAWK/USA/25-010511-001/2025|H5N1|USA|2025|avian|A3
>SRR33508778|A/COMMON RAVEN/USA/25-010464-001/2025|H5N1|USA|2025|avian|A3
>SRR33508834|A/BARRED OWL/USA/25-005028-002/2025|H5N1|USA|2025|avian|A3
>SRR33508835|A/AMERICAN CROW/USA/25-005028-001/2025|H5N1|USA|2025|avian|A3
>SRR33565207|A/TURKEY VULTURE/USA/25-013489-001/2025|H5N1|USA|2025|avian|A3
>SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N1|USA|2025|avian|A3
>SRR33125022|A/CROW/USA/25-004431-001/2025|H5N1|USA|2025|avian|A3
>SRR33125049|A/MALLARD/USA/25-005882-009/2025|H5N1|USA|2025|avian|A3
>SRR33125051|A/BALD EAGLE/USA/25-006076-002/2025|H5N1|USA|2025|avian|A3
>SRR33125053|A/MALLARD/USA/25-005882-006/2025|H5N1|USA|2025|avian|A3
>SRR33125055|A/MALLARD/USA/25-005882-003/2025|H5N1|USA|2025|avian|A3
>SRR33125062|A/BALD EAGLE/USA/25-006076-001/2025|H5N1|USA|2025|avian|A3
>SRR33125127|A/RED-TAILED HAWK/USA/25-004415-008/2025|H5N1|USA|2025|avian|A3
>SRR33319053|A/GREAT HORNED OWL/USA/25-011423-001/2025|H5N1|USA|2025|avian|A3
>SRR33319074|A/AMERICAN CROW/USA/25-011667-003/2025|H5N1|USA|2025|avian|A3
>SRR33319075|A/AMERICAN CROW/USA/25-011667-002/2025|H5N1|USA|2025|avian|A3
>SRR33476775|A/TRUMPETER SWAN/USA/25-011816-002/2025|H5N1|USA|2025|avian|A3
>SRR33508776|A/RED-TAILED HAWK/USA/25-010511-002/2025|H5N1|USA|2025|avian|A3
>SRR33508777|A/RED-TAILED HAWK/USA/25-010511-001/2025|H5N1|USA|2025|avian|A3
>SRR33508778|A/COMMON RAVEN/USA/25-010464-001/2025|H5N1|USA|2025|avian|A3
>SRR33508834|A/BARRED OWL/USA/25-005028-002/2025|H5N1|USA|2025|avian|A3
>SRR33508835|A/AMERICAN CROW/USA/25-005028-001/2025|H5N1|USA|2025|avian|A3
>SRR33565207|A/TURKEY VULTURE/USA/25-013489-001/2025|H5N1|USA|2025|avian|A3
>SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N1|USA|2025|avian|A3
>SRR33124594|A/CATTLE/USA/25-006243-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124595|A/CATTLE/USA/25-006243-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124597|A/CATTLE/USA/25-006240-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124598|A/CATTLE/USA/25-006031-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124599|A/CAT/USA/25-007097-002/2025|H5N1|USA|2025|feline|B3.13
>SRR33124600|A/CAT/USA/25-007097-001/2025|H5N1|USA|2025|feline|B3.13
>SRR33124601|A/CAT/USA/25-006638-001/2025|H5N1|USA|2025|feline|B3.13
>SRR33124602|A/CAT/USA/25-006544-001/2025|H5N1|USA|2025|feline|B3.13
>SRR33124603|A/CAT/USA/25-006543-001/2025|H5N1|USA|2025|feline|B3.13
>SRR33124604|A/CATTLE/USA/25-006954-002/2025|H5N1|USA|2024-11-19|cattle|B3.13
nan
>SRR33124606|A/CATTLE/USA/25-006029-002/2025|H5N1|USA|2024-11-19|cattle|B3.13
nan
nan
nan
>SRR33124610|A/CATTLE/USA/25-006276-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124611|A/CATTLE/USA/25-006276-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124612|A/CATTLE/USA/25-006276-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124613|A/CATTLE/USA/25-006276-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124614|A/CATTLE/USA/25-006274-006/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124616|A/CATTLE/USA/25-006274-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124617|A/CATTLE/USA/25-006028-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124618|A/CATTLE/USA/25-006274-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124619|A/CATTLE/USA/25-006274-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124620|A/CATTLE/USA/25-006274-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124621|A/CATTLE/USA/25-006263-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124622|A/CATTLE/USA/25-006263-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124623|A/CATTLE/USA/25-006263-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124624|A/CATTLE/USA/25-006260-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124625|A/CATTLE/USA/25-006260-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124626|A/CATTLE/USA/25-006260-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124627|A/CATTLE/USA/25-006260-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124628|A/CATTLE/USA/25-006026-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124629|A/CATTLE/USA/25-006260-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124630|A/CATTLE/USA/25-006251-007/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124631|A/CATTLE/USA/25-006251-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124632|A/CATTLE/USA/25-006251-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124633|A/CATTLE/USA/25-006251-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124634|A/CATTLE/USA/25-006248-006/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124635|A/CATTLE/USA/25-006248-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124638|A/CATTLE/USA/25-006243-006/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124639|A/CATTLE/USA/25-006020-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33124640|A/CATTLE/USA/25-006020-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318592|A/CATTLE/USA/25-011299-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318593|A/CATTLE/USA/25-011299-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318594|A/CATTLE/USA/25-011296-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318595|A/CATTLE/USA/25-011296-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318596|A/PET FOOD/USA/25-010008-011-v/2025|H5N1|USA|2025|feline|B3.13
>SRR33318597|A/PET FOOD/USA/25-010008-007-v/2025|H5N1|USA|2025|feline|B3.13
>SRR33318598|A/CATTLE/USA/25-011296-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318599|A/PET FOOD/USA/25-010008-005-v/2025|H5N1|USA|2025|feline|B3.13
>SRR33318600|A/PET FOOD/USA/25-010008-004-v/2025|H5N1|USA|2025|feline|B3.13
>SRR33318601|A/CATTLE/USA/25-012178-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318602|A/CATTLE/USA/25-012178-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318603|A/CATTLE/USA/25-012178-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318604|A/CATTLE/USA/25-012133-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318605|A/CATTLE/USA/25-012131-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318606|A/CATTLE/USA/25-012130-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318607|A/CATTLE/USA/25-012130-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318608|A/CATTLE/USA/25-012130-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318609|A/CATTLE/USA/25-011010-002/2025|H5N1|USA|2024|cattle|B3.13
>SRR33318610|A/CATTLE/USA/25-012118-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318612|A/CATTLE/USA/25-012115-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318613|A/CATTLE/USA/25-012115-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318614|A/CATTLE/USA/25-012114-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318615|A/CATTLE/USA/25-012113-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318616|A/CATTLE/USA/25-012113-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318617|A/CATTLE/USA/25-012112-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318618|A/CATTLE/USA/25-012112-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318619|A/CATTLE/USA/25-012111-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318620|A/CATTLE/USA/25-011010-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318621|A/CATTLE/USA/25-012111-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318622|A/CATTLE/USA/25-012092-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318623|A/CATTLE/USA/25-011474-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318624|A/CATTLE/USA/25-011468-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318625|A/CATTLE/USA/25-011468-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318626|A/CATTLE/USA/25-011468-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318627|A/CATTLE/USA/25-011387-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318628|A/CATTLE/USA/25-011387-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318629|A/CATTLE/USA/25-011387-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318630|A/CATTLE/USA/25-011373-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318631|A/CATTLE/USA/25-011000-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318632|A/CATTLE/USA/25-011373-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318633|A/CATTLE/USA/25-011373-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318634|A/CATTLE/USA/25-011373-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318635|A/CATTLE/USA/25-011373-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33318636|A/CATTLE/USA/25-011372-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33318637|A/CATTLE/USA/25-011320-002/2025|H5N1|USA|2024|cattle|B3.13
>SRR33318638|A/CATTLE/USA/25-011320-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33318639|A/CATTLE/USA/25-011318-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318640|A/CATTLE/USA/25-011318-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318641|A/CATTLE/USA/25-011318-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318642|A/CATTLE/USA/25-010999-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33318643|A/CATTLE/USA/25-010998-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369778|A/CATTLE/USA/24-036208-001/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369779|A/CATTLE/USA/24-036204-001/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369780|A/CATTLE/USA/24-036203-002/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369781|A/CATTLE/USA/24-036203-001/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369782|A/CATTLE/USA/25-012953-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369783|A/CATTLE/USA/25-012952-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369784|A/CATTLE/USA/25-012952-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369785|A/CATTLE/USA/25-012952-001/2025|H5N1|USA|2024|cattle|B3.13
>SRR33369786|A/CATTLE/USA/25-012951-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369787|A/CATTLE/USA/24-036187-002/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369788|A/CATTLE/USA/25-012949-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369789|A/CATTLE/USA/25-012948-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369790|A/CATTLE/USA/25-012189-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369791|A/CATTLE/USA/25-012189-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369792|A/CATTLE/USA/25-012189-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369793|A/CATTLE/USA/25-012189-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369794|A/CATTLE/USA/25-012187-005/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369795|A/CATTLE/USA/25-012187-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369796|A/CATTLE/USA/25-012183-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369797|A/CATTLE/USA/25-012183-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369798|A/CATTLE/USA/24-036187-001/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369799|A/CATTLE/USA/25-012183-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369800|A/CATTLE/USA/25-012183-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369801|A/CATTLE/USA/25-012134-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369802|A/CATTLE/USA/25-012134-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369803|A/CATTLE/USA/25-012132-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369804|A/CATTLE/USA/25-012129-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369805|A/CATTLE/USA/25-012128-004/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369806|A/CATTLE/USA/25-012128-003/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369807|A/CATTLE/USA/25-012128-002/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369808|A/CATTLE/USA/25-012128-001/2025|H5N1|USA|2025|cattle|B3.13
>SRR33369809|A/CATTLE/USA/24-036182-002/2024|H5N1|USA|2025|cattle|B3.13
>SRR33369810|A/CATTLE/USA/25-012127-006/2025|H5N1|USA|2025|cattle|B3.13

## De-Duplication

In [19]:
# De-duplication 

# Gisaid 
dfs_gisaid_list = []
for genotype in genotypes:

    gisaid = downloads + "GISAID/complete/" + genotype.replace(".", "_") + "/" + date_range + "_" + genotype.replace(".", "_") + "_North_America/"

    # gisaid = downloads + "Cats/Datasets/GISAID/"

    os.chdir(gisaid)

    dfs_gisaid = create_dataframes(gisaid)
    dfs_gisaid_list.append(dfs_gisaid)

dfs_gisaid = {}
for df_gisaid in dfs_gisaid_list:
    dfs_gisaid = dfs_gisaid | df_gisaid
# dfs_gisaid2 = create_dataframes(gisaid2)

B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2

In [20]:
# Do the same with Andersen 

# dfs_andersen = create_dataframes(complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/")
dfs_andersen = create_dataframes(originals + "complete/")

A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_HA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_MP
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NP
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NS
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PB1
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2

In [21]:
# os.chdir(downloads)
# dfs_gisaid["B3.13_HA"].to_csv

In [22]:
for key in dfs_andersen.keys():
    dataframes = dfs_andersen[key]
    print(key)

print(dfs_andersen)

A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
defaultdict(<class 'list'>, {'A3_HA': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
3   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
5   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
6   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
7   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
8   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
9   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
10  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
11  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
12  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
13  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
14  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
15  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
16  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
17  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...  ], 'A3_MP': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
5   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
6   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
7   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
8   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
9   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
10  ATGAGTCTTCTGACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
11  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
12  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
13  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
14  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
15  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
16  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
17  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...  ], 'A3_NA': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
1   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
2   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
3   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
4   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
5   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
6   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
7   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
8   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
9   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
10  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
11  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
12  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
13  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
14  ATGAATCCAAATCAAAGGATAATAATCACTGGATCAATCTGTATGG...
15  ATGAATCCAAATCAAAGGATAATAATCACTGGATCAATCTGTATGG...
16  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
17  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...  ], 'A3_NP': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
1   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
2   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
3   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
4   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
5   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
6   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
7   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
8   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
9   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
10  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
11  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
12  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
13  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
14  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
15  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
16  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
17  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...  ], 'A3_NS': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
1   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
2   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
3   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
4   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
5   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
6   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
7   ATGGATACCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
8   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
9   ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
10  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
11  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
12  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
13  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
14  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
15  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
16  ATGGATTCCAACACTGTGTCGAGCTTTCAGGTAGACTGCTTTCTTT...
17  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...  ], 'A3_PA': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
1   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
2   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
3   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
4   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
5   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
6   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
7   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
8   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
9   ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
10  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
11  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
12  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
13  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
14  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
15  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
16  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
17  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...  ], 'A3_PB1': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
1   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
2   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
3   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
4   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
5   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
6   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
7   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
8   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
9   ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
10  ATGGATGTCAATCCGACTTTACTTCTCTTAAAAGTGCCAGCGCAAG...
11  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
12  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
13  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
14  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
15  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
16  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
17  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...  ], 'A3_PB2': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
1   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
2   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
3   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
4   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
5   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
6   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
7   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
8   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
9   ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
10  ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
11  ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
12  ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
13  ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
14  ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
15  ATGGAGAGAATAAAAGAGCTAAGAAATTTGATGTCGCAGTCTCGCA...
16  ATGGAGAGAATAAAAAAGCTAAGAGATTTGATGTCGCAGTCTCGCA...
17  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...  ], 'B3.13_HA': [    isolate_partial                                        full_header  \
0        006243-005  >SRR33124594|A/CATTLE/USA/25-006243-005/2025|H...
1        006243-002  >SRR33124595|A/CATTLE/USA/25-006243-002/2025|H...
2        006240-005  >SRR33124597|A/CATTLE/USA/25-006240-005/2025|H...
3        006031-002  >SRR33124598|A/CATTLE/USA/25-006031-002/2025|H...
4        007097-002  >SRR33124599|A/CAT/USA/25-007097-002/2025|H5N1...
..              ...                                                ...
523      015681-003  >SRR33830443|A/CATTLE/USA/25-015681-003/2025|H...
524      015681-002  >SRR33830444|A/CATTLE/USA/25-015681-002/2025|H...

In [23]:
print(len(list(dfs_gisaid.keys())))
print(len(list(dfs_andersen.keys())))

32
32

In [24]:
# Merge dataframes and drop duplicates

full_dfs = defaultdict(list)
# same = []
# andersen = set()
# gisaid = set()

for i, andersen_key in enumerate(dfs_andersen.keys()):
    if len(dfs_andersen[andersen_key]) > 0:
        for j, gisaid_key in enumerate(dfs_gisaid.keys()):
            if andersen_key == gisaid_key:
                # same.append(gisaid_key)
        # gisaid_key = list(dfs_gisaid.keys())[i]
        # gisaid2_key = list(dfs_gisaid2.keys())[i]

                andersen_df = dfs_andersen[andersen_key][0]
                print(len(andersen_df))
                # print(andersen_df)
                gisaid_df = dfs_gisaid[gisaid_key][0]
                print(len(gisaid_df))
                # gisaid2_df = dfs_gisaid2[gisaid2_key][0]

                print(pd.concat([gisaid_df, andersen_df]).drop_duplicates())

                full_df = pd.concat([andersen_df, gisaid_df], ignore_index=True)
                print("len full df:", len(full_df))
                test = len(full_df.drop_duplicates(subset="isolate_partial"))

                dedup_df = full_df.drop_duplicates(subset="isolate_partial", keep="last")

                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print(full_df)
                
                print("Keeping nothing: ", test)
                
                print("len deduplicated:", len(dedup_df))
                full_dfs[andersen_key].append(dedup_df)
            # else:
                # gisaid.add(gisaid_key)
                # andersen.add(andersen_key)
    
    # break 


# print(full_dfs)
# print(len(full_dfs))
# print(319*8)
# print(len(same))
# print(len(andersen))
# print(len(gisaid))

18
22
   isolate_partial                                        full_header  \
0        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
1        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
2        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
3        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
4        IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
5        IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
6       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
7       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
8       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
9       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
10      010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
11      010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atggagaacatagtacttcttcttgcaataattagccttgttaaaa...
1   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
2   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
3   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
4   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
5   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
6   atggagaacatagtacttcttcttgcaataattagccttgttaaaa...
7   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
8   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
9   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
10  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
11  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
12  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
13  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
14  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
15  atggaaaccatagtacttcttcttgcaataattagccttgttaaaa...
16  atggaaaacatagcacttcttcttgcaataattagccttgttaaaa...
17  atggaaaccatagtacttcttcttgcaataattagccttgttaaaa...
18  atggaaaacatagcacttcttcttgcaataattagccttgttaaaa...
19  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
20  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
21  atggaaaacatagcacttcttcttgcaataattagccttgttaaaa...
0   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
3   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
5   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
6   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
7   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
8   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
9   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
10  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
11  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
12  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
13  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
14  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
15  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
16  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
17  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
len full df: 40
Keeping nothing:  24
len deduplicated: 24
18
22
   isolate_partial                                        full_header  \
0        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
1        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
2        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
3        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
4        IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
5        IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
6       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
7       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
8       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
9       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
10      010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
11      010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
1   tagatattgaaagatgagtcttctaaccgaggtcgaaacgtacgtt...
2   tagatattgaaagatgagtcttctaaccgaggtcgaaacgtacgtt...
3   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
4   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
5   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
6   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
7   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
8   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
9   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
10  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
11  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
12  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
13  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
14  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
15  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
16  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
17  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
18  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
19  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
20  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
21  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
0   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
5   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
6   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
7   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
8   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
9   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
10  ATGAGTCTTCTGACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
11  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
12  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
13  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
14  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
15  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
16  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
17  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
len full df: 40
Keeping nothing:  24
len deduplicated: 24
18
22
   isolate_partial                                        full_header  \
0        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
1        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
2        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
3        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
4        IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
5        IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
6       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
7       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
8       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
9       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
10      010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
11      010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
1   aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
2   agttcaaaatgaatccaaatcaaaggataataaccactggatcaat...
3   aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
4   aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
5   aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
6   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
7   atgaatccaaatcaaaggataataatcactggatcaatctgtatgg...
8   atgaatccaaatcaaaggataataatcactggatcaatctgtatgg...
9   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
10  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
11  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
12  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
13  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
14  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
15  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
16  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
17  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
18  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
19  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
20  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
21  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
0   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
1   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
2   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
3   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
4   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
5   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
6   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
7   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
8   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
9   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
10  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
11  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
12  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
13  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
14  ATGAATCCAAATCAAAGGATAATAATCACTGGATCAATCTGTATGG...
15  ATGAATCCAAATCAAAGGATAATAATCACTGGATCAATCTGTATGG...
16  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
17  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
len full df: 40
Keeping nothing:  24
len deduplicated: 24
18
22
   isolate_partial                                        full_header  \
0        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
1        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
2        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
3        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
4        IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
5        IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
6       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
7       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
8       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
9       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
10      010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
11      010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
1   gtagataatcactcactgagtgacatcaacatcatggcgtctcaag...
2   gtagataatcactcactgagtgacatcaacatcatggcgtctcaag...
3   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
4   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
5   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
6   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
7   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
8   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
9   atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
10  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
11  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
12  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
13  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
14  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
15  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
16  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
17  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
18  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
19  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
20  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
21  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
0   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
1   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
2   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
3   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
4   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
5   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
6   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...

In [25]:
# # If none in one database, only use the other and drop duplicates

# full_dfs = defaultdict(list)
# for key in dfs_andersen.keys():
#     print(key)
# # for key in ["D1.3"]:
#     dataframes = dfs_andersen[key]
#     for i, df in enumerate(dataframes):
#         print(i)
#         try:
#             full_df = df.merge(dfs_gisaid[key][i], how="outer")
#             # print(full_df)
#             full_df = full_df.drop_duplicates(subset=["isolate_partial"])
#             full_dfs[key].append(full_df)
#         except:
#             print("Failed to merge dataframes in ", key)
#             full_dfs[key].append(dataframes[i])

## Create FASTA files combining Andersen and GISAID

In [26]:
# Create FASTA files per segment

combined_files = downloads + "Combinations/GISAID_Andersen/" # B3_13_D1_1/" + date_range + "_B3_13_D1_1/"

os.chdir(combined_files)
for pair in full_dfs.keys():
    print(pair)
    output_path = combined_files + pair + "_combined_" + update_date + ".fasta" 

    output_file = open(output_path, "w")
    for item in full_dfs[pair]:
        # for item in item:
        # item = fasta_files[pair]
        for index, row in item.iterrows():
            name = item.loc[index, "full_header"]
            sequence = item.loc[index, "sequence"]
            # print(name)
        # First is header, second is sequence
        # print(value)
            output_file.write(name)
            output_file.write(sequence)
    output_file.close()

A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2