# Cleaning Downloaded Data from avian-flu

Author: Alexander Maksiaev

Purpose: Clean downloaded data from avian-flu, rename sequences according to convention, de-duplicate from GISAID

In [1]:
# Housekeeping

import os
import glob 
import pandas as pd
import xml.etree.ElementTree as ET
import requests
import time
import numpy as np
import dateutil 
from datetime import datetime
from collections import defaultdict 
import importlib
import utils  
importlib.reload(utils)
from utils import * 


# Dates
start_date = "11-01-2021"
end_date = "06-13-2025"
date_range = start_date + "--" + end_date
# update_date = "06-18-2025"

# Make sure you have the correct paths

home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/"
downloads = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/"
# downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
references = home + "references/"
originals = downloads + "Andersen/"
saved = originals + "saved/"
temp_files = originals + "temp/"
complete_files = downloads + "complete/"

os.chdir(downloads)

## Read Metadata

In [2]:
# Read metadata

# os.chdir(saved)
# metadata_normalized = pd.read_csv("metadata_normalized.tsv", delimiter="\t") # Collection dates

metadata_folder = originals + "avian-influenza/metadata/"
os.chdir(metadata_folder)

metadata = pd.read_csv("SraRunTable_automated.csv")

print(len(metadata)) # 7397 rows

# metadata = metadata.merge(metadata_normalized, how="outer")
print(metadata.columns)

metadata["name_state"] = metadata["geo_loc_name"].apply(lambda x: x.split("/")[1] if len(x.split("/")) > 1 else x.split("/")[0])

# Find only >= last date using Release Date from metadata 
metadata["ReleaseDate"] = metadata["ReleaseDate"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
# print(metadata["ReleaseDate"])
metadata = metadata[metadata["ReleaseDate"] >= dateutil.parser.parse(start_date).strftime("%Y-%m-%d")]
# Find only <= update date using Release Date from metadata
metadata = metadata[metadata["ReleaseDate"] <= dateutil.parser.parse(end_date).strftime("%Y-%m-%d")]

# Get rid of certain runs
os.chdir(saved)
runs_to_remove = pd.read_csv("andersen-lab-seqs-to-filter.csv")
print(runs_to_remove)
for run in runs_to_remove["Run"].values:
    metadata = metadata[metadata["Run"] != run]

print(len(metadata)) # 6053 rows between 1/1/2024 and 4/14/2025
display(metadata)
print(metadata["Library Name"])

9808
Index(['Run', 'Assay Type', 'AvgSpotLen', 'Bases', 'BioProject', 'BioSample',
       'BioSampleModel', 'Bytes', 'Center Name', 'Collection_Date', 'Consent',
       'DATASTORE filetype', 'DATASTORE provider', 'DATASTORE region',
       'Experiment', 'geo_loc_name_country', 'geo_loc_name_country_continent',
       'geo_loc_name', 'Host', 'Instrument', 'isolate', 'Library Name',
       'LibraryLayout', 'LibrarySelection', 'LibrarySource', 'Organism',
       'Platform', 'ReleaseDate', 'create_date', 'version', 'Sample Name',
       'SRA Study', 'serotype', 'isolation_source', 'BioSample Accession',
       'is_retracted', 'retraction_detection_date_utc'],
      dtype='object')
              Run
0     SRR24839736
1     SRR24839063
2     SRR24839065
3     SRR24839713
4     SRR24839570
...           ...
1310  SRR24843048
1311  SRR24839118
1312  SRR24839711
1313  SRR24843405
1314  SRR24843040

[1315 rows x 1 columns]
8444

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,create_date,version,Sample Name,SRA Study,serotype,isolation_source,BioSample Accession,is_retracted,retraction_detection_date_utc,name_state
0,SRR28752446,WGS,146.11,93605195,PRJNA1102327,SAMN41019184,Viral,30074178,USDA-NVSL,2024,...,2024-04-20T18:12:00Z,1,24-008354-001-original,SRP503016,H5N1,NaN,SRS21079812,False,NaN,USA
1,SRR28752447,WGS,241.29,86080323,PRJNA1102327,SAMN41019237,Viral,28164109,USDA-NVSL,2024,...,2024-04-20T18:12:00Z,1,24-009108-005-original,SRP503016,H5N1,NaN,SRS21079811,False,NaN,USA
2,SRR28752448,WGS,250.30,75035343,PRJNA1102327,SAMN41019236,Viral,24547283,USDA-NVSL,2024,...,2024-04-20T18:12:00Z,1,24-009108-004-original,SRP503016,H5N1,NaN,SRS21079810,False,NaN,USA
3,SRR28752449,WGS,146.61,59363690,PRJNA1102327,SAMN41019235,Viral,19686302,USDA-NVSL,2024,...,2024-04-20T18:12:00Z,1,24-009108-003-original,SRP503016,H5N1,NaN,SRS21079809,False,NaN,USA
4,SRR28752450,WGS,251.31,119232569,PRJNA1102327,SAMN41019234,Viral,38846827,USDA-NVSL,2024,...,2024-04-20T18:12:00Z,1,24-009108-002-original,SRP503016,H5N1,NaN,SRS21079808,False,NaN,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,SRR33943358,WGS,148.58,145468815,PRJNA1102327,SAMN49008963,Viral,50309372,USDA-NVSL,2025,...,2025-06-11 17:51:42,1,25-013594-001,SRP503016,NaN,milk,SRS25347775,False,NaN,USA
9755,SRR33943359,WGS,148.65,141682464,PRJNA1102327,SAMN49008954,Viral,52273363,USDA-NVSL,2025,...,2025-06-11 17:51:39,1,25-016317-001,SRP503016,NaN,milk,SRS25347774,False,NaN,USA
9756,SRR33943360,WGS,148.56,109583296,PRJNA1102327,SAMN49008953,Viral,40873907,USDA-NVSL,2025,...,2025-06-11 17:51:39,1,25-015080-001,SRP503016,NaN,"MILK, BULK TANK",SRS25347773,False,NaN,USA
9757,SRR33943301,WGS,148.82,146047742,PRJNA980729,SAMN49008919,Viral,51264801,USDA-NVSL,2025,...,2025-06-11 17:50:24,1,25-016837-002,SRP441379,NaN,OROPHARYNGEAL SWAB,SRS25347770,False,NaN,USA
9758,SRR33943302,WGS,148.87,176312039,PRJNA980729,SAMN49008918,Viral,61802719,USDA-NVSL,2025,...,2025-06-11 17:50:27,1,25-016837-001,SRP441379,NaN,OROPHARYNGEAL SWAB,SRS25347769,False,NaN,USA

0               24-008354-001-original
1               24-009108-005-original
2               24-009108-004-original
3               24-009108-003-original
4               24-009108-002-original
                     ...
9754    25-013594-001-original-repeat2
9755            25-016317-001-original
9756            25-015080-001-original
9757            25-016837-002-original
9758            25-016837-001-original
Name: Library Name, Length: 8444, dtype: object

In [3]:
# Get list of genotypes

os.chdir(home + "references/")

genotypes_df = pd.read_excel("genotype_key.xlsx")

genotypes = list(genotypes_df["Genotype"])

print(genotypes)

# genotypes = ["B3.13", "D1.1"]

# genotypes = ["B3.2"] #, "B3.2", "B3.6", "B3.7", "B3.5", "A3"]

['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'B1.1', 'B1.2', 'B1.3', 'B2.1', 'B2.2', 'B3.1', 'B3.2', 'B3.3', 'B3.4', 'B3.5', 'B3.6', 'B4.1', 'B5.1', 'Minor01', 'Minor04', 'Minor07', 'Minor08', 'Minor09', 'Minor10', 'Minor11', 'Minor12', 'Minor13', 'Minor14', 'Minor15', 'Minor16', 'Minor17', 'Minor18', 'Minor19', 'Minor24', 'Minor25', 'Minor26', 'Minor27', 'Minor28', 'Minor29', 'Minor30', 'Minor31', 'Minor32', 'Minor33', 'Minor34', 'Minor35', 'Minor36', 'Minor37', 'Minor38', 'Minor39', 'Minor40', 'Minor41', 'Minor42', 'Minor43', 'Minor44', 'Minor45', 'Minor46', 'Minor47', 'Minor48', 'B3.7', 'Minor50', 'Minor51', 'C1.1', 'Minor52', 'Minor53', 'B3.11', 'Minor55', 'Minor56', 'Minor57', 'Minor58', 'B3.10', 'C2.1', 'Minor60', 'Minor61', 'B3.8', 'Minor62', 'Minor63', 'B3.12', 'Minor65', 'Minor66', 'Minor67', 'B3.9', 'Minor70', 'Minor71', 'B3.13', 'Minor73', 'Minor74', 'Minor75', 'Minor76', 'Minor77', 'Minor78', 'Minor79', 'Minor80', 'Minor81', 'Minor82', 'Minor83', 'Minor84', 'C3.1', 'Minor86', 'Minor87', 'Minor89', 'Minor90', 'Minor91', 'Minor92', 'Minor93', 'Minor94', 'D1.1', 'D1.2', 'D2.1', 'Minor95', 'D1.3', 'Minor98', 'Minor99', 'Minor100', 'Minor101', 'Minor97', 'Minor102', 'Minor103', 'Minor104', 'Minor105', 'Minor106']

### Naming convention ###
>A/[host]/[geo_loc_name]/[isolate]/[year]|[serotype: H5N1]|[collection_date]|[host_type]|[genotype]

host_type is from manual animal reference

In metadata, we have: host, geo_loc_name, isolate, year

We need: geo_loc_name, collection_date, host_type, genotype

host = Host

geo_loc_name (primary) = geo_loc_name

geo_loc_name (secondary) = genbank_mapping.tsv > genbank_name

isolate = isolate

collection date (primary) = Collection_Date

collection date (secondary) = https://www.ncbi.nlm.nih.gov/genbank/ > BioSample (input: BioSample) > Nucleotide > [first result] > collection_date

serotype = serotype

host type = [from ref] 

genotype = [from genoflu] -- use genoflu_results.tsv

## Get genotype, specific geolocation

In [4]:
# Get genotype from genoflu_results.tsv

os.chdir(metadata_folder)

genoflu_results = pd.read_csv("genoflu_results.tsv", delimiter="\t")

genoflu_results["Run"] = genoflu_results["sample"]

metadata = metadata.merge(genoflu_results, on="Run", how="inner")
print(metadata)
# metadata = metadata[~metadata["Genotype"].str.contains('Not assigned')] # Do not include non-assigned genotypes
metadata = metadata[metadata["Genotype"].isin(genotypes)]

# Get only the genotypes we want: B3.13 and D1.1

# b313_and_d11_only = genoflu_results[(genoflu_results["Genotype"] == "B3.13") | (genoflu_results["Genotype"] == "D1.1")]
# b313_and_d11_only = b313_and_d11_only.rename(columns={"sample": "Run"})
# b313_and_d11_only = b313_and_d11_only.drop_duplicates(subset="Run", keep="last")

# metadata = metadata.merge(b313_and_d11_only, on=["Run", "Genotype"], how="inner")

print(len(metadata)) 

display(metadata)

              Run Assay Type  AvgSpotLen      Bases    BioProject  \
0     SRR28752446        WGS      146.11   93605195  PRJNA1102327
1     SRR28752447        WGS      241.29   86080323  PRJNA1102327
2     SRR28752448        WGS      250.30   75035343  PRJNA1102327
3     SRR28752449        WGS      146.61   59363690  PRJNA1102327
4     SRR28752450        WGS      251.31  119232569  PRJNA1102327
...           ...        ...         ...        ...           ...
8439  SRR33943358        WGS      148.58  145468815  PRJNA1102327
8440  SRR33943359        WGS      148.65  141682464  PRJNA1102327
8441  SRR33943360        WGS      148.56  109583296  PRJNA1102327
8442  SRR33943301        WGS      148.82  146047742   PRJNA980729
8443  SRR33943302        WGS      148.87  176312039   PRJNA980729

         BioSample BioSampleModel     Bytes Center Name Collection_Date  ...  \
0     SAMN41019184          Viral  30074178   USDA-NVSL            2024  ...
1     SAMN41019237          Viral  28164109   USDA-NVSL            2024  ...
2     SAMN41019236          Viral  24547283   USDA-NVSL            2024  ...
3     SAMN41019235          Viral  19686302   USDA-NVSL            2024  ...
4     SAMN41019234          Viral  38846827   USDA-NVSL            2024  ...
...            ...            ...       ...         ...             ...  ...
8439  SAMN49008963          Viral  50309372   USDA-NVSL            2025  ...
8440  SAMN49008954          Viral  52273363   USDA-NVSL            2025  ...
8441  SAMN49008953          Viral  40873907   USDA-NVSL            2025  ...
8442  SAMN49008919          Viral  51264801   USDA-NVSL            2025  ...
8443  SAMN49008918          Viral  61802719   USDA-NVSL            2025  ...

     name_state       sample                 date       File Name Genotype  \
0           USA  SRR28752446  2025-05-09_10-47-05  SRR28752446.fa    B3.13
1           USA  SRR28752447  2025-05-09_10-45-55  SRR28752447.fa    B3.13
2           USA  SRR28752448  2025-05-09_10-47-06  SRR28752448.fa    B3.13
3           USA  SRR28752449  2025-05-09_10-46-33  SRR28752449.fa    B3.13
4           USA  SRR28752450  2025-05-09_10-47-05  SRR28752450.fa    B3.13
...         ...          ...                  ...             ...      ...
8439        USA  SRR33943358  2025-06-13_07-18-34  SRR33943358.fa    B3.13
8440        USA  SRR33943359  2025-06-13_07-18-34  SRR33943359.fa    B3.13
8441        USA  SRR33943360  2025-06-13_07-18-34  SRR33943360.fa    B3.13
8442        USA  SRR33943301  2025-06-13_07-18-34  SRR33943301.fa     D1.1
8443        USA  SRR33943302  2025-06-13_07-18-34  SRR33943302.fa     D1.1

                            Genotype List Used, >=98.0%  \
0     NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...
1     NP:am8, MP:ea1, PB2:am2.2, HA:ea1, NA:ea1, PA:...
2     HA:ea1, NA:ea1, MP:ea1, PA:ea1, PB1:am4, PB2:a...
3     MP:ea1, PA:ea1, PB2:am2.2, NP:am8, NS:am1.1, N...
4     PA:ea1, PB2:am2.2, MP:ea1, NS:am1.1, PB1:am4, ...
...                                                 ...
8439  PA:ea1, NA:ea1, PB2:am2.2, NP:am8, HA:ea1, PB1...
8440  HA:ea1, PB1:am4, NA:ea1, MP:ea1, NP:am8, PA:ea...
8441  PB1:am4, MP:ea1, NP:am8, NA:ea1, PB2:am2.2, HA...
8442  PB2:am24, NA:am4N1, MP:ea3, NS:ea3, PA:am4, HA...
8443  NS:ea3, PB2:am24, PB1:ea3, MP:ea3, HA:ea3, PA:...

                             Genotype Sample Title List  \
0     am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
1     am8:23-032005-001:NP, ea1:22-003707-003:MP, am...
2     ea1:22-003707-003:HA, ea1:22-003707-003:NA, ea...
3     ea1:22-003707-003:MP, ea1:22-003707-003:PA, am...
4     ea1:22-003707-003:PA, am2.2:22-010445-001:PB2,...
...                                                 ...
8439  ea1:22-003707-003:PA, ea1:22-003707-003:NA, am...
8440  ea1:22-003707-003:HA, am4:23-001855-001:PB1, e...
8441  am4:23-001855-001:PB1, ea1:22-003707-003:MP, a...
8442  am24:24-030039-001:PB2, am4N1:24-030039-001:NA...
8443  ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...

                            Genotype Percent Match List  \
0     99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
1     99.40%, 98.88%, 98.86%, 98.77%, 99.08%, 99.16%...
2     98.77%, 99.08%, 98.88%, 99.21%, 99.56%, 98.86%...
3     98.88%, 99.16%, 98.86%, 99.33%, 99.28%, 99.08%...
4     99.21%, 98.82%, 98.88%, 99.17%, 99.56%, 98.77%...
...                                                 ...
8439  98.84%, 98.65%, 98.51%, 98.86%, 98.12%, 99.56%...
8440  98.42%, 99.34%, 98.58%, 98.78%, 98.93%, 98.79%...
8441  99.12%, 98.98%, 98.93%, 98.72%, 98.51%, 98.30%...
8442  99.56%, 99.04%, 100.00%, 98.93%, 98.75%, 99.47...
8443  98.81%, 99.47%, 99.16%, 99.90%, 99.41%, 99.44%...

              Genotype Mismatch List Genotype Average Depth of Coverage List
0      7, 11, 25, 21, 11, 18, 10, 14       Ran on FASTA - No Coverage Report
1       9, 11, 26, 21, 13, 18, 6, 10       Ran on FASTA - No Coverage Report
2      21, 13, 11, 17, 10, 26, 7, 10       Ran on FASTA - No Coverage Report
3      11, 18, 26, 10, 6, 13, 21, 10       Ran on FASTA - No Coverage Report
4      17, 27, 11, 7, 10, 21, 10, 13       Ran on FASTA - No Coverage Report
...                              ...                                     ...
8439   25, 19, 34, 17, 32, 10, 9, 10       Ran on FASTA - No Coverage Report
8440   27, 15, 20, 12, 16, 26, 33, 8       Ran on FASTA - No Coverage Report
8441  20, 10, 16, 18, 34, 29, 22, 11       Ran on FASTA - No Coverage Report
8442      10, 10, 0, 9, 27, 9, 17, 7       Ran on FASTA - No Coverage Report
8443    10, 12, 19, 1, 10, 12, 6, 12       Ran on FASTA - No Coverage Report

[8444 rows x 47 columns]
7959

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,name_state,sample,date,File Name,Genotype,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List
0,SRR28752446,WGS,146.11,93605195,PRJNA1102327,SAMN41019184,Viral,30074178,USDA-NVSL,2024,...,USA,SRR28752446,2025-05-09_10-47-05,SRR28752446.fa,B3.13,"NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...","am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...","99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...","7, 11, 25, 21, 11, 18, 10, 14",Ran on FASTA - No Coverage Report
1,SRR28752447,WGS,241.29,86080323,PRJNA1102327,SAMN41019237,Viral,28164109,USDA-NVSL,2024,...,USA,SRR28752447,2025-05-09_10-45-55,SRR28752447.fa,B3.13,"NP:am8, MP:ea1, PB2:am2.2, HA:ea1, NA:ea1, PA:...","am8:23-032005-001:NP, ea1:22-003707-003:MP, am...","99.40%, 98.88%, 98.86%, 98.77%, 99.08%, 99.16%...","9, 11, 26, 21, 13, 18, 6, 10",Ran on FASTA - No Coverage Report
2,SRR28752448,WGS,250.30,75035343,PRJNA1102327,SAMN41019236,Viral,24547283,USDA-NVSL,2024,...,USA,SRR28752448,2025-05-09_10-47-06,SRR28752448.fa,B3.13,"HA:ea1, NA:ea1, MP:ea1, PA:ea1, PB1:am4, PB2:a...","ea1:22-003707-003:HA, ea1:22-003707-003:NA, ea...","98.77%, 99.08%, 98.88%, 99.21%, 99.56%, 98.86%...","21, 13, 11, 17, 10, 26, 7, 10",Ran on FASTA - No Coverage Report
3,SRR28752449,WGS,146.61,59363690,PRJNA1102327,SAMN41019235,Viral,19686302,USDA-NVSL,2024,...,USA,SRR28752449,2025-05-09_10-46-33,SRR28752449.fa,B3.13,"MP:ea1, PA:ea1, PB2:am2.2, NP:am8, NS:am1.1, N...","ea1:22-003707-003:MP, ea1:22-003707-003:PA, am...","98.88%, 99.16%, 98.86%, 99.33%, 99.28%, 99.08%...","11, 18, 26, 10, 6, 13, 21, 10",Ran on FASTA - No Coverage Report
4,SRR28752450,WGS,251.31,119232569,PRJNA1102327,SAMN41019234,Viral,38846827,USDA-NVSL,2024,...,USA,SRR28752450,2025-05-09_10-47-05,SRR28752450.fa,B3.13,"PA:ea1, PB2:am2.2, MP:ea1, NS:am1.1, PB1:am4, ...","ea1:22-003707-003:PA, am2.2:22-010445-001:PB2,...","99.21%, 98.82%, 98.88%, 99.17%, 99.56%, 98.77%...","17, 27, 11, 7, 10, 21, 10, 13",Ran on FASTA - No Coverage Report
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8439,SRR33943358,WGS,148.58,145468815,PRJNA1102327,SAMN49008963,Viral,50309372,USDA-NVSL,2025,...,USA,SRR33943358,2025-06-13_07-18-34,SRR33943358.fa,B3.13,"PA:ea1, NA:ea1, PB2:am2.2, NP:am8, HA:ea1, PB1...","ea1:22-003707-003:PA, ea1:22-003707-003:NA, am...","98.84%, 98.65%, 98.51%, 98.86%, 98.12%, 99.56%...","25, 19, 34, 17, 32, 10, 9, 10",Ran on FASTA - No Coverage Report
8440,SRR33943359,WGS,148.65,141682464,PRJNA1102327,SAMN49008954,Viral,52273363,USDA-NVSL,2025,...,USA,SRR33943359,2025-06-13_07-18-34,SRR33943359.fa,B3.13,"HA:ea1, PB1:am4, NA:ea1, MP:ea1, NP:am8, PA:ea...","ea1:22-003707-003:HA, am4:23-001855-001:PB1, e...","98.42%, 99.34%, 98.58%, 98.78%, 98.93%, 98.79%...","27, 15, 20, 12, 16, 26, 33, 8",Ran on FASTA - No Coverage Report
8441,SRR33943360,WGS,148.56,109583296,PRJNA1102327,SAMN49008953,Viral,40873907,USDA-NVSL,2025,...,USA,SRR33943360,2025-06-13_07-18-34,SRR33943360.fa,B3.13,"PB1:am4, MP:ea1, NP:am8, NA:ea1, PB2:am2.2, HA...","am4:23-001855-001:PB1, ea1:22-003707-003:MP, a...","99.12%, 98.98%, 98.93%, 98.72%, 98.51%, 98.30%...","20, 10, 16, 18, 34, 29, 22, 11",Ran on FASTA - No Coverage Report
8442,SRR33943301,WGS,148.82,146047742,PRJNA980729,SAMN49008919,Viral,51264801,USDA-NVSL,2025,...,USA,SRR33943301,2025-06-13_07-18-34,SRR33943301.fa,D1.1,"PB2:am24, NA:am4N1, MP:ea3, NS:ea3, PA:am4, HA...","am24:24-030039-001:PB2, am4N1:24-030039-001:NA...","99.56%, 99.04%, 100.00%, 98.93%, 98.75%, 99.47...","10, 10, 0, 9, 27, 9, 17, 7",Ran on FASTA - No Coverage Report
8443,SRR33943302,WGS,148.87,176312039,PRJNA980729,SAMN49008918,Viral,61802719,USDA-NVSL,2025,...,USA,SRR33943302,2025-06-13_07-18-34,SRR33943302.fa,D1.1,"NS:ea3, PB2:am24, PB1:ea3, MP:ea3, HA:ea3, PA:...","ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...","98.81%, 99.47%, 99.16%, 99.90%, 99.41%, 99.44%...","10, 12, 19, 1, 10, 12, 6, 12",Ran on FASTA - No Coverage Report

In [ ]:
# Get specific geolocation and name_state from genbank_mapping.tsv

genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
genbank_mapping["Run"] = genbank_mapping["sra_run"]
genbank_mapping = genbank_mapping.drop_duplicates(subset="Run", keep="first") # Drop duplicates
genbank_mapping["name_state"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[2]) # Get the name of the state

# print(genbank_mapping)

# metadata_genbank = metadata.merge(genbank_mapping, on=["Run"]) # Only include data that has states

# Get geolocation for second state attribute

os.chdir(home + "references/")
state_ref = pd.read_csv("states_ref.csv")
metadata["Geo_Location"] = metadata["name_state"].apply(lambda x: 
                                                        state_ref.loc[state_ref["Abbreviation"].str.contains('|'.join(x.replace(', ', ' ').split(' ')), regex=True), 'Country'].iloc[0] 
                                                        + "-" + 
                                                        x
                                                        if state_ref["Abbreviation"].str.contains("|".join((x.replace(", ", " ").split(" "))), regex=True).any()
                                                        else state_ref.loc[state_ref['State'].str.contains('|'.join(x.replace(', ', ' ').split(' ')), regex=True), 'Country'].iloc[0]
                                                        + "-" + 
                                                        state_ref.loc[state_ref['State'].str.contains('|'.join(x.replace(', ', ' ').split(' ')), regex=True), 'Abbreviation'].iloc[0] 
                                                        if state_ref["State"].str.contains("|".join((x.replace(", ", " ").split(" "))), regex=True).any() 
                                                        else x)

print(state_ref.loc[state_ref['State'].str.contains('|'.join("Kentucky, whatever".replace(',', ' ').split(' ')), regex=True), 'Abbreviation'])
print(state_ref['State'].str.contains('|'.join("Kentucky, whatever".replace(', ', ' ').split(' ')), regex=True))
print(metadata["name_state"])
print(metadata["Geo_Location"])
print(len(metadata))
display(metadata) # Maybe there is no state information since 3/18/2025?

IndexError: single positional indexer is out-of-bounds

In [ ]:
# # If no states

# metadata_genbank = metadata

# metadata_genbank["name_state"] = "USA"

# metadata_genbank["Geo_Location"] = "USA"

# display(metadata_genbank)

## Collection Dates

If date is N/A, try finding it first

In [ ]:

# # Get all dates
# metadata["Collection_Date_Specific"] = metadata["BioSample"].apply(lambda x: search_collection_date(x, metadata) if "-" not in x else x)

# # Save this so we don't have to do it again

# # os.chdir(temp_files)
# metadata.to_csv("metadata_genbank.csv")

In [ ]:
os.chdir(saved)

metadata_to_merge = pd.read_csv("metadata_genbank_" + date_range + ".csv")
metadata = pd.merge(metadata, metadata_to_merge, how="left")
# metadata = pd.read_csv("metadata_genbank.csv")
print(len(metadata))

7959

C:\Users\maksi\AppData\Local\Temp\ipykernel_22472\3732131206.py:3: DtypeWarning: Columns (41,46,48) have mixed types. Specify dtype option on import or set low_memory=False.
  metadata_to_merge = pd.read_csv("metadata_genbank_" + date_range + ".csv")

In [ ]:
date = "2025" 

date = dateutil.parser.parse(date, default=datetime(2000, 1, 1))

print(date.month)

1

In [ ]:
# # # Upload saved data -- if doing this, make sure the above cell is commented out
# # os.chdir(temp_files + "saved/")
# # metadata_genbank = pd.read_csv("metadata_genbank.csv")
# # os.chdir(temp_files)

# # Get only updated dates

# # unknown_dates = metadata[(metadata["Collection_Date"] == "2024") | (metadata["Collection_Date"] == "2025")] # Dates we don't have

# def find_known_dates(x, df):
    
#     try:
#         date = metadata[metadata["BioSample"] == x]["Collection_Date"].values[0]
#     # print(date)
#         # print(date)
#         # if len(str(date)) == 4: # If this is just a year
#         #     date = search_collection_date(x, df)
#         # else:
#         date = dateutil.parser.parse(date, default=datetime(2000, 1, 1)) # .strftime("%Y-%m-%d") # If a date already exists
#         if date.day == dateutil.parser.parse("1/1/2000").day and date.month == dateutil.parser.parse("1/1/2000").month:
#             print("year only")
#             date = search_collection_date(x, df)
#         print("Success", date)
#     except:
#         date = search_collection_date(x, df) # If it's not parseable as a date
#     return date # If statement in lambda function will search for the "just year" values
        

# # years = ["2021", "2022", "2023", "2024", "2025"]
# # unknown_dates = metadata[metadata["Collection_Date"].isin(years)]
# # # known_dates = metadata[(metadata["Collection_Date"] != "2024") & (metadata["Collection_Date"] != "2025")] # Dates we've already gotten
# # known_dates = metadata[~metadata["Collection_Date"].isin(years)]

# # Get new dates also 
# # new_dates = metadata["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank) if )

# updated_dates = metadata["BioSample"].apply(lambda x: find_known_dates(x, metadata)) # Update unknown dates, if possible
# metadata["Collection_Date"] = updated_dates

# # metadata = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # updated_unknown_dates = unknown_dates["BioSample"].apply(lambda x: search_collection_date(x, unknown_dates)) # Update unknown dates, if possible
# # unknown_dates["Collection_Date"] = updated_unknown_dates

# # metadata = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # Save this so we don't have to do it again

# # os.chdir(temp_files)
# # metadata.to_csv("metadata_genbank_" + date_range + ".csv")

# # display(metadata)

In [ ]:
# os.chdir(temp_files)
# metadata.to_csv("metadata_genbank_" + date_range + ".csv")

# If no collection dates

# metadata_genbank["Collection_Date_Specific"] = metadata_genbank["Collection_Date"]

## Get host type

In [ ]:
# create a mask, where is True if the host does not exist
print(metadata["Host"])

mask = metadata["Host"].isna()

# choose between the original value and split isolate using the mask
metadata["Host"] = np.where(mask, metadata["isolate"].apply(lambda x: x if x != x or "/" not in x or len(x.split("/")) < 2 else x.split("/")[1]), metadata["Host"]) #  if "/" in metadata["isolate"] else metadata["Host"])
metadata["Host"] = metadata["Host"].apply(lambda x: x.lower() if x == x else x)

# print(metadata["Host"])

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

# print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

os.chdir(home + "references/")

animals_ref = pd.read_csv("animals_ref.csv") # Upload animals ref

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort2.csv") # Make sure name is different to avoid overwriting the first reference 

print(metadata["Host"])
# print(metadata["isolate"])

0       Blackbird
1          Cattle
2          Cattle
3          Cattle
4          Cattle
          ...
7954       CATTLE
7955       CATTLE
7956       CATTLE
7957      CHICKEN
7958      CHICKEN
Name: Host, Length: 7959, dtype: object
[]
                  avian               cattle        feline   other_mammal  \
0      great_horned_owl            dairy_cow           cat     deer mouse
1          common_raven               cattle  domestic_cat    house_mouse
2         cooper's_hawk  cattle milk product     feral_cat          skunk
3          coopers_hawk          bovine_milk        feline  striped_skunk
4               peafowl              bovine   domestic-cat     norway rat
..                  ...                  ...           ...            ...
466         anser anser                  NaN           NaN            NaN
467    northern harrier                  NaN           NaN            NaN
468              mergus                  NaN           NaN            NaN
469  thalasseus maximus                  NaN           NaN            NaN
470       calidris alba                  NaN           NaN            NaN

          human         other  new
0    washington         mixed  NaN
1        nevada   environment  NaN
2       wyoming  multispecies  NaN
3    california       unknown  NaN
4      michigan             '  NaN
..          ...           ...  ...
466         NaN           NaN  NaN
467         NaN           NaN  NaN
468         NaN           NaN  NaN
469         NaN           NaN  NaN
470         NaN           NaN  NaN

[471 rows x 7 columns]
0       blackbird
1          cattle
2          cattle
3          cattle
4          cattle
          ...
7954       cattle
7955       cattle
7956       cattle
7957      chicken
7958      chicken
Name: Host, Length: 7959, dtype: object

In [ ]:
# Get animals from animal reference
os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")
fix_animals_andersen(metadata, animals_ref) # Get host type

metadata["years"] = metadata["Collection_Date"].apply(lambda x: str(x).split("-")[0]) # Get year only from collection date

## Make names using all the attributes we collected

In [ ]:
for num, collection_date in enumerate(metadata["Collection_Date"]):
    if collection_date != collection_date: # if nan
         collection_date = "missing"
    try:
        print(collection_date)
        if collection_date.month == datetime.parser.parse("1/1/2000").month and collection_date.day == datetime.parser.parse("1/1/2000").day:
            # If not a valid collection date, but has year
            
            year = collection_date.year
            metadata.loc[num, "Collection_Date"] = year
            # if collection_date != collection_date: # If nan
        #     metadata.loc[num, "Collection_Date"] = metadata.loc[num, "years"]
        else: # If actual date
                
            # if len(str(collection_date)) == 4: # If it's a year
                # print("caught")
                metadata.loc[num, "Collection_Date"] = collection_date
    except:
         metadata.loc[num, "Collection_Date"] = collection_date
        # else:
        #     try:
        #         parsed_date = dateutil.parser.parse(collection_date)
        #         date = parsed_date.strftime("%Y-%m-%d") # Make sure it doesn't default to today, if just a year
        #         metadata.loc[num, "Collection_Date"] = date
        #     except: # If no date at all
        #         metadata.loc[num, "Collection_Date"] = collection_date

    # metadata = metadata.dropna(thresh=2)

2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2023
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024-05-24
2024-05-24
2024-06-04
2024-06-04
2024-06-03
2024-06-03
2024-06-03
2024-05-24
2024-06-03
2024-06-03
2024-05-30
2024-05-30
2024-06-04
2024-06-04
2024-06-04
2024-06-04
2024-05-28
2024-05-28
2024-05-24
2024-05-28
2024-05-25
2024-06-03
2024-05-28
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-05-24
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-05-24
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-04-29
2024-05-24
2024-05-28
2024-05-28
2024-05-28
2024-05-28
2024-04-30
2024-04-30
2024-04-30
2024-04-30
2024-04-30
2024-04-30
2024-05-24
2024-04-30
2024-04-30
2024-04-30
2024-04-30
2024-04-30
2024-05-24
2024-05-24
2024-05-24
2024-05-24
2024-05-24
2024-05-15
2024-05-15
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024-12-06
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2025
2025
2025
2025
2025
2025
2025
2025
2024
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2024
2025
2025
2024
2024
2024
2024
2024
2024
2024
2025
2024
2025
2025
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2025
2025
2025
2025
2025
2025
2024
2025
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024
2024-06-09
2024-06-09
2024-06-09
2024-06-09
2024-06-09
2024-06-09
2024-07-02
2024-07-02
2024-07-03
2024-07-02
2024-07-02
2024-07-02
2024-07-02
2024-06-24
2024-06-24
2024-06-10
2024-06-24
2024-06-24
2024-06-24
2024-05-30
2024-06-09
2024-06-09
2024-05-28
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025
2025

In [ ]:
# Make names

metadata = metadata.fillna("")

# + metadata["BioSample"] + "|" 
names = ">" + metadata["Run"] + "|" + "A/" + metadata["Host"] + "/" + metadata["name_state"] + "/" + metadata["Sample Name"] + "/" + metadata["years"].apply(lambda x: str(x)) + "|" + metadata["serotype"] + "|" + metadata["Geo_Location"] + "|" + metadata["Collection_Date"].apply(lambda x: str(x)) + "|" + metadata["Host_Type"] + "|" + metadata["Genotype"]

metadata["Name"] = names

# metadata_genbank.to_csv("metadata_genbank_named.csv")

display(metadata["Name"])

0       >SRR28752446|A/blackbird/USA/24-008354-001-ori...
1       >SRR28752447|A/cattle/USA/24-009108-005-origin...
2       >SRR28752448|A/cattle/USA/24-009108-004-origin...
3       >SRR28752449|A/cattle/USA/24-009108-003-origin...
4       >SRR28752450|A/cattle/USA/24-009108-002-origin...
                              ...
7954    >SRR33943358|A/cattle/USA/25-013594-001/2025||...
7955    >SRR33943359|A/cattle/USA/25-016317-001/2025||...
7956    >SRR33943360|A/cattle/USA/25-015080-001/2025||...
7957    >SRR33943301|A/chicken/USA/25-016837-002/2025|...
7958    >SRR33943302|A/chicken/USA/25-016837-001/2025|...
Name: Name, Length: 7959, dtype: object

In [ ]:
# Drop duplicate runs 
metadata = metadata.drop_duplicates(subset="Run", keep="first")

In [ ]:
print(metadata)
metadata.to_csv("metadata_test.csv")

              Run Assay Type AvgSpotLen      Bases    BioProject  \
0     SRR28752446        WGS     146.11   93605195  PRJNA1102327
1     SRR28752447        WGS     241.29   86080323  PRJNA1102327
2     SRR28752448        WGS      250.3   75035343  PRJNA1102327
3     SRR28752449        WGS     146.61   59363690  PRJNA1102327
4     SRR28752450        WGS     251.31  119232569  PRJNA1102327
...           ...        ...        ...        ...           ...
7954  SRR33943358        WGS     148.58  145468815  PRJNA1102327
7955  SRR33943359        WGS     148.65  141682464  PRJNA1102327
7956  SRR33943360        WGS     148.56  109583296  PRJNA1102327
7957  SRR33943301        WGS     148.82  146047742   PRJNA980729
7958  SRR33943302        WGS     148.87  176312039   PRJNA980729

         BioSample BioSampleModel     Bytes Center Name Collection_Date  ...  \
0     SAMN41019184          Viral  30074178   USDA-NVSL            2024  ...
1     SAMN41019237          Viral  28164109   USDA-NVSL            2024  ...
2     SAMN41019236          Viral  24547283   USDA-NVSL            2024  ...
3     SAMN41019235          Viral  19686302   USDA-NVSL            2024  ...
4     SAMN41019234          Viral  38846827   USDA-NVSL            2024  ...
...            ...            ...       ...         ...             ...  ...
7954  SAMN49008963          Viral  50309372   USDA-NVSL            2025  ...
7955  SAMN49008954          Viral  52273363   USDA-NVSL            2025  ...
7956  SAMN49008953          Viral  40873907   USDA-NVSL            2025  ...
7957  SAMN49008919          Viral  51264801   USDA-NVSL            2025  ...
7958  SAMN49008918          Viral  61802719   USDA-NVSL            2025  ...

                             Genotype Sample Title List  \
0     am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
1     am8:23-032005-001:NP, ea1:22-003707-003:MP, am...
2     ea1:22-003707-003:HA, ea1:22-003707-003:NA, ea...
3     ea1:22-003707-003:MP, ea1:22-003707-003:PA, am...
4     ea1:22-003707-003:PA, am2.2:22-010445-001:PB2,...
...                                                 ...
7954  ea1:22-003707-003:PA, ea1:22-003707-003:NA, am...
7955  ea1:22-003707-003:HA, am4:23-001855-001:PB1, e...
7956  am4:23-001855-001:PB1, ea1:22-003707-003:MP, a...
7957  am24:24-030039-001:PB2, am4N1:24-030039-001:NA...
7958  ea3:22-013001-001:NS, am24:24-030039-001:PB2, ...

                            Genotype Percent Match List  \
0     99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
1     99.40%, 98.88%, 98.86%, 98.77%, 99.08%, 99.16%...
2     98.77%, 99.08%, 98.88%, 99.21%, 99.56%, 98.86%...
3     98.88%, 99.16%, 98.86%, 99.33%, 99.28%, 99.08%...
4     99.21%, 98.82%, 98.88%, 99.17%, 99.56%, 98.77%...
...                                                 ...
7954  98.84%, 98.65%, 98.51%, 98.86%, 98.12%, 99.56%...
7955  98.42%, 99.34%, 98.58%, 98.78%, 98.93%, 98.79%...
7956  99.12%, 98.98%, 98.93%, 98.72%, 98.51%, 98.30%...
7957  99.56%, 99.04%, 100.00%, 98.93%, 98.75%, 99.47...
7958  98.81%, 99.47%, 99.16%, 99.90%, 99.41%, 99.44%...

              Genotype Mismatch List Genotype Average Depth of Coverage List  \
0      7, 11, 25, 21, 11, 18, 10, 14       Ran on FASTA - No Coverage Report
1       9, 11, 26, 21, 13, 18, 6, 10       Ran on FASTA - No Coverage Report
2      21, 13, 11, 17, 10, 26, 7, 10       Ran on FASTA - No Coverage Report
3      11, 18, 26, 10, 6, 13, 21, 10       Ran on FASTA - No Coverage Report
4      17, 27, 11, 7, 10, 21, 10, 13       Ran on FASTA - No Coverage Report
...                              ...                                     ...
7954   25, 19, 34, 17, 32, 10, 9, 10       Ran on FASTA - No Coverage Report
7955   27, 15, 20, 12, 16, 26, 33, 8       Ran on FASTA - No Coverage Report
7956  20, 10, 16, 18, 34, 29, 22, 11       Ran on FASTA - No Coverage Report
7957      10, 10, 0, 9, 27, 9, 17, 7       Ran on FASTA - No Coverage Report
7958    10, 12, 19, 1, 10, 12, 6, 12       Ran on FASTA - No Coverage Report

     Geo_Location Unnamed: 0.1 Unnamed: 0 Host_Type years  \
0             USA                             avian  2024
1             USA                            cattle  2024
2             USA                            cattle  2024
3             USA                            cattle  2024
4             USA                            cattle  2024
...           ...          ...        ...       ...   ...
7954          USA                            cattle  2025
7955          USA                            cattle  2025
7956          USA                            cattle  2025
7957          USA                             avian  2025
7958          USA                             avian  2025

                                                   Name
0     >SRR28752446|A/blackbird/USA/24-008354-001-ori...
1     >SRR28752447|A/cattle/USA/24-009108-005-origin...
2     >SRR28752448|A/cattle/USA/24-009108-004-origin...
3     >SRR28752449|A/cattle/USA/24-009108-003-origin...
4     >SRR28752450|A/cattle/USA/24-009108-002-origin...
...                                                 ...
7954  >SRR33943358|A/cattle/USA/25-013594-001/2025||...
7955  >SRR33943359|A/cattle/USA/25-016317-001/2025||...
7956  >SRR33943360|A/cattle/USA/25-015080-001/2025||...
7957  >SRR33943301|A/chicken/USA/25-016837-002/2025|...
7958  >SRR33943302|A/chicken/USA/25-016837-001/2025|...

[7959 rows x 53 columns]

## Make FASTA files

In [ ]:
# Get information to create the fasta files

fasta_folder = originals + "avian-influenza/fasta/"

os.chdir(fasta_folder)

segments = ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]
pairs = []
fasta_files = {}

for genotype in genotypes: # ["B3.13", "D1.1"]:
    for segment in segments:
        pair = genotype + "_" + segment
        pairs.append(pair)

for pair in pairs:
    fasta_files[pair] = [] # List to hold fasta files

for run in metadata["Run"].values: # For each run 
    for dirpath, dirs, files in os.walk(fasta_folder): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            # print(file_name)
            if run in file_name: # Note that there will be ~8 files total with that run name
                # Make a fasta file and put it in the list
                with open(file_name) as f:
                    lines = f.readlines()
                    sequence = lines[1] 
                    # Each run/segment pair has one sequence -- it's placed into a file with other run/segment pairs with the same segment and genotype
                    header = metadata[metadata["Run"] == run].loc[:, "Name"].values[0]
                    genotype = metadata[metadata["Run"] == run].loc[:, "Genotype"].values[0]
                    # print(header)
                    # print(genotype)
                    # break 
                    segment = file_name.split("_")[-2]
                    # Find the pair that corresponds to 
                    pair_name = genotype + "_" + segment
                    this_specific_fasta = []
                    for pair in pairs:
                        # print(pair)
                        # print(pair_name)
                        if pair_name == pair:
                            this_specific_fasta.append(header)
                            this_specific_fasta.append(sequence)
                            fasta_files[pair].append(this_specific_fasta)
                f.close()
        break

In [ ]:
# print(fasta_files.keys())

In [ ]:
# Create fasta files 

# os.chdir(complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/")
os.chdir(originals + "complete/")
names = []
for pair in fasta_files.keys():
    # output_path = complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/" + pair + "_andersen_updated_" + update_date + ".fasta" 
    output_path = originals + "complete/" + pair + "_" + date_range + "_andersen_updated.fasta"

    output_file = open(output_path, "w")
    for item in fasta_files[pair]:
        # for item in item:
        # item = fasta_files[pair]
        try:
            name = str(item[0].values[0]) # See if this is one we didn't have a collection date for
        except:
            name = str(item[0])
        print(name)
        names.append(name)
        # First is header, second is sequence
        # print(value)
        output_file.write(name + "\n")
        output_file.write(item[1])
    output_file.close()

print(len(names)/8)

>SRR29740415|A/red-tailed hawk/USA: Kittery, ME/24-007611-001/2023||USA: Kittery, ME|2023-12-29|avian|A2
>SRR29740446|A/sanderling/USA: Dennis, MA/23-015884-008/2023||USA: Dennis, MA|2023-02-21|avian|A2
>SRR29740465|A/canada goose/USA: Wellfleet, MA/24-004865-021/2024||USA: Wellfleet, MA|2024-01-23|avian|A2
>SRR29740479|A/red-tailed hawk/USA: Centerville, MA/23-015884-005/2023||USA: Centerville, MA|2023-02-11|avian|A2
>SRR29740484|A/canada goose/USA: South Boston, MA/24-004865-002/2024||USA-SC|2024-01-31|avian|A2
>SRR29740495|A/turkey vulture/USA: Tiverton, RI/24-014130-005/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR29740497|A/turkey vulture/USA: Tiverton, RI/24-014130-004/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR32499025|A/wood duck/USA/24-008552-015/2024||USA|2024|avian|A2
>SRR29740415|A/red-tailed hawk/USA: Kittery, ME/24-007611-001/2023||USA: Kittery, ME|2023-12-29|avian|A2
>SRR29740446|A/sanderling/USA: Dennis, MA/23-015884-008/2023||USA: Dennis, MA|2023-02-21|avian|A2
>SRR29740465|A/canada goose/USA: Wellfleet, MA/24-004865-021/2024||USA: Wellfleet, MA|2024-01-23|avian|A2
>SRR29740479|A/red-tailed hawk/USA: Centerville, MA/23-015884-005/2023||USA: Centerville, MA|2023-02-11|avian|A2
>SRR29740484|A/canada goose/USA: South Boston, MA/24-004865-002/2024||USA-SC|2024-01-31|avian|A2
>SRR29740495|A/turkey vulture/USA: Tiverton, RI/24-014130-005/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR29740497|A/turkey vulture/USA: Tiverton, RI/24-014130-004/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR32499025|A/wood duck/USA/24-008552-015/2024||USA|2024|avian|A2
>SRR29740415|A/red-tailed hawk/USA: Kittery, ME/24-007611-001/2023||USA: Kittery, ME|2023-12-29|avian|A2
>SRR29740446|A/sanderling/USA: Dennis, MA/23-015884-008/2023||USA: Dennis, MA|2023-02-21|avian|A2
>SRR29740465|A/canada goose/USA: Wellfleet, MA/24-004865-021/2024||USA: Wellfleet, MA|2024-01-23|avian|A2
>SRR29740479|A/red-tailed hawk/USA: Centerville, MA/23-015884-005/2023||USA: Centerville, MA|2023-02-11|avian|A2
>SRR29740484|A/canada goose/USA: South Boston, MA/24-004865-002/2024||USA-SC|2024-01-31|avian|A2
>SRR29740495|A/turkey vulture/USA: Tiverton, RI/24-014130-005/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR29740497|A/turkey vulture/USA: Tiverton, RI/24-014130-004/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR32499025|A/wood duck/USA/24-008552-015/2024||USA|2024|avian|A2
>SRR29740415|A/red-tailed hawk/USA: Kittery, ME/24-007611-001/2023||USA: Kittery, ME|2023-12-29|avian|A2
>SRR29740446|A/sanderling/USA: Dennis, MA/23-015884-008/2023||USA: Dennis, MA|2023-02-21|avian|A2
>SRR29740465|A/canada goose/USA: Wellfleet, MA/24-004865-021/2024||USA: Wellfleet, MA|2024-01-23|avian|A2
>SRR29740479|A/red-tailed hawk/USA: Centerville, MA/23-015884-005/2023||USA: Centerville, MA|2023-02-11|avian|A2
>SRR29740484|A/canada goose/USA: South Boston, MA/24-004865-002/2024||USA-SC|2024-01-31|avian|A2
>SRR29740495|A/turkey vulture/USA: Tiverton, RI/24-014130-005/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR29740497|A/turkey vulture/USA: Tiverton, RI/24-014130-004/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR32499025|A/wood duck/USA/24-008552-015/2024||USA|2024|avian|A2
>SRR29740415|A/red-tailed hawk/USA: Kittery, ME/24-007611-001/2023||USA: Kittery, ME|2023-12-29|avian|A2
>SRR29740446|A/sanderling/USA: Dennis, MA/23-015884-008/2023||USA: Dennis, MA|2023-02-21|avian|A2
>SRR29740465|A/canada goose/USA: Wellfleet, MA/24-004865-021/2024||USA: Wellfleet, MA|2024-01-23|avian|A2
>SRR29740479|A/red-tailed hawk/USA: Centerville, MA/23-015884-005/2023||USA: Centerville, MA|2023-02-11|avian|A2
>SRR29740484|A/canada goose/USA: South Boston, MA/24-004865-002/2024||USA-SC|2024-01-31|avian|A2
>SRR29740495|A/turkey vulture/USA: Tiverton, RI/24-014130-005/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR29740497|A/turkey vulture/USA: Tiverton, RI/24-014130-004/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR32499025|A/wood duck/USA/24-008552-015/2024||USA|2024|avian|A2
>SRR29740415|A/red-tailed hawk/USA: Kittery, ME/24-007611-001/2023||USA: Kittery, ME|2023-12-29|avian|A2
>SRR29740446|A/sanderling/USA: Dennis, MA/23-015884-008/2023||USA: Dennis, MA|2023-02-21|avian|A2
>SRR29740465|A/canada goose/USA: Wellfleet, MA/24-004865-021/2024||USA: Wellfleet, MA|2024-01-23|avian|A2
>SRR29740479|A/red-tailed hawk/USA: Centerville, MA/23-015884-005/2023||USA: Centerville, MA|2023-02-11|avian|A2
>SRR29740484|A/canada goose/USA: South Boston, MA/24-004865-002/2024||USA-SC|2024-01-31|avian|A2
>SRR29740495|A/turkey vulture/USA: Tiverton, RI/24-014130-005/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR29740497|A/turkey vulture/USA: Tiverton, RI/24-014130-004/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR32499025|A/wood duck/USA/24-008552-015/2024||USA|2024|avian|A2
>SRR29740415|A/red-tailed hawk/USA: Kittery, ME/24-007611-001/2023||USA: Kittery, ME|2023-12-29|avian|A2
>SRR29740446|A/sanderling/USA: Dennis, MA/23-015884-008/2023||USA: Dennis, MA|2023-02-21|avian|A2
>SRR29740465|A/canada goose/USA: Wellfleet, MA/24-004865-021/2024||USA: Wellfleet, MA|2024-01-23|avian|A2
>SRR29740479|A/red-tailed hawk/USA: Centerville, MA/23-015884-005/2023||USA: Centerville, MA|2023-02-11|avian|A2
>SRR29740484|A/canada goose/USA: South Boston, MA/24-004865-002/2024||USA-SC|2024-01-31|avian|A2
>SRR29740495|A/turkey vulture/USA: Tiverton, RI/24-014130-005/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR29740497|A/turkey vulture/USA: Tiverton, RI/24-014130-004/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR32499025|A/wood duck/USA/24-008552-015/2024||USA|2024|avian|A2
>SRR29740415|A/red-tailed hawk/USA: Kittery, ME/24-007611-001/2023||USA: Kittery, ME|2023-12-29|avian|A2
>SRR29740446|A/sanderling/USA: Dennis, MA/23-015884-008/2023||USA: Dennis, MA|2023-02-21|avian|A2
>SRR29740465|A/canada goose/USA: Wellfleet, MA/24-004865-021/2024||USA: Wellfleet, MA|2024-01-23|avian|A2
>SRR29740479|A/red-tailed hawk/USA: Centerville, MA/23-015884-005/2023||USA: Centerville, MA|2023-02-11|avian|A2
>SRR29740484|A/canada goose/USA: South Boston, MA/24-004865-002/2024||USA-SC|2024-01-31|avian|A2
>SRR29740495|A/turkey vulture/USA: Tiverton, RI/24-014130-005/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR29740497|A/turkey vulture/USA: Tiverton, RI/24-014130-004/2024||USA: Tiverton, RI|2024-04-19|avian|A2
>SRR32499025|A/wood duck/USA/24-008552-015/2024||USA|2024|avian|A2
>SRR31597182|A/dove/USA/24-033876-005/2024|H5N1|USA|2024|avian|A3
>SRR31597183|A/duck/USA/24-033876-004/2024|H5N1|USA|2024|avian|A3
>SRR31597184|A/goose/USA/24-033876-003/2024|H5N1|USA|2024|avian|A3
>SRR31597185|A/duck/USA/24-033876-002/2024|H5N1|USA|2024|avian|A3
>SRR32254436|A/bald eagle/USA/25-000778-001/2025||USA|2025|avian|A3
>SRR32254442|A/red-tailed hawk/USA/25-001425-001/2025||USA|2025|avian|A3
>SRR32226680|A/bald eagle/USA/25-001479-002/2025|H5N1|USA|2025|avian|A3
>SRR32226682|A/canada goose/USA/25-000616-011/2025|H5N1|USA|2025|avian|A3
>SRR32226693|A/fox/USA/25-000628-001/2025|H5N1|USA|2025|other_mammal|A3
>SRR32125550|A/chicken/USA/25-000537-002/2025|H5N1|USA|2025|avian|A3
>SRR32125551|A/chicken/USA/25-000537-001/2025|H5N1|USA|2025|avian|A3
>SRR32125552|A/chicken/USA/25-000536-002/2025|H5N1|USA|2025|avian|A3
>SRR32125553|A/chicken/USA/25-000536-001/2025|H5N1|USA|2025|avian|A3
>SRR32125577|A/chicken/USA/25-000282-001/2025|H5N1|USA|2025|avian|A3
>SRR32006895|A/chicken/USA/24-038841-001/2024|Influenza A virus|USA|2024|avian|A3
>SRR32006901|A/pheasant/USA/24-039001-001/2024|Influenza A virus|USA|2024|avian|A3
>SRR31959929|A/chicken/USA/24-038661-001/2024|H5N1|USA|2024|avian|A3
>SRR31959962|A/guineafowl/USA/24-038546-002/2024|H5N1|USA|2024|avian|A3
>SRR31959963|A/chicken/USA/24-038546-001/2024|H5N1|USA|2024|avian|A3
>SRR31959995|A/guineafowl/USA/24-038441-003/2024|H5N1|USA|2024|avian|A3
>SRR31959996|A/chicken/USA/24-038441-002/2024|H5N1|USA|2024|avian|A3
>SRR31914374|A/chicken/USA/24-035148-001/2024|H5N1|USA|2024|avian|A3
>SRR31914377|A/duck/USA/24-034987-010/2024|H5N1|USA|2024|avian|A3
>SRR31914378|A/duck/USA/24-034987-008/2024|H5N1|USA|2024|avian|A3
>SRR31914383|A/duck/USA/24-034987-005/2024|H5N1|USA|2024|avian|A3
>SRR31914394|A/duck/USA/24-034987-004/2024|H5N1|USA|2024|avian|A3
>SRR31914405|A/duck/USA/24-034987-002/2024|H5N1|USA|2024|avian|A3
>SRR31914415|A/chicken/USA/24-035148-002/2024|H5N1|USA|2024|avian|A3
>SRR31914416|A/duck/USA/24-034986-001/2024|H5N1|USA|2024|avian|A3
>SRR31914417|A/duck/USA/24-034985-001/2024|H5N1|USA|2024|avian|A3
>SRR31820730|A/turkey/USA/24-036503-001/2024|H5N1|USA|2024|avian|A3
>SRR31820764|A/cat/USA/24-036601-001/2024|H5N1|USA|2024|feline|A3
>SRR31820787|A/turkey/USA/24-036503-002/2024|H5N1|USA|2024|avian|A3
>SRR31596871|A/chicken/USA/24-034633-002/2024|H5N1|USA|2024|avian|A3
>SRR31596872|A/chicken/USA/24-034633-001/2024|H5N1|USA|2024|avian|A3
>SRR31596876|A/pheasant/USA/24-034185-004/2024|H5N1|USA|2024|avian|A3
>SRR31596877|A/pheasant/USA/24-034185-003/2024|H5N1|USA|2024|avian|A3
>SRR31596878|A/pheasant/USA/24-034185-002/2024|H5N1|USA|2024|avian|A3
>SRR31596879|A/pheasant/USA/24-034185-001/2024|H5N1|USA|2024|avian|A3
>SRR31596886|A/duck/USA/24-033969-003/2024|H5N1|USA|2024|avian|A3
>SRR31596887|A/guinea fowl/USA/24-033969-002/2024|H5N1|USA|2024|avian|A3
>SRR31596888|A/emu/USA/24-033969-001/2024|H5N1|USA|2024|avian|A3
>SRR31596889|A/duck/USA/24-033968-002/2024|H5N1|USA|2024|avian|A3
>SRR31596890|A/duck/USA/24-033968-001/2024|H5N1|USA|2024|avian|A3
>SRR32416333|A/gadwall/USA/25-003031-003/2025||USA|2025|avian|A3
>SRR32416382|A/western gull/USA/25-003273-006/2025||USA|2025|avian|A3
>SRR32416388|A/turkey vulture/USA/25-003487-002/2025||USA|2025|avian|A3
>SRR32416418|A/mallard/USA/25-003141-007/2025||USA|2025|avian|A3
>SRR32416422|A/mallard/USA/25-003141-002/2025||USA|2025|avian|A3
>SRR32416437|A/house mouse/USA/25-003474-005/2025||USA|2025|other_mammal|A3
>SRR32416446|A/red-tailed hawk/USA/25-003273-004/2025||USA|2025|avian|A3
>SRR32416455|A/red-tailed hawk/USA/25-002203-001/2025||USA|2025|avian|A3
>SRR32416476|A/bald eagle/USA/25-003067-004/2025||USA|2025|avian|A3
>SRR32513266|A/mallard/USA/25-003141-009/2025||USA|2025|avian|A3
>SRR32513267|A/mallard/USA/25-003141-008/2025||USA|2025|avian|A3
>SRR32512613|A/bald eagle/USA/25-004135-002/2025||USA|2025|avian|A3
>SRR32512672|A/american wigeon/USA/25-004135-009/2025||USA|2025|avian|A3
>SRR32654066|A/mallard/USA/25-002663-034/2025||USA|2025|avian|A3
>SRR32654068|A/mallard/USA/25-002663-032/2025||USA|2025|avian|A3
>SRR32654069|A/mallard/USA/25-002663-031/2025||USA|2025|avian|A3
>SRR32654070|A/mallard/USA/25-002663-030/2025||USA|2025|avian|A3
>SRR32654072|A/mallard/USA/25-002663-026/2025||USA|2025|avian|A3
>SRR32654078|A/mallard/USA/25-002663-014/2025||USA|2025|avian|A3
>SRR32654079|A/mallard/USA/25-002663-013/2025||USA|2025|avian|A3
>SRR32654080|A/mallard/USA/25-002663-012/2025||USA|2025|avian|A3
>SRR32654081|A/mallard/USA/25-002663-011/2025||USA|2025|avian|A3
>SRR32654082|A/mallard/USA/25-002663-010/2025||USA|2025|avian|A3
>SRR32654083|A/mallard/USA/25-002663-008/2025||USA|2025|avian|A3
>SRR32654084|A/mallard/USA/25-002663-007/2025||USA|2025|avian|A3
>SRR32654086|A/mallard/USA/25-002663-006/2025||USA|2025|avian|A3
>SRR32654087|A/mallard/USA/25-002663-005/2025||USA|2025|avian|A3
>SRR32654088|A/mallard/USA/25-002663-004/2025||USA|2025|avian|A3
>SRR32654089|A/mallard/USA/25-002663-001/2025||USA|2025|avian|A3
>SRR32653641|A/bald eagle/USA/25-005228-001/2025||USA|2025|avian|A3
>SRR32804610|A/fox/USA/25-004517-001/2025||USA|2025|other_mammal|A3
>SRR32868867|A/grackle/USA/25-009017-003/2025||USA|2025|avian|A3
>SRR32974039|A/bald eagle/USA/25-008364-001/2025||USA|2025|avian|A3
>SRR32974110|A/bald eagle/USA/25-009337-001/2025||USA|2025|avian|A3
>SRR33125022|A/crow/USA/25-004431-001/2025||USA|2025|avian|A3
>SRR33125049|A/mallard/USA/25-005882-009/2025||USA|2025|avian|A3
>SRR33125051|A/bald eagle/USA/25-006076-002/2025||USA|2025|avian|A3
>SRR33125053|A/mallard/USA/25-005882-006/2025||USA|2025|avian|A3
>SRR33125055|A/mallard/USA/25-005882-003/2025||USA|2025|avian|A3
>SRR33125062|A/bald eagle/USA/25-006076-001/2025||USA|2025|avian|A3
>SRR33125127|A/red-tailed hawk/USA/25-004415-008/2025||USA|2025|avian|A3
>SRR33319053|A/great horned owl/USA/25-011423-001/2025||USA|2025|avian|A3
>SRR33319074|A/american crow/USA/25-011667-003/2025||USA|2025|avian|A3
>SRR33319075|A/american crow/USA/25-011667-002/2025||USA|2025|avian|A3
>SRR33508776|A/red-tailed hawk/USA/25-010511-002/2025||USA|2025|avian|A3
>SRR33508777|A/red-tailed hawk/USA/25-010511-001/2025||USA|2025|avian|A3
>SRR33508778|A/common raven/USA/25-010464-001/2025||USA|2025|avian|A3
>SRR33508834|A/barred owl/USA/25-005028-002/2025||USA|2025|avian|A3
>SRR33508835|A/american crow/USA/25-005028-001/2025||USA|2025|avian|A3
>SRR33476775|A/trumpeter swan/USA/25-011816-002/2025||USA|2025|avian|A3
>SRR33565207|A/turkey vulture/USA/25-013489-001/2025||USA|2025|avian|A3
>SRR33682325|A/hawk/USA/25-014764-001/2025||USA|2025|avian|A3
>SRR31597182|A/dove/USA/24-033876-005/2024|H5N1|USA|2024|avian|A3
>SRR31597183|A/duck/USA/24-033876-004/2024|H5N1|USA|2024|avian|A3
>SRR31597184|A/goose/USA/24-033876-003/2024|H5N1|USA|2024|avian|A3
>SRR31597185|A/duck/USA/24-033876-002/2024|H5N1|USA|2024|avian|A3
>SRR32254436|A/bald eagle/USA/25-000778-001/2025||USA|2025|avian|A3
>SRR32254442|A/red-tailed hawk/USA/25-001425-001/2025||USA|2025|avian|A3
>SRR32226680|A/bald eagle/USA/25-001479-002/2025|H5N1|USA|2025|avian|A3
>SRR32226682|A/canada goose/USA/25-000616-011/2025|H5N1|USA|2025|avian|A3
>SRR32226693|A/fox/USA/25-000628-001/2025|H5N1|USA|2025|other_mammal|A3
>SRR32125550|A/chicken/USA/25-000537-002/2025|H5N1|USA|2025|avian|A3
>SRR32125551|A/chicken/USA/25-000537-001/2025|H5N1|USA|2025|avian|A3
>SRR32125552|A/chicken/USA/25-000536-002/2025|H5N1|USA|2025|avian|A3
>SRR32125553|A/chicken/USA/25-000536-001/2025|H5N1|USA|2025|avian|A3
>SRR32125577|A/chicken/USA/25-000282-001/2025|H5N1|USA|2025|avian|A3
>SRR32006895|A/chicken/USA/24-038841-001/2024|Influenza A virus|USA|2024|avian|A3
>SRR32006901|A/pheasant/USA/24-039001-001/2024|Influenza A virus|USA|2024|avian|A3
>SRR31959929|A/chicken/USA/24-038661-001/2024|H5N1|USA|2024|avian|A3
>SRR31959962|A/guineafowl/USA/24-038546-002/2024|H5N1|USA|2024|avian|A3
>SRR31959963|A/chicken/USA/24-038546-001/2024|H5N1|USA|2024|avian|A3
>SRR31959995|A/guineafowl/USA/24-038441-003/2024|H5N1|USA|2024|avian|A3
>SRR31959996|A/chicken/USA/24-038441-002/2024|H5N1|USA|2024|avian|A3
>SRR31914374|A/chicken/USA/24-035148-001/2024|H5N1|USA|2024|avian|A3
>SRR31914377|A/duck/USA/24-034987-010/2024|H5N1|USA|2024|avian|A3
>SRR31914378|A/duck/USA/24-034987-008/2024|H5N1|USA|2024|avian|A3
>SRR31914383|A/duck/USA/24-034987-005/2024|H5N1|USA|2024|avian|A3
>SRR31914394|A/duck/USA/24-034987-004/2024|H5N1|USA|2024|avian|A3
>SRR31914405|A/duck/USA/24-034987-002/2024|H5N1|USA|2024|avian|A3
>SRR31914415|A/chicken/USA/24-035148-002/2024|H5N1|USA|2024|avian|A3
>SRR31914416|A/duck/USA/24-034986-001/2024|H5N1|USA|2024|avian|A3
>SRR31914417|A/duck/USA/24-034985-001/2024|H5N1|USA|2024|avian|A3
>SRR31820730|A/turkey/USA/24-036503-001/2024|H5N1|USA|2024|avian|A3
>SRR31820764|A/cat/USA/24-036601-001/2024|H5N1|USA|2024|feline|A3
>SRR31820787|A/turkey/USA/24-036503-002/2024|H5N1|USA|2024|avian|A3
>SRR31596871|A/chicken/USA/24-034633-002/2024|H5N1|USA|2024|avian|A3
>SRR31596872|A/chicken/USA/24-034633-001/2024|H5N1|USA|2024|avian|A3
>SRR31596876|A/pheasant/USA/24-034185-004/2024|H5N1|USA|2024|avian|A3
>SRR31596877|A/pheasant/USA/24-034185-003/2024|H5N1|USA|2024|avian|A3
>SRR31596878|A/pheasant/USA/24-034185-002/2024|H5N1|USA|2024|avian|A3
>SRR31596879|A/pheasant/USA/24-034185-001/2024|H5N1|USA|2024|avian|A3
>SRR31596886|A/duck/USA/24-033969-003/2024|H5N1|USA|2024|avian|A3
>SRR31596887|A/guinea fowl/USA/24-033969-002/2024|H5N1|USA|2024|avian|A3
>SRR31596888|A/emu/USA/24-033969-001/2024|H5N1|USA|2024|avian|A3
>SRR31596889|A/duck/USA/24-033968-002/2024|H5N1|USA|2024|avian|A3
>SRR31596890|A/duck/USA/24-033968-001/2024|H5N1|USA|2024|avian|A3
>SRR32416333|A/gadwall/USA/25-003031-003/2025||USA|2025|avian|A3
>SRR32416382|A/western gull/USA/25-003273-006/2025||USA|2025|avian|A3
>SRR32416388|A/turkey vulture/USA/25-003487-002/2025||USA|2025|avian|A3
>SRR32416418|A/mallard/USA/25-003141-007/2025||USA|2025|avian|A3
>SRR32416422|A/mallard/USA/25-003141-002/2025||USA|2025|avian|A3
>SRR32416437|A/house mouse/USA/25-003474-005/2025||USA|2025|other_mammal|A3
>SRR32416446|A/red-tailed hawk/USA/25-003273-004/2025||USA|2025|avian|A3
>SRR32416455|A/red-tailed hawk/USA/25-002203-001/2025||USA|2025|avian|A3
>SRR32416476|A/bald eagle/USA/25-003067-004/2025||USA|2025|avian|A3
>SRR32513266|A/mallard/USA/25-003141-009/2025||USA|2025|avian|A3
>SRR32513267|A/mallard/USA/25-003141-008/2025||USA|2025|avian|A3
>SRR32512613|A/bald eagle/USA/25-004135-002/2025||USA|2025|avian|A3
>SRR32512672|A/american wigeon/USA/25-004135-009/2025||USA|2025|avian|A3
>SRR32654066|A/mallard/USA/25-002663-034/2025||USA|2025|avian|A3
>SRR32654068|A/mallard/USA/25-002663-032/2025||USA|2025|avian|A3
>SRR32654069|A/mallard/USA/25-002663-031/2025||USA|2025|avian|A3
>SRR32654070|A/mallard/USA/25-002663-030/2025||USA|2025|avian|A3
>SRR32654072|A/mallard/USA/25-002663-026/2025||USA|2025|avian|A3
>SRR32654078|A/mallard/USA/25-002663-014/2025||USA|2025|avian|A3
>SRR32654079|A/mallard/USA/25-002663-013/2025||USA|2025|avian|A3
>SRR32654080|A/mallard/USA/25-002663-012/2025||USA|2025|avian|A3
>SRR32654081|A/mallard/USA/25-002663-011/2025||USA|2025|avian|A3
>SRR32654082|A/mallard/USA/25-002663-010/2025||USA|2025|avian|A3
>SRR32654083|A/mallard/USA/25-002663-008/2025||USA|2025|avian|A3
>SRR32654084|A/mallard/USA/25-002663-007/2025||USA|2025|avian|A3
>SRR32654086|A/mallard/USA/25-002663-006/2025||USA|2025|avian|A3
>SRR32654087|A/mallard/USA/25-002663-005/2025||USA|2025|avian|A3
>SRR32654088|A/mallard/USA/25-002663-004/2025||USA|2025|avian|A3
>SRR32654089|A/mallard/USA/25-002663-001/2025||USA|2025|avian|A3
>SRR32653641|A/bald eagle/USA/25-005228-001/2025||USA|2025|avian|A3
>SRR32804610|A/fox/USA/25-004517-001/2025||USA|2025|other_mammal|A3
>SRR32868867|A/grackle/USA/25-009017-003/2025||USA|2025|avian|A3
>SRR32974039|A/bald eagle/USA/25-008364-001/2025||USA|2025|avian|A3
>SRR32974110|A/bald eagle/USA/25-009337-001/2025||USA|2025|avian|A3
>SRR33125022|A/crow/USA/25-004431-001/2025||USA|2025|avian|A3
>SRR33125049|A/mallard/USA/25-005882-009/2025||USA|2025|avian|A3
>SRR33125051|A/bald eagle/USA/25-006076-002/2025||USA|2025|avian|A3
>SRR33125053|A/mallard/USA/25-005882-006/2025||USA|2025|avian|A3
>SRR33125055|A/mallard/USA/25-005882-003/2025||USA|2025|avian|A3
>SRR33125062|A/bald eagle/USA/25-006076-001/2025||USA|2025|avian|A3
>SRR33125127|A/red-tailed hawk/USA/25-004415-008/2025||USA|2025|avian|A3
>SRR33319053|A/great horned owl/USA/25-011423-001/2025||USA|2025|avian|A3
>SRR33319074|A/american crow/USA/25-011667-003/2025||USA|2025|avian|A3
>SRR33319075|A/american crow/USA/25-011667-002/2025||USA|2025|avian|A3
>SRR33508776|A/red-tailed hawk/USA/25-010511-002/2025||USA|2025|avian|A3
>SRR33508777|A/red-tailed hawk/USA/25-010511-001/2025||USA|2025|avian|A3
>SRR33508778|A/common raven/USA/25-010464-001/2025||USA|2025|avian|A3
>SRR33508834|A/barred owl/USA/25-005028-002/2025||USA|2025|avian|A3
>SRR33508835|A/american crow/USA/25-005028-001/2025||USA|2025|avian|A3
>SRR33476775|A/trumpeter swan/USA/25-011816-002/2025||USA|2025|avian|A3
>SRR33565207|A/turkey vulture/USA/25-013489-001/2025||USA|2025|avian|A3
>SRR33682325|A/hawk/USA/25-014764-001/2025||USA|2025|avian|A3
>SRR31597182|A/dove/USA/24-033876-005/2024|H5N1|USA|2024|avian|A3
>SRR31597183|A/duck/USA/24-033876-004/2024|H5N1|USA|2024|avian|A3
>SRR31597184|A/goose/USA/24-033876-003/2024|H5N1|USA|2024|avian|A3
>SRR31597185|A/duck/USA/24-033876-002/2024|H5N1|USA|2024|avian|A3
>SRR32254436|A/bald eagle/USA/25-000778-001/2025||USA|2025|avian|A3
>SRR32254442|A/red-tailed hawk/USA/25-001425-001/2025||USA|2025|avian|A3
>SRR32226680|A/bald eagle/USA/25-001479-002/2025|H5N1|USA|2025|avian|A3

## De-Duplication

In [ ]:
# De-duplication 

# gisaid = downloads + "GISAID/complete/all_genotypes/11-01-2021--06-13-2025_all_genotypes_Antarctica_North_America_South_America/"
    # gisaid = downloads + "Cats/Datasets/GISAID/"

# for genotype in genotypes:

    # gisaid = downloads + "GISAID/complete/" + genotype.replace(".", "_") + "/" + date_range + "_" + genotype.replace(".", "_") + "_Antarctica_North_America_South_America/"
    
gisaid = downloads + "GISAID/complete/" + date_range + "_all_genotypes_Antarctica_North_America_South_America/"

os.chdir(gisaid)

# Gisaid 
dfs_gisaid_list = []
dfs_gisaid = create_dataframes(gisaid)
dfs_gisaid_list.append(dfs_gisaid)

# dfs_gisaid = {}
# for df_gisaid in dfs_gisaid_list:
#     dfs_gisaid = dfs_gisaid | df_gisaid
# # dfs_gisaid2 = create_dataframes(gisaid2)

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2

In [ ]:
# Do the same with Andersen 

# dfs_andersen = create_dataframes(complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/")
dfs_andersen = create_dataframes(originals + "complete/")

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
D2.1_HA
D2.1_MP
D2.1_NA
D2.1_NP
D2.1_NS
D2.1_PA
D2.1_PB1
D2.1_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor101_HA
Minor101_MP
Minor101_NA
Minor101_NP
Minor101_NS
Minor101_PA
Minor101_PB1
Minor101_PB2
Minor102_HA
Minor102_MP
Minor102_NA
Minor102_NP
Minor102_NS
Minor102_PA
Minor102_PB1
Minor102_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor104_HA
Minor104_MP
Minor104_NA
Minor104_NP
Minor104_NS
Minor104_PA
Minor104_PB1
Minor104_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor106_HA
Minor106_MP
Minor106_NA
Minor106_NP
Minor106_NS
Minor106_PA
Minor106_PB1
Minor106_PB2
Minor10_HA
Minor10_MP
Minor10_NA
Minor10_NP
Minor10_NS
Minor10_PA
Minor10_PB1
Minor10_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor16_HA
Minor16_MP
Minor16_NA
Minor16_NP
Minor16_NS
Minor16_PA
Minor16_PB1
Minor16_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor18_HA
Minor18_MP
Minor18_NA
Minor18_NP
Minor18_NS
Minor18_PA
Minor18_PB1
Minor18_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor24_HA
Minor24_MP
Minor24_NA
Minor24_NP
Minor24_NS
Minor24_PA
Minor24_PB1
Minor24_PB2
Minor25_HA
Minor25_MP
Minor25_NA
Minor25_NP
Minor25_NS
Minor25_PA
Minor25_PB1
Minor25_PB2
Minor26_HA
Minor26_MP
Minor26_NA
Minor26_NP
Minor26_NS
Minor26_PA
Minor26_PB1
Minor26_PB2
Minor27_HA
Minor27_MP
Minor27_NA
Minor27_NP
Minor27_NS
Minor27_PA
Minor27_PB1
Minor27_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor29_HA
Minor29_MP
Minor29_NA
Minor29_NP
Minor29_NS
Minor29_PA
Minor29_PB1
Minor29_PB2
Minor30_HA
Minor30_MP
Minor30_NA
Minor30_NP
Minor30_NS
Minor30_PA
Minor30_PB1
Minor30_PB2
Minor31_HA
Minor31_MP
Minor31_NA
Minor31_NP
Minor31_NS
Minor31_PA
Minor31_PB1
Minor31_PB2
Minor32_HA
Minor32_MP
Minor32_NA
Minor32_NP
Minor32_NS
Minor32_PA
Minor32_PB1
Minor32_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor37_HA
Minor37_MP
Minor37_NA
Minor37_NP
Minor37_NS
Minor37_PA
Minor37_PB1
Minor37_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor39_HA
Minor39_MP
Minor39_NA
Minor39_NP
Minor39_NS
Minor39_PA
Minor39_PB1
Minor39_PB2
Minor40_HA
Minor40_MP
Minor40_NA
Minor40_NP
Minor40_NS
Minor40_PA
Minor40_PB1
Minor40_PB2
Minor41_HA
Minor41_MP
Minor41_NA
Minor41_NP
Minor41_NS
Minor41_PA
Minor41_PB1
Minor41_PB2
Minor42_HA
Minor42_MP
Minor42_NA
Minor42_NP
Minor42_NS
Minor42_PA
Minor42_PB1
Minor42_PB2
Minor43_HA
Minor43_MP
Minor43_NA
Minor43_NP
Minor43_NS
Minor43_PA
Minor43_PB1
Minor43_PB2
Minor44_HA
Minor44_MP
Minor44_NA
Minor44_NP
Minor44_NS
Minor44_PA
Minor44_PB1
Minor44_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor46_HA
Minor46_MP
Minor46_NA
Minor46_NP
Minor46_NS
Minor46_PA
Minor46_PB1
Minor46_PB2
Minor47_HA
Minor47_MP
Minor47_NA
Minor47_NP
Minor47_NS
Minor47_PA
Minor47_PB1
Minor47_PB2
Minor48_HA
Minor48_MP
Minor48_NA
Minor48_NP
Minor48_NS
Minor48_PA
Minor48_PB1
Minor48_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor52_HA
Minor52_MP
Minor52_NA
Minor52_NP
Minor52_NS
Minor52_PA
Minor52_PB1
Minor52_PB2
Minor53_HA
Minor53_MP
Minor53_NA
Minor53_NP
Minor53_NS
Minor53_PA
Minor53_PB1
Minor53_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor56_HA
Minor56_MP
Minor56_NA
Minor56_NP
Minor56_NS
Minor56_PA
Minor56_PB1
Minor56_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor67_HA
Minor67_MP
Minor67_NA
Minor67_NP
Minor67_NS
Minor67_PA
Minor67_PB1
Minor67_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor71_HA
Minor71_MP
Minor71_NA
Minor71_NP
Minor71_NS
Minor71_PA
Minor71_PB1
Minor71_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor74_HA
Minor74_MP
Minor74_NA
Minor74_NP
Minor74_NS
Minor74_PA
Minor74_PB1
Minor74_PB2
Minor75_HA
Minor75_MP
Minor75_NA
Minor75_NP
Minor75_NS
Minor75_PA
Minor75_PB1
Minor75_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor78_HA
Minor78_MP
Minor78_NA
Minor78_NP
Minor78_NS
Minor78_PA
Minor78_PB1
Minor78_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor80_HA
Minor80_MP
Minor80_NA
Minor80_NP
Minor80_NS
Minor80_PA
Minor80_PB1
Minor80_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor82_HA
Minor82_MP
Minor82_NA
Minor82_NP
Minor82_NS
Minor82_PA
Minor82_PB1
Minor82_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor84_HA
Minor84_MP
Minor84_NA
Minor84_NP
Minor84_NS
Minor84_PA
Minor84_PB1
Minor84_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor92_HA
Minor92_MP
Minor92_NA
Minor92_NP
Minor92_NS
Minor92_PA
Minor92_PB1
Minor92_PB2
Minor93_HA
Minor93_MP
Minor93_NA
Minor93_NP
Minor93_NS
Minor93_PA
Minor93_PB1
Minor93_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor95_HA
Minor95_MP
Minor95_NA
Minor95_NP
Minor95_NS
Minor95_PA
Minor95_PB1
Minor95_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
Minor98_HA
Minor98_MP
Minor98_NA
Minor98_NP
Minor98_NS
Minor98_PA
Minor98_PB1
Minor98_PB2
Minor99_HA
Minor99_MP
Minor99_NA
Minor99_NP
Minor99_NS
Minor99_PA
Minor99_PB1
Minor99_PB2

In [ ]:
# os.chdir(downloads)
# dfs_gisaid["B3.13_HA"].to_csv

In [ ]:
for key in dfs_andersen.keys():
    dataframes = dfs_andersen[key]
    print(key)

print(dfs_andersen)

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
D2.1_HA
D2.1_MP
D2.1_NA
D2.1_NP
D2.1_NS
D2.1_PA
D2.1_PB1
D2.1_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor101_HA
Minor101_MP
Minor101_NA
Minor101_NP
Minor101_NS
Minor101_PA
Minor101_PB1
Minor101_PB2
Minor102_HA
Minor102_MP
Minor102_NA
Minor102_NP
Minor102_NS
Minor102_PA
Minor102_PB1
Minor102_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor104_HA
Minor104_MP
Minor104_NA
Minor104_NP
Minor104_NS
Minor104_PA
Minor104_PB1
Minor104_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor106_HA
Minor106_MP
Minor106_NA
Minor106_NP
Minor106_NS
Minor106_PA
Minor106_PB1
Minor106_PB2
Minor10_HA
Minor10_MP
Minor10_NA
Minor10_NP
Minor10_NS
Minor10_PA
Minor10_PB1
Minor10_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor16_HA
Minor16_MP
Minor16_NA
Minor16_NP
Minor16_NS
Minor16_PA
Minor16_PB1
Minor16_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor18_HA
Minor18_MP
Minor18_NA
Minor18_NP
Minor18_NS
Minor18_PA
Minor18_PB1
Minor18_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor24_HA
Minor24_MP
Minor24_NA
Minor24_NP
Minor24_NS
Minor24_PA
Minor24_PB1
Minor24_PB2
Minor25_HA
Minor25_MP
Minor25_NA
Minor25_NP
Minor25_NS
Minor25_PA
Minor25_PB1
Minor25_PB2
Minor26_HA
Minor26_MP
Minor26_NA
Minor26_NP
Minor26_NS
Minor26_PA
Minor26_PB1
Minor26_PB2
Minor27_HA
Minor27_MP
Minor27_NA
Minor27_NP
Minor27_NS
Minor27_PA
Minor27_PB1
Minor27_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor29_HA
Minor29_MP
Minor29_NA
Minor29_NP
Minor29_NS
Minor29_PA
Minor29_PB1
Minor29_PB2
Minor30_HA
Minor30_MP
Minor30_NA
Minor30_NP
Minor30_NS
Minor30_PA
Minor30_PB1
Minor30_PB2
Minor31_HA
Minor31_MP
Minor31_NA
Minor31_NP
Minor31_NS
Minor31_PA
Minor31_PB1
Minor31_PB2
Minor32_HA
Minor32_MP
Minor32_NA
Minor32_NP
Minor32_NS
Minor32_PA
Minor32_PB1
Minor32_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor37_HA
Minor37_MP
Minor37_NA
Minor37_NP
Minor37_NS
Minor37_PA
Minor37_PB1
Minor37_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor39_HA
Minor39_MP
Minor39_NA
Minor39_NP
Minor39_NS
Minor39_PA
Minor39_PB1
Minor39_PB2
Minor40_HA
Minor40_MP
Minor40_NA
Minor40_NP
Minor40_NS
Minor40_PA
Minor40_PB1
Minor40_PB2
Minor41_HA
Minor41_MP
Minor41_NA
Minor41_NP
Minor41_NS
Minor41_PA
Minor41_PB1
Minor41_PB2
Minor42_HA
Minor42_MP
Minor42_NA
Minor42_NP
Minor42_NS
Minor42_PA
Minor42_PB1
Minor42_PB2
Minor43_HA
Minor43_MP
Minor43_NA
Minor43_NP
Minor43_NS
Minor43_PA
Minor43_PB1
Minor43_PB2
Minor44_HA
Minor44_MP
Minor44_NA
Minor44_NP
Minor44_NS
Minor44_PA
Minor44_PB1
Minor44_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor46_HA
Minor46_MP
Minor46_NA
Minor46_NP
Minor46_NS
Minor46_PA
Minor46_PB1
Minor46_PB2
Minor47_HA
Minor47_MP
Minor47_NA
Minor47_NP
Minor47_NS
Minor47_PA
Minor47_PB1
Minor47_PB2
Minor48_HA
Minor48_MP
Minor48_NA
Minor48_NP
Minor48_NS
Minor48_PA
Minor48_PB1
Minor48_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor52_HA
Minor52_MP
Minor52_NA
Minor52_NP
Minor52_NS
Minor52_PA
Minor52_PB1
Minor52_PB2
Minor53_HA
Minor53_MP
Minor53_NA
Minor53_NP
Minor53_NS
Minor53_PA
Minor53_PB1
Minor53_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor56_HA
Minor56_MP
Minor56_NA
Minor56_NP
Minor56_NS
Minor56_PA
Minor56_PB1
Minor56_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor67_HA
Minor67_MP
Minor67_NA
Minor67_NP
Minor67_NS
Minor67_PA
Minor67_PB1
Minor67_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor71_HA
Minor71_MP
Minor71_NA
Minor71_NP
Minor71_NS
Minor71_PA
Minor71_PB1
Minor71_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor74_HA
Minor74_MP
Minor74_NA
Minor74_NP
Minor74_NS
Minor74_PA
Minor74_PB1
Minor74_PB2
Minor75_HA
Minor75_MP
Minor75_NA
Minor75_NP
Minor75_NS
Minor75_PA
Minor75_PB1
Minor75_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor78_HA
Minor78_MP
Minor78_NA
Minor78_NP
Minor78_NS
Minor78_PA
Minor78_PB1
Minor78_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor80_HA
Minor80_MP
Minor80_NA
Minor80_NP
Minor80_NS
Minor80_PA
Minor80_PB1
Minor80_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor82_HA
Minor82_MP
Minor82_NA
Minor82_NP
Minor82_NS
Minor82_PA
Minor82_PB1
Minor82_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor84_HA
Minor84_MP
Minor84_NA
Minor84_NP
Minor84_NS
Minor84_PA
Minor84_PB1
Minor84_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor92_HA
Minor92_MP
Minor92_NA
Minor92_NP
Minor92_NS
Minor92_PA
Minor92_PB1
Minor92_PB2
Minor93_HA
Minor93_MP
Minor93_NA
Minor93_NP
Minor93_NS
Minor93_PA
Minor93_PB1
Minor93_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor95_HA
Minor95_MP
Minor95_NA
Minor95_NP
Minor95_NS
Minor95_PA
Minor95_PB1
Minor95_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
Minor98_HA
Minor98_MP
Minor98_NA
Minor98_NP
Minor98_NS
Minor98_PA
Minor98_PB1
Minor98_PB2
Minor99_HA
Minor99_MP
Minor99_NA
Minor99_NP
Minor99_NS
Minor99_PA
Minor99_PB1
Minor99_PB2
defaultdict(<class 'list'>, {'A1_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_HA': [  isolate_partial                                        full_header  \
0      007611-001  >SRR29740415|A/red-tailed hawk/USA: Kittery, M...
1      015884-008  >SRR29740446|A/sanderling/USA: Dennis, MA/23-0...
2      004865-021  >SRR29740465|A/canada goose/USA: Wellfleet, MA...
3      015884-005  >SRR29740479|A/red-tailed hawk/USA: Centervill...
4      004865-002  >SRR29740484|A/canada goose/USA: South Boston,...
5      014130-005  >SRR29740495|A/turkey vulture/USA: Tiverton, R...
6      014130-004  >SRR29740497|A/turkey vulture/USA: Tiverton, R...
7      008552-015  >SRR32499025|A/wood duck/USA/24-008552-015/202...

                                            sequence
0  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
1  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
2  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
3  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
4  ATGGAGAACATAGTACTATTTCTTGCAATAGTTAGCCTTGTTAAAA...
5  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
6  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
7  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...  ], 'A2_MP': [  isolate_partial                                        full_header  \
0      007611-001  >SRR29740415|A/red-tailed hawk/USA: Kittery, M...
1      015884-008  >SRR29740446|A/sanderling/USA: Dennis, MA/23-0...
2      004865-021  >SRR29740465|A/canada goose/USA: Wellfleet, MA...
3      015884-005  >SRR29740479|A/red-tailed hawk/USA: Centervill...
4      004865-002  >SRR29740484|A/canada goose/USA: South Boston,...
5      014130-005  >SRR29740495|A/turkey vulture/USA: Tiverton, R...
6      014130-004  >SRR29740497|A/turkey vulture/USA: Tiverton, R...
7      008552-015  >SRR32499025|A/wood duck/USA/24-008552-015/202...

                                            sequence
0  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
5  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
6  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
7  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...  ], 'A2_NA': [  isolate_partial                                        full_header  \
0      007611-001  >SRR29740415|A/red-tailed hawk/USA: Kittery, M...
1      015884-008  >SRR29740446|A/sanderling/USA: Dennis, MA/23-0...
2      004865-021  >SRR29740465|A/canada goose/USA: Wellfleet, MA...
3      015884-005  >SRR29740479|A/red-tailed hawk/USA: Centervill...
4      004865-002  >SRR29740484|A/canada goose/USA: South Boston,...
5      014130-005  >SRR29740495|A/turkey vulture/USA: Tiverton, R...
6      014130-004  >SRR29740497|A/turkey vulture/USA: Tiverton, R...
7      008552-015  >SRR32499025|A/wood duck/USA/24-008552-015/202...

                                            sequence
0  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
1  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
2  ATGAATCCAAATCAAAAGATAACAACCATTGGGTCAATCTGTATGG...
3  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
4  ATGAATCCAAATCAAAAGATAACAACCATTGGGTCAATCTGTATGG...
5  ATGAATCCAAATCAAAAGATAACAACCATTGGGTCAATCTGTATGG...
6  ATGAATCCAAATCAAAAGATAACAACCATTGGGTCAATCTGTATGG...
7  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...  ], 'A2_NP': [  isolate_partial                                        full_header  \
0      007611-001  >SRR29740415|A/red-tailed hawk/USA: Kittery, M...
1      015884-008  >SRR29740446|A/sanderling/USA: Dennis, MA/23-0...
2      004865-021  >SRR29740465|A/canada goose/USA: Wellfleet, MA...
3      015884-005  >SRR29740479|A/red-tailed hawk/USA: Centervill...
4      004865-002  >SRR29740484|A/canada goose/USA: South Boston,...
5      014130-005  >SRR29740495|A/turkey vulture/USA: Tiverton, R...
6      014130-004  >SRR29740497|A/turkey vulture/USA: Tiverton, R...
7      008552-015  >SRR32499025|A/wood duck/USA/24-008552-015/202...

                                            sequence
0  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
1  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
2  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
3  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
4  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
5  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
6  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
7  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...  ], 'A2_NS': [  isolate_partial                                        full_header  \
0      007611-001  >SRR29740415|A/red-tailed hawk/USA: Kittery, M...
1      015884-008  >SRR29740446|A/sanderling/USA: Dennis, MA/23-0...
2      004865-021  >SRR29740465|A/canada goose/USA: Wellfleet, MA...
3      015884-005  >SRR29740479|A/red-tailed hawk/USA: Centervill...
4      004865-002  >SRR29740484|A/canada goose/USA: South Boston,...
5      014130-005  >SRR29740495|A/turkey vulture/USA: Tiverton, R...
6      014130-004  >SRR29740497|A/turkey vulture/USA: Tiverton, R...
7      008552-015  >SRR32499025|A/wood duck/USA/24-008552-015/202...

                                            sequence
0  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
1  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
2  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
3  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
4  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
5  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
6  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
7  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...  ], 'A2_PA': [  isolate_partial                                        full_header  \
0      007611-001  >SRR29740415|A/red-tailed hawk/USA: Kittery, M...
1      015884-008  >SRR29740446|A/sanderling/USA: Dennis, MA/23-0...
2      004865-021  >SRR29740465|A/canada goose/USA: Wellfleet, MA...
3      015884-005  >SRR29740479|A/red-tailed hawk/USA: Centervill...
4      004865-002  >SRR29740484|A/canada goose/USA: South Boston,...
5      014130-005  >SRR29740495|A/turkey vulture/USA: Tiverton, R...
6      014130-004  >SRR29740497|A/turkey vulture/USA: Tiverton, R...
7      008552-015  >SRR32499025|A/wood duck/USA/24-008552-015/202...

                                            sequence
0  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
1  ATGGAAGACTTTGTGCGACAATGTTTCAATCCAATGATTGTCGAGC...
2  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
3  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
4  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
5  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
6  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
7  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...  ], 'A2_PB1': [  isolate_partial                                        full_header  \
0      007611-001  >SRR29740415|A/red-tailed hawk/USA: Kittery, M...
1      015884-008  >SRR29740446|A/sanderling/USA: Dennis, MA/23-0...
2      004865-021  >SRR29740465|A/canada goose/USA: Wellfleet, MA...
3      015884-005  >SRR29740479|A/red-tailed hawk/USA: Centervill...
4      004865-002  >SRR29740484|A/canada goose/USA: South Boston,...
5      014130-005  >SRR29740495|A/turkey vulture/USA: Tiverton, R...
6      014130-004  >SRR29740497|A/turkey vulture/USA: Tiverton, R...
7      008552-015  >SRR32499025|A/wood duck/USA/24-008552-015/202...

                                            sequence
0  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAA...
1  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAA...
2  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAA...
3  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAA...
4  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAA...
5  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAA...
6  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAA...
7  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAA...  ], 'A2_PB2': [  isolate_partial                                        full_header  \
0      007611-001  >SRR29740415|A/red-tailed hawk/USA: Kittery, M...
1      015884-008  >SRR29740446|A/sanderling/USA: Dennis, MA/23-0...
2      004865-021  >SRR29740465|A/canada goose/USA: Wellfleet, MA...
3      015884-005  >SRR29740479|A/red-tailed hawk/USA: Centervill...
4      004865-002  >SRR29740484|A/canada goose/USA: South Boston,...
5      014130-005  >SRR29740495|A/turkey vulture/USA: Tiverton, R...
6      014130-004  >SRR29740497|A/turkey vulture/USA: Tiverton, R...
7      008552-015  >SRR32499025|A/wood duck/USA/24-008552-015/202...

                                            sequence
0  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...
1  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...
2  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...
3  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...
4  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...
5  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...
6  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...
7  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...  ], 'A3_HA': [   isolate_partial                                        full_header  \
0       033876-005  >SRR31597182|A/dove/USA/24-033876-005/2024|H5N...
1       033876-004  >SRR31597183|A/duck/USA/24-033876-004/2024|H5N...

In [ ]:
print(len(list(dfs_gisaid.keys())))
print(len(list(dfs_andersen.keys())))

632
968

In [ ]:
# Merge dataframes and drop duplicates

full_dfs = defaultdict(list)
# same = []
# andersen = set()
# gisaid = set()

for i, andersen_key in enumerate(dfs_andersen.keys()):
    if len(dfs_andersen[andersen_key]) > 0:
        for j, gisaid_key in enumerate(dfs_gisaid.keys()):
            if andersen_key == gisaid_key:
                # same.append(gisaid_key)
        # gisaid_key = list(dfs_gisaid.keys())[i]
        # gisaid2_key = list(dfs_gisaid2.keys())[i]

                andersen_df = dfs_andersen[andersen_key][0]
                print(len(andersen_df))
                # print(andersen_df)
                gisaid_df = dfs_gisaid[gisaid_key][0]
                print(len(gisaid_df))
                # gisaid2_df = dfs_gisaid2[gisaid2_key][0]

                # print(pd.concat([gisaid_df, andersen_df]).drop_duplicates())

                full_df = pd.concat([andersen_df, gisaid_df], ignore_index=True)
                print("len full df:", len(full_df))
                # test = len(full_df.drop_duplicates(subset="isolate_partial"))

                dedup_df = full_df.drop_duplicates(subset="isolate_partial", keep="last")

                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print(full_df)
                
                # print("Keeping nothing: ", test)
                
                print("len deduplicated:", len(dedup_df))
                full_dfs[andersen_key].append(dedup_df)
            # else:
                # gisaid.add(gisaid_key)
                # andersen.add(andersen_key)
    
    # break 


# print(full_dfs)
# print(len(full_dfs))
# print(319*8)
# print(len(same))
# print(len(andersen))
# print(len(gisaid))

0
729
len full df: 729
len deduplicated: 601
0
729
len full df: 729
len deduplicated: 601
0
729
len full df: 729
len deduplicated: 601
0
729
len full df: 729
len deduplicated: 601
0
729
len full df: 729
len deduplicated: 601
0
729
len full df: 729
len deduplicated: 601
0
729
len full df: 729
len deduplicated: 601
0
729
len full df: 729
len deduplicated: 601
8
497
len full df: 505
len deduplicated: 491
8
497
len full df: 505
len deduplicated: 491
8
497
len full df: 505
len deduplicated: 491
8
497
len full df: 505
len deduplicated: 491
8
497
len full df: 505
len deduplicated: 491
8
497
len full df: 505
len deduplicated: 491
8
497
len full df: 505
len deduplicated: 491
8
497
len full df: 505
len deduplicated: 491
96
318
len full df: 414
len deduplicated: 325
96
318
len full df: 414
len deduplicated: 325
96
318
len full df: 414
len deduplicated: 325
96
318
len full df: 414
len deduplicated: 325
96
318
len full df: 414
len deduplicated: 325
96
318
len full df: 414
len deduplicated: 325
96
318
len full df: 414
len deduplicated: 325
96
318
len full df: 414
len deduplicated: 325
0
13
len full df: 13
len deduplicated: 13
0
13
len full df: 13
len deduplicated: 13
0
13
len full df: 13
len deduplicated: 13
0
13
len full df: 13
len deduplicated: 13
0
13
len full df: 13
len deduplicated: 13
0
13
len full df: 13
len deduplicated: 13
0
13
len full df: 13
len deduplicated: 13
0
13
len full df: 13
len deduplicated: 13
3
23
len full df: 26
len deduplicated: 24
3
23
len full df: 26
len deduplicated: 24
3
23
len full df: 26
len deduplicated: 24
3
23
len full df: 26
len deduplicated: 24
3
23
len full df: 26
len deduplicated: 24
3
23
len full df: 26
len deduplicated: 24
3
23
len full df: 26
len deduplicated: 24
3
23
len full df: 26
len deduplicated: 24
0
87
len full df: 87
len deduplicated: 87
0
87
len full df: 87
len deduplicated: 87
0
87
len full df: 87
len deduplicated: 87
0
87
len full df: 87
len deduplicated: 87
0
87
len full df: 87
len deduplicated: 87
0
87
len full df: 87
len deduplicated: 87
0
87
len full df: 87
len deduplicated: 87
0
87
len full df: 87
len deduplicated: 87
0
705
len full df: 705
len deduplicated: 690
0
705
len full df: 705
len deduplicated: 690
0
705
len full df: 705
len deduplicated: 690
0
705
len full df: 705
len deduplicated: 690
0
705
len full df: 705
len deduplicated: 690
0
705
len full df: 705
len deduplicated: 690
0
705
len full df: 705
len deduplicated: 690
0
705
len full df: 705
len deduplicated: 690
0
651
len full df: 651
len deduplicated: 616
0
651
len full df: 651
len deduplicated: 616
0
651
len full df: 651
len deduplicated: 616
0
651
len full df: 651
len deduplicated: 616
0
651
len full df: 651
len deduplicated: 616
0
651
len full df: 651
len deduplicated: 616
0
651
len full df: 651
len deduplicated: 616
0
651
len full df: 651
len deduplicated: 616
4
562
len full df: 566
len deduplicated: 561
4
562
len full df: 566
len deduplicated: 561
4
562
len full df: 566
len deduplicated: 561
4
562
len full df: 566
len deduplicated: 561
4
562
len full df: 566
len deduplicated: 561
4
562
len full df: 566
len deduplicated: 561
4
562
len full df: 566
len deduplicated: 561
4
562
len full df: 566
len deduplicated: 561
0
1154
len full df: 1154
len deduplicated: 1011
0
1154
len full df: 1154
len deduplicated: 1011
0
1154
len full df: 1154
len deduplicated: 1011
0
1154
len full df: 1154
len deduplicated: 1011
0
1154
len full df: 1154
len deduplicated: 1011
0
1154
len full df: 1154
len deduplicated: 1011
0
1154
len full df: 1154
len deduplicated: 1011
0
1154
len full df: 1154
len deduplicated: 1011
0
269
len full df: 269
len deduplicated: 267
0
269
len full df: 269
len deduplicated: 267
0
269
len full df: 269
len deduplicated: 267
0
269
len full df: 269
len deduplicated: 267
0
269
len full df: 269
len deduplicated: 267
0
269
len full df: 269
len deduplicated: 267
0
269
len full df: 269
len deduplicated: 267
0
269
len full df: 269
len deduplicated: 267
0
109
len full df: 109
len deduplicated: 108
0
109
len full df: 109
len deduplicated: 108
0
109
len full df: 109
len deduplicated: 108
0
109
len full df: 109
len deduplicated: 108
0
109
len full df: 109
len deduplicated: 108
0
109
len full df: 109
len deduplicated: 108
0
109
len full df: 109
len deduplicated: 108
0
109
len full df: 109
len deduplicated: 108
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
6
20
len full df: 26
len deduplicated: 13
6
20
len full df: 26
len deduplicated: 13
6
20
len full df: 26
len deduplicated: 13
6
20
len full df: 26
len deduplicated: 13
6
20
len full df: 26
len deduplicated: 13
6
20
len full df: 26
len deduplicated: 13
6
20
len full df: 26
len deduplicated: 13
6
20
len full df: 26
len deduplicated: 13
4718
4031
len full df: 8749
len deduplicated: 4640
4718
4031
len full df: 8749
len deduplicated: 4640
4718
4031
len full df: 8749
len deduplicated: 4640
4718
4031
len full df: 8749
len deduplicated: 4640
4718
4031
len full df: 8749
len deduplicated: 4640
4718
4031
len full df: 8749
len deduplicated: 4640
4718
4031
len full df: 8749
len deduplicated: 4640
4718
4031
len full df: 8749
len deduplicated: 4640
0
244
len full df: 244
len deduplicated: 219
0
244
len full df: 244
len deduplicated: 219
0
244
len full df: 244
len deduplicated: 219
0
244
len full df: 244
len deduplicated: 219
0
244
len full df: 244
len deduplicated: 219
0
244
len full df: 244
len deduplicated: 219
0
244
len full df: 244
len deduplicated: 219
0
244
len full df: 244
len deduplicated: 219
17
2130
len full df: 2147
len deduplicated: 2058
17
2130
len full df: 2147
len deduplicated: 2058
17
2130
len full df: 2147
len deduplicated: 2058
17
2130
len full df: 2147
len deduplicated: 2058
17
2130
len full df: 2147
len deduplicated: 2058
17
2130
len full df: 2147
len deduplicated: 2058
17
2130
len full df: 2147
len deduplicated: 2058
17
2130
len full df: 2147
len deduplicated: 2058
0
113
len full df: 113
len deduplicated: 100
0
113
len full df: 113
len deduplicated: 100
0
113
len full df: 113
len deduplicated: 100
0
113
len full df: 113
len deduplicated: 100
0
113
len full df: 113
len deduplicated: 100
0
113
len full df: 113
len deduplicated: 100
0
113
len full df: 113
len deduplicated: 100
0
113
len full df: 113
len deduplicated: 100
0
20
len full df: 20
len deduplicated: 20
0
20
len full df: 20
len deduplicated: 20
0
20
len full df: 20
len deduplicated: 20
0
20
len full df: 20
len deduplicated: 20
0
20
len full df: 20
len deduplicated: 20
0
20
len full df: 20
len deduplicated: 20
0
20
len full df: 20
len deduplicated: 20
0
20
len full df: 20
len deduplicated: 20
2
158
len full df: 160
len deduplicated: 158
2
158
len full df: 160
len deduplicated: 158
2
158
len full df: 160
len deduplicated: 158
2
158
len full df: 160
len deduplicated: 158
2
158
len full df: 160
len deduplicated: 158
2
158
len full df: 160
len deduplicated: 158
2
158
len full df: 160
len deduplicated: 158
2
158
len full df: 160
len deduplicated: 158
68
1014
len full df: 1082
len deduplicated: 956
68
1014
len full df: 1082
len deduplicated: 956
68
1014
len full df: 1082
len deduplicated: 956
68
1014
len full df: 1082
len deduplicated: 956
68
1014
len full df: 1082
len deduplicated: 956
68
1014
len full df: 1082
len deduplicated: 956
68
1014
len full df: 1082
len deduplicated: 956
68
1014
len full df: 1082
len deduplicated: 956
6
125
len full df: 131
len deduplicated: 120
6
125
len full df: 131
len deduplicated: 120
6
125
len full df: 131
len deduplicated: 120
6
125
len full df: 131
len deduplicated: 120
6
125
len full df: 131
len deduplicated: 120
6
125
len full df: 131
len deduplicated: 120
6
125
len full df: 131
len deduplicated: 120
6
125
len full df: 131
len deduplicated: 120
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
866
len full df: 866
len deduplicated: 841
0
866
len full df: 866
len deduplicated: 841
0
866
len full df: 866
len deduplicated: 841
0
866
len full df: 866
len deduplicated: 841
0
866
len full df: 866
len deduplicated: 841
0
866
len full df: 866
len deduplicated: 841
0
866
len full df: 866
len deduplicated: 841
0
866
len full df: 866
len deduplicated: 841
0
27
len full df: 27
len deduplicated: 23
0
27
len full df: 27
len deduplicated: 23
0
27
len full df: 27
len deduplicated: 23
0
27
len full df: 27
len deduplicated: 23
0
27
len full df: 27
len deduplicated: 23
0
27
len full df: 27
len deduplicated: 23
0
27
len full df: 27
len deduplicated: 23
0
27
len full df: 27
len deduplicated: 23
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
127
297
len full df: 424
len deduplicated: 311
127
297
len full df: 424
len deduplicated: 311
127
297
len full df: 424
len deduplicated: 311
127
297
len full df: 424
len deduplicated: 311
127
297
len full df: 424
len deduplicated: 311
127
297
len full df: 424
len deduplicated: 311
127
297
len full df: 424
len deduplicated: 311
127
297
len full df: 424
len deduplicated: 311
4
5
len full df: 9
len deduplicated: 4
4
5
len full df: 9
len deduplicated: 4
4
5
len full df: 9
len deduplicated: 4
4
5
len full df: 9
len deduplicated: 4
4
5
len full df: 9
len deduplicated: 4
4
5
len full df: 9
len deduplicated: 4
4
5
len full df: 9
len deduplicated: 4
4
5
len full df: 9
len deduplicated: 4
2554
2128
len full df: 4682
len deduplicated: 2726
2554
2128
len full df: 4682
len deduplicated: 2726
2554
2128
len full df: 4682
len deduplicated: 2726
2554
2128
len full df: 4682
len deduplicated: 2726
2554
2128
len full df: 4682
len deduplicated: 2726
2554
2128
len full df: 4682
len deduplicated: 2726
2554
2128
len full df: 4682
len deduplicated: 2726
2554
2128
len full df: 4682
len deduplicated: 2726
5
6
len full df: 11
len deduplicated: 7
5
6
len full df: 11
len deduplicated: 7
5
6
len full df: 11
len deduplicated: 7
5
6
len full df: 11
len deduplicated: 7
5
6
len full df: 11
len deduplicated: 7
5
6
len full df: 11
len deduplicated: 7
5
6
len full df: 11
len deduplicated: 7
5
6
len full df: 11
len deduplicated: 7
318
105
len full df: 423
len deduplicated: 313
318
105
len full df: 423
len deduplicated: 313
318
105
len full df: 423
len deduplicated: 313
318
105
len full df: 423
len deduplicated: 313
318
105
len full df: 423
len deduplicated: 313
318
105
len full df: 423
len deduplicated: 313
318
105
len full df: 423
len deduplicated: 313
318
105
len full df: 423
len deduplicated: 313
0
11
len full df: 11
len deduplicated: 9
0
11
len full df: 11
len deduplicated: 9
0
11
len full df: 11
len deduplicated: 9
0
11
len full df: 11
len deduplicated: 9
0
11
len full df: 11
len deduplicated: 9
0
11
len full df: 11
len deduplicated: 9
0
11
len full df: 11
len deduplicated: 9
0
11
len full df: 11
len deduplicated: 9
0
3
len full df: 3
len deduplicated: 2
0
3
len full df: 3
len deduplicated: 2
0
3
len full df: 3
len deduplicated: 2
0
3
len full df: 3
len deduplicated: 2
0
3
len full df: 3
len deduplicated: 2
0
3
len full df: 3
len deduplicated: 2
0
3
len full df: 3
len deduplicated: 2
0
3
len full df: 3
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
8
len full df: 8
len deduplicated: 8
0
8
len full df: 8
len deduplicated: 8
0
8
len full df: 8
len deduplicated: 8
0
8
len full df: 8
len deduplicated: 8
0
8
len full df: 8
len deduplicated: 8
0
8
len full df: 8
len deduplicated: 8
0
8
len full df: 8
len deduplicated: 8
0
8
len full df: 8
len deduplicated: 8
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
12
6
len full df: 18
len deduplicated: 12
12
6
len full df: 18
len deduplicated: 12
12
6
len full df: 18
len deduplicated: 12
12
6
len full df: 18
len deduplicated: 12
12
6
len full df: 18
len deduplicated: 12
12
6
len full df: 18
len deduplicated: 12
12
6
len full df: 18
len deduplicated: 12
12
6
len full df: 18
len deduplicated: 12
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
1
1
len full df: 2
len deduplicated: 1
2
1
len full df: 3
len deduplicated: 2
2
1
len full df: 3
len deduplicated: 2
2
1
len full df: 3
len deduplicated: 2
2
1
len full df: 3
len deduplicated: 2
2
1
len full df: 3
len deduplicated: 2
2
1
len full df: 3
len deduplicated: 2
2
1
len full df: 3
len deduplicated: 2
2
1
len full df: 3
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
4
len full df: 4
len deduplicated: 3
0
4
len full df: 4
len deduplicated: 3
0
4
len full df: 4
len deduplicated: 3
0
4
len full df: 4
len deduplicated: 3
0
4
len full df: 4
len deduplicated: 3
0
4
len full df: 4
len deduplicated: 3
0
4
len full df: 4
len deduplicated: 3
0
4
len full df: 4
len deduplicated: 3
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
1
3
len full df: 4
len deduplicated: 3
1
3
len full df: 4
len deduplicated: 3
1
3
len full df: 4
len deduplicated: 3
1
3
len full df: 4
len deduplicated: 3
1
3
len full df: 4
len deduplicated: 3
1
3
len full df: 4
len deduplicated: 3
1
3
len full df: 4
len deduplicated: 3
1
3
len full df: 4
len deduplicated: 3
0
10
len full df: 10
len deduplicated: 10
0
10
len full df: 10
len deduplicated: 10
0
10
len full df: 10
len deduplicated: 10
0
10
len full df: 10
len deduplicated: 10
0
10
len full df: 10
len deduplicated: 10
0
10
len full df: 10
len deduplicated: 10
0
10
len full df: 10
len deduplicated: 10
0
10
len full df: 10
len deduplicated: 10
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
2
len full df: 2
len deduplicated: 2
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
3
len full df: 3
len deduplicated: 3
0
3
len full df: 3
len deduplicated: 3
0
3
len full df: 3
len deduplicated: 3
0
3
len full df: 3
len deduplicated: 3
0
3
len full df: 3
len deduplicated: 3
0
3
len full df: 3
len deduplicated: 3
0
3
len full df: 3
len deduplicated: 3
0
3
len full df: 3
len deduplicated: 3
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
1
len full df: 1
len deduplicated: 1
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
4
len full df: 4
len deduplicated: 4
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5
len full df: 5
len deduplicated: 5
0
5

In [ ]:
# # If none in one database, only use the other and drop duplicates

# full_dfs = defaultdict(list)
# for key in dfs_andersen.keys():
#     print(key)
# # for key in ["D1.3"]:
#     dataframes = dfs_andersen[key]
#     for i, df in enumerate(dataframes):
#         print(i)
#         try:
#             full_df = df.merge(dfs_gisaid[key][i], how="outer")
#             # print(full_df)
#             full_df = full_df.drop_duplicates(subset=["isolate_partial"])
#             full_dfs[key].append(full_df)
#         except:
#             print("Failed to merge dataframes in ", key)
#             full_dfs[key].append(dataframes[i])

## Create FASTA files combining Andersen and GISAID

In [ ]:
# Create FASTA files per segment

combined_files = downloads + "Combinations/GISAID_Andersen/" # B3_13_D1_1/" + date_range + "_B3_13_D1_1/"

os.chdir(combined_files)
for pair in full_dfs.keys():
    print(pair)
    output_path = combined_files + pair + "_combined_" + date_range + ".fasta" 

    output_file = open(output_path, "w")
    for item in full_dfs[pair]:
        # for item in item:
        # item = fasta_files[pair]
        for index, row in item.iterrows():
            name = item.loc[index, "full_header"]
            sequence = item.loc[index, "sequence"]
            # print(name)
        # First is header, second is sequence
        # print(value)
            output_file.write(name)
            output_file.write(sequence)
    output_file.close()

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2