# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI and relabeling sequences.

In [1]:
# Housekeeping

import os
import pandas as pd
import dateutil
import re
import shutil 
import numpy as np
import importlib
import utils  
importlib.reload(utils)
from utils import *

In [6]:
# Paths and input

# Input
browser = input("Browser (Firefox, Chrome, or Edge): ")
sleep_time = input("Seconds to wait in between clicks (recommended 3): ")
# locations = input("Locations (separate with commas and no spaces in between locations): ")
# start_date = input("Start date (format: MM-DD-YYYY): ")
# end_date = input("End date: (format: MM-DD-YYYY): ")

# Dates and locations
locations = "Antarctica,North America,South America"
start_date = "11-01-2021"
end_date = "12-12-2025"
date_range = start_date + "--" + end_date


# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# downloads = "C:/Users/maksi/Downloads/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Downloads/" # MUST be downloads folder. Clean out downloads folder after each use. 
downloads_saved = home + "NCBI_Virus/downloads/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/" # "_Antarctica_North_America_South_America/"
andersen = home + "Andersen/avian-influenza/metadata/"
temp_files = home + "NCBI_Virus/temp/"
complete_files = home + "NCBI_Virus/complete/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/"
if not os.path.exists(complete_files): # checking if the directory exists or not
    os.makedirs(complete_files) # if the directory is not present then create it

references = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/references/"
# references = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/references/"
os.chdir(references)
states_ref = pd.read_csv("states_ref.csv")

genotypes_df = pd.read_excel("genotype_key.xlsx")
genotypes = list(genotypes_df["Genotype"])

# serotype = "H5N1"
# genotypes = ["B3.13", "D1.1", "D1.3"]
# genotypes = ["B3.2", "B3.6", "B3.7", "B3.5", "A3", "B3.13", "D1.1", "D1.3"]

## Downloading Data

In [9]:
os.chdir(downloads)

if not os.path.exists(downloads_saved): # checking if the directory exists or not
    os.makedirs(downloads_saved) # if the directory is not present then create it

    # Move downloaded files to saved downloads
    for dirpath, dirs, files in os.walk(downloads):
        if len(files) > 0: # If we have any files that need to be moved
            for file in files:
                file_name = os.path.join(dirpath, file)
                destination_path = os.path.join(downloads_saved, os.path.basename(file_name))
                try:
                    shutil.move(file_name, destination_path)
                except:
                    print("Error moving file", file_name)
                    continue 
        else: # If we don't have any downloaded files
            # Get files
            open_ncbi_virus(browser, sleep_time, locations, start_date, end_date)

            # Re-try 
            for dirpath, dirs, files in os.walk(downloads):
                if len(files) > 0: # If we have any files that need to be moved
                    for file in files:
                        file_name = os.path.join(dirpath, file)
                        destination_path = os.path.join(downloads_saved, os.path.basename(file_name))
                        try:
                            shutil.move(file_name, destination_path)
                        except:
                            print("Error moving file", file_name)
                            continue 
                break 
        break

## De-Duplication

In [10]:
os.chdir(downloads_saved)
metadata = pd.read_csv("sequences.csv")
print(len(metadata))

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.Isolate, as_index=False).size()
# print(metadata_counts)
metadata_counted = metadata.merge(metadata_counts, on="Isolate")

# Only keep those with size >= 8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates
metadata_complete_segs = metadata_complete_segs.drop_duplicates(subset="GenBank_Title", keep="last") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]
metadata_segments

118136

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Host,Tissue_Specimen_Source,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size
0,PV659823.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Cygnus atratus,NaN,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8
1,PV659824.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Cygnus atratus,NaN,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8
2,PV659825.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Cygnus atratus,NaN,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8
3,PV659826.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Cygnus atratus,NaN,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8
4,PV659827.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Cygnus atratus,NaN,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110196,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
110197,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
110198,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
110199,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
110200,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8

## Add sequences to dataframe

In [11]:
# NCBI Virus Naming Convention Example:
# Influenza A virus |USA: IN|25-006338-001-original|H5N1|2025-02-20|Meleagris gallopavo|GenBank|SRR33124721|SAMN47941411|PRJNA980729|Influenza A virus (A/Turkey/IN/25-006338-001-original/2025(H5N1)) segment 1 polymerase PB2 (PB2) gene, complete cds
# Organism_Name | Geo_Location | Isolate | Genotype | Collection_Date | Host | GenBank_RefSeq | SRA_Accession | BioSample | BioProject | GenBank_Title | Accession

# Get sequences and headers together
# headers = []
# isolates = []
# sras = []
# headers_seqs = {}

os.chdir(downloads_saved)

sequences_fasta = df_from_fasta("sequences.fasta") # Turn fasta into a dataframe

# Filter dataframe to only include filtered SRA accessions
# sequences_fasta = sequences_fasta[sequences_fasta["full_header"].str.contains("|".join(list(metadata_segments["SRA_Accession"].values)))]
# sequences_fasta["SRA_Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split("|")[-4])
sequences_fasta["Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split("|")[-1][:-1])

print(sequences_fasta["full_header"])

# Extract segment number so that we can add the correct sequences to the correct sample
# sequences_fasta["Segment"] = sequences_fasta["full_header"].apply(lambda x: int(re.search(r'segment (.?) ', x.split("|")[-2]).group(1)))

# Double-check the de-duplication
print(len(sequences_fasta)) 
print(sequences_fasta.head())
print(len(metadata_segments))

# Add sequences to the dataframe
metadata_segments = pd.merge(metadata_segments, sequences_fasta, on=["Accession"]) # , "Segment"])

0         >Influenza A virus |Brazil: SapucaiaSulBR|1246...
1         >Influenza A virus |Brazil: SapucaiaSulBR|1246...
2         >Influenza A virus |Brazil: SapucaiaSulBR|1246...
3         >Influenza A virus |Brazil: SapucaiaSulBR|1246...
4         >Influenza A virus |Brazil: SapucaiaSulBR|1246...
                                ...
118131    >Influenza A virus |Mexico: Veracruz|28159-398...
118132    >Influenza A virus |Mexico: Veracruz|28159-398...
118133    >Influenza A virus |Mexico: Veracruz|28159-398...
118134    >Influenza A virus |Mexico: Veracruz|28159-398...
118135    >Influenza A virus |Mexico: Veracruz|28159-398...
Name: full_header, Length: 118136, dtype: object
118136
                                         full_header  \
0  >Influenza A virus |Brazil: SapucaiaSulBR|1246...
1  >Influenza A virus |Brazil: SapucaiaSulBR|1246...
2  >Influenza A virus |Brazil: SapucaiaSulBR|1246...
3  >Influenza A virus |Brazil: SapucaiaSulBR|1246...
4  >Influenza A virus |Brazil: SapucaiaSulBR|1246...

                                            sequence   Accession
0  AGCRAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...  PV659823.1
1  AGCRAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...  PV659824.1
2  AGCRAAAGCAGGTACTGATCCAAAATGGAAGACTTTGTGCGACAAT...  PV659825.1
3  AGCAAAAGCAGGGGTTCATTCTGTCAAAATGGAGAACATAGTACTA...  PV659826.1
4  AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...  PV659827.1
101616

In [12]:
metadata_segments

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size,full_header,sequence
0,PV659823.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCRAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...
1,PV659824.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCRAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...
2,PV659825.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCRAAAGCAGGTACTGATCCAAAATGGAAGACTTTGTGCGACAAT...
3,PV659826.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGGGTTCATTCTGTCAAAATGGAGAACATAGTACTA...
4,PV659827.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101611,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...
101612,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...
101613,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...
101614,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...
101615,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...

## Find genotype using old genoflu results or Andersen Lab genoflu output

Old genoflu results should accumulate into one file to avoid having to genotype anything again.

In [13]:
genoflu_old = pd.read_csv("output.tsv", delimiter="\t")
genoflu_old = genoflu_old.rename(columns={"Strain":"Partial_Header"}) # So we can merge
# print(genoflu_old)
metadata_segments["Partial_Header"] = metadata_segments["full_header"].apply(lambda x: "|".join(x.split("|")[:-2]))
metadata_segments["Partial_Header"] = metadata_segments["Partial_Header"].apply(lambda x: x.replace(">", "")) # Get rid of header indicator
for c in ["/", "|", " ", ":", ",", "(", ")", "-"]: # Forbidden punctuation
    metadata_segments["Partial_Header"] = metadata_segments["Partial_Header"].apply(lambda x: x.replace(c, "_"))
# metadata_segments["Accession_Root"] = metadata_segments["Accession"].values[0].split(".")[0]
# print(metadata_segments["Partial_Header"])

# Merge to get already-genotyped segments
metadata_segments_old = metadata_segments.merge(genoflu_old, how="inner", on="Partial_Header") # .dropna(subset="SRA_Accession")
# Isolate not-already-genotyped segments
metadata_segments_new = metadata_segments.merge(genoflu_old,indicator = True, how='left', on="Partial_Header").loc[lambda x : x['_merge']!='both'] # .dropna(subset="SRA_Accession")

print(len(metadata_segments_old))
print(len(metadata_segments_new))

100984
832

In [14]:
metadata_segments_new

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,sequence,Partial_Header,Genotype_y,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,Date run,_merge
8,PV660431.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
9,PV660432.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
10,PV660433.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGTACTGATCCAAAATGGAAGACTTTGTGCGACAAT...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
11,PV660434.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGGGTTCATTCTGTCAAAATGGAGAACATAGTACTA...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
12,PV660435.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100231,OQ747867.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100235,OQ747877.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...,Influenza_A_virus__Peru_A273_H5N1_2022_12__Gen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100239,OQ747893.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100251,OQ747888.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100255,OQ747899.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [15]:
# Get genoflu results from Andersen and see if any fit

os.chdir(andersen)

genoflu_andersen = pd.read_csv("genoflu_results.tsv", delimiter="\t")
genoflu_andersen = genoflu_andersen.rename(columns={"sample":"SRA_Accession"}) # So we can merge

# Find those genotyped by Andersen via merge
metadata_segments_known_andersen = metadata_segments_new.merge(genoflu_andersen, how="inner", on="SRA_Accession")
print(metadata_segments_known_andersen)
# Keep all known genotypes
metadata_segments_known = pd.merge(metadata_segments_old, metadata_segments_known_andersen, how="left") # .drop_duplicates(keep="last", inplace=True) # Since we know both of these

print(genoflu_andersen)

      Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0    PQ377700.1        GenBank  GCA_042347525.1   SRR29694558  SAMN42279018
1    PQ377701.1        GenBank  GCA_042347525.1   SRR29694558  SAMN42279018
2    PQ377702.1        GenBank  GCA_042347525.1   SRR29694558  SAMN42279018
3    PQ377703.1        GenBank  GCA_042347525.1   SRR29694558  SAMN42279018
4    PQ377704.1        GenBank  GCA_042347525.1   SRR29694558  SAMN42279018
..          ...            ...              ...           ...           ...
515  PQ135389.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998
516  PQ135390.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998
517  PQ135391.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998
518  PQ135392.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998
519  PQ135393.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998

       BioProject      Organism_Name                         Species  \
0    PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
1    PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
2    PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3    PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
4    PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
..            ...                ...                             ...
515  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
516  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
517  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
518  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
519  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                   Genus            Family  ... Date run     _merge  \
0    Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
1    Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
2    Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3    Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4    Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
..                   ...               ...  ...      ...        ...
515  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
516  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
517  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
518  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
519  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only

                    date       File Name  Genotype  \
0    2025-05-09_10-48-17  SRR29694558.fa     B3.13
1    2025-05-09_10-48-17  SRR29694558.fa     B3.13
2    2025-05-09_10-48-17  SRR29694558.fa     B3.13
3    2025-05-09_10-48-17  SRR29694558.fa     B3.13
4    2025-05-09_10-48-17  SRR29694558.fa     B3.13
..                   ...             ...       ...
515  2025-05-09_10-48-14  SRR29694510.fa     B3.13
516  2025-05-09_10-48-14  SRR29694510.fa     B3.13
517  2025-05-09_10-48-14  SRR29694510.fa     B3.13
518  2025-05-09_10-48-14  SRR29694510.fa     B3.13
519  2025-05-09_10-48-14  SRR29694510.fa     B3.13

                         Genotype List Used, >=98.0%_y  \
0    HA:ea1, NA:ea1, NS:am1.1, MP:ea1, PA:ea1, PB1:...
1    HA:ea1, NA:ea1, NS:am1.1, MP:ea1, PA:ea1, PB1:...
2    HA:ea1, NA:ea1, NS:am1.1, MP:ea1, PA:ea1, PB1:...
3    HA:ea1, NA:ea1, NS:am1.1, MP:ea1, PA:ea1, PB1:...
4    HA:ea1, NA:ea1, NS:am1.1, MP:ea1, PA:ea1, PB1:...
..                                                 ...
515  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, NP:...
516  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, NP:...
517  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, NP:...
518  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, NP:...
519  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, NP:...

                          Genotype Sample Title List_y  \
0    ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...
1    ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...
2    ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...
3    ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...
4    ea1:22-003707-003:HA, ea1:22-003707-003:NA, am...
..                                                 ...
515  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...
516  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...
517  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...
518  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...
519  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...

                         Genotype Percent Match List_y  \
0    98.65%, 99.08%, 98.81%, 98.88%, 99.21%, 99.56%...
1    98.65%, 99.08%, 98.81%, 98.88%, 99.21%, 99.56%...
2    98.65%, 99.08%, 98.81%, 98.88%, 99.21%, 99.56%...
3    98.65%, 99.08%, 98.81%, 98.88%, 99.21%, 99.56%...
4    98.65%, 99.08%, 98.81%, 98.88%, 99.21%, 99.56%...
..                                                 ...
515  99.38%, 98.93%, 99.08%, 98.77%, 99.17%, 99.40%...
516  99.38%, 98.93%, 99.08%, 98.77%, 99.17%, 99.40%...
517  99.38%, 98.93%, 99.08%, 98.77%, 99.17%, 99.40%...
518  99.38%, 98.93%, 99.08%, 98.77%, 99.17%, 99.40%...
519  99.38%, 98.93%, 99.08%, 98.77%, 99.17%, 99.40%...

           Genotype Mismatch List_y Genotype Average Depth of Coverage List_y
0    23, 13, 10, 11, 17, 10, 29, 10         Ran on FASTA - No Coverage Report
1    23, 13, 10, 11, 17, 10, 29, 10         Ran on FASTA - No Coverage Report
2    23, 13, 10, 11, 17, 10, 29, 10         Ran on FASTA - No Coverage Report
3    23, 13, 10, 11, 17, 10, 29, 10         Ran on FASTA - No Coverage Report
4    23, 13, 10, 11, 17, 10, 29, 10         Ran on FASTA - No Coverage Report
..                              ...                                       ...
515    14, 23, 13, 21, 7, 9, 29, 16         Ran on FASTA - No Coverage Report
516    14, 23, 13, 21, 7, 9, 29, 16         Ran on FASTA - No Coverage Report
517    14, 23, 13, 21, 7, 9, 29, 16         Ran on FASTA - No Coverage Report
518    14, 23, 13, 21, 7, 9, 29, 16         Ran on FASTA - No Coverage Report
519    14, 23, 13, 21, 7, 9, 29, 16         Ran on FASTA - No Coverage Report

[520 rows x 48 columns]
      SRA_Accession                 date       File Name  \
0       SRR30789580  2025-05-09_10-49-10  SRR30789580.fa
1       SRR32973809  2025-05-09_10-52-30  SRR32973809.fa
2       SRR32125669  2025-05-09_10-47-22  SRR32125669.fa
3       SRR31597237  2025-05-09_10-47-24  SRR31597237.fa
4       SRR31605135  2025-05-09_10-47-38  SRR31605135.fa
...             ...                  ...             ...
13280   SRR36212538  2025-11-28_05-40-32  SRR36212538.fa
13281   SRR36212539  2025-11-28_05-40-32  SRR36212539.fa
13282   SRR36212540  2025-11-28_05-40-31  SRR36212540.fa
13283   SRR36212541  2025-11-28_05-40-32  SRR36212541.fa
13284   SRR36212542  2025-11-28_05-40-17  SRR36212542.fa

                                                Genotype  \
0      Not assigned: Only 0 segments >98.0% match fou...
1                                                   D1.3
2                                                  B3.13
3                                                  B3.13
4                                                  B3.13
...                                                  ...
13280                                               D1.1
13281                                               D1.1
13282  Not assigned: Only 7 segments >98.0% match fou...
13283                                               D1.1
13284                                               D1.1

                             Genotype List Used, >=98.0%  \
0                                        PB1:am4, PA:ea1
1      PB1:ea3, HA:ea3, PB2:am24, NP:am13, NS:ea3, PA...
2      MP:ea1, PA:ea1, HA:ea1, NP:am8, PB2:am2.2, NA:...
3      NP:am8, PB2:am2.2, NA:ea1, MP:ea1, NS:am1.1, P...
4      HA:ea1, NP:am8, PB1:am4, NS:am1.1, PA:ea1, MP:...
...                                                  ...
13280  PA:am4, HA:ea3, NS:ea3, PB2:am24, NA:am4N1, PB...
13281  NS:ea3, NP:am13, PB1:ea3, PB2:am24, NA:am4N1, ...
13282  PB1:ea3, HA:ea3, MP:ea3, NP:am13, NS:ea3, PB2:...
13283  NP:am13, NA:am4N1, PB1:ea3, HA:ea3, MP:ea3, NS...
13284  NS:ea3, NP:am13, PA:am4, NA:am4N1, MP:ea3, PB1...

                              Genotype Sample Title List  \
0      am4:23-001855-001:PB1, ea1:22-003707-003:PA, a...
1      ea3:22-013001-001:PB1, ea3:22-013001-001:HA, a...
2      ea1:22-003707-003:MP, ea1:22-003707-003:PA, ea...
3      am8:23-032005-001:NP, am2.2:22-010445-001:PB2,...
4      ea1:22-003707-003:HA, am8:23-032005-001:NP, am...
...                                                  ...
13280  am4:24-030039-001:PA, ea3:22-013001-001:HA, ea...
13281  ea3:22-013001-001:NS, am13:24-030039-001:NP, e...
13282  ea3:22-013001-001:PB1, am4N1:24-030039-001:NA,...
13283  am13:24-030039-001:NP, am4N1:24-030039-001:NA,...
13284  ea3:22-013001-001:NS, am13:24-030039-001:NP, a...

                             Genotype Percent Match List  \
0         98.12%, 98.31%, 93.08%, 97.57%, 97.44%, 96.58%
1      99.21%, 99.59%, 99.56%, 99.47%, 98.93%, 99.58%...
2      98.98%, 98.88%, 98.41%, 98.93%, 98.68%, 98.86%...
3      99.06%, 98.60%, 98.86%, 98.98%, 99.05%, 99.07%...
4      98.47%, 99.06%, 99.47%, 99.17%, 99.02%, 98.98%...
...                                                  ...
13280  99.32%, 99.41%, 99.05%, 99.52%, 98.75%, 99.34%...
13281  98.81%, 99.53%, 99.16%, 99.56%, 98.78%, 99.35%...
13282  98.94%, 97.16%, 99.53%, 99.69%, 99.47%, 98.93%...
13283  99.60%, 98.76%, 99.21%, 99.53%, 99.80%, 98.93%...
13284  98.93%, 99.53%, 99.37%, 98.95%, 99.69%, 99.03%...

              Genotype Mismatch List Genotype Average Depth of Coverage List
0                  3, 3, 13, 5, 3, 4       Ran on FASTA - No Coverage Report
1          18, 7, 10, 8, 9, 9, 0, 19       Ran on FASTA - No Coverage Report
2      10, 24, 27, 16, 30, 16, 7, 12       Ran on FASTA - No Coverage Report
3      14, 32, 16, 10, 8, 20, 11, 26       Ran on FASTA - No Coverage Report
4      26, 14, 12, 7, 21, 10, 31, 15       Ran on FASTA - No Coverage Report
...                              ...                                     ...
13280    12, 10, 8, 11, 13, 15, 7, 3       Ran on FASTA - No Coverage Report
13281   10, 7, 19, 10, 14, 11, 12, 3       Ran on FASTA - No Coverage Report
13282      24, 40, 8, 3, 8, 9, 9, 15       Ran on FASTA - No Coverage Report
13283     6, 14, 18, 8, 2, 9, 14, 11       Ran on FASTA - No Coverage Report
13284    9, 7, 11, 11, 3, 22, 10, 10       Ran on FASTA - No Coverage Report

[13285 rows x 9 columns]

In [16]:
metadata_segments_unknown = metadata_segments_new # Variable rename so we don't break old code

metadata_segments_unknown

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,sequence,Partial_Header,Genotype_y,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,Date run,_merge
8,PV660431.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
9,PV660432.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
10,PV660433.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGTACTGATCCAAAATGGAAGACTTTGTGCGACAAT...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
11,PV660434.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGGGTTCATTCTGTCAAAATGGAGAACATAGTACTA...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
12,PV660435.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100231,OQ747867.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100235,OQ747877.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...,Influenza_A_virus__Peru_A273_H5N1_2022_12__Gen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100239,OQ747893.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100251,OQ747888.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100255,OQ747899.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

## Create FASTA files of unknown genotypes

In [17]:
# Create 8 fasta files per segment

# Get all the segments
metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["full_header"].apply(lambda x: "|".join(x.split("|")[:-2]))

# Create list of dataframes
df_list = []
for partial_header in list(set(metadata_segments_unknown["Partial_Header"].values)): # Unique partial headers only
    # Get smaller dataframe
    df = metadata_segments_unknown[metadata_segments_unknown["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    # Make sure there are 8 segments
    if len(df) == 8:
        # Forbidden characters in headers
        for c in ["/", "|", " ", ":", ",", "(", ")", "-"]:
            df["Partial_Header"] = df["Partial_Header"].apply(lambda x: x.replace(c, "_"))
            
        df["full_header"] = df["Partial_Header"]
        df_list.append(df)

print(metadata_segments_unknown["Partial_Header"])

print(df_list[0]["full_header"])

# Make fasta files
for df in df_list:
    segments = list(set(df["Segment"].apply(lambda x: int(x)).values))
    for segment in segments:
        one_row = df[df["Segment"] == segment]
        df_to_fasta(one_row, str(segment) + "_seg.fasta", temp_files)

8         >Influenza A virus |Brazil: SapucaiaSulBR|1246...
9         >Influenza A virus |Brazil: SapucaiaSulBR|1246...
10        >Influenza A virus |Brazil: SapucaiaSulBR|1246...
11        >Influenza A virus |Brazil: SapucaiaSulBR|1246...
12        >Influenza A virus |Brazil: SapucaiaSulBR|1246...
                                ...
100231    >Influenza A virus |Peru|A273|H5N1|2022-12|Fal...
100235    >Influenza A virus |Peru|A273|H5N1|2022-12||Ge...
100239    >Influenza A virus |Peru|A273|H5N1|2022-12|Fal...
100251    >Influenza A virus |Peru|A273|H5N1|2022-12|Fal...
100255    >Influenza A virus |Peru|A273|H5N1|2022-12|Fal...
Name: Partial_Header, Length: 832, dtype: object
82464    >Influenza_A_virus__USA__MN_24_017652_001_orig...
82465    >Influenza_A_virus__USA__MN_24_017652_001_orig...
82466    >Influenza_A_virus__USA__MN_24_017652_001_orig...
82467    >Influenza_A_virus__USA__MN_24_017652_001_orig...
82468    >Influenza_A_virus__USA__MN_24_017652_001_orig...
82469    >Influenza_A_virus__USA__MN_24_017652_001_orig...
82470    >Influenza_A_virus__USA__MN_24_017652_001_orig...
82471    >Influenza_A_virus__USA__MN_24_017652_001_orig...
Name: full_header, dtype: object

## Re-Labeling Using GenoFlu

**STOP HERE AND USE GENOFLU TO FIND NEW GENOTYPES.** Then, make sure "results.tsv" is in the downloads directory.

In [18]:
'''
To run GenoFLU-multi, first change directories to Multi-GenoFLU directory (and activate genoflu conda environment):

conda activate genoflu
cd GenoFLU-multi

And then call the python script:

python bin/genoflu-multi.py -f <FASTA_directory>
'''

'\nTo run GenoFLU-multi, first change directories to Multi-GenoFLU directory (and activate genoflu conda environment):\n\nconda activate genoflu\ncd GenoFLU-multi\n\nAnd then call the python script:\n\npython bin/genoflu-multi.py -f <FASTA_directory>\n'

In [19]:
# Merging

os.chdir(downloads_saved)

# Read in genoflu results
output_genoflu = pd.read_csv("results.tsv", delimiter="\t")

# Create partial headers to merge genoflu results with previously unknown segments
metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["full_header"].apply(lambda x: "|".join(x.split("|")[:-2]))
for c in ["/", "|", " ", ":", ",", "(", ")", "-"]:
    metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["Partial_Header"].apply(lambda x: x.replace(c, "_"))

metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["Partial_Header"].apply(lambda x: x.replace(">", ""))

metadata_segments_unknown["Strain"] = metadata_segments_unknown["Partial_Header"] # Renaming so we can merge

# Merge
metadata_genoflu = metadata_segments_unknown.merge(output_genoflu, how="left", on="Strain", suffixes=('_left', '_right')) 

# Fill the rest of the 8 segments with the same genotype
metadata_genoflu = metadata_genoflu.ffill()

print(metadata_genoflu)

print(metadata_genoflu["Genotype_x"])

print(metadata_genoflu.columns)

      Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0    PV660431.1        GenBank  GCA_053847005.1           NaN           NaN
1    PV660432.1        GenBank  GCA_053847005.1           NaN           NaN
2    PV660433.1        GenBank  GCA_053847005.1           NaN           NaN
3    PV660434.1        GenBank  GCA_053847005.1           NaN           NaN
4    PV660435.1        GenBank  GCA_053847005.1           NaN           NaN
..          ...            ...              ...           ...           ...
827  OQ747867.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998
828  OQ747877.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998
829  OQ747893.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998
830  OQ747888.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998
831  OQ747899.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998

       BioProject      Organism_Name                         Species  \
0             NaN  Influenza A virus  Alphainfluenzavirus influenzae
1             NaN  Influenza A virus  Alphainfluenzavirus influenzae
2             NaN  Influenza A virus  Alphainfluenzavirus influenzae
3             NaN  Influenza A virus  Alphainfluenzavirus influenzae
4             NaN  Influenza A virus  Alphainfluenzavirus influenzae
..            ...                ...                             ...
827  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
828  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
829  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
830  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
831  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                   Genus            Family  ... Date run_left     _merge  \
0    Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
1    Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
2    Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
3    Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
4    Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
..                   ...               ...  ...           ...        ...
827  Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
828  Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
829  Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
830  Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
831  Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only

                                                Strain  \
0    Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
1    Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
2    Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
3    Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
4    Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
..                                                 ...
827  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
828  Influenza_A_virus__Peru_A273_H5N1_2022_12__Gen...
829  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
830  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
831  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...

                                              Genotype  \
0    Not assigned: Only 4 segments >98.0% match fou...
1    Not assigned: Only 4 segments >98.0% match fou...
2    Not assigned: Only 4 segments >98.0% match fou...
3    Not assigned: Only 4 segments >98.0% match fou...
4    Not assigned: Only 4 segments >98.0% match fou...
..                                                 ...
827                                               B3.2
828                                               B3.2
829                                               B3.2
830                                               B3.2
831                                               B3.2

                     Genotype List Used, >=98.0%_right  \
0                     HA:ea1, NP:am1.1, NA:ea1, MP:ea1
1                     HA:ea1, NP:am1.1, NA:ea1, MP:ea1
2                     HA:ea1, NP:am1.1, NA:ea1, MP:ea1
3                     HA:ea1, NP:am1.1, NA:ea1, MP:ea1
4                     HA:ea1, NP:am1.1, NA:ea1, MP:ea1
..                                                 ...
827  PB2:am2.1, PB1:am1.2, PA:ea1, HA:ea1, NP:am1.4...
828  PB2:am2.1, PB1:am1.2, PA:ea1, HA:ea1, NP:am1.4...
829  PB2:am2.1, PB1:am1.2, PA:ea1, HA:ea1, NP:am1.4...
830  PB2:am2.1, PB1:am1.2, PA:ea1, HA:ea1, NP:am1.4...
831  PB2:am2.1, PB1:am1.2, PA:ea1, HA:ea1, NP:am1.4...

                      Genotype Sample Title List_right  \
0    am2.1:22-009329-001:PB2, am2:22-031266-001:PB1...
1    am2.1:22-009329-001:PB2, am2:22-031266-001:PB1...
2    am2.1:22-009329-001:PB2, am2:22-031266-001:PB1...
3    am2.1:22-009329-001:PB2, am2:22-031266-001:PB1...
4    am2.1:22-009329-001:PB2, am2:22-031266-001:PB1...
..                                                 ...
827  am2.1:22-009329-001:PB2, am1.2:22-010085-001:P...
828  am2.1:22-009329-001:PB2, am1.2:22-010085-001:P...
829  am2.1:22-009329-001:PB2, am1.2:22-010085-001:P...
830  am2.1:22-009329-001:PB2, am1.2:22-010085-001:P...
831  am2.1:22-009329-001:PB2, am1.2:22-010085-001:P...

                     Genotype Percent Match List_right  \
0    86.90%, 89.10%, 86.61%, 98.30%, 98.26%, 98.23%...
1    86.90%, 89.10%, 86.61%, 98.30%, 98.26%, 98.23%...
2    86.90%, 89.10%, 86.61%, 98.30%, 98.26%, 98.23%...
3    86.90%, 89.10%, 86.61%, 98.30%, 98.26%, 98.23%...
4    86.90%, 89.10%, 86.61%, 98.30%, 98.26%, 98.23%...
..                                                 ...
827  98.86%, 99.08%, 99.30%, 98.83%, 98.93%, 99.08%...
828  98.86%, 99.08%, 99.30%, 98.83%, 98.93%, 99.08%...
829  98.86%, 99.08%, 99.30%, 98.83%, 98.93%, 99.08%...
830  98.86%, 99.08%, 99.30%, 98.83%, 98.93%, 99.08%...
831  98.86%, 99.08%, 99.30%, 98.83%, 98.93%, 99.08%...

          Genotype Mismatch List_right  \
0    295, 246, 288, 29, 26, 25, 13, 72
1    295, 246, 288, 29, 26, 25, 13, 72
2    295, 246, 288, 29, 26, 25, 13, 72
3    295, 246, 288, 29, 26, 25, 13, 72
4    295, 246, 288, 29, 26, 25, 13, 72
..                                 ...
827       26, 21, 15, 20, 16, 13, 7, 5
828       26, 21, 15, 20, 16, 13, 7, 5
829       26, 21, 15, 20, 16, 13, 7, 5
830       26, 21, 15, 20, 16, 13, 7, 5
831       26, 21, 15, 20, 16, 13, 7, 5

    Genotype Average Depth of Coverage List_right       Date run_right
0               Ran on FASTA - No Coverage Report  2025-12-08_13-19-57
1               Ran on FASTA - No Coverage Report  2025-12-08_13-19-57
2               Ran on FASTA - No Coverage Report  2025-12-08_13-19-57
3               Ran on FASTA - No Coverage Report  2025-12-08_13-19-57
4               Ran on FASTA - No Coverage Report  2025-12-08_13-19-57
..                                            ...                  ...
827             Ran on FASTA - No Coverage Report  2025-12-08_13-19-35
828             Ran on FASTA - No Coverage Report  2025-12-08_13-19-35
829             Ran on FASTA - No Coverage Report  2025-12-08_13-19-35
830             Ran on FASTA - No Coverage Report  2025-12-08_13-19-35
831             Ran on FASTA - No Coverage Report  2025-12-08_13-19-35

[832 rows x 48 columns]
0      H5N1
1      H5N1
2      H5N1
3      H5N1
4      H5N1
       ...
827    H5N1
828    H5N1
829    H5N1
830    H5N1
831    H5N1
Name: Genotype_x, Length: 832, dtype: object
Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Partial_Header', 'Genotype_y',
       'Genotype List Used, >=98.0%_left', 'Genotype Sample Title List_left',
       'Genotype Percent Match List_left', 'Genotype Mismatch List_left',
       'Genotype Average Depth of Coverage List_left', 'Date run_left',
       '_merge', 'Strain', 'Genotype', 'Genotype List Used, >=98.0%_right',
       'Genotype Sample Title List_right', 'Genotype Percent Match List_right',
       'Genotype Mismatch List_right',
       'Genotype Average Depth of Coverage List_right', 'Date run_right'],
      dtype='object')

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_42688\2032597337.py:21: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  metadata_genoflu = metadata_genoflu.ffill()

# Concatenate with known genotypes

In [20]:
# Rename columns so we can concatenate
metadata_segments_known["Genotype_official"] = metadata_segments_known["Genotype_y"]
metadata_segments_known["Serotype"] = metadata_segments_known["Genotype_x"]
metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype"]
metadata_genoflu["Serotype"] = metadata_genoflu["Genotype_x"]

# Concatenation
metadata_genoflu = pd.concat([metadata_genoflu, metadata_segments_known])

metadata_genoflu.columns

Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Partial_Header', 'Genotype_y',
       'Genotype List Used, >=98.0%_left', 'Genotype Sample Title List_left',
       'Genotype Percent Match List_left', 'Genotype Mismatch List_left',
       'Genotype Average Depth of Coverage List_left', 'Date run_left',
       '_merge', 'Strain', 'Genotype', 'Genotype List Used, >=98.0%_right',
       'Genotype Sample Title List_right', 'Genotype Percent Match List_right',
       'Genotype Mismatch List_right',
       'Genotype Average Depth of Coverage List_right', 'Date run_right',
       'Genotype_official', 'Serotype', 'Genotype List Used, >=98.0%',
       'Genotype Sample Title List', 'Genotype Percent Match List',
       'Genotype Mismatch List', 'Genotype Average Depth of Coverage List',
       'Date run', 'Genotype List Used, >=98.0%_x',
       'Genotype Sample Title List_x', 'Genotype Percent Match List_x',
       'Genotype Mismatch List_x', 'Genotype Average Depth of Coverage List_x',
       'date', 'File Name', 'Genotype List Used, >=98.0%_y',
       'Genotype Sample Title List_y', 'Genotype Percent Match List_y',
       'Genotype Mismatch List_y',
       'Genotype Average Depth of Coverage List_y'],
      dtype='object')

In [21]:
metadata_segments_known # .dropna(subset="SRA_Accession")

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,date,File Name,Genotype,"Genotype List Used, >=98.0%_y",Genotype Sample Title List_y,Genotype Percent Match List_y,Genotype Mismatch List_y,Genotype Average Depth of Coverage List_y,Genotype_official,Serotype
0,PV659823.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
1,PV659824.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
2,PV659825.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
3,PV659826.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
4,PV659827.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100979,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2
100980,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2
100981,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2
100982,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2
100983,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2

In [22]:
# Cut down to only columns we want
metadata_genoflu = metadata_genoflu[["Accession", "GenBank_Title", "Host", "Collection_Date", "SRA_Accession", "Isolate", "Genotype_official", "Geo_Location", "full_header", "sequence", "Serotype", "Segment", "File Name", "Partial_Header", "Strain"]]

# Get genbank strain name
metadata_genoflu["genbank_name"] = metadata_genoflu["GenBank_Title"].apply(lambda x: x.split("(")[1] )
metadata_genoflu["Host"] = metadata_genoflu["genbank_name"].apply(lambda x: x.split("/")[1])

metadata_genoflu # [metadata_genoflu["Genotype"]  == "B3.13"]

,Accession,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype_official,Geo_Location,full_header,sequence,Serotype,Segment,File Name,Partial_Header,Strain,genbank_name
0,PV660431.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Not assigned: Only 4 segments >98.0% match fou...,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...,H5N1,1,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...
1,PV660432.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Not assigned: Only 4 segments >98.0% match fou...,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...,H5N1,2,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...
2,PV660433.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Not assigned: Only 4 segments >98.0% match fou...,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGTACTGATCCAAAATGGAAGACTTTGTGCGACAAT...,H5N1,3,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...
3,PV660434.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Not assigned: Only 4 segments >98.0% match fou...,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGGGTTCATTCTGTCAAAATGGAGAACATAGTACTA...,H5N1,4,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...
4,PV660435.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Not assigned: Only 4 segments >98.0% match fou...,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...,H5N1,5,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100979,OK205883.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...,H5N2,4,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995
100980,OK205884.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...,H5N2,5,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995
100981,OK205885.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...,H5N2,6,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995
100982,OK205886.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...,H5N2,7,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995
100983,OK205887.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...,H5N2,8,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995

In [23]:
metadata_genoflu["Serotype"]

0         H5N1
1         H5N1
2         H5N1
3         H5N1
4         H5N1
          ...
100979    H5N2
100980    H5N2
100981    H5N2
100982    H5N2
100983    H5N2
Name: Serotype, Length: 101816, dtype: object

## Relabeling Sequences

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

In [24]:
# Animals 

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genoflu)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['northern fulmar', 'rough-legged hawk', 'iceland gull', 'collared plover', 'green-winged teal', 'fregata magnificens', 'goat', 'muscovy duck', 'parasitic jaeger', 'merlin', 'bobcat', 'red-tailed hawk', 'pheasant', 'gallus', 'eared grebe', 'alpaca', 'backyard chicken', 'baikal teal', 'mergus', 'barred owl', 'snow goose', 'american wigeon', 'black vulture', 'thalasseus acuflavidus', 'goose', 'dairy cattle', 'sandhill crane', 'manx shearwater', 'black skimmer', 'herring gull', 'gannet', 'teal', 'hawk', 'northern gannet', 'common loon', 'atlantic white-sided dolphin', 'common murre', 'lesser scaup', 'ring-billed gull', 'raven', 'bald eagle', 'peafowl', 'ostrich', 'lesser snow goose white-morph', 'horned grebe', 'american crow', 'laridae', 'mink', 'roseate spoonbill', 'great-horned owl', 'lesser snow goose', 'willet', 'western sandpiper', 'pluvialis dominica', 'white-winged scoter', 'grackle', 'nasua nasua', 'crow', 'american robin', 'layer chicken', 'black swan', 'american coot', 'raccoon', 'nannopterum brasilianus', 'double-crested cormorant', 'irere', 'rock pigeon', 'emu', 'peacock', 'cat', 'dovekie', 'domestic grower', 'rosss goose', 'american white pelican', 'ferruginous hawk', 'taiwanese chicken', 'house sparrow', 'emperor goose', 'owl', 'american goshawk', 'gray seal', 'mountain lion', 'broiler breeders chicken', 'american woodcock', 'glaucous-winged gull', 'pelecanus', 'great grey owl', 'wild bird', 'barn owl', 'gadwall', 'pet food', 'quail', 'common goldeneye', 'great shearwater', 'sula leucogaster', 'fish crow', 'northwestern crow', 'vulture', 'lesser snow goose blue-morph', 'unknown', 'northern shoveler', 'numida meleagris', 'house mouse', 'common tern', 'red fox', 'fancy chicken', 'dog', 'glaucous gull', 'sterna hirundo', 'cackling goose', 'hooded merganser', 'blue-winged and cinnamon teal', 'fisher', 'thayers gull', 'greater yellowlegs', 'washington', 'franklins gull', 'striped skunk', 'common barn owl', 'pelican', 'blue-winged teal', 'california gull', 'osprey', 'brant', 'backyard duck', 'redhead duck', 'black-billed magpie', 'brown pelican', 'environment', 'lynx', 'gallus gallus', 'guanay cormorant', 'western grebe', 'south polar skua', 'pinniped', 'gallus gallus domesticus', 'dolphin', 'turkey vulture', 'panthera leo', 'american-kestrel', 'aves', 'poultry', 'feral cat', 'blue jay', 'crane', 'tiger', 'seabird', 'black-crowned night-heron', 'heron', 'wood duck', 'bos taurus', 'black-crowned night heron', 'black-necked swan', 'swan', 'california condor', 'common eider', 'long-eared owl', 'mottled duck', 'canada goose', 'partridge', 'great blue heron', 'greater white-fronted goose', 'snowy owl', 'surf scoter', 'cygnus melancoryphus', 'common merganser', 'ring-necked duck', 'skunk', 'sandwich tern', 'anatinae', 'pekin duck', 'red-shouldered hawk', 'gyrfalcon', 'ruffed grouse', 'great egret', 'bovine', 'polar bear', 'black scoter', 'chicken', 'black-legged kittiwake', 'swainsons hawk', 'avian', 'otaria flavescens', 'serval', 'parrot', 'procellaria aequinoctialis', 'furnarius rufus', 'turkey', 'trumpeter swan', 'snowy egret', 'backyard bird', 'northern harrier', 'mallard', 'megascops choliba', 'gadwall duck', 'western screech owl', 'golden eagle', 'southern elephant seal', 'antofagasta', 'american blue-winged teal', 'domestic cat', 'northern pintail', 'thalasseus maximus', 'cinnamon teal', 'south american fur seal', 'south american tern', 'backyard turkey', 'cattle', 'peruvian booby', 'mallard duck', 'swine', 'wild duck', 'snowy plover', 'wild turkey', 'tundra swan', 'black bear', 'cygnus atratus', 'dairy cow', 'lesser white-fronted goose', 'raptor', 'greater scaup', 'rosy-billed pochard', 'caspian tern', 'guineafowl', 'coopers hawk', 'pigeon', 'crested caracara', 'black swift', 'red-necked grebe', 'western gull', 'black turnstone', 'great horned owl', 'buteogallus urubitinga', 'american wood stork', 'chukar', 'bufflehead', 'green heron', 'black brant', 'eurasian collared dove', 'arctic tern', 'feline', 'duck', 'burrowing owl', 'silver pheasant', 'dunlin', 'pelecanus thagus', 'guinea fowl', 'harbor seal', 'neotropic cormorant', 'ring-necked pheasant', 'american kestrel', 'merganser', 'sharp-shinned hawk', 'magpie', 'raw pet food', 'savannah cat', 'pig', 'domestic bird', 'graylag goose', 'flamingo', 'razorbill', 'gull', 'waterfowl', 'red-breasted merganser', 'dromaius novaehollandiae', 'peregrine falcon', 'green winged teal', 'pintail', 'cattle milk product', 'south american sea lion', 'sparrow', 'redhead', 'short-billed gull', 'american black duck', 'short-eared owl', 'royal tern', 'atlantic puffin', 'red-necked phalarope', 'eider', 'american pelican', 'mute swan', 'white-winged dove', 'domestic turkey', 'dendrocygna viduata', 'great black-backed gull', 'cormorant', 'broad-winged hawk', 'american green-winged teal', 'dove', 'eastern screech owl', 'great-tailed grackle', 'common raven', 'western snowy plover', 'guinea', 'eagle', 'vulpes vulpes', 'sanderling']
[]
                     wild_avian domestic_avian               cattle  \
0              great_horned_owl       pheasant            dairy_cow
1                  common_raven         turkey               cattle
2                 cooper's_hawk        chicken  cattle milk product
3                  coopers_hawk          goose          bovine_milk
4                       peafowl    guinea_fowl              bovine
...                         ...            ...                  ...
1085          dalmatian pelican            NaN                  NaN
1086                common gull            NaN                  NaN
1087  greater_black_backed_gull            NaN                  NaN
1088          chinstrap_penguin            NaN                  NaN
1089             northern_raven            NaN                  NaN

            feline   other_mammal       human         other      pet_food  new
0              cat     deer mouse  washington         mixed      pet food  NaN
1     domestic_cat    house_mouse      nevada   environment  raw pet food  NaN
2        feral_cat          skunk     wyoming  multispecies  raw_pet_food  NaN
3           feline  striped_skunk  california       unknown      pet_food  NaN
4     domestic-cat     norway rat    michigan             '           NaN  NaN
...            ...            ...         ...           ...           ...  ...
1085           NaN            NaN         NaN           NaN           NaN  NaN
1086           NaN            NaN         NaN           NaN           NaN  NaN
1087           NaN            NaN         NaN           NaN           NaN  NaN
1088           NaN            NaN         NaN           NaN           NaN  NaN
1089           NaN            NaN         NaN           NaN           NaN  NaN

[1090 rows x 9 columns]

In [25]:
metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype_official"].apply(lambda x: "Unassigned" if "Not assigned" in str(x) else x) # Unassigned segments are labeled "Unassigned"
metadata_genoflu["Genotype"] = metadata_genoflu["Genotype_official"] # Rename column again to not break old code

In [26]:
metadata_genoflu

,Accession,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype_official,Geo_Location,full_header,sequence,Serotype,Segment,File Name,Partial_Header,Strain,genbank_name,Genotype
0,PV660431.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Unassigned,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...,H5N1,1,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...,Unassigned
1,PV660432.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Unassigned,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...,H5N1,2,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...,Unassigned
2,PV660433.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Unassigned,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGTACTGATCCAAAATGGAAGACTTTGTGCGACAAT...,H5N1,3,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...,Unassigned
3,PV660434.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Unassigned,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGGGTTCATTCTGTCAAAATGGAGAACATAGTACTA...,H5N1,4,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...,Unassigned
4,PV660435.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Unassigned,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...,H5N1,5,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...,Unassigned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100979,OK205883.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...,H5N2,4,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned
100980,OK205884.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...,H5N2,5,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned
100981,OK205885.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...,H5N2,6,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned
100982,OK205886.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...,H5N2,7,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned
100983,OK205887.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...,H5N2,8,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned

In [27]:
# Re-Labeling

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

# Fix animals
fix_animals_andersen(metadata_genoflu, animals_ref)

# Get the years
metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

# Get geographic locations
metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location"].apply(lambda x: 
                                                                        # If "x" has the state abbreviation (e.g. "MD")
                                                                        states_ref.loc[states_ref["Abbreviation"].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0] 
                                                                        + "-" + 
                                                                        x.split(" ")[-1]
                                                                        if states_ref["Abbreviation"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has the full state name (e.g. "Maryland")
                                                                        else states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0]
                                                                        + "-" + 
                                                                        states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Abbreviation'].iloc[0] 
                                                                        if states_ref["State"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has neither the state abbreviation nor the full state name nor is "USA"
                                                                        else 
                                                                        x
                                                                        )

metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location_Abrv"].apply(lambda x: x.split("-")[0] if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] else x)


print(metadata_genoflu["Geo_Location_Abrv"])

0         Brazil-SapucaiaSulBR
1         Brazil-SapucaiaSulBR
2         Brazil-SapucaiaSulBR
3         Brazil-SapucaiaSulBR
4         Brazil-SapucaiaSulBR
                  ...
100979         Mexico-Veracruz
100980         Mexico-Veracruz
100981         Mexico-Veracruz
100982         Mexico-Veracruz
100983         Mexico-Veracruz
Name: Geo_Location_Abrv, Length: 101816, dtype: object

In [28]:
metadata_genoflu['SRA_Accession'] = np.where(metadata_genoflu['SRA_Accession'] == "", metadata_genoflu['Accession'].apply(lambda x: x.split(".")[0]), metadata_genoflu['SRA_Accession'])

# Make new labels
names = ">" + metadata_genoflu["SRA_Accession"].apply(lambda x: x.split(",")[0]) + "|" + metadata_genoflu["genbank_name"] + "|" + metadata_genoflu["Serotype"] + "|" + metadata_genoflu["Geo_Location_Abrv"] + "|" + metadata_genoflu["Collection_Date"] + "|" + metadata_genoflu["Host_Type"] + "|" + metadata_genoflu["Genotype"]

metadata_genoflu["Name"] = names


print(metadata_genoflu)

         Accession                                      GenBank_Title  \
0       PV660431.1  Influenza A virus (A/Cygnus melancoryphus/Sapu...
1       PV660432.1  Influenza A virus (A/Cygnus melancoryphus/Sapu...
2       PV660433.1  Influenza A virus (A/Cygnus melancoryphus/Sapu...
3       PV660434.1  Influenza A virus (A/Cygnus melancoryphus/Sapu...
4       PV660435.1  Influenza A virus (A/Cygnus melancoryphus/Sapu...
...            ...                                                ...
100979  OK205883.1  Influenza A virus (A/chicken/Veracruz/28159-39...
100980  OK205884.1  Influenza A virus (A/chicken/Veracruz/28159-39...
100981  OK205885.1  Influenza A virus (A/chicken/Veracruz/28159-39...
100982  OK205886.1  Influenza A virus (A/chicken/Veracruz/28159-39...
100983  OK205887.1  Influenza A virus (A/chicken/Veracruz/28159-39...

                        Host Collection_Date SRA_Accession       Isolate  \
0       cygnus melancoryphus      2025-05-12      PV660431  1246-N7-2025
1       cygnus melancoryphus      2025-05-12      PV660432  1246-N7-2025
2       cygnus melancoryphus      2025-05-12      PV660433  1246-N7-2025
3       cygnus melancoryphus      2025-05-12      PV660434  1246-N7-2025
4       cygnus melancoryphus      2025-05-12      PV660435  1246-N7-2025
...                      ...             ...           ...           ...
100979               chicken            1995      OK205883     28159-398
100980               chicken            1995      OK205884     28159-398
100981               chicken            1995      OK205885     28159-398
100982               chicken            1995      OK205886     28159-398
100983               chicken            1995      OK205887     28159-398

       Genotype_official           Geo_Location  \
0             Unassigned  Brazil: SapucaiaSulBR
1             Unassigned  Brazil: SapucaiaSulBR
2             Unassigned  Brazil: SapucaiaSulBR
3             Unassigned  Brazil: SapucaiaSulBR
4             Unassigned  Brazil: SapucaiaSulBR
...                  ...                    ...
100979        Unassigned       Mexico: Veracruz
100980        Unassigned       Mexico: Veracruz
100981        Unassigned       Mexico: Veracruz
100982        Unassigned       Mexico: Veracruz
100983        Unassigned       Mexico: Veracruz

                                              full_header  \
0       >Influenza A virus |Brazil: SapucaiaSulBR|1246...
1       >Influenza A virus |Brazil: SapucaiaSulBR|1246...
2       >Influenza A virus |Brazil: SapucaiaSulBR|1246...
3       >Influenza A virus |Brazil: SapucaiaSulBR|1246...
4       >Influenza A virus |Brazil: SapucaiaSulBR|1246...
...                                                   ...
100979  >Influenza A virus |Mexico: Veracruz|28159-398...
100980  >Influenza A virus |Mexico: Veracruz|28159-398...
100981  >Influenza A virus |Mexico: Veracruz|28159-398...
100982  >Influenza A virus |Mexico: Veracruz|28159-398...
100983  >Influenza A virus |Mexico: Veracruz|28159-398...

                                                 sequence  ... Segment  \
0       AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...  ...       1
1       AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...  ...       2
2       AGCAAAAGCAGGTACTGATCCAAAATGGAAGACTTTGTGCGACAAT...  ...       3
3       AGCAAAAGCAGGGGTTCATTCTGTCAAAATGGAGAACATAGTACTA...  ...       4
4       AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...  ...       5
...                                                   ...  ...     ...
100979  AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...  ...       4
100980  AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...  ...       5
100981  AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...  ...       6
100982  AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...  ...       7
100983  AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...  ...       8

        File Name                                     Partial_Header  \
0                  Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
1                  Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
2                  Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
3                  Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
4                  Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
...           ...                                                ...
100979             Influenza_A_virus__Mexico__Veracruz_28159_398_...
100980             Influenza_A_virus__Mexico__Veracruz_28159_398_...
100981             Influenza_A_virus__Mexico__Veracruz_28159_398_...
100982             Influenza_A_virus__Mexico__Veracruz_28159_398_...
100983             Influenza_A_virus__Mexico__Veracruz_28159_398_...

                                                   Strain  \
0       Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
1       Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
2       Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
3       Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
4       Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
...                                                   ...
100979
100980
100981
100982
100983

                                             genbank_name    Genotype  \
0       A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...  Unassigned
1       A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...  Unassigned
2       A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...  Unassigned
3       A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...  Unassigned
4       A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...  Unassigned
...                                                   ...         ...
100979                  A/chicken/Veracruz/28159-398/1995  Unassigned
100980                  A/chicken/Veracruz/28159-398/1995  Unassigned
100981                  A/chicken/Veracruz/28159-398/1995  Unassigned
100982                  A/chicken/Veracruz/28159-398/1995  Unassigned
100983                  A/chicken/Veracruz/28159-398/1995  Unassigned

             Host_Type Years     Geo_Location_Abrv  \
0           wild_avian  2025  Brazil-SapucaiaSulBR
1           wild_avian  2025  Brazil-SapucaiaSulBR
2           wild_avian  2025  Brazil-SapucaiaSulBR
3           wild_avian  2025  Brazil-SapucaiaSulBR
4           wild_avian  2025  Brazil-SapucaiaSulBR
...                ...   ...                   ...
100979  domestic_avian  1995       Mexico-Veracruz
100980  domestic_avian  1995       Mexico-Veracruz
100981  domestic_avian  1995       Mexico-Veracruz
100982  domestic_avian  1995       Mexico-Veracruz
100983  domestic_avian  1995       Mexico-Veracruz

                                                     Name
0       >PV660431|A/Cygnus melancoryphus/SapucaiaSulBR...
1       >PV660432|A/Cygnus melancoryphus/SapucaiaSulBR...
2       >PV660433|A/Cygnus melancoryphus/SapucaiaSulBR...
3       >PV660434|A/Cygnus melancoryphus/SapucaiaSulBR...
4       >PV660435|A/Cygnus melancoryphus/SapucaiaSulBR...
...                                                   ...
100979  >OK205883|A/chicken/Veracruz/28159-398/1995|H5...
100980  >OK205884|A/chicken/Veracruz/28159-398/1995|H5...
100981  >OK205885|A/chicken/Veracruz/28159-398/1995|H5...
100982  >OK205886|A/chicken/Veracruz/28159-398/1995|H5...
100983  >OK205887|A/chicken/Veracruz/28159-398/1995|H5...

[101816 rows x 21 columns]

In [29]:
# De-duplicate

print(len(metadata_genoflu))
metadata_genoflu = metadata_genoflu.drop_duplicates(subset=["Isolate", "genbank_name", "Segment"], keep="last")
print(len(metadata_genoflu))

101816
101616

## Rename segments and make complete FASTA files

In [30]:
# Set up segments

genotypes.append("Unassigned") # Make sure unassigned genotypes are included
segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"} # Name segments 
metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].apply(lambda x: int(x)).map(segments)

# Separate into several dataframes based on genotype + segment
segment_genotype_dfs = []
for segment in segments.values():
    m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
    for genotype in list(set(m_g["Genotype"].values)):
        if genotype in genotypes:
            df = m_g[(m_g["Genotype"] == genotype)] 
            # df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
            segment_genotype_dfs.append(df)
            pair = genotype + "_" + segment
            print(pair)

B3.13_PB2
B3.5_PB2
Minor65_PB2
Unassigned_PB2
Minor90_PB2
A2_PB2
B1.1_PB2
B1.3_PB2
D1.3_PB2
Minor102_PB2
Minor12_PB2
Minor101_PB2
B2.2_PB2
B3.10_PB2
Minor14_PB2
A5_PB2
D1.1_PB2
Minor81_PB2
Minor98_PB2
B1.2_PB2
Minor105_PB2
B3.12_PB2
Minor19_PB2
B4.1_PB2
B3.2_PB2
B2.1_PB2
C2.1_PB2
B3.6_PB2
A1_PB2
D1.2_PB2
B3.4_PB2
Minor13_PB2
Minor94_PB2
Minor34_PB2
Minor08_PB2
Minor09_PB2
Minor91_PB2
Minor11_PB2
Minor04_PB2
A6_PB2
Minor77_PB2
Minor63_PB2
Minor104_PB2
Minor01_PB2
Minor45_PB2
B5.1_PB2
B3.3_PB2
B3.7_PB2
Minor07_PB2
Minor50_PB2
A3_PB2
B3.1_PB2
Minor87_PB2
Minor28_PB2
A4_PB2
B3.13_PB1
B3.5_PB1
Minor65_PB1
Unassigned_PB1
Minor90_PB1
A2_PB1
B1.1_PB1
B1.3_PB1
D1.3_PB1
Minor102_PB1
Minor12_PB1
Minor101_PB1
B2.2_PB1
B3.10_PB1
Minor14_PB1
A5_PB1
D1.1_PB1
Minor81_PB1
Minor98_PB1
B1.2_PB1
Minor105_PB1
B3.12_PB1
Minor19_PB1
B4.1_PB1
B3.2_PB1
B2.1_PB1
C2.1_PB1
B3.6_PB1
A1_PB1
D1.2_PB1
B3.4_PB1
Minor13_PB1
Minor94_PB1
Minor34_PB1
Minor08_PB1
Minor09_PB1
Minor91_PB1
Minor11_PB1
Minor04_PB1
A6_PB1
Minor77_PB1
Minor63_PB1
Minor104_PB1
Minor01_PB1
Minor45_PB1
B5.1_PB1
B3.3_PB1
B3.7_PB1
Minor07_PB1
Minor50_PB1
A3_PB1
B3.1_PB1
Minor87_PB1
Minor28_PB1
A4_PB1
B3.13_PA
B3.5_PA
Minor65_PA
Unassigned_PA
Minor90_PA
A2_PA
B1.1_PA
B1.3_PA
D1.3_PA
Minor102_PA
Minor12_PA
Minor101_PA
B2.2_PA
B3.10_PA
Minor14_PA
A5_PA
D1.1_PA
Minor81_PA
Minor98_PA
B1.2_PA
Minor105_PA
B3.12_PA
Minor19_PA
B4.1_PA
B3.2_PA
B2.1_PA
C2.1_PA
B3.6_PA
A1_PA
D1.2_PA
B3.4_PA
Minor13_PA
Minor94_PA
Minor34_PA
Minor08_PA
Minor09_PA
Minor91_PA
Minor11_PA
Minor04_PA
A6_PA
Minor77_PA
Minor63_PA
Minor104_PA
Minor01_PA
Minor45_PA
B5.1_PA
B3.3_PA
B3.7_PA
Minor07_PA
Minor50_PA
A3_PA
B3.1_PA
Minor87_PA
Minor28_PA
A4_PA
B3.13_HA
B3.5_HA
Minor65_HA
Unassigned_HA
Minor90_HA
A2_HA
B1.1_HA
B1.3_HA
D1.3_HA
Minor102_HA
Minor12_HA
Minor101_HA
B2.2_HA
B3.10_HA
Minor14_HA
A5_HA
D1.1_HA
Minor81_HA
Minor98_HA
B1.2_HA
Minor105_HA
B3.12_HA
Minor19_HA
B4.1_HA
B3.2_HA
B2.1_HA
C2.1_HA
B3.6_HA
A1_HA
D1.2_HA
B3.4_HA
Minor13_HA
Minor94_HA
Minor34_HA
Minor08_HA
Minor09_HA
Minor91_HA
Minor11_HA
Minor04_HA
A6_HA
Minor77_HA
Minor63_HA
Minor104_HA
Minor01_HA
Minor45_HA
B5.1_HA
B3.3_HA
B3.7_HA
Minor07_HA
Minor50_HA
A3_HA
B3.1_HA
Minor87_HA
Minor28_HA
A4_HA
B3.13_NP
B3.5_NP
Minor65_NP
Unassigned_NP
Minor90_NP
A2_NP
B1.1_NP
B1.3_NP
D1.3_NP
Minor102_NP
Minor12_NP
Minor101_NP
B2.2_NP
B3.10_NP
Minor14_NP
A5_NP
D1.1_NP
Minor81_NP
Minor98_NP
B1.2_NP
Minor105_NP
B3.12_NP
Minor19_NP
B4.1_NP
B3.2_NP
B2.1_NP
C2.1_NP
B3.6_NP
A1_NP
D1.2_NP
B3.4_NP
Minor13_NP
Minor94_NP
Minor34_NP
Minor08_NP
Minor09_NP
Minor91_NP
Minor11_NP
Minor04_NP
A6_NP
Minor77_NP
Minor63_NP
Minor104_NP
Minor01_NP
Minor45_NP
B5.1_NP
B3.3_NP
B3.7_NP
Minor07_NP
Minor50_NP
A3_NP
B3.1_NP
Minor87_NP
Minor28_NP
A4_NP
B3.13_NA
B3.5_NA
Minor65_NA
Unassigned_NA
Minor90_NA
A2_NA
B1.1_NA
B1.3_NA
D1.3_NA
Minor102_NA
Minor12_NA
Minor101_NA
B2.2_NA
B3.10_NA
Minor14_NA
A5_NA
D1.1_NA
Minor81_NA
Minor98_NA
B1.2_NA
Minor105_NA
B3.12_NA
Minor19_NA
B4.1_NA
B3.2_NA
B2.1_NA
C2.1_NA
B3.6_NA
A1_NA
D1.2_NA
B3.4_NA
Minor13_NA
Minor94_NA
Minor34_NA
Minor08_NA
Minor09_NA
Minor91_NA
Minor11_NA
Minor04_NA
A6_NA
Minor77_NA
Minor63_NA
Minor104_NA
Minor01_NA
Minor45_NA
B5.1_NA
B3.3_NA
B3.7_NA
Minor07_NA
Minor50_NA
A3_NA
B3.1_NA
Minor87_NA
Minor28_NA
A4_NA
B3.13_MP
B3.5_MP
Minor65_MP
Unassigned_MP
Minor90_MP
A2_MP
B1.1_MP
B1.3_MP
D1.3_MP
Minor102_MP
Minor12_MP
Minor101_MP
B2.2_MP
B3.10_MP
Minor14_MP
A5_MP
D1.1_MP
Minor81_MP
Minor98_MP
B1.2_MP
Minor105_MP
B3.12_MP
Minor19_MP
B4.1_MP
B3.2_MP
B2.1_MP
C2.1_MP
B3.6_MP
A1_MP
D1.2_MP
B3.4_MP
Minor13_MP
Minor94_MP
Minor34_MP
Minor08_MP
Minor09_MP
Minor91_MP
Minor11_MP
Minor04_MP
A6_MP
Minor77_MP
Minor63_MP
Minor104_MP
Minor01_MP
Minor45_MP
B5.1_MP
B3.3_MP
B3.7_MP
Minor07_MP
Minor50_MP
A3_MP
B3.1_MP
Minor87_MP
Minor28_MP
A4_MP
B3.13_NS
B3.5_NS
Minor65_NS
Unassigned_NS
Minor90_NS
A2_NS
B1.1_NS
B1.3_NS
D1.3_NS
Minor102_NS
Minor12_NS
Minor101_NS
B2.2_NS
B3.10_NS
Minor14_NS
A5_NS
D1.1_NS
Minor81_NS
Minor98_NS
B1.2_NS
Minor105_NS
B3.12_NS
Minor19_NS
B4.1_NS
B3.2_NS
B2.1_NS
C2.1_NS
B3.6_NS
A1_NS
D1.2_NS
B3.4_NS
Minor13_NS
Minor94_NS
Minor34_NS
Minor08_NS
Minor09_NS
Minor91_NS
Minor11_NS
Minor04_NS
A6_NS
Minor77_NS
Minor63_NS
Minor104_NS
Minor01_NS
Minor45_NS
B5.1_NS
B3.3_NS
B3.7_NS
Minor07_NS
Minor50_NS
A3_NS
B3.1_NS
Minor87_NS
Minor28_NS
A4_NS

In [32]:
# Create FASTA files

os.chdir(complete_files)

for df in segment_genotype_dfs:
    print(df)
    df = df.reset_index()
    if len(df["Genotype"].values[0]) > 0: # If we have assigned genotypes, including "Unassigned"
        file_name = df["Genotype"].values[0] + "_" + df["Segment_Name"].values[0] + "_" + date_range + ".fasta"
        output_file = open(complete_files + file_name, "w")

        for index, row in df.iterrows():
            name = df.loc[index, "Name"]
            name = name.replace(" ", "_")
            # names.append(name)
            sequence = df.loc[index, "sequence"]
            # First is header, second is sequence
            output_file.write(name + "\n")
            output_file.write(sequence + "\n")
        
    output_file.close()

        Accession                                      GenBank_Title    Host  \
48     PX579471.1  Influenza A virus (A/cattle/CA/25-020648-001-o...  cattle
64     PX579495.1  Influenza A virus (A/cattle/CA/25-024858-003-o...  cattle
288    PX579743.1  Influenza A virus (A/cattle/CA/24-032050-001-o...  cattle
296    PX579751.1  Influenza A virus (A/cattle/CA/24-033012-001-o...  cattle
304    PX579759.1  Influenza A virus (A/cattle/CA/24-033016-001-o...  cattle
...           ...                                                ...     ...
88184  PP737552.1  Influenza A virus (A/bovine/Ohio/B24OSU-UW13-8...  bovine
88192  PP599462.1  Influenza A virus (A/Bovine/texas/24-029328-01...  bovine
88200  PP599470.1  Influenza A virus (A/bovine/texas/24-029328-02...  bovine
88208  PP692139.1  Influenza A virus (A/feline/Texas/24-029329-01...  feline
88216  PP692192.1  Influenza A virus (A/feline/Texas/24-029329-02...  feline

      Collection_Date SRA_Accession                        Isolate  \
48         2025-07-15   SRR35088920    25-020648-001-original-tile
64         2025-09-09   SRR35705013  25-024858-003-original-repeat
288        2024-10-22   SRR31347673         24-032050-001-original
296        2024-10-29   SRR31597080         24-033012-001-original
304        2024-10-29   SRR31597201         24-033016-001-original
...               ...           ...                            ...
88184      2024-04-05      PP737552                B24OSU-UW13-869
88192      2024-03-20      PP599462                   24-029328-01
88200      2024-03-20      PP599470                   24-029328-02
88208      2024-03-20      PP692139                   24-029329-01
88216      2024-03-20      PP692192                   24-029329-02

      Genotype_official Geo_Location  \
48                B3.13      USA: CA
64                B3.13      USA: CA
288               B3.13      USA: CA
296               B3.13      USA: CA
304               B3.13      USA: CA
...                 ...          ...
88184             B3.13    USA: Ohio
88192             B3.13   USA: texas
88200             B3.13   USA: texas
88208             B3.13   USA: Texas
88216             B3.13   USA: Texas

                                             full_header  \
48     >Influenza A virus |USA: CA|25-020648-001-orig...
64     >Influenza A virus |USA: CA|25-024858-003-orig...
288    >Influenza A virus |USA: CA|24-032050-001-orig...
296    >Influenza A virus |USA: CA|24-033012-001-orig...
304    >Influenza A virus |USA: CA|24-033016-001-orig...
...                                                  ...
88184  >Influenza A virus |USA: Ohio|B24OSU-UW13-869|...
88192  >Influenza A virus |USA: texas|24-029328-01|H5...
88200  >Influenza A virus |USA: texas|24-029328-02|H5...
88208  >Influenza A virus |USA: Texas|24-029329-01|H5...
88216  >Influenza A virus |USA: Texas|24-029329-02|H5...

                                                sequence  ... File Name  \
48     ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
64     ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
288    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
296    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
304    ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
...                                                  ...  ...       ...
88184  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
88192  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...  ...
88200  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...  ...
88208  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAGGAAC...  ...
88216  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAGGAAC...  ...

                                          Partial_Header Strain  \
48     Influenza_A_virus__USA__CA_25_020648_001_origi...
64     Influenza_A_virus__USA__CA_25_024858_003_origi...
288    Influenza_A_virus__USA__CA_24_032050_001_origi...
296    Influenza_A_virus__USA__CA_24_033012_001_origi...
304    Influenza_A_virus__USA__CA_24_033016_001_origi...
...                                                  ...    ...
88184  Influenza_A_virus__USA__Ohio_B24OSU_UW13_869_H...
88192  Influenza_A_virus__USA__texas_24_029328_01_H5N...
88200  Influenza_A_virus__USA__texas_24_029328_02_H5N...
88208  Influenza_A_virus__USA__Texas_24_029329_01_H5N...
88216  Influenza_A_virus__USA__Texas_24_029329_02_H5N...

                                         genbank_name Genotype Host_Type  \
48       A/cattle/CA/25-020648-001-original-tile/2025    B3.13    cattle
64     A/cattle/CA/25-024858-003-original-repeat/2025    B3.13    cattle
288           A/cattle/CA/24-032050-001-original/2024    B3.13    cattle
296           A/cattle/CA/24-033012-001-original/2024    B3.13    cattle
304           A/cattle/CA/24-033016-001-original/2024    B3.13    cattle
...                                               ...      ...       ...
88184              A/bovine/Ohio/B24OSU-UW13-869/2024    B3.13    cattle
88192                A/Bovine/texas/24-029328-01/2024    B3.13    cattle
88200                A/bovine/texas/24-029328-02/2024    B3.13    cattle
88208                A/feline/Texas/24-029329-01/2024    B3.13    feline
88216                A/feline/Texas/24-029329-02/2024    B3.13    feline

      Years Geo_Location_Abrv  \
48     2025            USA-CA
64     2025            USA-CA
288    2024            USA-CA
296    2024            USA-CA
304    2024            USA-CA
...     ...               ...
88184  2024            USA-OH
88192  2024        USA: texas
88200  2024        USA: texas
88208  2024            USA-TX
88216  2024            USA-TX

                                                    Name Segment_Name
48     >SRR35088920|A/cattle/CA/25-020648-001-origina...          PB2
64     >SRR35705013|A/cattle/CA/25-024858-003-origina...          PB2
288    >SRR31347673|A/cattle/CA/24-032050-001-origina...          PB2
296    >SRR31597080|A/cattle/CA/24-033012-001-origina...          PB2
304    >SRR31597201|A/cattle/CA/24-033016-001-origina...          PB2
...                                                  ...          ...
88184  >PP737552|A/bovine/Ohio/B24OSU-UW13-869/2024|H...          PB2
88192  >PP599462|A/Bovine/texas/24-029328-01/2024|H5N...          PB2
88200  >PP599470|A/bovine/texas/24-029328-02/2024|H5N...          PB2
88208  >PP692139|A/feline/Texas/24-029329-01/2024|H5N...          PB2
88216  >PP692192|A/feline/Texas/24-029329-02/2024|H5N...          PB2

[3648 rows x 22 columns]
        Accession                                      GenBank_Title  \
7288   PV301057.1  Influenza A virus (A/American Crow/ON/FAV-0184...
8456   PV302253.1  Influenza A virus (A/American Crow/ON/FAV-0104...
8472   PV302269.1  Influenza A virus (A/American Crow/ON/FAV-0134...
8480   PV302277.1  Influenza A virus (A/American Crow/ON/FAV-0134...
8488   PV302285.1  Influenza A virus (A/American Crow/ON/FAV-0137...
...           ...                                                ...
69848  PQ710934.1  Influenza A virus (A/Great horned owl/CO/22-04...
69912  PQ710998.1  Influenza A virus (A/Great horned owl/CO/23-00...
71088  PQ712174.1  Influenza A virus (A/Great horned owl/WY/23-00...
74792  PQ715902.1  Influenza A virus (A/Red-tailed hawk/CO/23-001...
75760  PQ716870.1  Influenza A virus (A/Red-tailed hawk/WY/23-000...

                   Host Collection_Date SRA_Accession                 Isolate  \
7288      american crow      2023-04-22      PV301057         FAV-0184-1-2023
8456      american crow      2023-03-08      PV302253         FAV-0104-2-2023
8472      american crow      2023-03-31      PV302269         FAV-0134-2-2023
8480      american crow      2023-03-27      PV302277         FAV-0134-3-2023
8488      american crow      2023-03-26      PV302285         FAV-0137-1-2023
...                 ...             ...           ...                     ...
69848  great horned owl      2022-12-13      PQ710934  22-040755-001-original
69912  great horned owl      2023-01-08      PQ710998  23-001474-001-original
71088  great horned owl      2023-01-09      PQ712174  23-001193-001-original
74792   red-tailed hawk      2023-01-11      PQ715902  23-001573-001-original
75760   red-tailed hawk      2023-01-05      PQ716870  23-000757-001-original

      Genotype_official Geo_Location  \
7288               B3.5   Canada: ON
8456               B3.5   Canada: ON
8472               B3.5   Canada: ON
8480               B3.5   Canada: ON
8488               B3.5   Canada: ON
...                 ...          ...
69848              B3.5      USA: CO
69912              B3.5      USA: CO
71088              B3.5      USA: WY
74792              B3.5      USA: CO
75760              B3.5      USA: WY

                                             full_header  \
7288   >Influenza A virus |Canada: ON|FAV-0184-1-2023...
8456   >Influenza A virus |Canada: ON|FAV-0104-2-2023...
8472   >Influenza A virus |Canada: ON|FAV-0134-2-2023...
8480   >Influenza A virus |Canada: ON|FAV-0134-3-2023...
8488   >Influenza A virus |Canada: ON|FAV-0137-1-2023...
...                                                  ...
69848  >Influenza A virus |USA: CO|22-040755-001-orig...
69912  >Influenza A virus |USA: CO|23-001474-001-orig...
71088  >Influenza A virus |USA: WY|23-001193-001-orig...
74792  >Influenza A virus |USA: CO|23-001573-001-orig...
75760  >Influenza A virus |USA: WY|23-000757-001-orig...

                                                sequence  ... File Name  \
7288   ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
8456   ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
8472   ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
8480   ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
8488   ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
...                                                  ...  ...       ...
69848  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
69912  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
71088  ATGGAGAGAATAAAAGAACTAAGATATCTAATGTCACAGTCTCGCA...  ...
74792  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
75760  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...

                                          Partial_Header Strain  \
7288   Influenza_A_virus__Canada__ON_FAV_0184_1_2023_...
8456   Influenza_A_virus__Canada__ON_FAV_0104_2_2023_...
8472   Influenza_A_virus__Canada__ON_FAV_0134_2_2023_...
8480   Influenza_A_virus__Canada__ON_FAV_0134_3_2023_...
8488   Influenza_A_virus__Canada__ON_FAV_0137_1_2023_...
...                                                  ...    ...
69848  Influenza_A_virus__USA__CO_22_040755_001_origi...
69912  Influenza_A_virus__USA__CO_23_001474_001_origi...
71088  Influenza_A_virus__USA__WY_23_001193_001_origi...
74792  Influenza_A_virus__USA__CO_23_001573_001_origi...
75760  Influenza_A_virus__USA__WY_23_000757_001_origi...

                                            genbank_name Genotype   Host_Type  \
7288             A/American Crow/ON/FAV-0184-1-2023/2023     B3.5  wild_avian
8456             A/American Crow/ON/FAV-0104-2-2023/2023     B3.5  wild_avian
8472             A/American Crow/ON/FAV-0134-2-2023/2023     B3.5  wild_avian
8480             A/American Crow/ON/FAV-0134-3-2023/2023     B3.5  wild_avian
8488             A/American Crow/ON/FAV-0137-1-2023/2023     B3.5  wild_avian
...                                                  ...      ...         ...
69848  A/Great horned owl/CO/22-040755-001-original/2022     B3.5  wild_avian
69912  A/Great horned owl/CO/23-001474-001-original/2023     B3.5  wild_avian
71088  A/Great horned owl/WY/23-001193-001-original/2023     B3.5  wild_avian
74792   A/Red-tailed hawk/CO/23-001573-001-original/2023     B3.5  wild_avian
75760   A/Red-tailed hawk/WY/23-000757-001-original/2023     B3.5  wild_avian

      Years Geo_Location_Abrv  \
7288   2023         Canada-ON
8456   2023         Canada-ON
8472   2023         Canada-ON
8480   2023         Canada-ON
8488   2023         Canada-ON
...     ...               ...
69848  2022            USA-CO
69912  2023            USA-CO
71088  2023            USA-WY
74792  2023            USA-CO
75760  2023            USA-WY

                                                    Name Segment_Name
7288   >PV301057|A/American Crow/ON/FAV-0184-1-2023/2...          PB2
8456   >PV302253|A/American Crow/ON/FAV-0104-2-2023/2...          PB2
8472   >PV302269|A/American Crow/ON/FAV-0134-2-2023/2...          PB2
8480   >PV302277|A/American Crow/ON/FAV-0134-3-2023/2...          PB2
8488   >PV302285|A/American Crow/ON/FAV-0137-1-2023/2...          PB2
...                                                  ...          ...
69848  >PQ710934|A/Great horned owl/CO/22-040755-001-...          PB2
69912  >PQ710998|A/Great horned owl/CO/23-001474-001-...          PB2
71088  >PQ712174|A/Great horned owl/WY/23-001193-001-...          PB2
74792  >PQ715902|A/Red-tailed hawk/CO/23-001573-001-o...          PB2
75760  >PQ716870|A/Red-tailed hawk/WY/23-000757-001-o...          PB2

[120 rows x 22 columns]
        Accession                                      GenBank_Title  \
24032  PV317837.1  Influenza A virus (A/Snow Goose/ON/FAV-0457-2-...

             Host Collection_Date SRA_Accession          Isolate  \
24032  snow goose      2023-11-29      PV317837  FAV-0457-2-2023

      Genotype_official Geo_Location  \
24032           Minor65   Canada: ON

                                             full_header  \
24032  >Influenza A virus |Canada: ON|FAV-0457-2-2023...

                                                sequence  ... File Name  \
24032  ATGGAGAGAATAAAAGAACTAAGAGACCTAATGTCACAGTCTCGCA...  ...

                                          Partial_Header Strain  \
24032  Influenza_A_virus__Canada__ON_FAV_0457_2_2023_...

                               genbank_name Genotype   Host_Type Years  \
24032  A/Snow Goose/ON/FAV-0457-2-2023/2023  Minor65  wild_avian  2023

      Geo_Location_Abrv                                               Name  \
24032         Canada-ON  >PV317837|A/Snow Goose/ON/FAV-0457-2-2023/2023...

      Segment_Name
24032          PB2

[1 rows x 22 columns]
         Accession                                      GenBank_Title  \
0       PV660431.1  Influenza A virus (A/Cygnus melancoryphus/Sapu...
8       PV660439.1  Influenza A virus (A/Gallus gallus/MontenegroB...
16      PV740254.1  Influenza A virus (A/Cygnus atratus/MateusLeme...
24      PV740310.1  Influenza A virus (A/Cygnus atratus/MateusLeme...
32      PV796400.1  Influenza A virus (A/Furnarius rufus/Montenegr...
...            ...                                                ...
100944  OK205848.1  Influenza A virus (A/chicken/San Luis Potosi/7...
100952  OK205856.1  Influenza A virus (A/chicken/Tabasco/234-8289/...
100960  OK205864.1  Influenza A virus (A/chicken/Veracruz/232-6169...
100968  OK205872.1  Influenza A virus (A/chicken/Veracruz/233-7607...
100976  OK205880.1  Influenza A virus (A/chicken/Veracruz/28159-39...

                        Host Collection_Date SRA_Accession       Isolate  \
0       cygnus melancoryphus      2025-05-12      PV660431  1246-N7-2025
8              gallus gallus      2025-05-12      PV660439  1245-N3-2025
16            cygnus atratus      2025-05-25      PV740254   1367-N-2025
24            cygnus atratus      2025-05-25      PV740310   1369-T-2025
32           furnarius rufus      2025-05-28      PV796400   1355-N-2025
...                      ...             ...           ...           ...
100944               chicken            1996      OK205848          7651
100952               chicken            1998      OK205856      234-8289
100960               chicken            1998      OK205864      232-6169
100968               chicken            1998      OK205872      233-7607
100976               chicken            1995      OK205880     28159-398

       Genotype_official             Geo_Location  \
0             Unassigned    Brazil: SapucaiaSulBR
8             Unassigned     Brazil: MontenegroBR
16            Unassigned     Brazil: MateusLemeBR
24            Unassigned     Brazil: MateusLemeBR
32            Unassigned     Brazil: MontenegroBR
...                  ...                      ...
100944        Unassigned  Mexico: San Luis Potosi
100952        Unassigned          Mexico: Tabasco
100960        Unassigned         Mexico: Veracruz
100968        Unassigned         Mexico: Veracruz
100976        Unassigned         Mexico: Veracruz

                                              full_header  \
0       >Influenza A virus |Brazil: SapucaiaSulBR|1246...
8       >Influenza A virus |Brazil: MontenegroBR|1245-...
16      >Influenza A virus |Brazil: MateusLemeBR|1367-...
24      >Influenza A virus |Brazil: MateusLemeBR|1369-...
32      >Influenza A virus |Brazil: MontenegroBR|1355-...
...                                                   ...
100944  >Influenza A virus |Mexico: San Luis Potosi|76...
100952  >Influenza A virus |Mexico: Tabasco|234-8289|H...
100960  >Influenza A virus |Mexico: Veracruz|232-6169|...
100968  >Influenza A virus |Mexico: Veracruz|233-7607|...
100976  >Influenza A virus |Mexico: Veracruz|28159-398...

                                                 sequence  ... File Name  \
0       AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...  ...
8       AGCGAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...  ...
16      AGCRAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAGAGAAC...  ...
24      AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAGAGAAC...  ...
32      AGCRAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...  ...
...                                                   ...  ...       ...
100944  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...  ...
100952  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...  ...
100960  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAGC...  ...
100968  AGCGAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...  ...
100976  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...  ...

                                           Partial_Header  \
0       Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
8       Influenza_A_virus__Brazil__MontenegroBR_1245_N...
16      Influenza_A_virus__Brazil__MateusLemeBR_1367_N...
24      Influenza_A_virus__Brazil__MateusLemeBR_1369_T...
32      Influenza_A_virus__Brazil__MontenegroBR_1355_N...
...                                                   ...
100944  Influenza_A_virus__Mexico__San_Luis_Potosi_765...
100952  Influenza_A_virus__Mexico__Tabasco_234_8289_H5...
100960  Influenza_A_virus__Mexico__Veracruz_232_6169_H...
100968  Influenza_A_virus__Mexico__Veracruz_233_7607_H...
100976  Influenza_A_virus__Mexico__Veracruz_28159_398_...

                                                   Strain  \
0       Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
8       Influenza_A_virus__Brazil__MontenegroBR_1245_N...
16      Influenza_A_virus__Brazil__MateusLemeBR_1367_N...
24      Influenza_A_virus__Brazil__MateusLemeBR_1369_T...
32      Influenza_A_virus__Brazil__MontenegroBR_1355_N...
...                                                   ...
100944
100952
100960
100968
100976

                                             genbank_name    Genotype  \
0       A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...  Unassigned
8          A/Gallus gallus/MontenegroBR/1245-N3-2025/2025  Unassigned
16         A/Cygnus atratus/MateusLemeBR/1367-N-2025/2025  Unassigned
24         A/Cygnus atratus/MateusLemeBR/1369-T-2025/2025  Unassigned
32        A/Furnarius rufus/MontenegroBR/1355-N-2025/2025  Unassigned
...                                                   ...         ...
100944                A/chicken/San Luis Potosi/7651/1996  Unassigned
100952                    A/chicken/Tabasco/234-8289/1998  Unassigned
100960                   A/chicken/Veracruz/232-6169/1998  Unassigned
100968                   A/chicken/Veracruz/233-7607/1998  Unassigned
100976                  A/chicken/Veracruz/28159-398/1995  Unassigned

             Host_Type Years     Geo_Location_Abrv  \
0           wild_avian  2025  Brazil-SapucaiaSulBR