# Cleaning Downloaded Data from avian-flu

Author: Alexander Maksiaev

Purpose: Clean downloaded data from avian-flu, rename sequences according to convention, de-duplicate from GISAID

In [1]:
# Housekeeping

import os
import glob 
import pandas as pd
import xml.etree.ElementTree as ET
import requests
import time
import numpy as np
import dateutil 
from datetime import datetime
from collections import defaultdict 
import importlib
import utils  
importlib.reload(utils)
from utils import * 


# Dates
start_date = "06-14-2025"
end_date = "06-20-2025"
date_range = start_date + "--" + end_date
# update_date = "06-18-2025"

# Make sure you have the correct paths

home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/"
downloads = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/"
# downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
references = home + "references/"
originals = downloads + "Andersen/"
saved = originals + "saved/"
temp_files = originals + "temp/"
complete_files = downloads + "complete/"

os.chdir(downloads)

## Read Metadata

In [8]:
# Read metadata

os.chdir(saved)
metadata_normalized = pd.read_csv("metadata_normalized.tsv", delimiter="\t") # Collection dates

metadata_folder = originals + "avian-influenza/metadata/"
os.chdir(metadata_folder)

metadata = pd.read_csv("SraRunTable_automated.csv")

print(len(metadata)) # 7397 rows

metadata = metadata.merge(metadata_normalized, how="outer")
print(metadata.columns)

metadata["name_state"] = metadata["geo_loc_name"].apply(lambda x: x.split("/")[1] if len(x.split("/")) > 1 else x.split("/")[0])

# Find only >= last date using Release Date from metadata 
metadata["ReleaseDate"] = metadata["ReleaseDate"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y-%m-%d"))
metadata = metadata[metadata["ReleaseDate"] >= dateutil.parser.parse(start_date).strftime("%Y-%m-%d")]
# Find only <= update date using Release Date from metadata
metadata = metadata[metadata["ReleaseDate"] <= dateutil.parser.parse(end_date).strftime("%Y-%m-%d")]

print(len(metadata)) # 6053 rows between 1/1/2024 and 4/14/2025
display(metadata)
print(metadata["Library Name"])

9759
Index(['Run', 'Assay Type', 'AvgSpotLen', 'Bases', 'BioProject', 'BioSample',
       'BioSampleModel', 'Bytes', 'Center Name', 'Collection_Date', 'Consent',
       'DATASTORE filetype', 'DATASTORE provider', 'DATASTORE region',
       'Experiment', 'geo_loc_name_country', 'geo_loc_name_country_continent',
       'geo_loc_name', 'Host', 'Instrument', 'isolate', 'Library Name',
       'LibraryLayout', 'LibrarySelection', 'LibrarySource', 'Organism',
       'Platform', 'ReleaseDate', 'create_date', 'version', 'Sample Name',
       'SRA Study', 'serotype', 'isolation_source', 'BioSample Accession',
       'is_retracted', 'retraction_detection_date_utc'],
      dtype='object')
0

Empty DataFrame
Columns: [Run, Assay Type, AvgSpotLen, Bases, BioProject, BioSample, BioSampleModel, Bytes, Center Name, Collection_Date, Consent, DATASTORE filetype, DATASTORE provider, DATASTORE region, Experiment, geo_loc_name_country, geo_loc_name_country_continent, geo_loc_name, Host, Instrument, isolate, Library Name, LibraryLayout, LibrarySelection, LibrarySource, Organism, Platform, ReleaseDate, create_date, version, Sample Name, SRA Study, serotype, isolation_source, BioSample Accession, is_retracted, retraction_detection_date_utc, name_state]
Index: []

[0 rows x 38 columns]

Series([], Name: Library Name, dtype: object)

In [3]:
# Get list of genotypes

os.chdir(home + "references/")

# genotypes_df = pd.read_excel("genotype_key.xlsx")

# genotypes = list(genotypes_df["Genotype"])

# print(genotypes)

genotypes = ["B3.13", "D1.1"]

# genotypes = ["B3.2"] #, "B3.2", "B3.6", "B3.7", "B3.5", "A3"]

### Naming convention ###
>A/[host]/[geo_loc_name]/[isolate]/[year]|[serotype: H5N1]|[collection_date]|[host_type]|[genotype]

host_type is from manual animal reference

In metadata, we have: host, geo_loc_name, isolate, year

We need: geo_loc_name, collection_date, host_type, genotype

host = Host

geo_loc_name (primary) = geo_loc_name

geo_loc_name (secondary) = genbank_mapping.tsv > genbank_name

isolate = isolate

collection date (primary) = Collection_Date

collection date (secondary) = https://www.ncbi.nlm.nih.gov/genbank/ > BioSample (input: BioSample) > Nucleotide > [first result] > collection_date

serotype = serotype

host type = [from ref] 

genotype = [from genoflu] -- use genoflu_results.tsv

## Get genotype, specific geolocation

In [4]:
# Get genotype from genoflu_results.tsv

os.chdir(metadata_folder)

genoflu_results = pd.read_csv("genoflu_results.tsv", delimiter="\t")

genoflu_results["Run"] = genoflu_results["sample"]

metadata = metadata.merge(genoflu_results, on="Run", how="inner")
print(metadata)
# metadata = metadata[~metadata["Genotype"].str.contains('Not assigned')] # Do not include non-assigned genotypes
metadata = metadata[metadata["Genotype"].isin(genotypes)]

# Get only the genotypes we want: B3.13 and D1.1

# b313_and_d11_only = genoflu_results[(genoflu_results["Genotype"] == "B3.13") | (genoflu_results["Genotype"] == "D1.1")]
# b313_and_d11_only = b313_and_d11_only.rename(columns={"sample": "Run"})
# b313_and_d11_only = b313_and_d11_only.drop_duplicates(subset="Run", keep="last")

# metadata = metadata.merge(b313_and_d11_only, on=["Run", "Genotype"], how="inner")

print(len(metadata)) 

display(metadata)

Empty DataFrame
Columns: [Run, Assay Type, AvgSpotLen, Bases, BioProject, BioSample, BioSampleModel, Bytes, Center Name, Collection_Date, Consent, DATASTORE filetype, DATASTORE provider, DATASTORE region, Experiment, geo_loc_name_country, geo_loc_name_country_continent, geo_loc_name, Host, Instrument, isolate, Library Name, LibraryLayout, LibrarySelection, LibrarySource, Organism, Platform, ReleaseDate, create_date, version, Sample Name, SRA Study, serotype, isolation_source, BioSample Accession, is_retracted, retraction_detection_date_utc, name_state, sample, date, File Name, Genotype, Genotype List Used, >=98.0%, Genotype Sample Title List, Genotype Percent Match List, Genotype Mismatch List, Genotype Average Depth of Coverage List]
Index: []

[0 rows x 47 columns]
0

Empty DataFrame
Columns: [Run, Assay Type, AvgSpotLen, Bases, BioProject, BioSample, BioSampleModel, Bytes, Center Name, Collection_Date, Consent, DATASTORE filetype, DATASTORE provider, DATASTORE region, Experiment, geo_loc_name_country, geo_loc_name_country_continent, geo_loc_name, Host, Instrument, isolate, Library Name, LibraryLayout, LibrarySelection, LibrarySource, Organism, Platform, ReleaseDate, create_date, version, Sample Name, SRA Study, serotype, isolation_source, BioSample Accession, is_retracted, retraction_detection_date_utc, name_state, sample, date, File Name, Genotype, Genotype List Used, >=98.0%, Genotype Sample Title List, Genotype Percent Match List, Genotype Mismatch List, Genotype Average Depth of Coverage List]
Index: []

[0 rows x 47 columns]

In [5]:
# Get specific geolocation and name_state from genbank_mapping.tsv

genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
genbank_mapping["Run"] = genbank_mapping["sra_run"]
genbank_mapping = genbank_mapping.drop_duplicates(subset="Run", keep="first") # Drop duplicates
genbank_mapping["name_state"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[2]) # Get the name of the state

# print(genbank_mapping)

# metadata_genbank = metadata.merge(genbank_mapping, on=["Run"]) # Only include data that has states

# Get geolocation for second state attribute

os.chdir(home + "references/")
state_ref = pd.read_csv("states_ref.csv")
metadata["Geo_Location"] = metadata["name_state"].apply(lambda x: state_ref.loc[state_ref["Abbreviation"] == x, 'Country'].iloc[0] + "-" + x if x in state_ref["Abbreviation"].values else state_ref.loc[state_ref["State"] == x, 'Country'].iloc[0] + "-" + state_ref.loc[state_ref["State"] == x, 'Abbreviation'].iloc[0] if x in state_ref["State"].values else x)


print(metadata["name_state"])
print(len(metadata))
display(metadata) # Maybe there is no state information since 3/18/2025?

Series([], Name: name_state, dtype: object)
0

Empty DataFrame
Columns: [Run, Assay Type, AvgSpotLen, Bases, BioProject, BioSample, BioSampleModel, Bytes, Center Name, Collection_Date, Consent, DATASTORE filetype, DATASTORE provider, DATASTORE region, Experiment, geo_loc_name_country, geo_loc_name_country_continent, geo_loc_name, Host, Instrument, isolate, Library Name, LibraryLayout, LibrarySelection, LibrarySource, Organism, Platform, ReleaseDate, create_date, version, Sample Name, SRA Study, serotype, isolation_source, BioSample Accession, is_retracted, retraction_detection_date_utc, name_state, sample, date, File Name, Genotype, Genotype List Used, >=98.0%, Genotype Sample Title List, Genotype Percent Match List, Genotype Mismatch List, Genotype Average Depth of Coverage List, Geo_Location]
Index: []

[0 rows x 48 columns]

In [6]:
# # If no states

# metadata_genbank = metadata

# metadata_genbank["name_state"] = "USA"

# metadata_genbank["Geo_Location"] = "USA"

# display(metadata_genbank)

## Collection Dates

If date is N/A, try finding it first

In [7]:

# Get all dates
metadata["Collection_Date_Specific"] = metadata["BioSample"].apply(lambda x: search_collection_date(x, metadata) if "-" not in x else x)

# # Save this so we don't have to do it again

# # os.chdir(temp_files)
# metadata.to_csv("metadata_genbank.csv")

In [ ]:
# os.chdir(saved)
# metadata = pd.read_csv("metadata_genbank_" + date_range + ".csv")

FileNotFoundError: [Errno 2] No such file or directory: 'metadata_genbank_06-13-2025--06-20-2025.csv'

In [9]:
date = "2025" 

date = dateutil.parser.parse(date, default=datetime(2000, 1, 1))

print(date.month)

1

In [10]:
# # # Upload saved data -- if doing this, make sure the above cell is commented out
# # os.chdir(temp_files + "saved/")
# # metadata_genbank = pd.read_csv("metadata_genbank.csv")
# # os.chdir(temp_files)

# # Get only updated dates

# # unknown_dates = metadata[(metadata["Collection_Date"] == "2024") | (metadata["Collection_Date"] == "2025")] # Dates we don't have

# def find_known_dates(x, df):
    
#     try:
#         date = metadata[metadata["BioSample"] == x]["Collection_Date"].values[0]
#     # print(date)
#         # print(date)
#         # if len(str(date)) == 4: # If this is just a year
#         #     date = search_collection_date(x, df)
#         # else:
#         date = dateutil.parser.parse(date, default=datetime(2000, 1, 1)) # .strftime("%Y-%m-%d") # If a date already exists
#         if date.day == dateutil.parser.parse("1/1/2000").day and date.month == dateutil.parser.parse("1/1/2000").month:
#             print("year only")
#             date = search_collection_date(x, df)
#         print("Success", date)
#     except:
#         date = search_collection_date(x, df) # If it's not parseable as a date
#     return date # If statement in lambda function will search for the "just year" values
        

# # years = ["2021", "2022", "2023", "2024", "2025"]
# # unknown_dates = metadata[metadata["Collection_Date"].isin(years)]
# # # known_dates = metadata[(metadata["Collection_Date"] != "2024") & (metadata["Collection_Date"] != "2025")] # Dates we've already gotten
# # known_dates = metadata[~metadata["Collection_Date"].isin(years)]

# # Get new dates also 
# # new_dates = metadata["BioSample"].apply(lambda x: search_collection_date(x, metadata_genbank) if )

# updated_dates = metadata["BioSample"].apply(lambda x: find_known_dates(x, metadata)) # Update unknown dates, if possible
# metadata["Collection_Date"] = updated_dates

# # metadata = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # updated_unknown_dates = unknown_dates["BioSample"].apply(lambda x: search_collection_date(x, unknown_dates)) # Update unknown dates, if possible
# # unknown_dates["Collection_Date"] = updated_unknown_dates

# # metadata = pd.concat([known_dates, unknown_dates], ignore_index=True, sort=True)

# # Save this so we don't have to do it again

# # os.chdir(temp_files)
# # metadata.to_csv("metadata_genbank_" + date_range + ".csv")

# # display(metadata)

In [11]:
# os.chdir(temp_files)
# metadata.to_csv("metadata_genbank_" + date_range + ".csv")

# If no collection dates

# metadata_genbank["Collection_Date_Specific"] = metadata_genbank["Collection_Date"]

## Get host type

In [14]:
# create a mask, where is True if the host does not exist
print(metadata["Host"])

mask = metadata["Host"].isna()

# choose between the original value and split isolate using the mask
metadata["Host"] = np.where(mask, metadata["isolate"].apply(lambda x: x if x != x or "/" not in x or len(x.split("/")) < 2 else x.split("/")[1]), metadata["Host"]) #  if "/" in metadata["isolate"] else metadata["Host"])
metadata["Host"] = metadata["Host"].apply(lambda x: x.lower() if x == x else x)

# print(metadata["Host"])

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

# print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

os.chdir(home + "references/")

animals_ref = pd.read_csv("animals_ref.csv") # Upload animals ref

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference 

print(metadata["Host"])
# print(metadata["isolate"])

0             Canada Goose
1        Branta canadensis
2                  Gadwall
3          Mareca strepera
4            Backyard bird
               ...
18077               CATTLE
18078               CATTLE
18079               CATTLE
18080               CATTLE
18081               CATTLE
Name: Host, Length: 18082, dtype: object
[]
                      avian               cattle        feline   other_mammal  \
0          great_horned_owl            dairy_cow           cat     deer mouse
1              common_raven               cattle  domestic_cat    house_mouse
2             cooper's_hawk  cattle milk product     feral_cat          skunk
3              coopers_hawk          bovine_milk        feline  striped_skunk
4                   peafowl              bovine   domestic-cat     norway rat
..                      ...                  ...           ...            ...
523           backyard bird                  NaN           NaN            NaN
524  american white pelican                  NaN           NaN            NaN
525        peregrine falcon                  NaN           NaN            NaN
526             baikal teal                  NaN           NaN            NaN
527             black swift                  NaN           NaN            NaN

          human         other  new
0    washington         mixed  NaN
1        nevada   environment  NaN
2       wyoming  multispecies  NaN
3    california       unknown  NaN
4      michigan             -  NaN
..          ...           ...  ...
523         NaN           NaN  NaN
524         NaN           NaN  NaN
525         NaN           NaN  NaN
526         NaN           NaN  NaN
527         NaN           NaN  NaN

[528 rows x 7 columns]
0             canada goose
1        branta canadensis
2                  gadwall
3          mareca strepera
4            backyard bird
               ...
18077               cattle
18078               cattle
18079               cattle
18080               cattle
18081               cattle
Name: Host, Length: 18082, dtype: object

In [15]:
# Get animals from animal reference
os.chdir(downloads)
animals_ref = pd.read_csv("animals_ref.csv")
fix_animals_andersen(metadata, animals_ref) # Get host type

# metadata["years"] = metadata["Collection_Date"].apply(lambda x: str(x).split("-")[0]) # Get year only from collection date

## Make names using all the attributes we collected

In [16]:
for num, collection_date in enumerate(metadata["Collection_Date"]):
    if collection_date != collection_date: # if nan
         collection_date = "missing"
    try:
        print(collection_date)
        if collection_date.month == datetime.parser.parse("1/1/2000").month and collection_date.day == datetime.parser.parse("1/1/2000").day:
            # If not a valid collection date, but has year
            
            year = collection_date.year
            metadata.loc[num, "Collection_Date"] = year
            # if collection_date != collection_date: # If nan
        #     metadata.loc[num, "Collection_Date"] = metadata.loc[num, "years"]
        else: # If actual date
                
            # if len(str(collection_date)) == 4: # If it's a year
                # print("caught")
                metadata.loc[num, "Collection_Date"] = collection_date
    except:
         metadata.loc[num, "Collection_Date"] = collection_date
        # else:
        #     try:
        #         parsed_date = dateutil.parser.parse(collection_date)
        #         date = parsed_date.strftime("%Y-%m-%d") # Make sure it doesn't default to today, if just a year
        #         metadata.loc[num, "Collection_Date"] = date
        #     except: # If no date at all
        #         metadata.loc[num, "Collection_Date"] = collection_date

    # metadata = metadata.dropna(thresh=2)

missing
missing
2022-02-08 00:00:00
2022-02-08 00:00:00
2022-02-17 00:00:00
2022-02-17 00:00:00
2022-02-21 00:00:00
2022-02-21 00:00:00
2022-02-16 00:00:00
2022-02-16 00:00:00
2022-02-16 00:00:00
2022-02-16 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-02-16 00:00:00
2022-02-16 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-07 00:00:00
2022-02-07 00:00:00
2022-02-07 00:00:00
2022-02-07 00:00:00
2022-02-07 00:00:00
2022-02-07 00:00:00
2022-04-05 00:00:00
2022-04-05 00:00:00
2022-01-29 00:00:00
2022-01-29 00:00:00
2022-04-06 00:00:00
2022-04-06 00:00:00
2022-04-05 00:00:00
2022-04-05 00:00:00
2022-04-05 00:00:00
2022-04-05 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-03-30 00:00:00
2022-03-30 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-04-01 00:00:00
2022-04-01 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-01-31 00:00:00
2022-01-31 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-02-01 00:00:00
2022-02-01 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-05 00:00:00
2022-04-05 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-01-29 00:00:00
2022-01-29 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-04-01 00:00:00
2022-04-01 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-01-29 00:00:00
2022-01-29 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-01-29 00:00:00
2022-01-29 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-02-07 00:00:00
2022-02-07 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
missing
missing
missing
missing
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-01-22 00:00:00
2022-01-22 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-01-22 00:00:00
2022-01-22 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-03-30 00:00:00
2022-03-30 00:00:00
2022-03-30 00:00:00
2022-03-30 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-30 00:00:00
2022-03-30 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
missing
missing
2022-01-26 00:00:00
2022-01-26 00:00:00
missing
missing
2022-03-12 00:00:00
2022-03-12 00:00:00
2022-03-17 00:00:00
2022-03-17 00:00:00
missing
missing
missing
missing
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-03-30 00:00:00
2022-03-30 00:00:00
missing
missing
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-01-22 00:00:00
2022-01-22 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-01-15 00:00:00
2022-01-15 00:00:00
2022-03-24 00:00:00
2022-03-24 00:00:00
2022-03-24 00:00:00
2022-03-24 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-15 00:00:00
2022-03-15 00:00:00
2022-03-15 00:00:00
2022-03-15 00:00:00
missing
missing
missing
missing
2022-03-01 00:00:00
2022-03-01 00:00:00
2022-01-15 00:00:00
2022-01-15 00:00:00
missing
missing
2022-02-07 00:00:00
2022-02-07 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2021-12-30 00:00:00
2021-12-30 00:00:00
2021-12-30 00:00:00
2021-12-30 00:00:00
missing
missing
missing
missing
missing
missing
missing
missing
missing
missing
missing
missing
missing
missing
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-01-06 00:00:00
2022-01-06 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-01-06 00:00:00
2022-01-06 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
missing
missing
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-19 00:00:00
2022-03-19 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-13 00:00:00
2022-03-13 00:00:00
2022-03-15 00:00:00
2022-03-15 00:00:00
2022-03-17 00:00:00
2022-03-17 00:00:00
2022-03-17 00:00:00
2022-03-17 00:00:00
2022-03-17 00:00:00
2022-03-17 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-03-11 00:00:00
2022-03-11 00:00:00
2022-03-04 00:00:00
2022-03-04 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-03-12 00:00:00
2022-03-12 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-02-23 00:00:00
2022-02-23 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-01 00:00:00
2022-03-01 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
2022-03-06 00:00:00
2022-03-06 00:00:00
2022-03-04 00:00:00
2022-03-04 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-03-08 00:00:00
2022-03-08 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-03-02 00:00:00
2022-03-02 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-03-04 00:00:00
2022-03-04 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-02-23 00:00:00
2022-02-23 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-03-06 00:00:00
2022-03-06 00:00:00
2022-02-24 00:00:00
2022-02-24 00:00:00
missing
missing
missing
missing
2022-02-18 00:00:00
2022-02-18 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-02 00:00:00
2022-03-02 00:00:00
2022-03-02 00:00:00
2022-03-02 00:00:00
2022-03-02 00:00:00
2022-03-02 00:00:00
2022-03-02 00:00:00
2022-03-02 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
missing
missing
2022-02-24 00:00:00
2022-02-24 00:00:00
2022-02-24 00:00:00
2022-02-24 00:00:00
2022-02-24 00:00:00
2022-02-24 00:00:00
2022-02-24 00:00:00
2022-02-24 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-23 00:00:00
2022-02-23 00:00:00
2022-02-12 00:00:00
2022-02-12 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-03-01 00:00:00
2022-03-01 00:00:00
2022-02-26 00:00:00
2022-02-26 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-02-26 00:00:00
2022-02-26 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-22 00:00:00
2022-02-24 00:00:00
2022-02-24 00:00:00
2022-02-28 00:00:00
2022-02-28 00:00:00
2022-02-12 00:00:00
2022-02-12 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-04-01 00:00:00
2022-04-01 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-04-04 00:00:00
2022-04-04 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
missing
missing
2022-01-30 00:00:00
2022-01-30 00:00:00
missing
missing
missing
missing
missing
missing
missing
missing
missing
missing
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-01 00:00:00
2022-04-01 00:00:00
2022-04-01 00:00:00
2022-04-01 00:00:00
2022-01-29 00:00:00
2022-01-29 00:00:00
2022-04-01 00:00:00
2022-04-01 00:00:00
2022-01-21 00:00:00
2022-01-21 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-04-01 00:00:00
2022-04-01 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-01 00:00:00
2022-04-01 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-04-01 00:00:00
2022-04-01 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-01-29 00:00:00
2022-01-29 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
missing
missing
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-30 00:00:00
2022-03-30 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-04-01 00:00:00
2022-04-01 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-30 00:00:00
2022-03-30 00:00:00
2022-04-03 00:00:00
2022-04-03 00:00:00
2022-03-30 00:00:00
2022-03-30 00:00:00
2022-03-24 00:00:00
2022-03-24 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-04-02 00:00:00
2022-04-02 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-31 00:00:00
2022-03-29 00:00:00
2022-03-29 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-20 00:00:00
2022-03-20 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-20 00:00:00
2022-03-20 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
missing
missing
2022-03-18 00:00:00
2022-03-18 00:00:00
missing
missing
2022-01-26 00:00:00
2022-01-26 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-17 00:00:00
2022-03-17 00:00:00
2022-03-21 00:00:00
2022-03-21 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-22 00:00:00
2022-03-22 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-15 00:00:00
2022-03-15 00:00:00
2022-01-06 00:00:00
2022-01-06 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-15 00:00:00
2022-03-15 00:00:00
2022-03-15 00:00:00
2022-03-15 00:00:00
2022-03-19 00:00:00
2022-03-19 00:00:00
2022-03-19 00:00:00
2022-03-19 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-18 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-01-06 00:00:00
2022-01-06 00:00:00
2022-03-16 00:00:00
2022-03-16 00:00:00
2022-03-15 00:00:00
2022-03-15 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-03-17 00:00:00
2022-03-17 00:00:00
2022-03-17 00:00:00
2022-03-17 00:00:00
2022-03-15 00:00:00
2022-03-15 00:00:00
2022-03-04 00:00:00
2022-03-04 00:00:00
2022-03-04 00:00:00
2022-03-04 00:00:00
2022-03-07 00:00:00
2022-03-07 00:00:00
2022-03-06 00:00:00
2022-03-06 00:00:00
2022-03-06 00:00:00
2022-03-06 00:00:00
2022-03-06 00:00:00
2022-03-06 00:00:00
2022-03-04 00:00:00
2022-03-04 00:00:00
2022-03-03 00:00:00
2022-03-03 00:00:00
2022-03-02 00:00:00
2022-03-02 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-03-02 00:00:00
2022-03-02 00:00:00
2022-03-01 00:00:00
2022-03-01 00:00:00
2022-03-06 00:00:00
2022-03-06 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-10 00:00:00
2022-03-10 00:00:00
2022-03-10 00:00:00
2022-03-10 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-14 00:00:00
2022-03-08 00:00:00
2022-03-08 00:00:00
2022-03-11 00:00:00
2022-03-11 00:00:00
2022-03-08 00:00:00
2022-03-08 00:00:00
2022-03-13 00:00:00
2022-03-13 00:00:00
2022-03-13 00:00:00
2022-03-13 00:00:00
2022-03-13 00:00:00
2022-03-13 00:00:00
2022-03-11 00:00:00
2022-03-11 00:00:00
2022-03-02 00:00:00
2022-03-02 00:00:00
2022-01-08 00:00:00
2022-01-08 00:00:00
missing
missing
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-24 00:00:00
2022-03-24 00:00:00
2022-01-14 00:00:00
2022-01-14 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-27 00:00:00
2022-03-27 00:00:00
2022-03-23 00:00:00
2022-03-23 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
2022-03-09 00:00:00
2022-03-08 00:00:00
2022-03-08 00:00:00
2022-03-08 00:00:00
2022-03-08 00:00:00
2022-03-08 00:00:00
2022-03-08 00:00:00
2022-03-04 00:00:00
2022-03-04 00:00:00
2022-03-04 00:00:00
2022-03-04 00:00:00
2022-01-23 00:00:00
2022-01-23 00:00:00
2022-03-24 00:00:00
2022-03-24 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-26 00:00:00
2022-03-28 00:00:00
2022-03-28 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-25 00:00:00
2022-03-24 00:00:00
2022-03-24 00:00:00
missing

In [17]:
# Make names

metadata = metadata.fillna("")

# + metadata["BioSample"] + "|" 
names = ">" + metadata["Run"] + "|" + "A/" + metadata["Host"] + "/" + metadata["name_state"] + "/" + metadata["Library Name"] + "/" + metadata["years"].apply(lambda x: str(x)) + "|" + metadata["serotype"] + "|" + metadata["Geo_Location"] + "|" + metadata["Collection_Date"].apply(lambda x: str(x)) + "|" + metadata["Host_Type"] + "|" + metadata["Genotype"]

metadata["Name"] = names

# metadata_genbank.to_csv("metadata_genbank_named.csv")

display(metadata["Name"])

0        >SRR24839058|A/canada goose/Massachusetts/22-0...
1        >SRR24839058|A/branta canadensis/USA: Massachu...
2        >SRR24839059|A/gadwall/Kentucky/22-005154-004/...
3        >SRR24839059|A/mareca strepera/USA: Kentucky, ...
4        >SRR24839060|A/backyard bird/Maine/22-005158-0...
                               ...
18077    >SRR33830443|A/cattle/USA/25-015681-003-origin...
18078    >SRR33830444|A/cattle/USA/25-015681-002-origin...
18079    >SRR33830445|A/cattle/USA/25-015681-001-origin...
18080    >SRR33830449|A/cattle/USA/24-036379-001-tile/2...
18081    >SRR33830450|A/cattle/USA/24-034788-001-tile/2...
Name: Name, Length: 18082, dtype: object

In [18]:
# Drop duplicate runs 
metadata = metadata.drop_duplicates(subset="Run", keep="first")

In [19]:
print(metadata)

       Unnamed: 0.1  Unnamed: 0 Assay Type AvgSpotLen      Bases  \
0                 0           0   AMPLICON     230.77   32942716
2                 2           2   AMPLICON     207.54   53993591
4                 4           4   AMPLICON     201.66   21703662
6                 6           6   AMPLICON     209.57   46055893
8                 8           8   AMPLICON     237.36   26794193
...             ...         ...        ...        ...        ...
18077         18077       18077        WGS     148.11  100597029
18078         18078       18078        WGS      148.5  131987248
18079         18079       18079        WGS     148.12  115677479
18080         18080       18080        WGS     131.52   67358891
18081         18081       18081        WGS     131.13   69602732

         BioProject     BioSample BioSample Accession BioSampleModel  \
0       PRJNA980729  SAMN35647642         SRS17903639          Viral
2       PRJNA980729  SAMN35647620         SRS17903636          Viral
4       PRJNA980729  SAMN35647621         SRS17903631          Viral
6       PRJNA980729  SAMN35647622         SRS17903632          Viral
8       PRJNA980729  SAMN35647623         SRS17903627          Viral
...             ...           ...                 ...            ...
18077  PRJNA1102327  SAMN48895429         SRS25266467          Viral
18078  PRJNA1102327  SAMN48895428         SRS25266466          Viral
18079  PRJNA1102327  SAMN48895427         SRS25266465          Viral
18080  PRJNA1102327  SAMN48895415         SRS25266461          Viral
18081  PRJNA1102327  SAMN48895414         SRS25266460          Viral

          Bytes  ...                                          isolate  \
0      18373327  ...  A/Canada Goose/Massachusetts/22-005893-001/2022
2      29609119  ...            A/Gadwall/Kentucky/22-005154-004/2022
4      10716272  ...         A/Backyard bird/Maine/22-005158-001/2022
6      23524044  ...            A/Chicken/Delaware/22-005260-001/2022
8      16149521  ...              A/Turkey/Indiana/22-005289-001/2022
...         ...  ...                                              ...
18077  39710063  ...                                    25-015681-003
18078  51617990  ...                                    25-015681-002
18079  45674405  ...                                    25-015681-001
18080  26336550  ...                               24-036379-001-tile
18081  27556171  ...                               24-034788-001-tile

      isolation_source     name_state retraction_detection_date_utc  \
0                    ,  Massachusetts
2                   ,/       Kentucky
4                               Maine
6                    ,       Delaware
8                    ,        Indiana
...                ...            ...                           ...
18077  MILK, BULK TANK            USA
18078  MILK, BULK TANK            USA
18079  MILK, BULK TANK            USA
18080  MILK, BULK TANK            USA
18081  MILK, BULK TANK            USA

            sample serotype version Host_Type    years  \
0      SRR24839058     H5N1       1     avian  missing
2      SRR24839059     H5N1       1     avian     2022
4      SRR24839060     H5N1       1     other     2022
6      SRR24839061     H5N1       1     avian     2022
8      SRR24839062     H5N1       1     avian     2022
...            ...      ...     ...       ...      ...
18077  SRR33830443                1    cattle     2025
18078  SRR33830444                1    cattle     2025
18079  SRR33830445                1    cattle     2025
18080  SRR33830449                1    cattle     2024
18081  SRR33830450                1    cattle     2024

                                                    Name
0      >SRR24839058|A/canada goose/Massachusetts/22-0...
2      >SRR24839059|A/gadwall/Kentucky/22-005154-004/...
4      >SRR24839060|A/backyard bird/Maine/22-005158-0...
6      >SRR24839061|A/chicken/Delaware/22-005260-001/...
8      >SRR24839062|A/turkey/Indiana/22-005289-001/20...
...                                                  ...
18077  >SRR33830443|A/cattle/USA/25-015681-003-origin...
18078  >SRR33830444|A/cattle/USA/25-015681-002-origin...
18079  >SRR33830445|A/cattle/USA/25-015681-001-origin...
18080  >SRR33830449|A/cattle/USA/24-036379-001-tile/2...
18081  >SRR33830450|A/cattle/USA/24-034788-001-tile/2...

[9203 rows x 53 columns]

## Make FASTA files

In [ ]:
# Get information to create the fasta files

fasta_folder = originals + "avian-influenza/fasta/"

os.chdir(fasta_folder)

segments = ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]
pairs = []
fasta_files = {}

for genotype in genotypes: # ["B3.13", "D1.1"]:
    for segment in segments:
        pair = genotype + "_" + segment
        pairs.append(pair)

for pair in pairs:
    fasta_files[pair] = [] # List to hold fasta files

for run in metadata["Run"].values: # For each run 
    for dirpath, dirs, files in os.walk(fasta_folder): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            # print(file_name)
            if run in file_name: # Note that there will be ~8 files total with that run name
                # Make a fasta file and put it in the list
                with open(file_name) as f:
                    lines = f.readlines()
                    sequence = lines[1] 
                    # Each run/segment pair has one sequence -- it's placed into a file with other run/segment pairs with the same segment and genotype
                    header = metadata[metadata["Run"] == run].loc[:, "Name"].values[0]
                    genotype = metadata[metadata["Run"] == run].loc[:, "Genotype"].values[0]
                    # print(header)
                    # print(genotype)
                    # break 
                    segment = file_name.split("_")[-2]
                    # Find the pair that corresponds to 
                    pair_name = genotype + "_" + segment
                    this_specific_fasta = []
                    for pair in pairs:
                        # print(pair)
                        # print(pair_name)
                        if pair_name == pair:
                            this_specific_fasta.append(header)
                            this_specific_fasta.append(sequence)
                            fasta_files[pair].append(this_specific_fasta)
                f.close()
        break

In [ ]:
# print(fasta_files.keys())

In [ ]:
# Create fasta files 

# os.chdir(complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/")
os.chdir(originals + "complete/")
names = []
for pair in fasta_files.keys():
    # output_path = complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/" + pair + "_andersen_updated_" + update_date + ".fasta" 
    output_path = originals + "complete/" + pair + "_" + date_range + "_andersen_updated.fasta"

    output_file = open(output_path, "w")
    for item in fasta_files[pair]:
        # for item in item:
        # item = fasta_files[pair]
        try:
            name = str(item[0].values[0]) # See if this is one we didn't have a collection date for
        except:
            name = str(item[0])
        print(name)
        names.append(name)
        # First is header, second is sequence
        # print(value)
        output_file.write(name + "\n")
        output_file.write(item[1])
    output_file.close()

print(len(names)/8)

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839171|A/./Massachusetts/A/Backyard bird/Massachusetts/22-009371-001/2022/2022|H5N1|USA-MA|2022-03-25 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839298|A/./Nebraska/A/Swan/Nebraska/22-008227-001/2022/2022|H5N1|USA-NE|2022-03-13 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839316|A/./Kansas/A/Backyard bird/Kansas/22-008114-001/2022/2022|H5N1|USA-KS|2022-03-16 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839413|A/./Texas/A/Pheasant/Texas/22-010008-002/2022/2022|H5N1|USA-TX|2022-04-01 00:00:00|other|A1
nan
nan
>SRR24839416|A/./Texas/A/Pheasant/Texas/22-010008-001/2022/2022|H5N1|USA-TX|2022-04-01 00:00:00|other|A1
nan
nan
>SRR24839423|A/./Texas/A/Pheasant/Texas/22-009984-001/2022/2022|H5N1|USA-TX|2022-03-29 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839442|A/./Florida/A/Black Vulture/Florida/22-009936-001/2022/2022|H5N1|USA-FL|2022-03-27 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839476|A/./Maine/A/Backyard bird/Maine/22-009412-002/2022/2022|H5N1|USA-ME|2022-03-25 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839501|A/./Illinois/A/Graylag Goose/Illinois/22-008377-005/2022/2022|H5N1|USA-IL|2022-03-14 00:00:00|other|A1
>SRR24839502|A/./Illinois/A/Graylag Goose/Illinois/22-008377-002/2022/2022|H5N1|USA-IL|2022-03-14 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839551|A/./New York/A/Backyard bird/New York/22-009324-009/2022/2022|H5N1|USA-NY|2022-03-28 00:00:00|other|A1
nan
>SRR24839558|A/./Nebraska/A/Backyard bird/Nebraska/22-009190-001/2022/2022|H5N1|USA-NE|2022-03-24 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839628|A/./Florida/A/Gull/Florida/22-007915-006/2022/2022|H5N1|USA-FL|2022-03-01 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
>SRR24839652|A/./Illinois/A/Guineafowl/Illinois/22-007382-001/2022/2022|H5N1|USA-IL|2022-03-09 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839724|A/./New York/A/Backyard bird/New York/22-005647-001/2022/2022|H5N1|USA-NY|2022-02-19 00:00:00|other|A1
>SRR24839725|A/./New York/A/Backyard bird/New York/22-005647-002/2022/2022|H5N1|USA-NY|2022-02-19 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843008|A/./Missouri/A/Pelican/Missouri/22-012338-019/2022/missing|H5N1|USA-MO|missing|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843106|A/./Texas/A/Owl/Texas/22-012996-001/2022/2022|H5N1|USA-TX|2022-04-27 00:00:00|other|A1
nan
nan
>SRR24843142|A/./Missouri/A/Goose/Missouri/22-012338-006/2022/2022|H5N1|USA-MO|2022-03-15 00:00:00|other|A1
nan
>SRR24843264|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-004/2022/2022|H5N1|USA-PA|2022-04-28 00:00:00|other|A1
>SRR24843265|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-003/2022/2022|H5N1|USA-PA|2022-04-28 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839171|A/./Massachusetts/A/Backyard bird/Massachusetts/22-009371-001/2022/2022|H5N1|USA-MA|2022-03-25 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839298|A/./Nebraska/A/Swan/Nebraska/22-008227-001/2022/2022|H5N1|USA-NE|2022-03-13 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839316|A/./Kansas/A/Backyard bird/Kansas/22-008114-001/2022/2022|H5N1|USA-KS|2022-03-16 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839413|A/./Texas/A/Pheasant/Texas/22-010008-002/2022/2022|H5N1|USA-TX|2022-04-01 00:00:00|other|A1
nan
nan
>SRR24839416|A/./Texas/A/Pheasant/Texas/22-010008-001/2022/2022|H5N1|USA-TX|2022-04-01 00:00:00|other|A1
nan
nan
>SRR24839423|A/./Texas/A/Pheasant/Texas/22-009984-001/2022/2022|H5N1|USA-TX|2022-03-29 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839442|A/./Florida/A/Black Vulture/Florida/22-009936-001/2022/2022|H5N1|USA-FL|2022-03-27 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839476|A/./Maine/A/Backyard bird/Maine/22-009412-002/2022/2022|H5N1|USA-ME|2022-03-25 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839501|A/./Illinois/A/Graylag Goose/Illinois/22-008377-005/2022/2022|H5N1|USA-IL|2022-03-14 00:00:00|other|A1
>SRR24839502|A/./Illinois/A/Graylag Goose/Illinois/22-008377-002/2022/2022|H5N1|USA-IL|2022-03-14 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839551|A/./New York/A/Backyard bird/New York/22-009324-009/2022/2022|H5N1|USA-NY|2022-03-28 00:00:00|other|A1
nan
>SRR24839558|A/./Nebraska/A/Backyard bird/Nebraska/22-009190-001/2022/2022|H5N1|USA-NE|2022-03-24 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839628|A/./Florida/A/Gull/Florida/22-007915-006/2022/2022|H5N1|USA-FL|2022-03-01 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
>SRR24839652|A/./Illinois/A/Guineafowl/Illinois/22-007382-001/2022/2022|H5N1|USA-IL|2022-03-09 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839724|A/./New York/A/Backyard bird/New York/22-005647-001/2022/2022|H5N1|USA-NY|2022-02-19 00:00:00|other|A1
>SRR24839725|A/./New York/A/Backyard bird/New York/22-005647-002/2022/2022|H5N1|USA-NY|2022-02-19 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843008|A/./Missouri/A/Pelican/Missouri/22-012338-019/2022/missing|H5N1|USA-MO|missing|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843106|A/./Texas/A/Owl/Texas/22-012996-001/2022/2022|H5N1|USA-TX|2022-04-27 00:00:00|other|A1
nan
nan
>SRR24843142|A/./Missouri/A/Goose/Missouri/22-012338-006/2022/2022|H5N1|USA-MO|2022-03-15 00:00:00|other|A1
nan
>SRR24843264|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-004/2022/2022|H5N1|USA-PA|2022-04-28 00:00:00|other|A1
>SRR24843265|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-003/2022/2022|H5N1|USA-PA|2022-04-28 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839171|A/./Massachusetts/A/Backyard bird/Massachusetts/22-009371-001/2022/2022|H5N1|USA-MA|2022-03-25 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839298|A/./Nebraska/A/Swan/Nebraska/22-008227-001/2022/2022|H5N1|USA-NE|2022-03-13 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839316|A/./Kansas/A/Backyard bird/Kansas/22-008114-001/2022/2022|H5N1|USA-KS|2022-03-16 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839413|A/./Texas/A/Pheasant/Texas/22-010008-002/2022/2022|H5N1|USA-TX|2022-04-01 00:00:00|other|A1
nan
nan
>SRR24839416|A/./Texas/A/Pheasant/Texas/22-010008-001/2022/2022|H5N1|USA-TX|2022-04-01 00:00:00|other|A1
nan
nan
>SRR24839423|A/./Texas/A/Pheasant/Texas/22-009984-001/2022/2022|H5N1|USA-TX|2022-03-29 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839442|A/./Florida/A/Black Vulture/Florida/22-009936-001/2022/2022|H5N1|USA-FL|2022-03-27 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839476|A/./Maine/A/Backyard bird/Maine/22-009412-002/2022/2022|H5N1|USA-ME|2022-03-25 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839501|A/./Illinois/A/Graylag Goose/Illinois/22-008377-005/2022/2022|H5N1|USA-IL|2022-03-14 00:00:00|other|A1
>SRR24839502|A/./Illinois/A/Graylag Goose/Illinois/22-008377-002/2022/2022|H5N1|USA-IL|2022-03-14 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839551|A/./New York/A/Backyard bird/New York/22-009324-009/2022/2022|H5N1|USA-NY|2022-03-28 00:00:00|other|A1
nan
>SRR24839558|A/./Nebraska/A/Backyard bird/Nebraska/22-009190-001/2022/2022|H5N1|USA-NE|2022-03-24 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839628|A/./Florida/A/Gull/Florida/22-007915-006/2022/2022|H5N1|USA-FL|2022-03-01 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
>SRR24839652|A/./Illinois/A/Guineafowl/Illinois/22-007382-001/2022/2022|H5N1|USA-IL|2022-03-09 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839724|A/./New York/A/Backyard bird/New York/22-005647-001/2022/2022|H5N1|USA-NY|2022-02-19 00:00:00|other|A1
>SRR24839725|A/./New York/A/Backyard bird/New York/22-005647-002/2022/2022|H5N1|USA-NY|2022-02-19 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843008|A/./Missouri/A/Pelican/Missouri/22-012338-019/2022/missing|H5N1|USA-MO|missing|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843106|A/./Texas/A/Owl/Texas/22-012996-001/2022/2022|H5N1|USA-TX|2022-04-27 00:00:00|other|A1
nan
nan
>SRR24843142|A/./Missouri/A/Goose/Missouri/22-012338-006/2022/2022|H5N1|USA-MO|2022-03-15 00:00:00|other|A1
nan
>SRR24843264|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-004/2022/2022|H5N1|USA-PA|2022-04-28 00:00:00|other|A1
>SRR24843265|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-003/2022/2022|H5N1|USA-PA|2022-04-28 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839171|A/./Massachusetts/A/Backyard bird/Massachusetts/22-009371-001/2022/2022|H5N1|USA-MA|2022-03-25 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839298|A/./Nebraska/A/Swan/Nebraska/22-008227-001/2022/2022|H5N1|USA-NE|2022-03-13 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839316|A/./Kansas/A/Backyard bird/Kansas/22-008114-001/2022/2022|H5N1|USA-KS|2022-03-16 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839413|A/./Texas/A/Pheasant/Texas/22-010008-002/2022/2022|H5N1|USA-TX|2022-04-01 00:00:00|other|A1
nan
nan
>SRR24839416|A/./Texas/A/Pheasant/Texas/22-010008-001/2022/2022|H5N1|USA-TX|2022-04-01 00:00:00|other|A1
nan
nan
>SRR24839423|A/./Texas/A/Pheasant/Texas/22-009984-001/2022/2022|H5N1|USA-TX|2022-03-29 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839442|A/./Florida/A/Black Vulture/Florida/22-009936-001/2022/2022|H5N1|USA-FL|2022-03-27 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839476|A/./Maine/A/Backyard bird/Maine/22-009412-002/2022/2022|H5N1|USA-ME|2022-03-25 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839501|A/./Illinois/A/Graylag Goose/Illinois/22-008377-005/2022/2022|H5N1|USA-IL|2022-03-14 00:00:00|other|A1
>SRR24839502|A/./Illinois/A/Graylag Goose/Illinois/22-008377-002/2022/2022|H5N1|USA-IL|2022-03-14 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839551|A/./New York/A/Backyard bird/New York/22-009324-009/2022/2022|H5N1|USA-NY|2022-03-28 00:00:00|other|A1
nan
>SRR24839558|A/./Nebraska/A/Backyard bird/Nebraska/22-009190-001/2022/2022|H5N1|USA-NE|2022-03-24 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839628|A/./Florida/A/Gull/Florida/22-007915-006/2022/2022|H5N1|USA-FL|2022-03-01 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
>SRR24839652|A/./Illinois/A/Guineafowl/Illinois/22-007382-001/2022/2022|H5N1|USA-IL|2022-03-09 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839724|A/./New York/A/Backyard bird/New York/22-005647-001/2022/2022|H5N1|USA-NY|2022-02-19 00:00:00|other|A1
>SRR24839725|A/./New York/A/Backyard bird/New York/22-005647-002/2022/2022|H5N1|USA-NY|2022-02-19 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843008|A/./Missouri/A/Pelican/Missouri/22-012338-019/2022/missing|H5N1|USA-MO|missing|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843106|A/./Texas/A/Owl/Texas/22-012996-001/2022/2022|H5N1|USA-TX|2022-04-27 00:00:00|other|A1
nan
nan
>SRR24843142|A/./Missouri/A/Goose/Missouri/22-012338-006/2022/2022|H5N1|USA-MO|2022-03-15 00:00:00|other|A1
nan
>SRR24843264|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-004/2022/2022|H5N1|USA-PA|2022-04-28 00:00:00|other|A1
>SRR24843265|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-003/2022/2022|H5N1|USA-PA|2022-04-28 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839171|A/./Massachusetts/A/Backyard bird/Massachusetts/22-009371-001/2022/2022|H5N1|USA-MA|2022-03-25 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839298|A/./Nebraska/A/Swan/Nebraska/22-008227-001/2022/2022|H5N1|USA-NE|2022-03-13 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839316|A/./Kansas/A/Backyard bird/Kansas/22-008114-001/2022/2022|H5N1|USA-KS|2022-03-16 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839413|A/./Texas/A/Pheasant/Texas/22-010008-002/2022/2022|H5N1|USA-TX|2022-04-01 00:00:00|other|A1
nan
nan
>SRR24839416|A/./Texas/A/Pheasant/Texas/22-010008-001/2022/2022|H5N1|USA-TX|2022-04-01 00:00:00|other|A1
nan
nan
>SRR24839423|A/./Texas/A/Pheasant/Texas/22-009984-001/2022/2022|H5N1|USA-TX|2022-03-29 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839442|A/./Florida/A/Black Vulture/Florida/22-009936-001/2022/2022|H5N1|USA-FL|2022-03-27 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839476|A/./Maine/A/Backyard bird/Maine/22-009412-002/2022/2022|H5N1|USA-ME|2022-03-25 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839501|A/./Illinois/A/Graylag Goose/Illinois/22-008377-005/2022/2022|H5N1|USA-IL|2022-03-14 00:00:00|other|A1
>SRR24839502|A/./Illinois/A/Graylag Goose/Illinois/22-008377-002/2022/2022|H5N1|USA-IL|2022-03-14 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839551|A/./New York/A/Backyard bird/New York/22-009324-009/2022/2022|H5N1|USA-NY|2022-03-28 00:00:00|other|A1
nan
>SRR24839558|A/./Nebraska/A/Backyard bird/Nebraska/22-009190-001/2022/2022|H5N1|USA-NE|2022-03-24 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839628|A/./Florida/A/Gull/Florida/22-007915-006/2022/2022|H5N1|USA-FL|2022-03-01 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
>SRR24839652|A/./Illinois/A/Guineafowl/Illinois/22-007382-001/2022/2022|H5N1|USA-IL|2022-03-09 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839724|A/./New York/A/Backyard bird/New York/22-005647-001/2022/2022|H5N1|USA-NY|2022-02-19 00:00:00|other|A1
>SRR24839725|A/./New York/A/Backyard bird/New York/22-005647-002/2022/2022|H5N1|USA-NY|2022-02-19 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843008|A/./Missouri/A/Pelican/Missouri/22-012338-019/2022/missing|H5N1|USA-MO|missing|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24843106|A/./Texas/A/Owl/Texas/22-012996-001/2022/2022|H5N1|USA-TX|2022-04-27 00:00:00|other|A1
nan
nan
>SRR24843142|A/./Missouri/A/Goose/Missouri/22-012338-006/2022/2022|H5N1|USA-MO|2022-03-15 00:00:00|other|A1
nan
>SRR24843264|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-004/2022/2022|H5N1|USA-PA|2022-04-28 00:00:00|other|A1
>SRR24843265|A/./Pennsylvania/A/Duck/Pennsylvania/22-013189-003/2022/2022|H5N1|USA-PA|2022-04-28 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839171|A/./Massachusetts/A/Backyard bird/Massachusetts/22-009371-001/2022/2022|H5N1|USA-MA|2022-03-25 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839298|A/./Nebraska/A/Swan/Nebraska/22-008227-001/2022/2022|H5N1|USA-NE|2022-03-13 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839316|A/./Kansas/A/Backyard bird/Kansas/22-008114-001/2022/2022|H5N1|USA-KS|2022-03-16 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839413|A/./Texas/A/Pheasant/Texas/22-010008-002/2022/2022|H5N1|USA-TX|2022-04-01 00:00:00|other|A1
nan
nan
>SRR24839416|A/./Texas/A/Pheasant/Texas/22-010008-001/2022/2022|H5N1|USA-TX|2022-04-01 00:00:00|other|A1
nan
nan
>SRR24839423|A/./Texas/A/Pheasant/Texas/22-009984-001/2022/2022|H5N1|USA-TX|2022-03-29 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839442|A/./Florida/A/Black Vulture/Florida/22-009936-001/2022/2022|H5N1|USA-FL|2022-03-27 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839476|A/./Maine/A/Backyard bird/Maine/22-009412-002/2022/2022|H5N1|USA-ME|2022-03-25 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
>SRR24839501|A/./Illinois/A/Graylag Goose/Illinois/22-008377-005/2022/2022|H5N1|USA-IL|2022-03-14 00:00:00|other|A1
>SRR24839502|A/./Illinois/A/Graylag Goose/Illinois/22-008377-002/2022/2022|H5N1|USA-IL|2022-03-14 00:00:00|other|A1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

## De-Duplication

In [ ]:
# De-duplication 

# Gisaid 
dfs_gisaid_list = []
for genotype in genotypes:

    # gisaid = downloads + "GISAID/complete/" + genotype.replace(".", "_") + "/" + date_range + "_" + genotype.replace(".", "_") + "_Antarctica_North_America_South_America/"
    gisaid = downloads + "GISAID/complete/all_genotypes/11-01-2021--06-13-2025_all_genotypes_Antarctica_North_America_South_America/"
    # gisaid = downloads + "Cats/Datasets/GISAID/"

    os.chdir(gisaid)

    dfs_gisaid = create_dataframes(gisaid)
    dfs_gisaid_list.append(dfs_gisaid)

dfs_gisaid = {}
for df_gisaid in dfs_gisaid_list:
    dfs_gisaid = dfs_gisaid | df_gisaid
# dfs_gisaid2 = create_dataframes(gisaid2)

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP

KeyboardInterrupt:

In [ ]:
# Do the same with Andersen 

# dfs_andersen = create_dataframes(complete_files + "/B3_13_D1_1/" + date_range + "_B3_13_D1_1/")
dfs_andersen = create_dataframes(originals + "complete/")

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_HA
A3_MP
A3_MP
A3_NA
A3_NA
A3_NP
A3_NP
A3_NS
A3_NS
A3_PA
A3_PA
A3_PB1
A3_PB1
A3_PB2
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_HA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_HA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_MP
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_MP
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NP
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NP
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NS
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_NS
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PA
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PB1
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PB1
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PB2
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Andersen/complete/
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_HA
B3.6_MP
B3.6_MP
B3.6_NA
B3.6_NA
B3.6_NP
B3.6_NP
B3.6_NS
B3.6_NS
B3.6_PA
B3.6_PA
B3.6_PB1
B3.6_PB1
B3.6_PB2
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_HA
D1.1_MP
D1.1_MP
D1.1_NA
D1.1_NA
D1.1_NP
D1.1_NP
D1.1_NS
D1.1_NS
D1.1_PA
D1.1_PA
D1.1_PB1
D1.1_PB1
D1.1_PB2
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
D2.1_HA
D2.1_MP
D2.1_NA
D2.1_NP
D2.1_NS
D2.1_PA
D2.1_PB1
D2.1_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor101_HA
Minor101_MP
Minor101_NA
Minor101_NP
Minor101_NS
Minor101_PA
Minor101_PB1
Minor101_PB2
Minor102_HA
Minor102_MP
Minor102_NA
Minor102_NP
Minor102_NS
Minor102_PA
Minor102_PB1
Minor102_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor104_HA
Minor104_MP
Minor104_NA
Minor104_NP
Minor104_NS
Minor104_PA
Minor104_PB1
Minor104_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor106_HA
Minor106_MP
Minor106_NA
Minor106_NP
Minor106_NS
Minor106_PA
Minor106_PB1
Minor106_PB2
Minor10_HA
Minor10_MP
Minor10_NA
Minor10_NP
Minor10_NS
Minor10_PA
Minor10_PB1
Minor10_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor16_HA
Minor16_MP
Minor16_NA
Minor16_NP
Minor16_NS
Minor16_PA
Minor16_PB1
Minor16_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor18_HA
Minor18_MP
Minor18_NA
Minor18_NP
Minor18_NS
Minor18_PA
Minor18_PB1
Minor18_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor24_HA
Minor24_MP
Minor24_NA
Minor24_NP
Minor24_NS
Minor24_PA
Minor24_PB1
Minor24_PB2
Minor25_HA
Minor25_MP
Minor25_NA
Minor25_NP
Minor25_NS
Minor25_PA
Minor25_PB1
Minor25_PB2
Minor26_HA
Minor26_MP
Minor26_NA
Minor26_NP
Minor26_NS
Minor26_PA
Minor26_PB1
Minor26_PB2
Minor27_HA
Minor27_MP
Minor27_NA
Minor27_NP
Minor27_NS
Minor27_PA
Minor27_PB1
Minor27_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor29_HA
Minor29_MP
Minor29_NA
Minor29_NP
Minor29_NS
Minor29_PA
Minor29_PB1
Minor29_PB2
Minor30_HA
Minor30_MP
Minor30_NA
Minor30_NP
Minor30_NS
Minor30_PA
Minor30_PB1
Minor30_PB2
Minor31_HA
Minor31_MP
Minor31_NA
Minor31_NP
Minor31_NS
Minor31_PA
Minor31_PB1
Minor31_PB2
Minor32_HA
Minor32_MP
Minor32_NA
Minor32_NP
Minor32_NS
Minor32_PA
Minor32_PB1
Minor32_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor37_HA
Minor37_MP
Minor37_NA
Minor37_NP
Minor37_NS
Minor37_PA
Minor37_PB1
Minor37_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor39_HA
Minor39_MP
Minor39_NA
Minor39_NP
Minor39_NS
Minor39_PA
Minor39_PB1
Minor39_PB2
Minor40_HA
Minor40_MP
Minor40_NA
Minor40_NP
Minor40_NS
Minor40_PA
Minor40_PB1
Minor40_PB2
Minor41_HA
Minor41_MP
Minor41_NA
Minor41_NP
Minor41_NS
Minor41_PA
Minor41_PB1
Minor41_PB2
Minor42_HA
Minor42_MP
Minor42_NA
Minor42_NP
Minor42_NS
Minor42_PA
Minor42_PB1
Minor42_PB2
Minor43_HA
Minor43_MP
Minor43_NA
Minor43_NP
Minor43_NS
Minor43_PA
Minor43_PB1
Minor43_PB2
Minor44_HA
Minor44_MP
Minor44_NA
Minor44_NP
Minor44_NS
Minor44_PA
Minor44_PB1
Minor44_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor46_HA
Minor46_MP
Minor46_NA
Minor46_NP
Minor46_NS
Minor46_PA
Minor46_PB1
Minor46_PB2
Minor47_HA
Minor47_MP
Minor47_NA
Minor47_NP
Minor47_NS
Minor47_PA
Minor47_PB1
Minor47_PB2
Minor48_HA
Minor48_MP
Minor48_NA
Minor48_NP
Minor48_NS
Minor48_PA
Minor48_PB1
Minor48_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor52_HA
Minor52_MP
Minor52_NA
Minor52_NP
Minor52_NS
Minor52_PA
Minor52_PB1
Minor52_PB2
Minor53_HA
Minor53_MP
Minor53_NA
Minor53_NP
Minor53_NS
Minor53_PA
Minor53_PB1
Minor53_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor56_HA
Minor56_MP
Minor56_NA
Minor56_NP
Minor56_NS
Minor56_PA
Minor56_PB1
Minor56_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor67_HA
Minor67_MP
Minor67_NA
Minor67_NP
Minor67_NS
Minor67_PA
Minor67_PB1
Minor67_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor71_HA
Minor71_MP
Minor71_NA
Minor71_NP
Minor71_NS
Minor71_PA
Minor71_PB1
Minor71_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor74_HA
Minor74_MP
Minor74_NA
Minor74_NP
Minor74_NS
Minor74_PA
Minor74_PB1
Minor74_PB2
Minor75_HA
Minor75_MP
Minor75_NA
Minor75_NP
Minor75_NS
Minor75_PA
Minor75_PB1
Minor75_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor78_HA
Minor78_MP
Minor78_NA
Minor78_NP
Minor78_NS
Minor78_PA
Minor78_PB1
Minor78_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor80_HA
Minor80_MP
Minor80_NA
Minor80_NP
Minor80_NS
Minor80_PA
Minor80_PB1
Minor80_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor82_HA
Minor82_MP
Minor82_NA
Minor82_NP
Minor82_NS
Minor82_PA
Minor82_PB1
Minor82_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor84_HA
Minor84_MP
Minor84_NA
Minor84_NP
Minor84_NS
Minor84_PA
Minor84_PB1
Minor84_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor92_HA
Minor92_MP
Minor92_NA
Minor92_NP
Minor92_NS
Minor92_PA
Minor92_PB1
Minor92_PB2
Minor93_HA
Minor93_MP
Minor93_NA
Minor93_NP
Minor93_NS
Minor93_PA
Minor93_PB1
Minor93_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor95_HA
Minor95_MP
Minor95_NA
Minor95_NP
Minor95_NS
Minor95_PA
Minor95_PB1
Minor95_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
Minor98_HA
Minor98_MP
Minor98_NA
Minor98_NP
Minor98_NS
Minor98_PA
Minor98_PB1
Minor98_PB2
Minor99_HA
Minor99_MP
Minor99_NA
Minor99_NP
Minor99_NS
Minor99_PA
Minor99_PB1
Minor99_PB2

In [ ]:
# os.chdir(downloads)
# dfs_gisaid["B3.13_HA"].to_csv

In [ ]:
for key in dfs_andersen.keys():
    dataframes = dfs_andersen[key]
    print(key)

print(dfs_andersen)

A1_HA
A1_MP
A1_NA
A1_NP
A1_NS
A1_PA
A1_PB1
A1_PB2
A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
A4_HA
A4_MP
A4_NA
A4_NP
A4_NS
A4_PA
A4_PB1
A4_PB2
A5_HA
A5_MP
A5_NA
A5_NP
A5_NS
A5_PA
A5_PB1
A5_PB2
A6_HA
A6_MP
A6_NA
A6_NP
A6_NS
A6_PA
A6_PB1
A6_PB2
B1.1_HA
B1.1_MP
B1.1_NA
B1.1_NP
B1.1_NS
B1.1_PA
B1.1_PB1
B1.1_PB2
B1.2_HA
B1.2_MP
B1.2_NA
B1.2_NP
B1.2_NS
B1.2_PA
B1.2_PB1
B1.2_PB2
B1.3_HA
B1.3_MP
B1.3_NA
B1.3_NP
B1.3_NS
B1.3_PA
B1.3_PB1
B1.3_PB2
B2.1_HA
B2.1_MP
B2.1_NA
B2.1_NP
B2.1_NS
B2.1_PA
B2.1_PB1
B2.1_PB2
B2.2_HA
B2.2_MP
B2.2_NA
B2.2_NP
B2.2_NS
B2.2_PA
B2.2_PB1
B2.2_PB2
B3.10_HA
B3.10_MP
B3.10_NA
B3.10_NP
B3.10_NS
B3.10_PA
B3.10_PB1
B3.10_PB2
B3.11_HA
B3.11_MP
B3.11_NA
B3.11_NP
B3.11_NS
B3.11_PA
B3.11_PB1
B3.11_PB2
B3.12_HA
B3.12_MP
B3.12_NA
B3.12_NP
B3.12_NS
B3.12_PA
B3.12_PB1
B3.12_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.1_HA
B3.1_MP
B3.1_NA
B3.1_NP
B3.1_NS
B3.1_PA
B3.1_PB1
B3.1_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.3_HA
B3.3_MP
B3.3_NA
B3.3_NP
B3.3_NS
B3.3_PA
B3.3_PB1
B3.3_PB2
B3.4_HA
B3.4_MP
B3.4_NA
B3.4_NP
B3.4_NS
B3.4_PA
B3.4_PB1
B3.4_PB2
B3.5_HA
B3.5_MP
B3.5_NA
B3.5_NP
B3.5_NS
B3.5_PA
B3.5_PB1
B3.5_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.7_HA
B3.7_MP
B3.7_NA
B3.7_NP
B3.7_NS
B3.7_PA
B3.7_PB1
B3.7_PB2
B3.8_HA
B3.8_MP
B3.8_NA
B3.8_NP
B3.8_NS
B3.8_PA
B3.8_PB1
B3.8_PB2
B3.9_HA
B3.9_MP
B3.9_NA
B3.9_NP
B3.9_NS
B3.9_PA
B3.9_PB1
B3.9_PB2
B4.1_HA
B4.1_MP
B4.1_NA
B4.1_NP
B4.1_NS
B4.1_PA
B4.1_PB1
B4.1_PB2
B5.1_HA
B5.1_MP
B5.1_NA
B5.1_NP
B5.1_NS
B5.1_PA
B5.1_PB1
B5.1_PB2
C1.1_HA
C1.1_MP
C1.1_NA
C1.1_NP
C1.1_NS
C1.1_PA
C1.1_PB1
C1.1_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
C3.1_HA
C3.1_MP
C3.1_NA
C3.1_NP
C3.1_NS
C3.1_PA
C3.1_PB1
C3.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.2_HA
D1.2_MP
D1.2_NA
D1.2_NP
D1.2_NS
D1.2_PA
D1.2_PB1
D1.2_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
D2.1_HA
D2.1_MP
D2.1_NA
D2.1_NP
D2.1_NS
D2.1_PA
D2.1_PB1
D2.1_PB2
Minor01_HA
Minor01_MP
Minor01_NA
Minor01_NP
Minor01_NS
Minor01_PA
Minor01_PB1
Minor01_PB2
Minor04_HA
Minor04_MP
Minor04_NA
Minor04_NP
Minor04_NS
Minor04_PA
Minor04_PB1
Minor04_PB2
Minor07_HA
Minor07_MP
Minor07_NA
Minor07_NP
Minor07_NS
Minor07_PA
Minor07_PB1
Minor07_PB2
Minor08_HA
Minor08_MP
Minor08_NA
Minor08_NP
Minor08_NS
Minor08_PA
Minor08_PB1
Minor08_PB2
Minor09_HA
Minor09_MP
Minor09_NA
Minor09_NP
Minor09_NS
Minor09_PA
Minor09_PB1
Minor09_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor101_HA
Minor101_MP
Minor101_NA
Minor101_NP
Minor101_NS
Minor101_PA
Minor101_PB1
Minor101_PB2
Minor102_HA
Minor102_MP
Minor102_NA
Minor102_NP
Minor102_NS
Minor102_PA
Minor102_PB1
Minor102_PB2
Minor103_HA
Minor103_MP
Minor103_NA
Minor103_NP
Minor103_NS
Minor103_PA
Minor103_PB1
Minor103_PB2
Minor104_HA
Minor104_MP
Minor104_NA
Minor104_NP
Minor104_NS
Minor104_PA
Minor104_PB1
Minor104_PB2
Minor105_HA
Minor105_MP
Minor105_NA
Minor105_NP
Minor105_NS
Minor105_PA
Minor105_PB1
Minor105_PB2
Minor106_HA
Minor106_MP
Minor106_NA
Minor106_NP
Minor106_NS
Minor106_PA
Minor106_PB1
Minor106_PB2
Minor10_HA
Minor10_MP
Minor10_NA
Minor10_NP
Minor10_NS
Minor10_PA
Minor10_PB1
Minor10_PB2
Minor11_HA
Minor11_MP
Minor11_NA
Minor11_NP
Minor11_NS
Minor11_PA
Minor11_PB1
Minor11_PB2
Minor12_HA
Minor12_MP
Minor12_NA
Minor12_NP
Minor12_NS
Minor12_PA
Minor12_PB1
Minor12_PB2
Minor13_HA
Minor13_MP
Minor13_NA
Minor13_NP
Minor13_NS
Minor13_PA
Minor13_PB1
Minor13_PB2
Minor14_HA
Minor14_MP
Minor14_NA
Minor14_NP
Minor14_NS
Minor14_PA
Minor14_PB1
Minor14_PB2
Minor15_HA
Minor15_MP
Minor15_NA
Minor15_NP
Minor15_NS
Minor15_PA
Minor15_PB1
Minor15_PB2
Minor16_HA
Minor16_MP
Minor16_NA
Minor16_NP
Minor16_NS
Minor16_PA
Minor16_PB1
Minor16_PB2
Minor17_HA
Minor17_MP
Minor17_NA
Minor17_NP
Minor17_NS
Minor17_PA
Minor17_PB1
Minor17_PB2
Minor18_HA
Minor18_MP
Minor18_NA
Minor18_NP
Minor18_NS
Minor18_PA
Minor18_PB1
Minor18_PB2
Minor19_HA
Minor19_MP
Minor19_NA
Minor19_NP
Minor19_NS
Minor19_PA
Minor19_PB1
Minor19_PB2
Minor24_HA
Minor24_MP
Minor24_NA
Minor24_NP
Minor24_NS
Minor24_PA
Minor24_PB1
Minor24_PB2
Minor25_HA
Minor25_MP
Minor25_NA
Minor25_NP
Minor25_NS
Minor25_PA
Minor25_PB1
Minor25_PB2
Minor26_HA
Minor26_MP
Minor26_NA
Minor26_NP
Minor26_NS
Minor26_PA
Minor26_PB1
Minor26_PB2
Minor27_HA
Minor27_MP
Minor27_NA
Minor27_NP
Minor27_NS
Minor27_PA
Minor27_PB1
Minor27_PB2
Minor28_HA
Minor28_MP
Minor28_NA
Minor28_NP
Minor28_NS
Minor28_PA
Minor28_PB1
Minor28_PB2
Minor29_HA
Minor29_MP
Minor29_NA
Minor29_NP
Minor29_NS
Minor29_PA
Minor29_PB1
Minor29_PB2
Minor30_HA
Minor30_MP
Minor30_NA
Minor30_NP
Minor30_NS
Minor30_PA
Minor30_PB1
Minor30_PB2
Minor31_HA
Minor31_MP
Minor31_NA
Minor31_NP
Minor31_NS
Minor31_PA
Minor31_PB1
Minor31_PB2
Minor32_HA
Minor32_MP
Minor32_NA
Minor32_NP
Minor32_NS
Minor32_PA
Minor32_PB1
Minor32_PB2
Minor33_HA
Minor33_MP
Minor33_NA
Minor33_NP
Minor33_NS
Minor33_PA
Minor33_PB1
Minor33_PB2
Minor34_HA
Minor34_MP
Minor34_NA
Minor34_NP
Minor34_NS
Minor34_PA
Minor34_PB1
Minor34_PB2
Minor35_HA
Minor35_MP
Minor35_NA
Minor35_NP
Minor35_NS
Minor35_PA
Minor35_PB1
Minor35_PB2
Minor36_HA
Minor36_MP
Minor36_NA
Minor36_NP
Minor36_NS
Minor36_PA
Minor36_PB1
Minor36_PB2
Minor37_HA
Minor37_MP
Minor37_NA
Minor37_NP
Minor37_NS
Minor37_PA
Minor37_PB1
Minor37_PB2
Minor38_HA
Minor38_MP
Minor38_NA
Minor38_NP
Minor38_NS
Minor38_PA
Minor38_PB1
Minor38_PB2
Minor39_HA
Minor39_MP
Minor39_NA
Minor39_NP
Minor39_NS
Minor39_PA
Minor39_PB1
Minor39_PB2
Minor40_HA
Minor40_MP
Minor40_NA
Minor40_NP
Minor40_NS
Minor40_PA
Minor40_PB1
Minor40_PB2
Minor41_HA
Minor41_MP
Minor41_NA
Minor41_NP
Minor41_NS
Minor41_PA
Minor41_PB1
Minor41_PB2
Minor42_HA
Minor42_MP
Minor42_NA
Minor42_NP
Minor42_NS
Minor42_PA
Minor42_PB1
Minor42_PB2
Minor43_HA
Minor43_MP
Minor43_NA
Minor43_NP
Minor43_NS
Minor43_PA
Minor43_PB1
Minor43_PB2
Minor44_HA
Minor44_MP
Minor44_NA
Minor44_NP
Minor44_NS
Minor44_PA
Minor44_PB1
Minor44_PB2
Minor45_HA
Minor45_MP
Minor45_NA
Minor45_NP
Minor45_NS
Minor45_PA
Minor45_PB1
Minor45_PB2
Minor46_HA
Minor46_MP
Minor46_NA
Minor46_NP
Minor46_NS
Minor46_PA
Minor46_PB1
Minor46_PB2
Minor47_HA
Minor47_MP
Minor47_NA
Minor47_NP
Minor47_NS
Minor47_PA
Minor47_PB1
Minor47_PB2
Minor48_HA
Minor48_MP
Minor48_NA
Minor48_NP
Minor48_NS
Minor48_PA
Minor48_PB1
Minor48_PB2
Minor50_HA
Minor50_MP
Minor50_NA
Minor50_NP
Minor50_NS
Minor50_PA
Minor50_PB1
Minor50_PB2
Minor51_HA
Minor51_MP
Minor51_NA
Minor51_NP
Minor51_NS
Minor51_PA
Minor51_PB1
Minor51_PB2
Minor52_HA
Minor52_MP
Minor52_NA
Minor52_NP
Minor52_NS
Minor52_PA
Minor52_PB1
Minor52_PB2
Minor53_HA
Minor53_MP
Minor53_NA
Minor53_NP
Minor53_NS
Minor53_PA
Minor53_PB1
Minor53_PB2
Minor55_HA
Minor55_MP
Minor55_NA
Minor55_NP
Minor55_NS
Minor55_PA
Minor55_PB1
Minor55_PB2
Minor56_HA
Minor56_MP
Minor56_NA
Minor56_NP
Minor56_NS
Minor56_PA
Minor56_PB1
Minor56_PB2
Minor57_HA
Minor57_MP
Minor57_NA
Minor57_NP
Minor57_NS
Minor57_PA
Minor57_PB1
Minor57_PB2
Minor58_HA
Minor58_MP
Minor58_NA
Minor58_NP
Minor58_NS
Minor58_PA
Minor58_PB1
Minor58_PB2
Minor60_HA
Minor60_MP
Minor60_NA
Minor60_NP
Minor60_NS
Minor60_PA
Minor60_PB1
Minor60_PB2
Minor61_HA
Minor61_MP
Minor61_NA
Minor61_NP
Minor61_NS
Minor61_PA
Minor61_PB1
Minor61_PB2
Minor62_HA
Minor62_MP
Minor62_NA
Minor62_NP
Minor62_NS
Minor62_PA
Minor62_PB1
Minor62_PB2
Minor63_HA
Minor63_MP
Minor63_NA
Minor63_NP
Minor63_NS
Minor63_PA
Minor63_PB1
Minor63_PB2
Minor65_HA
Minor65_MP
Minor65_NA
Minor65_NP
Minor65_NS
Minor65_PA
Minor65_PB1
Minor65_PB2
Minor66_HA
Minor66_MP
Minor66_NA
Minor66_NP
Minor66_NS
Minor66_PA
Minor66_PB1
Minor66_PB2
Minor67_HA
Minor67_MP
Minor67_NA
Minor67_NP
Minor67_NS
Minor67_PA
Minor67_PB1
Minor67_PB2
Minor70_HA
Minor70_MP
Minor70_NA
Minor70_NP
Minor70_NS
Minor70_PA
Minor70_PB1
Minor70_PB2
Minor71_HA
Minor71_MP
Minor71_NA
Minor71_NP
Minor71_NS
Minor71_PA
Minor71_PB1
Minor71_PB2
Minor73_HA
Minor73_MP
Minor73_NA
Minor73_NP
Minor73_NS
Minor73_PA
Minor73_PB1
Minor73_PB2
Minor74_HA
Minor74_MP
Minor74_NA
Minor74_NP
Minor74_NS
Minor74_PA
Minor74_PB1
Minor74_PB2
Minor75_HA
Minor75_MP
Minor75_NA
Minor75_NP
Minor75_NS
Minor75_PA
Minor75_PB1
Minor75_PB2
Minor76_HA
Minor76_MP
Minor76_NA
Minor76_NP
Minor76_NS
Minor76_PA
Minor76_PB1
Minor76_PB2
Minor77_HA
Minor77_MP
Minor77_NA
Minor77_NP
Minor77_NS
Minor77_PA
Minor77_PB1
Minor77_PB2
Minor78_HA
Minor78_MP
Minor78_NA
Minor78_NP
Minor78_NS
Minor78_PA
Minor78_PB1
Minor78_PB2
Minor79_HA
Minor79_MP
Minor79_NA
Minor79_NP
Minor79_NS
Minor79_PA
Minor79_PB1
Minor79_PB2
Minor80_HA
Minor80_MP
Minor80_NA
Minor80_NP
Minor80_NS
Minor80_PA
Minor80_PB1
Minor80_PB2
Minor81_HA
Minor81_MP
Minor81_NA
Minor81_NP
Minor81_NS
Minor81_PA
Minor81_PB1
Minor81_PB2
Minor82_HA
Minor82_MP
Minor82_NA
Minor82_NP
Minor82_NS
Minor82_PA
Minor82_PB1
Minor82_PB2
Minor83_HA
Minor83_MP
Minor83_NA
Minor83_NP
Minor83_NS
Minor83_PA
Minor83_PB1
Minor83_PB2
Minor84_HA
Minor84_MP
Minor84_NA
Minor84_NP
Minor84_NS
Minor84_PA
Minor84_PB1
Minor84_PB2
Minor86_HA
Minor86_MP
Minor86_NA
Minor86_NP
Minor86_NS
Minor86_PA
Minor86_PB1
Minor86_PB2
Minor87_HA
Minor87_MP
Minor87_NA
Minor87_NP
Minor87_NS
Minor87_PA
Minor87_PB1
Minor87_PB2
Minor89_HA
Minor89_MP
Minor89_NA
Minor89_NP
Minor89_NS
Minor89_PA
Minor89_PB1
Minor89_PB2
Minor90_HA
Minor90_MP
Minor90_NA
Minor90_NP
Minor90_NS
Minor90_PA
Minor90_PB1
Minor90_PB2
Minor91_HA
Minor91_MP
Minor91_NA
Minor91_NP
Minor91_NS
Minor91_PA
Minor91_PB1
Minor91_PB2
Minor92_HA
Minor92_MP
Minor92_NA
Minor92_NP
Minor92_NS
Minor92_PA
Minor92_PB1
Minor92_PB2
Minor93_HA
Minor93_MP
Minor93_NA
Minor93_NP
Minor93_NS
Minor93_PA
Minor93_PB1
Minor93_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2
Minor95_HA
Minor95_MP
Minor95_NA
Minor95_NP
Minor95_NS
Minor95_PA
Minor95_PB1
Minor95_PB2
Minor97_HA
Minor97_MP
Minor97_NA
Minor97_NP
Minor97_NS
Minor97_PA
Minor97_PB1
Minor97_PB2
Minor98_HA
Minor98_MP
Minor98_NA
Minor98_NP
Minor98_NS
Minor98_PA
Minor98_PB1
Minor98_PB2
Minor99_HA
Minor99_MP
Minor99_NA
Minor99_NP
Minor99_NS
Minor99_PA
Minor99_PB1
Minor99_PB2
defaultdict(<class 'list'>, {'A1_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A1_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_HA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_MP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_NA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_NP': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_NS': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_PA': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_PB1': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A2_PB2': [Empty DataFrame
Columns: [isolate_partial, full_header, sequence]
Index: []], 'A3_HA': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
3   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
5   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
6   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
7   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
8   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
9   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
10  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
11  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
12  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
13  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
14  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
15  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
16  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
17  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...  ,    isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
3   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
5   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
6   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
7   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
8   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
9   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
10  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
11  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
12  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
13  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
14  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
15  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
16  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
17  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...  ], 'A3_MP': [   isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
5   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
6   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
7   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
8   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
9   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
10  ATGAGTCTTCTGACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
11  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
12  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
13  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
14  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
15  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
16  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
17  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...  ,    isolate_partial                                        full_header  \
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...


In [ ]:
print(len(list(dfs_gisaid.keys())))
print(len(list(dfs_andersen.keys())))

80
968

In [ ]:
# Merge dataframes and drop duplicates

full_dfs = defaultdict(list)
# same = []
# andersen = set()
# gisaid = set()

for i, andersen_key in enumerate(dfs_andersen.keys()):
    if len(dfs_andersen[andersen_key]) > 0:
        for j, gisaid_key in enumerate(dfs_gisaid.keys()):
            if andersen_key == gisaid_key:
                # same.append(gisaid_key)
        # gisaid_key = list(dfs_gisaid.keys())[i]
        # gisaid2_key = list(dfs_gisaid2.keys())[i]

                andersen_df = dfs_andersen[andersen_key][0]
                print(len(andersen_df))
                # print(andersen_df)
                gisaid_df = dfs_gisaid[gisaid_key][0]
                print(len(gisaid_df))
                # gisaid2_df = dfs_gisaid2[gisaid2_key][0]

                print(pd.concat([gisaid_df, andersen_df]).drop_duplicates())

                full_df = pd.concat([andersen_df, gisaid_df], ignore_index=True)
                print("len full df:", len(full_df))
                test = len(full_df.drop_duplicates(subset="isolate_partial"))

                dedup_df = full_df.drop_duplicates(subset="isolate_partial", keep="last")

                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print((full_df.loc[full_df.duplicated(subset="isolate_partial")]))
                # print(full_df)
                
                print("Keeping nothing: ", test)
                
                print("len deduplicated:", len(dedup_df))
                full_dfs[andersen_key].append(dedup_df)
            # else:
                # gisaid.add(gisaid_key)
                # andersen.add(andersen_key)
    
    # break 


# print(full_dfs)
# print(len(full_dfs))
# print(319*8)
# print(len(same))
# print(len(andersen))
# print(len(gisaid))

0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atggatgtcaatccgactttacttttcttaaaagtgccagcgcaaa...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
0
1
  isolate_partial                                        full_header  \
0        23OS0170  >EPI_ISL_19873848|A/wood_duck/Ohio/23OS0170/20...

                                            sequence
0  atggagagaataaaagagctaagagatttgatgtcgcagtctcgca...
len full df: 1
Keeping nothing:  1
len deduplicated: 1
18
22
   isolate_partial                                        full_header  \
0       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
1       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
2       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
3       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
4       010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
5       010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
6        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
7        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
8        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
9        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
10       IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
11       IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atggagaacatagtacttcttcttgcaataattagccttgttaaaa...
1   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
2   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
3   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
4   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
5   atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
6   atggagaacatagtacttcttcttgcaataattagccttgttaaaa...
7   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
8   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
9   ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
10  ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
11  ggttcactctgtcaaaatggagaacatagtacttcttcttgcaata...
12  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
13  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
14  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
15  atggaaaccatagtacttcttcttgcaataattagccttgttaaaa...
16  atggaaaacatagcacttcttcttgcaataattagccttgttaaaa...
17  atggaaaccatagtacttcttcttgcaataattagccttgttaaaa...
18  atggaaaacatagcacttcttcttgcaataattagccttgttaaaa...
19  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
20  atggaaaacatagtacttcttcttgcaataattagccttgttaaaa...
21  atggaaaacatagcacttcttcttgcaataattagccttgttaaaa...
0   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
3   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4   ATGGAAAACATAGCACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
5   ATGGAAACCATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
6   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
7   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
8   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
9   ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
10  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
11  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
12  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
13  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
14  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
15  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
16  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
17  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
len full df: 40
Keeping nothing:  24
len deduplicated: 24
18
22
   isolate_partial                                        full_header  \
0       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
1       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
2       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
3       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
4       010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
5       010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
6        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
7        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
8        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
9        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
10       IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
11       IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
1   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
2   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
3   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
4   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
5   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
6   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
7   tagatattgaaagatgagtcttctaaccgaggtcgaaacgtacgtt...
8   tagatattgaaagatgagtcttctaaccgaggtcgaaacgtacgtt...
9   atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
10  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
11  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
12  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
13  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
14  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
15  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
16  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
17  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
18  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
19  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
20  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
21  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...
0   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
1   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
4   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
5   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
6   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
7   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
8   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
9   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
10  ATGAGTCTTCTGACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
11  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
12  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
13  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
14  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
15  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
16  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
17  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
len full df: 40
Keeping nothing:  24
len deduplicated: 24
18
22
   isolate_partial                                        full_header  \
0       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
1       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
2       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
3       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
4       010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
5       010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
6        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
7        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
8        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
9        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
10       IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
11       IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...
6       004415-008  >SRR33125127|A/RED-TAILED HAWK/USA/25-004415-0...
7       011423-001  >SRR33319053|A/GREAT HORNED OWL/USA/25-011423-...
8       011667-003  >SRR33319074|A/AMERICAN CROW/USA/25-011667-003...
9       011667-002  >SRR33319075|A/AMERICAN CROW/USA/25-011667-002...
10      011816-002  >SRR33476775|A/TRUMPETER SWAN/USA/25-011816-00...
11      010511-002  >SRR33508776|A/RED-TAILED HAWK/USA/25-010511-0...
12      010511-001  >SRR33508777|A/RED-TAILED HAWK/USA/25-010511-0...
13      010464-001  >SRR33508778|A/COMMON RAVEN/USA/25-010464-001/...
14      005028-002  >SRR33508834|A/BARRED OWL/USA/25-005028-002/20...
15      005028-001  >SRR33508835|A/AMERICAN CROW/USA/25-005028-001...
16      013489-001  >SRR33565207|A/TURKEY VULTURE/USA/25-013489-00...
17      014764-001  >SRR33682325|A/HAWK/USA/25-014764-001/2025|H5N...

                                             sequence
0   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
1   atgaatccaaatcaaaggataataatcactggatcaatctgtatgg...
2   atgaatccaaatcaaaggataataatcactggatcaatctgtatgg...
3   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
4   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
5   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
6   atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
7   aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
8   agttcaaaatgaatccaaatcaaaggataataaccactggatcaat...
9   aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
10  aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
11  aaagcaggagttcaaaatgaatccaaatcaaaggataataaccact...
12  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
13  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
14  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
15  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
16  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
17  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
18  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
19  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
20  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
21  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...
0   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
1   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
2   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
3   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
4   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
5   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
6   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
7   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
8   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
9   ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
10  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
11  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
12  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
13  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
14  ATGAATCCAAATCAAAGGATAATAATCACTGGATCAATCTGTATGG...
15  ATGAATCCAAATCAAAGGATAATAATCACTGGATCAATCTGTATGG...
16  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
17  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
len full df: 40
Keeping nothing:  24
len deduplicated: 24
18
22
   isolate_partial                                        full_header  \
0       014764-001  >EPI_ISL_19882428|A/hawk/USA/014764-001/2025|H...
1       005028-001  >EPI_ISL_19870521|A/american_crow/USA/005028-0...
2       005028-002  >EPI_ISL_19870514|A/barred_owl/USA/005028-002/...
3       010464-001  >EPI_ISL_19870554|A/common_raven/USA/010464-00...
4       010511-001  >EPI_ISL_19870553|A/red-tailed_hawk/USA/010511...
5       010511-002  >EPI_ISL_19870552|A/red-tailed_hawk/USA/010511...
6        IZ24_0787  >EPI_ISL_19871019|A/northern_pintail/USA/IZ24_...
7        IZ24_0636  >EPI_ISL_19871011|A/northern_pintail/USA/IZ24_...
8        IZ24_0570  >EPI_ISL_19871010|A/northern_pintail/USA/IZ24_...
9        IZ24_0474  >EPI_ISL_19871007|A/northern_pintail/USA/IZ24_...
10       IZ23_0849  >EPI_ISL_19871006|A/northern_pintail/USA/IZ23_...
11       IZ23_0847  >EPI_ISL_19871005|A/northern_pintail/USA/IZ23_...
12      011667-003  >EPI_ISL_19851174|A/american_crow/USA/011667-0...
13      011667-002  >EPI_ISL_19851175|A/american_crow/USA/011667-0...
14      011423-001  >EPI_ISL_19851185|A/great_horned_owl/USA/01142...
15      006076-002  >EPI_ISL_19832366|A/bald_eagle/USA/006076-002/...
16      005882-009  >EPI_ISL_19832364|A/mallard/USA/005882-009/202...
17      006076-001  >EPI_ISL_19832373|A/bald_eagle/USA/006076-001/...
18      005882-003  >EPI_ISL_19832368|A/mallard/USA/005882-003/202...
19      004431-001  >EPI_ISL_19832343|A/crow/USA/004431-001/2025|H...
20      004415-008  >EPI_ISL_19832497|A/red-tailed_hawk/USA/004415...
21      005882-006  >EPI_ISL_19832458|A/mallard/USA/005882-006/202...
0       004431-001  >SRR33125022|A/CROW/USA/25-004431-001/2025|H5N...
1       005882-009  >SRR33125049|A/MALLARD/USA/25-005882-009/2025|...
2       006076-002  >SRR33125051|A/BALD EAGLE/USA/25-006076-002/20...
3       005882-006  >SRR33125053|A/MALLARD/USA/25-005882-006/2025|...
4       005882-003  >SRR33125055|A/MALLARD/USA/25-005882-003/2025|...
5       006076-001  >SRR33125062|A/BALD EAGLE/USA/25-006076-001/20...

In [ ]:
# # If none in one database, only use the other and drop duplicates

# full_dfs = defaultdict(list)
# for key in dfs_andersen.keys():
#     print(key)
# # for key in ["D1.3"]:
#     dataframes = dfs_andersen[key]
#     for i, df in enumerate(dataframes):
#         print(i)
#         try:
#             full_df = df.merge(dfs_gisaid[key][i], how="outer")
#             # print(full_df)
#             full_df = full_df.drop_duplicates(subset=["isolate_partial"])
#             full_dfs[key].append(full_df)
#         except:
#             print("Failed to merge dataframes in ", key)
#             full_dfs[key].append(dataframes[i])

## Create FASTA files combining Andersen and GISAID

In [ ]:
# Create FASTA files per segment

combined_files = downloads + "Combinations/GISAID_Andersen/" # B3_13_D1_1/" + date_range + "_B3_13_D1_1/"

os.chdir(combined_files)
for pair in full_dfs.keys():
    print(pair)
    output_path = combined_files + pair + "_combined_" + date_range + ".fasta" 

    output_file = open(output_path, "w")
    for item in full_dfs[pair]:
        # for item in item:
        # item = fasta_files[pair]
        for index, row in item.iterrows():
            name = item.loc[index, "full_header"]
            sequence = item.loc[index, "sequence"]
            # print(name)
        # First is header, second is sequence
        # print(value)
            output_file.write(name)
            output_file.write(sequence)
    output_file.close()

A2_HA
A2_MP
A2_NA
A2_NP
A2_NS
A2_PA
A2_PB1
A2_PB2
A3_HA
A3_MP
A3_NA
A3_NP
A3_NS
A3_PA
A3_PB1
A3_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2
B3.2_HA
B3.2_MP
B3.2_NA
B3.2_NP
B3.2_NS
B3.2_PA
B3.2_PB1
B3.2_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
C2.1_HA
C2.1_MP
C2.1_NA
C2.1_NP
C2.1_NS
C2.1_PA
C2.1_PB1
C2.1_PB2
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
D1.3_HA
D1.3_MP
D1.3_NA
D1.3_NP
D1.3_NS
D1.3_PA
D1.3_PB1
D1.3_PB2
Minor100_HA
Minor100_MP
Minor100_NA
Minor100_NP
Minor100_NS
Minor100_PA
Minor100_PB1
Minor100_PB2
Minor94_HA
Minor94_MP
Minor94_NA
Minor94_NP
Minor94_NS
Minor94_PA
Minor94_PB1
Minor94_PB2

: