# GISAID Discrepancies

## Housekeeping

In [23]:
# Housekeeping

import os
import glob 
import pandas as pd
import xml.etree.ElementTree as ET
import requests
import time
import numpy as np
import dateutil 
from datetime import datetime
from collections import defaultdict 
import matplotlib.pyplot as plt

def partial_isolate(id):

    partial = id.replace("_", "-") # [-1] # If 25_, get the last bit
    partial = partial.replace("-original", "") # If -original suffix, remove
    partial = partial.replace("G", "-0") # If 25G, fix
    digits = partial.split("-")
    # Build partial isolates
    isolate = ""
    # other = ""
    for d in digits:
        # print(d)
        if len(d) == 2 and d.isnumeric(): # The 25 bit
            # isolate = d + "-"
            pass
        if len(d) == 6 and d.isnumeric(): # If it's just digits and not one of those weird isolates
            isolate = d + "-"
        if len(d) == 3 and d.isnumeric():
            isolate = isolate + d
        # elif d.isnumeric() == False: # If it's a weird isolate
        #     other = d + "-"
        # else: 
        #     other = partial 
    # Now add to list to check in Andersen files without doing wild for loops
    if len(isolate) == 10: # If this is a correctly formatted isolate
        # isolates.append(isolate)
        # All headers are followed by sequences
        partial_isolate = isolate
    else: # If this is some other isolate
        partial_isolate = partial

    return partial_isolate

In [24]:
os.chdir("C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/")

gisaid_feb_20_2026 = pd.read_excel("GISAID/downloads/2021-11-01--2026-02-20_Antarctica_North_America_South_America/gisaid_epiflu_isolates.xls")
gisaid_apr_14_2025 = pd.read_csv("GISAID_submission_dates_02-14-2022--12-26-2024_accessed_04-14-2025.csv")
genbank_feb_20_2026 = pd.read_csv("GenBank_submission_dates_02-14-2022--12-26-2024_accessed_02-20-2026.csv")
genbank_apr_14_2025 = pd.read_csv("GenBank_submission_dates_02-14-2022--12-26-2024_accessed_04-14-2025.csv")

In [25]:
gisaid_apr_14_2025["Submission_Date"] = gisaid_apr_14_2025["Submission_Date"].apply(lambda x: dateutil.parser.parse(x))
gisaid_apr_14_2025["Collection_Date"] = gisaid_apr_14_2025["Collection_Date"].apply(lambda x: dateutil.parser.parse(x))

gisaid_apr_14_2025 = gisaid_apr_14_2025[(gisaid_apr_14_2025["Submission_Date"] >= dateutil.parser.parse("01/01/2023")) & (gisaid_apr_14_2025["Submission_Date"] <= dateutil.parser.parse("09/17/2024"))]
gisaid_apr_14_2025["Isolate"] = gisaid_apr_14_2025["Isolate_Name"].apply(lambda x: x.split("/")[-2])
gisaid_apr_14_2025["Authors"] = gisaid_apr_14_2025["Authors"].apply(lambda x: x.split(", ")[0] if x==x else x)
print(gisaid_apr_14_2025.sort_values("Submission_Date")[["Submission_Date", "Isolate_Name", "Isolate"]])

     Submission_Date                               Isolate_Name        Isolate
991       2023-01-03        A/Striped Skunk/SK/FAV-0824-01/2022    FAV-0824-01
992       2023-01-03              A/Red Fox/SK/FAV-0824-96/2022    FAV-0824-96
993       2023-01-18      A/Canada goose/California/246038/2022         246038
994       2023-01-18     A/eared grebe/North Dakota/245625/2022         245625
995       2023-01-18  A/neotropic cormorant/Arizona/245467/2022         245467
...              ...                                        ...            ...
7368      2024-09-11       A/dairy cow/Idaho/24_024698-002/2024  24_024698-002
7367      2024-09-11       A/dairy cow/Colorado/024240-001/2024     024240-001
7371      2024-09-16    A/dairy cow/Michigan/24_014001-001/2024  24_014001-001
7370      2024-09-16    A/dairy cow/Michigan/24_014001-002/2024  24_014001-002
7369      2024-09-16    A/dairy cow/Michigan/24_014001-004/2024  24_014001-004

[6392 rows x 3 columns]

In [26]:
gisaid_feb_20_2026["Submission_Date"] = gisaid_feb_20_2026["Submission_Date"].apply(lambda x: dateutil.parser.parse(x))
gisaid_feb_20_2026["Collection_Date"] = gisaid_feb_20_2026["Collection_Date"].apply(lambda x: dateutil.parser.parse(x))

gisaid_feb_20_2026 = gisaid_feb_20_2026[(gisaid_feb_20_2026["Submission_Date"] >= dateutil.parser.parse("01/01/2023")) & (gisaid_feb_20_2026["Submission_Date"] <= dateutil.parser.parse("09/17/2024"))]
gisaid_feb_20_2026["Isolate"] = gisaid_feb_20_2026["Isolate_Name"].apply(lambda x: x.split("/")[-2])
# gisaid_feb_20_2026["Isolate_gisaid"] = gisaid_feb_20_2026["Isolate"]
# gisaid_feb_20_2026["Publication"]
gisaid_feb_20_2026["Geo_Location_Specific"] = gisaid_feb_20_2026["Location"].apply(lambda x: x.split(" / ")[-1] if "United States" in x else x.split(" / ")[1])
gisaid_feb_20_2026["Partial"] = gisaid_feb_20_2026["Isolate"].apply(partial_isolate)
print(gisaid_feb_20_2026.sort_values("Submission_Date")[["Submission_Date", "Isolate_Name"]])

      Submission_Date                               Isolate_Name
46         2023-01-03              A/Red Fox/SK/FAV-0824-96/2022
45         2023-01-03        A/Striped Skunk/SK/FAV-0824-01/2022
3530       2023-01-18  A/neotropic cormorant/Arizona/245467/2022
3529       2023-01-18     A/eared grebe/North Dakota/245625/2022
3528       2023-01-18      A/Canada goose/California/246038/2022
...               ...                                        ...
11173      2024-09-11       A/dairy cow/Colorado/024240-001/2024
1698       2024-09-13   A/buff-necked ibis/Bio bio/247636-1/2023
779        2024-09-16    A/dairy cow/Michigan/24_014001-001/2024
778        2024-09-16    A/dairy cow/Michigan/24_014001-002/2024
777        2024-09-16    A/dairy cow/Michigan/24_014001-004/2024

[6859 rows x 2 columns]

In [27]:
genbank_apr_14_2025["Submission_Date"] = genbank_apr_14_2025["Release_Date"].apply(lambda x: dateutil.parser.parse(x))
genbank_apr_14_2025["Collection_Date"] = genbank_apr_14_2025["Collection_Date"].apply(lambda x: dateutil.parser.parse(x))

genbank_apr_14_2025 = genbank_apr_14_2025[(genbank_apr_14_2025["Submission_Date"] >= dateutil.parser.parse("01/01/2023")) & (genbank_apr_14_2025["Submission_Date"] <= dateutil.parser.parse("09/17/2024"))]
genbank_apr_14_2025["Isolate_Name"] = genbank_apr_14_2025["GenBank_Title"].apply(lambda x: x.split("(")[1])
genbank_apr_14_2025["Isolate"] = genbank_apr_14_2025["Isolate_Name"].apply(lambda x: x.split("/")[-2])
# genbank_feb_20_2026["Isolate_genbank"] = genbank_feb_20_2026["Isolate"]
genbank_apr_14_2025["Authors"] = genbank_apr_14_2025["Submitters"].apply(lambda x: x.split(" (")[0])
print(genbank_apr_14_2025.sort_values("Submission_Date")[["Submission_Date", "Isolate_Name"]])

     Submission_Date                                       Isolate_Name
24        2023-02-04                      A/gray gull/Chile/C61947/2022
45        2023-02-04                      A/gray gull/Chile/C61947/2022
44        2023-02-04                      A/gray gull/Chile/C61947/2022
42        2023-02-04                      A/gray gull/Chile/C61947/2022
41        2023-02-04                      A/gray gull/Chile/C61947/2022
...              ...                                                ...
2748      2024-09-17  A/slender-billed parakeet/Araucania /242881-1/...
2749      2024-09-17  A/slender-billed parakeet/Araucania /242881-1/...
2750      2024-09-17  A/slender-billed parakeet/Araucania /242881-1/...
2751      2024-09-17  A/slender-billed parakeet/Araucania /242881-1/...
2753      2024-09-17  A/slender-billed parakeet/Araucania /242881-1/...

[2730 rows x 2 columns]

In [28]:
genbank_feb_20_2026["Submission_Date"] = genbank_feb_20_2026["Release_Date"].apply(lambda x: dateutil.parser.parse(x))
genbank_feb_20_2026["Collection_Date"] = genbank_feb_20_2026["Collection_Date"].apply(lambda x: dateutil.parser.parse(x))

genbank_feb_20_2026 = genbank_feb_20_2026[(genbank_feb_20_2026["Submission_Date"] >= dateutil.parser.parse("01/01/2023")) & (genbank_feb_20_2026["Submission_Date"] <= dateutil.parser.parse("09/17/2024"))]
genbank_feb_20_2026["Isolate_Name"] = genbank_feb_20_2026["GenBank_Title"].apply(lambda x: x.split("(")[1])
genbank_feb_20_2026["Isolate"] = genbank_feb_20_2026["Isolate_Name"].apply(lambda x: x.split("/")[-2])
# genbank_feb_20_2026["Isolate_genbank"] = genbank_feb_20_2026["Isolate"]
# genbank_feb_20_2026["Authors"] = genbank_feb_20_2026["Submitters"] #.apply(lambda x: x.split(" (")[0])
genbank_feb_20_2026["Partial"] = genbank_feb_20_2026["Isolate"].apply(partial_isolate)
genbank_feb_20_2026["Geo_Location_Specific"] = genbank_feb_20_2026["Geo_Location"].apply(lambda x: x.split(": ")[-1] if "USA" not in x else genbank_feb_20_2026[genbank_feb_20_2026["Geo_Location"] == x]["USA"].values[0])
print(genbank_feb_20_2026.sort_values("Submission_Date")[["Submission_Date", "Isolate_Name"]])

      Submission_Date                                       Isolate_Name
2069       2023-02-04                      A/gray gull/Chile/C61947/2022
2090       2023-02-04                      A/gray gull/Chile/C61947/2022
2089       2023-02-04                      A/gray gull/Chile/C61947/2022
2088       2023-02-04                      A/gray gull/Chile/C61947/2022
2086       2023-02-04                      A/gray gull/Chile/C61947/2022
...               ...                                                ...
26685      2024-09-17  A/slender-billed parakeet/Araucania /242881-1/...
26686      2024-09-17  A/slender-billed parakeet/Araucania /242881-1/...
26687      2024-09-17  A/slender-billed parakeet/Araucania /242881-1/...
26688      2024-09-17  A/slender-billed parakeet/Araucania /242881-1/...
26690      2024-09-17  A/slender-billed parakeet/Araucania /242881-1/...

[24622 rows x 2 columns]

In [29]:
genbank_gisaid_common = genbank_feb_20_2026.merge(gisaid_feb_20_2026, on="Isolate", suffixes=["_genbank", "_gisaid"])
print(genbank_gisaid_common)

       Accession GenBank_RefSeq         Assembly SRA_Accession BioSample  \
0     OQ352538.1        GenBank  GCA_039344385.1           NaN       NaN
1     OQ352545.1        GenBank  GCA_039343775.1           NaN       NaN
2     OQ352546.1        GenBank  GCA_039343775.1           NaN       NaN
3     OQ352547.1        GenBank  GCA_039343775.1           NaN       NaN
4     OQ352548.1        GenBank  GCA_039343775.1           NaN       NaN
...          ...            ...              ...           ...       ...
4950  PQ325300.1        GenBank  GCA_053356475.1           NaN       NaN
4951  PQ327626.1        GenBank              NaN           NaN       NaN
4952  PQ327627.1        GenBank              NaN           NaN       NaN
4953  PQ327628.1        GenBank              NaN           NaN       NaN
4954  PQ327629.1        GenBank              NaN           NaN       NaN

        BioProject      Organism_Name                         Species  \
0      PRJNA803139  Influenza A virus  Alphainfluenzavirus influenzae
1      PRJNA803139  Influenza A virus  Alphainfluenzavirus influenzae
2      PRJNA803139  Influenza A virus  Alphainfluenzavirus influenzae
3      PRJNA803139  Influenza A virus  Alphainfluenzavirus influenzae
4      PRJNA803139  Influenza A virus  Alphainfluenzavirus influenzae
...            ...                ...                             ...
4950  PRJNA1037139  Influenza A virus  Alphainfluenzavirus influenzae
4951  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
4952  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
4953  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
4954  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae

                    Genus            Family  ... Outbreak Pathogen_Test_Info  \
0     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN                NaN
1     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN                NaN
2     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN                NaN
3     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN                NaN
4     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN                NaN
...                   ...               ...  ...      ...                ...
4950  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN                NaN
4951  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN                NaN
4952  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN                NaN
4953  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN                NaN
4954  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN                NaN

      Is_Vaccinated Human_Specimen_Source  Animal_Specimen_Source  \
0               NaN                   NaN                     NaN
1               NaN                   NaN                     NaN
2               NaN                   NaN                     NaN
3               NaN                   NaN                     NaN
4               NaN                   NaN                     NaN
...             ...                   ...                     ...
4950            NaN                   NaN                     NaN
4951            NaN                   NaN                     NaN
4952            NaN                   NaN                     NaN
4953            NaN                   NaN                     NaN
4954            NaN                   NaN                     NaN

     Animal_Health_Status Domestic_Status PMID Geo_Location_Specific_gisaid  \
0                     NaN             NaN  NaN                        Chile
1                     NaN             NaN  NaN                        Chile
2                     NaN             NaN  NaN                        Chile
3                     NaN             NaN  NaN                        Chile
4                     NaN             NaN  NaN                        Chile
...                   ...             ...  ...                          ...
4950                  NaN             NaN  NaN                        Chile
4951                  NaN             NaN  NaN               North Carolina
4952                  NaN             NaN  NaN               North Carolina
4953                  NaN             NaN  NaN               North Carolina
4954                  NaN             NaN  NaN               North Carolina

     Partial_gisaid
0            C61947
1            C61962
2            C61962
3            C61962
4            C61962
...             ...
4950       247636-1
4951            121
4952            121
4953            121
4954            121

[4955 rows x 87 columns]

In [30]:
genbank_gisaid_uncommon = genbank_feb_20_2026.merge(gisaid_feb_20_2026, on=["Collection_Date", "Submission_Date", "Partial"], suffixes=["_genbank", "_gisaid"])

In [31]:
gisaid_time = gisaid_apr_14_2025.merge(gisaid_feb_20_2026, on="Isolate_Id", suffixes=["_old", "_new"])
print(gisaid_time)

            Isolate_Id                                 PB2 Segment_Id_old  \
0     EPI_ISL_16367971     EPI2274963|A/Striped Skunk/SK/FAV-0824-01/2022
1     EPI_ISL_16367899           EPI2274955|A/Red Fox/SK/FAV-0824-96/2022
2     EPI_ISL_16555205  EPI2298226|PB2_A/Canada goose/California/22-02...
3     EPI_ISL_16555204  EPI2298218|PB2_A/eared grebe/North Dakota/22-0...
4     EPI_ISL_16555203  EPI2298210|PB2_A/neotropic cormorant/Arizona/2...
...                ...                                                ...
6380  EPI_ISL_19592596  EPI3675337|A/Glaucous-winged gull/Washington/W...
6381  EPI_ISL_19592595  EPI3675329|A/Glaucous-winged gull/Washington/W...
6382  EPI_ISL_19592618  EPI3675369|A/Harbor seal/Washington/W232510072...
6383  EPI_ISL_19592610  EPI3675361|A/Harbor seal/Washington/W232490069...
6384  EPI_ISL_19592604  EPI3675353|A/Harbor seal/Washington/W232430067...

                                     PB1 Segment_Id_old  \
0        EPI2274964|A/Striped Skunk/SK/FAV-0824-01/2022
1              EPI2274956|A/Red Fox/SK/FAV-0824-96/2022
2     EPI2298227|PB1_A/Canada goose/California/22-02...
3     EPI2298219|PB1_A/eared grebe/North Dakota/22-0...
4     EPI2298211|PB1_A/neotropic cormorant/Arizona/2...
...                                                 ...
6380  EPI3675335|A/Glaucous-winged gull/Washington/W...
6381  EPI3675327|A/Glaucous-winged gull/Washington/W...
6382  EPI3675367|A/Harbor seal/Washington/W232510072...
6383  EPI3675359|A/Harbor seal/Washington/W232490069...
6384  EPI3675351|A/Harbor seal/Washington/W232430067...

                                      PA Segment_Id_old  \
0        EPI2274965|A/Striped Skunk/SK/FAV-0824-01/2022
1              EPI2274957|A/Red Fox/SK/FAV-0824-96/2022
2     EPI2298225|PA_A/Canada goose/California/22-021...
3     EPI2298217|PA_A/eared grebe/North Dakota/22-01...
4     EPI2298209|PA_A/neotropic cormorant/Arizona/22...
...                                                 ...
6380  EPI3675332|A/Glaucous-winged gull/Washington/W...
6381  EPI3675324|A/Glaucous-winged gull/Washington/W...
6382  EPI3675364|A/Harbor seal/Washington/W232510072...
6383  EPI3675356|A/Harbor seal/Washington/W232490069...
6384  EPI3675348|A/Harbor seal/Washington/W232430067...

                                      HA Segment_Id_old  \
0        EPI2274966|A/Striped Skunk/SK/FAV-0824-01/2022
1              EPI2274958|A/Red Fox/SK/FAV-0824-96/2022
2     EPI2298229|HA_A/Canada goose/California/22-021...
3     EPI2298221|HA_A/eared grebe/North Dakota/22-01...
4     EPI2298213|HA_A/neotropic cormorant/Arizona/22...
...                                                 ...
6380  EPI3675333|A/Glaucous-winged gull/Washington/W...
6381  EPI3675325|A/Glaucous-winged gull/Washington/W...
6382  EPI3675365|A/Harbor seal/Washington/W232510072...
6383  EPI3675357|A/Harbor seal/Washington/W232490069...
6384  EPI3675349|A/Harbor seal/Washington/W232430067...

                                      NP Segment_Id_old  \
0        EPI2274967|A/Striped Skunk/SK/FAV-0824-01/2022
1              EPI2274959|A/Red Fox/SK/FAV-0824-96/2022
2     EPI2298222|NP_A/Canada goose/California/22-021...
3     EPI2298214|NP_A/eared grebe/North Dakota/22-01...
4     EPI2298206|NP_A/neotropic cormorant/Arizona/22...
...                                                 ...
6380  EPI3675334|A/Glaucous-winged gull/Washington/W...
6381  EPI3675326|A/Glaucous-winged gull/Washington/W...
6382  EPI3675366|A/Harbor seal/Washington/W232510072...
6383  EPI3675358|A/Harbor seal/Washington/W232490069...
6384  EPI3675350|A/Harbor seal/Washington/W232430067...

                                      NA Segment_Id_old  \
0        EPI2274968|A/Striped Skunk/SK/FAV-0824-01/2022
1              EPI2274960|A/Red Fox/SK/FAV-0824-96/2022
2     EPI2298228|NA_A/Canada goose/California/22-021...
3     EPI2298220|NA_A/eared grebe/North Dakota/22-01...
4     EPI2298212|NA_A/neotropic cormorant/Arizona/22...
...                                                 ...
6380  EPI3675331|A/Glaucous-winged gull/Washington/W...
6381  EPI3675323|A/Glaucous-winged gull/Washington/W...
6382  EPI3675363|A/Harbor seal/Washington/W232510072...
6383  EPI3675355|A/Harbor seal/Washington/W232490069...
6384  EPI3675347|A/Harbor seal/Washington/W232430067...

                                      MP Segment_Id_old  \
0        EPI2274969|A/Striped Skunk/SK/FAV-0824-01/2022
1              EPI2274961|A/Red Fox/SK/FAV-0824-96/2022
2     EPI2298224|MP_A/Canada goose/California/22-021...
3     EPI2298216|MP_A/eared grebe/North Dakota/22-01...
4     EPI2298208|MP_A/neotropic cormorant/Arizona/22...
...                                                 ...
6380  EPI3675338|A/Glaucous-winged gull/Washington/W...
6381  EPI3675330|A/Glaucous-winged gull/Washington/W...
6382  EPI3675370|A/Harbor seal/Washington/W232510072...
6383  EPI3675362|A/Harbor seal/Washington/W232490069...
6384  EPI3675354|A/Harbor seal/Washington/W232430067...

                                      NS Segment_Id_old  HE Segment_Id_old  \
0        EPI2274970|A/Striped Skunk/SK/FAV-0824-01/2022                NaN
1              EPI2274962|A/Red Fox/SK/FAV-0824-96/2022                NaN
2     EPI2298223|NS_A/Canada goose/California/22-021...                NaN
3     EPI2298215|NS_A/eared grebe/North Dakota/22-01...                NaN
4     EPI2298207|NS_A/neotropic cormorant/Arizona/22...                NaN
...                                                 ...                ...
6380  EPI3675336|A/Glaucous-winged gull/Washington/W...                NaN
6381  EPI3675328|A/Glaucous-winged gull/Washington/W...                NaN
6382  EPI3675368|A/Harbor seal/Washington/W232510072...                NaN
6383  EPI3675360|A/Harbor seal/Washington/W232490069...                NaN
6384  EPI3675352|A/Harbor seal/Washington/W232430067...                NaN

      ...  Pathogen_Test_Info_new Is_Vaccinated_new Human_Specimen_Source_new  \
0     ...                     NaN               NaN                       NaN
1     ...                     NaN               NaN                       NaN
2     ...                     NaN               NaN                       NaN
3     ...                     NaN               NaN                       NaN
4     ...                     NaN               NaN                       NaN
...   ...                     ...               ...                       ...
6380  ...                     NaN               NaN                       NaN
6381  ...                     NaN               NaN                       NaN
6382  ...                     NaN               NaN                       NaN
6383  ...                     NaN               NaN                       NaN
6384  ...                     NaN               NaN                       NaN

     Animal_Specimen_Source_new  Animal_Health_Status_new Domestic_Status_new  \
0                         Organ                      Dead                Wild
1                         Organ                      Dead                Wild
2                           NaN                       NaN                 NaN
3                           NaN                       NaN                 NaN
4                           NaN                       NaN                 NaN
...                         ...                       ...                 ...
6380                        NaN                       NaN                 NaN
6381                        NaN                       NaN                 NaN
6382                        NaN                       NaN                 NaN
6383                        NaN                       NaN                 NaN
6384                        NaN                       NaN                 NaN

     PMID_new     Isolate_new Geo_Location_Specific         Partial
0         NaN     FAV-0824-01                Canada     FAV-0824-01
1         NaN     FAV-0824-96                Canada     FAV-0824-96
2         NaN          246038         Colusa County          246038
3         NaN          245625       Stutsman County          245625
4         NaN          245467       Maricopa County          245467
...       ...             ...                   ...             ...
6380      NaN    W232270041-2            Washington    W232270041-2
6381      NaN    W231990001-1            Washington    W231990001-1
6382      NaN  W232510072-3-1            Washington  W232510072-3-1
6383      NaN    W232490069-3            Washington    W232490069-3
6384      NaN  W232430067-2-3            Washington  W232430067-2-3

[6385 rows x 112 columns]

## Differences between GenBank and GISAID

### Isolates

All of the following have the same isolate "root", but different complete isolates. 

Isolate discrepancy examples:
- Sometimes the beginning hyphen in an isolate will be changed to an underscore (24-014001-004 -> 24_014001-004)
- Sometimes an appended "-original" at the end of the isolate will disappear (24-014001-004-original -> 24-014001-004)
- Sometimes the last two digits of a year at the beginning of an isolate will disappear (24-009038-001 -> 009038-001)
- Sometimes a repeated isolate will have the "-repeat2" appendage changed to "-R2" (24-015840-001-original-repeat2 -> 24_015840-001-R2)
- Sometimes, despite the same authors, collection date, location, and host, the isolate IDs are completely different (CEIRR-293 -> TN22-293)

In [32]:
print(genbank_gisaid_uncommon[genbank_gisaid_uncommon["Isolate_genbank"] != genbank_gisaid_uncommon["Isolate_gisaid"]][["Isolate_genbank", "Isolate_gisaid", "Isolate_Name_genbank", "Isolate_Name_gisaid"]])

            Isolate_genbank Isolate_gisaid  \
0             24-009038-001     009038-001
1             24-009038-001     009038-001
2             24-009038-001     009038-001
3             24-009038-001     009038-001
4             24-009038-001     009038-001
..                      ...            ...
323  24-014001-004-original  24_014001-004
324  24-014001-004-original  24_014001-004
325  24-014001-004-original  24_014001-004
326  24-014001-004-original  24_014001-004
327  24-014001-004-original  24_014001-004

                          Isolate_Name_genbank  \
0    A/domestic cat/Montana/24-009038-001/2024
1    A/domestic cat/Montana/24-009038-001/2024
2    A/domestic cat/Montana/24-009038-001/2024
3    A/domestic cat/Montana/24-009038-001/2024
4    A/domestic cat/Montana/24-009038-001/2024
..                                         ...
323    A/cattle/MI/24-014001-004-original/2024
324    A/cattle/MI/24-014001-004-original/2024
325    A/cattle/MI/24-014001-004-original/2024
326    A/cattle/MI/24-014001-004-original/2024
327    A/cattle/MI/24-014001-004-original/2024

                         Isolate_Name_gisaid
0              A/cat/Montana/009038-001/2024
1              A/cat/Montana/009038-001/2024
2              A/cat/Montana/009038-001/2024
3              A/cat/Montana/009038-001/2024
4              A/cat/Montana/009038-001/2024
..                                       ...
323  A/dairy cow/Michigan/24_014001-004/2024
324  A/dairy cow/Michigan/24_014001-004/2024
325  A/dairy cow/Michigan/24_014001-004/2024
326  A/dairy cow/Michigan/24_014001-004/2024
327  A/dairy cow/Michigan/24_014001-004/2024

[72 rows x 4 columns]

In [33]:
print(genbank_gisaid_uncommon[genbank_gisaid_uncommon["Isolate_gisaid"] != genbank_gisaid_uncommon["Isolate_genbank"]][["Isolate_genbank", "Isolate_gisaid", "Isolate_Name_genbank", "Isolate_Name_gisaid"]][:50])

                    Isolate_genbank    Isolate_gisaid  \
0                     24-009038-001        009038-001
1                     24-009038-001        009038-001
2                     24-009038-001        009038-001
3                     24-009038-001        009038-001
4                     24-009038-001        009038-001
5                     24-009038-001        009038-001
6                     24-009038-001        009038-001
7                     24-009038-001        009038-001
8                     24-007379-002        007379-002
9                     24-007379-002        007379-002
10                    24-007379-002        007379-002
11                    24-007379-002        007379-002
12                    24-007379-002        007379-002
13                    24-007379-002        007379-002
14                    24-007379-002        007379-002
15                    24-007379-002        007379-002
16                    24-008552-021        008552-021
17                    24-008552-021        008552-021
18                    24-008552-021        008552-021
19                    24-008552-021        008552-021
20                    24-008552-021        008552-021
21                    24-008552-021        008552-021
22                    24-008552-021        008552-021
23                    24-008552-021        008552-021
24                    24-009109-002     24_009109-002
25                    24-009109-002     24_009109-002
26                    24-009109-002     24_009109-002
27                    24-009109-002     24_009109-002
28                    24-009109-002     24_009109-002
29                    24-009109-002     24_009109-002
30                    24-009109-002     24_009109-002
31                    24-009109-002     24_009109-002
72   24-015840-001-original-repeat2  24_015840-001-R2
73   24-015840-001-original-repeat2  24_015840-001-R2
74   24-015840-001-original-repeat2  24_015840-001-R2
75   24-015840-001-original-repeat2  24_015840-001-R2
76   24-015840-001-original-repeat2  24_015840-001-R2
77   24-015840-001-original-repeat2  24_015840-001-R2
78   24-015840-001-original-repeat2  24_015840-001-R2
79   24-015840-001-original-repeat2  24_015840-001-R2
80   24-015840-002-original-repeat2  24_015840-002-R2
81   24-015840-002-original-repeat2  24_015840-002-R2
82   24-015840-002-original-repeat2  24_015840-002-R2
83   24-015840-002-original-repeat2  24_015840-002-R2
84   24-015840-002-original-repeat2  24_015840-002-R2
85   24-015840-002-original-repeat2  24_015840-002-R2
86   24-015840-002-original-repeat2  24_015840-002-R2
87   24-015840-002-original-repeat2  24_015840-002-R2
304          24-014001-001-original     24_014001-001
305          24-014001-001-original     24_014001-001

                                Isolate_Name_genbank  \
0          A/domestic cat/Montana/24-009038-001/2024
1          A/domestic cat/Montana/24-009038-001/2024
2          A/domestic cat/Montana/24-009038-001/2024
3          A/domestic cat/Montana/24-009038-001/2024
4          A/domestic cat/Montana/24-009038-001/2024
5          A/domestic cat/Montana/24-009038-001/2024
6          A/domestic cat/Montana/24-009038-001/2024
7          A/domestic cat/Montana/24-009038-001/2024
8           A/turkey/South Dakota/24-007379-002/2024
9           A/turkey/South Dakota/24-007379-002/2024
10          A/turkey/South Dakota/24-007379-002/2024
11          A/turkey/South Dakota/24-007379-002/2024
12          A/turkey/South Dakota/24-007379-002/2024
13          A/turkey/South Dakota/24-007379-002/2024
14          A/turkey/South Dakota/24-007379-002/2024
15          A/turkey/South Dakota/24-007379-002/2024
16         A/american wigeon/Ohio/24-008552-021/2023
17         A/american wigeon/Ohio/24-008552-021/2023
18         A/american wigeon/Ohio/24-008552-021/2023
19         A/american wigeon/Ohio/24-008552-021/2023
20         A/american wigeon/Ohio/24-008552-021/2023
21         A/american wigeon/Ohio/24-008552-021/2023
22         A/american wigeon/Ohio/24-008552-021/2023
23         A/american wigeon/Ohio/24-008552-021/2023
24                 A/cattle/Texas/24-009109-002/2024
25                 A/cattle/Texas/24-009109-002/2024
26                 A/cattle/Texas/24-009109-002/2024
27                 A/cattle/Texas/24-009109-002/2024
28                 A/cattle/Texas/24-009109-002/2024
29                 A/cattle/Texas/24-009109-002/2024
30                 A/cattle/Texas/24-009109-002/2024
31                 A/cattle/Texas/24-009109-002/2024
72   A/cattle/NM/24-015840-001-original-repeat2/2024
73   A/cattle/NM/24-015840-001-original-repeat2/2024
74   A/cattle/NM/24-015840-001-original-repeat2/2024
75   A/cattle/NM/24-015840-001-original-repeat2/2024
76   A/cattle/NM/24-015840-001-original-repeat2/2024
77   A/cattle/NM/24-015840-001-original-repeat2/2024
78   A/cattle/NM/24-015840-001-original-repeat2/2024
79   A/cattle/NM/24-015840-001-original-repeat2/2024
80   A/cattle/NM/24-015840-002-original-repeat2/2024
81   A/cattle/NM/24-015840-002-original-repeat2/2024
82   A/cattle/NM/24-015840-002-original-repeat2/2024
83   A/cattle/NM/24-015840-002-original-repeat2/2024
84   A/cattle/NM/24-015840-002-original-repeat2/2024
85   A/cattle/NM/24-015840-002-original-repeat2/2024
86   A/cattle/NM/24-015840-002-original-repeat2/2024
87   A/cattle/NM/24-015840-002-original-repeat2/2024
304          A/cattle/MI/24-014001-001-original/2024
305          A/cattle/MI/24-014001-001-original/2024

                              Isolate_Name_gisaid
0                   A/cat/Montana/009038-001/2024
1                   A/cat/Montana/009038-001/2024
2                   A/cat/Montana/009038-001/2024
3                   A/cat/Montana/009038-001/2024
4                   A/cat/Montana/009038-001/2024
5                   A/cat/Montana/009038-001/2024
6                   A/cat/Montana/009038-001/2024
7                   A/cat/Montana/009038-001/2024
8           A/turkey/South Dakota/007379-002/2024
9           A/turkey/South Dakota/007379-002/2024
10          A/turkey/South Dakota/007379-002/2024
11          A/turkey/South Dakota/007379-002/2024
12          A/turkey/South Dakota/007379-002/2024
13          A/turkey/South Dakota/007379-002/2024
14          A/turkey/South Dakota/007379-002/2024
15          A/turkey/South Dakota/007379-002/2024
16         A/american wigeon/Ohio/008552-021/2023
17         A/american wigeon/Ohio/008552-021/2023
18         A/american wigeon/Ohio/008552-021/2023
19         A/american wigeon/Ohio/008552-021/2023
20         A/american wigeon/Ohio/008552-021/2023
21         A/american wigeon/Ohio/008552-021/2023
22         A/american wigeon/Ohio/008552-021/2023
23         A/american wigeon/Ohio/008552-021/2023
24           A/dairy_cow/Texas/24_009109-002/2024
25           A/dairy_cow/Texas/24_009109-002/2024
26           A/dairy_cow/Texas/24_009109-002/2024
27           A/dairy_cow/Texas/24_009109-002/2024
28           A/dairy_cow/Texas/24_009109-002/2024
29           A/dairy_cow/Texas/24_009109-002/2024
30           A/dairy_cow/Texas/24_009109-002/2024
31           A/dairy_cow/Texas/24_009109-002/2024
72   A/dairy cow/New Mexico/24_015840-001-R2/2024
73   A/dairy cow/New Mexico/24_015840-001-R2/2024
74   A/dairy cow/New Mexico/24_015840-001-R2/2024
75   A/dairy cow/New Mexico/24_015840-001-R2/2024
76   A/dairy cow/New Mexico/24_015840-001-R2/2024
77   A/dairy cow/New Mexico/24_015840-001-R2/2024
78   A/dairy cow/New Mexico/24_015840-001-R2/2024
79   A/dairy cow/New Mexico/24_015840-001-R2/2024
80   A/dairy cow/New Mexico/24_015840-002-R2/2024
81   A/dairy cow/New Mexico/24_015840-002-R2/2024
82   A/dairy cow/New Mexico/24_015840-002-R2/2024
83   A/dairy cow/New Mexico/24_015840-002-R2/2024
84   A/dairy cow/New Mexico/24_015840-002-R2/2024
85   A/dairy cow/New Mexico/24_015840-002-R2/2024
86   A/dairy cow/New Mexico/24_015840-002-R2/2024
87   A/dairy cow/New Mexico/24_015840-002-R2/2024
304       A/dairy cow/Michigan/24_014001-001/2024
305       A/dairy cow/Michigan/24_014001-001/2024

### Isolate Names

All of these share isolate IDs, but have different full isolate names. This occurs in about half (2719/4955) of our sample. 

Isolate name discrepancy examples:
- GISAID sometimes cuts off or changes the specific type of animal to a general animal (snow goose -> goose, black vulture -> vulture, mallard -> duck, etc.)
- GISAID sometimes subtly changes the location name (Bio Bio -> Biobio, CHL -> Chile, etc.)
- GISAID sometimes changes the specific location to a more general location (Antofagasta -> Chile, etc.)
- Sometimes the isolate ids between genbank and gisaid are the same, but the isolate names are completely different (A/Missouri/121/2024 has the same isolate id as A/red-shouldered hawk/North Carolina/121/2022, etc.)

In [34]:
genbank_gisaid_common[genbank_gisaid_common["Isolate_Name_genbank"] != genbank_gisaid_common["Isolate_Name_gisaid"]][["Isolate_Name_genbank", "Isolate_Name_gisaid"]]

,Isolate_Name_genbank,Isolate_Name_gisaid
16,A/Gull/CHL/227023-3/2022,A/Gull/Chile/227023-3/2022
17,A/Gull/CHL/227023-3/2022,A/Gull/Chile/227023-3/2022
18,A/Gull/CHL/227023-3/2022,A/Gull/Chile/227023-3/2022
19,A/Gull/CHL/227023-2/2022,A/Gull/Chile/227023-2/2022
20,A/Gull/CHL/227023-2/2022,A/Gull/Chile/227023-2/2022
...,...,...
4942,A/gull/Bio Bio/237012/2023,A/gull/Biobio/237012/2023
4951,A/Missouri/121/2024,A/red-shouldered hawk/North Carolina/121/2022
4952,A/Missouri/121/2024,A/red-shouldered hawk/North Carolina/121/2022
4953,A/Missouri/121/2024,A/red-shouldered hawk/North Carolina/121/2022
4954,A/Missouri/121/2024,A/red-shouldered hawk/North Carolina/121/2022

### Collection Dates

All of these share isolate IDs, but have different collection dates in the metadata. This occurs in (117/4955) entries of our sample.

Date discrepancy examples:
- GISAID sometimes changes the collection date to the beginning of the month (2022-12-26 -> 12-01-2022, etc.)
- GISAID sometimes changes the collection date to a completely different date (2024-03-08 -> 2024-02-26, etc.)
- GISAID sometimes changes the collection date, if unknown and year 2025-2026, to the first of the year (2025 -> 2025-01-01, etc.) (Not in this sample)

In [35]:
genbank_gisaid_common[genbank_gisaid_common["Collection_Date_gisaid"] != genbank_gisaid_common["Collection_Date_genbank"]][["Isolate_Name_genbank", "Isolate_Name_gisaid", "Isolate", "Collection_Date_genbank", "Collection_Date_gisaid"]]

,Isolate_Name_genbank,Isolate_Name_gisaid,Isolate,Collection_Date_genbank,Collection_Date_gisaid
33,A/Pelecanus/Peru/VFAR-140/2022,A/Pelecanus/Peru/VFAR-140/2022,VFAR-140,2022-12-27,2022-12-01
35,A/Pelecanus/Peru/VFAR-140/2022,A/Pelecanus/Peru/VFAR-140/2022,VFAR-140,2022-12-27,2022-12-01
37,A/Pelecanus/Peru/VFAR-140/2022,A/Pelecanus/Peru/VFAR-140/2022,VFAR-140,2022-12-27,2022-12-01
39,A/Pelecanus/Peru/VFAR-140/2022,A/Pelecanus/Peru/VFAR-140/2022,VFAR-140,2022-12-27,2022-12-01
41,A/Pelecanus/Peru/VFAR-140/2022,A/Pelecanus/Peru/VFAR-140/2022,VFAR-140,2022-12-27,2022-12-01
...,...,...,...,...,...
4652,A/Brown Skua/South Georgia and the South Sandw...,A/dairy cow/Kansas/5/2024,5,2023-10-08,2024-04-27
4951,A/Missouri/121/2024,A/red-shouldered hawk/North Carolina/121/2022,121,2024-08-22,2022-02-12
4952,A/Missouri/121/2024,A/red-shouldered hawk/North Carolina/121/2022,121,2024-08-22,2022-02-12
4953,A/Missouri/121/2024,A/red-shouldered hawk/North Carolina/121/2022,121,2024-08-22,2022-02-12
4954,A/Missouri/121/2024,A/red-shouldered hawk/North Carolina/121/2022,121,2024-08-22,2022-02-12

### Host Names

All of these share isolate IDs, but have different host names in the metadata. This occurs in the **majority** (4811/4955) of our sample, though much of this can be explained by GISAID opting for the common name over the scientific name of each species.

Host name discrepancy examples:
- GISAID often just has the word "Host" in place of a host name (Leucophaeus modestus/gray gull -> Host)
- GISAID often, instead of using the specific species, has the host type in place of a host name (Theristicus caudatus/buff-necked ibis -> Avian)

In [36]:
genbank_gisaid_common[genbank_gisaid_common["Host_gisaid"] != genbank_gisaid_common["Host_genbank"]][["Isolate_Name_genbank", "Isolate_Name_gisaid", "Isolate", "Host_genbank", "Host_gisaid"]]

,Isolate_Name_genbank,Isolate_Name_gisaid,Isolate,Host_genbank,Host_gisaid
0,A/gray gull/Chile/C61947/2022,A/gray gull/Chile/C61947/2022,C61947,Leucophaeus modestus,Host
9,A/gray gull/Chile/C61947/2022,A/gray gull/Chile/C61947/2022,C61947,Leucophaeus modestus,Host
10,A/gray gull/Chile/C61947/2022,A/gray gull/Chile/C61947/2022,C61947,Leucophaeus modestus,Host
11,A/gray gull/Chile/C61947/2022,A/gray gull/Chile/C61947/2022,C61947,Leucophaeus modestus,Host
12,A/gray gull/Chile/C61947/2022,A/gray gull/Chile/C61947/2022,C61947,Leucophaeus modestus,Host
...,...,...,...,...,...
4950,A/buff-necked ibis/Bio bio/247636-1/2023,A/buff-necked ibis/Bio bio/247636-1/2023,247636-1,Theristicus caudatus,Avian
4951,A/Missouri/121/2024,A/red-shouldered hawk/North Carolina/121/2022,121,Homo sapiens,Buteo lineatus
4952,A/Missouri/121/2024,A/red-shouldered hawk/North Carolina/121/2022,121,Homo sapiens,Buteo lineatus
4953,A/Missouri/121/2024,A/red-shouldered hawk/North Carolina/121/2022,121,Homo sapiens,Buteo lineatus
4954,A/Missouri/121/2024,A/red-shouldered hawk/North Carolina/121/2022,121,Homo sapiens,Buteo lineatus

### Locations

In [51]:
# print(genbank_gisaid_common[genbank_gisaid_common["Geo_Location_Specific_gisaid"] != genbank_gisaid_common["Geo_Location_Specific_genbank"]][["Isolate_Name_genbank", "Isolate_Name_gisaid", "Isolate", "Geo_Location_Specific_genbank", "Geo_Location_Specific_gisaid"]])
print(genbank_gisaid_common[(genbank_gisaid_common["Geo_Location_Specific_gisaid"] != genbank_gisaid_common["USA"]) & (genbank_gisaid_common["Country"] == "USA")][["Isolate_Name_genbank", "Isolate_Name_gisaid", "Isolate", "Geo_Location_Specific_genbank", "Geo_Location_Specific_gisaid"]][-50:])

                      Isolate_Name_genbank  \
4614                   A/Colorado/137/2024
4615                   A/Colorado/137/2024
4616                   A/Colorado/137/2024
4617                   A/Colorado/137/2024
4618                   A/Colorado/137/2024
4619                   A/Colorado/137/2024
4620                   A/Colorado/138/2024
4621                   A/Colorado/138/2024
4622                   A/Colorado/138/2024
4623                   A/Colorado/138/2024
4624                   A/Colorado/138/2024
4625                   A/Colorado/138/2024
4626                   A/Colorado/138/2024
4627                   A/Colorado/138/2024
4628                   A/Colorado/139/2024
4629                   A/Colorado/139/2024
4630                   A/Colorado/139/2024
4631                   A/Colorado/139/2024
4632                   A/Colorado/139/2024
4633                   A/Colorado/139/2024
4634                   A/Colorado/139/2024
4635                   A/Colorado/139/2024
4636          A/dairy cow/Kansas/SM-3/2024
4637          A/dairy cow/Kansas/SM-3/2024
4638          A/dairy cow/Kansas/SM-3/2024
4639          A/dairy cow/Kansas/SM-3/2024
4640          A/dairy cow/Kansas/SM-3/2024
4641          A/dairy cow/Kansas/SM-3/2024
4642          A/dairy cow/Kansas/SM-3/2024
4643          A/dairy cow/Kansas/SM-3/2024
4653  A/dairy cow/Texas/A240750066-18/2024
4654  A/dairy cow/Texas/A240750066-18/2024
4655  A/dairy cow/Texas/A240750066-18/2024
4656  A/dairy cow/Texas/A240750066-18/2024
4657  A/dairy cow/Texas/A240750066-18/2024
4658  A/dairy cow/Texas/A240750066-18/2024
4659  A/dairy cow/Texas/A240750066-18/2024
4660  A/dairy cow/Texas/A240750066-18/2024
4661         A/bovine/Ohio/B24OSU-541/2024
4662         A/bovine/Ohio/B24OSU-541/2024
4663         A/bovine/Ohio/B24OSU-541/2024
4664         A/bovine/Ohio/B24OSU-541/2024
4665         A/bovine/Ohio/B24OSU-541/2024
4666         A/bovine/Ohio/B24OSU-541/2024
4667         A/bovine/Ohio/B24OSU-541/2024
4668         A/bovine/Ohio/B24OSU-541/2024
4951                   A/Missouri/121/2024
4952                   A/Missouri/121/2024
4953                   A/Missouri/121/2024
4954                   A/Missouri/121/2024

                                Isolate_Name_gisaid        Isolate  \
4614                            A/Colorado/137/2024            137
4615                            A/Colorado/137/2024            137
4616                            A/Colorado/137/2024            137
4617                            A/Colorado/137/2024            137
4618                            A/Colorado/137/2024            137
4619                            A/Colorado/137/2024            137
4620                            A/Colorado/138/2024            138
4621                            A/Colorado/138/2024            138
4622                            A/Colorado/138/2024            138
4623                            A/Colorado/138/2024            138
4624                            A/Colorado/138/2024            138
4625                            A/Colorado/138/2024            138
4626                            A/Colorado/138/2024            138
4627                            A/Colorado/138/2024            138
4628                            A/Colorado/139/2024            139
4629                            A/Colorado/139/2024            139
4630                            A/Colorado/139/2024            139
4631                            A/Colorado/139/2024            139
4632                            A/Colorado/139/2024            139
4633                            A/Colorado/139/2024            139
4634                            A/Colorado/139/2024            139
4635                            A/Colorado/139/2024            139
4636               A/dairy cow/New Mexico/SM-3/2024           SM-3
4637               A/dairy cow/New Mexico/SM-3/2024           SM-3
4638               A/dairy cow/New Mexico/SM-3/2024           SM-3
4639               A/dairy cow/New Mexico/SM-3/2024           SM-3
4640               A/dairy cow/New Mexico/SM-3/2024           SM-3
4641               A/dairy cow/New Mexico/SM-3/2024           SM-3
4642               A/dairy cow/New Mexico/SM-3/2024           SM-3
4643               A/dairy cow/New Mexico/SM-3/2024           SM-3
4653           A/dairy cow/Texas/A240750066-18/2024  A240750066-18
4654           A/dairy cow/Texas/A240750066-18/2024  A240750066-18
4655           A/dairy cow/Texas/A240750066-18/2024  A240750066-18
4656           A/dairy cow/Texas/A240750066-18/2024  A240750066-18
4657           A/dairy cow/Texas/A240750066-18/2024  A240750066-18
4658           A/dairy cow/Texas/A240750066-18/2024  A240750066-18
4659           A/dairy cow/Texas/A240750066-18/2024  A240750066-18
4660           A/dairy cow/Texas/A240750066-18/2024  A240750066-18
4661               A/dairy cow/Ohio/B24OSU-541/2024     B24OSU-541
4662               A/dairy cow/Ohio/B24OSU-541/2024     B24OSU-541
4663               A/dairy cow/Ohio/B24OSU-541/2024     B24OSU-541
4664               A/dairy cow/Ohio/B24OSU-541/2024     B24OSU-541
4665               A/dairy cow/Ohio/B24OSU-541/2024     B24OSU-541
4666               A/dairy cow/Ohio/B24OSU-541/2024     B24OSU-541
4667               A/dairy cow/Ohio/B24OSU-541/2024     B24OSU-541
4668               A/dairy cow/Ohio/B24OSU-541/2024     B24OSU-541
4951  A/red-shouldered hawk/North Carolina/121/2022            121
4952  A/red-shouldered hawk/North Carolina/121/2022            121
4953  A/red-shouldered hawk/North Carolina/121/2022            121
4954  A/red-shouldered hawk/North Carolina/121/2022            121

     Geo_Location_Specific_genbank Geo_Location_Specific_gisaid
4614                            CO                     Colorado
4615                            CO                     Colorado
4616                            CO                     Colorado
4617                            CO                     Colorado
4618                            CO                     Colorado
4619                            CO                     Colorado
4620                            CO                     Colorado
4621                            CO                     Colorado
4622                            CO                     Colorado
4623                            CO                     Colorado
4624                            CO                     Colorado
4625                            CO                     Colorado
4626                            CO                     Colorado
4627                            CO                     Colorado
4628                            CO                     Colorado
4629                            CO                     Colorado
4630                            CO                     Colorado
4631                            CO                     Colorado
4632                            CO                     Colorado
4633                            CO                     Colorado
4634                            CO                     Colorado
4635                            CO                     Colorado
4636                            KS                   New Mexico
4637                            KS                   New Mexico
4638                            KS                   New Mexico
4639                            KS                   New Mexico
4640                            KS                   New Mexico
4641                            KS                   New Mexico
4642                            KS                   New Mexico
4643                            KS                   New Mexico
4653                            TX                        Texas
4654                            TX                        Texas
4655                            TX                        Texas
4656                            TX                        Texas
4657                            TX                        Texas
4658                            TX                        Texas
4659                            TX                        Texas
4660                            TX                        Texas
4661                            OH                         Ohio
4662                            OH                         Ohio
4663                            OH                         Ohio
4664                            OH                         Ohio
4665                            OH                         Ohio
4666                            OH                         Ohio
4667                            OH                         Ohio
4668                            OH                         Ohio
4951                            MO               North Carolina
4952                            MO               North Carolina
4953                            MO               North Carolina
4954                            MO               North Carolina

## GISAID Metadata Updates

Sometimes, GISAID silently updates or changes metadata without warning.

GISAID metadata change examples:
- Sometimes GISAID appends or removes the last two digits of the year to the isolate ID, changing the strain name altogether (24_035820-001 -> 024710-001)
    - The last two digits of the year may be appended with an underscore, or a hyphen, making parsing the "root" isolate ID difficult (24-000001-001 vs. 24_000001-001)
    - Some isolate IDs include an "-original" appendage, making de-duplication between databases difficult (24-000001-001-original vs. 24-000001-001)
    - Some isolate IDs include an "-R2" or "-repeat2" appendage, making de-duplication between databases difficult (24-000001-001-R2 or 24-000001-001-original-repeat2 vs. 24-000001-001)
- Sometimes dates change completely without warning (2024-02-27 -> 2024-08-26)
- Sometimes dates are egregiously incorrect, both in the isolate name and the metadata, and must be updated later (A/bald eagle/Alaska/22-035250-002/1905, 1905-07-14 -> A/bald eagle/Alaska/22-035250-002/2022, 2022-02-27) 
- Genotypes may change without warning, or a genotype may be changed from an assigned to genotype to "Not assigned", even when the genotype is still current (B3.13 -> Notassigned)
    - Genotypes disappear in (135/6385) entries in our sample.
    - Rarely will a genotype be updated from "Not assigned" to an assigned genotype
- There is no mechanism in GISAID to know when metadata is updated -- meaning that all data must be downloaded each time just in case metadata (or the strain name altogether) has changed (A/dairy cow/USA/24_024710-001/2024 -> A/dairy cow/California/024710-001/2024)
    - While an "update date" column exists in the metadata, it mostly seems to only match the submission date -- otherwise, the update is either unclear or a removal of a previously assigned genotype without a replacement (B3.2 -> Notassigned)

In [38]:
print(gisaid_time[gisaid_time["Isolate_old"] != gisaid_time["Isolate_new"]][["Isolate_Name_old", "Isolate_Name_new", "Isolate_old", "Isolate_new"]])

                        Isolate_Name_old  \
6362  A/dairy cow/USA/24_024710-001/2024
6363  A/dairy cow/USA/24_024710-006/2024
6364  A/dairy cow/USA/24_024710-008/2024
6365  A/dairy cow/USA/24_024710-009/2024

                            Isolate_Name_new    Isolate_old Isolate_new
6362  A/dairy cow/California/024710-001/2024  24_024710-001  024710-001
6363  A/dairy cow/California/024710-006/2024  24_024710-006  024710-006
6364  A/dairy cow/California/024710-008/2024  24_024710-008  024710-008
6365  A/dairy cow/California/024710-009/2024  24_024710-009  024710-009

In [39]:
print(gisaid_time[gisaid_time["Isolate_Name_old"] != gisaid_time["Isolate_Name_new"]][["Isolate_Name_old", "Isolate_Name_new", "Isolate_old", "Isolate_new", "Collection_Date_old", "Collection_Date_new"]])

                            Isolate_Name_old  \
4052  A/bald eagle/Alaska/22-035250-002/1905
4053  A/bald eagle/Alaska/22-035250-001/1905
6362      A/dairy cow/USA/24_024710-001/2024
6363      A/dairy cow/USA/24_024710-006/2024
6364      A/dairy cow/USA/24_024710-008/2024
6365      A/dairy cow/USA/24_024710-009/2024

                            Isolate_Name_new    Isolate_old    Isolate_new  \
4052  A/bald eagle/Alaska/22-035250-002/2022  22-035250-002  22-035250-002
4053  A/bald eagle/Alaska/22-035250-001/2022  22-035250-001  22-035250-001
6362  A/dairy cow/California/024710-001/2024  24_024710-001     024710-001
6363  A/dairy cow/California/024710-006/2024  24_024710-006     024710-006
6364  A/dairy cow/California/024710-008/2024  24_024710-008     024710-008
6365  A/dairy cow/California/024710-009/2024  24_024710-009     024710-009

     Collection_Date_old Collection_Date_new
4052          1905-07-14          2022-02-27
4053          1905-07-14          2022-02-27
6362          2024-02-27          2024-08-26
6363          2024-02-27          2024-08-26
6364          2024-02-27          2024-08-26
6365          2024-02-27          2024-08-26

In [40]:
print(gisaid_time[gisaid_time["Collection_Date_old"] != gisaid_time["Collection_Date_new"]][["Isolate_Name_old", "Isolate_Name_new", "Isolate_old", "Isolate_new", "Collection_Date_old", "Collection_Date_new"]])

                            Isolate_Name_old  \
4052  A/bald eagle/Alaska/22-035250-002/1905
4053  A/bald eagle/Alaska/22-035250-001/1905
6362      A/dairy cow/USA/24_024710-001/2024
6363      A/dairy cow/USA/24_024710-006/2024
6364      A/dairy cow/USA/24_024710-008/2024
6365      A/dairy cow/USA/24_024710-009/2024

                            Isolate_Name_new    Isolate_old    Isolate_new  \
4052  A/bald eagle/Alaska/22-035250-002/2022  22-035250-002  22-035250-002
4053  A/bald eagle/Alaska/22-035250-001/2022  22-035250-001  22-035250-001
6362  A/dairy cow/California/024710-001/2024  24_024710-001     024710-001
6363  A/dairy cow/California/024710-006/2024  24_024710-006     024710-006
6364  A/dairy cow/California/024710-008/2024  24_024710-008     024710-008
6365  A/dairy cow/California/024710-009/2024  24_024710-009     024710-009

     Collection_Date_old Collection_Date_new
4052          1905-07-14          2022-02-27
4053          1905-07-14          2022-02-27
6362          2024-02-27          2024-08-26
6363          2024-02-27          2024-08-26
6364          2024-02-27          2024-08-26
6365          2024-02-27          2024-08-26

In [41]:
print(gisaid_time[gisaid_time["Location_old"] != gisaid_time["Location_new"]][["Isolate_Name_old", "Isolate_Name_new", "Isolate_old", "Isolate_new","Location_old", "Location_new"]])

                        Isolate_Name_old  \
6362  A/dairy cow/USA/24_024710-001/2024
6363  A/dairy cow/USA/24_024710-006/2024
6364  A/dairy cow/USA/24_024710-008/2024
6365  A/dairy cow/USA/24_024710-009/2024

                            Isolate_Name_new    Isolate_old Isolate_new  \
6362  A/dairy cow/California/024710-001/2024  24_024710-001  024710-001
6363  A/dairy cow/California/024710-006/2024  24_024710-006  024710-006
6364  A/dairy cow/California/024710-008/2024  24_024710-008  024710-008
6365  A/dairy cow/California/024710-009/2024  24_024710-009  024710-009

                       Location_old  \
6362  North America / United States
6363  North America / United States
6364  North America / United States
6365  North America / United States

                                    Location_new
6362  North America / United States / California
6363  North America / United States / California
6364  North America / United States / California
6365  North America / United States / California

In [42]:
print(gisaid_time[gisaid_time["Genotype_old"] != gisaid_time["Genotype_new"]][["Isolate_Name_old", "Isolate_Name_new", "Isolate_old", "Isolate_new","Genotype_old", "Genotype_new"]])
print(gisaid_time[(gisaid_time["Genotype_old"] != gisaid_time["Genotype_new"]) & (gisaid_time["Genotype_new"].str.contains("Notassigned"))][["Isolate_Name_old", "Isolate_Name_new", "Isolate_old", "Isolate_new","Genotype_old", "Genotype_new"]])

                                       Isolate_Name_old  \
3527             A/Great_Horned_Owl/BC/FAV-0856-18/2022
3528       A/Great_Black-Backed_Gull/QC/FAV-0870-4/2022
3529      A/Great_Black-Backed_Gull/QC/FAV-0829-12/2022
3536             A/Northwestern_Crow/BC/FAV-0669-4/2022
5236         A/chicken/Iowa/23-038644-001-original/2023
...                                                 ...
6343        A/mallard/Maine/24-004330-004-original/2024
6345        A/mallard/Maine/24-004329-016-original/2024
6346        A/mallard/Maine/24-004329-015-original/2024
6347  A/green-winged teal/North Carolina/24-004327-0...
6370               A/dairy cow/Colorado/024240-001/2024

                                       Isolate_Name_new  \
3527             A/Great_Horned_Owl/BC/FAV-0856-18/2022
3528       A/Great_Black-Backed_Gull/QC/FAV-0870-4/2022
3529      A/Great_Black-Backed_Gull/QC/FAV-0829-12/2022
3536             A/Northwestern_Crow/BC/FAV-0669-4/2022
5236         A/chicken/Iowa/23-038644-001-original/2023
...                                                 ...
6343        A/mallard/Maine/24-004330-004-original/2024
6345        A/mallard/Maine/24-004329-016-original/2024
6346        A/mallard/Maine/24-004329-015-original/2024
6347  A/green-winged teal/North Carolina/24-004327-0...
6370               A/dairy cow/Colorado/024240-001/2024

                 Isolate_old             Isolate_new  \
3527             FAV-0856-18             FAV-0856-18
3528              FAV-0870-4              FAV-0870-4
3529             FAV-0829-12             FAV-0829-12
3536              FAV-0669-4              FAV-0669-4
5236  23-038644-001-original  23-038644-001-original
...                      ...                     ...
6343  24-004330-004-original  24-004330-004-original
6345  24-004329-016-original  24-004329-016-original
6346  24-004329-015-original  24-004329-015-original
6347  24-004327-001-original  24-004327-001-original
6370              024240-001              024240-001

                                       Genotype_old  \
3527   B4.1 (<i style='font-size:11px'>GenoFLU</i>)
3528     A2 (<i style='font-size:11px'>GenoFLU</i>)
3529   B1.2 (<i style='font-size:11px'>GenoFLU</i>)
3536   B4.1 (<i style='font-size:11px'>GenoFLU</i>)
5236                                   Not assigned
...                                             ...
6343   C2.1 (<i style='font-size:11px'>GenoFLU</i>)
6345   C2.1 (<i style='font-size:11px'>GenoFLU</i>)
6346   C2.1 (<i style='font-size:11px'>GenoFLU</i>)
6347   C2.1 (<i style='font-size:11px'>GenoFLU</i>)
6370  B3.13 (<i style='font-size:11px'>GenoFLU</i>)

                                           Genotype_new
3527  Notassigned (<i style='font-size:11px'>GenoFLU...
3528  Notassigned (<i style='font-size:11px'>GenoFLU...
3529  Notassigned (<i style='font-size:11px'>GenoFLU...
3536  Notassigned (<i style='font-size:11px'>GenoFLU...
5236       B3.6 (<i style='font-size:11px'>GenoFLU</i>)
...                                                 ...
6343  Notassigned (<i style='font-size:11px'>GenoFLU...
6345  Notassigned (<i style='font-size:11px'>GenoFLU...
6346  Notassigned (<i style='font-size:11px'>GenoFLU...
6347  Notassigned (<i style='font-size:11px'>GenoFLU...
6370  Notassigned (<i style='font-size:11px'>GenoFLU...

[137 rows x 6 columns]
                                       Isolate_Name_old  \
3527             A/Great_Horned_Owl/BC/FAV-0856-18/2022
3528       A/Great_Black-Backed_Gull/QC/FAV-0870-4/2022
3529      A/Great_Black-Backed_Gull/QC/FAV-0829-12/2022
3536             A/Northwestern_Crow/BC/FAV-0669-4/2022
5359                       A/grackle/Texas/USL_047/2024
...                                                 ...
6343        A/mallard/Maine/24-004330-004-original/2024
6345        A/mallard/Maine/24-004329-016-original/2024
6346        A/mallard/Maine/24-004329-015-original/2024
6347  A/green-winged teal/North Carolina/24-004327-0...
6370               A/dairy cow/Colorado/024240-001/2024

                                       Isolate_Name_new  \
3527             A/Great_Horned_Owl/BC/FAV-0856-18/2022
3528       A/Great_Black-Backed_Gull/QC/FAV-0870-4/2022
3529      A/Great_Black-Backed_Gull/QC/FAV-0829-12/2022
3536             A/Northwestern_Crow/BC/FAV-0669-4/2022
5359                       A/grackle/Texas/USL_047/2024
...                                                 ...
6343        A/mallard/Maine/24-004330-004-original/2024
6345        A/mallard/Maine/24-004329-016-original/2024
6346        A/mallard/Maine/24-004329-015-original/2024
6347  A/green-winged teal/North Carolina/24-004327-0...
6370               A/dairy cow/Colorado/024240-001/2024

                 Isolate_old             Isolate_new  \
3527             FAV-0856-18             FAV-0856-18
3528              FAV-0870-4              FAV-0870-4
3529             FAV-0829-12             FAV-0829-12
3536              FAV-0669-4              FAV-0669-4
5359                 USL_047                 USL_047
...                      ...                     ...
6343  24-004330-004-original  24-004330-004-original
6345  24-004329-016-original  24-004329-016-original
6346  24-004329-015-original  24-004329-015-original
6347  24-004327-001-original  24-004327-001-original
6370              024240-001              024240-001

                                       Genotype_old  \
3527   B4.1 (<i style='font-size:11px'>GenoFLU</i>)
3528     A2 (<i style='font-size:11px'>GenoFLU</i>)
3529   B1.2 (<i style='font-size:11px'>GenoFLU</i>)
3536   B4.1 (<i style='font-size:11px'>GenoFLU</i>)
5359  B3.13 (<i style='font-size:11px'>GenoFLU</i>)
...                                             ...
6343   C2.1 (<i style='font-size:11px'>GenoFLU</i>)
6345   C2.1 (<i style='font-size:11px'>GenoFLU</i>)
6346   C2.1 (<i style='font-size:11px'>GenoFLU</i>)
6347   C2.1 (<i style='font-size:11px'>GenoFLU</i>)
6370  B3.13 (<i style='font-size:11px'>GenoFLU</i>)

                                           Genotype_new
3527  Notassigned (<i style='font-size:11px'>GenoFLU...
3528  Notassigned (<i style='font-size:11px'>GenoFLU...
3529  Notassigned (<i style='font-size:11px'>GenoFLU...
3536  Notassigned (<i style='font-size:11px'>GenoFLU...
5359  Notassigned (<i style='font-size:11px'>GenoFLU...
...                                                 ...
6343  Notassigned (<i style='font-size:11px'>GenoFLU...
6345  Notassigned (<i style='font-size:11px'>GenoFLU...
6346  Notassigned (<i style='font-size:11px'>GenoFLU...
6347  Notassigned (<i style='font-size:11px'>GenoFLU...
6370  Notassigned (<i style='font-size:11px'>GenoFLU...

[135 rows x 6 columns]

In [43]:
print(gisaid_time[gisaid_time["Update_Date_old"] != gisaid_time["Update_Date_new"]][["Isolate_Name_old", "Isolate_Name_new", "Update_Date_old", "Update_Date_new"]]) # All NaN

                                       Isolate_Name_old  \
202               A/black vulture/Georgia/W22-719C/2022
203              A/black vulture/Virginia/W22-662A/2022
204                A/black vulture/Georgia/W22-395/2022
205               A/black vulture/Georgia/W22-404B/2022
206               A/black vulture/Georgia/W22-675A/2022
...                                                 ...
6380  A/Glaucous-winged gull/Washington/W232270041-2...
6381  A/Glaucous-winged gull/Washington/W231990001-1...
6382       A/Harbor seal/Washington/W232510072-3-1/2023
6383         A/Harbor seal/Washington/W232490069-3/2023
6384       A/Harbor seal/Washington/W232430067-2-3/2023

                                       Isolate_Name_new Update_Date_old  \
202               A/black vulture/Georgia/W22-719C/2022             NaN
203              A/black vulture/Virginia/W22-662A/2022             NaN
204                A/black vulture/Georgia/W22-395/2022             NaN
205               A/black vulture/Georgia/W22-404B/2022             NaN
206               A/black vulture/Georgia/W22-675A/2022             NaN
...                                                 ...             ...
6380  A/Glaucous-winged gull/Washington/W232270041-2...             NaN
6381  A/Glaucous-winged gull/Washington/W231990001-1...             NaN
6382       A/Harbor seal/Washington/W232510072-3-1/2023             NaN
6383         A/Harbor seal/Washington/W232490069-3/2023             NaN
6384       A/Harbor seal/Washington/W232430067-2-3/2023             NaN

     Update_Date_new
202              NaN
203              NaN
204              NaN
205              NaN
206              NaN
...              ...
6380             NaN
6381             NaN
6382             NaN
6383             NaN
6384             NaN

[2550 rows x 4 columns]

In [44]:
print(gisaid_time[(gisaid_time["Update_Date_old"] != gisaid_time["Submission_Date_old"]) & (gisaid_time["Update_Date_old"] == gisaid_time["Update_Date_old"])][["Isolate_Name_old", "Isolate_Name_new", "Update_Date_old", "Submission_Date_old", "Collection_Date_old", "Collection_Date_new", "Location_old", "Location_new", "Genotype_old", "Genotype_new", "Host_old", "Host_new"]])

                                       Isolate_Name_old  \
7                       A/gull/Maine/22-022526-005/2022
9     A/great black-backed gull/Massachusetts/22-025...
12    A/great black-backed gull/Maine/22-022526-015/...
14    A/great black-backed gull/Maine/22-022526-007/...
16    A/great black-backed gull/Massachusetts/22-016...
...                                                 ...
5228                        A/cat/South Dakota/001/2024
5272                A/dairy cow/Ohio/24-010202-009/2024
5651               A/dairy cow/Idaho/24-011573-007/2024
5893     A/mallard/Missouri/23-034483-001-original/2023
6005               A/dairy cow/Texas/24_009308-004/2024

                                       Isolate_Name_new Update_Date_old  \
7                       A/gull/Maine/22-022526-005/2022      2023-01-27
9     A/great black-backed gull/Massachusetts/22-025...      2023-01-27
12    A/great black-backed gull/Maine/22-022526-015/...      2023-01-27
14    A/great black-backed gull/Maine/22-022526-007/...      2023-01-27
16    A/great black-backed gull/Massachusetts/22-016...      2023-01-25
...                                                 ...             ...
5228                        A/cat/South Dakota/001/2024      2024-06-18
5272                A/dairy cow/Ohio/24-010202-009/2024      2024-06-29
5651               A/dairy cow/Idaho/24-011573-007/2024      2024-07-15
5893     A/mallard/Missouri/23-034483-001-original/2023      2024-07-22
6005               A/dairy cow/Texas/24_009308-004/2024      2024-08-23

     Submission_Date_old Collection_Date_old Collection_Date_new  \
7             2023-01-24          2022-07-08          2022-07-08
9             2023-01-24          2022-07-23          2022-07-23
12            2023-01-24          2022-06-29          2022-06-29
14            2023-01-24          2022-06-29          2022-06-29
16            2023-01-24          2022-03-25          2022-03-25
...                  ...                 ...                 ...
5228          2024-06-14          2024-04-10          2024-04-10
5272          2024-06-28          2024-03-30          2024-03-30
5651          2024-07-05          2024-04-15          2024-04-15
5893          2024-07-19          2023-11-05          2023-11-05
6005          2024-07-30          2024-03-19          2024-03-19

                                           Location_old  \
7     North America / United States / Maine / Hancoo...
9         North America / United States / Massachusetts
12    North America / United States / Maine / Hancoo...
14    North America / United States / Maine / Hancoo...
16    North America / United States / Massachusetts ...
...                                                 ...
5228  North America / United States / South Dakota /...
5272               North America / United States / Ohio
5651              North America / United States / Idaho
5893           North America / United States / Missouri
6005              North America / United States / Texas

                                           Location_new  \
7     North America / United States / Maine / Hancoo...
9         North America / United States / Massachusetts
12    North America / United States / Maine / Hancoo...
14    North America / United States / Maine / Hancoo...
16    North America / United States / Massachusetts ...
...                                                 ...
5228  North America / United States / South Dakota /...
5272               North America / United States / Ohio
5651              North America / United States / Idaho
5893           North America / United States / Missouri
6005              North America / United States / Texas

                                       Genotype_old  \
7        A2 (<i style='font-size:11px'>GenoFLU</i>)
9      B1.2 (<i style='font-size:11px'>GenoFLU</i>)
12       A2 (<i style='font-size:11px'>GenoFLU</i>)
14       A2 (<i style='font-size:11px'>GenoFLU</i>)
16       A2 (<i style='font-size:11px'>GenoFLU</i>)
...                                             ...
5228  B3.13 (<i style='font-size:11px'>GenoFLU</i>)
5272  B3.13 (<i style='font-size:11px'>GenoFLU</i>)
5651  B3.13 (<i style='font-size:11px'>GenoFLU</i>)
5893   B3.6 (<i style='font-size:11px'>GenoFLU</i>)
6005  B3.13 (<i style='font-size:11px'>GenoFLU</i>)

                                           Genotype_new       Host_old  \
7            A2 (<i style='font-size:11px'>GenoFLU</i>)           Gull
9          B1.2 (<i style='font-size:11px'>GenoFLU</i>)  Larus marinus
12           A2 (<i style='font-size:11px'>GenoFLU</i>)  Larus marinus
14           A2 (<i style='font-size:11px'>GenoFLU</i>)  Larus marinus
16           A2 (<i style='font-size:11px'>GenoFLU</i>)  Larus marinus
...                                                 ...            ...
5228      B3.13 (<i style='font-size:11px'>GenoFLU</i>)    Felis catus
5272      B3.13 (<i style='font-size:11px'>GenoFLU</i>)      Dairy cow
5651      B3.13 (<i style='font-size:11px'>GenoFLU</i>)      Dairy cow
5893  Notassigned (<i style='font-size:11px'>GenoFLU...          Avian
6005      B3.13 (<i style='font-size:11px'>GenoFLU</i>)      Dairy cow

           Host_new
7              Gull
9     Larus marinus
12    Larus marinus
14    Larus marinus
16    Larus marinus
...             ...
5228    Felis catus
5272      Dairy cow
5651      Dairy cow
5893          Avian
6005      Dairy cow

[470 rows x 12 columns]