## Housekeeping

In [1]:
# Libraries

import os
import pandas as pd
import dateutil
import re
import shutil 
import numpy as np
import importlib
import utils  
importlib.reload(utils)
from utils import * # If changing utils, must restart this file for changes to take effect

In [2]:
# Directory paths

home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Downloads/" # MUST be downloads folder. Clean out downloads folder after each use. 
references = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/references/"

downloads_saved = home + "Other/Paloma/" 

complete_files = downloads_saved + "complete/" 
if not os.path.exists(complete_files): # checking if the directory exists or not
    os.makedirs(complete_files) # if the directory is not present then create it

os.chdir(references)
states_ref = pd.read_csv("states_ref.csv")

In [3]:
# Get metadata
os.chdir(downloads_saved)
metadata = pd.read_csv("sequences.csv")
print(len(metadata))

metadata

354

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,USA,Host,Tissue_Specimen_Source,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type
0,PQ585340.1,GenBank,GCA_052072035.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,Sus scrofa,lung,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2022-09-21,2025-08-13,ssRNA(-)
1,PQ585341.1,GenBank,GCA_052072035.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,Sus scrofa,lung,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2022-09-21,2025-08-13,ssRNA(-)
2,PQ585342.1,GenBank,GCA_052072035.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,Sus scrofa,lung,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2022-09-21,2025-08-13,ssRNA(-)
3,PQ585343.1,GenBank,GCA_052072035.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,Sus scrofa,lung,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2022-09-21,2025-08-13,ssRNA(-)
4,PQ585344.1,GenBank,GCA_052072035.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,Sus scrofa,lung,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2022-09-21,2025-08-13,ssRNA(-)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,PP331800.1,GenBank,GCA_039221065.1,NaN,NaN,PRJNA399763,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,Sus scrofa,lung,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2020-06-16,2024-02-18,ssRNA(-)
350,PP331801.1,GenBank,GCA_039221065.1,NaN,NaN,PRJNA399763,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,Sus scrofa,lung,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2020-06-16,2024-02-18,ssRNA(-)
351,PP331802.1,GenBank,GCA_039221065.1,NaN,NaN,PRJNA399763,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,Sus scrofa,lung,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2020-06-16,2024-02-18,ssRNA(-)
352,PP331803.1,GenBank,GCA_039221065.1,NaN,NaN,PRJNA399763,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,Sus scrofa,lung,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2020-06-16,2024-02-18,ssRNA(-)
353,PP331804.1,GenBank,GCA_039221065.1,NaN,NaN,PRJNA399763,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,Sus scrofa,lung,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2020-06-16,2024-02-18,ssRNA(-)

## Add sequences to dataframe

In [4]:
# NCBI Virus Naming Convention:
# "Accession|GenBank_Title|Assembly|SRA Accession|BioSample|BioProject|Genotype|Isolate|Geo Location|Host|Collection Date"

# Get sequences and headers together
# headers = []
# isolates = []
# sras = []
# headers_seqs = {}

os.chdir(downloads_saved)

sequences_fasta = df_from_fasta("sequences.fasta") # Turn fasta into a dataframe

sequences_fasta["Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split("|")[0].replace(">", ""))

# print(sequences_fasta["full_header"])

# Extract segment number so that we can add the correct sequences to the correct sample
# sequences_fasta["Segment"] = sequences_fasta["full_header"].apply(lambda x: int(re.search(r'segment (.?) ', x.split("|")[-2]).group(1)))

# Double-check the de-duplication
print((sequences_fasta)) 
# print(sequences_fasta.head())
print((metadata))

# Add sequences to the dataframe
metadata_segments = pd.concat([metadata, sequences_fasta], axis=1) # , "Segment"])

                                           full_header  \
0    >PQ585340.1 |Influenza A virus (A/swine/Spain/...
1    >PQ585341.1 |Influenza A virus (A/swine/Spain/...
2    >PQ585342.1 |Influenza A virus (A/swine/Spain/...
3    >PQ585343.1 |Influenza A virus (A/swine/Spain/...
4    >PQ585344.1 |Influenza A virus (A/swine/Spain/...
..                                                 ...
349  >PP331800.1 |Influenza A virus (A/swine/Spain/...
350  >PP331801.1 |Influenza A virus (A/swine/Spain/...
351  >PP331802.1 |Influenza A virus (A/swine/Spain/...
352  >PP331803.1 |Influenza A virus (A/swine/Spain/...
353  >PP331804.1 |Influenza A virus (A/swine/Spain/...

                                              sequence    Accession
0    AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...  PQ585340.1
1    AGCAAAAGCAGGCAAACTATTTGAATGGATGTCAACCCGACTCTAC...  PQ585341.1
2    AGCAAAAGCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAAT...  PQ585342.1
3    AGCAAAAGCAGGGGATGATTAAATCAACCAAGATGAAAACAAAACT...  PQ585343.1
4    AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCCTACCA...  PQ585344.1
..                                                 ...          ...
349  AGCAAAAGCAGGGGATAATTAAATAAACCAAGATGAAAGCAAAATT...  PP331800.1
350  AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...  PP331801.1
351  AGCAAAAGCAGGAGTGAAGATGAACCCAAATCAAAAGATAATAACA...  PP331802.1
352  AGCAAAAGCAGGTAGATATTTAAAGATGAGTCTTCTAACCGAGGTC...  PP331803.1
353  AGCAAAAGCAGGGTGACAAAAACATAATGGATTCAAACACTGTATC...  PP331804.1

[354 rows x 3 columns]
      Accession GenBank_RefSeq         Assembly  SRA_Accession  BioSample  \
0    PQ585340.1        GenBank  GCA_052072035.1            NaN        NaN
1    PQ585341.1        GenBank  GCA_052072035.1            NaN        NaN
2    PQ585342.1        GenBank  GCA_052072035.1            NaN        NaN
3    PQ585343.1        GenBank  GCA_052072035.1            NaN        NaN
4    PQ585344.1        GenBank  GCA_052072035.1            NaN        NaN
..          ...            ...              ...            ...        ...
349  PP331800.1        GenBank  GCA_039221065.1            NaN        NaN
350  PP331801.1        GenBank  GCA_039221065.1            NaN        NaN
351  PP331802.1        GenBank  GCA_039221065.1            NaN        NaN
352  PP331803.1        GenBank  GCA_039221065.1            NaN        NaN
353  PP331804.1        GenBank  GCA_039221065.1            NaN        NaN

      BioProject      Organism_Name                         Species  \
0            NaN  Influenza A virus  Alphainfluenzavirus influenzae
1            NaN  Influenza A virus  Alphainfluenzavirus influenzae
2            NaN  Influenza A virus  Alphainfluenzavirus influenzae
3            NaN  Influenza A virus  Alphainfluenzavirus influenzae
4            NaN  Influenza A virus  Alphainfluenzavirus influenzae
..           ...                ...                             ...
349  PRJNA399763  Influenza A virus  Alphainfluenzavirus influenzae
350  PRJNA399763  Influenza A virus  Alphainfluenzavirus influenzae
351  PRJNA399763  Influenza A virus  Alphainfluenzavirus influenzae
352  PRJNA399763  Influenza A virus  Alphainfluenzavirus influenzae
353  PRJNA399763  Influenza A virus  Alphainfluenzavirus influenzae

                   Genus            Family  ... USA        Host  \
0    Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
1    Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
2    Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
3    Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
4    Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
..                   ...               ...  ...  ..         ...
349  Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
350  Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
351  Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
352  Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
353  Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa

     Tissue_Specimen_Source                          Submitters  \
0                      lung  Encinas,P., Del Real Soldevilla,G.
1                      lung  Encinas,P., Del Real Soldevilla,G.
2                      lung  Encinas,P., Del Real Soldevilla,G.
3                      lung  Encinas,P., Del Real Soldevilla,G.
4                      lung  Encinas,P., Del Real Soldevilla,G.
..                      ...                                 ...
349                    lung  Encinas,P., Del Real Soldevilla,G.
350                    lung  Encinas,P., Del Real Soldevilla,G.
351                    lung  Encinas,P., Del Real Soldevilla,G.
352                    lung  Encinas,P., Del Real Soldevilla,G.
353                    lung  Encinas,P., Del Real Soldevilla,G.

            Organization Org_location Publications Collection_Date  \
0    INIA, Biotechnology        Spain          NaN      2022-09-21
1    INIA, Biotechnology        Spain          NaN      2022-09-21
2    INIA, Biotechnology        Spain          NaN      2022-09-21
3    INIA, Biotechnology        Spain          NaN      2022-09-21
4    INIA, Biotechnology        Spain          NaN      2022-09-21
..                   ...          ...          ...             ...
349  INIA, Biotechnology        Spain          NaN      2020-06-16
350  INIA, Biotechnology        Spain          NaN      2020-06-16
351  INIA, Biotechnology        Spain          NaN      2020-06-16
352  INIA, Biotechnology        Spain          NaN      2020-06-16
353  INIA, Biotechnology        Spain          NaN      2020-06-16

     Release_Date Molecule_type
0      2025-08-13      ssRNA(-)
1      2025-08-13      ssRNA(-)
2      2025-08-13      ssRNA(-)
3      2025-08-13      ssRNA(-)
4      2025-08-13      ssRNA(-)
..            ...           ...
349    2024-02-18      ssRNA(-)
350    2024-02-18      ssRNA(-)
351    2024-02-18      ssRNA(-)
352    2024-02-18      ssRNA(-)
353    2024-02-18      ssRNA(-)

[354 rows x 28 columns]

In [5]:
metadata_segments

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,full_header,sequence,Accession
0,PQ585340.1,GenBank,GCA_052072035.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2022-09-21,2025-08-13,ssRNA(-),>PQ585340.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...,PQ585340.1
1,PQ585341.1,GenBank,GCA_052072035.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2022-09-21,2025-08-13,ssRNA(-),>PQ585341.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGCAAACTATTTGAATGGATGTCAACCCGACTCTAC...,PQ585341.1
2,PQ585342.1,GenBank,GCA_052072035.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2022-09-21,2025-08-13,ssRNA(-),>PQ585342.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAAT...,PQ585342.1
3,PQ585343.1,GenBank,GCA_052072035.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2022-09-21,2025-08-13,ssRNA(-),>PQ585343.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGGATGATTAAATCAACCAAGATGAAAACAAAACT...,PQ585343.1
4,PQ585344.1,GenBank,GCA_052072035.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2022-09-21,2025-08-13,ssRNA(-),>PQ585344.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCCTACCA...,PQ585344.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,PP331800.1,GenBank,GCA_039221065.1,NaN,NaN,PRJNA399763,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2020-06-16,2024-02-18,ssRNA(-),>PP331800.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGGATAATTAAATAAACCAAGATGAAAGCAAAATT...,PP331800.1
350,PP331801.1,GenBank,GCA_039221065.1,NaN,NaN,PRJNA399763,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2020-06-16,2024-02-18,ssRNA(-),>PP331801.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...,PP331801.1
351,PP331802.1,GenBank,GCA_039221065.1,NaN,NaN,PRJNA399763,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2020-06-16,2024-02-18,ssRNA(-),>PP331802.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGAGTGAAGATGAACCCAAATCAAAAGATAATAACA...,PP331802.1
352,PP331803.1,GenBank,GCA_039221065.1,NaN,NaN,PRJNA399763,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2020-06-16,2024-02-18,ssRNA(-),>PP331803.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGTAGATATTTAAAGATGAGTCTTCTAACCGAGGTC...,PP331803.1
353,PP331804.1,GenBank,GCA_039221065.1,NaN,NaN,PRJNA399763,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Encinas,P., Del Real Soldevilla,G.","INIA, Biotechnology",Spain,NaN,2020-06-16,2024-02-18,ssRNA(-),>PP331804.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGTGACAAAAACATAATGGATTCAAACACTGTATC...,PP331804.1

In [6]:
# Cut down to only columns we want
metadata_genoflu = metadata_segments[["Accession", "GenBank_Title", "Host", "Collection_Date", "SRA_Accession", "Isolate", "Genotype", "Geo_Location", "full_header", "sequence", "Segment"]].iloc[:, 1:]

# # Get genbank strain name
metadata_genoflu["genbank_name"] = metadata_genoflu["GenBank_Title"].apply(lambda x: x.split("(")[1] )
# metadata_genoflu["Host"] = metadata_genoflu["genbank_name"].apply(lambda x: x.split("/")[1])

metadata_genoflu # [metadata_genoflu["Genotype"]  == "B3.13"]

,Accession,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype,Geo_Location,full_header,sequence,Segment,genbank_name
0,PQ585340.1,Influenza A virus (A/swine/Spain/36520-1/2022(...,Sus scrofa,2022-09-21,NaN,36520-1,H1N1,Spain,>PQ585340.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...,1,A/swine/Spain/36520-1/2022
1,PQ585341.1,Influenza A virus (A/swine/Spain/36520-1/2022(...,Sus scrofa,2022-09-21,NaN,36520-1,H1N1,Spain,>PQ585341.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGCAAACTATTTGAATGGATGTCAACCCGACTCTAC...,2,A/swine/Spain/36520-1/2022
2,PQ585342.1,Influenza A virus (A/swine/Spain/36520-1/2022(...,Sus scrofa,2022-09-21,NaN,36520-1,H1N1,Spain,>PQ585342.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAAT...,3,A/swine/Spain/36520-1/2022
3,PQ585343.1,Influenza A virus (A/swine/Spain/36520-1/2022(...,Sus scrofa,2022-09-21,NaN,36520-1,H1N1,Spain,>PQ585343.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGGATGATTAAATCAACCAAGATGAAAACAAAACT...,4,A/swine/Spain/36520-1/2022
4,PQ585344.1,Influenza A virus (A/swine/Spain/36520-1/2022(...,Sus scrofa,2022-09-21,NaN,36520-1,H1N1,Spain,>PQ585344.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCCTACCA...,5,A/swine/Spain/36520-1/2022
...,...,...,...,...,...,...,...,...,...,...,...,...
349,PP331800.1,Influenza A virus (A/swine/Spain/40217-1/2020(...,Sus scrofa,2020-06-16,NaN,40217-1,H1N2,Spain,>PP331800.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGGATAATTAAATAAACCAAGATGAAAGCAAAATT...,4,A/swine/Spain/40217-1/2020
350,PP331801.1,Influenza A virus (A/swine/Spain/40217-1/2020(...,Sus scrofa,2020-06-16,NaN,40217-1,H1N2,Spain,>PP331801.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...,5,A/swine/Spain/40217-1/2020
351,PP331802.1,Influenza A virus (A/swine/Spain/40217-1/2020(...,Sus scrofa,2020-06-16,NaN,40217-1,H1N2,Spain,>PP331802.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGAGTGAAGATGAACCCAAATCAAAAGATAATAACA...,6,A/swine/Spain/40217-1/2020
352,PP331803.1,Influenza A virus (A/swine/Spain/40217-1/2020(...,Sus scrofa,2020-06-16,NaN,40217-1,H1N2,Spain,>PP331803.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGTAGATATTTAAAGATGAGTCTTCTAACCGAGGTC...,7,A/swine/Spain/40217-1/2020
353,PP331804.1,Influenza A virus (A/swine/Spain/40217-1/2020(...,Sus scrofa,2020-06-16,NaN,40217-1,H1N2,Spain,>PP331804.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGTGACAAAAACATAATGGATTCAAACACTGTATC...,8,A/swine/Spain/40217-1/2020

## Relabeling Sequences

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

In [7]:

iberian_swine = ["06001-4", "6176-2", "6370-7", "6370-6", "6370-8", "6370-9", "6370-10", "6370-11", "06070-1"]

metadata_genoflu["genbank_name"] = metadata_genoflu["genbank_name"].apply(lambda x: x.replace("other_mammal", "Iberian_swine") if x.split("/")[3] in iberian_swine else x.replace("other_mammal", "swine") if "swine" in x else x)

metadata_genoflu["genbank_name"]

0      A/swine/Spain/36520-1/2022
1      A/swine/Spain/36520-1/2022
2      A/swine/Spain/36520-1/2022
3      A/swine/Spain/36520-1/2022
4      A/swine/Spain/36520-1/2022
                  ...
349    A/swine/Spain/40217-1/2020
350    A/swine/Spain/40217-1/2020
351    A/swine/Spain/40217-1/2020
352    A/swine/Spain/40217-1/2020
353    A/swine/Spain/40217-1/2020
Name: genbank_name, Length: 354, dtype: object

In [8]:
# Re-Labeling

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

# Fix animals
fix_animals_andersen(metadata_genoflu, animals_ref)

# Get the years
metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

# Get geographic locations
metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location"]


print(metadata_genoflu["Geo_Location_Abrv"])

0      Spain
1      Spain
2      Spain
3      Spain
4      Spain
       ...
349    Spain
350    Spain
351    Spain
352    Spain
353    Spain
Name: Geo_Location_Abrv, Length: 354, dtype: object

In [9]:
# If there is no SRA Accession, replace identifier with Assembly
metadata_genoflu['SRA_Accession'] = np.where(metadata_genoflu['SRA_Accession'] == "", metadata_genoflu['Accession'].apply(lambda x: x.split(".")[0]), metadata_genoflu['SRA_Accession'])

# Make new labels
names = ">" + metadata_genoflu["SRA_Accession"].apply(lambda x: x.split(",")[0]) + "|" + metadata_genoflu["genbank_name"] + "|" + metadata_genoflu["Genotype"] + "|" + metadata_genoflu["Geo_Location_Abrv"] + "|" + metadata_genoflu["Collection_Date"] + "|" + metadata_genoflu["Host_Type"] 

metadata_genoflu["Name"] = names
metadata_genoflu["Name"] = metadata_genoflu["Name"].apply(lambda x: x.replace("other_mammal", "Iberian_swine") if x.split("/")[3] in iberian_swine else x.replace("other_mammal", "swine") if "swine" in x else x)


print(metadata_genoflu)

       Accession                                      GenBank_Title  \
0    PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
1    PQ585341.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
2    PQ585342.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
3    PQ585343.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
4    PQ585344.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
..           ...                                                ...
349  PP331800.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
350  PP331801.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
351  PP331802.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
352  PP331803.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
353  PP331804.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

           Host Collection_Date SRA_Accession  Isolate Genotype Geo_Location  \
0    sus scrofa      2022-09-21      PQ585340  36520-1     H1N1        Spain
1    sus scrofa      2022-09-21      PQ585341  36520-1     H1N1        Spain
2    sus scrofa      2022-09-21      PQ585342  36520-1     H1N1        Spain
3    sus scrofa      2022-09-21      PQ585343  36520-1     H1N1        Spain
4    sus scrofa      2022-09-21      PQ585344  36520-1     H1N1        Spain
..          ...             ...           ...      ...      ...          ...
349  sus scrofa      2020-06-16      PP331800  40217-1     H1N2        Spain
350  sus scrofa      2020-06-16      PP331801  40217-1     H1N2        Spain
351  sus scrofa      2020-06-16      PP331802  40217-1     H1N2        Spain
352  sus scrofa      2020-06-16      PP331803  40217-1     H1N2        Spain
353  sus scrofa      2020-06-16      PP331804  40217-1     H1N2        Spain

                                           full_header  \
0    >PQ585340.1 |Influenza A virus (A/swine/Spain/...
1    >PQ585341.1 |Influenza A virus (A/swine/Spain/...
2    >PQ585342.1 |Influenza A virus (A/swine/Spain/...
3    >PQ585343.1 |Influenza A virus (A/swine/Spain/...
4    >PQ585344.1 |Influenza A virus (A/swine/Spain/...
..                                                 ...
349  >PP331800.1 |Influenza A virus (A/swine/Spain/...
350  >PP331801.1 |Influenza A virus (A/swine/Spain/...
351  >PP331802.1 |Influenza A virus (A/swine/Spain/...
352  >PP331803.1 |Influenza A virus (A/swine/Spain/...
353  >PP331804.1 |Influenza A virus (A/swine/Spain/...

                                              sequence  Segment  \
0    AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
1    AGCAAAAGCAGGCAAACTATTTGAATGGATGTCAACCCGACTCTAC...        2
2    AGCAAAAGCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAAT...        3
3    AGCAAAAGCAGGGGATGATTAAATCAACCAAGATGAAAACAAAACT...        4
4    AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCCTACCA...        5
..                                                 ...      ...
349  AGCAAAAGCAGGGGATAATTAAATAAACCAAGATGAAAGCAAAATT...        4
350  AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...        5
351  AGCAAAAGCAGGAGTGAAGATGAACCCAAATCAAAAGATAATAACA...        6
352  AGCAAAAGCAGGTAGATATTTAAAGATGAGTCTTCTAACCGAGGTC...        7
353  AGCAAAAGCAGGGTGACAAAAACATAATGGATTCAAACACTGTATC...        8

                   genbank_name     Host_Type Years Geo_Location_Abrv  \
0    A/swine/Spain/36520-1/2022  other_mammal  2022             Spain
1    A/swine/Spain/36520-1/2022  other_mammal  2022             Spain
2    A/swine/Spain/36520-1/2022  other_mammal  2022             Spain
3    A/swine/Spain/36520-1/2022  other_mammal  2022             Spain
4    A/swine/Spain/36520-1/2022  other_mammal  2022             Spain
..                          ...           ...   ...               ...
349  A/swine/Spain/40217-1/2020  other_mammal  2020             Spain
350  A/swine/Spain/40217-1/2020  other_mammal  2020             Spain
351  A/swine/Spain/40217-1/2020  other_mammal  2020             Spain
352  A/swine/Spain/40217-1/2020  other_mammal  2020             Spain
353  A/swine/Spain/40217-1/2020  other_mammal  2020             Spain

                                                  Name
0    >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...
1    >PQ585341|A/swine/Spain/36520-1/2022|H1N1|Spai...
2    >PQ585342|A/swine/Spain/36520-1/2022|H1N1|Spai...
3    >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...
4    >PQ585344|A/swine/Spain/36520-1/2022|H1N1|Spai...
..                                                 ...
349  >PP331800|A/swine/Spain/40217-1/2020|H1N2|Spai...
350  >PP331801|A/swine/Spain/40217-1/2020|H1N2|Spai...
351  >PP331802|A/swine/Spain/40217-1/2020|H1N2|Spai...
352  >PP331803|A/swine/Spain/40217-1/2020|H1N2|Spai...
353  >PP331804|A/swine/Spain/40217-1/2020|H1N2|Spai...

[354 rows x 16 columns]

## Rename segments and make complete FASTA files

In [10]:
# Set up segments
serotypes = ["H1", "H3", "N1", "N2"]
segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"} # Name segments 
metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].apply(lambda x: int(x)).map(segments)

# Separate into several dataframes based on genotype + segment
segment_genotype_dfs = []
for serotype in serotypes:
    # metadata_genoflu["Serotype"] = metadata_genoflu["Name"].apply(lambda x: x.split("|")[2])
    m_g_s = metadata_genoflu[metadata_genoflu["Genotype"].str.contains(serotype)]
    m_g_s["Serotype"] = serotype
    for segment in segments.values():
        m_g = m_g_s[m_g_s["Segment_Name"] == segment]
        print(m_g)
        segment_genotype_dfs.append(m_g)
    # for genotype in list(set(m_g["Genotype"].values)):
    #     if genotype in genotypes:
    #         df = m_g[(m_g["Genotype"] == genotype)] 
    #         # df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
    #         segment_genotype_dfs.append(df)
    #         pair = genotype + "_" + segment
    #         print(pair)

       Accession                                      GenBank_Title  \
0    PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
8    PQ107519.1   Influenza A virus (A/swine/Spain/6370-8/2019(H...
16   PQ107529.1   Influenza A virus (A/swine/Spain/6370-9/2019(H...
24   PQ107537.1   Influenza A virus (A/swine/Spain/6370-10/2019(...
32   PQ107546.1   Influenza A virus (A/swine/Spain/17483-1/2021(...
40   PQ107554.1   Influenza A virus (A/swine/Spain/6370-11/2019(...
48   PQ107577.1   Influenza A virus (A/swine/Spain/44394-1/2021(...
56   PQ107585.1   Influenza A virus (A/swine/Spain/05165-2/2022(...
64   PQ107595.1   Influenza A virus (A/swine/Spain/37500-1/2022(...
80   PQ107616.1   Influenza A virus (A/swine/Spain/12510-1/2022(...
88   PQ107624.1   Influenza A virus (A/swine/Spain/49610-1/2022(...
96   PQ107637.1   Influenza A virus (A/swine/Spain/2247-1/2022(H...
104  PQ107645.1   Influenza A virus (A/swine/Spain/31510-1/2022(...
112  PQ107658.1   Influenza A virus (A/swine/Spain/46892-1/2022(...
127  PQ107769.1   Influenza A virus (A/swine/Spain/45790-1/2022(...
134  PQ107776.1   Influenza A virus (A/swine/Spain/50700-1/2022(...
142  PQ111069.1   Influenza A virus (A/swine/Spain/17491-1/2022(...
150  PQ580717.1   Influenza A virus (A/swine/Spain/06800-1/2020(...
157  PQ585327.1   Influenza A virus (A/swine/Spain/5296-1/2022(H...
165  PQ585394.1   Influenza A virus (A/swine/Spain/22220-1/2020(...
173  PP338223.1   Influenza A virus (A/swine/Spain/28000-1/2021(...
181  PP338238.1   Influenza A virus (A/swine/Spain/06070-1/2020(...
189  PP338247.1   Influenza A virus (A/swine/Spain/17473-1/2021(...
197  PP338272.1   Influenza A virus (A/swine/Spain/22253-1/2020(...
205  PP338281.1   Influenza A virus (A/swine/Spain/41566-1/2021(...
221  PP338511.1   Influenza A virus (A/swine/Spain/22192-1/2021(...
236  PP338530.1   Influenza A virus (A/swine/Spain/30870-1/2021(...
244  PP338682.1   Influenza A virus (A/swine/Spain/12312-1/2021(...
252  PP338713.1   Influenza A virus (A/swine/Spain/22260-1/2021(...
268  PP338874.1   Influenza A virus (A/swine/Spain/22269-1/2020(...
275  PP335236.1   Influenza A virus (A/swine/Spain/22270-2/2020(...
283  PP335491.1   Influenza A virus (A/swine/Spain/25211-1/2020(...
291  PP335504.1   Influenza A virus (A/swine/Spain/05530-1/2020(...
299  PP330401.1   Influenza A virus (A/swine/Spain/31310-1/2020(...
307  PP330414.1   Influenza A virus (A/swine/Spain/22070-1/2020(...
314  PP330721.1   Influenza A virus (A/swine/Spain/50070-1/2020(...
322  PP330730.1   Influenza A virus (A/swine/Spain/32070-1/2020(...
330  PP330763.1   Influenza A virus (A/swine/Spain/22270-1/2020(...
338  PP331788.1   Influenza A virus (A/swine/Spain/05165-1/2020(...
346  PP331797.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

           Host Collection_Date SRA_Accession  Isolate Genotype Geo_Location  \
0    sus scrofa      2022-09-21      PQ585340  36520-1     H1N1        Spain
8    sus scrofa      2019-05-17      PQ107519   6370-8     H1N2        Spain
16   sus scrofa      2019-05-17      PQ107529   6370-9     H1N2        Spain
24   sus scrofa      2019-05-17      PQ107537  6370-10     H1N2        Spain
32   sus scrofa      2021-10-20      PQ107546  17483-1     H1N2        Spain
40   sus scrofa      2019-05-17      PQ107554  6370-11     H1N2        Spain
48   sus scrofa      2021-12-29      PQ107577  44394-1     H1N1        Spain
56   sus scrofa      2022-03-03      PQ107585  05165-2     H1N2        Spain
64   sus scrofa      2022-04-27      PQ107595  37500-1     H1N2        Spain
80   sus scrofa      2022-05-17      PQ107616  12510-1     H1N1        Spain
88   sus scrofa      2022-05-25      PQ107624  49610-1     H1N2        Spain
96   sus scrofa      2022-07-06      PQ107637   2247-1     H1N1        Spain
104  sus scrofa      2022-07-29      PQ107645  31510-1     H1N1        Spain
112  sus scrofa      2022-08-30      PQ107658  46892-1     H1N1        Spain
127  sus scrofa      2022-09-15      PQ107769  45790-1     H1N2        Spain
134  sus scrofa      2022-10-04      PQ107776  50700-1     H1N1        Spain
142  sus scrofa      2022-08-24      PQ111069  17491-1     H1N1        Spain
150  sus scrofa      2020-10-07      PQ580717  06800-1       H1        Spain
157  sus scrofa      2022-10-27      PQ585327   5296-1     H1N2        Spain
165  sus scrofa      2020-10-29      PQ585394  22220-1     H1N2        Spain
173  sus scrofa      2021-04-20      PP338223  28000-1     H1N1        Spain
181  sus scrofa      2020-12-15      PP338238  06070-1     H1N2        Spain
189  sus scrofa      2021-01-13      PP338247  17473-1     H1N2        Spain
197  sus scrofa      2020-09-23      PP338272  22253-1     H1N1        Spain
205  sus scrofa      2021-02-03      PP338281  41566-1     H1N2        Spain
221  sus scrofa      2021-01-19      PP338511  22192-1     H1N1        Spain
236  sus scrofa      2021-05-18      PP338530  30870-1     H1N2        Spain
244  sus scrofa      2021-07-06      PP338682  12312-1     H1N1        Spain
252  sus scrofa      2021-02-17      PP338713  22260-1     H1N2        Spain
268  sus scrofa      2020-05-18      PP338874  22269-1     H1N1        Spain
275  sus scrofa      2020-07-13      PP335236  22270-2     H1N2        Spain
283  sus scrofa      2020-07-31      PP335491  25211-1     H1N1        Spain
291  sus scrofa      2020-09-23      PP335504  05530-1     H1N2        Spain
299  sus scrofa      2020-05-19      PP330401  31310-1     H1N2        Spain
307  sus scrofa      2020-05-21      PP330414  22070-1     H1N2        Spain
314  sus scrofa      2020-05-22      PP330721  50070-1     H1N1        Spain
322  sus scrofa      2020-05-26      PP330730  32070-1     H1N1        Spain
330  sus scrofa      2020-06-15      PP330763  22270-1     H1N2        Spain
338  sus scrofa      2020-06-19      PP331788  05165-1     H1N1        Spain
346  sus scrofa      2020-06-16      PP331797  40217-1     H1N2        Spain

                                           full_header  \
0    >PQ585340.1 |Influenza A virus (A/swine/Spain/...
8    >PQ107519.1 |Influenza A virus (A/swine/Spain/...
16   >PQ107529.1 |Influenza A virus (A/swine/Spain/...
24   >PQ107537.1 |Influenza A virus (A/swine/Spain/...
32   >PQ107546.1 |Influenza A virus (A/swine/Spain/...
40   >PQ107554.1 |Influenza A virus (A/swine/Spain/...
48   >PQ107577.1 |Influenza A virus (A/swine/Spain/...
56   >PQ107585.1 |Influenza A virus (A/swine/Spain/...
64   >PQ107595.1 |Influenza A virus (A/swine/Spain/...
80   >PQ107616.1 |Influenza A virus (A/swine/Spain/...
88   >PQ107624.1 |Influenza A virus (A/swine/Spain/...
96   >PQ107637.1 |Influenza A virus (A/swine/Spain/...
104  >PQ107645.1 |Influenza A virus (A/swine/Spain/...
112  >PQ107658.1 |Influenza A virus (A/swine/Spain/...
127  >PQ107769.1 |Influenza A virus (A/swine/Spain/...
134  >PQ107776.1 |Influenza A virus (A/swine/Spain/...
142  >PQ111069.1 |Influenza A virus (A/swine/Spain/...
150  >PQ580717.1 |Influenza A virus (A/swine/Spain/...
157  >PQ585327.1 |Influenza A virus (A/swine/Spain/...
165  >PQ585394.1 |Influenza A virus (A/swine/Spain/...
173  >PP338223.1 |Influenza A virus (A/swine/Spain/...
181  >PP338238.1 |Influenza A virus (A/swine/Spain/...
189  >PP338247.1 |Influenza A virus (A/swine/Spain/...
197  >PP338272.1 |Influenza A virus (A/swine/Spain/...
205  >PP338281.1 |Influenza A virus (A/swine/Spain/...
221  >PP338511.1 |Influenza A virus (A/swine/Spain/...
236  >PP338530.1 |Influenza A virus (A/swine/Spain/...
244  >PP338682.1 |Influenza A virus (A/swine/Spain/...
252  >PP338713.1 |Influenza A virus (A/swine/Spain/...
268  >PP338874.1 |Influenza A virus (A/swine/Spain/...
275  >PP335236.1 |Influenza A virus (A/swine/Spain/...
283  >PP335491.1 |Influenza A virus (A/swine/Spain/...
291  >PP335504.1 |Influenza A virus (A/swine/Spain/...
299  >PP330401.1 |Influenza A virus (A/swine/Spain/...
307  >PP330414.1 |Influenza A virus (A/swine/Spain/...
314  >PP330721.1 |Influenza A virus (A/swine/Spain/...
322  >PP330730.1 |Influenza A virus (A/swine/Spain/...
330  >PP330763.1 |Influenza A virus (A/swine/Spain/...
338  >PP331788.1 |Influenza A virus (A/swine/Spain/...
346  >PP331797.1 |Influenza A virus (A/swine/Spain/...

                                              sequence  Segment  \
0    AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
8    AGCAAAAGCAGGTCAAATATATTCAACATGGAGAGAATAAAAGAAC...        1
16   AGCAAAAGCAGGTCAAATATATTCAACATGGAGAGAATAAAAGAAC...        1
24   AGCAAAAGCAGGTCAAATATATTCAACATGGAGAGAATAAAAGAAC...        1
32   AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
40   AGCAAAAGCAGGTCAAATATATTCAACATGGAGAGAATAAAAGAAC...        1
48   AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
56   AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
64   AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAT...        1
80   AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
88   AGCAAAAGCAGGTCAAATATATTCAATATGGAAAGAATAAAAGAAT...        1
96   AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
104  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
112  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
127  AGCAAAAGCAGGTCAAATATATACAATATGGAAAGAATAAAAGAAT...        1
134  AGCAAAAGCAGGTCAAATATATTCAATATGGAAAGAATTAAAGAAT...        1
142  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
150  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
157  AGCAAAAGCAGGTCAAATATATTCAATATGGAAAGAATAAAAGAAC...        1
165  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAT...        1
173  AGCAAAAGCAGGTCAAATATATTCAATATGGAAAGAATAAAAGAAC...        1
181  AGCAAAAGCAGGTCAAATATATTCAATATGGAAAGAATAAAAGAAT...        1
189  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
197  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
205  AGCAAAAGCAGGTCAAATATATTCAATATGGAACGAATAAAAGAAT...        1
221  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAT...        1
236  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAT...        1
244  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
252  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
268  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
275  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
283  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
291  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAT...        1
299  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
307  AGCAAAAGCAGGTCAAATATATCCAGTATGGAGAGAATAAAAGAAT...        1
314  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
322  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
330  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
338  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAGC...        1
346  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAT...        1

                   genbank_name     Host_Type Years Geo_Location_Abrv  \
0    A/swine/Spain/36520-1/2022  other_mammal  2022             Spain
8     A/swine/Spain/6370-8/2019  other_mammal  2019             Spain
16    A/swine/Spain/6370-9/2019  other_mammal  2019             Spain
24   A/swine/Spain/6370-10/2019  other_mammal  2019             Spain
32   A/swine/Spain/17483-1/2021  other_mammal  2021             Spain
40   A/swine/Spain/6370-11/2019  other_mammal  2019             Spain
48   A/swine/Spain/44394-1/2021  other_mammal  2021             Spain
56   A/swine/Spain/05165-2/2022  other_mammal  2022             Spain
64   A/swine/Spain/37500-1/2022  other_mammal  2022             Spain
80   A/swine/Spain/12510-1/2022  other_mammal  2022             Spain
88   A/swine/Spain/49610-1/2022  other_mammal  2022             Spain
96    A/swine/Spain/2247-1/2022  other_mammal  2022             Spain
104  A/swine/Spain/31510-1/2022  other_mammal  2022             Spain
112  A/swine/Spain/46892-1/2022  other_mammal  2022             Spain
127  A/swine/Spain/45790-1/2022  other_mammal  2022             Spain
134  A/swine/Spain/50700-1/2022  other_mammal  2022             Spain
142  A/swine/Spain/17491-1/2022  other_mammal  2022             Spain
150  A/swine/Spain/06800-1/2020  other_mammal  2020             Spain
157   A/swine/Spain/5296-1/2022  other_mammal  2022             Spain
165  A/swine/Spain/22220-1/2020  other_mammal  2020             Spain
173  A/swine/Spain/28000-1/2021  other_mammal  2021             Spain
181  A/swine/Spain/06070-1/2020  other_mammal  2020             Spain
189  A/swine/Spain/17473-1/2021  other_mammal  2021             Spain
197  A/swine/Spain/22253-1/2020  other_mammal  2020             Spain
205  A/swine/Spain/41566-1/2021  other_mammal  2021             Spain
221  A/swine/Spain/22192-1/2021  other_mammal  2021             Spain
236  A/swine/Spain/30870-1/2021  other_mammal  2021             Spain
244  A/swine/Spain/12312-1/2021  other_mammal  2021             Spain
252  A/swine/Spain/22260-1/2021  other_mammal  2021             Spain
268  A/swine/Spain/22269-1/2020  other_mammal  2020             Spain
275  A/swine/Spain/22270-2/2020  other_mammal  2020             Spain
283  A/swine/Spain/25211-1/2020  other_mammal  2020             Spain
291  A/swine/Spain/05530-1/2020  other_mammal  2020             Spain
299  A/swine/Spain/31310-1/2020  other_mammal  2020             Spain
307  A/swine/Spain/22070-1/2020  other_mammal  2020             Spain
314  A/swine/Spain/50070-1/2020  other_mammal  2020             Spain
322  A/swine/Spain/32070-1/2020  other_mammal  2020             Spain
330  A/swine/Spain/22270-1/2020  other_mammal  2020             Spain
338  A/swine/Spain/05165-1/2020  other_mammal  2020             Spain
346  A/swine/Spain/40217-1/2020  other_mammal  2020             Spain

                                                  Name Segment_Name Serotype
0    >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB2       H1
8    >PQ107519|A/swine/Spain/6370-8/2019|H1N2|Spain...          PB2       H1
16   >PQ107529|A/swine/Spain/6370-9/2019|H1N2|Spain...          PB2       H1
24   >PQ107537|A/swine/Spain/6370-10/2019|H1N2|Spai...          PB2       H1
32   >PQ107546|A/swine/Spain/17483-1/2021|H1N2|Spai...          PB2       H1
40   >PQ107554|A/swine/Spain/6370-11/2019|H1N2|Spai...          PB2       H1
48   >PQ107577|A/swine/Spain/44394-1/2021|H1N1|Spai...          PB2       H1
56   >PQ107585|A/swine/Spain/05165-2/2022|H1N2|Spai...          PB2       H1
64   >PQ107595|A/swine/Spain/37500-1/2022|H1N2|Spai...          PB2       H1
80   >PQ107616|A/swine/Spain/12510-1/2022|H1N1|Spai...          PB2       H1
88   >PQ107624|A/swine/Spain/49610-1/2022|H1N2|Spai...          PB2       H1
96   >PQ107637|A/swine/Spain/2247-1/2022|H1N1|Spain...          PB2       H1
104  >PQ107645|A/swine/Spain/31510-1/2022|H1N1|Spai...          PB2       H1
112  >PQ107658|A/swine/Spain/46892-1/2022|H1N1|Spai...          PB2       H1
127  >PQ107769|A/swine/Spain/45790-1/2022|H1N2|Spai...          PB2       H1
134  >PQ107776|A/swine/Spain/50700-1/2022|H1N1|Spai...          PB2       H1
142  >PQ111069|A/swine/Spain/17491-1/2022|H1N1|Spai...          PB2       H1
150  >PQ580717|A/swine/Spain/06800-1/2020|H1|Spain|...          PB2       H1
157  >PQ585327|A/swine/Spain/5296-1/2022|H1N2|Spain...          PB2       H1
165  >PQ585394|A/swine/Spain/22220-1/2020|H1N2|Spai...          PB2       H1
173  >PP338223|A/swine/Spain/28000-1/2021|H1N1|Spai...          PB2       H1
181  >PP338238|A/swine/Spain/06070-1/2020|H1N2|Spai...          PB2       H1
189  >PP338247|A/swine/Spain/17473-1/2021|H1N2|Spai...          PB2       H1
197  >PP338272|A/swine/Spain/22253-1/2020|H1N1|Spai...          PB2       H1
205  >PP338281|A/swine/Spain/41566-1/2021|H1N2|Spai...          PB2       H1
221  >PP338511|A/swine/Spain/22192-1/2021|H1N1|Spai...          PB2       H1
236  >PP338530|A/swine/Spain/30870-1/2021|H1N2|Spai...          PB2       H1
244  >PP338682|A/swine/Spain/12312-1/2021|H1N1|Spai...          PB2       H1
252  >PP338713|A/swine/Spain/22260-1/2021|H1N2|Spai...          PB2       H1
268  >PP338874|A/swine/Spain/22269-1/2020|H1N1|Spai...          PB2       H1
275  >PP335236|A/swine/Spain/22270-2/2020|H1N2|Spai...          PB2       H1
283  >PP335491|A/swine/Spain/25211-1/2020|H1N1|Spai...          PB2       H1
291  >PP335504|A/swine/Spain/05530-1/2020|H1N2|Spai...          PB2       H1
299  >PP330401|A/swine/Spain/31310-1/2020|H1N2|Spai...          PB2       H1
307  >PP330414|A/swine/Spain/22070-1/2020|H1N2|Spai...          PB2       H1
314  >PP330721|A/swine/Spain/50070-1/2020|H1N1|Spai...          PB2       H1
322  >PP330730|A/swine/Spain/32070-1/2020|H1N1|Spai...          PB2       H1
330  >PP330763|A/swine/Spain/22270-1/2020|H1N2|Spai...          PB2       H1
338  >PP331788|A/swine/Spain/05165-1/2020|H1N1|Spai...          PB2       H1
346  >PP331797|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB2       H1
       Accession                                      GenBank_Title  \
1    PQ585341.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
9    PQ107520.1   Influenza A virus (A/swine/Spain/6370-8/2019(H...
17   PQ107530.1   Influenza A virus (A/swine/Spain/6370-9/2019(H...
25   PQ107538.1   Influenza A virus (A/swine/Spain/6370-10/2019(...
33   PQ107547.1   Influenza A virus (A/swine/Spain/17483-1/2021(...
41   PQ107555.1   Influenza A virus (A/swine/Spain/6370-11/2019(...
49   PQ107578.1   Influenza A virus (A/swine/Spain/44394-1/2021(...
57   PQ107586.1   Influenza A virus (A/swine/Spain/05165-2/2022(...
65   PQ107596.1   Influenza A virus (A/swine/Spain/37500-1/2022(...
81   PQ107617.1   Influenza A virus (A/swine/Spain/12510-1/2022(...
89   PQ107625.1   Influenza A virus (A/swine/Spain/49610-1/2022(...
97   PQ107638.1   Influenza A virus (A/swine/Spain/2247-1/2022(H...
105  PQ107646.1   Influenza A virus (A/swine/Spain/31510-1/2022(...
113  PQ107659.1   Influenza A virus (A/swine/Spain/46892-1/2022(...
135  PQ107777.1   Influenza A virus (A/swine/Spain/50700-1/2022(...
143  PQ111070.1   Influenza A virus (A/swine/Spain/17491-1/2022(...
151  PQ580718.1   Influenza A virus (A/swine/Spain/06800-1/2020(...
158  PQ585328.1   Influenza A virus (A/swine/Spain/5296-1/2022(H...
166  PQ585395.1   Influenza A virus (A/swine/Spain/22220-1/2020(...
174  PP338224.1   Influenza A virus (A/swine/Spain/28000-1/2021(...
182  PP338239.1   Influenza A virus (A/swine/Spain/06070-1/2020(...
190  PP338248.1   Influenza A virus (A/swine/Spain/17473-1/2021(...
198  PP338273.1   Influenza A virus (A/swine/Spain/22253-1/2020(...
206  PP338282.1   Influenza A virus (A/swine/Spain/41566-1/2021(...
222  PP338512.1   Influenza A virus (A/swine/Spain/22192-1/2021(...
229  PP338519.1   Influenza A virus (A/swine/Spain/44593-1/2021(...
237  PP338531.1   Influenza A virus (A/swine/Spain/30870-1/2021(...
245  PP338683.1   Influenza A virus (A/swine/Spain/12312-1/2021(...
253  PP338714.1   Influenza A virus (A/swine/Spain/22260-1/2021(...
269  PP338875.1   Influenza A virus (A/swine/Spain/22269-1/2020(...
276  PP335237.1   Influenza A virus (A/swine/Spain/22270-2/2020(...
284  PP335492.1   Influenza A virus (A/swine/Spain/25211-1/2020(...
292  PP335505.1   Influenza A virus (A/swine/Spain/05530-1/2020(...
300  PP330402.1   Influenza A virus (A/swine/Spain/31310-1/2020(...
308  PP330415.1   Influenza A virus (A/swine/Spain/22070-1/2020(...
315  PP330722.1   Influenza A virus (A/swine/Spain/50070-1/2020(...
323  PP330731.1   Influenza A virus (A/swine/Spain/32070-1/2020(...
331  PP330764.1   Influenza A virus (A/swine/Spain/22270-1/2020(...
339  PP331789.1   Influenza A virus (A/swine/Spain/05165-1/2020(...
347  PP331798.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

           Host Collection_Date SRA_Accession  Isolate Genotype Geo_Location  \
1    sus scrofa      2022-09-21      PQ585341  36520-1     H1N1        Spain
9    sus scrofa      2019-05-17      PQ107520   6370-8     H1N2        Spain
17   sus scrofa      2019-05-17      PQ107530   6370-9     H1N2        Spain

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\2916910232.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\2916910232.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\2916910232.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\2916910232.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype

In [11]:
# Create FASTA files

os.chdir(complete_files)

for df in segment_genotype_dfs:
    # print(df)
    for serotype in serotypes:
        if df["Serotype"].values[0] == serotype:
            print(df)
            df.to_csv("GenBank_" + df["Segment_Name"].values[0] + "_" + serotype + "_metadata_Paloma.csv")
            df = df.reset_index()
            if len(df) > 0: # If there are entries
                file_name = "GenBank_" + df["Segment_Name"].values[0] + "_" + serotype + "_Paloma.fasta"
                output_file = open(complete_files + file_name, "w")

                for index, row in df.iterrows():
                    name = df.loc[index, "Name"]
                    name = name.replace(" ", "_")
                    # names.append(name)
                    sequence = df.loc[index, "sequence"]
                    # First is header, second is sequence
                    output_file.write(name + "\n")
                    output_file.write(sequence + "\n")
                
            output_file.close()

       Accession                                      GenBank_Title  \
0    PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
8    PQ107519.1   Influenza A virus (A/swine/Spain/6370-8/2019(H...
16   PQ107529.1   Influenza A virus (A/swine/Spain/6370-9/2019(H...
24   PQ107537.1   Influenza A virus (A/swine/Spain/6370-10/2019(...
32   PQ107546.1   Influenza A virus (A/swine/Spain/17483-1/2021(...
40   PQ107554.1   Influenza A virus (A/swine/Spain/6370-11/2019(...
48   PQ107577.1   Influenza A virus (A/swine/Spain/44394-1/2021(...
56   PQ107585.1   Influenza A virus (A/swine/Spain/05165-2/2022(...
64   PQ107595.1   Influenza A virus (A/swine/Spain/37500-1/2022(...
80   PQ107616.1   Influenza A virus (A/swine/Spain/12510-1/2022(...
88   PQ107624.1   Influenza A virus (A/swine/Spain/49610-1/2022(...
96   PQ107637.1   Influenza A virus (A/swine/Spain/2247-1/2022(H...
104  PQ107645.1   Influenza A virus (A/swine/Spain/31510-1/2022(...
112  PQ107658.1   Influenza A virus (A/swine/Spain/46892-1/2022(...
127  PQ107769.1   Influenza A virus (A/swine/Spain/45790-1/2022(...
134  PQ107776.1   Influenza A virus (A/swine/Spain/50700-1/2022(...
142  PQ111069.1   Influenza A virus (A/swine/Spain/17491-1/2022(...
150  PQ580717.1   Influenza A virus (A/swine/Spain/06800-1/2020(...
157  PQ585327.1   Influenza A virus (A/swine/Spain/5296-1/2022(H...
165  PQ585394.1   Influenza A virus (A/swine/Spain/22220-1/2020(...
173  PP338223.1   Influenza A virus (A/swine/Spain/28000-1/2021(...
181  PP338238.1   Influenza A virus (A/swine/Spain/06070-1/2020(...
189  PP338247.1   Influenza A virus (A/swine/Spain/17473-1/2021(...
197  PP338272.1   Influenza A virus (A/swine/Spain/22253-1/2020(...
205  PP338281.1   Influenza A virus (A/swine/Spain/41566-1/2021(...
221  PP338511.1   Influenza A virus (A/swine/Spain/22192-1/2021(...
236  PP338530.1   Influenza A virus (A/swine/Spain/30870-1/2021(...
244  PP338682.1   Influenza A virus (A/swine/Spain/12312-1/2021(...
252  PP338713.1   Influenza A virus (A/swine/Spain/22260-1/2021(...
268  PP338874.1   Influenza A virus (A/swine/Spain/22269-1/2020(...
275  PP335236.1   Influenza A virus (A/swine/Spain/22270-2/2020(...
283  PP335491.1   Influenza A virus (A/swine/Spain/25211-1/2020(...
291  PP335504.1   Influenza A virus (A/swine/Spain/05530-1/2020(...
299  PP330401.1   Influenza A virus (A/swine/Spain/31310-1/2020(...
307  PP330414.1   Influenza A virus (A/swine/Spain/22070-1/2020(...
314  PP330721.1   Influenza A virus (A/swine/Spain/50070-1/2020(...
322  PP330730.1   Influenza A virus (A/swine/Spain/32070-1/2020(...
330  PP330763.1   Influenza A virus (A/swine/Spain/22270-1/2020(...
338  PP331788.1   Influenza A virus (A/swine/Spain/05165-1/2020(...
346  PP331797.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

           Host Collection_Date SRA_Accession  Isolate Genotype Geo_Location  \
0    sus scrofa      2022-09-21      PQ585340  36520-1     H1N1        Spain
8    sus scrofa      2019-05-17      PQ107519   6370-8     H1N2        Spain
16   sus scrofa      2019-05-17      PQ107529   6370-9     H1N2        Spain
24   sus scrofa      2019-05-17      PQ107537  6370-10     H1N2        Spain
32   sus scrofa      2021-10-20      PQ107546  17483-1     H1N2        Spain
40   sus scrofa      2019-05-17      PQ107554  6370-11     H1N2        Spain
48   sus scrofa      2021-12-29      PQ107577  44394-1     H1N1        Spain
56   sus scrofa      2022-03-03      PQ107585  05165-2     H1N2        Spain
64   sus scrofa      2022-04-27      PQ107595  37500-1     H1N2        Spain
80   sus scrofa      2022-05-17      PQ107616  12510-1     H1N1        Spain
88   sus scrofa      2022-05-25      PQ107624  49610-1     H1N2        Spain
96   sus scrofa      2022-07-06      PQ107637   2247-1     H1N1        Spain
104  sus scrofa      2022-07-29      PQ107645  31510-1     H1N1        Spain
112  sus scrofa      2022-08-30      PQ107658  46892-1     H1N1        Spain
127  sus scrofa      2022-09-15      PQ107769  45790-1     H1N2        Spain
134  sus scrofa      2022-10-04      PQ107776  50700-1     H1N1        Spain
142  sus scrofa      2022-08-24      PQ111069  17491-1     H1N1        Spain
150  sus scrofa      2020-10-07      PQ580717  06800-1       H1        Spain
157  sus scrofa      2022-10-27      PQ585327   5296-1     H1N2        Spain
165  sus scrofa      2020-10-29      PQ585394  22220-1     H1N2        Spain
173  sus scrofa      2021-04-20      PP338223  28000-1     H1N1        Spain
181  sus scrofa      2020-12-15      PP338238  06070-1     H1N2        Spain
189  sus scrofa      2021-01-13      PP338247  17473-1     H1N2        Spain
197  sus scrofa      2020-09-23      PP338272  22253-1     H1N1        Spain
205  sus scrofa      2021-02-03      PP338281  41566-1     H1N2        Spain
221  sus scrofa      2021-01-19      PP338511  22192-1     H1N1        Spain
236  sus scrofa      2021-05-18      PP338530  30870-1     H1N2        Spain
244  sus scrofa      2021-07-06      PP338682  12312-1     H1N1        Spain
252  sus scrofa      2021-02-17      PP338713  22260-1     H1N2        Spain
268  sus scrofa      2020-05-18      PP338874  22269-1     H1N1        Spain
275  sus scrofa      2020-07-13      PP335236  22270-2     H1N2        Spain
283  sus scrofa      2020-07-31      PP335491  25211-1     H1N1        Spain
291  sus scrofa      2020-09-23      PP335504  05530-1     H1N2        Spain
299  sus scrofa      2020-05-19      PP330401  31310-1     H1N2        Spain
307  sus scrofa      2020-05-21      PP330414  22070-1     H1N2        Spain
314  sus scrofa      2020-05-22      PP330721  50070-1     H1N1        Spain
322  sus scrofa      2020-05-26      PP330730  32070-1     H1N1        Spain
330  sus scrofa      2020-06-15      PP330763  22270-1     H1N2        Spain
338  sus scrofa      2020-06-19      PP331788  05165-1     H1N1        Spain
346  sus scrofa      2020-06-16      PP331797  40217-1     H1N2        Spain

                                           full_header  \
0    >PQ585340.1 |Influenza A virus (A/swine/Spain/...
8    >PQ107519.1 |Influenza A virus (A/swine/Spain/...
16   >PQ107529.1 |Influenza A virus (A/swine/Spain/...
24   >PQ107537.1 |Influenza A virus (A/swine/Spain/...
32   >PQ107546.1 |Influenza A virus (A/swine/Spain/...
40   >PQ107554.1 |Influenza A virus (A/swine/Spain/...
48   >PQ107577.1 |Influenza A virus (A/swine/Spain/...
56   >PQ107585.1 |Influenza A virus (A/swine/Spain/...
64   >PQ107595.1 |Influenza A virus (A/swine/Spain/...
80   >PQ107616.1 |Influenza A virus (A/swine/Spain/...
88   >PQ107624.1 |Influenza A virus (A/swine/Spain/...
96   >PQ107637.1 |Influenza A virus (A/swine/Spain/...
104  >PQ107645.1 |Influenza A virus (A/swine/Spain/...
112  >PQ107658.1 |Influenza A virus (A/swine/Spain/...
127  >PQ107769.1 |Influenza A virus (A/swine/Spain/...
134  >PQ107776.1 |Influenza A virus (A/swine/Spain/...
142  >PQ111069.1 |Influenza A virus (A/swine/Spain/...
150  >PQ580717.1 |Influenza A virus (A/swine/Spain/...
157  >PQ585327.1 |Influenza A virus (A/swine/Spain/...
165  >PQ585394.1 |Influenza A virus (A/swine/Spain/...
173  >PP338223.1 |Influenza A virus (A/swine/Spain/...
181  >PP338238.1 |Influenza A virus (A/swine/Spain/...
189  >PP338247.1 |Influenza A virus (A/swine/Spain/...
197  >PP338272.1 |Influenza A virus (A/swine/Spain/...
205  >PP338281.1 |Influenza A virus (A/swine/Spain/...
221  >PP338511.1 |Influenza A virus (A/swine/Spain/...
236  >PP338530.1 |Influenza A virus (A/swine/Spain/...
244  >PP338682.1 |Influenza A virus (A/swine/Spain/...
252  >PP338713.1 |Influenza A virus (A/swine/Spain/...
268  >PP338874.1 |Influenza A virus (A/swine/Spain/...
275  >PP335236.1 |Influenza A virus (A/swine/Spain/...
283  >PP335491.1 |Influenza A virus (A/swine/Spain/...
291  >PP335504.1 |Influenza A virus (A/swine/Spain/...
299  >PP330401.1 |Influenza A virus (A/swine/Spain/...
307  >PP330414.1 |Influenza A virus (A/swine/Spain/...
314  >PP330721.1 |Influenza A virus (A/swine/Spain/...
322  >PP330730.1 |Influenza A virus (A/swine/Spain/...
330  >PP330763.1 |Influenza A virus (A/swine/Spain/...
338  >PP331788.1 |Influenza A virus (A/swine/Spain/...
346  >PP331797.1 |Influenza A virus (A/swine/Spain/...

                                              sequence  Segment  \
0    AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
8    AGCAAAAGCAGGTCAAATATATTCAACATGGAGAGAATAAAAGAAC...        1
16   AGCAAAAGCAGGTCAAATATATTCAACATGGAGAGAATAAAAGAAC...        1
24   AGCAAAAGCAGGTCAAATATATTCAACATGGAGAGAATAAAAGAAC...        1
32   AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
40   AGCAAAAGCAGGTCAAATATATTCAACATGGAGAGAATAAAAGAAC...        1
48   AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
56   AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
64   AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAT...        1
80   AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
88   AGCAAAAGCAGGTCAAATATATTCAATATGGAAAGAATAAAAGAAT...        1
96   AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
104  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
112  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
127  AGCAAAAGCAGGTCAAATATATACAATATGGAAAGAATAAAAGAAT...        1
134  AGCAAAAGCAGGTCAAATATATTCAATATGGAAAGAATTAAAGAAT...        1
142  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
150  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
157  AGCAAAAGCAGGTCAAATATATTCAATATGGAAAGAATAAAAGAAC...        1
165  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAT...        1
173  AGCAAAAGCAGGTCAAATATATTCAATATGGAAAGAATAAAAGAAC...        1
181  AGCAAAAGCAGGTCAAATATATTCAATATGGAAAGAATAAAAGAAT...        1
189  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
197  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
205  AGCAAAAGCAGGTCAAATATATTCAATATGGAACGAATAAAAGAAT...        1
221  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAT...        1
236  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAT...        1
244  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
252  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
268  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
275  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
283  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
291  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAT...        1
299  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
307  AGCAAAAGCAGGTCAAATATATCCAGTATGGAGAGAATAAAAGAAT...        1
314  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
322  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...        1
330  AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...        1
338  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAGC...        1
346  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAT...        1

                   genbank_name     Host_Type Years Geo_Location_Abrv  \
0    A/swine/Spain/36520-1/2022  other_mammal  2022             Spain
8     A/swine/Spain/6370-8/2019  other_mammal  2019             Spain
16    A/swine/Spain/6370-9/2019  other_mammal  2019             Spain
24   A/swine/Spain/6370-10/2019  other_mammal  2019             Spain
32   A/swine/Spain/17483-1/2021  other_mammal  2021             Spain
40   A/swine/Spain/6370-11/2019  other_mammal  2019             Spain
48   A/swine/Spain/44394-1/2021  other_mammal  2021             Spain
56   A/swine/Spain/05165-2/2022  other_mammal  2022             Spain
64   A/swine/Spain/37500-1/2022  other_mammal  2022             Spain
80   A/swine/Spain/12510-1/2022  other_mammal  2022             Spain
88   A/swine/Spain/49610-1/2022  other_mammal  2022             Spain
96    A/swine/Spain/2247-1/2022  other_mammal  2022             Spain
104  A/swine/Spain/31510-1/2022  other_mammal  2022             Spain
112  A/swine/Spain/46892-1/2022  other_mammal  2022             Spain
127  A/swine/Spain/45790-1/2022  other_mammal  2022             Spain
134  A/swine/Spain/50700-1/2022  other_mammal  2022             Spain
142  A/swine/Spain/17491-1/2022  other_mammal  2022             Spain
150  A/swine/Spain/06800-1/2020  other_mammal  2020             Spain
157   A/swine/Spain/5296-1/2022  other_mammal  2022             Spain
165  A/swine/Spain/22220-1/2020  other_mammal  2020             Spain
173  A/swine/Spain/28000-1/2021  other_mammal  2021             Spain
181  A/swine/Spain/06070-1/2020  other_mammal  2020             Spain
189  A/swine/Spain/17473-1/2021  other_mammal  2021             Spain
197  A/swine/Spain/22253-1/2020  other_mammal  2020             Spain
205  A/swine/Spain/41566-1/2021  other_mammal  2021             Spain
221  A/swine/Spain/22192-1/2021  other_mammal  2021             Spain
236  A/swine/Spain/30870-1/2021  other_mammal  2021             Spain
244  A/swine/Spain/12312-1/2021  other_mammal  2021             Spain
252  A/swine/Spain/22260-1/2021  other_mammal  2021             Spain
268  A/swine/Spain/22269-1/2020  other_mammal  2020             Spain
275  A/swine/Spain/22270-2/2020  other_mammal  2020             Spain
283  A/swine/Spain/25211-1/2020  other_mammal  2020             Spain
291  A/swine/Spain/05530-1/2020  other_mammal  2020             Spain
299  A/swine/Spain/31310-1/2020  other_mammal  2020             Spain
307  A/swine/Spain/22070-1/2020  other_mammal  2020             Spain
314  A/swine/Spain/50070-1/2020  other_mammal  2020             Spain
322  A/swine/Spain/32070-1/2020  other_mammal  2020             Spain
330  A/swine/Spain/22270-1/2020  other_mammal  2020             Spain
338  A/swine/Spain/05165-1/2020  other_mammal  2020             Spain
346  A/swine/Spain/40217-1/2020  other_mammal  2020             Spain

                                                  Name Segment_Name Serotype
0    >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB2       H1
8    >PQ107519|A/swine/Spain/6370-8/2019|H1N2|Spain...          PB2       H1
16   >PQ107529|A/swine/Spain/6370-9/2019|H1N2|Spain...          PB2       H1
24   >PQ107537|A/swine/Spain/6370-10/2019|H1N2|Spai...          PB2       H1
32   >PQ107546|A/swine/Spain/17483-1/2021|H1N2|Spai...          PB2       H1
40   >PQ107554|A/swine/Spain/6370-11/2019|H1N2|Spai...          PB2       H1
48   >PQ107577|A/swine/Spain/44394-1/2021|H1N1|Spai...          PB2       H1
56   >PQ107585|A/swine/Spain/05165-2/2022|H1N2|Spai...          PB2       H1
64   >PQ107595|A/swine/Spain/37500-1/2022|H1N2|Spai...          PB2       H1
80   >PQ107616|A/swine/Spain/12510-1/2022|H1N1|Spai...          PB2       H1
88   >PQ107624|A/swine/Spain/49610-1/2022|H1N2|Spai...          PB2       H1
96   >PQ107637|A/swine/Spain/2247-1/2022|H1N1|Spain...          PB2       H1
104  >PQ107645|A/swine/Spain/31510-1/2022|H1N1|Spai...          PB2       H1
112  >PQ107658|A/swine/Spain/46892-1/2022|H1N1|Spai...          PB2       H1
127  >PQ107769|A/swine/Spain/45790-1/2022|H1N2|Spai...          PB2       H1
134  >PQ107776|A/swine/Spain/50700-1/2022|H1N1|Spai...          PB2       H1
142  >PQ111069|A/swine/Spain/17491-1/2022|H1N1|Spai...          PB2       H1
150  >PQ580717|A/swine/Spain/06800-1/2020|H1|Spain|...          PB2       H1
157  >PQ585327|A/swine/Spain/5296-1/2022|H1N2|Spain...          PB2       H1
165  >PQ585394|A/swine/Spain/22220-1/2020|H1N2|Spai...          PB2       H1
173  >PP338223|A/swine/Spain/28000-1/2021|H1N1|Spai...          PB2       H1
181  >PP338238|A/swine/Spain/06070-1/2020|H1N2|Spai...          PB2       H1
189  >PP338247|A/swine/Spain/17473-1/2021|H1N2|Spai...          PB2       H1
197  >PP338272|A/swine/Spain/22253-1/2020|H1N1|Spai...          PB2       H1
205  >PP338281|A/swine/Spain/41566-1/2021|H1N2|Spai...          PB2       H1
221  >PP338511|A/swine/Spain/22192-1/2021|H1N1|Spai...          PB2       H1
236  >PP338530|A/swine/Spain/30870-1/2021|H1N2|Spai...          PB2       H1
244  >PP338682|A/swine/Spain/12312-1/2021|H1N1|Spai...          PB2       H1
252  >PP338713|A/swine/Spain/22260-1/2021|H1N2|Spai...          PB2       H1
268  >PP338874|A/swine/Spain/22269-1/2020|H1N1|Spai...          PB2       H1
275  >PP335236|A/swine/Spain/22270-2/2020|H1N2|Spai...          PB2       H1
283  >PP335491|A/swine/Spain/25211-1/2020|H1N1|Spai...          PB2       H1
291  >PP335504|A/swine/Spain/05530-1/2020|H1N2|Spai...          PB2       H1
299  >PP330401|A/swine/Spain/31310-1/2020|H1N2|Spai...          PB2       H1
307  >PP330414|A/swine/Spain/22070-1/2020|H1N2|Spai...          PB2       H1
314  >PP330721|A/swine/Spain/50070-1/2020|H1N1|Spai...          PB2       H1
322  >PP330730|A/swine/Spain/32070-1/2020|H1N1|Spai...          PB2       H1
330  >PP330763|A/swine/Spain/22270-1/2020|H1N2|Spai...          PB2       H1
338  >PP331788|A/swine/Spain/05165-1/2020|H1N1|Spai...          PB2       H1
346  >PP331797|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB2       H1
       Accession                                      GenBank_Title  \
1    PQ585341.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
9    PQ107520.1   Influenza A virus (A/swine/Spain/6370-8/2019(H...
17   PQ107530.1   Influenza A virus (A/swine/Spain/6370-9/2019(H...
25   PQ107538.1   Influenza A virus (A/swine/Spain/6370-10/2019(...
33   PQ107547.1   Influenza A virus (A/swine/Spain/17483-1/2021(...
41   PQ107555.1   Influenza A virus (A/swine/Spain/6370-11/2019(...
49   PQ107578.1   Influenza A virus (A/swine/Spain/44394-1/2021(...
57   PQ107586.1   Influenza A virus (A/swine/Spain/05165-2/2022(...
65   PQ107596.1   Influenza A virus (A/swine/Spain/37500-1/2022(...
81   PQ107617.1   Influenza A virus (A/swine/Spain/12510-1/2022(...
89   PQ107625.1   Influenza A virus (A/swine/Spain/49610-1/2022(...
97   PQ107638.1   Influenza A virus (A/swine/Spain/2247-1/2022(H...
105  PQ107646.1   Influenza A virus (A/swine/Spain/31510-1/2022(...
113  PQ107659.1   Influenza A virus (A/swine/Spain/46892-1/2022(...
135  PQ107777.1   Influenza A virus (A/swine/Spain/50700-1/2022(...
143  PQ111070.1   Influenza A virus (A/swine/Spain/17491-1/2022(...
151  PQ580718.1   Influenza A virus (A/swine/Spain/06800-1/2020(...
158  PQ585328.1   Influenza A virus (A/swine/Spain/5296-1/2022(H...
166  PQ585395.1   Influenza A virus (A/swine/Spain/22220-1/2020(...
174  PP338224.1   Influenza A virus (A/swine/Spain/28000-1/2021(...
182  PP338239.1   Influenza A virus (A/swine/Spain/06070-1/2020(...
190  PP338248.1   Influenza A virus (A/swine/Spain/17473-1/2021(...
198  PP338273.1   Influenza A virus (A/swine/Spain/22253-1/2020(...
206  PP338282.1   Influenza A virus (A/swine/Spain/41566-1/2021(...
222  PP338512.1   Influenza A virus (A/swine/Spain/22192-1/2021(...
229  PP338519.1   Influenza A virus (A/swine/Spain/44593-1/2021(...
237  PP338531.1   Influenza A virus (A/swine/Spain/30870-1/2021(...
245  PP338683.1   Influenza A virus (A/swine/Spain/12312-1/2021(...
253  PP338714.1   Influenza A virus (A/swine/Spain/22260-1/2021(...
269  PP338875.1   Influenza A virus (A/swine/Spain/22269-1/2020(...
276  PP335237.1   Influenza A virus (A/swine/Spain/22270-2/2020(...
284  PP335492.1   Influenza A virus (A/swine/Spain/25211-1/2020(...
292  PP335505.1   Influenza A virus (A/swine/Spain/05530-1/2020(...
300  PP330402.1   Influenza A virus (A/swine/Spain/31310-1/2020(...
308  PP330415.1   Influenza A virus (A/swine/Spain/22070-1/2020(...
315  PP330722.1   Influenza A virus (A/swine/Spain/50070-1/2020(...
323  PP330731.1   Influenza A virus (A/swine/Spain/32070-1/2020(...
331  PP330764.1   Influenza A virus (A/swine/Spain/22270-1/2020(...
339  PP331789.1   Influenza A virus (A/swine/Spain/05165-1/2020(...
347  PP331798.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

           Host Collection_Date SRA_Accession  Isolate Genotype Geo_Location  \
1    sus scrofa      2022-09-21      PQ585341  36520-1     H1N1        Spain
9    sus scrofa      2019-05-17      PQ107520   6370-8     H1N2        Spain
17   sus scrofa      2019-05-17      PQ107530   6370-9     H1N2        Spain

## GISAID

In [12]:
# GISAID

os.chdir(downloads_saved)

gisaid_metadata = pd.read_excel("gisaid_epiflu_isolates.xls")

gisaid_fasta = fasta_df("gisaid_epiflu_sequence.fasta", states_ref)

# gisaid_metadata
genotypes = gisaid_metadata["Genotype"].values

# Separate fastas by segment
fastas, unique_segments = separate_fasta_by_segs(gisaid_metadata, gisaid_fasta, animals_ref, genotypes) # Separate the fasta dataframes into 8 different files based on segment
    # print(fastas[0])

Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned
Not assigned

c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:885: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["Genotype"] = "Unassigned"
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:889: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:885: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["Genotype"] = "Unassigned"
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:889: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:885: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["Genotype"] = "Unassigned"
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:889: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:885: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["Genotype"] = "Unassigned"
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:889: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:885: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["Genotype"] = "Unassigned"
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:889: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:885: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["Genotype"] = "Unassigned"
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:889: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:885: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["Genotype"] = "Unassigned"
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:889: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:885: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["Genotype"] = "Unassigned"
c:\Users\maksiaevai.NCBI_NT\Documents\Avian_Flu\utils.py:889: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name

### De-duplication

In [ ]:
# De-duplicate from GenBank





gisaid_fastas = []
for fasta in fastas:
    for serotype in serotypes:
        m_g_s = fasta[fasta["Subtype"].str.contains(serotype)]
        m_g_s["Serotype"] = serotype
        if len(m_g_s) > 0:
            # Check to see if isolate is already in GenBank
            m_g_s["Isolate"] = m_g_s["Isolate_Id"]
            exp_df = metadata_genoflu.merge(m_g_s, on="Isolate", how="right", indicator=True)
            # print(exp_df)
            exp_df["New_Name"] = exp_df[exp_df["_merge"] == "right_only"]["New_Name"].apply(lambda x: x.replace("other_mammal", "Iberian_swine") if x.split("/")[3] in iberian_swine else x.replace("other_mammal", "swine") if "swine" in x else x)
            exp_df = exp_df[exp_df["_merge"] == "right_only"]
            exp_df["New_Name"] = exp_df["New_Name"].apply(lambda x: "|".join(x.split("|")[:-1]))
            exp_df = exp_df.drop_duplicates(subset="New_Name", keep="first")
            gisaid_fastas.append(exp_df)

print(gisaid_fastas[0].columns)

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:

Index(['Accession', 'GenBank_Title', 'Host', 'Collection_Date',
       'SRA_Accession', 'Isolate', 'Genotype_x', 'Geo_Location_x',
       'full_header', 'sequence', 'Segment_x', 'genbank_name', 'Host_Type_x',
       'Years', 'Geo_Location_Abrv', 'Name', 'Segment_Name', 'Header',
       'Isolate_Id', 'Isolate_Name', 'Subtype', 'Segment_y', 'Location',
       'Geo_Location_y', 'Date Collected', 'Species', 'Sequence', 'Identifier',
       'Host_Type_y', 'Genotype_y', 'New_Name', 'Serotype', '_merge'],
      dtype='object')

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = serotype
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\4131835937.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Isolate"] = m_g_s["Isolate_Id"]

### Create FASTA Files

In [14]:
# Create FASTA files

os.chdir(complete_files)



for df in gisaid_fastas:
    for serotype in serotypes:
        if serotype == df["Serotype"].values[0]:
            df["Segment_Name"] = df["Segment_y"]
            print(df)
            df.to_csv("GISAID_" + df["Segment_Name"].values[0] + "_" + serotype + "_metadata_Paloma.csv")
            df = df.reset_index()
            if len(df["Genotype_y"].values[0]) > 0: # If we have assigned genotypes, including "Unassigned"
                file_name = "GISAID_" + df["Segment_Name"].values[0] + "_" + serotype + "_Paloma.fasta"
                output_file = open(complete_files + file_name, "w")

                for index, row in df.iterrows():
                    name = df.loc[index, "New_Name"]
                    name = name.replace(" ", "_")
                    # names.append(name)
                    sequence = df.loc[index, "Sequence"]
                    # First is header, second is sequence
                    output_file.write(name + "\n")
                    output_file.write(sequence + "\n")
                
            output_file.close()

    Accession GenBank_Title Host Collection_Date SRA_Accession        Isolate  \
24        NaN           NaN  NaN             NaN           NaN        50001-5
25        NaN           NaN  NaN             NaN           NaN        25001-3
42        NaN           NaN  NaN             NaN           NaN        50001-2
59        NaN           NaN  NaN             NaN           NaN        25001-2
76        NaN           NaN  NaN             NaN           NaN        44490-1
141       NaN           NaN  NaN             NaN           NaN        06001-3
142       NaN           NaN  NaN             NaN           NaN         6370-7
143       NaN           NaN  NaN             NaN           NaN        50800-1
144       NaN           NaN  NaN             NaN           NaN        22000-1
145       NaN           NaN  NaN             NaN           NaN          000-1
162       NaN           NaN  NaN             NaN           NaN        50001-6
226       NaN           NaN  NaN             NaN           NaN        25001-1
227       NaN           NaN  NaN             NaN           NaN        22251-1
228       NaN           NaN  NaN             NaN           NaN        25001-4
229       NaN           NaN  NaN             NaN           NaN         6370-6
230       NaN           NaN  NaN             NaN           NaN        31001-2
231       NaN           NaN  NaN             NaN           NaN        50001-4
232       NaN           NaN  NaN             NaN           NaN           4050
233       NaN           NaN  NaN             NaN           NaN  NSAV198309324

    Genotype_x Geo_Location_x full_header sequence  ...   Geo_Location_y  \
24         NaN            NaN         NaN      NaN  ...            Spain
25         NaN            NaN         NaN      NaN  ...            Spain
42         NaN            NaN         NaN      NaN  ...            Spain
59         NaN            NaN         NaN      NaN  ...            Spain
76         NaN            NaN         NaN      NaN  ...            Spain
141        NaN            NaN         NaN      NaN  ...            Spain
142        NaN            NaN         NaN      NaN  ...            Spain
143        NaN            NaN         NaN      NaN  ...            Spain
144        NaN            NaN         NaN      NaN  ...            Spain
145        NaN            NaN         NaN      NaN  ...            Spain
162        NaN            NaN         NaN      NaN  ...            Spain
226        NaN            NaN         NaN      NaN  ...            Spain
227        NaN            NaN         NaN      NaN  ...            Spain
228        NaN            NaN         NaN      NaN  ...            Spain
229        NaN            NaN         NaN      NaN  ...            Spain
230        NaN            NaN         NaN      NaN  ...            Spain
231        NaN            NaN         NaN      NaN  ...            Spain
232        NaN            NaN         NaN      NaN  ...    Spain-Navarra
233        NaN            NaN         NaN      NaN  ...  Spain-Catalonia

    Date Collected    Species  \
24      2019-11-20      swine
25      2019-12-04      swine
42      2019-04-26      swine
59      2019-11-20      swine
76      2020-04-13      swine
141     2019-10-17      swine
142     2020-06-15      swine
143     2020-05-12      swine
144     2020-03-19      swine
145     2019-10-01      swine
162     2019-11-07      swine
226     2019-11-15      swine
227     2020-04-15      swine
228     2019-12-24      swine
229     2020-06-15      swine
230     2019-10-17      swine
231     2019-11-06      swine
232     2022-10-17    Navarra
233     2024-10-01  Catalonia

                                              Sequence        Identifier  \
24   agcaaaagcaggtactgatccaaaatggaagactttgtgcgacaat...   EPI_ISL_6781292
25   agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...   EPI_ISL_6781291
42   agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...   EPI_ISL_6781289
59   agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...   EPI_ISL_6781304
76   agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...   EPI_ISL_6781259
141  agcaaaagcaggtactgattcaaaatggaagattttgtgcgacaat...   EPI_ISL_6781350
142  agcaaaagcaggtactgatccaaaatggaagactttgtgcggcaat...   EPI_ISL_6781349
143  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...   EPI_ISL_6781347
144  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...   EPI_ISL_6781345
145  agcaaaagcaggtactgatccaaaatggaagacttcgtgcgacagt...   EPI_ISL_6781344
162  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...   EPI_ISL_6781229
226  agcaaaagcaggtactgatccaaaatggaggactttgtgcgacaat...   EPI_ISL_6781343
227  agcaaaagcaggtactgatccaaaatggaagactttgtgagacaat...   EPI_ISL_6781342
228  agcaaaagcaggtactgatccaaaatggaagactttgtgcgacaat...   EPI_ISL_6781341
229  agcaaaagcaggtactgatccaaaatggaagactttgtgcggcaat...   EPI_ISL_6781340
230  agcaaaagcaggtactgatccaaaatggaagactttgtgcgacaat...   EPI_ISL_6781339
231  agcaaaagcaggtactgatccaaaatggaagactttgtgcgacaat...   EPI_ISL_6781338
232  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...  EPI_ISL_16074739
233  gtactgatccaaaatggaagactttgtgcgacagtgcttcaatcca...  EPI_ISL_19459695

      Host_Type_y  Genotype_y  \
24   other_mammal  Unassigned
25   other_mammal  Unassigned
42   other_mammal  Unassigned
59   other_mammal  Unassigned
76   other_mammal  Unassigned
141  other_mammal  Unassigned
142  other_mammal  Unassigned
143  other_mammal  Unassigned
144  other_mammal  Unassigned
145  other_mammal  Unassigned
162  other_mammal  Unassigned
226  other_mammal  Unassigned
227  other_mammal  Unassigned
228  other_mammal  Unassigned
229  other_mammal  Unassigned
230  other_mammal  Unassigned
231  other_mammal  Unassigned
232         human  Unassigned
233         human  Unassigned

                                              New_Name Serotype      _merge
24   >EPI_ISL_6781292|A/swine/Spain/50001-5/2019|H1...       H1  right_only
25   >EPI_ISL_6781291|A/swine/Spain/25001-3/2019|H1...       H1  right_only
42   >EPI_ISL_6781289|A/swine/Spain/50001-2/2019|H1...       H1  right_only
59   >EPI_ISL_6781304|A/swine/Spain/25001-2/2019|H1...       H1  right_only
76   >EPI_ISL_6781259|A/swine/Spain/44490-1/2020|H1...       H1  right_only
141  >EPI_ISL_6781350|A/swine/Spain/06001-3/2019|H1...       H1  right_only
142  >EPI_ISL_6781349|A/swine/Spain/6370-7/2020|H1N...       H1  right_only
143  >EPI_ISL_6781347|A/swine/Spain/50800-1/2020|H1...       H1  right_only
144  >EPI_ISL_6781345|A/swine/Spain/22000-1/2020|H1...       H1  right_only
145  >EPI_ISL_6781344|A/swine/Spain/000-1/2019|H1N1...       H1  right_only
162  >EPI_ISL_6781229|A/swine/Spain/50001-6/2019|H1...       H1  right_only
226  >EPI_ISL_6781343|A/swine/Spain/25001-1/2019|H1...       H1  right_only
227  >EPI_ISL_6781342|A/swine/Spain/22251-1/2020|H1...       H1  right_only
228  >EPI_ISL_6781341|A/swine/Spain/25001-4/2019|H1...       H1  right_only
229  >EPI_ISL_6781340|A/swine/Spain/6370-6/2020|H1N...       H1  right_only
230  >EPI_ISL_6781339|A/swine/Spain/31001-2/2019|H1...       H1  right_only
231  >EPI_ISL_6781338|A/swine/Spain/50001-4/2019|H1...       H1  right_only
232  >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...       H1  right_only
233  >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...       H1  right_only

[19 rows x 33 columns]
   Accession GenBank_Title Host Collection_Date SRA_Accession  Isolate  \
0        NaN           NaN  NaN             NaN           NaN  46314-2
9        NaN           NaN  NaN             NaN           NaN  44579-1
26       NaN           NaN  NaN             NaN           NaN  46314-1

   Genotype_x Geo_Location_x full_header sequence  ...  Geo_Location_y  \
0         NaN            NaN         NaN      NaN  ...           Spain
9         NaN            NaN         NaN      NaN  ...           Spain
26        NaN            NaN         NaN      NaN  ...           Spain

   Date Collected Species                                           Sequence  \
0      2020-04-30   swine  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...
9      2020-05-18   swine  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...
26     2020-02-21   swine  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...

         Identifier   Host_Type_y  Genotype_y  \
0   EPI_ISL_6781281  other_mammal  Unassigned
9   EPI_ISL_6781348  other_mammal  Unassigned
26  EPI_ISL_6781332  other_mammal  Unassigned

                                             New_Name Serotype      _merge
0   >EPI_ISL_6781281|A/swine/Spain/46314-2/2020|H3...       H3  right_only
9   >EPI_ISL_6781348|A/swine/Spain/44579-1/2020|H3...       H3  right_only
26  >EPI_ISL_6781332|A/swine/Spain/46314-1/2020|H3...       H3  right_only

[3 rows x 33 columns]
    Accession GenBank_Title Host Collection_Date SRA_Accession        Isolate  \
8         NaN           NaN  NaN             NaN           NaN        46314-2
65        NaN           NaN  NaN             NaN           NaN          000-1
113       NaN           NaN  NaN             NaN           NaN        46314-1
114       NaN           NaN  NaN             NaN           NaN        25001-4
115       NaN           NaN  NaN             NaN           NaN        31001-2
116       NaN           NaN  NaN             NaN           NaN        50001-4
117       NaN           NaN  NaN             NaN           NaN           4050
118       NaN           NaN  NaN             NaN           NaN  NSAV198309324

    Genotype_x Geo_Location_x full_header sequence  ...   Geo_Location_y  \
8          NaN            NaN         NaN      NaN  ...            Spain
65         NaN            NaN         NaN      NaN  ...            Spain
113        NaN            NaN         NaN      NaN  ...            Spain
114        NaN            NaN         NaN      NaN  ...            Spain
115        NaN            NaN         NaN      NaN  ...            Spain
116        NaN            NaN         NaN      NaN  ...            Spain
117        NaN            NaN         NaN      NaN  ...    Spain-Navarra
118        NaN            NaN         NaN      NaN  ...  Spain-Catalonia

    Date Collected    Species  \
8       2020-04-30      swine
65      2019-10-01      swine
113     2020-02-21      swine
114     2019-12-24      swine
115     2019-10-17      swine
116     2019-11-06      swine
117     2022-10-17    Navarra
118     2024-10-01  Catalonia

                                              Sequence        Identifier  \
8    agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...   EPI_ISL_6781281
65   agcaaaagcaggtactgatccaaaatggaagacttcgtgcgacagt...   EPI_ISL_6781344
113  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...   EPI_ISL_6781332
114  agcaaaagcaggtactgatccaaaatggaagactttgtgcgacaat...   EPI_ISL_6781341
115  agcaaaagcaggtactgatccaaaatggaagactttgtgcgacaat...   EPI_ISL_6781339
116  agcaaaagcaggtactgatccaaaatggaagactttgtgcgacaat...   EPI_ISL_6781338
117  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...  EPI_ISL_16074739
118  gtactgatccaaaatggaagactttgtgcgacagtgcttcaatcca...  EPI_ISL_19459695

      Host_Type_y  Genotype_y  \
8    other_mammal  Unassigned
65   other_mammal  Unassigned
113  other_mammal  Unassigned
114  other_mammal  Unassigned
115  other_mammal  Unassigned
116  other_mammal  Unassigned
117         human  Unassigned
118         human  Unassigned

                                              New_Name Serotype      _merge
8    >EPI_ISL_6781281|A/swine/Spain/46314-2/2020|H3...       N1  right_only
65   >EPI_ISL_6781344|A/swine/Spain/000-1/2019|H1N1...       N1  right_only
113  >EPI_ISL_6781332|A/swine/Spain/46314-1/2020|H3...       N1  right_only
114  >EPI_ISL_6781341|A/swine/Spain/25001-4/2019|H1...       N1  right_only
115  >EPI_ISL_6781339|A/swine/Spain/31001-2/2019|H1...       N1  right_only
116  >EPI_ISL_6781338|A/swine/Spain/50001-4/2019|H1...       N1  right_only
117  >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...       N1  right_only
118  >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...       N1  right_only

[8 rows x 33 columns]
    Accession GenBank_Title Host Collection_Date SRA_Accession  Isolate  \
16        NaN           NaN  NaN             NaN           NaN  50001-5
17        NaN           NaN  NaN             NaN           NaN  25001-3
34        NaN           NaN  NaN             NaN           NaN  50001-2
43        NaN           NaN  NaN             NaN           NaN  25001-2
44        NaN           NaN  NaN             NaN           NaN  44490-1
85        NaN           NaN  NaN             NaN           NaN  06001-3
86        NaN           NaN  NaN             NaN           NaN   6370-7
87        NaN           NaN  NaN             NaN           NaN  44579-1
88        NaN           NaN  NaN             NaN           NaN  50800-1
89        NaN           NaN  NaN             NaN           NaN  22000-1
98        NaN           NaN  NaN             NaN           NaN  50001-6
139       NaN           NaN  NaN             NaN           NaN  25001-1
140       NaN           NaN  NaN             NaN           NaN  22251-1
141       NaN           NaN  NaN             NaN           NaN   6370-6

    Genotype_x Geo_Location_x full_header sequence  ...  Geo_Location_y  \
16         NaN            NaN         NaN      NaN  ...           Spain
17         NaN            NaN         NaN      NaN  ...           Spain
34         NaN            NaN         NaN      NaN  ...           Spain
43         NaN            NaN         NaN      NaN  ...           Spain
44         NaN            NaN         NaN      NaN  ...           Spain
85         NaN            NaN         NaN      NaN  ...           Spain
86         NaN            NaN         NaN      NaN  ...           Spain
87         NaN            NaN         NaN      NaN  ...           Spain
88         NaN            NaN         NaN      NaN  ...           Spain
89         NaN            NaN         NaN      NaN  ...           Spain
98         NaN            NaN         NaN      NaN  ...           Spain
139        NaN            NaN         NaN      NaN  ...           Spain
140        NaN            NaN         NaN      NaN  ...           Spain
141        NaN            NaN         NaN      NaN  ...           Spain

    Date Collected Species                                           Sequence  \
16      2019-11-20   swine  agcaaaagcaggtactgatccaaaatggaagactttgtgcgacaat...
17      2019-12-04   swine  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...
34      2019-04-26   swine  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...
43      2019-11-20   swine  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...
44      2020-04-13   swine  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...
85      2019-10-17   swine  agcaaaagcaggtactgattcaaaatggaagattttgtgcgacaat...
86      2020-06-15   swine  agcaaaagcaggtactgatccaaaatggaagactttgtgcggcaat...
87      2020-05-18   swine  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...
88      2020-05-12   swine  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...
89      2020-03-19   swine  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...
98      2019-11-07   swine  agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...
139     2019-11-15   swine  agcaaaagcaggtactgatccaaaatggaggactttgtgcgacaat...
140     2020-04-15   swine  agcaaaagcaggtactgatccaaaatggaagactttgtgagacaat...
141     2020-06-15   swine  agcaaaagcaggtactgatccaaaatggaagactttgtgcggcaat...

          Identifier   Host_Type_y  Genotype_y  \
16   EPI_ISL_6781292  other_mammal  Unassigned
17   EPI_ISL_6781291  other_mammal  Unassigned
34   EPI_ISL_6781289  other_mammal  Unassigned
43   EPI_ISL_6781304  other_mammal  Unassigned
44   EPI_ISL_6781259  other_mammal  Unassigned
85   EPI_ISL_6781350  other_mammal  Unassigned
86   EPI_ISL_6781349  other_mammal  Unassigned
87   EPI_ISL_6781348  other_mammal  Unassigned
88   EPI_ISL_6781347  other_mammal  Unassigned
89   EPI_ISL_6781345  other_mammal  Unassigned
98   EPI_ISL_6781229  other_mammal  Unassigned
139  EPI_ISL_6781343  other_mammal  Unassigned
140  EPI_ISL_6781342  other_mammal  Unassigned
141  EPI_ISL_6781340  other_mammal  Unassigned

                                              New_Name Serotype      _merge
16   >EPI_ISL_6781292|A/swine/Spain/50001-5/2019|H1...       N2  right_only
17   >EPI_ISL_6781291|A/swine/Spain/25001-3/2019|H1...       N2  right_only
34   >EPI_ISL_6781289|A/swine/Spain/50001-2/2019|H1...       N2  right_only
43   >EPI_ISL_6781304|A/swine/Spain/25001-2/2019|H1...       N2  right_only
44   >EPI_ISL_6781259|A/swine/Spain/44490-1/2020|H1...       N2  right_only
85   >EPI_ISL_6781350|A/swine/Spain/06001-3/2019|H1...       N2  right_only
86   >EPI_ISL_6781349|A/swine/Spain/6370-7/2020|H1N...       N2  right_only
87   >EPI_ISL_6781348|A/swine/Spain/44579-1/2020|H3...       N2  right_only
88   >EPI_ISL_6781347|A/swine/Spain/50800-1/2020|H1...       N2  right_only
89   >EPI_ISL_6781345|A/swine/Spain/22000-1/2020|H1...       N2  right_only
98   >EPI_ISL_6781229|A/swine/Spain/50001-6/2019|H1...       N2  right_only
139  >EPI_ISL_6781343|A/swine/Spain/25001-1/2019|H1...       N2  right_only
140  >EPI_ISL_6781342|A/swine/Spain/22251-1/2020|H1...       N2  right_only
141  >EPI_ISL_6781340|A/swine/Spain/6370-6/2020|H1N...       N2  right_only

[14 rows x 33 columns]
    Accession GenBank_Title Host Collection_Date SRA_Accession        Isolate  \
16        NaN           NaN  NaN             NaN           NaN        50001-5
17        NaN           NaN  NaN             NaN           NaN        25001-3
26        NaN           NaN  NaN             NaN           NaN        50001-2
35        NaN           NaN  NaN             NaN           NaN        25001-2
51        NaN           NaN  NaN             NaN           NaN        44490-1
130       NaN           NaN  NaN             NaN           NaN        06001-3
131       NaN           NaN  NaN             NaN           NaN         6370-7
132       NaN           NaN  NaN             NaN           NaN        50800-1
133       NaN           NaN  NaN             NaN           NaN        50001-3
134       NaN           NaN  NaN             NaN           NaN        22000-1
135       NaN           NaN  NaN             NaN           NaN          000-1
152       NaN           NaN  NaN             NaN           NaN        50001-6
216       NaN           NaN  NaN             NaN           NaN        25001-1
217       NaN           NaN  NaN             NaN           NaN        22251-1
218       NaN           NaN  NaN             NaN           NaN        25001-4
219       NaN           NaN  NaN             NaN           NaN         6370-6
220       NaN           NaN  NaN             NaN           NaN        31001-2
221       NaN           NaN  NaN             NaN           NaN        50001-4
222       NaN           NaN  NaN             NaN           NaN           4050
223       NaN           NaN  NaN             NaN           NaN  NSAV198309324

    Genotype_x Geo_Location_x full_header sequence  ...   Geo_Location_y  \
16         NaN            NaN         NaN      NaN  ...            Spain
17         NaN            NaN         NaN      NaN  ...            Spain
26         NaN            NaN         NaN      NaN  ...            Spain
35         NaN            NaN         NaN      NaN  ...            Spain
51         NaN            NaN         NaN      NaN  ...            Spain
130        NaN            NaN         NaN      NaN  ...            Spain
131        NaN            NaN         NaN      NaN  ...            Spain
132        NaN            NaN         NaN      NaN  ...            Spain
133        NaN            NaN         NaN      NaN  ...            Spain
134        NaN            NaN         NaN      NaN  ...            Spain
135        NaN            NaN         NaN      NaN  ...            Spain
152        NaN            NaN         NaN      NaN  ...            Spain
216        NaN            NaN         NaN      NaN  ...            Spain
217        NaN            NaN         NaN      NaN  ...            Spain
218        NaN            NaN         NaN      NaN  ...            Spain

### Concatenation

In [15]:
# Now concatenate GISAID and GenBank

genbank_files = []
gisaid_files = []
for dirpath, dirs, files in os.walk(complete_files):
    for file in files:
        file_name = os.path.join(dirpath, file)
        if "GenBank" in file_name and ".fasta" in file_name:
            genbank_files.append(file_name)
        elif "GISAID" in file_name and ".fasta" in file_name:
            gisaid_files.append(file_name)
        else:
            continue

for file1 in genbank_files:
    if len(file1.split("_")) == 4:
        partial_file_name = "_".join(file1.split("_")[-3:])
    else:
        partial_file_name = "_".join(file1.split("_")[-3:])
    for file2 in gisaid_files:
        if len(file2.split("_")) == 4:
            partial_file_name_gisaid = "_".join(file2.split("_")[-3:])
        else:
            partial_file_name_gisaid = "_".join(file2.split("_")[-3:])
        if partial_file_name == partial_file_name_gisaid:
            with open(complete_files + partial_file_name, 'w') as outfile:
                with open(file1) as f1:
                    for line in f1:
                        outfile.write(line)
                    f1.close()
                with open(file2) as f2:
                    for line in f2:
                        outfile.write(line)
                    f2.close()
                outfile.close()

## GISAID (again)

In [16]:
downloads_saved = home + "Other/Paloma/Y2K_swine/" 

complete_files = downloads_saved + "complete/" 
if not os.path.exists(complete_files): # checking if the directory exists or not
    os.makedirs(complete_files) # if the directory is not present then create it

In [17]:
all_metadata_files = []
all_fasta_files = []

# If we have multiple files, name them nicely
for dirpath, dirs, files in os.walk(downloads_saved):
    for file in files:
        file_name = os.path.join(dirpath, file)
        # file_name = "_".join(file_name.split(" "))
        
        os.rename(file_name, "_".join(file_name.split(" ")).replace("(", "").replace(")", ""))

        print(file_name)

        # Now go through files and get contents
        if ".xls" in file_name:
            metadata = pd.read_excel(file_name)
            all_metadata_files.append(metadata)
        # if ".csv" in file_name:
        #     metadata = pd.read_csv(file_name)
        #     all_metadata_files.append(metadata)
        if ".fasta" in file_name:
            fasta_file = fasta_df(file_name, states_ref) # Convert fasta file to dataframe
            # print(fasta_file[fasta_file["Geo_Location"] != "USA"])
            # break 
            all_fasta_files.append(fasta_file)
    break

C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Other/Paloma/Y2K_swine/gisaid_epiflu_isolates.xls
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Other/Paloma/Y2K_swine/gisaid_epiflu_sequence.fasta
C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Other/Paloma/Y2K_swine/paloma_isolates.csv

In [65]:
# Separate FASTA files into 8 different files based on segment

def separate_fasta_by_seg(metadata, fasta, animals_df): 

    fasta = fix_animals(fasta, animals_df)
    # Dummy host type -- we'll actually add this in later
    # b313_fasta["Host_Type"] = "other"
    # d11_fasta["Host_Type"] = "other"

    unique_segments = list(set(fasta["Segment"]))
    # genotypes = ["B3.13", "D1.1"]
    # genotype_fastas = {"B3.13": b313_fasta, "D1.1": d11_fasta}

    # “>EPI_ID/Isolate_name|subtype|collection_date|host_type|genotype”

    segment_fastas = []
    for seg in unique_segments:

        xls = metadata

        # print(xls)
        # print("XLS: ", metadata["Genotype"])

        # print(d11_xls)

        # FASTA
        # if "Identifier" in fasta.columns:
        #     mask = fasta["Identifier"].isin(xls['Isolate_Id'])
        # else:           
        #     mask = fasta['Isolate_Id'].isin(xls['Isolate_Id'])
        #     fasta["Identifier"] = fasta["Isolate_Id"]

        # fasta_seg_pre = fasta[mask]
        # print(fasta_seg_pre)
        xls["Identifier"] = xls["Isolate_Id"]
        fasta_seg_pre = fasta.merge(xls, on="Identifier")

        # fasta_seg = genotype_fastas[fasta_gen][genotype_fastas[fasta_gen]["Segment"] == seg]
        fasta_seg = fasta_seg_pre[fasta_seg_pre["Segment"] == seg]
        print(fasta_seg)

        # Rename sequences 
        new_name = ">" + fasta_seg["Identifier"] + "|" + fasta_seg["Isolate_Name_x"] + "|" + fasta_seg["Subtype_x"].apply(lambda x: x.split("_")[-1]) + "|" + fasta_seg["Location_y"].apply(lambda x: x.split("/")[1].replace(" ", "")) + "|" + fasta_seg["Date Collected"].apply(lambda x: str(dateutil.parser.parse(x, default=dateutil.parser.parse("2000-01-01")).year) if dateutil.parser.parse(x, default=dateutil.parser.parse("2000-01-01")).month == dateutil.parser.parse("2000-01-01").month and dateutil.parser.parse(x, default=dateutil.parser.parse("2000-01-01")).day == dateutil.parser.parse("2000-01-01").day else x) + "|swine\n"
        fasta_seg["New_Name"] = new_name
        # print(fasta_seg["New_Name"])

        segment_fastas.append(fasta_seg)
        # print(fasta_seg)

    return segment_fastas, unique_segments

# Separate fastas by segment
segment_fastas = []
unique_animals_all = []
for i, fasta in enumerate(all_fasta_files):
    # print(all_fasta_files)
    # print(fasta)
    # print(i)
    metadata = all_metadata_files[i]
    # print(metadata["Clade"])
    # break 
    # print(fasta.loc[i, "Isolate_Name"])
    
    unique_animals = sort_animals(fasta) # Find unique animals
    # print("Animals: ", unique_animals)
    unique_animals_all.append(unique_animals)

    os.chdir(references)
    animals_ref = pd.read_csv("animals_ref.csv")
    print(fasta)
    fastas, unique_segments = separate_fasta_by_seg(metadata, fasta, animals_ref) # Separate the fasta dataframes into 8 different files based on segment
    # print(fastas[0])

    for fasta in fastas:
        segment_fastas.append(fasta)

                                                  Header Isolate_Id  \
0      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...       R313
1      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...       R313
2      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...       R313
3      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...       R313
4      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...       R313
...                                                  ...        ...
27011  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...       R312
27012  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...       R312
27013  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...       R312
27014  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...       R312
27015  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...       R312

                    Isolate_Name Subtype Segment Location Geo_Location  \
0      A/swine/Germany/R313/2015    H1N2      HA  Germany      Germany
1      A/swine/Germany/R313/2015    H1N2      NA  Germany      Germany
2      A/swine/Germany/R313/2015    H1N2     PB2  Germany      Germany
3      A/swine/Germany/R313/2015    H1N2     PB1  Germany      Germany
4      A/swine/Germany/R313/2015    H1N2      PA  Germany      Germany
...                          ...     ...     ...      ...          ...
27011  A/swine/Germany/R312/2015    H1N1     PB1  Germany      Germany
27012  A/swine/Germany/R312/2015    H1N1      PA  Germany      Germany
27013  A/swine/Germany/R312/2015    H1N1      NP  Germany      Germany
27014  A/swine/Germany/R312/2015    H1N1      MP  Germany      Germany
27015  A/swine/Germany/R312/2015    H1N1      NS  Germany      Germany

      Date Collected Species  \
0               2014   swine
1               2014   swine
2               2014   swine
3               2014   swine
4               2014   swine
...              ...     ...
27011           2014   swine
27012           2014   swine
27013           2014   swine
27014           2014   swine
27015           2014   swine

                                                Sequence      Identifier  \
0      atggaaacaagactgtttgtattatttagtgtattcactgcactaa...  EPI_ISL_245764
1      atgaatccaaatcaaaagataataacgattggttctgtatccctaa...  EPI_ISL_245764
2      atggagagaataaaagaactgagagatctaatgtcgcagtcccgca...  EPI_ISL_245764
3      atggatgtcaatccgactctacttttcctaaaaattccagcgcaaa...  EPI_ISL_245764
4      cattcacatcttttcattcactggagaggagattgccaccaaagcg...  EPI_ISL_245764
...                                                  ...             ...
27011  atggatgtcaacccgactctacttttcttaaaagtgccagcacaaa...  EPI_ISL_245748
27012  atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  EPI_ISL_245748
27013  ctcactgagtgacatttaagccatggtgtctcaaggcaccaaacga...  EPI_ISL_245748
27014  atgagtcttctaactgaggtcgaaacgtacgtcctttctatcatcc...  EPI_ISL_245748
27015  agcaaaagcagggtgacaaaaacataatggattcaaatactgtgtc...  EPI_ISL_245748

          Host_Type
0      other_mammal
1      other_mammal
2      other_mammal
3      other_mammal
4      other_mammal
...             ...
27011  other_mammal
27012  other_mammal
27013  other_mammal
27014  other_mammal
27015  other_mammal

[27016 rows x 12 columns]
                                                  Header Isolate_Id_x  \
4      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...         R313
12     EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...         R318
21     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|P...           18
26     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...        17671
35     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...          113
...                                                  ...          ...
26978  EPI_ISL_14761785|A/swine/Italy/23/2017|A_/_H1N...           23
26988  EPI_ISL_245726|A/swine/Germany/R1696/2014|A_/_...        R1696
26996  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...         R309
27004  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...       AR1026
27012  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...         R312

                             Isolate_Name_x Subtype_x Segment  \
4                 A/swine/Germany/R313/2015      H1N2      PA
12                A/swine/Germany/R318/2015      H1N2      PA
21                    A/swine/Italy/18/2000      H1N2      PA
26        A/swine/Czech_Republic/17671/2023      H1N2      PA
35     A/swine/Nordrhein-Westfalen/113/2024      H1N2      PA
...                                     ...       ...     ...
26978                 A/swine/Italy/23/2017      H1N1      PA
26988            A/swine/Germany/R1696/2014      H1N1      PA
26996             A/swine/Germany/R309/2015      H1N2      PA
27004           A/swine/Germany/AR1026/2016      H1N1      PA
27012             A/swine/Germany/R312/2015      H1N1      PA

                Location_x         Geo_Location Date Collected Species  \
4                  Germany              Germany           2014   swine
12                 Germany              Germany           2014   swine
21                   Italy                Italy     2000-01-03   swine
26          Czech_Republic       Czech_Republic     2023-11-13   swine
35     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20   swine
...                    ...                  ...            ...     ...
26978                Italy                Italy     2017-10-24   swine
26988              Germany              Germany           2014   swine
26996              Germany              Germany           2014   swine
27004              Germany              Germany     2016-02-17   swine
27012              Germany              Germany           2014   swine

                                                Sequence  ... Patient_Status  \
4      cattcacatcttttcattcactggagaggagattgccaccaaagcg...  ...            NaN
12     aaatggccagtaggagtctatgggattcctttcgtcagtccgaaag...  ...            NaN
21     tgattcaaaatggaagactttgtgcgacaatgcttcaatccaatga...  ...            NaN
26     tgatccaaaatggaagactttgtgcgacaatgcttcaatccaatga...  ...            NaN
35     atggaagactttgtgcgacaatgcttcaacccaatgattgtcgagc...  ...            NaN
...                                                  ...  ...            ...
26978  atggaagactttgtgcgacaatgcttcaatccaatgatcgttgagc...  ...            NaN
26988  atggaagacttcgtgcgacagtgcttcaatccaatgatcgtcgagc...  ...            NaN
26996  atggaagactttgtgcgacaatgcttcaacccaatggtcgtcgagc...  ...            NaN
27004  atggaagactttgtgcgacaatgcttcaatccaatggtcgtcgagc...  ...            NaN
27012  atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  ...            NaN

      Zip_Code Outbreak Pathogen_Test_Info Is_Vaccinated  \
4          NaN      NaN                NaN           NaN
12         NaN      NaN                NaN           NaN
21         NaN      NaN                NaN           0.0
26         NaN      NaN                NaN           NaN
35         NaN      NaN                NaN           NaN
...        ...      ...                ...           ...
26978      NaN      NaN                NaN           NaN
26988      NaN      NaN                NaN           NaN
26996      NaN      NaN                NaN           NaN
27004      NaN      NaN                NaN           NaN
27012      NaN      NaN                NaN           NaN

      Human_Specimen_Source Animal_Specimen_Source Animal_Health_Status  \
4                       NaN                    NaN                  NaN
12                      NaN                    NaN                  NaN
21                      NaN                    NaN                  NaN
26                      NaN             Nasal swab                  NaN
35                      NaN                    NaN                  NaN
...                     ...                    ...                  ...
26978                   NaN                    NaN                  NaN
26988                   NaN                    NaN                  NaN
26996                   NaN                    NaN                  NaN
27004                   NaN    Oro-pharyngeal swab                 Sick
27012                   NaN                    NaN                  NaN

      Domestic_Status PMID
4                 NaN  NaN
12                NaN  NaN
21                NaN  NaN
26           Domestic  NaN
35                NaN  NaN
...               ...  ...
26978             NaN  NaN
26988             NaN  NaN
26996             NaN  NaN
27004        Domestic  NaN
27012             NaN  NaN

[3377 rows x 65 columns]

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\3471010411.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name

                                                  Header Isolate_Id_x  \
7      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...         R313
15     EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...         R318
20     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|N...           18
31     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...        17671
33     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...          113
...                                                  ...          ...
26979  EPI_ISL_14761785|A/swine/Italy/23/2017|A_/_H1N...           23
26991  EPI_ISL_245726|A/swine/Germany/R1696/2014|A_/_...        R1696
26999  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...         R309
27007  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...       AR1026
27015  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...         R312

                             Isolate_Name_x Subtype_x Segment  \
7                 A/swine/Germany/R313/2015      H1N2      NS
15                A/swine/Germany/R318/2015      H1N2      NS
20                    A/swine/Italy/18/2000      H1N2      NS
31        A/swine/Czech_Republic/17671/2023      H1N2      NS
33     A/swine/Nordrhein-Westfalen/113/2024      H1N2      NS
...                                     ...       ...     ...
26979                 A/swine/Italy/23/2017      H1N1      NS
26991            A/swine/Germany/R1696/2014      H1N1      NS
26999             A/swine/Germany/R309/2015      H1N2      NS
27007           A/swine/Germany/AR1026/2016      H1N1      NS
27015             A/swine/Germany/R312/2015      H1N1      NS

                Location_x         Geo_Location Date Collected Species  \
7                  Germany              Germany           2014   swine
15                 Germany              Germany           2014   swine
20                   Italy                Italy     2000-01-03   swine
31          Czech_Republic       Czech_Republic     2023-11-13   swine
33     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20   swine
...                    ...                  ...            ...     ...
26979                Italy                Italy     2017-10-24   swine
26991              Germany              Germany           2014   swine
26999              Germany              Germany           2014   swine
27007              Germany              Germany     2016-02-17   swine
27015              Germany              Germany           2014   swine

                                                Sequence  ... Patient_Status  \
7      atggactccaacaccatgtcaagctttcaggtagactgtttccttt...  ...            NaN
15     agcaaaagcagggtgacaaaaacataatggactccaacaccatgtc...  ...            NaN
20     acaaaaacataatggattcaaacactgtgtcaagctttcaggtaga...  ...            NaN
31     acaaagacataatggattcaaacactgtgtcaagcttccaggtaga...  ...            NaN
33     atggattcaaacactgtttcgagcttccaggtagattgctttcttt...  ...            NaN
...                                                  ...  ...            ...
26979  atggattcaaacactgtgtcaagctttcaggtagactgctttcttt...  ...            NaN
26991  agcaaaagcagggtgacaaaacataatggattcaaacactgtgtca...  ...            NaN
26999  atggattcaaacactgtgtcaagctttcaggtagattgctttcttt...  ...            NaN
27007  atggattcaaacactgtgtcaagctttcaggtagattgctttcttt...  ...            NaN
27015  agcaaaagcagggtgacaaaaacataatggattcaaatactgtgtc...  ...            NaN

      Zip_Code Outbreak Pathogen_Test_Info Is_Vaccinated  \
7          NaN      NaN                NaN           NaN
15         NaN      NaN                NaN           NaN
20         NaN      NaN                NaN           0.0
31         NaN      NaN                NaN           NaN
33         NaN      NaN                NaN           NaN
...        ...      ...                ...           ...
26979      NaN      NaN                NaN           NaN
26991      NaN      NaN                NaN           NaN
26999      NaN      NaN                NaN           NaN
27007      NaN      NaN                NaN           NaN
27015      NaN      NaN                NaN           NaN

      Human_Specimen_Source Animal_Specimen_Source Animal_Health_Status  \
7                       NaN                    NaN                  NaN
15                      NaN                    NaN                  NaN
20                      NaN                    NaN                  NaN
31                      NaN             Nasal swab                  NaN
33                      NaN                    NaN                  NaN
...                     ...                    ...                  ...
26979                   NaN                    NaN                  NaN
26991                   NaN                    NaN                  NaN
26999                   NaN                    NaN                  NaN
27007                   NaN    Oro-pharyngeal swab                 Sick
27015                   NaN                    NaN                  NaN

      Domestic_Status PMID
7                 NaN  NaN
15                NaN  NaN
20                NaN  NaN
31           Domestic  NaN
33                NaN  NaN
...               ...  ...
26979             NaN  NaN
26991             NaN  NaN
26999             NaN  NaN
27007        Domestic  NaN
27015             NaN  NaN

[3377 rows x 65 columns]

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\3471010411.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name

                                                  Header Isolate_Id_x  \
1      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...         R313
9      EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...         R318
17     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|N...           18
29     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...        17671
38     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...          113
...                                                  ...          ...
26981  EPI_ISL_14761785|A/swine/Italy/23/2017|A_/_H1N...           23
26985  EPI_ISL_245726|A/swine/Germany/R1696/2014|A_/_...        R1696
26993  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...         R309
27001  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...       AR1026
27009  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...         R312

                             Isolate_Name_x Subtype_x Segment  \
1                 A/swine/Germany/R313/2015      H1N2      NA
9                 A/swine/Germany/R318/2015      H1N2      NA
17                    A/swine/Italy/18/2000      H1N2      NA
29        A/swine/Czech_Republic/17671/2023      H1N2      NA
38     A/swine/Nordrhein-Westfalen/113/2024      H1N2      NA
...                                     ...       ...     ...
26981                 A/swine/Italy/23/2017      H1N1      NA
26985            A/swine/Germany/R1696/2014      H1N1      NA
26993             A/swine/Germany/R309/2015      H1N2      NA
27001           A/swine/Germany/AR1026/2016      H1N1      NA
27009             A/swine/Germany/R312/2015      H1N1      NA

                Location_x         Geo_Location Date Collected Species  \
1                  Germany              Germany           2014   swine
9                  Germany              Germany           2014   swine
17                   Italy                Italy     2000-01-03   swine
29          Czech_Republic       Czech_Republic     2023-11-13   swine
38     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20   swine
...                    ...                  ...            ...     ...
26981                Italy                Italy     2017-10-24   swine
26985              Germany              Germany           2014   swine
26993              Germany              Germany           2014   swine
27001              Germany              Germany     2016-02-17   swine
27009              Germany              Germany           2014   swine

                                                Sequence  ... Patient_Status  \
1      atgaatccaaatcaaaagataataacgattggttctgtatccctaa...  ...            NaN
9      atgaatccaaatcaaaagataataacgattggttctatatccctaa...  ...            NaN
17     atgaatccaaatcagaagataataacaattggctctgtttctctct...  ...            NaN
29     aaaaatgaatccaaatcaaaggataataacgattggttctgtctcc...  ...            NaN
38     agtgaagatgaatccaagtcaaaagataataacgattggttctgtc...  ...            NaN
...                                                  ...  ...            ...
26981  atgaatccaaatcagaagataataattattagttcaatctgtatga...  ...            NaN
26985  atgaatccaaatcaaaagataataaccattggttcgatctgtatga...  ...            NaN
26993  atgaatccaaatcaaaagataataacaattggttctgtttctctca...  ...            NaN
27001  atgaatccaaatcaaaagataataatcattagctcgatctgcatga...  ...            NaN
27009  atgaatccaaatcagaagataataatcattagctcgatttgtatga...  ...            NaN

      Zip_Code Outbreak Pathogen_Test_Info Is_Vaccinated  \
1          NaN      NaN                NaN           NaN
9          NaN      NaN                NaN           NaN
17         NaN      NaN                NaN           0.0
29         NaN      NaN                NaN           NaN
38         NaN      NaN                NaN           NaN
...        ...      ...                ...           ...
26981      NaN      NaN                NaN           NaN
26985      NaN      NaN                NaN           NaN
26993      NaN      NaN                NaN           NaN
27001      NaN      NaN                NaN           NaN
27009      NaN      NaN                NaN           NaN

      Human_Specimen_Source Animal_Specimen_Source Animal_Health_Status  \
1                       NaN                    NaN                  NaN
9                       NaN                    NaN                  NaN
17                      NaN                    NaN                  NaN
29                      NaN             Nasal swab                  NaN
38                      NaN                    NaN                  NaN
...                     ...                    ...                  ...
26981                   NaN                    NaN                  NaN
26985                   NaN                    NaN                  NaN
26993                   NaN                    NaN                  NaN
27001                   NaN    Oro-pharyngeal swab                 Sick
27009                   NaN                    NaN                  NaN

      Domestic_Status PMID
1                 NaN  NaN
9                 NaN  NaN
17                NaN  NaN
29           Domestic  NaN
38                NaN  NaN
...               ...  ...
26981             NaN  NaN
26985             NaN  NaN
26993             NaN  NaN
27001        Domestic  NaN
27009             NaN  NaN

[3377 rows x 65 columns]

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\3471010411.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name

                                                  Header Isolate_Id_x  \
6      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...         R313
14     EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...         R318
18     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|M...           18
30     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...        17671
34     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...          113
...                                                  ...          ...
26982  EPI_ISL_14761785|A/swine/Italy/23/2017|A_/_H1N...           23
26990  EPI_ISL_245726|A/swine/Germany/R1696/2014|A_/_...        R1696
26998  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...         R309
27006  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...       AR1026
27014  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...         R312

                             Isolate_Name_x Subtype_x Segment  \
6                 A/swine/Germany/R313/2015      H1N2      MP
14                A/swine/Germany/R318/2015      H1N2      MP
18                    A/swine/Italy/18/2000      H1N2      MP
30        A/swine/Czech_Republic/17671/2023      H1N2      MP
34     A/swine/Nordrhein-Westfalen/113/2024      H1N2      MP
...                                     ...       ...     ...
26982                 A/swine/Italy/23/2017      H1N1      MP
26990            A/swine/Germany/R1696/2014      H1N1      MP
26998             A/swine/Germany/R309/2015      H1N2      MP
27006           A/swine/Germany/AR1026/2016      H1N1      MP
27014             A/swine/Germany/R312/2015      H1N1      MP

                Location_x         Geo_Location Date Collected Species  \
6                  Germany              Germany           2014   swine
14                 Germany              Germany           2014   swine
18                   Italy                Italy     2000-01-03   swine
30          Czech_Republic       Czech_Republic     2023-11-13   swine
34     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20   swine
...                    ...                  ...            ...     ...
26982                Italy                Italy     2017-10-24   swine
26990              Germany              Germany           2014   swine
26998              Germany              Germany           2014   swine
27006              Germany              Germany     2016-02-17   swine
27014              Germany              Germany           2014   swine

                                                Sequence  ... Patient_Status  \
6      atgagtcttctaaccgaggtcgaaacgtacgttctttctatcatcc...  ...            NaN
14     atgagtcttctaaccgaggtcgaaacgtacgttctttctatcatcc...  ...            NaN
18     cctcaaagccgagatcgcgcagagactggaaggtgtctttgcaggg...  ...            NaN
30     atatttaaagatgagtcttctaacagaggtcgaaacgtacgttctt...  ...            NaN
34     tagatatttaaagatgagtcttctaaccgaggtcgaaacgtatgtt...  ...            NaN
...                                                  ...  ...            ...
26982  atgagtcttctaaccgaggtcgaaacgtacgttctttctatcatcc...  ...            NaN
26990  agcaaaagcaggtagatattaaagatgagtcttctaaccgaggtcg...  ...            NaN
26998  agcaaaagcaggtagatatttaaagatgagtcttctaaccgaggtc...  ...            NaN
27006  agcaaaagcaggtagatatttaaagatgagtcttctaaccgaggtc...  ...            NaN
27014  atgagtcttctaactgaggtcgaaacgtacgtcctttctatcatcc...  ...            NaN

      Zip_Code Outbreak Pathogen_Test_Info Is_Vaccinated  \
6          NaN      NaN                NaN           NaN
14         NaN      NaN                NaN           NaN
18         NaN      NaN                NaN           0.0
30         NaN      NaN                NaN           NaN
34         NaN      NaN                NaN           NaN
...        ...      ...                ...           ...
26982      NaN      NaN                NaN           NaN
26990      NaN      NaN                NaN           NaN
26998      NaN      NaN                NaN           NaN
27006      NaN      NaN                NaN           NaN
27014      NaN      NaN                NaN           NaN

      Human_Specimen_Source Animal_Specimen_Source Animal_Health_Status  \
6                       NaN                    NaN                  NaN
14                      NaN                    NaN                  NaN
18                      NaN                    NaN                  NaN
30                      NaN             Nasal swab                  NaN
34                      NaN                    NaN                  NaN
...                     ...                    ...                  ...
26982                   NaN                    NaN                  NaN
26990                   NaN                    NaN                  NaN
26998                   NaN                    NaN                  NaN
27006                   NaN    Oro-pharyngeal swab                 Sick
27014                   NaN                    NaN                  NaN

      Domestic_Status PMID
6                 NaN  NaN
14                NaN  NaN
18                NaN  NaN
30           Domestic  NaN
34                NaN  NaN
...               ...  ...
26982             NaN  NaN
26990             NaN  NaN
26998             NaN  NaN
27006        Domestic  NaN
27014             NaN  NaN

[3377 rows x 65 columns]

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\3471010411.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name

                                                  Header Isolate_Id_x  \
0      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...         R313
8      EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...         R318
16     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|H...           18
27     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...        17671
39     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...          113
...                                                  ...          ...
26983  EPI_ISL_14761785|A/swine/Italy/23/2017|A_/_H1N...           23
26984  EPI_ISL_245726|A/swine/Germany/R1696/2014|A_/_...        R1696
26992  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...         R309
27000  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...       AR1026
27008  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...         R312

                             Isolate_Name_x Subtype_x Segment  \
0                 A/swine/Germany/R313/2015      H1N2      HA
8                 A/swine/Germany/R318/2015      H1N2      HA
16                    A/swine/Italy/18/2000      H1N2      HA
27        A/swine/Czech_Republic/17671/2023      H1N2      HA
39     A/swine/Nordrhein-Westfalen/113/2024      H1N2      HA
...                                     ...       ...     ...
26983                 A/swine/Italy/23/2017      H1N1      HA
26984            A/swine/Germany/R1696/2014      H1N1      HA
26992             A/swine/Germany/R309/2015      H1N2      HA
27000           A/swine/Germany/AR1026/2016      H1N1      HA
27008             A/swine/Germany/R312/2015      H1N1      HA

                Location_x         Geo_Location Date Collected Species  \
0                  Germany              Germany           2014   swine
8                  Germany              Germany           2014   swine
16                   Italy                Italy     2000-01-03   swine
27          Czech_Republic       Czech_Republic     2023-11-13   swine
39     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20   swine
...                    ...                  ...            ...     ...
26983                Italy                Italy     2017-10-24   swine
26984              Germany              Germany           2014   swine
26992              Germany              Germany           2014   swine
27000              Germany              Germany     2016-02-17   swine
27008              Germany              Germany           2014   swine

                                                Sequence  ... Patient_Status  \
0      atggaaacaagactgtttgtattatttagtgtattcactgcactaa...  ...            NaN
8      atggaagcaaaactgtttgtattgttcagtgtattcactgcactaa...  ...            NaN
16     atgagagctaagctactaatcctgttgtgtgcgctttcagctacag...  ...            NaN
27     ataattaaatcaaccaagatgaaagcaaaactgtttgtattattct...  ...            NaN
39     ggtaaatggaaacaaccaaaatgaaagctaaactgttaatcctgtt...  ...            NaN
...                                                  ...  ...            ...
26983  atgaaagcaaaattatttgtattattctgtgcgtttactgcactga...  ...            NaN
26984  atgaaagcaagactgtttgtattattctgtacactcaaatcactga...  ...            NaN
26992  atgagaaccaaattattaatcctgttgtatgtgctatcagctgcag...  ...            NaN
27000  agcaaaagcaggggataattaaatcaaccaaaatggaagtaaaact...  ...            NaN
27008  atggaagcaaaactgtttgtactattctgtgcattcactgcactga...  ...            NaN

      Zip_Code Outbreak Pathogen_Test_Info Is_Vaccinated  \
0          NaN      NaN                NaN           NaN
8          NaN      NaN                NaN           NaN
16         NaN      NaN                NaN           0.0
27         NaN      NaN                NaN           NaN
39         NaN      NaN                NaN           NaN
...        ...      ...                ...           ...
26983      NaN      NaN                NaN           NaN
26984      NaN      NaN                NaN           NaN
26992      NaN      NaN                NaN           NaN
27000      NaN      NaN                NaN           NaN
27008      NaN      NaN                NaN           NaN

      Human_Specimen_Source Animal_Specimen_Source Animal_Health_Status  \
0                       NaN                    NaN                  NaN
8                       NaN                    NaN                  NaN
16                      NaN                    NaN                  NaN
27                      NaN             Nasal swab                  NaN
39                      NaN                    NaN                  NaN
...                     ...                    ...                  ...
26983                   NaN                    NaN                  NaN
26984                   NaN                    NaN                  NaN
26992                   NaN                    NaN                  NaN
27000                   NaN    Oro-pharyngeal swab                 Sick
27008                   NaN                    NaN                  NaN

      Domestic_Status PMID
0                 NaN  NaN
8                 NaN  NaN
16                NaN  NaN
27           Domestic  NaN
39                NaN  NaN
...               ...  ...
26983             NaN  NaN
26984             NaN  NaN
26992             NaN  NaN
27000        Domestic  NaN
27008             NaN  NaN

[3377 rows x 65 columns]

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\3471010411.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name

                                                  Header Isolate_Id_x  \
5      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...         R313
13     EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...         R318
19     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|N...           18
28     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...        17671
32     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...          113
...                                                  ...          ...
26980  EPI_ISL_14761785|A/swine/Italy/23/2017|A_/_H1N...           23
26989  EPI_ISL_245726|A/swine/Germany/R1696/2014|A_/_...        R1696
26997  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...         R309
27005  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...       AR1026
27013  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...         R312

                             Isolate_Name_x Subtype_x Segment  \
5                 A/swine/Germany/R313/2015      H1N2      NP
13                A/swine/Germany/R318/2015      H1N2      NP
19                    A/swine/Italy/18/2000      H1N2      NP
28        A/swine/Czech_Republic/17671/2023      H1N2      NP
32     A/swine/Nordrhein-Westfalen/113/2024      H1N2      NP
...                                     ...       ...     ...
26980                 A/swine/Italy/23/2017      H1N1      NP
26989            A/swine/Germany/R1696/2014      H1N1      NP
26997             A/swine/Germany/R309/2015      H1N2      NP
27005           A/swine/Germany/AR1026/2016      H1N1      NP
27013             A/swine/Germany/R312/2015      H1N1      NP

                Location_x         Geo_Location Date Collected Species  \
5                  Germany              Germany           2014   swine
13                 Germany              Germany           2014   swine
19                   Italy                Italy     2000-01-03   swine
28          Czech_Republic       Czech_Republic     2023-11-13   swine
32     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20   swine
...                    ...                  ...            ...     ...
26980                Italy                Italy     2017-10-24   swine
26989              Germany              Germany           2014   swine
26997              Germany              Germany           2014   swine
27005              Germany              Germany     2016-02-17   swine
27013              Germany              Germany           2014   swine

                                                Sequence  ... Patient_Status  \
5      actcaatgagtgacatcgaagccatggcgtctcaaggcaccaaacg...  ...            NaN
13     atcactcaatgagtgacatcgaagccatggcgtctcaaggcaccaa...  ...            NaN
19     gataatcactcactgagtgacattcacatcatggcgtctcaaggca...  ...            NaN
28     gataatcactcaatgagtgacatcgaaaccatggcgtctcaaggca...  ...            NaN
32     gtagataatcactcactgagtgacatccatatcatggcgtctcaag...  ...            NaN
...                                                  ...  ...            ...
26980  atggcgtctcaaggcaccaaacgatcttatgaacagatggaaactg...  ...            NaN
26989  tgagtgacattcatatcatggcgtctcaaggcaccaaacgatctta...  ...            NaN
26997  ctgagtgacatttacgccatggcgtctcaaggcaccaaacgatctt...  ...            NaN
27005  tgagtgacatttacaccatggcgtctcaaggcaccaaacgatctta...  ...            NaN
27013  ctcactgagtgacatttaagccatggtgtctcaaggcaccaaacga...  ...            NaN

      Zip_Code Outbreak Pathogen_Test_Info Is_Vaccinated  \
5          NaN      NaN                NaN           NaN
13         NaN      NaN                NaN           NaN
19         NaN      NaN                NaN           0.0
28         NaN      NaN                NaN           NaN
32         NaN      NaN                NaN           NaN
...        ...      ...                ...           ...
26980      NaN      NaN                NaN           NaN
26989      NaN      NaN                NaN           NaN
26997      NaN      NaN                NaN           NaN
27005      NaN      NaN                NaN           NaN
27013      NaN      NaN                NaN           NaN

      Human_Specimen_Source Animal_Specimen_Source Animal_Health_Status  \
5                       NaN                    NaN                  NaN
13                      NaN                    NaN                  NaN
19                      NaN                    NaN                  NaN
28                      NaN             Nasal swab                  NaN
32                      NaN                    NaN                  NaN
...                     ...                    ...                  ...
26980                   NaN                    NaN                  NaN
26989                   NaN                    NaN                  NaN
26997                   NaN                    NaN                  NaN
27005                   NaN    Oro-pharyngeal swab                 Sick
27013                   NaN                    NaN                  NaN

      Domestic_Status PMID
5                 NaN  NaN
13                NaN  NaN
19                NaN  NaN
28           Domestic  NaN
32                NaN  NaN
...               ...  ...
26980             NaN  NaN
26989             NaN  NaN
26997             NaN  NaN
27005        Domestic  NaN
27013             NaN  NaN

[3377 rows x 65 columns]

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\3471010411.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name

                                                  Header Isolate_Id_x  \
2      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...         R313
10     EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...         R318
23     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|P...           18
24     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...        17671
36     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...          113
...                                                  ...          ...
26976  EPI_ISL_14761785|A/swine/Italy/23/2017|A_/_H1N...           23
26986  EPI_ISL_245726|A/swine/Germany/R1696/2014|A_/_...        R1696
26994  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...         R309
27002  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...       AR1026
27010  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...         R312

                             Isolate_Name_x Subtype_x Segment  \
2                 A/swine/Germany/R313/2015      H1N2     PB2
10                A/swine/Germany/R318/2015      H1N2     PB2
23                    A/swine/Italy/18/2000      H1N2     PB2
24        A/swine/Czech_Republic/17671/2023      H1N2     PB2
36     A/swine/Nordrhein-Westfalen/113/2024      H1N2     PB2
...                                     ...       ...     ...
26976                 A/swine/Italy/23/2017      H1N1     PB2
26986            A/swine/Germany/R1696/2014      H1N1     PB2
26994             A/swine/Germany/R309/2015      H1N2     PB2
27002           A/swine/Germany/AR1026/2016      H1N1     PB2
27010             A/swine/Germany/R312/2015      H1N1     PB2

                Location_x         Geo_Location Date Collected Species  \
2                  Germany              Germany           2014   swine
10                 Germany              Germany           2014   swine
23                   Italy                Italy     2000-01-03   swine
24          Czech_Republic       Czech_Republic     2023-11-13   swine
36     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20   swine
...                    ...                  ...            ...     ...
26976                Italy                Italy     2017-10-24   swine
26986              Germany              Germany           2014   swine
26994              Germany              Germany           2014   swine
27002              Germany              Germany     2016-02-17   swine
27010              Germany              Germany           2014   swine

                                                Sequence  ... Patient_Status  \
2      atggagagaataaaagaactgagagatctaatgtcgcagtcccgca...  ...            NaN
10     atggagagaataaaagaactgagagatctaatgtcgcagtcccgca...  ...            NaN
23     atggaaagaataaaagaattaagagatctaatgtcgcagtctcgca...  ...            NaN
24     aaatatattcaatatggagagaataaaagaactgagagatctaatg...  ...            NaN
36     tcaaatatattcaacatggagagaataaaagaattaagagatctaa...  ...            NaN
...                                                  ...  ...            ...
26976  atggagagaataaaagaattaagagatctgatgtcgcagtctcgca...  ...            NaN
26986  gctatattaaggaaagcaaccagaagactaattcagctgatagtaa...  ...            NaN
26994  atggagagaataaaagaattaagagatctaatgtcgcagtctcgca...  ...            NaN
27002  atggagagaataaaagaattaagagatctaatgtcgcagtctcgca...  ...            NaN
27010  atggagagaataaaagaattaagagatctgatgtcgcagtctcgca...  ...            NaN

      Zip_Code Outbreak Pathogen_Test_Info Is_Vaccinated  \
2          NaN      NaN                NaN           NaN
10         NaN      NaN                NaN           NaN
23         NaN      NaN                NaN           0.0
24         NaN      NaN                NaN           NaN
36         NaN      NaN                NaN           NaN
...        ...      ...                ...           ...
26976      NaN      NaN                NaN           NaN
26986      NaN      NaN                NaN           NaN
26994      NaN      NaN                NaN           NaN
27002      NaN      NaN                NaN           NaN
27010      NaN      NaN                NaN           NaN

      Human_Specimen_Source Animal_Specimen_Source Animal_Health_Status  \
2                       NaN                    NaN                  NaN
10                      NaN                    NaN                  NaN
23                      NaN                    NaN                  NaN
24                      NaN             Nasal swab                  NaN
36                      NaN                    NaN                  NaN
...                     ...                    ...                  ...
26976                   NaN                    NaN                  NaN
26986                   NaN                    NaN                  NaN
26994                   NaN                    NaN                  NaN
27002                   NaN    Oro-pharyngeal swab                 Sick
27010                   NaN                    NaN                  NaN

      Domestic_Status PMID
2                 NaN  NaN
10                NaN  NaN
23                NaN  NaN
24           Domestic  NaN
36                NaN  NaN
...               ...  ...
26976             NaN  NaN
26986             NaN  NaN
26994             NaN  NaN
27002        Domestic  NaN
27010             NaN  NaN

[3377 rows x 65 columns]

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\3471010411.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name

                                                  Header Isolate_Id_x  \
3      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...         R313
11     EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...         R318
22     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|P...           18
25     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...        17671
37     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...          113
...                                                  ...          ...
26977  EPI_ISL_14761785|A/swine/Italy/23/2017|A_/_H1N...           23
26987  EPI_ISL_245726|A/swine/Germany/R1696/2014|A_/_...        R1696
26995  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...         R309
27003  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...       AR1026
27011  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...         R312

                             Isolate_Name_x Subtype_x Segment  \
3                 A/swine/Germany/R313/2015      H1N2     PB1
11                A/swine/Germany/R318/2015      H1N2     PB1
22                    A/swine/Italy/18/2000      H1N2     PB1
25        A/swine/Czech_Republic/17671/2023      H1N2     PB1
37     A/swine/Nordrhein-Westfalen/113/2024      H1N2     PB1
...                                     ...       ...     ...
26977                 A/swine/Italy/23/2017      H1N1     PB1
26987            A/swine/Germany/R1696/2014      H1N1     PB1
26995             A/swine/Germany/R309/2015      H1N2     PB1
27003           A/swine/Germany/AR1026/2016      H1N1     PB1
27011             A/swine/Germany/R312/2015      H1N1     PB1

                Location_x         Geo_Location Date Collected Species  \
3                  Germany              Germany           2014   swine
11                 Germany              Germany           2014   swine
22                   Italy                Italy     2000-01-03   swine
25          Czech_Republic       Czech_Republic     2023-11-13   swine
37     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20   swine
...                    ...                  ...            ...     ...
26977                Italy                Italy     2017-10-24   swine
26987              Germany              Germany           2014   swine
26995              Germany              Germany           2014   swine
27003              Germany              Germany     2016-02-17   swine
27011              Germany              Germany           2014   swine

                                                Sequence  ... Patient_Status  \
3      atggatgtcaatccgactctacttttcctaaaaattccagcgcaaa...  ...            NaN
11     atggatgtcaatccgactctacttttcttaaaaattccagcgcaaa...  ...            NaN
22     accatttgaatggatgtcaacccgactctacttttcttgaaagtgc...  ...            NaN
25     aaccatttgaatggatgtcaatccgactctacttttcctaaaaatt...  ...            NaN
37     cccttatactggagatcccccatatagccatggaacagggacagga...  ...            NaN
...                                                  ...  ...            ...
26977  atggatgtcaacccgactctacttttcttaaaagtgccagcacaga...  ...            NaN
26987  atggatgtcaacccgattctacttttcttgaaagtgccagcacaaa...  ...            NaN
26995  atggatgtcaacccgactctacttttcttaaaggtgccagcacaaa...  ...            NaN
27003  atggatgtcaacccgactctacttttcttaaaggtgccagcacaaa...  ...            NaN
27011  atggatgtcaacccgactctacttttcttaaaagtgccagcacaaa...  ...            NaN

      Zip_Code Outbreak Pathogen_Test_Info Is_Vaccinated  \
3          NaN      NaN                NaN           NaN
11         NaN      NaN                NaN           NaN
22         NaN      NaN                NaN           0.0
25         NaN      NaN                NaN           NaN
37         NaN      NaN                NaN           NaN
...        ...      ...                ...           ...
26977      NaN      NaN                NaN           NaN
26987      NaN      NaN                NaN           NaN
26995      NaN      NaN                NaN           NaN
27003      NaN      NaN                NaN           NaN
27011      NaN      NaN                NaN           NaN

      Human_Specimen_Source Animal_Specimen_Source Animal_Health_Status  \
3                       NaN                    NaN                  NaN
11                      NaN                    NaN                  NaN
22                      NaN                    NaN                  NaN
25                      NaN             Nasal swab                  NaN
37                      NaN                    NaN                  NaN
...                     ...                    ...                  ...
26977                   NaN                    NaN                  NaN
26987                   NaN                    NaN                  NaN
26995                   NaN                    NaN                  NaN
27003                   NaN    Oro-pharyngeal swab                 Sick
27011                   NaN                    NaN                  NaN

      Domestic_Status PMID
3                 NaN  NaN
11                NaN  NaN
22                NaN  NaN
25           Domestic  NaN
37                NaN  NaN
...               ...  ...
26977             NaN  NaN
26987             NaN  NaN
26995             NaN  NaN
27003        Domestic  NaN
27011             NaN  NaN

[3377 rows x 65 columns]

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\3471010411.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fasta_seg["New_Name"] = new_name

In [66]:
# Find animals to sort, if needed

os.chdir(references)

# Flatten unique_animals
every_unique_animal = []
for l in unique_animals_all:
    for animal in l:
        every_unique_animal.append(animal)

# Rename host type

unique_animals_set = list(set(every_unique_animal))
animals_df = pd.DataFrame(columns=["wild_avian", "domestic_avian", "cattle", "feline", "other_mammal", "human", "other"])
animals_df["other"] = unique_animals_set # to sort

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

print(common_animals)
print(len(common_animals))

different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

print(animals_ref)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer
else:
    number_of_times_to_add_nan = len(different_animals) - len(animals_df)
    nan_row = pd.DataFrame([[np.nan] * len(animals_df.columns)], columns=animals_df.columns)
    for i in range(number_of_times_to_add_nan):
        animals_df = pd.concat([animals_df, nan_row], ignore_index=True)

animals_df["new"] = (different_animals)

print(animals_df)

os.chdir(references)
animals_df.to_csv("animals_ref_to_sort.csv")

['swine', 'sus_scrofa', 'verona', 'sw', 'poland', 'wild_boar']
6
[]
                    wild_avian domestic_avian               cattle  \
0             great_horned_owl       pheasant            dairy_cow
1                 common_raven         turkey               cattle
2                cooper's_hawk        chicken  cattle milk product
3                 coopers_hawk          goose          bovine_milk
4                      peafowl    guinea_fowl              bovine
...                        ...            ...                  ...
1136              common_goose            NaN                  NaN
1137  great_black-backed_gull_            NaN                  NaN
1138              bewicks_swan            NaN                  NaN
1139           ornamental_duck            NaN                  NaN
1140                  peregino            NaN                  NaN

            feline   other_mammal       human         other      pet_food
0              cat     deer mouse  washington         mixed      pet food
1     domestic_cat    house_mouse      nevada   environment  raw pet food
2        feral_cat          skunk     wyoming  multispecies  raw_pet_food
3           feline  striped_skunk  california       unknown      pet_food
4     domestic-cat     norway rat    michigan             '           NaN
...            ...            ...         ...           ...           ...
1136           NaN            NaN         NaN           NaN           NaN
1137           NaN            NaN         NaN           NaN           NaN
1138           NaN            NaN         NaN           NaN           NaN
1139           NaN            NaN         NaN           NaN           NaN
1140           NaN            NaN         NaN           NaN           NaN

[1141 rows x 8 columns]
                    wild_avian domestic_avian               cattle  \
0             great_horned_owl       pheasant            dairy_cow
1                 common_raven         turkey               cattle
2                cooper's_hawk        chicken  cattle milk product
3                 coopers_hawk          goose          bovine_milk
4                      peafowl    guinea_fowl              bovine
...                        ...            ...                  ...
1136              common_goose            NaN                  NaN
1137  great_black-backed_gull_            NaN                  NaN
1138              bewicks_swan            NaN                  NaN
1139           ornamental_duck            NaN                  NaN
1140                  peregino            NaN                  NaN

            feline   other_mammal       human         other      pet_food  new
0              cat     deer mouse  washington         mixed      pet food  NaN
1     domestic_cat    house_mouse      nevada   environment  raw pet food  NaN
2        feral_cat          skunk     wyoming  multispecies  raw_pet_food  NaN
3           feline  striped_skunk  california       unknown      pet_food  NaN
4     domestic-cat     norway rat    michigan             '           NaN  NaN
...            ...            ...         ...           ...           ...  ...
1136           NaN            NaN         NaN           NaN           NaN  NaN
1137           NaN            NaN         NaN           NaN           NaN  NaN
1138           NaN            NaN         NaN           NaN           NaN  NaN
1139           NaN            NaN         NaN           NaN           NaN  NaN
1140           NaN            NaN         NaN           NaN           NaN  NaN

[1141 rows x 9 columns]

In [67]:
# input("Check animal output.")

In [68]:
gisaid_fastas = []
for fasta in segment_fastas:
    if fasta["Segment"].values[0] == "HA":
        print("HA")
        for s in ["H1", "H3"]:
            m_g_s = fasta[fasta["Subtype_x"].str.contains(s)]
            m_g_s["Serotype"] = s
            if len(m_g_s) > 0:
                print(m_g_s["Subtype_x"])
                print(m_g_s)
                # m_g_s["New_Name"] = m_g_s["Header"] # .apply(lambda x: x.replace("other_mammal", "swine") if "other_mammal" in x else x)
                gisaid_fastas.append(m_g_s)
    elif fasta["Segment"].values[0] == "NA":
        print("NA")
        for se in ["N1", "N2"]:
            m_g_s = fasta[fasta["Subtype_x"].str.contains(se)]
            m_g_s["Serotype"] = se
            if len(m_g_s) > 0:
                # print(exp_df)
                # m_g_s["New_Name"] = m_g_s["Header"] # .apply(lambda x: x.replace("other_mammal", "swine") if "other_mammal" in x else x)
                gisaid_fastas.append(m_g_s)
    else:
        '''all other segments'''
        if len(fasta) > 0:
            fasta["Serotype"] = "None"
            # fasta["New_Name"] = fasta["Header"] # .apply(lambda x: x.replace("other_mammal", "swine") if "other_mammal" in x else x)
            gisaid_fastas.append(fasta)

print(gisaid_fastas[0]["New_Name"].values[0].split("|")[3:])

NA
HA
0        H1N2
8        H1N2
16       H1N2
27       H1N2
39       H1N2
         ...
26983    H1N1
26984    H1N1
26992    H1N2
27000    H1N1
27008    H1N1
Name: Subtype_x, Length: 2958, dtype: object
                                                  Header Isolate_Id_x  \
0      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...         R313
8      EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...         R318
16     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|H...           18
27     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...        17671
39     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...          113
...                                                  ...          ...
26983  EPI_ISL_14761785|A/swine/Italy/23/2017|A_/_H1N...           23
26984  EPI_ISL_245726|A/swine/Germany/R1696/2014|A_/_...        R1696
26992  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...         R309
27000  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...       AR1026
27008  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...         R312

                             Isolate_Name_x Subtype_x Segment  \
0                 A/swine/Germany/R313/2015      H1N2      HA
8                 A/swine/Germany/R318/2015      H1N2      HA
16                    A/swine/Italy/18/2000      H1N2      HA
27        A/swine/Czech_Republic/17671/2023      H1N2      HA
39     A/swine/Nordrhein-Westfalen/113/2024      H1N2      HA
...                                     ...       ...     ...
26983                 A/swine/Italy/23/2017      H1N1      HA
26984            A/swine/Germany/R1696/2014      H1N1      HA
26992             A/swine/Germany/R309/2015      H1N2      HA
27000           A/swine/Germany/AR1026/2016      H1N1      HA
27008             A/swine/Germany/R312/2015      H1N1      HA

                Location_x         Geo_Location Date Collected Species  \
0                  Germany              Germany           2014   swine
8                  Germany              Germany           2014   swine
16                   Italy                Italy     2000-01-03   swine
27          Czech_Republic       Czech_Republic     2023-11-13   swine
39     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20   swine
...                    ...                  ...            ...     ...
26983                Italy                Italy     2017-10-24   swine
26984              Germany              Germany           2014   swine
26992              Germany              Germany           2014   swine
27000              Germany              Germany     2016-02-17   swine
27008              Germany              Germany           2014   swine

                                                Sequence  ... Outbreak  \
0      atggaaacaagactgtttgtattatttagtgtattcactgcactaa...  ...      NaN
8      atggaagcaaaactgtttgtattgttcagtgtattcactgcactaa...  ...      NaN
16     atgagagctaagctactaatcctgttgtgtgcgctttcagctacag...  ...      NaN
27     ataattaaatcaaccaagatgaaagcaaaactgtttgtattattct...  ...      NaN
39     ggtaaatggaaacaaccaaaatgaaagctaaactgttaatcctgtt...  ...      NaN
...                                                  ...  ...      ...
26983  atgaaagcaaaattatttgtattattctgtgcgtttactgcactga...  ...      NaN
26984  atgaaagcaagactgtttgtattattctgtacactcaaatcactga...  ...      NaN
26992  atgagaaccaaattattaatcctgttgtatgtgctatcagctgcag...  ...      NaN
27000  agcaaaagcaggggataattaaatcaaccaaaatggaagtaaaact...  ...      NaN
27008  atggaagcaaaactgtttgtactattctgtgcattcactgcactga...  ...      NaN

      Pathogen_Test_Info Is_Vaccinated Human_Specimen_Source  \
0                    NaN           NaN                   NaN
8                    NaN           NaN                   NaN
16                   NaN           0.0                   NaN
27                   NaN           NaN                   NaN
39                   NaN           NaN                   NaN
...                  ...           ...                   ...
26983                NaN           NaN                   NaN
26984                NaN           NaN                   NaN
26992                NaN           NaN                   NaN
27000                NaN           NaN                   NaN
27008                NaN           NaN                   NaN

      Animal_Specimen_Source Animal_Health_Status Domestic_Status PMID  \
0                        NaN                  NaN             NaN  NaN
8                        NaN                  NaN             NaN  NaN
16                       NaN                  NaN             NaN  NaN
27                Nasal swab                  NaN        Domestic  NaN
39                       NaN                  NaN             NaN  NaN
...                      ...                  ...             ...  ...
26983                    NaN                  NaN             NaN  NaN
26984                    NaN                  NaN             NaN  NaN
26992                    NaN                  NaN             NaN  NaN
27000    Oro-pharyngeal swab                 Sick        Domestic  NaN
27008                    NaN                  NaN             NaN  NaN

                                                New_Name Serotype
0      >EPI_ISL_245764|A/swine/Germany/R313/2015|H1N2...       H1
8      >EPI_ISL_245771|A/swine/Germany/R318/2015|H1N2...       H1
16     >EPI_ISL_73783|A/swine/Italy/18/2000|H1N2|Ital...       H1
27     >EPI_ISL_18604439|A/swine/Czech_Republic/17671...       H1
39     >EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/...       H1
...                                                  ...      ...
26983  >EPI_ISL_14761785|A/swine/Italy/23/2017|H1N1|I...       H1
26984  >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...       H1
26992  >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...       H1
27000  >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...       H1
27008  >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...       H1

[2958 rows x 67 columns]
331      H3N2
338      H3N2
363      H3N2
371      H3N2
451      H3N2
         ...
26658    H3N2
26823    H3N2
26827    H3N2
26835    H3N2
26843    H3N2
Name: Subtype_x, Length: 419, dtype: object
                                                  Header Isolate_Id_x  \
331    EPI_ISL_278824|A/swine/Italy/229049/2015|A_/_H...       229049
338    EPI_ISL_19644422|A/swine/Italy/430612/2022|A_/...       430612
363    EPI_ISL_278826|A/swine/Italy/240849/2015|A_/_H...       240849
371    EPI_ISL_278827|A/swine/Italy/248147-8/2015|A_/...     248147-8
451    EPI_ISL_278844|A/swine/Italy/1103/2015|A_/_H3N...         1103
...                                                  ...          ...
26658  EPI_ISL_19644399|A/swine/Italy/35820/2022|A_/_...        35820
26823  EPI_ISL_163606|A/swine/Italy/187969/2013|A_/_H...       187969
26827  EPI_ISL_163607|A/swine/Italy/250481_2/2013|A_/...     250481_2
26835  EPI_ISL_163604|A/swine/Italy/311349/2013|A_/_H...       311349
26843  EPI_ISL_163605|A/swine/Italy/282811/2013|A_/_H...       282811

                    Isolate_Name_x Subtype_x Segment Location_x Geo_Location  \
331      A/swine/Italy/229049/2015      H3N2      HA      Italy        Italy
338      A/swine/Italy/430612/2022      H3N2      HA      Italy        Italy
363      A/swine/Italy/240849/2015      H3N2      HA      Italy        Italy
371    A/swine/Italy/248147-8/2015      H3N2      HA      Italy        Italy
451        A/swine/Italy/1103/2015      H3N2      HA      Italy        Italy
...                            ...       ...     ...        ...          ...
26658     A/swine/Italy/35820/2022      H3N2      HA      Italy        Italy
26823    A/swine/Italy/187969/2013      H3N2      HA      Italy        Italy
26827  A/swine/Italy/250481_2/2013      H3N2      HA      Italy        Italy
26835    A/swine/Italy/311349/2013      H3N2      HA      Italy        Italy
26843    A/swine/Italy/282811/2013      H3N2      HA      Italy        Italy

      Date Collected Species  \
331       2015-09-01   swine
338       2022-12-01   swine
363       2015-09-01   swine
371       2015-09-01   swine
451       2015-09-01   swine
...              ...     ...
26658           2022   swine
26823     2013-07-01   swine
26827     2013-09-01   swine
26835     2013-11-01   swine
26843     2013-10-01   swine

                                                Sequence  ... Outbreak  \
331    atgaagactgtcattgctttaagctacgtcttttgcctggtttttg...  ...      NaN
338    atgaagactgtcattgctttgagctacgtcttttgtctggtttttg...  ...      NaN
363    atgaagactgtcattgctttaagctacgtcttttgcctggtttttg...  ...      NaN
371    atgaagactgtcattgctttaagctacgtcttttgtctggtttttg...  ...      NaN
451    atgaagactgtcattgctttaagctacgtcttttgcctggtttttg...  ...      NaN
...                                                  ...  ...      ...
26658  atgaagactgtcattgctctaagctacgtcttttgtctgggttttg...  ...      NaN
26823  atgaagactgtcattgctttaagctacgtcttttgtctgggttttg...  ...      NaN
26827  atgaagactgtcattgctttaagctacgtcttttgtctggtttttg...  ...      NaN
26835  atgaagactgtcattgctttaagctacgtcatttgtctggttttta...  ...      NaN
26843  atgaagactgtcattgctttaagctacgtcttttgtctggtttttg...  ...      NaN

      Pathogen_Test_Info Is_Vaccinated Human_Specimen_Source  \
331                  NaN           NaN                   NaN
338                  NaN           NaN                   NaN
363                  NaN           NaN                   NaN
371                  NaN           NaN                   NaN
451                  NaN           NaN                   NaN
...                  ...           ...                   ...
26658                NaN           NaN                   NaN
26823                NaN           NaN                   NaN
26827                NaN           NaN                   NaN
26835                NaN           NaN                   NaN
26843                NaN           NaN                   NaN

      Animal_Specimen_Source Animal_Health_Status Domestic_Status PMID  \
331                      NaN                  NaN             NaN  NaN
338                      NaN                  NaN             NaN  NaN
363                      NaN                  NaN             NaN  NaN
371                      NaN                  NaN             NaN  NaN
451                      NaN                  NaN             NaN  NaN
...                      ...                  ...             ...  ...
26658                    NaN                  NaN             NaN  NaN
26823                    NaN                  NaN             NaN  NaN
26827                    NaN                  NaN             NaN  NaN
26835                    NaN                  NaN             NaN  NaN
26843                    NaN                  NaN             NaN  NaN

                                                New_Name Serotype
331    >EPI_ISL_278824|A/swine/Italy/229049/2015|H3N2...       H3
338    >EPI_ISL_19644422|A/swine/Italy/430612/2022|H3...       H3
363    >EPI_ISL_278826|A/swine/Italy/240849/2015|H3N2...       H3
371    >EPI_ISL_278827|A/swine/Italy/248147-8/2015|H3...       H3
451    >EPI_ISL_278844|A/swine/Italy/1103/2015|H3N2|I...       H3
...                                                  ...      ...
26658  >EPI_ISL_19644399|A/swine/Italy/35820/2022|H3N...       H3
26823  >EPI_ISL_163606|A/swine/Italy/187969/2013|H3N2...       H3
26827  >EPI_ISL_163607|A/swine/Italy/250481_2/2013|H3...       H3
26835  >EPI_ISL_163604|A/swine/Italy/311349/2013|H3N2...       H3
26843  >EPI_ISL_163605|A/swine/Italy/282811/2013|H3N2...       H3

[419 rows x 67 columns]
['Germany', '2014', 'swine\n']

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\2029038334.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = se
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\2029038334.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = se
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\2029038334.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = s
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\2029038334.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m_g_s["Serotype"] = s

In [ ]:
for gisaid_fasta in gisaid_fastas:
    print(gisaid_fasta)
    if "Segment_x" in gisaid_fasta.columns:
        gisaid_fasta["Segment"] = gisaid_fasta["Segment_x"]
    if "Isolate_Id_x" in gisaid_fasta.columns:
        gisaid_fasta["Isolate"] = gisaid_fasta["Isolate_Id_x"]
    print(gisaid_fasta["Segment"])

# Remove Paloma's sequences
os.chdir(downloads_saved)
paloma_isolates = pd.read_csv("paloma_isolates.csv")

for gisaid_fasta in gisaid_fastas:
    for isolate in paloma_isolates["isolate"].values:
        print(isolate)
        if isolate in gisaid_fasta["Isolate"]:
            gisaid_fasta = gisaid_fasta[gisaid_fasta["Isolate"] != isolate]

    # Remove duplicates
    gisaid_fasta = gisaid_fasta.drop_duplicates(subset="Header", keep="first")

                                                  Header Isolate_Id_x  \
4      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...         R313
12     EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...         R318
21     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|P...           18
26     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...        17671
35     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...          113
...                                                  ...          ...
26978  EPI_ISL_14761785|A/swine/Italy/23/2017|A_/_H1N...           23
26988  EPI_ISL_245726|A/swine/Germany/R1696/2014|A_/_...        R1696
26996  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...         R309
27004  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...       AR1026
27012  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...         R312

                             Isolate_Name_x Subtype_x Segment  \
4                 A/swine/Germany/R313/2015      H1N2      PA
12                A/swine/Germany/R318/2015      H1N2      PA
21                    A/swine/Italy/18/2000      H1N2      PA
26        A/swine/Czech_Republic/17671/2023      H1N2      PA
35     A/swine/Nordrhein-Westfalen/113/2024      H1N2      PA
...                                     ...       ...     ...
26978                 A/swine/Italy/23/2017      H1N1      PA
26988            A/swine/Germany/R1696/2014      H1N1      PA
26996             A/swine/Germany/R309/2015      H1N2      PA
27004           A/swine/Germany/AR1026/2016      H1N1      PA
27012             A/swine/Germany/R312/2015      H1N1      PA

                Location_x         Geo_Location Date Collected Species  \
4                  Germany              Germany           2014   swine
12                 Germany              Germany           2014   swine
21                   Italy                Italy     2000-01-03   swine
26          Czech_Republic       Czech_Republic     2023-11-13   swine
35     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20   swine
...                    ...                  ...            ...     ...
26978                Italy                Italy     2017-10-24   swine
26988              Germany              Germany           2014   swine
26996              Germany              Germany           2014   swine
27004              Germany              Germany     2016-02-17   swine
27012              Germany              Germany           2014   swine

                                                Sequence  ... Is_Vaccinated  \
4      cattcacatcttttcattcactggagaggagattgccaccaaagcg...  ...           NaN
12     aaatggccagtaggagtctatgggattcctttcgtcagtccgaaag...  ...           NaN
21     tgattcaaaatggaagactttgtgcgacaatgcttcaatccaatga...  ...           0.0
26     tgatccaaaatggaagactttgtgcgacaatgcttcaatccaatga...  ...           NaN
35     atggaagactttgtgcgacaatgcttcaacccaatgattgtcgagc...  ...           NaN
...                                                  ...  ...           ...
26978  atggaagactttgtgcgacaatgcttcaatccaatgatcgttgagc...  ...           NaN
26988  atggaagacttcgtgcgacagtgcttcaatccaatgatcgtcgagc...  ...           NaN
26996  atggaagactttgtgcgacaatgcttcaacccaatggtcgtcgagc...  ...           NaN
27004  atggaagactttgtgcgacaatgcttcaatccaatggtcgtcgagc...  ...           NaN
27012  atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  ...           NaN

      Human_Specimen_Source Animal_Specimen_Source Animal_Health_Status  \
4                       NaN                    NaN                  NaN
12                      NaN                    NaN                  NaN
21                      NaN                    NaN                  NaN
26                      NaN             Nasal swab                  NaN
35                      NaN                    NaN                  NaN
...                     ...                    ...                  ...
26978                   NaN                    NaN                  NaN
26988                   NaN                    NaN                  NaN
26996                   NaN                    NaN                  NaN
27004                   NaN    Oro-pharyngeal swab                 Sick
27012                   NaN                    NaN                  NaN

      Domestic_Status PMID                                           New_Name  \
4                 NaN  NaN  >EPI_ISL_245764|A/swine/Germany/R313/2015|H1N2...
12                NaN  NaN  >EPI_ISL_245771|A/swine/Germany/R318/2015|H1N2...
21                NaN  NaN  >EPI_ISL_73783|A/swine/Italy/18/2000|H1N2|Ital...
26           Domestic  NaN  >EPI_ISL_18604439|A/swine/Czech_Republic/17671...
35                NaN  NaN  >EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/...
...               ...  ...                                                ...
26978             NaN  NaN  >EPI_ISL_14761785|A/swine/Italy/23/2017|H1N1|I...
26988             NaN  NaN  >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...
26996             NaN  NaN  >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
27004        Domestic  NaN  >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
27012             NaN  NaN  >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...

      Serotype Isolate Segment_Name
4         None    R313           PA
12        None    R318           PA
21        None      18           PA
26        None   17671           PA
35        None     113           PA
...        ...     ...          ...
26978     None      23           PA
26988     None   R1696           PA
26996     None    R309           PA
27004     None  AR1026           PA
27012     None    R312           PA

[3377 rows x 69 columns]
4        PA
12       PA
21       PA
26       PA
35       PA
         ..
26978    PA
26988    PA
26996    PA
27004    PA
27012    PA
Name: Segment, Length: 3377, dtype: object
                                                  Header Isolate_Id_x  \
7      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...         R313
15     EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...         R318
20     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|N...           18
31     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...        17671
33     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...          113
...                                                  ...          ...
26979  EPI_ISL_14761785|A/swine/Italy/23/2017|A_/_H1N...           23
26991  EPI_ISL_245726|A/swine/Germany/R1696/2014|A_/_...        R1696
26999  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...         R309
27007  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...       AR1026
27015  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...         R312

                             Isolate_Name_x Subtype_x Segment  \
7                 A/swine/Germany/R313/2015      H1N2      NS
15                A/swine/Germany/R318/2015      H1N2      NS
20                    A/swine/Italy/18/2000      H1N2      NS
31        A/swine/Czech_Republic/17671/2023      H1N2      NS
33     A/swine/Nordrhein-Westfalen/113/2024      H1N2      NS
...                                     ...       ...     ...
26979                 A/swine/Italy/23/2017      H1N1      NS
26991            A/swine/Germany/R1696/2014      H1N1      NS
26999             A/swine/Germany/R309/2015      H1N2      NS
27007           A/swine/Germany/AR1026/2016      H1N1      NS
27015             A/swine/Germany/R312/2015      H1N1      NS

                Location_x         Geo_Location Date Collected Species  \
7                  Germany              Germany           2014   swine
15                 Germany              Germany           2014   swine
20                   Italy                Italy     2000-01-03   swine
31          Czech_Republic       Czech_Republic     2023-11-13   swine
33     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20   swine
...                    ...                  ...            ...     ...
26979                Italy                Italy     2017-10-24   swine
26991              Germany              Germany           2014   swine
26999              Germany              Germany           2014   swine
27007              Germany              Germany     2016-02-17   swine
27015              Germany              Germany           2014   swine

                                                Sequence  ... Is_Vaccinated  \
7      atggactccaacaccatgtcaagctttcaggtagactgtttccttt...  ...           NaN
15     agcaaaagcagggtgacaaaaacataatggactccaacaccatgtc...  ...           NaN
20     acaaaaacataatggattcaaacactgtgtcaagctttcaggtaga...  ...           0.0
31     acaaagacataatggattcaaacactgtgtcaagcttccaggtaga...  ...           NaN
33     atggattcaaacactgtttcgagcttccaggtagattgctttcttt...  ...           NaN
...                                                  ...  ...           ...
26979  atggattcaaacactgtgtcaagctttcaggtagactgctttcttt...  ...           NaN
26991  agcaaaagcagggtgacaaaacataatggattcaaacactgtgtca...  ...           NaN
26999  atggattcaaacactgtgtcaagctttcaggtagattgctttcttt...  ...           NaN
27007  atggattcaaacactgtgtcaagctttcaggtagattgctttcttt...  ...           NaN
27015  agcaaaagcagggtgacaaaaacataatggattcaaatactgtgtc...  ...           NaN

      Human_Specimen_Source Animal_Specimen_Source Animal_Health_Status  \
7                       NaN                    NaN                  NaN
15                      NaN                    NaN                  NaN
20                      NaN                    NaN                  NaN
31                      NaN             Nasal swab                  NaN
33                      NaN                    NaN                  NaN
...                     ...                    ...                  ...
26979                   NaN                    NaN                  NaN
26991                   NaN                    NaN                  NaN
26999                   NaN                    NaN                  NaN
27007                   NaN    Oro-pharyngeal swab                 Sick
27015                   NaN                    NaN                  NaN

      Domestic_Status PMID                                           New_Name  \
7                 NaN  NaN  >EPI_ISL_245764|A/swine/Germany/R313/2015|H1N2...
15                NaN  NaN  >EPI_ISL_245771|A/swine/Germany/R318/2015|H1N2...
20                NaN  NaN  >EPI_ISL_73783|A/swine/Italy/18/2000|H1N2|Ital...
31           Domestic  NaN  >EPI_ISL_18604439|A/swine/Czech_Republic/17671...
33                NaN  NaN  >EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/...
...               ...  ...                                                ...
26979             NaN  NaN  >EPI_ISL_14761785|A/swine/Italy/23/2017|H1N1|I...
26991             NaN  NaN  >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...
26999             NaN  NaN  >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
27007        Domestic  NaN  >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
27015             NaN  NaN  >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...

      Serotype Isolate Segment_Name
7         None    R313           NS
15        None    R318           NS
20        None      18           NS
31        None   17671           NS
33        None     113           NS
...        ...     ...          ...
26979     None      23           NS
26991     None   R1696           NS
26999     None    R309           NS
27007     None  AR1026           NS
27015     None    R312           NS

[3377 rows x 69 columns]
7        NS
15       NS
20       NS
31       NS
33       NS
         ..
26979    NS
26991    NS
26999    NS
27007    NS
27015    NS
Name: Segment, Length: 3377, dtype: object
                                                  Header Isolate_Id_x  \
56     EPI_ISL_19751421|A/swine/Denmark/LF22-7167-3/2...  LF22-7167-3
72     EPI_ISL_19751423|A/swine/Denmark/LF22-7302-1/2...  LF22-7302-1
80     EPI_ISL_19751422|A/swine/Denmark/LF22-7300-3/2...  LF22-7300-3
88     EPI_ISL_19751417|A/swine/Denmark/LF22-6877-4/2...  LF22-6877-4
112    EPI_ISL_19751418|A/swine/Denmark/LF22-6907-1/2...  LF22-6907-1
...                                                  ...          ...
26961  EPI_ISL_245702|A/swine/Germany/R1154/2014|A_/_...        R1154
26981  EPI_ISL_14761785|A/swine/Italy/23/2017|A_/_H1N...           23
26985  EPI_ISL_245726|A/swine/Germany/R1696/2014|A_/_...        R1696
27001  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...       AR1026
27009  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...         R312

                         Isolate_Name_x Subtype_x Segment Location_x  \
56     A/swine/Denmark/LF22-7167-3/2022      H1N1      NA    Denmark
72     A/swine/Denmark/LF22-7302-1/2022      H1N1      NA    Denmark
80     A/swine/Denmark/LF22-7300-3/2022      H1N1      NA    Denmark
88     A/swine/Denmark/LF22-6877-4/2022      H1N1      NA    Denmark
112    A/swine/Denmark/LF22-6907-1/2022      H1N1      NA    Denmark
...                                 ...       ...     ...        ...
26961        A/swine/Germany/R1154/2014      H1N1      NA    Germany
26981             A/swine/Italy/23/2017      H1N1      NA      Italy
26985        A/swine/Germany/R1696/2014      H1N1      NA    Germany
27001       A/swine/Germany/AR1026/2016      H1N1      NA    Germany
27009         A/swine/Germany/R312/2015      H1N1      NA    Germany

      Geo_Location Date Collected Species  \
56         Denmark           2022   swine
72         Denmark           2022   swine
80         Denmark           2022   swine
88         Denmark           2022   swine
112        Denmark           2022   swine
...            ...            ...     ...
26961      Germany           2014   swine
26981        Italy     2017-10-24   swine
26985      Germany           2014   swine
27001      Germany     2016-02-17   swine
27009      Germany           2014   swine

                                                Sequence  ... Is_Vaccinated  \
56     agcaaaagcaggagtttaaaatgaatccaaaccaaaagataataac...  ...           NaN
72     aagcaggagtttaaaatgaatccaaaccaaaagataataaccattg...  ...           NaN
80     agcaaaagcaggagttcaagatgaatccaaatcaaaagataataat...  ...           NaN
88     agcaaaagcaggagtttaaaatgaatccaaaccaaaagataataac...  ...           NaN
112    agcaaaagcaggagttcgaaatgaatccaaatcaaaagataataac...  ...           NaN
...                                                  ...  ...           ...
26961  atgaatccaaatcaaaagataataatcattagctcgatctgcatga...  ...           NaN
26981  atgaatccaaatcagaagataataattattagttcaatctgtatga...  ...           NaN
26985  atgaatccaaatcaaaagataataaccattggttcgatctgtatga...  ...           NaN
27001  atgaatccaaatcaaaagataataatcattagctcgatctgcatga...  ...           NaN
27009  atgaatccaaatcagaagataataatcattagctcgatttgtatga...  ...           NaN

      Human_Specimen_Source Animal_Specimen_Source Animal_Health_Status  \
56                      NaN             Nasal swab                  NaN
72                      NaN             Nasal swab                  NaN
80                      NaN             Nasal swab                  NaN
88                      NaN             Nasal swab                  NaN
112                     NaN             Nasal swab                  NaN
...                     ...                    ...                  ...
26961                   NaN                    NaN                  NaN
26981                   NaN                    NaN                  NaN
26985                   NaN                    NaN                  NaN
27001                   NaN    Oro-pharyngeal swab                 Sick
27009                   NaN                    NaN                  NaN

      Domestic_Status PMID                                           New_Name  \
56                NaN  NaN  >EPI_ISL_19751421|A/swine/Denmark/LF22-7167-3/...
72                NaN  NaN  >EPI_ISL_19751423|A/swine/Denmark/LF22-7302-1/...
80                NaN  NaN  >EPI_ISL_19751422|A/swine/Denmark/LF22-7300-3/...
88                NaN  NaN  >EPI_ISL_19751417|A/swine/Denmark/LF22-6877-4/...
112               NaN  NaN  >EPI_ISL_19751418|A/swine/Denmark/LF22-6907-1/...
...               ...  ...                                                ...
26961             NaN  NaN  >EPI_ISL_245702|A/swine/Germany/R1154/2014|H1N...
26981             NaN  NaN  >EPI_ISL_14761785|A/swine/Italy/23/2017|H1N1|I...
26985             NaN  NaN  >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...
27001        Domestic  NaN  >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
27009             NaN  NaN  >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...

      Serotype      Isolate Segment_Name
56          N1  LF22-7167-3           NA
72          N1  LF22-7302-1           NA
80          N1  LF22-7300-3           NA
88          N1  LF22-6877-4           NA
112         N1  LF22-6907-1           NA
...        ...          ...          ...
26961       N1        R1154           NA
26981       N1           23           NA
26985       N1        R1696           NA
27001       N1       AR1026           NA
27009       N1         R312           NA

[1616 rows x 69 columns]
56       NA
72       NA
80       NA
88       NA
112      NA
         ..
26961    NA
26981    NA
26985    NA
27001    NA
27009    NA
Name: Segment, Length: 1616, dtype: object
                                                  Header Isolate_Id_x  \
1      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...         R313
9      EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...         R318
17     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|N...           18
29     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...        17671
38     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...          113
...                                                  ...          ...
26929  EPI_ISL_245695|A/swine/Germany/R825/2014|A_/_H...         R825
26937  EPI_ISL_245699|A/swine/Germany/R1143/2014|A_/_...        R1143
26945  EPI_ISL_245697|A/swine/Germany/R916/2014|A_/_H...         R916
26969  EPI_ISL_245704|A/swine/Germany/R1190/2014|A_/_...        R1190
26993  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...         R309

                             Isolate_Name_x Subtype_x Segment  \
1                 A/swine/Germany/R313/2015      H1N2      NA
9                 A/swine/Germany/R318/2015      H1N2      NA
17                    A/swine/Italy/18/2000      H1N2      NA
29        A/swine/Czech_Republic/17671/2023      H1N2      NA
38     A/swine/Nordrhein-Westfalen/113/2024      H1N2      NA
...                                     ...       ...     ...
26929             A/swine/Germany/R825/2014      H1N2      NA
26937            A/swine/Germany/R1143/2014      H1N2      NA
26945             A/swine/Germany/R916/2014      H1N2      NA
26969            A/swine/Germany/R1190/2014      H1N2      NA
26993             A/swine/Germany/R309/2015      H1N2      NA

                Location_x         Geo_Location Date Collected Species  \
1                  Germany              Germany           2014   swine
9                  Germany              Germany           2014   swine
17                   Italy                Italy     2000-01-03   swine
29          Czech_Republic       Czech_Republic     2023-11-13   swine
38     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20   swine
...                    ...                  ...            ...     ...
26929              Germany              Germany           2014   swine
26937              Germany              Germany           2014   swine
26945              Germany              Germany           2014   swine
26969              Germany              Germany           2014   swine
26993              Germany              Germany           2014   swine

                                                Sequence  ... Is_Vaccinated  \
1      atgaatccaaatcaaaagataataacgattggttctgtatccctaa...  ...           NaN
9      atgaatccaaatcaaaagataataacgattggttctatatccctaa...  ...           NaN
17     atgaatccaaatcagaagataataacaattggctctgtttctctct...  ...           0.0

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\416099530.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gisaid_fasta["Isolate"] = gisaid_fasta["Isolate_Id_x"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\416099530.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gisaid_fasta["Isolate"] = gisaid_fasta["Isolate_Id_x"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\416099530.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gisaid_fasta["Isolate"] = gisaid_fasta["Isolate_Id_x"]
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\416099530.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gisaid_fasta["Isolate"] = gisaid_fasta["Isolate_Id_x"]

06001-4
6176-2
6370-7
6370-6
6370-8
6370-9
6370-10
6370-11
06070-1
37500-1
22270-2
41566-1
22251-1
50001-3
25001-2
50001-5
50800-1
31310-1
22270-1
000-1
12312-1
50700-1
32070-1
22269-1
25211-1
28000-1
22253-1
22192-1
36520-1
50070-1
17001-1
50001-2
22070-1
30870-1
22260-1
49610-1
45790-1
50001-6
22000-1
44490-1
40217-1
05530-1
22220-1
17473-1
46314-1
46314-2
45560-1
44579-1
41410-1
31001-2
05165-1
2247-1
46892-1
50001-4
5296-1
05165-2
06800-1
25001-3
06001-3
44394-1
31510-1
17491-1
44593-1
12510-1
17483-1
25001-4
25001-1
22210-1
06001-4
6176-2
6370-7
6370-6
6370-8
6370-9
6370-10
6370-11
06070-1
37500-1
22270-2
41566-1
22251-1
50001-3
25001-2
50001-5
50800-1
31310-1
22270-1
000-1
12312-1
50700-1
32070-1
22269-1
25211-1
28000-1
22253-1
22192-1
36520-1
50070-1
17001-1
50001-2
22070-1
30870-1
22260-1
49610-1
45790-1
50001-6
22000-1
44490-1
40217-1
05530-1
22220-1
17473-1
46314-1
46314-2
45560-1
44579-1
41410-1
31001-2
05165-1
2247-1
46892-1
50001-4
5296-1
05165-2
06800-1
25001-3
06001-3
44394-1
31510-1
17491-1
44593-1
12510-1
17483-1
25001-4
25001-1
22210-1
06001-4
6176-2
6370-7
6370-6
6370-8
6370-9
6370-10
6370-11
06070-1
37500-1
22270-2
41566-1
22251-1
50001-3
25001-2
50001-5
50800-1
31310-1
22270-1
000-1
12312-1
50700-1
32070-1
22269-1
25211-1
28000-1
22253-1
22192-1
36520-1
50070-1
17001-1
50001-2
22070-1
30870-1
22260-1
49610-1
45790-1
50001-6
22000-1
44490-1
40217-1
05530-1
22220-1
17473-1
46314-1
46314-2
45560-1
44579-1
41410-1
31001-2
05165-1
2247-1
46892-1
50001-4
5296-1
05165-2
06800-1
25001-3
06001-3
44394-1
31510-1
17491-1
44593-1
12510-1
17483-1
25001-4
25001-1
22210-1
06001-4
6176-2
6370-7
6370-6
6370-8
6370-9
6370-10
6370-11
06070-1
37500-1
22270-2
41566-1
22251-1
50001-3
25001-2
50001-5
50800-1
31310-1
22270-1
000-1
12312-1
50700-1
32070-1
22269-1
25211-1
28000-1
22253-1
22192-1
36520-1
50070-1
17001-1
50001-2
22070-1
30870-1
22260-1
49610-1
45790-1
50001-6
22000-1
44490-1
40217-1
05530-1
22220-1
17473-1
46314-1
46314-2
45560-1
44579-1
41410-1
31001-2
05165-1
2247-1
46892-1
50001-4
5296-1
05165-2
06800-1
25001-3
06001-3
44394-1
31510-1
17491-1
44593-1
12510-1
17483-1
25001-4
25001-1
22210-1

In [74]:
# Create FASTA files

os.chdir(complete_files)

for df in gisaid_fastas:
    for serotype in serotypes:
        if serotype == df["Serotype"].values[0]:
            print(serotype)
            if "Segment_y" in df.columns:
                df["Segment_Name"] = df["Segment_y"]
            else:
                df["Segment_Name"] = df["Segment"]
            # print(df.columns)
            df.to_csv("GISAID_" + df["Segment_Name"].values[0] + "_" + serotype + "_metadata_Paloma.csv")
            # df = df.reset_index()
            # if len(df["Genotype_y"].values[0]) > 0: # If we have assigned genotypes, including "Unassigned"
            file_name = "GISAID_" + df["Segment_Name"].values[0] + "_" + serotype + "_Paloma.fasta"
            output_file = open(complete_files + file_name, "a+")

            for index, row in df.iterrows():
                name = df.loc[index, "New_Name"]
                name = name.replace(" ", "_")
                # names.append(name)
                sequence = df.loc[index, "Sequence"]
                # First is header, second is sequence
                output_file.write(name)
                output_file.write(sequence + "\n")
    if df["Serotype"].values[0] == "None":
        # df["Segment_Name"] = df["Segment_x"]
        if "Segment" in df.columns:
            df["Segment_Name"] = df["Segment"]
        else:
            df["Segment_Name"] = ""
        # print(df)
        df.to_csv("GISAID_" + df["Segment_Name"].values[0] + "_metadata_Paloma.csv")
        # df = df.reset_index()
        # if len(df["Genotype"].values[0]) > 0: # If we have assigned genotypes, including "Unassigned"
        file_name = "GISAID_" + df["Segment_Name"].values[0] + "_Paloma.fasta"
        output_file = open(complete_files + file_name, "a+")

        for index, row in df.iterrows():
            name = df.loc[index, "New_Name"]
            name = name.replace(" ", "_")
            # names.append(name)
            sequence = df.loc[index, "Sequence"]
            # First is header, second is sequence
            output_file.write(name)
            output_file.write(sequence + "\n")
        output_file.close()

N1

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_29452\2491812912.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Segment_Name"] = df["Segment"]

N2
H1
H3