## Housekeeping

In [1]:
# Libraries

import os
import pandas as pd
import dateutil
import re
import shutil 
import numpy as np
import importlib
import utils  
importlib.reload(utils)
from utils import * # If changing utils, must restart this file for changes to take effect

pd.options.mode.chained_assignment = None # suppress warnings when using slices to make new columns

In [2]:
# Directory paths

home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Downloads/" # MUST be downloads folder. Clean out downloads folder after each use. 
references = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/references/"

downloads_saved = home + "Other/Paloma/" 

complete_files = downloads_saved + "complete/" 
if not os.path.exists(complete_files): # checking if the directory exists or not
    os.makedirs(complete_files) # if the directory is not present then create it

os.chdir(references)
states_ref = pd.read_csv("states_ref.csv")

In [3]:
# Get metadata
os.chdir(downloads_saved)
metadata = pd.read_csv("sequences.csv")
print(len(metadata))

paloma_metadata_2019 = pd.read_csv("paloma_isolates_metadata_2019.csv")
paloma_metadata_2019 = paloma_metadata_2019.rename(columns={"Strain name":"strain_name"})
paloma_metadata_2016 = pd.read_csv("paloma_isolates_metadata_2016.csv")
paloma_metadata_2016 = paloma_metadata_2016.rename(columns={"STRAIN NAME":"strain_name"})

paloma_isolates_metadata = pd.concat([paloma_metadata_2016, paloma_metadata_2019])

paloma_isolates_metadata

354

                   strain_name Collection date    Province      Breed Subtype
0   A/swine/Spain/45700-1/2016      11/18/2016      Toledo  White pig     NaN
1   A/swine/Spain/40250-2/2016      11/18/2016      Toledo  White pig     NaN
2   A/swine/Spain/40192-1/2016      12/20/2016     Segovia  White pig     NaN
3   A/swine/Spain/40250-1/2016      12/20/2016     Segovia  White pig     NaN
4   A/swine/Spain/45690-1/2016      12/27/2016      Toledo  White pig     NaN
..                         ...             ...         ...        ...     ...
63  A/swine/Spain/46892-1/2022       8/30/2022    Valencia  White pig    H1N1
64   A/swine/Spain/5296-1/2022      10/27/2022       Ávila  White pig    H1N2
65  A/swine/Spain/45790-1/2022       9/15/2022      Toledo  White pig    H1N2
66  A/swine/Spain/36520-1/2022       9/21/2022  Pontevedra  White pig    H1N1
67  A/swine/Spain/50700-1/2022       10/4/2022    Zaragoza  White pig    H1N1

[115 rows x 5 columns]

## Add sequences to dataframe

In [4]:
# NCBI Virus Naming Convention:
# "Accession|GenBank_Title|Assembly|SRA Accession|BioSample|BioProject|Genotype|Isolate|Geo Location|Host|Collection Date"

# Get sequences and headers together
# headers = []
# isolates = []
# sras = []
# headers_seqs = {}

os.chdir(downloads_saved)

sequences_fasta = df_from_fasta("sequences.fasta") # Turn fasta into a dataframe

sequences_fasta["Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split("|")[0].replace(">", ""))

# print(sequences_fasta["full_header"])

# Extract segment number so that we can add the correct sequences to the correct sample
# sequences_fasta["Segment"] = sequences_fasta["full_header"].apply(lambda x: int(re.search(r'segment (.?) ', x.split("|")[-2]).group(1)))

# Double-check the de-duplication
print((sequences_fasta)) 
# print(sequences_fasta.head())
print((metadata))

# Add sequences to the dataframe
metadata_segments = pd.concat([metadata, sequences_fasta], axis=1) # , "Segment"])

                                           full_header  \
0    >PQ585340.1 |Influenza A virus (A/swine/Spain/...
1    >PQ585341.1 |Influenza A virus (A/swine/Spain/...
2    >PQ585342.1 |Influenza A virus (A/swine/Spain/...
3    >PQ585343.1 |Influenza A virus (A/swine/Spain/...
4    >PQ585344.1 |Influenza A virus (A/swine/Spain/...
..                                                 ...
349  >PP331800.1 |Influenza A virus (A/swine/Spain/...
350  >PP331801.1 |Influenza A virus (A/swine/Spain/...
351  >PP331802.1 |Influenza A virus (A/swine/Spain/...
352  >PP331803.1 |Influenza A virus (A/swine/Spain/...
353  >PP331804.1 |Influenza A virus (A/swine/Spain/...

                                              sequence    Accession
0    AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...  PQ585340.1
1    AGCAAAAGCAGGCAAACTATTTGAATGGATGTCAACCCGACTCTAC...  PQ585341.1
2    AGCAAAAGCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAAT...  PQ585342.1
3    AGCAAAAGCAGGGGATGATTAAATCAACCAAGATGAAAACAAAACT...  PQ585343.1
4    AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCCTACCA...  PQ585344.1
..                                                 ...          ...
349  AGCAAAAGCAGGGGATAATTAAATAAACCAAGATGAAAGCAAAATT...  PP331800.1
350  AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...  PP331801.1
351  AGCAAAAGCAGGAGTGAAGATGAACCCAAATCAAAAGATAATAACA...  PP331802.1
352  AGCAAAAGCAGGTAGATATTTAAAGATGAGTCTTCTAACCGAGGTC...  PP331803.1
353  AGCAAAAGCAGGGTGACAAAAACATAATGGATTCAAACACTGTATC...  PP331804.1

[354 rows x 3 columns]
      Accession GenBank_RefSeq         Assembly  SRA_Accession  BioSample  \
0    PQ585340.1        GenBank  GCA_052072035.1            NaN        NaN
1    PQ585341.1        GenBank  GCA_052072035.1            NaN        NaN
2    PQ585342.1        GenBank  GCA_052072035.1            NaN        NaN
3    PQ585343.1        GenBank  GCA_052072035.1            NaN        NaN
4    PQ585344.1        GenBank  GCA_052072035.1            NaN        NaN
..          ...            ...              ...            ...        ...
349  PP331800.1        GenBank  GCA_039221065.1            NaN        NaN
350  PP331801.1        GenBank  GCA_039221065.1            NaN        NaN
351  PP331802.1        GenBank  GCA_039221065.1            NaN        NaN
352  PP331803.1        GenBank  GCA_039221065.1            NaN        NaN
353  PP331804.1        GenBank  GCA_039221065.1            NaN        NaN

      BioProject      Organism_Name                         Species  \
0            NaN  Influenza A virus  Alphainfluenzavirus influenzae
1            NaN  Influenza A virus  Alphainfluenzavirus influenzae
2            NaN  Influenza A virus  Alphainfluenzavirus influenzae
3            NaN  Influenza A virus  Alphainfluenzavirus influenzae
4            NaN  Influenza A virus  Alphainfluenzavirus influenzae
..           ...                ...                             ...
349  PRJNA399763  Influenza A virus  Alphainfluenzavirus influenzae
350  PRJNA399763  Influenza A virus  Alphainfluenzavirus influenzae
351  PRJNA399763  Influenza A virus  Alphainfluenzavirus influenzae
352  PRJNA399763  Influenza A virus  Alphainfluenzavirus influenzae
353  PRJNA399763  Influenza A virus  Alphainfluenzavirus influenzae

                   Genus            Family  ... USA        Host  \
0    Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
1    Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
2    Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
3    Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
4    Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
..                   ...               ...  ...  ..         ...
349  Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
350  Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
351  Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
352  Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa
353  Alphainfluenzavirus  Orthomyxoviridae  ... NaN  Sus scrofa

     Tissue_Specimen_Source                          Submitters  \
0                      lung  Encinas,P., Del Real Soldevilla,G.
1                      lung  Encinas,P., Del Real Soldevilla,G.
2                      lung  Encinas,P., Del Real Soldevilla,G.
3                      lung  Encinas,P., Del Real Soldevilla,G.
4                      lung  Encinas,P., Del Real Soldevilla,G.
..                      ...                                 ...
349                    lung  Encinas,P., Del Real Soldevilla,G.
350                    lung  Encinas,P., Del Real Soldevilla,G.
351                    lung  Encinas,P., Del Real Soldevilla,G.
352                    lung  Encinas,P., Del Real Soldevilla,G.
353                    lung  Encinas,P., Del Real Soldevilla,G.

            Organization Org_location Publications Collection_Date  \
0    INIA, Biotechnology        Spain          NaN      2022-09-21
1    INIA, Biotechnology        Spain          NaN      2022-09-21
2    INIA, Biotechnology        Spain          NaN      2022-09-21
3    INIA, Biotechnology        Spain          NaN      2022-09-21
4    INIA, Biotechnology        Spain          NaN      2022-09-21
..                   ...          ...          ...             ...
349  INIA, Biotechnology        Spain          NaN      2020-06-16
350  INIA, Biotechnology        Spain          NaN      2020-06-16
351  INIA, Biotechnology        Spain          NaN      2020-06-16
352  INIA, Biotechnology        Spain          NaN      2020-06-16
353  INIA, Biotechnology        Spain          NaN      2020-06-16

     Release_Date Molecule_type
0      2025-08-13      ssRNA(-)
1      2025-08-13      ssRNA(-)
2      2025-08-13      ssRNA(-)
3      2025-08-13      ssRNA(-)
4      2025-08-13      ssRNA(-)
..            ...           ...
349    2024-02-18      ssRNA(-)
350    2024-02-18      ssRNA(-)
351    2024-02-18      ssRNA(-)
352    2024-02-18      ssRNA(-)
353    2024-02-18      ssRNA(-)

[354 rows x 28 columns]

In [5]:
print(metadata_segments.columns)

print(metadata_segments["Isolate"])

Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family', 'Genotype',
       'Isolate', 'Segment', 'GenBank_Title', 'Length', 'Nuc_Completeness',
       'Geo_Location', 'Country', 'USA', 'Host', 'Tissue_Specimen_Source',
       'Submitters', 'Organization', 'Org_location', 'Publications',
       'Collection_Date', 'Release_Date', 'Molecule_type', 'full_header',
       'sequence', 'Accession'],
      dtype='object')
0      36520-1
1      36520-1
2      36520-1
3      36520-1
4      36520-1
        ...
349    40217-1
350    40217-1
351    40217-1
352    40217-1
353    40217-1
Name: Isolate, Length: 354, dtype: object

In [6]:
# Cut down to only columns we want
metadata_genoflu = metadata_segments[["Accession", "GenBank_Title", "Host", "Collection_Date", "SRA_Accession", "Assembly", "Isolate", "Genotype", "Geo_Location", "full_header", "sequence", "Segment"]].iloc[:, 1:]

# # Get genbank strain name
metadata_genoflu["genbank_name"] = metadata_genoflu["GenBank_Title"].apply(lambda x: x.split("(")[1] )
# metadata_genoflu["Host"] = metadata_genoflu["genbank_name"].apply(lambda x: x.split("/")[1])

metadata_genoflu # [metadata_genoflu["Genotype"]  == "B3.13"]

,Accession,GenBank_Title,Host,Collection_Date,SRA_Accession,Assembly,Isolate,Genotype,Geo_Location,full_header,sequence,Segment,genbank_name
0,PQ585340.1,Influenza A virus (A/swine/Spain/36520-1/2022(...,Sus scrofa,2022-09-21,NaN,GCA_052072035.1,36520-1,H1N1,Spain,>PQ585340.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGTCAAATATATCCAATATGGAGAGAATAAAAGAAT...,1,A/swine/Spain/36520-1/2022
1,PQ585341.1,Influenza A virus (A/swine/Spain/36520-1/2022(...,Sus scrofa,2022-09-21,NaN,GCA_052072035.1,36520-1,H1N1,Spain,>PQ585341.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGCAAACTATTTGAATGGATGTCAACCCGACTCTAC...,2,A/swine/Spain/36520-1/2022
2,PQ585342.1,Influenza A virus (A/swine/Spain/36520-1/2022(...,Sus scrofa,2022-09-21,NaN,GCA_052072035.1,36520-1,H1N1,Spain,>PQ585342.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAAT...,3,A/swine/Spain/36520-1/2022
3,PQ585343.1,Influenza A virus (A/swine/Spain/36520-1/2022(...,Sus scrofa,2022-09-21,NaN,GCA_052072035.1,36520-1,H1N1,Spain,>PQ585343.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGGATGATTAAATCAACCAAGATGAAAACAAAACT...,4,A/swine/Spain/36520-1/2022
4,PQ585344.1,Influenza A virus (A/swine/Spain/36520-1/2022(...,Sus scrofa,2022-09-21,NaN,GCA_052072035.1,36520-1,H1N1,Spain,>PQ585344.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCCTACCA...,5,A/swine/Spain/36520-1/2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,PP331800.1,Influenza A virus (A/swine/Spain/40217-1/2020(...,Sus scrofa,2020-06-16,NaN,GCA_039221065.1,40217-1,H1N2,Spain,>PP331800.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGGATAATTAAATAAACCAAGATGAAAGCAAAATT...,4,A/swine/Spain/40217-1/2020
350,PP331801.1,Influenza A virus (A/swine/Spain/40217-1/2020(...,Sus scrofa,2020-06-16,NaN,GCA_039221065.1,40217-1,H1N2,Spain,>PP331801.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...,5,A/swine/Spain/40217-1/2020
351,PP331802.1,Influenza A virus (A/swine/Spain/40217-1/2020(...,Sus scrofa,2020-06-16,NaN,GCA_039221065.1,40217-1,H1N2,Spain,>PP331802.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGAGTGAAGATGAACCCAAATCAAAAGATAATAACA...,6,A/swine/Spain/40217-1/2020
352,PP331803.1,Influenza A virus (A/swine/Spain/40217-1/2020(...,Sus scrofa,2020-06-16,NaN,GCA_039221065.1,40217-1,H1N2,Spain,>PP331803.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGTAGATATTTAAAGATGAGTCTTCTAACCGAGGTC...,7,A/swine/Spain/40217-1/2020
353,PP331804.1,Influenza A virus (A/swine/Spain/40217-1/2020(...,Sus scrofa,2020-06-16,NaN,GCA_039221065.1,40217-1,H1N2,Spain,>PP331804.1 |Influenza A virus (A/swine/Spain/...,AGCAAAAGCAGGGTGACAAAAACATAATGGATTCAAACACTGTATC...,8,A/swine/Spain/40217-1/2020

## Relabeling Sequences

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

In [7]:

iberian_swine = ["06001-4", "6176-2", "6370-7", "6370-6", "6370-8", "6370-9", "6370-10", "6370-11", "06070-1"]

metadata_genoflu["full_header"] = metadata_genoflu["full_header"].apply(lambda x: x.replace("other_mammal", "Iberian_swine") if x.split("/")[3] in iberian_swine else x.replace("other_mammal", "swine") if "sw" in x.lower() or "scrofa" in x.lower() else x)

metadata_genoflu["full_header"]

0      >PQ585340.1 |Influenza A virus (A/swine/Spain/...
1      >PQ585341.1 |Influenza A virus (A/swine/Spain/...
2      >PQ585342.1 |Influenza A virus (A/swine/Spain/...
3      >PQ585343.1 |Influenza A virus (A/swine/Spain/...
4      >PQ585344.1 |Influenza A virus (A/swine/Spain/...
                             ...
349    >PP331800.1 |Influenza A virus (A/swine/Spain/...
350    >PP331801.1 |Influenza A virus (A/swine/Spain/...
351    >PP331802.1 |Influenza A virus (A/swine/Spain/...
352    >PP331803.1 |Influenza A virus (A/swine/Spain/...
353    >PP331804.1 |Influenza A virus (A/swine/Spain/...
Name: full_header, Length: 354, dtype: object

In [8]:
# Re-Labeling

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

# Fix animals
fix_animals_andersen(metadata_genoflu, animals_ref)

# Add more animal information from paloma metadata
print(paloma_isolates_metadata.columns)
# For each genbank_name, check if in paloma isolates metadata and rename host type to be pig breed. Else stay the same.

# Get the years
metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

# Get geographic locations
metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location"]
# For each genbank name, check if in paloma isolates metadata and rename geo_location to include province. Else stay the same.

paloma_isolates_metadata = paloma_isolates_metadata.rename(columns={"strain_name":"genbank_name"})
paloma_isolates_metadata_merged = metadata_genoflu.merge(paloma_isolates_metadata, on="genbank_name", how="left")


paloma_isolates_metadata_merged["Host_Type_Breed"] = paloma_isolates_metadata_merged["Breed"].apply(lambda x: x.split(" ")[0] if x == x else x)
# If Breed == NaN, fill with host_type
paloma_isolates_metadata_merged["Host_Type"] = paloma_isolates_metadata_merged["Host_Type_Breed"].fillna(paloma_isolates_metadata_merged["Host_Type"].apply(lambda x: x.replace("other_mammal", "swine") if "sw" in x.lower() or "scrofa" in x.lower() else x))

paloma_isolates_metadata_merged["Geo_Location_Abrv_Province"] = paloma_isolates_metadata_merged["Geo_Location_Abrv"] + "-" + paloma_isolates_metadata_merged["Province"]
paloma_isolates_metadata_merged["Geo_Location_Abrv_Province"] = paloma_isolates_metadata_merged["Geo_Location_Abrv_Province"].fillna(paloma_isolates_metadata_merged["Geo_Location_Abrv"])

metadata_genoflu = metadata_genoflu.merge(paloma_isolates_metadata_merged, on="genbank_name")

print(metadata_genoflu)

Index(['strain_name', 'Collection date', 'Province', 'Breed', 'Subtype'], dtype='object')
      Accession_x                                    GenBank_Title_x  \
0     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
1     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
2     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
3     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
4     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
...           ...                                                ...
2785  PP331804.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2786  PP331804.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2787  PP331804.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2788  PP331804.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2789  PP331804.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

          Host_x Collection_Date_x SRA_Accession_x       Assembly_x Isolate_x  \
0     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
1     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
2     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
3     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
4     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
...          ...               ...             ...              ...       ...
2785  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2786  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2787  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2788  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2789  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1

     Genotype_x Geo_Location_x  \
0          H1N1          Spain
1          H1N1          Spain
2          H1N1          Spain
3          H1N1          Spain
4          H1N1          Spain
...         ...            ...
2785       H1N2          Spain
2786       H1N2          Spain
2787       H1N2          Spain
2788       H1N2          Spain
2789       H1N2          Spain

                                          full_header_x  ... Segment_y  \
0     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...         1
1     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...         2
2     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...         3
3     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...         4
4     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...         5
...                                                 ...  ...       ...
2785  >PP331804.1 |Influenza A virus (A/swine/Spain/...  ...         4
2786  >PP331804.1 |Influenza A virus (A/swine/Spain/...  ...         5
2787  >PP331804.1 |Influenza A virus (A/swine/Spain/...  ...         6
2788  >PP331804.1 |Influenza A virus (A/swine/Spain/...  ...         7
2789  >PP331804.1 |Influenza A virus (A/swine/Spain/...  ...         8

      Host_Type_y Years_y Geo_Location_Abrv_y Collection date    Province  \
0           White    2022               Spain       9/21/2022  Pontevedra
1           White    2022               Spain       9/21/2022  Pontevedra
2           White    2022               Spain       9/21/2022  Pontevedra
3           White    2022               Spain       9/21/2022  Pontevedra
4           White    2022               Spain       9/21/2022  Pontevedra
...           ...     ...                 ...             ...         ...
2785        White    2020               Spain       6/16/2020     Segovia
2786        White    2020               Spain       6/16/2020     Segovia
2787        White    2020               Spain       6/16/2020     Segovia
2788        White    2020               Spain       6/16/2020     Segovia
2789        White    2020               Spain       6/16/2020     Segovia

          Breed Subtype Host_Type_Breed Geo_Location_Abrv_Province
0     White pig    H1N1           White           Spain-Pontevedra
1     White pig    H1N1           White           Spain-Pontevedra
2     White pig    H1N1           White           Spain-Pontevedra
3     White pig    H1N1           White           Spain-Pontevedra
4     White pig    H1N1           White           Spain-Pontevedra
...         ...     ...             ...                        ...
2785  White pig    H1N2           White              Spain-Segovia
2786  White pig    H1N2           White              Spain-Segovia
2787  White pig    H1N2           White              Spain-Segovia
2788  White pig    H1N2           White              Spain-Segovia
2789  White pig    H1N2           White              Spain-Segovia

[2790 rows x 37 columns]

In [9]:
# If there is no SRA Accession, replace identifier with Assembly
metadata_genoflu['SRA_Accession'] = np.where(metadata_genoflu['SRA_Accession_x'] == "", metadata_genoflu['Accession_x'].apply(lambda x: x.split(".")[0]), metadata_genoflu['SRA_Accession_x'])

# Make new labels
names = ">" + metadata_genoflu["SRA_Accession"].apply(lambda x: x.split(",")[0]) + "|" + metadata_genoflu["genbank_name"] + "|" + metadata_genoflu["Genotype_x"] + "|" + metadata_genoflu["Geo_Location_Abrv_Province"] + "|" + metadata_genoflu["Collection_Date_x"] + "|" + metadata_genoflu["Host_Type_y"] 

metadata_genoflu["Name"] = names
metadata_genoflu["Name"] = metadata_genoflu["Name"].apply(lambda x: x.replace("other_mammal", "Iberian_swine") if x.split("/")[3] in iberian_swine else x.replace("other_mammal", "swine") if "sw" in x.lower() or "scrofa" in x.lower() else x)


print(metadata_genoflu)

      Accession_x                                    GenBank_Title_x  \
0     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
1     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
2     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
3     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
4     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
...           ...                                                ...
2785  PP331804.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2786  PP331804.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2787  PP331804.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2788  PP331804.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2789  PP331804.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

          Host_x Collection_Date_x SRA_Accession_x       Assembly_x Isolate_x  \
0     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
1     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
2     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
3     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
4     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
...          ...               ...             ...              ...       ...
2785  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2786  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2787  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2788  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2789  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1

     Genotype_x Geo_Location_x  \
0          H1N1          Spain
1          H1N1          Spain
2          H1N1          Spain
3          H1N1          Spain
4          H1N1          Spain
...         ...            ...
2785       H1N2          Spain
2786       H1N2          Spain
2787       H1N2          Spain
2788       H1N2          Spain
2789       H1N2          Spain

                                          full_header_x  ... Years_y  \
0     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...    2022
1     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...    2022
2     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...    2022
3     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...    2022
4     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...    2022
...                                                 ...  ...     ...
2785  >PP331804.1 |Influenza A virus (A/swine/Spain/...  ...    2020
2786  >PP331804.1 |Influenza A virus (A/swine/Spain/...  ...    2020
2787  >PP331804.1 |Influenza A virus (A/swine/Spain/...  ...    2020
2788  >PP331804.1 |Influenza A virus (A/swine/Spain/...  ...    2020
2789  >PP331804.1 |Influenza A virus (A/swine/Spain/...  ...    2020

      Geo_Location_Abrv_y Collection date    Province      Breed Subtype  \
0                   Spain       9/21/2022  Pontevedra  White pig    H1N1
1                   Spain       9/21/2022  Pontevedra  White pig    H1N1
2                   Spain       9/21/2022  Pontevedra  White pig    H1N1
3                   Spain       9/21/2022  Pontevedra  White pig    H1N1
4                   Spain       9/21/2022  Pontevedra  White pig    H1N1
...                   ...             ...         ...        ...     ...
2785                Spain       6/16/2020     Segovia  White pig    H1N2
2786                Spain       6/16/2020     Segovia  White pig    H1N2
2787                Spain       6/16/2020     Segovia  White pig    H1N2
2788                Spain       6/16/2020     Segovia  White pig    H1N2
2789                Spain       6/16/2020     Segovia  White pig    H1N2

     Host_Type_Breed Geo_Location_Abrv_Province SRA_Accession  \
0              White           Spain-Pontevedra      PQ585340
1              White           Spain-Pontevedra      PQ585340
2              White           Spain-Pontevedra      PQ585340
3              White           Spain-Pontevedra      PQ585340
4              White           Spain-Pontevedra      PQ585340
...              ...                        ...           ...
2785           White              Spain-Segovia      PP331804
2786           White              Spain-Segovia      PP331804
2787           White              Spain-Segovia      PP331804
2788           White              Spain-Segovia      PP331804
2789           White              Spain-Segovia      PP331804

                                                   Name
0     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...
1     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...
2     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...
3     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...
4     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...
...                                                 ...
2785  >PP331804|A/swine/Spain/40217-1/2020|H1N2|Spai...
2786  >PP331804|A/swine/Spain/40217-1/2020|H1N2|Spai...
2787  >PP331804|A/swine/Spain/40217-1/2020|H1N2|Spai...
2788  >PP331804|A/swine/Spain/40217-1/2020|H1N2|Spai...
2789  >PP331804|A/swine/Spain/40217-1/2020|H1N2|Spai...

[2790 rows x 39 columns]

## Rename segments and make complete FASTA files

In [10]:
# Set up segments
serotypes = ["H1", "H3", "N1", "N2"]
segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"} # Name segments 
metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment_x"].apply(lambda x: int(x)).map(segments)

# Separate into several dataframes based on genotype + segment
segment_genotype_dfs = []
for serotype in serotypes:
    # metadata_genoflu["Serotype"] = metadata_genoflu["Name"].apply(lambda x: x.split("|")[2])
    m_g_s = metadata_genoflu[metadata_genoflu["Genotype_x"].str.contains(serotype)]
    m_g_s["Serotype"] = serotype
    for segment in segments.values():
        m_g = m_g_s[m_g_s["Segment_Name"] == segment]
        print(m_g)
        segment_genotype_dfs.append(m_g)
    # for genotype in list(set(m_g["Genotype"].values)):
    #     if genotype in genotypes:
    #         df = m_g[(m_g["Genotype"] == genotype)] 
    #         # df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
    #         segment_genotype_dfs.append(df)
    #         pair = genotype + "_" + segment
    #         print(pair)

      Accession_x                                    GenBank_Title_x  \
0     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
1     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
2     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
3     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
4     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
...           ...                                                ...
2729  PP331797.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2730  PP331797.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2731  PP331797.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2732  PP331797.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2733  PP331797.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

          Host_x Collection_Date_x SRA_Accession_x       Assembly_x Isolate_x  \
0     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
1     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
2     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
3     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
4     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
...          ...               ...             ...              ...       ...
2729  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2730  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2731  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2732  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2733  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1

     Genotype_x Geo_Location_x  \
0          H1N1          Spain
1          H1N1          Spain
2          H1N1          Spain
3          H1N1          Spain
4          H1N1          Spain
...         ...            ...
2729       H1N2          Spain
2730       H1N2          Spain
2731       H1N2          Spain
2732       H1N2          Spain
2733       H1N2          Spain

                                          full_header_x  ... Collection date  \
0     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
1     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
2     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
3     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
4     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
...                                                 ...  ...             ...
2729  >PP331797.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2730  >PP331797.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2731  >PP331797.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2732  >PP331797.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2733  >PP331797.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020

        Province      Breed Subtype Host_Type_Breed  \
0     Pontevedra  White pig    H1N1           White
1     Pontevedra  White pig    H1N1           White
2     Pontevedra  White pig    H1N1           White
3     Pontevedra  White pig    H1N1           White
4     Pontevedra  White pig    H1N1           White
...          ...        ...     ...             ...
2729     Segovia  White pig    H1N2           White
2730     Segovia  White pig    H1N2           White
2731     Segovia  White pig    H1N2           White
2732     Segovia  White pig    H1N2           White
2733     Segovia  White pig    H1N2           White

     Geo_Location_Abrv_Province SRA_Accession  \
0              Spain-Pontevedra      PQ585340
1              Spain-Pontevedra      PQ585340
2              Spain-Pontevedra      PQ585340
3              Spain-Pontevedra      PQ585340
4              Spain-Pontevedra      PQ585340
...                         ...           ...
2729              Spain-Segovia      PP331797
2730              Spain-Segovia      PP331797
2731              Spain-Segovia      PP331797
2732              Spain-Segovia      PP331797
2733              Spain-Segovia      PP331797

                                                   Name Segment_Name Serotype
0     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB2       H1
1     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB2       H1
2     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB2       H1
3     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB2       H1
4     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB2       H1
...                                                 ...          ...      ...
2729  >PP331797|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB2       H1
2730  >PP331797|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB2       H1
2731  >PP331797|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB2       H1
2732  >PP331797|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB2       H1
2733  >PP331797|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB2       H1

[316 rows x 41 columns]
      Accession_x                                    GenBank_Title_x  \
8     PQ585341.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
9     PQ585341.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
10    PQ585341.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
11    PQ585341.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
12    PQ585341.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
...           ...                                                ...
2737  PP331798.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2738  PP331798.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2739  PP331798.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2740  PP331798.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2741  PP331798.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

          Host_x Collection_Date_x SRA_Accession_x       Assembly_x Isolate_x  \
8     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
9     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
10    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
11    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
12    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
...          ...               ...             ...              ...       ...
2737  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2738  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2739  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2740  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2741  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1

     Genotype_x Geo_Location_x  \
8          H1N1          Spain
9          H1N1          Spain
10         H1N1          Spain
11         H1N1          Spain
12         H1N1          Spain
...         ...            ...
2737       H1N2          Spain
2738       H1N2          Spain
2739       H1N2          Spain
2740       H1N2          Spain
2741       H1N2          Spain

                                          full_header_x  ... Collection date  \
8     >PQ585341.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
9     >PQ585341.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
10    >PQ585341.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
11    >PQ585341.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
12    >PQ585341.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
...                                                 ...  ...             ...
2737  >PP331798.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2738  >PP331798.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2739  >PP331798.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2740  >PP331798.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2741  >PP331798.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020

        Province      Breed Subtype Host_Type_Breed  \
8     Pontevedra  White pig    H1N1           White
9     Pontevedra  White pig    H1N1           White
10    Pontevedra  White pig    H1N1           White
11    Pontevedra  White pig    H1N1           White
12    Pontevedra  White pig    H1N1           White
...          ...        ...     ...             ...
2737     Segovia  White pig    H1N2           White
2738     Segovia  White pig    H1N2           White
2739     Segovia  White pig    H1N2           White
2740     Segovia  White pig    H1N2           White
2741     Segovia  White pig    H1N2           White

     Geo_Location_Abrv_Province SRA_Accession  \
8              Spain-Pontevedra      PQ585341
9              Spain-Pontevedra      PQ585341
10             Spain-Pontevedra      PQ585341
11             Spain-Pontevedra      PQ585341
12             Spain-Pontevedra      PQ585341
...                         ...           ...
2737              Spain-Segovia      PP331798
2738              Spain-Segovia      PP331798
2739              Spain-Segovia      PP331798
2740              Spain-Segovia      PP331798
2741              Spain-Segovia      PP331798

                                                   Name Segment_Name Serotype
8     >PQ585341|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB1       H1
9     >PQ585341|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB1       H1
10    >PQ585341|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB1       H1
11    >PQ585341|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB1       H1
12    >PQ585341|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB1       H1
...                                                 ...          ...      ...
2737  >PP331798|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB1       H1
2738  >PP331798|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB1       H1
2739  >PP331798|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB1       H1
2740  >PP331798|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB1       H1
2741  >PP331798|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB1       H1

[316 rows x 41 columns]
      Accession_x                                    GenBank_Title_x  \
16    PQ585342.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
17    PQ585342.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
18    PQ585342.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
19    PQ585342.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
20    PQ585342.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
...           ...                                                ...
2745  PP331799.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2746  PP331799.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2747  PP331799.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2748  PP331799.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2749  PP331799.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

          Host_x Collection_Date_x SRA_Accession_x       Assembly_x Isolate_x  \
16    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
17    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
18    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
19    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
20    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
...          ...               ...             ...              ...       ...
2745  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2746  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2747  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2748  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2749  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1

     Genotype_x Geo_Location_x  \
16         H1N1          Spain
17         H1N1          Spain
18         H1N1          Spain
19         H1N1          Spain
20         H1N1          Spain
...         ...            ...
2745       H1N2          Spain
2746       H1N2          Spain
2747       H1N2          Spain
2748       H1N2          Spain
2749       H1N2          Spain

                                          full_header_x  ... Collection date  \
16    >PQ585342.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
17    >PQ585342.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
18    >PQ585342.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
19    >PQ585342.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
20    >PQ585342.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
...                                                 ...  ...             ...
2745  >PP331799.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2746  >PP331799.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2747  >PP331799.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2748  >PP331799.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2749  >PP331799.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020

        Province      Breed Subtype Host_Type_Breed  \
16    Pontevedra  White pig    H1N1           White
17    Pontevedra  White pig    H1N1           White
18    Pontevedra  White pig    H1N1           White
19    Pontevedra  White pig    H1N1           White
20    Pontevedra  White pig    H1N1           White
...          ...        ...     ...             ...
2745     Segovia  White pig    H1N2           White
2746     Segovia  White pig    H1N2           White
2747     Segovia  White pig    H1N2           White
2748     Segovia  White pig    H1N2           White
2749     Segovia  White pig    H1N2           White

     Geo_Location_Abrv_Province SRA_Accession  \
16             Spain-Pontevedra      PQ585342
17             Spain-Pontevedra      PQ585342
18             Spain-Pontevedra      PQ585342
19             Spain-Pontevedra      PQ585342
20             Spain-Pontevedra      PQ585342
...                         ...           ...
2745              Spain-Segovia      PP331799
2746              Spain-Segovia      PP331799
2747              Spain-Segovia      PP331799
2748              Spain-Segovia      PP331799
2749              Spain-Segovia      PP331799

                                                   Name Segment_Name Serotype
16    >PQ585342|A/swine/Spain/36520-1/2022|H1N1|Spai...           PA       H1
17    >PQ585342|A/swine/Spain/36520-1/2022|H1N1|Spai...           PA       H1
18    >PQ585342|A/swine/Spain/36520-1/2022|H1N1|Spai...           PA       H1
19    >PQ585342|A/swine/Spain/36520-1/2022|H1N1|Spai...           PA       H1
20    >PQ585342|A/swine/Spain/36520-1/2022|H1N1|Spai...           PA       H1
...                                                 ...          ...      ...
2745  >PP331799|A/swine/Spain/40217-1/2020|H1N2|Spai...           PA       H1
2746  >PP331799|A/swine/Spain/40217-1/2020|H1N2|Spai...           PA       H1
2747  >PP331799|A/swine/Spain/40217-1/2020|H1N2|Spai...           PA       H1
2748  >PP331799|A/swine/Spain/40217-1/2020|H1N2|Spai...           PA       H1
2749  >PP331799|A/swine/Spain/40217-1/2020|H1N2|Spai...           PA       H1

[309 rows x 41 columns]
      Accession_x                                    GenBank_Title_x  \
24    PQ585343.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
25    PQ585343.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
26    PQ585343.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
27    PQ585343.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
28    PQ585343.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
...           ...                                                ...
2753  PP331800.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2754  PP331800.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2755  PP331800.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2756  PP331800.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2757  PP331800.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

          Host_x Collection_Date_x SRA_Accession_x       Assembly_x Isolate_x  \
24    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
25    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
26    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
27    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
28    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
...          ...               ...             ...              ...       ...
2753  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2754  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2755  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2756  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2757  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1

     Genotype_x Geo_Location_x  \
24         H1N1          Spain
25         H1N1          Spain
26         H1N1          Spain
27         H1N1          Spain
28         H1N1          Spain
...         ...            ...
2753       H1N2          Spain
2754       H1N2          Spain
2755       H1N2          Spain
2756       H1N2          Spain
2757       H1N2          Spain

                                          full_header_x  ... Collection date  \
24    >PQ585343.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
25    >PQ585343.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
26    >PQ585343.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
27    >PQ585343.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
28    >PQ585343.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
...                                                 ...  ...             ...
2753  >PP331800.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2754  >PP331800.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2755  >PP331800.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2756  >PP331800.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2757  >PP331800.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020

        Province      Breed Subtype Host_Type_Breed  \
24    Pontevedra  White pig    H1N1           White
25    Pontevedra  White pig    H1N1           White
26    Pontevedra  White pig    H1N1           White
27    Pontevedra  White pig    H1N1           White
28    Pontevedra  White pig    H1N1           White
...          ...        ...     ...             ...
2753     Segovia  White pig    H1N2           White
2754     Segovia  White pig    H1N2           White
2755     Segovia  White pig    H1N2           White
2756     Segovia  White pig    H1N2           White
2757     Segovia  White pig    H1N2           White

     Geo_Location_Abrv_Province SRA_Accession  \
24             Spain-Pontevedra      PQ585343
25             Spain-Pontevedra      PQ585343
26             Spain-Pontevedra      PQ585343
27             Spain-Pontevedra      PQ585343
28             Spain-Pontevedra      PQ585343
...                         ...           ...
2753              Spain-Segovia      PP331800
2754              Spain-Segovia      PP331800
2755              Spain-Segovia      PP331800
2756              Spain-Segovia      PP331800
2757              Spain-Segovia      PP331800


In [11]:
# Create FASTA files

os.chdir(complete_files)

for df in segment_genotype_dfs:
    # print(df)
    for serotype in serotypes:
        if df["Serotype"].values[0] == serotype:
            print(df)
            df.to_csv("GenBank_" + df["Segment_Name"].values[0] + "_" + serotype + "_metadata_Paloma.csv")
            df = df.reset_index()
            if len(df) > 0: # If there are entries
                file_name = "GenBank_" + df["Segment_Name"].values[0] + "_" + serotype + "_Paloma.fasta"
                output_file = open(complete_files + file_name, "w")

                for index, row in df.iterrows():
                    name = df.loc[index, "Name"]
                    name = name.replace(" ", "_")
                    # names.append(name)
                    sequence = df.loc[index, "sequence_x"]
                    # First is header, second is sequence
                    output_file.write(name + "\n")
                    output_file.write(sequence + "\n")
                
            output_file.close()

      Accession_x                                    GenBank_Title_x  \
0     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
1     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
2     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
3     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
4     PQ585340.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
...           ...                                                ...
2729  PP331797.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2730  PP331797.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2731  PP331797.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2732  PP331797.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2733  PP331797.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

          Host_x Collection_Date_x SRA_Accession_x       Assembly_x Isolate_x  \
0     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
1     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
2     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
3     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
4     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
...          ...               ...             ...              ...       ...
2729  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2730  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2731  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2732  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2733  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1

     Genotype_x Geo_Location_x  \
0          H1N1          Spain
1          H1N1          Spain
2          H1N1          Spain
3          H1N1          Spain
4          H1N1          Spain
...         ...            ...
2729       H1N2          Spain
2730       H1N2          Spain
2731       H1N2          Spain
2732       H1N2          Spain
2733       H1N2          Spain

                                          full_header_x  ... Collection date  \
0     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
1     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
2     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
3     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
4     >PQ585340.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
...                                                 ...  ...             ...
2729  >PP331797.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2730  >PP331797.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2731  >PP331797.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2732  >PP331797.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2733  >PP331797.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020

        Province      Breed Subtype Host_Type_Breed  \
0     Pontevedra  White pig    H1N1           White
1     Pontevedra  White pig    H1N1           White
2     Pontevedra  White pig    H1N1           White
3     Pontevedra  White pig    H1N1           White
4     Pontevedra  White pig    H1N1           White
...          ...        ...     ...             ...
2729     Segovia  White pig    H1N2           White
2730     Segovia  White pig    H1N2           White
2731     Segovia  White pig    H1N2           White
2732     Segovia  White pig    H1N2           White
2733     Segovia  White pig    H1N2           White

     Geo_Location_Abrv_Province SRA_Accession  \
0              Spain-Pontevedra      PQ585340
1              Spain-Pontevedra      PQ585340
2              Spain-Pontevedra      PQ585340
3              Spain-Pontevedra      PQ585340
4              Spain-Pontevedra      PQ585340
...                         ...           ...
2729              Spain-Segovia      PP331797
2730              Spain-Segovia      PP331797
2731              Spain-Segovia      PP331797
2732              Spain-Segovia      PP331797
2733              Spain-Segovia      PP331797

                                                   Name Segment_Name Serotype
0     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB2       H1
1     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB2       H1
2     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB2       H1
3     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB2       H1
4     >PQ585340|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB2       H1
...                                                 ...          ...      ...
2729  >PP331797|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB2       H1
2730  >PP331797|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB2       H1
2731  >PP331797|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB2       H1
2732  >PP331797|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB2       H1
2733  >PP331797|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB2       H1

[316 rows x 41 columns]

      Accession_x                                    GenBank_Title_x  \
8     PQ585341.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
9     PQ585341.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
10    PQ585341.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
11    PQ585341.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
12    PQ585341.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
...           ...                                                ...
2737  PP331798.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2738  PP331798.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2739  PP331798.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2740  PP331798.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2741  PP331798.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

          Host_x Collection_Date_x SRA_Accession_x       Assembly_x Isolate_x  \
8     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
9     sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
10    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
11    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
12    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
...          ...               ...             ...              ...       ...
2737  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2738  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2739  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2740  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2741  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1

     Genotype_x Geo_Location_x  \
8          H1N1          Spain
9          H1N1          Spain
10         H1N1          Spain
11         H1N1          Spain
12         H1N1          Spain
...         ...            ...
2737       H1N2          Spain
2738       H1N2          Spain
2739       H1N2          Spain
2740       H1N2          Spain
2741       H1N2          Spain

                                          full_header_x  ... Collection date  \
8     >PQ585341.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
9     >PQ585341.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
10    >PQ585341.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
11    >PQ585341.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
12    >PQ585341.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
...                                                 ...  ...             ...
2737  >PP331798.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2738  >PP331798.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2739  >PP331798.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2740  >PP331798.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2741  >PP331798.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020

        Province      Breed Subtype Host_Type_Breed  \
8     Pontevedra  White pig    H1N1           White
9     Pontevedra  White pig    H1N1           White
10    Pontevedra  White pig    H1N1           White
11    Pontevedra  White pig    H1N1           White
12    Pontevedra  White pig    H1N1           White
...          ...        ...     ...             ...
2737     Segovia  White pig    H1N2           White
2738     Segovia  White pig    H1N2           White
2739     Segovia  White pig    H1N2           White
2740     Segovia  White pig    H1N2           White
2741     Segovia  White pig    H1N2           White

     Geo_Location_Abrv_Province SRA_Accession  \
8              Spain-Pontevedra      PQ585341
9              Spain-Pontevedra      PQ585341
10             Spain-Pontevedra      PQ585341
11             Spain-Pontevedra      PQ585341
12             Spain-Pontevedra      PQ585341
...                         ...           ...
2737              Spain-Segovia      PP331798
2738              Spain-Segovia      PP331798
2739              Spain-Segovia      PP331798
2740              Spain-Segovia      PP331798
2741              Spain-Segovia      PP331798

                                                   Name Segment_Name Serotype
8     >PQ585341|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB1       H1
9     >PQ585341|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB1       H1
10    >PQ585341|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB1       H1
11    >PQ585341|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB1       H1
12    >PQ585341|A/swine/Spain/36520-1/2022|H1N1|Spai...          PB1       H1
...                                                 ...          ...      ...
2737  >PP331798|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB1       H1
2738  >PP331798|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB1       H1
2739  >PP331798|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB1       H1
2740  >PP331798|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB1       H1
2741  >PP331798|A/swine/Spain/40217-1/2020|H1N2|Spai...          PB1       H1

[316 rows x 41 columns]
      Accession_x                                    GenBank_Title_x  \
16    PQ585342.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
17    PQ585342.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
18    PQ585342.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
19    PQ585342.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
20    PQ585342.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
...           ...                                                ...
2745  PP331799.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2746  PP331799.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2747  PP331799.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2748  PP331799.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2749  PP331799.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

          Host_x Collection_Date_x SRA_Accession_x       Assembly_x Isolate_x  \
16    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
17    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
18    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
19    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
20    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
...          ...               ...             ...              ...       ...
2745  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2746  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2747  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2748  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2749  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1

     Genotype_x Geo_Location_x  \
16         H1N1          Spain
17         H1N1          Spain
18         H1N1          Spain
19         H1N1          Spain
20         H1N1          Spain
...         ...            ...
2745       H1N2          Spain
2746       H1N2          Spain
2747       H1N2          Spain
2748       H1N2          Spain
2749       H1N2          Spain

                                          full_header_x  ... Collection date  \
16    >PQ585342.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
17    >PQ585342.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
18    >PQ585342.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
19    >PQ585342.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
20    >PQ585342.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
...                                                 ...  ...             ...
2745  >PP331799.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2746  >PP331799.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2747  >PP331799.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2748  >PP331799.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2749  >PP331799.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020

        Province      Breed Subtype Host_Type_Breed  \
16    Pontevedra  White pig    H1N1           White
17    Pontevedra  White pig    H1N1           White
18    Pontevedra  White pig    H1N1           White
19    Pontevedra  White pig    H1N1           White
20    Pontevedra  White pig    H1N1           White
...          ...        ...     ...             ...
2745     Segovia  White pig    H1N2           White
2746     Segovia  White pig    H1N2           White
2747     Segovia  White pig    H1N2           White
2748     Segovia  White pig    H1N2           White
2749     Segovia  White pig    H1N2           White

     Geo_Location_Abrv_Province SRA_Accession  \
16             Spain-Pontevedra      PQ585342
17             Spain-Pontevedra      PQ585342
18             Spain-Pontevedra      PQ585342
19             Spain-Pontevedra      PQ585342
20             Spain-Pontevedra      PQ585342
...                         ...           ...
2745              Spain-Segovia      PP331799
2746              Spain-Segovia      PP331799
2747              Spain-Segovia      PP331799
2748              Spain-Segovia      PP331799
2749              Spain-Segovia      PP331799

                                                   Name Segment_Name Serotype
16    >PQ585342|A/swine/Spain/36520-1/2022|H1N1|Spai...           PA       H1
17    >PQ585342|A/swine/Spain/36520-1/2022|H1N1|Spai...           PA       H1
18    >PQ585342|A/swine/Spain/36520-1/2022|H1N1|Spai...           PA       H1
19    >PQ585342|A/swine/Spain/36520-1/2022|H1N1|Spai...           PA       H1
20    >PQ585342|A/swine/Spain/36520-1/2022|H1N1|Spai...           PA       H1
...                                                 ...          ...      ...
2745  >PP331799|A/swine/Spain/40217-1/2020|H1N2|Spai...           PA       H1
2746  >PP331799|A/swine/Spain/40217-1/2020|H1N2|Spai...           PA       H1
2747  >PP331799|A/swine/Spain/40217-1/2020|H1N2|Spai...           PA       H1
2748  >PP331799|A/swine/Spain/40217-1/2020|H1N2|Spai...           PA       H1
2749  >PP331799|A/swine/Spain/40217-1/2020|H1N2|Spai...           PA       H1

[309 rows x 41 columns]
      Accession_x                                    GenBank_Title_x  \
24    PQ585343.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
25    PQ585343.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
26    PQ585343.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
27    PQ585343.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
28    PQ585343.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
...           ...                                                ...
2753  PP331800.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2754  PP331800.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2755  PP331800.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2756  PP331800.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2757  PP331800.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

          Host_x Collection_Date_x SRA_Accession_x       Assembly_x Isolate_x  \
24    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
25    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
26    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
27    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
28    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
...          ...               ...             ...              ...       ...
2753  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2754  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2755  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2756  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2757  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1

     Genotype_x Geo_Location_x  \
24         H1N1          Spain
25         H1N1          Spain
26         H1N1          Spain
27         H1N1          Spain
28         H1N1          Spain
...         ...            ...
2753       H1N2          Spain
2754       H1N2          Spain
2755       H1N2          Spain
2756       H1N2          Spain
2757       H1N2          Spain

                                          full_header_x  ... Collection date  \
24    >PQ585343.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
25    >PQ585343.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
26    >PQ585343.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
27    >PQ585343.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
28    >PQ585343.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
...                                                 ...  ...             ...
2753  >PP331800.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2754  >PP331800.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2755  >PP331800.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2756  >PP331800.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2757  >PP331800.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020

        Province      Breed Subtype Host_Type_Breed  \
24    Pontevedra  White pig    H1N1           White
25    Pontevedra  White pig    H1N1           White
26    Pontevedra  White pig    H1N1           White
27    Pontevedra  White pig    H1N1           White
28    Pontevedra  White pig    H1N1           White
...          ...        ...     ...             ...
2753     Segovia  White pig    H1N2           White
2754     Segovia  White pig    H1N2           White
2755     Segovia  White pig    H1N2           White
2756     Segovia  White pig    H1N2           White
2757     Segovia  White pig    H1N2           White

     Geo_Location_Abrv_Province SRA_Accession  \
24             Spain-Pontevedra      PQ585343
25             Spain-Pontevedra      PQ585343
26             Spain-Pontevedra      PQ585343
27             Spain-Pontevedra      PQ585343
28             Spain-Pontevedra      PQ585343
...                         ...           ...
2753              Spain-Segovia      PP331800
2754              Spain-Segovia      PP331800
2755              Spain-Segovia      PP331800
2756              Spain-Segovia      PP331800
2757              Spain-Segovia      PP331800

                                                   Name Segment_Name Serotype
24    >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...           HA       H1
25    >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...           HA       H1
26    >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...           HA       H1
27    >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...           HA       H1
28    >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...           HA       H1
...                                                 ...          ...      ...
2753  >PP331800|A/swine/Spain/40217-1/2020|H1N2|Spai...           HA       H1
2754  >PP331800|A/swine/Spain/40217-1/2020|H1N2|Spai...           HA       H1
2755  >PP331800|A/swine/Spain/40217-1/2020|H1N2|Spai...           HA       H1
2756  >PP331800|A/swine/Spain/40217-1/2020|H1N2|Spai...           HA       H1
2757  >PP331800|A/swine/Spain/40217-1/2020|H1N2|Spai...           HA       H1

[323 rows x 41 columns]
      Accession_x                                    GenBank_Title_x  \
32    PQ585344.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
33    PQ585344.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
34    PQ585344.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
35    PQ585344.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
36    PQ585344.1   Influenza A virus (A/swine/Spain/36520-1/2022(...
...           ...                                                ...
2761  PP331801.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2762  PP331801.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2763  PP331801.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2764  PP331801.1   Influenza A virus (A/swine/Spain/40217-1/2020(...
2765  PP331801.1   Influenza A virus (A/swine/Spain/40217-1/2020(...

          Host_x Collection_Date_x SRA_Accession_x       Assembly_x Isolate_x  \
32    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
33    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
34    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
35    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
36    sus scrofa        2022-09-21                  GCA_052072035.1   36520-1
...          ...               ...             ...              ...       ...
2761  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2762  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2763  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2764  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1
2765  sus scrofa        2020-06-16                  GCA_039221065.1   40217-1

     Genotype_x Geo_Location_x  \
32         H1N1          Spain
33         H1N1          Spain
34         H1N1          Spain
35         H1N1          Spain
36         H1N1          Spain
...         ...            ...
2761       H1N2          Spain
2762       H1N2          Spain
2763       H1N2          Spain
2764       H1N2          Spain
2765       H1N2          Spain

                                          full_header_x  ... Collection date  \
32    >PQ585344.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
33    >PQ585344.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
34    >PQ585344.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
35    >PQ585344.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
36    >PQ585344.1 |Influenza A virus (A/swine/Spain/...  ...       9/21/2022
...                                                 ...  ...             ...
2761  >PP331801.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2762  >PP331801.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2763  >PP331801.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2764  >PP331801.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020
2765  >PP331801.1 |Influenza A virus (A/swine/Spain/...  ...       6/16/2020

        Province      Breed Subtype Host_Type_Breed  \
32    Pontevedra  White pig    H1N1           White
33    Pontevedra  White pig    H1N1           White
34    Pontevedra  White pig    H1N1           White
35    Pontevedra  White pig    H1N1           White
36    Pontevedra  White pig    H1N1           White
...          ...        ...     ...             ...
2761     Segovia  White pig    H1N2           White
2762     Segovia  White pig    H1N2           White
2763     Segovia  White pig    H1N2           White
2764     Segovia  White pig    H1N2           White
2765     Segovia  White pig    H1N2           White

     Geo_Location_Abrv_Province SRA_Accession  \
32             Spain-Pontevedra      PQ585344
33             Spain-Pontevedra      PQ585344
34             Spain-Pontevedra      PQ585344
35             Spain-Pontevedra      PQ585344
36             Spain-Pontevedra      PQ585344
...                         ...           ...
2761              Spain-Segovia      PP331801
2762              Spain-Segovia      PP331801
2763              Spain-Segovia      PP331801
2764              Spain-Segovia      PP331801
2765              Spain-Segovia      PP331801


## GISAID

In [44]:
# Function to get metadata
def separate_fasta_by_segs(metadata, fasta, animals_df, genotypes): #, b313_fasta, d11_fasta):

    fasta = fix_animals(fasta, animals_df) # Fix animals first

    unique_segments = list(set(fasta["Segment"])) # Get list of segments

    # “>EPI_ID|Isolate_name|subtype|collection_date|host_type|genotype”

    segment_fastas = [] # Get a list of fastas, separated by segment
    for genotype in genotypes: # .keys(): # For each genotype
        print(genotype)
        for seg in unique_segments: # For each segment

            xls = metadata # [metadata["Genotype"].apply(lambda x: x.split(" ")[0]) == genotype] # Get only the metadata corresponding to that genotype
            xls = xls.rename(columns={"Isolate_Id":"Identifier"})
            print(xls)
            # print("XLS: ", metadata["Genotype"])
            # print(xls["Clade"])

            # print(d11_xls)

            # FASTA
            # if "Identifier" in fasta.columns:
            #     mask = fasta["Identifier"].isin(xls['Isolate_Id'])
            # else:           
            #     mask = fasta['Isolate_Id'].isin(xls['Isolate_Id'])

            # fasta_seg_pre = fasta[fasta["Identifier"].isin(xls['Isolate_Id'])] # Get only the identifiers (Isolate_Id) that are left after metadata is filtered for genotype
            fasta_seg_pre = fasta.merge(xls, how="inner", on="Identifier")
            print(fasta_seg_pre.columns)
            # break 

            # fasta_seg = genotype_fastas[fasta_gen][genotype_fastas[fasta_gen]["Segment"] == seg]
            fasta_seg = fasta_seg_pre[fasta_seg_pre["Segment"] == seg]

            fasta_seg["Genotype"] = genotype

            # Rename sequences 
            new_name = ">" + fasta_seg["Identifier"] + "|" + fasta_seg["Isolate_Name_x"] + "|" + fasta_seg["Subtype_x"] + "|" + fasta_seg["Location"].apply(lambda x: x.split(" / ")[1] if x.split(" / ")[0] == "Europe" else x.split(" / ")[0]) + "|" + fasta_seg["Date Collected"].apply(lambda x: str(dateutil.parser.parse(x, default=dateutil.parser.parse("2000-01-01")).year) if dateutil.parser.parse(x, default=dateutil.parser.parse("2000-01-01")).month == dateutil.parser.parse("2000-01-01").month and dateutil.parser.parse(x, default=dateutil.parser.parse("2000-01-01")).day == dateutil.parser.parse("2000-01-01").day else x) + "|" + fasta_seg["Host_Type"] + "|" + fasta_seg["Genotype"] + "\n"
            fasta_seg["New_Name"] = new_name
            # print(fasta_seg["New_Name"])

            segment_fastas.append(fasta_seg)
            print(fasta_seg)

            segment_fastas.append(fasta_seg)

    return segment_fastas, unique_segments

def fasta_df(file_name):
    fasta = pd.DataFrame()
    headers = []
    isolate_ids = []
    isolate_names = []
    subtypes = []
    segments = []
    collection_dates = []
    sequences = []
    # host_types = []
    species = []
    identifiers = []
    locations = []
    # genotypes = []
    with open(file_name) as f:
        lines = f.readlines()
        for num, line in enumerate(lines):
            # print(line)
            if line[0] == ">": # If it's a header
                if line[1:].strip() not in headers: # And the previous line is not a header we've seen before
                    header = line[1:].strip() # Remove the ">"
                    # print(header)
                    try:
                        split_header = header.split("|")
                        if len(header.split("|")) > 4:
                            identifier = header.split("|")[0]
                            identifiers.append(identifier)
                            split_first_header = split_header[1].split("/")
                        # else:
                        #     identifiers.append("unknown")
                        #     split_first_header = split_header[0].split("/")
                        # print(split_first_header)
                        # print(split_header)
                        headers.append(header) 
                        isolate_ids.append(split_first_header[-2])
                        locations.append(split_first_header[-3])
                        isolate_names.append(split_header[-4]) # We'll need to extract data from this too
                        # print(split_header[2].split("_")[-1])
                        subtypes.append(split_header[-3].split("_")[-1])  # Get only H5N1
                        # genotypes.append(split_header[-1])
                        segments.append(split_header[-2]) # .split("|")[-1])
                        # host_types.append(split_header[-2])
                        species.append(split_first_header[1])
                        # if split_header[4] == "2024-01-01":
                        #     collection_dates.append("2024") # No samples were collected 1/1/2024, these are all unknown 
                        # elif split_header[4] == "2025-01-01":
                        #     collection_dates.append("2025")
                        # else: 
                        collection_dates.append(split_header[-1])
                        # collection_dates.append(split_header[-1].split("_")[-1])
                        if num < len(lines): # If we're not at the last line
                            # for i, l in enumerate(lines[num + 1:]):
                            i = num
                            sequence = ""
                            # print(lines[i])
                            # print(lines[i + 1])
                            while i < len(lines) - 1 and lines[i + 1][0] != ">": # While the next line is part of a sequence
                                sequence = sequence + lines[i + 1].strip()
                                i += 1
                            sequences.append(sequence) # Add next line to sequences
                    except:
                        headers.remove(header)
                        identifiers.remove(identifier)
                        print(header)
                        continue
        f.close()

    
    # Create columns for data frame 
    fasta["Header"] = headers
    fasta["Isolate_Id"] = isolate_ids
    fasta["Isolate_Name"] = isolate_names
    fasta["Subtype"] = subtypes
    fasta["Segment"] = segments
    fasta["Location_Header"] = locations
    # Geo_Location is more complicated
    try:
        fasta["Geo_Location"] = fasta["Location_Header"].apply( lambda x: x.split(" / ")[1] if x.split(" / ") == "Europe" else x.split(" / ")[0])
    except:
        print("Geo Location not found.")
        fasta["Geo_Location"] = fasta["Location_Header"]
    fasta["Date Collected"] = collection_dates
    fasta["Date Collected"] = fasta["Date Collected"].apply(lambda x: str(dateutil.parser.parse(x, default=dateutil.parser.parse("2000-01-01")).year) if dateutil.parser.parse(x, default=dateutil.parser.parse("2000-01-01")).month == dateutil.parser.parse("2000-01-01").month and dateutil.parser.parse(x, default=dateutil.parser.parse("2000-01-01")).day == dateutil.parser.parse("2000-01-01").day else x)
    fasta["Species"] = species
    # fasta["Host_Type"] = host_types
    # fasta["Genotype"] = genotypes
    fasta["Sequence"] = sequences
    # if len(identifiers) == len(fasta):
    fasta["Identifier"] = identifiers
        
    return fasta

In [45]:
# GISAID

os.chdir(downloads_saved + "Y2K_swine/")

gisaid_metadata = pd.read_excel("gisaid_epiflu_isolates.xls")

gisaid_fasta = fasta_df("gisaid_epiflu_sequence.fasta")

# gisaid_metadata
genotypes = list(set(gisaid_metadata["Genotype"].values))

# Separate fastas by segment
fastas, unique_segments = separate_fasta_by_segs(gisaid_metadata, gisaid_fasta, animals_ref, genotypes) # Separate the fasta dataframes into 8 different files based on segment
    # print(fastas[0])

Not assigned
            Identifier                                     PB2 Segment_Id  \
0     EPI_ISL_20177958  EPI4714739|PB2_25-08089-O-ms_AS-140905_250909_...
1     EPI_ISL_20177957  EPI4714731|PB2_25-08088-O-ms_AS-140904_250909_...
2     EPI_ISL_20177956  EPI4714723|PB2_25-08087-O-ms_AS-140903_250909_...
3     EPI_ISL_20177955  EPI4714715|PB2_25-08086-O-ms_AS-140902_250909_...
4     EPI_ISL_20177953  EPI4714701|PB2_25-07574-O-ms_AS-140896_250909_...
...                ...                                                ...
3374  EPI_ISL_19546010                        EPI3645891|2024-wk42-04_PB2
3375  EPI_ISL_19546009                        EPI3645883|2024-wk42-02_PB2
3376  EPI_ISL_19546008                        EPI3645875|2024-wk42-01_PB2
3377  EPI_ISL_16074739                 EPI2240800|A/Navarra/4050/2022_PB2
3378  EPI_ISL_19459695      EPI3585864|A/Catalonia/NSAV198309324_PB2/2024

                                         PB1 Segment_Id  \
0     EPI4714740|PB1_25-08089-O-ms_AS-140905_250909_...
1     EPI4714732|PB1_25-08088-O-ms_AS-140904_250909_...
2     EPI4714724|PB1_25-08087-O-ms_AS-140903_250909_...
3     EPI4714716|PB1_25-08086-O-ms_AS-140902_250909_...
4     EPI4714702|PB1_25-07574-O-ms_AS-140896_250909_...
...                                                 ...
3374                        EPI3645892|2024-wk42-04_PB1
3375                        EPI3645884|2024-wk42-02_PB1
3376                        EPI3645876|2024-wk42-01_PB1
3377                 EPI2240801|A/Navarra/4050/2022_PB1
3378      EPI3585865|A/Catalonia/NSAV198309324_PB1/2024

                                          PA Segment_Id  \
0     EPI4714738|PA_25-08089-O-ms_AS-140905_250909_S...
1     EPI4714730|PA_25-08088-O-ms_AS-140904_250909_S...
2     EPI4714722|PA_25-08087-O-ms_AS-140903_250909_S...
3     EPI4714714|PA_25-08086-O-ms_AS-140902_250909_S...
4     EPI4714700|PA_25-07574-O-ms_AS-140896_250909_S...
...                                                 ...
3374                         EPI3645890|2024-wk42-04_PA
3375                         EPI3645882|2024-wk42-02_PA
3376                         EPI3645874|2024-wk42-01_PA
3377                  EPI2240799|A/Navarra/4050/2022_PA
3378       EPI3585863|A/Catalonia/NSAV198309324_PA/2024

                                          HA Segment_Id  \
0     EPI4714742|HA_25-08089-O-ms_AS-140905_250909_S...
1     EPI4714734|HA_25-08088-O-ms_AS-140904_250909_S...
2     EPI4714726|HA_25-08087-O-ms_AS-140903_250909_S...
3     EPI4714718|HA_25-08086-O-ms_AS-140902_250909_S...
4     EPI4714704|HA_25-07574-O-ms_AS-140896_250909_S...
...                                                 ...
3374                         EPI3645894|2024-wk42-04_HA
3375                         EPI3645886|2024-wk42-02_HA
3376                         EPI3645878|2024-wk42-01_HA
3377                  EPI2240803|A/Navarra/4050/2022_HA
3378       EPI3585867|A/Catalonia/NSAV198309324_HA/2024

                                          NP Segment_Id  \
0     EPI4714735|NP_25-08089-O-ms_AS-140905_250909_S...
1     EPI4714727|NP_25-08088-O-ms_AS-140904_250909_S...
2     EPI4714719|NP_25-08087-O-ms_AS-140903_250909_S...
3     EPI4714711|NP_25-08086-O-ms_AS-140902_250909_S...
4     EPI4714697|NP_25-07574-O-ms_AS-140896_250909_S...
...                                                 ...
3374                         EPI3645887|2024-wk42-04_NP
3375                         EPI3645879|2024-wk42-02_NP
3376                         EPI3645871|2024-wk42-01_NP
3377                  EPI2240796|A/Navarra/4050/2022_NP
3378       EPI3585860|A/Catalonia/NSAV198309324_NP/2024

                                          NA Segment_Id  \
0     EPI4714741|NA_25-08089-O-ms_AS-140905_250909_S...
1     EPI4714733|NA_25-08088-O-ms_AS-140904_250909_S...
2     EPI4714725|NA_25-08087-O-ms_AS-140903_250909_S...
3     EPI4714717|NA_25-08086-O-ms_AS-140902_250909_S...
4     EPI4714703|NA_25-07574-O-ms_AS-140896_250909_S...
...                                                 ...
3374                         EPI3645893|2024-wk42-04_NA
3375                         EPI3645885|2024-wk42-02_NA
3376                         EPI3645877|2024-wk42-01_NA
3377                  EPI2240802|A/Navarra/4050/2022_NA
3378       EPI3585866|A/Catalonia/NSAV198309324_NA/2024

                                          MP Segment_Id  \
0     EPI4714737|M_25-08089-O-ms_AS-140905_250909_S1...
1     EPI4714729|M_25-08088-O-ms_AS-140904_250909_S1...
2     EPI4714721|M_25-08087-O-ms_AS-140903_250909_S1...
3     EPI4714713|M_25-08086-O-ms_AS-140902_250909_S1...
4     EPI4714699|M_25-07574-O-ms_AS-140896_250909_S2...
...                                                 ...
3374                         EPI3645889|2024-wk42-04_MP
3375                         EPI3645881|2024-wk42-02_MP
3376                         EPI3645873|2024-wk42-01_MP
3377                  EPI2240798|A/Navarra/4050/2022_MP
3378       EPI3585862|A/Catalonia/NSAV198309324_MP/2024

                                          NS Segment_Id  HE Segment_Id  ...  \
0     EPI4714736|NS_25-08089-O-ms_AS-140905_250909_S...            NaN  ...
1     EPI4714728|NS_25-08088-O-ms_AS-140904_250909_S...            NaN  ...
2     EPI4714720|NS_25-08087-O-ms_AS-140903_250909_S...            NaN  ...
3     EPI4714712|NS_25-08086-O-ms_AS-140902_250909_S...            NaN  ...
4     EPI4714698|NS_25-07574-O-ms_AS-140896_250909_S...            NaN  ...
...                                                 ...            ...  ...
3374                         EPI3645888|2024-wk42-04_NS            NaN  ...
3375                         EPI3645880|2024-wk42-02_NS            NaN  ...
3376                         EPI3645872|2024-wk42-01_NS            NaN  ...
3377                  EPI2240797|A/Navarra/4050/2022_NS            NaN  ...
3378       EPI3585861|A/Catalonia/NSAV198309324_NS/2024            NaN  ...

      Patient_Status Zip_Code Outbreak Pathogen_Test_Info Is_Vaccinated  \
0                NaN      NaN      NaN                NaN           NaN
1                NaN      NaN      NaN                NaN           NaN
2                NaN      NaN      NaN                NaN           NaN
3                NaN      NaN      NaN                NaN           NaN
4                NaN      NaN      NaN                NaN           NaN
...              ...      ...      ...                ...           ...
3374             NaN      NaN      NaN                NaN           NaN
3375             NaN      NaN      NaN                NaN           NaN
3376             NaN      NaN      NaN                NaN           NaN
3377      In-patient      NaN      NaN                NaN           NaN
3378             NaN      NaN      NaN                NaN           NaN

     Human_Specimen_Source Animal_Specimen_Source Animal_Health_Status  \
0                      NaN                    NaN                  NaN
1                      NaN                    NaN                  NaN
2                      NaN                    NaN                  NaN
3                      NaN                    NaN                  NaN
4                      NaN                    NaN                  NaN
...                    ...                    ...                  ...
3374                   NaN                    NaN                  NaN
3375                   NaN                    NaN                  NaN
3376                   NaN                    NaN                  NaN
3377                   NaN                    NaN                  NaN
3378                   NaN                    NaN                  NaN

     Domestic_Status PMID
0                NaN  NaN
1                NaN  NaN
2                NaN  NaN
3                NaN  NaN
4                NaN  NaN
...              ...  ...
3374             NaN  NaN
3375             NaN  NaN
3376             NaN  NaN
3377             NaN  NaN
3378             NaN  NaN

[3379 rows x 53 columns]
Index(['Header', 'Isolate_Id', 'Isolate_Name_x', 'Subtype_x', 'Segment',
       'Location_Header', 'Geo_Location', 'Date Collected', 'Species',
       'Sequence', 'Identifier', 'Host_Type', 'PB2 Segment_Id',
       'PB1 Segment_Id', 'PA Segment_Id', 'HA Segment_Id', 'NP Segment_Id',
       'NA Segment_Id', 'MP Segment_Id', 'NS Segment_Id', 'HE Segment_Id',
       'P3 Segment_Id', 'Isolate_Name_y', 'Subtype_y', 'Genotype', 'Lineage',
       'Clade', 'Pathogenicity', 'Passage_History', 'Location', 'Host',
       'Isolate_Submitter', 'Submitting_Sample_Id', 'Publication',
       'Originating_Sample_Id', 'Collection_Date', 'Note', 'Update_Date',
       'Submission_Date', 'Antigen_Character', 'Animal_Vaccin_Product',
       'Adamantanes_Resistance_geno', 'Oseltamivir_Resistance_geno',
       'Zanamivir_Resistance_geno', 'Peramivir_Resistance_geno',
       'Other_Resistance_geno', 'Adamantanes_Resistance_pheno',
       'Oseltamivir_Resistance_pheno', 'Zanamivir_Resistance_pheno',
       'Peramivir_Resistance_pheno', 'Other_Resistance_pheno', 'Host_Age',
       'Host_Age_Unit', 'Host_Gender', 'Patient_Status', 'Zip_Code',
       'Outbreak', 'Pathogen_Test_Info', 'Is_Vaccinated',
       'Human_Specimen_Source', 'Animal_Specimen_Source',
       'Animal_Health_Status', 'Domestic_Status', 'PMID'],
      dtype='object')
                                                  Header     Isolate_Id  \
4      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...           R313
12     EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...           R318
21     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|P...             18
26     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...          17671
35     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...            113
...                                                  ...            ...
26996  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...           R309
27004  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...         AR1026
27012  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...           R312
27019  EPI_ISL_16074739|A/Navarra/4050/2022|A_/_H1N1|...           4050
27027  EPI_ISL_19459695|A/Catalonia/NSAV198309324/202...  NSAV198309324

                             Isolate_Name_x Subtype_x Segment  \
4                 A/swine/Germany/R313/2015      H1N2      PA
12                A/swine/Germany/R318/2015      H1N2      PA
21                    A/swine/Italy/18/2000      H1N2      PA
26        A/swine/Czech_Republic/17671/2023      H1N2      PA
35     A/swine/Nordrhein-Westfalen/113/2024      H1N2      PA
...                                     ...       ...     ...
26996             A/swine/Germany/R309/2015      H1N2      PA
27004           A/swine/Germany/AR1026/2016      H1N1      PA
27012             A/swine/Germany/R312/2015      H1N1      PA
27019                   A/Navarra/4050/2022      H1N1      PA
27027        A/Catalonia/NSAV198309324/2024      H1N1      PA

           Location_Header         Geo_Location Date Collected    Species  \
4                  Germany              Germany           2014      swine
12                 Germany              Germany           2014      swine
21                   Italy                Italy     2000-01-03      swine
26          Czech_Republic       Czech_Republic     2023-11-13      swine
35     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20      swine
...                    ...                  ...            ...        ...
26996              Germany              Germany           2014      swine
27004              Germany              Germany     2016-02-17      swine
27012              Germany              Germany           2014      swine
27019              Navarra              Navarra     2022-10-17    Navarra
27027            Catalonia            Catalonia     2024-10-01  Catalonia

                                                Sequence  ... Zip_Code  \
4      cattcacatcttttcattcactggagaggagattgccaccaaagcg...  ...      NaN
12     aaatggccagtaggagtctatgggattcctttcgtcagtccgaaag...  ...      NaN
21     tgattcaaaatggaagactttgtgcgacaatgcttcaatccaatga...  ...      NaN
26     tgatccaaaatggaagactttgtgcgacaatgcttcaatccaatga...  ...      NaN
35     atggaagactttgtgcgacaatgcttcaacccaatgattgtcgagc...  ...      NaN
...                                                  ...  ...      ...
26996  atggaagactttgtgcgacaatgcttcaacccaatggtcgtcgagc...  ...      NaN
27004  atggaagactttgtgcgacaatgcttcaatccaatggtcgtcgagc...  ...      NaN
27012  atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  ...      NaN
27019  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...  ...      NaN
27027  gtactgatccaaaatggaagactttgtgcgacagtgcttcaatcca...  ...      NaN

      Outbreak Pathogen_Test_Info Is_Vaccinated Human_Specimen_Source  \
4          NaN                NaN           NaN                   NaN
12         NaN                NaN           NaN                   NaN
21         NaN                NaN           0.0                   NaN
26         NaN                NaN           NaN                   NaN
35         NaN                NaN           NaN                   NaN
...        ...                ...           ...                   ...
26996      NaN                NaN           NaN                   NaN
27004      NaN                NaN           NaN                   NaN
27012      NaN                NaN           NaN                   NaN
27019      NaN                NaN           NaN                   NaN
27027      NaN                NaN           NaN                   NaN

      Animal_Specimen_Source Animal_Health_Status Domestic_Status PMID  \
4                        NaN                  NaN             NaN  NaN
12                       NaN                  NaN             NaN  NaN
21                       NaN                  NaN             NaN  NaN
26                Nasal swab                  NaN        Domestic  NaN
35                       NaN                  NaN             NaN  NaN
...                      ...                  ...             ...  ...
26996                    NaN                  NaN             NaN  NaN
27004    Oro-pharyngeal swab                 Sick        Domestic  NaN
27012                    NaN                  NaN             NaN  NaN
27019                    NaN                  NaN             NaN  NaN
27027                    NaN                  NaN             NaN  NaN

                                                New_Name
4      >EPI_ISL_245764|A/swine/Germany/R313/2015|H1N2...
12     >EPI_ISL_245771|A/swine/Germany/R318/2015|H1N2...
21     >EPI_ISL_73783|A/swine/Italy/18/2000|H1N2|Ital...
26     >EPI_ISL_18604439|A/swine/Czech_Republic/17671...
35     >EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/...
...                                                  ...
26996  >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
27004  >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
27012  >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
27019  >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
27027  >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...

[3379 rows x 65 columns]
            Identifier                                     PB2 Segment_Id  \
0     EPI_ISL_20177958  EPI4714739|PB2_25-08089-O-ms_AS-140905_250909_...
1     EPI_ISL_20177957  EPI4714731|PB2_25-08088-O-ms_AS-140904_250909_...
2     EPI_ISL_20177956  EPI4714723|PB2_25-08087-O-ms_AS-140903_250909_...
3     EPI_ISL_20177955  EPI4714715|PB2_25-08086-O-ms_AS-140902_250909_...
4     EPI_ISL_20177953  EPI4714701|PB2_25-07574-O-ms_AS-140896_250909_...
...                ...                                                ...
3374  EPI_ISL_19546010                        EPI3645891|2024-wk42-04_PB2
3375  EPI_ISL_19546009                        EPI3645883|2024-wk42-02_PB2
3376  EPI_ISL_19546008                        EPI3645875|2024-wk42-01_PB2
3377  EPI_ISL_16074739                 EPI2240800|A/Navarra/4050/2022_PB2
3378  EPI_ISL_19459695      EPI3585864|A/Catalonia/NSAV198309324_PB2/2024

                                         PB1 Segment_Id  \
0     EPI4714740|PB1_25-08089-O-ms_AS-140905_250909_...
1     EPI4714732|PB1_25-08088-O-ms_AS-140904_250909_...
2     EPI4714724|PB1_25-08087-O-ms_AS-140903_250909_...
3     EPI4714716|PB1_25-08086-O-ms_AS-140902_250909_...
4     EPI4714702|PB1_25-07574-O-ms_AS-140896_250909_...
...                                                 ...
3374                        EPI3645892|2024-wk42-04_PB1
3375                        EPI3645884|2024-wk42-02_PB1
3376                        EPI3645876|2024-wk42-01_PB1
3377                 EPI2240801|A/Navarra/4050/2022_PB1
3378      EPI3585865|A/Catalonia/NSAV198309324_PB1/2024

                                          PA Segment_Id  \
0     EPI4714738|PA_25-08089-O-ms_AS-140905_250909_S...
1     EPI4714730|PA_25-08088-O-ms_AS-140904_250909_S...
2     EPI4714722|PA_25-08087-O-ms_AS-140903_250909_S...
3     EPI4714714|PA_25-08086-O-ms_AS-140902_250909_S...
4     EPI4714700|PA_25-07574-O-ms_AS-140896_250909_S...
...                                                 ...
3374                         EPI3645890|2024-wk42-04_PA
3375                         EPI3645882|2024-wk42-02_PA
3376                         EPI3645874|2024-wk42-01_PA
3377                  EPI2240799|A/Navarra/4050/2022_PA
3378       EPI3585863|A/Catalonia/NSAV198309324_PA/2024

                                          HA Segment_Id  \
0     EPI4714742|HA_25-08089-O-ms_AS-140905_250909_S...
1     EPI4714734|HA_25-08088-O-ms_AS-140904_250909_S...
2     EPI4714726|HA_25-08087-O-ms_AS-140903_250909_S...
3     EPI4714718|HA_25-08086-O-ms_AS-140902_250909_S...
4     EPI4714704|HA_25-07574-O-ms_AS-140896_250909_S...
...                                                 ...
3374                         EPI3645894|2024-wk42-04_HA
3375                         EPI3645886|2024-wk42-02_HA
3376                         EPI3645878|2024-wk42-01_HA
3377                  EPI2240803|A/Navarra/4050/2022_HA
3378       EPI3585867|A/Catalonia/NSAV198309324_HA/2024

                                          NP Segment_Id  \
0     EPI4714735|NP_25-08089-O-ms_AS-140905_250909_S...
1     EPI4714727|NP_25-08088-O-ms_AS-140904_250909_S...
2     EPI4714719|NP_25-08087-O-ms_AS-140903_250909_S...
3     EPI4714711|NP_25-08086-O-ms_AS-140902_250909_S...
4     EPI4714697|NP_25-07574-O-ms_AS-140896_250909_S...
...                                                 ...
3374                         EPI3645887|2024-wk42-04_NP
3375                         EPI3645879|2024-wk42-02_NP
3376                         EPI3645871|2024-wk42-01_NP
3377                  EPI2240796|A/Navarra/4050/2022_NP
3378       EPI3585860|A/Catalonia/NSAV198309324_NP/2024

                                          NA Segment_Id  \
0     EPI4714741|NA_25-08089-O-ms_AS-140905_250909_S...
1     EPI4714733|NA_25-08088-O-ms_AS-140904_250909_S...
2     EPI4714725|NA_25-08087-O-ms_AS-140903_250909_S...
3     EPI4714717|NA_25-08086-O-ms_AS-140902_250909_S...
4     EPI4714703|NA_25-07574-O-ms_AS-140896_250909_S...
...                                                 ...
3374                         EPI3645893|2024-wk42-04_NA
3375                         EPI3645885|2024-wk42-02_NA
3376                         EPI3645877|2024-wk42-01_NA
3377                  EPI2240802|A/Navarra/4050/2022_NA
3378       EPI3585866|A/Catalonia/NSAV198309324_NA/2024

                                          MP Segment_Id  \
0     EPI4714737|M_25-08089-O-ms_AS-140905_250909_S1...
1     EPI4714729|M_25-08088-O-ms_AS-140904_250909_S1...
2     EPI4714721|M_25-08087-O-ms_AS-140903_250909_S1...
3     EPI4714713|M_25-08086-O-ms_AS-140902_250909_S1...
4     EPI4714699|M_25-07574-O-ms_AS-140896_250909_S2...
...                                                 ...
3374                         EPI3645889|2024-wk42-04_MP
3375                         EPI3645881|2024-wk42-02_MP
3376                         EPI3645873|2024-wk42-01_MP
3377                  EPI2240798|A/Navarra/4050/2022_MP
3378       EPI3585862|A/Catalonia/NSAV198309324_MP/2024


### De-duplication

In [47]:
# De-duplicate from GenBank

gisaid_fastas = []
for fasta in fastas:
    # print(fasta)
    for serotype in serotypes:
        # print(serotype)
        m_g_s = fasta[fasta["Subtype_x"].str.contains(serotype)]
        m_g_s["Serotype"] = serotype
        if len(m_g_s) > 0:
            # Check to see if isolate is already in GenBank
            print(m_g_s)
            m_g_s["Isolate"] = m_g_s["Isolate_Id"]
            metadata_genoflu["Isolate"] = metadata_genoflu["Isolate_x"]
            exp_df = metadata_genoflu.merge(m_g_s, on="Isolate", how="right", indicator=True)
            # print(exp_df)
            exp_df["New_Name"] = exp_df[exp_df["_merge"] == "right_only"]["New_Name"].apply(lambda x: x.replace("other_mammal", "Iberian_swine") if x.split("/")[3] in iberian_swine else x.replace("other_mammal", "swine") if "sw" in x.lower() or "scrofa" in x.lower() else x)
            exp_df = exp_df[exp_df["_merge"] == "right_only"]
            exp_df["New_Name"] = exp_df["New_Name"].apply(lambda x: "|".join(x.split("|")[:-1]))
            exp_df = exp_df.drop_duplicates(subset="New_Name", keep="first")
            gisaid_fastas.append(exp_df)

                                                  Header     Isolate_Id  \
4      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...           R313
12     EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...           R318
21     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|P...             18
26     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...          17671
35     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...            113
...                                                  ...            ...
26996  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...           R309
27004  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...         AR1026
27012  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...           R312
27019  EPI_ISL_16074739|A/Navarra/4050/2022|A_/_H1N1|...           4050
27027  EPI_ISL_19459695|A/Catalonia/NSAV198309324/202...  NSAV198309324

                             Isolate_Name_x Subtype_x Segment  \
4                 A/swine/Germany/R313/2015      H1N2      PA
12                A/swine/Germany/R318/2015      H1N2      PA
21                    A/swine/Italy/18/2000      H1N2      PA
26        A/swine/Czech_Republic/17671/2023      H1N2      PA
35     A/swine/Nordrhein-Westfalen/113/2024      H1N2      PA
...                                     ...       ...     ...
26996             A/swine/Germany/R309/2015      H1N2      PA
27004           A/swine/Germany/AR1026/2016      H1N1      PA
27012             A/swine/Germany/R312/2015      H1N1      PA
27019                   A/Navarra/4050/2022      H1N1      PA
27027        A/Catalonia/NSAV198309324/2024      H1N1      PA

           Location_Header         Geo_Location Date Collected    Species  \
4                  Germany              Germany           2014      swine
12                 Germany              Germany           2014      swine
21                   Italy                Italy     2000-01-03      swine
26          Czech_Republic       Czech_Republic     2023-11-13      swine
35     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20      swine
...                    ...                  ...            ...        ...
26996              Germany              Germany           2014      swine
27004              Germany              Germany     2016-02-17      swine
27012              Germany              Germany           2014      swine
27019              Navarra              Navarra     2022-10-17    Navarra
27027            Catalonia            Catalonia     2024-10-01  Catalonia

                                                Sequence  ... Outbreak  \
4      cattcacatcttttcattcactggagaggagattgccaccaaagcg...  ...      NaN
12     aaatggccagtaggagtctatgggattcctttcgtcagtccgaaag...  ...      NaN
21     tgattcaaaatggaagactttgtgcgacaatgcttcaatccaatga...  ...      NaN
26     tgatccaaaatggaagactttgtgcgacaatgcttcaatccaatga...  ...      NaN
35     atggaagactttgtgcgacaatgcttcaacccaatgattgtcgagc...  ...      NaN
...                                                  ...  ...      ...
26996  atggaagactttgtgcgacaatgcttcaacccaatggtcgtcgagc...  ...      NaN
27004  atggaagactttgtgcgacaatgcttcaatccaatggtcgtcgagc...  ...      NaN
27012  atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  ...      NaN
27019  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...  ...      NaN
27027  gtactgatccaaaatggaagactttgtgcgacagtgcttcaatcca...  ...      NaN

      Pathogen_Test_Info Is_Vaccinated Human_Specimen_Source  \
4                    NaN           NaN                   NaN
12                   NaN           NaN                   NaN
21                   NaN           0.0                   NaN
26                   NaN           NaN                   NaN
35                   NaN           NaN                   NaN
...                  ...           ...                   ...
26996                NaN           NaN                   NaN
27004                NaN           NaN                   NaN
27012                NaN           NaN                   NaN
27019                NaN           NaN                   NaN
27027                NaN           NaN                   NaN

      Animal_Specimen_Source Animal_Health_Status Domestic_Status PMID  \
4                        NaN                  NaN             NaN  NaN
12                       NaN                  NaN             NaN  NaN
21                       NaN                  NaN             NaN  NaN
26                Nasal swab                  NaN        Domestic  NaN
35                       NaN                  NaN             NaN  NaN
...                      ...                  ...             ...  ...
26996                    NaN                  NaN             NaN  NaN
27004    Oro-pharyngeal swab                 Sick        Domestic  NaN
27012                    NaN                  NaN             NaN  NaN
27019                    NaN                  NaN             NaN  NaN
27027                    NaN                  NaN             NaN  NaN

                                                New_Name Serotype
4      >EPI_ISL_245764|A/swine/Germany/R313/2015|H1N2...       H1
12     >EPI_ISL_245771|A/swine/Germany/R318/2015|H1N2...       H1
21     >EPI_ISL_73783|A/swine/Italy/18/2000|H1N2|Ital...       H1
26     >EPI_ISL_18604439|A/swine/Czech_Republic/17671...       H1
35     >EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/...       H1
...                                                  ...      ...
26996  >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...       H1
27004  >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...       H1
27012  >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...       H1
27019  >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...       H1
27027  >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...       H1

[2960 rows x 66 columns]
                                                  Header Isolate_Id  \
330    EPI_ISL_278824|A/swine/Italy/229049/2015|A_/_H...     229049
337    EPI_ISL_19644422|A/swine/Italy/430612/2022|A_/...     430612
362    EPI_ISL_278826|A/swine/Italy/240849/2015|A_/_H...     240849
370    EPI_ISL_278827|A/swine/Italy/248147-8/2015|A_/...   248147-8
450    EPI_ISL_278844|A/swine/Italy/1103/2015|A_/_H3N...       1103
...                                                  ...        ...
26657  EPI_ISL_19644399|A/swine/Italy/35820/2022|A_/_...      35820
26816  EPI_ISL_163606|A/swine/Italy/187969/2013|A_/_H...     187969
26824  EPI_ISL_163607|A/swine/Italy/250481_2/2013|A_/...   250481_2
26832  EPI_ISL_163604|A/swine/Italy/311349/2013|A_/_H...     311349
26840  EPI_ISL_163605|A/swine/Italy/282811/2013|A_/_H...     282811

                    Isolate_Name_x Subtype_x Segment Location_Header  \
330      A/swine/Italy/229049/2015      H3N2      PA           Italy
337      A/swine/Italy/430612/2022      H3N2      PA           Italy
362      A/swine/Italy/240849/2015      H3N2      PA           Italy
370    A/swine/Italy/248147-8/2015      H3N2      PA           Italy
450        A/swine/Italy/1103/2015      H3N2      PA           Italy
...                            ...       ...     ...             ...
26657     A/swine/Italy/35820/2022      H3N2      PA           Italy
26816    A/swine/Italy/187969/2013      H3N2      PA           Italy
26824  A/swine/Italy/250481_2/2013      H3N2      PA           Italy
26832    A/swine/Italy/311349/2013      H3N2      PA           Italy
26840    A/swine/Italy/282811/2013      H3N2      PA           Italy

      Geo_Location Date Collected Species  \
330          Italy     2015-09-01   swine
337          Italy     2022-12-01   swine
362          Italy     2015-09-01   swine
370          Italy     2015-09-01   swine
450          Italy     2015-09-01   swine
...            ...            ...     ...
26657        Italy           2022   swine
26816        Italy     2013-07-01   swine
26824        Italy     2013-09-01   swine
26832        Italy     2013-11-01   swine
26840        Italy     2013-10-01   swine

                                                Sequence  ... Outbreak  \
330    atggaagactttgtgcgacagtgcttcaatccaatgatcgtcgagc...  ...      NaN
337    atggaagactttgtgcgacaatgcttcaacccaatgattgtcgagc...  ...      NaN
362    atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  ...      NaN
370    atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  ...      NaN
450    atggaagactttgtgcgacagtgcttcaatccaatgatcgtcgagc...  ...      NaN
...                                                  ...  ...      ...
26657  atggaagacttcgtgcgacaatgtttcaatccaatgattgtcgagc...  ...      NaN
26816  atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  ...      NaN
26824  atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  ...      NaN
26832  atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  ...      NaN
26840  atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  ...      NaN

      Pathogen_Test_Info Is_Vaccinated Human_Specimen_Source  \
330                  NaN           NaN                   NaN
337                  NaN           NaN                   NaN
362                  NaN           NaN                   NaN
370                  NaN           NaN                   NaN
450                  NaN           NaN                   NaN
...                  ...           ...                   ...
26657                NaN           NaN                   NaN
26816                NaN           NaN                   NaN
26824                NaN           NaN                   NaN
26832                NaN           NaN                   NaN
26840                NaN           NaN                   NaN

      Animal_Specimen_Source Animal_Health_Status Domestic_Status PMID  \
330                      NaN                  NaN             NaN  NaN
337                      NaN                  NaN             NaN  NaN
362                      NaN                  NaN             NaN  NaN
370                      NaN                  NaN             NaN  NaN
450                      NaN                  NaN             NaN  NaN
...                      ...                  ...             ...  ...
26657                    NaN                  NaN             NaN  NaN
26816                    NaN                  NaN             NaN  NaN
26824                    NaN                  NaN             NaN  NaN
26832                    NaN                  NaN             NaN  NaN
26840                    NaN                  NaN             NaN  NaN

                                                New_Name Serotype
330    >EPI_ISL_278824|A/swine/Italy/229049/2015|H3N2...       H3
337    >EPI_ISL_19644422|A/swine/Italy/430612/2022|H3...       H3
362    >EPI_ISL_278826|A/swine/Italy/240849/2015|H3N2...       H3
370    >EPI_ISL_278827|A/swine/Italy/248147-8/2015|H3...       H3
450    >EPI_ISL_278844|A/swine/Italy/1103/2015|H3N2|I...       H3
...                                                  ...      ...
26657  >EPI_ISL_19644399|A/swine/Italy/35820/2022|H3N...       H3
26816  >EPI_ISL_163606|A/swine/Italy/187969/2013|H3N2...       H3
26824  >EPI_ISL_163607|A/swine/Italy/250481_2/2013|H3...       H3
26832  >EPI_ISL_163604|A/swine/Italy/311349/2013|H3N2...       H3
26840  >EPI_ISL_163605|A/swine/Italy/282811/2013|H3N2...       H3

[419 rows x 66 columns]
                                                  Header     Isolate_Id  \
57     EPI_ISL_19751421|A/swine/Denmark/LF22-7167-3/2...    LF22-7167-3
73     EPI_ISL_19751423|A/swine/Denmark/LF22-7302-1/2...    LF22-7302-1
81     EPI_ISL_19751422|A/swine/Denmark/LF22-7300-3/2...    LF22-7300-3
89     EPI_ISL_19751417|A/swine/Denmark/LF22-6877-4/2...    LF22-6877-4
113    EPI_ISL_19751418|A/swine/Denmark/LF22-6907-1/2...    LF22-6907-1
...                                                  ...            ...
26988  EPI_ISL_245726|A/swine/Germany/R1696/2014|A_/_...          R1696
27004  EPI_ISL_237542|A/swine/Germany/AR1026/2016|A_/...         AR1026
27012  EPI_ISL_245748|A/swine/Germany/R312/2015|A_/_H...           R312
27019  EPI_ISL_16074739|A/Navarra/4050/2022|A_/_H1N1|...           4050
27027  EPI_ISL_19459695|A/Catalonia/NSAV198309324/202...  NSAV198309324

                         Isolate_Name_x Subtype_x Segment Location_Header  \
57     A/swine/Denmark/LF22-7167-3/2022      H1N1      PA         Denmark
73     A/swine/Denmark/LF22-7302-1/2022      H1N1      PA         Denmark
81     A/swine/Denmark/LF22-7300-3/2022      H1N1      PA         Denmark
89     A/swine/Denmark/LF22-6877-4/2022      H1N1      PA         Denmark
113    A/swine/Denmark/LF22-6907-1/2022      H1N1      PA         Denmark
...                                 ...       ...     ...             ...
26988        A/swine/Germany/R1696/2014      H1N1      PA         Germany
27004       A/swine/Germany/AR1026/2016      H1N1      PA         Germany
27012         A/swine/Germany/R312/2015      H1N1      PA         Germany
27019               A/Navarra/4050/2022      H1N1      PA         Navarra
27027    A/Catalonia/NSAV198309324/2024      H1N1      PA       Catalonia

      Geo_Location Date Collected    Species  \
57         Denmark           2022      swine
73         Denmark           2022      swine
81         Denmark           2022      swine
89         Denmark           2022      swine
113        Denmark           2022      swine
...            ...            ...        ...
26988      Germany           2014      swine
27004      Germany     2016-02-17      swine
27012      Germany           2014      swine
27019      Navarra     2022-10-17    Navarra
27027    Catalonia     2024-10-01  Catalonia

                                                Sequence  ... Outbreak  \
57     agcaaaagcaggtactgatccaaaatggaagactttgtgcgacaat...  ...      NaN
73     agcaaaagcaggtactgattcaaaatggaagactttgtgcgacaat...  ...      NaN
81     agcaaaagcaggtactgacacaaaatggaagactttgtgcgacaat...  ...      NaN
89     agcaaaagcaggtactgatccaaaatggaagactttgtgcgacaat...  ...      NaN
113    agcaaaagcaggtactgatccaaaatggaagactttgtgcgacaat...  ...      NaN
...                                                  ...  ...      ...
26988  atggaagacttcgtgcgacagtgcttcaatccaatgatcgtcgagc...  ...      NaN
27004  atggaagactttgtgcgacaatgcttcaatccaatggtcgtcgagc...  ...      NaN
27012  atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  ...      NaN
27019  atggaagactttgtgcgacaatgcttcaatccaatgattgtcgagc...  ...      NaN
27027  gtactgatccaaaatggaagactttgtgcgacagtgcttcaatcca...  ...      NaN

      Pathogen_Test_Info Is_Vaccinated Human_Specimen_Source  \
57                   NaN           NaN                   NaN
73                   NaN           NaN                   NaN
81                   NaN           NaN                   NaN
89                   NaN           NaN                   NaN
113                  NaN           NaN                   NaN
...                  ...           ...                   ...
26988                NaN           NaN                   NaN
27004                NaN           NaN                   NaN
27012                NaN           NaN                   NaN
27019                NaN           NaN                   NaN
27027                NaN           NaN                   NaN

      Animal_Specimen_Source Animal_Health_Status Domestic_Status PMID  \
57                Nasal swab                  NaN             NaN  NaN
73                Nasal swab                  NaN             NaN  NaN
81                Nasal swab                  NaN             NaN  NaN
89                Nasal swab                  NaN             NaN  NaN
113               Nasal swab                  NaN             NaN  NaN
...                      ...                  ...             ...  ...
26988                    NaN                  NaN             NaN  NaN
27004    Oro-pharyngeal swab                 Sick        Domestic  NaN
27012                    NaN                  NaN             NaN  NaN
27019                    NaN                  NaN             NaN  NaN
27027                    NaN                  NaN             NaN  NaN

                                                New_Name Serotype
57     >EPI_ISL_19751421|A/swine/Denmark/LF22-7167-3/...       N1
73     >EPI_ISL_19751423|A/swine/Denmark/LF22-7302-1/...       N1
81     >EPI_ISL_19751422|A/swine/Denmark/LF22-7300-3/...       N1
89     >EPI_ISL_19751417|A/swine/Denmark/LF22-6877-4/...       N1
113    >EPI_ISL_19751418|A/swine/Denmark/LF22-6907-1/...       N1
...                                                  ...      ...
26988  >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...       N1
27004  >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...       N1
27012  >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...       N1
27019  >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...       N1
27027  >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...       N1

[1618 rows x 66 columns]
                                                  Header Isolate_Id  \
4      EPI_ISL_245764|A/swine/Germany/R313/2015|A_/_H...       R313
12     EPI_ISL_245771|A/swine/Germany/R318/2015|A_/_H...       R318
21     EPI_ISL_73783|A/swine/Italy/18/2000|A_/_H1N2|P...         18
26     EPI_ISL_18604439|A/swine/Czech_Republic/17671/...      17671
35     EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/1...        113
...                                                  ...        ...
26932  EPI_ISL_245695|A/swine/Germany/R825/2014|A_/_H...       R825
26940  EPI_ISL_245699|A/swine/Germany/R1143/2014|A_/_...      R1143
26948  EPI_ISL_245697|A/swine/Germany/R916/2014|A_/_H...       R916
26972  EPI_ISL_245704|A/swine/Germany/R1190/2014|A_/_...      R1190
26996  EPI_ISL_245731|A/swine/Germany/R309/2015|A_/_H...       R309

                             Isolate_Name_x Subtype_x Segment  \
4                 A/swine/Germany/R313/2015      H1N2      PA
12                A/swine/Germany/R318/2015      H1N2      PA
21                    A/swine/Italy/18/2000      H1N2      PA
26        A/swine/Czech_Republic/17671/2023      H1N2      PA
35     A/swine/Nordrhein-Westfalen/113/2024      H1N2      PA
...                                     ...       ...     ...
26932             A/swine/Germany/R825/2014      H1N2      PA
26940            A/swine/Germany/R1143/2014      H1N2      PA
26948             A/swine/Germany/R916/2014      H1N2      PA
26972            A/swine/Germany/R1190/2014      H1N2      PA
26996             A/swine/Germany/R309/2015      H1N2      PA

           Location_Header         Geo_Location Date Collected Species  \
4                  Germany              Germany           2014   swine
12                 Germany              Germany           2014   swine
21                   Italy                Italy     2000-01-03   swine
26          Czech_Republic       Czech_Republic     2023-11-13   swine
35     Nordrhein-Westfalen  Nordrhein-Westfalen     2024-11-20   swine
...                    ...                  ...            ...     ...
26932              Germany              Germany           2014   swine
26940              Germany              Germany           2014   swine
26948              Germany              Germany           2014   swine
26972              Germany              Germany           2014   swine
26996              Germany              Germany           2014   swine

                                                Sequence  ... Outbreak  \
4      cattcacatcttttcattcactggagaggagattgccaccaaagcg...  ...      NaN
12     aaatggccagtaggagtctatgggattcctttcgtcagtccgaaag...  ...      NaN
21     tgattcaaaatggaagactttgtgcgacaatgcttcaatccaatga...  ...      NaN
26     tgatccaaaatggaagactttgtgcgacaatgcttcaatccaatga...  ...      NaN
35     atggaagactttgtgcgacaatgcttcaacccaatgattgtcgagc...  ...      NaN
...                                                  ...  ...      ...
26932  atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  ...      NaN
26940  atggaagactttgtgcgacaatgcttcaatccaatggtcgtcgagc...  ...      NaN
26948  atggaagactttgtgcgacaatgcttcaatccaatgatcgtcgagc...  ...      NaN
26972  atggaagactttgtgcgacaatgcttcaatccaatggtcgtcgagc...  ...      NaN

In [48]:
print(gisaid_fastas) #[0].columns)

[     Accession_x GenBank_Title_x Host_x Collection_Date_x SRA_Accession_x  \
0            NaN             NaN    NaN               NaN             NaN
1            NaN             NaN    NaN               NaN             NaN
2            NaN             NaN    NaN               NaN             NaN
3            NaN             NaN    NaN               NaN             NaN
4            NaN             NaN    NaN               NaN             NaN
...          ...             ...    ...               ...             ...
4089         NaN             NaN    NaN               NaN             NaN
4090         NaN             NaN    NaN               NaN             NaN
4091         NaN             NaN    NaN               NaN             NaN
4092         NaN             NaN    NaN               NaN             NaN
4093         NaN             NaN    NaN               NaN             NaN

     Assembly_x Isolate_x Genotype_x Geo_Location_x full_header_x  ...  \
0           NaN       NaN        NaN            NaN           NaN  ...
1           NaN       NaN        NaN            NaN           NaN  ...
2           NaN       NaN        NaN            NaN           NaN  ...
3           NaN       NaN        NaN            NaN           NaN  ...
4           NaN       NaN        NaN            NaN           NaN  ...
...         ...       ...        ...            ...           ...  ...
4089        NaN       NaN        NaN            NaN           NaN  ...
4090        NaN       NaN        NaN            NaN           NaN  ...
4091        NaN       NaN        NaN            NaN           NaN  ...
4092        NaN       NaN        NaN            NaN           NaN  ...
4093        NaN       NaN        NaN            NaN           NaN  ...

     Pathogen_Test_Info  Is_Vaccinated Human_Specimen_Source  \
0                   NaN            NaN                   NaN
1                   NaN            NaN                   NaN
2                   NaN            0.0                   NaN
3                   NaN            NaN                   NaN
4                   NaN            NaN                   NaN
...                 ...            ...                   ...
4089                NaN            NaN                   NaN
4090                NaN            NaN                   NaN
4091                NaN            NaN                   NaN
4092                NaN            NaN                   NaN
4093                NaN            NaN                   NaN

     Animal_Specimen_Source Animal_Health_Status Domestic_Status PMID  \
0                       NaN                  NaN             NaN  NaN
1                       NaN                  NaN             NaN  NaN
2                       NaN                  NaN             NaN  NaN
3                Nasal swab                  NaN        Domestic  NaN
4                       NaN                  NaN             NaN  NaN
...                     ...                  ...             ...  ...
4089                    NaN                  NaN             NaN  NaN
4090    Oro-pharyngeal swab                 Sick        Domestic  NaN
4091                    NaN                  NaN             NaN  NaN
4092                    NaN                  NaN             NaN  NaN
4093                    NaN                  NaN             NaN  NaN

                                               New_Name Serotype      _merge
0     >EPI_ISL_245764|A/swine/Germany/R313/2015|H1N2...       H1  right_only
1     >EPI_ISL_245771|A/swine/Germany/R318/2015|H1N2...       H1  right_only
2     >EPI_ISL_73783|A/swine/Italy/18/2000|H1N2|Ital...       H1  right_only
3     >EPI_ISL_18604439|A/swine/Czech_Republic/17671...       H1  right_only
4     >EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/...       H1  right_only
...                                                 ...      ...         ...
4089  >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...       H1  right_only
4090  >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...       H1  right_only
4091  >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...       H1  right_only
4092  >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...       H1  right_only
4093  >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...       H1  right_only

[2942 rows x 108 columns],     Accession_x GenBank_Title_x Host_x Collection_Date_x SRA_Accession_x  \
0           NaN             NaN    NaN               NaN             NaN
1           NaN             NaN    NaN               NaN             NaN
2           NaN             NaN    NaN               NaN             NaN
3           NaN             NaN    NaN               NaN             NaN
4           NaN             NaN    NaN               NaN             NaN
..          ...             ...    ...               ...             ...
540         NaN             NaN    NaN               NaN             NaN
541         NaN             NaN    NaN               NaN             NaN
542         NaN             NaN    NaN               NaN             NaN
543         NaN             NaN    NaN               NaN             NaN
544         NaN             NaN    NaN               NaN             NaN

    Assembly_x Isolate_x Genotype_x Geo_Location_x full_header_x  ...  \
0          NaN       NaN        NaN            NaN           NaN  ...
1          NaN       NaN        NaN            NaN           NaN  ...
2          NaN       NaN        NaN            NaN           NaN  ...
3          NaN       NaN        NaN            NaN           NaN  ...
4          NaN       NaN        NaN            NaN           NaN  ...
..         ...       ...        ...            ...           ...  ...
540        NaN       NaN        NaN            NaN           NaN  ...
541        NaN       NaN        NaN            NaN           NaN  ...
542        NaN       NaN        NaN            NaN           NaN  ...
543        NaN       NaN        NaN            NaN           NaN  ...
544        NaN       NaN        NaN            NaN           NaN  ...

    Pathogen_Test_Info  Is_Vaccinated Human_Specimen_Source  \
0                  NaN            NaN                   NaN
1                  NaN            NaN                   NaN
2                  NaN            NaN                   NaN
3                  NaN            NaN                   NaN
4                  NaN            NaN                   NaN
..                 ...            ...                   ...
540                NaN            NaN                   NaN
541                NaN            NaN                   NaN
542                NaN            NaN                   NaN
543                NaN            NaN                   NaN
544                NaN            NaN                   NaN

    Animal_Specimen_Source Animal_Health_Status Domestic_Status PMID  \
0                      NaN                  NaN             NaN  NaN
1                      NaN                  NaN             NaN  NaN
2                      NaN                  NaN             NaN  NaN
3                      NaN                  NaN             NaN  NaN
4                      NaN                  NaN             NaN  NaN
..                     ...                  ...             ...  ...
540                    NaN                  NaN             NaN  NaN
541                    NaN                  NaN             NaN  NaN
542                    NaN                  NaN             NaN  NaN
543                    NaN                  NaN             NaN  NaN
544                    NaN                  NaN             NaN  NaN

                                              New_Name Serotype      _merge
0    >EPI_ISL_278824|A/swine/Italy/229049/2015|H3N2...       H3  right_only
1    >EPI_ISL_19644422|A/swine/Italy/430612/2022|H3...       H3  right_only
2    >EPI_ISL_278826|A/swine/Italy/240849/2015|H3N2...       H3  right_only
3    >EPI_ISL_278827|A/swine/Italy/248147-8/2015|H3...       H3  right_only
4    >EPI_ISL_278844|A/swine/Italy/1103/2015|H3N2|I...       H3  right_only
..                                                 ...      ...         ...
540  >EPI_ISL_19644399|A/swine/Italy/35820/2022|H3N...       H3  right_only
541  >EPI_ISL_163606|A/swine/Italy/187969/2013|H3N2...       H3  right_only
542  >EPI_ISL_163607|A/swine/Italy/250481_2/2013|H3...       H3  right_only
543  >EPI_ISL_163604|A/swine/Italy/311349/2013|H3N2...       H3  right_only
544  >EPI_ISL_163605|A/swine/Italy/282811/2013|H3N2...       H3  right_only

[417 rows x 108 columns],      Accession_x GenBank_Title_x Host_x Collection_Date_x SRA_Accession_x  \
0            NaN             NaN    NaN               NaN             NaN
1            NaN             NaN    NaN               NaN             NaN
2            NaN             NaN    NaN               NaN             NaN
3            NaN             NaN    NaN               NaN             NaN
4            NaN             NaN    NaN               NaN             NaN
...          ...             ...    ...               ...             ...
2180         NaN             NaN    NaN               NaN             NaN
2181         NaN             NaN    NaN               NaN             NaN
2182         NaN             NaN    NaN               NaN             NaN
2183         NaN             NaN    NaN               NaN             NaN
2184         NaN             NaN    NaN               NaN             NaN

     Assembly_x Isolate_x Genotype_x Geo_Location_x full_header_x  ...  \
0           NaN       NaN        NaN            NaN           NaN  ...
1           NaN       NaN        NaN            NaN           NaN  ...
2           NaN       NaN        NaN            NaN           NaN  ...
3           NaN       NaN        NaN            NaN           NaN  ...
4           NaN       NaN        NaN            NaN           NaN  ...
...         ...       ...        ...            ...           ...  ...
2180        NaN       NaN        NaN            NaN           NaN  ...
2181        NaN       NaN        NaN            NaN           NaN  ...
2182        NaN       NaN        NaN            NaN           NaN  ...
2183        NaN       NaN        NaN            NaN           NaN  ...
2184        NaN       NaN        NaN            NaN           NaN  ...

     Pathogen_Test_Info  Is_Vaccinated Human_Specimen_Source  \
0                   NaN            NaN                   NaN
1                   NaN            NaN                   NaN
2                   NaN            NaN                   NaN
3                   NaN            NaN                   NaN
4                   NaN            NaN                   NaN
...                 ...            ...                   ...
2180                NaN            NaN                   NaN
2181                NaN            NaN                   NaN
2182                NaN            NaN                   NaN
2183                NaN            NaN                   NaN
2184                NaN            NaN                   NaN

     Animal_Specimen_Source Animal_Health_Status Domestic_Status PMID  \
0                Nasal swab                  NaN             NaN  NaN
1                Nasal swab                  NaN             NaN  NaN
2                Nasal swab                  NaN             NaN  NaN
3                Nasal swab                  NaN             NaN  NaN
4                Nasal swab                  NaN             NaN  NaN
...                     ...                  ...             ...  ...
2180                    NaN                  NaN             NaN  NaN
2181    Oro-pharyngeal swab                 Sick        Domestic  NaN
2182                    NaN                  NaN             NaN  NaN
2183                    NaN                  NaN             NaN  NaN
2184                    NaN                  NaN             NaN  NaN

                                               New_Name Serotype      _merge
0     >EPI_ISL_19751421|A/swine/Denmark/LF22-7167-3/...       N1  right_only
1     >EPI_ISL_19751423|A/swine/Denmark/LF22-7302-1/...       N1  right_only
2     >EPI_ISL_19751422|A/swine/Denmark/LF22-7300-3/...       N1  right_only
3     >EPI_ISL_19751417|A/swine/Denmark/LF22-6877-4/...       N1  right_only
4     >EPI_ISL_19751418|A/swine/Denmark/LF22-6907-1/...       N1  right_only
...                                                 ...      ...         ...
2180  >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...       N1  right_only
2181  >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...       N1  right_only
2182  >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...       N1  right_only
2183  >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...       N1  right_only
2184  >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...       N1  right_only

[1609 rows x 108 columns],      Accession_x GenBank_Title_x Host_x Collection_Date_x SRA_Accession_x  \
0            NaN             NaN    NaN               NaN             NaN
1            NaN             NaN    NaN               NaN             NaN
2            NaN             NaN    NaN               NaN             NaN
3            NaN             NaN    NaN               NaN             NaN
4            NaN             NaN    NaN               NaN             NaN
...          ...             ...    ...               ...             ...
2449         NaN             NaN    NaN               NaN             NaN
2450         NaN             NaN    NaN               NaN             NaN
2451         NaN             NaN    NaN               NaN             NaN
2452         NaN             NaN    NaN               NaN             NaN
2453         NaN             NaN    NaN               NaN             NaN

     Assembly_x Isolate_x Genotype_x Geo_Location_x full_header_x  ...  \
0           NaN       NaN        NaN            NaN           NaN  ...
1           NaN       NaN        NaN            NaN           NaN  ...
2           NaN       NaN        NaN            NaN           NaN  ...
3           NaN       NaN        NaN            NaN           NaN  ...
4           NaN       NaN        NaN            NaN           NaN  ...
...         ...       ...        ...            ...           ...  ...
2449        NaN       NaN        NaN            NaN           NaN  ...
2450        NaN       NaN        NaN            NaN           NaN  ...
2451        NaN       NaN        NaN            NaN           NaN  ...
2452        NaN       NaN        NaN            NaN           NaN  ...
2453        NaN       NaN        NaN            NaN           NaN  ...

     Pathogen_Test_Info  Is_Vaccinated Human_Specimen_Source  \
0                   NaN            NaN                   NaN
1                   NaN            NaN                   NaN
2                   NaN            0.0                   NaN
3                   NaN            NaN                   NaN
4                   NaN            NaN                   NaN
...                 ...            ...                   ...
2449                NaN            NaN                   NaN
2450                NaN            NaN                   NaN
2451                NaN            NaN                   NaN
2452                NaN            NaN                   NaN
2453                NaN            NaN                   NaN

     Animal_Specimen_Source Animal_Health_Status Domestic_Status PMID  \
0                       NaN                  NaN             NaN  NaN
1                       NaN                  NaN             NaN  NaN
2                       NaN                  NaN             NaN  NaN
3                Nasal swab                  NaN        Domestic  NaN
4                       NaN                  NaN             NaN  NaN
...                     ...                  ...             ...  ...
2449                    NaN                  NaN             NaN  NaN
2450                    NaN                  NaN             NaN  NaN
2451                    NaN                  NaN             NaN  NaN
2452                    NaN                  NaN             NaN  NaN
2453                    NaN                  NaN             NaN  NaN

                                               New_Name Serotype      _merge
0     >EPI_ISL_245764|A/swine/Germany/R313/2015|H1N2...       N2  right_only
1     >EPI_ISL_245771|A/swine/Germany/R318/2015|H1N2...       N2  right_only
2     >EPI_ISL_73783|A/swine/Italy/18/2000|H1N2|Ital...       N2  right_only
3     >EPI_ISL_18604439|A/swine/Czech_Republic/17671...       N2  right_only
4     >EPI_ISL_19636706|A/swine/Nordrhein-Westfalen/...       N2  right_only
...                                                 ...      ...         ...
2449  >EPI_ISL_245695|A/swine/Germany/R825/2014|H1N2...       N2  right_only
2450  >EPI_ISL_245699|A/swine/Germany/R1143/2014|H1N...       N2  right_only
2451  >EPI_ISL_245697|A/swine/Germany/R916/2014|H1N2...       N2  right_only
2452  >EPI_ISL_245704|A/swine/Germany/R1190/2014|H1N...       N2  right_only
2453  >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...       N2  right_only

[1750 rows x 108 columns],      Accession_x GenBank_Title_x Host_x Collection_Date_x SRA_Accession_x  \
0            NaN             NaN    NaN               NaN             NaN
1            NaN             NaN    NaN               NaN             NaN
2            NaN             NaN    NaN               NaN             NaN
3            NaN             NaN    NaN               NaN             NaN
4            NaN             NaN    NaN               NaN             NaN
...          ...             ...    ...               ...             ...
4089         NaN             NaN    NaN               NaN             NaN
4090         NaN             NaN    NaN               NaN             NaN
4091         NaN             NaN    NaN               NaN             NaN
4092         NaN             NaN    NaN               NaN             NaN
4093         NaN             NaN    NaN               NaN             NaN

     Assembly_x Isolate_x Genotype_x Geo_Location_x full_header_x  ...  \
0           NaN       NaN        NaN            NaN           NaN  ...
1           NaN       NaN        NaN            NaN           NaN  ...
2           NaN       NaN        NaN            NaN           NaN  ...
3           NaN       NaN        NaN            NaN           NaN  ...
4           NaN       NaN        NaN            NaN           NaN  ...
...         ...       ...        ...            ...           ...  ...
4089        NaN       NaN        NaN            NaN           NaN  ...
4090        NaN       NaN        NaN            NaN           NaN  ...
4091        NaN       NaN        NaN            NaN           NaN  ...
4092        NaN       NaN        NaN            NaN           NaN  ...
4093        NaN       NaN        NaN            NaN           NaN  ...

     Pathogen_Test_Info  Is_Vaccinated Human_Specimen_Source  \
0                   NaN            NaN                   NaN
1                   NaN            NaN                   NaN
2                   NaN            0.0                   NaN
3                   NaN            NaN                   NaN
4                   NaN            NaN                   NaN
...                 ...            ...                   ...
4089                NaN            NaN                   NaN
4090                NaN            NaN                   NaN
4091                NaN            NaN                   NaN
4092                NaN            NaN                   NaN
4093                NaN            NaN                   NaN

     Animal_Specimen_Source Animal_Health_Status Domestic_Status PMID  \
0                       NaN                  NaN             NaN  NaN
1                       NaN                  NaN             NaN  NaN
2                       NaN                  NaN             NaN  NaN
3                Nasal swab                  NaN        Domestic  NaN
4                       NaN                  NaN             NaN  NaN

### Create FASTA Files

In [49]:
# Create FASTA files

os.chdir(complete_files)



for df in gisaid_fastas:
    for serotype in serotypes:
        if serotype == df["Serotype"].values[0]:
            df["Segment_Name"] = df["Segment"]
            # print(df["Segment_Name"].values)
            df.to_csv("GISAID_" + df["Segment_Name"].values[0] + "_" + str(serotype) + "_metadata_Paloma.csv")
            df = df.reset_index()
            if len(df["Genotype"].values[0]) > 0: # If we have assigned genotypes, including "Unassigned"
                file_name = "GISAID_" + df["Segment_Name"].values[0] + "_" + str(serotype) + "_Paloma.fasta"
                output_file = open(complete_files + file_name, "w")

                for index, row in df.iterrows():
                    name = df.loc[index, "New_Name"]
                    name = name.replace(" ", "_")
                    # names.append(name)
                    sequence = df.loc[index, "Sequence"]
                    # First is header, second is sequence
                    output_file.write(name + "\n")
                    output_file.write(sequence + "\n")
                
            output_file.close()

### Concatenation

In [50]:
# Now concatenate GISAID and GenBank

genbank_files = []
gisaid_files = []
for dirpath, dirs, files in os.walk(complete_files):
    for file in files:
        file_name = os.path.join(dirpath, file)
        if "GenBank" in file_name and ".fasta" in file_name:
            genbank_files.append(file_name)
        elif "GISAID" in file_name and ".fasta" in file_name:
            gisaid_files.append(file_name)
        else:
            continue

for file1 in genbank_files:
    if len(file1.split("_")) == 4:
        partial_file_name = "_".join(file1.split("_")[-3:])
    else:
        partial_file_name = "_".join(file1.split("_")[-3:])
    for file2 in gisaid_files:
        if len(file2.split("_")) == 4:
            partial_file_name_gisaid = "_".join(file2.split("_")[-3:])
        else:
            partial_file_name_gisaid = "_".join(file2.split("_")[-3:])
        if partial_file_name == partial_file_name_gisaid:
            with open(complete_files + partial_file_name, 'w') as outfile:
                with open(file1) as f1:
                    for line in f1:
                        outfile.write(line)
                    f1.close()
                with open(file2) as f2:
                    for line in f2:
                        outfile.write(line)
                    f2.close()
                outfile.close()

## Second De-Duplication

In [53]:
output_path = complete_files + "deduplicated/"
if not os.path.exists(output_path): # checking if the directory exists or not
    os.makedirs(output_path) # if the directory is not present then create it

for dirpath, dirs, files in os.walk(complete_files):
    for file in files:
        file_name = os.path.join(dirpath, file)
        if ".fasta" in file_name and "GISAID" not in file_name and "GenBank" not in file_name and len(file_name.split("/")[-1].split("_")) == 3:
            df = df_from_fasta(file_name)
            print(df["full_header"])
            df["isolate"] = df["full_header"].apply(lambda x: x.split("/")[3])
            df = df.drop_duplicates(subset="isolate", keep="first")
            df = df[df["full_header"].str.contains(".*\\|20.*\\|.*")] # Make sure everything is 2000+
            print(df["full_header"])
            df_to_fasta(df, file_name.split("/")[-1], output_path)
    break

0       >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...
1       >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...
2       >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...
3       >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...
4       >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...
                              ...
3260    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
3261    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
3262    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
3263    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
3264    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 3265, dtype: object
0       >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...
8       >PQ107522|A/swine/Spain/6370-8/2019|H1N2|Spain...
16      >PQ107532|A/swine/Spain/6370-9/2019|H1N2|Spain...
24      >PQ107540|A/swine/Spain/6370-10/2019|H1N2|Spai...
32      >PQ107549|A/swine/Spain/17483-1/2021|H1N2|Spai...
                              ...
3260    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
3261    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
3262    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
3263    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
3264    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 2874, dtype: object
0      >PQ107611|A/swine/Spain/6176-2/2022|H3N1|Spain...
1      >PQ107611|A/swine/Spain/6176-2/2022|H3N1|Spain...
2      >PQ107611|A/swine/Spain/6176-2/2022|H3N1|Spain...
3      >PQ107611|A/swine/Spain/6176-2/2022|H3N1|Spain...
4      >PQ107611|A/swine/Spain/6176-2/2022|H3N1|Spain...
                             ...
436    >EPI_ISL_19644399|A/swine/Italy/35820/2022|H3N...
437    >EPI_ISL_163606|A/swine/Italy/187969/2013|H3N2...
438    >EPI_ISL_163607|A/swine/Italy/250481_2/2013|H3...
439    >EPI_ISL_163604|A/swine/Italy/311349/2013|H3N2...
440    >EPI_ISL_163605|A/swine/Italy/282811/2013|H3N2...
Name: full_header, Length: 441, dtype: object
0      >PQ107611|A/swine/Spain/6176-2/2022|H3N1|Spain...
8      >PP338506|A/swine/Spain/41410-1/2021|H3N2|Spai...
16     >PP338808|A/wild_boar/Spain/45560-1/2021|H3N1|...
24     >EPI_ISL_278824|A/swine/Italy/229049/2015|H3N2...
25     >EPI_ISL_19644422|A/swine/Italy/430612/2022|H3...
                             ...
436    >EPI_ISL_19644399|A/swine/Italy/35820/2022|H3N...
437    >EPI_ISL_163606|A/swine/Italy/187969/2013|H3N2...
438    >EPI_ISL_163607|A/swine/Italy/250481_2/2013|H3...
439    >EPI_ISL_163604|A/swine/Italy/311349/2013|H3N2...
440    >EPI_ISL_163605|A/swine/Italy/282811/2013|H3N2...
Name: full_header, Length: 409, dtype: object
0       >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...
1       >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...
2       >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...
3       >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...
4       >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...
                              ...
1762    >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...
1763    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
1764    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
1765    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
1766    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 1767, dtype: object
0       >PQ585343|A/swine/Spain/36520-1/2022|H1N1|Spai...
8       >PQ107580|A/swine/Spain/44394-1/2021|H1N1|Spai...
16      >PQ107611|A/swine/Spain/6176-2/2022|H3N1|Spain...
24      >PQ107619|A/swine/Spain/12510-1/2022|H1N1|Spai...
32      >PQ107640|A/swine/Spain/2247-1/2022|H1N1|Spain...
                              ...
1762    >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...
1763    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
1764    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
1765    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
1766    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 1554, dtype: object
0       >PQ107522|A/swine/Spain/6370-8/2019|H1N2|Spain...
1       >PQ107522|A/swine/Spain/6370-8/2019|H1N2|Spain...
2       >PQ107522|A/swine/Spain/6370-8/2019|H1N2|Spain...
3       >PQ107522|A/swine/Spain/6370-8/2019|H1N2|Spain...
4       >PQ107522|A/swine/Spain/6370-8/2019|H1N2|Spain...
                              ...
1927    >EPI_ISL_245695|A/swine/Germany/R825/2014|H1N2...
1928    >EPI_ISL_245699|A/swine/Germany/R1143/2014|H1N...
1929    >EPI_ISL_245697|A/swine/Germany/R916/2014|H1N2...
1930    >EPI_ISL_245704|A/swine/Germany/R1190/2014|H1N...
1931    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
Name: full_header, Length: 1932, dtype: object
0       >PQ107522|A/swine/Spain/6370-8/2019|H1N2|Spain...
8       >PQ107532|A/swine/Spain/6370-9/2019|H1N2|Spain...
16      >PQ107540|A/swine/Spain/6370-10/2019|H1N2|Spai...
24      >PQ107549|A/swine/Spain/17483-1/2021|H1N2|Spai...
32      >PQ107557|A/swine/Spain/6370-11/2019|H1N2|Spai...
                              ...
1926    >EPI_ISL_245681|A/swine/Germany/R404/2014|H1N2...
1927    >EPI_ISL_245695|A/swine/Germany/R825/2014|H1N2...
1928    >EPI_ISL_245699|A/swine/Germany/R1143/2014|H1N...
1929    >EPI_ISL_245697|A/swine/Germany/R916/2014|H1N2...
1931    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
Name: full_header, Length: 1733, dtype: object
0       >PQ585346|A/swine/Spain/36520-1/2022|H1N1|Spai...
1       >PQ585346|A/swine/Spain/36520-1/2022|H1N1|Spai...
2       >PQ585346|A/swine/Spain/36520-1/2022|H1N1|Spai...
3       >PQ585346|A/swine/Spain/36520-1/2022|H1N1|Spai...
4       >PQ585346|A/swine/Spain/36520-1/2022|H1N1|Spai...
                              ...
3260    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
3261    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
3262    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
3263    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
3264    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 3265, dtype: object
0       >PQ585346|A/swine/Spain/36520-1/2022|H1N1|Spai...
8       >PQ107525|A/swine/Spain/6370-8/2019|H1N2|Spain...
16      >PQ107535|A/swine/Spain/6370-9/2019|H1N2|Spain...
24      >PQ107543|A/swine/Spain/6370-10/2019|H1N2|Spai...
32      >PQ107552|A/swine/Spain/17483-1/2021|H1N2|Spai...
                              ...
3260    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
3261    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
3262    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
3263    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
3264    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 2874, dtype: object
0      >PQ107614|A/swine/Spain/6176-2/2022|H3N1|Spain...
1      >PQ107614|A/swine/Spain/6176-2/2022|H3N1|Spain...
2      >PQ107614|A/swine/Spain/6176-2/2022|H3N1|Spain...
3      >PQ107614|A/swine/Spain/6176-2/2022|H3N1|Spain...
4      >PQ107614|A/swine/Spain/6176-2/2022|H3N1|Spain...
                             ...
436    >EPI_ISL_19644399|A/swine/Italy/35820/2022|H3N...
437    >EPI_ISL_163606|A/swine/Italy/187969/2013|H3N2...
438    >EPI_ISL_163607|A/swine/Italy/250481_2/2013|H3...
439    >EPI_ISL_163604|A/swine/Italy/311349/2013|H3N2...
440    >EPI_ISL_163605|A/swine/Italy/282811/2013|H3N2...
Name: full_header, Length: 441, dtype: object
0      >PQ107614|A/swine/Spain/6176-2/2022|H3N1|Spain...
8      >PP338509|A/swine/Spain/41410-1/2021|H3N2|Spai...
16     >PP338811|A/wild_boar/Spain/45560-1/2021|H3N1|...
24     >EPI_ISL_278824|A/swine/Italy/229049/2015|H3N2...
25     >EPI_ISL_19644422|A/swine/Italy/430612/2022|H3...
                             ...
436    >EPI_ISL_19644399|A/swine/Italy/35820/2022|H3N...
437    >EPI_ISL_163606|A/swine/Italy/187969/2013|H3N2...
438    >EPI_ISL_163607|A/swine/Italy/250481_2/2013|H3...
439    >EPI_ISL_163604|A/swine/Italy/311349/2013|H3N2...
440    >EPI_ISL_163605|A/swine/Italy/282811/2013|H3N2...
Name: full_header, Length: 409, dtype: object
0       >PQ585346|A/swine/Spain/36520-1/2022|H1N1|Spai...
1       >PQ585346|A/swine/Spain/36520-1/2022|H1N1|Spai...
2       >PQ585346|A/swine/Spain/36520-1/2022|H1N1|Spai...
3       >PQ585346|A/swine/Spain/36520-1/2022|H1N1|Spai...
4       >PQ585346|A/swine/Spain/36520-1/2022|H1N1|Spai...
                              ...
1769    >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...
1770    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
1771    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
1772    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
1773    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 1774, dtype: object
0       >PQ585346|A/swine/Spain/36520-1/2022|H1N1|Spai...
8       >PQ107583|A/swine/Spain/44394-1/2021|H1N1|Spai...
16      >PQ107614|A/swine/Spain/6176-2/2022|H3N1|Spain...
24      >PQ107622|A/swine/Spain/12510-1/2022|H1N1|Spai...
32      >PQ107643|A/swine/Spain/2247-1/2022|H1N1|Spain...
                              ...
1769    >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...
1770    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
1771    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
1772    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
1773    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 1555, dtype: object
0       >PQ107525|A/swine/Spain/6370-8/2019|H1N2|Spain...
1       >PQ107525|A/swine/Spain/6370-8/2019|H1N2|Spain...
2       >PQ107525|A/swine/Spain/6370-8/2019|H1N2|Spain...
3       >PQ107525|A/swine/Spain/6370-8/2019|H1N2|Spain...
4       >PQ107525|A/swine/Spain/6370-8/2019|H1N2|Spain...
                              ...
1927    >EPI_ISL_245695|A/swine/Germany/R825/2014|H1N2...
1928    >EPI_ISL_245699|A/swine/Germany/R1143/2014|H1N...
1929    >EPI_ISL_245697|A/swine/Germany/R916/2014|H1N2...
1930    >EPI_ISL_245704|A/swine/Germany/R1190/2014|H1N...
1931    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
Name: full_header, Length: 1932, dtype: object
0       >PQ107525|A/swine/Spain/6370-8/2019|H1N2|Spain...
8       >PQ107535|A/swine/Spain/6370-9/2019|H1N2|Spain...
16      >PQ107543|A/swine/Spain/6370-10/2019|H1N2|Spai...
24      >PQ107552|A/swine/Spain/17483-1/2021|H1N2|Spai...
32      >PQ107560|A/swine/Spain/6370-11/2019|H1N2|Spai...
                              ...
1926    >EPI_ISL_245681|A/swine/Germany/R404/2014|H1N2...
1927    >EPI_ISL_245695|A/swine/Germany/R825/2014|H1N2...
1928    >EPI_ISL_245699|A/swine/Germany/R1143/2014|H1N...
1929    >EPI_ISL_245697|A/swine/Germany/R916/2014|H1N2...
1931    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
Name: full_header, Length: 1733, dtype: object
0       >PQ585345|A/swine/Spain/36520-1/2022|H1N1|Spai...
1       >PQ585345|A/swine/Spain/36520-1/2022|H1N1|Spai...
2       >PQ585345|A/swine/Spain/36520-1/2022|H1N1|Spai...
3       >PQ585345|A/swine/Spain/36520-1/2022|H1N1|Spai...
4       >PQ585345|A/swine/Spain/36520-1/2022|H1N1|Spai...
                              ...
3253    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
3254    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
3255    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
3256    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
3257    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 3258, dtype: object
0       >PQ585345|A/swine/Spain/36520-1/2022|H1N1|Spai...
8       >PQ107524|A/swine/Spain/6370-8/2019|H1N2|Spain...
16      >PQ107534|A/swine/Spain/6370-9/2019|H1N2|Spain...
24      >PQ107542|A/swine/Spain/6370-10/2019|H1N2|Spai...
32      >PQ107551|A/swine/Spain/17483-1/2021|H1N2|Spai...
                              ...
3253    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
3254    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
3255    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
3256    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
3257    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 2873, dtype: object
0      >PQ107613|A/swine/Spain/6176-2/2022|H3N1|Spain...
1      >PQ107613|A/swine/Spain/6176-2/2022|H3N1|Spain...
2      >PQ107613|A/swine/Spain/6176-2/2022|H3N1|Spain...
3      >PQ107613|A/swine/Spain/6176-2/2022|H3N1|Spain...
4      >PQ107613|A/swine/Spain/6176-2/2022|H3N1|Spain...
                             ...
436    >EPI_ISL_19644399|A/swine/Italy/35820/2022|H3N...
437    >EPI_ISL_163606|A/swine/Italy/187969/2013|H3N2...
438    >EPI_ISL_163607|A/swine/Italy/250481_2/2013|H3...
439    >EPI_ISL_163604|A/swine/Italy/311349/2013|H3N2...
440    >EPI_ISL_163605|A/swine/Italy/282811/2013|H3N2...
Name: full_header, Length: 441, dtype: object
0      >PQ107613|A/swine/Spain/6176-2/2022|H3N1|Spain...
8      >PP338508|A/swine/Spain/41410-1/2021|H3N2|Spai...
16     >PP338810|A/wild_boar/Spain/45560-1/2021|H3N1|...
24     >EPI_ISL_278824|A/swine/Italy/229049/2015|H3N2...
25     >EPI_ISL_19644422|A/swine/Italy/430612/2022|H3...
                             ...
436    >EPI_ISL_19644399|A/swine/Italy/35820/2022|H3N...
437    >EPI_ISL_163606|A/swine/Italy/187969/2013|H3N2...
438    >EPI_ISL_163607|A/swine/Italy/250481_2/2013|H3...
439    >EPI_ISL_163604|A/swine/Italy/311349/2013|H3N2...
440    >EPI_ISL_163605|A/swine/Italy/282811/2013|H3N2...
Name: full_header, Length: 409, dtype: object
0       >PQ585345|A/swine/Spain/36520-1/2022|H1N1|Spai...
1       >PQ585345|A/swine/Spain/36520-1/2022|H1N1|Spai...
2       >PQ585345|A/swine/Spain/36520-1/2022|H1N1|Spai...
3       >PQ585345|A/swine/Spain/36520-1/2022|H1N1|Spai...
4       >PQ585345|A/swine/Spain/36520-1/2022|H1N1|Spai...
                              ...
1769    >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...
1770    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
1771    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
1772    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
1773    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 1774, dtype: object
0       >PQ585345|A/swine/Spain/36520-1/2022|H1N1|Spai...
8       >PQ107582|A/swine/Spain/44394-1/2021|H1N1|Spai...
16      >PQ107613|A/swine/Spain/6176-2/2022|H3N1|Spain...
24      >PQ107621|A/swine/Spain/12510-1/2022|H1N1|Spai...
32      >PQ107642|A/swine/Spain/2247-1/2022|H1N1|Spain...
                              ...
1769    >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...
1770    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
1771    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
1772    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
1773    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 1555, dtype: object
0       >PQ107524|A/swine/Spain/6370-8/2019|H1N2|Spain...
1       >PQ107524|A/swine/Spain/6370-8/2019|H1N2|Spain...
2       >PQ107524|A/swine/Spain/6370-8/2019|H1N2|Spain...
3       >PQ107524|A/swine/Spain/6370-8/2019|H1N2|Spain...
4       >PQ107524|A/swine/Spain/6370-8/2019|H1N2|Spain...
                              ...
1927    >EPI_ISL_245695|A/swine/Germany/R825/2014|H1N2...
1928    >EPI_ISL_245699|A/swine/Germany/R1143/2014|H1N...
1929    >EPI_ISL_245697|A/swine/Germany/R916/2014|H1N2...
1930    >EPI_ISL_245704|A/swine/Germany/R1190/2014|H1N...
1931    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
Name: full_header, Length: 1932, dtype: object
0       >PQ107524|A/swine/Spain/6370-8/2019|H1N2|Spain...
8       >PQ107534|A/swine/Spain/6370-9/2019|H1N2|Spain...
16      >PQ107542|A/swine/Spain/6370-10/2019|H1N2|Spai...
24      >PQ107551|A/swine/Spain/17483-1/2021|H1N2|Spai...
32      >PQ107559|A/swine/Spain/6370-11/2019|H1N2|Spai...
                              ...
1926    >EPI_ISL_245681|A/swine/Germany/R404/2014|H1N2...
1927    >EPI_ISL_245695|A/swine/Germany/R825/2014|H1N2...
1928    >EPI_ISL_245699|A/swine/Germany/R1143/2014|H1N...
1929    >EPI_ISL_245697|A/swine/Germany/R916/2014|H1N2...
1931    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
Name: full_header, Length: 1733, dtype: object
0       >PQ585344|A/swine/Spain/36520-1/2022|H1N1|Spai...
1       >PQ585344|A/swine/Spain/36520-1/2022|H1N1|Spai...
2       >PQ585344|A/swine/Spain/36520-1/2022|H1N1|Spai...
3       >PQ585344|A/swine/Spain/36520-1/2022|H1N1|Spai...
4       >PQ585344|A/swine/Spain/36520-1/2022|H1N1|Spai...
                              ...
3260    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
3261    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
3262    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
3263    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
3264    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 3265, dtype: object
0       >PQ585344|A/swine/Spain/36520-1/2022|H1N1|Spai...
8       >PQ107523|A/swine/Spain/6370-8/2019|H1N2|Spain...
16      >PQ107533|A/swine/Spain/6370-9/2019|H1N2|Spain...
24      >PQ107541|A/swine/Spain/6370-10/2019|H1N2|Spai...
32      >PQ107550|A/swine/Spain/17483-1/2021|H1N2|Spai...
                              ...
3260    >EPI_ISL_245731|A/swine/Germany/R309/2015|H1N2...
3261    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
3262    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
3263    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
3264    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 2874, dtype: object
0      >PQ107612|A/swine/Spain/6176-2/2022|H3N1|Spain...
1      >PQ107612|A/swine/Spain/6176-2/2022|H3N1|Spain...
2      >PQ107612|A/swine/Spain/6176-2/2022|H3N1|Spain...
3      >PQ107612|A/swine/Spain/6176-2/2022|H3N1|Spain...
4      >PQ107612|A/swine/Spain/6176-2/2022|H3N1|Spain...
                             ...
436    >EPI_ISL_19644399|A/swine/Italy/35820/2022|H3N...
437    >EPI_ISL_163606|A/swine/Italy/187969/2013|H3N2...
438    >EPI_ISL_163607|A/swine/Italy/250481_2/2013|H3...
439    >EPI_ISL_163604|A/swine/Italy/311349/2013|H3N2...
440    >EPI_ISL_163605|A/swine/Italy/282811/2013|H3N2...
Name: full_header, Length: 441, dtype: object
0      >PQ107612|A/swine/Spain/6176-2/2022|H3N1|Spain...
8      >PP338507|A/swine/Spain/41410-1/2021|H3N2|Spai...
16     >PP338809|A/wild_boar/Spain/45560-1/2021|H3N1|...
24     >EPI_ISL_278824|A/swine/Italy/229049/2015|H3N2...
25     >EPI_ISL_19644422|A/swine/Italy/430612/2022|H3...
                             ...
436    >EPI_ISL_19644399|A/swine/Italy/35820/2022|H3N...
437    >EPI_ISL_163606|A/swine/Italy/187969/2013|H3N2...
438    >EPI_ISL_163607|A/swine/Italy/250481_2/2013|H3...
439    >EPI_ISL_163604|A/swine/Italy/311349/2013|H3N2...
440    >EPI_ISL_163605|A/swine/Italy/282811/2013|H3N2...
Name: full_header, Length: 409, dtype: object
0       >PQ585344|A/swine/Spain/36520-1/2022|H1N1|Spai...
1       >PQ585344|A/swine/Spain/36520-1/2022|H1N1|Spai...
2       >PQ585344|A/swine/Spain/36520-1/2022|H1N1|Spai...
3       >PQ585344|A/swine/Spain/36520-1/2022|H1N1|Spai...
4       >PQ585344|A/swine/Spain/36520-1/2022|H1N1|Spai...
                              ...
1769    >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...
1770    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
1771    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
1772    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
1773    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 1774, dtype: object
0       >PQ585344|A/swine/Spain/36520-1/2022|H1N1|Spai...
8       >PQ107581|A/swine/Spain/44394-1/2021|H1N1|Spai...
16      >PQ107612|A/swine/Spain/6176-2/2022|H3N1|Spain...
24      >PQ107620|A/swine/Spain/12510-1/2022|H1N1|Spai...
32      >PQ107641|A/swine/Spain/2247-1/2022|H1N1|Spain...
                              ...
1769    >EPI_ISL_245726|A/swine/Germany/R1696/2014|H1N...
1770    >EPI_ISL_237542|A/swine/Germany/AR1026/2016|H1...
1771    >EPI_ISL_245748|A/swine/Germany/R312/2015|H1N1...
1772    >EPI_ISL_16074739|A/Navarra/4050/2022|H1N1|Spa...
1773    >EPI_ISL_19459695|A/Catalonia/NSAV198309324/20...
Name: full_header, Length: 1555, dtype: object
0       >PQ107523|A/swine/Spain/6370-8/2019|H1N2|Spain...
1       >PQ107523|A/swine/Spain/6370-8/2019|H1N2|Spain...
2       >PQ107523|A/swine/Spain/6370-8/2019|H1N2|Spain...
3       >PQ107523|A/swine/Spain/6370-8/2019|H1N2|Spain...

In [54]:
# Modify files so only HA and NA are split
segments_seen = []
for dirpath, dirs, files in os.walk(output_path):
    for file in files:
        file_name = os.path.join(dirpath, file)
        segment = file_name.split("/")[-1].split("_")[0]
        # print(segment)
        if segment != "NA" and segment != "HA" and "rejects" not in file_name and segment not in segments_seen:
            file_list = []
            # Merge the segments
            for file2 in files:
                file_name2 = os.path.join(dirpath, file2)
                segment2 = file_name2.split("/")[-1].split("_")[0]
                if segment == segment2:
                    # Concatenate files
                    file_list.append(file_name2)
            df_list = []
            for listed_file in file_list:
                df = df_from_fasta(listed_file)
                df_list.append(df)
            concatenated_df = pd.concat(df_list).reset_index(drop=True).drop_duplicates(subset="full_header")
            # print(concatenated_df)
            df_to_fasta(concatenated_df, segment + "_Paloma.fasta", output_path)
            segments_seen.append(segment)
            print(segments_seen)
    break

['MP']
['MP', 'NP']
['MP', 'NP', 'NS']
['MP', 'NP', 'NS', 'PA']
['MP', 'NP', 'NS', 'PA', 'PB1']
['MP', 'NP', 'NS', 'PA', 'PB1', 'PB2']

## GISAID (again)

In [20]:
# downloads_saved = home + "Other/Paloma/Y2K_swine/" 

# complete_files = downloads_saved + "complete/" 
# if not os.path.exists(complete_files): # checking if the directory exists or not
#     os.makedirs(complete_files) # if the directory is not present then create it

In [21]:
# all_metadata_files = []
# all_fasta_files = []

# # If we have multiple files, name them nicely
# for dirpath, dirs, files in os.walk(downloads_saved):
#     for file in files:
#         file_name = os.path.join(dirpath, file)
#         # file_name = "_".join(file_name.split(" "))
        
#         os.rename(file_name, "_".join(file_name.split(" ")).replace("(", "").replace(")", ""))

#         print(file_name)

#         # Now go through files and get contents
#         if ".xls" in file_name:
#             metadata = pd.read_excel(file_name)
#             all_metadata_files.append(metadata)
#         # if ".csv" in file_name:
#         #     metadata = pd.read_csv(file_name)
#         #     all_metadata_files.append(metadata)
#         if ".fasta" in file_name:
#             fasta_file = fasta_df(file_name, states_ref) # Convert fasta file to dataframe
#             # print(fasta_file[fasta_file["Geo_Location"] != "USA"])
#             # break 
#             all_fasta_files.append(fasta_file)
#     break

In [22]:
# # Separate FASTA files into 8 different files based on segment

# def separate_fasta_by_seg(metadata, fasta, animals_df): 

#     fasta = fix_animals(fasta, animals_df)
#     # Dummy host type -- we'll actually add this in later
#     # b313_fasta["Host_Type"] = "other"
#     # d11_fasta["Host_Type"] = "other"

#     unique_segments = list(set(fasta["Segment"]))
#     # genotypes = ["B3.13", "D1.1"]
#     # genotype_fastas = {"B3.13": b313_fasta, "D1.1": d11_fasta}

#     # “>EPI_ID/Isolate_name|subtype|collection_date|host_type|genotype”

#     segment_fastas = []
#     for seg in unique_segments:

#         xls = metadata

#         # print(xls)
#         # print("XLS: ", metadata["Genotype"])

#         # print(d11_xls)

#         # FASTA
#         # if "Identifier" in fasta.columns:
#         #     mask = fasta["Identifier"].isin(xls['Isolate_Id'])
#         # else:           
#         #     mask = fasta['Isolate_Id'].isin(xls['Isolate_Id'])
#         #     fasta["Identifier"] = fasta["Isolate_Id"]

#         # fasta_seg_pre = fasta[mask]
#         # print(fasta_seg_pre)
#         xls["Identifier"] = xls["Isolate_Id"]
#         fasta_seg_pre = fasta.merge(xls, on="Identifier")

#         # fasta_seg = genotype_fastas[fasta_gen][genotype_fastas[fasta_gen]["Segment"] == seg]
#         fasta_seg = fasta_seg_pre[fasta_seg_pre["Segment"] == seg]
#         print(fasta_seg)

#         # Rename sequences 
#         new_name = ">" + fasta_seg["Identifier"] + "|" + fasta_seg["Isolate_Name_x"] + "|" + fasta_seg["Subtype_x"].apply(lambda x: x.split("_")[-1]) + "|" + fasta_seg["Location_y"].apply(lambda x: x.split("/")[1].replace(" ", "")) + "|" + fasta_seg["Date Collected"].apply(lambda x: str(dateutil.parser.parse(x, default=dateutil.parser.parse("2000-01-01")).year) if dateutil.parser.parse(x, default=dateutil.parser.parse("2000-01-01")).month == dateutil.parser.parse("2000-01-01").month and dateutil.parser.parse(x, default=dateutil.parser.parse("2000-01-01")).day == dateutil.parser.parse("2000-01-01").day else x) + "|swine\n"
#         fasta_seg["New_Name"] = new_name
#         # print(fasta_seg["New_Name"])

#         segment_fastas.append(fasta_seg)
#         # print(fasta_seg)

#     return segment_fastas, unique_segments

# # Separate fastas by segment
# segment_fastas = []
# unique_animals_all = []
# for i, fasta in enumerate(all_fasta_files):
#     # print(all_fasta_files)
#     # print(fasta)
#     # print(i)
#     metadata = all_metadata_files[i]
#     # print(metadata["Clade"])
#     # break 
#     # print(fasta.loc[i, "Isolate_Name"])
    
#     unique_animals = sort_animals(fasta) # Find unique animals
#     # print("Animals: ", unique_animals)
#     unique_animals_all.append(unique_animals)

#     os.chdir(references)
#     animals_ref = pd.read_csv("animals_ref.csv")
#     print(fasta)
#     fastas, unique_segments = separate_fasta_by_seg(metadata, fasta, animals_ref) # Separate the fasta dataframes into 8 different files based on segment
#     # print(fastas[0])

#     for fasta in fastas:
#         segment_fastas.append(fasta)

In [23]:
# # Find animals to sort, if needed

# os.chdir(references)

# # Flatten unique_animals
# every_unique_animal = []
# for l in unique_animals_all:
#     for animal in l:
#         every_unique_animal.append(animal)

# # Rename host type

# unique_animals_set = list(set(every_unique_animal))
# animals_df = pd.DataFrame(columns=["wild_avian", "domestic_avian", "cattle", "feline", "other_mammal", "human", "other"])
# animals_df["other"] = unique_animals_set # to sort

# # If animal not in ref1, put in ref2

# common_animals = []
# # Check if animals in unique_animals_set are in ref1
# for animal in unique_animals_set:
#     for col in animals_ref.columns:
#         if animal in animals_ref[col].values and type(animal) == str:
#             common_animals.append(animal)

# print(common_animals)
# print(len(common_animals))

# different_animals = []
# for animal in unique_animals_set:
#     if animal not in common_animals:
#         different_animals.append(animal)

# print(different_animals)

# print(animals_ref)

# # Add to dataframe
# animals_df = animals_ref
# # Make different_animals same length as dataframe, if shorter
# if len(different_animals) < len(animals_df):
#     number_of_times_to_add_nan = len(animals_df) - len(different_animals)
#     for i in range(number_of_times_to_add_nan):
#         different_animals.append(float('nan'))
# # If longer
# else:
#     number_of_times_to_add_nan = len(different_animals) - len(animals_df)
#     nan_row = pd.DataFrame([[np.nan] * len(animals_df.columns)], columns=animals_df.columns)
#     for i in range(number_of_times_to_add_nan):
#         animals_df = pd.concat([animals_df, nan_row], ignore_index=True)

# animals_df["new"] = (different_animals)

# print(animals_df)

# os.chdir(references)
# animals_df.to_csv("animals_ref_to_sort.csv")

In [24]:
# input("Check animal output.")

In [25]:
# gisaid_fastas = []
# for fasta in segment_fastas:
#     if fasta["Segment"].values[0] == "HA":
#         print("HA")
#         for s in ["H1", "H3"]:
#             m_g_s = fasta[fasta["Subtype_x"].str.contains(s)]
#             m_g_s["Serotype"] = s
#             if len(m_g_s) > 0:
#                 print(m_g_s["Subtype_x"])
#                 print(m_g_s)
#                 # m_g_s["New_Name"] = m_g_s["Header"] # .apply(lambda x: x.replace("other_mammal", "swine") if "other_mammal" in x else x)
#                 gisaid_fastas.append(m_g_s)
#     elif fasta["Segment"].values[0] == "NA":
#         print("NA")
#         for se in ["N1", "N2"]:
#             m_g_s = fasta[fasta["Subtype_x"].str.contains(se)]
#             m_g_s["Serotype"] = se
#             if len(m_g_s) > 0:
#                 # print(exp_df)
#                 # m_g_s["New_Name"] = m_g_s["Header"] # .apply(lambda x: x.replace("other_mammal", "swine") if "other_mammal" in x else x)
#                 gisaid_fastas.append(m_g_s)
#     else:
#         '''all other segments'''
#         if len(fasta) > 0:
#             fasta["Serotype"] = "None"
#             # fasta["New_Name"] = fasta["Header"] # .apply(lambda x: x.replace("other_mammal", "swine") if "other_mammal" in x else x)
#             gisaid_fastas.append(fasta)

# print(gisaid_fastas[0]["New_Name"].values[0].split("|")[3:])

In [26]:
# for gisaid_fasta in gisaid_fastas:
#     print(gisaid_fasta)
#     if "Segment_x" in gisaid_fasta.columns:
#         gisaid_fasta["Segment"] = gisaid_fasta["Segment_x"]
#     if "Isolate_Id_x" in gisaid_fasta.columns:
#         gisaid_fasta["Isolate"] = gisaid_fasta["Isolate_Id_x"]
#     print(gisaid_fasta["Segment"])

# # Remove Paloma's sequences
# os.chdir(downloads_saved)
# paloma_isolates = pd.read_csv("paloma_isolates.csv")

# for gisaid_fasta in gisaid_fastas:
#     for isolate in paloma_isolates["isolate"].values:
#         print(isolate)
#         if isolate in gisaid_fasta["Isolate"]:
#             gisaid_fasta = gisaid_fasta[gisaid_fasta["Isolate"] != isolate]

#     # Remove duplicates
#     gisaid_fasta = gisaid_fasta.drop_duplicates(subset="Header", keep="first")

In [27]:
# # Create FASTA files

# os.chdir(complete_files)

# for df in gisaid_fastas:
#     for serotype in serotypes:
#         if serotype == df["Serotype"].values[0]:
#             print(serotype)
#             if "Segment_y" in df.columns:
#                 df["Segment_Name"] = df["Segment_y"]
#             else:
#                 df["Segment_Name"] = df["Segment"]
#             # print(df.columns)
#             df.to_csv("GISAID_" + df["Segment_Name"].values[0] + "_" + serotype + "_metadata_Paloma.csv")
#             # df = df.reset_index()
#             # if len(df["Genotype_y"].values[0]) > 0: # If we have assigned genotypes, including "Unassigned"
#             file_name = "GISAID_" + df["Segment_Name"].values[0] + "_" + serotype + "_Paloma.fasta"
#             output_file = open(complete_files + file_name, "a+")

#             for index, row in df.iterrows():
#                 name = df.loc[index, "New_Name"]
#                 name = name.replace(" ", "_")
#                 # names.append(name)
#                 sequence = df.loc[index, "Sequence"]
#                 # First is header, second is sequence
#                 output_file.write(name)
#                 output_file.write(sequence + "\n")
#     if df["Serotype"].values[0] == "None":
#         # df["Segment_Name"] = df["Segment_x"]
#         if "Segment" in df.columns:
#             df["Segment_Name"] = df["Segment"]
#         else:
#             df["Segment_Name"] = ""
#         # print(df)
#         df.to_csv("GISAID_" + df["Segment_Name"].values[0] + "_metadata_Paloma.csv")
#         # df = df.reset_index()
#         # if len(df["Genotype"].values[0]) > 0: # If we have assigned genotypes, including "Unassigned"
#         file_name = "GISAID_" + df["Segment_Name"].values[0] + "_Paloma.fasta"
#         output_file = open(complete_files + file_name, "a+")

#         for index, row in df.iterrows():
#             name = df.loc[index, "New_Name"]
#             name = name.replace(" ", "_")
#             # names.append(name)
#             sequence = df.loc[index, "Sequence"]
#             # First is header, second is sequence
#             output_file.write(name)
#             output_file.write(sequence + "\n")
#         output_file.close()