# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI and relabeling sequences. 

Notes:
* This file must be in the same folder as "utils.py"

## Housekeeping

In [1]:
# Libraries

import os
import pandas as pd
import dateutil
import re
import shutil 
import numpy as np
import importlib
import utils  
importlib.reload(utils)
from utils import * # If changing utils, must restart this file for changes to take effect

In [2]:
# Directory paths and input

# Input
browser = input("Browser (Firefox, Chrome, or Edge): ")
sleep_time = input("Seconds to wait in between clicks (recommended 5): ")
# locations = input("Locations (separate with commas and no spaces in between locations): ")
# start_date = input("Start date (format: MM-DD-YYYY): ")
# end_date = input("End date: (format: MM-DD-YYYY): ")
# serotype = input("Serotype (e.g. H5N1): ")
# serotypes = list(serotype)
# genotypes = input("Genotypes (separate with commas and no spaces in between genotypes): ")
# genotypes = genotypes.split(",")

# Dates and locations
locations = "Antarctica,North America,South America"
start_date = "11-01-2021"
end_date = "06-19-2026"
prev_end_date = "06-05-2026"
date_range = start_date + "--" + end_date
prev_date_range = start_date + "--" + prev_end_date

# Maintenance serotypes and genotypes
serotypes = ["H5N1"]
genotypes = ["B3.13"] # , "D1.1", "Not"]

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# downloads = "C:/Users/maksi/Downloads/"
# references = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/references/"

home = "C:/Users/maksiaevai.NCBI_NT/OneDrive - National Institutes of Health/Documents/Virus_Evolution/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Downloads/" # MUST be downloads folder. Clean out downloads folder after each use. 
references = "C:/Users/maksiaevai.NCBI_NT/OneDrive - National Institutes of Health/Documents/Virus_Evolution/Avian_Flu/references/"

downloads_saved = home + "NCBI_Virus/downloads/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/" 
prev_downloads_saved = home + "NCBI_Virus/downloads/" + prev_date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/" 

andersen = home + "Andersen/avian-influenza/metadata/"
temp_files = home + "NCBI_Virus/temp/"
complete_files = home + "NCBI_Virus/complete/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/"
if not os.path.exists(complete_files): # checking if the directory exists or not
    os.makedirs(complete_files) # if the directory is not present then create it

os.chdir(references)
states_ref = pd.read_csv("states_ref.csv")

# All serotypes and genotypes
# serotype = ""
# genotypes_df = pd.read_excel("genotype_key.xlsx")
# genotypes = list(genotypes_df["Genotype"])

## Downloading Data

In [3]:
os.chdir(downloads)

if not os.path.exists(downloads_saved): # checking if the directory exists or not
    os.makedirs(downloads_saved) # if the directory is not present then create it

# Move downloaded files to saved downloads
for dirpath, dirs, files in os.walk(downloads_saved):
    if len(files) != 0:
        break 
    else: # If we don't have any downloaded files
        # Get files
        # open_ncbi_virus(browser, sleep_time, locations, start_date, end_date)

        # Re-try 
        for dirpath, dirs, files in os.walk(downloads):
            if len(files) > 0: # If we have any files that need to be moved
                for file in files:
                    file_name = os.path.join(dirpath, file)
                    destination_path = os.path.join(downloads_saved, os.path.basename(file_name))
                    try:
                        shutil.move(file_name, destination_path)
                    except:
                        print("Error moving file", file_name)
                        continue 
            break 
    break

## De-Duplication

In [4]:
# Get metadata
os.chdir(downloads_saved)
metadata = pd.read_csv("sequences.csv")
print(len(metadata))

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.Assembly, as_index=False).size()
print(metadata_counts)
metadata_counted = metadata.merge(metadata_counts, on="Assembly")

# Only keep those with size >= 8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates
metadata_complete_segs = metadata_counted.drop_duplicates(subset="GenBank_Title", keep="last") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]
metadata_segments = metadata_complete_segs
metadata_segments

162538
              Assembly  size
0      GCA_038163845.1     8
1      GCA_038163995.1     8
2      GCA_038164135.1     8
3      GCA_038164315.1     8
4      GCA_038164335.1     8
...                ...   ...
18712  GCA_058182645.1     8
18713  GCA_058315875.1     8
18714  GCA_058329715.1     8
18715  GCA_058329825.1     8
18716  GCA_058329855.1     8

[18717 rows x 2 columns]

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Host,Tissue_Specimen_Source,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size
0,PZ544326.1,GenBank,GCA_058329715.1,SRR38788396,SAMN60347461,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Bos taurus,mammalian milk,"Lantz,K., Stuber,T.",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2026-05-04,2026-06-17,ssRNA(-),8
1,PZ544327.1,GenBank,GCA_058329715.1,SRR38788396,SAMN60347461,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Bos taurus,mammalian milk,"Lantz,K., Stuber,T.",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2026-05-04,2026-06-17,ssRNA(-),8
2,PZ544328.1,GenBank,GCA_058329715.1,SRR38788396,SAMN60347461,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Bos taurus,mammalian milk,"Lantz,K., Stuber,T.",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2026-05-04,2026-06-17,ssRNA(-),8
3,PZ544329.1,GenBank,GCA_058329715.1,SRR38788396,SAMN60347461,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Bos taurus,mammalian milk,"Lantz,K., Stuber,T.",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2026-05-04,2026-06-17,ssRNA(-),8
4,PZ544330.1,GenBank,GCA_058329715.1,SRR38788396,SAMN60347461,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Bos taurus,mammalian milk,"Lantz,K., Stuber,T.",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2026-05-04,2026-06-17,ssRNA(-),8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149713,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
149714,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
149715,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
149716,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
149717,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8

## Add sequences to dataframe

In [5]:
# NCBI Virus Naming Convention:
# "Accession|GenBank_Title|Assembly|SRA Accession|BioSample|BioProject|Genotype|Isolate|Geo Location|Host|Collection Date"

# Get sequences and headers together
# headers = []
# isolates = []
# sras = []
# headers_seqs = {}

os.chdir(downloads_saved)

sequences_fasta = df_from_fasta("sequences.fasta") # Turn fasta into a dataframe

sequences_fasta["Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split(" |")[0].replace(">",""))

print(sequences_fasta["full_header"])

# Extract segment number so that we can add the correct sequences to the correct sample
# sequences_fasta["Segment"] = sequences_fasta["full_header"].apply(lambda x: int(re.search(r'segment (.?) ', x.split("|")[-2]).group(1)))

# Double-check the de-duplication
print(len(sequences_fasta)) 
# print(sequences_fasta.head())
print(len(metadata_segments))

# Add sequences to the dataframe
metadata_segments = pd.merge(metadata_segments, sequences_fasta, on="Accession") # , "Segment"])

0         >PZ437028.1 |Influenza A virus (A/Leptonychote...
1         >PZ544326.1 |Influenza A virus (A/cattle/ID/26...
2         >PZ544327.1 |Influenza A virus (A/cattle/ID/26...
3         >PZ544328.1 |Influenza A virus (A/cattle/ID/26...
4         >PZ544329.1 |Influenza A virus (A/cattle/ID/26...
                                ...
162533    >OK205883.1 |Influenza A virus (A/chicken/Vera...
162534    >OK205884.1 |Influenza A virus (A/chicken/Vera...
162535    >OK205885.1 |Influenza A virus (A/chicken/Vera...
162536    >OK205886.1 |Influenza A virus (A/chicken/Vera...
162537    >OK205887.1 |Influenza A virus (A/chicken/Vera...
Name: full_header, Length: 162538, dtype: object
162538
148206

In [6]:
metadata_segments

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size,full_header,sequence
0,PZ544326.1,GenBank,GCA_058329715.1,SRR38788396,SAMN60347461,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Lantz,K., Stuber,T.",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2026-05-04,2026-06-17,ssRNA(-),8,>PZ544326.1 |Influenza A virus (A/cattle/ID/26...,ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
1,PZ544327.1,GenBank,GCA_058329715.1,SRR38788396,SAMN60347461,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Lantz,K., Stuber,T.",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2026-05-04,2026-06-17,ssRNA(-),8,>PZ544327.1 |Influenza A virus (A/cattle/ID/26...,ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
2,PZ544328.1,GenBank,GCA_058329715.1,SRR38788396,SAMN60347461,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Lantz,K., Stuber,T.",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2026-05-04,2026-06-17,ssRNA(-),8,>PZ544328.1 |Influenza A virus (A/cattle/ID/26...,ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
3,PZ544329.1,GenBank,GCA_058329715.1,SRR38788396,SAMN60347461,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Lantz,K., Stuber,T.",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2026-05-04,2026-06-17,ssRNA(-),8,>PZ544329.1 |Influenza A virus (A/cattle/ID/26...,ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
4,PZ544330.1,GenBank,GCA_058329715.1,SRR38788396,SAMN60347461,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Lantz,K., Stuber,T.",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2026-05-04,2026-06-17,ssRNA(-),8,>PZ544330.1 |Influenza A virus (A/cattle/ID/26...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148201,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205883.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...
148202,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205884.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...
148203,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205885.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...
148204,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205886.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...
148205,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205887.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...

## Find genotypes

(Using old genoflu results or Andersen Lab genoflu output) <br>
Old genoflu results should accumulate into one file to avoid having to genotype anything again.

### Find old genotypes

In [7]:
# Switch directory to previous week
os.chdir(prev_downloads_saved)

# Get both files from previous week
genoflu_output = pd.read_csv("output.tsv", delimiter="\t")
genoflu_results = pd.read_csv("results.tsv", delimiter="\t")

# Get old results from output.tsv
genoflu_old = pd.concat([genoflu_output, genoflu_results])
# genoflu_old = genoflu_old.rename(columns={"Strain":"Partial_Header"}) # So we can merge
print(genoflu_old)

# Switch back directory
os.chdir(downloads_saved)

# Save this output for the future
genoflu_old.to_csv("output.tsv", sep="\t", index=False)

                                                  Strain  \
0      Influenza_A_virus__Mexico__Estado_de_Mexico_CP...
1      Influenza_A_virus__Mexico__Estado_de_Mexico_CP...
2      Influenza_A_virus__Mexico__Ciudad_de_Mexico_CP...
3      Influenza_A_virus__Mexico__Estado_de_Mexico_CP...
4      Influenza_A_virus__Mexico__Michoacan_CPA_02011...
...                                                  ...
13011                                    GCA_039460795_1
13012                                    GCA_046427615_1
13013                                    GCA_048675505_1
13014                                    GCA_039288985_1
13015                                    GCA_047522105_1

                                                Genotype  \
0      Not assigned: Only 3 segments >98.0% match fou...
1      Not assigned: Only 3 segments >98.0% match fou...
2      Not assigned: Only 3 segments >98.0% match fou...
3      Not assigned: Only 3 segments >98.0% match fou...
4      Not assigned: Only 6 segments >98.0% match fou...
...                                                  ...
13011                                               B3.6
13012                                               B3.6
13013                                               D1.3
13014                                                 A1
13015                                              B3.13

                             Genotype List Used, >=98.0%  \
0                               PA:ea1, MP:ea1, NS:am1.1
1                               PA:ea1, MP:ea1, NS:am1.1
2                               PA:ea1, MP:ea1, NS:am1.1
3                               PA:ea1, MP:ea1, NS:am1.1
4      PB2:am2.1, PB1:am1.2, PA:ea1, HA:ea1, MP:ea1, ...
...                                                  ...
13011  PB2:am5, PB1:am4, PA:ea1, HA:ea1, NP:am1.4.1, ...
13012  PB2:am5, PB1:am4, PA:ea1, HA:ea1, NP:am1.4.1, ...
13013  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
13014  PB2:ea1, PB1:ea1, PA:ea1, HA:ea1, NP:ea1, NA:e...
13015  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...

                              Genotype Sample Title List  \
0      am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
1      am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
2      am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
3      am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
4      am2.1:22-009329-001:PB2, am1.2:22-010085-001:P...
...                                                  ...
13011  am5:23-001855-001:PB2, am4:23-001855-001:PB1, ...
13012  am5:23-001855-001:PB2, am4:23-001855-001:PB1, ...
13013  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
13014  ea1:22-003707-003:PB2, ea1:22-003707-003:PB1, ...
13015  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...

                             Genotype Percent Match List  \
0      97.63%, 92.66%, 98.33%, 97.53%, 88.91%, 83.52%...
1      97.67%, 92.66%, 98.33%, 97.59%, 88.84%, 83.52%...
2      97.57%, 92.70%, 98.28%, 97.59%, 88.84%, 83.52%...
3      97.67%, 92.70%, 98.33%, 97.36%, 88.84%, 83.43%...
4      98.90%, 98.77%, 98.98%, 98.47%, 88.96%, 83.70%...
...                                                  ...
13011  99.56%, 99.65%, 99.07%, 99.00%, 99.53%, 99.29%...
13012  99.61%, 99.60%, 99.30%, 98.89%, 99.47%, 99.29%...
13013  99.65%, 99.30%, 99.53%, 99.53%, 99.60%, 98.58%...
13014  99.87%, 99.69%, 99.44%, 99.71%, 99.87%, 99.57%...
13015  98.55%, 99.43%, 99.07%, 98.47%, 99.06%, 98.79%...

                  Genotype Mismatch List  \
0      54, 167, 36, 42, 166, 186, 18, 14
1      53, 167, 36, 41, 167, 186, 18, 14
2      35, 166, 37, 41, 167, 186, 19, 14
3      53, 166, 36, 45, 167, 187, 18, 14
4        25, 28, 22, 26, 165, 182, 12, 9
...                                  ...
13011         10, 8, 20, 17, 7, 10, 9, 6
13012          9, 9, 15, 19, 8, 10, 9, 5
13013          8, 16, 10, 8, 6, 20, 2, 9
13014            3, 7, 12, 5, 2, 6, 1, 3
13015      33, 13, 20, 26, 14, 17, 10, 8

      Genotype Average Depth of Coverage List             Date run
0           Ran on FASTA - No Coverage Report  2025-12-03_10-28-26
1           Ran on FASTA - No Coverage Report  2025-12-03_10-28-27
2           Ran on FASTA - No Coverage Report  2025-12-03_10-28-27
3           Ran on FASTA - No Coverage Report  2025-12-03_10-28-27
4           Ran on FASTA - No Coverage Report  2025-12-03_10-28-28
...                                       ...                  ...
13011       Ran on FASTA - No Coverage Report  2026-06-10_12-52-04
13012       Ran on FASTA - No Coverage Report  2026-06-10_12-52-05
13013       Ran on FASTA - No Coverage Report  2026-06-10_12-52-05
13014       Ran on FASTA - No Coverage Report  2026-06-10_12-52-05
13015       Ran on FASTA - No Coverage Report  2026-06-10_12-52-05

[37735 rows x 8 columns]

In [8]:

metadata_segments["Partial_Header_temp"] = metadata_segments["Isolate"] # Get only isolate

for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]: # Forbidden punctuation
    metadata_segments["Partial_Header_temp"] = metadata_segments["Partial_Header_temp"].apply(lambda x: x.replace(c, "_") if x == x else x)

# Merge to get already-genotyped segments
genoflu_old["Partial_Header_temp"] = genoflu_old["Strain"].apply(lambda x: re.split(r'Influenza_A_virus__\D*__\D*_', x)[-1]) # Get only isolate 
genoflu_old["Partial_Header_temp"] = genoflu_old["Partial_Header_temp"].apply(lambda x: re.split(r'_H.N._20.{2}_.{2}_.{2}', x)[0]) # Get only isolate

metadata_segments_old = metadata_segments.merge(genoflu_old, how="inner", on="Partial_Header_temp") 

# Isolate not-already-genotyped segments
metadata_segments_new = metadata_segments.merge(genoflu_old, indicator=True, how='left', on="Partial_Header_temp").loc[lambda x : x['_merge']=='left_only'] 

print(len(metadata_segments_old))
print(len(metadata_segments_new))

128
148078

In [9]:
# Get genoflu results from Andersen and see if any fit

os.chdir(andersen)

genoflu_andersen = pd.read_csv("genoflu_results.tsv", delimiter="\t")
genoflu_andersen = genoflu_andersen.rename(columns={"sample":"SRA_Accession"}) # So we can merge with old
# genoflu_andersen["SRA_Accession"] = genoflu_andersen["Strain"] # So we can merge with new

# Find those genotyped by Andersen via merge
metadata_segments_known_andersen = metadata_segments_new.merge(genoflu_andersen, how="inner", on="SRA_Accession")
print(metadata_segments_known_andersen)
# Rename genotype by Andersen to concatenate
metadata_segments_known_andersen["Genotype_y"] = metadata_segments_known_andersen["Genotype"]

# Keep all known genotypes
metadata_segments_known = pd.concat([metadata_segments_old, metadata_segments_known_andersen]) # , on="SRA_Accession", how="left") # Since we know both of these

print(metadata_segments_old)
print(metadata_segments_known_andersen)

        Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0      PZ544326.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
1      PZ544327.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
2      PZ544328.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
3      PZ544329.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
4      PZ544330.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
...           ...            ...              ...           ...           ...
81315  PP740725.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184
81316  PP740726.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184
81317  PP740727.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184
81318  PP740728.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184
81319  PP740729.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184

         BioProject      Organism_Name                         Species  \
0      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
1      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
2      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
4      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
...             ...                ...                             ...
81315  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81316  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81317  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81318  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81319  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                     Genus            Family  ... Date run     _merge  \
0      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
1      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
2      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
...                    ...               ...  ...      ...        ...
81315  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81316  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81317  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81318  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81319  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only

                      date       File Name  Genotype  \
0      2026-05-27_13-57-06  SRR38788396.fa     B3.13
1      2026-05-27_13-57-06  SRR38788396.fa     B3.13
2      2026-05-27_13-57-06  SRR38788396.fa     B3.13
3      2026-05-27_13-57-06  SRR38788396.fa     B3.13
4      2026-05-27_13-57-06  SRR38788396.fa     B3.13
...                    ...             ...       ...
81315  2025-05-09_10-47-05  SRR28752446.fa     B3.13
81316  2025-05-09_10-47-05  SRR28752446.fa     B3.13
81317  2025-05-09_10-47-05  SRR28752446.fa     B3.13
81318  2025-05-09_10-47-05  SRR28752446.fa     B3.13
81319  2025-05-09_10-47-05  SRR28752446.fa     B3.13

                           Genotype List Used, >=98.0%_y  \
0      PA:ea1, NS:am1.1, PB2:am2.2, HA:ea1, NP:am8, P...
1      PA:ea1, NS:am1.1, PB2:am2.2, HA:ea1, NP:am8, P...
2      PA:ea1, NS:am1.1, PB2:am2.2, HA:ea1, NP:am8, P...
3      PA:ea1, NS:am1.1, PB2:am2.2, HA:ea1, NP:am8, P...
4      PA:ea1, NS:am1.1, PB2:am2.2, HA:ea1, NP:am8, P...
...                                                  ...
81315  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...
81316  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...
81317  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...
81318  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...
81319  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...

                            Genotype Sample Title List_y  \
0      ea1:22-003707-003:PA, am1.1:22-010085-001:NS, ...
1      ea1:22-003707-003:PA, am1.1:22-010085-001:NS, ...
2      ea1:22-003707-003:PA, am1.1:22-010085-001:NS, ...
3      ea1:22-003707-003:PA, am1.1:22-010085-001:NS, ...
4      ea1:22-003707-003:PA, am1.1:22-010085-001:NS, ...
...                                                  ...
81315  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
81316  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
81317  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
81318  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
81319  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...

                           Genotype Percent Match List_y  \
0      98.61%, 98.45%, 98.51%, 99.12%, 98.73%, 99.34%...
1      98.61%, 98.45%, 98.51%, 99.12%, 98.73%, 99.34%...
2      98.61%, 98.45%, 98.51%, 99.12%, 98.73%, 99.34%...
3      98.61%, 98.45%, 98.51%, 99.12%, 98.73%, 99.34%...
4      98.61%, 98.45%, 98.51%, 99.12%, 98.73%, 99.34%...
...                                                  ...
81315  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
81316  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
81317  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
81318  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
81319  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...

             Genotype Mismatch List_y  \
0      30, 13, 34, 15, 19, 15, 11, 14
1      30, 13, 34, 15, 19, 15, 11, 14
2      30, 13, 34, 15, 19, 15, 11, 14
3      30, 13, 34, 15, 19, 15, 11, 14
4      30, 13, 34, 15, 19, 15, 11, 14
...                               ...
81315   7, 11, 25, 21, 11, 18, 10, 14
81316   7, 11, 25, 21, 11, 18, 10, 14
81317   7, 11, 25, 21, 11, 18, 10, 14
81318   7, 11, 25, 21, 11, 18, 10, 14
81319   7, 11, 25, 21, 11, 18, 10, 14

      Genotype Average Depth of Coverage List_y
0             Ran on FASTA - No Coverage Report
1             Ran on FASTA - No Coverage Report
2             Ran on FASTA - No Coverage Report
3             Ran on FASTA - No Coverage Report
4             Ran on FASTA - No Coverage Report
...                                         ...
81315         Ran on FASTA - No Coverage Report
81316         Ran on FASTA - No Coverage Report
81317         Ran on FASTA - No Coverage Report
81318         Ran on FASTA - No Coverage Report
81319         Ran on FASTA - No Coverage Report

[81320 rows x 49 columns]
      Accession GenBank_RefSeq         Assembly SRA_Accession BioSample  \
0    OL539626.1        GenBank  GCA_039236455.1           NaN       NaN
1    OL539627.1        GenBank  GCA_039236455.1           NaN       NaN
2    OL539628.1        GenBank  GCA_039236455.1           NaN       NaN
3    OL539629.1        GenBank  GCA_039236455.1           NaN       NaN
4    OL539630.1        GenBank  GCA_039236455.1           NaN       NaN
..          ...            ...              ...           ...       ...
123  OK205667.1        GenBank  GCA_038971685.1           NaN       NaN
124  OK205668.1        GenBank  GCA_038971685.1           NaN       NaN
125  OK205669.1        GenBank  GCA_038971685.1           NaN       NaN
126  OK205670.1        GenBank  GCA_038971685.1           NaN       NaN
127  OK205671.1        GenBank  GCA_038971685.1           NaN       NaN

    BioProject      Organism_Name                         Species  \
0          NaN  Influenza A virus  Alphainfluenzavirus influenzae
1          NaN  Influenza A virus  Alphainfluenzavirus influenzae
2          NaN  Influenza A virus  Alphainfluenzavirus influenzae
3          NaN  Influenza A virus  Alphainfluenzavirus influenzae
4          NaN  Influenza A virus  Alphainfluenzavirus influenzae
..         ...                ...                             ...
123        NaN  Influenza A virus  Alphainfluenzavirus influenzae
124        NaN  Influenza A virus  Alphainfluenzavirus influenzae
125        NaN  Influenza A virus  Alphainfluenzavirus influenzae
126        NaN  Influenza A virus  Alphainfluenzavirus influenzae
127        NaN  Influenza A virus  Alphainfluenzavirus influenzae

                   Genus            Family  ...  \
0    Alphainfluenzavirus  Orthomyxoviridae  ...
1    Alphainfluenzavirus  Orthomyxoviridae  ...
2    Alphainfluenzavirus  Orthomyxoviridae  ...
3    Alphainfluenzavirus  Orthomyxoviridae  ...
4    Alphainfluenzavirus  Orthomyxoviridae  ...
..                   ...               ...  ...
123  Alphainfluenzavirus  Orthomyxoviridae  ...
124  Alphainfluenzavirus  Orthomyxoviridae  ...
125  Alphainfluenzavirus  Orthomyxoviridae  ...
126  Alphainfluenzavirus  Orthomyxoviridae  ...
127  Alphainfluenzavirus  Orthomyxoviridae  ...

                                              sequence Partial_Header_temp  \
0    ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...           AH0179389
1    ATGGATGTCAATCCGACTTTACTCTTCTTGAAAGTTCCAGCGCAAA...           AH0179389
2    ATGGAAGATTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...           AH0179389
3    ATGGAAAGAATAGTGATTGCCCTCGCAATAATCAGCATTGTCAAAG...           AH0179389
4    ATGGCGTCTCAAGGCACCAAACGATCTTATGAACAAATGGAAACTG...           AH0179389
..                                                 ...                 ...
123  ATGGAAAGAATAGCAATTGCCTTTGCATTAATCAGCATTGTCACAG...         LVVX17186_2
124  GTAGATAATCACTCACTGAGTGACATTCACATCATGGCGTCTCAAG...         LVVX17186_2
125  AATGAATCCAAATCAGAAAATAATAACAATAGGCTCCATTTCTCTA...         LVVX17186_2
126  TAGATGTTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTT...         LVVX17186_2
127  GTGACAAATACATAATGGACTCCAACACGATAACCTCGTTTCAGGT...         LVVX17186_2

                                                Strain  \
0    Influenza_A_virus__USA__Steuben_County__New_Yo...
1    Influenza_A_virus__USA__Steuben_County__New_Yo...
2    Influenza_A_virus__USA__Steuben_County__New_Yo...
3    Influenza_A_virus__USA__Steuben_County__New_Yo...
4    Influenza_A_virus__USA__Steuben_County__New_Yo...
..                                                 ...
123  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
124  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
125  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
126  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
127  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...

                                            Genotype_y  \
0    Not assigned: Only 4 segments >98.0% match fou...
1    Not assigned: Only 4 segments >98.0% match fou...
2    Not assigned: Only 4 segments >98.0% match fou...
3    Not assigned: Only 4 segments >98.0% match fou...
4    Not assigned: Only 4 segments >98.0% match fou...
..                                                 ...
123  Not assigned: Only 0 segments >98.0% match fou...
124  Not assigned: Only 0 segments >98.0% match fou...
125  Not assigned: Only 0 segments >98.0% match fou...
126  Not assigned: Only 0 segments >98.0% match fou...
127  Not assigned: Only 0 segments >98.0% match fou...

              Genotype List Used, >=98.0%  \
0    PB2:am5, PB1:am4, NA:am6N2, NS:am1.2
1    PB2:am5, PB1:am4, NA:am6N2, NS:am1.2
2    PB2:am5, PB1:am4, NA:am6N2, NS:am1.2
3    PB2:am5, PB1:am4, NA:am6N2, NS:am1.2
4    PB2:am5, PB1:am4, NA:am6N2, NS:am1.2
..                                    ...
123                                   NaN
124                                   NaN
125                                   NaN
126                                   NaN
127                                   NaN

                            Genotype Sample Title List  \
0    am5:23-001855-001:PB2, am4:23-001855-001:PB1, ...
1    am5:23-001855-001:PB2, am4:23-001855-001:PB1, ...
2    am5:23-001855-001:PB2, am4:23-001855-001:PB1, ...
3    am5:23-001855-001:PB2, am4:23-001855-001:PB1, ...
4    am5:23-001855-001:PB2, am4:23-001855-001:PB1, ...
..                                                 ...
123  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
124  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
125  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
126  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
127  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...

                           Genotype Percent Match List  \
0    99.25%, 99.08%, 97.44%, 80.56%, 95.72%, 100.00...
1    99.25%, 99.08%, 97.44%, 80.56%, 95.72%, 100.00...
2    99.25%, 99.08%, 97.44%, 80.56%, 95.72%, 100.00...
3    99.25%, 99.08%, 97.44%, 80.56%, 95.72%, 100.00...
4    99.25%, 99.08%, 97.44%, 80.56%, 95.72%, 100.00...
..                                                 ...
123  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
124  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
125  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
126  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
127  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...

                   Genotype Mismatch List  \
0          17, 21, 55, 311, 64, 0, 25, 11
1          17, 21, 55, 311, 64, 0, 25, 11
2          17, 21, 55, 311, 64, 0, 25, 11
3          17, 21, 55, 311, 64, 0, 25, 11
4          17, 21, 55, 311, 64, 0, 25, 11
..                                    ...
123  176, 113, 256, 363, 151, 171, 82, 77
124  176, 113, 256, 363, 151, 171, 82, 77
125  176, 113, 256, 363, 151, 171, 82, 77
126  176, 113, 256, 363, 151, 171, 82, 77
127  176, 113, 256, 363, 151, 171, 82, 77

    Genotype Average Depth of Coverage List             Date run
0         Ran on FASTA - No Coverage Report  2025-12-03_18-44-19
1         Ran on FASTA - No Coverage Report  2025-12-03_18-44-19
2         Ran on FASTA - No Coverage Report  2025-12-03_18-44-19
3         Ran on FASTA - No Coverage Report  2025-12-03_18-44-19
4         Ran on FASTA - No Coverage Report  2025-12-03_18-44-19
..                                      ...                  ...
123       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
124       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
125       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
126       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
127       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44

[128 rows x 40 columns]
        Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0      PZ544326.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
1      PZ544327.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
2      PZ544328.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
3      PZ544329.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
4      PZ544330.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
...           ...            ...              ...           ...           ...
81315  PP740725.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184
81316  PP740726.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184
81317  PP740727.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184
81318  PP740728.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184
81319  PP740729.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184

         BioProject      Organism_Name                         Species  \
0      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
1      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
2      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
4      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
...             ...                ...                             ...
81315  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81316  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81317  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81318  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81319  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                     Genus            Family  ... Date run     _merge  \
0      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
1      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
2      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
...                    ...               ...  ...      ...        ...
81315  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81316  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81317  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81318  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81319  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only

                      date       File Name  Genotype  \
0      2026-05-27_13-57-06  SRR38788396.fa     B3.13
1      2026-05-27_13-57-06  SRR38788396.fa     B3.13
2      2026-05-27_13-57-06  SRR38788396.fa     B3.13
3      2026-05-27_13-57-06  SRR38788396.fa     B3.13
4      2026-05-27_13-57-06  SRR38788396.fa     B3.13
...                    ...             ...       ...
81315  2025-05-09_10-47-05  SRR28752446.fa     B3.13
81316  2025-05-09_10-47-05  SRR28752446.fa     B3.13
81317  2025-05-09_10-47-05  SRR28752446.fa     B3.13
81318  2025-05-09_10-47-05  SRR28752446.fa     B3.13
81319  2025-05-09_10-47-05  SRR28752446.fa     B3.13

                           Genotype List Used, >=98.0%_y  \
0      PA:ea1, NS:am1.1, PB2:am2.2, HA:ea1, NP:am8, P...
1      PA:ea1, NS:am1.1, PB2:am2.2, HA:ea1, NP:am8, P...
2      PA:ea1, NS:am1.1, PB2:am2.2, HA:ea1, NP:am8, P...
3      PA:ea1, NS:am1.1, PB2:am2.2, HA:ea1, NP:am8, P...
4      PA:ea1, NS:am1.1, PB2:am2.2, HA:ea1, NP:am8, P...
...                                                  ...
81315  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...
81316  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...
81317  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...
81318  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...
81319  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...

                            Genotype Sample Title List_y  \
0      ea1:22-003707-003:PA, am1.1:22-010085-001:NS, ...
1      ea1:22-003707-003:PA, am1.1:22-010085-001:NS, ...
2      ea1:22-003707-003:PA, am1.1:22-010085-001:NS, ...
3      ea1:22-003707-003:PA, am1.1:22-010085-001:NS, ...
4      ea1:22-003707-003:PA, am1.1:22-010085-001:NS, ...
...                                                  ...
81315  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
81316  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
81317  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
81318  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
81319  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...

                           Genotype Percent Match List_y  \
0      98.61%, 98.45%, 98.51%, 99.12%, 98.73%, 99.34%...
1      98.61%, 98.45%, 98.51%, 99.12%, 98.73%, 99.34%...
2      98.61%, 98.45%, 98.51%, 99.12%, 98.73%, 99.34%...
3      98.61%, 98.45%, 98.51%, 99.12%, 98.73%, 99.34%...
4      98.61%, 98.45%, 98.51%, 99.12%, 98.73%, 99.34%...
...                                                  ...
81315  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
81316  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
81317  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
81318  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
81319  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...

             Genotype Mismatch List_y  \
0      30, 13, 34, 15, 19, 15, 11, 14
1      30, 13, 34, 15, 19, 15, 11, 14
2      30, 13, 34, 15, 19, 15, 11, 14
3      30, 13, 34, 15, 19, 15, 11, 14
4      30, 13, 34, 15, 19, 15, 11, 14
...                               ...
81315   7, 11, 25, 21, 11, 18, 10, 14
81316   7, 11, 25, 21, 11, 18, 10, 14
81317   7, 11, 25, 21, 11, 18, 10, 14
81318   7, 11, 25, 21, 11, 18, 10, 14
81319   7, 11, 25, 21, 11, 18, 10, 14

      Genotype Average Depth of Coverage List_y
0             Ran on FASTA - No Coverage Report
1             Ran on FASTA - No Coverage Report

### Create FASTA files of unknown genotypes

In [10]:
metadata_segments_known

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Genotype Average Depth of Coverage List_x,_merge,date,File Name,Genotype,"Genotype List Used, >=98.0%_y",Genotype Sample Title List_y,Genotype Percent Match List_y,Genotype Mismatch List_y,Genotype Average Depth of Coverage List_y
0,OL539626.1,GenBank,GCA_039236455.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,OL539627.1,GenBank,GCA_039236455.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,OL539628.1,GenBank,GCA_039236455.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,OL539629.1,GenBank,GCA_039236455.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,OL539630.1,GenBank,GCA_039236455.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81315,PP740725.1,GenBank,GCA_039251605.1,SRR28752446,SAMN41019184,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2025-05-09_10-47-05,SRR28752446.fa,B3.13,"NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...","am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...","99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...","7, 11, 25, 21, 11, 18, 10, 14",Ran on FASTA - No Coverage Report
81316,PP740726.1,GenBank,GCA_039251605.1,SRR28752446,SAMN41019184,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2025-05-09_10-47-05,SRR28752446.fa,B3.13,"NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...","am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...","99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...","7, 11, 25, 21, 11, 18, 10, 14",Ran on FASTA - No Coverage Report
81317,PP740727.1,GenBank,GCA_039251605.1,SRR28752446,SAMN41019184,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2025-05-09_10-47-05,SRR28752446.fa,B3.13,"NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...","am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...","99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...","7, 11, 25, 21, 11, 18, 10, 14",Ran on FASTA - No Coverage Report
81318,PP740728.1,GenBank,GCA_039251605.1,SRR28752446,SAMN41019184,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2025-05-09_10-47-05,SRR28752446.fa,B3.13,"NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...","am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...","99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...","7, 11, 25, 21, 11, 18, 10, 14",Ran on FASTA - No Coverage Report
81319,PP740729.1,GenBank,GCA_039251605.1,SRR28752446,SAMN41019184,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2025-05-09_10-47-05,SRR28752446.fa,B3.13,"NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...","am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...","99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...","7, 11, 25, 21, 11, 18, 10, 14",Ran on FASTA - No Coverage Report

In [11]:
# Create 8 fasta files per segment

# Get all the segments
metadata_segments_new["Partial_Header"] = metadata_segments_new["Assembly"].apply(lambda x: ">" + x if x == x else x) # .apply(lambda x: x.split("|")[-1].split(")")[0]) # Get only genbank name
metadata_segments_new = metadata_segments_new.dropna(subset="Partial_Header")

print(metadata_segments_new["Partial_Header"].values[0:5])

['>GCA_058329715.1' '>GCA_058329715.1' '>GCA_058329715.1'
 '>GCA_058329715.1' '>GCA_058329715.1']

In [12]:


# Create list of dataframes
df_list = []
for partial_header in list(set(metadata_segments_new["Partial_Header"].values)): # Unique partial headers only
    # Get smaller dataframe
    df = metadata_segments_new[metadata_segments_new["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    # Make sure there are 8 segments
    if len(df) == 8:
        # Forbidden characters in headers
        for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]:
            df["Partial_Header"] = df["Partial_Header"].apply(lambda x: x.replace(c, "_"))
            
        df["full_header"] = df["Partial_Header"]
        df_list.append(df)

print(metadata_segments_new["Partial_Header"])

print(df_list[0]["full_header"].values[:10])

# Make fasta files
for df in df_list:
    segments = list(set(df["Segment"].apply(lambda x: int(x)).values))
    for segment in segments:
        one_row = df[df["Segment"] == segment]
        df_to_fasta(one_row, str(segment) + "_seg.fasta", temp_files)

KeyboardInterrupt:

### Re-Labeling Using GenoFlu

**STOP HERE AND USE GENOFLU TO FIND NEW GENOTYPES.** Then, make sure "results.tsv" is in the NCBI_Virus downloads directory. <br>

To activate genoflu conda environment in BioWulf:
```
source myconda
conda activate genoflu
```

To run GenoFLU-multi, change directories to Multi-GenoFLU directory:
``` 
cd GenoFLU-multi
```

And then call the python script:

``` 
python bin/genoflu-multi.py -f <FASTA_directory>
```

In [12]:
# Ensure that user does the above
input("Use genoflu. Afterwards, press ENTER to continue.")

''

In [13]:
# Merging

os.chdir(downloads_saved)

# Read in genoflu results
output_genoflu = pd.read_csv("results.tsv", delimiter="\t") # This also shows the IDs of the new sequences -- incorporate into sequences report

# Create partial headers to merge genoflu results with previously unknown segments
metadata_segments_new["Partial_Header_Merge"] = metadata_segments_new["Assembly"] 
for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]: # Forbidden punctuation
    metadata_segments_new["Partial_Header_Merge"] = metadata_segments_new["Partial_Header_Merge"].apply(lambda x: x.replace(c, "_") if x==x else x)

# Reformat so we can merge
output_genoflu["Partial_Header_Merge"] = output_genoflu["Strain"] #.apply(lambda x: re.split(r'Influenza_A_virus__\D*__\D*_', x)[-1])
# output_genoflu["Partial_Header_Merge"] = output_genoflu["Partial_Header_Merge"].apply(lambda x: re.split(r'_H.N._(20|19).{2}_.{2}_.{2}', x)[0])

# Merge
metadata_genoflu = metadata_segments_new.merge(output_genoflu, how="inner", on="Partial_Header_Merge") #, suffixes=('_left', '_right')) 

# # Fill the rest of the 8 segments with the same genotype
# metadata_genoflu = metadata_genoflu.ffill(limit_area="inside", limit=7)



print(metadata_genoflu)

     Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0   PZ544326.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
1   PZ544327.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
2   PZ544328.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
3   PZ544329.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
4   PZ544330.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
5   PZ544331.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
6   PZ544332.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
7   PZ544333.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
8   PZ544334.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
9   PZ544335.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
10  PZ544336.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
11  PZ544337.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
12  PZ544338.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
13  PZ544339.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
14  PZ544340.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
15  PZ544341.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
16  PZ544342.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
17  PZ544343.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
18  PZ544344.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
19  PZ544345.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
20  PZ544346.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
21  PZ544347.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
22  PZ544348.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
23  PZ544349.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
24  PZ544350.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
25  PZ544351.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
26  PZ544352.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
27  PZ544353.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
28  PZ544354.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
29  PZ544355.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
30  PZ544356.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
31  PZ544357.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
32  PZ514095.1        GenBank  GCA_058182645.1           NaN           NaN
33  PZ514096.1        GenBank  GCA_058182645.1           NaN           NaN
34  PZ514097.1        GenBank  GCA_058182645.1           NaN           NaN
35  PZ514098.1        GenBank  GCA_058182645.1           NaN           NaN
36  PZ514099.1        GenBank  GCA_058182645.1           NaN           NaN
37  PZ514100.1        GenBank  GCA_058182645.1           NaN           NaN
38  PZ514101.1        GenBank  GCA_058182645.1           NaN           NaN
39  PZ514102.1        GenBank  GCA_058182645.1           NaN           NaN
40  PQ885514.1        GenBank  GCA_046891765.1           NaN           NaN
41  PQ885515.1        GenBank  GCA_046891765.1           NaN           NaN
42  PQ885516.1        GenBank  GCA_046891765.1           NaN           NaN
43  PQ885517.1        GenBank  GCA_046891765.1           NaN           NaN
44  PQ885518.1        GenBank  GCA_046891765.1           NaN           NaN
45  PQ885519.1        GenBank  GCA_046891765.1           NaN           NaN
46  PQ885520.1        GenBank  GCA_046891765.1           NaN           NaN
47  PQ885521.1        GenBank  GCA_046891765.1           NaN           NaN
48  PQ573558.1        GenBank  GCA_046435525.1           NaN           NaN
49  PQ573559.1        GenBank  GCA_046435525.1           NaN           NaN
50  PQ573560.1        GenBank  GCA_046435525.1           NaN           NaN
51  PQ573561.1        GenBank  GCA_046435525.1           NaN           NaN
52  PQ573562.1        GenBank  GCA_046435525.1           NaN           NaN
53  PQ573563.1        GenBank  GCA_046435525.1           NaN           NaN
54  PQ573564.1        GenBank  GCA_046435525.1           NaN           NaN
55  PQ573565.1        GenBank  GCA_046435525.1           NaN           NaN

      BioProject      Organism_Name                         Species  \
0   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
1   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
2   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
4   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
5   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
6   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
7   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
8   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
9   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
10  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
11  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
12  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
13  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
14  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
15  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
16  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
17  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
18  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
19  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
20  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
21  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
22  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
23  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
24  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
25  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
26  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
27  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
28  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
29  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
30  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
31  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
32           NaN  Influenza A virus  Alphainfluenzavirus influenzae
33           NaN  Influenza A virus  Alphainfluenzavirus influenzae
34           NaN  Influenza A virus  Alphainfluenzavirus influenzae
35           NaN  Influenza A virus  Alphainfluenzavirus influenzae
36           NaN  Influenza A virus  Alphainfluenzavirus influenzae
37           NaN  Influenza A virus  Alphainfluenzavirus influenzae
38           NaN  Influenza A virus  Alphainfluenzavirus influenzae
39           NaN  Influenza A virus  Alphainfluenzavirus influenzae
40  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
41  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
42  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
43  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
44  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
45  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
46  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
47  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
48  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
49  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
50  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
51  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
52  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
53  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
54  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
55  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae

                  Genus            Family  ...    Partial_Header  \
0   Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329715.1
1   Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329715.1
2   Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329715.1
3   Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329715.1
4   Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329715.1
5   Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329715.1
6   Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329715.1
7   Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329715.1
8   Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329825.1
9   Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329825.1
10  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329825.1
11  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329825.1
12  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329825.1
13  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329825.1
14  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329825.1
15  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329825.1
16  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329855.1
17  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329855.1
18  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329855.1
19  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329855.1
20  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329855.1
21  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329855.1
22  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329855.1
23  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058329855.1
24  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058315875.1
25  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058315875.1
26  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058315875.1
27  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058315875.1
28  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058315875.1
29  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058315875.1
30  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058315875.1
31  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058315875.1
32  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058182645.1
33  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058182645.1
34  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058182645.1
35  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058182645.1
36  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058182645.1
37  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058182645.1
38  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058182645.1
39  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_058182645.1
40  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046891765.1
41  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046891765.1
42  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046891765.1
43  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046891765.1
44  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046891765.1
45  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046891765.1
46  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046891765.1
47  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046891765.1
48  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046435525.1
49  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046435525.1
50  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046435525.1
51  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046435525.1
52  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046435525.1
53  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046435525.1
54  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046435525.1
55  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_046435525.1

   Partial_Header_Merge         Strain_y  \
0       GCA_058329715_1  GCA_058329715_1
1       GCA_058329715_1  GCA_058329715_1
2       GCA_058329715_1  GCA_058329715_1
3       GCA_058329715_1  GCA_058329715_1
4       GCA_058329715_1  GCA_058329715_1
5       GCA_058329715_1  GCA_058329715_1
6       GCA_058329715_1  GCA_058329715_1
7       GCA_058329715_1  GCA_058329715_1
8       GCA_058329825_1  GCA_058329825_1
9       GCA_058329825_1  GCA_058329825_1
10      GCA_058329825_1  GCA_058329825_1
11      GCA_058329825_1  GCA_058329825_1
12      GCA_058329825_1  GCA_058329825_1
13      GCA_058329825_1  GCA_058329825_1
14      GCA_058329825_1  GCA_058329825_1
15      GCA_058329825_1  GCA_058329825_1
16      GCA_058329855_1  GCA_058329855_1
17      GCA_058329855_1  GCA_058329855_1
18      GCA_058329855_1  GCA_058329855_1
19      GCA_058329855_1  GCA_058329855_1
20      GCA_058329855_1  GCA_058329855_1
21      GCA_058329855_1  GCA_058329855_1
22      GCA_058329855_1  GCA_058329855_1
23      GCA_058329855_1  GCA_058329855_1
24      GCA_058315875_1  GCA_058315875_1
25      GCA_058315875_1  GCA_058315875_1
26      GCA_058315875_1  GCA_058315875_1
27      GCA_058315875_1  GCA_058315875_1
28      GCA_058315875_1  GCA_058315875_1
29      GCA_058315875_1  GCA_058315875_1
30      GCA_058315875_1  GCA_058315875_1
31      GCA_058315875_1  GCA_058315875_1
32      GCA_058182645_1  GCA_058182645_1
33      GCA_058182645_1  GCA_058182645_1
34      GCA_058182645_1  GCA_058182645_1
35      GCA_058182645_1  GCA_058182645_1
36      GCA_058182645_1  GCA_058182645_1
37      GCA_058182645_1  GCA_058182645_1
38      GCA_058182645_1  GCA_058182645_1
39      GCA_058182645_1  GCA_058182645_1
40      GCA_046891765_1  GCA_046891765_1
41      GCA_046891765_1  GCA_046891765_1
42      GCA_046891765_1  GCA_046891765_1
43      GCA_046891765_1  GCA_046891765_1
44      GCA_046891765_1  GCA_046891765_1
45      GCA_046891765_1  GCA_046891765_1
46      GCA_046891765_1  GCA_046891765_1
47      GCA_046891765_1  GCA_046891765_1
48      GCA_046435525_1  GCA_046435525_1
49      GCA_046435525_1  GCA_046435525_1
50      GCA_046435525_1  GCA_046435525_1
51      GCA_046435525_1  GCA_046435525_1
52      GCA_046435525_1  GCA_046435525_1
53      GCA_046435525_1  GCA_046435525_1
54      GCA_046435525_1  GCA_046435525_1
55      GCA_046435525_1  GCA_046435525_1

                                             Genotype  \
0   Not assigned: Only 7 segments >98.0% match fou...
1   Not assigned: Only 7 segments >98.0% match fou...
2   Not assigned: Only 7 segments >98.0% match fou...
3   Not assigned: Only 7 segments >98.0% match fou...
4   Not assigned: Only 7 segments >98.0% match fou...
5   Not assigned: Only 7 segments >98.0% match fou...
6   Not assigned: Only 7 segments >98.0% match fou...
7   Not assigned: Only 7 segments >98.0% match fou...
8   Not assigned: Only 7 segments >98.0% match fou...
9   Not assigned: Only 7 segments >98.0% match fou...
10  Not assigned: Only 7 segments >98.0% match fou...
11  Not assigned: Only 7 segments >98.0% match fou...
12  Not assigned: Only 7 segments >98.0% match fou...
13  Not assigned: Only 7 segments >98.0% match fou...
14  Not assigned: Only 7 segments >98.0% match fou...
15  Not assigned: Only 7 segments >98.0% match fou...
16  Not assigned: Only 7 segments >98.0% match fou...
17  Not assigned: Only 7 segments >98.0% match fou...
18  Not assigned: Only 7 segments >98.0% match fou...
19  Not assigned: Only 7 segments >98.0% match fou...
20  Not assigned: Only 7 segments >98.0% match fou...
21  Not assigned: Only 7 segments >98.0% match fou...
22  Not assigned: Only 7 segments >98.0% match fou...
23  Not assigned: Only 7 segments >98.0% match fou...
24  Not assigned: Only 7 segments >98.0% match fou...
25  Not assigned: Only 7 segments >98.0% match fou...
26  Not assigned: Only 7 segments >98.0% match fou...
27  Not assigned: Only 7 segments >98.0% match fou...
28  Not assigned: Only 7 segments >98.0% match fou...
29  Not assigned: Only 7 segments >98.0% match fou...
30  Not assigned: Only 7 segments >98.0% match fou...
31  Not assigned: Only 7 segments >98.0% match fou...
32                                               D1.1
33                                               D1.1
34                                               D1.1
35                                               D1.1
36                                               D1.1
37                                               D1.1
38                                               D1.1
39                                               D1.1
40                                               D1.1
41                                               D1.1
42                                               D1.1
43                                               D1.1
44                                               D1.1
45                                               D1.1
46                                               D1.1
47                                               D1.1
48                                               D1.1
49                                               D1.1
50                                               D1.1
51                                               D1.1
52                                               D1.1
53                                               D1.1
54                                               D1.1
55                                               D1.1

                        Genotype List Used, >=98.0%_y  \
0   PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
1   PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
2   PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
3   PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
4   PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
5   PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
6   PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
7   PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
8   PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
9   PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
10  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
11  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
12  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
13  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
14  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
15  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
16  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
17  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
18  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
19  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
20  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
21  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
22  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
23  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
24  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
25  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
26  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
27  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
28  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
29  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
30  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
31  PB2:am2.2, PB1:am4, PA:ea1, NP:am8, NA:ea1, MP...
32  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
33  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
34  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
35  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
36  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
37  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
38  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
39  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
40  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
41  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
42  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
43  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
44  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
45  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
46  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
47  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
48  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

### Concatenate with known genotypes

In [14]:
# Rename columns so we can concatenate
print(metadata_segments_known.columns)

metadata_segments_known = metadata_segments_known.reset_index(drop=True)
print(metadata_segments_known)

print(metadata_genoflu.columns)
metadata_segments_known["Genotype_official"] = metadata_segments_known["Genotype_y"]
metadata_segments_known["Serotype"] = metadata_segments_known["Genotype_x"]
metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype"]
metadata_genoflu["Serotype"] = metadata_genoflu["Genotype_x"]

metadata_genoflu = metadata_genoflu.reset_index(drop=True)
print(metadata_genoflu)

# Concatenation
metadata_genoflu_concat = pd.concat([metadata_segments_known, metadata_genoflu])

metadata_genoflu_concat

Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Partial_Header_temp', 'Strain',
       'Genotype_y', 'Genotype List Used, >=98.0%',
       'Genotype Sample Title List', 'Genotype Percent Match List',
       'Genotype Mismatch List', 'Genotype Average Depth of Coverage List',
       'Date run', 'Genotype List Used, >=98.0%_x',
       'Genotype Sample Title List_x', 'Genotype Percent Match List_x',
       'Genotype Mismatch List_x', 'Genotype Average Depth of Coverage List_x',
       '_merge', 'date', 'File Name', 'Genotype',
       'Genotype List Used, >=98.0%_y', 'Genotype Sample Title List_y',
       'Genotype Percent Match List_y', 'Genotype Mismatch List_y',
       'Genotype Average Depth of Coverage List_y'],
      dtype='object')
        Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0      OL539626.1        GenBank  GCA_039236455.1           NaN           NaN
1      OL539627.1        GenBank  GCA_039236455.1           NaN           NaN
2      OL539628.1        GenBank  GCA_039236455.1           NaN           NaN
3      OL539629.1        GenBank  GCA_039236455.1           NaN           NaN
4      OL539630.1        GenBank  GCA_039236455.1           NaN           NaN
...           ...            ...              ...           ...           ...
81443  PP740725.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184
81444  PP740726.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184
81445  PP740727.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184
81446  PP740728.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184
81447  PP740729.1        GenBank  GCA_039251605.1   SRR28752446  SAMN41019184

         BioProject      Organism_Name                         Species  \
0               NaN  Influenza A virus  Alphainfluenzavirus influenzae
1               NaN  Influenza A virus  Alphainfluenzavirus influenzae
2               NaN  Influenza A virus  Alphainfluenzavirus influenzae
3               NaN  Influenza A virus  Alphainfluenzavirus influenzae
4               NaN  Influenza A virus  Alphainfluenzavirus influenzae
...             ...                ...                             ...
81443  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81444  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81445  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81446  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81447  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                     Genus            Family  ...  \
0      Alphainfluenzavirus  Orthomyxoviridae  ...
1      Alphainfluenzavirus  Orthomyxoviridae  ...
2      Alphainfluenzavirus  Orthomyxoviridae  ...
3      Alphainfluenzavirus  Orthomyxoviridae  ...
4      Alphainfluenzavirus  Orthomyxoviridae  ...
...                    ...               ...  ...
81443  Alphainfluenzavirus  Orthomyxoviridae  ...
81444  Alphainfluenzavirus  Orthomyxoviridae  ...
81445  Alphainfluenzavirus  Orthomyxoviridae  ...
81446  Alphainfluenzavirus  Orthomyxoviridae  ...
81447  Alphainfluenzavirus  Orthomyxoviridae  ...

      Genotype Average Depth of Coverage List_x     _merge  \
0                                           NaN        NaN
1                                           NaN        NaN
2                                           NaN        NaN
3                                           NaN        NaN
4                                           NaN        NaN
...                                         ...        ...
81443                                       NaN  left_only
81444                                       NaN  left_only
81445                                       NaN  left_only
81446                                       NaN  left_only
81447                                       NaN  left_only

                      date       File Name  Genotype  \
0                      NaN             NaN       NaN
1                      NaN             NaN       NaN
2                      NaN             NaN       NaN
3                      NaN             NaN       NaN
4                      NaN             NaN       NaN
...                    ...             ...       ...
81443  2025-05-09_10-47-05  SRR28752446.fa     B3.13
81444  2025-05-09_10-47-05  SRR28752446.fa     B3.13
81445  2025-05-09_10-47-05  SRR28752446.fa     B3.13
81446  2025-05-09_10-47-05  SRR28752446.fa     B3.13
81447  2025-05-09_10-47-05  SRR28752446.fa     B3.13

                           Genotype List Used, >=98.0%_y  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
81443  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...
81444  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...
81445  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...
81446  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...
81447  NS:am1.1, PB1:am4, PB2:am2.2, HA:ea1, MP:ea1, ...

                            Genotype Sample Title List_y  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
81443  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
81444  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
81445  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
81446  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...
81447  am1.1:22-010085-001:NS, am4:23-001855-001:PB1,...

                           Genotype Percent Match List_y  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
81443  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
81444  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
81445  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
81446  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...
81447  99.17%, 99.52%, 98.90%, 98.77%, 98.88%, 99.16%...

            Genotype Mismatch List_y Genotype Average Depth of Coverage List_y
0                                NaN                                       NaN
1                                NaN                                       NaN
2                                NaN                                       NaN
3                                NaN                                       NaN
4                                NaN                                       NaN
...                              ...                                       ...
81443  7, 11, 25, 21, 11, 18, 10, 14         Ran on FASTA - No Coverage Report
81444  7, 11, 25, 21, 11, 18, 10, 14         Ran on FASTA - No Coverage Report
81445  7, 11, 25, 21, 11, 18, 10, 14         Ran on FASTA - No Coverage Report
81446  7, 11, 25, 21, 11, 18, 10, 14         Ran on FASTA - No Coverage Report
81447  7, 11, 25, 21, 11, 18, 10, 14         Ran on FASTA - No Coverage Report

[81448 rows x 54 columns]
Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Partial_Header_temp', 'Strain_x',
       'Genotype_y', 'Genotype List Used, >=98.0%_x',
       'Genotype Sample Title List_x', 'Genotype Percent Match List_x',
       'Genotype Mismatch List_x', 'Genotype Average Depth of Coverage List_x',
       'Date run_x', '_merge', 'Partial_Header', 'Partial_Header_Merge',
       'Strain_y', 'Genotype', 'Genotype List Used, >=98.0%_y',
       'Genotype Sample Title List_y', 'Genotype Percent Match List_y',
       'Genotype Mismatch List_y', 'Genotype Average Depth of Coverage List_y',
       'Date run_y'],
      dtype='object')
     Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0   PZ544326.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
1   PZ544327.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
2   PZ544328.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
3   PZ544329.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
4   PZ544330.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
5   PZ544331.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
6   PZ544332.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
7   PZ544333.1        GenBank  GCA_058329715.1   SRR38788396  SAMN60347461
8   PZ544334.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
9   PZ544335.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
10  PZ544336.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
11  PZ544337.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
12  PZ544338.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
13  PZ544339.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
14  PZ544340.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
15  PZ544341.1        GenBank  GCA_058329825.1   SRR38788385  SAMN60347462
16  PZ544342.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
17  PZ544343.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
18  PZ544344.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
19  PZ544345.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
20  PZ544346.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
21  PZ544347.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
22  PZ544348.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
23  PZ544349.1        GenBank  GCA_058329855.1   SRR38788374  SAMN60347463
24  PZ544350.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
25  PZ544351.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
26  PZ544352.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
27  PZ544353.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
28  PZ544354.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
29  PZ544355.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
30  PZ544356.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
31  PZ544357.1        GenBank  GCA_058315875.1   SRR38788363  SAMN60347464
32  PZ514095.1        GenBank  GCA_058182645.1           NaN           NaN
33  PZ514096.1        GenBank  GCA_058182645.1           NaN           NaN
34  PZ514097.1        GenBank  GCA_058182645.1           NaN           NaN
35  PZ514098.1        GenBank  GCA_058182645.1           NaN           NaN
36  PZ514099.1        GenBank  GCA_058182645.1           NaN           NaN
37  PZ514100.1        GenBank  GCA_058182645.1           NaN           NaN
38  PZ514101.1        GenBank  GCA_058182645.1           NaN           NaN
39  PZ514102.1        GenBank  GCA_058182645.1           NaN           NaN
40  PQ885514.1        GenBank  GCA_046891765.1           NaN           NaN
41  PQ885515.1        GenBank  GCA_046891765.1           NaN           NaN
42  PQ885516.1        GenBank  GCA_046891765.1           NaN           NaN
43  PQ885517.1        GenBank  GCA_046891765.1           NaN           NaN
44  PQ885518.1        GenBank  GCA_046891765.1           NaN           NaN
45  PQ885519.1        GenBank  GCA_046891765.1           NaN           NaN
46  PQ885520.1        GenBank  GCA_046891765.1           NaN           NaN
47  PQ885521.1        GenBank  GCA_046891765.1           NaN           NaN
48  PQ573558.1        GenBank  GCA_046435525.1           NaN           NaN
49  PQ573559.1        GenBank  GCA_046435525.1           NaN           NaN
50  PQ573560.1        GenBank  GCA_046435525.1           NaN           NaN
51  PQ573561.1        GenBank  GCA_046435525.1           NaN           NaN
52  PQ573562.1        GenBank  GCA_046435525.1           NaN           NaN
53  PQ573563.1        GenBank  GCA_046435525.1           NaN           NaN
54  PQ573564.1        GenBank  GCA_046435525.1           NaN           NaN
55  PQ573565.1        GenBank  GCA_046435525.1           NaN           NaN

      BioProject      Organism_Name                         Species  \
0   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
1   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
2   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
4   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
5   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
6   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
7   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
8   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
9   PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
10  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
11  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
12  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
13  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
14  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
15  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
16  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
17  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
18  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
19  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
20  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
21  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
22  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
23  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
24  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
25  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
26  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
27  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
28  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
29  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
30  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
31  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
32           NaN  Influenza A virus  Alphainfluenzavirus influenzae
33           NaN  Influenza A virus  Alphainfluenzavirus influenzae
34           NaN  Influenza A virus  Alphainfluenzavirus influenzae
35           NaN  Influenza A virus  Alphainfluenzavirus influenzae
36           NaN  Influenza A virus  Alphainfluenzavirus influenzae
37           NaN  Influenza A virus  Alphainfluenzavirus influenzae
38           NaN  Influenza A virus  Alphainfluenzavirus influenzae
39           NaN  Influenza A virus  Alphainfluenzavirus influenzae
40  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
41  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
42  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
43  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
44  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
45  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
46  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
47  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
48  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
49  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
50  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
51  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
52  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
53  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
54  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae
55  PRJNA1095491  Influenza A virus  Alphainfluenzavirus influenzae

                  Genus            Family  ...         Strain_y  \
0   Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329715_1
1   Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329715_1
2   Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329715_1
3   Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329715_1
4   Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329715_1
5   Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329715_1
6   Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329715_1
7   Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329715_1
8   Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329825_1
9   Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329825_1
10  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329825_1
11  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329825_1
12  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329825_1
13  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329825_1
14  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329825_1
15  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329825_1
16  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329855_1
17  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329855_1
18  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329855_1
19  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329855_1
20  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329855_1
21  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329855_1
22  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329855_1
23  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058329855_1
24  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058315875_1
25  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058315875_1
26  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058315875_1
27  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058315875_1
28  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058315875_1
29  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058315875_1
30  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058315875_1
31  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058315875_1
32  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058182645_1
33  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058182645_1
34  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058182645_1
35  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058182645_1
36  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058182645_1
37  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058182645_1
38  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058182645_1
39  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_058182645_1
40  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_046891765_1
41  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_046891765_1

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Genotype Mismatch List_y,Genotype Average Depth of Coverage List_y,Genotype_official,Serotype,Strain_x,Date run_x,Partial_Header,Partial_Header_Merge,Strain_y,Date run_y
0,OL539626.1,GenBank,GCA_039236455.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N3,NaN,NaN,NaN,NaN,NaN,NaN
1,OL539627.1,GenBank,GCA_039236455.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N3,NaN,NaN,NaN,NaN,NaN,NaN
2,OL539628.1,GenBank,GCA_039236455.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N3,NaN,NaN,NaN,NaN,NaN,NaN
3,OL539629.1,GenBank,GCA_039236455.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N3,NaN,NaN,NaN,NaN,NaN,NaN
4,OL539630.1,GenBank,GCA_039236455.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N3,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,PQ573561.1,GenBank,GCA_046435525.1,NaN,NaN,PRJNA1095491,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"1, 17, 2, 7, 1, 0, 1, 7",Ran on FASTA - No Coverage Report,D1.1,H5N1,NaN,NaN,>GCA_046435525.1,GCA_046435525_1,GCA_046435525_1,2026-06-25_12-24-08
52,PQ573562.1,GenBank,GCA_046435525.1,NaN,NaN,PRJNA1095491,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"1, 17, 2, 7, 1, 0, 1, 7",Ran on FASTA - No Coverage Report,D1.1,H5N1,NaN,NaN,>GCA_046435525.1,GCA_046435525_1,GCA_046435525_1,2026-06-25_12-24-08
53,PQ573563.1,GenBank,GCA_046435525.1,NaN,NaN,PRJNA1095491,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"1, 17, 2, 7, 1, 0, 1, 7",Ran on FASTA - No Coverage Report,D1.1,H5N1,NaN,NaN,>GCA_046435525.1,GCA_046435525_1,GCA_046435525_1,2026-06-25_12-24-08
54,PQ573564.1,GenBank,GCA_046435525.1,NaN,NaN,PRJNA1095491,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"1, 17, 2, 7, 1, 0, 1, 7",Ran on FASTA - No Coverage Report,D1.1,H5N1,NaN,NaN,>GCA_046435525.1,GCA_046435525_1,GCA_046435525_1,2026-06-25_12-24-08
55,PQ573565.1,GenBank,GCA_046435525.1,NaN,NaN,PRJNA1095491,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"1, 17, 2, 7, 1, 0, 1, 7",Ran on FASTA - No Coverage Report,D1.1,H5N1,NaN,NaN,>GCA_046435525.1,GCA_046435525_1,GCA_046435525_1,2026-06-25_12-24-08

In [27]:
# Cut down to only columns we want
metadata_genoflu_concat = metadata_genoflu_concat[["Accession", "Assembly", "GenBank_Title", "Host", "Collection_Date", "SRA_Accession", "Isolate", "Genotype_official", "Geo_Location", "full_header", "sequence", "Serotype", "Segment", "File Name", "Partial_Header"]] #, "Strain"]]

# Get genbank strain name
metadata_genoflu_concat["genbank_name"] = metadata_genoflu_concat["GenBank_Title"].apply(lambda x: x.split("(")[1] if x == x else x)
metadata_genoflu_concat["Host"] = metadata_genoflu_concat["genbank_name"].apply(lambda x: x.split("/")[1] if x == x else x)

metadata_genoflu_concat = metadata_genoflu_concat.dropna(subset="genbank_name") # [metadata_genoflu["Genotype"]  == "B3.13"]

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\2\ipykernel_90640\4267596827.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata_genoflu_concat["genbank_name"] = metadata_genoflu_concat["GenBank_Title"].apply(lambda x: x.split("(")[1] if x == x else x)
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\2\ipykernel_90640\4267596827.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata_genoflu_concat["Host"] = metadata_genoflu_concat["genbank_name"].apply(lambda x: x.split("/")[1] if x == x else x)

In [28]:
metadata_genoflu_concat

# Make sure we only have the serotype(s) we want
for serotype in serotypes:
    metadata_genoflu = metadata_genoflu[metadata_genoflu["Serotype"] == serotype]

## Relabeling Sequences

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

In [29]:
# Re-re-name so that we don't break following code

metadata_genoflu = metadata_genoflu_concat

After running the below code, **STOP TO CHECK** if any new animals appear

In [30]:
# Animals 

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genoflu)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['hermit thrush', 'western sandpiper', 'peregrine falcon', 'pekin duck', 'cackling goose', 'cattle', 'mink', 'wild duck', 'ruddy duck', 'heron', 'skunk', 'rough-legged hawk', 'burrowing owl', 'domestic cat', 'fish crow', 'bluejay', 'crow', 'red-shouldered hawk', 'snowy egret', 'lynx', 'house mouse', 'pelican', 'common eider', 'lesser black-backed gull', 'mallard duck', 'hooded merganser', 'harbor seal', 'goat', 'northern elephant seal', 'glaucous-winged gull', 'common merganser', 'ring-billed gull', 'serval', 'bobcat', 'rock dove', 'western gull', 'blue-winged teal', 'great egret', 'dove', 'pig', 'mute swan', 'lesser snow goose', 'lion', 'common murre', 'canada goose', 'chinese goose', 'glaucous gull', 'american green-winged teal', 'common goldeneye', 'rock pigeon', 'owl', 'wood duck', 'great black-backed gull', 'fox', 'black swan', 'mottled duck', 'greater white-fronted goose', 'laughing gull', 'pigeon', 'california gull', 'chukar', 'european starling', 'sanderling', 'snowy owl', 'common loon', 'eurasian collared dove', 'great blue heron', 'bald eagle', 'northern shoveler', 'bird', 'broad-winged hawk', 'cinnamon teal', 'fisher', 'american white pelican', 'turkey vulture', 'northern pintail', 'bear', 'house sparrow', 'goose', 'dolphin', 'great horned owl', 'gull', 'guineafowl', 'finch', 'whooping crane', 'gadwell', 'sharp-shinned hawk', 'wild turkey', 'emu', 'chicken', 'common tern', 'quail', 'domestic duck', 'tiger', 'black skimmer', 'avian', 'common grackle', 'sandhill crane', 'great-horned owl', 'striped skunk', 'peacock', 'flamingo', 'herring gull', 'grackle', 'black vulture', 'green-winged teal', 'american crow', 'hooded merganser duck', 'cat', 'pintail duck', 'long-eared owl', 'blue jay', 'hawk', 'chukar partridge', 'domestic turkey', 'washington', 'wild goose', 'ermine', 'greater scaup', 'vulture', 'double-crested cormorant', 'blackbird', 'black-crowned night-heron', 'bufflehead', 'white-winged dove', 'swan', 'lesser scaup', 'alpaca', 'common rhea', 'guinea fowl', 'osprey', 'red-tailed hawk', 'red fox', 'gadwall duck', 'american widgeon', 'gadwall', 'caspian tern', 'snow goose', 'muscovy duck', 'turkey', 'american wigeon', 'virginia opossum', 'bottlenose dolphin', 'black-necked stilt', 'duck', 'white-faced ibis', 'domestic goose', 'sparrow', 'crane', 'mallard', 'sea otter', 'common raven', 'barn owl', 'falcon', 'ring-necked duck', 'american robin', 'dunlin', 'whooper swan', 'raccoon', 'northern harrier', 'teal', 'american woodcock', 'peafowl', 'bluebird', 'american black duck', 'golden eagle', 'pheasant', 'mountain lion', 'partridge', 'ring-necked pheasant']
[]
            wild_avian domestic_avian               cattle        feline  \
0     great_horned_owl       pheasant            dairy_cow           cat
1         common_raven         turkey               cattle  domestic_cat
2        cooper's_hawk        chicken  cattle milk product     feral_cat
3         coopers_hawk          goose          bovine_milk        feline
4              peafowl    guinea_fowl              bovine   domestic-cat
...                ...            ...                  ...           ...
1663               NaN            NaN                  NaN           NaN
1664               NaN            NaN                  NaN           NaN
1665               NaN            NaN                  NaN           NaN
1666               NaN            NaN                  NaN           NaN
1667               NaN            NaN                  NaN           NaN

       other_mammal               human         other      pet_food  \
0        deer mouse          washington         mixed      pet food
1       house_mouse              nevada   environment  raw pet food
2             skunk             wyoming  multispecies  raw_pet_food
3     striped_skunk          california       unknown      pet_food
4        norway rat            michigan             '           NaN
...             ...                 ...           ...           ...
1663            NaN            florence           NaN           NaN
1664            NaN                 oms           NaN           NaN
1665            NaN  castilla-la_mancha           NaN           NaN
1666            NaN          guadeloupe           NaN           NaN
1667            NaN               opole           NaN           NaN

     experimental  new
0         macaque  NaN
1           swine  NaN
2             NaN  NaN
3             NaN  NaN
4             NaN  NaN
...           ...  ...
1663          NaN  NaN
1664          NaN  NaN
1665          NaN  NaN
1666          NaN  NaN
1667          NaN  NaN

[1668 rows x 10 columns]

In [31]:
input("Check animals output. Afterwards, press ENTER to continue.")

''

In [32]:
# Re-label sequences with no assigned genotype as "Unassigned"

metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype_official"].apply(lambda x: "Not" if "Not assigned" in str(x) else x) # Unassigned segments are labeled "Unassigned"
metadata_genoflu["Genotype"] = metadata_genoflu["Genotype_official"] # Rename column again to not break old code

In [33]:
metadata_genoflu

,Accession,Assembly,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype_official,Geo_Location,full_header,sequence,Serotype,Segment,File Name,Partial_Header,genbank_name,Genotype
0,OL539626.1,GCA_039236455.1,Influenza A virus (A/mallard/New York/AH017938...,mallard,2021-09-03,NaN,AH0179389,Not,"USA: Steuben County, New York",>OL539626.1 |Influenza A virus (A/mallard/New ...,ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...,H5N3,1,NaN,NaN,A/mallard/New York/AH0179389/2021,Not
1,OL539627.1,GCA_039236455.1,Influenza A virus (A/mallard/New York/AH017938...,mallard,2021-09-03,NaN,AH0179389,Not,"USA: Steuben County, New York",>OL539627.1 |Influenza A virus (A/mallard/New ...,ATGGATGTCAATCCGACTTTACTCTTCTTGAAAGTTCCAGCGCAAA...,H5N3,2,NaN,NaN,A/mallard/New York/AH0179389/2021,Not
2,OL539628.1,GCA_039236455.1,Influenza A virus (A/mallard/New York/AH017938...,mallard,2021-09-03,NaN,AH0179389,Not,"USA: Steuben County, New York",>OL539628.1 |Influenza A virus (A/mallard/New ...,ATGGAAGATTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...,H5N3,3,NaN,NaN,A/mallard/New York/AH0179389/2021,Not
3,OL539629.1,GCA_039236455.1,Influenza A virus (A/mallard/New York/AH017938...,mallard,2021-09-03,NaN,AH0179389,Not,"USA: Steuben County, New York",>OL539629.1 |Influenza A virus (A/mallard/New ...,ATGGAAAGAATAGTGATTGCCCTCGCAATAATCAGCATTGTCAAAG...,H5N3,4,NaN,NaN,A/mallard/New York/AH0179389/2021,Not
4,OL539630.1,GCA_039236455.1,Influenza A virus (A/mallard/New York/AH017938...,mallard,2021-09-03,NaN,AH0179389,Not,"USA: Steuben County, New York",>OL539630.1 |Influenza A virus (A/mallard/New ...,ATGGCGTCTCAAGGCACCAAACGATCTTATGAACAAATGGAAACTG...,H5N3,5,NaN,NaN,A/mallard/New York/AH0179389/2021,Not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,PQ573561.1,GCA_046435525.1,Influenza A virus (A/Washington/240/2024(H5N1)...,Washington,2024-10-18,NaN,A/Washington/240/2024,D1.1,USA: Washington,>PQ573561.1 |Influenza A virus (A/Washington/2...,TCAAATATATTCAATATGGAGAGAATAAAAGAACTGAGAGATCTAA...,H5N1,1,NaN,>GCA_046435525.1,A/Washington/240/2024,D1.1
52,PQ573562.1,GCA_046435525.1,Influenza A virus (A/Washington/240/2024(H5N1)...,Washington,2024-10-18,NaN,A/Washington/240/2024,D1.1,USA: Washington,>PQ573562.1 |Influenza A virus (A/Washington/2...,GGTTCACTCTGTCAAAATGGAAAACATAGTACTTCTTCTTGCAATA...,H5N1,4,NaN,>GCA_046435525.1,A/Washington/240/2024,D1.1
53,PQ573563.1,GCA_046435525.1,Influenza A virus (A/Washington/240/2024(H5N1)...,Washington,2024-10-18,NaN,A/Washington/240/2024,D1.1,USA: Washington,>PQ573563.1 |Influenza A virus (A/Washington/2...,AGTTCAAAATGAATCCAAATCAAAAGATAATAACTATCGGGTCAAT...,H5N1,6,NaN,>GCA_046435525.1,A/Washington/240/2024,D1.1
54,PQ573564.1,GCA_046435525.1,Influenza A virus (A/Washington/240/2024(H5N1)...,Washington,2024-10-18,NaN,A/Washington/240/2024,D1.1,USA: Washington,>PQ573564.1 |Influenza A virus (A/Washington/2...,GTAGATAATCACTCACTGAGTGACATCCACATCATGGCGTCTCAAG...,H5N1,5,NaN,>GCA_046435525.1,A/Washington/240/2024,D1.1
55,PQ573565.1,GCA_046435525.1,Influenza A virus (A/Washington/240/2024(H5N1)...,Washington,2024-10-18,NaN,A/Washington/240/2024,D1.1,USA: Washington,>PQ573565.1 |Influenza A virus (A/Washington/2...,GTGACAAAAACATAATGGATTCCAACACTGTGTCAAGCTTTCAGGT...,H5N1,8,NaN,>GCA_046435525.1,A/Washington/240/2024,D1.1

In [115]:
def geo_location_normalize(geolocation: str) -> str:

    geolocation = geolocation.replace(":", ",") # We will need to split on commas later; e.g. USA: MD -> USA, MD

    country = geolocation.split(",")[0] # Get the first part of the geolocation, aka the country 

    state = geolocation.split(",")[-1] # Get the last part of the geolocation, aka the state

    state = state.strip().replace(" ", "_") # Remove leading and trailing whitespace, make sure that all internal spaces are underscored instead

    country = country.strip().replace(" ", "_") # Remove leading and trailing whitespace, make sure that all internal spaces are underscored instead

    country_state = country + "-" + state # Log needed

    return country_state 

# Format: USA-[state abbreviation], e.g. USA-MD
def geo_location_get(metadata: pd.DataFrame, state_ref_file: str = "states_ref.csv") -> pd.DataFrame:

    state_ref = pd.read_csv(state_ref_file)

    # Normalize the locations

    # metadata["name_state_genbank"] = metadata["genbank_name"].apply(lambda x: x.split("/")[2] if x == x else x)

    metadata["Geo_Location_Normalized"] = metadata["Geo_Location"].apply(geo_location_normalize)

    metadata["Geo_Location_Country"] = metadata["Geo_Location_Normalized"].apply(lambda x: x.split("-")[0])

    # Get country
    metadata["Geo_Location_Country"] = metadata["Geo_Location_Country"].apply(lambda x: state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Country'].iloc[0]
                                                                              if len(state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Country']) > 0
                                                                              else state_ref.loc[state_ref["State"].str.contains(x), 'Country'].iloc[0]
                                                                              if len(state_ref.loc[state_ref["State"].str.contains(x), 'Country']) > 0
                                                                              else x)

    # Get state
    metadata["Geo_Location_State_med"] = metadata["Geo_Location_Normalized"].apply(lambda x: x.split("-")[-1])

      
    metadata["Geo_Location_State_USA"] = metadata["Geo_Location_State_med"].apply(lambda x: 
    # # If "x" is the abbreviated state (e.g. "MD")
    state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Abbreviation'].iloc[0]
    if len(state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Abbreviation']) > 0 and len(x) > 0
    # # If "x" is the state name (e.g. "Maryland")
    else state_ref.loc[state_ref["State"].str.contains(x), 'Abbreviation'].iloc[0]
    if len(state_ref.loc[state_ref["State"].str.contains(x), 'Abbreviation']) > 0 and len(x) > 0
    # # If "x" has neither the state abbreviation nor the full state name
    else x)
    

    metadata["Geo_Location_New"] = metadata["Geo_Location_Country"] + "-" + metadata["Geo_Location_State"] 

    # If USA-, delete -
    metadata["Geo_Location_New"] = metadata["Geo_Location_New"].apply(lambda x: x.split("-")[0] 
    if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] 
    else x)

    return metadata

def geo_location_strain_name(metadata, state_ref_file):
    # If there is no state in the metadata, try the strain name
    state_ref = pd.read_csv(state_ref_file)

    metadata["strain_name_state_nonhuman"] = metadata["genbank_name"].apply(lambda x: x.split("/")[2])

    metadata["strain_name_state_human"] = metadata["genbank_name"].apply(lambda x: x.split("/")[1])

    # If nonhuman, do strain name [2]
    metadata["Geo_Location_State_Strain_Name"] = np.where((metadata["Geo_Location_State_USA"] == "USA") & (metadata["Host_Type"] != "human"), metadata["strain_name_state_nonhuman"], metadata["Geo_Location_State_USA"])

    # If human, do strain name [1]
    metadata["Geo_Location_State_Strain_Name"] = np.where((metadata["Geo_Location_State_USA"] == "USA") & (metadata["Host_Type"] == "human"), metadata["strain_name_state_human"], metadata["Geo_Location_State_USA"])

    metadata["Geo_Location_State_Strain_Name"] = metadata["Geo_Location_State_Strain_Name"].apply(geo_location_normalize)

    metadata["Geo_Location_State_Strain_Name_State"] = metadata["Geo_Location_State_Strain_Name"].apply(lambda x: x.split("-")[-1])
    
    metadata["Geo_Location_State_Strain_Name"] = metadata["Geo_Location_State_Strain_Name_State"].apply(lambda x: 
    # # If "x" is the abbreviated state (e.g. "MD")
    state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Abbreviation'].iloc[0]
    if len(state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Abbreviation']) > 0 and len(x) > 0
    # # If "x" is the state name (e.g. "Maryland")
    else state_ref.loc[state_ref["State"].str.contains(x), 'Abbreviation'].iloc[0]
    if len(state_ref.loc[state_ref["State"].str.contains(x), 'Abbreviation']) > 0 and len(x) > 0
    # # If "x" has neither the state abbreviation nor the full state name, and is just USA
    else ""
    if x == "USA" or x == "United_States"
    
    else x)

    metadata["Geo_Location_New"] = metadata["Geo_Location_Country"] + "-" + metadata["Geo_Location_State_Strain_Name"] 

    # If USA-, delete -
    metadata["Geo_Location_New"] = metadata["Geo_Location_New"].apply(lambda x: x.split("-")[0] 
    if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] 
    else x)

    # Log metadata

    
    return metadata

# # Format: USA-[state abbreviation], e.g. USA-MD
# def geo_location_get(metadata: pd.DataFrame, state_ref_file: str = "states_ref.csv") -> pd.DataFrame:

#     state_ref = pd.read_csv(state_ref_file)

#     # Normalize the locations

#     # metadata["name_state_genbank"] = metadata["genbank_name"].apply(lambda x: x.split("/")[2] if x == x else x)

#     metadata["Geo_Location_Normalized"] = metadata["Geo_Location"].apply(geo_location_normalize)

#     metadata["Geo_Location_Country"] = metadata["Geo_Location_Normalized"].apply(lambda x: x.split("-")[0])

#     # Get country
#     metadata["Geo_Location_Country"] = metadata["Geo_Location_Country"].apply(lambda x: state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Country'].iloc[0]
#                                                                               if len(state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Country']) > 0
#                                                                               else state_ref.loc[state_ref["State"].str.contains(x), 'Country'].iloc[0]
#                                                                               if len(state_ref.loc[state_ref["State"].str.contains(x), 'Country']) > 0
#                                                                               else x)

#     # Get state
#     metadata["Geo_Location_State_med"] = metadata["Geo_Location_Normalized"].apply(lambda x: x.split("-")[-1])

#     try:    
#         metadata["Geo_Location_State"] = metadata["Geo_Location_State_med"].apply(lambda x: 
#         # # If "x" is the abbreviated state (e.g. "MD")
#         state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Abbreviation'].iloc[0]
#         if len(state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Abbreviation']) > 0 and len(x) > 0
#         # # If "x" is the state name (e.g. "Maryland")
#         else state_ref.loc[state_ref["State"].str.contains(x), 'Abbreviation'].iloc[0]
#         if len(state_ref.loc[state_ref["State"].str.contains(x), 'Abbreviation']) > 0 and len(x) > 0
#         # # If "x" has neither the state abbreviation nor the full state name
#         else x)
#     except:
#         print("Could not find states in reference.")

#     # If there is no state in the metadata, try the strain name



#     metadata["Geo_Location_New"] = metadata["Geo_Location_Country"] + "-" + metadata["Geo_Location_State"] 

#     # If USA-, delete -
#     metadata["Geo_Location_New"] = metadata["Geo_Location_New"].apply(lambda x: x.split("-")[0] 
#     if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] 
#     else x)

#     # Log metadata
#     return metadata

# # Format: USA-[state abbreviation], e.g. USA-MD
# def geo_location_get(metadata: pd.DataFrame, state_ref_file: str = "states_ref.csv") -> pd.DataFrame:

#     state_ref = pd.read_csv(state_ref_file)

#     # Normalize the locations

#     # metadata["name_state_genbank"] = metadata["genbank_name"].apply(lambda x: x.split("/")[2] if x == x else x)

#     metadata["Geo_Location_Normalized"] = metadata["Geo_Location"].apply(geo_location_normalize)

#     metadata["Geo_Location_Country"] = metadata["Geo_Location_Normalized"].apply(lambda x: x.split("-")[0])

#     # Get country
#     # metadata["Geo_Location_Country"] = metadata["Geo_Location_Country"].apply(lambda x: state_ref.loc[state_ref["Abbreviation"].str.contains(x, regex=True), 'Country'].iloc[0])

#     # Get state
#     metadata["Geo_Location_State"] = metadata["Geo_Location_Normalized"].apply(lambda x: x.split("-")[-1])

#     try:    
#         metadata["Geo_Location_State"] = metadata["Geo_Location_State"].apply(lambda x: 
#         # If "x" is the abbreviated state (e.g. "MD")
#         state_ref[state_ref['Abbreviation'].str.contains(x)]['Abbreviation'].values[0] # .iloc[0]
#         if state_ref["Abbreviation"].str.contains(x).any()
#         # If "x" is the state name (e.g. "Maryland")
#         else state_ref[state_ref['State'].str.contains(x)]['Abbreviation'].values[0] # .iloc[0] 
#         if state_ref["State"].str.contains(x).any() 
#         # If "x" has neither the state abbreviation nor the full state name
#         else x)
#     except:
#         print("Could not find states in reference.")

#     metadata["Geo_Location_New"] = metadata["Geo_Location_Country"] + "-" + metadata["Geo_Location_State"] 

#     # If USA-, delete -
#     metadata["Geo_Location_New"] = metadata["Geo_Location_New"].apply(lambda x: x.split("-")[0] 
#     if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] 
#     else x)

#     # Log metadata
#     return metadata

In [116]:
print(states_ref[states_ref['State'].str.contains("New_York")]["Abbreviation"].values[0])

NY

In [117]:
# Re-Labeling

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

# Fix animals
fix_animals_andersen(metadata_genoflu, animals_ref)

# Get the years
metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

# # Get geographic locations
# metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location"].apply(lambda x: 
#                                                                         # If "x" has the state abbreviation (e.g. "MD")
#                                                                         states_ref.loc[states_ref["Abbreviation"].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0] 
#                                                                         + "-" + 
#                                                                         x.split(" ")[-1]
#                                                                         if states_ref["Abbreviation"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
#                                                                         # If "x" has the full state name (e.g. "Maryland")
#                                                                         else states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0]
#                                                                         + "-" + 
#                                                                         states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Abbreviation'].iloc[0] 
#                                                                         if states_ref["State"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
#                                                                         # If "x" has neither the state abbreviation nor the full state name nor is "USA"
#                                                                         else 
#                                                                         x
#                                                                         )

# metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location_Abrv"].apply(lambda x: x.split("-")[0] if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] else x)


# print(metadata_genoflu["Geo_Location_Abrv"])

In [ ]:
os.chdir(references)
metadata_genoflu = geo_location_get(metadata_genoflu, "states_ref.csv")

In [118]:
metadata_genoflu = geo_location_strain_name(metadata_genoflu, "states_ref.csv")

In [119]:
os.chdir(downloads_saved)
metadata_genoflu.to_csv("metadata_checkpoint.csv")

In [58]:
# If there is no SRA Accession, replace identifier with Assembly -- this part might be duplicating accessions :(
metadata_genoflu["Identifier"] = metadata_genoflu["Assembly"].apply(lambda x: x if metadata_genoflu[metadata_genoflu["Assembly"] == x]["SRA_Accession"].values[0] == "" else metadata_genoflu[metadata_genoflu["Assembly"] == x]["SRA_Accession"].values[0]) # np.where(metadata_genoflu['SRA_Accession'] != "", metadata_genoflu['SRA_Accession'], metadata_genoflu['Assembly'].apply(lambda x: x.split(".")[0]))
# # If there is no Assembly, replace identifier with Accession -- only for PB2
# metadata_genoflu["Identifier"] = np.where(metadata_genoflu["SRA_Accession_intermediate"] == "", metadata_genoflu["Accession"].apply(lambda x: metadata_genoflu[metadata_genoflu["Accession"] == x]["Accession"].values[0] if metadata_genoflu[metadata_genoflu["Accession"] == x].loc[:, "Segment"].values[0] == 1 else np.nan), metadata_genoflu["SRA_Accession_intermediate"])
# # Fill in other nans with PB2 Accession (interpolate, maximum of 7 other sequences)
# metadata_genoflu.loc[:,"Identifier"] = metadata_genoflu.loc[:, "Identifier"].ffill(limit=7, limit_area="inside")

print((metadata_genoflu[metadata_genoflu["Identifier"].str.contains("SRR")])) # metadata_genoflu[(metadata_genoflu["Identifier"].str.contains("GCA")) |

      Accession         Assembly  \
128  PZ544326.1  GCA_058329715.1
129  PZ544327.1  GCA_058329715.1
130  PZ544328.1  GCA_058329715.1
131  PZ544329.1  GCA_058329715.1
132  PZ544330.1  GCA_058329715.1
..          ...              ...
27   PZ544353.1  GCA_058315875.1
28   PZ544354.1  GCA_058315875.1
29   PZ544355.1  GCA_058315875.1
30   PZ544356.1  GCA_058315875.1
31   PZ544357.1  GCA_058315875.1

                                         GenBank_Title    Host  \
128  Influenza A virus (A/cattle/ID/26G07177-001-or...  cattle
129  Influenza A virus (A/cattle/ID/26G07177-001-or...  cattle
130  Influenza A virus (A/cattle/ID/26G07177-001-or...  cattle
131  Influenza A virus (A/cattle/ID/26G07177-001-or...  cattle
132  Influenza A virus (A/cattle/ID/26G07177-001-or...  cattle
..                                                 ...     ...
27   Influenza A virus (A/cattle/ID/26G07177-004-or...  cattle
28   Influenza A virus (A/cattle/ID/26G07177-004-or...  cattle
29   Influenza A virus (A/cattle/ID/26G07177-004-or...  cattle
30   Influenza A virus (A/cattle/ID/26G07177-004-or...  cattle
31   Influenza A virus (A/cattle/ID/26G07177-004-or...  cattle

    Collection_Date SRA_Accession                                 Isolate  \
128      2026-05-04   SRR38788396  A/cattle/ID/26G07177-001-original/2026
129      2026-05-04   SRR38788396  A/cattle/ID/26G07177-001-original/2026
130      2026-05-04   SRR38788396  A/cattle/ID/26G07177-001-original/2026
131      2026-05-04   SRR38788396  A/cattle/ID/26G07177-001-original/2026
132      2026-05-04   SRR38788396  A/cattle/ID/26G07177-001-original/2026
..              ...           ...                                     ...
27       2026-05-04   SRR38788363  A/cattle/ID/26G07177-004-original/2026
28       2026-05-04   SRR38788363  A/cattle/ID/26G07177-004-original/2026
29       2026-05-04   SRR38788363  A/cattle/ID/26G07177-004-original/2026
30       2026-05-04   SRR38788363  A/cattle/ID/26G07177-004-original/2026
31       2026-05-04   SRR38788363  A/cattle/ID/26G07177-004-original/2026

    Genotype_official Geo_Location  \
128             B3.13      USA: ID
129             B3.13      USA: ID
130             B3.13      USA: ID
131             B3.13      USA: ID
132             B3.13      USA: ID
..                ...          ...
27                Not      USA: ID
28                Not      USA: ID
29                Not      USA: ID
30                Not      USA: ID
31                Not      USA: ID

                                           full_header  ...    Partial_Header  \
128  >PZ544326.1 |Influenza A virus (A/cattle/ID/26...  ...
129  >PZ544327.1 |Influenza A virus (A/cattle/ID/26...  ...
130  >PZ544328.1 |Influenza A virus (A/cattle/ID/26...  ...
131  >PZ544329.1 |Influenza A virus (A/cattle/ID/26...  ...
132  >PZ544330.1 |Influenza A virus (A/cattle/ID/26...  ...
..                                                 ...  ...               ...
27   >PZ544353.1 |Influenza A virus (A/cattle/ID/26...  ...  >GCA_058315875.1
28   >PZ544354.1 |Influenza A virus (A/cattle/ID/26...  ...  >GCA_058315875.1
29   >PZ544355.1 |Influenza A virus (A/cattle/ID/26...  ...  >GCA_058315875.1
30   >PZ544356.1 |Influenza A virus (A/cattle/ID/26...  ...  >GCA_058315875.1
31   >PZ544357.1 |Influenza A virus (A/cattle/ID/26...  ...  >GCA_058315875.1

                               genbank_name  Genotype Host_Type Years  \
128  A/cattle/ID/26G07177-001-original/2026     B3.13    cattle  2026
129  A/cattle/ID/26G07177-001-original/2026     B3.13    cattle  2026
130  A/cattle/ID/26G07177-001-original/2026     B3.13    cattle  2026
131  A/cattle/ID/26G07177-001-original/2026     B3.13    cattle  2026
132  A/cattle/ID/26G07177-001-original/2026     B3.13    cattle  2026
..                                      ...       ...       ...   ...
27   A/cattle/ID/26G07177-004-original/2026       Not    cattle  2026
28   A/cattle/ID/26G07177-004-original/2026       Not    cattle  2026
29   A/cattle/ID/26G07177-004-original/2026       Not    cattle  2026
30   A/cattle/ID/26G07177-004-original/2026       Not    cattle  2026
31   A/cattle/ID/26G07177-004-original/2026       Not    cattle  2026

    Geo_Location_Normalized Geo_Location_Country Geo_Location_State  \
128                  USA-ID                  USA                 ID
129                  USA-ID                  USA                 ID
130                  USA-ID                  USA                 ID
131                  USA-ID                  USA                 ID
132                  USA-ID                  USA                 ID
..                      ...                  ...                ...
27                   USA-ID                  USA                 ID
28                   USA-ID                  USA                 ID
29                   USA-ID                  USA                 ID
30                   USA-ID                  USA                 ID
31                   USA-ID                  USA                 ID

    Geo_Location_New   Identifier
128           USA-ID  SRR38788396
129           USA-ID  SRR38788396
130           USA-ID  SRR38788396
131           USA-ID  SRR38788396
132           USA-ID  SRR38788396
..               ...          ...
27            USA-ID  SRR38788363
28            USA-ID  SRR38788363
29            USA-ID  SRR38788363
30            USA-ID  SRR38788363
31            USA-ID  SRR38788363

[81352 rows x 24 columns]

In [59]:

# Make new labels
names = ">" + metadata_genoflu["Identifier"].astype(str) + "|" + metadata_genoflu["genbank_name"] + "|" + metadata_genoflu["Serotype"] + "|" + metadata_genoflu["Geo_Location_New"] + "|" + metadata_genoflu["Collection_Date"].astype(str) + "|" + metadata_genoflu["Host_Type"] + "|" + metadata_genoflu["Genotype"]

metadata_genoflu["Name"] = names

In [60]:
os.chdir(complete_files)

# De-duplicate

print(len(metadata_genoflu))
metadata_genoflu = metadata_genoflu.drop_duplicates(subset=["Isolate", "genbank_name", "Segment"], keep="last")
print(len(metadata_genoflu))

# Save metadata
metadata_genoflu.to_csv("NCBI_Virus_" + date_range + "_metadata.csv") # Make file for metadata

81504
81472

## Rename segments and make complete FASTA files

In [61]:
# Set up segments

# if len(genotypes) > 3: # If we're not doing maintenance only
#     genotypes.append("Not assigned") # Make sure unassigned genotypes are included
segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"} # Name segments 
metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].apply(lambda x: int(x)).map(segments)

# Separate into several dataframes based on genotype + segment
segment_genotype_dfs = []
for segment in segments.values():
    m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
    for genotype in list(set(m_g["Genotype"].values)):
        if genotype in genotypes:
            df = m_g[(m_g["Genotype"] == genotype)] 
            # df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
            segment_genotype_dfs.append(df)
            pair = genotype + "_" + segment
            print(pair)

B3.13_PB2
B3.13_PB1
B3.13_PA
B3.13_HA
B3.13_NP
B3.13_NA
B3.13_MP
B3.13_NS

In [62]:
# Create FASTA files

os.chdir(complete_files)

for df in segment_genotype_dfs:
    print(df)
    
    df = df.reset_index()
    if len(df["Genotype"].values[0]) > 0: # If we have assigned genotypes, including "Unassigned"
        file_name = df["Genotype"].values[0] + "_" + df["Segment_Name"].values[0] + "_" + date_range + ".fasta"
        output_file = open(complete_files + file_name, "w")

        for index, row in df.iterrows():
            name = df.loc[index, "Name"]
            name = name.replace(" ", "_")
            # names.append(name)
            sequence = df.loc[index, "sequence"]
            # First is header, second is sequence
            output_file.write(name + "\n")
            output_file.write(sequence + "\n")
        
    output_file.close()

        Accession         Assembly  \
1104   PZ479596.1  GCA_058019015.1
1112   PZ479604.1  GCA_058019025.1
1120   PZ479612.1  GCA_058019055.1
1128   PZ479620.1  GCA_058019105.1
1136   PZ479628.1  GCA_058019115.1
...           ...              ...
81415  PP756076.1  GCA_039465795.1
81423  PP756084.1  GCA_039464765.1
81431  PP756092.1  GCA_039465935.1
81439  PP756100.1  GCA_039466035.1
81447  PP740729.1  GCA_039251605.1

                                           GenBank_Title       Host  \
1104   Influenza A virus (A/cattle/ID/26G07162-001-or...     cattle
1112   Influenza A virus (A/cattle/ID/26G07162-002-or...     cattle
1120   Influenza A virus (A/cattle/ID/26G07162-003-or...     cattle
1128   Influenza A virus (A/cattle/ID/26G07162-004-or...     cattle
1136   Influenza A virus (A/cattle/ID/26G07162-005-or...     cattle
...                                                  ...        ...
81415  Influenza A virus (A/cattle/New Mexico/24-0103...     cattle
81423  Influenza A virus (A/cattle/New Mexico/24-0103...     cattle
81431  Influenza A virus (A/cattle/North Carolina/24-...     cattle
81439  Influenza A virus (A/chicken/Michigan/24-01030...    chicken
81447  Influenza A virus (A/blackbird/Texas/24-008354...  blackbird

      Collection_Date SRA_Accession  \
1104       2026-05-04   SRR38788432
1112       2026-05-04   SRR38788431
1120       2026-05-04   SRR38788430
1128       2026-05-04   SRR38788428
1136       2026-05-04   SRR38788427
...               ...           ...
81415      2024-04-01   SRR28752633
81423      2024-04-01   SRR28752631
81431      2024-04-04   SRR28752637
81439      2024-04-06   SRR28752638
81447      2024-03-16   SRR28752446

                                          Isolate Genotype_official  \
1104       A/cattle/ID/26G07162-001-original/2026             B3.13
1112       A/cattle/ID/26G07162-002-original/2026             B3.13
1120       A/cattle/ID/26G07162-003-original/2026             B3.13
1128       A/cattle/ID/26G07162-004-original/2026             B3.13
1136       A/cattle/ID/26G07162-005-original/2026             B3.13
...                                           ...               ...
81415      A/cattle/New Mexico/24-010330-003/2024             B3.13
81423      A/cattle/New Mexico/24-010330-005/2024             B3.13
81431  A/cattle/North Carolina/24-010327-003/2024             B3.13
81439       A/chicken/Michigan/24-010308-012/2024             B3.13
81447        A/blackbird/Texas/24-008354-001/2024             B3.13

      Geo_Location                                        full_header  ...  \
1104       USA: ID  >PZ479596.1 |Influenza A virus (A/cattle/ID/26...  ...
1112       USA: ID  >PZ479604.1 |Influenza A virus (A/cattle/ID/26...  ...
1120       USA: ID  >PZ479612.1 |Influenza A virus (A/cattle/ID/26...  ...
1128       USA: ID  >PZ479620.1 |Influenza A virus (A/cattle/ID/26...  ...
1136       USA: ID  >PZ479628.1 |Influenza A virus (A/cattle/ID/26...  ...
...            ...                                                ...  ...
81415          USA  >PP756076.1 |Influenza A virus (A/cattle/New M...  ...
81423          USA  >PP756084.1 |Influenza A virus (A/cattle/New M...  ...
81431          USA  >PP756092.1 |Influenza A virus (A/cattle/North...  ...
81439          USA  >PP756100.1 |Influenza A virus (A/chicken/Mich...  ...
81447          USA  >PP740729.1 |Influenza A virus (A/blackbird/Te...  ...

      Genotype       Host_Type  Years Geo_Location_Normalized  \
1104     B3.13          cattle   2026                  USA-ID
1112     B3.13          cattle   2026                  USA-ID
1120     B3.13          cattle   2026                  USA-ID
1128     B3.13          cattle   2026                  USA-ID
1136     B3.13          cattle   2026                  USA-ID
...        ...             ...    ...                     ...
81415    B3.13          cattle   2024                 USA-USA
81423    B3.13          cattle   2024                 USA-USA
81431    B3.13          cattle   2024                 USA-USA
81439    B3.13  domestic_avian   2024                 USA-USA
81447    B3.13      wild_avian   2024                 USA-USA

      Geo_Location_Country Geo_Location_State Geo_Location_New   Identifier  \
1104                   USA                 ID           USA-ID  SRR38788432
1112                   USA                 ID           USA-ID  SRR38788431
1120                   USA                 ID           USA-ID  SRR38788430
1128                   USA                 ID           USA-ID  SRR38788428
1136                   USA                 ID           USA-ID  SRR38788427
...                    ...                ...              ...          ...
81415                  USA                USA              USA  SRR28752633
81423                  USA                USA              USA  SRR28752631
81431                  USA                USA              USA  SRR28752637
81439                  USA                USA              USA  SRR28752638
81447                  USA                USA              USA  SRR28752446

                                                    Name Segment_Name
1104   >SRR38788432|A/cattle/ID/26G07162-001-original...          PB2
1112   >SRR38788431|A/cattle/ID/26G07162-002-original...          PB2
1120   >SRR38788430|A/cattle/ID/26G07162-003-original...          PB2
1128   >SRR38788428|A/cattle/ID/26G07162-004-original...          PB2
1136   >SRR38788427|A/cattle/ID/26G07162-005-original...          PB2
...                                                  ...          ...
81415  >SRR28752633|A/cattle/New Mexico/24-010330-003...          PB2
81423  >SRR28752631|A/cattle/New Mexico/24-010330-005...          PB2
81431  >SRR28752637|A/cattle/North Carolina/24-010327...          PB2
81439  >SRR28752638|A/chicken/Michigan/24-010308-012/...          PB2
81447  >SRR28752446|A/blackbird/Texas/24-008354-001/2...          PB2

[4298 rows x 26 columns]
        Accession         Assembly  \
1105   PZ479597.1  GCA_058019015.1
1113   PZ479605.1  GCA_058019025.1
1121   PZ479613.1  GCA_058019055.1
1129   PZ479621.1  GCA_058019105.1
1137   PZ479629.1  GCA_058019115.1
...           ...              ...
81414  PP756075.1  GCA_039465795.1
81422  PP756083.1  GCA_039464765.1
81430  PP756091.1  GCA_039465935.1
81438  PP756099.1  GCA_039466035.1
81446  PP740728.1  GCA_039251605.1

                                           GenBank_Title       Host  \
1105   Influenza A virus (A/cattle/ID/26G07162-001-or...     cattle
1113   Influenza A virus (A/cattle/ID/26G07162-002-or...     cattle
1121   Influenza A virus (A/cattle/ID/26G07162-003-or...     cattle
1129   Influenza A virus (A/cattle/ID/26G07162-004-or...     cattle
1137   Influenza A virus (A/cattle/ID/26G07162-005-or...     cattle
...                                                  ...        ...
81414  Influenza A virus (A/cattle/New Mexico/24-0103...     cattle
81422  Influenza A virus (A/cattle/New Mexico/24-0103...     cattle
81430  Influenza A virus (A/cattle/North Carolina/24-...     cattle
81438  Influenza A virus (A/chicken/Michigan/24-01030...    chicken
81446  Influenza A virus (A/blackbird/Texas/24-008354...  blackbird

      Collection_Date SRA_Accession  \
1105       2026-05-04   SRR38788432
1113       2026-05-04   SRR38788431
1121       2026-05-04   SRR38788430
1129       2026-05-04   SRR38788428
1137       2026-05-04   SRR38788427
...               ...           ...
81414      2024-04-01   SRR28752633
81422      2024-04-01   SRR28752631
81430      2024-04-04   SRR28752637
81438      2024-04-06   SRR28752638
81446      2024-03-16   SRR28752446

                                          Isolate Genotype_official  \
1105       A/cattle/ID/26G07162-001-original/2026             B3.13
1113       A/cattle/ID/26G07162-002-original/2026             B3.13
1121       A/cattle/ID/26G07162-003-original/2026             B3.13
1129       A/cattle/ID/26G07162-004-original/2026             B3.13
1137       A/cattle/ID/26G07162-005-original/2026             B3.13
...                                           ...               ...
81414      A/cattle/New Mexico/24-010330-003/2024             B3.13
81422      A/cattle/New Mexico/24-010330-005/2024             B3.13
81430  A/cattle/North Carolina/24-010327-003/2024             B3.13
81438       A/chicken/Michigan/24-010308-012/2024             B3.13
81446        A/blackbird/Texas/24-008354-001/2024             B3.13

      Geo_Location                                        full_header  ...  \
1105       USA: ID  >PZ479597.1 |Influenza A virus (A/cattle/ID/26...  ...
1113       USA: ID  >PZ479605.1 |Influenza A virus (A/cattle/ID/26...  ...
1121       USA: ID  >PZ479613.1 |Influenza A virus (A/cattle/ID/26...  ...
1129       USA: ID  >PZ479621.1 |Influenza A virus (A/cattle/ID/26...  ...
1137       USA: ID  >PZ479629.1 |Influenza A virus (A/cattle/ID/26...  ...
...            ...                                                ...  ...
81414          USA  >PP756075.1 |Influenza A virus (A/cattle/New M...  ...
81422          USA  >PP756083.1 |Influenza A virus (A/cattle/New M...  ...
81430          USA  >PP756091.1 |Influenza A virus (A/cattle/North...  ...
81438          USA  >PP756099.1 |Influenza A virus (A/chicken/Mich...  ...
81446          USA  >PP740728.1 |Influenza A virus (A/blackbird/Te...  ...

      Genotype       Host_Type  Years Geo_Location_Normalized  \
1105     B3.13          cattle   2026                  USA-ID
1113     B3.13          cattle   2026                  USA-ID
1121     B3.13          cattle   2026                  USA-ID
1129     B3.13          cattle   2026                  USA-ID
1137     B3.13          cattle   2026                  USA-ID
...        ...             ...    ...                     ...
81414    B3.13          cattle   2024                 USA-USA
81422    B3.13          cattle   2024                 USA-USA
81430    B3.13          cattle   2024                 USA-USA
81438    B3.13  domestic_avian   2024                 USA-USA
81446    B3.13      wild_avian   2024                 USA-USA

      Geo_Location_Country Geo_Location_State Geo_Location_New   Identifier  \
1105                   USA                 ID           USA-ID  SRR38788432
1113                   USA                 ID           USA-ID  SRR38788431
1121                   USA                 ID           USA-ID  SRR38788430
1129                   USA                 ID           USA-ID  SRR38788428
1137                   USA                 ID           USA-ID  SRR38788427
...                    ...                ...              ...          ...
81414                  USA                USA              USA  SRR28752633
81422                  USA                USA              USA  SRR28752631
81430                  USA                USA              USA  SRR28752637
81438                  USA                USA              USA  SRR28752638
81446                  USA                USA              USA  SRR28752446

                                                    Name Segment_Name
1105   >SRR38788432|A/cattle/ID/26G07162-001-original...          PB1
1113   >SRR38788431|A/cattle/ID/26G07162-002-original...          PB1
1121   >SRR38788430|A/cattle/ID/26G07162-003-original...          PB1
1129   >SRR38788428|A/cattle/ID/26G07162-004-original...          PB1
1137   >SRR38788427|A/cattle/ID/26G07162-005-original...          PB1
...                                                  ...          ...
81414  >SRR28752633|A/cattle/New Mexico/24-010330-003...          PB1
81422  >SRR28752631|A/cattle/New Mexico/24-010330-005...          PB1
81430  >SRR28752637|A/cattle/North Carolina/24-010327...          PB1
81438  >SRR28752638|A/chicken/Michigan/24-010308-012/...          PB1
81446  >SRR28752446|A/blackbird/Texas/24-008354-001/2...          PB1

[4298 rows x 26 columns]
        Accession         Assembly  \
1106   PZ479598.1  GCA_058019015.1
1114   PZ479606.1  GCA_058019025.1
1122   PZ479614.1  GCA_058019055.1
1130   PZ479622.1  GCA_058019105.1
1138   PZ479630.1  GCA_058019115.1
...           ...              ...
81413  PP756074.1  GCA_039465795.1
81421  PP756082.1  GCA_039464765.1
81429  PP756090.1  GCA_039465935.1
81437  PP756098.1  GCA_039466035.1
81445  PP740727.1  GCA_039251605.1

                                           GenBank_Title       Host  \
1106   Influenza A virus (A/cattle/ID/26G07162-001-or...     cattle
1114   Influenza A virus (A/cattle/ID/26G07162-002-or...     cattle
1122   Influenza A virus (A/cattle/ID/26G07162-003-or...     cattle
1130   Influenza A virus (A/cattle/ID/26G07162-004-or...     cattle
1138   Influenza A virus (A/cattle/ID/26G07162-005-or...     cattle
...                                                  ...        ...
81413  Influenza A virus (A/cattle/New Mexico/24-0103...     cattle
81421  Influenza A virus (A/cattle/New Mexico/24-0103...     cattle
81429  Influenza A virus (A/cattle/North Carolina/24-...     cattle
81437  Influenza A virus (A/chicken/Michigan/24-01030...    chicken
81445  Influenza A virus (A/blackbird/Texas/24-008354...  blackbird

      Collection_Date SRA_Accession  \
1106       2026-05-04   SRR38788432
1114       2026-05-04   SRR38788431
1122       2026-05-04   SRR38788430
1130       2026-05-04   SRR38788428
1138       2026-05-04   SRR38788427
...               ...           ...
81413      2024-04-01   SRR28752633
81421      2024-04-01   SRR28752631
81429      2024-04-04   SRR28752637
81437      2024-04-06   SRR28752638
81445      2024-03-16   SRR28752446

                                          Isolate Genotype_official  \
1106       A/cattle/ID/26G07162-001-original/2026             B3.13
1114       A/cattle/ID/26G07162-002-original/2026             B3.13
1122       A/cattle/ID/26G07162-003-original/2026             B3.13
1130       A/cattle/ID/26G07162-004-original/2026             B3.13
1138       A/cattle/ID/26G07162-005-original/2026             B3.13
...                                           ...               ...
81413      A/cattle/New Mexico/24-010330-003/2024             B3.13
81421      A/cattle/New Mexico/24-010330-005/2024             B3.13
81429  A/cattle/North Carolina/24-010327-003/2024             B3.13
81437       A/chicken/Michigan/24-010308-012/2024             B3.13
81445        A/blackbird/Texas/24-008354-001/2024             B3.13

      Geo_Location                                        full_header  ...  \
1106       USA: ID  >PZ479598.1 |Influenza A virus (A/cattle/ID/26...  ...
1114       USA: ID  >PZ479606.1 |Influenza A virus (A/cattle/ID/26...  ...
1122       USA: ID  >PZ479614.1 |Influenza A virus (A/cattle/ID/26...  ...
1130       USA: ID  >PZ479622.1 |Influenza A virus (A/cattle/ID/26...  ...
1138       USA: ID  >PZ479630.1 |Influenza A virus (A/cattle/ID/26...  ...
...            ...                                                ...  ...
81413          USA  >PP756074.1 |Influenza A virus (A/cattle/New M...  ...
81421          USA  >PP756082.1 |Influenza A virus (A/cattle/New M...  ...
81429          USA  >PP756090.1 |Influenza A virus (A/cattle/North...  ...
81437          USA  >PP756098.1 |Influenza A virus (A/chicken/Mich...  ...
81445          USA  >PP740727.1 |Influenza A virus (A/blackbird/Te...  ...

      Genotype       Host_Type  Years Geo_Location_Normalized  \
1106     B3.13          cattle   2026                  USA-ID
1114     B3.13          cattle   2026                  USA-ID
1122     B3.13          cattle   2026                  USA-ID
1130     B3.13          cattle   2026                  USA-ID
1138     B3.13          cattle   2026                  USA-ID
...        ...             ...    ...                     ...
81413    B3.13          cattle   2024                 USA-USA
81421    B3.13          cattle   2024                 USA-USA
81429    B3.13          cattle   2024                 USA-USA
81437    B3.13  domestic_avian   2024                 USA-USA
81445    B3.13      wild_avian   2024                 USA-USA

      Geo_Location_Country Geo_Location_State Geo_Location_New   Identifier  \
1106                   USA                 ID           USA-ID  SRR38788432
1114                   USA                 ID           USA-ID  SRR38788431
1122                   USA                 ID           USA-ID  SRR38788430
1130                   USA                 ID           USA-ID  SRR38788428
1138                   USA                 ID           USA-ID  SRR38788427
...                    ...                ...              ...          ...
81413                  USA                USA              USA  SRR28752633
81421                  USA                USA              USA  SRR28752631
81429                  USA                USA              USA  SRR28752637
81437                  USA                USA              USA  SRR28752638
81445                  USA                USA              USA  SRR28752446

                                                    Name Segment_Name
1106   >SRR38788432|A/cattle/ID/26G07162-001-original...           PA
1114   >SRR38788431|A/cattle/ID/26G07162-002-original...           PA
1122   >SRR38788430|A/cattle/ID/26G07162-003-original...           PA
1130   >SRR38788428|A/cattle/ID/26G07162-004-original...           PA
1138   >SRR38788427|A/cattle/ID/26G07162-005-original...           PA
...                                                  ...          ...
81413  >SRR28752633|A/cattle/New Mexico/24-010330-003...           PA
81421  >SRR28752631|A/cattle/New Mexico/24-010330-005...           PA
81429  >SRR28752637|A/cattle/North Carolina/24-010327...           PA
81437  >SRR28752638|A/chicken/Michigan/24-010308-012/...           PA
81445  >SRR28752446|A/blackbird/Texas/24-008354-001/2...           PA

[4298 rows x 26 columns]
        Accession         Assembly  \
1107   PZ479599.1  GCA_058019015.1
1115   PZ479607.1  GCA_058019025.1
1123   PZ479615.1  GCA_058019055.1
1131   PZ479623.1  GCA_058019105.1
1139   PZ479631.1  GCA_058019115.1
...           ...              ...
81408  PP756069.1  GCA_039465795.1
81416  PP756077.1  GCA_039464765.1
81424  PP756085.1  GCA_039465935.1
81432  PP756093.1  GCA_039466035.1
81440  PP740722.1  GCA_039251605.1

                                           GenBank_Title       Host  \
1107   Influenza A virus (A/cattle/ID/26G07162-001-or...     cattle
1115   Influenza A virus (A/cattle/ID/26G07162-002-or...     cattle
1123   Influenza A virus (A/cattle/ID/26G07162-003-or...     cattle
1131   Influenza A virus (A/cattle/ID/26G07162-004-or...     cattle
1139   Influenza A virus (A/cattle/ID/26G07162-005-or...     cattle
...                                                  ...        ...
81408  Influenza A virus (A/cattle/New Mexico/24-0103...     cattle
81416  Influenza A virus (A/cattle/New Mexico/24-0103...     cattle
81424  Influenza A virus (A/cattle/North Carolina/24-...     cattle
81432  Influenza A virus (A/chicken/Michigan/24-01030...    chicken
81440  Influenza A virus (A/blackbird/Texas/24-008354...  blackbird

      Collection_Date SRA_Accession  \
1107       2026-05-04   SRR38788432
1115       2026-05-04   SRR38788431
1123       2026-05-04   SRR38788430
1131       2026-05-04   SRR38788428
1139       2026-05-04   SRR38788427
...               ...           ...
81408      2024-04-01   SRR28752633
81416      2024-04-01   SRR28752631
81424      2024-04-04   SRR28752637
81432      2024-04-06   SRR28752638
81440      2024-03-16   SRR28752446

                                          Isolate Genotype_official  \
1107       A/cattle/ID/26G07162-001-original/2026             B3.13
1115       A/cattle/ID/26G07162-002-original/2026             B3.13
1123       A/cattle/ID/26G07162-003-original/2026             B3.13
1131       A/cattle/ID/26G07162-004-original/2026             B3.13
1139       A/cattle/ID/26G07162-005-original/2026             B3.13
...                                           ...               ...