# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI and relabeling sequences. 

Notes:
* This file must be in the same folder as "utils.py"

## Housekeeping

In [1]:
# Libraries

import os
import pandas as pd
import dateutil
import re
import shutil 
import numpy as np
import importlib
import utils  
importlib.reload(utils)
from utils import * # If changing utils, must restart this file for changes to take effect

In [50]:
# Directory paths and input

# Input
browser = input("Browser (Firefox, Chrome, or Edge): ")
sleep_time = input("Seconds to wait in between clicks (recommended 5): ")
# locations = input("Locations (separate with commas and no spaces in between locations): ")
# start_date = input("Start date (format: MM-DD-YYYY): ")
# end_date = input("End date: (format: MM-DD-YYYY): ")
# serotype = input("Serotype (e.g. H5N1): ")
# serotypes = list(serotype)
# genotypes = input("Genotypes (separate with commas and no spaces in between genotypes): ")
# genotypes = genotypes.split(",")

# Dates and locations
locations = "Antarctica,North America,South America"
start_date = "11-01-2021"
end_date = "06-05-2026"
prev_end_date = "05-15-2026"
date_range = start_date + "--" + end_date
prev_date_range = start_date + "--" + prev_end_date

# Maintenance serotypes and genotypes
serotypes = ["H5N1"]
genotypes = ["B3.13"] #, "D1.1", "D1.3", "Not"]

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# downloads = "C:/Users/maksi/Downloads/"
# references = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/references/"

home = "C:/Users/maksiaevai.NCBI_NT/OneDrive - National Institutes of Health/Documents/Virus_Evolution/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Downloads/" # MUST be downloads folder. Clean out downloads folder after each use. 
references = "C:/Users/maksiaevai.NCBI_NT/OneDrive - National Institutes of Health/Documents/Virus_Evolution/Avian_Flu/references/"

downloads_saved = home + "NCBI_Virus/downloads/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/" 
prev_downloads_saved = home + "NCBI_Virus/downloads/" + prev_date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/" 

andersen = home + "Andersen/avian-influenza/metadata/"
temp_files = home + "NCBI_Virus/temp/"
complete_files = home + "NCBI_Virus/complete/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/"
if not os.path.exists(complete_files): # checking if the directory exists or not
    os.makedirs(complete_files) # if the directory is not present then create it

os.chdir(references)
states_ref = pd.read_csv("states_ref.csv")

# All serotypes and genotypes
# serotype = ""
# genotypes_df = pd.read_excel("genotype_key.xlsx")
# genotypes = list(genotypes_df["Genotype"])

## Downloading Data

In [3]:
os.chdir(downloads)

if not os.path.exists(downloads_saved): # checking if the directory exists or not
    os.makedirs(downloads_saved) # if the directory is not present then create it

# Move downloaded files to saved downloads
for dirpath, dirs, files in os.walk(downloads_saved):
    if len(files) != 0:
        break 
    else: # If we don't have any downloaded files
        # Get files
        # open_ncbi_virus(browser, sleep_time, locations, start_date, end_date)

        # Re-try 
        for dirpath, dirs, files in os.walk(downloads):
            if len(files) > 0: # If we have any files that need to be moved
                for file in files:
                    file_name = os.path.join(dirpath, file)
                    destination_path = os.path.join(downloads_saved, os.path.basename(file_name))
                    try:
                        shutil.move(file_name, destination_path)
                    except:
                        print("Error moving file", file_name)
                        continue 
            break 
    break

## De-Duplication

In [51]:
# Get metadata
os.chdir(downloads_saved)
metadata = pd.read_csv("sequences.csv")
print(len(metadata))

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.Assembly, as_index=False).size()
print(metadata_counts)
metadata_counted = metadata.merge(metadata_counts, on="Assembly")

# Only keep those with size >= 8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates
metadata_complete_segs = metadata_counted.drop_duplicates(subset="GenBank_Title", keep="last") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]
metadata_segments = metadata_complete_segs
metadata_segments

162482
              Assembly  size
0      GCA_038163845.1     8
1      GCA_038163995.1     8
2      GCA_038164135.1     8
3      GCA_038164315.1     8
4      GCA_038164335.1     8
...                ...   ...
18707  GCA_058020725.1     8
18708  GCA_058020755.1     8
18709  GCA_058020765.1     8
18710  GCA_058020775.1     8
18711  GCA_058020785.1     8

[18712 rows x 2 columns]

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Host,Tissue_Specimen_Source,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size
0,OK205528.2,GenBank,GCA_038185045.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C.M., Parris,D.J., Kariithi,H....","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,1.0,2001,2021-11-01,ssRNA(-),8
1,OK205529.2,GenBank,GCA_038185045.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C.M., Parris,D.J., Kariithi,H....","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,1.0,2001,2021-11-01,ssRNA(-),8
2,OK205530.2,GenBank,GCA_038185045.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C.M., Parris,D.J., Kariithi,H....","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,1.0,2001,2021-11-01,ssRNA(-),8
3,OK205531.1,GenBank,GCA_038185045.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C.M., Parris,D.J., Kariithi,H....","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,1.0,2001,2021-11-01,ssRNA(-),8
4,OK205532.1,GenBank,GCA_038185045.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C.M., Parris,D.J., Kariithi,H....","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,1.0,2001,2021-11-01,ssRNA(-),8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149673,PP755920.1,GenBank,GCA_039463595.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Bos taurus,NaN,"Nguyen,T., Hutter,C., Markin,A., Thomas,M., La...","National Animal Disease Center, USDA-ARS",USA,NaN,2024-03-19,2024-05-03,ssRNA(-),8
149674,PP755922.1,GenBank,GCA_039463595.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Bos taurus,NaN,"Nguyen,T., Hutter,C., Markin,A., Thomas,M., La...","National Animal Disease Center, USDA-ARS",USA,NaN,2024-03-19,2024-05-03,ssRNA(-),8
149675,PP755924.1,GenBank,GCA_039463595.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Bos taurus,NaN,"Nguyen,T., Hutter,C., Markin,A., Thomas,M., La...","National Animal Disease Center, USDA-ARS",USA,NaN,2024-03-19,2024-05-03,ssRNA(-),8
149676,PP756066.1,GenBank,GCA_039464865.1,SRR28834851,SAMN41100354,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Bos taurus,mammalian milk,"Nguyen,T., Hutter,C., Markin,A., Thomas,M., La...","National Animal Disease Center, USDA-ARS",USA,NaN,2024-04-04,2024-05-03,ssRNA(-),8
149677,PP756068.1,GenBank,GCA_039464865.1,SRR28834851,SAMN41100354,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Bos taurus,mammalian milk,"Nguyen,T., Hutter,C., Markin,A., Thomas,M., La...","National Animal Disease Center, USDA-ARS",USA,NaN,2024-04-04,2024-05-03,ssRNA(-),8

## Add sequences to dataframe

In [52]:
# NCBI Virus Naming Convention:
# "Accession|GenBank_Title|Assembly|SRA Accession|BioSample|BioProject|Genotype|Isolate|Geo Location|Host|Collection Date"

# Get sequences and headers together
# headers = []
# isolates = []
# sras = []
# headers_seqs = {}

os.chdir(downloads_saved)

sequences_fasta = df_from_fasta("sequences.fasta") # Turn fasta into a dataframe

sequences_fasta["Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split(" |")[0].replace(">",""))

print(sequences_fasta["full_header"])

# Extract segment number so that we can add the correct sequences to the correct sample
# sequences_fasta["Segment"] = sequences_fasta["full_header"].apply(lambda x: int(re.search(r'segment (.?) ', x.split("|")[-2]).group(1)))

# Double-check the de-duplication
print(len(sequences_fasta)) 
# print(sequences_fasta.head())
print(len(metadata_segments))

# Add sequences to the dataframe
metadata_segments = pd.merge(metadata_segments, sequences_fasta, on="Accession") # , "Segment"])

0         >OK205528.2 |Influenza A virus (A/chicken/El S...
1         >OK205529.2 |Influenza A virus (A/chicken/El S...
2         >OK205530.2 |Influenza A virus (A/chicken/El S...
3         >OK205531.1 |Influenza A virus (A/chicken/El S...
4         >OK205532.1 |Influenza A virus (A/chicken/El S...
                                ...
162477    >PP755920.1 |Influenza A virus (A/cattle/Texas...
162478    >PP755922.1 |Influenza A virus (A/cattle/Texas...
162479    >PP755924.1 |Influenza A virus (A/cattle/Texas...
162480    >PP756066.1 |Influenza A virus (A/cattle/North...
162481    >PP756068.1 |Influenza A virus (A/cattle/North...
Name: full_header, Length: 162482, dtype: object
162482
148166

In [53]:
metadata_segments

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size,full_header,sequence
0,OK205528.2,GenBank,GCA_038185045.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C.M., Parris,D.J., Kariithi,H....","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,1.0,2001,2021-11-01,ssRNA(-),8,>OK205528.2 |Influenza A virus (A/chicken/El S...,TCAAATATATTCAATATGGAGAGAATAAAAGAACTAAGAGATCTAA...
1,OK205529.2,GenBank,GCA_038185045.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C.M., Parris,D.J., Kariithi,H....","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,1.0,2001,2021-11-01,ssRNA(-),8,>OK205529.2 |Influenza A virus (A/chicken/El S...,CAGGCAAACTATTTGAATGGATGTCAATCCGACTTTACTTTTCTTG...
2,OK205530.2,GenBank,GCA_038185045.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C.M., Parris,D.J., Kariithi,H....","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,1.0,2001,2021-11-01,ssRNA(-),8,>OK205530.2 |Influenza A virus (A/chicken/El S...,CAGGTACTGATCAAAAATGGAAGACTTCGTGCGACAGTGCTTCAAT...
3,OK205531.1,GenBank,GCA_038185045.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C.M., Parris,D.J., Kariithi,H....","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,1.0,2001,2021-11-01,ssRNA(-),8,>OK205531.1 |Influenza A virus (A/chicken/El S...,AGCAAAAGCAGGGGTATCAACCATCAAAATGAAAAGAATAGTGATT...
4,OK205532.1,GenBank,GCA_038185045.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C.M., Parris,D.J., Kariithi,H....","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,1.0,2001,2021-11-01,ssRNA(-),8,>OK205532.1 |Influenza A virus (A/chicken/El S...,AGCAAAAGCAGGGTAGATAATCACTCACCGAGTGACATTCACATCA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148161,PP755920.1,GenBank,GCA_039463595.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Nguyen,T., Hutter,C., Markin,A., Thomas,M., La...","National Animal Disease Center, USDA-ARS",USA,NaN,2024-03-19,2024-05-03,ssRNA(-),8,>PP755920.1 |Influenza A virus (A/cattle/Texas...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
148162,PP755922.1,GenBank,GCA_039463595.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Nguyen,T., Hutter,C., Markin,A., Thomas,M., La...","National Animal Disease Center, USDA-ARS",USA,NaN,2024-03-19,2024-05-03,ssRNA(-),8,>PP755922.1 |Influenza A virus (A/cattle/Texas...,ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
148163,PP755924.1,GenBank,GCA_039463595.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Nguyen,T., Hutter,C., Markin,A., Thomas,M., La...","National Animal Disease Center, USDA-ARS",USA,NaN,2024-03-19,2024-05-03,ssRNA(-),8,>PP755924.1 |Influenza A virus (A/cattle/Texas...,ATGGAGAGAATAAAGGAACTGAGAGATCTAATGTCACAGTCTCGCA...
148164,PP756066.1,GenBank,GCA_039464865.1,SRR28834851,SAMN41100354,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Nguyen,T., Hutter,C., Markin,A., Thomas,M., La...","National Animal Disease Center, USDA-ARS",USA,NaN,2024-04-04,2024-05-03,ssRNA(-),8,>PP756066.1 |Influenza A virus (A/cattle/North...,ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
148165,PP756068.1,GenBank,GCA_039464865.1,SRR28834851,SAMN41100354,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Nguyen,T., Hutter,C., Markin,A., Thomas,M., La...","National Animal Disease Center, USDA-ARS",USA,NaN,2024-04-04,2024-05-03,ssRNA(-),8,>PP756068.1 |Influenza A virus (A/cattle/North...,CTGTTGACCACATGGCCATAATCAAGAAGTACACATCAGGAAGACA...

## Find genotypes

(Using old genoflu results or Andersen Lab genoflu output) <br>
Old genoflu results should accumulate into one file to avoid having to genotype anything again.

### Find old genotypes

In [55]:
# Switch directory to previous week
os.chdir(prev_downloads_saved)

# Get both files from previous week
genoflu_output = pd.read_csv("output.tsv", delimiter="\t")
genoflu_results = pd.read_csv("results.tsv", delimiter="\t")

# Get old results from output.tsv
genoflu_old = pd.concat([genoflu_output, genoflu_results])
# genoflu_old = genoflu_old.rename(columns={"Strain":"Partial_Header"}) # So we can merge
print(genoflu_old)

# Switch back directory
os.chdir(downloads_saved)

# Save this output for the future
genoflu_old.to_csv("output.tsv", sep="\t", index=False)

                                                 Strain  \
0     Influenza_A_virus__Mexico__Estado_de_Mexico_CP...
1     Influenza_A_virus__Mexico__Estado_de_Mexico_CP...
2     Influenza_A_virus__Mexico__Ciudad_de_Mexico_CP...
3     Influenza_A_virus__Mexico__Estado_de_Mexico_CP...
4     Influenza_A_virus__Mexico__Michoacan_CPA_02011...
...                                                 ...
5473                                    GCA_051456995_1
5474                                    GCA_046401875_1
5475                                    GCA_051455955_1
5476                                    GCA_056677775_1
5477                                    GCA_055688435_1

                                               Genotype  \
0     Not assigned: Only 3 segments >98.0% match fou...
1     Not assigned: Only 3 segments >98.0% match fou...
2     Not assigned: Only 3 segments >98.0% match fou...
3     Not assigned: Only 3 segments >98.0% match fou...
4     Not assigned: Only 6 segments >98.0% match fou...
...                                                 ...
5473                                               B4.1
5474                                                 A3
5475                                               B4.1
5476  Not assigned: Only 7 segments >98.0% match fou...
5477                                               D1.1

                            Genotype List Used, >=98.0%  \
0                              PA:ea1, MP:ea1, NS:am1.1
1                              PA:ea1, MP:ea1, NS:am1.1
2                              PA:ea1, MP:ea1, NS:am1.1
3                              PA:ea1, MP:ea1, NS:am1.1
4     PB2:am2.1, PB1:am1.2, PA:ea1, HA:ea1, MP:ea1, ...
...                                                 ...
5473  PB2:am2.2, PB1:ea1, PA:ea1, HA:ea1, NP:am1.3, ...
5474  PB2:ea3, PB1:ea3, PA:ea3, HA:ea3, NP:ea3, NA:e...
5475  PB2:am2.2, PB1:ea1, PA:ea1, HA:ea1, NP:am1.3, ...
5476  PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...
5477  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
0     am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
1     am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
2     am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
3     am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
4     am2.1:22-009329-001:PB2, am1.2:22-010085-001:P...
...                                                 ...
5473  am2.2:22-010445-001:PB2, ea1:22-003707-003:PB1...
5474  ea3:22-013001-001:PB2, ea3:22-013001-001:PB1, ...
5475  am2.2:22-010445-001:PB2, ea1:22-003707-003:PB1...
5476  am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...
5477  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
0     97.63%, 92.66%, 98.33%, 97.53%, 88.91%, 83.52%...
1     97.67%, 92.66%, 98.33%, 97.59%, 88.84%, 83.52%...
2     97.57%, 92.70%, 98.28%, 97.59%, 88.84%, 83.52%...
3     97.67%, 92.70%, 98.33%, 97.36%, 88.84%, 83.43%...
4     98.90%, 98.77%, 98.98%, 98.47%, 88.96%, 83.70%...
...                                                 ...
5473  99.69%, 99.91%, 99.81%, 99.41%, 99.80%, 99.43%...
5474  99.91%, 99.60%, 99.72%, 99.59%, 99.73%, 99.50%...
5475  99.69%, 99.69%, 99.67%, 99.65%, 100.00%, 99.64...
5476  98.29%, 99.16%, 97.40%, 99.30%, 99.47%, 99.22%...
5477  99.56%, 99.21%, 99.02%, 99.30%, 99.53%, 99.15%...

                 Genotype Mismatch List  \
0     54, 167, 36, 42, 166, 186, 18, 14
1     53, 167, 36, 41, 167, 186, 18, 14
2     35, 166, 37, 41, 167, 186, 19, 14
3     53, 166, 36, 45, 167, 187, 18, 14
4       25, 28, 22, 26, 165, 182, 12, 9
...                                 ...
5473            7, 2, 4, 10, 3, 8, 1, 7
5474             2, 9, 6, 7, 4, 7, 0, 2
5475             7, 7, 7, 6, 0, 5, 1, 5
5476        39, 19, 56, 12, 8, 11, 5, 9
5477        10, 18, 21, 12, 7, 12, 2, 9

     Genotype Average Depth of Coverage List             Date run
0          Ran on FASTA - No Coverage Report  2025-12-03_10-28-26
1          Ran on FASTA - No Coverage Report  2025-12-03_10-28-27
2          Ran on FASTA - No Coverage Report  2025-12-03_10-28-27
3          Ran on FASTA - No Coverage Report  2025-12-03_10-28-27
4          Ran on FASTA - No Coverage Report  2025-12-03_10-28-28
...                                      ...                  ...
5473       Ran on FASTA - No Coverage Report  2026-05-19_14-26-22
5474       Ran on FASTA - No Coverage Report  2026-05-19_14-26-22
5475       Ran on FASTA - No Coverage Report  2026-05-19_14-26-22
5476       Ran on FASTA - No Coverage Report  2026-05-19_14-26-23
5477       Ran on FASTA - No Coverage Report  2026-05-19_14-26-23

[24719 rows x 8 columns]

In [56]:

metadata_segments["Partial_Header_temp"] = metadata_segments["Isolate"] # Get only isolate

for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]: # Forbidden punctuation
    metadata_segments["Partial_Header_temp"] = metadata_segments["Partial_Header_temp"].apply(lambda x: x.replace(c, "_") if x == x else x)

# Merge to get already-genotyped segments
genoflu_old["Partial_Header_temp"] = genoflu_old["Strain"].apply(lambda x: re.split(r'Influenza_A_virus__\D*__\D*_', x)[-1]) # Get only isolate 
genoflu_old["Partial_Header_temp"] = genoflu_old["Partial_Header_temp"].apply(lambda x: re.split(r'_H.N._20.{2}_.{2}_.{2}', x)[0]) # Get only isolate

metadata_segments_old = metadata_segments.merge(genoflu_old, how="inner", on="Partial_Header_temp") 

# Isolate not-already-genotyped segments
metadata_segments_new = metadata_segments.merge(genoflu_old, indicator=True, how='left', on="Partial_Header_temp").loc[lambda x : x['_merge']=='left_only'] 

print(len(metadata_segments_old))
print(len(metadata_segments_new))

128
148038

In [57]:
# Get genoflu results from Andersen and see if any fit

os.chdir(andersen)

genoflu_andersen = pd.read_csv("genoflu_results.tsv", delimiter="\t")
genoflu_andersen = genoflu_andersen.rename(columns={"sample":"SRA_Accession"}) # So we can merge with old
# genoflu_andersen["SRA_Accession"] = genoflu_andersen["Strain"] # So we can merge with new

# Find those genotyped by Andersen via merge
metadata_segments_known_andersen = metadata_segments_new.merge(genoflu_andersen, how="inner", on="SRA_Accession")
print(metadata_segments_known_andersen)
# Rename genotype by Andersen to concatenate
metadata_segments_known_andersen["Genotype_y"] = metadata_segments_known_andersen["Genotype"]

# Keep all known genotypes
metadata_segments_known = pd.concat([metadata_segments_old, metadata_segments_known_andersen]) # , on="SRA_Accession", how="left") # Since we know both of these

print(metadata_segments_old)
print(metadata_segments_known_andersen)

        Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0      PQ051119.1        GenBank  GCA_040889855.1   SRR29455647  SAMN41892119
1      PQ051120.1        GenBank  GCA_040889855.1   SRR29455647  SAMN41892119
2      PQ051121.1        GenBank  GCA_040889855.1   SRR29455647  SAMN41892119
3      PQ051122.1        GenBank  GCA_040889855.1   SRR29455647  SAMN41892119
4      PQ051123.1        GenBank  GCA_040889855.1   SRR29455647  SAMN41892119
...           ...            ...              ...           ...           ...
81283  PZ422028.1        GenBank  GCA_057730505.1   SRR38140017  SAMN57311643
81284  PZ422029.1        GenBank  GCA_057730505.1   SRR38140017  SAMN57311643
81285  PZ422030.1        GenBank  GCA_057730505.1   SRR38140017  SAMN57311643
81286  PP756066.1        GenBank  GCA_039464865.1   SRR28834851  SAMN41100354
81287  PP756068.1        GenBank  GCA_039464865.1   SRR28834851  SAMN41100354

         BioProject      Organism_Name                         Species  \
0      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
1      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
2      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
4      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
...             ...                ...                             ...
81283  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
81284  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
81285  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
81286  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81287  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                     Genus            Family  ... Date run     _merge  \
0      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
1      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
2      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
...                    ...               ...  ...      ...        ...
81283  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81284  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81285  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81286  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81287  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only

                      date       File Name  \
0      2025-05-09_10-48-03  SRR29455647.fa
1      2025-05-09_10-48-03  SRR29455647.fa
2      2025-05-09_10-48-03  SRR29455647.fa
3      2025-05-09_10-48-03  SRR29455647.fa
4      2025-05-09_10-48-03  SRR29455647.fa
...                    ...             ...
81283  2026-04-18_06-41-27  SRR38140017.fa
81284  2026-04-18_06-41-27  SRR38140017.fa
81285  2026-04-18_06-41-27  SRR38140017.fa
81286  2025-05-09_10-47-27  SRR28834851.fa
81287  2025-05-09_10-47-27  SRR28834851.fa

                                  Genotype  \
0                                    B3.13
1                                    B3.13
2                                    B3.13
3                                    B3.13
4                                    B3.13
...                                    ...
81283                                 D1.8
81284                                 D1.8
81285                                 D1.8
81286  Not assigned: No Matching Genotypes
81287  Not assigned: No Matching Genotypes

                           Genotype List Used, >=98.0%_y  \
0      NS:am1.1, PB2:am2.2, PB1:am4, HA:ea1, PA:ea1, ...
1      NS:am1.1, PB2:am2.2, PB1:am4, HA:ea1, PA:ea1, ...
2      NS:am1.1, PB2:am2.2, PB1:am4, HA:ea1, PA:ea1, ...
3      NS:am1.1, PB2:am2.2, PB1:am4, HA:ea1, PA:ea1, ...
4      NS:am1.1, PB2:am2.2, PB1:am4, HA:ea1, PA:ea1, ...
...                                                  ...
81283  HA:ea3, NP:am1.1, NA:am4N1, PB1:ea3, PB2:am24,...
81284  HA:ea3, NP:am1.1, NA:am4N1, PB1:ea3, PB2:am24,...
81285  HA:ea3, NP:am1.1, NA:am4N1, PB1:ea3, PB2:am24,...
81286  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, MP:...
81287  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, MP:...

                            Genotype Sample Title List_y  \
0      am1.1:22-010085-001:NS, am2.2:22-010445-001:PB...
1      am1.1:22-010085-001:NS, am2.2:22-010445-001:PB...
2      am1.1:22-010085-001:NS, am2.2:22-010445-001:PB...
3      am1.1:22-010085-001:NS, am2.2:22-010445-001:PB...
4      am1.1:22-010085-001:NS, am2.2:22-010445-001:PB...
...                                                  ...
81283  ea3:22-013001-001:HA, am1.1:22-007805-001:NP, ...
81284  ea3:22-013001-001:HA, am1.1:22-007805-001:NP, ...
81285  ea3:22-013001-001:HA, am1.1:22-007805-001:NP, ...
81286  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...
81287  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...

                           Genotype Percent Match List_y  \
0      99.17%, 98.82%, 99.56%, 98.71%, 99.16%, 98.88%...
1      99.17%, 98.82%, 99.56%, 98.71%, 99.16%, 98.88%...
2      99.17%, 98.82%, 99.56%, 98.71%, 99.16%, 98.88%...
3      99.17%, 98.82%, 99.56%, 98.71%, 99.16%, 98.88%...
4      99.17%, 98.82%, 99.56%, 98.71%, 99.16%, 98.88%...
...                                                  ...
81283  99.00%, 98.86%, 98.56%, 99.03%, 99.34%, 98.81%...
81284  99.00%, 98.86%, 98.56%, 99.03%, 99.34%, 98.81%...
81285  99.00%, 98.86%, 98.56%, 99.03%, 99.34%, 98.81%...
81286  99.55%, 99.22%, 98.94%, 98.63%, 99.28%, 98.78%...
81287  99.55%, 99.22%, 98.94%, 98.63%, 99.28%, 98.78%...

            Genotype Mismatch List_y Genotype Average Depth of Coverage List_y
0      7, 27, 10, 22, 18, 11, 16, 12         Ran on FASTA - No Coverage Report
1      7, 27, 10, 22, 18, 11, 16, 12         Ran on FASTA - No Coverage Report
2      7, 27, 10, 22, 18, 11, 16, 12         Ran on FASTA - No Coverage Report
3      7, 27, 10, 22, 18, 11, 16, 12         Ran on FASTA - No Coverage Report
4      7, 27, 10, 22, 18, 11, 16, 12         Ran on FASTA - No Coverage Report
...                              ...                                       ...
81283  17, 17, 15, 22, 15, 10, 4, 18         Ran on FASTA - No Coverage Report
81284  17, 17, 15, 22, 15, 10, 4, 18         Ran on FASTA - No Coverage Report
81285  17, 17, 15, 22, 15, 10, 4, 18         Ran on FASTA - No Coverage Report
81286      4, 2, 15, 16, 6, 12, 2, 9         Ran on FASTA - No Coverage Report
81287      4, 2, 15, 16, 6, 12, 2, 9         Ran on FASTA - No Coverage Report

[81288 rows x 49 columns]
      Accession GenBank_RefSeq         Assembly SRA_Accession BioSample  \
0    OK205488.1        GenBank  GCA_039015945.1           NaN       NaN
1    OK205489.1        GenBank  GCA_039015945.1           NaN       NaN
2    OK205490.1        GenBank  GCA_039015945.1           NaN       NaN
3    OK205491.1        GenBank  GCA_039015945.1           NaN       NaN
4    OK205492.1        GenBank  GCA_039015945.1           NaN       NaN
..          ...            ...              ...           ...       ...
123  OK205667.1        GenBank  GCA_038971685.1           NaN       NaN
124  OK205668.1        GenBank  GCA_038971685.1           NaN       NaN
125  OK205669.1        GenBank  GCA_038971685.1           NaN       NaN
126  OK205670.1        GenBank  GCA_038971685.1           NaN       NaN
127  OK205671.1        GenBank  GCA_038971685.1           NaN       NaN

    BioProject      Organism_Name                         Species  \
0          NaN  Influenza A virus  Alphainfluenzavirus influenzae
1          NaN  Influenza A virus  Alphainfluenzavirus influenzae
2          NaN  Influenza A virus  Alphainfluenzavirus influenzae
3          NaN  Influenza A virus  Alphainfluenzavirus influenzae
4          NaN  Influenza A virus  Alphainfluenzavirus influenzae
..         ...                ...                             ...
123        NaN  Influenza A virus  Alphainfluenzavirus influenzae
124        NaN  Influenza A virus  Alphainfluenzavirus influenzae
125        NaN  Influenza A virus  Alphainfluenzavirus influenzae
126        NaN  Influenza A virus  Alphainfluenzavirus influenzae
127        NaN  Influenza A virus  Alphainfluenzavirus influenzae

                   Genus            Family  ...  \
0    Alphainfluenzavirus  Orthomyxoviridae  ...
1    Alphainfluenzavirus  Orthomyxoviridae  ...
2    Alphainfluenzavirus  Orthomyxoviridae  ...
3    Alphainfluenzavirus  Orthomyxoviridae  ...
4    Alphainfluenzavirus  Orthomyxoviridae  ...
..                   ...               ...  ...
123  Alphainfluenzavirus  Orthomyxoviridae  ...
124  Alphainfluenzavirus  Orthomyxoviridae  ...
125  Alphainfluenzavirus  Orthomyxoviridae  ...
126  Alphainfluenzavirus  Orthomyxoviridae  ...
127  Alphainfluenzavirus  Orthomyxoviridae  ...

                                              sequence Partial_Header_temp  \
0    TCAAATATATTCAATATGGAGAGAATAAAAGAACTAAGAGATCTAA...               716_2
1    CAAACTATTTGAATGGATGTCAATCCGACTCTACTTTTCTTGAAAG...               716_2
2    GCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAGTGTTTCAA...               716_2
3    TTCAACTGTCAAAATGGAAAGGATAGTAATCGCCTTTGCAATAATC...               716_2
4    GTAGATAATCACTCACTGAGTGACATTTACATCATGGCGTCTCAAG...               716_2
..                                                 ...                 ...
123  ATGGAAAGAATAGCAATTGCCTTTGCATTAATCAGCATTGTCACAG...         LVVX17186_2
124  GTAGATAATCACTCACTGAGTGACATTCACATCATGGCGTCTCAAG...         LVVX17186_2
125  AATGAATCCAAATCAGAAAATAATAACAATAGGCTCCATTTCTCTA...         LVVX17186_2
126  TAGATGTTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTT...         LVVX17186_2
127  GTGACAAATACATAATGGACTCCAACACGATAACCTCGTTTCAGGT...         LVVX17186_2

                                                Strain  \
0    Influenza_A_virus__Mexico__Jalisco_716_2_H5N2_...
1    Influenza_A_virus__Mexico__Jalisco_716_2_H5N2_...
2    Influenza_A_virus__Mexico__Jalisco_716_2_H5N2_...
3    Influenza_A_virus__Mexico__Jalisco_716_2_H5N2_...
4    Influenza_A_virus__Mexico__Jalisco_716_2_H5N2_...
..                                                 ...
123  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
124  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
125  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
126  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
127  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...

                                            Genotype_y  \
0    Not assigned: Only 0 segments >98.0% match fou...
1    Not assigned: Only 0 segments >98.0% match fou...
2    Not assigned: Only 0 segments >98.0% match fou...
3    Not assigned: Only 0 segments >98.0% match fou...
4    Not assigned: Only 0 segments >98.0% match fou...
..                                                 ...
123  Not assigned: Only 0 segments >98.0% match fou...
124  Not assigned: Only 0 segments >98.0% match fou...
125  Not assigned: Only 0 segments >98.0% match fou...
126  Not assigned: Only 0 segments >98.0% match fou...
127  Not assigned: Only 0 segments >98.0% match fou...

     Genotype List Used, >=98.0%  \
0                            NaN
1                            NaN
2                            NaN
3                            NaN
4                            NaN
..                           ...
123                          NaN
124                          NaN
125                          NaN
126                          NaN
127                          NaN

                            Genotype Sample Title List  \
0    am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
1    am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
2    am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
3    am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
4    am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
..                                                 ...
123  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
124  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
125  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
126  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
127  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...

                           Genotype Percent Match List  \
0    91.84%, 95.12%, 87.31%, 77.80%, 90.11%, 85.39%...
1    91.84%, 95.12%, 87.31%, 77.80%, 90.11%, 85.39%...
2    91.84%, 95.12%, 87.31%, 77.80%, 90.11%, 85.39%...
3    91.84%, 95.12%, 87.31%, 77.80%, 90.11%, 85.39%...
4    91.84%, 95.12%, 87.31%, 77.80%, 90.11%, 85.39%...
..                                                 ...
123  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
124  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
125  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
126  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
127  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...

                   Genotype Mismatch List  \
0    186, 109, 273, 359, 148, 170, 80, 75
1    186, 109, 273, 359, 148, 170, 80, 75
2    186, 109, 273, 359, 148, 170, 80, 75
3    186, 109, 273, 359, 148, 170, 80, 75
4    186, 109, 273, 359, 148, 170, 80, 75
..                                    ...
123  176, 113, 256, 363, 151, 171, 82, 77
124  176, 113, 256, 363, 151, 171, 82, 77
125  176, 113, 256, 363, 151, 171, 82, 77
126  176, 113, 256, 363, 151, 171, 82, 77
127  176, 113, 256, 363, 151, 171, 82, 77

    Genotype Average Depth of Coverage List             Date run
0         Ran on FASTA - No Coverage Report  2025-12-03_18-43-52
1         Ran on FASTA - No Coverage Report  2025-12-03_18-43-52
2         Ran on FASTA - No Coverage Report  2025-12-03_18-43-52
3         Ran on FASTA - No Coverage Report  2025-12-03_18-43-52
4         Ran on FASTA - No Coverage Report  2025-12-03_18-43-52
..                                      ...                  ...
123       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
124       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
125       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
126       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
127       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44

[128 rows x 40 columns]
        Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0      PQ051119.1        GenBank  GCA_040889855.1   SRR29455647  SAMN41892119
1      PQ051120.1        GenBank  GCA_040889855.1   SRR29455647  SAMN41892119
2      PQ051121.1        GenBank  GCA_040889855.1   SRR29455647  SAMN41892119
3      PQ051122.1        GenBank  GCA_040889855.1   SRR29455647  SAMN41892119
4      PQ051123.1        GenBank  GCA_040889855.1   SRR29455647  SAMN41892119
...           ...            ...              ...           ...           ...
81283  PZ422028.1        GenBank  GCA_057730505.1   SRR38140017  SAMN57311643
81284  PZ422029.1        GenBank  GCA_057730505.1   SRR38140017  SAMN57311643
81285  PZ422030.1        GenBank  GCA_057730505.1   SRR38140017  SAMN57311643
81286  PP756066.1        GenBank  GCA_039464865.1   SRR28834851  SAMN41100354
81287  PP756068.1        GenBank  GCA_039464865.1   SRR28834851  SAMN41100354

         BioProject      Organism_Name                         Species  \
0      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
1      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
2      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
4      PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
...             ...                ...                             ...
81283  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
81284  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
81285  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
81286  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81287  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                     Genus            Family  ... Date run     _merge  \
0      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
1      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
2      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4      Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
...                    ...               ...  ...      ...        ...
81283  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81284  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81285  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81286  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
81287  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only

                      date       File Name  \
0      2025-05-09_10-48-03  SRR29455647.fa
1      2025-05-09_10-48-03  SRR29455647.fa
2      2025-05-09_10-48-03  SRR29455647.fa
3      2025-05-09_10-48-03  SRR29455647.fa
4      2025-05-09_10-48-03  SRR29455647.fa
...                    ...             ...
81283  2026-04-18_06-41-27  SRR38140017.fa
81284  2026-04-18_06-41-27  SRR38140017.fa
81285  2026-04-18_06-41-27  SRR38140017.fa
81286  2025-05-09_10-47-27  SRR28834851.fa
81287  2025-05-09_10-47-27  SRR28834851.fa

                                  Genotype  \
0                                    B3.13
1                                    B3.13
2                                    B3.13
3                                    B3.13
4                                    B3.13
...                                    ...
81283                                 D1.8
81284                                 D1.8
81285                                 D1.8
81286  Not assigned: No Matching Genotypes
81287  Not assigned: No Matching Genotypes

                           Genotype List Used, >=98.0%_y  \
0      NS:am1.1, PB2:am2.2, PB1:am4, HA:ea1, PA:ea1, ...
1      NS:am1.1, PB2:am2.2, PB1:am4, HA:ea1, PA:ea1, ...
2      NS:am1.1, PB2:am2.2, PB1:am4, HA:ea1, PA:ea1, ...
3      NS:am1.1, PB2:am2.2, PB1:am4, HA:ea1, PA:ea1, ...
4      NS:am1.1, PB2:am2.2, PB1:am4, HA:ea1, PA:ea1, ...
...                                                  ...
81283  HA:ea3, NP:am1.1, NA:am4N1, PB1:ea3, PB2:am24,...
81284  HA:ea3, NP:am1.1, NA:am4N1, PB1:ea3, PB2:am24,...
81285  HA:ea3, NP:am1.1, NA:am4N1, PB1:ea3, PB2:am24,...
81286  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, MP:...
81287  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, MP:...

                            Genotype Sample Title List_y  \
0      am1.1:22-010085-001:NS, am2.2:22-010445-001:PB...
1      am1.1:22-010085-001:NS, am2.2:22-010445-001:PB...
2      am1.1:22-010085-001:NS, am2.2:22-010445-001:PB...
3      am1.1:22-010085-001:NS, am2.2:22-010445-001:PB...
4      am1.1:22-010085-001:NS, am2.2:22-010445-001:PB...
...                                                  ...
81283  ea3:22-013001-001:HA, am1.1:22-007805-001:NP, ...
81284  ea3:22-013001-001:HA, am1.1:22-007805-001:NP, ...
81285  ea3:22-013001-001:HA, am1.1:22-007805-001:NP, ...
81286  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...
81287  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...

                           Genotype Percent Match List_y  \
0      99.17%, 98.82%, 99.56%, 98.71%, 99.16%, 98.88%...
1      99.17%, 98.82%, 99.56%, 98.71%, 99.16%, 98.88%...
2      99.17%, 98.82%, 99.56%, 98.71%, 99.16%, 98.88%...
3      99.17%, 98.82%, 99.56%, 98.71%, 99.16%, 98.88%...
4      99.17%, 98.82%, 99.56%, 98.71%, 99.16%, 98.88%...
...                                                  ...
81283  99.00%, 98.86%, 98.56%, 99.03%, 99.34%, 98.81%...
81284  99.00%, 98.86%, 98.56%, 99.03%, 99.34%, 98.81%...
81285  99.00%, 98.86%, 98.56%, 99.03%, 99.34%, 98.81%...
81286  99.55%, 99.22%, 98.94%, 98.63%, 99.28%, 98.78%...
81287  99.55%, 99.22%, 98.94%, 98.63%, 99.28%, 98.78%...


### Create FASTA files of unknown genotypes

In [58]:
metadata_segments_known

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Genotype Average Depth of Coverage List_x,_merge,date,File Name,Genotype,"Genotype List Used, >=98.0%_y",Genotype Sample Title List_y,Genotype Percent Match List_y,Genotype Mismatch List_y,Genotype Average Depth of Coverage List_y
0,OK205488.1,GenBank,GCA_039015945.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,OK205489.1,GenBank,GCA_039015945.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,OK205490.1,GenBank,GCA_039015945.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,OK205491.1,GenBank,GCA_039015945.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,OK205492.1,GenBank,GCA_039015945.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81283,PZ422028.1,GenBank,GCA_057730505.1,SRR38140017,SAMN57311643,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2026-04-18_06-41-27,SRR38140017.fa,D1.8,"HA:ea3, NP:am1.1, NA:am4N1, PB1:ea3, PB2:am24,...","ea3:22-013001-001:HA, am1.1:22-007805-001:NP, ...","99.00%, 98.86%, 98.56%, 99.03%, 99.34%, 98.81%...","17, 17, 15, 22, 15, 10, 4, 18",Ran on FASTA - No Coverage Report
81284,PZ422029.1,GenBank,GCA_057730505.1,SRR38140017,SAMN57311643,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2026-04-18_06-41-27,SRR38140017.fa,D1.8,"HA:ea3, NP:am1.1, NA:am4N1, PB1:ea3, PB2:am24,...","ea3:22-013001-001:HA, am1.1:22-007805-001:NP, ...","99.00%, 98.86%, 98.56%, 99.03%, 99.34%, 98.81%...","17, 17, 15, 22, 15, 10, 4, 18",Ran on FASTA - No Coverage Report
81285,PZ422030.1,GenBank,GCA_057730505.1,SRR38140017,SAMN57311643,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2026-04-18_06-41-27,SRR38140017.fa,D1.8,"HA:ea3, NP:am1.1, NA:am4N1, PB1:ea3, PB2:am24,...","ea3:22-013001-001:HA, am1.1:22-007805-001:NP, ...","99.00%, 98.86%, 98.56%, 99.03%, 99.34%, 98.81%...","17, 17, 15, 22, 15, 10, 4, 18",Ran on FASTA - No Coverage Report
81286,PP756066.1,GenBank,GCA_039464865.1,SRR28834851,SAMN41100354,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2025-05-09_10-47-27,SRR28834851.fa,Not assigned: No Matching Genotypes,"PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, MP:...","am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...","99.55%, 99.22%, 98.94%, 98.63%, 99.28%, 98.78%...","4, 2, 15, 16, 6, 12, 2, 9",Ran on FASTA - No Coverage Report
81287,PP756068.1,GenBank,GCA_039464865.1,SRR28834851,SAMN41100354,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2025-05-09_10-47-27,SRR28834851.fa,Not assigned: No Matching Genotypes,"PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, MP:...","am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...","99.55%, 99.22%, 98.94%, 98.63%, 99.28%, 98.78%...","4, 2, 15, 16, 6, 12, 2, 9",Ran on FASTA - No Coverage Report

In [62]:
# Create 8 fasta files per segment

# Get all the segments
metadata_segments_new["Partial_Header"] = metadata_segments_new["Assembly"].apply(lambda x: ">" + x if x == x else x) # .apply(lambda x: x.split("|")[-1].split(")")[0]) # Get only genbank name
metadata_segments_new = metadata_segments_new.dropna(subset="Partial_Header")

print(metadata_segments_new["Partial_Header"].values[0:5])

['>GCA_038185045.1' '>GCA_038185045.1' '>GCA_038185045.1'
 '>GCA_038185045.1' '>GCA_038185045.1']

In [ ]:


# Create list of dataframes
df_list = []
for partial_header in list(set(metadata_segments_new["Partial_Header"].values)): # Unique partial headers only
    # Get smaller dataframe
    df = metadata_segments_new[metadata_segments_new["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    # Make sure there are 8 segments
    if len(df) == 8:
        # Forbidden characters in headers
        for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]:
            df["Partial_Header"] = df["Partial_Header"].apply(lambda x: x.replace(c, "_"))
            
        df["full_header"] = df["Partial_Header"]
        df_list.append(df)

print(metadata_segments_new["Partial_Header"])

print(df_list[0]["full_header"].values[:10])

# Make fasta files
for df in df_list:
    segments = list(set(df["Segment"].apply(lambda x: int(x)).values))
    for segment in segments:
        one_row = df[df["Segment"] == segment]
        df_to_fasta(one_row, str(segment) + "_seg.fasta", temp_files)

['>GCA_038185045.1' '>GCA_038185045.1' '>GCA_038185045.1'
 '>GCA_038185045.1' '>GCA_038185045.1']

KeyboardInterrupt:

### Re-Labeling Using GenoFlu

**STOP HERE AND USE GENOFLU TO FIND NEW GENOTYPES.** Then, make sure "results.tsv" is in the NCBI_Virus downloads directory. <br>

To activate genoflu conda environment in BioWulf:
```
source myconda
conda activate genoflu
```

To run GenoFLU-multi, change directories to Multi-GenoFLU directory:
``` 
cd GenoFLU-multi
```

And then call the python script:

``` 
python bin/genoflu-multi.py -f <FASTA_directory>
```

In [ ]:
# Ensure that user does the above
input("Use genoflu. Afterwards, press ENTER to continue.")

''

In [63]:
# Merging

os.chdir(downloads_saved)

# Read in genoflu results
output_genoflu = pd.read_csv("results.tsv", delimiter="\t") # This also shows the IDs of the new sequences -- incorporate into sequences report

# Create partial headers to merge genoflu results with previously unknown segments
metadata_segments_new["Partial_Header_Merge"] = metadata_segments_new["Assembly"] 
for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]: # Forbidden punctuation
    metadata_segments_new["Partial_Header_Merge"] = metadata_segments_new["Partial_Header_Merge"].apply(lambda x: x.replace(c, "_") if x==x else x)

# Reformat so we can merge
output_genoflu["Partial_Header_Merge"] = output_genoflu["Strain"] #.apply(lambda x: re.split(r'Influenza_A_virus__\D*__\D*_', x)[-1])
# output_genoflu["Partial_Header_Merge"] = output_genoflu["Partial_Header_Merge"].apply(lambda x: re.split(r'_H.N._(20|19).{2}_.{2}_.{2}', x)[0])

# Merge
metadata_genoflu = metadata_segments_new.merge(output_genoflu, how="inner", on="Partial_Header_Merge") #, suffixes=('_left', '_right')) 

# Fill the rest of the 8 segments with the same genotype
metadata_genoflu = metadata_genoflu.ffill(limit_area="inside", limit=7)



print(metadata_genoflu)

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\2\ipykernel_26996\2649279360.py:21: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  metadata_genoflu = metadata_genoflu.ffill(limit_area="inside", limit=7)

         Accession GenBank_RefSeq         Assembly SRA_Accession  \
0       PQ051119.1        GenBank  GCA_040889855.1   SRR29455647
1       PQ051120.1        GenBank  GCA_040889855.1   SRR29455647
2       PQ051121.1        GenBank  GCA_040889855.1   SRR29455647
3       PQ051122.1        GenBank  GCA_040889855.1   SRR29455647
4       PQ051123.1        GenBank  GCA_040889855.1   SRR29455647
...            ...            ...              ...           ...
104123  PP761582.1        GenBank  GCA_040104305.1           NaN
104124  PP761583.1        GenBank  GCA_040104305.1           NaN
104125  PP761584.1        GenBank  GCA_040104305.1           NaN
104126  PP761585.1        GenBank  GCA_040104305.1           NaN
104127  PP761586.1        GenBank  GCA_040104305.1           NaN

           BioSample    BioProject      Organism_Name  \
0       SAMN41892119  PRJNA1102327  Influenza A virus
1       SAMN41892119  PRJNA1102327  Influenza A virus
2       SAMN41892119  PRJNA1102327  Influenza A virus
3       SAMN41892119  PRJNA1102327  Influenza A virus
4       SAMN41892119  PRJNA1102327  Influenza A virus
...              ...           ...                ...
104123           NaN   PRJNA885497  Influenza A virus
104124           NaN   PRJNA885497  Influenza A virus
104125           NaN   PRJNA885497  Influenza A virus
104126           NaN   PRJNA885497  Influenza A virus
104127           NaN   PRJNA885497  Influenza A virus

                               Species                Genus            Family  \
0       Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
1       Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
2       Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
3       Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
4       Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
...                                ...                  ...               ...
104123  Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
104124  Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
104125  Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
104126  Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
104127  Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae

        ... Partial_Header_Merge    Partial_Header         Strain_y Genotype  \
0       ...      GCA_040889855_1  >GCA_040889855.1  GCA_040889855_1    B3.13
1       ...      GCA_040889855_1  >GCA_040889855.1  GCA_040889855_1    B3.13
2       ...      GCA_040889855_1  >GCA_040889855.1  GCA_040889855_1    B3.13
3       ...      GCA_040889855_1  >GCA_040889855.1  GCA_040889855_1    B3.13
4       ...      GCA_040889855_1  >GCA_040889855.1  GCA_040889855_1    B3.13
...     ...                  ...               ...              ...      ...
104123  ...      GCA_040104305_1  >GCA_040104305.1  GCA_040104305_1     C2.1
104124  ...      GCA_040104305_1  >GCA_040104305.1  GCA_040104305_1     C2.1
104125  ...      GCA_040104305_1  >GCA_040104305.1  GCA_040104305_1     C2.1
104126  ...      GCA_040104305_1  >GCA_040104305.1  GCA_040104305_1     C2.1
104127  ...      GCA_040104305_1  >GCA_040104305.1  GCA_040104305_1     C2.1

                            Genotype List Used, >=98.0%_y  \
0       PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
1       PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
2       PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3       PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
4       PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
...                                                   ...
104123  PB2:am19, PB1:am20, PA:am3, HA:ea2, NP:ea1, NA...
104124  PB2:am19, PB1:am20, PA:am3, HA:ea2, NP:ea1, NA...
104125  PB2:am19, PB1:am20, PA:am3, HA:ea2, NP:ea1, NA...
104126  PB2:am19, PB1:am20, PA:am3, HA:ea2, NP:ea1, NA...
104127  PB2:am19, PB1:am20, PA:am3, HA:ea2, NP:ea1, NA...

                             Genotype Sample Title List_y  \
0       am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
1       am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
2       am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3       am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
4       am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
...                                                   ...
104123  am19:23-036193-005:PB2, am20:23-036657-001:PB1...
104124  am19:23-036193-005:PB2, am20:23-036657-001:PB1...
104125  am19:23-036193-005:PB2, am20:23-036657-001:PB1...
104126  am19:23-036193-005:PB2, am20:23-036657-001:PB1...
104127  am19:23-036193-005:PB2, am20:23-036657-001:PB1...

                            Genotype Percent Match List_y  \
0       98.82%, 99.56%, 99.16%, 98.71%, 99.20%, 98.86%...
1       98.82%, 99.56%, 99.16%, 98.71%, 99.20%, 98.86%...
2       98.82%, 99.56%, 99.16%, 98.71%, 99.20%, 98.86%...
3       98.82%, 99.56%, 99.16%, 98.71%, 99.20%, 98.86%...
4       98.82%, 99.56%, 99.16%, 98.71%, 99.20%, 98.86%...
...                                                   ...
104123  99.83%, 99.65%, 99.40%, 99.88%, 99.67%, 99.72%...
104124  99.83%, 99.65%, 99.40%, 99.88%, 99.67%, 99.72%...
104125  99.83%, 99.65%, 99.40%, 99.88%, 99.67%, 99.72%...
104126  99.83%, 99.65%, 99.40%, 99.88%, 99.67%, 99.72%...
104127  99.83%, 99.65%, 99.40%, 99.88%, 99.67%, 99.72%...

             Genotype Mismatch List_y  \
0       27, 10, 18, 22, 12, 16, 11, 6
1       27, 10, 18, 22, 12, 16, 11, 6
2       27, 10, 18, 22, 12, 16, 11, 6
3       27, 10, 18, 22, 12, 16, 11, 6
4       27, 10, 18, 22, 12, 16, 11, 6
...                               ...
104123        4, 8, 13, 2, 5, 4, 5, 8
104124        4, 8, 13, 2, 5, 4, 5, 8
104125        4, 8, 13, 2, 5, 4, 5, 8
104126        4, 8, 13, 2, 5, 4, 5, 8
104127        4, 8, 13, 2, 5, 4, 5, 8

       Genotype Average Depth of Coverage List_y           Date run_y
0              Ran on FASTA - No Coverage Report  2026-06-10_12-23-56
1              Ran on FASTA - No Coverage Report  2026-06-10_12-23-56
2              Ran on FASTA - No Coverage Report  2026-06-10_12-23-56
3              Ran on FASTA - No Coverage Report  2026-06-10_12-23-56
4              Ran on FASTA - No Coverage Report  2026-06-10_12-23-56
...                                          ...                  ...
104123         Ran on FASTA - No Coverage Report  2026-06-10_12-23-04
104124         Ran on FASTA - No Coverage Report  2026-06-10_12-23-04
104125         Ran on FASTA - No Coverage Report  2026-06-10_12-23-04
104126         Ran on FASTA - No Coverage Report  2026-06-10_12-23-04
104127         Ran on FASTA - No Coverage Report  2026-06-10_12-23-04

[104128 rows x 51 columns]

### Concatenate with known genotypes

In [64]:
# Rename columns so we can concatenate
print(metadata_segments_known.columns)

metadata_segments_known = metadata_segments_known.reset_index(drop=True)
print(metadata_segments_known)

print(metadata_genoflu.columns)
metadata_segments_known["Genotype_official"] = metadata_segments_known["Genotype_y"]
metadata_segments_known["Serotype"] = metadata_segments_known["Genotype_x"]
metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype"]
metadata_genoflu["Serotype"] = metadata_genoflu["Genotype_x"]

metadata_genoflu = metadata_genoflu.reset_index(drop=True)
print(metadata_genoflu)

# Concatenation
metadata_genoflu_concat = pd.concat([metadata_segments_known, metadata_genoflu])

metadata_genoflu_concat

Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Partial_Header_temp', 'Strain',
       'Genotype_y', 'Genotype List Used, >=98.0%',
       'Genotype Sample Title List', 'Genotype Percent Match List',
       'Genotype Mismatch List', 'Genotype Average Depth of Coverage List',
       'Date run', 'Genotype List Used, >=98.0%_x',
       'Genotype Sample Title List_x', 'Genotype Percent Match List_x',
       'Genotype Mismatch List_x', 'Genotype Average Depth of Coverage List_x',
       '_merge', 'date', 'File Name', 'Genotype',
       'Genotype List Used, >=98.0%_y', 'Genotype Sample Title List_y',
       'Genotype Percent Match List_y', 'Genotype Mismatch List_y',
       'Genotype Average Depth of Coverage List_y', 'Genotype_official',
       'Serotype'],
      dtype='object')
        Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0      OK205488.1        GenBank  GCA_039015945.1           NaN           NaN
1      OK205489.1        GenBank  GCA_039015945.1           NaN           NaN
2      OK205490.1        GenBank  GCA_039015945.1           NaN           NaN
3      OK205491.1        GenBank  GCA_039015945.1           NaN           NaN
4      OK205492.1        GenBank  GCA_039015945.1           NaN           NaN
...           ...            ...              ...           ...           ...
81411  PZ422028.1        GenBank  GCA_057730505.1   SRR38140017  SAMN57311643
81412  PZ422029.1        GenBank  GCA_057730505.1   SRR38140017  SAMN57311643
81413  PZ422030.1        GenBank  GCA_057730505.1   SRR38140017  SAMN57311643
81414  PP756066.1        GenBank  GCA_039464865.1   SRR28834851  SAMN41100354
81415  PP756068.1        GenBank  GCA_039464865.1   SRR28834851  SAMN41100354

         BioProject      Organism_Name                         Species  \
0               NaN  Influenza A virus  Alphainfluenzavirus influenzae
1               NaN  Influenza A virus  Alphainfluenzavirus influenzae
2               NaN  Influenza A virus  Alphainfluenzavirus influenzae
3               NaN  Influenza A virus  Alphainfluenzavirus influenzae
4               NaN  Influenza A virus  Alphainfluenzavirus influenzae
...             ...                ...                             ...
81411  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
81412  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
81413  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
81414  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
81415  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                     Genus            Family  ...                 date  \
0      Alphainfluenzavirus  Orthomyxoviridae  ...                  NaN
1      Alphainfluenzavirus  Orthomyxoviridae  ...                  NaN
2      Alphainfluenzavirus  Orthomyxoviridae  ...                  NaN
3      Alphainfluenzavirus  Orthomyxoviridae  ...                  NaN
4      Alphainfluenzavirus  Orthomyxoviridae  ...                  NaN
...                    ...               ...  ...                  ...
81411  Alphainfluenzavirus  Orthomyxoviridae  ...  2026-04-18_06-41-27
81412  Alphainfluenzavirus  Orthomyxoviridae  ...  2026-04-18_06-41-27
81413  Alphainfluenzavirus  Orthomyxoviridae  ...  2026-04-18_06-41-27
81414  Alphainfluenzavirus  Orthomyxoviridae  ...  2025-05-09_10-47-27
81415  Alphainfluenzavirus  Orthomyxoviridae  ...  2025-05-09_10-47-27

            File Name                             Genotype  \
0                 NaN                                  NaN
1                 NaN                                  NaN
2                 NaN                                  NaN
3                 NaN                                  NaN
4                 NaN                                  NaN
...               ...                                  ...
81411  SRR38140017.fa                                 D1.8
81412  SRR38140017.fa                                 D1.8
81413  SRR38140017.fa                                 D1.8
81414  SRR28834851.fa  Not assigned: No Matching Genotypes
81415  SRR28834851.fa  Not assigned: No Matching Genotypes

                           Genotype List Used, >=98.0%_y  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
81411  HA:ea3, NP:am1.1, NA:am4N1, PB1:ea3, PB2:am24,...
81412  HA:ea3, NP:am1.1, NA:am4N1, PB1:ea3, PB2:am24,...
81413  HA:ea3, NP:am1.1, NA:am4N1, PB1:ea3, PB2:am24,...
81414  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, MP:...
81415  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, MP:...

                            Genotype Sample Title List_y  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
81411  ea3:22-013001-001:HA, am1.1:22-007805-001:NP, ...
81412  ea3:22-013001-001:HA, am1.1:22-007805-001:NP, ...
81413  ea3:22-013001-001:HA, am1.1:22-007805-001:NP, ...
81414  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...
81415  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...

                           Genotype Percent Match List_y  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
81411  99.00%, 98.86%, 98.56%, 99.03%, 99.34%, 98.81%...
81412  99.00%, 98.86%, 98.56%, 99.03%, 99.34%, 98.81%...
81413  99.00%, 98.86%, 98.56%, 99.03%, 99.34%, 98.81%...
81414  99.55%, 99.22%, 98.94%, 98.63%, 99.28%, 98.78%...
81415  99.55%, 99.22%, 98.94%, 98.63%, 99.28%, 98.78%...

            Genotype Mismatch List_y  \
0                                NaN
1                                NaN
2                                NaN
3                                NaN
4                                NaN
...                              ...
81411  17, 17, 15, 22, 15, 10, 4, 18
81412  17, 17, 15, 22, 15, 10, 4, 18
81413  17, 17, 15, 22, 15, 10, 4, 18
81414      4, 2, 15, 16, 6, 12, 2, 9
81415      4, 2, 15, 16, 6, 12, 2, 9

      Genotype Average Depth of Coverage List_y  \
0                                           NaN
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN
...                                         ...
81411         Ran on FASTA - No Coverage Report
81412         Ran on FASTA - No Coverage Report
81413         Ran on FASTA - No Coverage Report
81414         Ran on FASTA - No Coverage Report
81415         Ran on FASTA - No Coverage Report

                                       Genotype_official Serotype
0      Not assigned: Only 0 segments >98.0% match fou...     H5N2
1      Not assigned: Only 0 segments >98.0% match fou...     H5N2
2      Not assigned: Only 0 segments >98.0% match fou...     H5N2
3      Not assigned: Only 0 segments >98.0% match fou...     H5N2
4      Not assigned: Only 0 segments >98.0% match fou...     H5N2
...                                                  ...      ...
81411                                               D1.8     H5N1
81412                                               D1.8     H5N1
81413                                               D1.8     H5N1
81414                Not assigned: No Matching Genotypes     H5N1
81415                Not assigned: No Matching Genotypes     H5N1

[81416 rows x 56 columns]
Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Partial_Header_temp', 'Strain_x',
       'Genotype_y', 'Genotype List Used, >=98.0%_x',
       'Genotype Sample Title List_x', 'Genotype Percent Match List_x',
       'Genotype Mismatch List_x', 'Genotype Average Depth of Coverage List_x',
       'Date run_x', '_merge', 'Partial_Header_Merge', 'Partial_Header',
       'Strain_y', 'Genotype', 'Genotype List Used, >=98.0%_y',
       'Genotype Sample Title List_y', 'Genotype Percent Match List_y',
       'Genotype Mismatch List_y', 'Genotype Average Depth of Coverage List_y',
       'Date run_y'],
      dtype='object')
         Accession GenBank_RefSeq         Assembly SRA_Accession  \
0       PQ051119.1        GenBank  GCA_040889855.1   SRR29455647
1       PQ051120.1        GenBank  GCA_040889855.1   SRR29455647
2       PQ051121.1        GenBank  GCA_040889855.1   SRR29455647
3       PQ051122.1        GenBank  GCA_040889855.1   SRR29455647
4       PQ051123.1        GenBank  GCA_040889855.1   SRR29455647
...            ...            ...              ...           ...
104123  PP761582.1        GenBank  GCA_040104305.1           NaN
104124  PP761583.1        GenBank  GCA_040104305.1           NaN
104125  PP761584.1        GenBank  GCA_040104305.1           NaN
104126  PP761585.1        GenBank  GCA_040104305.1           NaN
104127  PP761586.1        GenBank  GCA_040104305.1           NaN

           BioSample    BioProject      Organism_Name  \
0       SAMN41892119  PRJNA1102327  Influenza A virus
1       SAMN41892119  PRJNA1102327  Influenza A virus
2       SAMN41892119  PRJNA1102327  Influenza A virus
3       SAMN41892119  PRJNA1102327  Influenza A virus
4       SAMN41892119  PRJNA1102327  Influenza A virus
...              ...           ...                ...
104123           NaN   PRJNA885497  Influenza A virus
104124           NaN   PRJNA885497  Influenza A virus
104125           NaN   PRJNA885497  Influenza A virus
104126           NaN   PRJNA885497  Influenza A virus
104127           NaN   PRJNA885497  Influenza A virus

                               Species                Genus            Family  \
0       Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
1       Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
2       Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
3       Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
4       Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
...                                ...                  ...               ...
104123  Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
104124  Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
104125  Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
104126  Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae
104127  Alphainfluenzavirus influenzae  Alphainfluenzavirus  Orthomyxoviridae

        ...         Strain_y Genotype  \
0       ...  GCA_040889855_1    B3.13
1       ...  GCA_040889855_1    B3.13
2       ...  GCA_040889855_1    B3.13
3       ...  GCA_040889855_1    B3.13
4       ...  GCA_040889855_1    B3.13
...     ...              ...      ...
104123  ...  GCA_040104305_1     C2.1
104124  ...  GCA_040104305_1     C2.1
104125  ...  GCA_040104305_1     C2.1
104126  ...  GCA_040104305_1     C2.1
104127  ...  GCA_040104305_1     C2.1

                            Genotype List Used, >=98.0%_y  \
0       PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
1       PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
2       PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3       PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
4       PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
...                                                   ...
104123  PB2:am19, PB1:am20, PA:am3, HA:ea2, NP:ea1, NA...
104124  PB2:am19, PB1:am20, PA:am3, HA:ea2, NP:ea1, NA...
104125  PB2:am19, PB1:am20, PA:am3, HA:ea2, NP:ea1, NA...
104126  PB2:am19, PB1:am20, PA:am3, HA:ea2, NP:ea1, NA...
104127  PB2:am19, PB1:am20, PA:am3, HA:ea2, NP:ea1, NA...

                             Genotype Sample Title List_y  \
0       am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
1       am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
2       am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3       am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
4       am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
...                                                   ...
104123  am19:23-036193-005:PB2, am20:23-036657-001:PB1...
104124  am19:23-036193-005:PB2, am20:23-036657-001:PB1...
104125  am19:23-036193-005:PB2, am20:23-036657-001:PB1...
104126  am19:23-036193-005:PB2, am20:23-036657-001:PB1...
104127  am19:23-036193-005:PB2, am20:23-036657-001:PB1...

                            Genotype Percent Match List_y  \
0       98.82%, 99.56%, 99.16%, 98.71%, 99.20%, 98.86%...
1       98.82%, 99.56%, 99.16%, 98.71%, 99.20%, 98.86%...
2       98.82%, 99.56%, 99.16%, 98.71%, 99.20%, 98.86%...
3       98.82%, 99.56%, 99.16%, 98.71%, 99.20%, 98.86%...
4       98.82%, 99.56%, 99.16%, 98.71%, 99.20%, 98.86%...
...                                                   ...
104123  99.83%, 99.65%, 99.40%, 99.88%, 99.67%, 99.72%...
104124  99.83%, 99.65%, 99.40%, 99.88%, 99.67%, 99.72%...
104125  99.83%, 99.65%, 99.40%, 99.88%, 99.67%, 99.72%...
104126  99.83%, 99.65%, 99.40%, 99.88%, 99.67%, 99.72%...
104127  99.83%, 99.65%, 99.40%, 99.88%, 99.67%, 99.72%...

             Genotype Mismatch List_y  \
0       27, 10, 18, 22, 12, 16, 11, 6
1       27, 10, 18, 22, 12, 16, 11, 6
2       27, 10, 18, 22, 12, 16, 11, 6
3       27, 10, 18, 22, 12, 16, 11, 6
4       27, 10, 18, 22, 12, 16, 11, 6
...                               ...
104123        4, 8, 13, 2, 5, 4, 5, 8
104124        4, 8, 13, 2, 5, 4, 5, 8
104125        4, 8, 13, 2, 5, 4, 5, 8
104126        4, 8, 13, 2, 5, 4, 5, 8
104127        4, 8, 13, 2, 5, 4, 5, 8

       Genotype Average Depth of Coverage List_y           Date run_y  \
0              Ran on FASTA - No Coverage Report  2026-06-10_12-23-56
1              Ran on FASTA - No Coverage Report  2026-06-10_12-23-56
2              Ran on FASTA - No Coverage Report  2026-06-10_12-23-56
3              Ran on FASTA - No Coverage Report  2026-06-10_12-23-56
4              Ran on FASTA - No Coverage Report  2026-06-10_12-23-56
...                                          ...                  ...
104123         Ran on FASTA - No Coverage Report  2026-06-10_12-23-04
104124         Ran on FASTA - No Coverage Report  2026-06-10_12-23-04
104125         Ran on FASTA - No Coverage Report  2026-06-10_12-23-04
104126         Ran on FASTA - No Coverage Report  2026-06-10_12-23-04
104127         Ran on FASTA - No Coverage Report  2026-06-10_12-23-04

       Genotype_official Serotype
0                  B3.13     H5N1
1                  B3.13     H5N1
2                  B3.13     H5N1
3                  B3.13     H5N1
4                  B3.13     H5N1
...                  ...      ...
104123              C2.1     H5N1
104124              C2.1     H5N1
104125              C2.1     H5N1
104126              C2.1     H5N1
104127              C2.1     H5N1

[104128 rows x 53 columns]

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Genotype Mismatch List_y,Genotype Average Depth of Coverage List_y,Genotype_official,Serotype,Strain_x,Date run_x,Partial_Header_Merge,Partial_Header,Strain_y,Date run_y
0,OK205488.1,GenBank,GCA_039015945.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2,NaN,NaN,NaN,NaN,NaN,NaN
1,OK205489.1,GenBank,GCA_039015945.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2,NaN,NaN,NaN,NaN,NaN,NaN
2,OK205490.1,GenBank,GCA_039015945.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2,NaN,NaN,NaN,NaN,NaN,NaN
3,OK205491.1,GenBank,GCA_039015945.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2,NaN,NaN,NaN,NaN,NaN,NaN
4,OK205492.1,GenBank,GCA_039015945.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104123,PP761582.1,GenBank,GCA_040104305.1,NaN,NaN,PRJNA885497,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"4, 8, 13, 2, 5, 4, 5, 8",Ran on FASTA - No Coverage Report,C2.1,H5N1,NaN,NaN,GCA_040104305_1,>GCA_040104305.1,GCA_040104305_1,2026-06-10_12-23-04
104124,PP761583.1,GenBank,GCA_040104305.1,NaN,NaN,PRJNA885497,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"4, 8, 13, 2, 5, 4, 5, 8",Ran on FASTA - No Coverage Report,C2.1,H5N1,NaN,NaN,GCA_040104305_1,>GCA_040104305.1,GCA_040104305_1,2026-06-10_12-23-04
104125,PP761584.1,GenBank,GCA_040104305.1,NaN,NaN,PRJNA885497,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"4, 8, 13, 2, 5, 4, 5, 8",Ran on FASTA - No Coverage Report,C2.1,H5N1,NaN,NaN,GCA_040104305_1,>GCA_040104305.1,GCA_040104305_1,2026-06-10_12-23-04
104126,PP761585.1,GenBank,GCA_040104305.1,NaN,NaN,PRJNA885497,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"4, 8, 13, 2, 5, 4, 5, 8",Ran on FASTA - No Coverage Report,C2.1,H5N1,NaN,NaN,GCA_040104305_1,>GCA_040104305.1,GCA_040104305_1,2026-06-10_12-23-04
104127,PP761586.1,GenBank,GCA_040104305.1,NaN,NaN,PRJNA885497,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"4, 8, 13, 2, 5, 4, 5, 8",Ran on FASTA - No Coverage Report,C2.1,H5N1,NaN,NaN,GCA_040104305_1,>GCA_040104305.1,GCA_040104305_1,2026-06-10_12-23-04

In [65]:
# Cut down to only columns we want
metadata_genoflu_concat = metadata_genoflu_concat[["Accession", "Assembly", "GenBank_Title", "Host", "Collection_Date", "SRA_Accession", "Isolate", "Genotype_official", "Geo_Location", "full_header", "sequence", "Serotype", "Segment", "File Name", "Partial_Header"]] #, "Strain"]]

# Get genbank strain name
metadata_genoflu_concat["genbank_name"] = metadata_genoflu_concat["GenBank_Title"].apply(lambda x: x.split("(")[1] if x == x else x)
metadata_genoflu_concat["Host"] = metadata_genoflu_concat["genbank_name"].apply(lambda x: x.split("/")[1] if x == x else x)

metadata_genoflu_concat = metadata_genoflu_concat.dropna(subset="genbank_name") # [metadata_genoflu["Genotype"]  == "B3.13"]

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\2\ipykernel_26996\4267596827.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata_genoflu_concat["genbank_name"] = metadata_genoflu_concat["GenBank_Title"].apply(lambda x: x.split("(")[1] if x == x else x)
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\2\ipykernel_26996\4267596827.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata_genoflu_concat["Host"] = metadata_genoflu_concat["genbank_name"].apply(lambda x: x.split("/")[1] if x == x else x)

In [66]:
metadata_genoflu_concat

# Make sure we only have the serotype(s) we want
for serotype in serotypes:
    metadata_genoflu = metadata_genoflu[metadata_genoflu["Serotype"] == serotype]

## Relabeling Sequences

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

In [67]:
# Re-re-name so that we don't break following code

metadata_genoflu = metadata_genoflu_concat

After running the below code, **STOP TO CHECK** if any new animals appear

In [68]:
# Animals 

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genoflu)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['great-tailed grackle', 'american wigeon', 'vulture', 'black swan', 'great egret', 'skunk', 'fregata magnificens', 'brown skua', 'common grackle', 'turkey vulture', 'harbor seal', 'emu', 'sanderling', 'chicken', 'black scoter', 'northern gannet', 'flamingo', 'guinea fowl', 'pintail duck', 'tundra swan', 'osprey', 'goose', 'common rhea', 'common eiders', 'franklin gull', 'guanay cormorant', 'greater white-fronted goose', 'brown pelican', 'chukar partridge', 'dunlin', 'american green-winged teal', 'falcon', 'herring gull', 'procellaria aequinoctialis', 'silver pheasant', 'bluebird', 'michigan', 'great blue heron', 'california', 'ohio', 'dendrocygna viduata', 'bos taurus', 'horned grebe', 'snow goose', 'snowy owl', 'gadwell', 'western sandpiper', 'long-eared owl', 'arctic tern', 'blue jay', 'thalasseus maximus', 'waterfowl', 'american robin', 'bluejay', 'ermine', 'serval', 'red fox', 'mute swan', 'south polar skua', 'cattle', 'buteogallus urubitinga', 'common eider', 'black turnstone', 'mink', 'red knot', 'northern shoveler', 'hermit thrush', 'rock pigeon', 'white-winged dove', 'lesser white-fronted goose', 'owl', 'swan', 'green-winged teal', 'poultry', 'goat', 'gadwall duck', 'brown-hooded gull', 'mountain lion', 'gallus gallus', 'pintail', 'chinese goose', 'ring-necked pheasant', 'dolphin', 'eurasian collared dove', 'bald eagle', 'mallard duck', 'whooper swan', 'lesser black-backed gull', 'red-necked phalarope', 'south american tern', 'bird', 'band-tailed gull', 'whooping crane', 'european starling', 'caspian tern', 'lion', 'bufflehead', 'common loon', 'dairy cow', 'peregrine falcon', 'northern elephant seal', 'redhead duck', 'muscovy duck', 'antofagasta', 'great grabe', 'pekin duck', 'inca tern', 'partridge', 'ring-billed gull', 'cat', 'heron', 'eagle', 'hawk', 'humboldt penguin', 'white-faced ibis', 'crane', 'raccoon', 'pluvialis dominica', 'royal tern', 'house sparrow', 'striped skunk', 'hooded merganser', 'northern pintail', 'raven', 'black-crowned night-heron', 'sea otter', 'wild turkey', 'dove', 'glaucous gull', 'southern elephant seal', 'peruvean booby', 'polar bear', 'avian', 'bobcat', 'cinnamon teal', 'wyoming', 'black swift', 'golden eagle', 'gallus', 'black skimmer', 'house mouse', 'western grebe', 'green heron', 'emperor goose', 'sandhill crane', 'thalasseus acuflavidus', 'barn owl', 'wood duck', 'alpaca', 'otaria flavescens', 'peruvian pelican', 'pelican', 'sparrow', 'tiger', 'great black-backed gull', 'american coot', 'pheasant', 'bovine', 'kelp gull', 'red-tailed hawk', 'antarctic fur seal', 'bottlenose dolphin', 'chungungo', 'burrowing owl', 'sandwich tern', 'texas', 'red-shouldered hawk', 'ruddy turnstone', 'pigeon', 'chilean dolphin', 'nevada', 'quail', 'graylag goose', 'black vulture', 'short-eared owl', 'greater scaup', 'finch', 'peacock', 'willet', 'california condor', 'snowy plover', 'guineafowl', 'turkey', 'american black duck', 'american white pelican', 'american woodcock', 'ring-necked duck', 'wild duck', 'baikal teal', 'cygnus melancoryphus', 'feline', 'trumpeter swan', 'california gull', 'snowy egret', 'louisiana', 'fox', 'cormorant', 'washington', 'duck', 'great grebe', 'irere', 'common murre', 'fisher', 'elegant tern', 'grackle', 'fish crow', 'rock dove', 'blackbird', 'canada goose', 'great-horned owl', 'lesser scaup', 'peruvian booby', 'peafowl', 'glaucous-winged gull', 'white-winged scoter', 'black-necked stilt', 'broad-winged hawk', 'hooded merganser duck', 'black-legged kittiwake', 'gadwall', 'cackling goose', 'dromaius novaehollandiae', 'furnarius rufus', 'wild bird', 'parrot', 'buff-necked ibis', 'american crow', 'lynx', 'american widgeon', 'common raven', 'domestic cat', 'domestic turkey', 'teal', 'mergus', 'collared plover', 'crow', 'sula leucogaster', 'virginia opossum', 'colorado', 'south american sea lion', 'chimango caracara', 'numida meleagris', 'lesser snow goose', 'american pelican', 'redhead', 'black-necked swan', 'black-crowned night heron', 'cygnus atratus', 'pig', 'chiloe wigeon', 'magpie', 'ruddy duck', 'american kestrel', 'neotropic cormorant', 'domestic duck', 'coscoroba coscoroba', 'rough-legged hawk', 'crested caracara', 'double-crested cormorant', 'megascops choliba', 'mottled duck', 'penguin', 'blue-winged teal', 'common goldeneye', 'laughing gull', 'western gull', 'gull', 'sharp-shinned hawk', 'green winged teal', 'sterna hirundo', 'bear', 'common merganser', 'mallard', 'common tern', 'chukar', 'domestic goose', 'great horned owl', 'northern harrier', 'gray gull', 'swine', 'wild goose', 'norway rat']
[]
            wild_avian domestic_avian               cattle        feline  \
0     great_horned_owl       pheasant            dairy_cow           cat
1         common_raven         turkey               cattle  domestic_cat
2        cooper's_hawk        chicken  cattle milk product     feral_cat
3         coopers_hawk          goose          bovine_milk        feline
4              peafowl    guinea_fowl              bovine   domestic-cat
...                ...            ...                  ...           ...
1663               NaN            NaN                  NaN           NaN
1664               NaN            NaN                  NaN           NaN
1665               NaN            NaN                  NaN           NaN
1666               NaN            NaN                  NaN           NaN
1667               NaN            NaN                  NaN           NaN

       other_mammal               human         other      pet_food  new
0        deer mouse          washington         mixed      pet food  NaN
1       house_mouse              nevada   environment  raw pet food  NaN
2             skunk             wyoming  multispecies  raw_pet_food  NaN
3     striped_skunk          california       unknown      pet_food  NaN
4        norway rat            michigan             '           NaN  NaN
...             ...                 ...           ...           ...  ...
1663            NaN            florence           NaN           NaN  NaN
1664            NaN                 oms           NaN           NaN  NaN
1665            NaN  castilla-la_mancha           NaN           NaN  NaN
1666            NaN          guadeloupe           NaN           NaN  NaN
1667            NaN               opole           NaN           NaN  NaN

[1668 rows x 9 columns]

In [ ]:
input("Check animals output. Afterwards, press ENTER to continue.")

''

In [69]:
# Re-label sequences with no assigned genotype as "Unassigned"

metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype_official"].apply(lambda x: "Not" if "Not assigned" in str(x) else x) # Unassigned segments are labeled "Unassigned"
metadata_genoflu["Genotype"] = metadata_genoflu["Genotype_official"] # Rename column again to not break old code

In [70]:
metadata_genoflu

,Accession,Assembly,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype_official,Geo_Location,full_header,sequence,Serotype,Segment,File Name,Partial_Header,genbank_name,Genotype
0,OK205488.1,GCA_039015945.1,Influenza A virus (A/chicken/Jalisco/716-2/201...,chicken,2017-07-04,NaN,716-2,Not,Mexico: Jalisco,>OK205488.1 |Influenza A virus (A/chicken/Jali...,TCAAATATATTCAATATGGAGAGAATAAAAGAACTAAGAGATCTAA...,H5N2,1,NaN,NaN,A/chicken/Jalisco/716-2/2017,Not
1,OK205489.1,GCA_039015945.1,Influenza A virus (A/chicken/Jalisco/716-2/201...,chicken,2017-07-04,NaN,716-2,Not,Mexico: Jalisco,>OK205489.1 |Influenza A virus (A/chicken/Jali...,CAAACTATTTGAATGGATGTCAATCCGACTCTACTTTTCTTGAAAG...,H5N2,2,NaN,NaN,A/chicken/Jalisco/716-2/2017,Not
2,OK205490.1,GCA_039015945.1,Influenza A virus (A/chicken/Jalisco/716-2/201...,chicken,2017-07-04,NaN,716-2,Not,Mexico: Jalisco,>OK205490.1 |Influenza A virus (A/chicken/Jali...,GCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAGTGTTTCAA...,H5N2,3,NaN,NaN,A/chicken/Jalisco/716-2/2017,Not
3,OK205491.1,GCA_039015945.1,Influenza A virus (A/chicken/Jalisco/716-2/201...,chicken,2017-07-04,NaN,716-2,Not,Mexico: Jalisco,>OK205491.1 |Influenza A virus (A/chicken/Jali...,TTCAACTGTCAAAATGGAAAGGATAGTAATCGCCTTTGCAATAATC...,H5N2,4,NaN,NaN,A/chicken/Jalisco/716-2/2017,Not
4,OK205492.1,GCA_039015945.1,Influenza A virus (A/chicken/Jalisco/716-2/201...,chicken,2017-07-04,NaN,716-2,Not,Mexico: Jalisco,>OK205492.1 |Influenza A virus (A/chicken/Jali...,GTAGATAATCACTCACTGAGTGACATTTACATCATGGCGTCTCAAG...,H5N2,5,NaN,NaN,A/chicken/Jalisco/716-2/2017,Not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104123,PP761582.1,GCA_040104305.1,Influenza A virus (A/wood duck/South Carolina/...,wood duck,2023-12-20,NaN,A/wood duck/South Carolina/W24-007C/2023,C2.1,USA,>PP761582.1 |Influenza A virus (A/wood duck/So...,ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...,H5N1,6,NaN,>GCA_040104305.1,A/wood duck/South Carolina/W24-007C/2023,C2.1
104124,PP761583.1,GCA_040104305.1,Influenza A virus (A/wood duck/South Carolina/...,wood duck,2023-12-20,NaN,A/wood duck/South Carolina/W24-007C/2023,C2.1,USA,>PP761583.1 |Influenza A virus (A/wood duck/So...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...,H5N1,5,NaN,>GCA_040104305.1,A/wood duck/South Carolina/W24-007C/2023,C2.1
104125,PP761584.1,GCA_040104305.1,Influenza A virus (A/wood duck/South Carolina/...,wood duck,2023-12-20,NaN,A/wood duck/South Carolina/W24-007C/2023,C2.1,USA,>PP761584.1 |Influenza A virus (A/wood duck/So...,ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...,H5N1,4,NaN,>GCA_040104305.1,A/wood duck/South Carolina/W24-007C/2023,C2.1
104126,PP761585.1,GCA_040104305.1,Influenza A virus (A/wood duck/South Carolina/...,wood duck,2023-12-20,NaN,A/wood duck/South Carolina/W24-007C/2023,C2.1,USA,>PP761585.1 |Influenza A virus (A/wood duck/So...,ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...,H5N1,7,NaN,>GCA_040104305.1,A/wood duck/South Carolina/W24-007C/2023,C2.1
104127,PP761586.1,GCA_040104305.1,Influenza A virus (A/wood duck/South Carolina/...,wood duck,2023-12-20,NaN,A/wood duck/South Carolina/W24-007C/2023,C2.1,USA,>PP761586.1 |Influenza A virus (A/wood duck/So...,ATGGATGTCAATCCGACTTTACTCTTCTTGAAAGTTCCAGCGCAAA...,H5N1,2,NaN,>GCA_040104305.1,A/wood duck/South Carolina/W24-007C/2023,C2.1

In [71]:
# Re-Labeling

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

# Fix animals
fix_animals_andersen(metadata_genoflu, animals_ref)

# Get the years
metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

# Get geographic locations
metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location"].apply(lambda x: 
                                                                        # If "x" has the state abbreviation (e.g. "MD")
                                                                        states_ref.loc[states_ref["Abbreviation"].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0] 
                                                                        + "-" + 
                                                                        x.split(" ")[-1]
                                                                        if states_ref["Abbreviation"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has the full state name (e.g. "Maryland")
                                                                        else states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0]
                                                                        + "-" + 
                                                                        states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Abbreviation'].iloc[0] 
                                                                        if states_ref["State"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has neither the state abbreviation nor the full state name nor is "USA"
                                                                        else 
                                                                        x
                                                                        )

metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location_Abrv"].apply(lambda x: x.split("-")[0] if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] else x)


print(metadata_genoflu["Geo_Location_Abrv"])

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\2\ipykernel_26996\4197312387.py:22: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  if states_ref["Abbreviation"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\2\ipykernel_26996\4197312387.py:19: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  states_ref.loc[states_ref["Abbreviation"].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0]

0         Mexico-Jalisco
1         Mexico-Jalisco
2         Mexico-Jalisco
3         Mexico-Jalisco
4         Mexico-Jalisco
               ...
104123               USA
104124               USA
104125               USA
104126               USA
104127               USA
Name: Geo_Location_Abrv, Length: 185544, dtype: object

In [72]:
# If there is no SRA Accession, replace identifier with Assembly -- this part might be duplicating accessions :(
metadata_genoflu["Identifier"] = metadata_genoflu["Assembly"].apply(lambda x: x if metadata_genoflu[metadata_genoflu["Assembly"] == x]["SRA_Accession"].values[0] == "" else metadata_genoflu[metadata_genoflu["Assembly"] == x]["SRA_Accession"].values[0]) # np.where(metadata_genoflu['SRA_Accession'] != "", metadata_genoflu['SRA_Accession'], metadata_genoflu['Assembly'].apply(lambda x: x.split(".")[0]))
# # If there is no Assembly, replace identifier with Accession -- only for PB2
# metadata_genoflu["Identifier"] = np.where(metadata_genoflu["SRA_Accession_intermediate"] == "", metadata_genoflu["Accession"].apply(lambda x: metadata_genoflu[metadata_genoflu["Accession"] == x]["Accession"].values[0] if metadata_genoflu[metadata_genoflu["Accession"] == x].loc[:, "Segment"].values[0] == 1 else np.nan), metadata_genoflu["SRA_Accession_intermediate"])
# # Fill in other nans with PB2 Accession (interpolate, maximum of 7 other sequences)
# metadata_genoflu.loc[:,"Identifier"] = metadata_genoflu.loc[:, "Identifier"].ffill(limit=7, limit_area="inside")

print((metadata_genoflu[metadata_genoflu["Identifier"].str.contains("SRR")])) # metadata_genoflu[(metadata_genoflu["Identifier"].str.contains("GCA")) |

         Accession         Assembly  \
128     PQ051119.1  GCA_040889855.1
129     PQ051120.1  GCA_040889855.1
130     PQ051121.1  GCA_040889855.1
131     PQ051122.1  GCA_040889855.1
132     PQ051123.1  GCA_040889855.1
...            ...              ...
104051  PZ422026.1  GCA_057730505.1
104052  PZ422027.1  GCA_057730505.1
104053  PZ422028.1  GCA_057730505.1
104054  PZ422029.1  GCA_057730505.1
104055  PZ422030.1  GCA_057730505.1

                                            GenBank_Title        Host  \
128     Influenza A virus (A/Alpaca/ID/24-014328-008/2...      alpaca
129     Influenza A virus (A/Alpaca/ID/24-014328-008/2...      alpaca
130     Influenza A virus (A/Alpaca/ID/24-014328-008/2...      alpaca
131     Influenza A virus (A/Alpaca/ID/24-014328-008/2...      alpaca
132     Influenza A virus (A/Alpaca/ID/24-014328-008/2...      alpaca
...                                                   ...         ...
104051  Influenza A virus (A/wild goose/WY/26G04147-00...  wild goose
104052  Influenza A virus (A/wild goose/WY/26G04147-00...  wild goose
104053  Influenza A virus (A/wild goose/WY/26G04147-00...  wild goose
104054  Influenza A virus (A/wild goose/WY/26G04147-00...  wild goose
104055  Influenza A virus (A/wild goose/WY/26G04147-00...  wild goose

       Collection_Date SRA_Accession  \
128         2024-05-15   SRR29455647
129         2024-05-15   SRR29455647
130         2024-05-15   SRR29455647
131         2024-05-15   SRR29455647
132         2024-05-15   SRR29455647
...                ...           ...
104051      2026-03-06   SRR38140017
104052      2026-03-06   SRR38140017
104053      2026-03-06   SRR38140017
104054      2026-03-06   SRR38140017
104055      2026-03-06   SRR38140017

                                           Isolate Genotype_official  \
128                 A/Alpaca/ID/24-014328-008/2024             B3.13
129                 A/Alpaca/ID/24-014328-008/2024             B3.13
130                 A/Alpaca/ID/24-014328-008/2024             B3.13
131                 A/Alpaca/ID/24-014328-008/2024             B3.13
132                 A/Alpaca/ID/24-014328-008/2024             B3.13
...                                            ...               ...
104051  A/wild goose/WY/26G04147-001-original/2026               Not
104052  A/wild goose/WY/26G04147-001-original/2026               Not
104053  A/wild goose/WY/26G04147-001-original/2026               Not
104054  A/wild goose/WY/26G04147-001-original/2026               Not
104055  A/wild goose/WY/26G04147-001-original/2026               Not

       Geo_Location                                        full_header  ...  \
128         USA: ID  >PQ051119.1 |Influenza A virus (A/Alpaca/ID/24...  ...
129         USA: ID  >PQ051120.1 |Influenza A virus (A/Alpaca/ID/24...  ...
130         USA: ID  >PQ051121.1 |Influenza A virus (A/Alpaca/ID/24...  ...
131         USA: ID  >PQ051122.1 |Influenza A virus (A/Alpaca/ID/24...  ...
132         USA: ID  >PQ051123.1 |Influenza A virus (A/Alpaca/ID/24...  ...
...             ...                                                ...  ...
104051      USA: WY  >PZ422026.1 |Influenza A virus (A/wild goose/W...  ...
104052      USA: WY  >PZ422027.1 |Influenza A virus (A/wild goose/W...  ...
104053      USA: WY  >PZ422028.1 |Influenza A virus (A/wild goose/W...  ...
104054      USA: WY  >PZ422029.1 |Influenza A virus (A/wild goose/W...  ...
104055      USA: WY  >PZ422030.1 |Influenza A virus (A/wild goose/W...  ...

       Serotype Segment       File Name    Partial_Header  \
128        H5N1       1  SRR29455647.fa
129        H5N1       2  SRR29455647.fa
130        H5N1       3  SRR29455647.fa
131        H5N1       4  SRR29455647.fa
132        H5N1       5  SRR29455647.fa
...         ...     ...             ...               ...
104051     H5N1       4                  >GCA_057730505.1
104052     H5N1       5                  >GCA_057730505.1
104053     H5N1       6                  >GCA_057730505.1
104054     H5N1       7                  >GCA_057730505.1
104055     H5N1       8                  >GCA_057730505.1

                                      genbank_name Genotype     Host_Type  \
128                 A/Alpaca/ID/24-014328-008/2024    B3.13  other_mammal
129                 A/Alpaca/ID/24-014328-008/2024    B3.13  other_mammal
130                 A/Alpaca/ID/24-014328-008/2024    B3.13  other_mammal
131                 A/Alpaca/ID/24-014328-008/2024    B3.13  other_mammal
132                 A/Alpaca/ID/24-014328-008/2024    B3.13  other_mammal
...                                            ...      ...           ...
104051  A/wild goose/WY/26G04147-001-original/2026      Not    wild_avian
104052  A/wild goose/WY/26G04147-001-original/2026      Not    wild_avian
104053  A/wild goose/WY/26G04147-001-original/2026      Not    wild_avian
104054  A/wild goose/WY/26G04147-001-original/2026      Not    wild_avian
104055  A/wild goose/WY/26G04147-001-original/2026      Not    wild_avian

       Years Geo_Location_Abrv   Identifier
128     2024            USA-ID  SRR29455647
129     2024            USA-ID  SRR29455647
130     2024            USA-ID  SRR29455647
131     2024            USA-ID  SRR29455647
132     2024            USA-ID  SRR29455647
...      ...               ...          ...
104051  2026            USA-WY  SRR38140017
104052  2026            USA-WY  SRR38140017
104053  2026            USA-WY  SRR38140017
104054  2026            USA-WY  SRR38140017
104055  2026            USA-WY  SRR38140017

[150992 rows x 21 columns]

In [73]:

# Make new labels
names = ">" + metadata_genoflu["Identifier"].astype(str) + "|" + metadata_genoflu["genbank_name"] + "|" + metadata_genoflu["Serotype"] + "|" + metadata_genoflu["Geo_Location_Abrv"] + "|" + metadata_genoflu["Collection_Date"].astype(str) + "|" + metadata_genoflu["Host_Type"] + "|" + metadata_genoflu["Genotype"]

metadata_genoflu["Name"] = names

In [74]:
os.chdir(complete_files)

# De-duplicate

print(len(metadata_genoflu))
metadata_genoflu = metadata_genoflu.drop_duplicates(subset=["Isolate", "genbank_name", "Segment"], keep="last")
print(len(metadata_genoflu))

# Save metadata
metadata_genoflu.to_csv("NCBI_Virus_" + date_range + "_metadata.csv") # Make file for metadata

185544
118656

## Rename segments and make complete FASTA files

In [75]:
# Set up segments

# if len(genotypes) > 3: # If we're not doing maintenance only
#     genotypes.append("Not assigned") # Make sure unassigned genotypes are included
segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"} # Name segments 
metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].apply(lambda x: int(x)).map(segments)

# Separate into several dataframes based on genotype + segment
segment_genotype_dfs = []
for segment in segments.values():
    m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
    for genotype in list(set(m_g["Genotype"].values)):
        if genotype in genotypes:
            df = m_g[(m_g["Genotype"] == genotype)] 
            # df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
            segment_genotype_dfs.append(df)
            pair = genotype + "_" + segment
            print(pair)

B3.13_PB2
B3.13_PB1
B3.13_PA
B3.13_HA
B3.13_NP
B3.13_NA
B3.13_MP
B3.13_NS

In [77]:
# Create FASTA files

os.chdir(complete_files)

for df in segment_genotype_dfs:
    print(df)
    
    df = df.reset_index()
    if len(df["Genotype"].values[0]) > 0: # If we have assigned genotypes, including "Unassigned"
        file_name = df["Genotype"].values[0] + "_" + df["Segment_Name"].values[0] + "_" + date_range + ".fasta"
        output_file = open(complete_files + file_name, "w")

        for index, row in df.iterrows():
            name = df.loc[index, "Name"]
            name = name.replace(" ", "_")
            # names.append(name)
            sequence = df.loc[index, "sequence"]
            # First is header, second is sequence
            output_file.write(name + "\n")
            output_file.write(sequence + "\n")
        
    output_file.close()

         Accession         Assembly  \
4528    PV070690.1  GCA_047521275.1
4536    PV070698.1  GCA_047521295.1
10768   PQ010976.1  GCA_042347135.1
10776   PQ012072.1  GCA_042347435.1
10784   PQ011176.1  GCA_040780605.1
...            ...              ...
103192  PV601972.1  GCA_050381395.1
103200  PV601948.1  GCA_050381405.1
103208  PV602004.1  GCA_050381415.1
103216  PV602012.1  GCA_050381425.1
103224  PV601980.1  GCA_050381435.1

                                            GenBank_Title    Host  \
4528    Influenza A virus (A/Bobcat/WA/24-037410-006-o...  bobcat
4536    Influenza A virus (A/Bobcat/WA/24-037410-013-o...  bobcat
10768   Influenza A virus (A/Cat/New Mexico/24-010948-...     cat
10776   Influenza A virus (A/Cat/Texas/24-009311-002-o...     cat
10784   Influenza A virus (A/Cattle/Colorado/24-012225...  cattle
...                                                   ...     ...
103192  Influenza A virus (A/swine/Kansas/ExpPig59-OP1...   swine
103200  Influenza A virus (A/swine/Kansas/ExpPig61-BAL...   swine
103208  Influenza A virus (A/swine/Kansas/ExpPig61-NS4...   swine
103216  Influenza A virus (A/swine/Kansas/ExpPig61-NS5...   swine
103224  Influenza A virus (A/swine/Kansas/ExpPig61-OP1...   swine

       Collection_Date SRA_Accession  \
4528              2024   SRR31885886
4536              2024   SRR31885873
10768       2024-04-09   SRR28912792
10776       2024-03-19   SRR28912858
10784       2024-04-23   SRR28912816
...                ...           ...
103192         2024-11
103200         2024-11
103208         2024-11
103216         2024-11
103224         2024-11

                                              Isolate Genotype_official  \
4528          A/Bobcat/WA/24-037410-006-original/2024             B3.13
4536          A/Bobcat/WA/24-037410-013-original/2024             B3.13
10768    A/Cat/New Mexico/24-010948-001-original/2024             B3.13
10776         A/Cat/Texas/24-009311-002-original/2024             B3.13
10784   A/Cattle/Colorado/24-012225-001-original/2024             B3.13
...                                               ...               ...
103192            A/swine/Kansas/ExpPig59-OP1DPI/2024             B3.13
103200           A/swine/Kansas/ExpPig61-BAL5DPI/2024             B3.13
103208            A/swine/Kansas/ExpPig61-NS4DPI/2024             B3.13
103216            A/swine/Kansas/ExpPig61-NS5DPI/2024             B3.13
103224            A/swine/Kansas/ExpPig61-OP1DPI/2024             B3.13

       Geo_Location                                        full_header  ...  \
4528        USA: WA  >PV070690.1 |Influenza A virus (A/Bobcat/WA/24...  ...
4536        USA: WA  >PV070698.1 |Influenza A virus (A/Bobcat/WA/24...  ...
10768        USA:NM  >PQ010976.1 |Influenza A virus (A/Cat/New Mexi...  ...
10776        USA:TX  >PQ012072.1 |Influenza A virus (A/Cat/Texas/24...  ...
10784        USA:CO  >PQ011176.1 |Influenza A virus (A/Cattle/Color...  ...
...             ...                                                ...  ...
103192  USA: Kansas  >PV601972.1 |Influenza A virus (A/swine/Kansas...  ...
103200  USA: Kansas  >PV601948.1 |Influenza A virus (A/swine/Kansas...  ...
103208  USA: Kansas  >PV602004.1 |Influenza A virus (A/swine/Kansas...  ...
103216  USA: Kansas  >PV602012.1 |Influenza A virus (A/swine/Kansas...  ...
103224  USA: Kansas  >PV601980.1 |Influenza A virus (A/swine/Kansas...  ...

             File Name    Partial_Header  \
4528    SRR31885886.fa
4536    SRR31885873.fa
10768   SRR28912792.fa
10776   SRR28912858.fa
10784   SRR28912816.fa
...                ...               ...
103192                  >GCA_050381395.1
103200                  >GCA_050381405.1
103208                  >GCA_050381415.1
103216                  >GCA_050381425.1
103224                  >GCA_050381435.1

                                         genbank_name Genotype     Host_Type  \
4528          A/Bobcat/WA/24-037410-006-original/2024    B3.13        feline
4536          A/Bobcat/WA/24-037410-013-original/2024    B3.13        feline
10768    A/Cat/New Mexico/24-010948-001-original/2024    B3.13        feline
10776         A/Cat/Texas/24-009311-002-original/2024    B3.13        feline
10784   A/Cattle/Colorado/24-012225-001-original/2024    B3.13        cattle
...                                               ...      ...           ...
103192            A/swine/Kansas/ExpPig59-OP1DPI/2024    B3.13  other_mammal
103200           A/swine/Kansas/ExpPig61-BAL5DPI/2024    B3.13  other_mammal
103208            A/swine/Kansas/ExpPig61-NS4DPI/2024    B3.13  other_mammal
103216            A/swine/Kansas/ExpPig61-NS5DPI/2024    B3.13  other_mammal
103224            A/swine/Kansas/ExpPig61-OP1DPI/2024    B3.13  other_mammal

       Years Geo_Location_Abrv       Identifier  \
4528    2024            USA-WA      SRR31885886
4536    2024            USA-WA      SRR31885873
10768   2024            USA:NM      SRR28912792
10776   2024            USA:TX      SRR28912858
10784   2024            USA:CO      SRR28912816
...      ...               ...              ...
103192  2024            USA-KS  GCA_050381395.1
103200  2024            USA-KS  GCA_050381405.1
103208  2024            USA-KS  GCA_050381415.1
103216  2024            USA-KS  GCA_050381425.1
103224  2024            USA-KS  GCA_050381435.1

                                                     Name Segment_Name
4528    >SRR31885886|A/Bobcat/WA/24-037410-006-origina...          PB2
4536    >SRR31885873|A/Bobcat/WA/24-037410-013-origina...          PB2
10768   >SRR28912792|A/Cat/New Mexico/24-010948-001-or...          PB2
10776   >SRR28912858|A/Cat/Texas/24-009311-002-origina...          PB2
10784   >SRR28912816|A/Cattle/Colorado/24-012225-001-o...          PB2
...                                                   ...          ...
103192  >GCA_050381395.1|A/swine/Kansas/ExpPig59-OP1DP...          PB2
103200  >GCA_050381405.1|A/swine/Kansas/ExpPig61-BAL5D...          PB2
103208  >GCA_050381415.1|A/swine/Kansas/ExpPig61-NS4DP...          PB2
103216  >GCA_050381425.1|A/swine/Kansas/ExpPig61-NS5DP...          PB2
103224  >GCA_050381435.1|A/swine/Kansas/ExpPig61-OP1DP...          PB2

[4531 rows x 23 columns]
         Accession         Assembly  \
4529    PV070691.1  GCA_047521275.1
4537    PV070699.1  GCA_047521295.1
10769   PQ010977.1  GCA_042347135.1
10777   PQ012073.1  GCA_042347435.1
10785   PQ011177.1  GCA_040780605.1
...            ...              ...
103193  PV601973.1  GCA_050381395.1
103201  PV601949.1  GCA_050381405.1
103209  PV602005.1  GCA_050381415.1
103217  PV602013.1  GCA_050381425.1
103225  PV601981.1  GCA_050381435.1

                                            GenBank_Title    Host  \
4529    Influenza A virus (A/Bobcat/WA/24-037410-006-o...  bobcat
4537    Influenza A virus (A/Bobcat/WA/24-037410-013-o...  bobcat
10769   Influenza A virus (A/Cat/New Mexico/24-010948-...     cat
10777   Influenza A virus (A/Cat/Texas/24-009311-002-o...     cat
10785   Influenza A virus (A/Cattle/Colorado/24-012225...  cattle
...                                                   ...     ...
103193  Influenza A virus (A/swine/Kansas/ExpPig59-OP1...   swine
103201  Influenza A virus (A/swine/Kansas/ExpPig61-BAL...   swine
103209  Influenza A virus (A/swine/Kansas/ExpPig61-NS4...   swine
103217  Influenza A virus (A/swine/Kansas/ExpPig61-NS5...   swine
103225  Influenza A virus (A/swine/Kansas/ExpPig61-OP1...   swine

       Collection_Date SRA_Accession  \
4529              2024   SRR31885886
4537              2024   SRR31885873
10769       2024-04-09   SRR28912792
10777       2024-03-19   SRR28912858
10785       2024-04-23   SRR28912816
...                ...           ...
103193         2024-11
103201         2024-11
103209         2024-11
103217         2024-11
103225         2024-11

                                              Isolate Genotype_official  \
4529          A/Bobcat/WA/24-037410-006-original/2024             B3.13
4537          A/Bobcat/WA/24-037410-013-original/2024             B3.13
10769    A/Cat/New Mexico/24-010948-001-original/2024             B3.13
10777         A/Cat/Texas/24-009311-002-original/2024             B3.13
10785   A/Cattle/Colorado/24-012225-001-original/2024             B3.13
...                                               ...               ...
103193            A/swine/Kansas/ExpPig59-OP1DPI/2024             B3.13
103201           A/swine/Kansas/ExpPig61-BAL5DPI/2024             B3.13
103209            A/swine/Kansas/ExpPig61-NS4DPI/2024             B3.13
103217            A/swine/Kansas/ExpPig61-NS5DPI/2024             B3.13
103225            A/swine/Kansas/ExpPig61-OP1DPI/2024             B3.13

       Geo_Location                                        full_header  ...  \
4529        USA: WA  >PV070691.1 |Influenza A virus (A/Bobcat/WA/24...  ...
4537        USA: WA  >PV070699.1 |Influenza A virus (A/Bobcat/WA/24...  ...
10769        USA:NM  >PQ010977.1 |Influenza A virus (A/Cat/New Mexi...  ...
10777        USA:TX  >PQ012073.1 |Influenza A virus (A/Cat/Texas/24...  ...
10785        USA:CO  >PQ011177.1 |Influenza A virus (A/Cattle/Color...  ...
...             ...                                                ...  ...
103193  USA: Kansas  >PV601973.1 |Influenza A virus (A/swine/Kansas...  ...
103201  USA: Kansas  >PV601949.1 |Influenza A virus (A/swine/Kansas...  ...
103209  USA: Kansas  >PV602005.1 |Influenza A virus (A/swine/Kansas...  ...
103217  USA: Kansas  >PV602013.1 |Influenza A virus (A/swine/Kansas...  ...
103225  USA: Kansas  >PV601981.1 |Influenza A virus (A/swine/Kansas...  ...

             File Name    Partial_Header  \
4529    SRR31885886.fa
4537    SRR31885873.fa
10769   SRR28912792.fa
10777   SRR28912858.fa
10785   SRR28912816.fa
...                ...               ...
103193                  >GCA_050381395.1
103201                  >GCA_050381405.1
103209                  >GCA_050381415.1
103217                  >GCA_050381425.1
103225                  >GCA_050381435.1

                                         genbank_name Genotype     Host_Type  \
4529          A/Bobcat/WA/24-037410-006-original/2024    B3.13        feline
4537          A/Bobcat/WA/24-037410-013-original/2024    B3.13        feline
10769    A/Cat/New Mexico/24-010948-001-original/2024    B3.13        feline
10777         A/Cat/Texas/24-009311-002-original/2024    B3.13        feline
10785   A/Cattle/Colorado/24-012225-001-original/2024    B3.13        cattle
...                                               ...      ...           ...
103193            A/swine/Kansas/ExpPig59-OP1DPI/2024    B3.13  other_mammal
103201           A/swine/Kansas/ExpPig61-BAL5DPI/2024    B3.13  other_mammal
103209            A/swine/Kansas/ExpPig61-NS4DPI/2024    B3.13  other_mammal
103217            A/swine/Kansas/ExpPig61-NS5DPI/2024    B3.13  other_mammal
103225            A/swine/Kansas/ExpPig61-OP1DPI/2024    B3.13  other_mammal

       Years Geo_Location_Abrv       Identifier  \
4529    2024            USA-WA      SRR31885886
4537    2024            USA-WA      SRR31885873
10769   2024            USA:NM      SRR28912792
10777   2024            USA:TX      SRR28912858
10785   2024            USA:CO      SRR28912816
...      ...               ...              ...
103193  2024            USA-KS  GCA_050381395.1
103201  2024            USA-KS  GCA_050381405.1
103209  2024            USA-KS  GCA_050381415.1
103217  2024            USA-KS  GCA_050381425.1
103225  2024            USA-KS  GCA_050381435.1

                                                     Name Segment_Name
4529    >SRR31885886|A/Bobcat/WA/24-037410-006-origina...          PB1
4537    >SRR31885873|A/Bobcat/WA/24-037410-013-origina...          PB1
10769   >SRR28912792|A/Cat/New Mexico/24-010948-001-or...          PB1
10777   >SRR28912858|A/Cat/Texas/24-009311-002-origina...          PB1
10785   >SRR28912816|A/Cattle/Colorado/24-012225-001-o...          PB1
...                                                   ...          ...
103193  >GCA_050381395.1|A/swine/Kansas/ExpPig59-OP1DP...          PB1
103201  >GCA_050381405.1|A/swine/Kansas/ExpPig61-BAL5D...          PB1
103209  >GCA_050381415.1|A/swine/Kansas/ExpPig61-NS4DP...          PB1
103217  >GCA_050381425.1|A/swine/Kansas/ExpPig61-NS5DP...          PB1
103225  >GCA_050381435.1|A/swine/Kansas/ExpPig61-OP1DP...          PB1

[4531 rows x 23 columns]
         Accession         Assembly  \
4530    PV070692.1  GCA_047521275.1
4538    PV070700.1  GCA_047521295.1
10770   PQ010978.1  GCA_042347135.1
10778   PQ012074.1  GCA_042347435.1
10786   PQ011178.1  GCA_040780605.1
...            ...              ...
103194  PV601974.1  GCA_050381395.1
103202  PV601950.1  GCA_050381405.1
103210  PV602006.1  GCA_050381415.1
103218  PV602014.1  GCA_050381425.1
103226  PV601982.1  GCA_050381435.1

                                            GenBank_Title    Host  \
4530    Influenza A virus (A/Bobcat/WA/24-037410-006-o...  bobcat
4538    Influenza A virus (A/Bobcat/WA/24-037410-013-o...  bobcat
10770   Influenza A virus (A/Cat/New Mexico/24-010948-...     cat
10778   Influenza A virus (A/Cat/Texas/24-009311-002-o...     cat
10786   Influenza A virus (A/Cattle/Colorado/24-012225...  cattle
...                                                   ...     ...
103194  Influenza A virus (A/swine/Kansas/ExpPig59-OP1...   swine
103202  Influenza A virus (A/swine/Kansas/ExpPig61-BAL...   swine
103210  Influenza A virus (A/swine/Kansas/ExpPig61-NS4...   swine
103218  Influenza A virus (A/swine/Kansas/ExpPig61-NS5...   swine
103226  Influenza A virus (A/swine/Kansas/ExpPig61-OP1...   swine

       Collection_Date SRA_Accession  \
4530              2024   SRR31885886
4538              2024   SRR31885873
10770       2024-04-09   SRR28912792
10778       2024-03-19   SRR28912858
10786       2024-04-23   SRR28912816
...                ...           ...
103194         2024-11
103202         2024-11
103210         2024-11
103218         2024-11
103226         2024-11

                                              Isolate Genotype_official  \
4530          A/Bobcat/WA/24-037410-006-original/2024             B3.13
4538          A/Bobcat/WA/24-037410-013-original/2024             B3.13
10770    A/Cat/New Mexico/24-010948-001-original/2024             B3.13
10778         A/Cat/Texas/24-009311-002-original/2024             B3.13
10786   A/Cattle/Colorado/24-012225-001-original/2024             B3.13
...                                               ...               ...
103194            A/swine/Kansas/ExpPig59-OP1DPI/2024             B3.13
103202           A/swine/Kansas/ExpPig61-BAL5DPI/2024             B3.13
103210            A/swine/Kansas/ExpPig61-NS4DPI/2024             B3.13
103218            A/swine/Kansas/ExpPig61-NS5DPI/2024             B3.13
103226            A/swine/Kansas/ExpPig61-OP1DPI/2024             B3.13

       Geo_Location                                        full_header  ...  \
4530        USA: WA  >PV070692.1 |Influenza A virus (A/Bobcat/WA/24...  ...
4538        USA: WA  >PV070700.1 |Influenza A virus (A/Bobcat/WA/24...  ...
10770        USA:NM  >PQ010978.1 |Influenza A virus (A/Cat/New Mexi...  ...
10778        USA:TX  >PQ012074.1 |Influenza A virus (A/Cat/Texas/24...  ...
10786        USA:CO  >PQ011178.1 |Influenza A virus (A/Cattle/Color...  ...
...             ...                                                ...  ...
103194  USA: Kansas  >PV601974.1 |Influenza A virus (A/swine/Kansas...  ...
103202  USA: Kansas  >PV601950.1 |Influenza A virus (A/swine/Kansas...  ...
103210  USA: Kansas  >PV602006.1 |Influenza A virus (A/swine/Kansas...  ...
103218  USA: Kansas  >PV602014.1 |Influenza A virus (A/swine/Kansas...  ...
103226  USA: Kansas  >PV601982.1 |Influenza A virus (A/swine/Kansas...  ...

             File Name    Partial_Header  \
4530    SRR31885886.fa
4538    SRR31885873.fa
10770   SRR28912792.fa
10778   SRR28912858.fa
10786   SRR28912816.fa
...                ...               ...
103194                  >GCA_050381395.1
103202                  >GCA_050381405.1
103210                  >GCA_050381415.1
103218                  >GCA_050381425.1
103226                  >GCA_050381435.1

                                         genbank_name Genotype     Host_Type  \
4530          A/Bobcat/WA/24-037410-006-original/2024    B3.13        feline
4538          A/Bobcat/WA/24-037410-013-original/2024    B3.13        feline
10770    A/Cat/New Mexico/24-010948-001-original/2024    B3.13        feline
10778         A/Cat/Texas/24-009311-002-original/2024    B3.13        feline
10786   A/Cattle/Colorado/24-012225-001-original/2024    B3.13        cattle
...                                               ...      ...           ...
103194            A/swine/Kansas/ExpPig59-OP1DPI/2024    B3.13  other_mammal
103202           A/swine/Kansas/ExpPig61-BAL5DPI/2024    B3.13  other_mammal
103210            A/swine/Kansas/ExpPig61-NS4DPI/2024    B3.13  other_mammal
103218            A/swine/Kansas/ExpPig61-NS5DPI/2024    B3.13  other_mammal
103226            A/swine/Kansas/ExpPig61-OP1DPI/2024    B3.13  other_mammal

       Years Geo_Location_Abrv       Identifier  \
4530    2024            USA-WA      SRR31885886
4538    2024            USA-WA      SRR31885873
10770   2024            USA:NM      SRR28912792
10778   2024            USA:TX      SRR28912858
10786   2024            USA:CO      SRR28912816
...      ...               ...              ...
103194  2024            USA-KS  GCA_050381395.1
103202  2024            USA-KS  GCA_050381405.1
103210  2024            USA-KS  GCA_050381415.1
103218  2024            USA-KS  GCA_050381425.1
103226  2024            USA-KS  GCA_050381435.1

                                                     Name Segment_Name
4530    >SRR31885886|A/Bobcat/WA/24-037410-006-origina...           PA
4538    >SRR31885873|A/Bobcat/WA/24-037410-013-origina...           PA
10770   >SRR28912792|A/Cat/New Mexico/24-010948-001-or...           PA
10778   >SRR28912858|A/Cat/Texas/24-009311-002-origina...           PA
10786   >SRR28912816|A/Cattle/Colorado/24-012225-001-o...           PA
...                                                   ...          ...
103194  >GCA_050381395.1|A/swine/Kansas/ExpPig59-OP1DP...           PA
103202  >GCA_050381405.1|A/swine/Kansas/ExpPig61-BAL5D...           PA
103210  >GCA_050381415.1|A/swine/Kansas/ExpPig61-NS4DP...           PA
103218  >GCA_050381425.1|A/swine/Kansas/ExpPig61-NS5DP...           PA
103226  >GCA_050381435.1|A/swine/Kansas/ExpPig61-OP1DP...           PA

[4531 rows x 23 columns]
         Accession         Assembly  \
4531    PV070693.1  GCA_047521275.1
4539    PV070701.1  GCA_047521295.1
10771   PQ010979.1  GCA_042347135.1
10779   PQ012075.1  GCA_042347435.1
10787   PQ011179.1  GCA_040780605.1
...            ...              ...
103195  PV601975.1  GCA_050381395.1
103203  PV601951.1  GCA_050381405.1
103211  PV602007.1  GCA_050381415.1
103219  PV602015.1  GCA_050381425.1
103227  PV601983.1  GCA_050381435.1

                                            GenBank_Title    Host  \
4531    Influenza A virus (A/Bobcat/WA/24-037410-006-o...  bobcat
4539    Influenza A virus (A/Bobcat/WA/24-037410-013-o...  bobcat
10771   Influenza A virus (A/Cat/New Mexico/24-010948-...     cat
10779   Influenza A virus (A/Cat/Texas/24-009311-002-o...     cat
10787   Influenza A virus (A/Cattle/Colorado/24-012225...  cattle
...                                                   ...     ...
103195  Influenza A virus (A/swine/Kansas/ExpPig59-OP1...   swine
103203  Influenza A virus (A/swine/Kansas/ExpPig61-BAL...   swine
103211  Influenza A virus (A/swine/Kansas/ExpPig61-NS4...   swine
103219  Influenza A virus (A/swine/Kansas/ExpPig61-NS5...   swine
103227  Influenza A virus (A/swine/Kansas/ExpPig61-OP1...   swine

       Collection_Date SRA_Accession  \
4531              2024   SRR31885886
4539              2024   SRR31885873
10771       2024-04-09   SRR28912792
10779       2024-03-19   SRR28912858