# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI and relabeling sequences. 

Notes:
* This file must be in the same folder as "utils.py"

## Housekeeping

In [1]:
# Libraries

import os
import pandas as pd
import dateutil
import re
import shutil 
import numpy as np
import importlib
import utils  
importlib.reload(utils)
from utils import * # If changing utils, must restart this file for changes to take effect

In [2]:
# Directory paths and input

# Input
browser = input("Browser (Firefox, Chrome, or Edge): ")
sleep_time = input("Seconds to wait in between clicks (recommended 5): ")
# locations = input("Locations (separate with commas and no spaces in between locations): ")
# start_date = input("Start date (format: MM-DD-YYYY): ")
# end_date = input("End date: (format: MM-DD-YYYY): ")
# serotype = input("Serotype (e.g. H5N1): ")
# serotypes = list(serotype)
# genotypes = input("Genotypes (separate with commas and no spaces in between genotypes): ")
# genotypes = genotypes.split(",")

# Dates and locations
locations = "Antarctica,North America,South America"
start_date = "11-01-2021"
end_date = "02-20-2026"
prev_end_date = "01-23-2026"
date_range = start_date + "--" + end_date
prev_date_range = start_date + "--" + prev_end_date

# Maintenance serotypes and genotypes
serotypes = ["H5N1"]
genotypes = ["B3.13", "D1.1", "D1.3"]

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# downloads = "C:/Users/maksi/Downloads/"
# references = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/references/"

home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Downloads/" # MUST be downloads folder. Clean out downloads folder after each use. 
references = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/references/"

downloads_saved = home + "NCBI_Virus/downloads/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/" 
prev_downloads_saved = home + "NCBI_Virus/downloads/" + prev_date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/" 

andersen = home + "Andersen/avian-influenza/metadata/"
temp_files = home + "NCBI_Virus/temp/"
complete_files = home + "NCBI_Virus/complete/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/"
if not os.path.exists(complete_files): # checking if the directory exists or not
    os.makedirs(complete_files) # if the directory is not present then create it

os.chdir(references)
states_ref = pd.read_csv("states_ref.csv")

# All serotypes and genotypes
# serotype = ""
# genotypes_df = pd.read_excel("genotype_key.xlsx")
# genotypes = list(genotypes_df["Genotype"])

## Downloading Data

In [3]:
os.chdir(downloads)

if not os.path.exists(downloads_saved): # checking if the directory exists or not
    os.makedirs(downloads_saved) # if the directory is not present then create it

# Move downloaded files to saved downloads
for dirpath, dirs, files in os.walk(downloads_saved):
    if len(files) != 0:
        break 
    else: # If we don't have any downloaded files
        # Get files
        open_ncbi_virus(browser, sleep_time, locations, start_date, end_date)

        # Re-try 
        for dirpath, dirs, files in os.walk(downloads):
            if len(files) > 0: # If we have any files that need to be moved
                for file in files:
                    file_name = os.path.join(dirpath, file)
                    destination_path = os.path.join(downloads_saved, os.path.basename(file_name))
                    try:
                        shutil.move(file_name, destination_path)
                    except:
                        print("Error moving file", file_name)
                        continue 
            break 
    break

## De-Duplication

In [4]:
# Get metadata
os.chdir(downloads_saved)
metadata = pd.read_csv("sequences.csv")
print(len(metadata))

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.Isolate, as_index=False).size()
# print(metadata_counts)
metadata_counted = metadata.merge(metadata_counts, on="Isolate")

# Only keep those with size >= 8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates
metadata_complete_segs = metadata_complete_segs.drop_duplicates(subset="GenBank_Title", keep="last") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]
metadata_segments

143517

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Host,Tissue_Specimen_Source,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size
0,PZ016555.1,GenBank,GCA_055411775.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Canidae,brain,"Falghoush,A.M.","Washington state university, Veterinary Microb...",USA,NaN,2025-12-24,2026-02-18,ssRNA(-),8
1,PZ016556.1,GenBank,GCA_055411775.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Canidae,brain,"Falghoush,A.M.","Washington state university, Veterinary Microb...",USA,NaN,2025-12-24,2026-02-18,ssRNA(-),8
2,PZ016557.1,GenBank,GCA_055411775.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Canidae,brain,"Falghoush,A.M.","Washington state university, Veterinary Microb...",USA,NaN,2025-12-24,2026-02-18,ssRNA(-),8
3,PZ016558.1,GenBank,GCA_055411775.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Canidae,brain,"Falghoush,A.M.","Washington state university, Veterinary Microb...",USA,NaN,2025-12-24,2026-02-18,ssRNA(-),8
4,PZ016559.1,GenBank,GCA_055411775.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Canidae,brain,"Falghoush,A.M.","Washington state university, Veterinary Microb...",USA,NaN,2025-12-24,2026-02-18,ssRNA(-),8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135476,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
135477,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
135478,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
135479,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
135480,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8

## Add sequences to dataframe

In [5]:
# NCBI Virus Naming Convention:
# "Accession|GenBank_Title|Assembly|SRA Accession|BioSample|BioProject|Genotype|Isolate|Geo Location|Host|Collection Date"

# Get sequences and headers together
# headers = []
# isolates = []
# sras = []
# headers_seqs = {}

os.chdir(downloads_saved)

sequences_fasta = df_from_fasta("sequences.fasta") # Turn fasta into a dataframe

sequences_fasta["Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split(" |")[0].replace(">",""))

print(sequences_fasta["full_header"])

# Extract segment number so that we can add the correct sequences to the correct sample
# sequences_fasta["Segment"] = sequences_fasta["full_header"].apply(lambda x: int(re.search(r'segment (.?) ', x.split("|")[-2]).group(1)))

# Double-check the de-duplication
print(len(sequences_fasta)) 
# print(sequences_fasta.head())
print(len(metadata_segments))

# Add sequences to the dataframe
metadata_segments = pd.merge(metadata_segments, sequences_fasta, on="Accession") # , "Segment"])

0         >PZ016555.1 |Influenza A virus (A/Fox/WA/W2602...
1         >PZ016556.1 |Influenza A virus (A/Fox/WA/W2602...
2         >PZ016557.1 |Influenza A virus (A/Fox/WA/W2602...
3         >PZ016558.1 |Influenza A virus (A/Fox/WA/W2602...
4         >PZ016559.1 |Influenza A virus (A/Fox/WA/W2602...
                                ...
143512    >OK205883.1 |Influenza A virus (A/chicken/Vera...
143513    >OK205884.1 |Influenza A virus (A/chicken/Vera...
143514    >OK205885.1 |Influenza A virus (A/chicken/Vera...
143515    >OK205886.1 |Influenza A virus (A/chicken/Vera...
143516    >OK205887.1 |Influenza A virus (A/chicken/Vera...
Name: full_header, Length: 143517, dtype: object
143517
124080

In [6]:
metadata_segments

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size,full_header,sequence
0,PZ016555.1,GenBank,GCA_055411775.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Falghoush,A.M.","Washington state university, Veterinary Microb...",USA,NaN,2025-12-24,2026-02-18,ssRNA(-),8,>PZ016555.1 |Influenza A virus (A/Fox/WA/W2602...,ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...
1,PZ016556.1,GenBank,GCA_055411775.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Falghoush,A.M.","Washington state university, Veterinary Microb...",USA,NaN,2025-12-24,2026-02-18,ssRNA(-),8,>PZ016556.1 |Influenza A virus (A/Fox/WA/W2602...,ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
2,PZ016557.1,GenBank,GCA_055411775.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Falghoush,A.M.","Washington state university, Veterinary Microb...",USA,NaN,2025-12-24,2026-02-18,ssRNA(-),8,>PZ016557.1 |Influenza A virus (A/Fox/WA/W2602...,ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
3,PZ016558.1,GenBank,GCA_055411775.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Falghoush,A.M.","Washington state university, Veterinary Microb...",USA,NaN,2025-12-24,2026-02-18,ssRNA(-),8,>PZ016558.1 |Influenza A virus (A/Fox/WA/W2602...,ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4,PZ016559.1,GenBank,GCA_055411775.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Falghoush,A.M.","Washington state university, Veterinary Microb...",USA,NaN,2025-12-24,2026-02-18,ssRNA(-),8,>PZ016559.1 |Influenza A virus (A/Fox/WA/W2602...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAGATGGAGACTG...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124075,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205883.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...
124076,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205884.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...
124077,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205885.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...
124078,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205886.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...
124079,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205887.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...

## Find genotypes

(Using old genoflu results or Andersen Lab genoflu output) <br>
Old genoflu results should accumulate into one file to avoid having to genotype anything again.

### Find old genotypes

In [7]:
# Switch directory to previous week
os.chdir(prev_downloads_saved)

# Get both files from previous week
genoflu_output = pd.read_csv("output.tsv", delimiter="\t")
genoflu_results = pd.read_csv("results.tsv", delimiter="\t")

# Get old results from output.tsv
genoflu_old = pd.concat([genoflu_output, genoflu_results])
# genoflu_old = genoflu_old.rename(columns={"Strain":"Partial_Header"}) # So we can merge
print(genoflu_old)

# Switch back directory
os.chdir(downloads_saved)

# Save this output for the future
genoflu_old.to_csv("output.tsv", sep="\t", index=False)

                                               Strain  \
0   Influenza_A_virus__Mexico__Estado_de_Mexico_CP...
1   Influenza_A_virus__Mexico__Estado_de_Mexico_CP...
2   Influenza_A_virus__Mexico__Ciudad_de_Mexico_CP...
3   Influenza_A_virus__Mexico__Estado_de_Mexico_CP...
4   Influenza_A_virus__Mexico__Michoacan_CPA_02011...
..                                                ...
70                                    GCA_054697095_1
71                                    GCA_054697065_1
72                                    GCA_054697345_1
73                                    GCA_054697675_1
74                                    GCA_054697625_1

                                             Genotype  \
0   Not assigned: Only 3 segments >98.0% match fou...
1   Not assigned: Only 3 segments >98.0% match fou...
2   Not assigned: Only 3 segments >98.0% match fou...
3   Not assigned: Only 3 segments >98.0% match fou...
4   Not assigned: Only 6 segments >98.0% match fou...
..                                                ...
70                                               D1.1
71                                               D1.1
72                Not assigned: No Matching Genotypes
73                                               D1.1
74                                               D1.1

                          Genotype List Used, >=98.0%  \
0                            PA:ea1, MP:ea1, NS:am1.1
1                            PA:ea1, MP:ea1, NS:am1.1
2                            PA:ea1, MP:ea1, NS:am1.1
3                            PA:ea1, MP:ea1, NS:am1.1
4   PB2:am2.1, PB1:am1.2, PA:ea1, HA:ea1, MP:ea1, ...
..                                                ...
70  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
71  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
72  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am1.1, N...
73  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
74  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                           Genotype Sample Title List  \
0   am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
1   am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
2   am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
3   am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
4   am2.1:22-009329-001:PB2, am1.2:22-010085-001:P...
..                                                ...
70  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
71  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
72  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
73  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
74  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                          Genotype Percent Match List  \
0   97.63%, 92.66%, 98.33%, 97.53%, 88.91%, 83.52%...
1   97.67%, 92.66%, 98.33%, 97.59%, 88.84%, 83.52%...
2   97.57%, 92.70%, 98.28%, 97.59%, 88.84%, 83.52%...
3   97.67%, 92.70%, 98.33%, 97.36%, 88.84%, 83.43%...
4   98.90%, 98.77%, 98.98%, 98.47%, 88.96%, 83.70%...
..                                                ...
70  99.34%, 99.25%, 99.21%, 99.35%, 99.40%, 99.15%...
71  99.47%, 99.38%, 99.21%, 99.24%, 99.47%, 99.22%...
72  99.61%, 99.30%, 99.21%, 99.18%, 98.80%, 99.01%...
73  99.61%, 99.12%, 99.30%, 99.24%, 99.47%, 99.22%...
74  99.43%, 99.21%, 99.21%, 99.41%, 99.47%, 99.22%...

               Genotype Mismatch List Genotype Average Depth of Coverage List  \
0   54, 167, 36, 42, 166, 186, 18, 14       Ran on FASTA - No Coverage Report
1   53, 167, 36, 41, 167, 186, 18, 14       Ran on FASTA - No Coverage Report
2   35, 166, 37, 41, 167, 186, 19, 14       Ran on FASTA - No Coverage Report
3   53, 166, 36, 45, 167, 187, 18, 14       Ran on FASTA - No Coverage Report
4     25, 28, 22, 26, 165, 182, 12, 9       Ran on FASTA - No Coverage Report
..                                ...                                     ...
70       15, 17, 17, 11, 9, 12, 3, 10       Ran on FASTA - No Coverage Report
71        12, 14, 17, 13, 8, 11, 2, 9       Ran on FASTA - No Coverage Report
72        9, 16, 17, 14, 18, 14, 5, 9       Ran on FASTA - No Coverage Report
73         9, 20, 15, 13, 8, 11, 5, 9       Ran on FASTA - No Coverage Report
74       13, 18, 17, 10, 8, 11, 3, 10       Ran on FASTA - No Coverage Report

               Date run
0   2025-12-03_10-28-26
1   2025-12-03_10-28-27
2   2025-12-03_10-28-27
3   2025-12-03_10-28-27
4   2025-12-03_10-28-28
..                  ...
70  2026-01-29_11-19-08
71  2026-01-29_11-19-09
72  2026-01-29_11-19-09
73  2026-01-29_11-19-10
74  2026-01-29_11-19-11

[19085 rows x 8 columns]

In [8]:

metadata_segments["Partial_Header_temp"] = metadata_segments["Isolate"] # Get only isolate

for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]: # Forbidden punctuation
    metadata_segments["Partial_Header_temp"] = metadata_segments["Partial_Header_temp"].apply(lambda x: x.replace(c, "_") if x == x else x)

# Merge to get already-genotyped segments
genoflu_old["Partial_Header_temp"] = genoflu_old["Strain"].apply(lambda x: re.split(r'Influenza_A_virus__\D*__\D*_', x)[-1]) # Get only isolate 
genoflu_old["Partial_Header_temp"] = genoflu_old["Partial_Header_temp"].apply(lambda x: re.split(r'_H.N._20.{2}_.{2}_.{2}', x)[0]) # Get only isolate

metadata_segments_old = metadata_segments.merge(genoflu_old, how="inner", on="Partial_Header_temp") 

# Isolate not-already-genotyped segments
metadata_segments_new = metadata_segments.merge(genoflu_old, indicator=True, how='left', on="Partial_Header_temp").loc[lambda x : x['_merge']=='left_only'] 

print(len(metadata_segments_old))
print(len(metadata_segments_new))

89336
35424

In [9]:
# Get genoflu results from Andersen and see if any fit

os.chdir(andersen)

genoflu_andersen = pd.read_csv("genoflu_results.tsv", delimiter="\t")
genoflu_andersen = genoflu_andersen.rename(columns={"sample":"SRA_Accession"}) # So we can merge with old
# genoflu_andersen["SRA_Accession"] = genoflu_andersen["Strain"] # So we can merge with new

# Find those genotyped by Andersen via merge
metadata_segments_known_andersen = metadata_segments_new.merge(genoflu_andersen, how="inner", on="SRA_Accession")
print(metadata_segments_known_andersen)
# Rename genotype by Andersen to concatenate
metadata_segments_known_andersen["Genotype_y"] = metadata_segments_known_andersen["Genotype"]

# Keep all known genotypes
metadata_segments_known = pd.concat([metadata_segments_old, metadata_segments_known_andersen]) # , on="SRA_Accession", how="left") # Since we know both of these

print(metadata_segments_old)
print(metadata_segments_known_andersen)

       Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0     PZ008639.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
1     PZ008640.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
2     PZ008641.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
3     PZ008642.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
4     PZ008643.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
...          ...            ...              ...           ...           ...
6171  PQ012131.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
6172  PQ012132.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
6173  PQ012133.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
6174  PQ012134.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
6175  PQ012135.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639

        BioProject      Organism_Name                         Species  \
0     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
1     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
2     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
3     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
4     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
...            ...                ...                             ...
6171  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
6172  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
6173  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
6174  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
6175  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                    Genus            Family  ... Date run     _merge  \
0     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
1     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
2     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
...                   ...               ...  ...      ...        ...
6171  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
6172  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
6173  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
6174  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
6175  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only

                     date       File Name  \
0     2026-01-16_05-26-12  SRR36856000.fa
1     2026-01-16_05-26-12  SRR36856000.fa
2     2026-01-16_05-26-12  SRR36856000.fa
3     2026-01-16_05-26-12  SRR36856000.fa
4     2026-01-16_05-26-12  SRR36856000.fa
...                   ...             ...
6171  2025-05-09_10-47-50  SRR29281472.fa
6172  2025-05-09_10-47-50  SRR29281472.fa
6173  2025-05-09_10-47-50  SRR29281472.fa
6174  2025-05-09_10-47-50  SRR29281472.fa
6175  2025-05-09_10-47-50  SRR29281472.fa

                                 Genotype  \
0     Not assigned: No Matching Genotypes
1     Not assigned: No Matching Genotypes
2     Not assigned: No Matching Genotypes
3     Not assigned: No Matching Genotypes
4     Not assigned: No Matching Genotypes
...                                   ...
6171                                B3.13
6172                                B3.13
6173                                B3.13
6174                                B3.13
6175                                B3.13

                          Genotype List Used, >=98.0%_y  \
0     NP:am1.1, NS:ea3, PB1:ea3, MP:ea3, PA:am4, PB2...
1     NP:am1.1, NS:ea3, PB1:ea3, MP:ea3, PA:am4, PB2...
2     NP:am1.1, NS:ea3, PB1:ea3, MP:ea3, PA:am4, PB2...
3     NP:am1.1, NS:ea3, PB1:ea3, MP:ea3, PA:am4, PB2...
4     NP:am1.1, NS:ea3, PB1:ea3, MP:ea3, PA:am4, PB2...
...                                                 ...
6171  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
6172  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
6173  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
6174  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
6175  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...

                           Genotype Sample Title List_y  \
0     am1.1:22-007805-001:NP, ea3:22-013001-001:NS, ...
1     am1.1:22-007805-001:NP, ea3:22-013001-001:NS, ...
2     am1.1:22-007805-001:NP, ea3:22-013001-001:NS, ...
3     am1.1:22-007805-001:NP, ea3:22-013001-001:NS, ...
4     am1.1:22-007805-001:NP, ea3:22-013001-001:NS, ...
...                                                 ...
6171  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
6172  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
6173  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
6174  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
6175  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...

                          Genotype Percent Match List_y  \
0     99.00%, 98.69%, 99.16%, 99.39%, 99.14%, 99.52%...
1     99.00%, 98.69%, 99.16%, 99.39%, 99.14%, 99.52%...
2     99.00%, 98.69%, 99.16%, 99.39%, 99.14%, 99.52%...
3     99.00%, 98.69%, 99.16%, 99.39%, 99.14%, 99.52%...
4     99.00%, 98.69%, 99.16%, 99.39%, 99.14%, 99.52%...
...                                                 ...
6171  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...
6172  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...
6173  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...
6174  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...
6175  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...

           Genotype Mismatch List_y Genotype Average Depth of Coverage List_y
0     15, 11, 19, 6, 15, 11, 16, 13         Ran on FASTA - No Coverage Report
1     15, 11, 19, 6, 15, 11, 16, 13         Ran on FASTA - No Coverage Report
2     15, 11, 19, 6, 15, 11, 16, 13         Ran on FASTA - No Coverage Report
3     15, 11, 19, 6, 15, 11, 16, 13         Ran on FASTA - No Coverage Report
4     15, 11, 19, 6, 15, 11, 16, 13         Ran on FASTA - No Coverage Report
...                             ...                                       ...
6171  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report
6172  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report
6173  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report
6174  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report
6175  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report

[6176 rows x 49 columns]
        Accession GenBank_RefSeq         Assembly SRA_Accession BioSample  \
0      PX831491.1        GenBank  GCA_054448965.1           NaN       NaN
1      PX831492.1        GenBank  GCA_054448965.1           NaN       NaN
2      PX831493.1        GenBank  GCA_054448965.1           NaN       NaN
3      PX831494.1        GenBank  GCA_054448965.1           NaN       NaN
4      PX831495.1        GenBank  GCA_054448965.1           NaN       NaN
...           ...            ...              ...           ...       ...
89331  OK205667.1        GenBank  GCA_038971685.1           NaN       NaN
89332  OK205668.1        GenBank  GCA_038971685.1           NaN       NaN
89333  OK205669.1        GenBank  GCA_038971685.1           NaN       NaN
89334  OK205670.1        GenBank  GCA_038971685.1           NaN       NaN
89335  OK205671.1        GenBank  GCA_038971685.1           NaN       NaN

      BioProject      Organism_Name                         Species  \
0            NaN  Influenza A virus  Alphainfluenzavirus influenzae
1            NaN  Influenza A virus  Alphainfluenzavirus influenzae
2            NaN  Influenza A virus  Alphainfluenzavirus influenzae
3            NaN  Influenza A virus  Alphainfluenzavirus influenzae
4            NaN  Influenza A virus  Alphainfluenzavirus influenzae
...          ...                ...                             ...
89331        NaN  Influenza A virus  Alphainfluenzavirus influenzae
89332        NaN  Influenza A virus  Alphainfluenzavirus influenzae
89333        NaN  Influenza A virus  Alphainfluenzavirus influenzae
89334        NaN  Influenza A virus  Alphainfluenzavirus influenzae
89335        NaN  Influenza A virus  Alphainfluenzavirus influenzae

                     Genus            Family  ...  \
0      Alphainfluenzavirus  Orthomyxoviridae  ...
1      Alphainfluenzavirus  Orthomyxoviridae  ...
2      Alphainfluenzavirus  Orthomyxoviridae  ...
3      Alphainfluenzavirus  Orthomyxoviridae  ...
4      Alphainfluenzavirus  Orthomyxoviridae  ...
...                    ...               ...  ...
89331  Alphainfluenzavirus  Orthomyxoviridae  ...
89332  Alphainfluenzavirus  Orthomyxoviridae  ...
89333  Alphainfluenzavirus  Orthomyxoviridae  ...
89334  Alphainfluenzavirus  Orthomyxoviridae  ...
89335  Alphainfluenzavirus  Orthomyxoviridae  ...

                                                sequence Partial_Header_temp  \
0      AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...         063224_24_1
1      AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACCTTAC...         063224_24_1
2      AGCAAAAGCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAAT...         063224_24_1
3      AGCAAAAGCAGGGGTTCACTCTGTCAAAATGGAGAACATAGTACTA...         063224_24_1
4      AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...         063224_24_1
...                                                  ...                 ...
89331  ATGGAAAGAATAGCAATTGCCTTTGCATTAATCAGCATTGTCACAG...         LVVX17186_2
89332  GTAGATAATCACTCACTGAGTGACATTCACATCATGGCGTCTCAAG...         LVVX17186_2
89333  AATGAATCCAAATCAGAAAATAATAACAATAGGCTCCATTTCTCTA...         LVVX17186_2
89334  TAGATGTTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTT...         LVVX17186_2
89335  GTGACAAATACATAATGGACTCCAACACGATAACCTCGTTTCAGGT...         LVVX17186_2

                                                  Strain  \
0      Influenza_A_virus__USA__Texas_063224_24_1_H5N1...
1      Influenza_A_virus__USA__Texas_063224_24_1_H5N1...
2      Influenza_A_virus__USA__Texas_063224_24_1_H5N1...
3      Influenza_A_virus__USA__Texas_063224_24_1_H5N1...
4      Influenza_A_virus__USA__Texas_063224_24_1_H5N1...
...                                                  ...
89331  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
89332  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
89333  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
89334  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
89335  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...

                                              Genotype_y  \
0                                                  B3.13
1                                                  B3.13
2                                                  B3.13
3                                                  B3.13
4                                                  B3.13
...                                                  ...
89331  Not assigned: Only 0 segments >98.0% match fou...
89332  Not assigned: Only 0 segments >98.0% match fou...
89333  Not assigned: Only 0 segments >98.0% match fou...
89334  Not assigned: Only 0 segments >98.0% match fou...
89335  Not assigned: Only 0 segments >98.0% match fou...

                             Genotype List Used, >=98.0%  \
0      PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
1      PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
2      PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3      PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
4      PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
...                                                  ...
89331                                                NaN
89332                                                NaN
89333                                                NaN
89334                                                NaN
89335                                                NaN

                              Genotype Sample Title List  \
0      am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
1      am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
2      am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3      am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
4      am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
...                                                  ...
89331  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
89332  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
89333  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
89334  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
89335  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...

                             Genotype Percent Match List  \
0      98.86%, 99.56%, 99.16%, 98.77%, 99.40%, 99.15%...
1      98.86%, 99.56%, 99.16%, 98.77%, 99.40%, 99.15%...
2      98.86%, 99.56%, 99.16%, 98.77%, 99.40%, 99.15%...
3      98.86%, 99.56%, 99.16%, 98.77%, 99.40%, 99.15%...
4      98.86%, 99.56%, 99.16%, 98.77%, 99.40%, 99.15%...
...                                                  ...
89331  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
89332  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
89333  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
89334  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
89335  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...

                     Genotype Mismatch List  \
0              26, 10, 18, 21, 9, 12, 11, 6
1              26, 10, 18, 21, 9, 12, 11, 6
2              26, 10, 18, 21, 9, 12, 11, 6
3              26, 10, 18, 21, 9, 12, 11, 6
4              26, 10, 18, 21, 9, 12, 11, 6
...                                     ...
89331  176, 113, 256, 363, 151, 171, 82, 77
89332  176, 113, 256, 363, 151, 171, 82, 77
89333  176, 113, 256, 363, 151, 171, 82, 77
89334  176, 113, 256, 363, 151, 171, 82, 77
89335  176, 113, 256, 363, 151, 171, 82, 77

      Genotype Average Depth of Coverage List             Date run
0           Ran on FASTA - No Coverage Report  2026-01-12_12-08-38
1           Ran on FASTA - No Coverage Report  2026-01-12_12-08-38
2           Ran on FASTA - No Coverage Report  2026-01-12_12-08-38
3           Ran on FASTA - No Coverage Report  2026-01-12_12-08-38
4           Ran on FASTA - No Coverage Report  2026-01-12_12-08-38
...                                       ...                  ...
89331       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
89332       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
89333       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
89334       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
89335       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44

[89336 rows x 40 columns]
       Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0     PZ008639.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
1     PZ008640.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
2     PZ008641.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
3     PZ008642.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
4     PZ008643.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
...          ...            ...              ...           ...           ...
6171  PQ012131.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
6172  PQ012132.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
6173  PQ012133.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
6174  PQ012134.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
6175  PQ012135.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639

        BioProject      Organism_Name                         Species  \
0     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
1     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
2     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
3     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
4     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
...            ...                ...                             ...
6171  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
6172  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
6173  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
6174  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
6175  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                    Genus            Family  ... Date run     _merge  \
0     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
1     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
2     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
...                   ...               ...  ...      ...        ...
6171  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
6172  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
6173  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
6174  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
6175  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only

                     date       File Name  \
0     2026-01-16_05-26-12  SRR36856000.fa
1     2026-01-16_05-26-12  SRR36856000.fa
2     2026-01-16_05-26-12  SRR36856000.fa
3     2026-01-16_05-26-12  SRR36856000.fa
4     2026-01-16_05-26-12  SRR36856000.fa
...                   ...             ...
6171  2025-05-09_10-47-50  SRR29281472.fa
6172  2025-05-09_10-47-50  SRR29281472.fa
6173  2025-05-09_10-47-50  SRR29281472.fa
6174  2025-05-09_10-47-50  SRR29281472.fa
6175  2025-05-09_10-47-50  SRR29281472.fa

                                 Genotype  \
0     Not assigned: No Matching Genotypes
1     Not assigned: No Matching Genotypes
2     Not assigned: No Matching Genotypes
3     Not assigned: No Matching Genotypes
4     Not assigned: No Matching Genotypes
...                                   ...
6171                                B3.13
6172                                B3.13
6173                                B3.13
6174                                B3.13
6175                                B3.13

                          Genotype List Used, >=98.0%_y  \
0     NP:am1.1, NS:ea3, PB1:ea3, MP:ea3, PA:am4, PB2...
1     NP:am1.1, NS:ea3, PB1:ea3, MP:ea3, PA:am4, PB2...
2     NP:am1.1, NS:ea3, PB1:ea3, MP:ea3, PA:am4, PB2...
3     NP:am1.1, NS:ea3, PB1:ea3, MP:ea3, PA:am4, PB2...
4     NP:am1.1, NS:ea3, PB1:ea3, MP:ea3, PA:am4, PB2...
...                                                 ...
6171  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
6172  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
6173  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
6174  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
6175  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...

                           Genotype Sample Title List_y  \
0     am1.1:22-007805-001:NP, ea3:22-013001-001:NS, ...
1     am1.1:22-007805-001:NP, ea3:22-013001-001:NS, ...
2     am1.1:22-007805-001:NP, ea3:22-013001-001:NS, ...
3     am1.1:22-007805-001:NP, ea3:22-013001-001:NS, ...
4     am1.1:22-007805-001:NP, ea3:22-013001-001:NS, ...
...                                                 ...
6171  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
6172  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
6173  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
6174  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
6175  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...

                          Genotype Percent Match List_y  \
0     99.00%, 98.69%, 99.16%, 99.39%, 99.14%, 99.52%...
1     99.00%, 98.69%, 99.16%, 99.39%, 99.14%, 99.52%...
2     99.00%, 98.69%, 99.16%, 99.39%, 99.14%, 99.52%...
3     99.00%, 98.69%, 99.16%, 99.39%, 99.14%, 99.52%...
4     99.00%, 98.69%, 99.16%, 99.39%, 99.14%, 99.52%...

### Create FASTA files of unknown genotypes

In [10]:
metadata_segments_known

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Genotype Average Depth of Coverage List_x,_merge,date,File Name,Genotype,"Genotype List Used, >=98.0%_y",Genotype Sample Title List_y,Genotype Percent Match List_y,Genotype Mismatch List_y,Genotype Average Depth of Coverage List_y
0,PX831491.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PX831492.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PX831493.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PX831494.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PX831495.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6171,PQ012131.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report
6172,PQ012132.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report
6173,PQ012133.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report
6174,PQ012134.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report
6175,PQ012135.1,GenBank,GCA_040780295.1,SRR29281472,SAMN41656639,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,left_only,2025-05-09_10-47-50,SRR29281472.fa,B3.13,"NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...","am8:23-032005-001:NP, ea1:22-003707-003:NA, am...","99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...","13, 15, 6, 29, 11, 22, 22, 10",Ran on FASTA - No Coverage Report

In [12]:
# Create 8 fasta files per segment

# Get all the segments
metadata_segments_new["Partial_Header"] = metadata_segments_new["Assembly"].apply(lambda x: ">" + x if x == x else x) # .apply(lambda x: x.split("|")[-1].split(")")[0]) # Get only genbank name

print(metadata_segments_new["Partial_Header"].values[0:5])

# Create list of dataframes
df_list = []
for partial_header in list(set(metadata_segments_new["Partial_Header"].values)): # Unique partial headers only
    # Get smaller dataframe
    df = metadata_segments_new[metadata_segments_new["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    # Make sure there are 8 segments
    if len(df) == 8:
        # Forbidden characters in headers
        for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]:
            df["Partial_Header"] = df["Partial_Header"].apply(lambda x: x.replace(c, "_"))
            
        df["full_header"] = df["Partial_Header"]
        df_list.append(df)

print(metadata_segments_new["Partial_Header"])

print(df_list[0]["full_header"].values[:10])

# Make fasta files
for df in df_list:
    segments = list(set(df["Segment"].apply(lambda x: int(x)).values))
    for segment in segments:
        one_row = df[df["Segment"] == segment]
        df_to_fasta(one_row, str(segment) + "_seg.fasta", temp_files)

['>GCA_055411775.1' '>GCA_055411775.1' '>GCA_055411775.1'
 '>GCA_055411775.1' '>GCA_055411775.1']
0         >GCA_055411775.1
1         >GCA_055411775.1
2         >GCA_055411775.1
3         >GCA_055411775.1
4         >GCA_055411775.1
                ...
124755    >GCA_038165665.1
124756    >GCA_038165665.1
124757    >GCA_038165665.1
124758    >GCA_038165665.1
124759    >GCA_038165665.1
Name: Partial_Header, Length: 35424, dtype: object
['>GCA_054871925_1' '>GCA_054871925_1' '>GCA_054871925_1'
 '>GCA_054871925_1' '>GCA_054871925_1' '>GCA_054871925_1'
 '>GCA_054871925_1' '>GCA_054871925_1']

### Re-Labeling Using GenoFlu

**STOP HERE AND USE GENOFLU TO FIND NEW GENOTYPES.** Then, make sure "results.tsv" is in the NCBI_Virus downloads directory. <br>

To activate genoflu conda environment in BioWulf:
```
source myconda
conda activate genoflu
```

To run GenoFLU-multi, change directories to Multi-GenoFLU directory:
``` 
cd GenoFLU-multi
```

And then call the python script:

``` 
python bin/genoflu-multi.py -f <FASTA_directory>
```

In [ ]:
# Ensure that user does the above
input("Use genoflu. Afterwards, press ENTER to continue.")

''

In [13]:
# Merging

os.chdir(downloads_saved)

# Read in genoflu results
output_genoflu = pd.read_csv("results.tsv", delimiter="\t") # This also shows the IDs of the new sequences -- incorporate into sequences report

# Create partial headers to merge genoflu results with previously unknown segments
metadata_segments_new["Partial_Header_Merge"] = metadata_segments_new["Assembly"] 
for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]: # Forbidden punctuation
    metadata_segments_new["Partial_Header_Merge"] = metadata_segments_new["Partial_Header_Merge"].apply(lambda x: x.replace(c, "_") if x==x else x)

# Reformat so we can merge
output_genoflu["Partial_Header_Merge"] = output_genoflu["Strain"] #.apply(lambda x: re.split(r'Influenza_A_virus__\D*__\D*_', x)[-1])
# output_genoflu["Partial_Header_Merge"] = output_genoflu["Partial_Header_Merge"].apply(lambda x: re.split(r'_H.N._(20|19).{2}_.{2}_.{2}', x)[0])

# Merge
metadata_genoflu = metadata_segments_new.merge(output_genoflu, how="inner", on="Partial_Header_Merge") #, suffixes=('_left', '_right')) 

# Fill the rest of the 8 segments with the same genotype
metadata_genoflu = metadata_genoflu.ffill(limit_area="inside")



print(metadata_genoflu)

       Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0     PZ008639.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
1     PZ008640.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
2     PZ008641.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
3     PZ008642.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
4     PZ008643.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
...          ...            ...              ...           ...           ...
1243  PX934299.1        GenBank  GCA_054864435.1           NaN           NaN
1244  PX934300.1        GenBank  GCA_054864435.1           NaN           NaN
1245  PX934301.1        GenBank  GCA_054864435.1           NaN           NaN
1246  PX934302.1        GenBank  GCA_054864435.1           NaN           NaN
1247  PX934303.1        GenBank  GCA_054864435.1           NaN           NaN

        BioProject      Organism_Name                         Species  \
0     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
1     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
2     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
3     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
4     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
...            ...                ...                             ...
1243           NaN  Influenza A virus  Alphainfluenzavirus influenzae
1244           NaN  Influenza A virus  Alphainfluenzavirus influenzae
1245           NaN  Influenza A virus  Alphainfluenzavirus influenzae
1246           NaN  Influenza A virus  Alphainfluenzavirus influenzae
1247           NaN  Influenza A virus  Alphainfluenzavirus influenzae

                    Genus            Family  ...    Partial_Header  \
0     Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_055411335.1
1     Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_055411335.1
2     Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_055411335.1
3     Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_055411335.1
4     Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_055411335.1
...                   ...               ...  ...               ...
1243  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_054864435.1
1244  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_054864435.1
1245  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_054864435.1
1246  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_054864435.1
1247  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_054864435.1

     Partial_Header_Merge         Strain_y  \
0         GCA_055411335_1  GCA_055411335_1
1         GCA_055411335_1  GCA_055411335_1
2         GCA_055411335_1  GCA_055411335_1
3         GCA_055411335_1  GCA_055411335_1
4         GCA_055411335_1  GCA_055411335_1
...                   ...              ...
1243      GCA_054864435_1  GCA_054864435_1
1244      GCA_054864435_1  GCA_054864435_1
1245      GCA_054864435_1  GCA_054864435_1
1246      GCA_054864435_1  GCA_054864435_1
1247      GCA_054864435_1  GCA_054864435_1

                                 Genotype  \
0     Not assigned: No Matching Genotypes
1     Not assigned: No Matching Genotypes
2     Not assigned: No Matching Genotypes
3     Not assigned: No Matching Genotypes
4     Not assigned: No Matching Genotypes
...                                   ...
1243                                 D1.1
1244                                 D1.1
1245                                 D1.1
1246                                 D1.1
1247                                 D1.1

                          Genotype List Used, >=98.0%_y  \
0     NA:am4N1, NS:ea3, PB1:ea3, NP:am1.1, HA:ea3, M...
1     NA:am4N1, NS:ea3, PB1:ea3, NP:am1.1, HA:ea3, M...
2     NA:am4N1, NS:ea3, PB1:ea3, NP:am1.1, HA:ea3, M...
3     NA:am4N1, NS:ea3, PB1:ea3, NP:am1.1, HA:ea3, M...
4     NA:am4N1, NS:ea3, PB1:ea3, NP:am1.1, HA:ea3, M...
...                                                 ...
1243  NA:am4N1, NS:ea3, PB1:ea3, NP:am13, HA:ea3, MP...
1244  NA:am4N1, NS:ea3, PB1:ea3, NP:am13, HA:ea3, MP...
1245  NA:am4N1, NS:ea3, PB1:ea3, NP:am13, HA:ea3, MP...
1246  NA:am4N1, NS:ea3, PB1:ea3, NP:am13, HA:ea3, MP...
1247  NA:am4N1, NS:ea3, PB1:ea3, NP:am13, HA:ea3, MP...

                           Genotype Sample Title List_y  \
0     am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
1     am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
2     am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
3     am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
4     am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
...                                                 ...
1243  am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
1244  am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
1245  am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
1246  am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
1247  am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...

                          Genotype Percent Match List_y  \
0     98.79%, 98.69%, 99.16%, 99.00%, 99.06%, 99.39%...
1     98.79%, 98.69%, 99.16%, 99.00%, 99.06%, 99.39%...
2     98.79%, 98.69%, 99.16%, 99.00%, 99.06%, 99.39%...
3     98.79%, 98.69%, 99.16%, 99.00%, 99.06%, 99.39%...
4     98.79%, 98.69%, 99.16%, 99.00%, 99.06%, 99.39%...
...                                                 ...
1243  99.43%, 99.05%, 99.30%, 99.73%, 99.47%, 99.90%...
1244  99.43%, 99.05%, 99.30%, 99.73%, 99.47%, 99.90%...
1245  99.43%, 99.05%, 99.30%, 99.73%, 99.47%, 99.90%...
1246  99.43%, 99.05%, 99.30%, 99.73%, 99.47%, 99.90%...
1247  99.43%, 99.05%, 99.30%, 99.73%, 99.47%, 99.90%...

           Genotype Mismatch List_y Genotype Average Depth of Coverage List_y  \
0     17, 11, 19, 15, 16, 6, 18, 11         Ran on FASTA - No Coverage Report
1     17, 11, 19, 15, 16, 6, 18, 11         Ran on FASTA - No Coverage Report
2     17, 11, 19, 15, 16, 6, 18, 11         Ran on FASTA - No Coverage Report
3     17, 11, 19, 15, 16, 6, 18, 11         Ran on FASTA - No Coverage Report
4     17, 11, 19, 15, 16, 6, 18, 11         Ran on FASTA - No Coverage Report
...                             ...                                       ...
1243       8, 8, 16, 4, 9, 1, 10, 7         Ran on FASTA - No Coverage Report
1244       8, 8, 16, 4, 9, 1, 10, 7         Ran on FASTA - No Coverage Report
1245       8, 8, 16, 4, 9, 1, 10, 7         Ran on FASTA - No Coverage Report
1246       8, 8, 16, 4, 9, 1, 10, 7         Ran on FASTA - No Coverage Report
1247       8, 8, 16, 4, 9, 1, 10, 7         Ran on FASTA - No Coverage Report

               Date run_y
0     2026-02-24_09-45-21
1     2026-02-24_09-45-21
2     2026-02-24_09-45-21
3     2026-02-24_09-45-21
4     2026-02-24_09-45-21
...                   ...
1243  2026-02-24_09-45-23
1244  2026-02-24_09-45-23
1245  2026-02-24_09-45-23
1246  2026-02-24_09-45-23
1247  2026-02-24_09-45-23

[1248 rows x 51 columns]

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_58640\2836936310.py:21: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  metadata_genoflu = metadata_genoflu.ffill(limit_area="inside")

### Concatenate with known genotypes

In [14]:
# Rename columns so we can concatenate
print(metadata_segments_known.columns)

metadata_segments_known = metadata_segments_known.reset_index(drop=True)
print(metadata_segments_known)

print(metadata_genoflu.columns)
metadata_segments_known["Genotype_official"] = metadata_segments_known["Genotype_y"]
metadata_segments_known["Serotype"] = metadata_segments_known["Genotype_x"]
metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype"]
metadata_genoflu["Serotype"] = metadata_genoflu["Genotype_x"]

metadata_genoflu = metadata_genoflu.reset_index(drop=True)
print(metadata_genoflu)

# Concatenation
metadata_genoflu_concat = pd.concat([metadata_segments_known, metadata_genoflu])

metadata_genoflu_concat

Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Partial_Header_temp', 'Strain',
       'Genotype_y', 'Genotype List Used, >=98.0%',
       'Genotype Sample Title List', 'Genotype Percent Match List',
       'Genotype Mismatch List', 'Genotype Average Depth of Coverage List',
       'Date run', 'Genotype List Used, >=98.0%_x',
       'Genotype Sample Title List_x', 'Genotype Percent Match List_x',
       'Genotype Mismatch List_x', 'Genotype Average Depth of Coverage List_x',
       '_merge', 'date', 'File Name', 'Genotype',
       'Genotype List Used, >=98.0%_y', 'Genotype Sample Title List_y',
       'Genotype Percent Match List_y', 'Genotype Mismatch List_y',
       'Genotype Average Depth of Coverage List_y'],
      dtype='object')
        Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0      PX831491.1        GenBank  GCA_054448965.1           NaN           NaN
1      PX831492.1        GenBank  GCA_054448965.1           NaN           NaN
2      PX831493.1        GenBank  GCA_054448965.1           NaN           NaN
3      PX831494.1        GenBank  GCA_054448965.1           NaN           NaN
4      PX831495.1        GenBank  GCA_054448965.1           NaN           NaN
...           ...            ...              ...           ...           ...
95507  PQ012131.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
95508  PQ012132.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
95509  PQ012133.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
95510  PQ012134.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
95511  PQ012135.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639

         BioProject      Organism_Name                         Species  \
0               NaN  Influenza A virus  Alphainfluenzavirus influenzae
1               NaN  Influenza A virus  Alphainfluenzavirus influenzae
2               NaN  Influenza A virus  Alphainfluenzavirus influenzae
3               NaN  Influenza A virus  Alphainfluenzavirus influenzae
4               NaN  Influenza A virus  Alphainfluenzavirus influenzae
...             ...                ...                             ...
95507  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
95508  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
95509  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
95510  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
95511  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                     Genus            Family  ...  \
0      Alphainfluenzavirus  Orthomyxoviridae  ...
1      Alphainfluenzavirus  Orthomyxoviridae  ...
2      Alphainfluenzavirus  Orthomyxoviridae  ...
3      Alphainfluenzavirus  Orthomyxoviridae  ...
4      Alphainfluenzavirus  Orthomyxoviridae  ...
...                    ...               ...  ...
95507  Alphainfluenzavirus  Orthomyxoviridae  ...
95508  Alphainfluenzavirus  Orthomyxoviridae  ...
95509  Alphainfluenzavirus  Orthomyxoviridae  ...
95510  Alphainfluenzavirus  Orthomyxoviridae  ...
95511  Alphainfluenzavirus  Orthomyxoviridae  ...

      Genotype Average Depth of Coverage List_x     _merge  \
0                                           NaN        NaN
1                                           NaN        NaN
2                                           NaN        NaN
3                                           NaN        NaN
4                                           NaN        NaN
...                                         ...        ...
95507                                       NaN  left_only
95508                                       NaN  left_only
95509                                       NaN  left_only
95510                                       NaN  left_only
95511                                       NaN  left_only

                      date       File Name  Genotype  \
0                      NaN             NaN       NaN
1                      NaN             NaN       NaN
2                      NaN             NaN       NaN
3                      NaN             NaN       NaN
4                      NaN             NaN       NaN
...                    ...             ...       ...
95507  2025-05-09_10-47-50  SRR29281472.fa     B3.13
95508  2025-05-09_10-47-50  SRR29281472.fa     B3.13
95509  2025-05-09_10-47-50  SRR29281472.fa     B3.13
95510  2025-05-09_10-47-50  SRR29281472.fa     B3.13
95511  2025-05-09_10-47-50  SRR29281472.fa     B3.13

                           Genotype List Used, >=98.0%_y  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
95507  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
95508  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
95509  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
95510  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
95511  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...

                            Genotype Sample Title List_y  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
95507  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
95508  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
95509  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
95510  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
95511  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...

                           Genotype Percent Match List_y  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
95507  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...
95508  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...
95509  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...
95510  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...
95511  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...

            Genotype Mismatch List_y Genotype Average Depth of Coverage List_y
0                                NaN                                       NaN
1                                NaN                                       NaN
2                                NaN                                       NaN
3                                NaN                                       NaN
4                                NaN                                       NaN
...                              ...                                       ...
95507  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report
95508  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report
95509  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report
95510  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report
95511  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report

[95512 rows x 54 columns]
Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Partial_Header_temp', 'Strain_x',
       'Genotype_y', 'Genotype List Used, >=98.0%_x',
       'Genotype Sample Title List_x', 'Genotype Percent Match List_x',
       'Genotype Mismatch List_x', 'Genotype Average Depth of Coverage List_x',
       'Date run_x', '_merge', 'Partial_Header', 'Partial_Header_Merge',
       'Strain_y', 'Genotype', 'Genotype List Used, >=98.0%_y',
       'Genotype Sample Title List_y', 'Genotype Percent Match List_y',
       'Genotype Mismatch List_y', 'Genotype Average Depth of Coverage List_y',
       'Date run_y'],
      dtype='object')
       Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0     PZ008639.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
1     PZ008640.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
2     PZ008641.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
3     PZ008642.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
4     PZ008643.1        GenBank  GCA_055411335.1   SRR36856000  SAMN54681016
...          ...            ...              ...           ...           ...
1243  PX934299.1        GenBank  GCA_054864435.1           NaN           NaN
1244  PX934300.1        GenBank  GCA_054864435.1           NaN           NaN
1245  PX934301.1        GenBank  GCA_054864435.1           NaN           NaN
1246  PX934302.1        GenBank  GCA_054864435.1           NaN           NaN
1247  PX934303.1        GenBank  GCA_054864435.1           NaN           NaN

        BioProject      Organism_Name                         Species  \
0     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
1     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
2     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
3     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
4     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
...            ...                ...                             ...
1243           NaN  Influenza A virus  Alphainfluenzavirus influenzae
1244           NaN  Influenza A virus  Alphainfluenzavirus influenzae
1245           NaN  Influenza A virus  Alphainfluenzavirus influenzae
1246           NaN  Influenza A virus  Alphainfluenzavirus influenzae
1247           NaN  Influenza A virus  Alphainfluenzavirus influenzae

                    Genus            Family  ...         Strain_y  \
0     Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_055411335_1
1     Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_055411335_1
2     Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_055411335_1
3     Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_055411335_1
4     Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_055411335_1
...                   ...               ...  ...              ...
1243  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_054864435_1
1244  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_054864435_1
1245  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_054864435_1
1246  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_054864435_1
1247  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_054864435_1

                                 Genotype  \
0     Not assigned: No Matching Genotypes
1     Not assigned: No Matching Genotypes
2     Not assigned: No Matching Genotypes
3     Not assigned: No Matching Genotypes
4     Not assigned: No Matching Genotypes
...                                   ...
1243                                 D1.1
1244                                 D1.1
1245                                 D1.1
1246                                 D1.1
1247                                 D1.1

                          Genotype List Used, >=98.0%_y  \
0     NA:am4N1, NS:ea3, PB1:ea3, NP:am1.1, HA:ea3, M...
1     NA:am4N1, NS:ea3, PB1:ea3, NP:am1.1, HA:ea3, M...
2     NA:am4N1, NS:ea3, PB1:ea3, NP:am1.1, HA:ea3, M...
3     NA:am4N1, NS:ea3, PB1:ea3, NP:am1.1, HA:ea3, M...
4     NA:am4N1, NS:ea3, PB1:ea3, NP:am1.1, HA:ea3, M...
...                                                 ...
1243  NA:am4N1, NS:ea3, PB1:ea3, NP:am13, HA:ea3, MP...
1244  NA:am4N1, NS:ea3, PB1:ea3, NP:am13, HA:ea3, MP...
1245  NA:am4N1, NS:ea3, PB1:ea3, NP:am13, HA:ea3, MP...
1246  NA:am4N1, NS:ea3, PB1:ea3, NP:am13, HA:ea3, MP...
1247  NA:am4N1, NS:ea3, PB1:ea3, NP:am13, HA:ea3, MP...

                           Genotype Sample Title List_y  \
0     am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
1     am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
2     am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
3     am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
4     am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
...                                                 ...
1243  am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
1244  am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
1245  am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
1246  am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...
1247  am4N1:24-030039-001:NA, ea3:22-013001-001:NS, ...

                          Genotype Percent Match List_y  \
0     98.79%, 98.69%, 99.16%, 99.00%, 99.06%, 99.39%...
1     98.79%, 98.69%, 99.16%, 99.00%, 99.06%, 99.39%...
2     98.79%, 98.69%, 99.16%, 99.00%, 99.06%, 99.39%...
3     98.79%, 98.69%, 99.16%, 99.00%, 99.06%, 99.39%...
4     98.79%, 98.69%, 99.16%, 99.00%, 99.06%, 99.39%...
...                                                 ...
1243  99.43%, 99.05%, 99.30%, 99.73%, 99.47%, 99.90%...
1244  99.43%, 99.05%, 99.30%, 99.73%, 99.47%, 99.90%...
1245  99.43%, 99.05%, 99.30%, 99.73%, 99.47%, 99.90%...
1246  99.43%, 99.05%, 99.30%, 99.73%, 99.47%, 99.90%...
1247  99.43%, 99.05%, 99.30%, 99.73%, 99.47%, 99.90%...

           Genotype Mismatch List_y Genotype Average Depth of Coverage List_y  \
0     17, 11, 19, 15, 16, 6, 18, 11         Ran on FASTA - No Coverage Report
1     17, 11, 19, 15, 16, 6, 18, 11         Ran on FASTA - No Coverage Report
2     17, 11, 19, 15, 16, 6, 18, 11         Ran on FASTA - No Coverage Report
3     17, 11, 19, 15, 16, 6, 18, 11         Ran on FASTA - No Coverage Report
4     17, 11, 19, 15, 16, 6, 18, 11         Ran on FASTA - No Coverage Report
...                             ...                                       ...
1243       8, 8, 16, 4, 9, 1, 10, 7         Ran on FASTA - No Coverage Report
1244       8, 8, 16, 4, 9, 1, 10, 7         Ran on FASTA - No Coverage Report
1245       8, 8, 16, 4, 9, 1, 10, 7         Ran on FASTA - No Coverage Report
1246       8, 8, 16, 4, 9, 1, 10, 7         Ran on FASTA - No Coverage Report
1247       8, 8, 16, 4, 9, 1, 10, 7         Ran on FASTA - No Coverage Report

               Date run_y                    Genotype_official Serotype
0     2026-02-24_09-45-21  Not assigned: No Matching Genotypes     H5N1
1     2026-02-24_09-45-21  Not assigned: No Matching Genotypes     H5N1
2     2026-02-24_09-45-21  Not assigned: No Matching Genotypes     H5N1
3     2026-02-24_09-45-21  Not assigned: No Matching Genotypes     H5N1
4     2026-02-24_09-45-21  Not assigned: No Matching Genotypes     H5N1
...                   ...                                  ...      ...
1243  2026-02-24_09-45-23                                 D1.1     H5N1
1244  2026-02-24_09-45-23                                 D1.1     H5N1
1245  2026-02-24_09-45-23                                 D1.1     H5N1
1246  2026-02-24_09-45-23                                 D1.1     H5N1
1247  2026-02-24_09-45-23                                 D1.1     H5N1

[1248 rows x 53 columns]

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Genotype Mismatch List_y,Genotype Average Depth of Coverage List_y,Genotype_official,Serotype,Strain_x,Date run_x,Partial_Header,Partial_Header_Merge,Strain_y,Date run_y
0,PX831491.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,B3.13,H5N1,NaN,NaN,NaN,NaN,NaN,NaN
1,PX831492.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,B3.13,H5N1,NaN,NaN,NaN,NaN,NaN,NaN
2,PX831493.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,B3.13,H5N1,NaN,NaN,NaN,NaN,NaN,NaN
3,PX831494.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,B3.13,H5N1,NaN,NaN,NaN,NaN,NaN,NaN
4,PX831495.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,B3.13,H5N1,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1243,PX934299.1,GenBank,GCA_054864435.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"8, 8, 16, 4, 9, 1, 10, 7",Ran on FASTA - No Coverage Report,D1.1,H5N1,NaN,NaN,>GCA_054864435.1,GCA_054864435_1,GCA_054864435_1,2026-02-24_09-45-23
1244,PX934300.1,GenBank,GCA_054864435.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"8, 8, 16, 4, 9, 1, 10, 7",Ran on FASTA - No Coverage Report,D1.1,H5N1,NaN,NaN,>GCA_054864435.1,GCA_054864435_1,GCA_054864435_1,2026-02-24_09-45-23
1245,PX934301.1,GenBank,GCA_054864435.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"8, 8, 16, 4, 9, 1, 10, 7",Ran on FASTA - No Coverage Report,D1.1,H5N1,NaN,NaN,>GCA_054864435.1,GCA_054864435_1,GCA_054864435_1,2026-02-24_09-45-23
1246,PX934302.1,GenBank,GCA_054864435.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"8, 8, 16, 4, 9, 1, 10, 7",Ran on FASTA - No Coverage Report,D1.1,H5N1,NaN,NaN,>GCA_054864435.1,GCA_054864435_1,GCA_054864435_1,2026-02-24_09-45-23
1247,PX934303.1,GenBank,GCA_054864435.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"8, 8, 16, 4, 9, 1, 10, 7",Ran on FASTA - No Coverage Report,D1.1,H5N1,NaN,NaN,>GCA_054864435.1,GCA_054864435_1,GCA_054864435_1,2026-02-24_09-45-23

In [15]:
# Cut down to only columns we want
metadata_genoflu_concat = metadata_genoflu_concat[["Accession", "Assembly", "GenBank_Title", "Host", "Collection_Date", "SRA_Accession", "Isolate", "Genotype_official", "Geo_Location", "full_header", "sequence", "Serotype", "Segment", "File Name", "Partial_Header"]] #, "Strain"]]

# Get genbank strain name
metadata_genoflu_concat["genbank_name"] = metadata_genoflu_concat["GenBank_Title"].apply(lambda x: x.split("(")[1] if x == x else x)
metadata_genoflu_concat["Host"] = metadata_genoflu_concat["genbank_name"].apply(lambda x: x.split("/")[1] if x == x else x)

metadata_genoflu_concat = metadata_genoflu_concat.dropna(subset="genbank_name") # [metadata_genoflu["Genotype"]  == "B3.13"]

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_58640\4267596827.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata_genoflu_concat["genbank_name"] = metadata_genoflu_concat["GenBank_Title"].apply(lambda x: x.split("(")[1] if x == x else x)
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_58640\4267596827.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata_genoflu_concat["Host"] = metadata_genoflu_concat["genbank_name"].apply(lambda x: x.split("/")[1] if x == x else x)

In [16]:
metadata_genoflu_concat

# Make sure we only have the serotype(s) we want
for serotype in serotypes:
    metadata_genoflu = metadata_genoflu[metadata_genoflu["Serotype"] == serotype]

## Relabeling Sequences

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

In [17]:
# Re-re-name so that we don't break following code

metadata_genoflu = metadata_genoflu_concat

After running the below code, **STOP TO CHECK** if any new animals appear

In [19]:
# Animals 

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genoflu)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['rock goose', 'antofagasta', 'common loon', 'crow', 'common grackle', 'northern shoveler', 'tundra swan', 'double-crested cormorant', 'pekin duck', 'green heron', 'domestic grower', 'black-legged kittiwake', 'dolphin', 'brant', 'gannet', 'red-shouldered hawk', 'rough-legged hawk', 'pheasant', 'numida meleagris', 'pet food', 'pelican', 'vulture', 'sparrow', 'short-billed gull', 'whooping crane', 'owl', 'tiger', 'long-eared owl', 'black-crowned night-heron', 'serval', 'muscovy duck', 'virginia opossum', 'feline', 'ring-necked duck', 'loon, common', 'western sandpiper', 'green winged teal', 'red-necked phalarope', 'gull', 'royal tern', 'emu', 'poultry', 'goat', 'barred owl', 'heron', 'american wood stork', 'waterfowl', 'lesser snow goose blue-morph', 'bird', 'domestic goose', 'raccoon', 'raw pet food', 'grackle', 'ring-necked pheasant', 'hermit thrush', 'buteogallus urubitinga', 'chukar partridge', 'peafowl', 'bufflehead duck', 'trumpeter swan', 'wild duck', 'great black-backed gull', 'american widgeon', 'pluvialis dominica', 'irere', 'eared grebe', 'pintail', 'thalasseus maximus', 'silver pheasant', 'bluejay', 'redhead duck', 'domestic turkey', 'parrot', 'eurasian collared dove', 'baikal teal', 'wild turkey', 'gadwall', 'american white pelican', 'avian', 'magpie', 'guinea fowl', 'western snowy plover', 'mallard', 'embden goose', 'gallus', 'common merganser', 'rosss goose', 'bufflehead', 'dairy cow', 'american woodcock', 'black turnstone', 'pig', 'falcon', 'lesser white-fronted goose', 'short-eared owl', 'domestic cat', 'sharp-shinned hawk', 'brown pelican', 'sand crane', 'glaucous gull', 'cinnamon teal', 'western grebe', 'eastern screech owl', 'european starling', 'american robin', 'american wigeon', 'cygnus melancoryphus', 'guinea', 'greater scaup', 'great egret', 'peregrine falcon', 'bovine', 'red-breasted goose', 'broad-winged hawk', 'polar bear', 'glaucous-winged gull', 'greater white-fronted goose', 'sandwich tern', 'arctic tern', 'dunlin', 'wood duck', 'great-tailed grackle', 'hawk', 'northern pintail', 'duck', 'fox', 'western screech owl', 'mountain lion', 'cygnus atratus', 'rock dove', 'neotropic cormorant', 'lesser snow goose white-morph', 'snow goose', 'mergus', 'roseate spoonbill', 'furnarius rufus', 'procellaria aequinoctialis', 'backyard bird', 'fish crow', 'rock pigeon', 'snowy plover', 'common goldeneye', 'american crow', 'comon goldeneye', 'emperor goose', 'american black duck', 'cat', 'striped skunk', 'gallus gallus', 'mottled duck', 'red-tailed hawk', 'white-winged scoter', 'sula leucogaster', 'bald eagle', 'osprey', 'crane', 'white-winged dove', 'cormorant', 'dove', 'black scoter', 'dairy cattle', 'otaria flavescens', 'redhead', 'cackling goose', 'chicken', 'house sparrow', 'mute swan', 'great-horned owl', 'lynx', 'mallard x american black duck hybrid', 'swainsons hawk', 'lesser snow goose', 'cattle milk product', 'willet', 'graylag goose', 'western gull', 'quail', 'manx shearwater', 'domestic duck', 'black skimmer', 'washington', 'mallard duck', 'black vulture', 'chukar', 'parasitic jaeger', 'sanderling', 'red-necked grebe', 'american kestrel', 'teal', 'nene goose', 'raven', 'house mouse', 'cattle', 'guineafowl', 'herring gull', 'sandhill crane', 'american goshawk', 'snowy egret', 'canvasback duck', 'american blue-winged teal', 'swan', 'american coot', 'snowy owl', 'northern harrier', 'crested caracara', 'thalasseus acuflavidus', 'pintail duck', 'savannah cat', 'american green-winged teal', 'green-winged teal', 'weasel', 'merganser', 'sterna hirundo', 'common raven', 'horned grebe', 'alpaca', 'hooded merganser', 'black swan', 'blue-winged teal', 'south polar skua', 'dendrocygna viduata', 'american pelican', 'fregata magnificens', 'eagle', 'fisher', 'red fox', 'wild goose', 'harbor seal', 'caspian tern', 'skunk', 'california gull', 'great horned owl', 'great blue heron', 'common eider', 'gadwell', 'goose', 'common tern', 'cougar', 'turkey', 'lesser scaup', 'bos taurus', 'red-breasted merganser', 'wild bird', 'barn owl', 'bobcat', 'blue jay', 'black brant', 'northern gannet', 'blue-winged and cinnamon teal', 'california condor', 'flamingo', 'swine', 'dromaius novaehollandiae', 'canada goose', 'pigeon', 'burrowing owl', 'partridge', 'megascops choliba', 'ring-billed gull', 'black-crowned night heron', 'black swift', 'turkey vulture', 'collared plover']
[]
                wild_avian domestic_avian               cattle        feline  \
0         great_horned_owl       pheasant            dairy_cow           cat
1             common_raven         turkey               cattle  domestic_cat
2            cooper's_hawk        chicken  cattle milk product     feral_cat
3             coopers_hawk          goose          bovine_milk        feline
4                  peafowl    guinea_fowl              bovine   domestic-cat
...                    ...            ...                  ...           ...
1179      american_widgeon            NaN                  NaN           NaN
1180                 finch            NaN                  NaN           NaN
1181  glaucose winged gull            NaN                  NaN           NaN
1182      chukar partridge            NaN                  NaN           NaN
1183          embden goose            NaN                  NaN           NaN

       other_mammal       human         other      pet_food  new
0        deer mouse  washington         mixed      pet food  NaN
1       house_mouse      nevada   environment  raw pet food  NaN
2             skunk     wyoming  multispecies  raw_pet_food  NaN
3     striped_skunk  california       unknown      pet_food  NaN
4        norway rat    michigan             '           NaN  NaN
...             ...         ...           ...           ...  ...
1179            NaN         NaN           NaN           NaN  NaN
1180            NaN         NaN           NaN           NaN  NaN
1181            NaN         NaN           NaN           NaN  NaN
1182            NaN         NaN           NaN           NaN  NaN
1183            NaN         NaN           NaN           NaN  NaN

[1184 rows x 9 columns]

In [ ]:
input("Check animals output. Afterwards, press ENTER to continue.")

''

In [ ]:
# Re-label sequences with no assigned genotype as "Unassigned"

metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype_official"].apply(lambda x: "Not assigned" if "Not assigned" in str(x) else x) # Unassigned segments are labeled "Unassigned"
metadata_genoflu["Genotype"] = metadata_genoflu["Genotype_official"] # Rename column again to not break old code

In [22]:
metadata_genoflu

,Accession,Assembly,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype_official,Geo_Location,full_header,sequence,Serotype,Segment,File Name,Partial_Header,genbank_name,Genotype
0,PX831491.1,GCA_054448965.1,Influenza A virus (A/Dairy cow/Texas/063224-24...,Dairy cow,2024-03,NaN,063224-24-1,B3.13,USA: Texas,>PX831491.1 |Influenza A virus (A/Dairy cow/Te...,AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...,H5N1,1,NaN,NaN,A/Dairy cow/Texas/063224-24-1/2024,B3.13
1,PX831492.1,GCA_054448965.1,Influenza A virus (A/Dairy cow/Texas/063224-24...,Dairy cow,2024-03,NaN,063224-24-1,B3.13,USA: Texas,>PX831492.1 |Influenza A virus (A/Dairy cow/Te...,AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACCTTAC...,H5N1,2,NaN,NaN,A/Dairy cow/Texas/063224-24-1/2024,B3.13
2,PX831493.1,GCA_054448965.1,Influenza A virus (A/Dairy cow/Texas/063224-24...,Dairy cow,2024-03,NaN,063224-24-1,B3.13,USA: Texas,>PX831493.1 |Influenza A virus (A/Dairy cow/Te...,AGCAAAAGCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAAT...,H5N1,3,NaN,NaN,A/Dairy cow/Texas/063224-24-1/2024,B3.13
3,PX831494.1,GCA_054448965.1,Influenza A virus (A/Dairy cow/Texas/063224-24...,Dairy cow,2024-03,NaN,063224-24-1,B3.13,USA: Texas,>PX831494.1 |Influenza A virus (A/Dairy cow/Te...,AGCAAAAGCAGGGGTTCACTCTGTCAAAATGGAGAACATAGTACTA...,H5N1,4,NaN,NaN,A/Dairy cow/Texas/063224-24-1/2024,B3.13
4,PX831495.1,GCA_054448965.1,Influenza A virus (A/Dairy cow/Texas/063224-24...,Dairy cow,2024-03,NaN,063224-24-1,B3.13,USA: Texas,>PX831495.1 |Influenza A virus (A/Dairy cow/Te...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...,H5N1,5,NaN,NaN,A/Dairy cow/Texas/063224-24-1/2024,B3.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1243,PX934299.1,GCA_054864435.1,Influenza A virus (A/Dairy Cow/NV/W250550062-1...,Dairy Cow,2025-02-23,NaN,W250550062-1,D1.1,USA: NV,>PX934299.1 |Influenza A virus (A/Dairy Cow/NV...,ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...,H5N1,4,NaN,>GCA_054864435.1,A/Dairy Cow/NV/W250550062-1/2025,D1.1
1244,PX934300.1,GCA_054864435.1,Influenza A virus (A/Dairy Cow/NV/W250550062-1...,Dairy Cow,2025-02-23,NaN,W250550062-1,D1.1,USA: NV,>PX934300.1 |Influenza A virus (A/Dairy Cow/NV...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...,H5N1,5,NaN,>GCA_054864435.1,A/Dairy Cow/NV/W250550062-1/2025,D1.1
1245,PX934301.1,GCA_054864435.1,Influenza A virus (A/Dairy Cow/NV/W250550062-1...,Dairy Cow,2025-02-23,NaN,W250550062-1,D1.1,USA: NV,>PX934301.1 |Influenza A virus (A/Dairy Cow/NV...,ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...,H5N1,6,NaN,>GCA_054864435.1,A/Dairy Cow/NV/W250550062-1/2025,D1.1
1246,PX934302.1,GCA_054864435.1,Influenza A virus (A/Dairy Cow/NV/W250550062-1...,Dairy Cow,2025-02-23,NaN,W250550062-1,D1.1,USA: NV,>PX934302.1 |Influenza A virus (A/Dairy Cow/NV...,ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...,H5N1,7,NaN,>GCA_054864435.1,A/Dairy Cow/NV/W250550062-1/2025,D1.1
1247,PX934303.1,GCA_054864435.1,Influenza A virus (A/Dairy Cow/NV/W250550062-1...,Dairy Cow,2025-02-23,NaN,W250550062-1,D1.1,USA: NV,>PX934303.1 |Influenza A virus (A/Dairy Cow/NV...,ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...,H5N1,8,NaN,>GCA_054864435.1,A/Dairy Cow/NV/W250550062-1/2025,D1.1

In [23]:
# Re-Labeling

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

# Fix animals
fix_animals_andersen(metadata_genoflu, animals_ref)

# Get the years
metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

# Get geographic locations
metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location"].apply(lambda x: 
                                                                        # If "x" has the state abbreviation (e.g. "MD")
                                                                        states_ref.loc[states_ref["Abbreviation"].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0] 
                                                                        + "-" + 
                                                                        x.split(" ")[-1]
                                                                        if states_ref["Abbreviation"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has the full state name (e.g. "Maryland")
                                                                        else states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0]
                                                                        + "-" + 
                                                                        states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Abbreviation'].iloc[0] 
                                                                        if states_ref["State"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has neither the state abbreviation nor the full state name nor is "USA"
                                                                        else 
                                                                        x
                                                                        )

metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location_Abrv"].apply(lambda x: x.split("-")[0] if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] else x)


print(metadata_genoflu["Geo_Location_Abrv"])

0       USA-TX
1       USA-TX
2       USA-TX
3       USA-TX
4       USA-TX
         ...
1243    USA-NV
1244    USA-NV
1245    USA-NV
1246    USA-NV
1247    USA-NV
Name: Geo_Location_Abrv, Length: 96760, dtype: object

In [24]:
# If there is no SRA Accession, replace identifier with Accession
metadata_genoflu["SRA_Accession"] = np.where(metadata_genoflu['SRA_Accession'] == "", metadata_genoflu['Assembly'].apply(lambda x: x.split(".")[0]), metadata_genoflu['SRA_Accession'])
# If there is no Assembly, replace identifier with Accession -- only for PB2
metadata_genoflu["Identifier"] = np.where(metadata_genoflu["SRA_Accession"] == "", metadata_genoflu["Accession"].apply(lambda x: metadata_genoflu[metadata_genoflu["Accession"] == x] if metadata_genoflu[metadata_genoflu["Accession"] == x].loc[:, "Segment"].values[0] == 1 else np.nan), metadata_genoflu["SRA_Accession"])
# Fill in other nans with PB2 Accession (interpolate, maximum of 7 other sequences)
metadata_genoflu.loc[:,"Identifier"] = metadata_genoflu.loc[:, "Identifier"].ffill(limit=7, limit_area="inside")

print(metadata_genoflu)

       Accession         Assembly  \
0     PX831491.1  GCA_054448965.1
1     PX831492.1  GCA_054448965.1
2     PX831493.1  GCA_054448965.1
3     PX831494.1  GCA_054448965.1
4     PX831495.1  GCA_054448965.1
...          ...              ...
1243  PX934299.1  GCA_054864435.1
1244  PX934300.1  GCA_054864435.1
1245  PX934301.1  GCA_054864435.1
1246  PX934302.1  GCA_054864435.1
1247  PX934303.1  GCA_054864435.1

                                          GenBank_Title       Host  \
0     Influenza A virus (A/Dairy cow/Texas/063224-24...  dairy cow
1     Influenza A virus (A/Dairy cow/Texas/063224-24...  dairy cow
2     Influenza A virus (A/Dairy cow/Texas/063224-24...  dairy cow
3     Influenza A virus (A/Dairy cow/Texas/063224-24...  dairy cow
4     Influenza A virus (A/Dairy cow/Texas/063224-24...  dairy cow
...                                                 ...        ...
1243  Influenza A virus (A/Dairy Cow/NV/W250550062-1...  dairy cow
1244  Influenza A virus (A/Dairy Cow/NV/W250550062-1...  dairy cow
1245  Influenza A virus (A/Dairy Cow/NV/W250550062-1...  dairy cow
1246  Influenza A virus (A/Dairy Cow/NV/W250550062-1...  dairy cow
1247  Influenza A virus (A/Dairy Cow/NV/W250550062-1...  dairy cow

     Collection_Date  SRA_Accession       Isolate Genotype_official  \
0            2024-03  GCA_054448965   063224-24-1             B3.13
1            2024-03  GCA_054448965   063224-24-1             B3.13
2            2024-03  GCA_054448965   063224-24-1             B3.13
3            2024-03  GCA_054448965   063224-24-1             B3.13
4            2024-03  GCA_054448965   063224-24-1             B3.13
...              ...            ...           ...               ...
1243      2025-02-23  GCA_054864435  W250550062-1              D1.1
1244      2025-02-23  GCA_054864435  W250550062-1              D1.1
1245      2025-02-23  GCA_054864435  W250550062-1              D1.1
1246      2025-02-23  GCA_054864435  W250550062-1              D1.1
1247      2025-02-23  GCA_054864435  W250550062-1              D1.1

     Geo_Location                                        full_header  ...  \
0      USA: Texas  >PX831491.1 |Influenza A virus (A/Dairy cow/Te...  ...
1      USA: Texas  >PX831492.1 |Influenza A virus (A/Dairy cow/Te...  ...
2      USA: Texas  >PX831493.1 |Influenza A virus (A/Dairy cow/Te...  ...
3      USA: Texas  >PX831494.1 |Influenza A virus (A/Dairy cow/Te...  ...
4      USA: Texas  >PX831495.1 |Influenza A virus (A/Dairy cow/Te...  ...
...           ...                                                ...  ...
1243      USA: NV  >PX934299.1 |Influenza A virus (A/Dairy Cow/NV...  ...
1244      USA: NV  >PX934300.1 |Influenza A virus (A/Dairy Cow/NV...  ...
1245      USA: NV  >PX934301.1 |Influenza A virus (A/Dairy Cow/NV...  ...
1246      USA: NV  >PX934302.1 |Influenza A virus (A/Dairy Cow/NV...  ...
1247      USA: NV  >PX934303.1 |Influenza A virus (A/Dairy Cow/NV...  ...

     Serotype Segment  File Name    Partial_Header  \
0        H5N1       1
1        H5N1       2
2        H5N1       3
3        H5N1       4
4        H5N1       5
...       ...     ...        ...               ...
1243     H5N1       4             >GCA_054864435.1
1244     H5N1       5             >GCA_054864435.1
1245     H5N1       6             >GCA_054864435.1
1246     H5N1       7             >GCA_054864435.1
1247     H5N1       8             >GCA_054864435.1

                            genbank_name Genotype Host_Type Years  \
0     A/Dairy cow/Texas/063224-24-1/2024    B3.13    cattle  2024
1     A/Dairy cow/Texas/063224-24-1/2024    B3.13    cattle  2024
2     A/Dairy cow/Texas/063224-24-1/2024    B3.13    cattle  2024
3     A/Dairy cow/Texas/063224-24-1/2024    B3.13    cattle  2024
4     A/Dairy cow/Texas/063224-24-1/2024    B3.13    cattle  2024
...                                  ...      ...       ...   ...
1243    A/Dairy Cow/NV/W250550062-1/2025     D1.1    cattle  2025
1244    A/Dairy Cow/NV/W250550062-1/2025     D1.1    cattle  2025
1245    A/Dairy Cow/NV/W250550062-1/2025     D1.1    cattle  2025
1246    A/Dairy Cow/NV/W250550062-1/2025     D1.1    cattle  2025
1247    A/Dairy Cow/NV/W250550062-1/2025     D1.1    cattle  2025

     Geo_Location_Abrv     Identifier
0               USA-TX  GCA_054448965
1               USA-TX  GCA_054448965
2               USA-TX  GCA_054448965
3               USA-TX  GCA_054448965
4               USA-TX  GCA_054448965
...                ...            ...
1243            USA-NV  GCA_054864435
1244            USA-NV  GCA_054864435
1245            USA-NV  GCA_054864435
1246            USA-NV  GCA_054864435
1247            USA-NV  GCA_054864435

[96760 rows x 21 columns]

In [25]:

# Make new labels
names = ">" + metadata_genoflu["Identifier"].astype(str) + "|" + metadata_genoflu["genbank_name"] + "|" + metadata_genoflu["Serotype"] + "|" + metadata_genoflu["Geo_Location_Abrv"] + "|" + metadata_genoflu["Collection_Date"].astype(str) + "|" + metadata_genoflu["Host_Type"] + "|" + metadata_genoflu["Genotype"]

metadata_genoflu["Name"] = names

In [26]:
os.chdir(complete_files)

# De-duplicate

print(len(metadata_genoflu))
metadata_genoflu = metadata_genoflu.drop_duplicates(subset=["Isolate", "genbank_name", "Segment"], keep="last")
print(len(metadata_genoflu))

# Save metadata
metadata_genoflu.to_csv("NCBI_Virus_" + date_range + "_metadata.csv") # Make file for metadata

96760
95216

## Rename segments and make complete FASTA files

In [ ]:
# Set up segments

if len(genotypes) > 3: # If we're not doing maintenance only
    genotypes.append("Not assigned") # Make sure unassigned genotypes are included
segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"} # Name segments 
metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].apply(lambda x: int(x)).map(segments)

# Separate into several dataframes based on genotype + segment
segment_genotype_dfs = []
for segment in segments.values():
    m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
    for genotype in list(set(m_g["Genotype"].values)):
        if genotype in genotypes:
            df = m_g[(m_g["Genotype"] == genotype)] 
            # df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
            segment_genotype_dfs.append(df)
            pair = genotype + "_" + segment
            print(pair)

B3.13_PB2
D1.3_PB2
D1.1_PB2
B3.13_PB1
D1.3_PB1
D1.1_PB1
B3.13_PA
D1.3_PA
D1.1_PA
B3.13_HA
D1.3_HA
D1.1_HA
B3.13_NP
D1.3_NP
D1.1_NP
B3.13_NA
D1.3_NA
D1.1_NA
B3.13_MP
D1.3_MP
D1.1_MP
B3.13_NS
D1.3_NS
D1.1_NS

In [28]:
# Create FASTA files

os.chdir(complete_files)

for df in segment_genotype_dfs:
    print(df)
    
    df = df.reset_index()
    if len(df["Genotype"].values[0]) > 0: # If we have assigned genotypes, including "Unassigned"
        file_name = df["Genotype"].values[0] + "_" + df["Segment_Name"].values[0] + "_" + date_range + ".fasta"
        output_file = open(complete_files + file_name, "w")

        for index, row in df.iterrows():
            name = df.loc[index, "Name"]
            name = name.replace(" ", "_")
            # names.append(name)
            sequence = df.loc[index, "sequence"]
            # First is header, second is sequence
            output_file.write(name + "\n")
            output_file.write(sequence + "\n")
        
    output_file.close()

       Accession         Assembly  \
0     PX831491.1  GCA_054448965.1
120   PX806572.1  GCA_054433815.1
168   PX806620.1  GCA_054435515.1
2056  PX809220.1  GCA_054429805.1
2064  PX809228.1  GCA_054434675.1
...          ...              ...
911   PX936693.1  GCA_054872375.1
919   PX936709.1  GCA_054872415.1
927   PX936717.1  GCA_054872425.1
935   PX936725.1  GCA_054872495.1
1071  PX936981.1  GCA_054872785.1

                                          GenBank_Title       Host  \
0     Influenza A virus (A/Dairy cow/Texas/063224-24...  dairy cow
120   Influenza A virus (A/cattle/CA/25-026029-002-o...     cattle
168   Influenza A virus (A/cattle/CA/25G02121-002-or...     cattle
2056  Influenza A virus (A/cattle/CA/25-024071-005-o...     cattle
2064  Influenza A virus (A/cattle/CA/25-026426-003-o...     cattle
...                                                 ...        ...
911   Influenza A virus (A/Bovine/California/B240054...     bovine
919   Influenza A virus (A/Bovine/California/B240140...     bovine
927   Influenza A virus (A/Bovine/California/B240162...     bovine
935   Influenza A virus (A/Bovine/California/B240175...     bovine
1071  Influenza A virus (A/Turkey/California/B240266...     turkey

     Collection_Date  SRA_Accession                         Isolate  \
0            2024-03  GCA_054448965                     063224-24-1
120       2025-09-23    SRR36114811          25-026029-002-original
168       2025-10-07    SRR36114768           25G02121-002-original
2056      2025-08-26    SRR36114812  25-024071-005-original-repeat2
2064      2025-09-30    SRR36114780          25-026426-003-original
...              ...            ...                             ...
911       2024-09-12  GCA_054872375                        B2400548
919       2024-10-16  GCA_054872415                        B2401408
927       2024-10-22  GCA_054872425                        B2401620
935       2024-10-24  GCA_054872495                        B2401751
1071      2024-11-29  GCA_054872785                        B2402661

     Genotype_official     Geo_Location  \
0                B3.13       USA: Texas
120              B3.13          USA: CA
168              B3.13          USA: CA
2056             B3.13          USA: CA
2064             B3.13          USA: CA
...                ...              ...
911              B3.13  USA: California
919              B3.13  USA: California
927              B3.13  USA: California
935              B3.13  USA: California
1071             B3.13  USA: California

                                            full_header  ... File Name  \
0     >PX831491.1 |Influenza A virus (A/Dairy cow/Te...  ...
120   >PX806572.1 |Influenza A virus (A/cattle/CA/25...  ...
168   >PX806620.1 |Influenza A virus (A/cattle/CA/25...  ...
2056  >PX809220.1 |Influenza A virus (A/cattle/CA/25...  ...
2064  >PX809228.1 |Influenza A virus (A/cattle/CA/25...  ...
...                                                 ...  ...       ...
911   >PX936693.1 |Influenza A virus (A/Bovine/Calif...  ...
919   >PX936709.1 |Influenza A virus (A/Bovine/Calif...  ...
927   >PX936717.1 |Influenza A virus (A/Bovine/Calif...  ...
935   >PX936725.1 |Influenza A virus (A/Bovine/Calif...  ...
1071  >PX936981.1 |Influenza A virus (A/Turkey/Calif...  ...

        Partial_Header                                     genbank_name  \
0                                    A/Dairy cow/Texas/063224-24-1/2024
120                             A/cattle/CA/25-026029-002-original/2025
168                              A/cattle/CA/25G02121-002-original/2025
2056                    A/cattle/CA/25-024071-005-original-repeat2/2025
2064                            A/cattle/CA/25-026426-003-original/2025
...                ...                                              ...
911   >GCA_054872375.1                A/Bovine/California/B2400548/2024
919   >GCA_054872415.1                A/Bovine/California/B2401408/2024
927   >GCA_054872425.1                A/Bovine/California/B2401620/2024
935   >GCA_054872495.1                A/Bovine/California/B2401751/2024
1071  >GCA_054872785.1                A/Turkey/California/B2402661/2024

     Genotype       Host_Type Years Geo_Location_Abrv     Identifier  \
0       B3.13          cattle  2024            USA-TX  GCA_054448965
120     B3.13          cattle  2025            USA-CA    SRR36114811
168     B3.13          cattle  2025            USA-CA    SRR36114768
2056    B3.13          cattle  2025            USA-CA    SRR36114812
2064    B3.13          cattle  2025            USA-CA    SRR36114780
...       ...             ...   ...               ...            ...
911     B3.13          cattle  2024            USA-CA  GCA_054872375
919     B3.13          cattle  2024            USA-CA  GCA_054872415
927     B3.13          cattle  2024            USA-CA  GCA_054872425
935     B3.13          cattle  2024            USA-CA  GCA_054872495
1071    B3.13  domestic_avian  2024            USA-CA  GCA_054872785

                                                   Name Segment_Name
0     >GCA_054448965|A/Dairy cow/Texas/063224-24-1/2...          PB2
120   >SRR36114811|A/cattle/CA/25-026029-002-origina...          PB2
168   >SRR36114768|A/cattle/CA/25G02121-002-original...          PB2
2056  >SRR36114812|A/cattle/CA/25-024071-005-origina...          PB2
2064  >SRR36114780|A/cattle/CA/25-026426-003-origina...          PB2
...                                                 ...          ...
911   >GCA_054872375|A/Bovine/California/B2400548/20...          PB2
919   >GCA_054872415|A/Bovine/California/B2401408/20...          PB2
927   >GCA_054872425|A/Bovine/California/B2401620/20...          PB2
935   >GCA_054872495|A/Bovine/California/B2401751/20...          PB2
1071  >GCA_054872785|A/Turkey/California/B2402661/20...          PB2

[3910 rows x 23 columns]
        Accession         Assembly  \
1624   PX808748.1  GCA_054422885.1
1704   PX808836.1
1712   PX808844.1  GCA_054423675.1
1720   PX808852.1  GCA_054424055.1
3568   PX812072.1  GCA_054422555.1
...           ...              ...
94392  PV219030.1  GCA_048434355.1
94400  PV219038.1  GCA_048433605.1
94488  PV219126.1  GCA_048434965.1
94496  PV219134.1  GCA_048434085.1
94504  PV219142.1  GCA_048435015.1

                                           GenBank_Title             Host  \
1624   Influenza A virus (A/Red-tailed Hawk/MI/25-008...  red-tailed hawk
1704   Influenza A virus (A/Sand Crane/WI/25-012104-0...       sand crane
1712   Influenza A virus (A/Sandhill Crane/MI/25-0094...   sandhill crane
1720   Influenza A virus (A/Sandhill Crane/MI/25-0102...   sandhill crane
3568   Influenza A virus (A/Canada Goose/MI/25-008087...     canada goose
...                                                  ...              ...
94392  Influenza A virus (A/chicken/IN/25-001513-001-...          chicken
94400  Influenza A virus (A/chicken/IN/25-001513-002-...          chicken
94488  Influenza A virus (A/chicken/OH/25-001529-001-...          chicken
94496  Influenza A virus (A/chicken/OH/25-001529-002-...          chicken
94504  Influenza A virus (A/chicken/OH/25-001532-001-...          chicken

      Collection_Date SRA_Accession                 Isolate Genotype_official  \
1624       2025-03-05   SRR32973980  25-008362-001-original              D1.3
1704       2025-03-27   SRR33370185  25-012104-001-original              D1.3
1712       2025-03-13   SRR32974094  25-009428-003-original              D1.3
1720       2025-03-19   SRR33029801  25-010298-001-original              D1.3
3568       2025-03-02   SRR32868815  25-008087-001-original              D1.3
...               ...           ...                     ...               ...
94392            2025   SRR32226911  25-001513-001-original              D1.3
94400            2025   SRR32226910  25-001513-002-original              D1.3
94488            2025   SRR32226908  25-001529-001-original              D1.3
94496            2025   SRR32226907  25-001529-002-original              D1.3
94504            2025   SRR32226903  25-001532-001-original              D1.3

      Geo_Location                                        full_header  ...  \
1624       USA: MI  >PX808748.1 |Influenza A virus (A/Red-tailed H...  ...
1704       USA: WI  >PX808836.1 |Influenza A virus (A/Sand Crane/W...  ...
1712       USA: MI  >PX808844.1 |Influenza A virus (A/Sandhill Cra...  ...
1720       USA: MI  >PX808852.1 |Influenza A virus (A/Sandhill Cra...  ...
3568       USA: MI  >PX812072.1 |Influenza A virus (A/Canada Goose...  ...
...            ...                                                ...  ...
94392      USA: IN  >PV219030.1 |Influenza A virus (A/chicken/IN/2...  ...
94400      USA: IN  >PV219038.1 |Influenza A virus (A/chicken/IN/2...  ...
94488      USA: OH  >PV219126.1 |Influenza A virus (A/chicken/OH/2...  ...
94496      USA: OH  >PV219134.1 |Influenza A virus (A/chicken/OH/2...  ...
94504      USA: OH  >PV219142.1 |Influenza A virus (A/chicken/OH/2...  ...

            File Name Partial_Header  \
1624
1704
1712
1720
3568
...               ...            ...
94392  SRR32226911.fa
94400  SRR32226910.fa
94488  SRR32226908.fa
94496  SRR32226907.fa
94504  SRR32226903.fa

                                           genbank_name Genotype  \
1624   A/Red-tailed Hawk/MI/25-008362-001-original/2025     D1.3
1704        A/Sand Crane/WI/25-012104-001-original/2025     D1.3
1712    A/Sandhill Crane/MI/25-009428-003-original/2025     D1.3
1720    A/Sandhill Crane/MI/25-010298-001-original/2025     D1.3
3568      A/Canada Goose/MI/25-008087-001-original/2025     D1.3
...                                                 ...      ...
94392          A/chicken/IN/25-001513-001-original/2025     D1.3
94400          A/chicken/IN/25-001513-002-original/2025     D1.3
94488          A/chicken/OH/25-001529-001-original/2025     D1.3
94496          A/chicken/OH/25-001529-002-original/2025     D1.3
94504          A/chicken/OH/25-001532-001-original/2025     D1.3

            Host_Type Years Geo_Location_Abrv   Identifier  \
1624       wild_avian  2025            USA-MI  SRR32973980
1704       wild_avian  2025            USA-WI  SRR33370185
1712       wild_avian  2025            USA-MI  SRR32974094
1720       wild_avian  2025            USA-MI  SRR33029801
3568       wild_avian  2025            USA-MI  SRR32868815
...               ...   ...               ...          ...
94392  domestic_avian  2025            USA-IN  SRR32226911
94400  domestic_avian  2025            USA-IN  SRR32226910
94488  domestic_avian  2025            USA-OH  SRR32226908
94496  domestic_avian  2025            USA-OH  SRR32226907
94504  domestic_avian  2025            USA-OH  SRR32226903

                                                    Name Segment_Name
1624   >SRR32973980|A/Red-tailed Hawk/MI/25-008362-00...          PB2
1704   >SRR33370185|A/Sand Crane/WI/25-012104-001-ori...          PB2
1712   >SRR32974094|A/Sandhill Crane/MI/25-009428-003...          PB2
1720   >SRR33029801|A/Sandhill Crane/MI/25-010298-001...          PB2
3568   >SRR32868815|A/Canada Goose/MI/25-008087-001-o...          PB2
...                                                  ...          ...
94392  >SRR32226911|A/chicken/IN/25-001513-001-origin...          PB2
94400  >SRR32226910|A/chicken/IN/25-001513-002-origin...          PB2
94488  >SRR32226908|A/chicken/OH/25-001529-001-origin...          PB2
94496  >SRR32226907|A/chicken/OH/25-001529-002-origin...          PB2
94504  >SRR32226903|A/chicken/OH/25-001532-001-origin...          PB2

[241 rows x 23 columns]
       Accession         Assembly  \
8     PX806460.1
16    PX806468.1
24    PX806476.1  GCA_054439025.1
32    PX806484.1  GCA_054418305.1
40    PX806492.1  GCA_054437805.1
...          ...              ...
1208  PX934232.1  GCA_054864355.1
1216  PX934248.1  GCA_054864375.1
1224  PX934256.1  GCA_054864385.1
1232  PX934264.1  GCA_054864395.1
1240  PX934296.1  GCA_054864435.1

                                          GenBank_Title  \
8     Influenza A virus (A/American blue-winged Teal...
16    Influenza A virus (A/Eared Grebe/UT/25G03450-0...
24    Influenza A virus (A/Turkey/MI/25G03685-001-or...
32    Influenza A virus (A/Red-tailed Hawk/MA/25-021...
40    Influenza A virus (A/Red-Tailed Hawk/MT/25G033...
...                                                 ...
1208  Influenza A virus (A/Dairy Cow/NV/W250280080-1...
1216  Influenza A virus (A/Dairy Cow/NV/W250340039-1...
1224  Influenza A virus (A/Dairy Cow/NV/W250490059-1...
1232  Influenza A virus (A/Dairy Cow/NV/W250490064-1...
1240  Influenza A virus (A/Dairy Cow/NV/W250550062-1...

                           Host Collection_Date  SRA_Accession  \
8     american blue-winged teal      2025-09-27    SRR36211608
16                  eared grebe      2025-10-22    SRR36203325
24                       turkey      2025-11-09    SRR36202266
32              red-tailed hawk      2025-02-01    SRR35089287
40              red-tailed hawk      2025-10-27    SRR36209050
...                         ...             ...            ...
1208                  dairy cow      2025-01-27  GCA_054864355
1216                  dairy cow      2025-02-02  GCA_054864375
1224                  dairy cow      2025-02-17  GCA_054864385
1232                  dairy cow      2025-02-17  GCA_054864395
1240                  dairy cow      2025-02-23  GCA_054864435

                     Isolate Genotype_official Geo_Location  \
8      25G01357-014-original              D1.1      USA: KS
16     25G03450-007-original              D1.1      USA: UT
24     25G03685-001-original              D1.1      USA: MI
32    25-021407-002-original              D1.1      USA: MA
40     25G03371-001-original              D1.1      USA: MT
...                      ...               ...          ...
1208            W250280080-1              D1.1      USA: NV
1216            W250340039-1              D1.1      USA: NV
1224            W250490059-1              D1.1      USA: NV
1232            W250490064-1              D1.1      USA: NV
1240            W250550062-1              D1.1      USA: NV

                                            full_header  ... File Name  \
8     >PX806460.1 |Influenza A virus (A/American blu...  ...
16    >PX806468.1 |Influenza A virus (A/Eared Grebe/...  ...
24    >PX806476.1 |Influenza A virus (A/Turkey/MI/25...  ...
32    >PX806484.1 |Influenza A virus (A/Red-tailed H...  ...
40    >PX806492.1 |Influenza A virus (A/Red-Tailed H...  ...
...                                                 ...  ...       ...
1208  >PX934232.1 |Influenza A virus (A/Dairy Cow/NV...  ...
1216  >PX934248.1 |Influenza A virus (A/Dairy Cow/NV...  ...
1224  >PX934256.1 |Influenza A virus (A/Dairy Cow/NV...  ...
1232  >PX934264.1 |Influenza A virus (A/Dairy Cow/NV...  ...
1240  >PX934296.1 |Influenza A virus (A/Dairy Cow/NV...  ...

        Partial_Header                                       genbank_name  \
8                       A/American blue-winged Teal/KS/25G01357-014-or...
16                            A/Eared Grebe/UT/25G03450-007-original/2025
24                                 A/Turkey/MI/25G03685-001-original/2025
32                       A/Red-tailed Hawk/MA/25-021407-002-original/2025
40                        A/Red-Tailed Hawk/MT/25G03371-001-original/2025
...                ...                                                ...
1208  >GCA_054864355.1                   A/Dairy Cow/NV/W250280080-1/2025
1216  >GCA_054864375.1                   A/Dairy Cow/NV/W250340039-1/2025
1224  >GCA_054864385.1                   A/Dairy Cow/NV/W250490059-1/2025
1232  >GCA_054864395.1                   A/Dairy Cow/NV/W250490064-1/2025
1240  >GCA_054864435.1                   A/Dairy Cow/NV/W250550062-1/2025

     Genotype       Host_Type Years Geo_Location_Abrv     Identifier  \
8        D1.1      wild_avian  2025            USA-KS    SRR36211608
16       D1.1      wild_avian  2025            USA-UT    SRR36203325
24       D1.1  domestic_avian  2025            USA-MI    SRR36202266
32       D1.1      wild_avian  2025            USA-MA    SRR35089287
40       D1.1      wild_avian  2025            USA-MT    SRR36209050
...       ...             ...   ...               ...            ...
1208     D1.1          cattle  2025            USA-NV  GCA_054864355
1216     D1.1          cattle  2025            USA-NV  GCA_054864375
1224     D1.1          cattle  2025            USA-NV  GCA_054864385
1232     D1.1          cattle  2025            USA-NV  GCA_054864395
1240     D1.1          cattle  2025            USA-NV  GCA_054864435

                                                   Name Segment_Name
8     >SRR36211608|A/American blue-winged Teal/KS/25...          PB2
16    >SRR36203325|A/Eared Grebe/UT/25G03450-007-ori...          PB2
24    >SRR36202266|A/Turkey/MI/25G03685-001-original...          PB2
32    >SRR35089287|A/Red-tailed Hawk/MA/25-021407-00...          PB2
40    >SRR36209050|A/Red-Tailed Hawk/MT/25G03371-001...          PB2
...                                                 ...          ...
1208  >GCA_054864355|A/Dairy Cow/NV/W250280080-1/202...          PB2
1216  >GCA_054864375|A/Dairy Cow/NV/W250340039-1/202...          PB2
1224  >GCA_054864385|A/Dairy Cow/NV/W250490059-1/202...          PB2
1232  >GCA_054864395|A/Dairy Cow/NV/W250490064-1/202...          PB2
1240  >GCA_054864435|A/Dairy Cow/NV/W250550062-1/202...          PB2

[3259 rows x 23 columns]
       Accession         Assembly  \
1     PX831492.1  GCA_054448965.1
121   PX806573.1  GCA_054433815.1
169   PX806621.1  GCA_054435515.1
2057  PX809221.1  GCA_054429805.1
2065  PX809229.1  GCA_054434675.1
...          ...              ...
910   PX936692.1  GCA_054872375.1
918   PX936708.1  GCA_054872415.1
926   PX936716.1  GCA_054872425.1
934   PX936724.1  GCA_054872495.1
1070  PX936980.1  GCA_054872785.1

                                          GenBank_Title       Host  \
1     Influenza A virus (A/Dairy cow/Texas/063224-24...  dairy cow
121   Influenza A virus (A/cattle/CA/25-026029-002-o...     cattle
169   Influenza A virus (A/cattle/CA/25G02121-002-or...     cattle
2057  Influenza A virus (A/cattle/CA/25-024071-005-o...     cattle
2065  Influenza A virus (A/cattle/CA/25-026426-003-o...     cattle
...                                                 ...        ...
910   Influenza A virus (A/Bovine/California/B240054...     bovine
918   Influenza A virus (A/Bovine/California/B240140...     bovine
926   Influenza A virus (A/Bovine/California/B240162...     bovine
934   Influenza A virus (A/Bovine/California/B240175...     bovine
1070  Influenza A virus (A/Turkey/California/B240266...     turkey

     Collection_Date  SRA_Accession                         Isolate  \
1            2024-03  GCA_054448965                     063224-24-1
121       2025-09-23    SRR36114811          25-026029-002-original
169       2025-10-07    SRR36114768           25G02121-002-original
2057      2025-08-26    SRR36114812  25-024071-005-original-repeat2
2065      2025-09-30    SRR36114780          25-026426-003-original
...              ...            ...                             ...
910       2024-09-12  GCA_054872375                        B2400548
918       2024-10-16  GCA_054872415                        B2401408
926       2024-10-22  GCA_054872425                        B2401620
934       2024-10-24  GCA_054872495                        B2401751
1070      2024-11-29  GCA_054872785                        B2402661

     Genotype_official     Geo_Location  \
1                B3.13       USA: Texas
121              B3.13          USA: CA
169              B3.13          USA: CA
2057             B3.13          USA: CA
2065             B3.13          USA: CA
...                ...              ...
910              B3.13  USA: California
918              B3.13  USA: California
926              B3.13  USA: California
934              B3.13  USA: California
1070             B3.13  USA: California
