# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI and relabeling sequences. 

Notes:
* This file must be in the same folder as "utils.py"

## Housekeeping

In [1]:
# Libraries

import os
import pandas as pd
import dateutil
import re
import shutil 
import numpy as np
import importlib
import utils  
importlib.reload(utils)
from utils import * # If changing utils, must restart this file for changes to take effect

In [2]:
# Directory paths and input

# Input
browser = input("Browser (Firefox, Chrome, or Edge): ")
sleep_time = input("Seconds to wait in between clicks (recommended 5): ")
# locations = input("Locations (separate with commas and no spaces in between locations): ")
# start_date = input("Start date (format: MM-DD-YYYY): ")
# end_date = input("End date: (format: MM-DD-YYYY): ")
# serotype = input("Serotype (e.g. H5N1): ")
# serotypes = list(serotype)
# genotypes = input("Genotypes (separate with commas and no spaces in between genotypes): ")
# genotypes = genotypes.split(",")

# Dates and locations
locations = "Antarctica,North America,South America"
start_date = "11-01-2021"
end_date = "01-16-2026"
prev_end_date = "01-09-2026"
date_range = start_date + "--" + end_date
prev_date_range = start_date + "--" + prev_end_date

# Maintenance serotypes and genotypes
serotypes = ["H5N1"]
genotypes = ["B3.13", "D1.1", "D1.3"]

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# downloads = "C:/Users/maksi/Downloads/"
# references = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/references/"

home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Downloads/" # MUST be downloads folder. Clean out downloads folder after each use. 
references = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/references/"

downloads_saved = home + "NCBI_Virus/downloads/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/" 
prev_downloads_saved = home + "NCBI_Virus/downloads/" + prev_date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/" 

andersen = home + "Andersen/avian-influenza/metadata/"
temp_files = home + "NCBI_Virus/temp/"
complete_files = home + "NCBI_Virus/complete/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/"
if not os.path.exists(complete_files): # checking if the directory exists or not
    os.makedirs(complete_files) # if the directory is not present then create it

os.chdir(references)
states_ref = pd.read_csv("states_ref.csv")

# All serotypes and genotypes
# serotype = ""
# genotypes_df = pd.read_excel("genotype_key.xlsx")
# genotypes = list(genotypes_df["Genotype"])

## Downloading Data

In [3]:
os.chdir(downloads)

if not os.path.exists(downloads_saved): # checking if the directory exists or not
    os.makedirs(downloads_saved) # if the directory is not present then create it

# Move downloaded files to saved downloads
for dirpath, dirs, files in os.walk(downloads_saved):
    if len(files) != 0:
        break 
    else: # If we don't have any downloaded files
        # Get files
        open_ncbi_virus(browser, sleep_time, locations, start_date, end_date)

        # Re-try 
        for dirpath, dirs, files in os.walk(downloads):
            if len(files) > 0: # If we have any files that need to be moved
                for file in files:
                    file_name = os.path.join(dirpath, file)
                    destination_path = os.path.join(downloads_saved, os.path.basename(file_name))
                    try:
                        shutil.move(file_name, destination_path)
                    except:
                        print("Error moving file", file_name)
                        continue 
            break 
    break

## De-Duplication

In [4]:
# Get metadata
os.chdir(downloads_saved)
metadata = pd.read_csv("sequences.csv")
print(len(metadata))

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.Isolate, as_index=False).size()
# print(metadata_counts)
metadata_counted = metadata.merge(metadata_counts, on="Isolate")

# Only keep those with size >= 8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates
metadata_complete_segs = metadata_complete_segs.drop_duplicates(subset="GenBank_Title", keep="last") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]
metadata_segments

140400

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Host,Tissue_Specimen_Source,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size
0,PX880763.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Falco peregrinus,NaN,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2025-11-20,2026-01-16,ssRNA(-),8
1,PX880764.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Falco peregrinus,NaN,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2025-11-20,2026-01-16,ssRNA(-),8
2,PX880765.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Falco peregrinus,NaN,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2025-11-20,2026-01-16,ssRNA(-),8
3,PX880766.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Falco peregrinus,NaN,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2025-11-20,2026-01-16,ssRNA(-),8
4,PX880767.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Falco peregrinus,NaN,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2025-11-20,2026-01-16,ssRNA(-),8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132376,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
132377,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
132378,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
132379,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
132380,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8

## Add sequences to dataframe

In [5]:
# NCBI Virus Naming Convention:
# "Accession|GenBank_Title|Assembly|SRA Accession|BioSample|BioProject|Genotype|Isolate|Geo Location|Host|Collection Date"

# Get sequences and headers together
# headers = []
# isolates = []
# sras = []
# headers_seqs = {}

os.chdir(downloads_saved)

sequences_fasta = df_from_fasta("sequences.fasta") # Turn fasta into a dataframe

sequences_fasta["Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split(" |")[0].replace(">",""))

print(sequences_fasta["full_header"])

# Extract segment number so that we can add the correct sequences to the correct sample
# sequences_fasta["Segment"] = sequences_fasta["full_header"].apply(lambda x: int(re.search(r'segment (.?) ', x.split("|")[-2]).group(1)))

# Double-check the de-duplication
print(len(sequences_fasta)) 
# print(sequences_fasta.head())
print(len(metadata_segments))

# Add sequences to the dataframe
metadata_segments = pd.merge(metadata_segments, sequences_fasta, on="Accession") # , "Segment"])

0         >PX879581.1 |Influenza A virus (A/Glaucous gul...
1         >PX879582.1 |Influenza A virus (A/Glaucous gul...
2         >PX879583.1 |Influenza A virus (A/Glaucous gul...
3         >PX879584.1 |Influenza A virus (A/Glaucous gul...
4         >PX879585.1 |Influenza A virus (A/Glaucous gul...
                                ...
140395    >OK205883.1 |Influenza A virus (A/chicken/Vera...
140396    >OK205884.1 |Influenza A virus (A/chicken/Vera...
140397    >OK205885.1 |Influenza A virus (A/chicken/Vera...
140398    >OK205886.1 |Influenza A virus (A/chicken/Vera...
140399    >OK205887.1 |Influenza A virus (A/chicken/Vera...
Name: full_header, Length: 140400, dtype: object
140400
121096

In [6]:
metadata_segments

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size,full_header,sequence
0,PX880763.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2025-11-20,2026-01-16,ssRNA(-),8,>PX880763.1 |Influenza A virus (A/Peregrine Fa...,ATGGATAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
1,PX880764.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2025-11-20,2026-01-16,ssRNA(-),8,>PX880764.1 |Influenza A virus (A/Peregrine Fa...,ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
2,PX880765.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2025-11-20,2026-01-16,ssRNA(-),8,>PX880765.1 |Influenza A virus (A/Peregrine Fa...,ATGGAAGATTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
3,PX880766.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2025-11-20,2026-01-16,ssRNA(-),8,>PX880766.1 |Influenza A virus (A/Peregrine Fa...,ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4,PX880767.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,NaN,2025-11-20,2026-01-16,ssRNA(-),8,>PX880767.1 |Influenza A virus (A/Peregrine Fa...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121091,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205883.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...
121092,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205884.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...
121093,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205885.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...
121094,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205886.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...
121095,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>OK205887.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...

## Find genotypes

(Using old genoflu results or Andersen Lab genoflu output) <br>
Old genoflu results should accumulate into one file to avoid having to genotype anything again.

### Find old genotypes

In [7]:
# Switch directory to previous week
os.chdir(prev_downloads_saved)

# Get both files from previous week
genoflu_output = pd.read_csv("output.tsv", delimiter="\t")
genoflu_results = pd.read_csv("results.tsv", delimiter="\t")

# Get old results from output.tsv
genoflu_old = pd.concat([genoflu_output, genoflu_results])
# genoflu_old = genoflu_old.rename(columns={"Strain":"Partial_Header"}) # So we can merge
print(genoflu_old)

# Switch back directory
os.chdir(downloads_saved)

# Save this output for the future
genoflu_old.to_csv("output.tsv", sep="\t", index=False)

                                                 Strain  \
0     Influenza_A_virus__Mexico__Estado_de_Mexico_CP...
1     Influenza_A_virus__Mexico__Estado_de_Mexico_CP...
2     Influenza_A_virus__Mexico__Ciudad_de_Mexico_CP...
3     Influenza_A_virus__Mexico__Estado_de_Mexico_CP...
4     Influenza_A_virus__Mexico__Michoacan_CPA_02011...
...                                                 ...
1746  Influenza_A_virus__USA__PA_25_006666_003_origi...
1747  Influenza_A_virus__USA__IL_25_025606_001_origi...
1748  Influenza_A_virus__USA__MI_25_013658_010_origi...
1749  Influenza_A_virus__USA__NY_25_023581_001_origi...
1750  Influenza_A_virus__USA__MN_25_011610_001_origi...

                                               Genotype  \
0     Not assigned: Only 3 segments >98.0% match fou...
1     Not assigned: Only 3 segments >98.0% match fou...
2     Not assigned: Only 3 segments >98.0% match fou...
3     Not assigned: Only 3 segments >98.0% match fou...
4     Not assigned: Only 6 segments >98.0% match fou...
...                                                 ...
1746  Not assigned: Only 4 segments >98.0% match fou...
1747                                               D1.1
1748                                               D1.3
1749                                               D1.1
1750                                               D1.3

                            Genotype List Used, >=98.0%  \
0                              PA:ea1, MP:ea1, NS:am1.1
1                              PA:ea1, MP:ea1, NS:am1.1
2                              PA:ea1, MP:ea1, NS:am1.1
3                              PA:ea1, MP:ea1, NS:am1.1
4     PB2:am2.1, PB1:am1.2, PA:ea1, HA:ea1, MP:ea1, ...
...                                                 ...
1746         PB2:am2.3.1, PB1:am1.3, NP:am1.1, NS:am1.2
1747  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1748  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1749  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1750  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
0     am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
1     am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
2     am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
3     am2.1:22-009329-001:PB2, am2:22-008760-007:PB1...
4     am2.1:22-009329-001:PB2, am1.2:22-010085-001:P...
...                                                 ...
1746  am2.3.1:22-008760-007:PB2, am1.3:23-003733-001...
1747  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1748  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1749  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1750  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
0     97.63%, 92.66%, 98.33%, 97.53%, 88.91%, 83.52%...
1     97.67%, 92.66%, 98.33%, 97.59%, 88.84%, 83.52%...
2     97.57%, 92.70%, 98.28%, 97.59%, 88.84%, 83.52%...
3     97.67%, 92.70%, 98.33%, 97.36%, 88.84%, 83.43%...
4     98.90%, 98.77%, 98.98%, 98.47%, 88.96%, 83.70%...
...                                                 ...
1746  98.55%, 98.77%, 97.77%, 80.17%, 98.53%, 75.16%...
1747  99.47%, 99.25%, 99.30%, 99.53%, 99.53%, 99.22%...
1748  99.69%, 99.25%, 99.63%, 99.00%, 99.73%, 98.94%...
1749  99.47%, 98.94%, 99.58%, 99.35%, 99.87%, 99.29%...
1750  99.83%, 99.43%, 99.67%, 99.30%, 99.87%, 99.08%...

                 Genotype Mismatch List  \
0     54, 167, 36, 42, 166, 186, 18, 14
1     53, 167, 36, 41, 167, 186, 18, 14
2     35, 166, 37, 41, 167, 186, 19, 14
3     53, 166, 36, 45, 167, 187, 18, 14
4       25, 28, 22, 26, 165, 182, 12, 9
...                                 ...
1746     33, 28, 48, 314, 22, 28, 22, 7
1747         12, 17, 15, 8, 7, 11, 3, 8
1748         7, 17, 8, 17, 4, 15, 1, 10
1749         12, 24, 9, 11, 2, 10, 1, 6
1750          4, 13, 7, 12, 2, 13, 1, 8

     Genotype Average Depth of Coverage List             Date run
0          Ran on FASTA - No Coverage Report  2025-12-03_10-28-26
1          Ran on FASTA - No Coverage Report  2025-12-03_10-28-27
2          Ran on FASTA - No Coverage Report  2025-12-03_10-28-27
3          Ran on FASTA - No Coverage Report  2025-12-03_10-28-27
4          Ran on FASTA - No Coverage Report  2025-12-03_10-28-28
...                                      ...                  ...
1746       Ran on FASTA - No Coverage Report  2026-01-12_12-20-06
1747       Ran on FASTA - No Coverage Report  2026-01-12_12-20-07
1748       Ran on FASTA - No Coverage Report  2026-01-12_12-20-07
1749       Ran on FASTA - No Coverage Report  2026-01-12_12-20-07
1750       Ran on FASTA - No Coverage Report  2026-01-12_12-20-08

[15098 rows x 8 columns]

In [17]:

# metadata_segments["Partial_Header"] = metadata_segments["full_header"].apply(lambda x: x.split("|")[1].split("(")[1]) # Get only genbank name
metadata_segments["Partial_Header_temp"] = metadata_segments["Isolate"] # Get only isolate

# metadata_segments["Partial_Header_temp"] = metadata_segments["Partial_Header"].apply(lambda x: x.replace(">", "").split("segment")[0][:-3]) # Get rid of header indicator, stop at segment bit
print(metadata_segments["Partial_Header_temp"].values[:10])

# metadata_segments["Partial_Header_temp"] = metadata_segments["Partial_Header"].apply(lambda x: x.split("|")[1]) 
for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]: # Forbidden punctuation
    metadata_segments["Partial_Header_temp"] = metadata_segments["Partial_Header_temp"].apply(lambda x: x.replace(c, "_") if x == x else x)




# Merge to get already-genotyped segments
# genoflu_old["Partial_Header_temp"] = genoflu_old["Partial_Header"].apply(lambda x: re.split(r'_H.N._20.{2}_.{2}_.{2}', x)[0]) # Get only genbank name
genoflu_old["Partial_Header_temp"] = genoflu_old["Strain"].apply(lambda x: re.split(r'Influenza_A_virus__\D*__\D*_', x)[-1]) # Get only isolate 
genoflu_old["Partial_Header_temp"] = genoflu_old["Partial_Header_temp"].apply(lambda x: re.split(r'_H.N._20.{2}_.{2}_.{2}', x)[0]) # Get only isolate


print(metadata_segments["Partial_Header_temp"].values[:10])
print(genoflu_old["Partial_Header_temp"].values[100:120])

print(metadata_segments.head())
metadata_segments_old = metadata_segments.merge(genoflu_old, how="inner", on="Partial_Header_temp") 

# Isolate not-already-genotyped segments
metadata_segments_new = metadata_segments.merge(genoflu_old, indicator=True, how='left', on="Partial_Header_temp").loc[lambda x : x['_merge']=='left_only'] 

print(len(metadata_segments_old))
print(len(metadata_segments_new))

['25G04838-001-original' '25G04838-001-original' '25G04838-001-original'
 '25G04838-001-original' '25G04838-001-original' '25G04838-001-original'
 '25G04838-001-original' '25G04838-001-original' '25G05080-001-original'
 '25G05080-001-original']
['25G04838_001_original' '25G04838_001_original' '25G04838_001_original'
 '25G04838_001_original' '25G04838_001_original' '25G04838_001_original'
 '25G04838_001_original' '25G04838_001_original' '25G05080_001_original'
 '25G05080_001_original']
['24_013789_010_original' '1266_8_2022' '22_017571_001_original'
 '22_020657_001_original' '0660_3_2022' '22_012334_001' '0833_79_2022'
 '0097_26_2022' '0014_1_2024' '22_001330_015' '1309_10_2022'
 '22_009329_001' '22_034080_032_original' '0802_90_2022' '0934_84_2022'
 '0481_R' '1466_11_2022' '0100_2_2024' '1628_29_2022'
 '22_028596_002_original']
    Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0  PX880763.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
1  PX880764.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
2  PX880765.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
3  PX880766.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
4  PX880767.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216

     BioProject      Organism_Name                         Species  \
0  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
1  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
2  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
3  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
4  PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae

                 Genus            Family  ...  \
0  Alphainfluenzavirus  Orthomyxoviridae  ...
1  Alphainfluenzavirus  Orthomyxoviridae  ...
2  Alphainfluenzavirus  Orthomyxoviridae  ...
3  Alphainfluenzavirus  Orthomyxoviridae  ...
4  Alphainfluenzavirus  Orthomyxoviridae  ...

                                        Organization Org_location  \
0  USDA Animal Plant Health Inspection Service-Na...          USA
1  USDA Animal Plant Health Inspection Service-Na...          USA
2  USDA Animal Plant Health Inspection Service-Na...          USA
3  USDA Animal Plant Health Inspection Service-Na...          USA
4  USDA Animal Plant Health Inspection Service-Na...          USA

   Publications Collection_Date  Release_Date Molecule_type size  \
0           NaN      2025-11-20    2026-01-16      ssRNA(-)    8
1           NaN      2025-11-20    2026-01-16      ssRNA(-)    8
2           NaN      2025-11-20    2026-01-16      ssRNA(-)    8
3           NaN      2025-11-20    2026-01-16      ssRNA(-)    8
4           NaN      2025-11-20    2026-01-16      ssRNA(-)    8

                                         full_header  \
0  >PX880763.1 |Influenza A virus (A/Peregrine Fa...
1  >PX880764.1 |Influenza A virus (A/Peregrine Fa...
2  >PX880765.1 |Influenza A virus (A/Peregrine Fa...
3  >PX880766.1 |Influenza A virus (A/Peregrine Fa...
4  >PX880767.1 |Influenza A virus (A/Peregrine Fa...

                                            sequence    Partial_Header_temp
0  ATGGATAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  25G04838_001_original
1  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...  25G04838_001_original
2  ATGGAAGATTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...  25G04838_001_original
3  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...  25G04838_001_original
4  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...  25G04838_001_original

[5 rows x 32 columns]
89344
32432

In [21]:
# Get genoflu results from Andersen and see if any fit

os.chdir(andersen)

genoflu_andersen = pd.read_csv("genoflu_results.tsv", delimiter="\t")
genoflu_andersen = genoflu_andersen.rename(columns={"sample":"SRA_Accession"}) # So we can merge with old
# genoflu_andersen["SRA_Accession"] = genoflu_andersen["Strain"] # So we can merge with new

# Find those genotyped by Andersen via merge
metadata_segments_known_andersen = metadata_segments_new.merge(genoflu_andersen, how="inner", on="SRA_Accession")
print(metadata_segments_known_andersen)
# Keep all known genotypes
metadata_segments_known = pd.merge(metadata_segments_old, metadata_segments_known_andersen, on="SRA_Accession", how="left") # Since we know both of these

print(metadata_segments_old)
print(metadata_segments_known_andersen)

       Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0     PX880763.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
1     PX880764.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
2     PX880765.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
3     PX880766.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
4     PX880767.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
...          ...            ...              ...           ...           ...
3859  PQ012131.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
3860  PQ012132.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
3861  PQ012133.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
3862  PQ012134.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
3863  PQ012135.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639

        BioProject      Organism_Name                         Species  \
0     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
1     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
2     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
3     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
4     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
...            ...                ...                             ...
3859  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3860  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3861  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3862  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3863  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                    Genus            Family  ... Date run     _merge  \
0     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
1     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
2     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
...                   ...               ...  ...      ...        ...
3859  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3860  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3861  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3862  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3863  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only

                     date       File Name  \
0     2025-12-20_14-36-11  SRR36538378.fa
1     2025-12-20_14-36-11  SRR36538378.fa
2     2025-12-20_14-36-11  SRR36538378.fa
3     2025-12-20_14-36-11  SRR36538378.fa
4     2025-12-20_14-36-11  SRR36538378.fa
...                   ...             ...
3859  2025-05-09_10-47-50  SRR29281472.fa
3860  2025-05-09_10-47-50  SRR29281472.fa
3861  2025-05-09_10-47-50  SRR29281472.fa
3862  2025-05-09_10-47-50  SRR29281472.fa
3863  2025-05-09_10-47-50  SRR29281472.fa

                                               Genotype  \
0     Not assigned: Only 7 segments >98.0% match fou...
1     Not assigned: Only 7 segments >98.0% match fou...
2     Not assigned: Only 7 segments >98.0% match fou...
3     Not assigned: Only 7 segments >98.0% match fou...
4     Not assigned: Only 7 segments >98.0% match fou...
...                                                 ...
3859                                              B3.13
3860                                              B3.13
3861                                              B3.13
3862                                              B3.13
3863                                              B3.13

                          Genotype List Used, >=98.0%_y  \
0     NS:ea3, HA:ea3, PB1:ea3, NA:am4N1, MP:ea3, NP:...
1     NS:ea3, HA:ea3, PB1:ea3, NA:am4N1, MP:ea3, NP:...
2     NS:ea3, HA:ea3, PB1:ea3, NA:am4N1, MP:ea3, NP:...
3     NS:ea3, HA:ea3, PB1:ea3, NA:am4N1, MP:ea3, NP:...
4     NS:ea3, HA:ea3, PB1:ea3, NA:am4N1, MP:ea3, NP:...
...                                                 ...
3859  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
3860  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
3861  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
3862  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
3863  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...

                           Genotype Sample Title List_y  \
0     ea3:22-013001-001:NS, am8:24-036222-001:PA, ea...
1     ea3:22-013001-001:NS, am8:24-036222-001:PA, ea...
2     ea3:22-013001-001:NS, am8:24-036222-001:PA, ea...
3     ea3:22-013001-001:NS, am8:24-036222-001:PA, ea...
4     ea3:22-013001-001:NS, am8:24-036222-001:PA, ea...
...                                                 ...
3859  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
3860  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
3861  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
3862  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
3863  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...

                          Genotype Percent Match List_y  \
0     99.05%, 97.58%, 99.41%, 99.30%, 98.67%, 99.69%...
1     99.05%, 97.58%, 99.41%, 99.30%, 98.67%, 99.69%...
2     99.05%, 97.58%, 99.41%, 99.30%, 98.67%, 99.69%...
3     99.05%, 97.58%, 99.41%, 99.30%, 98.67%, 99.69%...
4     99.05%, 97.58%, 99.41%, 99.30%, 98.67%, 99.69%...
...                                                 ...
3859  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...
3860  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...
3861  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...
3862  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...
3863  99.13%, 98.94%, 99.28%, 98.73%, 98.88%, 98.71%...

           Genotype Mismatch List_y Genotype Average Depth of Coverage List_y
0       8, 52, 10, 16, 15, 3, 8, 20         Ran on FASTA - No Coverage Report
1       8, 52, 10, 16, 15, 3, 8, 20         Ran on FASTA - No Coverage Report
2       8, 52, 10, 16, 15, 3, 8, 20         Ran on FASTA - No Coverage Report
3       8, 52, 10, 16, 15, 3, 8, 20         Ran on FASTA - No Coverage Report
4       8, 52, 10, 16, 15, 3, 8, 20         Ran on FASTA - No Coverage Report
...                             ...                                       ...
3859  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report
3860  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report
3861  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report
3862  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report
3863  13, 15, 6, 29, 11, 22, 22, 10         Ran on FASTA - No Coverage Report

[3864 rows x 49 columns]
        Accession GenBank_RefSeq         Assembly SRA_Accession BioSample  \
0      PX831491.1        GenBank  GCA_054448965.1           NaN       NaN
1      PX831492.1        GenBank  GCA_054448965.1           NaN       NaN
2      PX831493.1        GenBank  GCA_054448965.1           NaN       NaN
3      PX831494.1        GenBank  GCA_054448965.1           NaN       NaN
4      PX831495.1        GenBank  GCA_054448965.1           NaN       NaN
...           ...            ...              ...           ...       ...
89339  OK205667.1        GenBank  GCA_038971685.1           NaN       NaN
89340  OK205668.1        GenBank  GCA_038971685.1           NaN       NaN
89341  OK205669.1        GenBank  GCA_038971685.1           NaN       NaN
89342  OK205670.1        GenBank  GCA_038971685.1           NaN       NaN
89343  OK205671.1        GenBank  GCA_038971685.1           NaN       NaN

      BioProject      Organism_Name                         Species  \
0            NaN  Influenza A virus  Alphainfluenzavirus influenzae
1            NaN  Influenza A virus  Alphainfluenzavirus influenzae
2            NaN  Influenza A virus  Alphainfluenzavirus influenzae
3            NaN  Influenza A virus  Alphainfluenzavirus influenzae
4            NaN  Influenza A virus  Alphainfluenzavirus influenzae
...          ...                ...                             ...
89339        NaN  Influenza A virus  Alphainfluenzavirus influenzae
89340        NaN  Influenza A virus  Alphainfluenzavirus influenzae
89341        NaN  Influenza A virus  Alphainfluenzavirus influenzae
89342        NaN  Influenza A virus  Alphainfluenzavirus influenzae
89343        NaN  Influenza A virus  Alphainfluenzavirus influenzae

                     Genus            Family  ...  \
0      Alphainfluenzavirus  Orthomyxoviridae  ...
1      Alphainfluenzavirus  Orthomyxoviridae  ...
2      Alphainfluenzavirus  Orthomyxoviridae  ...
3      Alphainfluenzavirus  Orthomyxoviridae  ...
4      Alphainfluenzavirus  Orthomyxoviridae  ...
...                    ...               ...  ...
89339  Alphainfluenzavirus  Orthomyxoviridae  ...
89340  Alphainfluenzavirus  Orthomyxoviridae  ...
89341  Alphainfluenzavirus  Orthomyxoviridae  ...
89342  Alphainfluenzavirus  Orthomyxoviridae  ...
89343  Alphainfluenzavirus  Orthomyxoviridae  ...

                                                sequence Partial_Header_temp  \
0      AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...         063224_24_1
1      AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACCTTAC...         063224_24_1
2      AGCAAAAGCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAAT...         063224_24_1
3      AGCAAAAGCAGGGGTTCACTCTGTCAAAATGGAGAACATAGTACTA...         063224_24_1
4      AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...         063224_24_1
...                                                  ...                 ...
89339  ATGGAAAGAATAGCAATTGCCTTTGCATTAATCAGCATTGTCACAG...         LVVX17186_2
89340  GTAGATAATCACTCACTGAGTGACATTCACATCATGGCGTCTCAAG...         LVVX17186_2
89341  AATGAATCCAAATCAGAAAATAATAACAATAGGCTCCATTTCTCTA...         LVVX17186_2
89342  TAGATGTTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTT...         LVVX17186_2
89343  GTGACAAATACATAATGGACTCCAACACGATAACCTCGTTTCAGGT...         LVVX17186_2

                                                  Strain  \
0      Influenza_A_virus__USA__Texas_063224_24_1_H5N1...
1      Influenza_A_virus__USA__Texas_063224_24_1_H5N1...
2      Influenza_A_virus__USA__Texas_063224_24_1_H5N1...
3      Influenza_A_virus__USA__Texas_063224_24_1_H5N1...
4      Influenza_A_virus__USA__Texas_063224_24_1_H5N1...
...                                                  ...
89339  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
89340  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
89341  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
89342  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...
89343  Influenza_A_virus__Mexico__Jalisco_LVVX17186_2...

                                              Genotype_y  \
0                                                  B3.13
1                                                  B3.13
2                                                  B3.13
3                                                  B3.13
4                                                  B3.13
...                                                  ...
89339  Not assigned: Only 0 segments >98.0% match fou...
89340  Not assigned: Only 0 segments >98.0% match fou...
89341  Not assigned: Only 0 segments >98.0% match fou...
89342  Not assigned: Only 0 segments >98.0% match fou...
89343  Not assigned: Only 0 segments >98.0% match fou...

                             Genotype List Used, >=98.0%  \
0      PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
1      PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
2      PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3      PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
4      PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
...                                                  ...
89339                                                NaN
89340                                                NaN
89341                                                NaN
89342                                                NaN
89343                                                NaN

                              Genotype Sample Title List  \
0      am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
1      am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
2      am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3      am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
4      am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
...                                                  ...
89339  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
89340  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
89341  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
89342  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...
89343  am8:23-004320-002:PB2, am2:22-008760-007:PB1, ...

                             Genotype Percent Match List  \
0      98.86%, 99.56%, 99.16%, 98.77%, 99.40%, 99.15%...
1      98.86%, 99.56%, 99.16%, 98.77%, 99.40%, 99.15%...
2      98.86%, 99.56%, 99.16%, 98.77%, 99.40%, 99.15%...
3      98.86%, 99.56%, 99.16%, 98.77%, 99.40%, 99.15%...
4      98.86%, 99.56%, 99.16%, 98.77%, 99.40%, 99.15%...
...                                                  ...
89339  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
89340  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
89341  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
89342  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...
89343  92.28%, 95.03%, 87.92%, 77.42%, 89.66%, 85.31%...

                     Genotype Mismatch List  \
0              26, 10, 18, 21, 9, 12, 11, 6
1              26, 10, 18, 21, 9, 12, 11, 6
2              26, 10, 18, 21, 9, 12, 11, 6
3              26, 10, 18, 21, 9, 12, 11, 6
4              26, 10, 18, 21, 9, 12, 11, 6
...                                     ...
89339  176, 113, 256, 363, 151, 171, 82, 77
89340  176, 113, 256, 363, 151, 171, 82, 77
89341  176, 113, 256, 363, 151, 171, 82, 77
89342  176, 113, 256, 363, 151, 171, 82, 77
89343  176, 113, 256, 363, 151, 171, 82, 77

      Genotype Average Depth of Coverage List             Date run
0           Ran on FASTA - No Coverage Report  2026-01-12_12-08-38
1           Ran on FASTA - No Coverage Report  2026-01-12_12-08-38
2           Ran on FASTA - No Coverage Report  2026-01-12_12-08-38
3           Ran on FASTA - No Coverage Report  2026-01-12_12-08-38
4           Ran on FASTA - No Coverage Report  2026-01-12_12-08-38
...                                       ...                  ...
89339       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
89340       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
89341       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
89342       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44
89343       Ran on FASTA - No Coverage Report  2025-12-03_18-43-44

[89344 rows x 40 columns]
       Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0     PX880763.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
1     PX880764.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
2     PX880765.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
3     PX880766.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
4     PX880767.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
...          ...            ...              ...           ...           ...
3859  PQ012131.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
3860  PQ012132.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
3861  PQ012133.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
3862  PQ012134.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639
3863  PQ012135.1        GenBank  GCA_040780295.1   SRR29281472  SAMN41656639

        BioProject      Organism_Name                         Species  \
0     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
1     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
2     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
3     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
4     PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
...            ...                ...                             ...
3859  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3860  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3861  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3862  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3863  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                    Genus            Family  ... Date run     _merge  \
0     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
1     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
2     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
...                   ...               ...  ...      ...        ...
3859  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3860  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3861  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3862  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3863  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only

                     date       File Name  \
0     2025-12-20_14-36-11  SRR36538378.fa
1     2025-12-20_14-36-11  SRR36538378.fa
2     2025-12-20_14-36-11  SRR36538378.fa
3     2025-12-20_14-36-11  SRR36538378.fa
4     2025-12-20_14-36-11  SRR36538378.fa
...                   ...             ...
3859  2025-05-09_10-47-50  SRR29281472.fa
3860  2025-05-09_10-47-50  SRR29281472.fa
3861  2025-05-09_10-47-50  SRR29281472.fa
3862  2025-05-09_10-47-50  SRR29281472.fa
3863  2025-05-09_10-47-50  SRR29281472.fa

                                               Genotype  \
0     Not assigned: Only 7 segments >98.0% match fou...
1     Not assigned: Only 7 segments >98.0% match fou...
2     Not assigned: Only 7 segments >98.0% match fou...
3     Not assigned: Only 7 segments >98.0% match fou...
4     Not assigned: Only 7 segments >98.0% match fou...
...                                                 ...
3859                                              B3.13
3860                                              B3.13
3861                                              B3.13
3862                                              B3.13
3863                                              B3.13

                          Genotype List Used, >=98.0%_y  \
0     NS:ea3, HA:ea3, PB1:ea3, NA:am4N1, MP:ea3, NP:...
1     NS:ea3, HA:ea3, PB1:ea3, NA:am4N1, MP:ea3, NP:...
2     NS:ea3, HA:ea3, PB1:ea3, NA:am4N1, MP:ea3, NP:...
3     NS:ea3, HA:ea3, PB1:ea3, NA:am4N1, MP:ea3, NP:...
4     NS:ea3, HA:ea3, PB1:ea3, NA:am4N1, MP:ea3, NP:...
...                                                 ...
3859  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
3860  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
3861  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
3862  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...
3863  NP:am8, NA:ea1, NS:am1.1, PB2:am2.2, MP:ea1, H...

                           Genotype Sample Title List_y  \
0     ea3:22-013001-001:NS, am8:24-036222-001:PA, ea...
1     ea3:22-013001-001:NS, am8:24-036222-001:PA, ea...
2     ea3:22-013001-001:NS, am8:24-036222-001:PA, ea...
3     ea3:22-013001-001:NS, am8:24-036222-001:PA, ea...
4     ea3:22-013001-001:NS, am8:24-036222-001:PA, ea...
...                                                 ...
3859  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
3860  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
3861  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
3862  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...
3863  am8:23-032005-001:NP, ea1:22-003707-003:NA, am...


### Create FASTA files of unknown genotypes

In [19]:
metadata_segments_known

,Accession_x,GenBank_RefSeq_x,Assembly_x,SRA_Accession,BioSample_x,BioProject_x,Organism_Name_x,Species_x,Genus_x,Family_x,...,Date run_y,_merge,date,File Name,Genotype,"Genotype List Used, >=98.0%_y",Genotype Sample Title List_y,Genotype Percent Match List_y,Genotype Mismatch List_y,Genotype Average Depth of Coverage List_y
0,PX831491.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PX831492.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PX831493.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PX831494.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PX831495.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89339,OK205667.1,GenBank,GCA_038971685.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89340,OK205668.1,GenBank,GCA_038971685.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89341,OK205669.1,GenBank,GCA_038971685.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89342,OK205670.1,GenBank,GCA_038971685.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89343,OK205671.1,GenBank,GCA_038971685.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Create 8 fasta files per segment

# Get all the segments
metadata_segments_new["Partial_Header"] = metadata_segments_new["Assembly"].apply(lambda x: ">" + x if x == x else x) # .apply(lambda x: x.split("|")[-1].split(")")[0]) # Get only genbank name

print(metadata_segments_new["Partial_Header"].values[0:5])

# Create list of dataframes
df_list = []
for partial_header in list(set(metadata_segments_new["Partial_Header"].values)): # Unique partial headers only
    # Get smaller dataframe
    df = metadata_segments_new[metadata_segments_new["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    # Make sure there are 8 segments
    if len(df) == 8:
        # Forbidden characters in headers
        for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]:
            df["Partial_Header"] = df["Partial_Header"].apply(lambda x: x.replace(c, "_"))
            
        df["full_header"] = df["Partial_Header"]
        df_list.append(df)

print(metadata_segments_new["Partial_Header"])

print(df_list[0]["full_header"].values[:10])

# Make fasta files
for df in df_list:
    segments = list(set(df["Segment"].apply(lambda x: int(x)).values))
    for segment in segments:
        one_row = df[df["Segment"] == segment]
        df_to_fasta(one_row, str(segment) + "_seg.fasta", temp_files)

['>GCA_054514015.1' '>GCA_054514015.1' '>GCA_054514015.1'
 '>GCA_054514015.1' '>GCA_054514015.1']
0         >GCA_054514015.1
1         >GCA_054514015.1
2         >GCA_054514015.1
3         >GCA_054514015.1
4         >GCA_054514015.1
                ...
121771    >GCA_038165665.1
121772    >GCA_038165665.1
121773    >GCA_038165665.1
121774    >GCA_038165665.1
121775    >GCA_038165665.1
Name: Partial_Header, Length: 32432, dtype: object
['>GCA_051497195_1' '>GCA_051497195_1' '>GCA_051497195_1'
 '>GCA_051497195_1' '>GCA_051497195_1' '>GCA_051497195_1'
 '>GCA_051497195_1' '>GCA_051497195_1']

### Re-Labeling Using GenoFlu

**STOP HERE AND USE GENOFLU TO FIND NEW GENOTYPES.** Then, make sure "results.tsv" is in the downloads directory. <br>
To run GenoFLU-multi, first change directories to Multi-GenoFLU directory (and activate genoflu conda environment):
``` 
conda activate genoflu
cd GenoFLU-multi
```

And then call the python script:

``` 
python bin/genoflu-multi.py -f <FASTA_directory>
```

In [12]:
# Ensure that user does the above
input("Use genoflu. Afterwards, press ESCAPE to continue.")

''

In [13]:
# Merging

os.chdir(downloads_saved)

# Read in genoflu results
output_genoflu = pd.read_csv("results.tsv", delimiter="\t")

# Create partial headers to merge genoflu results with previously unknown segments
metadata_segments_new["Partial_Header_Merge"] = metadata_segments_new["Assembly"] # .apply(lambda x: ">" + x if x == x else x) # .apply(lambda x: x.replace(">", "")) # .apply(lambda x: x.split("|")[-1].split(")")[0]) # metadata_segments_new["Isolate"] #.apply(lambda x: x.split("|")[-1])
for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]: # Forbidden punctuation
    metadata_segments_new["Partial_Header_Merge"] = metadata_segments_new["Partial_Header_Merge"].apply(lambda x: x.replace(c, "_") if x==x else x)

# # Reformat so we can merge
# metadata_segments_new["Partial_Header_Merge"] = metadata_segments_new["Partial_Header_Merge"].apply(lambda x: x.replace(">", "")) # Removing header indicator
# metadata_segments_new["Partial_Header_Merge"] = metadata_segments_new["Partial_Header_Merge"].apply(lambda x: re.split(r'Influenza_A_virus__\D*_', x)[-1])
# metadata_segments_new["Partial_Header_Merge"] = metadata_segments_new["Partial_Header_Merge"].apply(lambda x: re.split(r'_(20|19).{2}_H.N.', x)[0])

# print(metadata_segments_new["Partial_Header_Merge"].values)

# Reformat so we can merge
output_genoflu["Partial_Header_Merge"] = output_genoflu["Strain"] #.apply(lambda x: re.split(r'Influenza_A_virus__\D*__\D*_', x)[-1])
# output_genoflu["Partial_Header_Merge"] = output_genoflu["Partial_Header_Merge"].apply(lambda x: re.split(r'_H.N._(20|19).{2}_.{2}_.{2}', x)[0])

# print(output_genoflu["Partial_Header_Merge"].values)
# metadata_segments_new["Strain"] = metadata_segments_new["Partial_Header"] # Renaming so we can merge

# Merge
metadata_genoflu = metadata_segments_new.merge(output_genoflu, how="inner", on="Partial_Header_Merge") #, suffixes=('_left', '_right')) 

# print(metadata_genoflu.dropna(subset="Genotype"))

# Fill the rest of the 8 segments with the same genotype
metadata_genoflu = metadata_genoflu.ffill(limit_area="inside")



print(metadata_genoflu)

        Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0      PX880763.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
1      PX880764.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
2      PX880765.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
3      PX880766.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
4      PX880767.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
...           ...            ...              ...           ...           ...
31291  OK205883.1        GenBank  GCA_038165665.1           NaN           NaN
31292  OK205884.1        GenBank  GCA_038165665.1           NaN           NaN
31293  OK205885.1        GenBank  GCA_038165665.1           NaN           NaN
31294  OK205886.1        GenBank  GCA_038165665.1           NaN           NaN
31295  OK205887.1        GenBank  GCA_038165665.1           NaN           NaN

         BioProject      Organism_Name                         Species  \
0      PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
1      PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
2      PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
3      PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
4      PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
...             ...                ...                             ...
31291           NaN  Influenza A virus  Alphainfluenzavirus influenzae
31292           NaN  Influenza A virus  Alphainfluenzavirus influenzae
31293           NaN  Influenza A virus  Alphainfluenzavirus influenzae
31294           NaN  Influenza A virus  Alphainfluenzavirus influenzae
31295           NaN  Influenza A virus  Alphainfluenzavirus influenzae

                     Genus            Family  ...    Partial_Header  \
0      Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_054514015.1
1      Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_054514015.1
2      Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_054514015.1
3      Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_054514015.1
4      Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_054514015.1
...                    ...               ...  ...               ...
31291  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_038165665.1
31292  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_038165665.1
31293  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_038165665.1
31294  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_038165665.1
31295  Alphainfluenzavirus  Orthomyxoviridae  ...  >GCA_038165665.1

      Partial_Header_Merge         Strain_y  \
0          GCA_054514015_1  GCA_054514015_1
1          GCA_054514015_1  GCA_054514015_1
2          GCA_054514015_1  GCA_054514015_1
3          GCA_054514015_1  GCA_054514015_1
4          GCA_054514015_1  GCA_054514015_1
...                    ...              ...
31291      GCA_038165665_1  GCA_038165665_1
31292      GCA_038165665_1  GCA_038165665_1
31293      GCA_038165665_1  GCA_038165665_1
31294      GCA_038165665_1  GCA_038165665_1
31295      GCA_038165665_1  GCA_038165665_1

                                                Genotype  \
0      Not assigned: Only 7 segments >98.0% match fou...
1      Not assigned: Only 7 segments >98.0% match fou...
2      Not assigned: Only 7 segments >98.0% match fou...
3      Not assigned: Only 7 segments >98.0% match fou...
4      Not assigned: Only 7 segments >98.0% match fou...
...                                                  ...
31291  Not assigned: Only 0 segments >98.0% match fou...
31292  Not assigned: Only 0 segments >98.0% match fou...
31293  Not assigned: Only 0 segments >98.0% match fou...
31294  Not assigned: Only 0 segments >98.0% match fou...
31295  Not assigned: Only 0 segments >98.0% match fou...

                           Genotype List Used, >=98.0%_y  \
0      PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...
1      PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...
2      PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...
3      PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...
4      PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...
...                                                  ...
31291                                                NaN
31292                                                NaN
31293                                                NaN
31294                                                NaN
31295                                                NaN

                            Genotype Sample Title List_y  \
0      am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...
1      am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...
2      am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...
3      am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...
4      am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...
...                                                  ...
31291  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...
31292  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...
31293  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...
31294  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...
31295  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...

                           Genotype Percent Match List_y  \
0      99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...
1      99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...
2      99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...
3      99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...
4      99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...
...                                                  ...
31291  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...
31292  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...
31293  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...
31294  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...
31295  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...

                  Genotype Mismatch List_y  \
0              20, 16, 52, 10, 8, 12, 3, 8
1              20, 16, 52, 10, 8, 12, 3, 8
2              20, 16, 52, 10, 8, 12, 3, 8
3              20, 16, 52, 10, 8, 12, 3, 8
4              20, 16, 52, 10, 8, 12, 3, 8
...                                    ...
31291  194, 103, 194, 319, 91, 134, 39, 40
31292  194, 103, 194, 319, 91, 134, 39, 40
31293  194, 103, 194, 319, 91, 134, 39, 40
31294  194, 103, 194, 319, 91, 134, 39, 40
31295  194, 103, 194, 319, 91, 134, 39, 40

      Genotype Average Depth of Coverage List_y           Date run_y
0             Ran on FASTA - No Coverage Report  2026-01-22_11-57-25
1             Ran on FASTA - No Coverage Report  2026-01-22_11-57-25
2             Ran on FASTA - No Coverage Report  2026-01-22_11-57-25
3             Ran on FASTA - No Coverage Report  2026-01-22_11-57-25
4             Ran on FASTA - No Coverage Report  2026-01-22_11-57-25
...                                         ...                  ...
31291         Ran on FASTA - No Coverage Report  2026-01-22_12-21-20
31292         Ran on FASTA - No Coverage Report  2026-01-22_12-21-20
31293         Ran on FASTA - No Coverage Report  2026-01-22_12-21-20
31294         Ran on FASTA - No Coverage Report  2026-01-22_12-21-20
31295         Ran on FASTA - No Coverage Report  2026-01-22_12-21-20

[31296 rows x 51 columns]

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\5\ipykernel_36384\1701310832.py:33: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  metadata_genoflu = metadata_genoflu.ffill(limit_area="inside")

### Concatenate with known genotypes

In [14]:
# Rename columns so we can concatenate
print(metadata_segments_known.columns)

metadata_segments_known = metadata_segments_known.reset_index(drop=True)
print(metadata_segments_known)

print(metadata_genoflu.columns)
metadata_segments_known["Genotype_official"] = metadata_segments_known["Genotype_y_y"]
metadata_segments_known["Serotype"] = metadata_segments_known["Genotype_x_x"]
metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype"]
metadata_genoflu["Serotype"] = metadata_genoflu["Genotype_x"]

metadata_genoflu = metadata_genoflu.reset_index(drop=True)
print(metadata_genoflu)

# Concatenation
metadata_genoflu_concat = pd.concat([metadata_segments_known, metadata_genoflu])

metadata_genoflu_concat

Index(['Accession_x', 'GenBank_RefSeq_x', 'Assembly_x', 'SRA_Accession',
       'BioSample_x', 'BioProject_x', 'Organism_Name_x', 'Species_x',
       'Genus_x', 'Family_x', 'Genotype_x_x', 'Isolate_x', 'Segment_x',
       'GenBank_Title_x', 'Length_x', 'Nuc_Completeness_x', 'Geo_Location_x',
       'Country_x', 'USA_x', 'Host_x', 'Tissue_Specimen_Source_x',
       'Submitters_x', 'Organization_x', 'Org_location_x', 'Publications_x',
       'Collection_Date_x', 'Release_Date_x', 'Molecule_type_x', 'size_x',
       'full_header_x', 'sequence_x', 'Partial_Header_temp_x', 'Strain_x',
       'Genotype_y_x', 'Genotype List Used, >=98.0%',
       'Genotype Sample Title List', 'Genotype Percent Match List',
       'Genotype Mismatch List', 'Genotype Average Depth of Coverage List',
       'Date run_x', 'Accession_y', 'GenBank_RefSeq_y', 'Assembly_y',
       'BioSample_y', 'BioProject_y', 'Organism_Name_y', 'Species_y',
       'Genus_y', 'Family_y', 'Genotype_x_y', 'Isolate_y', 'Segment_y',
       'GenBank_Title_y', 'Length_y', 'Nuc_Completeness_y', 'Geo_Location_y',
       'Country_y', 'USA_y', 'Host_y', 'Tissue_Specimen_Source_y',
       'Submitters_y', 'Organization_y', 'Org_location_y', 'Publications_y',
       'Collection_Date_y', 'Release_Date_y', 'Molecule_type_y', 'size_y',
       'full_header_y', 'sequence_y', 'Partial_Header_temp_y', 'Strain_y',
       'Genotype_y_y', 'Genotype List Used, >=98.0%_x',
       'Genotype Sample Title List_x', 'Genotype Percent Match List_x',
       'Genotype Mismatch List_x', 'Genotype Average Depth of Coverage List_x',
       'Date run_y', '_merge', 'date', 'File Name', 'Genotype',
       'Genotype List Used, >=98.0%_y', 'Genotype Sample Title List_y',
       'Genotype Percent Match List_y', 'Genotype Mismatch List_y',
       'Genotype Average Depth of Coverage List_y'],
      dtype='object')
      Accession_x GenBank_RefSeq_x       Assembly_x SRA_Accession BioSample_x  \
0      PX831491.1          GenBank  GCA_054448965.1           NaN         NaN
1      PX831492.1          GenBank  GCA_054448965.1           NaN         NaN
2      PX831493.1          GenBank  GCA_054448965.1           NaN         NaN
3      PX831494.1          GenBank  GCA_054448965.1           NaN         NaN
4      PX831495.1          GenBank  GCA_054448965.1           NaN         NaN
...           ...              ...              ...           ...         ...
89339  OK205667.1          GenBank  GCA_038971685.1           NaN         NaN
89340  OK205668.1          GenBank  GCA_038971685.1           NaN         NaN
89341  OK205669.1          GenBank  GCA_038971685.1           NaN         NaN
89342  OK205670.1          GenBank  GCA_038971685.1           NaN         NaN
89343  OK205671.1          GenBank  GCA_038971685.1           NaN         NaN

      BioProject_x    Organism_Name_x                       Species_x  \
0              NaN  Influenza A virus  Alphainfluenzavirus influenzae
1              NaN  Influenza A virus  Alphainfluenzavirus influenzae
2              NaN  Influenza A virus  Alphainfluenzavirus influenzae
3              NaN  Influenza A virus  Alphainfluenzavirus influenzae
4              NaN  Influenza A virus  Alphainfluenzavirus influenzae
...            ...                ...                             ...
89339          NaN  Influenza A virus  Alphainfluenzavirus influenzae
89340          NaN  Influenza A virus  Alphainfluenzavirus influenzae
89341          NaN  Influenza A virus  Alphainfluenzavirus influenzae
89342          NaN  Influenza A virus  Alphainfluenzavirus influenzae
89343          NaN  Influenza A virus  Alphainfluenzavirus influenzae

                   Genus_x          Family_x  ... Date run_y _merge  date  \
0      Alphainfluenzavirus  Orthomyxoviridae  ...        NaN    NaN   NaN
1      Alphainfluenzavirus  Orthomyxoviridae  ...        NaN    NaN   NaN
2      Alphainfluenzavirus  Orthomyxoviridae  ...        NaN    NaN   NaN
3      Alphainfluenzavirus  Orthomyxoviridae  ...        NaN    NaN   NaN
4      Alphainfluenzavirus  Orthomyxoviridae  ...        NaN    NaN   NaN
...                    ...               ...  ...        ...    ...   ...
89339  Alphainfluenzavirus  Orthomyxoviridae  ...        NaN    NaN   NaN
89340  Alphainfluenzavirus  Orthomyxoviridae  ...        NaN    NaN   NaN
89341  Alphainfluenzavirus  Orthomyxoviridae  ...        NaN    NaN   NaN
89342  Alphainfluenzavirus  Orthomyxoviridae  ...        NaN    NaN   NaN
89343  Alphainfluenzavirus  Orthomyxoviridae  ...        NaN    NaN   NaN

      File Name  Genotype Genotype List Used, >=98.0%_y  \
0           NaN       NaN                           NaN
1           NaN       NaN                           NaN
2           NaN       NaN                           NaN
3           NaN       NaN                           NaN
4           NaN       NaN                           NaN
...         ...       ...                           ...
89339       NaN       NaN                           NaN
89340       NaN       NaN                           NaN
89341       NaN       NaN                           NaN
89342       NaN       NaN                           NaN
89343       NaN       NaN                           NaN

      Genotype Sample Title List_y Genotype Percent Match List_y  \
0                              NaN                           NaN
1                              NaN                           NaN
2                              NaN                           NaN
3                              NaN                           NaN
4                              NaN                           NaN
...                            ...                           ...
89339                          NaN                           NaN
89340                          NaN                           NaN
89341                          NaN                           NaN
89342                          NaN                           NaN
89343                          NaN                           NaN

      Genotype Mismatch List_y Genotype Average Depth of Coverage List_y
0                          NaN                                       NaN
1                          NaN                                       NaN
2                          NaN                                       NaN
3                          NaN                                       NaN
4                          NaN                                       NaN
...                        ...                                       ...
89339                      NaN                                       NaN
89340                      NaN                                       NaN
89341                      NaN                                       NaN
89342                      NaN                                       NaN
89343                      NaN                                       NaN

[89344 rows x 88 columns]
Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Partial_Header_temp', 'Strain_x',
       'Genotype_y', 'Genotype List Used, >=98.0%_x',
       'Genotype Sample Title List_x', 'Genotype Percent Match List_x',
       'Genotype Mismatch List_x', 'Genotype Average Depth of Coverage List_x',
       'Date run_x', '_merge', 'Partial_Header', 'Partial_Header_Merge',
       'Strain_y', 'Genotype', 'Genotype List Used, >=98.0%_y',
       'Genotype Sample Title List_y', 'Genotype Percent Match List_y',
       'Genotype Mismatch List_y', 'Genotype Average Depth of Coverage List_y',
       'Date run_y'],
      dtype='object')
        Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0      PX880763.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
1      PX880764.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
2      PX880765.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
3      PX880766.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
4      PX880767.1        GenBank  GCA_054514015.1   SRR36538378  SAMN54232216
...           ...            ...              ...           ...           ...
31291  OK205883.1        GenBank  GCA_038165665.1           NaN           NaN
31292  OK205884.1        GenBank  GCA_038165665.1           NaN           NaN
31293  OK205885.1        GenBank  GCA_038165665.1           NaN           NaN
31294  OK205886.1        GenBank  GCA_038165665.1           NaN           NaN
31295  OK205887.1        GenBank  GCA_038165665.1           NaN           NaN

         BioProject      Organism_Name                         Species  \
0      PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
1      PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
2      PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
3      PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
4      PRJNA1207547  Influenza A virus  Alphainfluenzavirus influenzae
...             ...                ...                             ...
31291           NaN  Influenza A virus  Alphainfluenzavirus influenzae
31292           NaN  Influenza A virus  Alphainfluenzavirus influenzae
31293           NaN  Influenza A virus  Alphainfluenzavirus influenzae
31294           NaN  Influenza A virus  Alphainfluenzavirus influenzae
31295           NaN  Influenza A virus  Alphainfluenzavirus influenzae

                     Genus            Family  ...         Strain_y  \
0      Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_054514015_1
1      Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_054514015_1
2      Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_054514015_1
3      Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_054514015_1
4      Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_054514015_1
...                    ...               ...  ...              ...
31291  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_038165665_1
31292  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_038165665_1
31293  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_038165665_1
31294  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_038165665_1
31295  Alphainfluenzavirus  Orthomyxoviridae  ...  GCA_038165665_1

                                                Genotype  \
0      Not assigned: Only 7 segments >98.0% match fou...
1      Not assigned: Only 7 segments >98.0% match fou...
2      Not assigned: Only 7 segments >98.0% match fou...
3      Not assigned: Only 7 segments >98.0% match fou...
4      Not assigned: Only 7 segments >98.0% match fou...
...                                                  ...
31291  Not assigned: Only 0 segments >98.0% match fou...
31292  Not assigned: Only 0 segments >98.0% match fou...
31293  Not assigned: Only 0 segments >98.0% match fou...
31294  Not assigned: Only 0 segments >98.0% match fou...
31295  Not assigned: Only 0 segments >98.0% match fou...

                           Genotype List Used, >=98.0%_y  \
0      PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...
1      PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...
2      PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...
3      PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...
4      PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...
...                                                  ...
31291                                                NaN
31292                                                NaN
31293                                                NaN
31294                                                NaN
31295                                                NaN

                            Genotype Sample Title List_y  \
0      am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...
1      am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...
2      am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...
3      am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...
4      am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...
...                                                  ...
31291  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...
31292  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...
31293  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...
31294  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...
31295  am22:24-001196-005:PB2, am2:22-008760-007:PB1,...

                           Genotype Percent Match List_y  \
0      99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...
1      99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...
2      99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...
3      99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...
4      99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...
...                                                  ...
31291  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...
31292  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...
31293  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...
31294  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...
31295  91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...

                  Genotype Mismatch List_y  \
0              20, 16, 52, 10, 8, 12, 3, 8
1              20, 16, 52, 10, 8, 12, 3, 8
2              20, 16, 52, 10, 8, 12, 3, 8
3              20, 16, 52, 10, 8, 12, 3, 8
4              20, 16, 52, 10, 8, 12, 3, 8
...                                    ...
31291  194, 103, 194, 319, 91, 134, 39, 40
31292  194, 103, 194, 319, 91, 134, 39, 40
31293  194, 103, 194, 319, 91, 134, 39, 40
31294  194, 103, 194, 319, 91, 134, 39, 40
31295  194, 103, 194, 319, 91, 134, 39, 40

      Genotype Average Depth of Coverage List_y           Date run_y  \
0             Ran on FASTA - No Coverage Report  2026-01-22_11-57-25
1             Ran on FASTA - No Coverage Report  2026-01-22_11-57-25
2             Ran on FASTA - No Coverage Report  2026-01-22_11-57-25
3             Ran on FASTA - No Coverage Report  2026-01-22_11-57-25
4             Ran on FASTA - No Coverage Report  2026-01-22_11-57-25
...                                         ...                  ...
31291         Ran on FASTA - No Coverage Report  2026-01-22_12-21-20
31292         Ran on FASTA - No Coverage Report  2026-01-22_12-21-20
31293         Ran on FASTA - No Coverage Report  2026-01-22_12-21-20
31294         Ran on FASTA - No Coverage Report  2026-01-22_12-21-20
31295         Ran on FASTA - No Coverage Report  2026-01-22_12-21-20

                                       Genotype_official Serotype
0      Not assigned: Only 7 segments >98.0% match fou...     H5N1
1      Not assigned: Only 7 segments >98.0% match fou...     H5N1
2      Not assigned: Only 7 segments >98.0% match fou...     H5N1
3      Not assigned: Only 7 segments >98.0% match fou...     H5N1
4      Not assigned: Only 7 segments >98.0% match fou...     H5N1
...                                                  ...      ...
31291  Not assigned: Only 0 segments >98.0% match fou...     H5N2
31292  Not assigned: Only 0 segments >98.0% match fou...     H5N2
31293  Not assigned: Only 0 segments >98.0% match fou...     H5N2
31294  Not assigned: Only 0 segments >98.0% match fou...     H5N2
31295  Not assigned: Only 0 segments >98.0% match fou...     H5N2

[31296 rows x 53 columns]

,Accession_x,GenBank_RefSeq_x,Assembly_x,SRA_Accession,BioSample_x,BioProject_x,Organism_Name_x,Species_x,Genus_x,Family_x,...,Collection_Date,Release_Date,Molecule_type,size,full_header,sequence,Partial_Header_temp,Genotype_y,Partial_Header,Partial_Header_Merge
0,PX831491.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PX831492.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PX831493.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PX831494.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PX831495.1,GenBank,GCA_054448965.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1995,2021-11-01,ssRNA(-),8.0,>OK205883.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...,28159_398,NaN,>GCA_038165665.1,GCA_038165665_1
31292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1995,2021-11-01,ssRNA(-),8.0,>OK205884.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...,28159_398,NaN,>GCA_038165665.1,GCA_038165665_1
31293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1995,2021-11-01,ssRNA(-),8.0,>OK205885.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...,28159_398,NaN,>GCA_038165665.1,GCA_038165665_1
31294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1995,2021-11-01,ssRNA(-),8.0,>OK205886.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...,28159_398,NaN,>GCA_038165665.1,GCA_038165665_1
31295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1995,2021-11-01,ssRNA(-),8.0,>OK205887.1 |Influenza A virus (A/chicken/Vera...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...,28159_398,NaN,>GCA_038165665.1,GCA_038165665_1

In [15]:
metadata_genoflu.dropna(subset="Accession")

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Strain_y,Genotype,"Genotype List Used, >=98.0%_y",Genotype Sample Title List_y,Genotype Percent Match List_y,Genotype Mismatch List_y,Genotype Average Depth of Coverage List_y,Date run_y,Genotype_official,Serotype
0,PX880763.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,GCA_054514015_1,Not assigned: Only 7 segments >98.0% match fou...,"PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...","am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...","99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...","20, 16, 52, 10, 8, 12, 3, 8",Ran on FASTA - No Coverage Report,2026-01-22_11-57-25,Not assigned: Only 7 segments >98.0% match fou...,H5N1
1,PX880764.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,GCA_054514015_1,Not assigned: Only 7 segments >98.0% match fou...,"PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...","am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...","99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...","20, 16, 52, 10, 8, 12, 3, 8",Ran on FASTA - No Coverage Report,2026-01-22_11-57-25,Not assigned: Only 7 segments >98.0% match fou...,H5N1
2,PX880765.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,GCA_054514015_1,Not assigned: Only 7 segments >98.0% match fou...,"PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...","am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...","99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...","20, 16, 52, 10, 8, 12, 3, 8",Ran on FASTA - No Coverage Report,2026-01-22_11-57-25,Not assigned: Only 7 segments >98.0% match fou...,H5N1
3,PX880766.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,GCA_054514015_1,Not assigned: Only 7 segments >98.0% match fou...,"PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...","am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...","99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...","20, 16, 52, 10, 8, 12, 3, 8",Ran on FASTA - No Coverage Report,2026-01-22_11-57-25,Not assigned: Only 7 segments >98.0% match fou...,H5N1
4,PX880767.1,GenBank,GCA_054514015.1,SRR36538378,SAMN54232216,PRJNA1207547,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,GCA_054514015_1,Not assigned: Only 7 segments >98.0% match fou...,"PB2:am27, PB1:ea3, HA:ea3, NP:am13, NA:am4N1, ...","am27:24-037288-001:PB2, ea3:22-013001-001:PB1,...","99.12%, 99.30%, 97.58%, 99.41%, 99.47%, 99.15%...","20, 16, 52, 10, 8, 12, 3, 8",Ran on FASTA - No Coverage Report,2026-01-22_11-57-25,Not assigned: Only 7 segments >98.0% match fou...,H5N1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31291,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,GCA_038165665_1,Not assigned: Only 0 segments >98.0% match fou...,NaN,"am22:24-001196-005:PB2, am2:22-008760-007:PB1,...","91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...","194, 103, 194, 319, 91, 134, 39, 40",Ran on FASTA - No Coverage Report,2026-01-22_12-21-20,Not assigned: Only 0 segments >98.0% match fou...,H5N2
31292,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,GCA_038165665_1,Not assigned: Only 0 segments >98.0% match fou...,NaN,"am22:24-001196-005:PB2, am2:22-008760-007:PB1,...","91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...","194, 103, 194, 319, 91, 134, 39, 40",Ran on FASTA - No Coverage Report,2026-01-22_12-21-20,Not assigned: Only 0 segments >98.0% match fou...,H5N2
31293,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,GCA_038165665_1,Not assigned: Only 0 segments >98.0% match fou...,NaN,"am22:24-001196-005:PB2, am2:22-008760-007:PB1,...","91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...","194, 103, 194, 319, 91, 134, 39, 40",Ran on FASTA - No Coverage Report,2026-01-22_12-21-20,Not assigned: Only 0 segments >98.0% match fou...,H5N2
31294,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,GCA_038165665_1,Not assigned: Only 0 segments >98.0% match fou...,NaN,"am22:24-001196-005:PB2, am2:22-008760-007:PB1,...","91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...","194, 103, 194, 319, 91, 134, 39, 40",Ran on FASTA - No Coverage Report,2026-01-22_12-21-20,Not assigned: Only 0 segments >98.0% match fou...,H5N2
31295,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,GCA_038165665_1,Not assigned: Only 0 segments >98.0% match fou...,NaN,"am22:24-001196-005:PB2, am2:22-008760-007:PB1,...","91.49%, 95.47%, 90.89%, 79.86%, 93.92%, 88.50%...","194, 103, 194, 319, 91, 134, 39, 40",Ran on FASTA - No Coverage Report,2026-01-22_12-21-20,Not assigned: Only 0 segments >98.0% match fou...,H5N2

In [16]:
# Cut down to only columns we want
metadata_genoflu = metadata_genoflu[["Assembly", "GenBank_Title", "Host", "Collection_Date", "SRA_Accession", "Isolate", "Genotype_official", "Geo_Location", "full_header", "sequence", "Serotype", "Segment", "File Name", "Partial_Header"]] #, "Strain"]]

# Get genbank strain name
metadata_genoflu["genbank_name"] = metadata_genoflu["GenBank_Title"].apply(lambda x: x.split("(")[1] if x == x else x)
metadata_genoflu["Host"] = metadata_genoflu["genbank_name"].apply(lambda x: x.split("/")[1] if x == x else x)

metadata_genoflu = metadata_genoflu.dropna(subset="genbank_name") # [metadata_genoflu["Genotype"]  == "B3.13"]

KeyError: "['File Name'] not in index"

In [ ]:
metadata_genoflu

# for serotype in serotypes:
#     metadata_genoflu = metadata_genoflu[metadata_genoflu["Serotype"] == serotype]

,Assembly,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype_official,Geo_Location,full_header,sequence,Serotype,Segment,File Name,Partial_Header,genbank_name
0,GCA_054514015.1,Influenza A virus (A/Peregrine Falcon/CA/25G04...,Peregrine Falcon,2025-11-20,SRR36538378,25G04838-001-original,Not assigned: Only 7 segments >98.0% match fou...,USA: CA,>PX880763.1 |Influenza A virus (A/Peregrine Fa...,ATGGATAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...,H5N1,1.0,NaN,>GCA_054514015.1,A/Peregrine Falcon/CA/25G04838-001-original/2025
1,GCA_054514015.1,Influenza A virus (A/Peregrine Falcon/CA/25G04...,Peregrine Falcon,2025-11-20,SRR36538378,25G04838-001-original,Not assigned: Only 7 segments >98.0% match fou...,USA: CA,>PX880764.1 |Influenza A virus (A/Peregrine Fa...,ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...,H5N1,2.0,NaN,>GCA_054514015.1,A/Peregrine Falcon/CA/25G04838-001-original/2025
2,GCA_054514015.1,Influenza A virus (A/Peregrine Falcon/CA/25G04...,Peregrine Falcon,2025-11-20,SRR36538378,25G04838-001-original,Not assigned: Only 7 segments >98.0% match fou...,USA: CA,>PX880765.1 |Influenza A virus (A/Peregrine Fa...,ATGGAAGATTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...,H5N1,3.0,NaN,>GCA_054514015.1,A/Peregrine Falcon/CA/25G04838-001-original/2025
3,GCA_054514015.1,Influenza A virus (A/Peregrine Falcon/CA/25G04...,Peregrine Falcon,2025-11-20,SRR36538378,25G04838-001-original,Not assigned: Only 7 segments >98.0% match fou...,USA: CA,>PX880766.1 |Influenza A virus (A/Peregrine Fa...,ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...,H5N1,4.0,NaN,>GCA_054514015.1,A/Peregrine Falcon/CA/25G04838-001-original/2025
4,GCA_054514015.1,Influenza A virus (A/Peregrine Falcon/CA/25G04...,Peregrine Falcon,2025-11-20,SRR36538378,25G04838-001-original,Not assigned: Only 7 segments >98.0% match fou...,USA: CA,>PX880767.1 |Influenza A virus (A/Peregrine Fa...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...,H5N1,5.0,NaN,>GCA_054514015.1,A/Peregrine Falcon/CA/25G04838-001-original/2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30067,GCA_039321425.1,Influenza A virus (A/Falco_rusticolus/EdoMex/C...,Falco_rusticolus,2022-10,NaN,CPA-19638-22,B3.2,Mexico: EdoMex,>OP691324.1 |Influenza A virus (A/Falco_rustic...,GGTTCACTCTGTCAAAATGGAGAACATAGTACTACTTCTTGCAATA...,H5N1,4.0,NaN,>GCA_039321425.1,A/Falco_rusticolus/EdoMex/CPA-19638-22/2022
30068,GCA_039321425.1,Influenza A virus (A/Falco_rusticolus/EdoMex/C...,Falco_rusticolus,2022-10,NaN,CPA-19638-22,B3.2,Mexico: EdoMex,>OP691325.1 |Influenza A virus (A/Falco_rustic...,AAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCATGGCG...,H5N1,5.0,NaN,>GCA_039321425.1,A/Falco_rusticolus/EdoMex/CPA-19638-22/2022
30069,GCA_039321425.1,Influenza A virus (A/Falco_rusticolus/EdoMex/C...,Falco_rusticolus,2022-10,NaN,CPA-19638-22,B3.2,Mexico: EdoMex,>OP691326.1 |Influenza A virus (A/Falco_rustic...,AAAGCAGGAGTTCAAAATGAATCCAAATCAAAAGATAACAACCATT...,H5N1,6.0,NaN,>GCA_039321425.1,A/Falco_rusticolus/EdoMex/CPA-19638-22/2022
30070,GCA_039321425.1,Influenza A virus (A/Falco_rusticolus/EdoMex/C...,Falco_rusticolus,2022-10,NaN,CPA-19638-22,B3.2,Mexico: EdoMex,>OP691327.1 |Influenza A virus (A/Falco_rustic...,AAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTCGAA...,H5N1,7.0,NaN,>GCA_039321425.1,A/Falco_rusticolus/EdoMex/CPA-19638-22/2022
30071,GCA_039321425.1,Influenza A virus (A/Falco_rusticolus/EdoMex/C...,Falco_rusticolus,2022-10,NaN,CPA-19638-22,B3.2,Mexico: EdoMex,>OP691328.1 |Influenza A virus (A/Falco_rustic...,AGCAAAAGCAGGGTGACAAAAACATAATGGATTCCAACACTGTGTC...,H5N1,8.0,NaN,>GCA_039321425.1,A/Falco_rusticolus/EdoMex/CPA-19638-22/2022

## Relabeling Sequences

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

After running the below code, **STOP TO CHECK** if any new animals appear

In [ ]:
# Animals 

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genoflu)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['aves', 'neotropic cormorant', 'ring-billed gull', 'owl', 'fish crow', 'striped skunk', 'pluvialis dominica', 'mergus', 'environment', 'swine', 'dunlin', 'black swan', 'mottled duck', 'royal tern', 'gallus gallus domesticus', 'gannet', 'snowy owl', 'great egret', 'common loon', 'western grebe', 'turkey vulture', 'gallus gallus', 'nasua nasua', 'skunk', 'pelican', 'harbor seal', 'american green-winged teal', 'parasitic jaeger', 'ring-necked duck', 'eagle', 'eurasian collared dove', 'northern shoveler', 'serval', 'avian', 'horned grebe', 'barred owl', 'american wigeon', 'magpie', 'grackle', 'megascops choliba', 'eastern screech owl', 'willet', 'parrot', 'sandwich tern', 'osprey', 'western screech owl', 'antofagasta', 'baikal teal', 'pinniped', 'american wood stork', 'south american sea lion', 'canada goose', 'pelecanus thagus', 'lesser snow goose white-morph', 'pintail', 'vulpes vulpes', 'peafowl', 'sandhill crane', 'ring-necked pheasant', 'glaucous gull', 'green winged teal', 'black turnstone', 'bovine', 'broad-winged hawk', 'glaucous-winged gull', 'pelecanus', 'tundra swan', 'american crow', 'fisher', 'sparrow', 'south polar skua', 'sterna hirundo', 'pig', 'black bear', 'panthera leo', 'bufflehead', 'duck', 'trumpeter swan', 'cackling goose', 'common eider', 'great-tailed grackle', 'guineafowl', 'rosss goose', 'procellaria aequinoctialis', 'thalasseus acuflavidus', 'raptor', 'flamingo', 'brown pelican', 'crow', 'redhead', 'rosy-billed pochard', 'blue-winged teal', 'tiger', 'guinea fowl', 'great-horned owl', 'swainsons hawk', 'teal', 'western snowy plover', 'great blue heron', 'mute swan', 'greater scaup', 'poultry', 'manx shearwater', 'nannopterum brasilianus', 'goat', 'domestic turkey', 'western gull', 'raccoon', 'brant', 'barn owl', 'american blue-winged teal', 'alpaca', 'caspian tern', 'mallard', 'northern gannet', 'western sandpiper', 'lesser scaup', 'house sparrow', 'american-kestrel', 'bos taurus', 'wild bird', 'american pelican', 'short-billed gull', 'pekin duck', 'american woodcock', 'turkey', 'gallus', 'eider', 'lesser white-fronted goose', 'backyard chicken', 'wild duck', 'fregata magnificens', 'dairy cattle', 'chukar', 'common goldeneye', 'raw pet food', 'american kestrel', 'black skimmer', 'peruvian booby', 'house mouse', 'crane', 'black-legged kittiwake', 'numida meleagris', 'black swift', 'buteogallus urubitinga', 'southern elephant seal', 'black-crowned night-heron', 'red-breasted merganser', 'double-crested cormorant', 'wood duck', 'cormorant', 'eared grebe', 'mountain lion', 'northern harrier', 'american coot', 'red-shouldered hawk', 'cinnamon teal', 'raven', 'dairy cow', 'common raven', 'short-eared owl', 'swan', 'gull', 'peregrine falcon', 'burrowing owl', 'backyard duck', 'red-tailed hawk', 'american robin', 'northern pintail', 'guanay cormorant', 'black brant', 'common tern', 'lesser snow goose', 'emu', 'muscovy duck', 'black-crowned night heron', 'snowy plover', 'herring gull', 'sharp-shinned hawk', 'emperor goose', 'gadwall', 'quail', 'roseate spoonbill', 'green-winged teal', 'california condor', 'goose', 'red fox', 'sanderling', 'greater white-fronted goose', 'black scoter', 'thalasseus maximus', 'dolphin', 'feline', 'unknown', 'south american tern', 'polar bear', 'hooded merganser', 'lynx', 'white-winged dove', 'otaria flavescens', 'black vulture', 'south american fur seal', 'backyard turkey', 'cattle milk product', 'graylag goose', 'cat', 'red-necked phalarope', 'savannah cat', 'bobcat', 'hawk', 'washington', 'crested caracara', 'great black-backed gull', 'merganser', 'american black duck', 'redhead duck', 'black-necked swan', 'snowy egret', 'lesser snow goose blue-morph', 'white-winged scoter', 'great horned owl', 'vulture', 'cattle', 'red-necked grebe', 'seabird', 'dove', 'bald eagle', 'arctic tern', 'pet food', 'snow goose', 'green heron', 'blue-winged and cinnamon teal', 'silver pheasant', 'sula leucogaster', 'thayers gull', 'rock pigeon', 'rough-legged hawk', 'american white pelican', 'waterfowl', 'pheasant', 'wild turkey', 'backyard bird', 'chicken', 'heron', 'ostrich', 'pigeon']
[]
                       wild_avian domestic_avian               cattle  \
0                great_horned_owl       pheasant            dairy_cow
1                    common_raven         turkey               cattle
2                   cooper's_hawk        chicken  cattle milk product
3                    coopers_hawk          goose          bovine_milk
4                         peafowl    guinea_fowl              bovine
...                           ...            ...                  ...
1128  greater white fronted goose            NaN                  NaN
1129             barrow goldeneye            NaN                  NaN
1130                 cattle egret            NaN                  NaN
1131             wild duck hybrid            NaN                  NaN
1132                 pintail duck            NaN                  NaN

            feline   other_mammal       human         other      pet_food  new
0              cat     deer mouse  washington         mixed      pet food  NaN
1     domestic_cat    house_mouse      nevada   environment  raw pet food  NaN
2        feral_cat          skunk     wyoming  multispecies  raw_pet_food  NaN
3           feline  striped_skunk  california       unknown      pet_food  NaN
4     domestic-cat     norway rat    michigan             '           NaN  NaN
...            ...            ...         ...           ...           ...  ...
1128           NaN            NaN         NaN           NaN           NaN  NaN
1129           NaN            NaN         NaN           NaN           NaN  NaN
1130           NaN            NaN         NaN           NaN           NaN  NaN
1131           NaN            NaN         NaN           NaN           NaN  NaN
1132           NaN            NaN         NaN           NaN           NaN  NaN

[1133 rows x 9 columns]

In [ ]:
input("Check animals output. Afterwards, press ESCAPE to continue.")

In [ ]:
# Re-label sequences with no assigned genotype as "Unassigned"

metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype_official"].apply(lambda x: "Unassigned" if "Not assigned" in str(x) else x) # Unassigned segments are labeled "Unassigned"
metadata_genoflu["Genotype"] = metadata_genoflu["Genotype_official"] # Rename column again to not break old code

In [ ]:
metadata_genoflu

,Accession,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype_official,Geo_Location,full_header,sequence,Serotype,Segment,File Name,Partial_Header,Strain,genbank_name,Genotype
0,PV602142.1,Influenza A virus (A/American green-winged tea...,American green-winged teal,2024-10-17,NaN,IZ24_0776,D1.1,USA: Alaska,>Influenza A virus |USA: Alaska|IZ24_0776|H5N1...,GGTTCACTCTGTCAAAATGGAAAACATAGTACTTCTTCTTGCAATA...,H5N1,4,NaN,Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...,Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...,A/American green-winged teal/USA/IZ24_0776/2024,D1.1
1,PV602143.1,Influenza A virus (A/American green-winged tea...,American green-winged teal,2024-10-17,NaN,IZ24_0776,D1.1,USA: Alaska,>Influenza A virus |USA: Alaska|IZ24_0776|H5N1...,TAGATATTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTT...,H5N1,7,NaN,Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...,Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...,A/American green-winged teal/USA/IZ24_0776/2024,D1.1
2,PV602144.1,Influenza A virus (A/American green-winged tea...,American green-winged teal,2024-10-17,NaN,IZ24_0776,D1.1,USA: Alaska,>Influenza A virus |USA: Alaska|IZ24_0776|H5N1...,AAAGCAGGAGTTCAAAATGAATCCAAATCAAAAGATAATAACTATC...,H5N1,6,NaN,Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...,Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...,A/American green-winged teal/USA/IZ24_0776/2024,D1.1
3,PV602145.1,Influenza A virus (A/American green-winged tea...,American green-winged teal,2024-10-17,NaN,IZ24_0776,D1.1,USA: Alaska,>Influenza A virus |USA: Alaska|IZ24_0776|H5N1...,GTAGATAATCACTCACTGAGTGACATCCACATCATGGCGTCTCAAG...,H5N1,5,NaN,Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...,Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...,A/American green-winged teal/USA/IZ24_0776/2024,D1.1
4,PV602146.1,Influenza A virus (A/American green-winged tea...,American green-winged teal,2024-10-17,NaN,IZ24_0776,D1.1,USA: Alaska,>Influenza A virus |USA: Alaska|IZ24_0776|H5N1...,GTGACAAAAACATAATGGATTCCAACACTGTGTCAAGCTTTCAGGT...,H5N1,8,NaN,Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...,Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...,A/American green-winged teal/USA/IZ24_0776/2024,D1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67619,OK205883.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...,H5N2,4,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned
67620,OK205884.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...,H5N2,5,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned
67621,OK205885.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...,H5N2,6,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned
67622,OK205886.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...,H5N2,7,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned
67623,OK205887.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...,H5N2,8,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned

In [ ]:
# Re-Labeling

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

# Fix animals
fix_animals_andersen(metadata_genoflu, animals_ref)

# Get the years
metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

# Get geographic locations
metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location"].apply(lambda x: 
                                                                        # If "x" has the state abbreviation (e.g. "MD")
                                                                        states_ref.loc[states_ref["Abbreviation"].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0] 
                                                                        + "-" + 
                                                                        x.split(" ")[-1]
                                                                        if states_ref["Abbreviation"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has the full state name (e.g. "Maryland")
                                                                        else states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0]
                                                                        + "-" + 
                                                                        states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Abbreviation'].iloc[0] 
                                                                        if states_ref["State"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has neither the state abbreviation nor the full state name nor is "USA"
                                                                        else 
                                                                        x
                                                                        )

metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location_Abrv"].apply(lambda x: x.split("-")[0] if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] else x)


print(metadata_genoflu["Geo_Location_Abrv"])

0                 USA-AK
1                 USA-AK
2                 USA-AK
3                 USA-AK
4                 USA-AK
              ...
67619    Mexico-Veracruz
67620    Mexico-Veracruz
67621    Mexico-Veracruz
67622    Mexico-Veracruz
67623    Mexico-Veracruz
Name: Geo_Location_Abrv, Length: 67800, dtype: object

In [ ]:
# If there is no SRA Accession, replace identifier with Accession
metadata_genoflu['SRA_Accession'] = np.where(metadata_genoflu['SRA_Accession'] == "", metadata_genoflu['Assembly'].apply(lambda x: x.split(".")[0]), metadata_genoflu['SRA_Accession'])
# If there is no Assembly, replace identifier with Accession -- only for PB2
metadata_genoflu["Identifier"] = np.where(metadata_genoflu["SRA_Accession"] == "", metadata_genoflu["Accession"].apply(lambda x: x.split(".")[0] if x["Segment"] == 1 else np.nan), metadata_genoflu["SRA_Accession"])
# Fill in other nans with PB2 Accession (interpolate, maximum of 7 other sequences)
metadata_genoflu["Identifier"] = metadata_genoflu.ffill(metadata_genoflu["Identifier"], limit=7, limit_area="inside")

# Make new labels
names = ">" + metadata_genoflu["Identifier"].apply(lambda x: x.split(",")[0]) + "|" + metadata_genoflu["genbank_name"] + "|" + metadata_genoflu["Serotype"] + "|" + metadata_genoflu["Geo_Location_Abrv"] + "|" + metadata_genoflu["Collection_Date"] + "|" + metadata_genoflu["Host_Type"] + "|" + metadata_genoflu["Genotype"]

metadata_genoflu["Name"] = names


print(metadata_genoflu)

        Accession                                      GenBank_Title  \
0      PV602142.1  Influenza A virus (A/American green-winged tea...
1      PV602143.1  Influenza A virus (A/American green-winged tea...
2      PV602144.1  Influenza A virus (A/American green-winged tea...
3      PV602145.1  Influenza A virus (A/American green-winged tea...
4      PV602146.1  Influenza A virus (A/American green-winged tea...
...           ...                                                ...
67619  OK205883.1  Influenza A virus (A/chicken/Veracruz/28159-39...
67620  OK205884.1  Influenza A virus (A/chicken/Veracruz/28159-39...
67621  OK205885.1  Influenza A virus (A/chicken/Veracruz/28159-39...
67622  OK205886.1  Influenza A virus (A/chicken/Veracruz/28159-39...
67623  OK205887.1  Influenza A virus (A/chicken/Veracruz/28159-39...

                             Host Collection_Date SRA_Accession    Isolate  \
0      american green-winged teal      2024-10-17      PV602142  IZ24_0776
1      american green-winged teal      2024-10-17      PV602143  IZ24_0776
2      american green-winged teal      2024-10-17      PV602144  IZ24_0776
3      american green-winged teal      2024-10-17      PV602145  IZ24_0776
4      american green-winged teal      2024-10-17      PV602146  IZ24_0776
...                           ...             ...           ...        ...
67619                     chicken            1995      OK205883  28159-398
67620                     chicken            1995      OK205884  28159-398
67621                     chicken            1995      OK205885  28159-398
67622                     chicken            1995      OK205886  28159-398
67623                     chicken            1995      OK205887  28159-398

      Genotype_official      Geo_Location  \
0                  D1.1       USA: Alaska
1                  D1.1       USA: Alaska
2                  D1.1       USA: Alaska
3                  D1.1       USA: Alaska
4                  D1.1       USA: Alaska
...                 ...               ...
67619        Unassigned  Mexico: Veracruz
67620        Unassigned  Mexico: Veracruz
67621        Unassigned  Mexico: Veracruz
67622        Unassigned  Mexico: Veracruz
67623        Unassigned  Mexico: Veracruz

                                             full_header  \
0      >Influenza A virus |USA: Alaska|IZ24_0776|H5N1...
1      >Influenza A virus |USA: Alaska|IZ24_0776|H5N1...
2      >Influenza A virus |USA: Alaska|IZ24_0776|H5N1...
3      >Influenza A virus |USA: Alaska|IZ24_0776|H5N1...
4      >Influenza A virus |USA: Alaska|IZ24_0776|H5N1...
...                                                  ...
67619  >Influenza A virus |Mexico: Veracruz|28159-398...
67620  >Influenza A virus |Mexico: Veracruz|28159-398...
67621  >Influenza A virus |Mexico: Veracruz|28159-398...
67622  >Influenza A virus |Mexico: Veracruz|28159-398...
67623  >Influenza A virus |Mexico: Veracruz|28159-398...

                                                sequence  ... Segment  \
0      GGTTCACTCTGTCAAAATGGAAAACATAGTACTTCTTCTTGCAATA...  ...       4
1      TAGATATTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTT...  ...       7
2      AAAGCAGGAGTTCAAAATGAATCCAAATCAAAAGATAATAACTATC...  ...       6
3      GTAGATAATCACTCACTGAGTGACATCCACATCATGGCGTCTCAAG...  ...       5
4      GTGACAAAAACATAATGGATTCCAACACTGTGTCAAGCTTTCAGGT...  ...       8
...                                                  ...  ...     ...
67619  AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...  ...       4
67620  AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...  ...       5
67621  AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...  ...       6
67622  AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...  ...       7
67623  AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...  ...       8

       File Name                                     Partial_Header  \
0                 Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...
1                 Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...
2                 Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...
3                 Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...
4                 Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...
...          ...                                                ...
67619             Influenza_A_virus__Mexico__Veracruz_28159_398_...
67620             Influenza_A_virus__Mexico__Veracruz_28159_398_...
67621             Influenza_A_virus__Mexico__Veracruz_28159_398_...
67622             Influenza_A_virus__Mexico__Veracruz_28159_398_...
67623             Influenza_A_virus__Mexico__Veracruz_28159_398_...

                                                  Strain  \
0      Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...
1      Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...
2      Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...
3      Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...
4      Influenza_A_virus__USA__Alaska_IZ24_0776_H5N1_...
...                                                  ...
67619
67620
67621
67622
67623

                                          genbank_name    Genotype  \
0      A/American green-winged teal/USA/IZ24_0776/2024        D1.1
1      A/American green-winged teal/USA/IZ24_0776/2024        D1.1
2      A/American green-winged teal/USA/IZ24_0776/2024        D1.1
3      A/American green-winged teal/USA/IZ24_0776/2024        D1.1
4      A/American green-winged teal/USA/IZ24_0776/2024        D1.1
...                                                ...         ...
67619                A/chicken/Veracruz/28159-398/1995  Unassigned
67620                A/chicken/Veracruz/28159-398/1995  Unassigned
67621                A/chicken/Veracruz/28159-398/1995  Unassigned
67622                A/chicken/Veracruz/28159-398/1995  Unassigned
67623                A/chicken/Veracruz/28159-398/1995  Unassigned

            Host_Type Years Geo_Location_Abrv  \
0          wild_avian  2024            USA-AK
1          wild_avian  2024            USA-AK
2          wild_avian  2024            USA-AK
3          wild_avian  2024            USA-AK
4          wild_avian  2024            USA-AK
...               ...   ...               ...
67619  domestic_avian  1995   Mexico-Veracruz
67620  domestic_avian  1995   Mexico-Veracruz
67621  domestic_avian  1995   Mexico-Veracruz
67622  domestic_avian  1995   Mexico-Veracruz
67623  domestic_avian  1995   Mexico-Veracruz

                                                    Name
0      >PV602142|A/American green-winged teal/USA/IZ2...
1      >PV602143|A/American green-winged teal/USA/IZ2...
2      >PV602144|A/American green-winged teal/USA/IZ2...
3      >PV602145|A/American green-winged teal/USA/IZ2...
4      >PV602146|A/American green-winged teal/USA/IZ2...
...                                                  ...
67619  >OK205883|A/chicken/Veracruz/28159-398/1995|H5...
67620  >OK205884|A/chicken/Veracruz/28159-398/1995|H5...
67621  >OK205885|A/chicken/Veracruz/28159-398/1995|H5...
67622  >OK205886|A/chicken/Veracruz/28159-398/1995|H5...
67623  >OK205887|A/chicken/Veracruz/28159-398/1995|H5...

[67800 rows x 21 columns]

In [ ]:
os.chdir(complete_files)

# De-duplicate

print(len(metadata_genoflu))
metadata_genoflu = metadata_genoflu.drop_duplicates(subset=["Isolate", "genbank_name", "Segment"], keep="last")
print(len(metadata_genoflu))

# Save metadata
metadata_genoflu.to_csv("NCBI_Virus_" + date_range + "_metadata.csv") # Make file for metadata

67800
67696

## Rename segments and make complete FASTA files

In [ ]:
# Set up segments

if len(genotypes) > 3: # If we're not doing maintenance only
    genotypes.append("Unassigned") # Make sure unassigned genotypes are included
segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"} # Name segments 
metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].apply(lambda x: int(x)).map(segments)

# Separate into several dataframes based on genotype + segment
segment_genotype_dfs = []
for segment in segments.values():
    m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
    for genotype in list(set(m_g["Genotype"].values)):
        if genotype in genotypes:
            df = m_g[(m_g["Genotype"] == genotype)] 
            # df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
            segment_genotype_dfs.append(df)
            pair = genotype + "_" + segment
            print(pair)

Minor104_PB2
Minor14_PB2
B1.1_PB2
Minor04_PB2
B3.7_PB2
A2_PB2
B5.1_PB2
Minor11_PB2
Minor08_PB2
Minor01_PB2
Minor07_PB2
Minor34_PB2
Minor12_PB2
B1.2_PB2
Minor94_PB2
B4.1_PB2
B1.3_PB2
A6_PB2
A4_PB2
B2.2_PB2
Minor50_PB2
B2.1_PB2
C2.1_PB2
B3.5_PB2
A3_PB2
D1.1_PB2
A1_PB2
Unassigned_PB2
B3.6_PB2
B3.13_PB2
A5_PB2
B3.1_PB2
D1.3_PB2
D1.2_PB2
Minor105_PB2
Minor19_PB2
Minor13_PB2
B3.12_PB2
Minor28_PB2
Minor102_PB2
B3.2_PB2
Minor98_PB2
Minor45_PB2
B3.3_PB2
B3.4_PB2
Minor09_PB2
Minor104_PB1
Minor14_PB1
B1.1_PB1
Minor04_PB1
B3.7_PB1
A2_PB1
B5.1_PB1
Minor11_PB1
Minor08_PB1
Minor01_PB1
Minor07_PB1
Minor34_PB1
Minor12_PB1
B1.2_PB1
Minor94_PB1
B4.1_PB1
B1.3_PB1
A6_PB1
A4_PB1
B2.2_PB1
Minor50_PB1
B2.1_PB1
C2.1_PB1
B3.5_PB1
A3_PB1
D1.1_PB1
A1_PB1
Unassigned_PB1
B3.6_PB1
B3.13_PB1
A5_PB1
B3.1_PB1
D1.3_PB1
D1.2_PB1
Minor105_PB1
Minor19_PB1
Minor13_PB1
B3.12_PB1
Minor28_PB1
Minor102_PB1
B3.2_PB1
Minor98_PB1
Minor45_PB1
B3.3_PB1
B3.4_PB1
Minor09_PB1
Minor104_PA
Minor14_PA
B1.1_PA
Minor04_PA
B3.7_PA
A2_PA
B5.1_PA
Minor11_PA
Minor08_PA
Minor01_PA
Minor07_PA
Minor34_PA
Minor12_PA
B1.2_PA
Minor94_PA
B4.1_PA
B1.3_PA
A6_PA
A4_PA
B2.2_PA
Minor50_PA
B2.1_PA
C2.1_PA
B3.5_PA
A3_PA
D1.1_PA
A1_PA
Unassigned_PA
B3.6_PA
B3.13_PA
A5_PA
B3.1_PA
D1.3_PA
D1.2_PA
Minor105_PA
Minor19_PA
Minor13_PA
B3.12_PA
Minor28_PA
Minor102_PA
B3.2_PA
Minor98_PA
Minor45_PA
B3.3_PA
B3.4_PA
Minor09_PA
Minor104_HA
Minor14_HA
B1.1_HA
Minor04_HA
B3.7_HA
A2_HA
B5.1_HA
Minor11_HA
Minor08_HA
Minor01_HA
Minor07_HA
Minor34_HA
Minor12_HA
B1.2_HA
Minor94_HA
B4.1_HA
B1.3_HA
A6_HA
A4_HA
B2.2_HA
Minor50_HA
B2.1_HA
C2.1_HA
B3.5_HA
A3_HA
D1.1_HA
A1_HA
Unassigned_HA
B3.6_HA
B3.13_HA
A5_HA
B3.1_HA
D1.3_HA
D1.2_HA
Minor105_HA
Minor19_HA
Minor13_HA
B3.12_HA
Minor28_HA
Minor102_HA
B3.2_HA
Minor98_HA
Minor45_HA
B3.3_HA
B3.4_HA
Minor09_HA
Minor104_NP
Minor14_NP
B1.1_NP
Minor04_NP
B3.7_NP
A2_NP
B5.1_NP
Minor11_NP
Minor08_NP
Minor01_NP
Minor07_NP
Minor34_NP
Minor12_NP
B1.2_NP
Minor94_NP
B4.1_NP
B1.3_NP
A6_NP
A4_NP
B2.2_NP
Minor50_NP
B2.1_NP
C2.1_NP
B3.5_NP
A3_NP
D1.1_NP
A1_NP
Unassigned_NP
B3.6_NP
B3.13_NP
A5_NP
B3.1_NP
D1.3_NP
D1.2_NP
Minor105_NP
Minor19_NP
Minor13_NP
B3.12_NP
Minor28_NP
Minor102_NP
B3.2_NP
Minor98_NP
Minor45_NP
B3.3_NP
B3.4_NP
Minor09_NP
Minor104_NA
Minor14_NA
B1.1_NA
Minor04_NA
B3.7_NA
A2_NA
B5.1_NA
Minor11_NA
Minor08_NA
Minor01_NA
Minor07_NA
Minor34_NA
Minor12_NA
B1.2_NA
Minor94_NA
B4.1_NA
B1.3_NA
A6_NA
A4_NA
B2.2_NA
Minor50_NA
B2.1_NA
C2.1_NA
B3.5_NA
A3_NA
D1.1_NA
A1_NA
Unassigned_NA
B3.6_NA
B3.13_NA
A5_NA
B3.1_NA
D1.3_NA
D1.2_NA
Minor105_NA
Minor19_NA
Minor13_NA
B3.12_NA
Minor28_NA
Minor102_NA
B3.2_NA
Minor98_NA
Minor45_NA
B3.3_NA
B3.4_NA
Minor09_NA
Minor104_MP
Minor14_MP
B1.1_MP
Minor04_MP
B3.7_MP
A2_MP
B5.1_MP
Minor11_MP
Minor08_MP
Minor01_MP
Minor07_MP
Minor34_MP
Minor12_MP
B1.2_MP
Minor94_MP
B4.1_MP
B1.3_MP
A6_MP
A4_MP
B2.2_MP
Minor50_MP
B2.1_MP
C2.1_MP
B3.5_MP
A3_MP
D1.1_MP
A1_MP
Unassigned_MP
B3.6_MP
B3.13_MP
A5_MP
B3.1_MP
D1.3_MP
D1.2_MP
Minor105_MP
Minor19_MP
Minor13_MP
B3.12_MP
Minor28_MP
Minor102_MP
B3.2_MP
Minor98_MP
Minor45_MP
B3.3_MP
B3.4_MP
Minor09_MP
Minor104_NS
Minor14_NS
B1.1_NS
Minor04_NS
B3.7_NS
A2_NS
B5.1_NS
Minor11_NS
Minor08_NS
Minor01_NS
Minor07_NS
Minor34_NS
Minor12_NS
B1.2_NS
Minor94_NS
B4.1_NS
B1.3_NS
A6_NS
A4_NS
B2.2_NS
Minor50_NS
B2.1_NS
C2.1_NS
B3.5_NS
A3_NS
D1.1_NS
A1_NS
Unassigned_NS
B3.6_NS
B3.13_NS
A5_NS
B3.1_NS
D1.3_NS
D1.2_NS
Minor105_NS
Minor19_NS
Minor13_NS
B3.12_NS
Minor28_NS
Minor102_NS
B3.2_NS
Minor98_NS
Minor45_NS
B3.3_NS
B3.4_NS
Minor09_NS

In [ ]:
# Create FASTA files

os.chdir(complete_files)

for df in segment_genotype_dfs:
    print(df)
    
    df = df.reset_index()
    if len(df["Genotype"].values[0]) > 0: # If we have assigned genotypes, including "Unassigned"
        file_name = df["Genotype"].values[0] + "_" + df["Segment_Name"].values[0] + "_" + date_range + ".fasta"
        output_file = open(complete_files + file_name, "w")

        for index, row in df.iterrows():
            name = df.loc[index, "Name"]
            name = name.replace(" ", "_")
            # names.append(name)
            sequence = df.loc[index, "sequence"]
            # First is header, second is sequence
            output_file.write(name + "\n")
            output_file.write(sequence + "\n")
        
    output_file.close()

        Accession                                      GenBank_Title  \
12008  PV267613.1  Influenza A virus (A/snow goose/Arkansas/AR24-...

             Host Collection_Date SRA_Accession   Isolate Genotype_official  \
12008  snow goose      2024-12-06      PV267613  AR24-104          Minor104

        Geo_Location                                        full_header  \
12008  USA: Arkansas  >Influenza A virus |USA: Arkansas|AR24-104|H5N...

                                                sequence  ... File Name  \
12008  TCAAATATATTCAATATGGAGAGAATAAAAGAACTAAGAGATCTAA...  ...

                                          Partial_Header Strain  \
12008  Influenza_A_virus__USA__Arkansas_AR24_104_H5N1...

                              genbank_name  Genotype   Host_Type Years  \
12008  A/snow goose/Arkansas/AR24-104/2024  Minor104  wild_avian  2024

      Geo_Location_Abrv                                               Name  \
12008            USA-AR  >PV267613|A/snow goose/Arkansas/AR24-104/2024|...

      Segment_Name
12008          PB2

[1 rows x 22 columns]
        Accession                                      GenBank_Title  \
60416  OQ962769.1  Influenza A virus (A/Pheasant/New York/22-0087...

           Host Collection_Date SRA_Accession        Isolate  \
60416  pheasant      2022-03-22      OQ962769  22-008760-010

      Genotype_official   Geo_Location  \
60416           Minor14  USA: New York

                                             full_header  \
60416  >Influenza A virus |USA: New York|22-008760-01...

                                                sequence  ... File Name  \
60416  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...

                                          Partial_Header Strain  \
60416  Influenza_A_virus__USA__New_York_22_008760_010...

                                 genbank_name Genotype       Host_Type Years  \
60416  A/Pheasant/New York/22-008760-010/2022  Minor14  domestic_avian  2022

      Geo_Location_Abrv                                               Name  \
60416            USA-NH  >OQ962769|A/Pheasant/New York/22-008760-010/20...

      Segment_Name
60416          PB2

[1 rows x 22 columns]
        Accession                                      GenBank_Title  \
12128  PV212388.1  Influenza A virus (A/Duck/PA/22-037031-004-ori...
12136  PV212396.1  Influenza A virus (A/chicken/PA/22-037031-001-...
12144  PV212404.1  Influenza A virus (A/chicken/PA/22-024929-005-...
12152  PV212412.1  Influenza A virus (A/Duck/PA/22-037031-003-ori...
25264  PQ700374.1  Influenza A virus (A/Black Vulture/VA/22-02185...
...           ...                                                ...
64720  OQ967073.1  Influenza A virus (A/Wood Duck/New York/22-011...
64744  OQ967097.1  Influenza A virus (A/Wood Duck/Wisconsin/22-01...
64992  OQ967345.1  Influenza A virus (A/chicken/Iowa/22-009287-00...
66131  OP269959.1  Influenza A virus (A/Vulpes vulpes/USA/088592/...
66157  OP270007.1  Influenza A virus (A/Vulpes vulpes/USA/074441/...

                Host Collection_Date SRA_Accession  \
12128           duck      2022-11-15      PV212388
12136        chicken      2022-11-15      PV212396
12144        chicken      2022-08-10      PV212404
12152           duck      2022-11-15      PV212412
25264  black vulture      2022-06-30      PQ700374
...              ...             ...           ...
64720      wood duck      2022-04-11      OQ967073
64744      wood duck      2022-03-29      OQ967097
64992        chicken      2022-03-28      OQ967345
66131  vulpes vulpes      2022-04-25      OP269959
66157  vulpes vulpes      2022-04-11      OP270007

                             Isolate Genotype_official    Geo_Location  \
12128  22-037031-004-original-repeat              B1.1         USA: PA
12136  22-037031-001-original-repeat              B1.1         USA: PA
12144         22-024929-005-original              B1.1         USA: PA
12152  22-037031-003-original-repeat              B1.1         USA: PA
25264         22-021852-002-original              B1.1         USA: VA
...                              ...               ...             ...
64720                  22-011188-001              B1.1   USA: New York
64744                  22-011240-001              B1.1  USA: Wisconsin
64992                  22-009287-001              B1.1       USA: Iowa
66131                         088592              B1.1             USA
66157                         074441              B1.1             USA

                                             full_header  \
12128  >Influenza A virus |USA: PA|22-037031-004-orig...
12136  >Influenza A virus |USA: PA|22-037031-001-orig...
12144  >Influenza A virus |USA: PA|22-024929-005-orig...
12152  >Influenza A virus |USA: PA|22-037031-003-orig...
25264  >Influenza A virus |USA: VA|22-021852-002-orig...
...                                                  ...
64720  >Influenza A virus |USA: New York|22-011188-00...
64744  >Influenza A virus |USA: Wisconsin|22-011240-0...
64992  >Influenza A virus |USA: Iowa|22-009287-001|H5...
66131  >Influenza A virus |USA|088592|H5N1|2022-04-25...
66157  >Influenza A virus |USA|074441|H5N1|2022-04-11...

                                                sequence  ... File Name  \
12128  ATGGAGAGAATAAGAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
12136  ATGGAGAGAATAAGAGAACTAAGAGATCTAATGTCACATTCTCGCA...  ...
12144  ATGGAGAGAATAAGAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
12152  ATGGAGAGAATAAGAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
25264  ATGGAGAGAATAAGAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
...                                                  ...  ...       ...
64720  ATGGAGAGAATAAGAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
64744  ATGGAGAGAATAAGAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
64992  ATGGAGAGAATAAGAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
66131  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAGAGAAC...  ...
66157  AGCGAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAGAGAAC...  ...

                                          Partial_Header Strain  \
12128  Influenza_A_virus__USA__PA_22_037031_004_origi...
12136  Influenza_A_virus__USA__PA_22_037031_001_origi...
12144  Influenza_A_virus__USA__PA_22_024929_005_origi...
12152  Influenza_A_virus__USA__PA_22_037031_003_origi...
25264  Influenza_A_virus__USA__VA_22_021852_002_origi...
...                                                  ...    ...
64720  Influenza_A_virus__USA__New_York_22_011188_001...
64744  Influenza_A_virus__USA__Wisconsin_22_011240_00...
64992  Influenza_A_virus__USA__Iowa_22_009287_001_H5N...
66131  Influenza_A_virus__USA_088592_H5N1_2022_04_25_...
66157  Influenza_A_virus__USA_074441_H5N1_2022_04_11_...

                                          genbank_name Genotype  \
12128     A/Duck/PA/22-037031-004-original-repeat/2022     B1.1
12136  A/chicken/PA/22-037031-001-original-repeat/2022     B1.1
12144         A/chicken/PA/22-024929-005-original/2022     B1.1
12152     A/Duck/PA/22-037031-003-original-repeat/2022     B1.1
25264   A/Black Vulture/VA/22-021852-002-original/2022     B1.1
...                                                ...      ...
64720          A/Wood Duck/New York/22-011188-001/2022     B1.1
64744         A/Wood Duck/Wisconsin/22-011240-001/2022     B1.1
64992                A/chicken/Iowa/22-009287-001/2022     B1.1
66131                  A/Vulpes vulpes/USA/088592/2022     B1.1
66157                  A/Vulpes vulpes/USA/074441/2022     B1.1

            Host_Type Years Geo_Location_Abrv  \
12128  domestic_avian  2022            USA-PA
12136  domestic_avian  2022            USA-PA
12144  domestic_avian  2022            USA-PA
12152  domestic_avian  2022            USA-PA
25264      wild_avian  2022            USA-VA
...               ...   ...               ...
64720      wild_avian  2022            USA-NH
64744      wild_avian  2022            USA-WI
64992  domestic_avian  2022            USA-IA
66131    other_mammal  2022               USA
66157    other_mammal  2022               USA

                                                    Name Segment_Name
12128  >PV212388|A/Duck/PA/22-037031-004-original-rep...          PB2
12136  >PV212396|A/chicken/PA/22-037031-001-original-...          PB2
12144  >PV212404|A/chicken/PA/22-024929-005-original/...          PB2
12152  >PV212412|A/Duck/PA/22-037031-003-original-rep...          PB2
25264  >PQ700374|A/Black Vulture/VA/22-021852-002-ori...          PB2
...                                                  ...          ...
64720  >OQ967073|A/Wood Duck/New York/22-011188-001/2...          PB2
64744  >OQ967097|A/Wood Duck/Wisconsin/22-011240-001/...          PB2
64992  >OQ967345|A/chicken/Iowa/22-009287-001/2022|H5...          PB2
66131  >OP269959|A/Vulpes vulpes/USA/088592/2022|H5N1...          PB2
66157  >OP270007|A/Vulpes vulpes/USA/074441/2022|H5N1...          PB2

[525 rows x 22 columns]
        Accession                                      GenBank_Title    Host  \
63080  OQ965433.1  Influenza A virus (A/Turkey/Kansas/22-011119-0...  turkey
63088  OQ965441.1  Influenza A virus (A/Turkey/Kansas/22-011119-0...  turkey

      Collection_Date SRA_Accession        Isolate Genotype_official  \
63080      2022-04-09      OQ965433  22-011119-002           Minor04
63088      2022-04-09      OQ965441  22-011119-004           Minor04

      Geo_Location                                        full_header  \
63080  USA: Kansas  >Influenza A virus |USA: Kansas|22-011119-002|...
63088  USA: Kansas  >Influenza A virus |USA: Kansas|22-011119-004|...

                                                sequence  ... File Name  \
63080  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAATCTCGCA...  ...
63088  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAATCTCGCA...  ...

                                          Partial_Header Strain  \
63080  Influenza_A_virus__USA__Kansas_22_011119_002_H...
63088  Influenza_A_virus__USA__Kansas_22_011119_004_H...

                             genbank_name Genotype       Host_Type Years  \
63080  A/Turkey/Kansas/22-011119-002/2022  Minor04  domestic_avian  2022
63088  A/Turkey/Kansas/22-011119-004/2022  Minor04  domestic_avian  2022

      Geo_Location_Abrv                                               Name  \
63080            USA-KS  >OQ965433|A/Turkey/Kansas/22-011119-002/2022|H...
63088            USA-KS  >OQ965441|A/Turkey/Kansas/22-011119-004/2022|H...

      Segment_Name
63080          PB2
63088          PB2

[2 rows x 22 columns]
        Accession                                      GenBank_Title  \
10960  PV338481.1  Influenza A virus (A/cat/MT/24-006142-001-orig...
19056  PQ827602.1  Influenza A virus (A/Canada Goose/IN/24-005146...
19072  PQ827618.1  Influenza A virus (A/Canada Goose/MO/24-006385...
19096  PQ827650.1  Influenza A virus (A/Crow/IL/24-004479-001-ori...
19104  PQ827658.1  Influenza A virus (A/Crow/IL/24-004479-002-ori...
19424  PQ828066.1  Influenza A virus (A/Western Gull/CA/24-004708...
33600  PQ708710.1  Influenza A virus (A/Canada goose/OR/23-031491...
38056  PQ713166.1  Influenza A virus (A/Mallard/ID/23-028151-005-...
38064  PQ713174.1  Influenza A virus (A/Mallard/ID/23-028151-007-...
38072  PQ713182.1  Influenza A virus (A/Mallard/ID/23-028151-008-...
38080  PQ713190.1  Influenza A virus (A/Mallard/ID/23-028151-018-...
38088  PQ713198.1  Influenza A virus (A/Mallard/ID/23-028151-026-...
38096  PQ713206.1  Influenza A virus (A/Mallard/ID/23-029400-008-...
38104  PQ713214.1  Influenza A virus (A/Mallard/ID/23-029400-012-...
38112  PQ713222.1  Influenza A virus (A/Mallard/ID/23-029400-013-...
38120  PQ713230.1  Influenza A virus (A/Mallard/ID/23-029400-016-...
38128  PQ713238.1  Influenza A virus (A/Mallard/ID/23-029400-017-...
38136  PQ713246.1  Influenza A virus (A/Mallard/ID/23-029400-018-...
43576  PQ718686.1  Influenza A virus (A/Swan/TX/23-030412-001-ori...

               Host Collection_Date SRA_Accession  \
10960           cat      2023-12-05   SRR32654216
19056  canada goose      2024-02-14   SRR28834886
19072  canada goose      2024-02-22   SRR28834902
19096          crow      2024-02-08   SRR28834920
19104          crow      2024-02-08   SRR28834909
19424  western gull      2024-01-30   SRR28834951
33600  canada goose      2023-10-11      PQ708710
38056       mallard      2023-09-11      PQ713166
38064       mallard      2023-09-11      PQ713174
38072       mallard      2023-09-11      PQ713182
38080       mallard      2023-09-11      PQ713190
38088       mallard      2023-09-11      PQ713198
38096       mallard      2023-09-23      PQ713206
38104       mallard      2023-09-23      PQ713214
38112       mallard      2023-09-23      PQ713222
38120       mallard      2023-09-23      PQ713230
38128       mallard      2023-09-23      PQ713238
38136       mallard      2023-09-23      PQ713246
43576          swan      2023-10-06      PQ718686

                             Isolate Genotype_official Geo_Location  \
10960         24-006142-001-original              B3.7      USA: MT
19056         24-005146-001-original              B3.7      USA: IN
19072  24-006385-003-original-repeat              B3.7      USA: MO
19096         24-004479-001-original              B3.7      USA: IL
19104         24-004479-002-original              B3.7      USA: IL
19424         24-004708-001-original              B3.7      USA: CA
33600         23-031491-001-original              B3.7      USA: OR
38056         23-028151-005-original              B3.7      USA: ID
38064         23-028151-007-original              B3.7      USA: ID
38072         23-028151-008-original              B3.7      USA: ID
38080         23-028151-018-original              B3.7      USA: ID
38088         23-028151-026-original              B3.7      USA: ID
38096         23-029400-008-original              B3.7      USA: ID
38104  23-029400-012-original-repeat              B3.7      USA: ID
38112  23-029400-013-original-repeat              B3.7      USA: ID
38120         23-029400-016-original              B3.7      USA: ID
38128         23-029400-017-original              B3.7      USA: ID
38136  23-029400-018-original-repeat              B3.7      USA: ID
43576         23-030412-001-original              B3.7      USA: TX

                                             full_header  \
10960  >Influenza A virus |USA: MT|24-006142-001-orig...
19056  >Influenza A virus |USA: IN|24-005146-001-orig...
19072  >Influenza A virus |USA: MO|24-006385-003-orig...
19096  >Influenza A virus |USA: IL|24-004479-001-orig...
19104  >Influenza A virus |USA: IL|24-004479-002-orig...
19424  >Influenza A virus |USA: CA|24-004708-001-orig...
33600  >Influenza A virus |USA: OR|23-031491-001-orig...
38056  >Influenza A virus |USA: ID|23-028151-005-orig...
38064  >Influenza A virus |USA: ID|23-028151-007-orig...
38072  >Influenza A virus |USA: ID|23-028151-008-orig...
38080  >Influenza A virus |USA: ID|23-028151-018-orig...
38088  >Influenza A virus |USA: ID|23-028151-026-orig...
38096  >Influenza A virus |USA: ID|23-029400-008-orig...
38104  >Influenza A virus |USA: ID|23-029400-012-orig...
38112  >Influenza A virus |USA: ID|23-029400-013-orig...
38120  >Influenza A virus |USA: ID|23-029400-016-orig...
38128  >Influenza A virus |USA: ID|23-029400-017-orig...
38136  >Influenza A virus |USA: ID|23-029400-018-orig...
43576  >Influenza A virus |USA: TX|23-030412-001-orig...

                                                sequence  ... File Name  \
10960  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
19056  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
19072  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
19096  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
19104  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
19424  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
33600  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
38056  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
38064  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
38072  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
38080  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
38088  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
38096  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
38104  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
38112  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
38120  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
38128  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
38136  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
43576  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...

                                          Partial_Header Strain  \
10960  Influenza_A_virus__USA__MT_24_006142_001_origi...
19056  Influenza_A_virus__USA__IN_24_005146_001_origi...
19072  Influenza_A_virus__USA__MO_24_006385_003_origi...
19096  Influenza_A_virus__USA__IL_24_004479_001_origi...
19104  Influenza_A_virus__USA__IL_24_004479_002_origi...
19424  Influenza_A_virus__USA__CA_24_004708_001_origi...
33600  Influenza_A_virus__USA__OR_23_031491_001_origi...
38056  Influenza_A_virus__USA__ID_23_028151_005_origi...
38064  Influenza_A_virus__USA__ID_23_028151_007_origi...
38072  Influenza_A_virus__USA__ID_23_028151_008_origi...
38080  Influenza_A_virus__USA__ID_23_028151_018_origi...
38088  Influenza_A_virus__USA__ID_23_028151_026_origi...
38096  Influenza_A_virus__USA__ID_23_029400_008_origi...
38104  Influenza_A_virus__USA__ID_23_029400_012_origi...
38112  Influenza_A_virus__USA__ID_23_029400_013_origi...
38120  Influenza_A_virus__USA__ID_23_029400_016_origi...
38128  Influenza_A_virus__USA__ID_23_029400_017_origi...
38136  Influenza_A_virus__USA__ID_23_029400_018_origi...
43576  Influenza_A_virus__USA__TX_23_030412_001_origi...

                                            genbank_name Genotype   Host_Type  \
10960               A/cat/MT/24-006142-001-original/2023     B3.7      feline
19056      A/Canada Goose/IN/24-005146-001-original/2024     B3.7  wild_avian
19072  A/Canada Goose/MO/24-006385-003-original-repea...     B3.7  wild_avian
19096              A/Crow/IL/24-004479-001-original/2024     B3.7  wild_avian
19104              A/Crow/IL/24-004479-002-original/2024     B3.7  wild_avian
19424      A/Western Gull/CA/24-004708-001-original/2024     B3.7  wild_avian
33600      A/Canada goose/OR/23-031491-001-original/2023     B3.7  wild_avian
38056           A/Mallard/ID/23-028151-005-original/2023     B3.7  wild_avian
38064           A/Mallard/ID/23-028151-007-original/2023     B3.7  wild_avian
38072           A/Mallard/ID/23-028151-008-original/2023     B3.7  wild_avian
38080           A/Mallard/ID/23-028151-018-original/2023     B3.7  wild_avian
38088           A/Mallard/ID/23-028151-026-original/2023     B3.7  wild_avian
38096           A/Mallard/ID/23-029400-008-original/2023     B3.7  wild_avian
38104    A/Mallard/ID/23-029400-012-original-repeat/2023     B3.7  wild_avian
38112    A/Mallard/ID/23-029400-013-original-repeat/2023     B3.7  wild_avian
38120           A/Mallard/ID/23-029400-016-original/2023     B3.7  wild_avian
38128           A/Mallard/ID/23-029400-017-original/2023     B3.7  wild_avian
38136    A/Mallard/ID/23-029400-018-original-repeat/2023     B3.7  wild_avian
43576              A/Swan/TX/23-030412-001-original/2023     B3.7  wild_avian

      Years Geo_Location_Abrv  \
10960  2023            USA-MT
19056  2024            USA-IN
19072  2024            USA-MO
19096  2024            USA-IL
19104  2024            USA-IL
19424  2024            USA-CA
33600  2023            USA-OR
38056  2023            USA-ID
38064  2023            USA-ID
38072  2023            USA-ID
38080  2023            USA-ID
38088  2023            USA-ID
38096  2023            USA-ID
38104  2023            USA-ID
38112  2023            USA-ID
38120  2023            USA-ID
38128  2023            USA-ID
38136  2023            USA-ID
43576  2023            USA-TX

                                                    Name Segment_Name